	.align 2
voicegroup281:: @ drums 4 (misc)
	voice_directsound 60, 64, DirectSoundWaveData_bw_snareroll, 255, 0, 227, 2      			@ 127/127/120/124/ 64
	voice_directsound 61, 64, DirectSoundWaveData_bw_snareroll, 255, 0, 227, 2      			@ 127/127/120/124/ 64	+ 1
	voice_directsound 60, 64, DirectSoundWaveData_hg_032crash, 255, 246, 0, 214    				@ 127/ 90/  0/114/ 64	
	voice_directsound 60, 64, DirectSoundWaveData_bw_phatkick_e4, 255, 0, 255, 0    			@ 127/127/127/127/ 64	
	voice_directsound 60, 64, DirectSoundWaveData_bw_punchysnare_e4, 255, 0, 255, 0    			@ 127/127/127/127/ 64	
	voice_directsound 60, 64, DirectSoundWaveData_bw_808snarereverb, 255, 0, 227, 2    			@ 127/127/120/124/ 64	
	voice_directsound 51, 64, DirectSoundWaveData_dp_synthsnare, 255, 0, 255, 0    				@ 127/127/127/127/ 64	- 9
	voice_directsound 63, 64, DirectSoundWaveData_bw_synthkick_vsrival, 255, 0, 227, 205    	@ 127/127/120/116/ 64	+ 3
	voice_directsound 66, 64, DirectSoundWaveData_bw_synthkick_vsrival, 255, 0, 227, 205    	@ 127/127/120/116/ 64	+ 6
	voice_directsound 60, 30, DirectSoundWaveData_dp_ridecap, 255, 250, 0, 210					@ 127/ 70/  0/115/ 30
