	.align 2
voicegroup004:: @ 8676658
	voice_directsound_no_resample 66, 34, DirectSoundWaveData_sc88pro_tambourine, 255, 127, 77, 204  @ 8676658
	voice_directsound_no_resample 64, 14, DirectSoundWaveData_trinity_cymbal_crash, 255, 231, 0, 188  @ 8676664
	voice_directsound_no_resample 64, 89, DirectSoundWaveData_sd90_cowbell, 255, 0, 255, 242  @ 8676670
	voice_directsound_no_resample 64, 29, DirectSoundWaveData_sc88pro_orchestra_cymbal_crash, 255, 235, 0, 231  @ 867667C
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 8676688
	voice_directsound_no_resample 64, 54, DirectSoundWaveData_sc88pro_orchestra_cymbal_crash, 255, 235, 0, 231  @ 8676694
	voice_directsound_no_resample 64, 54, DirectSoundWaveData_sc88pro_orchestra_cymbal_crash, 8, 0, 255, 216  @ 86766A0
	voice_directsound_no_resample 64, 94, DirectSoundWaveData_unused_heart_of_asia_indian_drum, 255, 0, 255, 0  @ 86766AC
	voice_directsound_no_resample 64, 34, DirectSoundWaveData_sc88pro_mute_high_conga, 255, 0, 255, 0  @ 86766B8
	voice_directsound_no_resample 64, 34, DirectSoundWaveData_sc88pro_open_low_conga, 255, 0, 255, 0  @ 86766C4
	voice_directsound_no_resample 64, 90, DirectSoundWaveData_sc88pro_open_low_conga, 255, 0, 255, 0  @ 86766D0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 86766DC
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 86766E8
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 86766F4
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 8676700
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 867670C
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 8676718
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 8676724
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 8676730
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 867673C
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 8676748
	voice_directsound_no_resample 61, 84, DirectSoundWaveData_ethnic_flavours_hyoushigi, 255, 0, 255, 0  @ 8676754
	voice_directsound_no_resample 64, 64, DirectSoundWaveData_ethnic_flavours_ohtsuzumi, 255, 0, 255, 0  @ 8676760
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 867676C
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 8676778
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 8676784
	voice_directsound_no_resample 64, 39, DirectSoundWaveData_sd90_open_triangle, 255, 242, 103, 188  @ 8676790
	voice_directsound_no_resample 64, 79, DirectSoundWaveData_sd90_open_triangle, 255, 242, 103, 188  @ 867679C
	voice_directsound_no_resample 64, 39, DirectSoundWaveData_sd90_open_triangle, 255, 165, 103, 188  @ 86767A8
	voice_directsound_no_resample 64, 24, DirectSoundWaveData_sc88pro_jingle_bell, 255, 0, 255, 0  @ 86767B4
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 86767C0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 86767CC
	voice_directsound_no_resample 64, 104, DirectSoundWaveData_ethnic_flavours_atarigane, 255, 0, 255, 0  @ 86767D8
	voice_directsound 63, 64, DirectSoundWaveData_sc88pro_taiko, 255, 0, 255, 0  @ 86767E4
	voice_directsound 50, 84, DirectSoundWaveData_ethnic_flavours_kotsuzumi, 255, 0, 255, 0  @ 86767F0
	voice_directsound 64, 84, DirectSoundWaveData_ethnic_flavours_kotsuzumi, 255, 0, 255, 0  @ 86767FC
	voice_directsound 62, 64, DirectSoundWaveData_drum_and_percussion_kick, 255, 0, 255, 0  @ 8676808
	voice_directsound_no_resample 64, 64, DirectSoundWaveData_sd90_solo_snare, 255, 180, 175, 228  @ 8676814
	voice_directsound_no_resample 64, 64, DirectSoundWaveData_sd90_solo_snare, 255, 0, 255, 242  @ 8676820
	voice_directsound_no_resample 64, 54, DirectSoundWaveData_sc88pro_tr909_hand_clap, 255, 255, 255, 127  @ 867682C
	voice_directsound 65, 64, DirectSoundWaveData_sc88pro_orchestra_snare, 255, 0, 255, 242  @ 8676838
	voice_directsound 64, 24, DirectSoundWaveData_sd90_ambient_tom, 255, 0, 255, 226  @ 8676844
	voice_directsound_no_resample 64, 80, DirectSoundWaveData_sc88pro_orchestra_snare, 255, 0, 255, 242  @ 8676850
	voice_directsound 68, 34, DirectSoundWaveData_sd90_ambient_tom, 255, 0, 255, 226  @ 867685C
	voice_directsound_no_resample 60, 64, DirectSoundWaveData_sc88pro_rnd_snare, 255, 0, 255, 242  @ 8676868
	voice_directsound 72, 44, DirectSoundWaveData_sd90_ambient_tom, 255, 0, 255, 226  @ 8676874
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 8676880
	voice_directsound 76, 84, DirectSoundWaveData_sd90_ambient_tom, 255, 0, 255, 226  @ 867688C
	voice_directsound 80, 94, DirectSoundWaveData_sd90_ambient_tom, 255, 0, 255, 226  @ 8676898
	voice_directsound 56, 89, DirectSoundWaveData_sc88pro_orchestra_cymbal_crash, 255, 235, 0, 231  @ 86768A4
	voice_directsound 64, 104, DirectSoundWaveData_sc88pro_taiko, 255, 0, 255, 235  @ 86768B0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 86768BC
	voice_directsound 63, 64, DirectSoundWaveData_sc88pro_orchestra_cymbal_crash, 255, 235, 0, 231  @ 86768C8
	voice_directsound_no_resample 64, 24, DirectSoundWaveData_dance_drums_ride_bell, 255, 165, 103, 231  @ 86768D4
	voice_directsound_no_resample 66, 34, DirectSoundWaveData_sc88pro_tambourine, 255, 127, 77, 204  @ 86768E0
	voice_directsound 64, 14, DirectSoundWaveData_trinity_cymbal_crash, 255, 231, 0, 188  @ 86768EC
	voice_directsound 64, 89, DirectSoundWaveData_sd90_cowbell, 255, 0, 255, 242  @ 86768F8
	voice_directsound 60, 29, DirectSoundWaveData_sc88pro_orchestra_cymbal_crash, 255, 235, 0, 231  @ 8676904
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 8676910
	voice_directsound 58, 54, DirectSoundWaveData_sc88pro_orchestra_cymbal_crash, 255, 235, 0, 231  @ 867691C
	voice_directsound 62, 54, DirectSoundWaveData_sc88pro_orchestra_cymbal_crash, 8, 0, 255, 216  @ 8676928
	voice_directsound 64, 94, DirectSoundWaveData_unused_heart_of_asia_indian_drum, 255, 0, 255, 0  @ 8676934
	voice_directsound 64, 34, DirectSoundWaveData_sc88pro_mute_high_conga, 255, 0, 255, 0  @ 8676940
	voice_directsound 64, 34, DirectSoundWaveData_sc88pro_open_low_conga, 255, 0, 255, 0  @ 867694C
	voice_directsound 64, 90, DirectSoundWaveData_sc88pro_open_low_conga, 255, 0, 255, 0  @ 8676958
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 8676964
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 8676970
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 867697C
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 8676988
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 8676994
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 86769A0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 86769AC
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 86769B8
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 86769C4
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 86769D0
	voice_directsound 61, 84, DirectSoundWaveData_ethnic_flavours_hyoushigi, 255, 0, 255, 0  @ 86769DC
	voice_directsound 64, 64, DirectSoundWaveData_ethnic_flavours_ohtsuzumi, 255, 0, 255, 0  @ 86769E8
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 86769F4
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 8676A00
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 8676A0C
	voice_directsound 64, 39, DirectSoundWaveData_sd90_open_triangle, 255, 242, 103, 188  @ 8676A18
	voice_directsound 64, 79, DirectSoundWaveData_sd90_open_triangle, 255, 242, 103, 188  @ 8676A24
	voice_directsound 64, 39, DirectSoundWaveData_sd90_open_triangle, 255, 165, 103, 188  @ 8676A30
	voice_directsound_no_resample 64, 64, DirectSoundWaveData_sc88pro_jingle_bell, 255, 0, 255, 0  @ 8676A3C
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 8676A48
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 8676A54
	voice_directsound 64, 104, DirectSoundWaveData_ethnic_flavours_atarigane, 255, 0, 255, 0  @ 8676A60
	voice_directsound 63, 64, DirectSoundWaveData_sc88pro_taiko, 255, 0, 255, 0  @ 8676A6C
	voice_directsound 50, 84, DirectSoundWaveData_ethnic_flavours_kotsuzumi, 255, 0, 255, 0  @ 8676A78
	voice_directsound 64, 84, DirectSoundWaveData_ethnic_flavours_kotsuzumi, 255, 0, 255, 0  @ 8676A84

