	.align 2
voicegroup160:: @ 86AAABC
	voice_keysplit_all voicegroup001  @ 86AAABC
	voice_square_1 0, 2, 0, 0, 15, 0  @ 86AAAC8
	voice_square_1 0, 2, 0, 0, 15, 0  @ 86AAAD4
	voice_square_1 0, 2, 0, 0, 15, 0  @ 86AAAE0
	voice_square_1 0, 2, 0, 0, 15, 0  @ 86AAAEC
	voice_square_1 0, 2, 0, 0, 15, 0  @ 86AAAF8
	voice_square_1 0, 2, 0, 0, 15, 0  @ 86AAB04
	voice_square_1 0, 2, 0, 0, 15, 0  @ 86AAB10
	voice_square_1 0, 2, 0, 0, 15, 0  @ 86AAB1C
	voice_square_1 0, 2, 0, 0, 15, 0  @ 86AAB28
	voice_square_1 0, 2, 0, 0, 15, 0  @ 86AAB34
	voice_square_1 0, 2, 0, 0, 15, 0  @ 86AAB40
	voice_square_1 0, 2, 0, 0, 15, 0  @ 86AAB4C
	voice_square_1 0, 2, 0, 0, 15, 0  @ 86AAB58
	voice_directsound 60, 0, DirectSoundWaveData_sc88_tubular_bell, 255, 165, 90, 216  @ 86AAB64
	voice_square_1 0, 2, 0, 0, 15, 0  @ 86AAB70
	voice_square_1 0, 2, 0, 0, 15, 0  @ 86AAB7C
	voice_square_1 0, 2, 0, 0, 15, 0  @ 86AAB88
	voice_square_1 0, 2, 0, 0, 15, 0  @ 86AAB94
	voice_square_1 0, 2, 0, 0, 15, 0  @ 86AABA0
	voice_square_1 0, 2, 0, 0, 15, 0  @ 86AABAC
	voice_square_1 0, 2, 0, 0, 15, 0  @ 86AABB8
	voice_square_1 0, 2, 0, 0, 15, 0  @ 86AABC4
	voice_square_1 0, 2, 0, 0, 15, 0  @ 86AABD0
	voice_directsound 60, 0, DirectSoundWaveData_sc88_nylon_str_guitar, 128, 249, 25, 127  @ 86AABDC
	voice_square_1 0, 2, 0, 0, 15, 0  @ 86AABE8
	voice_square_1 0, 2, 0, 0, 15, 0  @ 86AABF4
	voice_square_1 0, 2, 0, 0, 15, 0  @ 86AAC00
	voice_square_1 0, 2, 0, 0, 15, 0  @ 86AAC0C
	voice_square_1 0, 2, 0, 0, 15, 0  @ 86AAC18
	voice_square_1 0, 2, 0, 0, 15, 0  @ 86AAC24
	voice_square_1 0, 2, 0, 0, 15, 0  @ 86AAC30
	voice_square_1 0, 2, 0, 0, 15, 0  @ 86AAC3C
	voice_square_1 0, 2, 0, 0, 15, 0  @ 86AAC48
	voice_square_1 0, 2, 0, 0, 15, 0  @ 86AAC54
	voice_directsound 60, 0, DirectSoundWaveData_sc88_fretless_bass, 255, 253, 0, 188  @ 86AAC60
	voice_square_1 0, 2, 0, 0, 15, 0  @ 86AAC6C
	voice_square_1 0, 2, 0, 0, 15, 0  @ 86AAC78
	voice_square_1 0, 2, 0, 0, 15, 0  @ 86AAC84
	voice_square_1 0, 2, 0, 0, 15, 0  @ 86AAC90
	voice_square_1 0, 2, 0, 0, 15, 0  @ 86AAC9C
	voice_square_1 0, 2, 0, 0, 15, 0  @ 86AACA8
	voice_square_1 0, 2, 0, 0, 15, 0  @ 86AACB4
	voice_square_1 0, 2, 0, 0, 15, 0  @ 86AACC0
	voice_square_1 0, 2, 0, 0, 15, 0  @ 86AACCC
	voice_square_1 0, 2, 0, 0, 15, 0  @ 86AACD8
	voice_square_1 0, 2, 0, 0, 15, 0  @ 86AACE4
	voice_square_1 0, 2, 0, 0, 15, 0  @ 86AACF0
	voice_keysplit voicegroup006, KeySplitTable2  @ 86AACFC
	voice_square_1 0, 2, 0, 0, 15, 0  @ 86AAD08
	voice_square_1 0, 2, 0, 0, 15, 0  @ 86AAD14
	voice_square_1 0, 2, 0, 0, 15, 0  @ 86AAD20
	voice_square_1 0, 2, 0, 0, 15, 0  @ 86AAD2C
	voice_square_1 0, 2, 0, 0, 15, 0  @ 86AAD38
	voice_square_1 0, 2, 0, 0, 15, 0  @ 86AAD44
	voice_square_1 0, 2, 0, 0, 15, 0  @ 86AAD50
	voice_square_1 0, 2, 0, 0, 15, 0  @ 86AAD5C
	voice_square_1 0, 2, 0, 0, 15, 0  @ 86AAD68
	voice_square_1 0, 2, 0, 0, 15, 0  @ 86AAD74
	voice_square_1 0, 2, 0, 0, 15, 0  @ 86AAD80
	voice_square_1 0, 2, 0, 0, 15, 0  @ 86AAD8C
	voice_square_1 0, 2, 0, 0, 15, 0  @ 86AAD98
	voice_square_1 0, 2, 0, 0, 15, 0  @ 86AADA4
	voice_square_1 0, 2, 0, 0, 15, 0  @ 86AADB0
	voice_square_1 0, 2, 0, 0, 15, 0  @ 86AADBC
	voice_square_1 0, 2, 0, 0, 15, 0  @ 86AADC8
	voice_square_1 0, 2, 0, 0, 15, 0  @ 86AADD4
	voice_square_1 0, 2, 0, 0, 15, 0  @ 86AADE0
	voice_square_1 0, 2, 0, 0, 15, 0  @ 86AADEC
	voice_square_1 0, 2, 0, 0, 15, 0  @ 86AADF8
	voice_square_1 0, 2, 0, 0, 15, 0  @ 86AAE04
	voice_square_1 0, 2, 0, 0, 15, 0  @ 86AAE10
	voice_square_1 0, 2, 0, 0, 15, 0  @ 86AAE1C
	voice_square_1 0, 2, 0, 0, 15, 0  @ 86AAE28
	voice_square_1 0, 2, 0, 0, 15, 0  @ 86AAE34
	voice_square_1 0, 2, 0, 0, 15, 0  @ 86AAE40
	voice_square_1 0, 2, 0, 0, 15, 0  @ 86AAE4C
	voice_square_1 0, 2, 0, 0, 15, 0  @ 86AAE58
	voice_square_1 0, 2, 0, 0, 15, 0  @ 86AAE64
	voice_square_1 0, 2, 0, 0, 15, 0  @ 86AAE70
	voice_square_1_alt 0, 1, 0, 2, 3, 1  @ 86AAE7C
	voice_square_2_alt 1, 0, 2, 4, 2  @ 86AAE88
	voice_square_1 0, 2, 0, 0, 15, 0  @ 86AAE94
	voice_square_1 0, 2, 0, 0, 15, 0  @ 86AAEA0
	voice_square_1 0, 2, 0, 0, 15, 0  @ 86AAEAC
	voice_square_1 0, 2, 0, 0, 15, 0  @ 86AAEB8
	voice_square_1 0, 2, 0, 0, 15, 0  @ 86AAEC4
	voice_programmable_wave_alt ProgrammableWaveData_86B4870, 0, 7, 15, 0  @ 86AAED0

