	.align 2
voicegroup130::
	voice_directsound 60, 0, DirectSoundWaveData_88DBBC0, 255, 0, 255, 0 
	voice_directsound 60, 0, DirectSoundWaveData_88DC220, 255, 0, 255, 0 
	voice_directsound 60, 0, DirectSoundWaveData_88DC704, 255, 0, 255, 0 
	voice_directsound 60, 0, DirectSoundWaveData_88DD054, 255, 0, 255, 0 
	voice_directsound 60, 0, DirectSoundWaveData_88DDAC4, 255, 0, 255, 0 
	voice_directsound 60, 0, DirectSoundWaveData_88DDDE4, 255, 0, 255, 0 
	voice_directsound 60, 0, DirectSoundWaveData_88DEA6C, 255, 0, 255, 0 
	voice_directsound 60, 0, DirectSoundWaveData_88DF08C, 255, 0, 255, 0 
	voice_directsound 60, 0, DirectSoundWaveData_88DF414, 255, 0, 255, 0 
	voice_directsound 60, 0, DirectSoundWaveData_88E01F8, 255, 0, 255, 0 
	voice_directsound 60, 0, DirectSoundWaveData_88E0B68, 255, 0, 255, 0 
	voice_directsound 60, 0, DirectSoundWaveData_88E0F04, 255, 0, 255, 0 
	voice_directsound 60, 0, DirectSoundWaveData_88E16B8, 255, 0, 255, 0 
	voice_directsound 60, 0, DirectSoundWaveData_88E2414, 255, 0, 255, 0 
	voice_directsound 60, 0, DirectSoundWaveData_88E2658, 255, 0, 255, 0 
	voice_directsound 60, 0, DirectSoundWaveData_88E3498, 255, 0, 255, 0 
	voice_directsound 60, 0, DirectSoundWaveData_88E3DEC, 255, 0, 255, 0 
	voice_directsound 60, 0, DirectSoundWaveData_88E4140, 255, 0, 255, 0 
	voice_directsound 60, 0, DirectSoundWaveData_88E4774, 255, 0, 255, 0 
	voice_directsound 60, 0, DirectSoundWaveData_88E53E0, 255, 0, 255, 0 
	voice_directsound 60, 0, DirectSoundWaveData_88E5978, 255, 0, 255, 0 
	voice_directsound 60, 0, DirectSoundWaveData_88E647C, 255, 0, 255, 0 
	voice_directsound 60, 0, DirectSoundWaveData_88E6A80, 255, 0, 255, 0 
	voice_directsound 60, 0, DirectSoundWaveData_88E6C78, 255, 0, 255, 0 
	voice_directsound 60, 0, DirectSoundWaveData_88E75DC, 255, 0, 255, 0 
	voice_directsound 60, 0, DirectSoundWaveData_88E8568, 255, 0, 255, 0 
	voice_directsound 60, 0, DirectSoundWaveData_88E8BA0, 255, 0, 255, 0 
	voice_directsound 60, 0, DirectSoundWaveData_88E9674, 255, 0, 255, 0 
	voice_directsound 60, 0, DirectSoundWaveData_88EA5B8, 255, 0, 255, 0 
	voice_directsound 60, 0, DirectSoundWaveData_88EAB30, 255, 0, 255, 0 
	voice_directsound 60, 0, DirectSoundWaveData_88EB97C, 255, 0, 255, 0 
	voice_directsound 60, 0, DirectSoundWaveData_88EC884, 255, 0, 255, 0 
	voice_directsound 60, 0, DirectSoundWaveData_88ED358, 255, 0, 255, 0 
	voice_directsound 60, 0, DirectSoundWaveData_88EDEEC, 255, 0, 255, 0 
	voice_directsound 60, 0, DirectSoundWaveData_88EE8C4, 255, 0, 255, 0 
	voice_directsound 60, 0, DirectSoundWaveData_88EEF04, 255, 0, 255, 0 
	voice_directsound 60, 0, DirectSoundWaveData_88EF9E4, 255, 0, 255, 0 
	voice_directsound 60, 0, DirectSoundWaveData_88F0020, 255, 0, 255, 0 
	voice_directsound 60, 0, DirectSoundWaveData_88F0738, 255, 0, 255, 0 
	voice_directsound 60, 0, DirectSoundWaveData_88F1074, 255, 0, 255, 0 
	voice_directsound 60, 0, DirectSoundWaveData_88F1830, 255, 0, 255, 0 
	voice_directsound 60, 0, DirectSoundWaveData_88F1D94, 255, 0, 255, 0 
	voice_directsound 60, 0, DirectSoundWaveData_88F2B08, 255, 0, 255, 0 
	voice_directsound 60, 0, DirectSoundWaveData_88F2F84, 255, 0, 255, 0 
	voice_directsound 60, 0, DirectSoundWaveData_88F3470, 255, 0, 255, 0 
	voice_directsound 60, 0, DirectSoundWaveData_88F3C38, 255, 0, 255, 0 
	voice_directsound 60, 0, DirectSoundWaveData_88F4834, 255, 0, 255, 0 
	voice_directsound 60, 0, DirectSoundWaveData_88F4BAC, 255, 0, 255, 0 
	voice_directsound 60, 0, DirectSoundWaveData_88F5368, 255, 0, 255, 0 
	voice_directsound 60, 0, DirectSoundWaveData_88F5FCC, 255, 0, 255, 0 
	voice_directsound 60, 0, DirectSoundWaveData_88F6498, 255, 0, 255, 0 
	voice_keysplit_all voicegroup001 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_accordion, 255, 249, 25, 248 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 
	voice_noise_alt 60, 0, 0, 0, 1, 7, 1 

