	.align 2
voicegroup202:: @ 
	voice_directsound 60, 0, DirectSoundWaveData_dp_xylphone_c2_16, 255, 249, 25, 196
	voice_directsound 60, 0, DirectSoundWaveData_dp_xylphone_c3_16, 255, 249, 25, 196
	voice_directsound 60, 0, DirectSoundWaveData_dp_xylphone_c4_16, 255, 249, 57, 196
	voice_directsound 60, 0, DirectSoundWaveData_dp_xylphone_c5_16, 255, 249, 57, 196
	voice_directsound 60, 0, DirectSoundWaveData_dp_xylphone_c6_16, 255, 247, 25, 196
