
SeafloorCavern_Room9_Text_ArchieHoldItRightThere:
	.string "ARTHUR: Ne bouge pas! Reste là!$"

SeafloorCavern_Room9_Text_ArchieSoItWasYou:
	.string "ARTHUR: Hummm…\n"
	.string "Alors c’était toi en fait.$"

SeafloorCavern_Room9_Text_ArchieBeholdKyogre:
	.string "ARTHUR: Regarde!\p"
	.string "Vois comme c’est beau, la silhouette\n"
	.string "endormie de l’ancien POKéMON KYOGRE!\p"
	.string "J’ai attendu ce jour si longtemps…$"

SeafloorCavern_Room9_Text_ArchieYouMustDisappear:
	.string "ARTHUR: Je suis surpris de voir que tu\n"
	.string "as réussi à me suivre jusqu’ici.\p"
	.string "Mais tout est fini désormais.\p"
	.string "Pour que je puisse réaliser mon rêve,\n"
	.string "il faut que tu disparaisses maintenant!$"

SeafloorCavern_Room9_Text_ArchieDefeat:
	.string "Quoi?!\p"
	.string "Tu m’as vraiment battu?!$"

SeafloorCavern_Room9_Text_ArchieWithThisRedOrb:
	.string "ARTHUR: Hummm…\p"
	.string "Je te félicite. Je dois reconnaître que\n"
	.string "tu as vraiment du talent.\p"
	.string "Mais!\n"
	.string "J’ai ceci en ma possession!\p"
	.string "Avec cet ORBE ROUGE, KYOGRE\n"
	.string "peut…$"

SeafloorCavern_Room9_Text_RedOrbShinesByItself:
	.string "L’ORBE ROUGE commence soudain\n"
	.string "à briller!$"

SeafloorCavern_Room9_Text_ArchieWhereDidKyogreGo:
	.string "ARTHUR: Quoi?!\p"
	.string "Je n’ai rien fait du tout.\n"
	.string "Pourquoi l’ORBE ROUGE…\p"
	.string "Où est passé KYOGRE?$"

SeafloorCavern_Room9_Text_ArchieAMessageFromOutside:
	.string "ARTHUR: Hum? C’est un message envoyé\n"
	.string "par nos membres qui sont à l’extérieur…$"

SeafloorCavern_Room9_Text_ArchieWhatRainingTooHard:
	.string "ARTHUR: Oui, qu’y a-t-il?\p"
	.string "Hum…\n"
	.string "Il pleut beaucoup?\p"
	.string "Bon… Ça devait arriver. C’est pour\n"
	.string "cela que nous avons réveillé KYOGRE,\l"
	.string "pour réaliser le désir de la TEAM AQUA\l"
	.string "d’étendre la mer.\p"
	.string "Quoi?!\p"
	.string "Il pleut bien plus que prévu?\n"
	.string "C’est dangereux?\p"
	.string "Ce n’est pas…\n"
	.string "C’est tout simplement impossible…\p"
	.string "Restez à vos postes et maîtrisez\n"
	.string "la situation!$"

SeafloorCavern_Room9_Text_ArchieWhyDidKyogreDisappear:
	.string "ARTHUR: Quelque chose est anormal…\p"
	.string "L’ORBE ROUGE est censé réveiller et\n"
	.string "contrôler KYOGRE…\p"
	.string "Mais… Pourquoi?\n"
	.string "Pourquoi KYOGRE a-t-il disparu?\p"
	.string "Pourquoi?!$"

SeafloorCavern_Room9_Text_MaxieWhatHaveYouWrought:
	.string "MAX: Qu’est-ce que t’as fabriqué?\p"
	.string "ARTHUR, tu as finalement réveillé\n"
	.string "KYOGRE, n’est-ce pas?\p"
	.string "Que va devenir le monde si cette\n"
	.string "forte pluie continue à tomber pour\l"
	.string "l’éternité?\p"
	.string "Toute la surface terrestre sera noyée\n"
	.string "dans les eaux profondes de la mer.$"

SeafloorCavern_Room9_Text_ArchieDontGetAllHighAndMighty:
	.string "ARTHUR: Qu’est-ce que tu dis?\n"
	.string "Ne prends pas ce ton avec moi!\p"
	.string "N’est-ce pas vous, la TEAM MAGMA,\n"
	.string "qui avez rendu GROUDON furieux?\p"
	.string "L’ORBE ROUGE devrait me permettre\n"
	.string "de contrôler KYOGRE…\p"
	.string "Je devais pouvoir le contrôler…$"

SeafloorCavern_Room9_Text_MaxieWeDontHaveTimeToArgue:
	.string "MAX: On n’a pas le temps de discuter\n"
	.string "de ça ici!\p"
	.string "Va dehors et vois par toi-même!\p"
	.string "Vois si ce que tu as fait correspond\n"
	.string "au monde de tes rêves!$"

SeafloorCavern_Room9_Text_MaxieComeOnPlayer:
	.string "MAX: {PLAYER}, viens, il faut\n"
	.string "aussi que tu partes d’ici!$"
