
Route101_Text_HelpMe:
	.string "A… A l’aide!$"

Route101_Text_PleaseHelp:
	.string "Hé! Toi, là-bas!\n"
	.string "Je t’en supplie! Aide-moi!\p"
	.string "Dans mon SAC!\n"
	.string "Il y a des POKé BALLS!$"

Route101_Text_DontLeaveMe:
	.string "Où… Où est-ce que tu vas?!\n"
	.string "Ne me laisse pas comme ça!$"

Route101_Text_YouSavedMe:
	.string "PROF. SEKO: Ouf…\p"
	.string "J’étudiais les POKéMON sauvages\n"
	.string "dans les hautes herbes, quand il m’a\l"
	.string "sauté dessus.\p"
	.string "Tu m’as sauvé.\n"
	.string "Merci beaucoup!\p"
	.string "Oh?\p"
	.string "Hé, c’est toi, {PLAYER}{KUN}!\p"
	.string "Ce n’est pas un endroit pour discuter.\n"
	.string "Allons au LABO POKéMON, OK?$"

Route101_Text_TakeTiredPokemonToPokeCenter:
	.string "Si tes POKéMON sont fatigués,\n"
	.string "emmène-les dans un CENTRE POKéMON.\p"
	.string "Il y a un CENTRE POKéMON à ROSYERES,\n"
	.string "tout près d’ici.$"

Route101_Text_WildPokemonInTallGrass:
	.string "Les POKéMON sauvages vont te sauter\n"
	.string "dessus dans les hautes herbes.\p"
	.string "Pour attraper des POKéMON,\n"
	.string "tu dois aller dans les hautes herbes\l"
	.string "et chercher.$"

Route101_Text_RouteSign:
	.string "ROUTE 101\n"
	.string "{UP_ARROW} ROSYERES$"
