DewfordTown_PokemonCenter_2F_MapScripts:: @ 81FC615
	map_script 2, DewfordTown_PokemonCenter_2F_MapScript2_276C3B
	map_script 4, DewfordTown_PokemonCenter_2F_MapScript2_276B6C
	map_script 1, DewfordTown_PokemonCenter_2F_MapScript1_276BBE
	map_script 3, DewfordTown_PokemonCenter_2F_MapScript1_276ACF
	.byte 0

DewfordTown_PokemonCenter_2F_EventScript_1FC62A:: @ 81FC62A
	call OldaleTown_PokemonCenter_2F_EventScript_276EB7
	end

DewfordTown_PokemonCenter_2F_EventScript_1FC630:: @ 81FC630
	call OldaleTown_PokemonCenter_2F_EventScript_2770B2
	end

DewfordTown_PokemonCenter_2F_EventScript_1FC636:: @ 81FC636
	call OldaleTown_PokemonCenter_2F_EventScript_2771DB
	end

