BerryBlender_Text_BlendWithTheBlendMaster:
	.string "LICUÓLOGO: ¡Que sí, que sí!\n"
	.string "¡Que yo soy el LICUÓLOGO! ¿Quién si no?\p"
	.string "¡Quédate conmigo y aprenderás\n"
	.string "a sacarle el jugo a las cosas!$"

BerryBlender_Text_SeeMyMasteryInAction:
	.string "LICUÓLOGO: ¡Mmmm! ¿Cómo?\n"
	.string "¿Quieres ver al LICUÓLOGO en acción?$"

BerryBlender_Text_TooBusyNowIsee:
	.string "¡Mmmm!\p"
	.string "Conque no tienes tiempo, ¿eh?\p"
	.string "¡No te preocupes!\n"
	.string "¡Estaré aquí todo el día!\l"
	.string "¡Acaba pronto lo que tengas que hacer!$"

BerryBlender_Text_BlendMasterNoBerries:
	.string "¡Mmmm!\p"
	.string "Conque no tienes BAYAS, ¿eh?\p"
	.string "¡Estaré aquí todo el día!\n"
	.string "¡Ve a buscar algunas BAYAS!$"

BerryBlender_Text_BlendMasterKnowHowToMakePokeblocks:
	.string "¡Por supuesto!\n"
	.string "¡Por supuesto!\p"
	.string "Por cierto…\n"
	.string "¿Sabes cómo crear {POKEBLOCK}S\l"
	.string "con BAYAS?$"

BerryBlender_Text_BlendMasterExplainBerryBlending:
	.string "Vale, pues entonces te explico.\p"
	.string "No te asustes, es facilísimo.\p"
	.string "Cuando la flecha de la LICUABAYAS\n"
	.string "llegue a tu marcador, pulsa el Botón A.\p"
	.string "Es lo único que hay que hacer.\p"
	.string "Cuando veas lo bien que pulso\n"
	.string "el Botón A, ya verás cómo aprendes…$"

BerryBlender_Text_BlendMasterLetsBerryBlender:
	.string "¡Bien!\p"
	.string "¡Comencemos, pues!\p"
	.string "¡Que eche humo esa LICUABAYAS!\n"
	.string "¡A licuar con el LICUÓLOGO!$"

BerryBlender_Text_BlendMasterNoPokeblockCase:
	.string "¡Mmm!\p"
	.string "¡Pero si no tienes ningún\n"
	.string "TUBO de {POKEBLOCK}S!\p"
	.string "¡Estaré aquí todo el día!\n"
	.string "¡Consigue un TUBO de {POKEBLOCK}S y vuelve!$"

BerryBlender_Text_BlendMasterPokeblockCaseFull:
	.string "¡Mmm!\p"
	.string "¡Pero si tu TUBO de {POKEBLOCK}S está lleno!\p"
	.string "¡Estaré aquí todo el día!\n"
	.string "¡Gasta unos {POKEBLOCK}S y vuelve luego!$"

BerryBlender_Text_WhoaAwesome:
	.string "¡Eh!\n"
	.string "¡Fenomenal!$"

BerryBlender_Text_WickedlyFast:
	.string "¡Espectacular!$"

BerryBlender_Text_WhatAnExpert:
	.string "¡Estoy francamente impresionado!$"

BerryBlender_Text_MadeAmazingPokeblocksWithMaster:
	.string "Me encanta licuar con el LICUÓLOGO,\n"
	.string "¡hacemos {POKEBLOCK}S alucinantes!$"

BerryBlender_Text_QualitiesOfBlendMaster:
	.string "Esa concentración…\n"
	.string "Esos ojos fijos en la flecha…\p"
	.string "Esa rapidez para pulsar el Botón A…\n"
	.string "Esa increíble precisión…\p"
	.string "Ese LICUÓLOGO es realmente único.$"

BerryBlender_Text_MasterWorksOnSkillsInMountains:
	.string "Dicen que el LICUÓLOGO se pasa la vida\n"
	.string "practicando su técnica en la montaña.\p"
	.string "Pero a veces se acerca a CALAGUA y\n"
	.string "se queda el día entero licuando BAYAS.$"
