LilycoveCity_ContestLobby_Text_ReceptionDontHavePokeblockCase:
	.string "¡Hola!\p"
	.string "¡Nos encargamos de organizar\n"
	.string "los CONCURSOS POKéMON!\p"
	.string "Vaya, parece que todavía no tienes\n"
	.string "TUBO para los {POKEBLOCK}S.\p"
	.string "¡En ese caso, habrá que darte esto!$"

LilycoveCity_ContestLobby_Text_NowThatWeveClearedThatUp:
	.string "Bueno, y ahora que ya hemos\n"
	.string "solucionado ese problemilla…\p"
	.string "¡Hola!\p"
	.string "¡Nos encargamos de organizar\n"
	.string "los CONCURSOS POKéMON!$"

LilycoveCity_ContestLobby_Text_ContestReception:
	.string "¡Hola!\p"
	.string "¡Nos encargamos de organizar\n"
	.string "los CONCURSOS POKéMON!$"

LilycoveCity_ContestLobby_Text_CounterOnlyFor4PlayerContests:
	.string "Hello!\p"
	.string "This reception counter is only\n"
	.string "for 4-player POKéMON CONTESTS.$"

LilycoveCity_ContestLobby_Text_EnterContest1:
	.string "Si quieres, podemos inscribir a tu\n"
	.string "POKéMON en un CONCURSO.$"

LilycoveCity_ContestLobby_Text_WhichTopic1:
	.string "¿Qué te gustaría saber?$"

LilycoveCity_ContestLobby_Text_ExplainContests:
	.string "En un CONCURSO POKéMON participan\n"
	.string "cuatro ENTRENADORES y cada uno\l"
	.string "de ellos presenta un POKéMON.\p"
	.string "Un CONCURSO consta de dos partes.\p"
	.string "La primera votación es un sondeo\n"
	.string "de popularidad en el que participa\l"
	.string "el público.\p"
	.string "En la segunda votación los POKéMON\n"
	.string "exhiben sus distintos movimientos.\p"
	.string "Planea con cuidado estas exhibiciones\n"
	.string "de forma que atraigas lo más posible\l"
	.string "la atención del JUEZ y entusiasmes\l"
	.string "al público. Debes sobresalir.\p"
	.string "Las dos puntuaciones obtenidas\n"
	.string "se combinan al final.\p"
	.string "El POKéMON que reúna más puntos\n"
	.string "será el ganador.$"

LilycoveCity_ContestLobby_Text_ExplainContestTypes:
	.string "Hay cinco tipos de CONCURSO.\p"
	.string "Las categorías son CARISMA, BELLEZA,\n"
	.string "DULZURA, INGENIO y DUREZA.\p"
	.string "Elige el CONCURSO que convenga más\n"
	.string "al POKéMON con el que vas a participar.$"

LilycoveCity_ContestLobby_Text_ExplainContestRanks:
	.string "Hay cuatro niveles en los CONCURSOS\n"
	.string "POKéMON.\p"
	.string "Son los niveles NORMAL, ALTO,\n"
	.string "AVANZADO y EXPERTO.\p"
	.string "En el nivel NORMAL puede participar\n"
	.string "cualquier POKéMON.\p"
	.string "Todo POKéMON que haya ganado en un\n"
	.string "CONCURSO del nivel NORMAL puede\l"
	.string "participar en el nivel ALTO de la misma\l"
	.string "categoría.\p"
	.string "Del mismo modo, si gana en el nivel ALTO,\n"
	.string "puede participar en el nivel AVANZADO y,\l"
	.string "si vuelve a ganar, llegar hasta el nivel\l"
	.string "EXPERTO de la misma categoría.\p"
	.string "Un POKéMON que haya ganado en el nivel\n"
	.string "EXPERTO puede competir en el mismo\l"
	.string "tantas veces como desee su\l"
	.string "ENTRENADOR.$"

LilycoveCity_ContestLobby_Text_EnterWhichRank:
	.string "¿En qué nivel quieres participar?$"

LilycoveCity_ContestLobby_Text_EnterWhichContest1:
	.string "¿En qué CONCURSO quieres entrar?$"

LilycoveCity_ContestLobby_Text_EnterWhichPokemon1:
	.string "¿Con qué POKéMON quieres participar?$"

LilycoveCity_ContestLobby_Text_MonNotQualifiedForRank:
	.string "Lo siento, pero tu POKéMON todavía\n"
	.string "no está cualificado para competir\l"
	.string "en este nivel…$"

LilycoveCity_ContestLobby_Text_EggCannotTakePart:
	.string "Lo siento, pero un HUEVO no puede\n"
	.string "participar en un CONCURSO POKéMON.$"

LilycoveCity_ContestLobby_Text_MonInNoConditionForContest:
	.string "Parece que tu POKéMON no está\n"
	.string "en condiciones de competir…$"

LilycoveCity_ContestLobby_Text_AlreadyWonEnterAnyway:
	.string "Anda, esa CINTA…\p"
	.string "Tu POKéMON ya ha ganado\n"
	.string "este CONCURSO, ¿verdad?\p"
	.string "¿Quieres participar igualmente?$"

LilycoveCity_ContestLobby_Text_ConfirmContestMon:
	.string "¿Éste es el POKéMON que va a competir?$"

LilycoveCity_ContestLobby_Text_YourMonIsEntryNum4:
	.string "Muy bien, hemos inscrito a tu POKéMON\n"
	.string "en este CONCURSO.\p"
	.string "Tu POKéMON tiene la entrada n.º 4.\n"
	.string "El CONCURSO empezará enseguida.$"

LilycoveCity_ContestLobby_Text_ComeThroughHere:
	.string "Pasa por aquí.\n"
	.string "¡Buena suerte!$"

LilycoveCity_ContestLobby_Text_PokemonWonWeHavePrize:
	.string "¡Felicidades!\n"
	.string "¡Tu POKéMON es el ganador del CONCURSO!\p"
	.string "Tenemos tu premio aquí.\n"
	.string "Sígueme, por favor…$"

LilycoveCity_ContestLobby_Text_ComeBackForPrizeLater:
	.string "Vuelve a recoger tu premio\n"
	.string "más adelante.$"

ContestHall_Text_GettingStartedParticipantsAsFollows:
	.string "PRESENTADORA: ¡Hola! ¡Estamos a punto\n"
	.string "de empezar un CONCURSO POKéMON\l"
	.string "de {STR_VAR_2} del nivel {STR_VAR_3}!\p"
	.string "Los ENTRENADORES y POKéMON\n"
	.string "participantes son los siguientes…$"

ContestHall_Text_GettingStartedParticipantsAsFollowsLink:
	.string "PRESENTADORA: ¡Hola! ¡Estamos a punto\n"
	.string "de empezar un CONCURSO POKéMON\l"
	.string "de {STR_VAR_2} para 4 jugadores\l"
	.string "conectados!\p"
	.string "Los ENTRENADORES y POKéMON\n"
	.string "participantes son los siguientes…$"

ContestHall_Text_EntryXTrainersMon:
	.string "PRESENTADORA: ¡Entrada n.º {STR_VAR_2}!\n"
	.string "¡{STR_VAR_3}, de {STR_VAR_1}!$"

ContestHall_Text_SeenContestantsAudienceWillVote:
	.string "PRESENTADORA: Acabamos de conocer\n"
	.string "a los cuatro POKéMON participantes.\p"
	.string "¡Es hora de realizar la primera\n"
	.string "votación!\p"
	.string "El público votará a su POKéMON\n"
	.string "favorito entre los participantes.\p"
	.string "¡Que empiece la votación!$"

ContestHall_Text_VotingUnderWay:
	.string "Se está realizando la votación…$"

ContestHall_Text_VotingCompleteLetsAppeal:
	.string "¡La votación ha concluido!\p"
	.string "Mientras se recuentan los votos,\n"
	.string "pasemos a la segunda votación.\p"
	.string "Se trata del muy esperado momento\n"
	.string "de las exhibiciones.\p"
	.string "Esperemos que los participantes nos\n"
	.string "impresionen exhibiendo sus mejores\l"
	.string "y más sorprendentes movimientos.\p"
	.string "¡Es hora de mostrar entusiasmo!\n"
	.string "¡Adelante con las exhibiciones!$"

ContestHall_Text_ThatsItForJudging:
	.string "PRESENTADORA: ¡Ha concluido\n"
	.string "la votación!$"

ContestHall_Text_ThankYouForAppeals:
	.string "¡Muchas gracias por ofrecernos\n"
	.string "esta magnífica exhibición!\p"
	.string "¡La votación ha finalizado!\n"
	.string "¡Os agradecemos el esfuerzo realizado!$"

ContestHall_Text_JudgeLooksReady:
	.string "Sólo queda proclamar al ganador\n"
	.string "de este emocionante evento.\p"
	.string "El JUEZ está a punto de anunciar\n"
	.string "al vencedor…$"

ContestHall_Text_WeWillNowDeclareWinner:
	.string "JUEZ: El ganador es…$"

ContestHall_Text_CongratsTrainerXandMon:
	.string "PRESENTADORA: ¡La entrada n.º {STR_VAR_2}!\p"
	.string "{STR_VAR_3} y {STR_VAR_1},\n"
	.string "¡muchas felicidades!$"

ContestHall_Text_CongratsPleaseCompeteAgain:
	.string "PRESENTADORA: ¡Felicidades!\n"
	.string "Esperamos que vuelvas a concursar.$"

ContestHall_Text_AcceptYourPrize:
	.string "PRESENTADORA: ¡Aquí está!\n"
	.string "Te rogamos que aceptes el premio.$"

ContestHall_Text_ConferRibbonAsPrize:
	.string "¡Te entregamos esta CINTA como\n"
	.string "premio a tu gran actuación!$"

ContestHall_Text_ReceivedRibbon:
	.string "{PLAYER} recibió una CINTA.$"

ContestHall_Text_PutRibbonOnMon:
	.string "{PLAYER} le puso la CINTA\n"
	.string "a {STR_VAR_1}.$"

ContestHall_Text_PickUpPrizeAtCounterLater:
	.string "Puedes recoger tu premio en el\n"
	.string "mostrador de recepción más adelante.\l"
	.string "Esperamos que vuelvas a concursar.$"

ContestHall_Text_OnlyRegister4Players:
	.string "I only register four players for\n"
	.string "POKéMON CONTESTS.\p"
	.string "If three other players link up, all\n"
	.string "four may enter the same CONTEST.\p"
	.string "Would you like to take part?$"

LilycoveCity_ContestLobby_Text_ProgressWillBeSaved:
	.string "Antes de entrar en un CONCURSO,\n"
	.string "tienes que guardar la partida.$"

LilycoveCity_ContestLobby_Text_ParticipateAnotherTime:
	.string "Esperamos que participes en alguna\n"
	.string "otra ocasión.$"

LilycoveCity_ContestLobby_Text_EnterContest2:
	.string "Would you like to enter a CONTEST?$"

LilycoveCity_ContestLobby_Text_Explain4PlayerContest:
	.string "When four players are ready, connect\n"
	.string "over a Game Link cable, and register\l"
	.string "with me, please.\p"
	.string "Please choose the same CONTEST\n"
	.string "as your fellow contestants.\p"
	.string "The CONTEST begins as soon as all\n"
	.string "players register their entry.\p"
	.string "After that, the usual CONTEST rules\n"
	.string "apply.$"

LilycoveCity_ContestLobby_Text_EnterWhichContest2:
	.string "Which CONTEST would you like to enter?$"

LilycoveCity_ContestLobby_Text_EnterWhichPokemon2:
	.string "Which POKéMON would you like to enter?$"

LilycoveCity_ContestLobby_Text_Transmitting:
	.string "Transmitiendo… $"

LilycoveCity_ContestLobby_Text_TransmissionError:
	.string "Error de transmisión…$"

LilycoveCity_ContestLobby_Text_PlayersChoseDifferentContest:
	.string "Es posible que hayas escogido\n"
	.string "un CONCURSO diferente al de los\l"
	.string "demás jugadores.$"

LilycoveCity_ContestLobby_Text_PlayersMadeDifferentChoice:
	.string "Es posible que hayas hecho una elección\n"
	.string "diferente a la de los demás jugadores.$"

LilycoveCity_ContestLobby_Text_PleaseWaitBButtonCancel:
	.string "Espera unos instantes.\n"
	.string "Pulsa el Botón B para cancelar.$"

LilycoveCity_ContestLobby_Text_ParticipateAnotherTime2:
	.string "We hope you will participate another\n"
	.string "time.$"

LilycoveCity_ContestLobby_Text_TransmissionErrorTryAgain:
	.string "Transmission error.\n"
	.string "Please try again.$"

LilycoveCity_ContestLobby_Text_YourMonIsEntryNumX:
	.string "Tu POKéMON va a participar\n"
	.string "en el CONCURSO.\p"
	.string "Tiene la entrada n.º {STR_VAR_2}.$"

LilycoveCity_ContestLobby_Text_ContestBeginShortly:
	.string "El CONCURSO está a punto de empezar.$"

LilycoveCity_ContestLobby_Text_LinkContestReception:
	.string "¡Hola, nos encargamos de organizar los\n"
	.string "CONCURSOS POKéMON en modo conexión!\p"
	.string "Puedes participar en estos CONCURSOS\n"
	.string "con uno o más amigos.$"

LilycoveCity_ContestLobby_Text_WhichTopic2:
	.string "¿Qué te gustaría saber?$"

LilycoveCity_ContestLobby_Text_EnterContest3:
	.string "¿Quieres entrar en un CONCURSO?$"

LilycoveCity_ContestLobby_Text_EnterWhichContest3:
	.string "¿En qué CONCURSO quieres entrar?$"

LilycoveCity_ContestLobby_Text_MonInNoCondition2:
	.string "Parece que tu POKéMON no está\n"
	.string "en condiciones de competir…$"

LilycoveCity_ContestLobby_Text_EggCannotTakePart2:
	.string "Lo siento, pero un HUEVO no puede\n"
	.string "participar en un CONCURSO POKéMON.$"

LilycoveCity_ContestLobby_Text_EnterWhichPokemon3:
	.string "¿Con qué POKéMON quieres participar?$"

LilycoveCity_ContestLobby_Text_PleaseDecideLinkLeader:
	.string "Un jugador debe ser LÍDER del GRUPO.\p"
	.string "Y los otros, “UNIRSE al GRUPO”.$"

LilycoveCity_ContestLobby_Text_PlayerAt4PCounterUseGMode:
	.string "Al menos un jugador ha entrado a través\n"
	.string "del mostrador para 4 jugadores.\p"
	.string "Se necesitan 4 jugadores conectados\n"
	.string "con el cable Game Link de GBA.\p"
	.string "Cuando todos los jugadores estén\n"
	.string "listos, elige CONEXIÓN G (GLOBAL)\l"
	.string "y regístrate para participar.$"

LilycoveCity_ContestLobby_Text_ExplainLinkContest:
	.string "En este CONCURSO pueden participar\n"
	.string "de 2 a 4 jugadores usando el Conector\l"
	.string "inalámbrico o un cable Game Link de GBA.\p"
	.string "Los participantes deben elegir el tipo\n"
	.string "de conexión que desean utilizar.\p"
	.string "Hay dos posibilidades.\p"
	.string "En la CONEXIÓN ESMERALDA pueden\n"
	.string "jugar de 2 a 4 jugadores, cada uno con\l"
	.string "un cartucho de POKéMON Esmeralda.\p"
	.string "La CONEXIÓN GLOBAL es sólo para\n"
	.string "4 jugadores, cada uno con un cartucho\l"
	.string "de POKéMON Esmeralda, Rubí o Zafiro.\p"
	.string "Los jugadores deben decidir el tipo\n"
	.string "de conexión que desean y seleccionarlo.\p"
	.string "El registro se completará una vez que\n"
	.string "todos los jugadores hayan elegido\l"
	.string "el mismo CONCURSO y la misma conexión.\p"
	.string "Una vez hecho, se dará inicio\n"
	.string "al CONCURSO de la manera habitual.$"

LilycoveCity_ContestLobby_Text_ExplainEMode:
	.string "En la CONEXIÓN E (ESMERALDA) pueden\n"
	.string "jugar de 2 a 4 jugadores.\l"
	.string "Cada uno de ellos debe tener un\l"
	.string "cartucho de POKéMON Esmeralda.\p"
	.string "Los jugadores deben estar conectados\n"
	.string "entre sí con Conectores inalámbricos\l"
	.string "o cables Game Link de GBA.\p"
	.string "Si hay menos de 4 jugadores, la\n"
	.string "alineación del CONCURSO se completará\l"
	.string "con ENTRENADORES del vestíbulo.\p"
	.string "Recuerda que la CONEXIÓN E no está\n"
	.string "disponible en POKéMON Rubí o Zafiro.$"

LilycoveCity_ContestLobby_Text_ExplainGMode:
	.string "La CONEXIÓN G (GLOBAL) es exclusiva\n"
	.string "para CONCURSOS de 4 jugadores, que se\l"
	.string "conectan con cables Game Link de GBA.\p"
	.string "Cada jugador debe tener un cartucho\n"
	.string "de POKéMON Esmeralda, Rubí o Zafiro.\p"
	.string "El CONCURSO empieza una vez que todos\n"
	.string "los jugadores seleccionan CONEXIÓN G\l"
	.string "(POKéMON Esmeralda) o entran a través\l"
	.string "del mostrador para 4 jugadores\l"
	.string "(POKéMON Rubí o Zafiro).$"

LilycoveCity_ContestLobby_Text_NoWirelessAdapterInGMode:
	.string "Cuánto lo siento.\p"
	.string "La CONEXIÓN G no es compatible\n"
	.string "con los Conectores inalámbricos.\p"
	.string "Elige la CONEXIÓN E o inténtalo de\n"
	.string "nuevo con el cable Game Link de GBA.$"

LilycoveCity_ContestLobby_Text_WhichContestMode:
	.string "¿Qué tipo de CONEXIÓN quieres?$"

ContestHall_Text_GettingStartedWireless:
	.string "PRESENTADORA: ¡Hola! ¡Estamos a punto\n"
	.string "de empezar un CONCURSO POKéMON de\l"
	.string "{STR_VAR_2} para 4 jugadores\l"
	.string "conectados!$"

ContestHall_Text_ParticipantsAsFollows:
	.string "Los ENTRENADORES y POKéMON\n"
	.string "participantes son los siguientes…$"

ContestHall_Text_WeveSeenContestants:
	.string "PRESENTADORA: Acabamos de conocer\n"
	.string "a los cuatro POKéMON participantes.\p"
	.string "¡Es hora de realizar la primera\n"
	.string "votación!$"

ContestHall_Text_AudienceWillVote:
	.string "El público votará a su POKéMON\n"
	.string "favorito entre los participantes.$"

ContestHall_Text_LetVotingBegin:
	.string "¡Que empiece la votación!$"

ContestHall_Text_VotingComplete:
	.string "¡La votación ha concluido!\p"
	.string "Mientras se recuentan los votos,\n"
	.string "pasemos a la segunda votación.$"

ContestHall_Text_SecondStageOfJudging:
	.string "Se trata del muy esperado momento\n"
	.string "de las exhibiciones.\p"
	.string "Esperemos que los participantes nos\n"
	.string "impresionen exhibiendo sus mejores\l"
	.string "y más sorprendentes movimientos.$"

ContestHall_Text_LetsAppeal:
	.string "¡Es hora de mostrar entusiasmo!\n"
	.string "¡Adelante con las exhibiciones!$"
