
Route117_Text_SeeWifeIfYoudLikeMeToRaiseMon:
	.string "Soy el ENCARGADO de la GUARDERÍA.\p"
	.string "Ayudo a los ENTRENADORES a cuidar\n"
	.string "de sus preciosos POKéMON.\p"
	.string "Si quieres que me encargue del tuyo,\n"
	.string "ve a hablar con mi mujer.$"

Route117_Text_DoYouWantEgg:
	.string "¡Ah, eres tú!\p"
	.string "¡Hemos cuidado de tu POKéMON y vaya\n"
	.string "sorpresa que nos hemos llevado!\p"
	.string "¡Tu POKéMON ha tenido un HUEVO!\p"
	.string "No sabemos cómo ha sucedido,\n"
	.string "pero es de tu POKéMON, seguro.\p"
	.string "¿Lo quieres?$"

Route117_Text_YourMonIsDoingFine:
	.string "¡Ah, eres tú! Me alegro de verte.\n"
	.string "Tu {STR_VAR_1} está estupendamente.$"

Route117_Text_IllKeepIt:
	.string "Muy bien, entonces me seguiré\n"
	.string "ocupando de él. ¡Gracias!$"

Route117_Text_YouHaveNoRoomForIt:
	.string "No tienes sitio para él…\n"
	.string "Vuelve cuando lo tengas.$"

Route117_Text_ReceivedEgg:
	.string "{PLAYER} recibió el HUEVO del\n"
	.string "ENCARGADO de la GUARDERÍA.$"

Route117_Text_TakeGoodCareOfIt:
	.string "Cuídalo bien.$"

Route117_Text_FriendlyWithOtherTrainersMon:
	.string "Por cierto, con respecto a tu\n"
	.string "{STR_VAR_1}, parece que se ha hecho\l"
	.string "amigo del {STR_VAR_3} de {STR_VAR_2}.\p"
	.string "Es incluso posible que haya\n"
	.string "recibido una CARTA.$"

@ Unused
Route117_Text_SeeWifeIfYouWantToPickUpMon:
	.string "If you want to pick up your POKéMON,\n"
	.string "have a word with my wife.$"

Route117_Text_YourMonsAreDoingFine:
	.string "¡Ah, eres tú! Tu {STR_VAR_1} y el\n"
	.string "{STR_VAR_2} están muy bien.$"

Route117_Text_IWillKeepDoYouWantIt:
	.string "Yo me lo quedaría.\n"
	.string "Pero imagino que lo quieres.$"

Route117_PokemonDayCare_Text_WouldYouLikeUsToRaiseAMon:
	.string "Soy la ENCARGADA de la GUARDERÍA.\p"
	.string "Podemos ocuparnos de tus POKéMON.\p"
	.string "¿Quieres que cuidemos de alguno?$"

Route117_PokemonDayCare_Text_WhichMonShouldWeRaise:
	.string "¿Qué POKéMON quieres que cuidemos?$"

Route117_PokemonDayCare_Text_WellRaiseYourMon:
	.string "Estupendo, nos ocuparemos de tu\n"
	.string "{STR_VAR_1} cuanto sea necesario.\p"
	.string "Vuelve cuando quieras.$"

Route117_PokemonDayCare_Text_WeCanRaiseOneMore:
	.string "Podemos cuidar a dos de tus POKéMON.\n"
	.string "¿Quieres que cuidemos de otro más?$"

Route117_PokemonDayCare_Text_HusbandWasLookingForYou:
	.string "Mi marido te estaba buscando.$"

Route117_PokemonDayCare_Text_FineThenComeAgain:
	.string "Muy bien.\n"
	.string "Vuelve cuando quieras.$"

Route117_PokemonDayCare_Text_NotEnoughMoney:
	.string "No tienes bastante dinero.$"

Route117_PokemonDayCare_Text_TakeOtherOneBackToo:
	.string "¿Quieres llevarte el otro también?$"

Route117_PokemonDayCare_Text_ComeAgain:
	.string "Muy bien.\n"
	.string "Vuelve cuando quieras.$"

Route117_PokemonDayCare_Text_GoodToSeeYou:
	.string "¡Ah, eres tú! Me alegro de verte.\n"
	.string "Y tú te alegrarás de saber esto…$"

Route117_PokemonDayCare_Text_YourMonHasGrownXLevels:
	.string "Tu {STR_VAR_1} ha crecido\n"
	.string "estos niveles: ¡{STR_VAR_2}!$"

Route117_PokemonDayCare_Text_YourTeamIsFull:
	.string "Tu equipo POKéMON está lleno.\n"
	.string "Haz un hueco y vuelve a verme.$"

@ Unused
Route117_PokemonDayCare_Text_TakeBackWhichMon:
	.string "Which POKéMON will you take back?$"

Route117_PokemonDayCare_Text_ItWillCostX:
	.string "Si quieres llevarte a tu {STR_VAR_1},\n"
	.string "tendrás que pagar {STR_VAR_2}¥.$"

Route117_PokemonDayCare_Text_HeresYourMon:
	.string "¡Perfecto!\n"
	.string "Aquí tienes a tu POKéMON.$"

Route117_PokemonDayCare_Text_TookBackMon:
	.string "{PLAYER} recogió a {STR_VAR_1} de\n"
	.string "la GUARDERÍA POKéMON.$"

Route117_PokemonDayCare_Text_YouHaveJustOneMon:
	.string "Anda, pero si sólo tienes un POKéMON…\p"
	.string "Vuelve cuando tengas alguno más.$"

Route117_PokemonDayCare_Text_TakeYourMonBack:
	.string "¿Quieres recoger un POKéMON?$"

Route117_PokemonDayCare_Text_WhatWillYouBattleWith:
	.string "Si me dejas ese POKéMON,\n"
	.string "no podrás entablar combates.\p"
	.string "Vuelve en otra ocasión.$"

Text_EggHatchHuh:
	.string "¿Y esto?$"

Route117_PokemonDayCare_Text_YoullBeLeftWithJustOne:
	.string "¿Eh?\n"
	.string "A ver, a ver.\p"
	.string "Si me dejas ese POKéMON aquí, \n"
	.string "sólo te quedarás con uno en forma.\p"
	.string "Será mejor que atrapes alguno más,\n"
	.string "vamos, digo yo.$"
