@ Only contains the text for the Mauville Man named Giddy. The rest is in scripts/mauville_man.inc
GiddyText_SoPretty::
	.string " belleza.$"

GiddyText_SoDarling::
	.string " dulzura.$"

GiddyText_SoRelaxed::
	.string " serenidad.$"

GiddyText_SoSunny::
	.string " alegría.$"

GiddyText_SoDesirable::
	.string " atractivo.$"

GiddyText_SoExciting::
	.string " emoción.$"

GiddyText_SoAmusing::
	.string " diversión.$"

GiddyText_SoMagical::
	.string " magia.$"

GiddyText_Is::
	.string " sugiere$"

GiddyText_DontYouAgree::
	.string "\n"
	.string "¿No crees?$"

GiddyText_ISoWantToGoOnAVacation::
	.string "Quiero tomarme unas vacaciones.\n"
	.string "¿Conoces algún lugar bonito?$"

GiddyText_IBoughtCrayonsWith120Colors::
	.string "¡Compré lápices de 120 colores!\n"
	.string "¿No te parece estupendo?$"

GiddyText_WouldntItBeNiceIfWeCouldFloat::
	.string "¿A que estaría bien poder flotar\n"
	.string "en una nube de burbujas?$"

GiddyText_WhenYouWriteOnASandyBeach::
	.string "Es una pena que las olas borren\n"
	.string "lo que se escribe en la arena…$"

GiddyText_WhatsTheBottomOfTheSeaLike::
	.string "¿Cómo será el fondo del mar?\n"
	.string "¿No te encantaría verlo?$"

GiddyText_WhenYouSeeTheSettingSunDoesIt::
	.string "Cuando se hace de noche, \n"
	.string "¿te apetece volver a casa?$"

GiddyText_LyingBackInTheGreenGrass::
	.string "¡Tumbado en la hierba se\n"
	.string "está tan bien! ¿A que sí?$"

GiddyText_SecretBasesAreSoWonderful::
	.string "¡Las BASES SECRETAS son geniales!\n"
	.string "¿No estás de acuerdo?$"
