gText_ObtainedTheItem::
	.string "¡Obtuvo {STR_VAR_2}!$"

gText_TheBagIsFull::
	.string "La MOCHILA está llena…$"

gText_PutItemInPocket::
	.string "{PLAYER} puso {STR_VAR_2}\n"
	.string "en el BOLSILLO de {STR_VAR_3}.$"

gText_PlayerFoundOneItem::
	.string "¡{PLAYER} encontró {STR_VAR_2}!$"

gText_TooBadBagIsFull::
	.string "¡Mala suerte!\n"
	.string "La MOCHILA está llena…$"

gText_PlayerPutItemInBag::
	.string "{PLAYER} puso {STR_VAR_2}\n"
	.string "en la MOCHILA.$"

gText_ObtainedTheDecor::
	.string "¡Obtuvo {STR_VAR_2}!$"

gText_NoRoomLeftForAnother::
	.string "¡Mala suerte! No queda sitio\n"
	.string "para {STR_VAR_2}…$"

gText_TheDecorWasTransferredToThePC::
	.string "Se envió {STR_VAR_2} al PC.$"
