SafariZone_Text_WouldYouLikeToExit:
	.string "¿Quieres salir de la ZONA SAFARI\n"
	.string "ahora mismo?$"

SafariZone_Text_TimesUp:
	.string "¡Ding, dong! ¡Se acabó el tiempo!\n"
	.string "Tu partida SAFARI ha terminado.$"

SafariZone_Text_OutOfBalls:
	.string "Te has quedado sin SAFARI BALLS.\n"
	.string "Tu partida SAFARI ha terminado.$"

SafariZone_Text_PlacePokeblockOnFeeder:
	.string "¿Quieres colocar un {POKEBLOCK}\n"
	.string "en el COMEDERO de {POKEBLOCK}S?$"

SafariZone_Text_PokeblockStillHere:
	.string "El {STR_VAR_1} que colocaste\n"
	.string "antes sigue aquí.$"

SafariZone_Text_PokeblockWasPlaced:
	.string "Has colocado un {STR_VAR_1}\n"
	.string "en el COMEDERO de {POKEBLOCK}S.$"

Route121_SafariZoneEntrance_Text_WelcomeToSafariZone:
	.string "¡Hola! ¡Ésta es la ZONA SAFARI!\p"
	.string "Aquí puedes ver muchos tipos\n"
	.string "de POKéMON poco comunes en HOENN.\p"
	.string "Y además los verás en estado\n"
	.string "salvaje, en su hábitat natural.\p"
	.string "Lo que es más, hemos abierto nuestras\n"
	.string "puertas a los ENTRENADORES POKéMON.\p"
	.string "¡Puedes atrapar los POKéMON\n"
	.string "que quieras y quedártelos para siempre!\p"
	.string "¡Pasa y disfruta de la ZONA SAFARI!$"

Route121_SafariZoneEntrance_Text_WelcomeFirstTime:
	.string "¡Hola! ¡Ésta es la ZONA SAFARI!\n"
	.string "¿Es la primera vez que vienes?$"

Route121_SafariZoneEntrance_Text_ComeInAndEnjoy:
	.string "¡Pasa y disfruta de la ZONA SAFARI!$"

Route121_SafariZoneEntrance_Text_FirstTimeInfo:
	.string "Cuando entras en la ZONA SAFARI,\n"
	.string "te dan 30 SAFARI BALLS para\l"
	.string "atrapar POKéMON.\p"
	.string "La partida SAFARI se acaba cuando\n"
	.string "te quedas sin SAFARI BALLS\l"
	.string "o has dado 500 pasos.\p"
	.string "¡Pasa y disfruta de la ZONA SAFARI!$"

Route121_SafariZoneEntrance_Text_WouldYouLikeToPlay:
	.string "¡Hola! ¡Ésta es la ZONA SAFARI!\p"
	.string "¡Atrapa todo lo que puedas por sólo\n"
	.string "500¥! ¿Quieres jugar una partida\l"
	.string "SAFARI?$"

Route121_SafariZoneEntrance_Text_PlayAnotherTime:
	.string "No hay problema.\n"
	.string "Ven cuando quieras.$"

Route121_SafariZoneEntrance_Text_NotEnoughMoney:
	.string "Lo siento, no tienes bastante dinero.$"

Route121_SafariZoneEntrance_Text_ThatWillBe500Please:
	.string "Son 500¥, por favor.$"

Route121_SafariZoneEntrance_Text_HereAreYourSafariBalls:
	.string "Aquí tienes tus SAFARI BALLS.$"

Route121_SafariZoneEntrance_Text_Received30SafariBalls:
	.string "{PLAYER} recibió 30 SAFARI BALLS.$"

Route121_SafariZoneEntrance_Text_PleaseEnjoyYourself:
	.string "Te avisaremos cuando se termine\n"
	.string "la partida.\p"
	.string "Hasta entonces, pásatelo bien.\n"
	.string "¡La aventura ha comenzado!$"

Route121_SafariZoneEntrance_Text_PCIsFull:
	.string "Lo siento, pero todas las CAJAS\n"
	.string "de tu PC están llenas.$"

Route121_SafariZoneEntrance_Text_YouNeedPokeblockCase:
	.string "Lo siento, pero parece que no tienes\n"
	.string "ningún TUBO de {POKEBLOCK}S.\p"
	.string "Tu partida SAFARI será mucho más\n"
	.string "fructífera si usas {POKEBLOCK}S.\p"
	.string "Vuelve cuando tengas un TUBO.\p"
	.string "Puedes conseguir uno en la SALA\n"
	.string "de CONCURSOS de CALAGUA.$"

SafariZone_South_Text_StillHaveTimeExit:
	.string "Todavía te queda tiempo. ¿Quieres\n"
	.string "salir de la ZONA SAFARI ahora mismo?$"

SafariZone_South_Text_EnjoyTheRestOfYourAdventure:
	.string "¡Sigue disfrutando de tu aventura!$"

SafariZone_South_Text_ExitEarlyThankYouForPlaying:
	.string "Muy bien.\p"
	.string "Me quedaré con las SAFARI BALLS\n"
	.string "que te sobran.\p"
	.string "Gracias por jugar con nosotros.\n"
	.string "Vuelve siempre que quieras.$"

SafariZone_South_Text_GoodLuck:
	.string "¡Buena suerte!\p"
	.string "Si necesitas algo, lo que sea,\n"
	.string "avísame, ¿de acuerdo?$"

SafariZone_South_Text_Boy:
	.string "¿No lo sabías?\p"
	.string "Si pones un {POKEBLOCK} en ese cajón,\n"
	.string "atraerás a muchos POKéMON.$"

SafariZone_South_Text_Man:
	.string "Quiero seguir adentrándome,\n"
	.string "pero he olvidado mi BICI.\p"
	.string "Tengo la corazonada de que en\n"
	.string "las zonas más distantes viven\l"
	.string "POKéMON raros.$"

SafariZone_Southwest_Text_Woman:
	.string "A veces, cuando lanzo un {POKEBLOCK}\n"
	.string "a un POKéMON, no le hace ni caso.\p"
	.string "¿Los POKéMON también son\n"
	.string "tiquismiquis con la comida?$"

SafariZone_Northwest_Text_Man:
	.string "Uf… Uf…\n"
	.string "He… llegado hasta… aquí…\p"
	.string "Estoy agotado… No me quedan\n"
	.string "fuerzas para atrapar POKéMON…$"

SafariZone_North_Text_Fisherman:
	.string "Estoy en una misión de búsqueda\n"
	.string "de POKéMON raros de tipo AGUA.\p"
	.string "¿Sabes por dónde queda el lago?$"

SafariZone_North_Text_Man:
	.string "Voy a atrapar un montón de POKéMON\n"
	.string "raros para cambiarlos con mis amigos.$"

SafariZone_South_Text_Youngster:
	.string "He puesto un {POKEBLOCK} en el COMEDERO\n"
	.string "de {POKEBLOCK}S, pero ha desaparecido.\p"
	.string "Creo que algún POKéMON se lo habrá\n"
	.string "comido cuando no miraba.$"

Route121_SafariZoneEntrance_Text_TrainerTip:
	.string "PISTA para ENTRENADORES\n"
	.string "de la ZONA SAFARI\p"
	.string "Lanza {POKEBLOCK}S a los POKéMON salvajes\n"
	.string "para que no se escapen corriendo.$"

SafariZone_Southwest_Text_RestHouseSign:
	.string "POSADA\n"
	.string "“Alivia tus cansados pies.”$"

SafariZone_RestHouse_Text_Youngster:
	.string "No tengo ningún {POKEBLOCK}, pero\n"
	.string "he atrapado bastantes POKéMON.\p"
	.string "Puedes mejorar tus posibilidades\n"
	.string "de atrapar POKéMON acercándote a ellos\l"
	.string "antes de lanzar una SAFARI BALL.$"

SafariZone_RestHouse_Text_PsychicM:
	.string "Si usas {POKEBLOCK}S, los POKéMON\n"
	.string "salvajes no escaparán tan rápido.\p"
	.string "Pero no vale la pena dar {POKEBLOCK}S a los\n"
	.string "POKéMON que son más mansos…$"

SafariZone_RestHouse_Text_FatMan:
	.string "Si pones un {POKEBLOCK} en el COMEDERO\n"
	.string "de {POKEBLOCK}S, atraerás a POKéMON.\p"
	.string "Creo que a los POKéMON que comparten\n"
	.string "la misma naturaleza les gusta el mismo\l"
	.string "tipo de {POKEBLOCK}.$"

SafariZone_South_Text_AreaOffLimits1:
	.string "Aún se está construyendo esta zona.\n"
	.string "¡No te acerques, por favor!$"

SafariZone_Southeast_Text_ExpansionIsFinished:
	.string "Ya ha concluido el proyecto\n"
	.string "de ampliación de la ZONA SAFARI.\p"
	.string "Espero que disfrutes de las nuevas\n"
	.string "instalaciones.$"

SafariZone_South_Text_AreaOffLimits2:
	.string "Aún se está construyendo esta zona.\n"
	.string "¡No te acerques, por favor!$"

SafariZone_Southeast_Text_LittleGirl:
	.string "¡Guau! ¡Eh! ¡Nunca había visto\n"
	.string "estos POKéMON antes!$"

SafariZone_Southeast_Text_FatMan:
	.string "Todos los POKéMON de esta zona\n"
	.string "son nuevos para mí.\p"
	.string "¡Y tengo permiso para atraparlos!\n"
	.string "¡Qué suerte!$"

SafariZone_Southeast_Text_RichBoy:
	.string "Los POKéMON que hay por aquí\n"
	.string "no parece que sean de HOENN.$"

SafariZone_Northeast_Text_Boy:
	.string "Ya sólo me quedan dos SAFARI BALLS.\p"
	.string "Lo estoy pasando mal teniendo que\n"
	.string "decidir cuáles atrapo y cuáles no.$"

SafariZone_Northeast_Text_Woman:
	.string "He oído que hay PIKACHU por aquí.\n"
	.string "¿Por dónde andarán?$"

SafariZone_Northeast_Text_Girl:
	.string "¡Bah!\n"
	.string "¡Oye, no pillo nada!\p"
	.string "¡Con lo que cuesta la entrada\n"
	.string "y yo no voy a atrapar ni uno!$"
