SecretBase_Text_TreeCanBeClimbed:
	.string "Si cae una liana, querrá decir\n"
	.string "que se puede trepar a este árbol.$"

SecretBase_Text_TreeUseSecretPower:
	.string "Si cae una liana, querrá decir\n"
	.string "que se puede trepar a este árbol.\p"
	.string "¿Usas DAÑO SECRETO?$"

SecretBase_Text_VineDroppedDown:
	.string "¡Ha caído una liana muy gruesa!$"

SecretBase_Text_ClumpOfGrass:
	.string "Si se puede mover este montón\n"
	.string "de hierba, es porque se puede entrar.$"

SecretBase_Text_ClumpUseSecretPower:
	.string "Si se puede mover este montón\n"
	.string "de hierba, es porque se puede entrar.\p"
	.string "¿Usas DAÑO SECRETO?$"

SecretBase_Text_DiscoveredSmallEntrance:
	.string "¡Has descubierto una pequeña abertura!$"
