
FortreeCity_House2_Text_HiddenPowersArousedByNature:
	.string "Los poderes ocultos de la gente y de\n"
	.string "los POKéMON salen a la luz cuando\l"
	.string "viven en contacto con la naturaleza.$"

FortreeCity_House2_Text_CoinInWhichHand:
	.string "Deja que compruebe si tus poderes\n"
	.string "ocultos han despertado…\p"
	.string "Tengo una moneda en una mano.\p"
	.string "Ahora dime, ¿está en la mano derecha?\n"
	.string "¿O quizás en la izquierda?$"

FortreeCity_House2_Text_CorrectTryAgainWhichHand:
	.string "¡Has acertado!\p"
	.string "Volvamos a intentarlo.\p"
	.string "¿Dónde guardo la moneda?\n"
	.string "¿En la mano derecha o en la izquierda?$"

FortreeCity_House2_Text_CorrectTryAgainWhichHand2:
	.string "¡Has acertado!\p"
	.string "Volvamos a intentarlo.\p"
	.string "¿Dónde guardo la moneda?\n"
	.string "¿En la mano derecha o en la izquierda?$"

FortreeCity_House2_Text_YourHiddenPowerHasAwoken:
	.string "¡Magnífico!\n"
	.string "¡Tus poderes ocultos están activos!\p"
	.string "Mira, te voy a dar esto para que puedas\n"
	.string "hacer lo mismo con tus POKéMON.$"

FortreeCity_House2_Text_ExplainHiddenPower:
	.string "PODER OCULTO es un movimiento\n"
	.string "que se adapta a cada POKéMON.$"

FortreeCity_House2_Text_YouGuessedWrong:
	.string "Pues no. Te has equivocado.$"
