BattleFrontier_Lounge8_MapScripts::
	.byte 0

BattleFrontier_Lounge8_EventScript_Man::
	msgbox BattleFrontier_Lounge8_Text_WhatATrainerNeeds, MSGBOX_NPC
	end

BattleFrontier_Lounge8_EventScript_Woman::
	msgbox BattleFrontier_Lounge8_Text_KnowAboutFrontierBrains, MSGBOX_NPC
	end

BattleFrontier_Lounge8_EventScript_NinjaBoy::
	msgbox BattleFrontier_Lounge8_Text_ToldMeIHaveTalentForBattling, MSGBOX_NPC
	end

BattleFrontier_Lounge8_Text_WhatATrainerNeeds:
	.string "Ce dont un DRESSEUR a besoin…\p"
	.string "Savoir…\n"
	.string "Tactique…\l"
	.string "Chance…\l"
	.string "Cran…\l"
	.string "Esprit…\l"
	.string "Bravoure…\l"
	.string "Capacité…\p"
	.string "Parfait, je suis prêt!\n"
	.string "Je vais relever tous les défis!\p"
	.string "Quoi? Des POKéMON?\n"
	.string "C’est quoi ça?$"

BattleFrontier_Lounge8_Text_KnowAboutFrontierBrains:
	.string "Tu as entendu parler des MENEURS DE\n"
	.string "ZONE?\p"
	.string "C’est ainsi que SCOTT appelle les sept\n"
	.string "DRESSEURS responsables de chaque\l"
	.string "bâtiment de la ZONE DE COMBAT.$"

BattleFrontier_Lounge8_Text_ToldMeIHaveTalentForBattling:
	.string "A la TOUR DE COMBAT, une fille m’a dit\n"
	.string "que j’avais beaucoup de talent!\p"
	.string "Moi, je préfère les CONCOURS POKéMON!\n"
	.string "Mais je ne suis pas fort!\p"
	.string "On n’est pas forcément doué pour les\n"
	.string "choses qu’on aime…$"

