BattleFrontier_Lounge8_MapScripts:: @ 82676C9
	.byte 0

BattleFrontier_Lounge8_EventScript_Man:: @ 82676CA
	msgbox BattleFrontier_Lounge8_Text_WhatATrainerNeeds, MSGBOX_NPC
	end

BattleFrontier_Lounge8_EventScript_Woman:: @ 82676D3
	msgbox BattleFrontier_Lounge8_Text_KnowAboutFrontierBrains, MSGBOX_NPC
	end

BattleFrontier_Lounge8_EventScript_NinjaBoy:: @ 82676DC
	msgbox BattleFrontier_Lounge8_Text_ToldMeIHaveTalentForBattling, MSGBOX_NPC
	end

BattleFrontier_Lounge8_Text_WhatATrainerNeeds: @ 82676E5
	.string "What a Trainer needs…\p"
	.string "Knowledge…\n"
	.string "Strategy…\l"
	.string "Luck…\l"
	.string "Guts…\l"
	.string "Spirit…\l"
	.string "Bravery…\l"
	.string "And ability…\p"
	.string "Well, I'm all set in every way!\n"
	.string "I'll be unstoppable at every building!\p"
	.string "Huh? Pokémon?\n"
	.string "What's that?$"

BattleFrontier_Lounge8_Text_KnowAboutFrontierBrains: @ 826779C
	.string "Do you know about the Frontier\n"
	.string "Brains?\p"
	.string "That's what Scott calls the seven\n"
	.string "special Trainers that run the seven\l"
	.string "facilities in the Battle Frontier.$"

BattleFrontier_Lounge8_Text_ToldMeIHaveTalentForBattling: @ 826782C
	.string "At the Battle Tower, an older girl\n"
	.string "told me that I have a lot of talent\l"
	.string "for battling!\p"
	.string "I like Pokémon Contests more!\p"
	.string "But I'm no good at Contests!\p"
	.string "I guess having talent and liking\n"
	.string "something aren't the same.$"

