
BattleFrontier_Lounge8_Text_WhatATrainerNeeds:
	.string "Dicen que un ENTRENADOR necesita:\p"
	.string "sabiduría,\n"
	.string "táctica,\l"
	.string "fortuna,\l"
	.string "coraje,\l"
	.string "ánimo,\l"
	.string "valentía\l"
	.string "y destreza.\p"
	.string "Bien, ¡pues yo lo tengo todo!\n"
	.string "¡No va a haber nadie que me pare!\p"
	.string "¿Eh? ¿POKéMON?\n"
	.string "¿Y eso qué es lo que es?$"

BattleFrontier_Lounge8_Text_KnowAboutFrontierBrains:
	.string "¿Has oído alguna vez hablar\n"
	.string "de los ASES del FRENTE?\p"
	.string "Es como TRETO llama a los siete\n"
	.string "ENTRENADORES que mandan en los\l"
	.string "siete edificios del FRENTE de BATALLA.$"

BattleFrontier_Lounge8_Text_ToldMeIHaveTalentForBattling:
	.string "En la TORRE BATALLA una niña mayor\n"
	.string "me dijo que yo valía para los combates.\p"
	.string "¡Pero a mí me gustan mucho más\n"
	.string "los CONCURSOS POKéMON!\p"
	.string "Lo que pasa es que… para\n"
	.string "los CONCURSOS soy una patata.\p"
	.string "Supongo que una cosa es que te guste\n"
	.string "algo y otra que realmente valgas…$"
