PetalburgCity_Gym_Text_GiveEnigmaBerry:
	.string "PAPÀ: Ciao, {PLAYER}!\p"
	.string "Ho appena ricevuto una BACCA molto\n"
	.string "rara. Vorrei che la prendessi tu!$"

Route104_Text_PlantBerriesInSoilTakeThis:
	.string "Se vedi delle BACCHE che crescono su\n"
	.string "un terreno fertile, prendile pure.\p"
	.string "Però è regola comune piantare un’altra\n"
	.string "BACCA nello stesso punto. Ricordati!\p"
	.string "Ecco, un regalo per te.$"

Route104_Text_TrainersOftenMakeMonHoldBerries:
	.string "Dall’aspetto sembri un ALLENATORE,\n"
	.string "o sbaglio?\p"
	.string "Gli ALLENATORI spesso fanno tenere\n"
	.string "BACCHE ai loro POKéMON.\p"
	.string "Sei tu a decidere quante BACCHE vuoi\n"
	.string "usare e quante ne vuoi piantare.$"

Route111_Text_WateredPlantsEveryDayTakeBerry:
	.string "Ho annaffiato le piante ogni giorno.\n"
	.string "Sono sbocciati molti fiori.\p"
	.string "E hanno fatto anche molte BACCHE.\p"
	.string "Ecco!\n"
	.string "Puoi prenderla!$"

Route111_Text_GoingToTryToMakeDifferentColorBerries:
	.string "Cercherò di piantare BACCHE di\n"
	.string "diverso tipo.\p"
	.string "Spero che ti impegnerai anche tu!$"

Route111_Text_WhatColorBerriesToLookForToday:
	.string "Di quale colore cercherò le BACCHE\n"
	.string "oggi?$"

Route114_Text_LoveUsingBerryCrushShareBerry:
	.string "Mi piace molto usare il MACINABACCHE.\n"
	.string "Per questo cerco le BACCHE.\p"
	.string "Se vuoi, te ne do una.$"

Route114_Text_TryBerryCrushWithFriends:
	.string "Dovresti provare il MACINABACCHE\n"
	.string "con i tuoi amici.$"

Route114_Text_FunToThinkAboutBerries:
	.string "Che BACCHE è meglio piantare?\n"
	.string "È meglio usarle o accumularle?\p"
	.string "Mi piace riflettere su cose come\n"
	.string "queste.$"

Route120_Text_BerriesExpressionOfLoveIsntIt:
	.string "Le BACCHE crescono grazie alla\n"
	.string "luce del sole.\p"
	.string "Innaffiandole regolarmente, noi le\n"
	.string "aiutiamo a crescere.\p"
	.string "È un segno d’affetto, non credi?$"

Route120_Text_YesYouUnderstand:
	.string "Sì, sì.\n"
	.string "Hai capito cosa intendo!\p"
	.string "Vorrei darti questa.$"

Route120_Text_MakeYourOwnImpressions:
	.string "Oh… è importante che tu abbia\n"
	.string "le tue opinioni, credo…\p"
	.string "Prendi questa.$"

Route120_Text_BerryIsRareRaiseItWithCare:
	.string "Penso che questa BACCA sia rara.\n"
	.string "Spero che te ne prenderai cura.$"

Route120_Text_IllGetMoreBerriesFromBerryMaster:
	.string "Io mi farò dare altre BACCHE da BACCO\n"
	.string "BACCHINI.$"

LilycoveCity_Text_BerrySuitsYou:
	.string "In parole semplici…\p"
	.string "L’abito è perfetto su di me, come una \n"
	.string "frizzante brezza che accarezza il mare.\p"
	.string "Allo stesso modo, la BACCA è perfetta\n"
	.string "su di te…\p"
	.string "Perché?$"

LilycoveCity_Text_BecauseYoureTrainer:
	.string "In parole semplici…\p"
	.string "È perché sei un ALLENATORE!$"

LilycoveCity_Text_PokeblocksSuitPokemon:
	.string "In parole semplici…\p"
	.string "La semplicità è il mio dono, e le {POKEMELLE}\n"
	.string "sono doni per i POKéMON.$"

Route123_BerryMastersHouse_Text_YoureDeservingOfBerry:
	.string "Puoi chiamarmi BACCO.\p"
	.string "Il mio sogno è colmare il mondo di\n"
	.string "magnifici fiori e far crescere BACCHE\l"
	.string "da donare a tutti.\p"
	.string "Tu ne meriti una!$"

Route123_BerryMastersHouse_Text_WhyBeStingyTakeAnother:
	.string "Non voglio essere tirchio.\n"
	.string "Eccotene un’altra!$"

Route123_BerryMastersHouse_Text_VisitPrettyPetalFlowerShop:
	.string "Ricordati di fare un salto dal FIORISTA\n"
	.string "BEL PETALO vicino a FERRUGIPOLI.\p"
	.string "Riempiamo il mondo di fiori!$"

Route123_BerryMastersHouse_Text_DoneForToday:
	.string "È tutto per oggi.\n"
	.string "Ritorna un’altra volta.\p"
	.string "Riempiamo il mondo di fiori!$"

Route123_BerryMastersHouse_Text_HeardAGoodSayingLately:
	.string "Mio marito è il miglior coltivatore di\n"
	.string "BACCHE del mondo!\p"
	.string "Sono così orgogliosa di lui.\p"
	.string "Hai per caso sentito un bel detto\n"
	.string "di recente?$"

Route123_BerryMastersHouse_Text_InspirationalTakeThis:
	.string "Ah! Che detto interessante!\n"
	.string "Ispirato, direi!\p"
	.string "Ti meriti una ricompensa!$"

Route123_BerryMastersHouse_Text_GoodSayingTakeThis:
	.string "Oh! Proprio un bel detto.\n"
	.string "Sei eccezionale!\p"
	.string "Ti meriti una ricompensa!$"

Route123_BerryMastersHouse_Text_JoyNeverGoesOutOfMyLife:
	.string "I nostri quattro nipotini dovrebbero\n"
	.string "diventare ancora più abili di mio marito.\p"
	.string "Io continuerò ad essere sempre felice!$"

Route123_BerryMastersHouse_Text_Ah:
	.string "Ah…$"

Route104_PrettyPetalFlowerShop_Text_ThisIsPrettyPetalFlowerShop:
	.string "Ciao!\p"
	.string "Questo è il FIORISTA BEL PETALO.\n"
	.string "Copriamo il mondo di fiori!$"

Route104_PrettyPetalFlowerShop_Text_LearnAboutBerries:
	.string "{PLAYER}{KUN}, ti piacerebbe sapere qualcosa\n"
	.string "sulle BACCHE?$"

Route104_PrettyPetalFlowerShop_Text_IntroLearnAboutBerries:
	.string "Come ti chiami?\p"
	.string "{PLAYER}{KUN}!\n"
	.string "Proprio un bel nome!\p"
	.string "Senti, {PLAYER}{KUN}, ti piacerebbe sapere\n"
	.string "qualcosa sulle BACCHE?$"

Route104_PrettyPetalFlowerShop_Text_BerriesExplanation:
	.string "Le BACCHE si trovano su alberelli che\n"
	.string "crescono in aree fertili e soffici.\p"
	.string "Se raccogli delle BACCHE, piantane delle\n"
	.string "altre nello stesso terreno fertile.\p"
	.string "Una volta piantata, la BACCA\n"
	.string "germoglierà, diventerà pianta,\l"
	.string "darà bellissimi fiori e nuove BACCHE.\p"
	.string "Mi piacerebbe vedere il mondo ricoperto\n"
	.string "di magnifici fiori. È il mio sogno.\p"
	.string "Ti prego aiutami, {PLAYER}{KUN}.\n"
	.string "Pianta le BACCHE e fai fiorire il mondo!$"

Route104_PrettyPetalFlowerShop_Text_FlowersBringHappiness:
	.string "I fiori portano il sorriso alle persone,\n"
	.string "non credi?$"

Route104_PrettyPetalFlowerShop_Text_YouCanHaveThis:
	.string "Ciao!\p"
	.string "I fiori hanno bisogno di molte cure e \n"
	.string "attenzioni per diventare belli.\p"
	.string "Ti piacerà prenderti cura dei fiori,\n"
	.string "ne sono sicura. Prendi questo!$"

Route104_PrettyPetalFlowerShop_Text_WailmerPailExplanation:
	.string "Mentre le piante da BACCHE crescono,\n"
	.string "bisogna annaffiarle col VASO WAILMER.\p"
	.string "Oh, un’altra cosa.\p"
	.string "Se non raccogli le BACCHE per un po’,\n"
	.string "cadranno a terra.\l"
	.string "E germoglieranno ancora.\p"
	.string "Non è strano? È come se avessero\n"
	.string "il desiderio di rigenerarsi da sole!$"

Route104_PrettyPetalFlowerShop_Text_ImGrowingFlowers:
	.string "Voglio essere come le mie sorelle grandi.\n"
	.string "Anch’io coltivo fiori!\p"
	.string "Guarda! È per te!$"

Route104_PrettyPetalFlowerShop_Text_MachineMixesBerries:
	.string "Puoi piantare una BACCA per farla\n"
	.string "germogliare o farla tenere a un\l"
	.string "POKéMON.\p"
	.string "Adesso, però, esiste anche una macchina\n"
	.string "con cui si possono fare mix di BACCHE\l"
	.string "diverse, e farne caramelle per i\l"
	.string "POKéMON.\p"
	.string "Anch’io voglio delle caramelle.$"

SootopolisCity_Text_NameIsKiriHaveOneOfThese:
	.string "Ciao, come ti chiami?\p"
	.string "… … …  … … …  … … …\n"
	.string "Ok, bello!\p"
	.string "Io mi chiamo KIRA.\p"
	.string "I miei genitori mi hanno dato questo\n"
	.string "nome perché volevano che crescessi\l"
	.string "in salute e diventassi cordiale.\p"
	.string "Puoi avere una di queste.$"

SootopolisCity_Text_GiveYouThisBerryToo:
	.string "KIRA ti dà anche questa BACCA.\n"
	.string "È veramente bella!$"

SootopolisCity_Text_WhatKindOfWishInYourName:
	.string "Che significato misterioso avrà\n"
	.string "il tuo nome?$"

SootopolisCity_Text_LikeSeasonBornIn:
	.string "Primavera, estate, autunno e inverno.\p"
	.string "I nati in primavera amano la primavera,\n"
	.string "mentre i nati in estate amano l’estate?$"

SootopolisCity_Text_ThenILoveAutumn:
	.string "Allora… KIRA è nata in autunno…\n"
	.string "Io amo l’autunno!\p"
	.string "Che stagione ti piace?$"

SootopolisCity_Text_OhDoesntMatter:
	.string "Oh… non importa…\p"
	.string "Ci sono tante cose che vorrei sapere…$"
