Route117_Text_SeeWifeIfYoudLikeMeToRaiseMon:
	.string "Sono il PADRONE della PENSIONE\n"
	.string "POKéMON.\p"
	.string "Aiutiamo gli ALLENATORI a prendersi\n"
	.string "cura dei loro preziosi amici.\p"
	.string "Se vuoi che alleviamo anche i tuoi\n"
	.string "POKéMON, rivolgiti a mia moglie.$"

Route117_Text_DoYouWantEgg:
	.string "Ah, sei tu!\p"
	.string "Stavamo allevando i tuoi POKéMON\n"
	.string "e, mamma mia, che sorpresa!!!\p"
	.string "Hanno avuto un UOVO!\p"
	.string "Non sappiamo come sia finito lì, ma\n"
	.string "sta di fatto che c’è!\p"
	.string "Vuoi ritirarlo, vero?$"

Route117_Text_YourMonIsDoingFine:
	.string "Ah, sei tu! Hai fatto bene a\n"
	.string "passare. Il tuo {STR_VAR_1} sta\l"
	.string "crescendo bene.$"

Route117_Text_IllKeepIt:
	.string "Va bene, allora lo tengo io.\n"
	.string "Grazie!$"

Route117_Text_YouHaveNoRoomForIt:
	.string "La tua squadra è al completo.\n"
	.string "Torna quando hai un po’ più di\l"
	.string "spazio.$"

Route117_Text_ReceivedEgg:
	.string "{PLAYER} riceve l’UOVO dalla\n"
	.string "PENSIONE POKéMON.$"

Route117_Text_TakeGoodCareOfIt:
	.string "Abbine cura!$"

Route117_Text_FriendlyWithOtherTrainersMon:
	.string "A proposito del tuo {STR_VAR_1},\n"
	.string "pare andare d’accordo con\l"
	.string "{STR_VAR_3} di {STR_VAR_2}.\p"
	.string "Mi pare di averlo visto ricevere\n"
	.string "un MESSAGGIO.$"

@ Unused
Route117_Text_SeeWifeIfYouWantToPickUpMon:
	.string "If you want to pick up your POKéMON,\n"
	.string "have a word with my wife.$"

Route117_Text_YourMonsAreDoingFine:
	.string "Ah, sei tu! I tuoi {STR_VAR_1} e\n"
	.string "{STR_VAR_2} stanno crescendo bene.$"

Route117_Text_IWillKeepDoYouWantIt:
	.string "Vorrei tenerlo io.\n"
	.string "Ma tu lo rivuoi indietro, vero?$"

Route117_PokemonDayCare_Text_WouldYouLikeUsToRaiseAMon:
	.string "Sono la PADRONA della PENSIONE\n"
	.string "POKéMON.\p"
	.string "Possiamo allevare i tuoi POKéMON!\p"
	.string "Vuoi affidarcene uno?$"

Route117_PokemonDayCare_Text_WhichMonShouldWeRaise:
	.string "Che POKéMON vuoi che alleviamo?$"

Route117_PokemonDayCare_Text_WellRaiseYourMon:
	.string "Perfetto, alleveremo il tuo\n"
	.string "{STR_VAR_1} per un po’.\p"
	.string "Torna a prenderlo più tardi.$"

Route117_PokemonDayCare_Text_WeCanRaiseOneMore:
	.string "Possiamo allevare due dei tuoi\n"
	.string "POKéMON. Vuoi lasciarcene un\l"
	.string "altro?$"

Route117_PokemonDayCare_Text_HusbandWasLookingForYou:
	.string "Mio marito ti stava cercando.$"

Route117_PokemonDayCare_Text_FineThenComeAgain:
	.string "Oh, come vuoi.\n"
	.string "Torna a trovarci.$"

Route117_PokemonDayCare_Text_NotEnoughMoney:
	.string "Non hai abbastanza soldi…$"

Route117_PokemonDayCare_Text_TakeOtherOneBackToo:
	.string "Vuoi ritirare anche l’altro?$"

Route117_PokemonDayCare_Text_ComeAgain:
	.string "Va bene.\n"
	.string "Torna quando vuoi.$"

Route117_PokemonDayCare_Text_GoodToSeeYou:
	.string "Ah, sei tu! Hai fatto bene a passare.\n"
	.string "Stiamo ottenendo ottimi risultati!$"

Route117_PokemonDayCare_Text_YourMonHasGrownXLevels:
	.string "Il livello del tuo {STR_VAR_1} è\n"
	.string "cresciuto di {STR_VAR_2}!$"

Route117_PokemonDayCare_Text_YourTeamIsFull:
	.string "La tua squadra POKéMON è completa.\n"
	.string "Torna quando hai qualche posto libero.$"

@ Unused
Route117_PokemonDayCare_Text_TakeBackWhichMon:
	.string "Which POKéMON will you take back?$"

Route117_PokemonDayCare_Text_ItWillCostX:
	.string "Per ritirare il tuo {STR_VAR_1},\n"
	.string "devi pagare ¥{STR_VAR_2}.$"

Route117_PokemonDayCare_Text_HeresYourMon:
	.string "Perfetto!\n"
	.string "Eccoti il POKéMON.$"

Route117_PokemonDayCare_Text_TookBackMon:
	.string "{PLAYER} ritira {STR_VAR_1} dalla\n"
	.string "PENSIONE POKéMON.$"

Route117_PokemonDayCare_Text_YouHaveJustOneMon:
	.string "Eh? Ma tu hai soltanto un POKéMON.\p"
	.string "Torna un’altra volta.$"

Route117_PokemonDayCare_Text_TakeYourMonBack:
	.string "Sei qui per ritirare un POKéMON?$"

Route117_PokemonDayCare_Text_WhatWillYouBattleWith:
	.string "Se mi affidi quel POKéMON,\n"
	.string "non potrai più lottare.\p"
	.string "Torna un’altra volta.$"

Text_EggHatchHuh:
	.string "Uh?$"

Route117_PokemonDayCare_Text_YoullBeLeftWithJustOne:
	.string "Uh?\n"
	.string "Ehm.\p"
	.string "Se mi affidi quel POKéMON te\n"
	.string "ne rimarrà solo uno.\p"
	.string "Ti consiglio di catturarne qualcuno\n"
	.string "in più.$"
