
gText_PokemartSign::
	.string "POKéMON-MARKET\n"
	.string "“Strumenti per ogni esigenza!”.$"

gText_PokemonCenterSign::
	.string "CENTRO POKéMON\n"
	.string "“Per rinvigorire i tuoi amici stanchi!”.$"

gText_MomOrDadMightLikeThisProgram::
	.string "Questo programma piacerebbe a {STR_VAR_1}.\n"
	.string "… … … … … … … … … … … … … … … …\p"
	.string "La TV è come una calamita!$"

gText_WhichFloorWouldYouLike::
	.string "Ti trovi nell’ascensore del CENTRO\n"
	.string "COMMERCIALE di ALGHEPOLI.\p"
	.string "A quale piano ti porto?$"

gText_SandstormIsVicious::
	.string "La tempesta di sabbia è impetuosa.\n"
	.string "È impossibile proseguire il cammino.$"

gText_SelectWithoutRegisteredItem::
	.string "Puoi assegnare uno strumento\n"
	.string "dello ZAINO a SELECT.$"

gText_PokemonTrainerSchoolEmail::
	.string "È arrivata una e-mail dalla SCUOLA per\n"
	.string "ALLENATORI di POKéMON.\p"
	.string "… … … … … …\p"
	.string "Un POKéMON può conoscere fino\n"
	.string "a quattro mosse.\p"
	.string "Più bravo è l’ALLENATORE, migliore sarà\n"
	.string "la rosa di mosse scelta per POKéMON.\p"
	.string "… … … … … …$"

gText_PlayerHouseBootPC::
	.string "{PLAYER} accende il PC.$"

gText_PokeblockLinkCanceled::
	.string "Collegamento annullato.$"

gText_UnusedNicknameReceivedPokemon::
	.string "Want to give a nickname to\n"
	.string "the {STR_VAR_2} you received?$"

gText_PlayerWhitedOut::
	.string "{PLAYER} non ha più POKéMON utili!\p"
	.string "{PLAYER} è fuori combattimento!$"

gText_RegisteredTrainerinPokeNav::
	.string "Registrazione di {STR_VAR_2},\n"
	.string "{STR_VAR_1}, nel POKéNAV avvenuta.$"

gText_ComeBackWithSecretPower::
	.string "Conosci la MT FORZASEGRETA?\p"
	.string "Il nostro gruppo adora la MT\n"
	.string "FORZASEGRETA.\p"
	.string "La potrai ottenere da uno dei nostri.\n"
	.string "Ritorna quando ce l’hai per mostrarmela.\p"
	.string "Così sarai dei nostri e ti venderemo\n"
	.string "della buona merce in segreto.$"

gText_PokerusExplanation::
	.string "I tuoi POKéMON potrebbero essere\n"
	.string "infettati dal POKéRUS.\p"
	.string "Si sa poco sul POKéRUS, ma pare che\n"
	.string "si tratti di forme di vita microscopiche\l"
	.string "che infettano i POKéMON.\p"
	.string "Pare che i POKéMON infettati crescano\n"
	.string "straordinariamente bene.$"

gText_WantToUseSurf::
	.string "L’acqua ha un colore azzurro marino…\n"
	.string "Vuoi usare SURF?$"

gText_PlayerUsedSurf::
	.string "{STR_VAR_1} usa SURF!$"

gText_DoorOpenedFarAway::
	.string "Sembra che si sia aperta una porta\n"
	.string "in lontananza.$"

gText_BigHoleInTheWall::
	.string "C’è un grosso buco nella parete.$"

gText_SorryWirelessClubAdjustments::
	.string "Sono spiacente.\n"
	.string "Il CLUB WIRELESS POKéMON\l"
	.string "è chiuso per lavori.$"

gText_UndergoingAdjustments::
	.string "Sembra che sia chiuso per lavori.$"

@ Unused
gText_SorryTradeCenterInspections::
	.string "I’m terribly sorry. The TRADE CENTER\n"
	.string "is undergoing inspections.$"

@ Unused
gText_SorryRecordCornerPreparation::
	.string "I’m terribly sorry. The RECORD CORNER\n"
	.string "is under preparation.$"

gText_PlayerHandedOverTheItem::
	.string "{PLAYER} cede\n"
	.string "{STR_VAR_1}.$"

gText_ThankYouForAccessingMysteryGift::
	.string "Grazie per usufruire del Sistema\n"
	.string "DONO SEGRETO!$"

gText_PlayerFoundOneTMHM::
	.string "{PLAYER} trova la {STR_VAR_1}\n"
	.string "contenente {STR_VAR_2}!$"

gText_Sudowoodo_Attacked::
	.string "Lo strano albero non gradisce\n"
	.string "il VASO WAILMER!\p"
	.string "Lo strano albero ti sta attaccando!$"

gText_LegendaryFlewAway::
	.string "{STR_VAR_1} è fuggito!$"
