@ Only contains the text for the Mauville Man named Giddy. The rest is in scripts/mauville_man.inc
GiddyText_SoPretty::
	.string "che piacevole!$"

GiddyText_SoDarling::
	.string "che dolce!$"

GiddyText_SoRelaxed::
	.string "che riposante!$"

GiddyText_SoSunny::
	.string "che solare!$"

GiddyText_SoDesirable::
	.string "che spasso!$"

GiddyText_SoExciting::
	.string "che frizzante!$"

GiddyText_SoAmusing::
	.string "che divertente!$"

GiddyText_SoMagical::
	.string "che mistero!$"

GiddyText_Is::
	.string ": $"

GiddyText_DontYouAgree::
	.string "\n"
	.string "Non sei d’accordo?$"

GiddyText_ISoWantToGoOnAVacation::
	.string "Ho tanta voglia di andare in vacanza.\n"
	.string "Per caso conosci qualche bel posto?$"

GiddyText_IBoughtCrayonsWith120Colors::
	.string "Ho comprato dei pastelli di 120 colori!\n"
	.string "Che bella cosa, vero?$"

GiddyText_WouldntItBeNiceIfWeCouldFloat::
	.string "Non sarebbe stupendo volar via\n"
	.string "su una nube di bollicine?$"

GiddyText_WhenYouWriteOnASandyBeach::
	.string "Quando scrivi sulla spiaggia, l’acqua\n"
	.string "lava via le parole. È così triste!$"

GiddyText_WhatsTheBottomOfTheSeaLike::
	.string "Com’è il fondo del mare?\n"
	.string "Vorrei tanto andarci una volta!$"

GiddyText_WhenYouSeeTheSettingSunDoesIt::
	.string "Quando vedi il tramonto, non ti viene\n"
	.string "voglia di andare a casa?$"

GiddyText_LyingBackInTheGreenGrass::
	.string "Stendersi su un bel tappeto d’erba!\n"
	.string "Oh, è così bello!$"

GiddyText_SecretBasesAreSoWonderful::
	.string "Le BASI SEGRETE sono fantastiche!\n"
	.string "Non sei d’accordo?$"
