MoveTutor_Text_ThisMoveCanOnlyBeLearnedOnce:
	.string "Questa mossa può essere appresa\n"
	.string "soltanto una volta: vuoi continuare?$"

MoveTutor_Text_SwaggerTeach:
	.string "Ehi! Il mio POKéMON è un grande!\n"
	.string "Dà dei punti agli altri POKéMON!\p"
	.string "Mi stavo comportando da gradasso e\n"
	.string "camminavo con aria boriosa quando\l"
	.string "il PRESIDENTE mi ha ripreso.\p"
	.string "Per questo ho smesso di pavoneggiarmi.\p"
	.string "Se vuoi, posso insegnare la mossa\n"
	.string "BULLO a uno dei tuoi POKéMON.$"

MoveTutor_Text_SwaggerDeclined:
	.string "Perché no? Non riesci a cogliere\n"
	.string "lo spirito delle cose?$"

MoveTutor_Text_SwaggerWhichMon:
	.string "Bene! Quale dei tuoi POKéMON vuole\n"
	.string "imparare BULLO?$"

MoveTutor_Text_SwaggerTaught:
	.string "D’ora in poi loderò i miei POKéMON\n"
	.string "senza fare lo sbruffone.$"

MoveTutor_Text_RolloutTeach:
	.string "Lo sapevi che puoi andare lontano\n"
	.string "in quella direzione senza mai voltare?\p"
	.string "Rotolando è facilissimo.\p"
	.string "Credi che anche i tuoi POKéMON vogliano\n"
	.string "rotolare?\p"
	.string "Se vuoi, posso insegnare a uno dei tuoi\n"
	.string "POKéMON la mossa ROTOLAMENTO.$"

MoveTutor_Text_RolloutDeclined:
	.string "Non devi avere tante riserve.\n"
	.string "Rotolare è bello!$"

MoveTutor_Text_RolloutWhichMon:
	.string "Certo! Sarebbe fantastico se\n"
	.string "il POKéMON mi somigliasse.$"

MoveTutor_Text_RolloutTaught:
	.string "Rotolare nell’erba è divertentissimo.\n"
	.string "Forza, rotoliamo!$"

MoveTutor_Text_FuryCutterTeach:
	.string "C’è una mossa che aumenta di\n"
	.string "intensità se continui ad usarla.\p"
	.string "È una mossa di tipo COLEOTTERO ed\n"
	.string "è troppo forte.\p"
	.string "Si chiama TAGLIOFURIA.\n"
	.string "Vuoi che la insegni a un POKéMON?$"

MoveTutor_Text_FuryCutterDeclined:
	.string "Non siamo sulla stessa lunghezza\n"
	.string "d’onda.$"

MoveTutor_Text_FuryCutterWhichMon:
	.string "Ehi! Mostrami il POKéMON al quale\n"
	.string "la dovrei insegnare.$"

MoveTutor_Text_FuryCutterTaught:
	.string "L’idea che la mossa possa aumentare di\n"
	.string "intensità mi elettrizza!$"

MoveTutor_MimicTeach:
	.string "Ehi, giovane!\p"
	.string "Anche se sono giovane, mi piace\n"
	.string "imitare lo stile e il linguaggio delle\l"
	.string "persone anziane di questa città.\p"
	.string "Anche se sei giovane, ti piacerebbe\n"
	.string "che insegnassi la mossa MIMICA a\l"
	.string "uno dei tuoi POKéMON?$"

MoveTutor_MimicDeclined:
	.string "Buu! Volevo insegnare MIMICA\n"
	.string "a uno dei tuoi POKéMON!$"

MoveTutor_Text_MimicWhichMon:
	.string "Sono qui per questo!\n"
	.string "Mostrami il POKéMON al quale\l"
	.string "devo insegnare la mossa.$"

MoveTutor_Text_MimicTaught:
	.string "MIMICA è una mossa molto profonda.\p"
	.string "La sapresti eseguire alla perfezione\n"
	.string "come il sottoscritto…?$"

MoveTutor_Text_MetronomeTeach:
	.string "Voglio tante cose!\n"
	.string "Ma ho finito la paghetta…\p"
	.string "Non sarebbe fantastico se esistesse\n"
	.string "un incantesimo in grado di far apparire\l"
	.string "dei soldi facendo oscillare un dito?\p"
	.string "Se vuoi, posso insegnare a uno dei \n"
	.string "tuoi POKéMON la mossa METRONOMO.\p"
	.string "Non appariranno soldi, ma il tuo POKéMON\n"
	.string "farà oscillare un dito. Va bene?$"

MoveTutor_Text_MetronomeDeclined:
	.string "Okay. Se cambi idea sono a tua\n"
	.string "disposizione.$"

MoveTutor_Text_MetronomeWhichMon:
	.string "Okay! Sono pronta! Quale POKéMON\n"
	.string "devo istruire?$"

MoveTutor_Text_MetronomeTaught:
	.string "Quando un POKéMON fa oscillare il dito\n"
	.string "come un METRONOMO, accadono\l"
	.string "delle cose molto belle.\p"
	.string "Non sarebbe fantastico se la potessimo\n"
	.string "usare anche noi?$"

MoveTutor_Text_SleepTalkTeach:
	.string "Per rimanere sveglia mia moglie\n"
	.string "si affida a INTROFORZA.\p"
	.string "Dovrebbe fare un sonnellino come me e\n"
	.string "abbandonarsi a SONNOLALIA.\p"
	.string "Posso istruire uno dei tuoi POKéMON\n"
	.string "ad usare SONNOLALIA. Ti interessa?$"

MoveTutor_Text_SleepTalkDeclined:
	.string "Oh, capisco. Anche tu vuoi tenere gli\n"
	.string "occhi aperti con INTROFORZA…$"

MoveTutor_Text_SleepTalkWhichMon:
	.string "Ah, vedo che apprezzi! Quale POKéMON\n"
	.string "devo istruire?$"

MoveTutor_Text_SleepTalkTaught:
	.string "Non mi è mai riuscito il trucco della\n"
	.string "moneta di mia moglie.\p"
	.string "Mi piacerebbe azzeccarlo anche quando\n"
	.string "mi affido a SONNOLALIA…$"

MoveTutor_Text_SubstituteTeach:
	.string "Quando guardo il mondo dal tetto…\p"
	.string "penso a quanto sarebbe bello se\n"
	.string "esistessero più persone uguali a me\l"
	.string "e potessi vivere le loro esistenze.\p"
	.string "Ovviamente ciò non è possibile.\n"
	.string "Ihihih…\p"
	.string "Ti interesserebbe istruire un POKéMON\n"
	.string "a usare SOSTITUTO?$"

MoveTutor_Text_SubstituteDeclined:
	.string "Oh, no?\p"
	.string "Quando la usa il POKéMON può fare\n"
	.string "una copia di se stesso.$"

MoveTutor_Text_SubstituteWhichMon:
	.string "Ihihih… a quale POKéMON devo\n"
	.string "insegnare SOSTITUTO?$"

MoveTutor_Text_SubstituteTaught:
	.string "Noi esseri umani dovremmo goderci\n"
	.string "la vita al meglio!\p"
	.string "Spero che anche tu sia d’accordo\n"
	.string "con me!$"

MoveTutor_Text_DynamicPunchTeach:
	.string "Non ce la faccio più!\p"
	.string "Non ho speranza!\p"
	.string "Sono un ALLENATORE di tipo LOTTA e\n"
	.string "nella PALESTRA di VERDEAZZUPOLI\l"
	.string "non ho alcuna chance!\p"
	.string "Argh! Pugno! Pugno! Pugno!\n"
	.string "Pugno! Pugno! Pugno!\p"
	.string "Non guardarmi in quel modo!\n"
	.string "Sto solo colpendo a terra!\p"
	.string "O vuoi che insegni a uno dei tuoi\n"
	.string "POKéMON la mossa DINAMIPUGNO?$"

MoveTutor_Text_DynamicPunchDeclined:
	.string "Ti stai prendendo gioco di me?\n"
	.string "Pugno! Pugno! Pugno!$"

MoveTutor_Text_DynamicPunchWhichMon:
	.string "Davvero? Sei un tipo in gamba!\n"
	.string "Quale POKéMON vuoi che istruisca?$"

MoveTutor_Text_DynamicPunchTaught:
	.string "Voglio che tu vinca alla PALESTRA di\n"
	.string "VERDEAZZUPOLI con DINAMIPUGNO!$"

MoveTutor_Text_DoubleEdgeTeach:
	.string "Sigh…\p"
	.string "Il CAPOPALESTRA di CENERIDE\n"
	.string "è davvero ammirevole.\p"
	.string "Ma questo significa che molte\n"
	.string "vogliono catturare la sua attenzione.\p"
	.string "Con SDOPPIATORE è così affascinante\n"
	.string "da non riuscire a catturarne lo sguardo.\p"
	.string "Fammi insegnare a uno dei tuoi POKéMON\n"
	.string "la mossa SDOPPIATORE!$"

MoveTutor_Text_DoubleEdgeDeclined:
	.string "Oh… persino tu mi rifiuti…$"

MoveTutor_Text_DoubleEdgeWhichMon:
	.string "Okay, a quale POKéMON devo insegnare\n"
	.string "SDOPPIATORE?$"

MoveTutor_Text_DoubleEdgeTaught:
	.string "L’amore non sarà l’unico scopo della\n"
	.string "mia vita! Diventerò forte!$"

MoveTutor_Text_ExplosionTeach:
	.string "Se continuo a vivere in campagna\n"
	.string "non diventerò nessuno.\p"
	.string "Non perdermi di vista perché andrò a\n"
	.string "vivere in città per diventare una star.\p"
	.string "Non sto scherzando! Sarà\n"
	.string "un’ESPLOSIONE di popolarità!\p"
	.string "Ascoltami bene, vuoi che insegni\n"
	.string "ESPLOSIONE a uno dei tuoi POKéMON?$"

MoveTutor_Text_ExplosionDeclined:
	.string "Gaah! Hai rifiutato perché sono un tipo\n"
	.string "di campagna?$"

MoveTutor_Text_ExplosionWhichMon:
	.string "Bene! Ci sarà un’ESPLOSIONE!\n"
	.string "Quale POKéMON farà il botto?$"

MoveTutor_Text_ExplosionTaught:
	.string "È da tanto che insegno ESPLOSIONE ai\n"
	.string "POKéMON. Purtroppo quello che non\l"
	.string "ha ancora fatto il botto sono io…\p"
	.string "Forse, inconsciamente, voglio rimanere\n"
	.string "quello che sono…$"
