gText_WouldYouLikeToRestYourPkmn::
	.string "Sei in un CENTRO POKéMON.\p"
	.string "Rimettiamo in sesto i POKéMON stanchi.\p"
	.string "Vuoi far riposare la tua squadra?$"

gText_IllTakeYourPkmn::
	.string "Ok, mi prendo la tua squadra di POKéMON\n"
	.string "per qualche secondo.$"

gText_RestoredPkmnToFullHealth::
	.string "Grazie per l’attesa.\p"
	.string "Ora la tua squadra di POKéMON è \n"
	.string "in perfetta forma.$"

gText_WeHopeToSeeYouAgain::
	.string "Torna a farci visita!$"

gText_WelcomeCutShort::
	.string "Sei in un CENTRO POKéMON.\p"
	.string "Rimettiamo in sesto i POKéMON stanchi.\p"
	.string "Vuoi…?$"

gText_NoticesGoldCard::
	.string "Que-quella scheda…\n"
	.string "non è… una SCHEDA d’ORO?!\p"
	.string "Che lucentezza!\n"
	.string "Le quattro stelle sono brillantissime!\p"
	.string "Ho visto molti ALLENATORI con SCHEDE\n"
	.string "d’ARGENTO ma, ti dico la verità {PLAYER},\l"
	.string "tu sei il primo ALLENATORE con una\l"
	.string "SCHEDA d’ORO che io abbia incontrato!\p"
	.string "{PLAYER}, mi concedi l’onore di rimettere\n"
	.string "in sesto la tua squadra di POKéMON?$"

gText_YouWantTheUsual::
	.string "Sono felice di vederti, {PLAYER}!\n"
	.string "Il solito, suppongo?$"

gText_IllTakeYourPkmn2::
	.string "Ok, prenderò i tuoi POKéMON\n"
	.string "per qualche secondo.$"

gText_ThankYouForWaiting::
	.string "Grazie per l’attesa.$"

gText_WeHopeToSeeYouAgain2::
	.string "Arrivederci!$"
