gTrickHouse_Mechadoll_Oddish::
	.string "ODDISH$"

gTrickHouse_Mechadoll_Poochyena::
	.string "POOCHYENA$"

gTrickHouse_Mechadoll_Taillow::
	.string "TAILLOW$"

gTrickHouse_Mechadoll_Azurill::
	.string "AZURILL$"

gTrickHouse_Mechadoll_Lotad::
	.string "LOTAD$"

gTrickHouse_Mechadoll_Wingull::
	.string "WINGULL$"

gTrickHouse_Mechadoll_Dustox::
	.string "DUSTOX$"

gTrickHouse_Mechadoll_Zubat::
	.string "ZUBAT$"

gTrickHouse_Mechadoll_Nincada::
	.string "NINCADA$"

gTrickHouse_Mechadoll_Ralts::
	.string "RALTS$"

gTrickHouse_Mechadoll_Zigzagoon::
	.string "ZIGZAGOON$"

gTrickHouse_Mechadoll_Slakoth::
	.string "SLAKOTH$"

gTrickHouse_Mechadoll_Poochyena2::
	.string "POOCHYENA$"

gTrickHouse_Mechadoll_Shroomish::
	.string "SHROOMISH$"

gTrickHouse_Mechadoll_Zigzagoon2::
	.string "ZIGZAGOON$"

gTrickHouse_Mechadoll_Poochyena3::
	.string "POOCHYENA$"

gTrickHouse_Mechadoll_Zubat2::
	.string "ZUBAT$"

gTrickHouse_Mechadoll_Carvanha::
	.string "CARVANHA$"

gTrickHouse_Mechadoll_BurnHeal::
	.string "ANTISCOTTATURA$"

gTrickHouse_Mechadoll_HarborMail::
	.string "MESSAGGI PORTO$"

gTrickHouse_Mechadoll_SamePrice::
	.string "Stesso prezzo$"

gTrickHouse_Mechadoll_60Yen::
	.string "¥60$"

gTrickHouse_Mechadoll_55Yen::
	.string "¥55$"

gTrickHouse_Mechadoll_Nothing::
	.string "Nulla$"

gTrickHouse_Mechadoll_CostMore::
	.string "Costano di più$"

gTrickHouse_Mechadoll_CostLess::
	.string "Costano meno$"

gTrickHouse_Mechadoll_SamePrice2::
	.string "Stesso prezzo$"

gTrickHouse_Mechadoll_Male::
	.string "Uomini$"

gTrickHouse_Mechadoll_Female::
	.string "Donne$"

gTrickHouse_Mechadoll_Neither::
	.string "Stesso numero$"

gTrickHouse_Mechadoll_ElderlyMen::
	.string "Uomini anziani$"

gTrickHouse_Mechadoll_ElderlyLadies::
	.string "Donne anziane$"

gTrickHouse_Mechadoll_SameNumber::
	.string "Stesso numero$"

gTrickHouse_Mechadoll_None::
	.string "Nessuna$"

gTrickHouse_Mechadoll_One::
	.string "1$"

gTrickHouse_Mechadoll_Two::
	.string "2$"

gTrickHouse_Mechadoll_Two2::
	.string "2$"

gTrickHouse_Mechadoll_Three::
	.string "3$"

gTrickHouse_Mechadoll_Four::
	.string "4$"

gTrickHouse_Mechadoll_Six::
	.string "6$"

gTrickHouse_Mechadoll_Seven::
	.string "7$"

gTrickHouse_Mechadoll_Eight::
	.string "8$"

gTrickHouse_Mechadoll_Six2::
	.string "6$"

gTrickHouse_Mechadoll_Seven2::
	.string "7$"

gTrickHouse_Mechadoll_Eight2::
	.string "8$"
