
BattleFrontier_BattleArenaBattleRoom_Text_PlayerStepForward:
	.string "ARBITRO: {PLAYER}, fai un passo\n"
	.string "avanti!$"

BattleFrontier_BattleArenaBattleRoom_Text_OpponentStepForward:
	.string "ARBITRO: {STR_VAR_1}, fai un passo\n"
	.string "avanti!$"

BattleFrontier_BattleArenaBattleRoom_Text_SetKOTourneyBegin:
	.string "ARBITRO: Diamo inizio all’incontro!$"

BattleFrontier_BattleArenaBattleRoom_Text_WinnerIsPlayer:
	.string "ARBITRO: La vittoria va a {PLAYER}!$"

BattleFrontier_BattleArenaBattleRoom_Text_WinnerIsOpponent:
	.string "ARBITRO: La vittoria va a {STR_VAR_1}!$"

BattleFrontier_BattleArenaBattleRoom_Text_MonsWillBeRestored:
	.string "I tuoi POKéMON verranno rimessi\n"
	.string "in sesto.$"

BattleFrontier_BattleArenaBattleRoom_Text_ReadyFor2ndOpponent:
	.string "Ti attende il secondo rivale!\n"
	.string "Vuoi andare avanti?$"

BattleFrontier_BattleArenaBattleRoom_Text_ReadyFor3rdOpponent:
	.string "Ti attende il terzo rivale!\n"
	.string "Vuoi andare avanti?$"

BattleFrontier_BattleArenaBattleRoom_Text_ReadyFor4thOpponent:
	.string "Ti attende il quarto rivale!\n"
	.string "Vuoi andare avanti?$"

BattleFrontier_BattleArenaBattleRoom_Text_ReadyFor5thOpponent:
	.string "Ti attende il quinto rivale!\n"
	.string "Vuoi andare avanti?$"

BattleFrontier_BattleArenaBattleRoom_Text_ReadyFor6thOpponent:
	.string "Ti attende il sesto rivale!\n"
	.string "Vuoi andare avanti?$"

BattleFrontier_BattleArenaBattleRoom_Text_ReadyFor7thOpponent:
	.string "Ti attende il settimo rivale!\n"
	.string "Vuoi andare avanti?$"

BattleFrontier_BattleArenaBattleRoom_Text_SaveAndShutDown:
	.string "Vuoi salvare e interrompere il gioco?$"

BattleFrontier_BattleArenaBattleRoom_Text_RetireFromChallenge:
	.string "Vuoi ritirarti dalla sfida\n"
	.string "TORNEO TRE TURNI?$"

BattleFrontier_BattleArenaBattleRoom_Text_SavingPleaseWait:
	.string "Sto salvando i tuoi dati di gioco.\n"
	.string "Attendi.$"

BattleFrontier_BattleArenaBattleRoom_Text_RecordLastBattle:
	.string "Vuoi che il filmato della tua ultima\n"
	.string "lotta venga registrato nel PASS PARCO?$"

BattleFrontier_BattleArenaBattleRoom_Text_NowFaceTycoon:
	.string "Mio caro ALLENATORE!\p"
	.string "Le tue capacità sono straordinarie!\p"
	.string "Ti concediamo l’onore di lottare contro\n"
	.string "la nostra MAESTRA DOJO!$"

BattleFrontier_BattleArenaBattleRoom_Text_PreparedForTycoon:
	.string "Una lotta contro la MAESTRA DOJO!\n"
	.string "Te la senti?$"

BattleFrontier_BattleArenaBattleRoom_Text_MakeWayForGreta:
	.string "ARBITRO: Ecco la nostra MAESTRA DOJO,\n"
	.string "VALENTINA!$"

BattleFrontier_BattleArenaBattleRoom_Text_GretaYoureChallenger:
	.string "VALENTINA: Ehi!\n"
	.string "Salve!\p"
	.string "Sei tu che vuoi sfidarmi?$"

BattleFrontier_BattleArenaBattleRoom_Text_IsThatRight:
	.string "Davvero? Uhm… uhm…$"

BattleFrontier_BattleArenaBattleRoom_Text_YouLookWeakTakeThingsEasy:
	.string "Non so come dirtelo, ma hai\n"
	.string "un aspetto debole.\l"
	.string "Sarai alla mia altezza?\p"
	.string "Uhm…\p"
	.string "Vabbè!\n"
	.string "Cercherò di non infierire!$"

BattleFrontier_BattleArenaBattleRoom_Text_IgniteMyPassionForBattle:
	.string "Okay! Hai acceso il mio spirito\n"
	.string "combattivo!$"

BattleFrontier_BattleArenaBattleRoom_Text_GretaYoureToughAfterAll:
	.string "VALENTINA: Ehi, aspetta un attimo!\n"
	.string "Sei forte, nonostante le apparenze!\p"
	.string "Mi piaci!\n"
	.string "Mostrami il tuo PASS PARCO.$"

BattleFrontier_BattleArenaBattleRoom_Text_ReceivedGutsSymbol:
	.string "Il SIMBOLO VALORE è stato aggiunto\n"
	.string "al PASS PARCO!$"

BattleFrontier_BattleArenaBattleRoom_Text_GoingToBeFunNextTime:
	.string "Uhm…\p"
	.string "La prossima volta ci sarà da divertirsi!\n"
	.string "Non vedo l’ora!$"

BattleFrontier_BattleArenaBattleRoom_Text_GretaLookingForwardToSeeingAgain:
	.string "VALENTINA: Ehi! Salve!\n"
	.string "Finalmente ce l’hai fatta!\p"
	.string "L’attesa è stata snervante! Non vedevo\n"
	.string "l’ora di incontrarti di nuovo!$"

BattleFrontier_BattleArenaBattleRoom_Text_SoAreYouReady:
	.string "… … … te la senti?$"

BattleFrontier_BattleArenaBattleRoom_Text_WontAllowHalfheartedEffort:
	.string "Non accetto le mezze misure!\n"
	.string "Preparati a una lotta molto accesa!$"

BattleFrontier_BattleArenaBattleRoom_Text_LetsGetThisStarted:
	.string "Forza, ARBITRO!\n"
	.string "Diamo inizio alla lotta!$"

BattleFrontier_BattleArenaBattleRoom_Text_GretaBlownAway:
	.string "VALENTINA: Aaah! Che delusione!\n"
	.string "Mostrami il tuo PASS PARCO!$"

BattleFrontier_BattleArenaBattleRoom_Text_GutsSymbolTookGoldenShine:
	.string "Il SIMBOLO VALORE si è colorato\n"
	.string "d’oro!$"

BattleFrontier_BattleArenaBattleRoom_Text_IfWeBattleAgainWontLose:
	.string "Arrrgh!\n"
	.string "Sono così arrabbiata!\p"
	.string "Questa è l’ultima volta che perdo\n"
	.string "contro di te! Promesso! Ciao!$"