SafariZone_Northeast: @ 848528C
	.4byte SafariZone_Northeast_Layout
	.4byte SafariZone_Northeast_MapEvents
	.4byte SafariZone_Northeast_MapScripts
	.4byte SafariZone_Northeast_MapConnections
	.2byte MUS_SAFARI
	.2byte 394
	.byte MAPSEC_SAFARI_ZONE
	.byte 0
	.byte WEATHER_NONE
	.byte MAP_TYPE_ROUTE
	.2byte 0
	map_header_flags allow_bike=1, allow_escape_rope=0, allow_run=1, show_map_name=1
	.byte MAP_BATTLE_SCENE_NORMAL

