	.set BERRY_FIRMNESS_UNKNOWN,    0
	.set BERRY_FIRMNESS_VERY_SOFT,  1
	.set BERRY_FIRMNESS_SOFT,       2
	.set BERRY_FIRMNESS_HARD,       3
	.set BERRY_FIRMNESS_VERY_HARD,  4
	.set BERRY_FIRMNESS_SUPER_HARD, 5
