	.set FIELD_OBJ_GFX_BRENDAN_NORMAL,              0
	.set FIELD_OBJ_GFX_BRENDAN_MACH_BIKE,           1
	.set FIELD_OBJ_GFX_BRENDAN_SURFING,             2
	.set FIELD_OBJ_GFX_BRENDAN_FIELD_MOVE,          3
	.set FIELD_OBJ_GFX_QUINTY_PLUMP,                4
	.set FIELD_OBJ_GFX_LITTLE_BOY_1,                5
	.set FIELD_OBJ_GFX_LITTLE_GIRL_1,               6
	.set FIELD_OBJ_GFX_BOY_1,                       7
	.set FIELD_OBJ_GFX_GIRL_1,                      8
	.set FIELD_OBJ_GFX_BOY_2,                       9
	.set FIELD_OBJ_GFX_GIRL_2,                     10
	.set FIELD_OBJ_GFX_LITTLE_BOY_2,               11
	.set FIELD_OBJ_GFX_LITTLE_GIRL_2,              12
	.set FIELD_OBJ_GFX_BOY_3,                      13
	.set FIELD_OBJ_GFX_GIRL_3,                     14
	.set FIELD_OBJ_GFX_BOY_4,                      15
	.set FIELD_OBJ_GFX_WOMAN_1,                    16
	.set FIELD_OBJ_GFX_FAT_MAN,                    17
	.set FIELD_OBJ_GFX_WOMAN_2,                    18
	.set FIELD_OBJ_GFX_MAN_1,                      19
	.set FIELD_OBJ_GFX_WOMAN_3,                    20
	.set FIELD_OBJ_GFX_OLD_MAN_1,                  21
	.set FIELD_OBJ_GFX_OLD_WOMAN_1,                22
	.set FIELD_OBJ_GFX_MAN_2,                      23
	.set FIELD_OBJ_GFX_WOMAN_4,                    24
	.set FIELD_OBJ_GFX_MAN_3,                      25
	.set FIELD_OBJ_GFX_WOMAN_5,                    26
	.set FIELD_OBJ_GFX_COOK,                       27
	.set FIELD_OBJ_GFX_WOMAN_6,                    28
	.set FIELD_OBJ_GFX_OLD_MAN_2,                  29
	.set FIELD_OBJ_GFX_OLD_WOMAN_2,                30
	.set FIELD_OBJ_GFX_CAMPER,                     31
	.set FIELD_OBJ_GFX_PICNICKER,                  32
	.set FIELD_OBJ_GFX_MAN_4,                      33
	.set FIELD_OBJ_GFX_WOMAN_7,                    34
	.set FIELD_OBJ_GFX_YOUNGSTER,                  35
	.set FIELD_OBJ_GFX_BUG_CATCHER,                36
	.set FIELD_OBJ_GFX_PSYCHIC_M,                  37
	.set FIELD_OBJ_GFX_SCHOOL_KID_M,               38
	.set FIELD_OBJ_GFX_MANIAC,                     39
	.set FIELD_OBJ_GFX_HEX_MANIAC,                 40
	.set FIELD_OBJ_GFX_RAYQUAZA_1,                 41
	.set FIELD_OBJ_GFX_SWIMMER_M,                  42
	.set FIELD_OBJ_GFX_SWIMMER_F,                  43
	.set FIELD_OBJ_GFX_BLACK_BELT,                 44
	.set FIELD_OBJ_GFX_BEAUTY,                     45
	.set FIELD_OBJ_GFX_SCIENTIST_1,                46
	.set FIELD_OBJ_GFX_LASS,                       47
	.set FIELD_OBJ_GFX_GENTLEMAN,                  48
	.set FIELD_OBJ_GFX_SAILOR,                     49
	.set FIELD_OBJ_GFX_FISHERMAN,                  50
	.set FIELD_OBJ_GFX_RUNNING_TRIATHLETE_M,       51
	.set FIELD_OBJ_GFX_RUNNING_TRIATHLETE_F,       52
	.set FIELD_OBJ_GFX_TUBER_F,                    53
	.set FIELD_OBJ_GFX_TUBER_M,                    54
	.set FIELD_OBJ_GFX_HIKER,                      55
	.set FIELD_OBJ_GFX_CYCLING_TRIATHLETE_M,       56
	.set FIELD_OBJ_GFX_CYCLING_TRIATHLETE_F,       57
	.set FIELD_OBJ_GFX_NURSE,                      58
	.set FIELD_OBJ_GFX_ITEM_BALL,                  59
	.set FIELD_OBJ_GFX_BERRY_TREE,                 60
	.set FIELD_OBJ_GFX_BERRY_TREE_EARLY_STAGES,    61
	.set FIELD_OBJ_GFX_BERRY_TREE_LATE_STAGES,     62
	.set FIELD_OBJ_GFX_BRENDAN_ACRO_BIKE,          63
	.set FIELD_OBJ_GFX_PROF_BIRCH,                 64
	.set FIELD_OBJ_GFX_MAN_5,                      65
	.set FIELD_OBJ_GFX_MAN_6,                      66
	.set FIELD_OBJ_GFX_REPORTER_M,                 67
	.set FIELD_OBJ_GFX_REPORTER_F,                 68
	.set FIELD_OBJ_GFX_MAUVILLE_OLD_MAN,           69
	.set FIELD_OBJ_GFX_ANABEL,                     70
	.set FIELD_OBJ_GFX_TUCKER,                     71
	.set FIELD_OBJ_GFX_GRETA,                      72
	.set FIELD_OBJ_GFX_SPENSER,                    73
	.set FIELD_OBJ_GFX_NOLAND,                     74
	.set FIELD_OBJ_GFX_LUCY,                       75
	.set FIELD_OBJ_GFX_UNUSED_NATU_DOLL,           76
	.set FIELD_OBJ_GFX_UNUSED_MAGNEMITE_DOLL,      77
	.set FIELD_OBJ_GFX_UNUSED_SQUIRTLE_DOLL,       78
	.set FIELD_OBJ_GFX_UNUSED_WOOPER_DOLL,         79
	.set FIELD_OBJ_GFX_UNUSED_PIKACHU_DOLL,        80
	.set FIELD_OBJ_GFX_UNUSED_PORYGON2_DOLL,       81
	.set FIELD_OBJ_GFX_CUTTABLE_TREE,              82
	.set FIELD_OBJ_GFX_MART_EMPLOYEE,              83
	.set FIELD_OBJ_GFX_ROOFTOP_SALE_WOMAN,         84
	.set FIELD_OBJ_GFX_TEALA,                      85
	.set FIELD_OBJ_GFX_BREAKABLE_ROCK,             86
	.set FIELD_OBJ_GFX_PUSHABLE_BOULDER,           87
	.set FIELD_OBJ_GFX_MR_BRINEYS_BOAT,            88
	.set FIELD_OBJ_GFX_MAY_NORMAL,                 89
	.set FIELD_OBJ_GFX_MAY_MACH_BIKE,              90
	.set FIELD_OBJ_GFX_MAY_ACRO_BIKE,              91
	.set FIELD_OBJ_GFX_MAY_SURFING,                92
	.set FIELD_OBJ_GFX_MAY_FIELD_MOVE,             93
	.set FIELD_OBJ_GFX_TRUCK,                      94
	.set FIELD_OBJ_GFX_VIGOROTH_CARRYING_BOX,      95
	.set FIELD_OBJ_GFX_VIGOROTH_FACING_AWAY,       96
	.set FIELD_OBJ_GFX_BIRCHS_BAG,                 97
	.set FIELD_OBJ_GFX_ENEMY_ZIGZAGOON,            98
	.set FIELD_OBJ_GFX_ARTIST,                     99
	.set FIELD_OBJ_GFX_RIVAL_BRENDAN_NORMAL,      100
	.set FIELD_OBJ_GFX_RIVAL_BRENDAN_MACH_BIKE,   101
	.set FIELD_OBJ_GFX_RIVAL_BRENDAN_ACRO_BIKE,   102
	.set FIELD_OBJ_GFX_RIVAL_BRENDAN_SURFING,     103
	.set FIELD_OBJ_GFX_RIVAL_BRENDAN_FIELD_MOVE,  104
	.set FIELD_OBJ_GFX_RIVAL_MAY_NORMAL,          105
	.set FIELD_OBJ_GFX_RIVAL_MAY_MACH_BIKE,       106
	.set FIELD_OBJ_GFX_RIVAL_MAY_ACRO_BIKE,       107
	.set FIELD_OBJ_GFX_RIVAL_MAY_SURFING,         108
	.set FIELD_OBJ_GFX_RIVAL_MAY_FIELD_MOVE,      109
	.set FIELD_OBJ_GFX_CAMERAMAN,                 110
	.set FIELD_OBJ_GFX_BRENDAN_UNDERWATER,        111
	.set FIELD_OBJ_GFX_MAY_UNDERWATER,            112
	.set FIELD_OBJ_GFX_MOVING_BOX,                113
	.set FIELD_OBJ_GFX_CABLE_CAR,                 114
	.set FIELD_OBJ_GFX_SCIENTIST_2,               115
	.set FIELD_OBJ_GFX_MAN_7,                     116
	.set FIELD_OBJ_GFX_AQUA_MEMBER_M,             117
	.set FIELD_OBJ_GFX_AQUA_MEMBER_F,             118
	.set FIELD_OBJ_GFX_MAGMA_MEMBER_M,            119
	.set FIELD_OBJ_GFX_MAGMA_MEMBER_F,            120
	.set FIELD_OBJ_GFX_SIDNEY,                    121
	.set FIELD_OBJ_GFX_PHOEBE,                    122
	.set FIELD_OBJ_GFX_GLACIA,                    123
	.set FIELD_OBJ_GFX_DRAKE,                     124
	.set FIELD_OBJ_GFX_ROXANNE,                   125
	.set FIELD_OBJ_GFX_BRAWLY,                    126
	.set FIELD_OBJ_GFX_WATTSON,                   127
	.set FIELD_OBJ_GFX_FLANNERY,                  128
	.set FIELD_OBJ_GFX_NORMAN,                    129
	.set FIELD_OBJ_GFX_WINONA,                    130
	.set FIELD_OBJ_GFX_LIZA,                      131
	.set FIELD_OBJ_GFX_TATE,                      132
	.set FIELD_OBJ_GFX_WALLACE,                   133
	.set FIELD_OBJ_GFX_STEVEN,                    134
	.set FIELD_OBJ_GFX_WALLY,                     135
	.set FIELD_OBJ_GFX_RUBY_SAPPHIRE_LITTLE_BOY,  136
	.set FIELD_OBJ_GFX_BRENDAN_FISHING,           137
	.set FIELD_OBJ_GFX_MAY_FISHING,               138
	.set FIELD_OBJ_GFX_HOT_SPRINGS_OLD_WOMAN,     139
	.set FIELD_OBJ_GFX_SS_TIDAL,                  140
	.set FIELD_OBJ_GFX_SUBMARINE_SHADOW,          141
	.set FIELD_OBJ_GFX_PICHU_DOLL,                142
	.set FIELD_OBJ_GFX_PIKACHU_DOLL,              143
	.set FIELD_OBJ_GFX_MARILL_DOLL,               144
	.set FIELD_OBJ_GFX_TOGEPI_DOLL,               145
	.set FIELD_OBJ_GFX_CYNDAQUIL_DOLL,            146
	.set FIELD_OBJ_GFX_CHIKORITA_DOLL,            147
	.set FIELD_OBJ_GFX_TOTODILE_DOLL,             148
	.set FIELD_OBJ_GFX_JIGGLYPUFF_DOLL,           149
	.set FIELD_OBJ_GFX_MEOWTH_DOLL,               150
	.set FIELD_OBJ_GFX_CLEFAIRY_DOLL,             151
	.set FIELD_OBJ_GFX_DITTO_DOLL,                152
	.set FIELD_OBJ_GFX_SMOOCHUM_DOLL,             153
	.set FIELD_OBJ_GFX_TREECKO_DOLL,              154
	.set FIELD_OBJ_GFX_TORCHIC_DOLL,              155
	.set FIELD_OBJ_GFX_MUDKIP_DOLL,               156
	.set FIELD_OBJ_GFX_DUSKULL_DOLL,              157
	.set FIELD_OBJ_GFX_WYNAUT_DOLL,               158
	.set FIELD_OBJ_GFX_BALTOY_DOLL,               159
	.set FIELD_OBJ_GFX_KECLEON_DOLL,              160
	.set FIELD_OBJ_GFX_AZURILL_DOLL,              161
	.set FIELD_OBJ_GFX_SKITTY_DOLL,               162
	.set FIELD_OBJ_GFX_SWABLU_DOLL,               163
	.set FIELD_OBJ_GFX_GULPIN_DOLL,               164
	.set FIELD_OBJ_GFX_LOTAD_DOLL,                165
	.set FIELD_OBJ_GFX_SEEDOT_DOLL,               166
	.set FIELD_OBJ_GFX_PIKA_CUSHION,              167
	.set FIELD_OBJ_GFX_ROUND_CUSHION,             168
	.set FIELD_OBJ_GFX_KISS_CUSHION,              169
	.set FIELD_OBJ_GFX_ZIGZAG_CUSHION,            170
	.set FIELD_OBJ_GFX_SPIN_CUSHION,              171
	.set FIELD_OBJ_GFX_DIAMOND_CUSHION,           172
	.set FIELD_OBJ_GFX_BALL_CUSHION,              173
	.set FIELD_OBJ_GFX_GRASS_CUSHION,             174
	.set FIELD_OBJ_GFX_FIRE_CUSHION,              175
	.set FIELD_OBJ_GFX_WATER_CUSHION,             176
	.set FIELD_OBJ_GFX_BIG_SNORLAX_DOLL,          177
	.set FIELD_OBJ_GFX_BIG_RHYDON_DOLL,           178
	.set FIELD_OBJ_GFX_BIG_LAPRAS_DOLL,           179
	.set FIELD_OBJ_GFX_BIG_VENUSAUR_DOLL,         180
	.set FIELD_OBJ_GFX_BIG_CHARIZARD_DOLL,        181
	.set FIELD_OBJ_GFX_BIG_BLASTOISE_DOLL,        182
	.set FIELD_OBJ_GFX_BIG_WAILMER_DOLL,          183
	.set FIELD_OBJ_GFX_BIG_REGIROCK_DOLL,         184
	.set FIELD_OBJ_GFX_BIG_REGICE_DOLL,           185
	.set FIELD_OBJ_GFX_BIG_REGISTEEL_DOLL,        186
	.set FIELD_OBJ_GFX_LATIAS,                    187
	.set FIELD_OBJ_GFX_LATIOS,                    188
	.set FIELD_OBJ_GFX_BOY_5,                     189
	.set FIELD_OBJ_GFX_CONTEST_OLD_MAN,           190
	.set FIELD_OBJ_GFX_BRENDAN_WATERING,          191
	.set FIELD_OBJ_GFX_MAY_WATERING,              192
	.set FIELD_OBJ_GFX_BRENDAN_UNKNOWN,           193
	.set FIELD_OBJ_GFX_MAY_UNKNOWN,               194
	.set FIELD_OBJ_GFX_ARCHIE,                    195
	.set FIELD_OBJ_GFX_MAXIE,                     196
	.set FIELD_OBJ_GFX_KYOGRE_1,                  197
	.set FIELD_OBJ_GFX_GROUDON_1,                 198
	.set FIELD_OBJ_GFX_FOSSIL,                    199
	.set FIELD_OBJ_GFX_REGIROCK,                  200
	.set FIELD_OBJ_GFX_REGICE,                    201
	.set FIELD_OBJ_GFX_REGISTEEL,                 202
	.set FIELD_OBJ_GFX_SKITTY,                    203
	.set FIELD_OBJ_GFX_KECLEON_1,                 204
	.set FIELD_OBJ_GFX_KYOGRE_2,                  205
	.set FIELD_OBJ_GFX_GROUDON_2,                 206
	.set FIELD_OBJ_GFX_RAYQUAZA_2,                207
	.set FIELD_OBJ_GFX_ZIGZAGOON,                 208
	.set FIELD_OBJ_GFX_PIKACHU,                   209
	.set FIELD_OBJ_GFX_AZUMARILL,                 210
	.set FIELD_OBJ_GFX_WINGULL,                   211
	.set FIELD_OBJ_GFX_KECLEON_2,                 212
	.set FIELD_OBJ_GFX_TUBER_M_SWIMMING,          213
	.set FIELD_OBJ_GFX_AZURILL,                   214
	.set FIELD_OBJ_GFX_MOM,                       215
	.set FIELD_OBJ_GFX_LINK_BRENDAN,              216
	.set FIELD_OBJ_GFX_LINK_MAY,                  217
	.set FIELD_OBJ_GFX_JUAN,                      218
	.set FIELD_OBJ_GFX_SCOTT,                     219
	.set FIELD_OBJ_GFX_POOCHYENA,                 220
	.set FIELD_OBJ_GFX_KYOGRE_3,                  221
	.set FIELD_OBJ_GFX_GROUDON_3,                 222
	.set FIELD_OBJ_GFX_MYSTERY_EVENT_DELIVERYMAN, 223
	.set FIELD_OBJ_GFX_STATUE,                    224
	.set FIELD_OBJ_GFX_KIRLIA,                    225
	.set FIELD_OBJ_GFX_DUSCLOPS,                  226
	.set FIELD_OBJ_GFX_UNION_ROOM_ATTENDANT,      227
	.set FIELD_OBJ_GFX_SUDOWOODO,                 228
	.set FIELD_OBJ_GFX_MEW,                       229
	.set FIELD_OBJ_GFX_RED,                       230
	.set FIELD_OBJ_GFX_LEAF,                      231
	.set FIELD_OBJ_GFX_DEOXYS,                    232
	.set FIELD_OBJ_GFX_BIRTH_ISLAND_STONE,        233
	.set FIELD_OBJ_GFX_BRANDON,                   234
	.set FIELD_OBJ_GFX_RUBY_SAPPHIRE_BRENDAN,     235
	.set FIELD_OBJ_GFX_RUBY_SAPPHIRE_MAY,         236
	.set FIELD_OBJ_GFX_LUGIA,                     237
	.set FIELD_OBJ_GFX_HO_OH,                     238

	.set SHADOW_SIZE_S,  0
	.set SHADOW_SIZE_M,  1
	.set SHADOW_SIZE_L,  2
	.set SHADOW_SIZE_XL, 3

	.set F_INANIMATE,                       1 << 6
	.set F_DISABLE_REFLECTION_PALETTE_LOAD, 1 << 7

	.set TRACKS_NONE,      0
	.set TRACKS_FOOT,      1
	.set TRACKS_BIKE_TIRE, 2
