SootopolisCity_House5_MapScripts::
	.byte 0

SootopolisCity_House5_EventScript_Maniac::
	msgbox SootopolisCity_House5_Text_SootopolisMtPyreConnection, MSGBOX_NPC
	end

SootopolisCity_House5_EventScript_Girl::
	msgbox SootopolisCity_House5_Text_BrotherUsedToStudySea, MSGBOX_NPC
	end

SootopolisCity_House5_Text_SootopolisMtPyreConnection:
	.string "Il semblerait qu’il existe un rapport\n"
	.string "entre ATALANOPOLIS et le MONT MEMORIA.\p"
	.string "Avec mes amis, on a fait des recherches\n"
	.string "à ce sujet au labo où je travaillais.$"

SootopolisCity_House5_Text_BrotherUsedToStudySea:
	.string "Mon grand frère étudie la mer.$"

