
MossdeepCity_House1_Text_HmmYourPokemon:
	.string "Hum!\n"
	.string "Ton {STR_VAR_1}…$"

MossdeepCity_House1_Text_ItLikesXPokeblocks:
	.string "Un {STR_VAR_1}, il aime bien ça,\n"
	.string "n’est-ce pas?\p"
	.string "Je suis catégorique là-dessus! Il aime\n"
	.string "beaucoup le {STR_VAR_1}.$"

MossdeepCity_House1_Text_DoesntLikeOrDislikePokeblocks:
	.string "Il semble insensible aux différents\n"
	.string "goûts des {POKEBLOCK}S.$"

MossdeepCity_House1_Text_HusbandCanTellPokeblockMonLikes:
	.string "En un clin d’œil, mon mari peut dire\n"
	.string "quels {POKEBLOCK}S un POKéMON aime.$"
