
MossdeepCity_House1_Text_HmmYourPokemon:
	.string "Mhmm!\n"
	.string "Il tuo {STR_VAR_1}…$"

MossdeepCity_House1_Text_ItLikesXPokeblocks:
	.string "Va matto per la {STR_VAR_1},\n"
	.string "giusto?\p"
	.string "Anzi, non ho dubbi! Sicuramente sarà\n"
	.string "un patito della {STR_VAR_1}!$"

MossdeepCity_House1_Text_DoesntLikeOrDislikePokeblocks:
	.string "Non sembra prediligere nessuna\n"
	.string "{POKEMELLA}.$"

MossdeepCity_House1_Text_HusbandCanTellPokeblockMonLikes:
	.string "Mio marito con uno sguardo capisce\n"
	.string "quale {POKEMELLA} prediliga un POKéMON.$"
