
BattleFrontier_BattlePyramidLobby_Text_WelcomeToBattlePyramid:
	.string "Bienvenue à la PYRAMIDE DE COMBAT!\p"
	.string "Ici, nous mettons à l’épreuve\n"
	.string "le courage des DRESSEURS!\p"
	.string "Je serai votre guide pour le\n"
	.string "COMBAT QUETE.$"

BattleFrontier_BattlePyramidLobby_Text_EmbarkOnChallenge:
	.string "Avez-vous le courage de relever le\n"
	.string "défi du COMBAT QUETE?$"

BattleFrontier_BattlePyramidLobby_Text_AwaitFutureChallenge:
	.string "Nous attendrons votre prochain défi\n"
	.string "avec impatience.$"

BattleFrontier_BattlePyramidLobby_Text_ExplainBattlePyramid:
	.string "Lors du COMBAT QUETE, vous devez\n"
	.string "explorer la PYRAMIDE et essayer d’en\l"
	.string "atteindre le sommet.\p"
	.string "Chacun des sept niveaux de la PYRAMIDE\n"
	.string "est un labyrinthe. Ils sont truffés de\l"
	.string "DRESSEURS et de POKéMON sauvages.\p"
	.string "Vous devez y entrer avec trois POKéMON\n"
	.string "ne portant aucun objet.\p"
	.string "On vous fournira un SAC DE COMBAT\n"
	.string "pour y mettre les objets.\p"
	.string "Si vous échouez, vous perdez les objets\n"
	.string "placés dans le SAC DE COMBAT.\p"
	.string "Si vous voulez interrompre le défi,\n"
	.string "sélectionnez “REPOS”\l"
	.string "et sauvegardez la partie.\p"
	.string "Assurez-vous de bien sauvegarder, ou\n"
	.string "vous ne pourrez pas reprendre le défi.$"

BattleFrontier_BattlePyramidLobby_Text_WhichLevelMode:
	.string "La PYRAMIDE offre deux possibilités:\n"
	.string "niveau 50 et niveau libre.\l"
	.string "Que choisissez-vous?$"

BattleFrontier_BattlePyramidLobby_Text_SelectThreeMons:
	.string "Très bien. Choisissez les trois POKéMON\n"
	.string "qui vont vous accompagner.$"

BattleFrontier_BattlePyramidLobby_Text_NotEnoughValidMonsLvOpen:
	.string "Il y a un petit problème!\p"
	.string "Vous n’avez pas trois POKéMON\n"
	.string "aptes à participer.\p"
	.string "Souvenez-vous que vous devez leur\n"
	.string "reprendre les objets qu’ils portent.\p"
	.string "Les OEUFS{STR_VAR_1} inaptes au combat.\p"
	.string "On en reparlera quand vous aurez\n"
	.string "ce qu’il faut.$"

BattleFrontier_BattlePyramidLobby_Text_NotEnoughValidMonsLv50:
	.string "Il y a un petit problème!\p"
	.string "Vous n’avez pas trois POKéMON\n"
	.string "aptes à participer.\p"
	.string "Il vous faut trois POKéMON différents\n"
	.string "de niveau 50 ou moins pour participer.\p"
	.string "Souvenez-vous que vous devez leur\n"
	.string "reprendre les objets qu’ils portent.\p"
	.string "Les OEUFS{STR_VAR_1} inaptes au combat.\p"
	.string "On en reparlera quand vous aurez\n"
	.string "ce qu’il faut.$"

BattleFrontier_BattlePyramidLobby_Text_OkayToSaveBeforeChallenge:
	.string "Pour accéder à la PYRAMIDE DE COMBAT,\n"
	.string "votre partie doit être sauvegardée. OK?$"

BattleFrontier_BattlePyramidLobby_Text_ShowYouIntoPyramid:
	.string "Très bien. Je vais vous accompagner\n"
	.string "dans la PYRAMIDE DE COMBAT.$"

BattleFrontier_BattlePyramidLobby_Text_WeWillHoldBagForSafekeeping:
	.string "Nous gardons votre SAC pendant votre\n"
	.string "exploration, {PLAYER}.$"

BattleFrontier_BattlePyramidLobby_Text_PleaseTakePreviousBattleBag:
	.string "Tenez, prenez votre ancien SAC DE\n"
	.string "COMBAT en échange.$"

BattleFrontier_BattlePyramidLobby_Text_PleaseTakeThisBattleBag:
	.string "Tenez, prenez ce SAC DE\n"
	.string "COMBAT en échange.$"

BattleFrontier_BattlePyramidLobby_Text_ExchangedBagForBattleBag:
	.string "{PLAYER} a échangé le SAC avec le\n"
	.string "SAC DE COMBAT.$"

BattleFrontier_BattlePyramidLobby_Text_StepOnFloorPanel:
	.string "Ce type de plaque permet d’être\n"
	.string "transporté au niveau supérieur de\l"
	.string "la PYRAMIDE.\p"
	.string "J’espère que tout va bien se passer\n"
	.string "pour vous!$"

BattleFrontier_BattlePyramidLobby_Text_DidntSaveBeforeQuittingTakeBag:
	.string "Il y a un gros problème!\p"
	.string "Vous n’avez pas sauvegardé avant de\n"
	.string "quitter votre dernier défi.\p"
	.string "Dans ce cas, c’est la disqualification.\n"
	.string "C’est dommage!\p"
	.string "Je vous rends votre SAC, tenez.\p"
	.string "{PLAYER} a récupéré le SAC.$"

BattleFrontier_BattlePyramidLobby_Text_YouveConqueredPyramid:
	.string "Quel plaisir de vous revoir!\p"
	.string "Vous avez conquis la PYRAMIDE!\n"
	.string "Ce fut splendide!$"

BattleFrontier_BattlePyramidLobby_Text_MonHoldingItemCannotTake:
	.string "Il y a un petit problème!\p"
	.string "Au moins un de vos POKéMON porte\n"
	.string "un objet.\p"
	.string "Malheureusement, les objets obtenus\n"
	.string "dans la PYRAMIDE doivent rester ici.$"

BattleFrontier_BattlePyramidLobby_Text_HeldItemsMovedToBag:
	.string "Tous les objets vont être placés dans\n"
	.string "votre SAC DE COMBAT, {PLAYER}.$"

BattleFrontier_BattlePyramidLobby_Text_BagCannotHoldPickItemsToKeep:
	.string "Le SAC DE COMBAT ne peut pas contenir\n"
	.string "tous vos objets, je suis désolé.\p"
	.string "Choisissez les objets à laisser dans le\n"
	.string "SAC DE COMBAT et avec vos POKéMON.$"

BattleFrontier_BattlePyramidLobby_Text_LeastOneMonHoldingItem:
	.string "Au moins un POKéMON porte encore\n"
	.string "un objet.$"

BattleFrontier_BattlePyramidLobby_Text_PickItemsToKeep:
	.string "Choisissez les objets à laisser dans le\n"
	.string "SAC DE COMBAT et avec vos POKéMON.$"

@ Unused
BattleFrontier_BattlePyramidLobby_Text_ReturnedEverythingMonsHeld:
	.string "{PLAYER} returned everything that\n"
	.string "the POKéMON held.$"

BattleFrontier_BattlePyramidLobby_Text_UsedBattleBagWillBeKept:
	.string "Votre SAC DE COMBAT va être conservé\n"
	.string "pour votre prochain défi.\p"
	.string "{PLAYER} a rendu le SAC DE COMBAT et a\n"
	.string "repris le SAC.$"

BattleFrontier_BattlePyramidLobby_Text_RecordResultsWait:
	.string "Votre résultat va être sauvegardé.\n"
	.string "Veuillez patienter.$"

@ Unused
BattleFrontier_BattlePyramidLobby_Text_ForConqueringPyramidTakeThis:
	.string "As a memento for conquering\n"
	.string "the BATTLE PYRAMID, please take this.$"

@ Unused
BattleFrontier_BattlePyramidLobby_Text_ReceivedPrizeItem:
	.string "{PLAYER} received the prize\n"
	.string "{STR_VAR_1}.$"

@ Unused
BattleFrontier_BattlePyramidLobby_Text_BagIsFull:
	.string "…Ah…\n"
	.string "Your BAG appears to be filled.\p"
	.string "Please return after you’ve organized\n"
	.string "your BAG’s contents.$"

BattleFrontier_BattlePyramidLobby_Text_DisappointingHereIsBag:
	.string "Que c’est décevant…\p"
	.string "Voici votre SAC.\p"
	.string "{PLAYER} a récupéré le SAC.$"

BattleFrontier_BattlePyramidLobby_Text_LookForwardToNextChallenge:
	.string "Nous attendrons votre prochain défi\n"
	.string "avec impatience.$"

@ Unused
BattleFrontier_BattlePyramidLobby_Text_HereIsPrize:
	.string "We have been looking forward to\n"
	.string "your arrival!\p"
	.string "Here is your prize for conquering\n"
	.string "the PYRAMID.$"

BattleFrontier_BattlePyramidLobby_Text_TellYouWhatMisfortunesAwait:
	.string "Bienvenue à toi…\p"
	.string "Je serais ravie de te dire les malheurs\n"
	.string "qui t’attendent dans la PYRAMIDE…$"

BattleFrontier_BattlePyramidLobby_Text_Aah:
	.string "… … … … … …\n"
	.string "… … … … … …\p"
	.string "… … … … … …\n"
	.string "Ah!$"

BattleFrontier_BattlePyramidLobby_Text_HintParalysis:
	.string "Je vois une pluie d’étincelles…\p"
	.string "Dans cette pluie, je vois tes POKéMON\n"
	.string "lutter contre la paralysie…$"

BattleFrontier_BattlePyramidLobby_Text_HintPoison:
	.string "Je vois du poison…\p"
	.string "Oui, tes POKéMON souffrent d’un\n"
	.string "empoisonnement…$"

BattleFrontier_BattlePyramidLobby_Text_HintBurn:
	.string "Je vois des flammes rouges…\p"
	.string "Tes POKéMON souffrent de\n"
	.string "brûlures…$"

BattleFrontier_BattlePyramidLobby_Text_HintPPWaste:
	.string "Je ressens la pression d’une fureur\n"
	.string "incontrôlable…\p"
	.string "C’est une malédiction…\p"
	.string "Et je vois les POINTS DE POUVOIR de\n"
	.string "tes POKéMON se faire drainer.\l"
	.string "Ils sont obligés d’utiliser LUTTE…$"

BattleFrontier_BattlePyramidLobby_Text_HintLevitate:
	.string "Je vois des POKéMON voler à haute\n"
	.string "altitude…\p"
	.string "Tes POKéMON sont frustrés face à\n"
	.string "l’échec de leurs capacités de type SOL…$"

BattleFrontier_BattlePyramidLobby_Text_HintTrapAbility:
	.string "Je sens une énergie incroyable\n"
	.string "provenant du sol…\p"
	.string "Je vois tes POKéMON incapables\n"
	.string "d’échapper à son emprise…$"

BattleFrontier_BattlePyramidLobby_Text_HintIce:
	.string "Je vois des POKéMON de type GLACE…\p"
	.string "Tes POKéMON luttent contre le froid\n"
	.string "mordant de la glace…$"

BattleFrontier_BattlePyramidLobby_Text_HintExplosion:
	.string "Je vois une myriade de capacités\n"
	.string "dangereuses pour celui qui les utilise…\p"
	.string "Tes POKéMON en souffrent…$"

BattleFrontier_BattlePyramidLobby_Text_HintPsychic:
	.string "Je vois des POKéMON de type PSY…\p"
	.string "Tes POKéMON sont aux prises avec\n"
	.string "des capacités de type PSY…$"

BattleFrontier_BattlePyramidLobby_Text_HintRock:
	.string "Je vois des POKéMON de type ROCHE…\p"
	.string "Et je vois tes POKéMON souffrir à cause\n"
	.string "de capacités de type ROCHE…$"

BattleFrontier_BattlePyramidLobby_Text_HintFighting:
	.string "Je vois des POKéMON de type COMBAT…\p"
	.string "Tes POKéMON sont assaillis d’attaques\n"
	.string "de type COMBAT…$"

BattleFrontier_BattlePyramidLobby_Text_HintWeather:
	.string "DANSE PLUIE… ZENITH…\n"
	.string "TEMPETESABLE… GRELE…\p"
	.string "Je vois des POKéMON qui se renforcent\n"
	.string "avec les conditions climatiques…\p"
	.string "Tes POKéMON sont perdus, les\n"
	.string "capacités sont de tous types…$"

BattleFrontier_BattlePyramidLobby_Text_HintBug:
	.string "Je vois des POKéMON de type INSECTE…\p"
	.string "Tes POKéMON subissent des attaques\n"
	.string "de différentes sortes…$"

BattleFrontier_BattlePyramidLobby_Text_HintDark:
	.string "Je vois des POKéMON de type TENEBRES…\p"
	.string "Tes POKéMON sont aux prises avec\n"
	.string "des capacités de type TENEBRES…$"

BattleFrontier_BattlePyramidLobby_Text_HintWater:
	.string "Je vois des POKéMON de type EAU…\p"
	.string "Tes POKéMON sont aux prises avec\n"
	.string "des capacités de type EAU…$"

BattleFrontier_BattlePyramidLobby_Text_HintGhost:
	.string "Je vois des POKéMON de type SPECTRE…\p"
	.string "Tes POKéMON sont aux prises avec des\n"
	.string "capacités de type SPECTRE…$"

BattleFrontier_BattlePyramidLobby_Text_HintSteel:
	.string "Je vois des POKéMON de type ACIER…\p"
	.string "Tes POKéMON sont aux prises avec des\n"
	.string "capacités très puissantes…$"

BattleFrontier_BattlePyramidLobby_Text_HintFlyingDragon:
	.string "Je vois des POKéMON volants…\p"
	.string "Tes POKéMON sont aux prises avec des\n"
	.string "capacités très puissantes…$"

BattleFrontier_BattlePyramidLobby_Text_HintStoneEvolve:
	.string "Je vois ceux qui dérivent du pouvoir\n"
	.string "de la pierre…\p"
	.string "Je sens le feu, l’eau et l’électricité…\p"
	.string "Tes POKéMON doivent affronter ces\n"
	.string "trois pouvoirs…$"

BattleFrontier_BattlePyramidLobby_Text_HintNormal:
	.string "Je vois des POKéMON de type NORMAL…\p"
	.string "Tes POKéMON sont aux prises avec des\n"
	.string "capacités très puissantes…$"

BattleFrontier_BattlePyramidLobby_Text_BelieveMyFortunesOrNot:
	.string "Que tu me croies ou non n’a aucune\n"
	.string "importance…\p"
	.string "Tu as le pouvoir de modifier ton avenir…\n"
	.string "Je te souhaite de réussir…$"

BattleFrontier_BattlePyramidLobby_Text_TrainersNoticeRunning:
	.string "J’ai un secret pour toi.\p"
	.string "Si tu cours, tu risques d’attirer\n"
	.string "l’attention des DRESSEURS et ils\l"
	.string "voudront se battre contre toi.\p"
	.string "Pour les éviter, il faut se faire discret\n"
	.string "et passer lentement à côté d’eux.$"

BattleFrontier_BattlePyramidLobby_Text_LostLotOfItems:
	.string "Ahhhhh!\p"
	.string "J’avais plein d’objets, mais ils se sont\n"
	.string "envolés quand j’ai perdu!\p"
	.string "Ouin!!!!!!!!!!!!$"

BattleFrontier_BattlePyramidLobby_Text_YouveDefeatedPyramidKing:
	.string "Vous voilà de retour!\n"
	.string "Vous avez réussi l’impossible!\p"
	.string "Vous avez battu le ROI PYRAMIDE\n"
	.string "et conquis la PYRAMIDE DE COMBAT!$"

BattleFrontier_BattlePyramidLobby_Text_GiveYouTheseBattlePoints:
	.string "Jeune intrépide!\n"
	.string "Votre courage va être récompensé\l"
	.string "par des POINTS DE COMBAT!$"

BattleFrontier_BattlePyramidLobby_Text_RulesAreListed:
	.string "Règles du COMBAT QUETE.$"

BattleFrontier_BattlePyramidLobby_Text_ReadWhichHeading:
	.string "Quel chapitre voulez-vous lire?$"

BattleFrontier_BattlePyramidLobby_Text_ExplainMonRules:
	.string "Une fois la PYRAMIDE conquise,\n"
	.string "les POKéMON sauvages qui s’y trouvent\l"
	.string "sont remplacés par d’autres.\p"
	.string "Il faut en profiter pour les observer\n"
	.string "et apprendre à connaître de\l"
	.string "nouveaux POKéMON sauvages.$"

BattleFrontier_BattlePyramidLobby_Text_ExplainTrainerRules:
	.string "Des DRESSEURS vous attendent à\n"
	.string "l’intérieur de la PYRAMIDE.\p"
	.string "A chaque niveau, il y a jusqu’à\n"
	.string "huit DRESSEURS.\p"
	.string "Quand vous en battez un, vous\n"
	.string "recevez une information importante.$"

BattleFrontier_BattlePyramidLobby_Text_ExplainMazeRules:
	.string "Les labyrinthes de la PYRAMIDE\n"
	.string "changent à chaque fois que vous\l"
	.string "y entrez.\p"
	.string "Les labyrinthes sont très peu éclairés.\n"
	.string "Vous devez avancer avec précaution.\p"
	.string "Quand vous battez un POKéMON sauvage\n"
	.string "ou un DRESSEUR, la lumière s’intensifie.$"

BattleFrontier_BattlePyramidLobby_Text_ExplainBagRules:
	.string "Le SAC DE COMBAT sera votre SAC\n"
	.string "dans la PYRAMIDE.\p"
	.string "Il y a deux SACS DE COMBAT: un pour\n"
	.string "niveau 50 et un pour niveau libre.\p"
	.string "Chacun peut contenir 99 exemplaires\n"
	.string "de dix types d’objets différents.\p"
	.string "Le contenu du SAC DE COMBAT est\n"
	.string "perdu si vous échouez.$"
