
MossdeepCity_SpaceCenter_1F_Text_RocketLaunchImminent:
	.string "Le lancement de la fusée est imminent!$"

MossdeepCity_SpaceCenter_1F_Text_SuccessfulLaunchNumber:
	.string "La fusée a décollé en toute sécurité!\n"
	.string "Lancement nº {STR_VAR_1} réussi!$"

MossdeepCity_SpaceCenter_1F_Text_HaywireButRocketLaunchImminent:
	.string "Je sais que tout est un peu sens\n"
	.string "dessus dessous en ce moment…\p"
	.string "Mais le lancement de la fusée\n"
	.string "est imminent!$"

MossdeepCity_SpaceCenter_1F_Text_HaywireButSuccessfulLaunchNumber:
	.string "Je sais que tout est un peu sens\n"
	.string "dessus dessous en ce moment…\p"
	.string "Mais la fusée a décollé sans problème!\n"
	.string "Lancement nº {STR_VAR_1} réussi!$"

MossdeepCity_SpaceCenter_1F_Text_RocketLaunchDemandsPerfection:
	.string "Lancer une fusée exige la perfection.\n"
	.string "L’erreur n’est pas permise.\p"
	.string "Même si tout est juste à 99%,\n"
	.string "ça ne sert à rien si le dernier 1%\l"
	.string "n’est pas correct.\p"
	.string "Malgré ça, on essaie toujours.\n"
	.string "Pourquoi? C’est un rêve sans fin.$"

MossdeepCity_SpaceCenter_1F_Text_MagmaHaveSightsOnSpaceCenter:
	.string "Ces types sont intéressés par le\n"
	.string "CENTRE SPATIAL.\p"
	.string "Mais on ne peut pas se permettre\n"
	.string "de les laisser gêner le lancement\l"
	.string "de notre fusée.$"

MossdeepCity_SpaceCenter_1F_Text_FoundThisYouCanHaveIt:
	.string "Je faisais un petit tour sur la plage,\n"
	.string "quand j’ai trouvé ça.\p"
	.string "Ça ne me servira pas, alors autant\n"
	.string "que ce soit toi qui l’aies.$"

MossdeepCity_SpaceCenter_1F_Text_HoennFamousForMeteorShowers:
	.string "La région de HOENN a longtemps été\n"
	.string "réputée pour ses pluies de météorites.$"

MossdeepCity_SpaceCenter_1F_Text_MagmaCantStealFuelTakeThis:
	.string "On ne peut pas laisser la TEAM MAGMA\n"
	.string "voler le carburant pour la fusée.\p"
	.string "Oh, au fait, j’ai trouvé cette pierre sur\n"
	.string "la plage. Je te la donne si tu veux.$"

MossdeepCity_SpaceCenter_1F_Text_CantStrollOnBeachWithMagma:
	.string "Avec la TEAM MAGMA dans le coin,\n"
	.string "les promenades sur la plage ne sont\l"
	.string "plus vraiment sûres.$"

MossdeepCity_SpaceCenter_1F_Text_DidPokemonComeFromSpace:
	.string "Certains prétendent que les POKéMON\n"
	.string "viennent de l’espace. Est-ce possible?$"

MossdeepCity_SpaceCenter_1F_Text_AquaShouldBeatMagma:
	.string "La TEAM AQUA devrait s’occuper de\n"
	.string "la TEAM MAGMA!\p"
	.string "Mais s’ils font ça, ils risquent de\n"
	.string "croire qu’ils ont tous les droits, non?$"

MossdeepCity_SpaceCenter_1F_Text_RocketsBoggleMyMind:
	.string "Un gigantesque bloc de métal qui\n"
	.string "franchit l’atmosphère et flotte dans\l"
	.string "l’espace…\p"
	.string "Ça laisse rêveur!$"

MossdeepCity_SpaceCenter_1F_Text_MagmaWantsToSpoilMyDream:
	.string "Un gigantesque bloc de métal qui\n"
	.string "franchit l’atmosphère et flotte dans\l"
	.string "l’espace…\p"
	.string "Mais la TEAM MAGMA veut gâcher mon\n"
	.string "rêve de voir la fusée décoller!\p"
	.string "Je ne les laisserai pas faire!$"

MossdeepCity_SpaceCenter_1F_Text_StevenMagmaCantBeAllowedToTakeFuel:
	.string "PIERRE: {PLAYER}{KUN}, as-tu déjà lu cette\n"
	.string "annonce?\p"
	.string "La TEAM MAGMA veut s’approprier le\n"
	.string "carburant destiné à la fusée.\p"
	.string "Je ne sais pas pourquoi ils en ont\n"
	.string "besoin, mais ils ne peuvent pas faire ça.\p"
	.string "Je vais rester ici et garder l’œil ouvert\n"
	.string "encore quelque temps.\p"
	.string "Tu devrais en profiter pour aller faire\n"
	.string "un tour en ville.$"

MossdeepCity_SpaceCenter_1F_Text_Grunt3Intro:
	.string "Comme promis, nous sommes venus\n"
	.string "pour voler le carburant de la fusée.$"

MossdeepCity_SpaceCenter_1F_Text_Grunt3Defeat:
	.string "J’ai dû manquer de carburant…$"

MossdeepCity_SpaceCenter_1F_Text_Grunt3PostBattle:
	.string "Ne prends pas la grosse tête juste\n"
	.string "pour m’avoir battue.$"

MossdeepCity_SpaceCenter_1F_Text_Grunt1Intro:
	.string "On t’avait dit de rester en dehors!\n"
	.string "Rien ne doit gêner nos plans.$"

MossdeepCity_SpaceCenter_1F_Text_Grunt1Defeat:
	.string "Grrr… Je n’aurais pas dû me\n"
	.string "battre à la loyale!$"

MossdeepCity_SpaceCenter_1F_Text_Grunt1PostBattle:
	.string "OK, j’ai compris! La prochaine fois, on\n"
	.string "viendra sans prévenir personne.$"

MossdeepCity_SpaceCenter_1F_Text_Grunt4Intro:
	.string "Le carburant que le CENTRE SPATIAL\n"
	.string "garde pour la fusée…\p"
	.string "C’est ça qui nous intéresse, on n’en\n"
	.string "laissera pas une goutte.$"

MossdeepCity_SpaceCenter_1F_Text_Grunt4Defeat:
	.string "Je retire ce que j’ai dit…\n"
	.string "Un jerrycan suffira…$"

MossdeepCity_SpaceCenter_1F_Text_Grunt4PostBattle:
	.string "Ce que nous voulons faire avec\n"
	.string "le carburant?\p"
	.string "Comment je le saurais?\n"
	.string "Je ne suis qu’un sbire!$"

MossdeepCity_SpaceCenter_1F_Text_Grunt2Intro:
	.string "Notre chef a dit que personne ne\n"
	.string "devait passer… PERSONNE!$"

MossdeepCity_SpaceCenter_1F_Text_Grunt2Defeat:
	.string "Aille aïe aïe!$"

MossdeepCity_SpaceCenter_1F_Text_Grunt2PostBattle:
	.string "S’il te plaît, dis à mon chef que je n’ai\n"
	.string "pas abandonné mon poste.\p"
	.string "Dis-lui que je suis resté jusqu’au bout…$"

MossdeepCity_SpaceCenter_1F_Text_MagmaIntentToStealNotice:
	.string "Ceci est une…\n"
	.string "déclaration d’intention de vol?\p"
	.string "“A l’intention du personnel du\n"
	.string "CENTRE SPATIAL: Comment ça va?\l"
	.string "Nous ça va plutôt pas mal.\p"
	.string "“Nous passerons bientôt vous\n"
	.string "piquer le carburant pour la fusée.\p"
	.string "“N’essayez pas de nous arrêter.\n"
	.string "On le prendra quand même!\p"
	.string "“Pour l’expansion de la terre!\n"
	.string "                                          TEAM MAGMA”$"
