Underwater_SealedChamber: @ 8484668
	.4byte Underwater_SealedChamber_Layout
	.4byte Underwater_SealedChamber_MapEvents
	.4byte Underwater_SealedChamber_MapScripts
	.4byte 0x0
	.2byte MUS_DEEPDEEP
	.2byte 283
	.byte MAPSEC_UNDERWATER_SEALED_CHAMBER
	.byte 0
	.byte WEATHER_BUBBLES
	.byte MAP_TYPE_UNDERWATER
	.2byte 0
	map_header_flags allow_bike=1, allow_escape_rope=0, allow_run=1, show_map_name=1
	.byte MAP_BATTLE_SCENE_NORMAL

