
LilycoveCity_LilycoveMuseum_2F_Text_ThisIsExhibitHall:
	.string "Notre salle d’œuvres contemporaines!$"

LilycoveCity_LilycoveMuseum_2F_Text_ExplainExhibitHall:
	.string "Comme il est facile de le constater, il\n"
	.string "n’y a pas un seul tableau exposé.\p"
	.string "Je ne souhaite pas exposer d’œuvres\n"
	.string "dites “classiques” ici.\p"
	.string "Les œuvres de ce type ont déjà leur\n"
	.string "place au rez-de-chaussée.\p"
	.string "Mon désir est d’exposer des œuvres\n"
	.string "qui se distinguent de l’art classique.\p"
	.string "L’art, après tout, ne se limite pas\n"
	.string "aux anciennes œuvres célèbres!\p"
	.string "Cette salle, je désire l’emplir…\p"
	.string "d’œuvres modernes et pleines de vie\n"
	.string "représentant des POKéMON prêts à\l"
	.string "s’élancer dans une vie heureuse!$"

LilycoveCity_LilycoveMuseum_2F_Text_PleaseObtainPaintingsForExhibit:
	.string "Je m’excuse. Je n’avais pas l’intention\n"
	.string "de monopoliser la conversation.\p"
	.string "Tu es jeune et as déjà beaucoup\n"
	.string "voyagé…\p"
	.string "Tu as dû voir des POKéMON pleins\n"
	.string "de vie et des œuvres les dépeignant.\p"
	.string "Si tu découvrais une telle œuvre, nous\n"
	.string "te serions reconnaissants de bien\l"
	.string "vouloir obtenir la permission de\l"
	.string "l’artiste pour l’exposer ici.$"

LilycoveCity_LilycoveMuseum_2F_Text_WishToFillExhibit:
	.string "J’aimerais emplir cette salle de\n"
	.string "tableaux modernes et pleins de\l"
	.string "vie représentant des POKéMON.$"

LilycoveCity_LilycoveMuseum_2F_Text_ThanksAddedNewPainting:
	.string "Merci. Grâce à toi, nous avons ajouté\n"
	.string "un nouveau tableau à notre collection!\p"
	.string "Il paraît qu’il représente ton POKéMON.\n"
	.string "Vraiment magnifique!\p"
	.string "Merci beaucoup!$"

LilycoveCity_LilycoveMuseum_2F_Text_ItsYouPlayer:
	.string "Ah, c’est toi!\n"
	.string "{PLAYER}!$"

LilycoveCity_LilycoveMuseum_2F_Text_PaintingsAttractedMoreGuests:
	.string "N’est-ce pas fabuleux?\n"
	.string "Cette collection de tableaux!\p"
	.string "Tous parfaits! Il n’y en a pas un\n"
	.string "meilleur que les autres!\p"
	.string "Ces tableaux ont fait augmenter le\n"
	.string "nombre de visiteurs dans notre MUSEE.\p"
	.string "Merci vraiment, {PLAYER}.\n"
	.string "Mon rêve est devenu réalité!$"

LilycoveCity_LilycoveMuseum_2F_Text_TokenOfGratitude:
	.string "Voici un gage de ma reconnaissance.$"

LilycoveCity_LilycoveMuseum_2F_Text_KeepThisForYou:
	.string "Je vais le garder pour toi jusqu’à notre\n"
	.string "prochaine rencontre.$"

LilycoveCity_LilycoveMuseum_2F_Text_HonorToHaveYouVisit:
	.string "Ah, ça fait plaisir de te voir, {PLAYER}!\p"
	.string "Quel honneur que tu trouves le temps de\n"
	.string "nous rendre visite entre tes voyages!\p"
	.string "Détends-toi et apprécie ta venue\n"
	.string "à nos côtés.$"

LilycoveCity_LilycoveMuseum_2F_Text_ItsPinkPictureFrame:
	.string "C’est un cadre à ornements roses.$"

LilycoveCity_LilycoveMuseum_2F_Text_ItsYellowPictureFrame:
	.string "C’est un cadre à ornements jaunes.$"

LilycoveCity_LilycoveMuseum_2F_Text_ItsBluePictureFrame:
	.string "C’est un cadre à ornements bleus.$"

LilycoveCity_LilycoveMuseum_2F_Text_ItsRedPictureFrame:
	.string "C’est un cadre à ornements rouges.$"

LilycoveCity_LilycoveMuseum_2F_Text_ItsGreenPictureFrame:
	.string "C’est un cadre à ornements verts.$"

LilycoveCity_LilycoveMuseum_2F_Text_ItsPaintingOfPokemon:
	.string "C’est un tableau de POKéMON.$"

LilycoveCity_LilycoveMuseum_2F_Text_NewPaintingsSurprisedMe:
	.string "J’ai été absente longtemps. Alors les\n"
	.string "tableaux à l’étage me surprennent.\p"
	.string "J’aimerais bien que quelqu’un peigne\n"
	.string "mes POKéMON comme ça.$"

LilycoveCity_LilycoveMuseum_2F_Text_NewPaintingsRatherAmusing:
	.string "Alors voilà où sont exposés les\n"
	.string "tableaux à thèmes de POKéMON.\p"
	.string "Je vois, ces nouveaux tableaux sont\n"
	.string "effectivement très amusants.$"

LilycoveCity_LilycoveMuseum_2F_Text_ThesePaintingsOfYourPokemon:
	.string "Waouh, c’est vrai? Ces tableaux\n"
	.string "représentent tes POKéMON.\p"
	.string "N’est-ce pas la joie ultime pour un\n"
	.string "DRESSEUR?$"
