
LilycoveCity_LilycoveMuseum_2F_Text_ThisIsExhibitHall:
	.string "Ésta es nuestra sala especial\n"
	.string "de exposiciones.$"

LilycoveCity_LilycoveMuseum_2F_Text_ExplainExhibitHall:
	.string "Como puedes ver, no tenemos expuesto\n"
	.string "ni un solo cuadro…\p"
	.string "Aquí no quiero exponer las obras\n"
	.string "del llamado arte clásico.\p"
	.string "Dichas obras están en nuestra planta\n"
	.string "baja.\p"
	.string "Aquí quiero exponer obras totalmente\n"
	.string "nuevas, diferentes.\p"
	.string "¡El arte no se restringe a las obras\n"
	.string "más famosas de tiempos pasados!\p"
	.string "Esta sala… quisiera llenarla con…\p"
	.string "¡obras modernas y atrevidas sobre\n"
	.string "POKéMON dispuestos a entrar\l"
	.string "en los anales de la historia!$"

LilycoveCity_LilycoveMuseum_2F_Text_PleaseObtainPaintingsForExhibit:
	.string "Discúlpame, no pretendía monopolizar\n"
	.string "la conversación.\p"
	.string "En fin, aunque eres joven, se ve que\n"
	.string "has viajado mucho…\p"
	.string "Seguro que te cruzarás con muchos\n"
	.string "POKéMON y obras que los plasmen.\p"
	.string "Si encontraras algún cuadro de este\n"
	.string "tipo, ¿podrías obtener la autorización\l"
	.string "del artista para exponerlo aquí?$"

LilycoveCity_LilycoveMuseum_2F_Text_WishToFillExhibit:
	.string "Deseo llenar esta sala de exposiciones\n"
	.string "con cuadros modernos y atrevidos\l"
	.string "sobre POKéMON.$"

LilycoveCity_LilycoveMuseum_2F_Text_ThanksAddedNewPainting:
	.string "Gracias a ti, esta pintura formará\n"
	.string "parte de nuestra colección.\p"
	.string "Y además plasma a tu POKéMON.\n"
	.string "¡Es una obra excepcional!\p"
	.string "Muchísimas gracias.$"

LilycoveCity_LilycoveMuseum_2F_Text_ItsYouPlayer:
	.string "¡Ah, eres tú, {PLAYER}!$"

LilycoveCity_LilycoveMuseum_2F_Text_PaintingsAttractedMoreGuests:
	.string "¿No es soberbio?\n"
	.string "¡Qué colección de arte!\p"
	.string "¡Todas impecables!\n"
	.string "¡Todas admirables!\p"
	.string "Estas obras han atraído a muchos\n"
	.string "visitantes a nuestro MUSEO.\p"
	.string "Te lo agradezco de verdad, {PLAYER}.\n"
	.string "¡Es un sueño hecho realidad!$"

LilycoveCity_LilycoveMuseum_2F_Text_TokenOfGratitude:
	.string "Ésta es sólo una muestra de mi gratitud.$"

LilycoveCity_LilycoveMuseum_2F_Text_KeepThisForYou:
	.string "Te lo guardo hasta que vuelvas\n"
	.string "por aquí.$"

LilycoveCity_LilycoveMuseum_2F_Text_HonorToHaveYouVisit:
	.string "¡Qué alegría verte, {PLAYER}!\p"
	.string "Es un honor que tengas tiempo\n"
	.string "para visitarnos a pesar de tus viajes.\p"
	.string "Adelante, descansa y disfruta\n"
	.string "de tu visita.$"

LilycoveCity_LilycoveMuseum_2F_Text_ItsPinkPictureFrame:
	.string "Es un marco con motivos rosas.$"

LilycoveCity_LilycoveMuseum_2F_Text_ItsYellowPictureFrame:
	.string "Es un marco con motivos amarillos.$"

LilycoveCity_LilycoveMuseum_2F_Text_ItsBluePictureFrame:
	.string "Es un marco con motivos azules.$"

LilycoveCity_LilycoveMuseum_2F_Text_ItsRedPictureFrame:
	.string "Es un marco con motivos rojos.$"

LilycoveCity_LilycoveMuseum_2F_Text_ItsGreenPictureFrame:
	.string "Es un marco con motivos verdes.$"

LilycoveCity_LilycoveMuseum_2F_Text_ItsPaintingOfPokemon:
	.string "Es un cuadro de un POKéMON.$"

LilycoveCity_LilycoveMuseum_2F_Text_NewPaintingsSurprisedMe:
	.string "Hacía tiempo que no venía, así que me\n"
	.string "he sorprendido al ver las nuevas obras.\p"
	.string "¡Cuánto me gustaría que alguien\n"
	.string "retratara a mi POKéMON también!$"

LilycoveCity_LilycoveMuseum_2F_Text_NewPaintingsRatherAmusing:
	.string "Ajá, así que aquí es donde exponen\n"
	.string "las nuevas pinturas sobre POKéMON.\p"
	.string "Pues sí, la verdad es que son\n"
	.string "bastante divertidas.$"

LilycoveCity_LilycoveMuseum_2F_Text_ThesePaintingsOfYourPokemon:
	.string "Ahí va, ¿es verdad?\n"
	.string "¿Son cuadros de tus POKéMON?\p"
	.string "Ésa debe de ser la mayor alegría que\n"
	.string "pueden dar a cualquier ENTRENADOR.$"
