
LavaridgeTown_Mart_Text_XSpeedFirstStrike:
	.string "Usa VELOCIDAD X para aumentar la\n"
	.string "VELOCIDAD de tus POKéMON en combate.\p"
	.string "Así podrán asestar el primer golpe.\n"
	.string "¡Es una gran ventaja!$"

LavaridgeTown_Mart_Text_LocalSpecialtyOnMtChimney:
	.string "En la cima del MONTE CENIZO puedes\n"
	.string "comprar una especialidad local.\p"
	.string "Dásela a un POKéMON: ¡se pondrá\n"
	.string "loco de contento!$"
