
Route110_TrickHouseEnd_Text_YouveMadeItToMe:
	.string "Aaargh! Tu m’as retrouvé?\n"
	.string "Hmmm… Tu as l’œil!$"

Route110_TrickHouseEnd_Text_AllNightToPlantTrees:
	.string "Il m’a fallu toute la nuit pour planter\n"
	.string "tous ces arbres…\p"
	.string "Tu es presque aussi balèze que moi,\n"
	.string "à 1, 2, 3, 4, 5, 6 endroits près!$"

Route110_TrickHouseEnd_Text_AllNightToMakeMaze:
	.string "Il m’a fallu toute la nuit pour faire ce\n"
	.string "labyrinthe…\p"
	.string "Tu es presque aussi balèze que moi,\n"
	.string "à 1, 2, 3, 4, 5 endroits près!$"

Route110_TrickHouseEnd_Text_AllNightToPreparePanels:
	.string "Il m’a fallu toute la nuit pour préparer\n"
	.string "ces pans de mur…\p"
	.string "Tu es presque aussi balèze que moi,\n"
	.string "à un, deux, trois, quatre endroits près!$"

Route110_TrickHouseEnd_Text_AllNightToShoveBoulders:
	.string "Il m’a fallu toute la nuit pour pousser\n"
	.string "jusqu’ici tous ces rochers…\p"
	.string "Tu es presque aussi balèze que moi,\n"
	.string "à un, deux, trois endroits près!$"

Route110_TrickHouseEnd_Text_AllNightToMakeMechadolls:
	.string "Il m’a fallu une nuit pour fabriquer ces\n"
	.string "MECAPOUPEES et une pour les questions.\p"
	.string "Tu es presque aussi balèze que moi,\n"
	.string "à un, deux endroits près!$"

Route110_TrickHouseEnd_Text_AllNightToInstallDoors:
	.string "Il m’a fallu toute une nuit pour\n"
	.string "installer ces portes…\p"
	.string "Tu es presque aussi balèze que moi!$"

Route110_TrickHouseEnd_Text_AllNightSettingUpArrows:
	.string "Il m’a fallu toute la nuit pour installer\n"
	.string "ces flèches…\p"
	.string "Tu es aussi balèze que moi!$"

Route110_TrickHouseEnd_Text_AllNightPolishingFloors:
	.string "Il m’a fallu toute la nuit pour cirer\n"
	.string "les parquets…\p"
	.string "Tu es plus balèze que moi!\n"
	.string "Il est possible que…$"

Route110_TrickHouseEnd_Text_FountainOfIdeasRunDry:
	.string "Que… Qu’est-ce que je vais faire? Mes\n"
	.string "sources d’inspiration sont épuisées…\p"
	.string "Je devrais peut-être parcourir le pays\n"
	.string "à la recherche de nouveaux pièges…$"

Route110_TrickHouseEnd_Text_DefeatedMePreferWhichTent:
	.string "Ça me coûte de l’admettre, mais je\n"
	.string "crois que tu as fait mieux que moi!\p"
	.string "Cependant, mon charisme doit\n"
	.string "t’impressionner, puisque tu viens me\l"
	.string "voir très souvent. Aucun doute!\p"
	.string "Mais malgré tout, j’ai perdu!\p"
	.string "Pour sceller cette nouvelle amitié\n"
	.string "entre toi, le disciple, et moi, le génie,\l"
	.string "je te propose de garder un petit\l"
	.string "souvenir!\p"
	.string "Tu as le choix entre une TENTE ROUGE\n"
	.string "ou une TENTE BLEUE.\l"
	.string "Que préfères-tu?$"

Route110_TrickHouseEnd_Text_NoRoomInPC:
	.string "Quoi? Plus de place dans ton PC?\n"
	.string "Qu’est-ce que je vais faire de ça?\p"
	.string "J’aimerais te dire tant pis, mais je suis\n"
	.string "sympa. J’attendrai que tu reviennes!$"

Route110_TrickHouseEnd_Text_LeavingOnJourney:
	.string "… … … … … …\p"
	.string "Je vais partir à l’aventure.\n"
	.string "En quête de nouveaux pièges!\p"
	.string "J’espère que tu reviendras me voir\n"
	.string "pour me divertir.\p"
	.string "Bon, allez, à la prochaine!$"

Route110_TrickHouseEnd_Text_YouHaveEarnedThisReward:
	.string "Excellent!\n"
	.string "Tu as gagné cette récompense!$"

Route110_TrickHouseEnd_Text_NoRoomForThis:
	.string "Quoi? Tu n’as plus de place?\n"
	.string "Combien d’objets transportes-tu déjà?\p"
	.string "Soit, puisque tu m’as trouvé, je garde\n"
	.string "ta récompense. Reviens me voir.$"

Route110_TrickHouseEnd_Text_MakeNewTricksToStumpYou:
	.string "Epargne-moi ce sourire narquois! Ne va\n"
	.string "pas t’imaginer que tu as déjà gagné!\p"
	.string "Je trouverai de nouveaux pièges pour\n"
	.string "te coller. Après, tu pourras te moquer.\p"
	.string "Reviens me voir pour un autre\n"
	.string "défi passionnant!$"

Route110_TrickHouseEnd_Text_YoureIgnoringMe:
	.string "Quoi? Comment oses-tu? Tu m’ignores,\n"
	.string "maintenant? Ça me fend le cœur!$"
