
MossdeepCity_House4_Text_BrotherLikesToFindBases:
	.string "A mio fratello più piccolo piace scovare\n"
	.string "le BASI SEGRETE degli altri.$"

MossdeepCity_House4_Text_BrotherLikesToVisitBasesAndBattle:
	.string "A mio fratello più piccolo piace visitare\n"
	.string "le BASI SEGRETE degli altri e lottare\l"
	.string "con i POKéMON.$"

MossdeepCity_House4_Text_YouMadeSecretBaseNearX:
	.string "È tua la BASE SEGRETA del\n"
	.string "{STR_VAR_1}?$"

MossdeepCity_House4_Text_MakeSecretBase:
	.string "Ti dovresti creare una BASE SEGRETA\n"
	.string "da qualche parte. Così io te la scovo!$"

MossdeepCity_House4_Text_Skitty:
	.string "SKITTY: Ssskkkiiitttyyy?$"
