
BattleFrontier_Lounge3_Text_CantYouSeeWereBusyHere::
	.string "…\n"
	.string "Qu’est-ce que tu veux?\p"
	.string "Nous sommes occupés.\n"
	.string "Tu ne peux pas revenir plus tard?$"

BattleFrontier_Lounge3_Text_YouLookToughExplainGambling::
	.string "…\n"
	.string "Tu as l’air d’être un bon DRESSEUR.\p"
	.string "Hé, hé…\n"
	.string "J’ai quelque chose à te proposer.\p"
	.string "On est un petit groupe et on joue\n"
	.string "à un petit jeu ici. On mise sur ce qui\l"
	.string "se passe à la ZONE DE COMBAT.\p"
	.string "Les règles sont simples.\p"
	.string "D’abord, on choisit un des bâtiments\n"
	.string "de la ZONE DE COMBAT.\p"
	.string "Ensuite, on choisit chacun un DRESSEUR\n"
	.string "qui relève le défi de ce bâtiment et on\l"
	.string "mise des POINTS DE COMBAT dessus.\p"
	.string "Celui qui a misé sur le DRESSEUR qui\n"
	.string "fait le meilleur score récolte tous les\l"
	.string "POINTS DE COMBAT mis en jeu.\p"
	.string "Plutôt simple, non?\n"
	.string "De toute façon…$"

BattleFrontier_Lounge3_Text_ChallengeBattleTowerSingle::
	.string "Je cherche un DRESSEUR qui va relever\n"
	.string "le défi des SALLES DE COMBAT SOLO\l"
	.string "de la TOUR DE COMBAT.\p"
	.string "Mais je n’ai pas vu un seul DRESSEUR\n"
	.string "à la hauteur.$"

BattleFrontier_Lounge3_Text_ChallengeBattleTowerDouble::
	.string "Je cherche un DRESSEUR qui va relever\n"
	.string "le défi des SALLES DE COMBAT DUO\l"
	.string "de la TOUR DE COMBAT.\p"
	.string "Mais je n’ai pas vu un seul DRESSEUR\n"
	.string "à la hauteur.$"

BattleFrontier_Lounge3_Text_ChallengeBattleTowerMulti::
	.string "Je cherche un DRESSEUR qui va relever\n"
	.string "le défi des SALLES DE COMBAT MULTI\l"
	.string "de la TOUR DE COMBAT.\p"
	.string "Mais je n’ai pas vu un seul DRESSEUR\n"
	.string "à la hauteur.$"

BattleFrontier_Lounge3_Text_ChallengeBattleDomeSingle::
	.string "Je cherche un DRESSEUR qui va\n"
	.string "participer au TOURNOI DE COMBAT\l"
	.string "SOLO du DOME DE COMBAT.\p"
	.string "Mais je n’ai pas vu un seul DRESSEUR\n"
	.string "à la hauteur.$"

BattleFrontier_Lounge3_Text_ChallengeBattleDomeDouble::
	.string "Je cherche un DRESSEUR qui va\n"
	.string "participer au TOURNOI DE COMBAT\l"
	.string "DUO du DOME DE COMBAT.\p"
	.string "Mais je n’ai pas vu un seul DRESSEUR\n"
	.string "à la hauteur.$"

BattleFrontier_Lounge3_Text_ChallengeBattleFactorySingle::
	.string "Je cherche un DRESSEUR qui va\n"
	.string "participer au TOURNOI COMBAT\l"
	.string "ECHANGE SOLO de l’USINE DE COMBAT.\p"
	.string "Mais je n’ai pas vu un seul DRESSEUR\n"
	.string "à la hauteur.$"

BattleFrontier_Lounge3_Text_ChallengeBattleFactoryDouble::
	.string "Je cherche un DRESSEUR qui va\n"
	.string "participer au TOURNOI COMBAT\l"
	.string "ECHANGE DUO de l’USINE DE COMBAT.\p"
	.string "Mais je n’ai pas vu un seul DRESSEUR\n"
	.string "à la hauteur.$"

BattleFrontier_Lounge3_Text_ChallengeBattlePalaceSingle::
	.string "Je cherche un DRESSEUR qui va relever\n"
	.string "le défi des HALLS DE COMBAT SOLO\l"
	.string "du PALACE DE COMBAT.\p"
	.string "Mais je n’ai pas vu un seul DRESSEUR\n"
	.string "à la hauteur.$"

BattleFrontier_Lounge3_Text_ChallengeBattlePalaceDouble::
	.string "Je cherche un DRESSEUR qui va relever\n"
	.string "le défi des HALLS DE COMBAT DUO\l"
	.string "du PALACE DE COMBAT.\p"
	.string "Mais je n’ai pas vu un seul DRESSEUR\n"
	.string "à la hauteur.$"

BattleFrontier_Lounge3_Text_ChallengeBattleArena::
	.string "Je cherche un DRESSEUR qui va\n"
	.string "participer au TOURNOI K.O. du\l"
	.string "DOJO DE COMBAT.\p"
	.string "Mais je n’ai pas vu un seul DRESSEUR\n"
	.string "à la hauteur.$"

BattleFrontier_Lounge3_Text_ChallengeBattlePike::
	.string "Je cherche un DRESSEUR qui va\n"
	.string "relever le défi du COMBAT HASARD\l"
	.string "au REPTILE DE COMBAT.\p"
	.string "Mais je n’ai pas vu un seul DRESSEUR\n"
	.string "à la hauteur.$"

BattleFrontier_Lounge3_Text_ChallengeBattlePyramid::
	.string "Je cherche un DRESSEUR qui va\n"
	.string "relever le défi du COMBAT QUETE\l"
	.string "dans la PYRAMIDE DE COMBAT.\p"
	.string "Mais je n’ai pas vu un seul DRESSEUR\n"
	.string "à la hauteur.$"

BattleFrontier_Lounge3_Text_HowAboutEnteringEventForMe::
	.string "Bien sûr, tu ne feras pas ça pour rien.\n"
	.string "Qu’est-ce que tu en dis?\l"
	.string "Tu veux bien être ce DRESSEUR?$"

BattleFrontier_Lounge3_Text_SpotMeSomeBattlePoints::
	.string "Très bien. Parfait.\n"
	.string "Heu… Tu veux bien me prêter\l"
	.string "quelques POINTS DE COMBAT?\p"
	.string "Fais-moi confiance, je te remercierai\n"
	.string "comme il se doit.$"

BattleFrontier_Lounge3_Text_HowMuchCanYouSpot::
	.string "Super!\n"
	.string "Combien tu peux me prêter?$"

BattleFrontier_Lounge3_Text_YouDontHaveEnoughPoints::
	.string "Non mais!\n"
	.string "Tu n’as pas assez de POINTS DE COMBAT!\p"
	.string "Ça t’amuse de faire perdre leur temps\n"
	.string "aux honnêtes gens?$"

BattleFrontier_Lounge3_Text_ThanksOffYouGo::
	.string "Hé, hé! Merci bien!\n"
	.string "C’est parti!$"

BattleFrontier_Lounge3_Text_GetToBattleTowerSingle::
	.string "Vite, les SALLES DE COMBAT SOLO\n"
	.string "de la TOUR DE COMBAT t’attendent!\p"
	.string "Tu dois gagner!\n"
	.string "Je compte sur toi!\l"
	.string "Notre avenir à tous les deux en dépend!$"

BattleFrontier_Lounge3_Text_GetToBattleTowerDouble::
	.string "Vite, les SALLES DE COMBAT DUO\n"
	.string "de la TOUR DE COMBAT t’attendent!\p"
	.string "Tu dois gagner!\n"
	.string "Je compte sur toi!\l"
	.string "Notre avenir à tous les deux en dépend!$"

BattleFrontier_Lounge3_Text_GetToBattleTowerMulti::
	.string "Vite, les SALLES DE COMBAT MULTI\n"
	.string "de la TOUR DE COMBAT t’attendent!\p"
	.string "Tu dois gagner!\n"
	.string "Je compte sur toi!\l"
	.string "Notre avenir à tous les deux en dépend!$"

BattleFrontier_Lounge3_Text_GetToBattleDomeSingle::
	.string "Vite, le TOURNOI DE COMBAT SOLO\n"
	.string "du DOME DE COMBAT t’attend!\p"
	.string "Tu dois gagner!\n"
	.string "Je compte sur toi!\l"
	.string "Notre avenir à tous les deux en dépend!$"

BattleFrontier_Lounge3_Text_GetToBattleDomeDouble::
	.string "Vite, le TOURNOI DE COMBAT DUO\n"
	.string "du DOME DE COMBAT t’attend!\p"
	.string "Tu dois gagner!\n"
	.string "Je compte sur toi!\l"
	.string "Notre avenir à tous les deux en dépend!$"

BattleFrontier_Lounge3_Text_GetToBattleFactorySingle::
	.string "Vite, le TOURNOI COMBAT ECHANGE\n"
	.string "SOLO de l’USINE DE COMBAT t’attend!\p"
	.string "Tu dois gagner!\n"
	.string "Je compte sur toi!\l"
	.string "Notre avenir à tous les deux en dépend!$"

BattleFrontier_Lounge3_Text_GetToBattleFactoryDouble::
	.string "Vite, le TOURNOI COMBAT ECHANGE\n"
	.string "DUO de l’USINE DE COMBAT t’attend!\p"
	.string "Tu dois gagner!\n"
	.string "Je compte sur toi!\l"
	.string "Notre avenir à tous les deux en dépend!$"

BattleFrontier_Lounge3_Text_GetToBattlePalaceSingle::
	.string "Vite, les HALLS DE COMBAT SOLO\n"
	.string "du PALACE DE COMBAT t’attendent!\p"
	.string "Tu dois gagner!\n"
	.string "Je compte sur toi!\l"
	.string "Notre avenir à tous les deux en dépend!$"

BattleFrontier_Lounge3_Text_GetToBattlePalaceDouble::
	.string "Vite, les HALLS DE COMBAT DUO\n"
	.string "du PALACE DE COMBAT t’attendent!\p"
	.string "Tu dois gagner!\n"
	.string "Je compte sur toi!\l"
	.string "Notre avenir à tous les deux en dépend!$"

BattleFrontier_Lounge3_Text_GetToBattleArena::
	.string "Vite, le TOURNOI K.O. du DOJO DE\n"
	.string "COMBAT t’attend!\p"
	.string "Tu dois gagner!\n"
	.string "Je compte sur toi!\l"
	.string "Notre avenir à tous les deux en dépend!$"

BattleFrontier_Lounge3_Text_GetToBattlePike::
	.string "Vite, le défi du COMBAT HASARD\n"
	.string "t’attend au REPTILE DE COMBAT!\p"
	.string "Tu dois gagner!\n"
	.string "Je compte sur toi!\l"
	.string "Notre avenir à tous les deux en dépend!$"

BattleFrontier_Lounge3_Text_GetToBattlePyramid::
	.string "Vite, le défi du COMBAT QUETE\n"
	.string "t’attend dans la PYRAMIDE DE COMBAT!\p"
	.string "Tu dois gagner!\n"
	.string "Je compte sur toi!\l"
	.string "Notre avenir à tous les deux en dépend!$"

BattleFrontier_Lounge3_Text_NiceTryCantReturnPoints::
	.string "Oh, c’est toi…\n"
	.string "C’était bien tenté…\p"
	.string "Malheureusement, je ne peux pas te\n"
	.string "rendre ce que tu m’as prêté…\p"
	.string "Ça nous apprendra à faire plus\n"
	.string "attention la prochaine fois!$"

BattleFrontier_Lounge3_Text_HelloChampHeresYourPoints::
	.string "Bravo!\n"
	.string "Tu as été formidable!\p"
	.string "Je le savais!\n"
	.string "Je te faisais confiance!\l"
	.string "On est les meilleurs!\p"
	.string "Je te rends ce que tu m’as prêté avec\n"
	.string "un petit extra!$"

BattleFrontier_Lounge3_Text_ObtainedBattlePoints::
	.string "{PLAYER} reçoit\n"
	.string "{STR_VAR_1} POINTS DE COMBAT.$"

BattleFrontier_Lounge3_Text_ThinkOfMeForAnotherChallenge::
	.string "Si tu as envie de relever un autre\n"
	.string "défi, pense à moi!$"

BattleFrontier_Lounge3_Text_NotInterested::
	.string "Ça ne t’intéresse pas?\n"
	.string "Penses-y, au moins!$"

BattleFrontier_Lounge3_Text_Oh::
	.string "Oh…$"

BattleFrontier_Lounge3_Text_BackedWrongTrainer::
	.string "J’ai encore misé sur le mauvais\n"
	.string "DRESSEUR!\p"
	.string "Je crois que je devrais arrêter ces\n"
	.string "bêtises…$"

BattleFrontier_Lounge3_Text_TrainerGoodButRattled::
	.string "Ce DRESSEUR…\p"
	.string "Il est bon, mais il n’a pas les nerfs\n"
	.string "assez solides pour le DOME DE COMBAT…$"

BattleFrontier_Lounge3_Text_KnowWinnerWhenISeeOne::
	.string "Hi, hi, hi!\n"
	.string "Je sais reconnaître un gagnant!$"

BattleFrontier_Lounge3_Text_ShouldBeTakingChallenges::
	.string "Ces DRESSEURS…\n"
	.string "Mais que font-ils?\l"
	.string "Ils devraient aller se battre.$"