
BattleFrontier_Lounge3_Text_CantYouSeeWereBusyHere::
	.string "Che cosa vuoi?\p"
	.string "Non vedi che qui si lavora?\n"
	.string "Perché non togli il disturbo?$"

BattleFrontier_Lounge3_Text_YouLookToughExplainGambling::
	.string "Uh?\n"
	.string "Mi sembri un ALLENATORE forte.\p"
	.string "Eheh…\n"
	.string "Ascolta, ho una proposta da farti.\p"
	.string "Insieme a un piccolo gruppo di amici\n"
	.string "facciamo un giochino ispirato al\l"
	.string "PARCO LOTTA.\p"
	.string "Le regole sono davvero semplici.\p"
	.string "Innanzitutto, scegliamo un edificio\n"
	.string "del PARCO LOTTA.\p"
	.string "Poi, ognuno di noi scommette\n"
	.string "PUNTI LOTTA su un ALLENATORE\l"
	.string "a scelta che parteciperà alla sfida\l"
	.string "in quell’edificio.\p"
	.string "La persona che ha scommesso\n"
	.string "sull’ALLENATORE vincente si\l"
	.string "prende tutti i PUNTI LOTTA in palio.\p"
	.string "Facile, vero?\n"
	.string "Passiamo al sodo…$"

BattleFrontier_Lounge3_Text_ChallengeBattleTowerSingle::
	.string "Sto cercando un ALLENATORE che\n"
	.string "sfidi le SALE LOTTA in SINGOLO\l"
	.string "della TORRE LOTTA.\p"
	.string "Ma, finora, non ho incrociato un\n"
	.string "ALLENATORE all’altezza.$"

BattleFrontier_Lounge3_Text_ChallengeBattleTowerDouble::
	.string "Sto cercando un ALLENATORE che\n"
	.string "sfidi le SALE LOTTA in DOPPIO\l"
	.string "della TORRE LOTTA.\p"
	.string "Ma, finora, non ho incrociato un\n"
	.string "ALLENATORE all’altezza.$"

BattleFrontier_Lounge3_Text_ChallengeBattleTowerMulti::
	.string "Sto cercando un ALLENATORE che\n"
	.string "sfidi le SALE LOTTA MULTIPLA\l"
	.string "della TORRE LOTTA.\p"
	.string "Ma, finora, non ho incrociato un\n"
	.string "ALLENATORE all’altezza.$"

BattleFrontier_Lounge3_Text_ChallengeBattleDomeSingle::
	.string "Sto cercando un ALLENATORE\n"
	.string "che si iscriva al TORNEO LOTTA\l"
	.string "in SINGOLO della CUPOLA LOTTA.\p"
	.string "Ma, finora, non ho incrociato nessun\n"
	.string "ALLENATORE all’altezza.$"

BattleFrontier_Lounge3_Text_ChallengeBattleDomeDouble::
	.string "Sto cercando un ALLENATORE\n"
	.string "che si iscriva al TORNEO LOTTA\l"
	.string "in DOPPIO della CUPOLA LOTTA.\p"
	.string "Ma, finora, non ho incrociato nessun\n"
	.string "ALLENATORE all’altezza.$"

BattleFrontier_Lounge3_Text_ChallengeBattleFactorySingle::
	.string "Sto cercando un ALLENATORE che si\n"
	.string "iscriva al TORNEO LOTTA SCAMBIO\l"
	.string "in SINGOLO dell’AZIENDA LOTTA.\p"
	.string "Ma, finora, non ho incrociato nessun\n"
	.string "ALLENATORE all’altezza.$"

BattleFrontier_Lounge3_Text_ChallengeBattleFactoryDouble::
	.string "Sto cercando un ALLENATORE che si\n"
	.string "iscriva al TORNEO LOTTA SCAMBIO\l"
	.string "in DOPPIO dell’AZIENDA LOTTA.\p"
	.string "Ma, finora, non ho incrociato nessun\n"
	.string "ALLENATORE all’altezza.$"

BattleFrontier_Lounge3_Text_ChallengeBattlePalaceSingle::
	.string "Sto cercando un ALLENATORE che \n"
	.string "sfidi le AREE LOTTA in SINGOLO\l"
	.string "del PALAZZO LOTTA.\p"
	.string "Ma, finora, non ho incrociato nessun\n"
	.string "ALLENATORE all’altezza.$"

BattleFrontier_Lounge3_Text_ChallengeBattlePalaceDouble::
	.string "Sto cercando un ALLENATORE che \n"
	.string "sfidi le AREE LOTTA in DOPPIO\l"
	.string "del PALAZZO LOTTA.\p"
	.string "Ma, finora, non ho incrociato nessun\n"
	.string "ALLENATORE all’altezza.$"

BattleFrontier_Lounge3_Text_ChallengeBattleArena::
	.string "Sto cercando un ALLENATORE che si\n"
	.string "iscriva al TORNEO TRE TURNI del\l"
	.string "DOJO LOTTA.\p"
	.string "Ma, finora, non ho incrociato nessun\n"
	.string "ALLENATORE all’altezza.$"

BattleFrontier_Lounge3_Text_ChallengeBattlePike::
	.string "Sto cercando un ALLENATORE che si\n"
	.string "iscriva alla LOTTA DILEMMA della\l"
	.string "SERPE LOTTA.\p"
	.string "Ma, finora, non ho incrociato nessun\n"
	.string "ALLENATORE all’altezza.$"

BattleFrontier_Lounge3_Text_ChallengeBattlePyramid::
	.string "Sto cercando un ALLENATORE che si\n"
	.string "iscriva alla LOTTA ESPLORAZIONE\l"
	.string "della PIRAMIDE LOTTA.\p"
	.string "Ma, finora, non ho incrociato nessun\n"
	.string "ALLENATORE all’altezza.$"

BattleFrontier_Lounge3_Text_HowAboutEnteringEventForMe::
	.string "Farò in modo che sia vantaggioso\n"
	.string "anche per te. Cosa ne pensi?\l"
	.string "Vuoi partecipare all’evento?$"

BattleFrontier_Lounge3_Text_SpotMeSomeBattlePoints::
	.string "Benissimo.\n"
	.string "Ehm… che ne dici di prestarmi\l"
	.string "qualche PUNTO LOTTA dei tuoi?\p"
	.string "Fidati di me. Più tardi ti dimostrerò\n"
	.string "la mia riconoscenza.$"

BattleFrontier_Lounge3_Text_HowMuchCanYouSpot::
	.string "Fantastico!\n"
	.string "Allora quanti riesci a prestarmene?$"

BattleFrontier_Lounge3_Text_YouDontHaveEnoughPoints::
	.string "Oh, no!\n"
	.string "Non hai PUNTI LOTTA sufficienti!\p"
	.string "Non fare il pagliaccio! Non ho tempo\n"
	.string "da perdere, io!$"

BattleFrontier_Lounge3_Text_ThanksOffYouGo::
	.string "Eheh! Grazie mille!\n"
	.string "Forza e coraggio!$"

BattleFrontier_Lounge3_Text_GetToBattleTowerSingle::
	.string "Parti subito alla conquista delle SALE\n"
	.string "LOTTA in SINGOLO della TORRE LOTTA!\p"
	.string "Non puoi non vincere!\n"
	.string "Non farti scappare questa opportunità!\l"
	.string "Sei l’artefice del mio e del tuo destino!$"

BattleFrontier_Lounge3_Text_GetToBattleTowerDouble::
	.string "Parti subito alla conquista delle SALE\n"
	.string "LOTTA in DOPPIO della TORRE LOTTA!\p"
	.string "Non puoi non vincere!\n"
	.string "Non farti scappare questa opportunità!\l"
	.string "Sei l’artefice del mio e del tuo destino!$"

BattleFrontier_Lounge3_Text_GetToBattleTowerMulti::
	.string "Parti subito alla conquista delle SALE\n"
	.string "LOTTA MULTIPLA della TORRE LOTTA!\p"
	.string "Non puoi non vincere!\n"
	.string "Non farti scappare questa opportunità!\l"
	.string "Sei l’artefice del mio e del tuo destino!$"

BattleFrontier_Lounge3_Text_GetToBattleDomeSingle::
	.string "Parti subito alla conquista del TORNEO\n"
	.string "LOTTA in SINGOLO della CUPOLA LOTTA!\p"
	.string "Non puoi non vincere!\n"
	.string "Non farti scappare questa opportunità!\l"
	.string "Sei l’artefice del mio e del tuo destino!$"

BattleFrontier_Lounge3_Text_GetToBattleDomeDouble::
	.string "Parti subito alla conquista del TORNEO\n"
	.string "LOTTA in DOPPIO della CUPOLA LOTTA!\p"
	.string "Non puoi non vincere!\n"
	.string "Non farti scappare questa opportunità!\l"
	.string "Sei l’artefice del mio e del tuo destino!$"

BattleFrontier_Lounge3_Text_GetToBattleFactorySingle::
	.string "Parti subito alla conquista del TORNEO\n"
	.string "LOTTA SCAMBIO in SINGOLO\l"
	.string "dell’AZIENDA LOTTA!\p"
	.string "Non puoi non vincere!\n"
	.string "Non farti scappare questa opportunità!\l"
	.string "Sei l’artefice del mio e del tuo destino!$"

BattleFrontier_Lounge3_Text_GetToBattleFactoryDouble::
	.string "Parti subito alla conquista del TORNEO\n"
	.string "LOTTA SCAMBIO in DOPPIO\l"
	.string "dell’AZIENDA LOTTA!\p"
	.string "Non puoi non vincere!\n"
	.string "Non farti scappare questa opportunità!\l"
	.string "Sei l’artefice del mio e del tuo destino!$"

BattleFrontier_Lounge3_Text_GetToBattlePalaceSingle::
	.string "Parti subito alla conquista delle AREE\n"
	.string "LOTTA in SINGOLO del PALAZZO LOTTA!\p"
	.string "Non puoi non vincere!\n"
	.string "Non farti scappare questa opportunità!\l"
	.string "Sei l’artefice del mio e del tuo destino!$"

BattleFrontier_Lounge3_Text_GetToBattlePalaceDouble::
	.string "Parti subito alla conquista delle AREE\n"
	.string "LOTTA in DOPPIO del PALAZZO LOTTA!\p"
	.string "Non puoi non vincere!\n"
	.string "Non farti scappare questa opportunità!\l"
	.string "Sei l’artefice del mio e del tuo destino!$"

BattleFrontier_Lounge3_Text_GetToBattleArena::
	.string "Parti subito alla conquista del TORNEO\n"
	.string "TRE TURNI del DOJO LOTTA!\p"
	.string "Non puoi non vincere!\n"
	.string "Non farti scappare questa opportunità!\l"
	.string "Sei l’artefice del mio e del tuo destino!$"

BattleFrontier_Lounge3_Text_GetToBattlePike::
	.string "Parti subito alla conquista della LOTTA\n"
	.string "DILEMMA della SERPE LOTTA!\p"
	.string "Non puoi non vincere!\n"
	.string "Non farti scappare questa opportunità!\l"
	.string "Sei l’artefice del mio e del tuo destino!$"

BattleFrontier_Lounge3_Text_GetToBattlePyramid::
	.string "Parti subito alla conquista della LOTTA\n"
	.string "ESPLORAZIONE della PIRAMIDE LOTTA!\p"
	.string "Non puoi non vincere!\n"
	.string "Non farti scappare questa opportunità!\l"
	.string "Sei l’artefice del mio e del tuo destino!$"

BattleFrontier_Lounge3_Text_NiceTryCantReturnPoints::
	.string "Ah, sei tu… ce l’hai messa tutta…\p"
	.string "Mi dispiace, ma non posso restituirti\n"
	.string "i tuoi PUNTI LOTTA…\p"
	.string "La prossima volta dobbiamo metterci\n"
	.string "più impegno!$"

BattleFrontier_Lounge3_Text_HelloChampHeresYourPoints::
	.string "Oh, sì!\n"
	.string "Ciao, campione!\p"
	.string "Sapevo che avresti potuto farcela!\n"
	.string "Sapevo che ce l’avresti fatta!\l"
	.string "Siamo imbattibili!\p"
	.string "Ti restituisco i tuoi PUNTI LOTTA, con\n"
	.string "una piccola aggiunta da parte mia!$"

BattleFrontier_Lounge3_Text_ObtainedBattlePoints::
	.string "{PLAYER} ottiene\n"
	.string "{STR_VAR_1} PUNTI LOTTA.$"

BattleFrontier_Lounge3_Text_ThinkOfMeForAnotherChallenge::
	.string "Se sei in vena di sfide,\n"
	.string "non ti scordar di me!$"

BattleFrontier_Lounge3_Text_NotInterested::
	.string "Non ti interessa?! Chi non risica,\n"
	.string "non rosica!$"

BattleFrontier_Lounge3_Text_Oh::
	.string "Oh…$"

BattleFrontier_Lounge3_Text_BackedWrongTrainer::
	.string "Ancora una volta ho dato retta\n"
	.string "all’ALLENATORE sbagliato!\p"
	.string "Forse dovrei lottare normalmente,\n"
	.string "come fanno tutti…$"

BattleFrontier_Lounge3_Text_TrainerGoodButRattled::
	.string "Quell’ALLENATORE…\p"
	.string "È bravo, ma si lascia suggestionare\n"
	.string "troppo dalla CUPOLA LOTTA…$"

BattleFrontier_Lounge3_Text_KnowWinnerWhenISeeOne::
	.string "Ihihih! So riconoscere un vincitore\n"
	.string "a colpo d’occhio!$"

BattleFrontier_Lounge3_Text_ShouldBeTakingChallenges::
	.string "Quegli ALLENATORI…\n"
	.string "Perché se ne stanno in panciolle?\l"
	.string "Dovrebbero partecipare alle sfide.$"
