
RustboroCity_DevonCorp_2F_Text_DeviceForTalkingToPokemon:
	.string "Estamos desarrollando un dispositivo\n"
	.string "para hablar con los POKéMON.\p"
	.string "Bueno, la verdad es que todavía no\n"
	.string "hemos conseguido gran cosa…$"

RustboroCity_DevonCorp_2F_Text_DevelopingNewBalls:
	.string "Estoy desarrollando nuevos tipos\n"
	.string "de POKé BALLS…\p"
	.string "En fin, lo cierto es que aún no he\n"
	.string "descubierto nada que funcione…$"

RustboroCity_DevonCorp_2F_Text_WeFinallyMadeNewBalls:
	.string "¡Por fin hemos creado nuevos tipos\n"
	.string "de POKé BALLS!\p"
	.string "Con la ACOPIO BALL es más fácil cazar\n"
	.string "aquellos tipos de POKéMON que ya has\l"
	.string "atrapado al menos una vez antes.\p"
	.string "Con la TURNO BALL resulta más fácil\n"
	.string "atrapar POKéMON a medida que va\l"
	.string "avanzando el combate.\p"
	.string "Ambas son patentes exclusivas\n"
	.string "de DEVON S.A. ¡Pruébalas!$"

RustboroCity_DevonCorp_2F_Text_IMadePokenav:
	.string "¡Soy el creador del POKéNAV!\p"
	.string "¡Como ingeniero, es un gran orgullo\n"
	.string "ser el autor de esta maravilla!$"

RustboroCity_DevonCorp_2F_Text_WowThatsAPokenav:
	.string "¡Guau!\n"
	.string "¡Tienes un POKéNAV!\p"
	.string "¿Sabes que se creó porque nuestro\n"
	.string "PRESIDENTE quería saber más sobre\l"
	.string "los sentimientos de los POKéMON?\p"
	.string "¿Quieres que te explique con detalle\n"
	.string "todas sus características?\p"
	.string "No, mejor las vas descubriendo tú\n"
	.string "a base de usarlo. No es tan difícil.$"

RustboroCity_DevonCorp_2F_Text_DeviceToVisualizePokemonDreams:
	.string "Estoy intentando desarrollar un\n"
	.string "dispositivo que reproduzca una imagen\l"
	.string "de los sueños de los POKéMON.\p"
	.string "Por ahora no he avanzado mucho…$"

RustboroCity_DevonCorp_2F_Text_DevelopDeviceToResurrectFossils:
	.string "Llevo siglos intentando crear\n"
	.string "un dispositivo para reanimar POKéMON\l"
	.string "a partir de sus fósiles…\p"
	.string "¡Y por fin lo he conseguido!$"

RustboroCity_DevonCorp_2F_Text_WantToBringFossilBackToLife:
	.string "Un momento. Eso que tienes ahí…\n"
	.string "¿no es un fósil de un POKéMON?\p"
	.string "¿Querrías reanimarlo?\p"
	.string "Pues yo puedo hacerlo con mi\n"
	.string "REGENERADOR de FÓSILES.$"

RustboroCity_DevonCorp_2F_Text_OhIsThatSo:
	.string "¿No quieres?\p"
	.string "Mira que la tecnología DEVON\n"
	.string "es algo nunca visto…$"

RustboroCity_DevonCorp_2F_Text_TwoFossilsPickOne:
	.string "¡Guau, esto sí que es excepcional!\n"
	.string "¡No tienes uno, sino dos fósiles!\p"
	.string "Desgraciadamente, esta máquina sólo\n"
	.string "puede regenerar un POKéMON cada vez.\p"
	.string "¿Quieres regenerar alguno\n"
	.string "de tus dos fósiles?$"

RustboroCity_DevonCorp_2F_Text_HandedFossilToResearcher:
	.string "¡Maravilloso!\n"
	.string "Pongámonos manos a la obra.\p"
	.string "{PLAYER} entregó el {STR_VAR_1} al\n"
	.string "INVESTIGADOR de DEVON.$"

RustboroCity_DevonCorp_2F_Text_FossilRegeneratorTakesTime:
	.string "El REGENERADOR de FÓSILES\n"
	.string "que he ideado es algo impresionante.\p"
	.string "Pero tiene un problemilla… Tarda\n"
	.string "un montón en funcionar…\p"
	.string "Así que, ejem, ¿por qué no vas a darte\n"
	.string "una vueltecita mientras tanto?$"

RustboroCity_DevonCorp_2F_Text_FossilizedMonBroughtBackToLife:
	.string "¡Gracias por tu paciencia!\p"
	.string "Tu POKéMON fosilizado ya vuelve\n"
	.string "a estar vivito y coleando.\p"
	.string "Este fósil era un antiguo {STR_VAR_2}\n"
	.string "POKéMON, sí, señor.$"

RustboroCity_DevonCorp_2F_Text_ReceivedMonFromResearcher:
	.string "{PLAYER} recibió {STR_VAR_2} del\n"
	.string "INVESTIGADOR de DEVON.$"

@ Unused
RustboroCity_DevonCorp_2F_Text_TooManyPokemon:
	.string "Uh-oh, you’ve got too many POKéMON.\n"
	.string "You have no room for this one.$"

RustboroCity_DevonCorp_2F_Text_DevelopNewPokenavFeature:
	.string "Estoy intentando crear una nueva\n"
	.string "función para el POKéNAV…\p"
	.string "Pero no me sale, no me sale…$"

RustboroCity_DevonCorp_2F_Text_WhatToWorkOnNext:
	.string "Bueno, bueno, ¿qué podría\n"
	.string "ponerme a investigar ahora?\p"
	.string "¿Sabes? Esta empresa nos permite\n"
	.string "hacer realidad nuestros sueños.\p"
	.string "No existe mejor lugar para un\n"
	.string "ingeniero con visión de futuro.$"
