
SootopolisCity_House6_Text_FirstGuestInWhileTakeDoll:
	.string "Ciao! Era da un po’ che non avevamo\n"
	.string "clienti.\p"
	.string "Mi hai illuminato la giornata, quindi ti\n"
	.string "meriti questa BAMBOLA WAILMER.$"

SootopolisCity_House6_Text_TakeGoodCareOfIt:
	.string "Abbine cura!$"

SootopolisCity_House6_Text_IllHoldItForYou:
	.string "Oh, la vuoi, ma non ora?\n"
	.string "Ok, te la terrò qui.$"

SootopolisCity_House6_Text_DontWantThisDoll:
	.string "Davvero?\n"
	.string "Non vuoi questa BAMBOLA?$"

SootopolisCity_House6_Text_LovePlushDolls:
	.string "Adoro le BAMBOLE di pezza!$"
