
EverGrandeCity_DrakesRoom_Text_IntroSpeech:
	.string "Je suis le dernier du CONSEIL 4,\n"
	.string "ARAGON, le maître DRAGON.\p"
	.string "A l’état naturel, les POKéMON sont des\n"
	.string "créatures sauvages. Ils sont libres.\p"
	.string "Parfois, ils nous font obstacle.\n"
	.string "Parfois, ils nous aident.\p"
	.string "Combattre en s’alliant avec les\n"
	.string "POKéMON, tu sais ce que ça représente?\p"
	.string "Tu sais ce qu’il faut pour y parvenir?\p"
	.string "Si tu ne le sais pas, alors tu ne pourras\n"
	.string "jamais me dominer!$"

EverGrandeCity_DrakesRoom_Text_Defeat:
	.string "Superbe! Ça vaut la peine d’être dit!$"

EverGrandeCity_DrakesRoom_Text_PostBattleSpeech:
	.string "Quel mérite d’avoir fait tout ce chemin\n"
	.string "en tant que DRESSEUR de POKéMON!\p"
	.string "Tu sembles avoir la qualité que\n"
	.string "possèdent les vrais DRESSEURS.\p"
	.string "Oui, ce qu’un DRESSEUR doit avoir, c’est\n"
	.string "un cœur vertueux.\p"
	.string "Les POKéMON touchent le cœur vertueux\n"
	.string "des DRESSEURS et apprennent le bien.\p"
	.string "Ils touchent le cœur vertueux des\n"
	.string "DRESSEURS et deviennent forts.\p"
	.string "Allez, en avant!\n"
	.string "Le MAITRE t’attend!$"

