
GraniteCave_1F_Text_GetsDarkAheadHereYouGo:
	.string "Oye, tú.\n"
	.string "Aquí dentro está muy oscuro.\l"
	.string "No va a ser fácil explorar esto.\p"
	.string "Ese tipo que vino antes…\n"
	.string "MÁXIMO se llamaba…\p"
	.string "Él sabía cómo usar DESTELLO, así\n"
	.string "que no ha debido de tener problemas…\p"
	.string "Pero nosotros, los MONTAÑEROS,\n"
	.string "estamos siempre dispuestos a echar\l"
	.string "una mano… ¡o dos!\p"
	.string "Así que toma, es para ti.$"

GraniteCave_1F_Text_ExplainFlash:
	.string "Enseña el movimiento de MO DESTELLO\n"
	.string "a un POKéMON y úsalo.\p"
	.string "Podrás alumbrar incluso las cuevas\n"
	.string "oscuras como boca de lobo.\p"
	.string "Pero, para usarlo, necesitas la MEDALLA\n"
	.string "del GIMNASIO de AZULIZA.$"
