
GraniteCave_1F_Text_GetsDarkAheadHereYouGo:
	.string "Ehi, tu!\n"
	.string "Più avanti è davvero buio.\l"
	.string "Non sarà facile addentrarsi.\p"
	.string "Quel ragazzo che è passato prima…\n"
	.string "si chiamava ROCCO…\p"
	.string "Lui sapeva usare FLASH, quindi di sicuro\n"
	.string "se la starà cavando bene, ma…\p"
	.string "aiutare chi incontriamo è il motto di noi\n"
	.string "AVVENTURIERI!\p"
	.string "Prendi questo, ti sarà utile.$"

GraniteCave_1F_Text_ExplainFlash:
	.string "Insegna la mossa MN FLASH\n"
	.string "ad un POKéMON.\p"
	.string "FLASH illumina anche gli angoli\n"
	.string "più oscuri delle grotte.\p"
	.string "Ma senza la MEDAGLIA della PALESTRA\n"
	.string "POKéMON di BLURUVIA non puoi usarla.$"
