EverGrandeCity_Hall2: @ 8483C74
	.4byte EverGrandeCity_ShortHall_Layout
	.4byte EverGrandeCity_Hall2_MapEvents
	.4byte EverGrandeCity_Hall2_MapScripts
	.4byte 0x0
	.2byte MUS_C_ROAD
	.2byte 116
	.byte MAPSEC_EVER_GRANDE_CITY
	.byte 0
	.byte WEATHER_NONE
	.byte MAP_TYPE_INDOOR
	.2byte 0
	map_header_flags allow_bike=0, allow_escape_rope=0, allow_run=0, show_map_name=0
	.byte MAP_BATTLE_SCENE_NORMAL

