
BattleFrontier_BattlePikeRoomNormal_Text_WillRestoreToFullHealth:
	.string "Ti do il benvenuto.\n"
	.string "La tua fortuna è notevole…\p"
	.string "I tuoi POKéMON verranno rimessi\n"
	.string "in sesto…$"

BattleFrontier_BattlePikeRoomNormal_Text_EnjoyRestOfChallenge:
	.string "Che la sfida LOTTA DILEMMA sia\n"
	.string "di tuo gradimento!$"

BattleFrontier_BattlePikeRoomNormal_Text_WillRestoreOneMon:
	.string "Ah, la buona sorte ti assiste.\n"
	.string "Mi hai risollevato un po’ l’umore.\p"
	.string "Rimetterò in sesto uno dei tuoi\n"
	.string "POKéMON.$"

BattleFrontier_BattlePikeRoomNormal_Text_BestOfLuckFarewell:
	.string "Che la fortuna sia dalla tua.\n"
	.string "Alla prossima.$"

@ Seems there was a planned room type where the player could choose to battle and would be healed if they won
@ Possibly replaced/superseded by the hard battle room, which is the same but the battle isnt optional
@ Unused
BattleFrontier_BattlePikeRoomNormal_Text_CareForBattleWillRestoreMons:
	.string "Excuse me…\p"
	.string "Would you care for a battle?\n"
	.string "I’ll restore your POKéMON if you win.$"

@ Unused
BattleFrontier_BattlePikeRoomNormal_Text_NowShallWe:
	.string "Very well…\n"
	.string "Now, shall we?$"

@ Unused
BattleFrontier_BattlePikeRoomNormal_Text_HowUnsportingOfYou:
	.string "I see…\n"
	.string "How unsporting of you…$"

@ Unused
BattleFrontier_BattlePikeRoomNormal_Text_WillRestoreMonsAsPromised:
	.string "Magnificent…\p"
	.string "As promised, I shall restore your\n"
	.string "POKéMON to full health.$"

@ Unused
BattleFrontier_BattlePikeRoomNormal_Text_BestOfLuckFarewell2:
	.string "The best of luck to you.\n"
	.string "Farewell.$"

BattleFrontier_BattlePikeRoomNormal_Text_WatchOut:
	.string "Oh, cielo!\p"
	.string "Fai attenzione!$"

BattleFrontier_BattlePikeRoomNormal_Text_KirliaStop:
	.string "KIRLIA, smettila!\n"
	.string "Adesso!$"

BattleFrontier_BattlePikeRoomNormal_Text_DusclopsStop:
	.string "DUSCLOPS, smettila!\n"
	.string "Adesso!$"

BattleFrontier_BattlePikeRoomNormal_Text_KirliaUsedToxic:
	.string "KIRLIA usa TOSSINA!$"

BattleFrontier_BattlePikeRoomNormal_Text_KirliaUsedHypnosis:
	.string "KIRLIA usa IPNOSI!$"

BattleFrontier_BattlePikeRoomNormal_Text_KirliaUsedThunderWave:
	.string "KIRLIA usa TUONONDA!$"

BattleFrontier_BattlePikeRoomNormal_Text_KirliaUsedWillOWisp:
	.string "KIRLIA usa FUOCOFATUO!$"

BattleFrontier_BattlePikeRoomNormal_Text_DusclopsUsedWillOWisp:
	.string "DUSCLOPS usa FUOCOFATUO!$"

BattleFrontier_BattlePikeRoomNormal_Text_DusclopsUsedIceBeam:
	.string "DUSCLOPS usa GELORAGGIO!$"

BattleFrontier_BattlePikeRoomNormal_Text_ThatsEnough:
	.string "Guarda qui!\n"
	.string "Adesso basta!$"

BattleFrontier_BattlePikeRoomNormal_Text_ApologizeForKirlia:
	.string "Accetta le mie scuse…\p"
	.string "Il mio KIRLIA ha una natura TIMIDA…$"

BattleFrontier_BattlePikeRoomNormal_Text_ApologizeForDusclops:
	.string "Accetta le mie scuse…\p"
	.string "Il mio DUSCLOPS ha una natura TIMIDA…$"

BattleFrontier_BattlePikeRoomNormal_Text_AttacksWhenStartled:
	.string "Se una persona lo spaventa, attacca\n"
	.string "all’improvviso…\p"
	.string "Tu e i tuoi POKéMON state bene?$"

BattleFrontier_BattlePikeRoomNormal_Text_ApologizeHopeMonsAreFine:
	.string "Mi scuso per quello che è accaduto.\n"
	.string "Spero che i tuoi POKéMON siano a posto.$"

BattleFrontier_BattlePikeRoomNormal_Text_Silence:
	.string "… … … … … …\n"
	.string "… … … … … …$"

BattleFrontier_BattlePikeRoomNormal_Text_BattleSomewhatToughTrainer:
	.string "Salve…\p"
	.string "Ti aspetta un ALLENATORE molto\n"
	.string "forte…$"

BattleFrontier_BattlePikeRoomNormal_Text_RestoreToFullHealth:
	.string "Che meraviglia…\p"
	.string "In onore alla tua vittoria, i tuoi\n"
	.string "POKéMON verranno rimessi\l"
	.string "in sesto…$"

BattleFrontier_BattlePikeRoomNormal_Text_EnjoyRestOfChallenge2:
	.string "Che la sfida LOTTA DILEMMA sia\n"
	.string "di tuo gradimento!$"

BattleFrontier_BattlePikeRoomNormal_Text_ImThePikeQueen:
	.string "Mi chiamo FORTUNATA.\n"
	.string "Qui comando io.\l"
	.string "In veste di REGINA SERPE…\p"
	.string "Come tu ben sai, per avanzare devi\n"
	.string "sconfiggermi…\p"
	.string "Basta con le chiacchiere inutili!\n"
	.string "Non c’è tempo da perdere…$"

BattleFrontier_BattlePikeRoomNormal_Text_HopeYouDidntUseUpLuck:
	.string "Spero che nel frattempo la fortuna\n"
	.string "non ti abbia voltato le spalle…$"

BattleFrontier_BattlePikeRoomNormal_Text_LucyShowMeFrontierPass:
	.string "FORTUNATA: … … … … … …\n"
	.string "Mostrami il tuo PASS PARCO…$"

BattleFrontier_BattlePikeRoomNormal_Text_ReceivedLuckSymbol:
	.string "Il SIMBOLO FORTUNA è stato aggiunto\n"
	.string "al PASS PARCO!$"

BattleFrontier_BattlePikeRoomNormal_Text_AllThereIsDisappear:
	.string "Non ho altro da aggiungere.\n"
	.string "Sparisci…$"

BattleFrontier_BattlePikeRoomNormal_Text_LucyYouAgain:
	.string "FORTUNATA: Di nuovo tu…\p"
	.string "… … … … … …\p"
	.string "Ho dovuto superare mille avversità\n"
	.string "per diventare quella che sono…\p"
	.string "Non voglio continuare a perdere\n"
	.string "contro lo stesso avversario…\p"
	.string "… … … … … …\n"
	.string "Bene…  siamo alla resa dei conti…$"

BattleFrontier_BattlePikeRoomNormal_Text_NowComeOn:
	.string "Ora!\n"
	.string "Forza!$"

BattleFrontier_BattlePikeRoomNormal_Text_LucyFrontierPass:
	.string "FORTUNATA: … … … … … …\p"
	.string "Il tuo PASS PARCO, prego…$"

BattleFrontier_BattlePikeRoomNormal_Text_LuckSymbolTookGoldenShine:
	.string "Il SIMBOLO FORTUNA si è colorato\n"
	.string "d’oro!$"

BattleFrontier_BattlePikeRoomNormal_Text_IWontForget:
	.string "Questa me la lego al dito!\n"
	.string "Per sempre…$"

BattleFrontier_BattlePikeRoomNormal_Text_ChoseRoomNoHeal:
	.string "Salve…\p"
	.string "Ehm…\n"
	.string "Una bella sfortuna, la tua…\p"
	.string "Se solo avessi scelto un’altra sala,\n"
	.string "i tuoi POKéMON sarebbero stati rimessi\l"
	.string "in sesto…$"

BattleFrontier_BattlePikeRoomNormal_Text_ChoseRoomHealOne:
	.string "Salve…\p"
	.string "Poiché hai scelto questa sala,\n"
	.string "rimetterò in sesto un POKéMON…$"

BattleFrontier_BattlePikeRoomNormal_Text_ChoseRoomHealTwo:
	.string "Salve…\p"
	.string "Poiché hai scelto questa sala,\n"
	.string "rimetterò in sesto due POKéMON…$"

@ Unused
BattleFrontier_BattlePikeRoomNormal_Text_WillRestoreAllMons:
	.string "I welcome you…\p"
	.string "Giggle…\n"
	.string "You should thank your lucky stars…\p"
	.string "Since you have chosen this room,\n"
	.string "all your POKéMON will be restored…$"

BattleFrontier_BattlePikeRoomNormal_Text_ShallFetchOurMaster:
	.string "Vado a chiamare il nostro capo…$"

BattleFrontier_BattlePikeRoomNormal_Text_WillRestoreTwoMons:
	.string "Ah, la fortuna è dalla tua!\n"
	.string "Sono proprio di buon umore.\p"
	.string "Rimetterò in sesto due dei tuoi\n"
	.string "POKéMON!$"