ifeq ($(OS),Windows_NT)
export COMWRAP_GFX :=
export COMWRAP_PROC :=
export COMWRAP_JSON :=
export COMWRAP_DAT_AS :=
export COMWRAP_MUSIC :=
export COMWRAP_SND_AS :=
export COMWRAP_MID :=
export COMWRAP_ASM :=
export COMWRAP_CPP :=
export COMWRAP_CC :=
export COMWRAP_LD :=
export COMWRAP_ADJ :=
export COMWRAP_OCPY :=
export COMWRAP_FIX :=
export COMWRAP_CLEAN :=
export COMWRAP_TIDY :=
export COMWRAP = $(1)
else
export COMWRAP_GFX = \e[33mTransmogrifying\e[0m \e[1m$@\e[0m ...
export COMWRAP_PROC = \e[33mProcessing\e[0m \e[1m$@\e[0m ...
export COMWRAP_JSON = \e[33mProcessing\e[0m \e[1m$<\e[0m ...
export COMWRAP_DAT_AS \e[33mAssembling\e[0m \e[1m$@\e[0m ...
export COMWRAP_MUSIC = \e[35mConverting\e[0m \e[1m$@\e[0m ...
export COMWRAP_SND_AS = \e[35mAssembling\e[0m \e[1m$@\e[0m ...
export COMWRAP_MID = \e[35mProcessing\e[0m \e[1m$@\e[0m ...
export COMWRAP_ASM = \e[32mAssembling\e[0m \e[1m$@\e[0m ...
export COMWRAP_CPP = \e[33mCompiling\e[0m \e[1m$@\e[0m ...
export COMWRAP_CC = \e[34mCompiling\e[0m \e[1m$@\e[0m ...
export COMWRAP_LD = \e[31mLinking\e[0m \e[1m$@\e[0m ...
export COMWRAP_ADJ = \e[31mAdjusting\e[0m \e[1m$@\e[0m ...
export COMWRAP_OCPY = \e[37mCopying binary of\e[0m \e[1m$@\e[0m ...
export COMWRAP_FIX = \e[37mFixing\e[0m \e[1m$@\e[0m ...
export COMWRAP_CLEAN = \e[37mCleaning\e[0m the repository...
export COMWRAP_TIDY = \e[37mTidying\e[0m the repository...

ifeq ($(NOCOLOR),1)
export COMWRAP = $(1)
else
export COMWRAP = @echo -ne "   $(2)$$(REPLY=$$($(1) 2>&1); if [ "$$REPLY" != '' ]; then echo -e "\n$(1)\n$$REPLY";exit 1;fi)\n"
endif
endif

# Sometimes commands are complicated and make can’t handle it
COMMA := ,
SPACE :=
SPACE +=

export COMMA
export SPACE
