
SlateportCity_PokemonCenter_1F_Text_RaiseDifferentTypesOfPokemon:
	.string "Une petite astuce pour combattre?\p"
	.string "Il faut faire progresser divers types\n"
	.string "de POKéMON en même temps.\p"
	.string "Ce n’est pas bien d’avoir un seul\n"
	.string "POKéMON qui soit fort.\p"
	.string "S’il a un handicap à cause de son type,\n"
	.string "il n’aura aucune chance.$"

SlateportCity_PokemonCenter_1F_Text_TradedMonWithFriend:
	.string "J’échange des POKéMON avec mes amis.\p"
	.string "Quand le POKéMON échangé porte\n"
	.string "un objet, je suis encore plus contente.$"
