
SSTidalCorridor_Text_ScottBattleFrontierInvite:
	.string "TRETO: ¡Bueno, bueno!\n"
	.string "¡{PLAYER}{KUN}, {PLAYER}{KUN}!\p"
	.string "Me ha surgido algo, así que tengo que\n"
	.string "desembarcar, pero encantado de verte.\p"
	.string "¡Enhorabuena por el título\n"
	.string "de CAMPEÓN de la LIGA!\p"
	.string "Me gustaría invitarte a un lugar\n"
	.string "que creo que debes conocer.\p"
	.string "Es el…\n"
	.string "¡FRENTE de BATALLA!\p"
	.string "¡Pero no voy a contarte nada,\n"
	.string "quiero que seas tú quien lo descubra!\p"
	.string "He hablado con el CAPITÁN del barco\n"
	.string "sobre el tema.\p"
	.string "La próxima vez que tomes un ferry,\n"
	.string "podrás bajarte en el FRENTE de BATALLA.\p"
	.string "¡Bueno, {PLAYER}{KUN}, te estaré esperando\n"
	.string "en el FRENTE de BATALLA!$"

SSTidal_Text_FastCurrentsHopeYouEnjoyVoyage:
	.string "Este ferry ha sido construido para\n"
	.string "navegar en las corrientes rápidas.\p"
	.string "Os deseamos un agradable viaje.\n"
	.string "No dudéis en visitar el barco.$"

SSTidal_Text_HopeYouEnjoyVoyage:
	.string "Os deseamos un agradable viaje\n"
	.string "en nuestro ferry.$"

SSTidal_Text_MadeLandInSlateport:
	.string "Hemos arribado a CIUDAD PORTUAL.\n"
	.string "Gracias por navegar con nosotros.$"

SSTidal_Text_MadeLandInLilycove:
	.string "Hemos arribado a CIUDAD CALAGUA.\n"
	.string "Gracias por navegar con nosotros.$"

SSTidalCorridor_Text_CanRestInCabin2:
	.string "Creo que aún tardaremos algún tiempo\n"
	.string "en llegar a puerto.\p"
	.string "Puedes descansar en un camarote si\n"
	.string "lo deseas. El tuyo es el n.º 2.\p"
	.string "Tiene una cama blandita y cómoda.\n"
	.string "¡Vas a dormir como un bebé!$"

SSTidalCorridor_Text_WeveArrived:
	.string "¡Hemos llegado a puerto!$"

SSTidalCorridor_Text_VisitOtherCabins:
	.string "Visita otros camarotes, si quieres.\n"
	.string "Sin duda habrá ENTRENADORES aburridos\l"
	.string "del viaje que estarán deseando luchar.$"

SSTidalCorridor_Text_EnjoyYourCruise:
	.string "¡Disfruta del crucero!$"

SSTidalCorridor_Text_HorizonSpreadsBeyondPorthole:
	.string "La línea del horizonte se pierde\n"
	.string "en el infinito.$"

SSTidalCorridor_Text_BrineyWelcomeAboard:
	.string "SR. ARENQUE: ¡Hola, {PLAYER}{KUN}!\p"
	.string "¡Me han hecho capitán honorario\n"
	.string "del S.S. MAREA!\p"
	.string "¡Ahora soy el CAPITÁN ARENQUE!\p"
	.string "¿Sabes? Yo estaba retirado, pero al\n"
	.string "ver este barco tan majestuoso…\p"
	.string "se me despertó el bichito del mar.\n"
	.string "¡Tengo alma de marinero!$"

SSTidalCorridor_Text_Peeko:
	.string "PEEKO: Piko, pikopikopiko…$"

SSTidalCorridor_Text_Cabin1:
	.string "Camarote 1$"

SSTidalCorridor_Text_Cabin2:
	.string "Camarote 2$"

SSTidalCorridor_Text_Cabin3:
	.string "Camarote 3$"

SSTidalCorridor_Text_Cabin4:
	.string "Camarote 4$"
