
SSTidalCorridor_Text_ScottBattleFrontierInvite:
	.string "SCOTT: Ciao, {PLAYER}{KUN}!\p"
	.string "A causa di un impegno improvviso devo\n"
	.string "sbarcare, ma sono contento di vederti!\p"
	.string "Complimenti, CAMPIONE della LEGA!\p"
	.string "C’è un posto che una persona come\n"
	.string "te deve visitare.\p"
	.string "Si chiama…\n"
	.string "PARCO LOTTA!\p"
	.string "Che posto è?\n"
	.string "Capirai quando lo vedrai!\p"
	.string "Ho parlato con il CAPITANO a\n"
	.string "questo proposito.\p"
	.string "La prossima volta che sali sul\n"
	.string "traghetto, dovresti riuscire a\l"
	.string "salpare per il PARCO LOTTA.\p"
	.string "Okay, {PLAYER}{KUN}, ci vediamo\n"
	.string "al PARCO LOTTA!$"

SSTidal_Text_FastCurrentsHopeYouEnjoyVoyage:
	.string "Questo traghetto è stato costruito per\n"
	.string "solcare le correnti impetuose.\p"
	.string "Buon viaggio! I passeggeri sono\n"
	.string "invitati ad esplorare la nave.$"

SSTidal_Text_HopeYouEnjoyVoyage:
	.string "Buon viaggio sul nostro traghetto!$"

SSTidal_Text_MadeLandInSlateport:
	.string "Siamo approdati a PORTO SELCEPOLI.\n"
	.string "Grazie per aver viaggiato con noi.$"

SSTidal_Text_MadeLandInLilycove:
	.string "Siamo approdati a PORTO ALGHEPOLI.\n"
	.string "Grazie per aver viaggiato con noi.$"

SSTidalCorridor_Text_CanRestInCabin2:
	.string "Ci vorrà un po’ prima di toccare terra,\n"
	.string "direi…\p"
	.string "Puoi riposarti nella tua cabina, se ti\n"
	.string "va. La tua cabina è la nº 2.\p"
	.string "Il letto lì dentro è morbido e caldo.\n"
	.string "L’ho provato ed è davvero comodo!$"

SSTidalCorridor_Text_WeveArrived:
	.string "Siamo arrivati!$"

SSTidalCorridor_Text_VisitOtherCabins:
	.string "Va’ a visitare le altre cabine. Gli\n"
	.string "ALLENATORI annoiati dal lungo viaggio\l"
	.string "non aspettano altro che di lottare.$"

SSTidalCorridor_Text_EnjoyYourCruise:
	.string "Goditi la crociera!$"

SSTidalCorridor_Text_HorizonSpreadsBeyondPorthole:
	.string "Dall’oblò si può ammirare l’orizzonte.$"

SSTidalCorridor_Text_BrineyWelcomeAboard:
	.string "SIG. MARINO: Ti do il benvenuto\n"
	.string "a bordo, {PLAYER}{KUN}!\p"
	.string "Sono stato nominato capitano onorario\n"
	.string "della M/N MAREA!\p"
	.string "Ora puoi chiamarmi CAPITAN MARINO!\p"
	.string "Sai, ero andato in pensione, ma quando\n"
	.string "ho visto questa magnifica nave…\p"
	.string "Devo dire che ha risvegliato la mia\n"
	.string "indole marinara ormai assopita!$"

SSTidalCorridor_Text_Peeko:
	.string "PEEKO: Pee peekkooo…$"

SSTidalCorridor_Text_Cabin1:
	.string "Cabina 1$"

SSTidalCorridor_Text_Cabin2:
	.string "Cabina 2$"

SSTidalCorridor_Text_Cabin3:
	.string "Cabina 3$"

SSTidalCorridor_Text_Cabin4:
	.string "Cabina 4$"
