
BattleFrontier_BattleArenaLobby_Text_WelcomeToBattleArena:
	.string "Bienvenue au DOJO DE COMBAT!\p"
	.string "Ici, nous mettons à l’épreuve\n"
	.string "le cran des DRESSEURS!\p"
	.string "Je serai votre guide pour le\n"
	.string "TOURNOI K.O.!$"

BattleFrontier_BattleArenaLobby_Text_WishToTakeChallenge:
	.string "Voulez-vous relever le défi du\n"
	.string "DOJO DE COMBAT?$"

BattleFrontier_BattleArenaLobby_Text_AwaitAnotherChallenge:
	.string "Nous espérons que vous relèverez\n"
	.string "bientôt notre défi!$"

BattleFrontier_BattleArenaLobby_Text_ExplainChallenge:
	.string "Au DOJO DE COMBAT, vous participez à un\n"
	.string "TOURNOI K.O.\p"
	.string "Les participants s’inscrivent avec une\n"
	.string "équipe de trois POKéMON.\p"
	.string "Ces POKéMON doivent être placés dans\n"
	.string "l’ordre dans lequel ils apparaîtront.\p"
	.string "Pendant un combat, ils apparaîtront\n"
	.string "l’un après l’autre dans l’ordre\l"
	.string "prédéfini.\p"
	.string "Un POKéMON qui entre au combat doit\n"
	.string "y rester jusqu’à la fin.\p"
	.string "S’il n’y a pas de vainqueur au bout de\n"
	.string "trois tours, l’ARBITRE intervient.\p"
	.string "Si vous voulez interrompre le défi,\n"
	.string "veuillez sauvegarder la partie.\p"
	.string "Si vous ne sauvegardez pas, vous ne\n"
	.string "pourrez pas reprendre ce défi.\p"
	.string "Si vous mettez K.O. sept DRESSEURS\n"
	.string "à la suite, nous vous remettons des\l"
	.string "POINTS DE COMBAT.$"

BattleFrontier_BattleArenaLobby_Text_OkayToSave:
	.string "Avant de me suivre dans le DOJO DE\n"
	.string "COMBAT, vous devez sauvegarder. OK?$"

BattleFrontier_BattleArenaLobby_Text_WhichLevelMode:
	.string "Au DOJO DE COMBAT, vous avez le choix\n"
	.string "entre niveau 50 et niveau libre.\l"
	.string "Que choisissez-vous?$"

BattleFrontier_BattleArenaLobby_Text_SelectThreeMons:
	.string "Veuillez choisir les trois POKéMON que\n"
	.string "vous souhaitez inscrire.$"

BattleFrontier_BattleArenaLobby_Text_NotEnoughValidMonsLvOpen:
	.string "Je regrette, cher DRESSEUR!\p"
	.string "Vous n’avez pas trois POKéMON\n"
	.string "aptes à participer.\p"
	.string "Il vous faut trois POKéMON différents\n"
	.string "pour participer.\p"
	.string "Ils doivent aussi tenir des objets\n"
	.string "différents.\p"
	.string "Les OEUFS{STR_VAR_1} inaptes au combat.\p"
	.string "Revenez me voir quand vous aurez\n"
	.string "ce qu’il faut.$"

BattleFrontier_BattleArenaLobby_Text_NotEnoughValidMonsLv50:
	.string "Je regrette, cher DRESSEUR!\p"
	.string "Vous n’avez pas trois POKéMON\n"
	.string "aptes à participer.\p"
	.string "Il vous faut trois POKéMON différents\n"
	.string "pour participer.\p"
	.string "Il vous faut trois POKéMON différents\n"
	.string "de niveau 50 ou moins pour participer.\p"
	.string "Ils doivent aussi tenir des objets\n"
	.string "différents.\p"
	.string "Les OEUFS{STR_VAR_1} inaptes au combat.\p"
	.string "Revenez me voir quand vous aurez\n"
	.string "ce qu’il faut.$"

BattleFrontier_BattleArenaLobby_Text_GuideYouToArena:
	.string "Suivez-moi dans le DOJO DE COMBAT.$"

BattleFrontier_BattleArenaLobby_Text_DidntSaveBeforeShuttingDown:
	.string "Je regrette, cher DRESSEUR!\p"
	.string "Vous n’avez pas sauvegardé avant de\n"
	.string "quitter votre dernier défi.\p"
	.string "Dans ce cas, c’est la disqualification.\n"
	.string "Quel dommage!\p"
	.string "Bien entendu, vous pouvez recommencer\n"
	.string "un autre défi.$"

BattleFrontier_BattleArenaLobby_Text_CongratsOnSevenWins:
	.string "Toutes mes félicitations! Vous avez\n"
	.string "battu sept DRESSEURS à la suite!$"

BattleFrontier_BattleArenaLobby_Text_RecordAchievement:
	.string "Votre performance va être sauvegardée.\n"
	.string "Veuillez patienter.$"

@ Unused
BattleFrontier_BattleArenaLobby_Text_PresentYouWithPrize:
	.string "In commemoration of your 7-win streak,\n"
	.string "we present you with this prize.$"

@ Unused
BattleFrontier_BattleArenaLobby_Text_ReceivedPrize:
	.string "{PLAYER} received the prize\n"
	.string "{STR_VAR_1}.$"

@ Unused
BattleFrontier_BattleArenaLobby_Text_BagFullReturnForPrize:
	.string "Oh?\n"
	.string "Your BAG seems to be full.\p"
	.string "I urge you to clear space and\n"
	.string "return for your prize.$"

BattleFrontier_BattleArenaLobby_Text_ThankYouWaitWhileSave:
	.string "Merci d’avoir participé!\p"
	.string "Votre résultat va être sauvegardé.\n"
	.string "Veuillez patienter.$"

BattleFrontier_BattleArenaLobby_Text_AwaitAnotherChallenge2:
	.string "J’espère vous revoir bientôt au DOJO DE\n"
	.string "COMBAT.$"

BattleFrontier_BattleArenaLobby_Text_LookingForwardToArrivalSaveGame:
	.string "Nous vous attendions!\p"
	.string "Vous devez sauvegarder avant de me\n"
	.string "suivre dans le DOJO DE COMBAT.\l"
	.string "Veuillez patienter.$"

BattleFrontier_BattleArenaLobby_Text_RecordLastMatch:
	.string "J’enregistre votre dernier combat au\n"
	.string "DOJO DE COMBAT sur votre PASSE ZONE?$"

BattleFrontier_BattleArenaLobby_Text_BadIdeaToNotAttack:
	.string "J’ai perdu sur décision de l’ARBITRE…\n"
	.string "J’aurais dû attaquer…\p"
	.string "Mais je n’ai utilisé que des capacités\n"
	.string "défensives…$"

BattleFrontier_BattleArenaLobby_Text_LandingHitsWorked:
	.string "J’ai gagné sur décision de l’ARBITRE!\p"
	.string "Je n’ai pas arrêté de porter des coups\n"
	.string "et ça lui a plu!$"

BattleFrontier_BattleArenaLobby_Text_MatchWasDeclaredDraw:
	.string "Le combat a été déclaré nul.\p"
	.string "Il ne restait plus de temps et mes\n"
	.string "POKéMON et ceux de l’adversaire\l"
	.string "avaient le même niveau de PV.$"

BattleFrontier_BattleArenaLobby_Text_OrderOfMonsImportant:
	.string "Dans le DOJO DE COMBAT, l’ordre\n"
	.string "des POKéMON est très important.\p"
	.string "Si ton premier POKéMON a certains\n"
	.string "points faibles liés à son type, ton\l"
	.string "deuxième POKéMON doit les compenser,\l"
	.string "par exemple.\p"
	.string "Ça permet de créer une équipe efficace.$"

BattleFrontier_BattleArenaLobby_Text_RulesAreListed:
	.string "Règles du TOURNOI K.O.$"

BattleFrontier_BattleArenaLobby_Text_ReadWhichHeading:
	.string "Quel chapitre voulez-vous lire?$"

BattleFrontier_BattleArenaLobby_Text_ExplainBattleRules:
	.string "Le TOURNOI K.O. n’a pas les mêmes règles\n"
	.string "que les combats normaux.\p"
	.string "Tout d’abord, un combat ne dure que\n"
	.string "trois tours.\p"
	.string "S’il n’y a pas de vainqueur au bout de\n"
	.string "trois tours, l’ARBITRE intervient.\p"
	.string "L’ARBITRE basera son choix sur la façon\n"
	.string "dont les POKéMON ont combattu.\p"
	.string "Aussi, un POKéMON qui entre au combat\n"
	.string "doit y rester jusqu’à la fin.$"

BattleFrontier_BattleArenaLobby_Text_ExplainMindRules:
	.string "Le premier critère de jugement\n"
	.string "est le “mental”.\l"
	.string "C’est l’agressivité des concurrents.\p"
	.string "Cela dépend du nombre de capacités\n"
	.string "offensives qui ont été utilisées.$"

BattleFrontier_BattleArenaLobby_Text_ExplainSkillRules:
	.string "Le second critère de jugement est\n"
	.string "la “technique”.\l"
	.string "C’est l’efficacité avec laquelle les\l"
	.string "POKéMON utilisent leurs capacités.\p"
	.string "Si une capacité est réussie, le\n"
	.string "niveau de technique augmente.\p"
	.string "Si une capacité a échoué, le niveau de\n"
	.string "technique diminue.\p"
	.string "Pour une capacité offensive, le niveau\n"
	.string "de technique augmente si la capacité\l"
	.string "est “super efficace” et diminue\l"
	.string "si elle n’est “pas très efficace”.\p"
	.string "Les capacités telles qu’ABRI et\n"
	.string "DETECTION ne comptent pas.\p"
	.string "Si l’adversaire a utilisé ABRI ou\n"
	.string "DETECTION et que l’attaque de votre\l"
	.string "POKéMON n’a pas pu l’atteindre, son\l"
	.string "niveau de technique ne descend pas.$"

BattleFrontier_BattleArenaLobby_Text_ExplainBodyRules:
	.string "Le troisième critère de jugement est\n"
	.string "le “physique”.\l"
	.string "Il dépend du nombre de PV restant\l"
	.string "à la fin du combat.\p"
	.string "Cela prend en compte les PV que le\n"
	.string "POKéMON avait au début et ceux qui\l"
	.string "lui restent à la fin.$"

BattleFrontier_BattleArenaLobby_Text_CongratsOnDefeatingTycoon:
	.string "Vous avez arraché la victoire à la\n"
	.string "PRO DU DOJO et battu sept DRESSEURS!\p"
	.string "Félicitations pour cette magnifique\n"
	.string "performance!$"

BattleFrontier_BattleArenaLobby_Text_PleaseAcceptBattlePoints:
	.string "Cher DRESSEUR, votre cran vous\n"
	.string "rapporte des POINTS DE COMBAT.$"
