#ifndef GUARD_CONSTANTS_BATTLE_PALACE_H
#define GUARD_CONSTANTS_BATTLE_PALACE_H

#define BATTLE_PALACE_FUNC_0   0
#define BATTLE_PALACE_FUNC_1  1
#define BATTLE_PALACE_FUNC_2  2
#define BATTLE_PALACE_FUNC_3  3
#define BATTLE_PALACE_FUNC_4  4
#define BATTLE_PALACE_FUNC_GET_OPPONENT_INTRO  5
#define BATTLE_PALACE_FUNC_6  6
#define BATTLE_PALACE_FUNC_7  7
#define BATTLE_PALACE_FUNC_8  8
#define BATTLE_PALACE_FUNC_9  9

#endif //GUARD_CONSTANTS_BATTLE_PALACE_H
