#ifndef GUARD_CONSTANTS_BATTLE_MOVE_EFFECTS_H
#define GUARD_CONSTANTS_BATTLE_MOVE_EFFECTS_H

#define EFFECT_HIT                          0
#define EFFECT_SLEEP                        1
#define EFFECT_ABSORB                       2
#define EFFECT_EXPLOSION                    3
#define EFFECT_DREAM_EATER                  4
#define EFFECT_MIRROR_MOVE                  5
#define EFFECT_ATTACK_UP                    6
#define EFFECT_DEFENSE_UP                   7
#define EFFECT_SPEED_UP                     8
#define EFFECT_SPECIAL_ATTACK_UP            9
#define EFFECT_SPECIAL_DEFENSE_UP           10
#define EFFECT_ACCURACY_UP                  11
#define EFFECT_EVASION_UP                   12
#define EFFECT_SPECIAL_ATTACK_UP_3          13
#define EFFECT_ATTACK_DOWN                  14
#define EFFECT_DEFENSE_DOWN                 15
#define EFFECT_SPEED_DOWN                   16
#define EFFECT_SPECIAL_ATTACK_DOWN          17
#define EFFECT_SPECIAL_DEFENSE_DOWN         18
#define EFFECT_ACCURACY_DOWN                19
#define EFFECT_EVASION_DOWN                 20
#define EFFECT_HAZE                         21
#define EFFECT_BIDE                         22
#define EFFECT_RAMPAGE                      23
#define EFFECT_ROAR                         24
#define EFFECT_MULTI_HIT                    25
#define EFFECT_CONVERSION                   26
#define EFFECT_RESTORE_HP                   27
#define EFFECT_TOXIC                        28
#define EFFECT_LIGHT_SCREEN                 29
#define EFFECT_REST                         30
#define EFFECT_OHKO                         31
#define EFFECT_FUSION_COMBO                 32
#define EFFECT_SUPER_FANG                   33
#define EFFECT_ARG_FIXED_DAMAGE             34
#define EFFECT_UNUSED_35                    35
#define EFFECT_HEAL_BLOCK                   36
#define EFFECT_RECOIL_IF_MISS               37
#define EFFECT_MIST                         38
#define EFFECT_FOCUS_ENERGY                 39
#define EFFECT_UNUSED_40                    40
#define EFFECT_CONFUSE                      41
#define EFFECT_ATTACK_UP_2                  42
#define EFFECT_DEFENSE_UP_2                 43
#define EFFECT_SPEED_UP_2                   44
#define EFFECT_SPECIAL_ATTACK_UP_2          45
#define EFFECT_SPECIAL_DEFENSE_UP_2         46
#define EFFECT_ACCURACY_UP_2                47
#define EFFECT_EVASION_UP_2                 48
#define EFFECT_TRANSFORM                    49
#define EFFECT_ATTACK_DOWN_2                50
#define EFFECT_DEFENSE_DOWN_2               51
#define EFFECT_SPEED_DOWN_2                 52
#define EFFECT_SPECIAL_ATTACK_DOWN_2        53
#define EFFECT_SPECIAL_DEFENSE_DOWN_2       54
#define EFFECT_ACCURACY_DOWN_2              55
#define EFFECT_EVASION_DOWN_2               56
#define EFFECT_REFLECT                      57
#define EFFECT_POISON                       58
#define EFFECT_PARALYZE                     59
#define EFFECT_TWO_TURNS_ATTACK             60
#define EFFECT_UNUSED_61                    61
#define EFFECT_SUBSTITUTE                   62
#define EFFECT_UNUSED_63                    63
#define EFFECT_RAGE                         64
#define EFFECT_MIMIC                        65
#define EFFECT_METRONOME                    66
#define EFFECT_LEECH_SEED                   67
#define EFFECT_DO_NOTHING                   68
#define EFFECT_DISABLE                      69
#define EFFECT_LEVEL_DAMAGE                 70
#define EFFECT_PSYWAVE                      71
#define EFFECT_COUNTER                      72
#define EFFECT_ENCORE                       73
#define EFFECT_PAIN_SPLIT                   74
#define EFFECT_SNORE                        75
#define EFFECT_CONVERSION_2                 76
#define EFFECT_LOCK_ON                      77
#define EFFECT_SKETCH                       78
#define EFFECT_SLEEP_TALK                   79
#define EFFECT_DESTINY_BOND                 80
#define EFFECT_FLAIL                        81
#define EFFECT_SPITE                        82
#define EFFECT_FALSE_SWIPE                  83
#define EFFECT_HEAL_BELL                    84
#define EFFECT_TRIPLE_KICK                  85
#define EFFECT_UNUSED_86                    86
#define EFFECT_MEAN_LOOK                    87
#define EFFECT_NIGHTMARE                    88
#define EFFECT_MINIMIZE                     89
#define EFFECT_CURSE                        90
#define EFFECT_HEALING_WISH                 91
#define EFFECT_PROTECT                      92
#define EFFECT_SPIKES                       93
#define EFFECT_FORESIGHT                    94
#define EFFECT_PERISH_SONG                  95
#define EFFECT_SANDSTORM                    96
#define EFFECT_ENDURE                       97
#define EFFECT_ROLLOUT                      98
#define EFFECT_SWAGGER                      99
#define EFFECT_FURY_CUTTER                  100
#define EFFECT_ATTRACT                      101
#define EFFECT_RETURN                       102
#define EFFECT_PRESENT                      103
#define EFFECT_FRUSTRATION                  104
#define EFFECT_SAFEGUARD                    105
#define EFFECT_MAGNITUDE                    106
#define EFFECT_BATON_PASS                   107
#define EFFECT_PURSUIT                      108
#define EFFECT_UNUSED_109                   109
#define EFFECT_UNUSED_110                   110
#define EFFECT_CAPTIVATE                    111
#define EFFECT_MORNING_SUN                  112
#define EFFECT_SYNTHESIS                    113
#define EFFECT_MOONLIGHT                    114
#define EFFECT_HIDDEN_POWER                 115
#define EFFECT_RAIN_DANCE                   116
#define EFFECT_SUNNY_DAY                    117
#define EFFECT_UNUSED_118                   118
#define EFFECT_FELL_STINGER                 119
#define EFFECT_BELLY_DRUM                   120
#define EFFECT_PSYCH_UP                     121
#define EFFECT_MIRROR_COAT                  122
#define EFFECT_SKULL_BASH                   123
#define EFFECT_EARTHQUAKE                   124
#define EFFECT_FUTURE_SIGHT                 125
#define EFFECT_GUST                         126
#define EFFECT_SOLAR_BEAM                   127
#define EFFECT_THUNDER                      128
#define EFFECT_TELEPORT                     129
#define EFFECT_BEAT_UP                      130
#define EFFECT_SEMI_INVULNERABLE            131
#define EFFECT_DEFENSE_CURL                 132
#define EFFECT_SOFTBOILED                   133
#define EFFECT_FAKE_OUT                     134
#define EFFECT_UPROAR                       135
#define EFFECT_STOCKPILE                    136
#define EFFECT_SPIT_UP                      137
#define EFFECT_SWALLOW                      138
#define EFFECT_WORRY_SEED                   139
#define EFFECT_HAIL                         140
#define EFFECT_TORMENT                      141
#define EFFECT_FLATTER                      142
#define EFFECT_WILL_O_WISP                  143
#define EFFECT_MEMENTO                      144
#define EFFECT_FACADE                       145
#define EFFECT_FOCUS_PUNCH                  146
#define EFFECT_DOUBLE_POWER_ON_ARG_STATUS   147
#define EFFECT_FOLLOW_ME                    148
#define EFFECT_NATURE_POWER                 149
#define EFFECT_CHARGE                       150
#define EFFECT_TAUNT                        151
#define EFFECT_HELPING_HAND                 152
#define EFFECT_TRICK                        153
#define EFFECT_ROLE_PLAY                    154
#define EFFECT_WISH                         155
#define EFFECT_ASSIST                       156
#define EFFECT_INGRAIN                      157
#define EFFECT_MAGIC_COAT                   158
#define EFFECT_RECYCLE                      159
#define EFFECT_REVENGE                      160
#define EFFECT_BRICK_BREAK                  161
#define EFFECT_YAWN                         162
#define EFFECT_KNOCK_OFF                    163
#define EFFECT_ENDEAVOR                     164
#define EFFECT_ERUPTION                     165
#define EFFECT_SKILL_SWAP                   166
#define EFFECT_IMPRISON                     167
#define EFFECT_REFRESH                      168
#define EFFECT_GRUDGE                       169
#define EFFECT_SNATCH                       170
#define EFFECT_LOW_KICK                     171
#define EFFECT_UNUSED_172                   172
#define EFFECT_TEETER_DANCE                 173
#define EFFECT_HIT_ESCAPE                   174
#define EFFECT_MUD_SPORT                    175
#define EFFECT_WEATHER_BALL                 176
#define EFFECT_TICKLE                       177
#define EFFECT_COSMIC_POWER                 178
#define EFFECT_SKY_UPPERCUT                 179
#define EFFECT_BULK_UP                      180
#define EFFECT_PLACEHOLDER                  181
#define EFFECT_WATER_SPORT                  182
#define EFFECT_CALM_MIND                    183
#define EFFECT_DRAGON_DANCE                 184
#define EFFECT_CAMOUFLAGE                   185
#define EFFECT_PLEDGE                       186
#define EFFECT_FLING                        187
#define EFFECT_NATURAL_GIFT                 188
#define EFFECT_UNUSED_189                   189
#define EFFECT_WRING_OUT                    190
#define EFFECT_UNUSED_191                   191
#define EFFECT_ASSURANCE                    192
#define EFFECT_TRUMP_CARD                   193
#define EFFECT_ACROBATICS                   194
#define EFFECT_HEAT_CRASH                   195
#define EFFECT_PUNISHMENT                   196
#define EFFECT_STORED_POWER                 197
#define EFFECT_ELECTRO_BALL                 198
#define EFFECT_GYRO_BALL                    199
#define EFFECT_ECHOED_VOICE                 200
#define EFFECT_PAYBACK                      201
#define EFFECT_ROUND                        202
#define EFFECT_BRINE                        203
#define EFFECT_UNUSED_204                   204
#define EFFECT_RETALIATE                    205
#define EFFECT_BULLDOZE                     206
#define EFFECT_FOUL_PLAY                    207
#define EFFECT_PSYSHOCK                     208
#define EFFECT_ROOST                        209
#define EFFECT_GRAVITY                      210
#define EFFECT_MIRACLE_EYE                  211
#define EFFECT_TAILWIND                     212
#define EFFECT_EMBARGO                      213
#define EFFECT_AQUA_RING                    214
#define EFFECT_TRICK_ROOM                   215
#define EFFECT_WONDER_ROOM                  216
#define EFFECT_MAGIC_ROOM                   217
#define EFFECT_MAGNET_RISE                  218
#define EFFECT_TOXIC_SPIKES                 219
#define EFFECT_GASTRO_ACID                  220
#define EFFECT_STEALTH_ROCK                 221
#define EFFECT_TELEKINESIS                  222
#define EFFECT_POWER_SWAP                   223
#define EFFECT_GUARD_SWAP                   224
#define EFFECT_HEART_SWAP                   225
#define EFFECT_POWER_SPLIT                  226
#define EFFECT_GUARD_SPLIT                  227
#define EFFECT_STICKY_WEB                   228
#define EFFECT_METAL_BURST                  229
#define EFFECT_LUCKY_CHANT                  230
#define EFFECT_SUCKER_PUNCH                 231
#define EFFECT_SIMPLE_BEAM                  232
#define EFFECT_ENTRAINMENT                  233
#define EFFECT_HEAL_PULSE                   234
#define EFFECT_QUASH                        235
#define EFFECT_ION_DELUGE                   236
#define EFFECT_FREEZE_DRY                   237
#define EFFECT_TOPSY_TURVY                  238
#define EFFECT_MISTY_TERRAIN                239
#define EFFECT_GRASSY_TERRAIN               240
#define EFFECT_ELECTRIC_TERRAIN             241
#define EFFECT_PSYCHIC_TERRAIN              242
#define EFFECT_ATTACK_ACCURACY_UP           243
#define EFFECT_ATTACK_SPATK_UP              244
#define EFFECT_HURRICANE                    245
#define EFFECT_TWO_TYPED_MOVE               246
#define EFFECT_ME_FIRST                     247
#define EFFECT_QUIVER_DANCE                 248
#define EFFECT_COIL                         249
#define EFFECT_ELECTRIFY                    250
#define EFFECT_REFLECT_TYPE                 251
#define EFFECT_SOAK                         252
#define EFFECT_GROWTH                       253
#define EFFECT_LAST_RESORT                  254
#define EFFECT_SHELL_SMASH                  255
#define EFFECT_SHIFT_GEAR                   256
#define EFFECT_DEFENSE_UP_3                 257
#define EFFECT_NOBLE_ROAR                   258
#define EFFECT_VENOM_DRENCH                 259
#define EFFECT_TOXIC_THREAD                 260
#define EFFECT_HIT_SWITCH_TARGET            261
#define EFFECT_FINAL_GAMBIT                 262
#define EFFECT_CHANGE_TYPE_ON_ITEM          263
#define EFFECT_AUTOTOMIZE                   264
#define EFFECT_COPYCAT                      265
#define EFFECT_DEFOG                        266
#define EFFECT_HIT_ENEMY_HEAL_ALLY          267
#define EFFECT_UNUSED_268                   268
#define EFFECT_SYNCHRONOISE                 269
#define EFFECT_PSYCHO_SHIFT                 270
#define EFFECT_POWER_TRICK                  271
#define EFFECT_UNUSED_272                   272
#define EFFECT_AFTER_YOU                    273
#define EFFECT_BESTOW                       274
#define EFFECT_ROTOTILLER                   275
#define EFFECT_FLOWER_SHIELD                276
#define EFFECT_UNUSED_277                   277
#define EFFECT_SPEED_SWAP                   278
#define EFFECT_UNUSED_279                   279
#define EFFECT_REVELATION_DANCE             280
#define EFFECT_AURORA_VEIL                  281
#define EFFECT_THIRD_TYPE                   282
#define EFFECT_UNUSED_283                   283
#define EFFECT_UNUSED_284                   284
#define EFFECT_ACUPRESSURE                  285
#define EFFECT_AROMATIC_MIST                286
#define EFFECT_POWDER                       287
#define EFFECT_BELCH                        288
#define EFFECT_PARTING_SHOT                 289
#define EFFECT_MAT_BLOCK                    290
#define EFFECT_STOMPING_TANTRUM             291
#define EFFECT_INSTRUCT                     292
#define EFFECT_UNUSED_293                   293
#define EFFECT_LASER_FOCUS                  294
#define EFFECT_MAGNETIC_FLUX                295
#define EFFECT_GEAR_UP                      296
#define EFFECT_UNUSED_297                   297
#define EFFECT_UNUSED_298                   298
#define EFFECT_STRENGTH_SAP                 299
#define EFFECT_MIND_BLOWN                   300
#define EFFECT_PURIFY                       301
#define EFFECT_FAIL_IF_NOT_ARG_TYPE         302
#define EFFECT_SHORE_UP                     303
#define EFFECT_GEOMANCY                     304
#define EFFECT_FAIRY_LOCK                   305
#define EFFECT_ALLY_SWITCH                  306
#define EFFECT_RELIC_SONG                   307
#define EFFECT_BODY_PRESS                   308
#define EFFECT_EERIE_SPELL                  309
#define EFFECT_JUNGLE_HEALING               310
#define EFFECT_COACHING                     311
#define EFFECT_LASH_OUT                     312
#define EFFECT_GRASSY_GLIDE                 313
#define EFFECT_DYNAMAX_DOUBLE_DMG           314
#define EFFECT_DECORATE                     315
#define EFFECT_SNIPE_SHOT                   316
#define EFFECT_RECOIL_HP_25                 317
#define EFFECT_STUFF_CHEEKS                 318
#define EFFECT_GRAV_APPLE                   319
#define EFFECT_GLITZY_GLOW                  320
#define EFFECT_BADDY_BAD                    321
#define EFFECT_SAPPY_SEED                   322
#define EFFECT_FREEZY_FROST                 323
#define EFFECT_SPARKLY_SWIRL                324
#define EFFECT_PLASMA_FISTS                 325
#define EFFECT_HYPERSPACE_FURY              326
#define EFFECT_AURA_WHEEL                   327
#define EFFECT_PHOTON_GEYSER                328
#define EFFECT_SHELL_SIDE_ARM               329
#define EFFECT_TERRAIN_PULSE                330
#define EFFECT_NO_RETREAT                   331
#define EFFECT_TAR_SHOT                     332
#define EFFECT_POLTERGEIST                  333
#define EFFECT_OCTOLOCK                     334
#define EFFECT_CLANGOROUS_SOUL              335
#define EFFECT_BOLT_BEAK                    336
#define EFFECT_SKY_DROP                     337
#define EFFECT_EXPANDING_FORCE              338
#define EFFECT_METEOR_BEAM                  339
#define EFFECT_RISING_VOLTAGE               340
#define EFFECT_BEAK_BLAST                   341
#define EFFECT_COURT_CHANGE                 342
#define EFFECT_STEEL_BEAM                   343
#define EFFECT_EXTREME_EVOBOOST             344
#define EFFECT_HIT_SET_REMOVE_TERRAIN       345
#define EFFECT_DARK_VOID                    346
#define EFFECT_UNUSED_347                   347
#define EFFECT_VICTORY_DANCE                348
#define EFFECT_TEATIME                      349
#define EFFECT_ATTACK_UP_USER_ALLY          350
#define EFFECT_SHELL_TRAP                   351
#define EFFECT_PSYBLADE                     352
#define EFFECT_HYDRO_STEAM                  353
#define EFFECT_UNUSED_354                   354
#define EFFECT_UNUSED_355                   355
#define EFFECT_REVIVAL_BLESSING             356
#define EFFECT_SNOWSCAPE                    357
#define EFFECT_UNUSED_358                   358
#define EFFECT_TAKE_HEART                   359
#define EFFECT_COLLISION_COURSE             360
#define EFFECT_CORROSIVE_GAS                361
#define EFFECT_POPULATION_BOMB              362
#define EFFECT_SALT_CURE                    363
#define EFFECT_CHILLY_RECEPTION             364
#define EFFECT_MAX_MOVE                     365
#define EFFECT_GLAIVE_RUSH                  366
#define EFFECT_RAGING_BULL                  367
#define EFFECT_RAGE_FIST                    368
#define EFFECT_DOODLE                       369

#define NUM_BATTLE_MOVE_EFFECTS             370

#endif  // GUARD_CONSTANTS_BATTLE_MOVE_EFFECTS_H
