#ifndef GUARD_CONSTANTS_BATTLE_TENT_H
#define GUARD_CONSTANTS_BATTLE_TENT_H

#define TENT_MIN_LEVEL 30

// The number of battles in each Battle Tent challenge.
// Battle Tent equivalent of FRONTIER_STAGES_PER_CHALLENGE.
#define TENT_STAGES_PER_CHALLENGE  3

#define VERDANTURF_TENT_FUNC_INIT                0
#define VERDANTURF_TENT_FUNC_GET_PRIZE           1
#define VERDANTURF_TENT_FUNC_SET_PRIZE           2
#define VERDANTURF_TENT_FUNC_SET_OPPONENT_GFX    3
#define VERDANTURF_TENT_FUNC_GET_OPPONENT_INTRO  4
#define VERDANTURF_TENT_FUNC_SAVE                5
#define VERDANTURF_TENT_FUNC_SET_RANDOM_PRIZE    6
#define VERDANTURF_TENT_FUNC_GIVE_PRIZE          7

#define FALLARBOR_TENT_FUNC_INIT               0
#define FALLARBOR_TENT_FUNC_GET_PRIZE          1
#define FALLARBOR_TENT_FUNC_SET_PRIZE          2
#define FALLARBOR_TENT_FUNC_SAVE               3
#define FALLARBOR_TENT_FUNC_SET_RANDOM_PRIZE   4
#define FALLARBOR_TENT_FUNC_GIVE_PRIZE         5
#define FALLARBOR_TENT_FUNC_GET_OPPONENT_NAME  6

#define SLATEPORT_TENT_FUNC_INIT                    0
#define SLATEPORT_TENT_FUNC_GET_PRIZE               1
#define SLATEPORT_TENT_FUNC_SET_PRIZE               2
#define SLATEPORT_TENT_FUNC_SAVE                    3
#define SLATEPORT_TENT_FUNC_SET_RANDOM_PRIZE        4
#define SLATEPORT_TENT_FUNC_GIVE_PRIZE              5
#define SLATEPORT_TENT_FUNC_SELECT_RENT_MONS        6
#define SLATEPORT_TENT_FUNC_SWAP_RENT_MONS          7
#define SLATEPORT_TENT_FUNC_GENERATE_OPPONENT_MONS  8
#define SLATEPORT_TENT_FUNC_GENERATE_RENTAL_MONS    9

#endif // GUARD_CONSTANTS_BATTLE_TENT_H
