#ifndef GUARD_CONSTANTS_BATTLE_MOVE_EFFECTS_H
#define GUARD_CONSTANTS_BATTLE_MOVE_EFFECTS_H

#define EFFECT_HIT                          0
#define EFFECT_SLEEP                        1
#define EFFECT_POISON_HIT                   2
#define EFFECT_ABSORB                       3
#define EFFECT_BURN_HIT                     4
#define EFFECT_FREEZE_HIT                   5
#define EFFECT_PARALYZE_HIT                 6
#define EFFECT_EXPLOSION                    7
#define EFFECT_DREAM_EATER                  8
#define EFFECT_MIRROR_MOVE                  9
#define EFFECT_ATTACK_UP                    10
#define EFFECT_DEFENSE_UP                   11
#define EFFECT_SPEED_UP                     12
#define EFFECT_SPECIAL_ATTACK_UP            13
#define EFFECT_SPECIAL_DEFENSE_UP           14
#define EFFECT_ACCURACY_UP                  15
#define EFFECT_EVASION_UP                   16
#define EFFECT_SPECIAL_ATTACK_UP_3          17
#define EFFECT_ATTACK_DOWN                  18
#define EFFECT_DEFENSE_DOWN                 19
#define EFFECT_SPEED_DOWN                   20
#define EFFECT_SPECIAL_ATTACK_DOWN          21
#define EFFECT_SPECIAL_DEFENSE_DOWN         22
#define EFFECT_ACCURACY_DOWN                23
#define EFFECT_EVASION_DOWN                 24
#define EFFECT_HAZE                         25
#define EFFECT_BIDE                         26
#define EFFECT_RAMPAGE                      27
#define EFFECT_ROAR                         28
#define EFFECT_MULTI_HIT                    29
#define EFFECT_CONVERSION                   30
#define EFFECT_FLINCH_HIT                   31
#define EFFECT_RESTORE_HP                   32
#define EFFECT_TOXIC                        33
#define EFFECT_PAY_DAY                      34
#define EFFECT_LIGHT_SCREEN                 35
#define EFFECT_TRI_ATTACK                   36
#define EFFECT_REST                         37
#define EFFECT_OHKO                         38
#define EFFECT_FUSION_COMBO                 39
#define EFFECT_SUPER_FANG                   40
#define EFFECT_DRAGON_RAGE                  41
#define EFFECT_TRAP                         42
#define EFFECT_HEAL_BLOCK                   43
#define EFFECT_RECOIL_IF_MISS               44
#define EFFECT_MIST                         45
#define EFFECT_FOCUS_ENERGY                 46
#define EFFECT_RECOIL_25                    47
#define EFFECT_CONFUSE                      48
#define EFFECT_ATTACK_UP_2                  49
#define EFFECT_DEFENSE_UP_2                 50
#define EFFECT_SPEED_UP_2                   51
#define EFFECT_SPECIAL_ATTACK_UP_2          52
#define EFFECT_SPECIAL_DEFENSE_UP_2         53
#define EFFECT_ACCURACY_UP_2                54
#define EFFECT_EVASION_UP_2                 55
#define EFFECT_TRANSFORM                    56
#define EFFECT_ATTACK_DOWN_2                57
#define EFFECT_DEFENSE_DOWN_2               58
#define EFFECT_SPEED_DOWN_2                 59
#define EFFECT_SPECIAL_ATTACK_DOWN_2        60
#define EFFECT_SPECIAL_DEFENSE_DOWN_2       61
#define EFFECT_ACCURACY_DOWN_2              62
#define EFFECT_EVASION_DOWN_2               63
#define EFFECT_REFLECT                      64
#define EFFECT_POISON                       65
#define EFFECT_PARALYZE                     66
#define EFFECT_ATTACK_DOWN_HIT              67
#define EFFECT_DEFENSE_DOWN_HIT             68
#define EFFECT_SPEED_DOWN_HIT               69
#define EFFECT_SPECIAL_ATTACK_DOWN_HIT      70
#define EFFECT_SPECIAL_DEFENSE_DOWN_HIT     71
#define EFFECT_ACCURACY_DOWN_HIT            72
#define EFFECT_EVASION_DOWN_HIT             73
#define EFFECT_TWO_TURNS_ATTACK             74
#define EFFECT_CONFUSE_HIT                  75
#define EFFECT_VITAL_THROW                  76
#define EFFECT_SUBSTITUTE                   77
#define EFFECT_RECHARGE                     78
#define EFFECT_RAGE                         79
#define EFFECT_MIMIC                        80
#define EFFECT_METRONOME                    81
#define EFFECT_LEECH_SEED                   82
#define EFFECT_DO_NOTHING                   83
#define EFFECT_DISABLE                      84
#define EFFECT_LEVEL_DAMAGE                 85
#define EFFECT_PSYWAVE                      86
#define EFFECT_COUNTER                      87
#define EFFECT_ENCORE                       88
#define EFFECT_PAIN_SPLIT                   89
#define EFFECT_SNORE                        90
#define EFFECT_CONVERSION_2                 91
#define EFFECT_LOCK_ON                      92
#define EFFECT_SKETCH                       93
#define EFFECT_HAMMER_ARM                   94
#define EFFECT_SLEEP_TALK                   95
#define EFFECT_DESTINY_BOND                 96
#define EFFECT_FLAIL                        97
#define EFFECT_SPITE                        98
#define EFFECT_FALSE_SWIPE                  99
#define EFFECT_HEAL_BELL                    100
#define EFFECT_ALWAYS_CRIT                  101
#define EFFECT_TRIPLE_KICK                  102
#define EFFECT_THIEF                        103
#define EFFECT_MEAN_LOOK                    104
#define EFFECT_NIGHTMARE                    105
#define EFFECT_MINIMIZE                     106
#define EFFECT_CURSE                        107
#define EFFECT_HEALING_WISH                 108
#define EFFECT_PROTECT                      109
#define EFFECT_SPIKES                       110
#define EFFECT_FORESIGHT                    111
#define EFFECT_PERISH_SONG                  112
#define EFFECT_SANDSTORM                    113
#define EFFECT_ENDURE                       114
#define EFFECT_ROLLOUT                      115
#define EFFECT_SWAGGER                      116
#define EFFECT_FURY_CUTTER                  117
#define EFFECT_ATTRACT                      118
#define EFFECT_RETURN                       119
#define EFFECT_PRESENT                      120
#define EFFECT_FRUSTRATION                  121
#define EFFECT_SAFEGUARD                    122
#define EFFECT_UNUSED_125                   123
#define EFFECT_MAGNITUDE                    124
#define EFFECT_BATON_PASS                   125
#define EFFECT_PURSUIT                      126
#define EFFECT_RAPID_SPIN                   127
#define EFFECT_SONICBOOM                    128
#define EFFECT_CAPTIVATE                    129
#define EFFECT_MORNING_SUN                  130
#define EFFECT_SYNTHESIS                    131
#define EFFECT_MOONLIGHT                    132
#define EFFECT_HIDDEN_POWER                 133
#define EFFECT_RAIN_DANCE                   134
#define EFFECT_SUNNY_DAY                    135
#define EFFECT_DEFENSE_UP_HIT               136
#define EFFECT_ATTACK_UP_HIT                137
#define EFFECT_ALL_STATS_UP_HIT             138
#define EFFECT_FELL_STINGER                 139
#define EFFECT_BELLY_DRUM                   140
#define EFFECT_PSYCH_UP                     141
#define EFFECT_MIRROR_COAT                  142
#define EFFECT_SKULL_BASH                   143
#define EFFECT_TWISTER                      144
#define EFFECT_EARTHQUAKE                   145
#define EFFECT_FUTURE_SIGHT                 146
#define EFFECT_GUST                         147
#define EFFECT_FLINCH_MINIMIZE_HIT          148
#define EFFECT_SOLAR_BEAM                   149
#define EFFECT_THUNDER                      150
#define EFFECT_TELEPORT                     151
#define EFFECT_BEAT_UP                      152
#define EFFECT_SEMI_INVULNERABLE            153
#define EFFECT_DEFENSE_CURL                 154
#define EFFECT_SOFTBOILED                   155
#define EFFECT_FAKE_OUT                     156
#define EFFECT_UPROAR                       157
#define EFFECT_STOCKPILE                    158
#define EFFECT_SPIT_UP                      159
#define EFFECT_SWALLOW                      160
#define EFFECT_WORRY_SEED                   161
#define EFFECT_HAIL                         162
#define EFFECT_TORMENT                      163
#define EFFECT_FLATTER                      164
#define EFFECT_WILL_O_WISP                  165
#define EFFECT_MEMENTO                      166
#define EFFECT_FACADE                       167
#define EFFECT_FOCUS_PUNCH                  168
#define EFFECT_SMELLINGSALT                 169
#define EFFECT_FOLLOW_ME                    170
#define EFFECT_NATURE_POWER                 171
#define EFFECT_CHARGE                       172
#define EFFECT_TAUNT                        173
#define EFFECT_HELPING_HAND                 174
#define EFFECT_TRICK                        175
#define EFFECT_ROLE_PLAY                    176
#define EFFECT_WISH                         177
#define EFFECT_ASSIST                       178
#define EFFECT_INGRAIN                      179
#define EFFECT_SUPERPOWER                   180
#define EFFECT_MAGIC_COAT                   181
#define EFFECT_RECYCLE                      182
#define EFFECT_REVENGE                      183
#define EFFECT_BRICK_BREAK                  184
#define EFFECT_YAWN                         185
#define EFFECT_KNOCK_OFF                    186
#define EFFECT_ENDEAVOR                     187
#define EFFECT_ERUPTION                     188
#define EFFECT_SKILL_SWAP                   189
#define EFFECT_IMPRISON                     190
#define EFFECT_REFRESH                      191
#define EFFECT_GRUDGE                       192
#define EFFECT_SNATCH                       193
#define EFFECT_LOW_KICK                     194
#define EFFECT_SECRET_POWER                 195
#define EFFECT_RECOIL_33                    196
#define EFFECT_TEETER_DANCE                 197
#define EFFECT_HIT_ESCAPE                   198
#define EFFECT_MUD_SPORT                    199
#define EFFECT_POISON_FANG                  200
#define EFFECT_WEATHER_BALL                 201
#define EFFECT_OVERHEAT                     202
#define EFFECT_TICKLE                       203
#define EFFECT_COSMIC_POWER                 204
#define EFFECT_SKY_UPPERCUT                 205
#define EFFECT_BULK_UP                      206
#define EFFECT_PLACEHOLDER                  207
#define EFFECT_WATER_SPORT                  208
#define EFFECT_CALM_MIND                    209
#define EFFECT_DRAGON_DANCE                 210
#define EFFECT_CAMOUFLAGE                   211

// New move effects
#define EFFECT_PLEDGE                       212
#define EFFECT_FLING                        213
#define EFFECT_NATURAL_GIFT                 214
#define EFFECT_WAKE_UP_SLAP                 215
#define EFFECT_WRING_OUT                    216
#define EFFECT_HEX                          217
#define EFFECT_ASSURANCE                    218
#define EFFECT_TRUMP_CARD                   219
#define EFFECT_ACROBATICS                   220
#define EFFECT_HEAT_CRASH                   221
#define EFFECT_PUNISHMENT                   222
#define EFFECT_STORED_POWER                 223
#define EFFECT_ELECTRO_BALL                 224
#define EFFECT_GYRO_BALL                    225
#define EFFECT_ECHOED_VOICE                 226
#define EFFECT_PAYBACK                      227
#define EFFECT_ROUND                        228
#define EFFECT_BRINE                        229
#define EFFECT_VENOSHOCK                    230
#define EFFECT_RETALIATE                    231
#define EFFECT_BULLDOZE                     232
#define EFFECT_FOUL_PLAY                    233
#define EFFECT_PSYSHOCK                     234
#define EFFECT_ROOST                        235
#define EFFECT_GRAVITY                      236
#define EFFECT_MIRACLE_EYE                  237
#define EFFECT_TAILWIND                     238
#define EFFECT_EMBARGO                      239
#define EFFECT_AQUA_RING                    240
#define EFFECT_TRICK_ROOM                   241
#define EFFECT_WONDER_ROOM                  242
#define EFFECT_MAGIC_ROOM                   243
#define EFFECT_MAGNET_RISE                  244
#define EFFECT_TOXIC_SPIKES                 245
#define EFFECT_GASTRO_ACID                  246
#define EFFECT_STEALTH_ROCK                 247
#define EFFECT_TELEKINESIS                  248
#define EFFECT_POWER_SWAP                   249
#define EFFECT_GUARD_SWAP                   250
#define EFFECT_HEART_SWAP                   251
#define EFFECT_POWER_SPLIT                  252
#define EFFECT_GUARD_SPLIT                  253
#define EFFECT_STICKY_WEB                   254
#define EFFECT_METAL_BURST                  255
#define EFFECT_LUCKY_CHANT                  256
#define EFFECT_SUCKER_PUNCH                 257
#define EFFECT_SPECIAL_DEFENSE_DOWN_HIT_2   258
#define EFFECT_SIMPLE_BEAM                  259
#define EFFECT_ENTRAINMENT                  260
#define EFFECT_HEAL_PULSE                   261
#define EFFECT_QUASH                        262
#define EFFECT_ION_DELUGE                   263
#define EFFECT_FREEZE_DRY                   264
#define EFFECT_TOPSY_TURVY                  265
#define EFFECT_MISTY_TERRAIN                266
#define EFFECT_GRASSY_TERRAIN               267
#define EFFECT_ELECTRIC_TERRAIN             268
#define EFFECT_PSYCHIC_TERRAIN              269
#define EFFECT_ATTACK_ACCURACY_UP           270
#define EFFECT_ATTACK_SPATK_UP              271
#define EFFECT_HURRICANE                    272
#define EFFECT_TWO_TYPED_MOVE               273
#define EFFECT_ME_FIRST                     274
#define EFFECT_SPEED_UP_HIT                 275
#define EFFECT_QUIVER_DANCE                 276
#define EFFECT_COIL                         277
#define EFFECT_ELECTRIFY                    278
#define EFFECT_SCALD                        279
#define EFFECT_REFLECT_TYPE                 280
#define EFFECT_SOAK                         281
#define EFFECT_GROWTH                       282
#define EFFECT_CLOSE_COMBAT                 283
#define EFFECT_LAST_RESORT                  284
#define EFFECT_RECOIL_33_STATUS             285
#define EFFECT_FLINCH_STATUS                286
#define EFFECT_RECOIL_50                    287
#define EFFECT_SHELL_SMASH                  288
#define EFFECT_SHIFT_GEAR                   289
#define EFFECT_DEFENSE_UP_3                 290
#define EFFECT_NOBLE_ROAR                   291
#define EFFECT_VENOM_DRENCH                 292
#define EFFECT_TOXIC_THREAD                 293
#define EFFECT_CLEAR_SMOG                   294
#define EFFECT_HIT_SWITCH_TARGET            295
#define EFFECT_FINAL_GAMBIT                 296
#define EFFECT_CHANGE_TYPE_ON_ITEM          297
#define EFFECT_AUTOTOMIZE                   298
#define EFFECT_COPYCAT                      299
#define EFFECT_DEFOG                        300
#define EFFECT_HIT_ENEMY_HEAL_ALLY          301
#define EFFECT_SMACK_DOWN                   302
#define EFFECT_SYNCHRONOISE                 303
#define EFFECT_PSYCHO_SHIFT                 304
#define EFFECT_POWER_TRICK                  305
#define EFFECT_FLAME_BURST                  306
#define EFFECT_AFTER_YOU                    307
#define EFFECT_BESTOW                       308
#define EFFECT_ROTOTILLER                   309
#define EFFECT_FLOWER_SHIELD                310
#define EFFECT_HIT_PREVENT_ESCAPE           311
#define EFFECT_SPEED_SWAP                   312
#define EFFECT_DEFENSE_UP2_HIT              313
#define EFFECT_REVELATION_DANCE             314
#define EFFECT_AURORA_VEIL                  315
#define EFFECT_THIRD_TYPE                   316
#define EFFECT_FEINT                        317
#define EFFECT_SPARKLING_ARIA               318
#define EFFECT_ACUPRESSURE                  319
#define EFFECT_AROMATIC_MIST                320
#define EFFECT_POWDER                       321
#define EFFECT_SP_ATTACK_UP_HIT             322
#define EFFECT_BELCH                        323
#define EFFECT_PARTING_SHOT                 324
#define EFFECT_SPECTRAL_THIEF               325
#define EFFECT_V_CREATE                     326
#define EFFECT_MAT_BLOCK                    327
#define EFFECT_STOMPING_TANTRUM             328
#define EFFECT_CORE_ENFORCER                329
#define EFFECT_INSTRUCT                     330
#define EFFECT_THROAT_CHOP                  331
#define EFFECT_LASER_FOCUS                  332
#define EFFECT_MAGNETIC_FLUX                333
#define EFFECT_GEAR_UP                      334
#define EFFECT_INCINERATE                   335
#define EFFECT_BUG_BITE                     336
#define EFFECT_STRENGTH_SAP                 337
#define EFFECT_MIND_BLOWN                   338
#define EFFECT_PURIFY                       339
#define EFFECT_BURN_UP                      340
#define EFFECT_SHORE_UP                     341
#define EFFECT_GEOMANCY                     342
#define EFFECT_FAIRY_LOCK                   343
#define EFFECT_ALLY_SWITCH                  344
#define EFFECT_RELIC_SONG                   345
#define EFFECT_ATTACKER_DEFENSE_DOWN_HIT    346
#define EFFECT_BODY_PRESS                   347
#define EFFECT_EERIE_SPELL                  348
#define EFFECT_JUNGLE_HEALING               349
#define EFFECT_COACHING                     350
#define EFFECT_LASH_OUT                     351
#define EFFECT_GRASSY_GLIDE                 352
#define EFFECT_REMOVE_TERRAIN               353
#define EFFECT_DYNAMAX_DOUBLE_DMG           354
#define EFFECT_DECORATE                     355
#define EFFECT_SNIPE_SHOT                   356
#define EFFECT_RECOIL_HP_25                 357
#define EFFECT_STUFF_CHEEKS                 358
#define EFFECT_GRAV_APPLE                   359
#define EFFECT_EVASION_UP_HIT               360
#define EFFECT_GLITZY_GLOW                  361
#define EFFECT_BADDY_BAD                    362
#define EFFECT_SAPPY_SEED                   363
#define EFFECT_FREEZY_FROST                 364
#define EFFECT_SPARKLY_SWIRL                365
#define EFFECT_PLASMA_FISTS                 366
#define EFFECT_HYPERSPACE_FURY              367
#define EFFECT_AURA_WHEEL                   368
#define EFFECT_PHOTON_GEYSER                369
#define EFFECT_SHELL_SIDE_ARM               370
#define EFFECT_TERRAIN_PULSE                371
#define EFFECT_JAW_LOCK                     372
#define EFFECT_NO_RETREAT                   373
#define EFFECT_TAR_SHOT                     374
#define EFFECT_POLTERGEIST                  375
#define EFFECT_OCTOLOCK                     376
#define EFFECT_CLANGOROUS_SOUL              377
#define EFFECT_BOLT_BEAK                    378
#define EFFECT_SKY_DROP                     379
#define EFFECT_EXPANDING_FORCE              380
#define EFFECT_SCALE_SHOT                   381
#define EFFECT_METEOR_BEAM                  382
#define EFFECT_RISING_VOLTAGE               383
#define EFFECT_BEAK_BLAST                   384
#define EFFECT_COURT_CHANGE                 385
#define EFFECT_STEEL_BEAM                   386
#define EFFECT_EXTREME_EVOBOOST             387
#define EFFECT_DAMAGE_SET_TERRAIN           388 // genesis supernova
#define EFFECT_DARK_VOID                    389

#define NUM_BATTLE_MOVE_EFFECTS             389

#endif  // GUARD_CONSTANTS_BATTLE_MOVE_EFFECTS_H
