#ifndef GUARD_Z_MOVE_EFFECTS_H
#define GUARD_Z_MOVE_EFFECTS_H

enum ZEffect
{
    Z_EFFECT_NONE,
    Z_EFFECT_RESET_STATS,
    Z_EFFECT_ALL_STATS_UP_1,
    Z_EFFECT_BOOST_CRITS,
    Z_EFFECT_FOLLOW_ME,
    Z_EFFECT_CURSE,
    Z_EFFECT_RECOVER_HP,
    Z_EFFECT_RESTORE_REPLACEMENT_HP,
    Z_EFFECT_ATK_UP_1,
    Z_EFFECT_ATK_UP_2,
    Z_EFFECT_ATK_UP_3,
    Z_EFFECT_DEF_UP_1,
    Z_EFFECT_DEF_UP_2,
    Z_EFFECT_DEF_UP_3,
    Z_EFFECT_SPD_UP_1,
    Z_EFFECT_SPD_UP_2,
    Z_EFFECT_SPD_UP_3,
    Z_EFFECT_SPATK_UP_1,
    Z_EFFECT_SPATK_UP_2,
    Z_EFFECT_SPATK_UP_3,
    Z_EFFECT_SPDEF_UP_1,
    Z_EFFECT_SPDEF_UP_2,
    Z_EFFECT_SPDEF_UP_3,
    Z_EFFECT_ACC_UP_1,
    Z_EFFECT_ACC_UP_2,
    Z_EFFECT_ACC_UP_3,
    Z_EFFECT_EVSN_UP_1,
    Z_EFFECT_EVSN_UP_2,
    Z_EFFECT_EVSN_UP_3,
};

#endif // GUARD_Z_MOVE_EFFECTS_H
