#ifndef GUARD_CONSTANTS_BATTLE_FACTORY_H
#define GUARD_CONSTANTS_BATTLE_FACTORY_H

#define FACTORY_STYLE_NONE           0
#define FACTORY_STYLE_PREPARATION    1
#define FACTORY_STYLE_SLOW_STEADY    2
#define FACTORY_STYLE_ENDURANCE      3
#define FACTORY_STYLE_HIGH_RISK      4
#define FACTORY_STYLE_WEAKENING      5
#define FACTORY_STYLE_UNPREDICTABLE  6
#define FACTORY_STYLE_WEATHER        7
#define FACTORY_NUM_STYLES           8


#define BATTLE_FACTORY_FUNC_INIT                    0
#define BATTLE_FACTORY_FUNC_GET_DATA                1
#define BATTLE_FACTORY_FUNC_SET_DATA                2
#define BATTLE_FACTORY_FUNC_SAVE                    3
#define BATTLE_FACTORY_FUNC_NULL                    4
#define BATTLE_FACTORY_FUNC_NULL2                   5
#define BATTLE_FACTORY_FUNC_SELECT_RENT_MONS        6
#define BATTLE_FACTORY_FUNC_SWAP_RENT_MONS          7
#define BATTLE_FACTORY_FUNC_SET_SWAPPED             8
#define BATTLE_FACTORY_FUNC_SET_OPPONENT_MONS       9
#define BATTLE_FACTORY_FUNC_SET_PARTIES             10
#define BATTLE_FACTORY_FUNC_SET_OPPONENT_GFX        11
#define BATTLE_FACTORY_FUNC_GENERATE_OPPONENT_MONS  12
#define BATTLE_FACTORY_FUNC_GENERATE_RENTAL_MONS    13
#define BATTLE_FACTORY_FUNC_GET_OPPONENT_MON_TYPE   14
#define BATTLE_FACTORY_FUNC_GET_OPPONENT_STYLE      15
#define BATTLE_FACTORY_FUNC_RESET_HELD_ITEMS        16

#define FACTORY_DATA_WIN_STREAK         1
#define FACTORY_DATA_WIN_STREAK_ACTIVE  2
#define FACTORY_DATA_WIN_STREAK_SWAPS   3

#endif // GUARD_CONSTANTS_BATTLE_FACTORY_H
