#ifndef GUARD_CONSTANTS_BATTLE_ARENA_H
#define GUARD_CONSTANTS_BATTLE_ARENA_H

#define BATTLE_ARENA_FUNC_INIT              0
#define BATTLE_ARENA_FUNC_GET_DATA          1
#define BATTLE_ARENA_FUNC_SET_DATA          2
#define BATTLE_ARENA_FUNC_SAVE              3
#define BATTLE_ARENA_FUNC_SET_PRIZE         4
#define BATTLE_ARENA_FUNC_GIVE_PRIZE        5
#define BATTLE_ARENA_FUNC_GET_TRAINER_NAME  6

#define ARENA_DATA_PRIZE              0
#define ARENA_DATA_WIN_STREAK         1
#define ARENA_DATA_WIN_STREAK_ACTIVE  2

#define ARENA_CATEGORY_MIND  0
#define ARENA_CATEGORY_SKILL 1
#define ARENA_CATEGORY_BODY  2

#endif //GUARD_CONSTANTS_BATTLE_ARENA_H
