#ifndef GUARD_CONSTANTS_CABLE_CLUB_H
#define GUARD_CONSTANTS_CABLE_CLUB_H

// States for VAR_CABLE_CLUB_STATE
#define USING_SINGLE_BATTLE  1
#define USING_DOUBLE_BATTLE  2
#define USING_TRADE_CENTER   3
#define USING_RECORD_CORNER  4
#define USING_MULTI_BATTLE   5
#define USING_UNION_ROOM     6
#define USING_BERRY_CRUSH    7
#define USING_MINIGAME       8
#define USING_BATTLE_TOWER   9

#endif //GUARD_CONSTANTS_CABLE_CLUB_H
