#ifndef GUARD_CONSTANTS_CRIES_H
#define GUARD_CONSTANTS_CRIES_H

enum {
    CRY_NONE,
#if P_FAMILY_BULBASAUR
    CRY_BULBASAUR,
    CRY_IVYSAUR,
    CRY_VENUSAUR,
#if P_MEGA_EVOLUTIONS
    CRY_VENUSAUR_MEGA,
#endif //P_MEGA_EVOLUTIONS
#endif //P_FAMILY_BULBASAUR
#if P_FAMILY_CHARMANDER
    CRY_CHARMANDER,
    CRY_CHARMELEON,
    CRY_CHARIZARD,
#if P_MEGA_EVOLUTIONS
    CRY_CHARIZARD_MEGA_X,
    CRY_CHARIZARD_MEGA_Y,
#endif //P_MEGA_EVOLUTIONS
#endif //P_FAMILY_CHARMANDER
#if P_FAMILY_SQUIRTLE
    CRY_SQUIRTLE,
    CRY_WARTORTLE,
    CRY_BLASTOISE,
#if P_MEGA_EVOLUTIONS
    CRY_BLASTOISE_MEGA,
#endif //P_MEGA_EVOLUTIONS
#endif //P_FAMILY_SQUIRTLE
#if P_FAMILY_CATERPIE
    CRY_CATERPIE,
    CRY_METAPOD,
    CRY_BUTTERFREE,
#endif //P_FAMILY_CATERPIE
#if P_FAMILY_WEEDLE
    CRY_WEEDLE,
    CRY_KAKUNA,
    CRY_BEEDRILL,
#if P_MEGA_EVOLUTIONS
    CRY_BEEDRILL_MEGA,
#endif //P_MEGA_EVOLUTIONS
#endif //P_FAMILY_WEEDLE
#if P_FAMILY_PIDGEY
    CRY_PIDGEY,
    CRY_PIDGEOTTO,
    CRY_PIDGEOT,
#if P_MEGA_EVOLUTIONS
    CRY_PIDGEOT_MEGA,
#endif //P_MEGA_EVOLUTIONS
#endif //P_FAMILY_PIDGEY
#if P_FAMILY_RATTATA
    CRY_RATTATA,
    CRY_RATICATE,
#endif //P_FAMILY_RATTATA
#if P_FAMILY_SPEAROW
    CRY_SPEAROW,
    CRY_FEAROW,
#endif //P_FAMILY_SPEAROW
#if P_FAMILY_EKANS
    CRY_EKANS,
    CRY_ARBOK,
#endif //P_FAMILY_EKANS
#if P_FAMILY_PIKACHU
#if P_GEN_2_CROSS_EVOS
    CRY_PICHU,
#endif //P_GEN_2_CROSS_EVOS
    CRY_PIKACHU,
    CRY_RAICHU,
#endif //P_FAMILY_PIKACHU
#if P_FAMILY_SANDSHREW
    CRY_SANDSHREW,
    CRY_SANDSLASH,
#endif //P_FAMILY_SANDSHREW
#if P_FAMILY_NIDORAN
    CRY_NIDORAN_F,
    CRY_NIDORINA,
    CRY_NIDOQUEEN,
    CRY_NIDORAN_M,
    CRY_NIDORINO,
    CRY_NIDOKING,
#endif //P_FAMILY_NIDORAN
#if P_FAMILY_CLEFAIRY
#if P_GEN_2_CROSS_EVOS
    CRY_CLEFFA,
#endif //P_GEN_2_CROSS_EVOS
    CRY_CLEFAIRY,
    CRY_CLEFABLE,
#endif //P_FAMILY_CLEFAIRY
#if P_FAMILY_VULPIX
    CRY_VULPIX,
    CRY_NINETALES,
#endif //P_FAMILY_VULPIX
#if P_FAMILY_JIGGLYPUFF
#if P_GEN_2_CROSS_EVOS
    CRY_IGGLYBUFF,
#endif //P_GEN_2_CROSS_EVOS
    CRY_JIGGLYPUFF,
    CRY_WIGGLYTUFF,
#endif //P_FAMILY_JIGGLYPUFF
#if P_FAMILY_ZUBAT
    CRY_ZUBAT,
    CRY_GOLBAT,
#if P_GEN_2_CROSS_EVOS
    CRY_CROBAT,
#endif //P_GEN_2_CROSS_EVOS
#endif //P_FAMILY_ZUBAT
#if P_FAMILY_ODDISH
    CRY_ODDISH,
    CRY_GLOOM,
    CRY_VILEPLUME,
#if P_GEN_2_CROSS_EVOS
    CRY_BELLOSSOM,
#endif //P_GEN_2_CROSS_EVOS
#endif //P_FAMILY_ODDISH
#if P_FAMILY_PARAS
    CRY_PARAS,
    CRY_PARASECT,
#endif //P_FAMILY_PARAS
#if P_FAMILY_VENONAT
    CRY_VENONAT,
    CRY_VENOMOTH,
#endif //P_FAMILY_VENONAT
#if P_FAMILY_DIGLETT
    CRY_DIGLETT,
    CRY_DUGTRIO,
#endif //P_FAMILY_DIGLETT
#if P_FAMILY_MEOWTH
    CRY_MEOWTH,
    CRY_PERSIAN,
#if P_GALARIAN_FORMS
    CRY_PERRSERKER,
#endif //P_GALARIAN_FORMS
#endif //P_FAMILY_MEOWTH
#if P_FAMILY_PSYDUCK
    CRY_PSYDUCK,
    CRY_GOLDUCK,
#endif //P_FAMILY_PSYDUCK
#if P_FAMILY_MANKEY
    CRY_MANKEY,
    CRY_PRIMEAPE,
#if P_GEN_9_CROSS_EVOS
    CRY_ANNIHILAPE,
#endif //P_GEN_9_CROSS_EVOS
#endif //P_FAMILY_MANKEY
#if P_FAMILY_GROWLITHE
    CRY_GROWLITHE,
    CRY_ARCANINE,
#endif //P_FAMILY_GROWLITHE
#if P_FAMILY_POLIWAG
    CRY_POLIWAG,
    CRY_POLIWHIRL,
    CRY_POLIWRATH,
#if P_GEN_2_CROSS_EVOS
    CRY_POLITOED,
#endif //P_GEN_2_CROSS_EVOS
#endif //P_FAMILY_POLIWAG
#if P_FAMILY_ABRA
    CRY_ABRA,
    CRY_KADABRA,
    CRY_ALAKAZAM,
#if P_MEGA_EVOLUTIONS
    CRY_ALAKAZAM_MEGA,
#endif //P_MEGA_EVOLUTIONS
#endif //P_FAMILY_ABRA
#if P_FAMILY_MACHOP
    CRY_MACHOP,
    CRY_MACHOKE,
    CRY_MACHAMP,
#endif //P_FAMILY_MACHOP
#if P_FAMILY_BELLSPROUT
    CRY_BELLSPROUT,
    CRY_WEEPINBELL,
    CRY_VICTREEBEL,
#endif //P_FAMILY_BELLSPROUT
#if P_FAMILY_TENTACOOL
    CRY_TENTACOOL,
    CRY_TENTACRUEL,
#endif //P_FAMILY_TENTACOOL
#if P_FAMILY_GEODUDE
    CRY_GEODUDE,
    CRY_GRAVELER,
    CRY_GOLEM,
#endif //P_FAMILY_GEODUDE
#if P_FAMILY_PONYTA
    CRY_PONYTA,
    CRY_RAPIDASH,
#endif //P_FAMILY_PONYTA
#if P_FAMILY_SLOWPOKE
    CRY_SLOWPOKE,
    CRY_SLOWBRO,
#if P_GEN_2_CROSS_EVOS
    CRY_SLOWKING,
#endif //P_GEN_2_CROSS_EVOS
#if P_MEGA_EVOLUTIONS
    CRY_SLOWBRO_MEGA,
#endif //P_MEGA_EVOLUTIONS
#if P_GALARIAN_FORMS
    CRY_SLOWPOKE_GALARIAN,
#endif //P_GALARIAN_FORMS
#endif //P_FAMILY_SLOWPOKE
#if P_FAMILY_MAGNEMITE
    CRY_MAGNEMITE,
    CRY_MAGNETON,
#if P_GEN_4_CROSS_EVOS
    CRY_MAGNEZONE,
#endif //P_GEN_4_CROSS_EVOS
#endif //P_FAMILY_MAGNEMITE
#if P_FAMILY_FARFETCHD
    CRY_FARFETCHD,
#if P_GALARIAN_FORMS
    CRY_SIRFETCHD,
#endif //P_GALARIAN_FORMS
#endif //P_FAMILY_FARFETCHD
#if P_FAMILY_DODUO
    CRY_DODUO,
    CRY_DODRIO,
#endif //P_FAMILY_DODUO
#if P_FAMILY_SEEL
    CRY_SEEL,
    CRY_DEWGONG,
#endif //P_FAMILY_SEEL
#if P_FAMILY_GRIMER
    CRY_GRIMER,
    CRY_MUK,
#endif //P_FAMILY_GRIMER
#if P_FAMILY_SHELLDER
    CRY_SHELLDER,
    CRY_CLOYSTER,
#endif //P_FAMILY_SHELLDER
#if P_FAMILY_GASTLY
    CRY_GASTLY,
    CRY_HAUNTER,
    CRY_GENGAR,
#if P_MEGA_EVOLUTIONS
    CRY_GENGAR_MEGA,
#endif //P_MEGA_EVOLUTIONS
#endif //P_FAMILY_GASTLY
#if P_FAMILY_ONIX
    CRY_ONIX,
#if P_GEN_2_CROSS_EVOS
    CRY_STEELIX,
#if P_MEGA_EVOLUTIONS
    CRY_STEELIX_MEGA,
#endif //P_MEGA_EVOLUTIONS
#endif //P_GEN_2_CROSS_EVOS
#endif //P_FAMILY_ONIX
#if P_FAMILY_DROWZEE
    CRY_DROWZEE,
    CRY_HYPNO,
#endif //P_FAMILY_DROWZEE
#if P_FAMILY_KRABBY
    CRY_KRABBY,
    CRY_KINGLER,
#endif //P_FAMILY_KRABBY
#if P_FAMILY_VOLTORB
    CRY_VOLTORB,
    CRY_ELECTRODE,
#endif //P_FAMILY_VOLTORB
#if P_FAMILY_EXEGGCUTE
    CRY_EXEGGCUTE,
    CRY_EXEGGUTOR,
#endif //P_FAMILY_EXEGGCUTE
#if P_FAMILY_CUBONE
    CRY_CUBONE,
    CRY_MAROWAK,
#endif //P_FAMILY_CUBONE
#if P_FAMILY_HITMONS
#if P_GEN_2_CROSS_EVOS
    CRY_TYROGUE,
#endif //P_GEN_2_CROSS_EVOS
    CRY_HITMONLEE,
    CRY_HITMONCHAN,
#if P_GEN_2_CROSS_EVOS
    CRY_HITMONTOP,
#endif //P_GEN_2_CROSS_EVOS
#endif //P_FAMILY_HITMONS
#if P_FAMILY_LICKITUNG
    CRY_LICKITUNG,
#if P_GEN_4_CROSS_EVOS
    CRY_LICKILICKY,
#endif //P_GEN_4_CROSS_EVOS
#endif //P_FAMILY_LICKITUNG
#if P_FAMILY_KOFFING
    CRY_KOFFING,
    CRY_WEEZING,
#endif //P_FAMILY_KOFFING
#if P_FAMILY_RHYHORN
    CRY_RHYHORN,
    CRY_RHYDON,
#if P_GEN_4_CROSS_EVOS
    CRY_RHYPERIOR,
#endif //P_GEN_4_CROSS_EVOS
#endif //P_FAMILY_RHYHORN
#if P_FAMILY_CHANSEY
#if P_GEN_4_CROSS_EVOS
    CRY_HAPPINY,
#endif //P_GEN_4_CROSS_EVOS
    CRY_CHANSEY,
#if P_GEN_2_CROSS_EVOS
    CRY_BLISSEY,
#endif //P_GEN_2_CROSS_EVOS
#endif //P_FAMILY_CHANSEY
#if P_FAMILY_TANGELA
    CRY_TANGELA,
#if P_GEN_4_CROSS_EVOS
    CRY_TANGROWTH,
#endif //P_GEN_4_CROSS_EVOS
#endif //P_FAMILY_TANGELA
#if P_FAMILY_KANGASKHAN
    CRY_KANGASKHAN,
#if P_MEGA_EVOLUTIONS
    CRY_KANGASKHAN_MEGA,
#endif //P_MEGA_EVOLUTIONS
#endif //P_FAMILY_KANGASKHAN
#if P_FAMILY_HORSEA
    CRY_HORSEA,
    CRY_SEADRA,
#if P_GEN_2_CROSS_EVOS
    CRY_KINGDRA,
#endif //P_GEN_2_CROSS_EVOS
#endif //P_FAMILY_HORSEA
#if P_FAMILY_GOLDEEN
    CRY_GOLDEEN,
    CRY_SEAKING,
#endif //P_FAMILY_GOLDEEN
#if P_FAMILY_STARYU
    CRY_STARYU,
    CRY_STARMIE,
#endif //P_FAMILY_STARYU
#if P_FAMILY_MR_MIME
#if P_GEN_4_CROSS_EVOS
    CRY_MIME_JR,
#endif //P_GEN_4_CROSS_EVOS
    CRY_MR_MIME,
#if P_GALARIAN_FORMS
    CRY_MR_RIME,
#endif //P_GALARIAN_FORMS
#endif //P_FAMILY_MR_MIME
#if P_FAMILY_SCYTHER
    CRY_SCYTHER,
#if P_GEN_2_CROSS_EVOS
    CRY_SCIZOR,
#if P_MEGA_EVOLUTIONS
    CRY_SCIZOR_MEGA,
#endif //P_MEGA_EVOLUTIONS
#endif //P_GEN_2_CROSS_EVOS
#if P_GEN_8_CROSS_EVOS
    CRY_KLEAVOR,
#endif //P_GEN_8_CROSS_EVOS
#endif //P_FAMILY_SCYTHER
#if P_FAMILY_JYNX
#if P_GEN_2_CROSS_EVOS
    CRY_SMOOCHUM,
#endif //P_GEN_2_CROSS_EVOS
    CRY_JYNX,
#endif //P_FAMILY_JYNX
#if P_FAMILY_ELECTABUZZ
#if P_GEN_2_CROSS_EVOS
    CRY_ELEKID,
#endif //P_GEN_2_CROSS_EVOS
    CRY_ELECTABUZZ,
#if P_GEN_4_CROSS_EVOS
    CRY_ELECTIVIRE,
#endif //P_GEN_4_CROSS_EVOS
#endif //P_FAMILY_ELECTABUZZ
#if P_FAMILY_MAGMAR
#if P_GEN_2_CROSS_EVOS
    CRY_MAGBY,
#endif //P_GEN_2_CROSS_EVOS
    CRY_MAGMAR,
#if P_GEN_4_CROSS_EVOS
    CRY_MAGMORTAR,
#endif //P_GEN_4_CROSS_EVOS
#endif //P_FAMILY_MAGMAR
#if P_FAMILY_PINSIR
    CRY_PINSIR,
#if P_MEGA_EVOLUTIONS
    CRY_PINSIR_MEGA,
#endif //P_MEGA_EVOLUTIONS
#endif //P_FAMILY_PINSIR
#if P_FAMILY_TAUROS
    CRY_TAUROS,
#endif //P_FAMILY_TAUROS
#if P_FAMILY_MAGIKARP
    CRY_MAGIKARP,
    CRY_GYARADOS,
#if P_MEGA_EVOLUTIONS
    CRY_GYARADOS_MEGA,
#endif //P_MEGA_EVOLUTIONS
#endif //P_FAMILY_MAGIKARP
#if P_FAMILY_LAPRAS
    CRY_LAPRAS,
#endif //P_FAMILY_LAPRAS
#if P_FAMILY_DITTO
    CRY_DITTO,
#endif //P_FAMILY_DITTO
#if P_FAMILY_EEVEE
    CRY_EEVEE,
    CRY_VAPOREON,
    CRY_JOLTEON,
    CRY_FLAREON,
#if P_GEN_2_CROSS_EVOS
    CRY_ESPEON,
    CRY_UMBREON,
#endif //P_GEN_2_CROSS_EVOS
#if P_GEN_4_CROSS_EVOS
    CRY_LEAFEON,
    CRY_GLACEON,
#endif //P_GEN_4_CROSS_EVOS
#if P_GEN_6_CROSS_EVOS
    CRY_SYLVEON,
#endif //P_GEN_6_CROSS_EVOS
#endif //P_FAMILY_EEVEE
#if P_FAMILY_PORYGON
    CRY_PORYGON,
#if P_GEN_2_CROSS_EVOS
    CRY_PORYGON2,
#if P_GEN_4_CROSS_EVOS
    CRY_PORYGON_Z,
#endif //P_GEN_4_CROSS_EVOS
#endif //P_GEN_2_CROSS_EVOS
#endif //P_FAMILY_PORYGON
#if P_FAMILY_OMANYTE
    CRY_OMANYTE,
    CRY_OMASTAR,
#endif //P_FAMILY_OMANYTE
#if P_FAMILY_KABUTO
    CRY_KABUTO,
    CRY_KABUTOPS,
#endif //P_FAMILY_KABUTO
#if P_FAMILY_AERODACTYL
    CRY_AERODACTYL,
#if P_MEGA_EVOLUTIONS
    CRY_AERODACTYL_MEGA,
#endif //P_MEGA_EVOLUTIONS
#endif //P_FAMILY_AERODACTYL
#if P_FAMILY_SNORLAX
#if P_GEN_4_CROSS_EVOS
    CRY_MUNCHLAX,
#endif //P_GEN_4_CROSS_EVOS
    CRY_SNORLAX,
#endif //P_FAMILY_SNORLAX
#if P_FAMILY_ARTICUNO
    CRY_ARTICUNO,
#endif //P_FAMILY_ARTICUNO
#if P_FAMILY_ZAPDOS
    CRY_ZAPDOS,
#endif //P_FAMILY_ZAPDOS
#if P_FAMILY_MOLTRES
    CRY_MOLTRES,
#endif //P_FAMILY_MOLTRES
#if P_FAMILY_DRATINI
    CRY_DRATINI,
    CRY_DRAGONAIR,
    CRY_DRAGONITE,
#endif //P_FAMILY_DRATINI
#if P_FAMILY_MEWTWO
    CRY_MEWTWO,
#if P_MEGA_EVOLUTIONS
    CRY_MEWTWO_MEGA_X,
    CRY_MEWTWO_MEGA_Y,
#endif //P_MEGA_EVOLUTIONS
#endif //P_FAMILY_MEWTWO
#if P_FAMILY_MEW
    CRY_MEW,
#endif //P_FAMILY_MEW
#if P_FAMILY_CHIKORITA
    CRY_CHIKORITA,
    CRY_BAYLEEF,
    CRY_MEGANIUM,
#endif //P_FAMILY_CHIKORITA
#if P_FAMILY_CYNDAQUIL
    CRY_CYNDAQUIL,
    CRY_QUILAVA,
    CRY_TYPHLOSION,
#endif //P_FAMILY_CYNDAQUIL
#if P_FAMILY_TOTODILE
    CRY_TOTODILE,
    CRY_CROCONAW,
    CRY_FERALIGATR,
#endif //P_FAMILY_TOTODILE
#if P_FAMILY_SENTRET
    CRY_SENTRET,
    CRY_FURRET,
#endif //P_FAMILY_SENTRET
#if P_FAMILY_HOOTHOOT
    CRY_HOOTHOOT,
    CRY_NOCTOWL,
#endif //P_FAMILY_HOOTHOOT
#if P_FAMILY_LEDYBA
    CRY_LEDYBA,
    CRY_LEDIAN,
#endif //P_FAMILY_LEDYBA
#if P_FAMILY_SPINARAK
    CRY_SPINARAK,
    CRY_ARIADOS,
#endif //P_FAMILY_SPINARAK
#if P_FAMILY_CHINCHOU
    CRY_CHINCHOU,
    CRY_LANTURN,
#endif //P_FAMILY_CHINCHOU
#if P_FAMILY_TOGEPI
    CRY_TOGEPI,
    CRY_TOGETIC,
#if P_GEN_4_CROSS_EVOS
    CRY_TOGEKISS,
#endif //P_GEN_4_CROSS_EVOS
#endif //P_FAMILY_TOGEPI
#if P_FAMILY_NATU
    CRY_NATU,
    CRY_XATU,
#endif //P_FAMILY_NATU
#if P_FAMILY_MAREEP
    CRY_MAREEP,
    CRY_FLAAFFY,
    CRY_AMPHAROS,
#if P_MEGA_EVOLUTIONS
    CRY_AMPHAROS_MEGA,
#endif //P_MEGA_EVOLUTIONS
#endif //P_FAMILY_MAREEP
#if P_FAMILY_MARILL
#if P_GEN_3_CROSS_EVOS
    CRY_AZURILL,
#endif //P_GEN_3_CROSS_EVOS
    CRY_MARILL,
    CRY_AZUMARILL,
#endif //P_FAMILY_MARILL
#if P_FAMILY_SUDOWOODO
    CRY_BONSLY,
    CRY_SUDOWOODO,
#endif //P_FAMILY_SUDOWOODO
#if P_FAMILY_HOPPIP
    CRY_HOPPIP,
    CRY_SKIPLOOM,
    CRY_JUMPLUFF,
#endif //P_FAMILY_HOPPIP
#if P_FAMILY_AIPOM
    CRY_AIPOM,
    CRY_AMBIPOM,
#endif //P_FAMILY_AIPOM
#if P_FAMILY_SUNKERN
    CRY_SUNKERN,
    CRY_SUNFLORA,
#endif //P_FAMILY_SUNKERN
#if P_FAMILY_YANMA
    CRY_YANMA,
#if P_GEN_4_CROSS_EVOS
    CRY_YANMEGA,
#endif //P_GEN_4_CROSS_EVOS
#endif //P_FAMILY_YANMA
#if P_FAMILY_WOOPER
    CRY_WOOPER,
    CRY_QUAGSIRE,
#if P_PALDEAN_FORMS
    CRY_CLODSIRE,
#endif //P_PALDEAN_FORMS
#endif //P_FAMILY_WOOPER
#if P_FAMILY_MURKROW
    CRY_MURKROW,
    CRY_HONCHKROW,
#endif //P_FAMILY_MURKROW
#if P_FAMILY_MISDREAVUS
    CRY_MISDREAVUS,
    CRY_MISMAGIUS,
#endif //P_FAMILY_MISDREAVUS
#if P_FAMILY_UNOWN
    CRY_UNOWN,
#endif //P_FAMILY_UNOWN
#if P_FAMILY_WOBBUFFET
#if P_GEN_3_CROSS_EVOS
    CRY_WYNAUT,
#endif //P_GEN_3_CROSS_EVOS
    CRY_WOBBUFFET,
#endif //P_FAMILY_WOBBUFFET
#if P_FAMILY_GIRAFARIG
    CRY_GIRAFARIG,
#if P_GEN_9_CROSS_EVOS
    CRY_FARIGIRAF,
#endif //P_GEN_9_CROSS_EVOS
#endif //P_FAMILY_GIRAFARIG
#if P_FAMILY_PINECO
    CRY_PINECO,
    CRY_FORRETRESS,
#endif //P_FAMILY_PINECO
#if P_FAMILY_DUNSPARCE
    CRY_DUNSPARCE,
#if P_GEN_9_CROSS_EVOS
    CRY_DUDUNSPARCE,
#endif //P_GEN_9_CROSS_EVOS
#endif //P_FAMILY_DUNSPARCE
#if P_FAMILY_GLIGAR
    CRY_GLIGAR,
#if P_GEN_4_CROSS_EVOS
    CRY_GLISCOR,
#endif //P_GEN_4_CROSS_EVOS
#endif //P_FAMILY_GLIGAR
#if P_FAMILY_SNUBBULL
    CRY_SNUBBULL,
    CRY_GRANBULL,
#endif //P_FAMILY_SNUBBULL
#if P_FAMILY_QWILFISH
    CRY_QWILFISH,
#if P_HISUIAN_FORMS
    CRY_OVERQWIL,
#endif //P_HISUIAN_FORMS
#endif //P_FAMILY_QWILFISH
#if P_FAMILY_SHUCKLE
    CRY_SHUCKLE,
#endif //P_FAMILY_SHUCKLE
#if P_FAMILY_HERACROSS
    CRY_HERACROSS,
#if P_MEGA_EVOLUTIONS
    CRY_HERACROSS_MEGA,
#endif //P_MEGA_EVOLUTIONS
#endif //P_FAMILY_HERACROSS
#if P_FAMILY_SNEASEL
    CRY_SNEASEL,
#if P_GEN_4_CROSS_EVOS
    CRY_WEAVILE,
#endif //P_GEN_4_CROSS_EVOS
#if P_HISUIAN_FORMS
    CRY_SNEASLER,
#endif //P_HISUIAN_FORMS
#endif //P_FAMILY_SNEASEL
#if P_FAMILY_TEDDIURSA
    CRY_TEDDIURSA,
    CRY_URSARING,
#if P_GEN_8_CROSS_EVOS
    CRY_URSALUNA,
#endif //P_GEN_8_CROSS_EVOS
#endif //P_FAMILY_TEDDIURSA
#if P_FAMILY_SLUGMA
    CRY_SLUGMA,
    CRY_MAGCARGO,
#endif //P_FAMILY_SLUGMA
#if P_FAMILY_SWINUB
    CRY_SWINUB,
    CRY_PILOSWINE,
#if P_GEN_4_CROSS_EVOS
    CRY_MAMOSWINE,
#endif //P_GEN_4_CROSS_EVOS
#endif //P_FAMILY_SWINUB
#if P_FAMILY_CORSOLA
    CRY_CORSOLA,
#if P_GALARIAN_FORMS
    CRY_CURSOLA,
#endif //P_GALARIAN_FORMS
#endif //P_FAMILY_CORSOLA
#if P_FAMILY_REMORAID
    CRY_REMORAID,
    CRY_OCTILLERY,
#endif //P_FAMILY_REMORAID
#if P_FAMILY_DELIBIRD
    CRY_DELIBIRD,
#endif //P_FAMILY_DELIBIRD
#if P_FAMILY_MANTINE
#if P_GEN_4_CROSS_EVOS
    CRY_MANTYKE,
#endif //P_GEN_4_CROSS_EVOS
    CRY_MANTINE,
#endif //P_FAMILY_MANTINE
#if P_FAMILY_SKARMORY
    CRY_SKARMORY,
#endif //P_FAMILY_SKARMORY
#if P_FAMILY_HOUNDOUR
    CRY_HOUNDOUR,
    CRY_HOUNDOOM,
#if P_MEGA_EVOLUTIONS
    CRY_HOUNDOOM_MEGA,
#endif //P_MEGA_EVOLUTIONS
#endif //P_FAMILY_HOUNDOUR
#if P_FAMILY_PHANPY
    CRY_PHANPY,
    CRY_DONPHAN,
#endif //P_FAMILY_PHANPY
#if P_FAMILY_STANTLER
    CRY_STANTLER,
#if P_GEN_8_CROSS_EVOS
    CRY_WYRDEER,
#endif //P_GEN_8_CROSS_EVOS
#endif //P_FAMILY_STANTLER
#if P_FAMILY_SMEARGLE
    CRY_SMEARGLE,
#endif //P_FAMILY_SMEARGLE
#if P_FAMILY_MILTANK
    CRY_MILTANK,
#endif //P_FAMILY_MILTANK
#if P_FAMILY_RAIKOU
    CRY_RAIKOU,
#endif //P_FAMILY_RAIKOU
#if P_FAMILY_ENTEI
    CRY_ENTEI,
#endif //P_FAMILY_ENTEI
#if P_FAMILY_SUICUNE
    CRY_SUICUNE,
#endif //P_FAMILY_SUICUNE
#if P_FAMILY_LARVITAR
    CRY_LARVITAR,
    CRY_PUPITAR,
    CRY_TYRANITAR,
#if P_MEGA_EVOLUTIONS
    CRY_TYRANITAR_MEGA,
#endif //P_MEGA_EVOLUTIONS
#endif //P_FAMILY_LARVITAR
#if P_FAMILY_LUGIA
    CRY_LUGIA,
#endif //P_FAMILY_LUGIA
#if P_FAMILY_HO_OH
    CRY_HO_OH,
#endif //P_FAMILY_HO_OH
#if P_FAMILY_CELEBI
    CRY_CELEBI,
#endif //P_FAMILY_CELEBI
#if P_FAMILY_TREECKO
    CRY_TREECKO,
    CRY_GROVYLE,
    CRY_SCEPTILE,
#if P_MEGA_EVOLUTIONS
    CRY_SCEPTILE_MEGA,
#endif //P_MEGA_EVOLUTIONS
#endif //P_FAMILY_TREECKO
#if P_FAMILY_TORCHIC
    CRY_TORCHIC,
    CRY_COMBUSKEN,
    CRY_BLAZIKEN,
#if P_MEGA_EVOLUTIONS
    CRY_BLAZIKEN_MEGA,
#endif //P_MEGA_EVOLUTIONS
#endif //P_FAMILY_TORCHIC
#if P_FAMILY_MUDKIP
    CRY_MUDKIP,
    CRY_MARSHTOMP,
    CRY_SWAMPERT,
#if P_MEGA_EVOLUTIONS
    CRY_SWAMPERT_MEGA,
#endif //P_MEGA_EVOLUTIONS
#endif //P_FAMILY_MUDKIP
#if P_FAMILY_POOCHYENA
    CRY_POOCHYENA,
    CRY_MIGHTYENA,
#endif //P_FAMILY_POOCHYENA
#if P_FAMILY_ZIGZAGOON
    CRY_ZIGZAGOON,
    CRY_LINOONE,
#if P_GALARIAN_FORMS
    CRY_OBSTAGOON,
#endif //P_GALARIAN_FORMS
#endif //P_FAMILY_ZIGZAGOON
#if P_FAMILY_WURMPLE
    CRY_WURMPLE,
    CRY_SILCOON,
    CRY_BEAUTIFLY,
    CRY_CASCOON,
    CRY_DUSTOX,
#endif //P_FAMILY_WURMPLE
#if P_FAMILY_LOTAD
    CRY_LOTAD,
    CRY_LOMBRE,
    CRY_LUDICOLO,
#endif //P_FAMILY_LOTAD
#if P_FAMILY_SEEDOT
    CRY_SEEDOT,
    CRY_NUZLEAF,
    CRY_SHIFTRY,
#endif //P_FAMILY_SEEDOT
#if P_FAMILY_TAILLOW
    CRY_TAILLOW,
    CRY_SWELLOW,
#endif //P_FAMILY_TAILLOW
#if P_FAMILY_WINGULL
    CRY_WINGULL,
    CRY_PELIPPER,
#endif //P_FAMILY_WINGULL
#if P_FAMILY_RALTS
    CRY_RALTS,
    CRY_KIRLIA,
    CRY_GARDEVOIR,
#if P_MEGA_EVOLUTIONS
    CRY_GARDEVOIR_MEGA,
#endif //P_MEGA_EVOLUTIONS
#if P_GEN_4_CROSS_EVOS
    CRY_GALLADE,
#if P_MEGA_EVOLUTIONS
    CRY_GALLADE_MEGA,
#endif //P_MEGA_EVOLUTIONS
#endif //P_GEN_4_CROSS_EVOS
#endif //P_FAMILY_RALTS
#if P_FAMILY_SURSKIT
    CRY_SURSKIT,
    CRY_MASQUERAIN,
#endif //P_FAMILY_SURSKIT
#if P_FAMILY_SHROOMISH
    CRY_SHROOMISH,
    CRY_BRELOOM,
#endif //P_FAMILY_SHROOMISH
#if P_FAMILY_SLAKOTH
    CRY_SLAKOTH,
    CRY_VIGOROTH,
    CRY_SLAKING,
#endif //P_FAMILY_SLAKOTH
#if P_FAMILY_NINCADA
    CRY_NINCADA,
    CRY_NINJASK,
    CRY_SHEDINJA,
#endif //P_FAMILY_NINCADA
#if P_FAMILY_WHISMUR
    CRY_WHISMUR,
    CRY_LOUDRED,
    CRY_EXPLOUD,
#endif //P_FAMILY_WHISMUR
#if P_FAMILY_MAKUHITA
    CRY_MAKUHITA,
    CRY_HARIYAMA,
#endif //P_FAMILY_MAKUHITA
#if P_FAMILY_NOSEPASS
    CRY_NOSEPASS,
#if P_GEN_4_CROSS_EVOS
    CRY_PROBOPASS,
#endif //P_GEN_4_CROSS_EVOS
#endif //P_FAMILY_NOSEPASS
#if P_FAMILY_SKITTY
    CRY_SKITTY,
    CRY_DELCATTY,
#endif //P_FAMILY_SKITTY
#if P_FAMILY_SABLEYE
    CRY_SABLEYE,
#if P_MEGA_EVOLUTIONS
    CRY_SABLEYE_MEGA,
#endif //P_MEGA_EVOLUTIONS
#endif //P_FAMILY_SABLEYE
#if P_FAMILY_MAWILE
    CRY_MAWILE,
#if P_MEGA_EVOLUTIONS
    CRY_MAWILE_MEGA,
#endif //P_MEGA_EVOLUTIONS
#endif //P_FAMILY_MAWILE
#if P_FAMILY_ARON
    CRY_ARON,
    CRY_LAIRON,
    CRY_AGGRON,
#if P_MEGA_EVOLUTIONS
    CRY_AGGRON_MEGA,
#endif //P_MEGA_EVOLUTIONS
#endif //P_FAMILY_ARON
#if P_FAMILY_MEDITITE
    CRY_MEDITITE,
    CRY_MEDICHAM,
#if P_MEGA_EVOLUTIONS
    CRY_MEDICHAM_MEGA,
#endif //P_MEGA_EVOLUTIONS
#endif //P_FAMILY_MEDITITE
#if P_FAMILY_ELECTRIKE
    CRY_ELECTRIKE,
    CRY_MANECTRIC,
#if P_MEGA_EVOLUTIONS
    CRY_MANECTRIC_MEGA,
#endif //P_MEGA_EVOLUTIONS
#endif //P_FAMILY_ELECTRIKE
#if P_FAMILY_PLUSLE
    CRY_PLUSLE,
#endif //P_FAMILY_PLUSLE
#if P_FAMILY_MINUN
    CRY_MINUN,
#endif //P_FAMILY_MINUN
#if P_FAMILY_VOLBEAT_ILLUMISE
    CRY_VOLBEAT,
    CRY_ILLUMISE,
#endif //P_FAMILY_VOLBEAT_ILLUMISE
#if P_FAMILY_ROSELIA
#if P_GEN_4_CROSS_EVOS
    CRY_BUDEW,
#endif //P_GEN_4_CROSS_EVOS
    CRY_ROSELIA,
#if P_GEN_4_CROSS_EVOS
    CRY_ROSERADE,
#endif //P_GEN_4_CROSS_EVOS
#endif //P_FAMILY_ROSELIA
#if P_FAMILY_GULPIN
    CRY_GULPIN,
    CRY_SWALOT,
#endif //P_FAMILY_GULPIN
#if P_FAMILY_CARVANHA
    CRY_CARVANHA,
    CRY_SHARPEDO,
#if P_MEGA_EVOLUTIONS
    CRY_SHARPEDO_MEGA,
#endif //P_MEGA_EVOLUTIONS
#endif //P_FAMILY_CARVANHA
#if P_FAMILY_WAILMER
    CRY_WAILMER,
    CRY_WAILORD,
#endif //P_FAMILY_WAILMER
#if P_FAMILY_NUMEL
    CRY_NUMEL,
    CRY_CAMERUPT,
#if P_MEGA_EVOLUTIONS
    CRY_CAMERUPT_MEGA,
#endif //P_MEGA_EVOLUTIONS
#endif //P_FAMILY_NUMEL
#if P_FAMILY_TORKOAL
    CRY_TORKOAL,
#endif //P_FAMILY_TORKOAL
#if P_FAMILY_SPOINK
    CRY_SPOINK,
    CRY_GRUMPIG,
#endif //P_FAMILY_SPOINK
#if P_FAMILY_SPINDA
    CRY_SPINDA,
#endif //P_FAMILY_SPINDA
#if P_FAMILY_TRAPINCH
    CRY_TRAPINCH,
    CRY_VIBRAVA,
    CRY_FLYGON,
#endif //P_FAMILY_TRAPINCH
#if P_FAMILY_CACNEA
    CRY_CACNEA,
    CRY_CACTURNE,
#endif //P_FAMILY_CACNEA
#if P_FAMILY_SWABLU
    CRY_SWABLU,
    CRY_ALTARIA,
#if P_MEGA_EVOLUTIONS
    CRY_ALTARIA_MEGA,
#endif //P_MEGA_EVOLUTIONS
#endif //P_FAMILY_SWABLU
#if P_FAMILY_ZANGOOSE
    CRY_ZANGOOSE,
#endif //P_FAMILY_ZANGOOSE
#if P_FAMILY_SEVIPER
    CRY_SEVIPER,
#endif //P_FAMILY_SEVIPER
#if P_FAMILY_LUNATONE
    CRY_LUNATONE,
#endif //P_FAMILY_LUNATONE
#if P_FAMILY_SOLROCK
    CRY_SOLROCK,
#endif //P_FAMILY_SOLROCK
#if P_FAMILY_BARBOACH
    CRY_BARBOACH,
    CRY_WHISCASH,
#endif //P_FAMILY_BARBOACH
#if P_FAMILY_CORPHISH
    CRY_CORPHISH,
    CRY_CRAWDAUNT,
#endif //P_FAMILY_CORPHISH
#if P_FAMILY_BALTOY
    CRY_BALTOY,
    CRY_CLAYDOL,
#endif //P_FAMILY_BALTOY
#if P_FAMILY_LILEEP
    CRY_LILEEP,
    CRY_CRADILY,
#endif //P_FAMILY_LILEEP
#if P_FAMILY_ANORITH
    CRY_ANORITH,
    CRY_ARMALDO,
#endif //P_FAMILY_ANORITH
#if P_FAMILY_FEEBAS
    CRY_FEEBAS,
    CRY_MILOTIC,
#endif //P_FAMILY_FEEBAS
#if P_FAMILY_CASTFORM
    CRY_CASTFORM,
#endif //P_FAMILY_CASTFORM
#if P_FAMILY_KECLEON
    CRY_KECLEON,
#endif //P_FAMILY_KECLEON
#if P_FAMILY_SHUPPET
    CRY_SHUPPET,
    CRY_BANETTE,
#if P_MEGA_EVOLUTIONS
    CRY_BANETTE_MEGA,
#endif //P_MEGA_EVOLUTIONS
#endif //P_FAMILY_SHUPPET
#if P_FAMILY_DUSKULL
    CRY_DUSKULL,
    CRY_DUSCLOPS,
#if P_GEN_4_CROSS_EVOS
    CRY_DUSKNOIR,
#endif //P_GEN_4_CROSS_EVOS
#endif //P_FAMILY_DUSKULL
#if P_FAMILY_TROPIUS
    CRY_TROPIUS,
#endif //P_FAMILY_TROPIUS
#if P_FAMILY_CHIMECHO
#if P_GEN_4_CROSS_EVOS
    CRY_CHINGLING,
#endif //P_GEN_4_CROSS_EVOS
    CRY_CHIMECHO,
#endif //P_FAMILY_CHIMECHO
#if P_FAMILY_ABSOL
    CRY_ABSOL,
#if P_MEGA_EVOLUTIONS
    CRY_ABSOL_MEGA,
#endif //P_MEGA_EVOLUTIONS
#endif //P_FAMILY_ABSOL
#if P_FAMILY_SNORUNT
    CRY_SNORUNT,
    CRY_GLALIE,
#if P_MEGA_EVOLUTIONS
    CRY_GLALIE_MEGA,
#endif //P_MEGA_EVOLUTIONS
#if P_GEN_4_CROSS_EVOS
    CRY_FROSLASS,
#endif //P_GEN_4_CROSS_EVOS
#endif //P_FAMILY_SNORUNT
#if P_FAMILY_SPHEAL
    CRY_SPHEAL,
    CRY_SEALEO,
    CRY_WALREIN,
#endif //P_FAMILY_SPHEAL
#if P_FAMILY_CLAMPERL
    CRY_CLAMPERL,
    CRY_HUNTAIL,
    CRY_GOREBYSS,
#endif //P_FAMILY_CLAMPERL
#if P_FAMILY_RELICANTH
    CRY_RELICANTH,
#endif //P_FAMILY_RELICANTH
#if P_FAMILY_LUVDISC
    CRY_LUVDISC,
#endif //P_FAMILY_LUVDISC
#if P_FAMILY_BAGON
    CRY_BAGON,
    CRY_SHELGON,
    CRY_SALAMENCE,
#if P_MEGA_EVOLUTIONS
    CRY_SALAMENCE_MEGA,
#endif //P_MEGA_EVOLUTIONS
#endif //P_FAMILY_BAGON
#if P_FAMILY_BELDUM
    CRY_BELDUM,
    CRY_METANG,
    CRY_METAGROSS,
#if P_MEGA_EVOLUTIONS
    CRY_METAGROSS_MEGA,
#endif //P_MEGA_EVOLUTIONS
#endif //P_FAMILY_BELDUM
#if P_FAMILY_REGIROCK
    CRY_REGIROCK,
#endif //P_FAMILY_REGIROCK
#if P_FAMILY_REGICE
    CRY_REGICE,
#endif //P_FAMILY_REGICE
#if P_FAMILY_REGISTEEL
    CRY_REGISTEEL,
#endif //P_FAMILY_REGISTEEL
#if P_FAMILY_LATIAS
    CRY_LATIAS,
#if P_MEGA_EVOLUTIONS
    CRY_LATIAS_MEGA,
#endif //P_MEGA_EVOLUTIONS
#endif //P_FAMILY_LATIAS
#if P_FAMILY_LATIOS
    CRY_LATIOS,
#if P_MEGA_EVOLUTIONS
    CRY_LATIOS_MEGA,
#endif //P_MEGA_EVOLUTIONS
#endif //P_FAMILY_LATIOS
#if P_FAMILY_KYOGRE
    CRY_KYOGRE,
#if P_PRIMAL_REVERSIONS
    CRY_KYOGRE_PRIMAL,
#endif //P_PRIMAL_REVERSIONS
#endif //P_FAMILY_KYOGRE
#if P_FAMILY_GROUDON
    CRY_GROUDON,
#if P_PRIMAL_REVERSIONS
    CRY_GROUDON_PRIMAL,
#endif //P_PRIMAL_REVERSIONS
#endif //P_FAMILY_GROUDON
#if P_FAMILY_RAYQUAZA
    CRY_RAYQUAZA,
#if P_MEGA_EVOLUTIONS
    CRY_RAYQUAZA_MEGA,
#endif //P_MEGA_EVOLUTIONS
#endif //P_FAMILY_RAYQUAZA
#if P_FAMILY_JIRACHI
    CRY_JIRACHI,
#endif //P_FAMILY_JIRACHI
#if P_FAMILY_DEOXYS
    CRY_DEOXYS,
#endif //P_FAMILY_DEOXYS
#if P_FAMILY_TURTWIG
    CRY_TURTWIG,
    CRY_GROTLE,
    CRY_TORTERRA,
#endif //P_FAMILY_TURTWIG
#if P_FAMILY_CHIMCHAR
    CRY_CHIMCHAR,
    CRY_MONFERNO,
    CRY_INFERNAPE,
#endif //P_FAMILY_CHIMCHAR
#if P_FAMILY_PIPLUP
    CRY_PIPLUP,
    CRY_PRINPLUP,
    CRY_EMPOLEON,
#endif //P_FAMILY_PIPLUP
#if P_FAMILY_STARLY
    CRY_STARLY,
    CRY_STARAVIA,
    CRY_STARAPTOR,
#endif //P_FAMILY_STARLY
#if P_FAMILY_BIDOOF
    CRY_BIDOOF,
    CRY_BIBAREL,
#endif //P_FAMILY_BIDOOF
#if P_FAMILY_KRICKETOT
    CRY_KRICKETOT,
    CRY_KRICKETUNE,
#endif //P_FAMILY_KRICKETOT
#if P_FAMILY_SHINX
    CRY_SHINX,
    CRY_LUXIO,
    CRY_LUXRAY,
#endif //P_FAMILY_SHINX
#if P_FAMILY_CRANIDOS
    CRY_CRANIDOS,
    CRY_RAMPARDOS,
#endif //P_FAMILY_CRANIDOS
#if P_FAMILY_SHIELDON
    CRY_SHIELDON,
    CRY_BASTIODON,
#endif //P_FAMILY_SHIELDON
#if P_FAMILY_BURMY
    CRY_BURMY,
    CRY_WORMADAM,
    CRY_MOTHIM,
#endif //P_FAMILY_BURMY
#if P_FAMILY_COMBEE
    CRY_COMBEE,
    CRY_VESPIQUEN,
#endif //P_FAMILY_COMBEE
#if P_FAMILY_PACHIRISU
    CRY_PACHIRISU,
#endif //P_FAMILY_PACHIRISU
#if P_FAMILY_BUIZEL
    CRY_BUIZEL,
    CRY_FLOATZEL,
#endif //P_FAMILY_BUIZEL
#if P_FAMILY_CHERUBI
    CRY_CHERUBI,
    CRY_CHERRIM,
#endif //P_FAMILY_CHERUBI
#if P_FAMILY_SHELLOS
    CRY_SHELLOS,
    CRY_GASTRODON,
#endif //P_FAMILY_SHELLOS
#if P_FAMILY_DRIFLOON
    CRY_DRIFLOON,
    CRY_DRIFBLIM,
#endif //P_FAMILY_DRIFLOON
#if P_FAMILY_BUNEARY
    CRY_BUNEARY,
    CRY_LOPUNNY,
#if P_MEGA_EVOLUTIONS
    CRY_LOPUNNY_MEGA,
#endif //P_MEGA_EVOLUTIONS
#endif //P_FAMILY_BUNEARY
#if P_FAMILY_GLAMEOW
    CRY_GLAMEOW,
    CRY_PURUGLY,
#endif //P_FAMILY_GLAMEOW
#if P_FAMILY_STUNKY
    CRY_STUNKY,
    CRY_SKUNTANK,
#endif //P_FAMILY_STUNKY
#if P_FAMILY_BRONZOR
    CRY_BRONZOR,
    CRY_BRONZONG,
#endif //P_FAMILY_BRONZOR
#if P_FAMILY_CHATOT
    CRY_CHATOT,
#endif //P_FAMILY_CHATOT
#if P_FAMILY_SPIRITOMB
    CRY_SPIRITOMB,
#endif //P_FAMILY_SPIRITOMB
#if P_FAMILY_GIBLE
    CRY_GIBLE,
    CRY_GABITE,
    CRY_GARCHOMP,
#if P_MEGA_EVOLUTIONS
    CRY_GARCHOMP_MEGA,
#endif //P_MEGA_EVOLUTIONS
#endif //P_FAMILY_GIBLE
#if P_FAMILY_RIOLU
    CRY_RIOLU,
    CRY_LUCARIO,
#if P_MEGA_EVOLUTIONS
    CRY_LUCARIO_MEGA,
#endif //P_MEGA_EVOLUTIONS
#endif //P_FAMILY_RIOLU
#if P_FAMILY_HIPPOPOTAS
    CRY_HIPPOPOTAS,
    CRY_HIPPOWDON,
#endif //P_FAMILY_HIPPOPOTAS
#if P_FAMILY_SKORUPI
    CRY_SKORUPI,
    CRY_DRAPION,
#endif //P_FAMILY_SKORUPI
#if P_FAMILY_CROAGUNK
    CRY_CROAGUNK,
    CRY_TOXICROAK,
#endif //P_FAMILY_CROAGUNK
#if P_FAMILY_CARNIVINE
    CRY_CARNIVINE,
#endif //P_FAMILY_CARNIVINE
#if P_FAMILY_FINNEON
    CRY_FINNEON,
    CRY_LUMINEON,
#endif //P_FAMILY_FINNEON
#if P_FAMILY_SNOVER
    CRY_SNOVER,
    CRY_ABOMASNOW,
#if P_MEGA_EVOLUTIONS
    CRY_ABOMASNOW_MEGA,
#endif //P_MEGA_EVOLUTIONS
#endif //P_FAMILY_SNOVER
#if P_FAMILY_ROTOM
    CRY_ROTOM,
#endif //P_FAMILY_ROTOM
#if P_FAMILY_UXIE
    CRY_UXIE,
#endif //P_FAMILY_UXIE
#if P_FAMILY_MESPRIT
    CRY_MESPRIT,
#endif //P_FAMILY_MESPRIT
#if P_FAMILY_AZELF
    CRY_AZELF,
#endif //P_FAMILY_AZELF
#if P_FAMILY_DIALGA
    CRY_DIALGA,
#endif //P_FAMILY_DIALGA
#if P_FAMILY_PALKIA
    CRY_PALKIA,
#endif //P_FAMILY_PALKIA
#if P_FAMILY_HEATRAN
    CRY_HEATRAN,
#endif //P_FAMILY_HEATRAN
#if P_FAMILY_REGIGIGAS
    CRY_REGIGIGAS,
#endif //P_FAMILY_REGIGIGAS
#if P_FAMILY_GIRATINA
    CRY_GIRATINA,
#endif //P_FAMILY_GIRATINA
#if P_FAMILY_CRESSELIA
    CRY_CRESSELIA,
#endif //P_FAMILY_CRESSELIA
#if P_FAMILY_MANAPHY
    CRY_PHIONE,
    CRY_MANAPHY,
#endif //P_FAMILY_MANAPHY
#if P_FAMILY_DARKRAI
    CRY_DARKRAI,
#endif //P_FAMILY_DARKRAI
#if P_FAMILY_SHAYMIN
    CRY_SHAYMIN_LAND,
    CRY_SHAYMIN_SKY,
#endif //P_FAMILY_SHAYMIN
#if P_FAMILY_ARCEUS
    CRY_ARCEUS,
#endif //P_FAMILY_ARCEUS
#if P_FAMILY_VICTINI
    CRY_VICTINI,
#endif //P_FAMILY_VICTINI
#if P_FAMILY_SNIVY
    CRY_SNIVY,
    CRY_SERVINE,
    CRY_SERPERIOR,
#endif //P_FAMILY_SNIVY
#if P_FAMILY_TEPIG
    CRY_TEPIG,
    CRY_PIGNITE,
    CRY_EMBOAR,
#endif //P_FAMILY_TEPIG
#if P_FAMILY_OSHAWOTT
    CRY_OSHAWOTT,
    CRY_DEWOTT,
    CRY_SAMUROTT,
#endif //P_FAMILY_OSHAWOTT
#if P_FAMILY_PATRAT
    CRY_PATRAT,
    CRY_WATCHOG,
#endif //P_FAMILY_PATRAT
#if P_FAMILY_LILLIPUP
    CRY_LILLIPUP,
    CRY_HERDIER,
    CRY_STOUTLAND,
#endif //P_FAMILY_LILLIPUP
#if P_FAMILY_PURRLOIN
    CRY_PURRLOIN,
    CRY_LIEPARD,
#endif //P_FAMILY_PURRLOIN
#if P_FAMILY_PANSAGE
    CRY_PANSAGE,
    CRY_SIMISAGE,
#endif //P_FAMILY_PANSAGE
#if P_FAMILY_PANSEAR
    CRY_PANSEAR,
    CRY_SIMISEAR,
#endif //P_FAMILY_PANSEAR
#if P_FAMILY_PANPOUR
    CRY_PANPOUR,
    CRY_SIMIPOUR,
#endif //P_FAMILY_PANPOUR
#if P_FAMILY_MUNNA
    CRY_MUNNA,
    CRY_MUSHARNA,
#endif //P_FAMILY_MUNNA
#if P_FAMILY_PIDOVE
    CRY_PIDOVE,
    CRY_TRANQUILL,
    CRY_UNFEZANT,
#endif //P_FAMILY_PIDOVE
#if P_FAMILY_BLITZLE
    CRY_BLITZLE,
    CRY_ZEBSTRIKA,
#endif //P_FAMILY_BLITZLE
#if P_FAMILY_ROGGENROLA
    CRY_ROGGENROLA,
    CRY_BOLDORE,
    CRY_GIGALITH,
#endif //P_FAMILY_ROGGENROLA
#if P_FAMILY_WOOBAT
    CRY_WOOBAT,
    CRY_SWOOBAT,
#endif //P_FAMILY_WOOBAT
#if P_FAMILY_DRILBUR
    CRY_DRILBUR,
    CRY_EXCADRILL,
#endif //P_FAMILY_DRILBUR
#if P_FAMILY_AUDINO
    CRY_AUDINO,
#if P_MEGA_EVOLUTIONS
    CRY_AUDINO_MEGA,
#endif //P_MEGA_EVOLUTIONS
#endif //P_FAMILY_AUDINO
#if P_FAMILY_TIMBURR
    CRY_TIMBURR,
    CRY_GURDURR,
    CRY_CONKELDURR,
#endif //P_FAMILY_TIMBURR
#if P_FAMILY_TYMPOLE
    CRY_TYMPOLE,
    CRY_PALPITOAD,
    CRY_SEISMITOAD,
#endif //P_FAMILY_TYMPOLE
#if P_FAMILY_THROH
    CRY_THROH,
#endif //P_FAMILY_THROH
#if P_FAMILY_SAWK
    CRY_SAWK,
#endif //P_FAMILY_SAWK
#if P_FAMILY_SEWADDLE
    CRY_SEWADDLE,
    CRY_SWADLOON,
    CRY_LEAVANNY,
#endif //P_FAMILY_SEWADDLE
#if P_FAMILY_VENIPEDE
    CRY_VENIPEDE,
    CRY_WHIRLIPEDE,
    CRY_SCOLIPEDE,
#endif //P_FAMILY_VENIPEDE
#if P_FAMILY_COTTONEE
    CRY_COTTONEE,
    CRY_WHIMSICOTT,
#endif //P_FAMILY_COTTONEE
#if P_FAMILY_PETILIL
    CRY_PETILIL,
    CRY_LILLIGANT,
#endif //P_FAMILY_PETILIL
#if P_FAMILY_BASCULIN
    CRY_BASCULIN,
#if P_HISUIAN_FORMS
    CRY_BASCULEGION,
#endif //P_HISUIAN_FORMS
#endif //P_FAMILY_BASCULIN
#if P_FAMILY_SANDILE
    CRY_SANDILE,
    CRY_KROKOROK,
    CRY_KROOKODILE,
#endif //P_FAMILY_SANDILE
#if P_FAMILY_DARUMAKA
    CRY_DARUMAKA,
    CRY_DARMANITAN,
#endif //P_FAMILY_DARUMAKA
#if P_FAMILY_MARACTUS
    CRY_MARACTUS,
#endif //P_FAMILY_MARACTUS
#if P_FAMILY_DWEBBLE
    CRY_DWEBBLE,
    CRY_CRUSTLE,
#endif //P_FAMILY_DWEBBLE
#if P_FAMILY_SCRAGGY
    CRY_SCRAGGY,
    CRY_SCRAFTY,
#endif //P_FAMILY_SCRAGGY
#if P_FAMILY_SIGILYPH
    CRY_SIGILYPH,
#endif //P_FAMILY_SIGILYPH
#if P_FAMILY_YAMASK
    CRY_YAMASK,
    CRY_COFAGRIGUS,
#if P_GALARIAN_FORMS
    CRY_RUNERIGUS,
#endif //P_GALARIAN_FORMS
#endif //P_FAMILY_YAMASK
#if P_FAMILY_TIRTOUGA
    CRY_TIRTOUGA,
    CRY_CARRACOSTA,
#endif //P_FAMILY_TIRTOUGA
#if P_FAMILY_ARCHEN
    CRY_ARCHEN,
    CRY_ARCHEOPS,
#endif //P_FAMILY_ARCHEN
#if P_FAMILY_TRUBBISH
    CRY_TRUBBISH,
    CRY_GARBODOR,
#endif //P_FAMILY_TRUBBISH
#if P_FAMILY_ZORUA
    CRY_ZORUA,
    CRY_ZOROARK,
#endif //P_FAMILY_ZORUA
#if P_FAMILY_MINCCINO
    CRY_MINCCINO,
    CRY_CINCCINO,
#endif //P_FAMILY_MINCCINO
#if P_FAMILY_GOTHITA
    CRY_GOTHITA,
    CRY_GOTHORITA,
    CRY_GOTHITELLE,
#endif //P_FAMILY_GOTHITA
#if P_FAMILY_SOLOSIS
    CRY_SOLOSIS,
    CRY_DUOSION,
    CRY_REUNICLUS,
#endif //P_FAMILY_SOLOSIS
#if P_FAMILY_DUCKLETT
    CRY_DUCKLETT,
    CRY_SWANNA,
#endif //P_FAMILY_DUCKLETT
#if P_FAMILY_VANILLITE
    CRY_VANILLITE,
    CRY_VANILLISH,
    CRY_VANILLUXE,
#endif //P_FAMILY_VANILLITE
#if P_FAMILY_DEERLING
    CRY_DEERLING,
    CRY_SAWSBUCK,
#endif //P_FAMILY_DEERLING
#if P_FAMILY_EMOLGA
    CRY_EMOLGA,
#endif //P_FAMILY_EMOLGA
#if P_FAMILY_KARRABLAST
    CRY_KARRABLAST,
    CRY_ESCAVALIER,
#endif //P_FAMILY_KARRABLAST
#if P_FAMILY_FOONGUS
    CRY_FOONGUS,
    CRY_AMOONGUSS,
#endif //P_FAMILY_FOONGUS
#if P_FAMILY_FRILLISH
    CRY_FRILLISH,
    CRY_JELLICENT,
#endif //P_FAMILY_FRILLISH
#if P_FAMILY_ALOMOMOLA
    CRY_ALOMOMOLA,
#endif //P_FAMILY_ALOMOMOLA
#if P_FAMILY_JOLTIK
    CRY_JOLTIK,
    CRY_GALVANTULA,
#endif //P_FAMILY_JOLTIK
#if P_FAMILY_FERROSEED
    CRY_FERROSEED,
    CRY_FERROTHORN,
#endif //P_FAMILY_FERROSEED
#if P_FAMILY_KLINK
    CRY_KLINK,
    CRY_KLANG,
    CRY_KLINKLANG,
#endif //P_FAMILY_KLINK
#if P_FAMILY_TYNAMO
    CRY_TYNAMO,
    CRY_EELEKTRIK,
    CRY_EELEKTROSS,
#endif //P_FAMILY_TYNAMO
#if P_FAMILY_ELGYEM
    CRY_ELGYEM,
    CRY_BEHEEYEM,
#endif //P_FAMILY_ELGYEM
#if P_FAMILY_LITWICK
    CRY_LITWICK,
    CRY_LAMPENT,
    CRY_CHANDELURE,
#endif //P_FAMILY_LITWICK
#if P_FAMILY_AXEW
    CRY_AXEW,
    CRY_FRAXURE,
    CRY_HAXORUS,
#endif //P_FAMILY_AXEW
#if P_FAMILY_CUBCHOO
    CRY_CUBCHOO,
    CRY_BEARTIC,
#endif //P_FAMILY_CUBCHOO
#if P_FAMILY_CRYOGONAL
    CRY_CRYOGONAL,
#endif //P_FAMILY_CRYOGONAL
#if P_FAMILY_SHELMET
    CRY_SHELMET,
    CRY_ACCELGOR,
#endif //P_FAMILY_SHELMET
#if P_FAMILY_STUNFISK
    CRY_STUNFISK,
#endif //P_FAMILY_STUNFISK
#if P_FAMILY_MIENFOO
    CRY_MIENFOO,
    CRY_MIENSHAO,
#endif //P_FAMILY_MIENFOO
#if P_FAMILY_DRUDDIGON
    CRY_DRUDDIGON,
#endif //P_FAMILY_DRUDDIGON
#if P_FAMILY_GOLETT
    CRY_GOLETT,
    CRY_GOLURK,
#endif //P_FAMILY_GOLETT
#if P_FAMILY_PAWNIARD
    CRY_PAWNIARD,
    CRY_BISHARP,
#if P_GEN_9_CROSS_EVOS
    CRY_KINGAMBIT,
#endif //P_GEN_9_CROSS_EVOS
#endif //P_FAMILY_PAWNIARD
#if P_FAMILY_BOUFFALANT
    CRY_BOUFFALANT,
#endif //P_FAMILY_BOUFFALANT
#if P_FAMILY_RUFFLET
    CRY_RUFFLET,
    CRY_BRAVIARY,
#endif //P_FAMILY_RUFFLET
#if P_FAMILY_VULLABY
    CRY_VULLABY,
    CRY_MANDIBUZZ,
#endif //P_FAMILY_VULLABY
#if P_FAMILY_HEATMOR
    CRY_HEATMOR,
#endif //P_FAMILY_HEATMOR
#if P_FAMILY_DURANT
    CRY_DURANT,
#endif //P_FAMILY_DURANT
#if P_FAMILY_DEINO
    CRY_DEINO,
    CRY_ZWEILOUS,
    CRY_HYDREIGON,
#endif //P_FAMILY_DEINO
#if P_FAMILY_LARVESTA
    CRY_LARVESTA,
    CRY_VOLCARONA,
#endif //P_FAMILY_LARVESTA
#if P_FAMILY_COBALION
    CRY_COBALION,
#endif //P_FAMILY_COBALION
#if P_FAMILY_TERRAKION
    CRY_TERRAKION,
#endif //P_FAMILY_TERRAKION
#if P_FAMILY_VIRIZION
    CRY_VIRIZION,
#endif //P_FAMILY_VIRIZION
#if P_FAMILY_TORNADUS
    CRY_TORNADUS_INCARNATE,
    CRY_TORNADUS_THERIAN,
#endif //P_FAMILY_TORNADUS
#if P_FAMILY_THUNDURUS
    CRY_THUNDURUS_INCARNATE,
    CRY_THUNDURUS_THERIAN,
#endif //P_FAMILY_THUNDURUS
#if P_FAMILY_RESHIRAM
    CRY_RESHIRAM,
#endif //P_FAMILY_RESHIRAM
#if P_FAMILY_ZEKROM
    CRY_ZEKROM,
#endif //P_FAMILY_ZEKROM
#if P_FAMILY_LANDORUS
    CRY_LANDORUS_INCARNATE,
    CRY_LANDORUS_THERIAN,
#endif //P_FAMILY_LANDORUS
#if P_FAMILY_KYUREM
    CRY_KYUREM,
#if P_FUSION_FORMS
    CRY_KYUREM_WHITE,
    CRY_KYUREM_BLACK,
#endif //P_FUSION_FORMS
#endif //P_FAMILY_KYUREM
#if P_FAMILY_KELDEO
    CRY_KELDEO,
#endif //P_FAMILY_KELDEO
#if P_FAMILY_MELOETTA
    CRY_MELOETTA,
#endif //P_FAMILY_MELOETTA
#if P_FAMILY_GENESECT
    CRY_GENESECT,
#endif //P_FAMILY_GENESECT
#if P_FAMILY_CHESPIN
    CRY_CHESPIN,
    CRY_QUILLADIN,
    CRY_CHESNAUGHT,
#endif //P_FAMILY_CHESPIN
#if P_FAMILY_FENNEKIN
    CRY_FENNEKIN,
    CRY_BRAIXEN,
    CRY_DELPHOX,
#endif //P_FAMILY_FENNEKIN
#if P_FAMILY_FROAKIE
    CRY_FROAKIE,
    CRY_FROGADIER,
    CRY_GRENINJA,
#endif //P_FAMILY_FROAKIE
#if P_FAMILY_BUNNELBY
    CRY_BUNNELBY,
    CRY_DIGGERSBY,
#endif //P_FAMILY_BUNNELBY
#if P_FAMILY_FLETCHLING
    CRY_FLETCHLING,
    CRY_FLETCHINDER,
    CRY_TALONFLAME,
#endif //P_FAMILY_FLETCHLING
#if P_FAMILY_SCATTERBUG
    CRY_SCATTERBUG,
    CRY_SPEWPA,
    CRY_VIVILLON,
#endif //P_FAMILY_SCATTERBUG
#if P_FAMILY_LITLEO
    CRY_LITLEO,
    CRY_PYROAR,
#endif //P_FAMILY_LITLEO
#if P_FAMILY_FLABEBE
    CRY_FLABEBE,
    CRY_FLOETTE,
    CRY_FLOETTE_ETERNAL_FLOWER,
    CRY_FLORGES,
#endif //P_FAMILY_FLABEBE
#if P_FAMILY_SKIDDO
    CRY_SKIDDO,
    CRY_GOGOAT,
#endif //P_FAMILY_SKIDDO
#if P_FAMILY_PANCHAM
    CRY_PANCHAM,
    CRY_PANGORO,
#endif //P_FAMILY_PANCHAM
#if P_FAMILY_FURFROU
    CRY_FURFROU,
#endif //P_FAMILY_FURFROU
#if P_FAMILY_ESPURR
    CRY_ESPURR,
    CRY_MEOWSTIC,
#endif //P_FAMILY_ESPURR
#if P_FAMILY_HONEDGE
    CRY_HONEDGE,
    CRY_DOUBLADE,
    CRY_AEGISLASH,
#endif //P_FAMILY_HONEDGE
#if P_FAMILY_SPRITZEE
    CRY_SPRITZEE,
    CRY_AROMATISSE,
#endif //P_FAMILY_SPRITZEE
#if P_FAMILY_SWIRLIX
    CRY_SWIRLIX,
    CRY_SLURPUFF,
#endif //P_FAMILY_SWIRLIX
#if P_FAMILY_INKAY
    CRY_INKAY,
    CRY_MALAMAR,
#endif //P_FAMILY_INKAY
#if P_FAMILY_BINACLE
    CRY_BINACLE,
    CRY_BARBARACLE,
#endif //P_FAMILY_BINACLE
#if P_FAMILY_SKRELP
    CRY_SKRELP,
    CRY_DRAGALGE,
#endif //P_FAMILY_SKRELP
#if P_FAMILY_CLAUNCHER
    CRY_CLAUNCHER,
    CRY_CLAWITZER,
#endif //P_FAMILY_CLAUNCHER
#if P_FAMILY_HELIOPTILE
    CRY_HELIOPTILE,
    CRY_HELIOLISK,
#endif //P_FAMILY_HELIOPTILE
#if P_FAMILY_TYRUNT
    CRY_TYRUNT,
    CRY_TYRANTRUM,
#endif //P_FAMILY_TYRUNT
#if P_FAMILY_AMAURA
    CRY_AMAURA,
    CRY_AURORUS,
#endif //P_FAMILY_AMAURA
#if P_FAMILY_HAWLUCHA
    CRY_HAWLUCHA,
#endif //P_FAMILY_HAWLUCHA
#if P_FAMILY_DEDENNE
    CRY_DEDENNE,
#endif //P_FAMILY_DEDENNE
#if P_FAMILY_CARBINK
    CRY_CARBINK,
#endif //P_FAMILY_CARBINK
#if P_FAMILY_GOOMY
    CRY_GOOMY,
    CRY_SLIGGOO,
    CRY_GOODRA,
#endif //P_FAMILY_GOOMY
#if P_FAMILY_KLEFKI
    CRY_KLEFKI,
#endif //P_FAMILY_KLEFKI
#if P_FAMILY_PHANTUMP
    CRY_PHANTUMP,
    CRY_TREVENANT,
#endif //P_FAMILY_PHANTUMP
#if P_FAMILY_PUMPKABOO
    CRY_PUMPKABOO,
    CRY_PUMPKABOO_SUPER,
    CRY_GOURGEIST,
    CRY_GOURGEIST_SUPER,
#endif //P_FAMILY_PUMPKABOO
#if P_FAMILY_BERGMITE
    CRY_BERGMITE,
    CRY_AVALUGG,
#endif //P_FAMILY_BERGMITE
#if P_FAMILY_NOIBAT
    CRY_NOIBAT,
    CRY_NOIVERN,
#endif //P_FAMILY_NOIBAT
#if P_FAMILY_XERNEAS
    CRY_XERNEAS,
#endif //P_FAMILY_XERNEAS
#if P_FAMILY_YVELTAL
    CRY_YVELTAL,
#endif //P_FAMILY_YVELTAL
#if P_FAMILY_ZYGARDE
    CRY_ZYGARDE_50,
    CRY_ZYGARDE_10,
    CRY_ZYGARDE_COMPLETE,
#endif //P_FAMILY_ZYGARDE
#if P_FAMILY_DIANCIE
    CRY_DIANCIE,
#if P_MEGA_EVOLUTIONS
    CRY_DIANCIE_MEGA,
#endif //P_MEGA_EVOLUTIONS
#endif //P_FAMILY_DIANCIE
#if P_FAMILY_HOOPA
    CRY_HOOPA_CONFINED,
    CRY_HOOPA_UNBOUND,
#endif //P_FAMILY_HOOPA
#if P_FAMILY_VOLCANION
    CRY_VOLCANION,
#endif //P_FAMILY_VOLCANION
#if P_FAMILY_ROWLET
    CRY_ROWLET,
    CRY_DARTRIX,
    CRY_DECIDUEYE,
#endif //P_FAMILY_ROWLET
#if P_FAMILY_LITTEN
    CRY_LITTEN,
    CRY_TORRACAT,
    CRY_INCINEROAR,
#endif //P_FAMILY_LITTEN
#if P_FAMILY_POPPLIO
    CRY_POPPLIO,
    CRY_BRIONNE,
    CRY_PRIMARINA,
#endif //P_FAMILY_POPPLIO
#if P_FAMILY_PIKIPEK
    CRY_PIKIPEK,
    CRY_TRUMBEAK,
    CRY_TOUCANNON,
#endif //P_FAMILY_PIKIPEK
#if P_FAMILY_YUNGOOS
    CRY_YUNGOOS,
    CRY_GUMSHOOS,
#endif //P_FAMILY_YUNGOOS
#if P_FAMILY_GRUBBIN
    CRY_GRUBBIN,
    CRY_CHARJABUG,
    CRY_VIKAVOLT,
#endif //P_FAMILY_GRUBBIN
#if P_FAMILY_CRABRAWLER
    CRY_CRABRAWLER,
    CRY_CRABOMINABLE,
#endif //P_FAMILY_CRABRAWLER
#if P_FAMILY_ORICORIO
    CRY_ORICORIO_BAILE,
    CRY_ORICORIO_POM_POM,
    CRY_ORICORIO_PAU,
    CRY_ORICORIO_SENSU,
#endif //P_FAMILY_ORICORIO
#if P_FAMILY_CUTIEFLY
    CRY_CUTIEFLY,
    CRY_RIBOMBEE,
#endif //P_FAMILY_CUTIEFLY
#if P_FAMILY_ROCKRUFF
    CRY_ROCKRUFF,
    CRY_LYCANROC_MIDDAY,
    CRY_LYCANROC_MIDNIGHT,
    CRY_LYCANROC_DUSK,
#endif //P_FAMILY_ROCKRUFF
#if P_FAMILY_WISHIWASHI
    CRY_WISHIWASHI_SOLO,
    CRY_WISHIWASHI_SCHOOL,
#endif //P_FAMILY_WISHIWASHI
#if P_FAMILY_MAREANIE
    CRY_MAREANIE,
    CRY_TOXAPEX,
#endif //P_FAMILY_MAREANIE
#if P_FAMILY_MUDBRAY
    CRY_MUDBRAY,
    CRY_MUDSDALE,
#endif //P_FAMILY_MUDBRAY
#if P_FAMILY_DEWPIDER
    CRY_DEWPIDER,
    CRY_ARAQUANID,
#endif //P_FAMILY_DEWPIDER
#if P_FAMILY_FOMANTIS
    CRY_FOMANTIS,
    CRY_LURANTIS,
#endif //P_FAMILY_FOMANTIS
#if P_FAMILY_MORELULL
    CRY_MORELULL,
    CRY_SHIINOTIC,
#endif //P_FAMILY_MORELULL
#if P_FAMILY_SALANDIT
    CRY_SALANDIT,
    CRY_SALAZZLE,
#endif //P_FAMILY_SALANDIT
#if P_FAMILY_STUFFUL
    CRY_STUFFUL,
    CRY_BEWEAR,
#endif //P_FAMILY_STUFFUL
#if P_FAMILY_BOUNSWEET
    CRY_BOUNSWEET,
    CRY_STEENEE,
    CRY_TSAREENA,
#endif //P_FAMILY_BOUNSWEET
#if P_FAMILY_COMFEY
    CRY_COMFEY,
#endif //P_FAMILY_COMFEY
#if P_FAMILY_ORANGURU
    CRY_ORANGURU,
#endif //P_FAMILY_ORANGURU
#if P_FAMILY_PASSIMIAN
    CRY_PASSIMIAN,
#endif //P_FAMILY_PASSIMIAN
#if P_FAMILY_WIMPOD
    CRY_WIMPOD,
    CRY_GOLISOPOD,
#endif //P_FAMILY_WIMPOD
#if P_FAMILY_SANDYGAST
    CRY_SANDYGAST,
    CRY_PALOSSAND,
#endif //P_FAMILY_SANDYGAST
#if P_FAMILY_PYUKUMUKU
    CRY_PYUKUMUKU,
#endif //P_FAMILY_PYUKUMUKU
#if P_FAMILY_TYPE_NULL
    CRY_TYPE_NULL,
    CRY_SILVALLY,
#endif //P_FAMILY_TYPE_NULL
#if P_FAMILY_MINIOR
    CRY_MINIOR,
#endif //P_FAMILY_MINIOR
#if P_FAMILY_KOMALA
    CRY_KOMALA,
#endif //P_FAMILY_KOMALA
#if P_FAMILY_TURTONATOR
    CRY_TURTONATOR,
#endif //P_FAMILY_TURTONATOR
#if P_FAMILY_TOGEDEMARU
    CRY_TOGEDEMARU,
#endif //P_FAMILY_TOGEDEMARU
#if P_FAMILY_MIMIKYU
    CRY_MIMIKYU,
#endif //P_FAMILY_MIMIKYU
#if P_FAMILY_BRUXISH
    CRY_BRUXISH,
#endif //P_FAMILY_BRUXISH
#if P_FAMILY_DRAMPA
    CRY_DRAMPA,
#endif //P_FAMILY_DRAMPA
#if P_FAMILY_DHELMISE
    CRY_DHELMISE,
#endif //P_FAMILY_DHELMISE
#if P_FAMILY_JANGMO_O
    CRY_JANGMO_O,
    CRY_HAKAMO_O,
    CRY_KOMMO_O,
#endif //P_FAMILY_JANGMO_O
#if P_FAMILY_TAPU_KOKO
    CRY_TAPU_KOKO,
#endif //P_FAMILY_TAPU_KOKO
#if P_FAMILY_TAPU_LELE
    CRY_TAPU_LELE,
#endif //P_FAMILY_TAPU_LELE
#if P_FAMILY_TAPU_BULU
    CRY_TAPU_BULU,
#endif //P_FAMILY_TAPU_BULU
#if P_FAMILY_TAPU_FINI
    CRY_TAPU_FINI,
#endif //P_FAMILY_TAPU_FINI
#if P_FAMILY_COSMOG
    CRY_COSMOG,
    CRY_COSMOEM,
    CRY_SOLGALEO,
    CRY_LUNALA,
#endif //P_FAMILY_COSMOG
#if P_FAMILY_NIHILEGO
    CRY_NIHILEGO,
#endif //P_FAMILY_NIHILEGO
#if P_FAMILY_BUZZWOLE
    CRY_BUZZWOLE,
#endif //P_FAMILY_BUZZWOLE
#if P_FAMILY_PHEROMOSA
    CRY_PHEROMOSA,
#endif //P_FAMILY_PHEROMOSA
#if P_FAMILY_XURKITREE
    CRY_XURKITREE,
#endif //P_FAMILY_XURKITREE
#if P_FAMILY_CELESTEELA
    CRY_CELESTEELA,
#endif //P_FAMILY_CELESTEELA
#if P_FAMILY_KARTANA
    CRY_KARTANA,
#endif //P_FAMILY_KARTANA
#if P_FAMILY_GUZZLORD
    CRY_GUZZLORD,
#endif //P_FAMILY_GUZZLORD
#if P_FAMILY_NECROZMA
    CRY_NECROZMA,
#if P_FUSION_FORMS
    CRY_NECROZMA_DUSK_MANE,
    CRY_NECROZMA_DAWN_WINGS,
#if P_ULTRA_BURST_FORMS
    CRY_NECROZMA_ULTRA,
#endif //P_ULTRA_BURST_FORMS
#endif //P_FUSION_FORMS
#endif //P_FAMILY_NECROZMA
#if P_FAMILY_MAGEARNA
    CRY_MAGEARNA,
#endif //P_FAMILY_MAGEARNA
#if P_FAMILY_MARSHADOW
    CRY_MARSHADOW,
#endif //P_FAMILY_MARSHADOW
#if P_FAMILY_POIPOLE
    CRY_POIPOLE,
    CRY_NAGANADEL,
#endif //P_FAMILY_POIPOLE
#if P_FAMILY_STAKATAKA
    CRY_STAKATAKA,
#endif //P_FAMILY_STAKATAKA
#if P_FAMILY_BLACEPHALON
    CRY_BLACEPHALON,
#endif //P_FAMILY_BLACEPHALON
#if P_FAMILY_ZERAORA
    CRY_ZERAORA,
#endif //P_FAMILY_ZERAORA
#if P_FAMILY_MELTAN
    CRY_MELTAN,
    CRY_MELMETAL,
#endif //P_FAMILY_MELTAN
#if P_FAMILY_GROOKEY
    CRY_GROOKEY,
    CRY_THWACKEY,
    CRY_RILLABOOM,
#endif //P_FAMILY_GROOKEY
#if P_FAMILY_SCORBUNNY
    CRY_SCORBUNNY,
    CRY_RABOOT,
    CRY_CINDERACE,
#endif //P_FAMILY_SCORBUNNY
#if P_FAMILY_SOBBLE
    CRY_SOBBLE,
    CRY_DRIZZILE,
    CRY_INTELEON,
#endif //P_FAMILY_SOBBLE
#if P_FAMILY_SKWOVET
    CRY_SKWOVET,
    CRY_GREEDENT,
#endif //P_FAMILY_SKWOVET
#if P_FAMILY_ROOKIDEE
    CRY_ROOKIDEE,
    CRY_CORVISQUIRE,
    CRY_CORVIKNIGHT,
#endif //P_FAMILY_ROOKIDEE
#if P_FAMILY_BLIPBUG
    CRY_BLIPBUG,
    CRY_DOTTLER,
    CRY_ORBEETLE,
#endif //P_FAMILY_BLIPBUG
#if P_FAMILY_NICKIT
    CRY_NICKIT,
    CRY_THIEVUL,
#endif //P_FAMILY_NICKIT
#if P_FAMILY_GOSSIFLEUR
    CRY_GOSSIFLEUR,
    CRY_ELDEGOSS,
#endif //P_FAMILY_GOSSIFLEUR
#if P_FAMILY_WOOLOO
    CRY_WOOLOO,
    CRY_DUBWOOL,
#endif //P_FAMILY_WOOLOO
#if P_FAMILY_CHEWTLE
    CRY_CHEWTLE,
    CRY_DREDNAW,
#endif //P_FAMILY_CHEWTLE
#if P_FAMILY_YAMPER
    CRY_YAMPER,
    CRY_BOLTUND,
#endif //P_FAMILY_YAMPER
#if P_FAMILY_ROLYCOLY
    CRY_ROLYCOLY,
    CRY_CARKOL,
    CRY_COALOSSAL,
#endif //P_FAMILY_ROLYCOLY
#if P_FAMILY_APPLIN
    CRY_APPLIN,
    CRY_FLAPPLE,
    CRY_APPLETUN,
#if P_GEN_9_CROSS_EVOS
    CRY_DIPPLIN,
#endif //P_GEN_9_CROSS_EVOS
#endif //P_FAMILY_APPLIN
#if P_FAMILY_SILICOBRA
    CRY_SILICOBRA,
    CRY_SANDACONDA,
#endif //P_FAMILY_SILICOBRA
#if P_FAMILY_CRAMORANT
    CRY_CRAMORANT,
#endif //P_FAMILY_CRAMORANT
#if P_FAMILY_ARROKUDA
    CRY_ARROKUDA,
    CRY_BARRASKEWDA,
#endif //P_FAMILY_ARROKUDA
#if P_FAMILY_TOXEL
    CRY_TOXEL,
    CRY_TOXTRICITY_AMPED,
    CRY_TOXTRICITY_LOW_KEY,
#endif //P_FAMILY_TOXEL
#if P_FAMILY_SIZZLIPEDE
    CRY_SIZZLIPEDE,
    CRY_CENTISKORCH,
#endif //P_FAMILY_SIZZLIPEDE
#if P_FAMILY_CLOBBOPUS
    CRY_CLOBBOPUS,
    CRY_GRAPPLOCT,
#endif //P_FAMILY_CLOBBOPUS
#if P_FAMILY_SINISTEA
    CRY_SINISTEA,
    CRY_POLTEAGEIST,
#endif //P_FAMILY_SINISTEA
#if P_FAMILY_HATENNA
    CRY_HATENNA,
    CRY_HATTREM,
    CRY_HATTERENE,
#endif //P_FAMILY_HATENNA
#if P_FAMILY_IMPIDIMP
    CRY_IMPIDIMP,
    CRY_MORGREM,
    CRY_GRIMMSNARL,
#endif //P_FAMILY_IMPIDIMP
#if P_FAMILY_MILCERY
    CRY_MILCERY,
    CRY_ALCREMIE,
#endif //P_FAMILY_MILCERY
#if P_FAMILY_FALINKS
    CRY_FALINKS,
#endif //P_FAMILY_FALINKS
#if P_FAMILY_PINCURCHIN
    CRY_PINCURCHIN,
#endif //P_FAMILY_PINCURCHIN
#if P_FAMILY_SNOM
    CRY_SNOM,
    CRY_FROSMOTH,
#endif //P_FAMILY_SNOM
#if P_FAMILY_STONJOURNER
    CRY_STONJOURNER,
#endif //P_FAMILY_STONJOURNER
#if P_FAMILY_EISCUE
    CRY_EISCUE_ICE_FACE,
    CRY_EISCUE_NOICE_FACE,
#endif //P_FAMILY_EISCUE
#if P_FAMILY_INDEEDEE
    CRY_INDEEDEE_MALE,
    CRY_INDEEDEE_FEMALE,
#endif //P_FAMILY_INDEEDEE
#if P_FAMILY_MORPEKO
    CRY_MORPEKO_FULL_BELLY,
    CRY_MORPEKO_HANGRY,
#endif //P_FAMILY_MORPEKO
#if P_FAMILY_CUFANT
    CRY_CUFANT,
    CRY_COPPERAJAH,
#endif //P_FAMILY_CUFANT
#if P_FAMILY_DRACOZOLT
    CRY_DRACOZOLT,
#endif //P_FAMILY_DRACOZOLT
#if P_FAMILY_ARCTOZOLT
    CRY_ARCTOZOLT,
#endif //P_FAMILY_ARCTOZOLT
#if P_FAMILY_DRACOVISH
    CRY_DRACOVISH,
#endif //P_FAMILY_DRACOVISH
#if P_FAMILY_ARCTOVISH
    CRY_ARCTOVISH,
#endif //P_FAMILY_ARCTOVISH
#if P_FAMILY_DURALUDON
    CRY_DURALUDON,
#endif //P_FAMILY_DURALUDON
#if P_FAMILY_DREEPY
    CRY_DREEPY,
    CRY_DRAKLOAK,
    CRY_DRAGAPULT,
#endif //P_FAMILY_DREEPY
#if P_FAMILY_ZACIAN
    CRY_ZACIAN_HERO_OF_MANY_BATTLES,
    CRY_ZACIAN_CROWNED_SWORD,
#endif //P_FAMILY_ZACIAN
#if P_FAMILY_ZAMAZENTA
    CRY_ZAMAZENTA_HERO_OF_MANY_BATTLES,
    CRY_ZAMAZENTA_CROWNED_SHIELD,
#endif //P_FAMILY_ZAMAZENTA
#if P_FAMILY_ETERNATUS
    CRY_ETERNATUS,
    CRY_ETERNATUS_ETERNAMAX,
#endif //P_FAMILY_ETERNATUS
#if P_FAMILY_KUBFU
    CRY_KUBFU,
    CRY_URSHIFU_SINGLE_STRIKE_STYLE,
    CRY_URSHIFU_RAPID_STRIKE_STYLE,
#endif //P_FAMILY_KUBFU
#if P_FAMILY_ZARUDE
    CRY_ZARUDE,
#endif //P_FAMILY_ZARUDE
#if P_FAMILY_REGIELEKI
    CRY_REGIELEKI,
#endif //P_FAMILY_REGIELEKI
#if P_FAMILY_REGIDRAGO
    CRY_REGIDRAGO,
#endif //P_FAMILY_REGIDRAGO
#if P_FAMILY_GLASTRIER
    CRY_GLASTRIER,
#endif //P_FAMILY_GLASTRIER
#if P_FAMILY_SPECTRIER
    CRY_SPECTRIER,
#endif //P_FAMILY_SPECTRIER
#if P_FAMILY_CALYREX
    CRY_CALYREX,
#if P_FUSION_FORMS
    CRY_CALYREX_ICE_RIDER,
    CRY_CALYREX_SHADOW_RIDER,
#endif //P_FUSION_FORMS
#endif //P_FAMILY_CALYREX
#if P_FAMILY_ENAMORUS
    CRY_ENAMORUS_INCARNATE,
    CRY_ENAMORUS_THERIAN,
#endif //P_FAMILY_ENAMORUS
#if P_FAMILY_SPRIGATITO
    CRY_SPRIGATITO,
    CRY_FLORAGATO,
    CRY_MEOWSCARADA,
#endif //P_FAMILY_SPRIGATITO
#if P_FAMILY_FUECOCO
    CRY_FUECOCO,
    CRY_CROCALOR,
    CRY_SKELEDIRGE,
#endif //P_FAMILY_FUECOCO
#if P_FAMILY_QUAXLY
    CRY_QUAXLY,
    CRY_QUAXWELL,
    CRY_QUAQUAVAL,
#endif //P_FAMILY_QUAXLY
#if P_FAMILY_LECHONK
    CRY_LECHONK,
    CRY_OINKOLOGNE_MALE,
    CRY_OINKOLOGNE_FEMALE,
#endif //P_FAMILY_LECHONK
#if P_FAMILY_TAROUNTULA
    CRY_TAROUNTULA,
    CRY_SPIDOPS,
#endif //P_FAMILY_TAROUNTULA
#if P_FAMILY_NYMBLE
    CRY_NYMBLE,
    CRY_LOKIX,
#endif //P_FAMILY_NYMBLE
#if P_FAMILY_PAWMI
    CRY_PAWMI,
    CRY_PAWMO,
    CRY_PAWMOT,
#endif //P_FAMILY_PAWMI
#if P_FAMILY_TANDEMAUS
    CRY_TANDEMAUS,
    CRY_MAUSHOLD_FAMILY_OF_THREE,
    CRY_MAUSHOLD_FAMILY_OF_FOUR,
#endif //P_FAMILY_TANDEMAUS
#if P_FAMILY_FIDOUGH
    CRY_FIDOUGH,
    CRY_DACHSBUN,
#endif //P_FAMILY_FIDOUGH
#if P_FAMILY_SMOLIV
    CRY_SMOLIV,
    CRY_DOLLIV,
    CRY_ARBOLIVA,
#endif //P_FAMILY_SMOLIV
#if P_FAMILY_SQUAWKABILLY
    CRY_SQUAWKABILLY,
#endif //P_FAMILY_SQUAWKABILLY
#if P_FAMILY_NACLI
    CRY_NACLI,
    CRY_NACLSTACK,
    CRY_GARGANACL,
#endif //P_FAMILY_NACLI
#if P_FAMILY_CHARCADET
    CRY_CHARCADET,
    CRY_ARMAROUGE,
    CRY_CERULEDGE,
#endif //P_FAMILY_CHARCADET
#if P_FAMILY_TADBULB
    CRY_TADBULB,
    CRY_BELLIBOLT,
#endif //P_FAMILY_TADBULB
#if P_FAMILY_WATTREL
    CRY_WATTREL,
    CRY_KILOWATTREL,
#endif //P_FAMILY_WATTREL
#if P_FAMILY_MASCHIFF
    CRY_MASCHIFF,
    CRY_MABOSSTIFF,
#endif //P_FAMILY_MASCHIFF
#if P_FAMILY_SHROODLE
    CRY_SHROODLE,
    CRY_GRAFAIAI,
#endif //P_FAMILY_SHROODLE
#if P_FAMILY_BRAMBLIN
    CRY_BRAMBLIN,
    CRY_BRAMBLEGHAST,
#endif //P_FAMILY_BRAMBLIN
#if P_FAMILY_TOEDSCOOL
    CRY_TOEDSCOOL,
    CRY_TOEDSCRUEL,
#endif //P_FAMILY_TOEDSCOOL
#if P_FAMILY_KLAWF
    CRY_KLAWF,
#endif //P_FAMILY_KLAWF
#if P_FAMILY_CAPSAKID
    CRY_CAPSAKID,
    CRY_SCOVILLAIN,
#endif //P_FAMILY_CAPSAKID
#if P_FAMILY_RELLOR
    CRY_RELLOR,
    CRY_RABSCA,
#endif //P_FAMILY_RELLOR
#if P_FAMILY_FLITTLE
    CRY_FLITTLE,
    CRY_ESPATHRA,
#endif //P_FAMILY_FLITTLE
#if P_FAMILY_TINKATINK
    CRY_TINKATINK,
    CRY_TINKATUFF,
    CRY_TINKATON,
#endif //P_FAMILY_TINKATINK
#if P_FAMILY_WIGLETT
    CRY_WIGLETT,
    CRY_WUGTRIO,
#endif //P_FAMILY_WIGLETT
#if P_FAMILY_BOMBIRDIER
    CRY_BOMBIRDIER,
#endif //P_FAMILY_BOMBIRDIER
#if P_FAMILY_FINIZEN
    CRY_FINIZEN,
    CRY_PALAFIN_ZERO,
    CRY_PALAFIN_HERO,
#endif //P_FAMILY_FINIZEN
#if P_FAMILY_VAROOM
    CRY_VAROOM,
    CRY_REVAVROOM,
#endif //P_FAMILY_VAROOM
#if P_FAMILY_CYCLIZAR
    CRY_CYCLIZAR,
#endif //P_FAMILY_CYCLIZAR
#if P_FAMILY_ORTHWORM
    CRY_ORTHWORM,
#endif //P_FAMILY_ORTHWORM
#if P_FAMILY_GLIMMET
    CRY_GLIMMET,
    CRY_GLIMMORA,
#endif //P_FAMILY_GLIMMET
#if P_FAMILY_GREAVARD
    CRY_GREAVARD,
    CRY_HOUNDSTONE,
#endif //P_FAMILY_GREAVARD
#if P_FAMILY_FLAMIGO
    CRY_FLAMIGO,
#endif //P_FAMILY_FLAMIGO
#if P_FAMILY_CETODDLE
    CRY_CETODDLE,
    CRY_CETITAN,
#endif //P_FAMILY_CETODDLE
#if P_FAMILY_VELUZA
    CRY_VELUZA,
#endif //P_FAMILY_VELUZA
#if P_FAMILY_DONDOZO
    CRY_DONDOZO,
#endif //P_FAMILY_DONDOZO
#if P_FAMILY_TATSUGIRI
    CRY_TATSUGIRI_CURLY,
    CRY_TATSUGIRI_DROOPY,
    CRY_TATSUGIRI_STRETCHY,
#endif //P_FAMILY_TATSUGIRI
#if P_FAMILY_GREAT_TUSK
    CRY_GREAT_TUSK,
#endif //P_FAMILY_GREAT_TUSK
#if P_FAMILY_SCREAM_TAIL
    CRY_SCREAM_TAIL,
#endif //P_FAMILY_SCREAM_TAIL
#if P_FAMILY_BRUTE_BONNET
    CRY_BRUTE_BONNET,
#endif //P_FAMILY_BRUTE_BONNET
#if P_FAMILY_FLUTTER_MANE
    CRY_FLUTTER_MANE,
#endif //P_FAMILY_FLUTTER_MANE
#if P_FAMILY_SLITHER_WING
    CRY_SLITHER_WING,
#endif //P_FAMILY_SLITHER_WING
#if P_FAMILY_SANDY_SHOCKS
    CRY_SANDY_SHOCKS,
#endif //P_FAMILY_SANDY_SHOCKS
#if P_FAMILY_IRON_TREADS
    CRY_IRON_TREADS,
#endif //P_FAMILY_IRON_TREADS
#if P_FAMILY_IRON_BUNDLE
    CRY_IRON_BUNDLE,
#endif //P_FAMILY_IRON_BUNDLE
#if P_FAMILY_IRON_HANDS
    CRY_IRON_HANDS,
#endif //P_FAMILY_IRON_HANDS
#if P_FAMILY_IRON_JUGULIS
    CRY_IRON_JUGULIS,
#endif //P_FAMILY_IRON_JUGULIS
#if P_FAMILY_IRON_MOTH
    CRY_IRON_MOTH,
#endif //P_FAMILY_IRON_MOTH
#if P_FAMILY_IRON_THORNS
    CRY_IRON_THORNS,
#endif //P_FAMILY_IRON_THORNS
#if P_FAMILY_FRIGIBAX
    CRY_FRIGIBAX,
    CRY_ARCTIBAX,
    CRY_BAXCALIBUR,
#endif //P_FAMILY_FRIGIBAX
#if P_FAMILY_GIMMIGHOUL
    CRY_GIMMIGHOUL,
    CRY_GHOLDENGO,
#endif //P_FAMILY_GIMMIGHOUL
#if P_FAMILY_WO_CHIEN
    CRY_WO_CHIEN,
#endif //P_FAMILY_WO_CHIEN
#if P_FAMILY_CHIEN_PAO
    CRY_CHIEN_PAO,
#endif //P_FAMILY_CHIEN_PAO
#if P_FAMILY_TING_LU
    CRY_TING_LU,
#endif //P_FAMILY_TING_LU
#if P_FAMILY_CHI_YU
    CRY_CHI_YU,
#endif //P_FAMILY_CHI_YU
#if P_FAMILY_ROARING_MOON
    CRY_ROARING_MOON,
#endif //P_FAMILY_ROARING_MOON
#if P_FAMILY_IRON_VALIANT
    CRY_IRON_VALIANT,
#endif //P_FAMILY_IRON_VALIANT
#if P_FAMILY_KORAIDON
    CRY_KORAIDON,
#endif //P_FAMILY_KORAIDON
#if P_FAMILY_MIRAIDON
    CRY_MIRAIDON,
#endif //P_FAMILY_MIRAIDON
#if P_FAMILY_WALKING_WAKE
    CRY_WALKING_WAKE,
#endif //P_FAMILY_WALKING_WAKE
#if P_FAMILY_IRON_LEAVES
    CRY_IRON_LEAVES,
#endif //P_FAMILY_IRON_LEAVES
#if P_FAMILY_POLTCHAGEIST
    CRY_POLTCHAGEIST,
    CRY_SINISTCHA,
#endif //P_FAMILY_POLTCHAGEIST
#if P_FAMILY_OKIDOGI
    CRY_OKIDOGI,
#endif //P_FAMILY_OKIDOGI
#if P_FAMILY_MUNKIDORI
    CRY_MUNKIDORI,
#endif //P_FAMILY_MUNKIDORI
#if P_FAMILY_FEZANDIPITI
    CRY_FEZANDIPITI,
#endif //P_FAMILY_FEZANDIPITI
#if P_FAMILY_OGERPON
    CRY_OGERPON,
#endif //P_FAMILY_OGERPON
    CRY_COUNT,
};

#endif // GUARD_CONSTANTS_CRIES_H
