#ifndef GUARD_CONSTANTS_EVENT_OBJECTS_H
#define GUARD_CONSTANTS_EVENT_OBJECTS_H

#define OBJ_EVENT_GFX_BRENDAN_NORMAL               0
#define OBJ_EVENT_GFX_BRENDAN_MACH_BIKE            1
#define OBJ_EVENT_GFX_BRENDAN_SURFING              2
#define OBJ_EVENT_GFX_BRENDAN_FIELD_MOVE           3
#define OBJ_EVENT_GFX_QUINTY_PLUMP                 4
#define OBJ_EVENT_GFX_NINJA_BOY                    5
#define OBJ_EVENT_GFX_TWIN                         6
#define OBJ_EVENT_GFX_BOY_1                        7
#define OBJ_EVENT_GFX_GIRL_1                       8
#define OBJ_EVENT_GFX_BOY_2                        9
#define OBJ_EVENT_GFX_GIRL_2                      10
#define OBJ_EVENT_GFX_LITTLE_BOY                  11
#define OBJ_EVENT_GFX_LITTLE_GIRL                 12
#define OBJ_EVENT_GFX_BOY_3                       13
#define OBJ_EVENT_GFX_GIRL_3                      14
#define OBJ_EVENT_GFX_RICH_BOY                    15
#define OBJ_EVENT_GFX_WOMAN_1                     16
#define OBJ_EVENT_GFX_FAT_MAN                     17
#define OBJ_EVENT_GFX_POKEFAN_F                   18
#define OBJ_EVENT_GFX_MAN_1                       19
#define OBJ_EVENT_GFX_WOMAN_2                     20
#define OBJ_EVENT_GFX_EXPERT_M                    21
#define OBJ_EVENT_GFX_EXPERT_F                    22
#define OBJ_EVENT_GFX_MAN_2                       23
#define OBJ_EVENT_GFX_WOMAN_3                     24
#define OBJ_EVENT_GFX_POKEFAN_M                   25
#define OBJ_EVENT_GFX_WOMAN_4                     26
#define OBJ_EVENT_GFX_COOK                        27
#define OBJ_EVENT_GFX_LINK_RECEPTIONIST           28
#define OBJ_EVENT_GFX_OLD_MAN                     29
#define OBJ_EVENT_GFX_OLD_WOMAN                   30
#define OBJ_EVENT_GFX_CAMPER                      31
#define OBJ_EVENT_GFX_PICNICKER                   32
#define OBJ_EVENT_GFX_MAN_3                       33
#define OBJ_EVENT_GFX_WOMAN_5                     34
#define OBJ_EVENT_GFX_YOUNGSTER                   35
#define OBJ_EVENT_GFX_BUG_CATCHER                 36
#define OBJ_EVENT_GFX_PSYCHIC_M                   37
#define OBJ_EVENT_GFX_SCHOOL_KID_M                38
#define OBJ_EVENT_GFX_MANIAC                      39
#define OBJ_EVENT_GFX_HEX_MANIAC                  40
#define OBJ_EVENT_GFX_RAYQUAZA_STILL              41
#define OBJ_EVENT_GFX_SWIMMER_M                   42
#define OBJ_EVENT_GFX_SWIMMER_F                   43
#define OBJ_EVENT_GFX_BLACK_BELT                  44
#define OBJ_EVENT_GFX_BEAUTY                      45
#define OBJ_EVENT_GFX_SCIENTIST_1                 46
#define OBJ_EVENT_GFX_LASS                        47
#define OBJ_EVENT_GFX_GENTLEMAN                   48
#define OBJ_EVENT_GFX_SAILOR                      49
#define OBJ_EVENT_GFX_FISHERMAN                   50
#define OBJ_EVENT_GFX_RUNNING_TRIATHLETE_M        51
#define OBJ_EVENT_GFX_RUNNING_TRIATHLETE_F        52
#define OBJ_EVENT_GFX_TUBER_F                     53
#define OBJ_EVENT_GFX_TUBER_M                     54
#define OBJ_EVENT_GFX_HIKER                       55
#define OBJ_EVENT_GFX_CYCLING_TRIATHLETE_M        56
#define OBJ_EVENT_GFX_CYCLING_TRIATHLETE_F        57
#define OBJ_EVENT_GFX_NURSE                       58
#define OBJ_EVENT_GFX_ITEM_BALL                   59
#define OBJ_EVENT_GFX_BERRY_TREE                  60
#define OBJ_EVENT_GFX_BERRY_TREE_EARLY_STAGES     61
#define OBJ_EVENT_GFX_BERRY_TREE_LATE_STAGES      62
#define OBJ_EVENT_GFX_BRENDAN_ACRO_BIKE           63
#define OBJ_EVENT_GFX_PROF_BIRCH                  64
#define OBJ_EVENT_GFX_MAN_4                       65
#define OBJ_EVENT_GFX_MAN_5                       66
#define OBJ_EVENT_GFX_REPORTER_M                  67
#define OBJ_EVENT_GFX_REPORTER_F                  68
#define OBJ_EVENT_GFX_BARD                        69
#define OBJ_EVENT_GFX_ANABEL                      70
#define OBJ_EVENT_GFX_TUCKER                      71
#define OBJ_EVENT_GFX_GRETA                       72
#define OBJ_EVENT_GFX_SPENSER                     73
#define OBJ_EVENT_GFX_NOLAND                      74
#define OBJ_EVENT_GFX_LUCY                        75
#define OBJ_EVENT_GFX_UNUSED_NATU_DOLL            76
#define OBJ_EVENT_GFX_UNUSED_MAGNEMITE_DOLL       77
#define OBJ_EVENT_GFX_UNUSED_SQUIRTLE_DOLL        78
#define OBJ_EVENT_GFX_UNUSED_WOOPER_DOLL          79
#define OBJ_EVENT_GFX_UNUSED_PIKACHU_DOLL         80
#define OBJ_EVENT_GFX_UNUSED_PORYGON2_DOLL        81
#define OBJ_EVENT_GFX_CUTTABLE_TREE               82
#define OBJ_EVENT_GFX_MART_EMPLOYEE               83
#define OBJ_EVENT_GFX_ROOFTOP_SALE_WOMAN          84
#define OBJ_EVENT_GFX_TEALA                       85
#define OBJ_EVENT_GFX_BREAKABLE_ROCK              86
#define OBJ_EVENT_GFX_PUSHABLE_BOULDER            87
#define OBJ_EVENT_GFX_MR_BRINEYS_BOAT             88
#define OBJ_EVENT_GFX_MAY_NORMAL                  89
#define OBJ_EVENT_GFX_MAY_MACH_BIKE               90
#define OBJ_EVENT_GFX_MAY_ACRO_BIKE               91
#define OBJ_EVENT_GFX_MAY_SURFING                 92
#define OBJ_EVENT_GFX_MAY_FIELD_MOVE              93
#define OBJ_EVENT_GFX_TRUCK                       94
#define OBJ_EVENT_GFX_VIGOROTH_CARRYING_BOX       95
#define OBJ_EVENT_GFX_VIGOROTH_FACING_AWAY        96
#define OBJ_EVENT_GFX_BIRCHS_BAG                  97
#define OBJ_EVENT_GFX_ZIGZAGOON_1                 98
#define OBJ_EVENT_GFX_ARTIST                      99
#define OBJ_EVENT_GFX_RIVAL_BRENDAN_NORMAL       100
#define OBJ_EVENT_GFX_RIVAL_BRENDAN_MACH_BIKE    101
#define OBJ_EVENT_GFX_RIVAL_BRENDAN_ACRO_BIKE    102
#define OBJ_EVENT_GFX_RIVAL_BRENDAN_SURFING      103
#define OBJ_EVENT_GFX_RIVAL_BRENDAN_FIELD_MOVE   104
#define OBJ_EVENT_GFX_RIVAL_MAY_NORMAL           105
#define OBJ_EVENT_GFX_RIVAL_MAY_MACH_BIKE        106
#define OBJ_EVENT_GFX_RIVAL_MAY_ACRO_BIKE        107
#define OBJ_EVENT_GFX_RIVAL_MAY_SURFING          108
#define OBJ_EVENT_GFX_RIVAL_MAY_FIELD_MOVE       109
#define OBJ_EVENT_GFX_CAMERAMAN                  110
#define OBJ_EVENT_GFX_BRENDAN_UNDERWATER         111
#define OBJ_EVENT_GFX_MAY_UNDERWATER             112
#define OBJ_EVENT_GFX_MOVING_BOX                 113
#define OBJ_EVENT_GFX_CABLE_CAR                  114
#define OBJ_EVENT_GFX_SCIENTIST_2                115
#define OBJ_EVENT_GFX_DEVON_EMPLOYEE             116
#define OBJ_EVENT_GFX_AQUA_MEMBER_M              117
#define OBJ_EVENT_GFX_AQUA_MEMBER_F              118
#define OBJ_EVENT_GFX_MAGMA_MEMBER_M             119
#define OBJ_EVENT_GFX_MAGMA_MEMBER_F             120
#define OBJ_EVENT_GFX_SIDNEY                     121
#define OBJ_EVENT_GFX_PHOEBE                     122
#define OBJ_EVENT_GFX_GLACIA                     123
#define OBJ_EVENT_GFX_DRAKE                      124
#define OBJ_EVENT_GFX_ROXANNE                    125
#define OBJ_EVENT_GFX_BRAWLY                     126
#define OBJ_EVENT_GFX_WATTSON                    127
#define OBJ_EVENT_GFX_FLANNERY                   128
#define OBJ_EVENT_GFX_NORMAN                     129
#define OBJ_EVENT_GFX_WINONA                     130
#define OBJ_EVENT_GFX_LIZA                       131
#define OBJ_EVENT_GFX_TATE                       132
#define OBJ_EVENT_GFX_WALLACE                    133
#define OBJ_EVENT_GFX_STEVEN                     134
#define OBJ_EVENT_GFX_WALLY                      135
#define OBJ_EVENT_GFX_LITTLE_BOY_3               136
#define OBJ_EVENT_GFX_BRENDAN_FISHING            137
#define OBJ_EVENT_GFX_MAY_FISHING                138
#define OBJ_EVENT_GFX_HOT_SPRINGS_OLD_WOMAN      139
#define OBJ_EVENT_GFX_SS_TIDAL                   140
#define OBJ_EVENT_GFX_SUBMARINE_SHADOW           141
#define OBJ_EVENT_GFX_PICHU_DOLL                 142
#define OBJ_EVENT_GFX_PIKACHU_DOLL               143
#define OBJ_EVENT_GFX_MARILL_DOLL                144
#define OBJ_EVENT_GFX_TOGEPI_DOLL                145
#define OBJ_EVENT_GFX_CYNDAQUIL_DOLL             146
#define OBJ_EVENT_GFX_CHIKORITA_DOLL             147
#define OBJ_EVENT_GFX_TOTODILE_DOLL              148
#define OBJ_EVENT_GFX_JIGGLYPUFF_DOLL            149
#define OBJ_EVENT_GFX_MEOWTH_DOLL                150
#define OBJ_EVENT_GFX_CLEFAIRY_DOLL              151
#define OBJ_EVENT_GFX_DITTO_DOLL                 152
#define OBJ_EVENT_GFX_SMOOCHUM_DOLL              153
#define OBJ_EVENT_GFX_TREECKO_DOLL               154
#define OBJ_EVENT_GFX_TORCHIC_DOLL               155
#define OBJ_EVENT_GFX_MUDKIP_DOLL                156
#define OBJ_EVENT_GFX_DUSKULL_DOLL               157
#define OBJ_EVENT_GFX_WYNAUT_DOLL                158
#define OBJ_EVENT_GFX_BALTOY_DOLL                159
#define OBJ_EVENT_GFX_KECLEON_DOLL               160
#define OBJ_EVENT_GFX_AZURILL_DOLL               161
#define OBJ_EVENT_GFX_SKITTY_DOLL                162
#define OBJ_EVENT_GFX_SWABLU_DOLL                163
#define OBJ_EVENT_GFX_GULPIN_DOLL                164
#define OBJ_EVENT_GFX_LOTAD_DOLL                 165
#define OBJ_EVENT_GFX_SEEDOT_DOLL                166
#define OBJ_EVENT_GFX_PIKA_CUSHION               167
#define OBJ_EVENT_GFX_ROUND_CUSHION              168
#define OBJ_EVENT_GFX_KISS_CUSHION               169
#define OBJ_EVENT_GFX_ZIGZAG_CUSHION             170
#define OBJ_EVENT_GFX_SPIN_CUSHION               171
#define OBJ_EVENT_GFX_DIAMOND_CUSHION            172
#define OBJ_EVENT_GFX_BALL_CUSHION               173
#define OBJ_EVENT_GFX_GRASS_CUSHION              174
#define OBJ_EVENT_GFX_FIRE_CUSHION               175
#define OBJ_EVENT_GFX_WATER_CUSHION              176
#define OBJ_EVENT_GFX_BIG_SNORLAX_DOLL           177
#define OBJ_EVENT_GFX_BIG_RHYDON_DOLL            178
#define OBJ_EVENT_GFX_BIG_LAPRAS_DOLL            179
#define OBJ_EVENT_GFX_BIG_VENUSAUR_DOLL          180
#define OBJ_EVENT_GFX_BIG_CHARIZARD_DOLL         181
#define OBJ_EVENT_GFX_BIG_BLASTOISE_DOLL         182
#define OBJ_EVENT_GFX_BIG_WAILMER_DOLL           183
#define OBJ_EVENT_GFX_BIG_REGIROCK_DOLL          184
#define OBJ_EVENT_GFX_BIG_REGICE_DOLL            185
#define OBJ_EVENT_GFX_BIG_REGISTEEL_DOLL         186
#define OBJ_EVENT_GFX_LATIAS                     187
#define OBJ_EVENT_GFX_LATIOS                     188
#define OBJ_EVENT_GFX_GAMEBOY_KID                189
#define OBJ_EVENT_GFX_CONTEST_JUDGE              190
#define OBJ_EVENT_GFX_BRENDAN_WATERING           191
#define OBJ_EVENT_GFX_MAY_WATERING               192
#define OBJ_EVENT_GFX_BRENDAN_DECORATING         193
#define OBJ_EVENT_GFX_MAY_DECORATING             194
#define OBJ_EVENT_GFX_ARCHIE                     195
#define OBJ_EVENT_GFX_MAXIE                      196
#define OBJ_EVENT_GFX_KYOGRE_FRONT               197
#define OBJ_EVENT_GFX_GROUDON_FRONT              198
#define OBJ_EVENT_GFX_FOSSIL                     199
#define OBJ_EVENT_GFX_REGIROCK                   200
#define OBJ_EVENT_GFX_REGICE                     201
#define OBJ_EVENT_GFX_REGISTEEL                  202
#define OBJ_EVENT_GFX_SKITTY                     203
#define OBJ_EVENT_GFX_KECLEON                    204
#define OBJ_EVENT_GFX_KYOGRE_ASLEEP              205
#define OBJ_EVENT_GFX_GROUDON_ASLEEP             206
#define OBJ_EVENT_GFX_RAYQUAZA                   207
#define OBJ_EVENT_GFX_ZIGZAGOON_2                208
#define OBJ_EVENT_GFX_PIKACHU                    209
#define OBJ_EVENT_GFX_AZUMARILL                  210
#define OBJ_EVENT_GFX_WINGULL                    211
#define OBJ_EVENT_GFX_KECLEON_BRIDGE_SHADOW      212
#define OBJ_EVENT_GFX_TUBER_M_SWIMMING           213
#define OBJ_EVENT_GFX_AZURILL                    214
#define OBJ_EVENT_GFX_MOM                        215
#define OBJ_EVENT_GFX_LINK_BRENDAN               216
#define OBJ_EVENT_GFX_LINK_MAY                   217
#define OBJ_EVENT_GFX_JUAN                       218
#define OBJ_EVENT_GFX_SCOTT                      219
#define OBJ_EVENT_GFX_POOCHYENA                  220
#define OBJ_EVENT_GFX_KYOGRE_SIDE                221
#define OBJ_EVENT_GFX_GROUDON_SIDE               222
#define OBJ_EVENT_GFX_MYSTERY_GIFT_MAN           223
#define OBJ_EVENT_GFX_TRICK_HOUSE_STATUE         224
#define OBJ_EVENT_GFX_KIRLIA                     225
#define OBJ_EVENT_GFX_DUSCLOPS                   226
#define OBJ_EVENT_GFX_UNION_ROOM_NURSE           227
#define OBJ_EVENT_GFX_SUDOWOODO                  228
#define OBJ_EVENT_GFX_MEW                        229
#define OBJ_EVENT_GFX_RED                        230
#define OBJ_EVENT_GFX_LEAF                       231
#define OBJ_EVENT_GFX_DEOXYS                     232
#define OBJ_EVENT_GFX_DEOXYS_TRIANGLE            233
#define OBJ_EVENT_GFX_BRANDON                    234
#define OBJ_EVENT_GFX_LINK_RS_BRENDAN            235
#define OBJ_EVENT_GFX_LINK_RS_MAY                236
#define OBJ_EVENT_GFX_LUGIA                      237
#define OBJ_EVENT_GFX_HOOH                       238
#define OBJ_EVENT_GFX_BULBASAUR                  239
#define OBJ_EVENT_GFX_IVYSAUR                    240
#define OBJ_EVENT_GFX_VENUSAUR                   241 
#define OBJ_EVENT_GFX_CHARMANDER                 242
#define OBJ_EVENT_GFX_CHARMELEON                 243
#define OBJ_EVENT_GFX_CHARIZARD                  244
#define OBJ_EVENT_GFX_SQUIRTLE                   245
#define OBJ_EVENT_GFX_WARTORTLE                  246
#define OBJ_EVENT_GFX_BLASTOISE                  247
#define OBJ_EVENT_GFX_CATERPIE                   248
#define OBJ_EVENT_GFX_METAPOD                    249
#define OBJ_EVENT_GFX_BUTTERFREE                 250
#define OBJ_EVENT_GFX_WEEDLE                     251
#define OBJ_EVENT_GFX_KAKUNA                     252
#define OBJ_EVENT_GFX_BEEDRILL                   253
#define OBJ_EVENT_GFX_PIDGEY                     254
#define OBJ_EVENT_GFX_PIDGEOTTO                  255
#define OBJ_EVENT_GFX_PIDGEOT                    256
#define OBJ_EVENT_GFX_RATTATA                    257
#define OBJ_EVENT_GFX_RATICATE                   258
#define OBJ_EVENT_GFX_SPEAROW                    259
#define OBJ_EVENT_GFX_FEAROW                     260
#define OBJ_EVENT_GFX_EKANS                      261
#define OBJ_EVENT_GFX_ARBOK                      262
#define OBJ_EVENT_GFX_PIKACHU_FOLLOWER           263
#define OBJ_EVENT_GFX_RAICHU                     264
#define OBJ_EVENT_GFX_SANDSHREW                  265
#define OBJ_EVENT_GFX_SANDSLASH                  266
#define OBJ_EVENT_GFX_NIDORAN_F                  267
#define OBJ_EVENT_GFX_NIDORINA                   268
#define OBJ_EVENT_GFX_NIDOQUEEN                  269
#define OBJ_EVENT_GFX_NIDORAN_M                  270
#define OBJ_EVENT_GFX_NIDORINO                   271
#define OBJ_EVENT_GFX_NIDOKING                   272
#define OBJ_EVENT_GFX_CLEFAIRY                   273
#define OBJ_EVENT_GFX_CLEFABLE                   274
#define OBJ_EVENT_GFX_VULPIX                     275
#define OBJ_EVENT_GFX_NINETALES                  276
#define OBJ_EVENT_GFX_JIGGLYPUFF                 277
#define OBJ_EVENT_GFX_WIGGLYTUFF                 278
#define OBJ_EVENT_GFX_ZUBAT                      279
#define OBJ_EVENT_GFX_GOLBAT                     280
#define OBJ_EVENT_GFX_ODDISH                     281
#define OBJ_EVENT_GFX_GLOOM                      282
#define OBJ_EVENT_GFX_VILEPLUME                  283
#define OBJ_EVENT_GFX_PARAS                      284
#define OBJ_EVENT_GFX_PARASECT                   285
#define OBJ_EVENT_GFX_VENONAT                    286
#define OBJ_EVENT_GFX_VENOMOTH                   287
#define OBJ_EVENT_GFX_DIGLETT                    288
#define OBJ_EVENT_GFX_DUGTRIO                    289
#define OBJ_EVENT_GFX_MEOWTH                     290
#define OBJ_EVENT_GFX_PERSIAN                    291
#define OBJ_EVENT_GFX_PSYDUCK                    292
#define OBJ_EVENT_GFX_GOLDUCK                    293
#define OBJ_EVENT_GFX_MANKEY                     294
#define OBJ_EVENT_GFX_PRIMEAPE                   295
#define OBJ_EVENT_GFX_GROWLITHE                  296
#define OBJ_EVENT_GFX_ARCANINE                   297
#define OBJ_EVENT_GFX_POLIWAG                    298
#define OBJ_EVENT_GFX_POLIWHIRL                  299
#define OBJ_EVENT_GFX_POLIWRATH                  300
#define OBJ_EVENT_GFX_ABRA                       301
#define OBJ_EVENT_GFX_KADABRA                    302
#define OBJ_EVENT_GFX_ALAKAZAM                   303
#define OBJ_EVENT_GFX_MACHOP                     304
#define OBJ_EVENT_GFX_MACHOKE                    305
#define OBJ_EVENT_GFX_MACHAMP                    306
#define OBJ_EVENT_GFX_BELLSPROUT                 307
#define OBJ_EVENT_GFX_WEEPINBELL                 308
#define OBJ_EVENT_GFX_VICTREEBEL                 309
#define OBJ_EVENT_GFX_TENTACOOL                  310
#define OBJ_EVENT_GFX_TENTACRUEL                 311
#define OBJ_EVENT_GFX_GEODUDE                    312
#define OBJ_EVENT_GFX_GRAVELER                   313
#define OBJ_EVENT_GFX_GOLEM                      314
#define OBJ_EVENT_GFX_PONYTA                     315
#define OBJ_EVENT_GFX_RAPIDASH                   316
#define OBJ_EVENT_GFX_SLOWPOKE                   317
#define OBJ_EVENT_GFX_SLOWBRO                    318
#define OBJ_EVENT_GFX_MAGNEMITE                  319
#define OBJ_EVENT_GFX_MAGNETON                   320
#define OBJ_EVENT_GFX_FARFETCHD                  321
#define OBJ_EVENT_GFX_DODUO                      322
#define OBJ_EVENT_GFX_DODRIO                     323
#define OBJ_EVENT_GFX_SEEL                       324
#define OBJ_EVENT_GFX_DEWGONG                    325
#define OBJ_EVENT_GFX_GRIMER                     326
#define OBJ_EVENT_GFX_MUK                        327
#define OBJ_EVENT_GFX_SHELLDER                   328
#define OBJ_EVENT_GFX_CLOYSTER                   329
#define OBJ_EVENT_GFX_GASTLY                     330
#define OBJ_EVENT_GFX_HAUNTER                    331
#define OBJ_EVENT_GFX_GENGAR                     332
#define OBJ_EVENT_GFX_ONIX                       333
#define OBJ_EVENT_GFX_DROWZEE                    334
#define OBJ_EVENT_GFX_HYPNO                      335
#define OBJ_EVENT_GFX_KRABBY                     336
#define OBJ_EVENT_GFX_KINGLER                    337
#define OBJ_EVENT_GFX_VOLTORB                    338
#define OBJ_EVENT_GFX_ELECTRODE                  339
#define OBJ_EVENT_GFX_EXEGGCUTE                  340
#define OBJ_EVENT_GFX_EXEGGUTOR                  341
#define OBJ_EVENT_GFX_CUBONE                     342
#define OBJ_EVENT_GFX_MAROWAK                    343
#define OBJ_EVENT_GFX_HITMONLEE                  344
#define OBJ_EVENT_GFX_HITMONCHAN                 345
#define OBJ_EVENT_GFX_LICKITUNG                  346
#define OBJ_EVENT_GFX_KOFFING                    347
#define OBJ_EVENT_GFX_WEEZING                    348
#define OBJ_EVENT_GFX_RHYHORN                    349
#define OBJ_EVENT_GFX_RHYDON                     350
#define OBJ_EVENT_GFX_CHANSEY                    351
#define OBJ_EVENT_GFX_TANGELA                    352
#define OBJ_EVENT_GFX_KANGASKHAN                 353
#define OBJ_EVENT_GFX_HORSEA                     354
#define OBJ_EVENT_GFX_SEADRA                     355
#define OBJ_EVENT_GFX_GOLDEEN                    356
#define OBJ_EVENT_GFX_SEAKING                    357
#define OBJ_EVENT_GFX_STARYU                     358
#define OBJ_EVENT_GFX_STARMIE                    359
#define OBJ_EVENT_GFX_MR_MIME                    360
#define OBJ_EVENT_GFX_SCYTHER                    361
#define OBJ_EVENT_GFX_JYNX                       362
#define OBJ_EVENT_GFX_ELECTABUZZ                 363
#define OBJ_EVENT_GFX_MAGMAR                     364
#define OBJ_EVENT_GFX_PINSIR                     365
#define OBJ_EVENT_GFX_TAUROS                     366
#define OBJ_EVENT_GFX_MAGIKARP                   367
#define OBJ_EVENT_GFX_GYARADOS                   368
#define OBJ_EVENT_GFX_LAPRAS                     369
#define OBJ_EVENT_GFX_DITTO                      370
#define OBJ_EVENT_GFX_EEVEE                      371
#define OBJ_EVENT_GFX_VAPOREON                   372
#define OBJ_EVENT_GFX_JOLTEON                    373
#define OBJ_EVENT_GFX_FLAREON                    374
#define OBJ_EVENT_GFX_PORYGON                    375
#define OBJ_EVENT_GFX_OMANYTE                    376
#define OBJ_EVENT_GFX_OMASTAR                    377
#define OBJ_EVENT_GFX_KABUTO                     378
#define OBJ_EVENT_GFX_KABUTOPS                   379
#define OBJ_EVENT_GFX_AERODACTYL                 380
#define OBJ_EVENT_GFX_SNORLAX                    381
#define OBJ_EVENT_GFX_ARTICUNO                   382
#define OBJ_EVENT_GFX_ZAPDOS                     383
#define OBJ_EVENT_GFX_MOLTRES                    384
#define OBJ_EVENT_GFX_DRATINI                    385
#define OBJ_EVENT_GFX_DRAGONAIR                  386
#define OBJ_EVENT_GFX_DRAGONITE                  387
#define OBJ_EVENT_GFX_MEWTWO                     388
#define OBJ_EVENT_GFX_MEW_FOLLOWER               389
#define OBJ_EVENT_GFX_CHIKORITA                  390
#define OBJ_EVENT_GFX_BAYLEEF                    391
#define OBJ_EVENT_GFX_MEGANIUM                   392
#define OBJ_EVENT_GFX_CYNDAQUIL                  393
#define OBJ_EVENT_GFX_QUILAVA                    394
#define OBJ_EVENT_GFX_TYPHLOSION                 395
#define OBJ_EVENT_GFX_TOTODILE                   396
#define OBJ_EVENT_GFX_CROCONAW                   397
#define OBJ_EVENT_GFX_FERALIGATR                 398
#define OBJ_EVENT_GFX_SENTRET                    399
#define OBJ_EVENT_GFX_FURRET                     400
#define OBJ_EVENT_GFX_HOOTHOOT                   401
#define OBJ_EVENT_GFX_NOCTOWL                    402
#define OBJ_EVENT_GFX_LEDYBA                     403
#define OBJ_EVENT_GFX_LEDIAN                     404
#define OBJ_EVENT_GFX_SPINARAK                   405
#define OBJ_EVENT_GFX_ARIADOS                    406
#define OBJ_EVENT_GFX_CROBAT                     407
#define OBJ_EVENT_GFX_CHINCHOU                   408
#define OBJ_EVENT_GFX_LANTURN                    409
#define OBJ_EVENT_GFX_PICHU                      410
#define OBJ_EVENT_GFX_CLEFFA                     411
#define OBJ_EVENT_GFX_IGGLYBUFF                  412
#define OBJ_EVENT_GFX_TOGEPI                     413
#define OBJ_EVENT_GFX_TOGETIC                    414
#define OBJ_EVENT_GFX_NATU                       415
#define OBJ_EVENT_GFX_XATU                       416
#define OBJ_EVENT_GFX_MAREEP                     417
#define OBJ_EVENT_GFX_FLAAFFY                    418
#define OBJ_EVENT_GFX_AMPHAROS                   419
#define OBJ_EVENT_GFX_BELLOSSOM                  420
#define OBJ_EVENT_GFX_MARILL                     421
#define OBJ_EVENT_GFX_AZUMARILL_FOLLOWER         422
#define OBJ_EVENT_GFX_SUDOWOODO_FOLLOWER         423
#define OBJ_EVENT_GFX_POLITOED                   424
#define OBJ_EVENT_GFX_HOPPIP                     425
#define OBJ_EVENT_GFX_SKIPLOOM                   426
#define OBJ_EVENT_GFX_JUMPLUFF                   427
#define OBJ_EVENT_GFX_AIPOM                      428
#define OBJ_EVENT_GFX_SUNKERN                    429
#define OBJ_EVENT_GFX_SUNFLORA                   430
#define OBJ_EVENT_GFX_YANMA                      431
#define OBJ_EVENT_GFX_WOOPER                     432
#define OBJ_EVENT_GFX_QUAGSIRE                   433
#define OBJ_EVENT_GFX_ESPEON                     434
#define OBJ_EVENT_GFX_UMBREON                    435
#define OBJ_EVENT_GFX_MURKROW                    436
#define OBJ_EVENT_GFX_SLOWKING                   437
#define OBJ_EVENT_GFX_MISDREAVUS                 438
#define OBJ_EVENT_GFX_UNOWN_A                    439
#define OBJ_EVENT_GFX_WOBBUFFET                  440
#define OBJ_EVENT_GFX_GIRAFARIG                  441
#define OBJ_EVENT_GFX_PINECO                     442
#define OBJ_EVENT_GFX_FORRETRESS                 443
#define OBJ_EVENT_GFX_DUNSPARCE                  444
#define OBJ_EVENT_GFX_GLIGAR                     445
#define OBJ_EVENT_GFX_STEELIX                    446
#define OBJ_EVENT_GFX_SNUBBULL                   447
#define OBJ_EVENT_GFX_GRANBULL                   448
#define OBJ_EVENT_GFX_QWILFISH                   449
#define OBJ_EVENT_GFX_SCIZOR                     450
#define OBJ_EVENT_GFX_SHUCKLE                    451
#define OBJ_EVENT_GFX_HERACROSS                  452
#define OBJ_EVENT_GFX_SNEASEL                    453
#define OBJ_EVENT_GFX_TEDDIURSA                  454
#define OBJ_EVENT_GFX_URSARING                   455
#define OBJ_EVENT_GFX_SLUGMA                     456
#define OBJ_EVENT_GFX_MAGCARGO                   457
#define OBJ_EVENT_GFX_SWINUB                     458
#define OBJ_EVENT_GFX_PILOSWINE                  459
#define OBJ_EVENT_GFX_CORSOLA                    460
#define OBJ_EVENT_GFX_REMORAID                   461
#define OBJ_EVENT_GFX_OCTILLERY                  462
#define OBJ_EVENT_GFX_DELIBIRD                   463
#define OBJ_EVENT_GFX_MANTINE                    464
#define OBJ_EVENT_GFX_SKARMORY                   465
#define OBJ_EVENT_GFX_HOUNDOUR                   466
#define OBJ_EVENT_GFX_HOUNDOOM                   467
#define OBJ_EVENT_GFX_KINGDRA                    468
#define OBJ_EVENT_GFX_PHANPY                     469
#define OBJ_EVENT_GFX_DONPHAN                    470
#define OBJ_EVENT_GFX_PORYGON2                   471
#define OBJ_EVENT_GFX_STANTLER                   472
#define OBJ_EVENT_GFX_SMEARGLE                   473
#define OBJ_EVENT_GFX_TYROGUE                    474
#define OBJ_EVENT_GFX_HITMONTOP                  475
#define OBJ_EVENT_GFX_SMOOCHUM                   476
#define OBJ_EVENT_GFX_ELEKID                     477
#define OBJ_EVENT_GFX_MAGBY                      478
#define OBJ_EVENT_GFX_MILTANK                    479
#define OBJ_EVENT_GFX_BLISSEY                    480
#define OBJ_EVENT_GFX_RAIKOU                     481
#define OBJ_EVENT_GFX_ENTEI                      482
#define OBJ_EVENT_GFX_SUICUNE                    483
#define OBJ_EVENT_GFX_LARVITAR                   484
#define OBJ_EVENT_GFX_PUPITAR                    485
#define OBJ_EVENT_GFX_TYRANITAR                  486
#define OBJ_EVENT_GFX_LUGIA_FOLLOWER             487
#define OBJ_EVENT_GFX_HOOH_FOLLOWER              488
#define OBJ_EVENT_GFX_CELEBI                     489

#ifndef POKEMON_EXPANSION

#define OBJ_EVENT_GFX_GREAT_BALL                 490
#define OBJ_EVENT_GFX_ULTRA_BALL                 491
#define OBJ_EVENT_GFX_MASTER_BALL                492
#define OBJ_EVENT_GFX_SAFARI_BALL                493
#define OBJ_EVENT_GFX_NET_BALL                   494
#define OBJ_EVENT_GFX_DIVE_BALL                  495
#define OBJ_EVENT_GFX_NEST_BALL                  496
#define OBJ_EVENT_GFX_REPEAT_BALL                497
#define OBJ_EVENT_GFX_TIMER_BALL                 498
#define OBJ_EVENT_GFX_LUXURY_BALL                499
#define OBJ_EVENT_GFX_PREMIER_BALL               500
#define OBJ_EVENT_GFX_HEAL_BALL                  501
#define OBJ_EVENT_GFX_DUSK_BALL                  502
#define OBJ_EVENT_GFX_QUICK_BALL                 503
#define OBJ_EVENT_GFX_LEVEL_BALL                 504
#define OBJ_EVENT_GFX_LURE_BALL                  505
#define OBJ_EVENT_GFX_MOON_BALL                  506
#define OBJ_EVENT_GFX_FRIEND_BALL                507
#define OBJ_EVENT_GFX_LOVE_BALL                  508
#define OBJ_EVENT_GFX_FAST_BALL                  509
#define OBJ_EVENT_GFX_HEAVY_BALL                 510
#define OBJ_EVENT_GFX_DREAM_BALL                 511
#define OBJ_EVENT_GFX_SPORT_BALL                 512
#define OBJ_EVENT_GFX_PARK_BALL                  513
#define OBJ_EVENT_GFX_CHERISH_BALL               514

// Jump in numbers due to SPECIES_OLD_UNOWN constants
#define OBJ_EVENT_GFX_TREECKO                    515
#define OBJ_EVENT_GFX_GROVYLE                    516
#define OBJ_EVENT_GFX_SCEPTILE                   517
#define OBJ_EVENT_GFX_TORCHIC                    518
#define OBJ_EVENT_GFX_COMBUSKEN                  519
#define OBJ_EVENT_GFX_BLAZIKEN                   520
#define OBJ_EVENT_GFX_MUDKIP                     521
#define OBJ_EVENT_GFX_MARSHTOMP                  522
#define OBJ_EVENT_GFX_SWAMPERT                   523
#define OBJ_EVENT_GFX_POOCHYENA_FOLLOWER         524
#define OBJ_EVENT_GFX_MIGHTYENA                  525
#define OBJ_EVENT_GFX_ZIGZAGOON_FOLLOWER         526
#define OBJ_EVENT_GFX_LINOONE                    527
#define OBJ_EVENT_GFX_WURMPLE                    528
#define OBJ_EVENT_GFX_SILCOON                    529
#define OBJ_EVENT_GFX_BEAUTIFLY                  530
#define OBJ_EVENT_GFX_CASCOON                    531
#define OBJ_EVENT_GFX_DUSTOX                     532
#define OBJ_EVENT_GFX_LOTAD                      533
#define OBJ_EVENT_GFX_LOMBRE                     534
#define OBJ_EVENT_GFX_LUDICOLO                   535
#define OBJ_EVENT_GFX_SEEDOT                     536
#define OBJ_EVENT_GFX_NUZLEAF                    537
#define OBJ_EVENT_GFX_SHIFTRY                    538
#define OBJ_EVENT_GFX_NINCADA                    539
#define OBJ_EVENT_GFX_NINJASK                    540
#define OBJ_EVENT_GFX_SHEDINJA                   541
#define OBJ_EVENT_GFX_TAILLOW                    542
#define OBJ_EVENT_GFX_SWELLOW                    543
#define OBJ_EVENT_GFX_SHROOMISH                  544
#define OBJ_EVENT_GFX_BRELOOM                    545
#define OBJ_EVENT_GFX_SPINDA                     546
#define OBJ_EVENT_GFX_WINGULL_FOLLOWER           547
#define OBJ_EVENT_GFX_PELIPPER                   548
#define OBJ_EVENT_GFX_SURSKIT                    549
#define OBJ_EVENT_GFX_MASQUERAIN                 550
#define OBJ_EVENT_GFX_WAILMER                    551
#define OBJ_EVENT_GFX_WAILORD                    552
#define OBJ_EVENT_GFX_SKITTY_FOLLOWER            553
#define OBJ_EVENT_GFX_DELCATTY                   554
#define OBJ_EVENT_GFX_KECLEON_FOLLOWER           555
#define OBJ_EVENT_GFX_BALTOY                     556
#define OBJ_EVENT_GFX_CLAYDOL                    557
#define OBJ_EVENT_GFX_NOSEPASS                   558
#define OBJ_EVENT_GFX_TORKOAL                    559
#define OBJ_EVENT_GFX_SABLEYE                    560
#define OBJ_EVENT_GFX_BARBOACH                   561
#define OBJ_EVENT_GFX_WHISCASH                   562
#define OBJ_EVENT_GFX_LUVDISC                    563
#define OBJ_EVENT_GFX_CORPHISH                   564
#define OBJ_EVENT_GFX_CRAWDAUNT                  565
#define OBJ_EVENT_GFX_FEEBAS                     566
#define OBJ_EVENT_GFX_MILOTIC                    567
#define OBJ_EVENT_GFX_CARVANHA                   568
#define OBJ_EVENT_GFX_SHARPEDO                   569
#define OBJ_EVENT_GFX_TRAPINCH                   570
#define OBJ_EVENT_GFX_VIBRAVA                    571
#define OBJ_EVENT_GFX_FLYGON                     572
#define OBJ_EVENT_GFX_MAKUHITA                   573
#define OBJ_EVENT_GFX_HARIYAMA                   574
#define OBJ_EVENT_GFX_ELECTRIKE                  575
#define OBJ_EVENT_GFX_MANECTRIC                  576
#define OBJ_EVENT_GFX_NUMEL                      577
#define OBJ_EVENT_GFX_CAMERUPT                   578
#define OBJ_EVENT_GFX_SPHEAL                     579
#define OBJ_EVENT_GFX_SEALEO                     580
#define OBJ_EVENT_GFX_WALREIN                    581
#define OBJ_EVENT_GFX_CACNEA                     582
#define OBJ_EVENT_GFX_CACTURNE                   583
#define OBJ_EVENT_GFX_SNORUNT                    584
#define OBJ_EVENT_GFX_GLALIE                     585
#define OBJ_EVENT_GFX_LUNATONE                   586
#define OBJ_EVENT_GFX_SOLROCK                    587
#define OBJ_EVENT_GFX_AZURILL_FOLLOWER           588
#define OBJ_EVENT_GFX_SPOINK                     589
#define OBJ_EVENT_GFX_GRUMPIG                    590
#define OBJ_EVENT_GFX_PLUSLE                     591
#define OBJ_EVENT_GFX_MINUN                      592
#define OBJ_EVENT_GFX_MAWILE                     593
#define OBJ_EVENT_GFX_MEDITITE                   594
#define OBJ_EVENT_GFX_MEDICHAM                   595
#define OBJ_EVENT_GFX_SWABLU                     596
#define OBJ_EVENT_GFX_ALTARIA                    597
#define OBJ_EVENT_GFX_WYNAUT                     598
#define OBJ_EVENT_GFX_DUSKULL                    599
#define OBJ_EVENT_GFX_DUSCLOPS_FOLLOWER          600
#define OBJ_EVENT_GFX_ROSELIA                    601
#define OBJ_EVENT_GFX_SLAKOTH                    602
#define OBJ_EVENT_GFX_VIGOROTH_FOLLOWER          603
#define OBJ_EVENT_GFX_SLAKING                    604
#define OBJ_EVENT_GFX_GULPIN                     605
#define OBJ_EVENT_GFX_SWALOT                     606
#define OBJ_EVENT_GFX_TROPIUS                    607
#define OBJ_EVENT_GFX_WHISMUR                    608
#define OBJ_EVENT_GFX_LOUDRED                    609
#define OBJ_EVENT_GFX_EXPLOUD                    610
#define OBJ_EVENT_GFX_CLAMPERL                   611
#define OBJ_EVENT_GFX_HUNTAIL                    612
#define OBJ_EVENT_GFX_GOREBYSS                   613
#define OBJ_EVENT_GFX_ABSOL                      614
#define OBJ_EVENT_GFX_SHUPPET                    615
#define OBJ_EVENT_GFX_BANETTE                    616
#define OBJ_EVENT_GFX_SEVIPER                    617
#define OBJ_EVENT_GFX_ZANGOOSE                   618
#define OBJ_EVENT_GFX_RELICANTH                  619
#define OBJ_EVENT_GFX_ARON                       620
#define OBJ_EVENT_GFX_LAIRON                     621
#define OBJ_EVENT_GFX_AGGRON                     622
#define OBJ_EVENT_GFX_CASTFORM                   623
#define OBJ_EVENT_GFX_VOLBEAT                    624
#define OBJ_EVENT_GFX_ILLUMISE                   625
#define OBJ_EVENT_GFX_LILEEP                     626
#define OBJ_EVENT_GFX_CRADILY                    627
#define OBJ_EVENT_GFX_ANORITH                    628
#define OBJ_EVENT_GFX_ARMALDO                    629
#define OBJ_EVENT_GFX_RALTS                      630
#define OBJ_EVENT_GFX_KIRLIA_FOLLOWER            631
#define OBJ_EVENT_GFX_GARDEVOIR                  632
#define OBJ_EVENT_GFX_BAGON                      633
#define OBJ_EVENT_GFX_SHELGON                    634
#define OBJ_EVENT_GFX_SALAMENCE                  635
#define OBJ_EVENT_GFX_BELDUM                     636
#define OBJ_EVENT_GFX_METANG                     637
#define OBJ_EVENT_GFX_METAGROSS                  638
#define OBJ_EVENT_GFX_REGIROCK_FOLLOWER          639
#define OBJ_EVENT_GFX_REGICE_FOLLOWER            640
#define OBJ_EVENT_GFX_REGISTEEL_FOLLOWER         641
#define OBJ_EVENT_GFX_KYOGRE                     642
#define OBJ_EVENT_GFX_GROUDON                    643
#define OBJ_EVENT_GFX_RAYQUAZA_FOLLOWER          644
#define OBJ_EVENT_GFX_LATIAS_FOLLOWER            645
#define OBJ_EVENT_GFX_LATIOS_FOLLOWER            646
#define OBJ_EVENT_GFX_JIRACHI                    647
#define OBJ_EVENT_GFX_DEOXYS_NORMAL              648
#define OBJ_EVENT_GFX_CHIMECHO                   649

// Other forms
#define OBJ_EVENT_GFX_DEOXYS_ATTACK              650
#define OBJ_EVENT_GFX_DEOXYS_DEFENSE             651
#define OBJ_EVENT_GFX_DEOXYS_SPEED               652
#define OBJ_EVENT_GFX_UNOWN_B                    653
#define OBJ_EVENT_GFX_UNOWN_C                    654
#define OBJ_EVENT_GFX_UNOWN_D                    655
#define OBJ_EVENT_GFX_UNOWN_E                    656
#define OBJ_EVENT_GFX_UNOWN_F                    657
#define OBJ_EVENT_GFX_UNOWN_G                    658
#define OBJ_EVENT_GFX_UNOWN_H                    659
#define OBJ_EVENT_GFX_UNOWN_I                    660
#define OBJ_EVENT_GFX_UNOWN_J                    661
#define OBJ_EVENT_GFX_UNOWN_K                    662
#define OBJ_EVENT_GFX_UNOWN_L                    663
#define OBJ_EVENT_GFX_UNOWN_M                    664
#define OBJ_EVENT_GFX_UNOWN_N                    665
#define OBJ_EVENT_GFX_UNOWN_O                    666
#define OBJ_EVENT_GFX_UNOWN_P                    667
#define OBJ_EVENT_GFX_UNOWN_Q                    668
#define OBJ_EVENT_GFX_UNOWN_R                    669
#define OBJ_EVENT_GFX_UNOWN_S                    670
#define OBJ_EVENT_GFX_UNOWN_T                    671
#define OBJ_EVENT_GFX_UNOWN_U                    672
#define OBJ_EVENT_GFX_UNOWN_V                    673
#define OBJ_EVENT_GFX_UNOWN_W                    674
#define OBJ_EVENT_GFX_UNOWN_X                    675
#define OBJ_EVENT_GFX_UNOWN_Y                    676
#define OBJ_EVENT_GFX_UNOWN_Z                    677
#define OBJ_EVENT_GFX_UNOWN_EXCLAMATION          678
#define OBJ_EVENT_GFX_UNOWN_QUESTION             679

#define OBJ_EVENT_GFX_EXPANDING_SPARKLE          680

#else
// There are no OLD_UNOWN constants in the pokemon_expansion, and the species constants are reordered

#define OBJ_EVENT_GFX_TREECKO                    490
#define OBJ_EVENT_GFX_GROVYLE                    491
#define OBJ_EVENT_GFX_SCEPTILE                   492
#define OBJ_EVENT_GFX_TORCHIC                    493
#define OBJ_EVENT_GFX_COMBUSKEN                  494
#define OBJ_EVENT_GFX_BLAZIKEN                   495
#define OBJ_EVENT_GFX_MUDKIP                     496
#define OBJ_EVENT_GFX_MARSHTOMP                  497
#define OBJ_EVENT_GFX_SWAMPERT                   498
#define OBJ_EVENT_GFX_POOCHYENA_FOLLOWER         499
#define OBJ_EVENT_GFX_MIGHTYENA                  500
#define OBJ_EVENT_GFX_ZIGZAGOON_FOLLOWER         501
#define OBJ_EVENT_GFX_LINOONE                    502
#define OBJ_EVENT_GFX_WURMPLE                    503
#define OBJ_EVENT_GFX_SILCOON                    504
#define OBJ_EVENT_GFX_BEAUTIFLY                  505
#define OBJ_EVENT_GFX_CASCOON                    506
#define OBJ_EVENT_GFX_DUSTOX                     507
#define OBJ_EVENT_GFX_LOTAD                      508
#define OBJ_EVENT_GFX_LOMBRE                     509
#define OBJ_EVENT_GFX_LUDICOLO                   510
#define OBJ_EVENT_GFX_SEEDOT                     511
#define OBJ_EVENT_GFX_NUZLEAF                    512
#define OBJ_EVENT_GFX_SHIFTRY                    513
#define OBJ_EVENT_GFX_TAILLOW                    514
#define OBJ_EVENT_GFX_SWELLOW                    515
#define OBJ_EVENT_GFX_WINGULL_FOLLOWER           516
#define OBJ_EVENT_GFX_PELIPPER                   517
#define OBJ_EVENT_GFX_RALTS                      518
#define OBJ_EVENT_GFX_KIRLIA_FOLLOWER            519
#define OBJ_EVENT_GFX_GARDEVOIR                  520
#define OBJ_EVENT_GFX_SURSKIT                    521
#define OBJ_EVENT_GFX_MASQUERAIN                 522
#define OBJ_EVENT_GFX_SHROOMISH                  523
#define OBJ_EVENT_GFX_BRELOOM                    524
#define OBJ_EVENT_GFX_SLAKOTH                    525
#define OBJ_EVENT_GFX_VIGOROTH_FOLLOWER          526
#define OBJ_EVENT_GFX_SLAKING                    527
#define OBJ_EVENT_GFX_NINCADA                    528
#define OBJ_EVENT_GFX_NINJASK                    529
#define OBJ_EVENT_GFX_SHEDINJA                   530
#define OBJ_EVENT_GFX_WHISMUR                    531
#define OBJ_EVENT_GFX_LOUDRED                    532
#define OBJ_EVENT_GFX_EXPLOUD                    533
#define OBJ_EVENT_GFX_MAKUHITA                   534
#define OBJ_EVENT_GFX_HARIYAMA                   535
#define OBJ_EVENT_GFX_AZURILL_FOLLOWER           536
#define OBJ_EVENT_GFX_NOSEPASS                   537
#define OBJ_EVENT_GFX_SKITTY_FOLLOWER            538
#define OBJ_EVENT_GFX_DELCATTY                   539
#define OBJ_EVENT_GFX_SABLEYE                    540
#define OBJ_EVENT_GFX_MAWILE                     541
#define OBJ_EVENT_GFX_ARON                       542
#define OBJ_EVENT_GFX_LAIRON                     543
#define OBJ_EVENT_GFX_AGGRON                     544
#define OBJ_EVENT_GFX_MEDITITE                   545
#define OBJ_EVENT_GFX_MEDICHAM                   546
#define OBJ_EVENT_GFX_ELECTRIKE                  547
#define OBJ_EVENT_GFX_MANECTRIC                  548
#define OBJ_EVENT_GFX_PLUSLE                     549
#define OBJ_EVENT_GFX_MINUN                      550
#define OBJ_EVENT_GFX_VOLBEAT                    551
#define OBJ_EVENT_GFX_ILLUMISE                   552
#define OBJ_EVENT_GFX_ROSELIA                    553
#define OBJ_EVENT_GFX_GULPIN                     554
#define OBJ_EVENT_GFX_SWALOT                     555
#define OBJ_EVENT_GFX_CARVANHA                   556
#define OBJ_EVENT_GFX_SHARPEDO                   557
#define OBJ_EVENT_GFX_WAILMER                    558
#define OBJ_EVENT_GFX_WAILORD                    559
#define OBJ_EVENT_GFX_NUMEL                      560
#define OBJ_EVENT_GFX_CAMERUPT                   561
#define OBJ_EVENT_GFX_TORKOAL                    562
#define OBJ_EVENT_GFX_SPOINK                     563
#define OBJ_EVENT_GFX_GRUMPIG                    564
#define OBJ_EVENT_GFX_SPINDA                     565
#define OBJ_EVENT_GFX_TRAPINCH                   566
#define OBJ_EVENT_GFX_VIBRAVA                    567
#define OBJ_EVENT_GFX_FLYGON                     568
#define OBJ_EVENT_GFX_CACNEA                     569
#define OBJ_EVENT_GFX_CACTURNE                   570
#define OBJ_EVENT_GFX_SWABLU                     571
#define OBJ_EVENT_GFX_ALTARIA                    572
#define OBJ_EVENT_GFX_ZANGOOSE                   573
#define OBJ_EVENT_GFX_SEVIPER                    574
#define OBJ_EVENT_GFX_LUNATONE                   575
#define OBJ_EVENT_GFX_SOLROCK                    576
#define OBJ_EVENT_GFX_BARBOACH                   577
#define OBJ_EVENT_GFX_WHISCASH                   578
#define OBJ_EVENT_GFX_CORPHISH                   579
#define OBJ_EVENT_GFX_CRAWDAUNT                  580
#define OBJ_EVENT_GFX_BALTOY                     581
#define OBJ_EVENT_GFX_CLAYDOL                    582
#define OBJ_EVENT_GFX_LILEEP                     583
#define OBJ_EVENT_GFX_CRADILY                    584
#define OBJ_EVENT_GFX_ANORITH                    585
#define OBJ_EVENT_GFX_ARMALDO                    586
#define OBJ_EVENT_GFX_FEEBAS                     587
#define OBJ_EVENT_GFX_MILOTIC                    588
#define OBJ_EVENT_GFX_CASTFORM                   589
#define OBJ_EVENT_GFX_KECLEON_FOLLOWER           590
#define OBJ_EVENT_GFX_SHUPPET                    591
#define OBJ_EVENT_GFX_BANETTE                    592
#define OBJ_EVENT_GFX_DUSKULL                    593
#define OBJ_EVENT_GFX_DUSCLOPS_FOLLOWER          594
#define OBJ_EVENT_GFX_TROPIUS                    595
#define OBJ_EVENT_GFX_CHIMECHO                   596
#define OBJ_EVENT_GFX_ABSOL                      597
#define OBJ_EVENT_GFX_WYNAUT                     598
#define OBJ_EVENT_GFX_SNORUNT                    599
#define OBJ_EVENT_GFX_GLALIE                     600
#define OBJ_EVENT_GFX_SPHEAL                     601
#define OBJ_EVENT_GFX_SEALEO                     602
#define OBJ_EVENT_GFX_WALREIN                    603
#define OBJ_EVENT_GFX_CLAMPERL                   604
#define OBJ_EVENT_GFX_HUNTAIL                    605
#define OBJ_EVENT_GFX_GOREBYSS                   606
#define OBJ_EVENT_GFX_RELICANTH                  607
#define OBJ_EVENT_GFX_LUVDISC                    608
#define OBJ_EVENT_GFX_BAGON                      609
#define OBJ_EVENT_GFX_SHELGON                    610
#define OBJ_EVENT_GFX_SALAMENCE                  611
#define OBJ_EVENT_GFX_BELDUM                     612
#define OBJ_EVENT_GFX_METANG                     613
#define OBJ_EVENT_GFX_METAGROSS                  614
#define OBJ_EVENT_GFX_REGIROCK_FOLLOWER          615
#define OBJ_EVENT_GFX_REGICE_FOLLOWER            616
#define OBJ_EVENT_GFX_REGISTEEL_FOLLOWER         617
#define OBJ_EVENT_GFX_LATIAS_FOLLOWER            618
#define OBJ_EVENT_GFX_LATIOS_FOLLOWER            619
#define OBJ_EVENT_GFX_KYOGRE                     620
#define OBJ_EVENT_GFX_GROUDON                    621
#define OBJ_EVENT_GFX_RAYQUAZA_FOLLOWER          622
#define OBJ_EVENT_GFX_JIRACHI                    623
#define OBJ_EVENT_GFX_DEOXYS_NORMAL              624

// Other forms
#define OBJ_EVENT_GFX_DEOXYS_ATTACK              625
#define OBJ_EVENT_GFX_DEOXYS_DEFENSE             626
#define OBJ_EVENT_GFX_DEOXYS_SPEED               627
#define OBJ_EVENT_GFX_UNOWN_B                    628
#define OBJ_EVENT_GFX_UNOWN_C                    629
#define OBJ_EVENT_GFX_UNOWN_D                    630
#define OBJ_EVENT_GFX_UNOWN_E                    631
#define OBJ_EVENT_GFX_UNOWN_F                    632
#define OBJ_EVENT_GFX_UNOWN_G                    633
#define OBJ_EVENT_GFX_UNOWN_H                    634
#define OBJ_EVENT_GFX_UNOWN_I                    635
#define OBJ_EVENT_GFX_UNOWN_J                    636
#define OBJ_EVENT_GFX_UNOWN_K                    637
#define OBJ_EVENT_GFX_UNOWN_L                    638
#define OBJ_EVENT_GFX_UNOWN_M                    639
#define OBJ_EVENT_GFX_UNOWN_N                    640
#define OBJ_EVENT_GFX_UNOWN_O                    641
#define OBJ_EVENT_GFX_UNOWN_P                    642
#define OBJ_EVENT_GFX_UNOWN_Q                    643
#define OBJ_EVENT_GFX_UNOWN_R                    644
#define OBJ_EVENT_GFX_UNOWN_S                    645
#define OBJ_EVENT_GFX_UNOWN_T                    646
#define OBJ_EVENT_GFX_UNOWN_U                    647
#define OBJ_EVENT_GFX_UNOWN_V                    648
#define OBJ_EVENT_GFX_UNOWN_W                    649
#define OBJ_EVENT_GFX_UNOWN_X                    650
#define OBJ_EVENT_GFX_UNOWN_Y                    651
#define OBJ_EVENT_GFX_UNOWN_Z                    652
#define OBJ_EVENT_GFX_UNOWN_EXCLAMATION          653
#define OBJ_EVENT_GFX_UNOWN_QUESTION             654

#define OBJ_EVENT_GFX_GREAT_BALL                 655
#define OBJ_EVENT_GFX_ULTRA_BALL                 656
#define OBJ_EVENT_GFX_MASTER_BALL                657
#define OBJ_EVENT_GFX_SAFARI_BALL                658
#define OBJ_EVENT_GFX_NET_BALL                   659
#define OBJ_EVENT_GFX_DIVE_BALL                  660
#define OBJ_EVENT_GFX_NEST_BALL                  661
#define OBJ_EVENT_GFX_REPEAT_BALL                662
#define OBJ_EVENT_GFX_TIMER_BALL                 663
#define OBJ_EVENT_GFX_LUXURY_BALL                664
#define OBJ_EVENT_GFX_PREMIER_BALL               665
#define OBJ_EVENT_GFX_HEAL_BALL                  666
#define OBJ_EVENT_GFX_DUSK_BALL                  667
#define OBJ_EVENT_GFX_QUICK_BALL                 668
#define OBJ_EVENT_GFX_LEVEL_BALL                 669
#define OBJ_EVENT_GFX_LURE_BALL                  670
#define OBJ_EVENT_GFX_MOON_BALL                  671
#define OBJ_EVENT_GFX_FRIEND_BALL                672
#define OBJ_EVENT_GFX_LOVE_BALL                  673
#define OBJ_EVENT_GFX_FAST_BALL                  674
#define OBJ_EVENT_GFX_HEAVY_BALL                 675
#define OBJ_EVENT_GFX_DREAM_BALL                 676
#define OBJ_EVENT_GFX_SPORT_BALL                 677
#define OBJ_EVENT_GFX_PARK_BALL                  678
#define OBJ_EVENT_GFX_CHERISH_BALL               679
#define OBJ_EVENT_GFX_EXPANDING_SPARKLE          680

#endif

#define NUM_OBJ_EVENT_GFX                        681


// These are dynamic object gfx ids.
// They correspond with the values of the VAR_OBJ_GFX_ID_X vars.
// More info about them in include/constants/vars.h
#define OBJ_EVENT_GFX_VARS   (NUM_OBJ_EVENT_GFX + 1)
#define OBJ_EVENT_GFX_VAR_0  (OBJ_EVENT_GFX_VARS + 0x0) // 240
#define OBJ_EVENT_GFX_VAR_1  (OBJ_EVENT_GFX_VARS + 0x1)
#define OBJ_EVENT_GFX_VAR_2  (OBJ_EVENT_GFX_VARS + 0x2)
#define OBJ_EVENT_GFX_VAR_3  (OBJ_EVENT_GFX_VARS + 0x3)
#define OBJ_EVENT_GFX_VAR_4  (OBJ_EVENT_GFX_VARS + 0x4)
#define OBJ_EVENT_GFX_VAR_5  (OBJ_EVENT_GFX_VARS + 0x5)
#define OBJ_EVENT_GFX_VAR_6  (OBJ_EVENT_GFX_VARS + 0x6)
#define OBJ_EVENT_GFX_VAR_7  (OBJ_EVENT_GFX_VARS + 0x7)
#define OBJ_EVENT_GFX_VAR_8  (OBJ_EVENT_GFX_VARS + 0x8)
#define OBJ_EVENT_GFX_VAR_9  (OBJ_EVENT_GFX_VARS + 0x9)
#define OBJ_EVENT_GFX_VAR_A  (OBJ_EVENT_GFX_VARS + 0xA)
#define OBJ_EVENT_GFX_VAR_B  (OBJ_EVENT_GFX_VARS + 0xB)
#define OBJ_EVENT_GFX_VAR_C  (OBJ_EVENT_GFX_VARS + 0xC)
#define OBJ_EVENT_GFX_VAR_D  (OBJ_EVENT_GFX_VARS + 0xD)
#define OBJ_EVENT_GFX_VAR_E  (OBJ_EVENT_GFX_VARS + 0xE)
#define OBJ_EVENT_GFX_VAR_F  (OBJ_EVENT_GFX_VARS + 0xF) // 255

#define SHADOW_SIZE_S   0
#define SHADOW_SIZE_M   1
#define SHADOW_SIZE_L   2
#define SHADOW_SIZE_XL  3

#define F_INANIMATE                        (1 << 6)
#define F_DISABLE_REFLECTION_PALETTE_LOAD  (1 << 7)

#define TRACKS_NONE       0
#define TRACKS_FOOT       1
#define TRACKS_BIKE_TIRE  2
#define TRACKS_SLITHER    3
#define TRACKS_SPOT       4
#define TRACKS_BUG        5

#define FIRST_DECORATION_SPRITE_GFX OBJ_EVENT_GFX_PICHU_DOLL

// Special object event local ids
#define OBJ_EVENT_ID_PLAYER 0xFF
#define OBJ_EVENT_ID_FOLLOWER 0xFE
#define OBJ_EVENT_ID_CAMERA 0x7F

// Object event local ids referenced in C files
#define LOCALID_ROUTE111_PLAYER_FALLING 45
#define LOCALID_BIRTH_ISLAND_EXTERIOR_ROCK 1
#define LOCALID_FARAWAY_ISLAND_MEW 1
#define LOCALID_UNION_ROOM_PLAYER_4 2
#define LOCALID_UNION_ROOM_PLAYER_8 3
#define LOCALID_UNION_ROOM_PLAYER_7 4
#define LOCALID_UNION_ROOM_PLAYER_6 5
#define LOCALID_UNION_ROOM_PLAYER_5 6
#define LOCALID_UNION_ROOM_PLAYER_3 7
#define LOCALID_UNION_ROOM_PLAYER_2 8
#define LOCALID_UNION_ROOM_PLAYER_1 9
#define LOCALID_BATTLE_TOWER_LOBBY_REPORTER 5
#define LOCALID_TRUCK_BOX_TOP 1
#define LOCALID_TRUCK_BOX_BOTTOM_L 2
#define LOCALID_TRUCK_BOX_BOTTOM_R 3
#define LOCALID_OLDALE_MART_CLERK 1
#define LOCALID_LAVARIDGE_MART_CLERK 1
#define LOCALID_FALLARBOR_MART_CLERK 1
#define LOCALID_VERDANTURF_MART_CLERK 1
#define LOCALID_PETALBURG_MART_CLERK 1
#define LOCALID_SLATEPORT_MART_CLERK 1
#define LOCALID_MAUVILLE_MART_CLERK 1
#define LOCALID_RUSTBORO_MART_CLERK 1
#define LOCALID_FORTREE_MART_CLERK 1
#define LOCALID_MOSSDEEP_MART_CLERK 1
#define LOCALID_SOOTOPOLIS_MART_CLERK 1
#define LOCALID_BATTLE_FRONTIER_MART_CLERK 1
#define LOCALID_SLATEPORT_ENERGY_GURU 25

#endif  // GUARD_CONSTANTS_EVENT_OBJECTS_H
