#ifndef GUARD_CONSTANTS_EVENT_BG_H
#define GUARD_CONSTANTS_EVENT_BG_H

#define BG_EVENT_PLAYER_FACING_ANY   0
#define BG_EVENT_PLAYER_FACING_NORTH 1
#define BG_EVENT_PLAYER_FACING_SOUTH 2
#define BG_EVENT_PLAYER_FACING_EAST  3
#define BG_EVENT_PLAYER_FACING_WEST  4

#define BG_EVENT_HIDDEN_ITEM         7
#define BG_EVENT_SECRET_BASE         8

#endif // GUARD_CONSTANTS_EVENT_BG_H
