#ifndef GUARD_CONSTANTS_EVENT_OBJECTS_H
#define GUARD_CONSTANTS_EVENT_OBJECTS_H

#define OBJ_EVENT_GFX_BRENDAN_NORMAL               0
#define OBJ_EVENT_GFX_BRENDAN_MACH_BIKE            1
#define OBJ_EVENT_GFX_BRENDAN_SURFING              2
#define OBJ_EVENT_GFX_BRENDAN_FIELD_MOVE           3
#define OBJ_EVENT_GFX_QUINTY_PLUMP                 4
#define OBJ_EVENT_GFX_NINJA_BOY                    5
#define OBJ_EVENT_GFX_TWIN                         6
#define OBJ_EVENT_GFX_BOY_1                        7
#define OBJ_EVENT_GFX_GIRL_1                       8
#define OBJ_EVENT_GFX_BOY_2                        9
#define OBJ_EVENT_GFX_GIRL_2                      10
#define OBJ_EVENT_GFX_LITTLE_BOY                  11
#define OBJ_EVENT_GFX_LITTLE_GIRL                 12
#define OBJ_EVENT_GFX_BOY_3                       13
#define OBJ_EVENT_GFX_GIRL_3                      14
#define OBJ_EVENT_GFX_RICH_BOY                    15
#define OBJ_EVENT_GFX_WOMAN_1                     16
#define OBJ_EVENT_GFX_FAT_MAN                     17
#define OBJ_EVENT_GFX_POKEFAN_F                   18
#define OBJ_EVENT_GFX_MAN_1                       19
#define OBJ_EVENT_GFX_WOMAN_2                     20
#define OBJ_EVENT_GFX_EXPERT_M                    21
#define OBJ_EVENT_GFX_EXPERT_F                    22
#define OBJ_EVENT_GFX_MAN_2                       23
#define OBJ_EVENT_GFX_WOMAN_3                     24
#define OBJ_EVENT_GFX_POKEFAN_M                   25
#define OBJ_EVENT_GFX_WOMAN_4                     26
#define OBJ_EVENT_GFX_COOK                        27
#define OBJ_EVENT_GFX_LINK_RECEPTIONIST           28
#define OBJ_EVENT_GFX_OLD_MAN                     29
#define OBJ_EVENT_GFX_OLD_WOMAN                   30
#define OBJ_EVENT_GFX_CAMPER                      31
#define OBJ_EVENT_GFX_PICNICKER                   32
#define OBJ_EVENT_GFX_MAN_3                       33
#define OBJ_EVENT_GFX_WOMAN_5                     34
#define OBJ_EVENT_GFX_YOUNGSTER                   35
#define OBJ_EVENT_GFX_BUG_CATCHER                 36
#define OBJ_EVENT_GFX_PSYCHIC_M                   37
#define OBJ_EVENT_GFX_SCHOOL_KID_M                38
#define OBJ_EVENT_GFX_MANIAC                      39
#define OBJ_EVENT_GFX_HEX_MANIAC                  40
#define OBJ_EVENT_GFX_RAYQUAZA_STILL              41
#define OBJ_EVENT_GFX_SWIMMER_M                   42
#define OBJ_EVENT_GFX_SWIMMER_F                   43
#define OBJ_EVENT_GFX_BLACK_BELT                  44
#define OBJ_EVENT_GFX_BEAUTY                      45
#define OBJ_EVENT_GFX_SCIENTIST_1                 46
#define OBJ_EVENT_GFX_LASS                        47
#define OBJ_EVENT_GFX_GENTLEMAN                   48
#define OBJ_EVENT_GFX_SAILOR                      49
#define OBJ_EVENT_GFX_FISHERMAN                   50
#define OBJ_EVENT_GFX_RUNNING_TRIATHLETE_M        51
#define OBJ_EVENT_GFX_RUNNING_TRIATHLETE_F        52
#define OBJ_EVENT_GFX_TUBER_F                     53
#define OBJ_EVENT_GFX_TUBER_M                     54
#define OBJ_EVENT_GFX_HIKER                       55
#define OBJ_EVENT_GFX_CYCLING_TRIATHLETE_M        56
#define OBJ_EVENT_GFX_CYCLING_TRIATHLETE_F        57
#define OBJ_EVENT_GFX_NURSE                       58
#define OBJ_EVENT_GFX_ITEM_BALL                   59
#define OBJ_EVENT_GFX_BERRY_TREE                  60
#define OBJ_EVENT_GFX_BERRY_TREE_EARLY_STAGES     61
#define OBJ_EVENT_GFX_BERRY_TREE_LATE_STAGES      62
#define OBJ_EVENT_GFX_BRENDAN_ACRO_BIKE           63
#define OBJ_EVENT_GFX_PROF_BIRCH                  64
#define OBJ_EVENT_GFX_MAN_4                       65
#define OBJ_EVENT_GFX_MAN_5                       66
#define OBJ_EVENT_GFX_REPORTER_M                  67
#define OBJ_EVENT_GFX_REPORTER_F                  68
#define OBJ_EVENT_GFX_BARD                        69
#define OBJ_EVENT_GFX_ANABEL                      70
#define OBJ_EVENT_GFX_TUCKER                      71
#define OBJ_EVENT_GFX_GRETA                       72
#define OBJ_EVENT_GFX_SPENSER                     73
#define OBJ_EVENT_GFX_NOLAND                      74
#define OBJ_EVENT_GFX_LUCY                        75
#define OBJ_EVENT_GFX_UNUSED_NATU_DOLL            76
#define OBJ_EVENT_GFX_UNUSED_MAGNEMITE_DOLL       77
#define OBJ_EVENT_GFX_UNUSED_SQUIRTLE_DOLL        78
#define OBJ_EVENT_GFX_UNUSED_WOOPER_DOLL          79
#define OBJ_EVENT_GFX_UNUSED_PIKACHU_DOLL         80
#define OBJ_EVENT_GFX_UNUSED_PORYGON2_DOLL        81
#define OBJ_EVENT_GFX_CUTTABLE_TREE               82
#define OBJ_EVENT_GFX_MART_EMPLOYEE               83
#define OBJ_EVENT_GFX_ROOFTOP_SALE_WOMAN          84
#define OBJ_EVENT_GFX_TEALA                       85
#define OBJ_EVENT_GFX_BREAKABLE_ROCK              86
#define OBJ_EVENT_GFX_PUSHABLE_BOULDER            87
#define OBJ_EVENT_GFX_MR_BRINEYS_BOAT             88
#define OBJ_EVENT_GFX_MAY_NORMAL                  89
#define OBJ_EVENT_GFX_MAY_MACH_BIKE               90
#define OBJ_EVENT_GFX_MAY_ACRO_BIKE               91
#define OBJ_EVENT_GFX_MAY_SURFING                 92
#define OBJ_EVENT_GFX_MAY_FIELD_MOVE              93
#define OBJ_EVENT_GFX_TRUCK                       94
#define OBJ_EVENT_GFX_VIGOROTH_CARRYING_BOX       95
#define OBJ_EVENT_GFX_VIGOROTH_FACING_AWAY        96
#define OBJ_EVENT_GFX_BIRCHS_BAG                  97
#define OBJ_EVENT_GFX_ZIGZAGOON_1                 98
#define OBJ_EVENT_GFX_ARTIST                      99
#define OBJ_EVENT_GFX_RIVAL_BRENDAN_NORMAL       100
#define OBJ_EVENT_GFX_RIVAL_BRENDAN_MACH_BIKE    101
#define OBJ_EVENT_GFX_RIVAL_BRENDAN_ACRO_BIKE    102
#define OBJ_EVENT_GFX_RIVAL_BRENDAN_SURFING      103
#define OBJ_EVENT_GFX_RIVAL_BRENDAN_FIELD_MOVE   104
#define OBJ_EVENT_GFX_RIVAL_MAY_NORMAL           105
#define OBJ_EVENT_GFX_RIVAL_MAY_MACH_BIKE        106
#define OBJ_EVENT_GFX_RIVAL_MAY_ACRO_BIKE        107
#define OBJ_EVENT_GFX_RIVAL_MAY_SURFING          108
#define OBJ_EVENT_GFX_RIVAL_MAY_FIELD_MOVE       109
#define OBJ_EVENT_GFX_CAMERAMAN                  110
#define OBJ_EVENT_GFX_BRENDAN_UNDERWATER         111
#define OBJ_EVENT_GFX_MAY_UNDERWATER             112
#define OBJ_EVENT_GFX_MOVING_BOX                 113
#define OBJ_EVENT_GFX_CABLE_CAR                  114
#define OBJ_EVENT_GFX_SCIENTIST_2                115
#define OBJ_EVENT_GFX_DEVON_EMPLOYEE             116
#define OBJ_EVENT_GFX_AQUA_MEMBER_M              117
#define OBJ_EVENT_GFX_AQUA_MEMBER_F              118
#define OBJ_EVENT_GFX_MAGMA_MEMBER_M             119
#define OBJ_EVENT_GFX_MAGMA_MEMBER_F             120
#define OBJ_EVENT_GFX_SIDNEY                     121
#define OBJ_EVENT_GFX_PHOEBE                     122
#define OBJ_EVENT_GFX_GLACIA                     123
#define OBJ_EVENT_GFX_DRAKE                      124
#define OBJ_EVENT_GFX_ROXANNE                    125
#define OBJ_EVENT_GFX_BRAWLY                     126
#define OBJ_EVENT_GFX_WATTSON                    127
#define OBJ_EVENT_GFX_FLANNERY                   128
#define OBJ_EVENT_GFX_NORMAN                     129
#define OBJ_EVENT_GFX_WINONA                     130
#define OBJ_EVENT_GFX_LIZA                       131
#define OBJ_EVENT_GFX_TATE                       132
#define OBJ_EVENT_GFX_WALLACE                    133
#define OBJ_EVENT_GFX_STEVEN                     134
#define OBJ_EVENT_GFX_WALLY                      135
#define OBJ_EVENT_GFX_LITTLE_BOY_3               136
#define OBJ_EVENT_GFX_BRENDAN_FISHING            137
#define OBJ_EVENT_GFX_MAY_FISHING                138
#define OBJ_EVENT_GFX_HOT_SPRINGS_OLD_WOMAN      139
#define OBJ_EVENT_GFX_SS_TIDAL                   140
#define OBJ_EVENT_GFX_SUBMARINE_SHADOW           141
#define OBJ_EVENT_GFX_PICHU_DOLL                 142
#define OBJ_EVENT_GFX_PIKACHU_DOLL               143
#define OBJ_EVENT_GFX_MARILL_DOLL                144
#define OBJ_EVENT_GFX_TOGEPI_DOLL                145
#define OBJ_EVENT_GFX_CYNDAQUIL_DOLL             146
#define OBJ_EVENT_GFX_CHIKORITA_DOLL             147
#define OBJ_EVENT_GFX_TOTODILE_DOLL              148
#define OBJ_EVENT_GFX_JIGGLYPUFF_DOLL            149
#define OBJ_EVENT_GFX_MEOWTH_DOLL                150
#define OBJ_EVENT_GFX_CLEFAIRY_DOLL              151
#define OBJ_EVENT_GFX_DITTO_DOLL                 152
#define OBJ_EVENT_GFX_SMOOCHUM_DOLL              153
#define OBJ_EVENT_GFX_TREECKO_DOLL               154
#define OBJ_EVENT_GFX_TORCHIC_DOLL               155
#define OBJ_EVENT_GFX_MUDKIP_DOLL                156
#define OBJ_EVENT_GFX_DUSKULL_DOLL               157
#define OBJ_EVENT_GFX_WYNAUT_DOLL                158
#define OBJ_EVENT_GFX_BALTOY_DOLL                159
#define OBJ_EVENT_GFX_KECLEON_DOLL               160
#define OBJ_EVENT_GFX_AZURILL_DOLL               161
#define OBJ_EVENT_GFX_SKITTY_DOLL                162
#define OBJ_EVENT_GFX_SWABLU_DOLL                163
#define OBJ_EVENT_GFX_GULPIN_DOLL                164
#define OBJ_EVENT_GFX_LOTAD_DOLL                 165
#define OBJ_EVENT_GFX_SEEDOT_DOLL                166
#define OBJ_EVENT_GFX_PIKA_CUSHION               167
#define OBJ_EVENT_GFX_ROUND_CUSHION              168
#define OBJ_EVENT_GFX_KISS_CUSHION               169
#define OBJ_EVENT_GFX_ZIGZAG_CUSHION             170
#define OBJ_EVENT_GFX_SPIN_CUSHION               171
#define OBJ_EVENT_GFX_DIAMOND_CUSHION            172
#define OBJ_EVENT_GFX_BALL_CUSHION               173
#define OBJ_EVENT_GFX_GRASS_CUSHION              174
#define OBJ_EVENT_GFX_FIRE_CUSHION               175
#define OBJ_EVENT_GFX_WATER_CUSHION              176
#define OBJ_EVENT_GFX_BIG_SNORLAX_DOLL           177
#define OBJ_EVENT_GFX_BIG_RHYDON_DOLL            178
#define OBJ_EVENT_GFX_BIG_LAPRAS_DOLL            179
#define OBJ_EVENT_GFX_BIG_VENUSAUR_DOLL          180
#define OBJ_EVENT_GFX_BIG_CHARIZARD_DOLL         181
#define OBJ_EVENT_GFX_BIG_BLASTOISE_DOLL         182
#define OBJ_EVENT_GFX_BIG_WAILMER_DOLL           183
#define OBJ_EVENT_GFX_BIG_REGIROCK_DOLL          184
#define OBJ_EVENT_GFX_BIG_REGICE_DOLL            185
#define OBJ_EVENT_GFX_BIG_REGISTEEL_DOLL         186
#define OBJ_EVENT_GFX_LATIAS                     187
#define OBJ_EVENT_GFX_LATIOS                     188
#define OBJ_EVENT_GFX_GAMEBOY_KID                189
#define OBJ_EVENT_GFX_CONTEST_JUDGE              190
#define OBJ_EVENT_GFX_BRENDAN_WATERING           191
#define OBJ_EVENT_GFX_MAY_WATERING               192
#define OBJ_EVENT_GFX_BRENDAN_DECORATING         193
#define OBJ_EVENT_GFX_MAY_DECORATING             194
#define OBJ_EVENT_GFX_ARCHIE                     195
#define OBJ_EVENT_GFX_MAXIE                      196
#define OBJ_EVENT_GFX_KYOGRE_FRONT               197
#define OBJ_EVENT_GFX_GROUDON_FRONT              198
#define OBJ_EVENT_GFX_FOSSIL                     199
#define OBJ_EVENT_GFX_REGIROCK                   200
#define OBJ_EVENT_GFX_REGICE                     201
#define OBJ_EVENT_GFX_REGISTEEL                  202
#define OBJ_EVENT_GFX_SKITTY                     203
#define OBJ_EVENT_GFX_KECLEON                    204
#define OBJ_EVENT_GFX_KYOGRE_ASLEEP              205
#define OBJ_EVENT_GFX_GROUDON_ASLEEP             206
#define OBJ_EVENT_GFX_RAYQUAZA                   207
#define OBJ_EVENT_GFX_ZIGZAGOON_2                208
#define OBJ_EVENT_GFX_PIKACHU                    209
#define OBJ_EVENT_GFX_AZUMARILL                  210
#define OBJ_EVENT_GFX_WINGULL                    211
#define OBJ_EVENT_GFX_KECLEON_BRIDGE_SHADOW      212
#define OBJ_EVENT_GFX_TUBER_M_SWIMMING           213
#define OBJ_EVENT_GFX_AZURILL                    214
#define OBJ_EVENT_GFX_MOM                        215
#define OBJ_EVENT_GFX_LINK_BRENDAN               216
#define OBJ_EVENT_GFX_LINK_MAY                   217
#define OBJ_EVENT_GFX_JUAN                       218
#define OBJ_EVENT_GFX_SCOTT                      219
#define OBJ_EVENT_GFX_POOCHYENA                  220
#define OBJ_EVENT_GFX_KYOGRE_SIDE                221
#define OBJ_EVENT_GFX_GROUDON_SIDE               222
#define OBJ_EVENT_GFX_MYSTERY_GIFT_MAN           223
#define OBJ_EVENT_GFX_TRICK_HOUSE_STATUE         224
#define OBJ_EVENT_GFX_KIRLIA                     225
#define OBJ_EVENT_GFX_DUSCLOPS                   226
#define OBJ_EVENT_GFX_UNION_ROOM_NURSE           227
#define OBJ_EVENT_GFX_SUDOWOODO                  228
#define OBJ_EVENT_GFX_MEW                        229
#define OBJ_EVENT_GFX_RED                        230
#define OBJ_EVENT_GFX_LEAF                       231
#define OBJ_EVENT_GFX_DEOXYS                     232
#define OBJ_EVENT_GFX_DEOXYS_TRIANGLE            233
#define OBJ_EVENT_GFX_BRANDON                    234
#define OBJ_EVENT_GFX_LINK_RS_BRENDAN            235
#define OBJ_EVENT_GFX_LINK_RS_MAY                236
#define OBJ_EVENT_GFX_LUGIA                      237
#define OBJ_EVENT_GFX_HOOH                       238
#define OBJ_EVENT_GFX_ITEM_BALL_GREEN            239
#define OBJ_EVENT_GFX_ITEM_BALL_PURPLE           240

#define NUM_REGULAR_OBJ_EVENT_GFX                241

#define OBJ_EVENT_GFX_POKEMON_001		(NUM_REGULAR_OBJ_EVENT_GFX + 0)
#define OBJ_EVENT_GFX_POKEMON_002		(NUM_REGULAR_OBJ_EVENT_GFX + 1)
#define OBJ_EVENT_GFX_POKEMON_003		(NUM_REGULAR_OBJ_EVENT_GFX + 2)
#define OBJ_EVENT_GFX_POKEMON_004		(NUM_REGULAR_OBJ_EVENT_GFX + 3)
#define OBJ_EVENT_GFX_POKEMON_005		(NUM_REGULAR_OBJ_EVENT_GFX + 4)
#define OBJ_EVENT_GFX_POKEMON_006		(NUM_REGULAR_OBJ_EVENT_GFX + 5)
#define OBJ_EVENT_GFX_POKEMON_007		(NUM_REGULAR_OBJ_EVENT_GFX + 6)
#define OBJ_EVENT_GFX_POKEMON_008		(NUM_REGULAR_OBJ_EVENT_GFX + 7)
#define OBJ_EVENT_GFX_POKEMON_009		(NUM_REGULAR_OBJ_EVENT_GFX + 8)
#define OBJ_EVENT_GFX_POKEMON_010		(NUM_REGULAR_OBJ_EVENT_GFX + 9)
#define OBJ_EVENT_GFX_POKEMON_011		(NUM_REGULAR_OBJ_EVENT_GFX + 10)
#define OBJ_EVENT_GFX_POKEMON_012		(NUM_REGULAR_OBJ_EVENT_GFX + 11)
#define OBJ_EVENT_GFX_POKEMON_013		(NUM_REGULAR_OBJ_EVENT_GFX + 12)
#define OBJ_EVENT_GFX_POKEMON_014		(NUM_REGULAR_OBJ_EVENT_GFX + 13)
#define OBJ_EVENT_GFX_POKEMON_015		(NUM_REGULAR_OBJ_EVENT_GFX + 14)
#define OBJ_EVENT_GFX_POKEMON_016		(NUM_REGULAR_OBJ_EVENT_GFX + 15)
#define OBJ_EVENT_GFX_POKEMON_017		(NUM_REGULAR_OBJ_EVENT_GFX + 16)
#define OBJ_EVENT_GFX_POKEMON_018		(NUM_REGULAR_OBJ_EVENT_GFX + 17)
#define OBJ_EVENT_GFX_POKEMON_019		(NUM_REGULAR_OBJ_EVENT_GFX + 18)
#define OBJ_EVENT_GFX_POKEMON_020		(NUM_REGULAR_OBJ_EVENT_GFX + 19)
#define OBJ_EVENT_GFX_POKEMON_021		(NUM_REGULAR_OBJ_EVENT_GFX + 20)
#define OBJ_EVENT_GFX_POKEMON_022		(NUM_REGULAR_OBJ_EVENT_GFX + 21)
#define OBJ_EVENT_GFX_POKEMON_023		(NUM_REGULAR_OBJ_EVENT_GFX + 22)
#define OBJ_EVENT_GFX_POKEMON_024		(NUM_REGULAR_OBJ_EVENT_GFX + 23)
#define OBJ_EVENT_GFX_POKEMON_025		(NUM_REGULAR_OBJ_EVENT_GFX + 24)
#define OBJ_EVENT_GFX_POKEMON_026		(NUM_REGULAR_OBJ_EVENT_GFX + 25)
#define OBJ_EVENT_GFX_POKEMON_027		(NUM_REGULAR_OBJ_EVENT_GFX + 26)
#define OBJ_EVENT_GFX_POKEMON_028		(NUM_REGULAR_OBJ_EVENT_GFX + 27)
#define OBJ_EVENT_GFX_POKEMON_029		(NUM_REGULAR_OBJ_EVENT_GFX + 28)
#define OBJ_EVENT_GFX_POKEMON_030		(NUM_REGULAR_OBJ_EVENT_GFX + 29)
#define OBJ_EVENT_GFX_POKEMON_031		(NUM_REGULAR_OBJ_EVENT_GFX + 30)
#define OBJ_EVENT_GFX_POKEMON_032		(NUM_REGULAR_OBJ_EVENT_GFX + 31)
#define OBJ_EVENT_GFX_POKEMON_033		(NUM_REGULAR_OBJ_EVENT_GFX + 32)
#define OBJ_EVENT_GFX_POKEMON_034		(NUM_REGULAR_OBJ_EVENT_GFX + 33)
#define OBJ_EVENT_GFX_POKEMON_035		(NUM_REGULAR_OBJ_EVENT_GFX + 34)
#define OBJ_EVENT_GFX_POKEMON_036		(NUM_REGULAR_OBJ_EVENT_GFX + 35)
#define OBJ_EVENT_GFX_POKEMON_037		(NUM_REGULAR_OBJ_EVENT_GFX + 36)
#define OBJ_EVENT_GFX_POKEMON_038		(NUM_REGULAR_OBJ_EVENT_GFX + 37)
#define OBJ_EVENT_GFX_POKEMON_039		(NUM_REGULAR_OBJ_EVENT_GFX + 38)
#define OBJ_EVENT_GFX_POKEMON_040		(NUM_REGULAR_OBJ_EVENT_GFX + 39)
#define OBJ_EVENT_GFX_POKEMON_041		(NUM_REGULAR_OBJ_EVENT_GFX + 40)
#define OBJ_EVENT_GFX_POKEMON_042		(NUM_REGULAR_OBJ_EVENT_GFX + 41)
#define OBJ_EVENT_GFX_POKEMON_043		(NUM_REGULAR_OBJ_EVENT_GFX + 42)
#define OBJ_EVENT_GFX_POKEMON_044		(NUM_REGULAR_OBJ_EVENT_GFX + 43)
#define OBJ_EVENT_GFX_POKEMON_045		(NUM_REGULAR_OBJ_EVENT_GFX + 44)
#define OBJ_EVENT_GFX_POKEMON_046		(NUM_REGULAR_OBJ_EVENT_GFX + 45)
#define OBJ_EVENT_GFX_POKEMON_047		(NUM_REGULAR_OBJ_EVENT_GFX + 46)
#define OBJ_EVENT_GFX_POKEMON_048		(NUM_REGULAR_OBJ_EVENT_GFX + 47)
#define OBJ_EVENT_GFX_POKEMON_049		(NUM_REGULAR_OBJ_EVENT_GFX + 48)
#define OBJ_EVENT_GFX_POKEMON_050		(NUM_REGULAR_OBJ_EVENT_GFX + 49)
#define OBJ_EVENT_GFX_POKEMON_051		(NUM_REGULAR_OBJ_EVENT_GFX + 50)
#define OBJ_EVENT_GFX_POKEMON_052		(NUM_REGULAR_OBJ_EVENT_GFX + 51)
#define OBJ_EVENT_GFX_POKEMON_053		(NUM_REGULAR_OBJ_EVENT_GFX + 52)
#define OBJ_EVENT_GFX_POKEMON_054		(NUM_REGULAR_OBJ_EVENT_GFX + 53)
#define OBJ_EVENT_GFX_POKEMON_055		(NUM_REGULAR_OBJ_EVENT_GFX + 54)
#define OBJ_EVENT_GFX_POKEMON_056		(NUM_REGULAR_OBJ_EVENT_GFX + 55)
#define OBJ_EVENT_GFX_POKEMON_057		(NUM_REGULAR_OBJ_EVENT_GFX + 56)
#define OBJ_EVENT_GFX_POKEMON_058		(NUM_REGULAR_OBJ_EVENT_GFX + 57)
#define OBJ_EVENT_GFX_POKEMON_059		(NUM_REGULAR_OBJ_EVENT_GFX + 58)
#define OBJ_EVENT_GFX_POKEMON_060		(NUM_REGULAR_OBJ_EVENT_GFX + 59)
#define OBJ_EVENT_GFX_POKEMON_061		(NUM_REGULAR_OBJ_EVENT_GFX + 60)
#define OBJ_EVENT_GFX_POKEMON_062		(NUM_REGULAR_OBJ_EVENT_GFX + 61)
#define OBJ_EVENT_GFX_POKEMON_063		(NUM_REGULAR_OBJ_EVENT_GFX + 62)
#define OBJ_EVENT_GFX_POKEMON_064		(NUM_REGULAR_OBJ_EVENT_GFX + 63)
#define OBJ_EVENT_GFX_POKEMON_065		(NUM_REGULAR_OBJ_EVENT_GFX + 64)
#define OBJ_EVENT_GFX_POKEMON_066		(NUM_REGULAR_OBJ_EVENT_GFX + 65)
#define OBJ_EVENT_GFX_POKEMON_067		(NUM_REGULAR_OBJ_EVENT_GFX + 66)
#define OBJ_EVENT_GFX_POKEMON_068		(NUM_REGULAR_OBJ_EVENT_GFX + 67)
#define OBJ_EVENT_GFX_POKEMON_069		(NUM_REGULAR_OBJ_EVENT_GFX + 68)
#define OBJ_EVENT_GFX_POKEMON_070		(NUM_REGULAR_OBJ_EVENT_GFX + 69)
#define OBJ_EVENT_GFX_POKEMON_071		(NUM_REGULAR_OBJ_EVENT_GFX + 70)
#define OBJ_EVENT_GFX_POKEMON_072		(NUM_REGULAR_OBJ_EVENT_GFX + 71)
#define OBJ_EVENT_GFX_POKEMON_073		(NUM_REGULAR_OBJ_EVENT_GFX + 72)
#define OBJ_EVENT_GFX_POKEMON_074		(NUM_REGULAR_OBJ_EVENT_GFX + 73)
#define OBJ_EVENT_GFX_POKEMON_075		(NUM_REGULAR_OBJ_EVENT_GFX + 74)
#define OBJ_EVENT_GFX_POKEMON_076		(NUM_REGULAR_OBJ_EVENT_GFX + 75)
#define OBJ_EVENT_GFX_POKEMON_077		(NUM_REGULAR_OBJ_EVENT_GFX + 76)
#define OBJ_EVENT_GFX_POKEMON_078		(NUM_REGULAR_OBJ_EVENT_GFX + 77)
#define OBJ_EVENT_GFX_POKEMON_079		(NUM_REGULAR_OBJ_EVENT_GFX + 78)
#define OBJ_EVENT_GFX_POKEMON_080		(NUM_REGULAR_OBJ_EVENT_GFX + 79)
#define OBJ_EVENT_GFX_POKEMON_081		(NUM_REGULAR_OBJ_EVENT_GFX + 80)
#define OBJ_EVENT_GFX_POKEMON_082		(NUM_REGULAR_OBJ_EVENT_GFX + 81)
#define OBJ_EVENT_GFX_POKEMON_083		(NUM_REGULAR_OBJ_EVENT_GFX + 82)
#define OBJ_EVENT_GFX_POKEMON_084		(NUM_REGULAR_OBJ_EVENT_GFX + 83)
#define OBJ_EVENT_GFX_POKEMON_085		(NUM_REGULAR_OBJ_EVENT_GFX + 84)
#define OBJ_EVENT_GFX_POKEMON_086		(NUM_REGULAR_OBJ_EVENT_GFX + 85)
#define OBJ_EVENT_GFX_POKEMON_087		(NUM_REGULAR_OBJ_EVENT_GFX + 86)
#define OBJ_EVENT_GFX_POKEMON_088		(NUM_REGULAR_OBJ_EVENT_GFX + 87)
#define OBJ_EVENT_GFX_POKEMON_089		(NUM_REGULAR_OBJ_EVENT_GFX + 88)
#define OBJ_EVENT_GFX_POKEMON_090		(NUM_REGULAR_OBJ_EVENT_GFX + 89)
#define OBJ_EVENT_GFX_POKEMON_091		(NUM_REGULAR_OBJ_EVENT_GFX + 90)
#define OBJ_EVENT_GFX_POKEMON_092		(NUM_REGULAR_OBJ_EVENT_GFX + 91)
#define OBJ_EVENT_GFX_POKEMON_093		(NUM_REGULAR_OBJ_EVENT_GFX + 92)
#define OBJ_EVENT_GFX_POKEMON_094		(NUM_REGULAR_OBJ_EVENT_GFX + 93)
#define OBJ_EVENT_GFX_POKEMON_095		(NUM_REGULAR_OBJ_EVENT_GFX + 94)
#define OBJ_EVENT_GFX_POKEMON_096		(NUM_REGULAR_OBJ_EVENT_GFX + 95)
#define OBJ_EVENT_GFX_POKEMON_097		(NUM_REGULAR_OBJ_EVENT_GFX + 96)
#define OBJ_EVENT_GFX_POKEMON_098		(NUM_REGULAR_OBJ_EVENT_GFX + 97)
#define OBJ_EVENT_GFX_POKEMON_099		(NUM_REGULAR_OBJ_EVENT_GFX + 98)
#define OBJ_EVENT_GFX_POKEMON_100		(NUM_REGULAR_OBJ_EVENT_GFX + 99)
#define OBJ_EVENT_GFX_POKEMON_101		(NUM_REGULAR_OBJ_EVENT_GFX + 100)
#define OBJ_EVENT_GFX_POKEMON_102		(NUM_REGULAR_OBJ_EVENT_GFX + 101)
#define OBJ_EVENT_GFX_POKEMON_103		(NUM_REGULAR_OBJ_EVENT_GFX + 102)
#define OBJ_EVENT_GFX_POKEMON_104		(NUM_REGULAR_OBJ_EVENT_GFX + 103)
#define OBJ_EVENT_GFX_POKEMON_105		(NUM_REGULAR_OBJ_EVENT_GFX + 104)
#define OBJ_EVENT_GFX_POKEMON_106		(NUM_REGULAR_OBJ_EVENT_GFX + 105)
#define OBJ_EVENT_GFX_POKEMON_107		(NUM_REGULAR_OBJ_EVENT_GFX + 106)
#define OBJ_EVENT_GFX_POKEMON_108		(NUM_REGULAR_OBJ_EVENT_GFX + 107)
#define OBJ_EVENT_GFX_POKEMON_109		(NUM_REGULAR_OBJ_EVENT_GFX + 108)
#define OBJ_EVENT_GFX_POKEMON_110		(NUM_REGULAR_OBJ_EVENT_GFX + 109)
#define OBJ_EVENT_GFX_POKEMON_111		(NUM_REGULAR_OBJ_EVENT_GFX + 110)
#define OBJ_EVENT_GFX_POKEMON_112		(NUM_REGULAR_OBJ_EVENT_GFX + 111)
#define OBJ_EVENT_GFX_POKEMON_113		(NUM_REGULAR_OBJ_EVENT_GFX + 112)
#define OBJ_EVENT_GFX_POKEMON_114		(NUM_REGULAR_OBJ_EVENT_GFX + 113)
#define OBJ_EVENT_GFX_POKEMON_115		(NUM_REGULAR_OBJ_EVENT_GFX + 114)
#define OBJ_EVENT_GFX_POKEMON_116		(NUM_REGULAR_OBJ_EVENT_GFX + 115)
#define OBJ_EVENT_GFX_POKEMON_117		(NUM_REGULAR_OBJ_EVENT_GFX + 116)
#define OBJ_EVENT_GFX_POKEMON_118		(NUM_REGULAR_OBJ_EVENT_GFX + 117)
#define OBJ_EVENT_GFX_POKEMON_119		(NUM_REGULAR_OBJ_EVENT_GFX + 118)
#define OBJ_EVENT_GFX_POKEMON_120		(NUM_REGULAR_OBJ_EVENT_GFX + 119)
#define OBJ_EVENT_GFX_POKEMON_121		(NUM_REGULAR_OBJ_EVENT_GFX + 120)
#define OBJ_EVENT_GFX_POKEMON_122		(NUM_REGULAR_OBJ_EVENT_GFX + 121)
#define OBJ_EVENT_GFX_POKEMON_123		(NUM_REGULAR_OBJ_EVENT_GFX + 122)
#define OBJ_EVENT_GFX_POKEMON_124		(NUM_REGULAR_OBJ_EVENT_GFX + 123)
#define OBJ_EVENT_GFX_POKEMON_125		(NUM_REGULAR_OBJ_EVENT_GFX + 124)
#define OBJ_EVENT_GFX_POKEMON_126		(NUM_REGULAR_OBJ_EVENT_GFX + 125)
#define OBJ_EVENT_GFX_POKEMON_127		(NUM_REGULAR_OBJ_EVENT_GFX + 126)
#define OBJ_EVENT_GFX_POKEMON_128		(NUM_REGULAR_OBJ_EVENT_GFX + 127)
#define OBJ_EVENT_GFX_POKEMON_129		(NUM_REGULAR_OBJ_EVENT_GFX + 128)
#define OBJ_EVENT_GFX_POKEMON_130		(NUM_REGULAR_OBJ_EVENT_GFX + 129)
#define OBJ_EVENT_GFX_POKEMON_131		(NUM_REGULAR_OBJ_EVENT_GFX + 130)
#define OBJ_EVENT_GFX_POKEMON_132		(NUM_REGULAR_OBJ_EVENT_GFX + 131)
#define OBJ_EVENT_GFX_POKEMON_133		(NUM_REGULAR_OBJ_EVENT_GFX + 132)
#define OBJ_EVENT_GFX_POKEMON_134		(NUM_REGULAR_OBJ_EVENT_GFX + 133)
#define OBJ_EVENT_GFX_POKEMON_135		(NUM_REGULAR_OBJ_EVENT_GFX + 134)
#define OBJ_EVENT_GFX_POKEMON_136		(NUM_REGULAR_OBJ_EVENT_GFX + 135)
#define OBJ_EVENT_GFX_POKEMON_137		(NUM_REGULAR_OBJ_EVENT_GFX + 136)
#define OBJ_EVENT_GFX_POKEMON_138		(NUM_REGULAR_OBJ_EVENT_GFX + 137)
#define OBJ_EVENT_GFX_POKEMON_139		(NUM_REGULAR_OBJ_EVENT_GFX + 138)
#define OBJ_EVENT_GFX_POKEMON_140		(NUM_REGULAR_OBJ_EVENT_GFX + 139)
#define OBJ_EVENT_GFX_POKEMON_141		(NUM_REGULAR_OBJ_EVENT_GFX + 140)
#define OBJ_EVENT_GFX_POKEMON_142		(NUM_REGULAR_OBJ_EVENT_GFX + 141)
#define OBJ_EVENT_GFX_POKEMON_143		(NUM_REGULAR_OBJ_EVENT_GFX + 142)
#define OBJ_EVENT_GFX_POKEMON_144		(NUM_REGULAR_OBJ_EVENT_GFX + 143)
#define OBJ_EVENT_GFX_POKEMON_145		(NUM_REGULAR_OBJ_EVENT_GFX + 144)
#define OBJ_EVENT_GFX_POKEMON_146		(NUM_REGULAR_OBJ_EVENT_GFX + 145)
#define OBJ_EVENT_GFX_POKEMON_147		(NUM_REGULAR_OBJ_EVENT_GFX + 146)
#define OBJ_EVENT_GFX_POKEMON_148		(NUM_REGULAR_OBJ_EVENT_GFX + 147)
#define OBJ_EVENT_GFX_POKEMON_149		(NUM_REGULAR_OBJ_EVENT_GFX + 148)
#define OBJ_EVENT_GFX_POKEMON_150		(NUM_REGULAR_OBJ_EVENT_GFX + 149)
#define OBJ_EVENT_GFX_POKEMON_151		(NUM_REGULAR_OBJ_EVENT_GFX + 150)
#define OBJ_EVENT_GFX_POKEMON_152		(NUM_REGULAR_OBJ_EVENT_GFX + 151)
#define OBJ_EVENT_GFX_POKEMON_153		(NUM_REGULAR_OBJ_EVENT_GFX + 152)
#define OBJ_EVENT_GFX_POKEMON_154		(NUM_REGULAR_OBJ_EVENT_GFX + 153)
#define OBJ_EVENT_GFX_POKEMON_155		(NUM_REGULAR_OBJ_EVENT_GFX + 154)
#define OBJ_EVENT_GFX_POKEMON_156		(NUM_REGULAR_OBJ_EVENT_GFX + 155)
#define OBJ_EVENT_GFX_POKEMON_157		(NUM_REGULAR_OBJ_EVENT_GFX + 156)
#define OBJ_EVENT_GFX_POKEMON_158		(NUM_REGULAR_OBJ_EVENT_GFX + 157)
#define OBJ_EVENT_GFX_POKEMON_159		(NUM_REGULAR_OBJ_EVENT_GFX + 158)
#define OBJ_EVENT_GFX_POKEMON_160		(NUM_REGULAR_OBJ_EVENT_GFX + 159)
#define OBJ_EVENT_GFX_POKEMON_161		(NUM_REGULAR_OBJ_EVENT_GFX + 160)
#define OBJ_EVENT_GFX_POKEMON_162		(NUM_REGULAR_OBJ_EVENT_GFX + 161)
#define OBJ_EVENT_GFX_POKEMON_163		(NUM_REGULAR_OBJ_EVENT_GFX + 162)
#define OBJ_EVENT_GFX_POKEMON_164		(NUM_REGULAR_OBJ_EVENT_GFX + 163)
#define OBJ_EVENT_GFX_POKEMON_165		(NUM_REGULAR_OBJ_EVENT_GFX + 164)
#define OBJ_EVENT_GFX_POKEMON_166		(NUM_REGULAR_OBJ_EVENT_GFX + 165)
#define OBJ_EVENT_GFX_POKEMON_167		(NUM_REGULAR_OBJ_EVENT_GFX + 166)
#define OBJ_EVENT_GFX_POKEMON_168		(NUM_REGULAR_OBJ_EVENT_GFX + 167)
#define OBJ_EVENT_GFX_POKEMON_169		(NUM_REGULAR_OBJ_EVENT_GFX + 168)
#define OBJ_EVENT_GFX_POKEMON_170		(NUM_REGULAR_OBJ_EVENT_GFX + 169)
#define OBJ_EVENT_GFX_POKEMON_171		(NUM_REGULAR_OBJ_EVENT_GFX + 170)
#define OBJ_EVENT_GFX_POKEMON_172		(NUM_REGULAR_OBJ_EVENT_GFX + 171)
#define OBJ_EVENT_GFX_POKEMON_173		(NUM_REGULAR_OBJ_EVENT_GFX + 172)
#define OBJ_EVENT_GFX_POKEMON_174		(NUM_REGULAR_OBJ_EVENT_GFX + 173)
#define OBJ_EVENT_GFX_POKEMON_175		(NUM_REGULAR_OBJ_EVENT_GFX + 174)
#define OBJ_EVENT_GFX_POKEMON_176		(NUM_REGULAR_OBJ_EVENT_GFX + 175)
#define OBJ_EVENT_GFX_POKEMON_177		(NUM_REGULAR_OBJ_EVENT_GFX + 176)
#define OBJ_EVENT_GFX_POKEMON_178		(NUM_REGULAR_OBJ_EVENT_GFX + 177)
#define OBJ_EVENT_GFX_POKEMON_179		(NUM_REGULAR_OBJ_EVENT_GFX + 178)
#define OBJ_EVENT_GFX_POKEMON_180		(NUM_REGULAR_OBJ_EVENT_GFX + 179)
#define OBJ_EVENT_GFX_POKEMON_181		(NUM_REGULAR_OBJ_EVENT_GFX + 180)
#define OBJ_EVENT_GFX_POKEMON_182		(NUM_REGULAR_OBJ_EVENT_GFX + 181)
#define OBJ_EVENT_GFX_POKEMON_183		(NUM_REGULAR_OBJ_EVENT_GFX + 182)
#define OBJ_EVENT_GFX_POKEMON_184		(NUM_REGULAR_OBJ_EVENT_GFX + 183)
#define OBJ_EVENT_GFX_POKEMON_185		(NUM_REGULAR_OBJ_EVENT_GFX + 184)
#define OBJ_EVENT_GFX_POKEMON_186		(NUM_REGULAR_OBJ_EVENT_GFX + 185)
#define OBJ_EVENT_GFX_POKEMON_187		(NUM_REGULAR_OBJ_EVENT_GFX + 186)
#define OBJ_EVENT_GFX_POKEMON_188		(NUM_REGULAR_OBJ_EVENT_GFX + 187)
#define OBJ_EVENT_GFX_POKEMON_189		(NUM_REGULAR_OBJ_EVENT_GFX + 188)
#define OBJ_EVENT_GFX_POKEMON_190		(NUM_REGULAR_OBJ_EVENT_GFX + 189)
#define OBJ_EVENT_GFX_POKEMON_191		(NUM_REGULAR_OBJ_EVENT_GFX + 190)
#define OBJ_EVENT_GFX_POKEMON_192		(NUM_REGULAR_OBJ_EVENT_GFX + 191)
#define OBJ_EVENT_GFX_POKEMON_193		(NUM_REGULAR_OBJ_EVENT_GFX + 192)
#define OBJ_EVENT_GFX_POKEMON_194		(NUM_REGULAR_OBJ_EVENT_GFX + 193)
#define OBJ_EVENT_GFX_POKEMON_195		(NUM_REGULAR_OBJ_EVENT_GFX + 194)
#define OBJ_EVENT_GFX_POKEMON_196		(NUM_REGULAR_OBJ_EVENT_GFX + 195)
#define OBJ_EVENT_GFX_POKEMON_197		(NUM_REGULAR_OBJ_EVENT_GFX + 196)
#define OBJ_EVENT_GFX_POKEMON_198		(NUM_REGULAR_OBJ_EVENT_GFX + 197)
#define OBJ_EVENT_GFX_POKEMON_199		(NUM_REGULAR_OBJ_EVENT_GFX + 198)
#define OBJ_EVENT_GFX_POKEMON_200		(NUM_REGULAR_OBJ_EVENT_GFX + 199)
#define OBJ_EVENT_GFX_POKEMON_201		(NUM_REGULAR_OBJ_EVENT_GFX + 200)
#define OBJ_EVENT_GFX_POKEMON_202		(NUM_REGULAR_OBJ_EVENT_GFX + 201)
#define OBJ_EVENT_GFX_POKEMON_203		(NUM_REGULAR_OBJ_EVENT_GFX + 202)
#define OBJ_EVENT_GFX_POKEMON_204		(NUM_REGULAR_OBJ_EVENT_GFX + 203)
#define OBJ_EVENT_GFX_POKEMON_205		(NUM_REGULAR_OBJ_EVENT_GFX + 204)
#define OBJ_EVENT_GFX_POKEMON_206		(NUM_REGULAR_OBJ_EVENT_GFX + 205)
#define OBJ_EVENT_GFX_POKEMON_207		(NUM_REGULAR_OBJ_EVENT_GFX + 206)
#define OBJ_EVENT_GFX_POKEMON_208		(NUM_REGULAR_OBJ_EVENT_GFX + 207)
#define OBJ_EVENT_GFX_POKEMON_209		(NUM_REGULAR_OBJ_EVENT_GFX + 208)
#define OBJ_EVENT_GFX_POKEMON_210		(NUM_REGULAR_OBJ_EVENT_GFX + 209)
#define OBJ_EVENT_GFX_POKEMON_211		(NUM_REGULAR_OBJ_EVENT_GFX + 210)
#define OBJ_EVENT_GFX_POKEMON_212		(NUM_REGULAR_OBJ_EVENT_GFX + 211)
#define OBJ_EVENT_GFX_POKEMON_213		(NUM_REGULAR_OBJ_EVENT_GFX + 212)
#define OBJ_EVENT_GFX_POKEMON_214		(NUM_REGULAR_OBJ_EVENT_GFX + 213)
#define OBJ_EVENT_GFX_POKEMON_215		(NUM_REGULAR_OBJ_EVENT_GFX + 214)
#define OBJ_EVENT_GFX_POKEMON_216		(NUM_REGULAR_OBJ_EVENT_GFX + 215)
#define OBJ_EVENT_GFX_POKEMON_217		(NUM_REGULAR_OBJ_EVENT_GFX + 216)
#define OBJ_EVENT_GFX_POKEMON_218		(NUM_REGULAR_OBJ_EVENT_GFX + 217)
#define OBJ_EVENT_GFX_POKEMON_219		(NUM_REGULAR_OBJ_EVENT_GFX + 218)
#define OBJ_EVENT_GFX_POKEMON_220		(NUM_REGULAR_OBJ_EVENT_GFX + 219)
#define OBJ_EVENT_GFX_POKEMON_221		(NUM_REGULAR_OBJ_EVENT_GFX + 220)
#define OBJ_EVENT_GFX_POKEMON_222		(NUM_REGULAR_OBJ_EVENT_GFX + 221)
#define OBJ_EVENT_GFX_POKEMON_223		(NUM_REGULAR_OBJ_EVENT_GFX + 222)
#define OBJ_EVENT_GFX_POKEMON_224		(NUM_REGULAR_OBJ_EVENT_GFX + 223)
#define OBJ_EVENT_GFX_POKEMON_225		(NUM_REGULAR_OBJ_EVENT_GFX + 224)
#define OBJ_EVENT_GFX_POKEMON_226		(NUM_REGULAR_OBJ_EVENT_GFX + 225)
#define OBJ_EVENT_GFX_POKEMON_227		(NUM_REGULAR_OBJ_EVENT_GFX + 226)
#define OBJ_EVENT_GFX_POKEMON_228		(NUM_REGULAR_OBJ_EVENT_GFX + 227)
#define OBJ_EVENT_GFX_POKEMON_229		(NUM_REGULAR_OBJ_EVENT_GFX + 228)
#define OBJ_EVENT_GFX_POKEMON_230		(NUM_REGULAR_OBJ_EVENT_GFX + 229)
#define OBJ_EVENT_GFX_POKEMON_231		(NUM_REGULAR_OBJ_EVENT_GFX + 230)
#define OBJ_EVENT_GFX_POKEMON_232		(NUM_REGULAR_OBJ_EVENT_GFX + 231)
#define OBJ_EVENT_GFX_POKEMON_233		(NUM_REGULAR_OBJ_EVENT_GFX + 232)
#define OBJ_EVENT_GFX_POKEMON_234		(NUM_REGULAR_OBJ_EVENT_GFX + 233)
#define OBJ_EVENT_GFX_POKEMON_235		(NUM_REGULAR_OBJ_EVENT_GFX + 234)
#define OBJ_EVENT_GFX_POKEMON_236		(NUM_REGULAR_OBJ_EVENT_GFX + 235)
#define OBJ_EVENT_GFX_POKEMON_237		(NUM_REGULAR_OBJ_EVENT_GFX + 236)
#define OBJ_EVENT_GFX_POKEMON_238		(NUM_REGULAR_OBJ_EVENT_GFX + 237)
#define OBJ_EVENT_GFX_POKEMON_239		(NUM_REGULAR_OBJ_EVENT_GFX + 238)
#define OBJ_EVENT_GFX_POKEMON_240		(NUM_REGULAR_OBJ_EVENT_GFX + 239)
#define OBJ_EVENT_GFX_POKEMON_241		(NUM_REGULAR_OBJ_EVENT_GFX + 240)
#define OBJ_EVENT_GFX_POKEMON_242		(NUM_REGULAR_OBJ_EVENT_GFX + 241)
#define OBJ_EVENT_GFX_POKEMON_243		(NUM_REGULAR_OBJ_EVENT_GFX + 242)
#define OBJ_EVENT_GFX_POKEMON_244		(NUM_REGULAR_OBJ_EVENT_GFX + 243)
#define OBJ_EVENT_GFX_POKEMON_245		(NUM_REGULAR_OBJ_EVENT_GFX + 244)
#define OBJ_EVENT_GFX_POKEMON_246		(NUM_REGULAR_OBJ_EVENT_GFX + 245)
#define OBJ_EVENT_GFX_POKEMON_247		(NUM_REGULAR_OBJ_EVENT_GFX + 246)
#define OBJ_EVENT_GFX_POKEMON_248		(NUM_REGULAR_OBJ_EVENT_GFX + 247)
#define OBJ_EVENT_GFX_POKEMON_249		(NUM_REGULAR_OBJ_EVENT_GFX + 248)
#define OBJ_EVENT_GFX_POKEMON_250		(NUM_REGULAR_OBJ_EVENT_GFX + 249)
#define OBJ_EVENT_GFX_POKEMON_251		(NUM_REGULAR_OBJ_EVENT_GFX + 250)
#define OBJ_EVENT_GFX_POKEMON_252		(NUM_REGULAR_OBJ_EVENT_GFX + 251)
#define OBJ_EVENT_GFX_POKEMON_253		(NUM_REGULAR_OBJ_EVENT_GFX + 252)
#define OBJ_EVENT_GFX_POKEMON_254		(NUM_REGULAR_OBJ_EVENT_GFX + 253)
#define OBJ_EVENT_GFX_POKEMON_255		(NUM_REGULAR_OBJ_EVENT_GFX + 254)
#define OBJ_EVENT_GFX_POKEMON_256		(NUM_REGULAR_OBJ_EVENT_GFX + 255)
#define OBJ_EVENT_GFX_POKEMON_257		(NUM_REGULAR_OBJ_EVENT_GFX + 256)
#define OBJ_EVENT_GFX_POKEMON_258		(NUM_REGULAR_OBJ_EVENT_GFX + 257)
#define OBJ_EVENT_GFX_POKEMON_259		(NUM_REGULAR_OBJ_EVENT_GFX + 258)
#define OBJ_EVENT_GFX_POKEMON_260		(NUM_REGULAR_OBJ_EVENT_GFX + 259)
#define OBJ_EVENT_GFX_POKEMON_261		(NUM_REGULAR_OBJ_EVENT_GFX + 260)
#define OBJ_EVENT_GFX_POKEMON_262		(NUM_REGULAR_OBJ_EVENT_GFX + 261)
#define OBJ_EVENT_GFX_POKEMON_263		(NUM_REGULAR_OBJ_EVENT_GFX + 262)
#define OBJ_EVENT_GFX_POKEMON_264		(NUM_REGULAR_OBJ_EVENT_GFX + 263)
#define OBJ_EVENT_GFX_POKEMON_265		(NUM_REGULAR_OBJ_EVENT_GFX + 264)
#define OBJ_EVENT_GFX_POKEMON_266		(NUM_REGULAR_OBJ_EVENT_GFX + 265)
#define OBJ_EVENT_GFX_POKEMON_267		(NUM_REGULAR_OBJ_EVENT_GFX + 266)
#define OBJ_EVENT_GFX_POKEMON_268		(NUM_REGULAR_OBJ_EVENT_GFX + 267)
#define OBJ_EVENT_GFX_POKEMON_269		(NUM_REGULAR_OBJ_EVENT_GFX + 268)
#define OBJ_EVENT_GFX_POKEMON_270		(NUM_REGULAR_OBJ_EVENT_GFX + 269)
#define OBJ_EVENT_GFX_POKEMON_271		(NUM_REGULAR_OBJ_EVENT_GFX + 270)
#define OBJ_EVENT_GFX_POKEMON_272		(NUM_REGULAR_OBJ_EVENT_GFX + 271)
#define OBJ_EVENT_GFX_POKEMON_273		(NUM_REGULAR_OBJ_EVENT_GFX + 272)
#define OBJ_EVENT_GFX_POKEMON_274		(NUM_REGULAR_OBJ_EVENT_GFX + 273)
#define OBJ_EVENT_GFX_POKEMON_275		(NUM_REGULAR_OBJ_EVENT_GFX + 274)
#define OBJ_EVENT_GFX_POKEMON_276		(NUM_REGULAR_OBJ_EVENT_GFX + 275)
#define OBJ_EVENT_GFX_POKEMON_277		(NUM_REGULAR_OBJ_EVENT_GFX + 276)
#define OBJ_EVENT_GFX_POKEMON_278		(NUM_REGULAR_OBJ_EVENT_GFX + 277)
#define OBJ_EVENT_GFX_POKEMON_279		(NUM_REGULAR_OBJ_EVENT_GFX + 278)
#define OBJ_EVENT_GFX_POKEMON_280		(NUM_REGULAR_OBJ_EVENT_GFX + 279)
#define OBJ_EVENT_GFX_POKEMON_281		(NUM_REGULAR_OBJ_EVENT_GFX + 280)
#define OBJ_EVENT_GFX_POKEMON_282		(NUM_REGULAR_OBJ_EVENT_GFX + 281)
#define OBJ_EVENT_GFX_POKEMON_283		(NUM_REGULAR_OBJ_EVENT_GFX + 282)
#define OBJ_EVENT_GFX_POKEMON_284		(NUM_REGULAR_OBJ_EVENT_GFX + 283)
#define OBJ_EVENT_GFX_POKEMON_285		(NUM_REGULAR_OBJ_EVENT_GFX + 284)
#define OBJ_EVENT_GFX_POKEMON_286		(NUM_REGULAR_OBJ_EVENT_GFX + 285)
#define OBJ_EVENT_GFX_POKEMON_287		(NUM_REGULAR_OBJ_EVENT_GFX + 286)
#define OBJ_EVENT_GFX_POKEMON_288		(NUM_REGULAR_OBJ_EVENT_GFX + 287)
#define OBJ_EVENT_GFX_POKEMON_289		(NUM_REGULAR_OBJ_EVENT_GFX + 288)
#define OBJ_EVENT_GFX_POKEMON_290		(NUM_REGULAR_OBJ_EVENT_GFX + 289)
#define OBJ_EVENT_GFX_POKEMON_291		(NUM_REGULAR_OBJ_EVENT_GFX + 290)
#define OBJ_EVENT_GFX_POKEMON_292		(NUM_REGULAR_OBJ_EVENT_GFX + 291)
#define OBJ_EVENT_GFX_POKEMON_293		(NUM_REGULAR_OBJ_EVENT_GFX + 292)
#define OBJ_EVENT_GFX_POKEMON_294		(NUM_REGULAR_OBJ_EVENT_GFX + 293)
#define OBJ_EVENT_GFX_POKEMON_295		(NUM_REGULAR_OBJ_EVENT_GFX + 294)
#define OBJ_EVENT_GFX_POKEMON_296		(NUM_REGULAR_OBJ_EVENT_GFX + 295)
#define OBJ_EVENT_GFX_POKEMON_297		(NUM_REGULAR_OBJ_EVENT_GFX + 296)
#define OBJ_EVENT_GFX_POKEMON_298		(NUM_REGULAR_OBJ_EVENT_GFX + 297)
#define OBJ_EVENT_GFX_POKEMON_299		(NUM_REGULAR_OBJ_EVENT_GFX + 298)
#define OBJ_EVENT_GFX_POKEMON_300		(NUM_REGULAR_OBJ_EVENT_GFX + 299)
#define OBJ_EVENT_GFX_POKEMON_301		(NUM_REGULAR_OBJ_EVENT_GFX + 300)
#define OBJ_EVENT_GFX_POKEMON_302		(NUM_REGULAR_OBJ_EVENT_GFX + 301)
#define OBJ_EVENT_GFX_POKEMON_303		(NUM_REGULAR_OBJ_EVENT_GFX + 302)
#define OBJ_EVENT_GFX_POKEMON_304		(NUM_REGULAR_OBJ_EVENT_GFX + 303)
#define OBJ_EVENT_GFX_POKEMON_305		(NUM_REGULAR_OBJ_EVENT_GFX + 304)
#define OBJ_EVENT_GFX_POKEMON_306		(NUM_REGULAR_OBJ_EVENT_GFX + 305)
#define OBJ_EVENT_GFX_POKEMON_307		(NUM_REGULAR_OBJ_EVENT_GFX + 306)
#define OBJ_EVENT_GFX_POKEMON_308		(NUM_REGULAR_OBJ_EVENT_GFX + 307)
#define OBJ_EVENT_GFX_POKEMON_309		(NUM_REGULAR_OBJ_EVENT_GFX + 308)
#define OBJ_EVENT_GFX_POKEMON_310		(NUM_REGULAR_OBJ_EVENT_GFX + 309)
#define OBJ_EVENT_GFX_POKEMON_311		(NUM_REGULAR_OBJ_EVENT_GFX + 310)
#define OBJ_EVENT_GFX_POKEMON_312		(NUM_REGULAR_OBJ_EVENT_GFX + 311)
#define OBJ_EVENT_GFX_POKEMON_313		(NUM_REGULAR_OBJ_EVENT_GFX + 312)
#define OBJ_EVENT_GFX_POKEMON_314		(NUM_REGULAR_OBJ_EVENT_GFX + 313)
#define OBJ_EVENT_GFX_POKEMON_315		(NUM_REGULAR_OBJ_EVENT_GFX + 314)
#define OBJ_EVENT_GFX_POKEMON_316		(NUM_REGULAR_OBJ_EVENT_GFX + 315)
#define OBJ_EVENT_GFX_POKEMON_317		(NUM_REGULAR_OBJ_EVENT_GFX + 316)
#define OBJ_EVENT_GFX_POKEMON_318		(NUM_REGULAR_OBJ_EVENT_GFX + 317)
#define OBJ_EVENT_GFX_POKEMON_319		(NUM_REGULAR_OBJ_EVENT_GFX + 318)
#define OBJ_EVENT_GFX_POKEMON_320		(NUM_REGULAR_OBJ_EVENT_GFX + 319)
#define OBJ_EVENT_GFX_POKEMON_321		(NUM_REGULAR_OBJ_EVENT_GFX + 320)
#define OBJ_EVENT_GFX_POKEMON_322		(NUM_REGULAR_OBJ_EVENT_GFX + 321)
#define OBJ_EVENT_GFX_POKEMON_323		(NUM_REGULAR_OBJ_EVENT_GFX + 322)
#define OBJ_EVENT_GFX_POKEMON_324		(NUM_REGULAR_OBJ_EVENT_GFX + 323)
#define OBJ_EVENT_GFX_POKEMON_325		(NUM_REGULAR_OBJ_EVENT_GFX + 324)
#define OBJ_EVENT_GFX_POKEMON_326		(NUM_REGULAR_OBJ_EVENT_GFX + 325)
#define OBJ_EVENT_GFX_POKEMON_327		(NUM_REGULAR_OBJ_EVENT_GFX + 326)
#define OBJ_EVENT_GFX_POKEMON_328		(NUM_REGULAR_OBJ_EVENT_GFX + 327)
#define OBJ_EVENT_GFX_POKEMON_329		(NUM_REGULAR_OBJ_EVENT_GFX + 328)
#define OBJ_EVENT_GFX_POKEMON_330		(NUM_REGULAR_OBJ_EVENT_GFX + 329)
#define OBJ_EVENT_GFX_POKEMON_331		(NUM_REGULAR_OBJ_EVENT_GFX + 330)
#define OBJ_EVENT_GFX_POKEMON_332		(NUM_REGULAR_OBJ_EVENT_GFX + 331)
#define OBJ_EVENT_GFX_POKEMON_333		(NUM_REGULAR_OBJ_EVENT_GFX + 332)
#define OBJ_EVENT_GFX_POKEMON_334		(NUM_REGULAR_OBJ_EVENT_GFX + 333)
#define OBJ_EVENT_GFX_POKEMON_335		(NUM_REGULAR_OBJ_EVENT_GFX + 334)
#define OBJ_EVENT_GFX_POKEMON_336		(NUM_REGULAR_OBJ_EVENT_GFX + 335)
#define OBJ_EVENT_GFX_POKEMON_337		(NUM_REGULAR_OBJ_EVENT_GFX + 336)
#define OBJ_EVENT_GFX_POKEMON_338		(NUM_REGULAR_OBJ_EVENT_GFX + 337)
#define OBJ_EVENT_GFX_POKEMON_339		(NUM_REGULAR_OBJ_EVENT_GFX + 338)
#define OBJ_EVENT_GFX_POKEMON_340		(NUM_REGULAR_OBJ_EVENT_GFX + 339)
#define OBJ_EVENT_GFX_POKEMON_341		(NUM_REGULAR_OBJ_EVENT_GFX + 340)
#define OBJ_EVENT_GFX_POKEMON_342		(NUM_REGULAR_OBJ_EVENT_GFX + 341)
#define OBJ_EVENT_GFX_POKEMON_343		(NUM_REGULAR_OBJ_EVENT_GFX + 342)
#define OBJ_EVENT_GFX_POKEMON_344		(NUM_REGULAR_OBJ_EVENT_GFX + 343)
#define OBJ_EVENT_GFX_POKEMON_345		(NUM_REGULAR_OBJ_EVENT_GFX + 344)
#define OBJ_EVENT_GFX_POKEMON_346		(NUM_REGULAR_OBJ_EVENT_GFX + 345)
#define OBJ_EVENT_GFX_POKEMON_347		(NUM_REGULAR_OBJ_EVENT_GFX + 346)
#define OBJ_EVENT_GFX_POKEMON_348		(NUM_REGULAR_OBJ_EVENT_GFX + 347)
#define OBJ_EVENT_GFX_POKEMON_349		(NUM_REGULAR_OBJ_EVENT_GFX + 348)
#define OBJ_EVENT_GFX_POKEMON_350		(NUM_REGULAR_OBJ_EVENT_GFX + 349)
#define OBJ_EVENT_GFX_POKEMON_351		(NUM_REGULAR_OBJ_EVENT_GFX + 350)
#define OBJ_EVENT_GFX_POKEMON_352		(NUM_REGULAR_OBJ_EVENT_GFX + 351)
#define OBJ_EVENT_GFX_POKEMON_353		(NUM_REGULAR_OBJ_EVENT_GFX + 352)
#define OBJ_EVENT_GFX_POKEMON_354		(NUM_REGULAR_OBJ_EVENT_GFX + 353)
#define OBJ_EVENT_GFX_POKEMON_355		(NUM_REGULAR_OBJ_EVENT_GFX + 354)
#define OBJ_EVENT_GFX_POKEMON_356		(NUM_REGULAR_OBJ_EVENT_GFX + 355)
#define OBJ_EVENT_GFX_POKEMON_357		(NUM_REGULAR_OBJ_EVENT_GFX + 356)
#define OBJ_EVENT_GFX_POKEMON_358		(NUM_REGULAR_OBJ_EVENT_GFX + 357)
#define OBJ_EVENT_GFX_POKEMON_359		(NUM_REGULAR_OBJ_EVENT_GFX + 358)
#define OBJ_EVENT_GFX_POKEMON_360		(NUM_REGULAR_OBJ_EVENT_GFX + 359)
#define OBJ_EVENT_GFX_POKEMON_361		(NUM_REGULAR_OBJ_EVENT_GFX + 360)
#define OBJ_EVENT_GFX_POKEMON_362		(NUM_REGULAR_OBJ_EVENT_GFX + 361)
#define OBJ_EVENT_GFX_POKEMON_363		(NUM_REGULAR_OBJ_EVENT_GFX + 362)
#define OBJ_EVENT_GFX_POKEMON_364		(NUM_REGULAR_OBJ_EVENT_GFX + 363)
#define OBJ_EVENT_GFX_POKEMON_365		(NUM_REGULAR_OBJ_EVENT_GFX + 364)
#define OBJ_EVENT_GFX_POKEMON_366		(NUM_REGULAR_OBJ_EVENT_GFX + 365)
#define OBJ_EVENT_GFX_POKEMON_367		(NUM_REGULAR_OBJ_EVENT_GFX + 366)
#define OBJ_EVENT_GFX_POKEMON_368		(NUM_REGULAR_OBJ_EVENT_GFX + 367)
#define OBJ_EVENT_GFX_POKEMON_369		(NUM_REGULAR_OBJ_EVENT_GFX + 368)
#define OBJ_EVENT_GFX_POKEMON_370		(NUM_REGULAR_OBJ_EVENT_GFX + 369)
#define OBJ_EVENT_GFX_POKEMON_371		(NUM_REGULAR_OBJ_EVENT_GFX + 370)
#define OBJ_EVENT_GFX_POKEMON_372		(NUM_REGULAR_OBJ_EVENT_GFX + 371)
#define OBJ_EVENT_GFX_POKEMON_373		(NUM_REGULAR_OBJ_EVENT_GFX + 372)
#define OBJ_EVENT_GFX_POKEMON_374		(NUM_REGULAR_OBJ_EVENT_GFX + 373)
#define OBJ_EVENT_GFX_POKEMON_375		(NUM_REGULAR_OBJ_EVENT_GFX + 374)
#define OBJ_EVENT_GFX_POKEMON_376		(NUM_REGULAR_OBJ_EVENT_GFX + 375)
#define OBJ_EVENT_GFX_POKEMON_377		(NUM_REGULAR_OBJ_EVENT_GFX + 376)
#define OBJ_EVENT_GFX_POKEMON_378		(NUM_REGULAR_OBJ_EVENT_GFX + 377)
#define OBJ_EVENT_GFX_POKEMON_379		(NUM_REGULAR_OBJ_EVENT_GFX + 378)
#define OBJ_EVENT_GFX_POKEMON_380		(NUM_REGULAR_OBJ_EVENT_GFX + 379)
#define OBJ_EVENT_GFX_POKEMON_381		(NUM_REGULAR_OBJ_EVENT_GFX + 380)
#define OBJ_EVENT_GFX_POKEMON_382		(NUM_REGULAR_OBJ_EVENT_GFX + 381)
#define OBJ_EVENT_GFX_POKEMON_383		(NUM_REGULAR_OBJ_EVENT_GFX + 382)
#define OBJ_EVENT_GFX_POKEMON_384		(NUM_REGULAR_OBJ_EVENT_GFX + 383)
#define OBJ_EVENT_GFX_POKEMON_385		(NUM_REGULAR_OBJ_EVENT_GFX + 384)
#define OBJ_EVENT_GFX_POKEMON_386		(NUM_REGULAR_OBJ_EVENT_GFX + 385)
#define OBJ_EVENT_GFX_POKEMON_387		(NUM_REGULAR_OBJ_EVENT_GFX + 386)
#define OBJ_EVENT_GFX_POKEMON_388		(NUM_REGULAR_OBJ_EVENT_GFX + 387)
#define OBJ_EVENT_GFX_POKEMON_389		(NUM_REGULAR_OBJ_EVENT_GFX + 388)
#define OBJ_EVENT_GFX_POKEMON_390		(NUM_REGULAR_OBJ_EVENT_GFX + 389)
#define OBJ_EVENT_GFX_POKEMON_391		(NUM_REGULAR_OBJ_EVENT_GFX + 390)
#define OBJ_EVENT_GFX_POKEMON_392		(NUM_REGULAR_OBJ_EVENT_GFX + 391)
#define OBJ_EVENT_GFX_POKEMON_393		(NUM_REGULAR_OBJ_EVENT_GFX + 392)
#define OBJ_EVENT_GFX_POKEMON_394		(NUM_REGULAR_OBJ_EVENT_GFX + 393)
#define OBJ_EVENT_GFX_POKEMON_395		(NUM_REGULAR_OBJ_EVENT_GFX + 394)
#define OBJ_EVENT_GFX_POKEMON_396		(NUM_REGULAR_OBJ_EVENT_GFX + 395)
#define OBJ_EVENT_GFX_POKEMON_397		(NUM_REGULAR_OBJ_EVENT_GFX + 396)
#define OBJ_EVENT_GFX_POKEMON_398		(NUM_REGULAR_OBJ_EVENT_GFX + 397)
#define OBJ_EVENT_GFX_POKEMON_399		(NUM_REGULAR_OBJ_EVENT_GFX + 398)
#define OBJ_EVENT_GFX_POKEMON_400		(NUM_REGULAR_OBJ_EVENT_GFX + 399)
#define OBJ_EVENT_GFX_POKEMON_401		(NUM_REGULAR_OBJ_EVENT_GFX + 400)
#define OBJ_EVENT_GFX_POKEMON_402		(NUM_REGULAR_OBJ_EVENT_GFX + 401)
#define OBJ_EVENT_GFX_POKEMON_403		(NUM_REGULAR_OBJ_EVENT_GFX + 402)
#define OBJ_EVENT_GFX_POKEMON_404		(NUM_REGULAR_OBJ_EVENT_GFX + 403)
#define OBJ_EVENT_GFX_POKEMON_405		(NUM_REGULAR_OBJ_EVENT_GFX + 404)
#define OBJ_EVENT_GFX_POKEMON_406		(NUM_REGULAR_OBJ_EVENT_GFX + 405)
#define OBJ_EVENT_GFX_POKEMON_407		(NUM_REGULAR_OBJ_EVENT_GFX + 406)
#define OBJ_EVENT_GFX_POKEMON_408		(NUM_REGULAR_OBJ_EVENT_GFX + 407)
#define OBJ_EVENT_GFX_POKEMON_409		(NUM_REGULAR_OBJ_EVENT_GFX + 408)
#define OBJ_EVENT_GFX_POKEMON_410		(NUM_REGULAR_OBJ_EVENT_GFX + 409)
#define OBJ_EVENT_GFX_POKEMON_411		(NUM_REGULAR_OBJ_EVENT_GFX + 410)
#define OBJ_EVENT_GFX_POKEMON_412		(NUM_REGULAR_OBJ_EVENT_GFX + 411)
#define OBJ_EVENT_GFX_POKEMON_413		(NUM_REGULAR_OBJ_EVENT_GFX + 412)
#define OBJ_EVENT_GFX_POKEMON_414		(NUM_REGULAR_OBJ_EVENT_GFX + 413)
#define OBJ_EVENT_GFX_POKEMON_415		(NUM_REGULAR_OBJ_EVENT_GFX + 414)
#define OBJ_EVENT_GFX_POKEMON_416		(NUM_REGULAR_OBJ_EVENT_GFX + 415)
#define OBJ_EVENT_GFX_POKEMON_417		(NUM_REGULAR_OBJ_EVENT_GFX + 416)
#define OBJ_EVENT_GFX_POKEMON_418		(NUM_REGULAR_OBJ_EVENT_GFX + 417)
#define OBJ_EVENT_GFX_POKEMON_419		(NUM_REGULAR_OBJ_EVENT_GFX + 418)
#define OBJ_EVENT_GFX_POKEMON_420		(NUM_REGULAR_OBJ_EVENT_GFX + 419)
#define OBJ_EVENT_GFX_POKEMON_421		(NUM_REGULAR_OBJ_EVENT_GFX + 420)
#define OBJ_EVENT_GFX_POKEMON_422		(NUM_REGULAR_OBJ_EVENT_GFX + 421)
#define OBJ_EVENT_GFX_POKEMON_423		(NUM_REGULAR_OBJ_EVENT_GFX + 422)
#define OBJ_EVENT_GFX_POKEMON_424		(NUM_REGULAR_OBJ_EVENT_GFX + 423)
#define OBJ_EVENT_GFX_POKEMON_425		(NUM_REGULAR_OBJ_EVENT_GFX + 424)
#define OBJ_EVENT_GFX_POKEMON_426		(NUM_REGULAR_OBJ_EVENT_GFX + 425)
#define OBJ_EVENT_GFX_POKEMON_427		(NUM_REGULAR_OBJ_EVENT_GFX + 426)
#define OBJ_EVENT_GFX_POKEMON_428		(NUM_REGULAR_OBJ_EVENT_GFX + 427)
#define OBJ_EVENT_GFX_POKEMON_429		(NUM_REGULAR_OBJ_EVENT_GFX + 428)
#define OBJ_EVENT_GFX_POKEMON_430		(NUM_REGULAR_OBJ_EVENT_GFX + 429)
#define OBJ_EVENT_GFX_POKEMON_431		(NUM_REGULAR_OBJ_EVENT_GFX + 430)
#define OBJ_EVENT_GFX_POKEMON_432		(NUM_REGULAR_OBJ_EVENT_GFX + 431)
#define OBJ_EVENT_GFX_POKEMON_433		(NUM_REGULAR_OBJ_EVENT_GFX + 432)
#define OBJ_EVENT_GFX_POKEMON_434		(NUM_REGULAR_OBJ_EVENT_GFX + 433)
#define OBJ_EVENT_GFX_POKEMON_435		(NUM_REGULAR_OBJ_EVENT_GFX + 434)
#define OBJ_EVENT_GFX_POKEMON_436		(NUM_REGULAR_OBJ_EVENT_GFX + 435)
#define OBJ_EVENT_GFX_POKEMON_437		(NUM_REGULAR_OBJ_EVENT_GFX + 436)
#define OBJ_EVENT_GFX_POKEMON_438		(NUM_REGULAR_OBJ_EVENT_GFX + 437)
#define OBJ_EVENT_GFX_POKEMON_439		(NUM_REGULAR_OBJ_EVENT_GFX + 438)
#define OBJ_EVENT_GFX_POKEMON_440		(NUM_REGULAR_OBJ_EVENT_GFX + 439)
#define OBJ_EVENT_GFX_POKEMON_441		(NUM_REGULAR_OBJ_EVENT_GFX + 440)
#define OBJ_EVENT_GFX_POKEMON_442		(NUM_REGULAR_OBJ_EVENT_GFX + 441)
#define OBJ_EVENT_GFX_POKEMON_443		(NUM_REGULAR_OBJ_EVENT_GFX + 442)
#define OBJ_EVENT_GFX_POKEMON_444		(NUM_REGULAR_OBJ_EVENT_GFX + 443)
#define OBJ_EVENT_GFX_POKEMON_445		(NUM_REGULAR_OBJ_EVENT_GFX + 444)
#define OBJ_EVENT_GFX_POKEMON_446		(NUM_REGULAR_OBJ_EVENT_GFX + 445)
#define OBJ_EVENT_GFX_POKEMON_447		(NUM_REGULAR_OBJ_EVENT_GFX + 446)
#define OBJ_EVENT_GFX_POKEMON_448		(NUM_REGULAR_OBJ_EVENT_GFX + 447)
#define OBJ_EVENT_GFX_POKEMON_449		(NUM_REGULAR_OBJ_EVENT_GFX + 448)
#define OBJ_EVENT_GFX_POKEMON_450		(NUM_REGULAR_OBJ_EVENT_GFX + 449)
#define OBJ_EVENT_GFX_POKEMON_451		(NUM_REGULAR_OBJ_EVENT_GFX + 450)
#define OBJ_EVENT_GFX_POKEMON_452		(NUM_REGULAR_OBJ_EVENT_GFX + 451)
#define OBJ_EVENT_GFX_POKEMON_453		(NUM_REGULAR_OBJ_EVENT_GFX + 452)
#define OBJ_EVENT_GFX_POKEMON_454		(NUM_REGULAR_OBJ_EVENT_GFX + 453)
#define OBJ_EVENT_GFX_POKEMON_455		(NUM_REGULAR_OBJ_EVENT_GFX + 454)
#define OBJ_EVENT_GFX_POKEMON_456		(NUM_REGULAR_OBJ_EVENT_GFX + 455)
#define OBJ_EVENT_GFX_POKEMON_457		(NUM_REGULAR_OBJ_EVENT_GFX + 456)
#define OBJ_EVENT_GFX_POKEMON_458		(NUM_REGULAR_OBJ_EVENT_GFX + 457)
#define OBJ_EVENT_GFX_POKEMON_459		(NUM_REGULAR_OBJ_EVENT_GFX + 458)
#define OBJ_EVENT_GFX_POKEMON_460		(NUM_REGULAR_OBJ_EVENT_GFX + 459)
#define OBJ_EVENT_GFX_POKEMON_461		(NUM_REGULAR_OBJ_EVENT_GFX + 460)
#define OBJ_EVENT_GFX_POKEMON_462		(NUM_REGULAR_OBJ_EVENT_GFX + 461)
#define OBJ_EVENT_GFX_POKEMON_463		(NUM_REGULAR_OBJ_EVENT_GFX + 462)
#define OBJ_EVENT_GFX_POKEMON_464		(NUM_REGULAR_OBJ_EVENT_GFX + 463)
#define OBJ_EVENT_GFX_POKEMON_465		(NUM_REGULAR_OBJ_EVENT_GFX + 464)
#define OBJ_EVENT_GFX_POKEMON_466		(NUM_REGULAR_OBJ_EVENT_GFX + 465)
#define OBJ_EVENT_GFX_POKEMON_467		(NUM_REGULAR_OBJ_EVENT_GFX + 466)
#define OBJ_EVENT_GFX_POKEMON_468		(NUM_REGULAR_OBJ_EVENT_GFX + 467)
#define OBJ_EVENT_GFX_POKEMON_469		(NUM_REGULAR_OBJ_EVENT_GFX + 468)
#define OBJ_EVENT_GFX_POKEMON_470		(NUM_REGULAR_OBJ_EVENT_GFX + 469)
#define OBJ_EVENT_GFX_POKEMON_471		(NUM_REGULAR_OBJ_EVENT_GFX + 470)
#define OBJ_EVENT_GFX_POKEMON_472		(NUM_REGULAR_OBJ_EVENT_GFX + 471)
#define OBJ_EVENT_GFX_POKEMON_473		(NUM_REGULAR_OBJ_EVENT_GFX + 472)
#define OBJ_EVENT_GFX_POKEMON_474		(NUM_REGULAR_OBJ_EVENT_GFX + 473)
#define OBJ_EVENT_GFX_POKEMON_475		(NUM_REGULAR_OBJ_EVENT_GFX + 474)
#define OBJ_EVENT_GFX_POKEMON_476		(NUM_REGULAR_OBJ_EVENT_GFX + 475)
#define OBJ_EVENT_GFX_POKEMON_477		(NUM_REGULAR_OBJ_EVENT_GFX + 476)
#define OBJ_EVENT_GFX_POKEMON_478		(NUM_REGULAR_OBJ_EVENT_GFX + 477)
#define OBJ_EVENT_GFX_POKEMON_479		(NUM_REGULAR_OBJ_EVENT_GFX + 478)
#define OBJ_EVENT_GFX_POKEMON_480		(NUM_REGULAR_OBJ_EVENT_GFX + 479)
#define OBJ_EVENT_GFX_POKEMON_481		(NUM_REGULAR_OBJ_EVENT_GFX + 480)
#define OBJ_EVENT_GFX_POKEMON_482		(NUM_REGULAR_OBJ_EVENT_GFX + 481)
#define OBJ_EVENT_GFX_POKEMON_483		(NUM_REGULAR_OBJ_EVENT_GFX + 482)
#define OBJ_EVENT_GFX_POKEMON_484		(NUM_REGULAR_OBJ_EVENT_GFX + 483)
#define OBJ_EVENT_GFX_POKEMON_485		(NUM_REGULAR_OBJ_EVENT_GFX + 484)
#define OBJ_EVENT_GFX_POKEMON_486		(NUM_REGULAR_OBJ_EVENT_GFX + 485)
#define OBJ_EVENT_GFX_POKEMON_487		(NUM_REGULAR_OBJ_EVENT_GFX + 486)
#define OBJ_EVENT_GFX_POKEMON_488		(NUM_REGULAR_OBJ_EVENT_GFX + 487)
#define OBJ_EVENT_GFX_POKEMON_489		(NUM_REGULAR_OBJ_EVENT_GFX + 488)
#define OBJ_EVENT_GFX_POKEMON_490		(NUM_REGULAR_OBJ_EVENT_GFX + 489)
#define OBJ_EVENT_GFX_POKEMON_491		(NUM_REGULAR_OBJ_EVENT_GFX + 490)
#define OBJ_EVENT_GFX_POKEMON_492		(NUM_REGULAR_OBJ_EVENT_GFX + 491)
#define OBJ_EVENT_GFX_POKEMON_493		(NUM_REGULAR_OBJ_EVENT_GFX + 492)
#define OBJ_EVENT_GFX_POKEMON_494		(NUM_REGULAR_OBJ_EVENT_GFX + 493)
#define OBJ_EVENT_GFX_POKEMON_495		(NUM_REGULAR_OBJ_EVENT_GFX + 494)
#define OBJ_EVENT_GFX_POKEMON_496		(NUM_REGULAR_OBJ_EVENT_GFX + 495)
#define OBJ_EVENT_GFX_POKEMON_497		(NUM_REGULAR_OBJ_EVENT_GFX + 496)
#define OBJ_EVENT_GFX_POKEMON_498		(NUM_REGULAR_OBJ_EVENT_GFX + 497)
#define OBJ_EVENT_GFX_POKEMON_499		(NUM_REGULAR_OBJ_EVENT_GFX + 498)
#define OBJ_EVENT_GFX_POKEMON_500		(NUM_REGULAR_OBJ_EVENT_GFX + 499)
#define OBJ_EVENT_GFX_POKEMON_501		(NUM_REGULAR_OBJ_EVENT_GFX + 500)
#define OBJ_EVENT_GFX_POKEMON_502		(NUM_REGULAR_OBJ_EVENT_GFX + 501)
#define OBJ_EVENT_GFX_POKEMON_503		(NUM_REGULAR_OBJ_EVENT_GFX + 502)
#define OBJ_EVENT_GFX_POKEMON_504		(NUM_REGULAR_OBJ_EVENT_GFX + 503)
#define OBJ_EVENT_GFX_POKEMON_505		(NUM_REGULAR_OBJ_EVENT_GFX + 504)
#define OBJ_EVENT_GFX_POKEMON_506		(NUM_REGULAR_OBJ_EVENT_GFX + 505)
#define OBJ_EVENT_GFX_POKEMON_507		(NUM_REGULAR_OBJ_EVENT_GFX + 506)
#define OBJ_EVENT_GFX_POKEMON_508		(NUM_REGULAR_OBJ_EVENT_GFX + 507)
#define OBJ_EVENT_GFX_POKEMON_509		(NUM_REGULAR_OBJ_EVENT_GFX + 508)
#define OBJ_EVENT_GFX_POKEMON_510		(NUM_REGULAR_OBJ_EVENT_GFX + 509)
#define OBJ_EVENT_GFX_POKEMON_511		(NUM_REGULAR_OBJ_EVENT_GFX + 510)
#define OBJ_EVENT_GFX_POKEMON_512		(NUM_REGULAR_OBJ_EVENT_GFX + 511)
#define OBJ_EVENT_GFX_POKEMON_513		(NUM_REGULAR_OBJ_EVENT_GFX + 512)
#define OBJ_EVENT_GFX_POKEMON_514		(NUM_REGULAR_OBJ_EVENT_GFX + 513)
#define OBJ_EVENT_GFX_POKEMON_515		(NUM_REGULAR_OBJ_EVENT_GFX + 514)
#define OBJ_EVENT_GFX_POKEMON_516		(NUM_REGULAR_OBJ_EVENT_GFX + 515)
#define OBJ_EVENT_GFX_POKEMON_517		(NUM_REGULAR_OBJ_EVENT_GFX + 516)
#define OBJ_EVENT_GFX_POKEMON_518		(NUM_REGULAR_OBJ_EVENT_GFX + 517)
#define OBJ_EVENT_GFX_POKEMON_519		(NUM_REGULAR_OBJ_EVENT_GFX + 518)
#define OBJ_EVENT_GFX_POKEMON_520		(NUM_REGULAR_OBJ_EVENT_GFX + 519)
#define OBJ_EVENT_GFX_POKEMON_521		(NUM_REGULAR_OBJ_EVENT_GFX + 520)
#define OBJ_EVENT_GFX_POKEMON_522		(NUM_REGULAR_OBJ_EVENT_GFX + 521)
#define OBJ_EVENT_GFX_POKEMON_523		(NUM_REGULAR_OBJ_EVENT_GFX + 522)
#define OBJ_EVENT_GFX_POKEMON_524		(NUM_REGULAR_OBJ_EVENT_GFX + 523)
#define OBJ_EVENT_GFX_POKEMON_525		(NUM_REGULAR_OBJ_EVENT_GFX + 524)
#define OBJ_EVENT_GFX_POKEMON_526		(NUM_REGULAR_OBJ_EVENT_GFX + 525)
#define OBJ_EVENT_GFX_POKEMON_527		(NUM_REGULAR_OBJ_EVENT_GFX + 526)
#define OBJ_EVENT_GFX_POKEMON_528		(NUM_REGULAR_OBJ_EVENT_GFX + 527)
#define OBJ_EVENT_GFX_POKEMON_529		(NUM_REGULAR_OBJ_EVENT_GFX + 528)
#define OBJ_EVENT_GFX_POKEMON_530		(NUM_REGULAR_OBJ_EVENT_GFX + 529)
#define OBJ_EVENT_GFX_POKEMON_531		(NUM_REGULAR_OBJ_EVENT_GFX + 530)
#define OBJ_EVENT_GFX_POKEMON_532		(NUM_REGULAR_OBJ_EVENT_GFX + 531)
#define OBJ_EVENT_GFX_POKEMON_533		(NUM_REGULAR_OBJ_EVENT_GFX + 532)
#define OBJ_EVENT_GFX_POKEMON_534		(NUM_REGULAR_OBJ_EVENT_GFX + 533)
#define OBJ_EVENT_GFX_POKEMON_535		(NUM_REGULAR_OBJ_EVENT_GFX + 534)
#define OBJ_EVENT_GFX_POKEMON_536		(NUM_REGULAR_OBJ_EVENT_GFX + 535)
#define OBJ_EVENT_GFX_POKEMON_537		(NUM_REGULAR_OBJ_EVENT_GFX + 536)
#define OBJ_EVENT_GFX_POKEMON_538		(NUM_REGULAR_OBJ_EVENT_GFX + 537)
#define OBJ_EVENT_GFX_POKEMON_539		(NUM_REGULAR_OBJ_EVENT_GFX + 538)
#define OBJ_EVENT_GFX_POKEMON_540		(NUM_REGULAR_OBJ_EVENT_GFX + 539)
#define OBJ_EVENT_GFX_POKEMON_541		(NUM_REGULAR_OBJ_EVENT_GFX + 540)
#define OBJ_EVENT_GFX_POKEMON_542		(NUM_REGULAR_OBJ_EVENT_GFX + 541)
#define OBJ_EVENT_GFX_POKEMON_543		(NUM_REGULAR_OBJ_EVENT_GFX + 542)
#define OBJ_EVENT_GFX_POKEMON_544		(NUM_REGULAR_OBJ_EVENT_GFX + 543)
#define OBJ_EVENT_GFX_POKEMON_545		(NUM_REGULAR_OBJ_EVENT_GFX + 544)
#define OBJ_EVENT_GFX_POKEMON_546		(NUM_REGULAR_OBJ_EVENT_GFX + 545)
#define OBJ_EVENT_GFX_POKEMON_547		(NUM_REGULAR_OBJ_EVENT_GFX + 546)
#define OBJ_EVENT_GFX_POKEMON_548		(NUM_REGULAR_OBJ_EVENT_GFX + 547)
#define OBJ_EVENT_GFX_POKEMON_549		(NUM_REGULAR_OBJ_EVENT_GFX + 548)
#define OBJ_EVENT_GFX_POKEMON_550		(NUM_REGULAR_OBJ_EVENT_GFX + 549)
#define OBJ_EVENT_GFX_POKEMON_551		(NUM_REGULAR_OBJ_EVENT_GFX + 550)
#define OBJ_EVENT_GFX_POKEMON_552		(NUM_REGULAR_OBJ_EVENT_GFX + 551)
#define OBJ_EVENT_GFX_POKEMON_553		(NUM_REGULAR_OBJ_EVENT_GFX + 552)
#define OBJ_EVENT_GFX_POKEMON_554		(NUM_REGULAR_OBJ_EVENT_GFX + 553)
#define OBJ_EVENT_GFX_POKEMON_555		(NUM_REGULAR_OBJ_EVENT_GFX + 554)
#define OBJ_EVENT_GFX_POKEMON_556		(NUM_REGULAR_OBJ_EVENT_GFX + 555)
#define OBJ_EVENT_GFX_POKEMON_557		(NUM_REGULAR_OBJ_EVENT_GFX + 556)
#define OBJ_EVENT_GFX_POKEMON_558		(NUM_REGULAR_OBJ_EVENT_GFX + 557)
#define OBJ_EVENT_GFX_POKEMON_559		(NUM_REGULAR_OBJ_EVENT_GFX + 558)
#define OBJ_EVENT_GFX_POKEMON_560		(NUM_REGULAR_OBJ_EVENT_GFX + 559)
#define OBJ_EVENT_GFX_POKEMON_561		(NUM_REGULAR_OBJ_EVENT_GFX + 560)
#define OBJ_EVENT_GFX_POKEMON_562		(NUM_REGULAR_OBJ_EVENT_GFX + 561)
#define OBJ_EVENT_GFX_POKEMON_563		(NUM_REGULAR_OBJ_EVENT_GFX + 562)
#define OBJ_EVENT_GFX_POKEMON_564		(NUM_REGULAR_OBJ_EVENT_GFX + 563)
#define OBJ_EVENT_GFX_POKEMON_565		(NUM_REGULAR_OBJ_EVENT_GFX + 564)
#define OBJ_EVENT_GFX_POKEMON_566		(NUM_REGULAR_OBJ_EVENT_GFX + 565)
#define OBJ_EVENT_GFX_POKEMON_567		(NUM_REGULAR_OBJ_EVENT_GFX + 566)
#define OBJ_EVENT_GFX_POKEMON_568		(NUM_REGULAR_OBJ_EVENT_GFX + 567)
#define OBJ_EVENT_GFX_POKEMON_569		(NUM_REGULAR_OBJ_EVENT_GFX + 568)
#define OBJ_EVENT_GFX_POKEMON_570		(NUM_REGULAR_OBJ_EVENT_GFX + 569)
#define OBJ_EVENT_GFX_POKEMON_571		(NUM_REGULAR_OBJ_EVENT_GFX + 570)
#define OBJ_EVENT_GFX_POKEMON_572		(NUM_REGULAR_OBJ_EVENT_GFX + 571)
#define OBJ_EVENT_GFX_POKEMON_573		(NUM_REGULAR_OBJ_EVENT_GFX + 572)
#define OBJ_EVENT_GFX_POKEMON_574		(NUM_REGULAR_OBJ_EVENT_GFX + 573)
#define OBJ_EVENT_GFX_POKEMON_575		(NUM_REGULAR_OBJ_EVENT_GFX + 574)
#define OBJ_EVENT_GFX_POKEMON_576		(NUM_REGULAR_OBJ_EVENT_GFX + 575)
#define OBJ_EVENT_GFX_POKEMON_577		(NUM_REGULAR_OBJ_EVENT_GFX + 576)
#define OBJ_EVENT_GFX_POKEMON_578		(NUM_REGULAR_OBJ_EVENT_GFX + 577)
#define OBJ_EVENT_GFX_POKEMON_579		(NUM_REGULAR_OBJ_EVENT_GFX + 578)
#define OBJ_EVENT_GFX_POKEMON_580		(NUM_REGULAR_OBJ_EVENT_GFX + 579)
#define OBJ_EVENT_GFX_POKEMON_581		(NUM_REGULAR_OBJ_EVENT_GFX + 580)
#define OBJ_EVENT_GFX_POKEMON_582		(NUM_REGULAR_OBJ_EVENT_GFX + 581)
#define OBJ_EVENT_GFX_POKEMON_583		(NUM_REGULAR_OBJ_EVENT_GFX + 582)
#define OBJ_EVENT_GFX_POKEMON_584		(NUM_REGULAR_OBJ_EVENT_GFX + 583)
#define OBJ_EVENT_GFX_POKEMON_585		(NUM_REGULAR_OBJ_EVENT_GFX + 584)
#define OBJ_EVENT_GFX_POKEMON_586		(NUM_REGULAR_OBJ_EVENT_GFX + 585)
#define OBJ_EVENT_GFX_POKEMON_587		(NUM_REGULAR_OBJ_EVENT_GFX + 586)
#define OBJ_EVENT_GFX_POKEMON_588		(NUM_REGULAR_OBJ_EVENT_GFX + 587)
#define OBJ_EVENT_GFX_POKEMON_589		(NUM_REGULAR_OBJ_EVENT_GFX + 588)
#define OBJ_EVENT_GFX_POKEMON_590		(NUM_REGULAR_OBJ_EVENT_GFX + 589)
#define OBJ_EVENT_GFX_POKEMON_591		(NUM_REGULAR_OBJ_EVENT_GFX + 590)
#define OBJ_EVENT_GFX_POKEMON_592		(NUM_REGULAR_OBJ_EVENT_GFX + 591)
#define OBJ_EVENT_GFX_POKEMON_593		(NUM_REGULAR_OBJ_EVENT_GFX + 592)
#define OBJ_EVENT_GFX_POKEMON_594		(NUM_REGULAR_OBJ_EVENT_GFX + 593)
#define OBJ_EVENT_GFX_POKEMON_595		(NUM_REGULAR_OBJ_EVENT_GFX + 594)
#define OBJ_EVENT_GFX_POKEMON_596		(NUM_REGULAR_OBJ_EVENT_GFX + 595)
#define OBJ_EVENT_GFX_POKEMON_597		(NUM_REGULAR_OBJ_EVENT_GFX + 596)
#define OBJ_EVENT_GFX_POKEMON_598		(NUM_REGULAR_OBJ_EVENT_GFX + 597)
#define OBJ_EVENT_GFX_POKEMON_599		(NUM_REGULAR_OBJ_EVENT_GFX + 598)
#define OBJ_EVENT_GFX_POKEMON_600		(NUM_REGULAR_OBJ_EVENT_GFX + 599)
#define OBJ_EVENT_GFX_POKEMON_601		(NUM_REGULAR_OBJ_EVENT_GFX + 600)
#define OBJ_EVENT_GFX_POKEMON_602		(NUM_REGULAR_OBJ_EVENT_GFX + 601)
#define OBJ_EVENT_GFX_POKEMON_603		(NUM_REGULAR_OBJ_EVENT_GFX + 602)
#define OBJ_EVENT_GFX_POKEMON_604		(NUM_REGULAR_OBJ_EVENT_GFX + 603)
#define OBJ_EVENT_GFX_POKEMON_605		(NUM_REGULAR_OBJ_EVENT_GFX + 604)
#define OBJ_EVENT_GFX_POKEMON_606		(NUM_REGULAR_OBJ_EVENT_GFX + 605)
#define OBJ_EVENT_GFX_POKEMON_607		(NUM_REGULAR_OBJ_EVENT_GFX + 606)
#define OBJ_EVENT_GFX_POKEMON_608		(NUM_REGULAR_OBJ_EVENT_GFX + 607)
#define OBJ_EVENT_GFX_POKEMON_609		(NUM_REGULAR_OBJ_EVENT_GFX + 608)
#define OBJ_EVENT_GFX_POKEMON_610		(NUM_REGULAR_OBJ_EVENT_GFX + 609)
#define OBJ_EVENT_GFX_POKEMON_611		(NUM_REGULAR_OBJ_EVENT_GFX + 610)
#define OBJ_EVENT_GFX_POKEMON_612		(NUM_REGULAR_OBJ_EVENT_GFX + 611)
#define OBJ_EVENT_GFX_POKEMON_613		(NUM_REGULAR_OBJ_EVENT_GFX + 612)
#define OBJ_EVENT_GFX_POKEMON_614		(NUM_REGULAR_OBJ_EVENT_GFX + 613)
#define OBJ_EVENT_GFX_POKEMON_615		(NUM_REGULAR_OBJ_EVENT_GFX + 614)
#define OBJ_EVENT_GFX_POKEMON_616		(NUM_REGULAR_OBJ_EVENT_GFX + 615)
#define OBJ_EVENT_GFX_POKEMON_617		(NUM_REGULAR_OBJ_EVENT_GFX + 616)
#define OBJ_EVENT_GFX_POKEMON_618		(NUM_REGULAR_OBJ_EVENT_GFX + 617)
#define OBJ_EVENT_GFX_POKEMON_619		(NUM_REGULAR_OBJ_EVENT_GFX + 618)
#define OBJ_EVENT_GFX_POKEMON_620		(NUM_REGULAR_OBJ_EVENT_GFX + 619)
#define OBJ_EVENT_GFX_POKEMON_621		(NUM_REGULAR_OBJ_EVENT_GFX + 620)
#define OBJ_EVENT_GFX_POKEMON_622		(NUM_REGULAR_OBJ_EVENT_GFX + 621)
#define OBJ_EVENT_GFX_POKEMON_623		(NUM_REGULAR_OBJ_EVENT_GFX + 622)
#define OBJ_EVENT_GFX_POKEMON_624		(NUM_REGULAR_OBJ_EVENT_GFX + 623)
#define OBJ_EVENT_GFX_POKEMON_625		(NUM_REGULAR_OBJ_EVENT_GFX + 624)
#define OBJ_EVENT_GFX_POKEMON_626		(NUM_REGULAR_OBJ_EVENT_GFX + 625)
#define OBJ_EVENT_GFX_POKEMON_627		(NUM_REGULAR_OBJ_EVENT_GFX + 626)
#define OBJ_EVENT_GFX_POKEMON_628		(NUM_REGULAR_OBJ_EVENT_GFX + 627)
#define OBJ_EVENT_GFX_POKEMON_629		(NUM_REGULAR_OBJ_EVENT_GFX + 628)
#define OBJ_EVENT_GFX_POKEMON_630		(NUM_REGULAR_OBJ_EVENT_GFX + 629)
#define OBJ_EVENT_GFX_POKEMON_631		(NUM_REGULAR_OBJ_EVENT_GFX + 630)
#define OBJ_EVENT_GFX_POKEMON_632		(NUM_REGULAR_OBJ_EVENT_GFX + 631)
#define OBJ_EVENT_GFX_POKEMON_633		(NUM_REGULAR_OBJ_EVENT_GFX + 632)
#define OBJ_EVENT_GFX_POKEMON_634		(NUM_REGULAR_OBJ_EVENT_GFX + 633)
#define OBJ_EVENT_GFX_POKEMON_635		(NUM_REGULAR_OBJ_EVENT_GFX + 634)
#define OBJ_EVENT_GFX_POKEMON_636		(NUM_REGULAR_OBJ_EVENT_GFX + 635)
#define OBJ_EVENT_GFX_POKEMON_637		(NUM_REGULAR_OBJ_EVENT_GFX + 636)
#define OBJ_EVENT_GFX_POKEMON_638		(NUM_REGULAR_OBJ_EVENT_GFX + 637)
#define OBJ_EVENT_GFX_POKEMON_639		(NUM_REGULAR_OBJ_EVENT_GFX + 638)
#define OBJ_EVENT_GFX_POKEMON_640		(NUM_REGULAR_OBJ_EVENT_GFX + 639)
#define OBJ_EVENT_GFX_POKEMON_641		(NUM_REGULAR_OBJ_EVENT_GFX + 640)
#define OBJ_EVENT_GFX_POKEMON_642		(NUM_REGULAR_OBJ_EVENT_GFX + 641)
#define OBJ_EVENT_GFX_POKEMON_643		(NUM_REGULAR_OBJ_EVENT_GFX + 642)
#define OBJ_EVENT_GFX_POKEMON_644		(NUM_REGULAR_OBJ_EVENT_GFX + 643)
#define OBJ_EVENT_GFX_POKEMON_645		(NUM_REGULAR_OBJ_EVENT_GFX + 644)
#define OBJ_EVENT_GFX_POKEMON_646		(NUM_REGULAR_OBJ_EVENT_GFX + 645)
#define OBJ_EVENT_GFX_POKEMON_647		(NUM_REGULAR_OBJ_EVENT_GFX + 646)
#define OBJ_EVENT_GFX_POKEMON_648		(NUM_REGULAR_OBJ_EVENT_GFX + 647)
#define OBJ_EVENT_GFX_POKEMON_649		(NUM_REGULAR_OBJ_EVENT_GFX + 648)
#define OBJ_EVENT_GFX_POKEMON_650		(NUM_REGULAR_OBJ_EVENT_GFX + 649)
#define OBJ_EVENT_GFX_POKEMON_651		(NUM_REGULAR_OBJ_EVENT_GFX + 650)
#define OBJ_EVENT_GFX_POKEMON_652		(NUM_REGULAR_OBJ_EVENT_GFX + 651)
#define OBJ_EVENT_GFX_POKEMON_653		(NUM_REGULAR_OBJ_EVENT_GFX + 652)
#define OBJ_EVENT_GFX_POKEMON_654		(NUM_REGULAR_OBJ_EVENT_GFX + 653)
#define OBJ_EVENT_GFX_POKEMON_655		(NUM_REGULAR_OBJ_EVENT_GFX + 654)
#define OBJ_EVENT_GFX_POKEMON_656		(NUM_REGULAR_OBJ_EVENT_GFX + 655)
#define OBJ_EVENT_GFX_POKEMON_657		(NUM_REGULAR_OBJ_EVENT_GFX + 656)
#define OBJ_EVENT_GFX_POKEMON_658		(NUM_REGULAR_OBJ_EVENT_GFX + 657)
#define OBJ_EVENT_GFX_POKEMON_659		(NUM_REGULAR_OBJ_EVENT_GFX + 658)
#define OBJ_EVENT_GFX_POKEMON_660		(NUM_REGULAR_OBJ_EVENT_GFX + 659)
#define OBJ_EVENT_GFX_POKEMON_661		(NUM_REGULAR_OBJ_EVENT_GFX + 660)
#define OBJ_EVENT_GFX_POKEMON_662		(NUM_REGULAR_OBJ_EVENT_GFX + 661)
#define OBJ_EVENT_GFX_POKEMON_663		(NUM_REGULAR_OBJ_EVENT_GFX + 662)
#define OBJ_EVENT_GFX_POKEMON_664		(NUM_REGULAR_OBJ_EVENT_GFX + 663)
#define OBJ_EVENT_GFX_POKEMON_665		(NUM_REGULAR_OBJ_EVENT_GFX + 664)
#define OBJ_EVENT_GFX_POKEMON_666		(NUM_REGULAR_OBJ_EVENT_GFX + 665)
#define OBJ_EVENT_GFX_POKEMON_667		(NUM_REGULAR_OBJ_EVENT_GFX + 666)
#define OBJ_EVENT_GFX_POKEMON_668		(NUM_REGULAR_OBJ_EVENT_GFX + 667)
#define OBJ_EVENT_GFX_POKEMON_669		(NUM_REGULAR_OBJ_EVENT_GFX + 668)
#define OBJ_EVENT_GFX_POKEMON_670		(NUM_REGULAR_OBJ_EVENT_GFX + 669)
#define OBJ_EVENT_GFX_POKEMON_671		(NUM_REGULAR_OBJ_EVENT_GFX + 670)
#define OBJ_EVENT_GFX_POKEMON_672		(NUM_REGULAR_OBJ_EVENT_GFX + 671)
#define OBJ_EVENT_GFX_POKEMON_673		(NUM_REGULAR_OBJ_EVENT_GFX + 672)
#define OBJ_EVENT_GFX_POKEMON_674		(NUM_REGULAR_OBJ_EVENT_GFX + 673)
#define OBJ_EVENT_GFX_POKEMON_675		(NUM_REGULAR_OBJ_EVENT_GFX + 674)
#define OBJ_EVENT_GFX_POKEMON_676		(NUM_REGULAR_OBJ_EVENT_GFX + 675)
#define OBJ_EVENT_GFX_POKEMON_677		(NUM_REGULAR_OBJ_EVENT_GFX + 676)
#define OBJ_EVENT_GFX_POKEMON_678		(NUM_REGULAR_OBJ_EVENT_GFX + 677)
#define OBJ_EVENT_GFX_POKEMON_679		(NUM_REGULAR_OBJ_EVENT_GFX + 678)
#define OBJ_EVENT_GFX_POKEMON_680		(NUM_REGULAR_OBJ_EVENT_GFX + 679)
#define OBJ_EVENT_GFX_POKEMON_681		(NUM_REGULAR_OBJ_EVENT_GFX + 680)
#define OBJ_EVENT_GFX_POKEMON_682		(NUM_REGULAR_OBJ_EVENT_GFX + 681)
#define OBJ_EVENT_GFX_POKEMON_683		(NUM_REGULAR_OBJ_EVENT_GFX + 682)
#define OBJ_EVENT_GFX_POKEMON_684		(NUM_REGULAR_OBJ_EVENT_GFX + 683)
#define OBJ_EVENT_GFX_POKEMON_685		(NUM_REGULAR_OBJ_EVENT_GFX + 684)
#define OBJ_EVENT_GFX_POKEMON_686		(NUM_REGULAR_OBJ_EVENT_GFX + 685)
#define OBJ_EVENT_GFX_POKEMON_687		(NUM_REGULAR_OBJ_EVENT_GFX + 686)
#define OBJ_EVENT_GFX_POKEMON_688		(NUM_REGULAR_OBJ_EVENT_GFX + 687)
#define OBJ_EVENT_GFX_POKEMON_689		(NUM_REGULAR_OBJ_EVENT_GFX + 688)
#define OBJ_EVENT_GFX_POKEMON_690		(NUM_REGULAR_OBJ_EVENT_GFX + 689)
#define OBJ_EVENT_GFX_POKEMON_691		(NUM_REGULAR_OBJ_EVENT_GFX + 690)
#define OBJ_EVENT_GFX_POKEMON_692		(NUM_REGULAR_OBJ_EVENT_GFX + 691)
#define OBJ_EVENT_GFX_POKEMON_693		(NUM_REGULAR_OBJ_EVENT_GFX + 692)
#define OBJ_EVENT_GFX_POKEMON_694		(NUM_REGULAR_OBJ_EVENT_GFX + 693)
#define OBJ_EVENT_GFX_POKEMON_695		(NUM_REGULAR_OBJ_EVENT_GFX + 694)
#define OBJ_EVENT_GFX_POKEMON_696		(NUM_REGULAR_OBJ_EVENT_GFX + 695)
#define OBJ_EVENT_GFX_POKEMON_697		(NUM_REGULAR_OBJ_EVENT_GFX + 696)
#define OBJ_EVENT_GFX_POKEMON_698		(NUM_REGULAR_OBJ_EVENT_GFX + 697)
#define OBJ_EVENT_GFX_POKEMON_699		(NUM_REGULAR_OBJ_EVENT_GFX + 698)
#define OBJ_EVENT_GFX_POKEMON_700		(NUM_REGULAR_OBJ_EVENT_GFX + 699)
#define OBJ_EVENT_GFX_POKEMON_701		(NUM_REGULAR_OBJ_EVENT_GFX + 700)
#define OBJ_EVENT_GFX_POKEMON_702		(NUM_REGULAR_OBJ_EVENT_GFX + 701)
#define OBJ_EVENT_GFX_POKEMON_703		(NUM_REGULAR_OBJ_EVENT_GFX + 702)
#define OBJ_EVENT_GFX_POKEMON_704		(NUM_REGULAR_OBJ_EVENT_GFX + 703)
#define OBJ_EVENT_GFX_POKEMON_705		(NUM_REGULAR_OBJ_EVENT_GFX + 704)
#define OBJ_EVENT_GFX_POKEMON_706		(NUM_REGULAR_OBJ_EVENT_GFX + 705)
#define OBJ_EVENT_GFX_POKEMON_707		(NUM_REGULAR_OBJ_EVENT_GFX + 706)
#define OBJ_EVENT_GFX_POKEMON_708		(NUM_REGULAR_OBJ_EVENT_GFX + 707)
#define OBJ_EVENT_GFX_POKEMON_709		(NUM_REGULAR_OBJ_EVENT_GFX + 708)
#define OBJ_EVENT_GFX_POKEMON_710		(NUM_REGULAR_OBJ_EVENT_GFX + 709)
#define OBJ_EVENT_GFX_POKEMON_711		(NUM_REGULAR_OBJ_EVENT_GFX + 710)
#define OBJ_EVENT_GFX_POKEMON_712		(NUM_REGULAR_OBJ_EVENT_GFX + 711)
#define OBJ_EVENT_GFX_POKEMON_713		(NUM_REGULAR_OBJ_EVENT_GFX + 712)
#define OBJ_EVENT_GFX_POKEMON_714		(NUM_REGULAR_OBJ_EVENT_GFX + 713)
#define OBJ_EVENT_GFX_POKEMON_715		(NUM_REGULAR_OBJ_EVENT_GFX + 714)
#define OBJ_EVENT_GFX_POKEMON_716		(NUM_REGULAR_OBJ_EVENT_GFX + 715)
#define OBJ_EVENT_GFX_POKEMON_717		(NUM_REGULAR_OBJ_EVENT_GFX + 716)
#define OBJ_EVENT_GFX_POKEMON_718		(NUM_REGULAR_OBJ_EVENT_GFX + 717)
#define OBJ_EVENT_GFX_POKEMON_719		(NUM_REGULAR_OBJ_EVENT_GFX + 718)
#define OBJ_EVENT_GFX_POKEMON_720		(NUM_REGULAR_OBJ_EVENT_GFX + 719)
#define OBJ_EVENT_GFX_POKEMON_721		(NUM_REGULAR_OBJ_EVENT_GFX + 720)
#define OBJ_EVENT_GFX_POKEMON_722		(NUM_REGULAR_OBJ_EVENT_GFX + 721)
#define OBJ_EVENT_GFX_POKEMON_723		(NUM_REGULAR_OBJ_EVENT_GFX + 722)
#define OBJ_EVENT_GFX_POKEMON_724		(NUM_REGULAR_OBJ_EVENT_GFX + 723)
#define OBJ_EVENT_GFX_POKEMON_725		(NUM_REGULAR_OBJ_EVENT_GFX + 724)
#define OBJ_EVENT_GFX_POKEMON_726		(NUM_REGULAR_OBJ_EVENT_GFX + 725)
#define OBJ_EVENT_GFX_POKEMON_727		(NUM_REGULAR_OBJ_EVENT_GFX + 726)
#define OBJ_EVENT_GFX_POKEMON_728		(NUM_REGULAR_OBJ_EVENT_GFX + 727)
#define OBJ_EVENT_GFX_POKEMON_729		(NUM_REGULAR_OBJ_EVENT_GFX + 728)
#define OBJ_EVENT_GFX_POKEMON_730		(NUM_REGULAR_OBJ_EVENT_GFX + 729)
#define OBJ_EVENT_GFX_POKEMON_731		(NUM_REGULAR_OBJ_EVENT_GFX + 730)
#define OBJ_EVENT_GFX_POKEMON_732		(NUM_REGULAR_OBJ_EVENT_GFX + 731)
#define OBJ_EVENT_GFX_POKEMON_733		(NUM_REGULAR_OBJ_EVENT_GFX + 732)
#define OBJ_EVENT_GFX_POKEMON_734		(NUM_REGULAR_OBJ_EVENT_GFX + 733)
#define OBJ_EVENT_GFX_POKEMON_735		(NUM_REGULAR_OBJ_EVENT_GFX + 734)
#define OBJ_EVENT_GFX_POKEMON_736		(NUM_REGULAR_OBJ_EVENT_GFX + 735)
#define OBJ_EVENT_GFX_POKEMON_737		(NUM_REGULAR_OBJ_EVENT_GFX + 736)
#define OBJ_EVENT_GFX_POKEMON_738		(NUM_REGULAR_OBJ_EVENT_GFX + 737)
#define OBJ_EVENT_GFX_POKEMON_739		(NUM_REGULAR_OBJ_EVENT_GFX + 738)
#define OBJ_EVENT_GFX_POKEMON_740		(NUM_REGULAR_OBJ_EVENT_GFX + 739)
#define OBJ_EVENT_GFX_POKEMON_741		(NUM_REGULAR_OBJ_EVENT_GFX + 740)
#define OBJ_EVENT_GFX_POKEMON_742		(NUM_REGULAR_OBJ_EVENT_GFX + 741)
#define OBJ_EVENT_GFX_POKEMON_743		(NUM_REGULAR_OBJ_EVENT_GFX + 742)
#define OBJ_EVENT_GFX_POKEMON_744		(NUM_REGULAR_OBJ_EVENT_GFX + 743)
#define OBJ_EVENT_GFX_POKEMON_745		(NUM_REGULAR_OBJ_EVENT_GFX + 744)
#define OBJ_EVENT_GFX_POKEMON_746		(NUM_REGULAR_OBJ_EVENT_GFX + 745)
#define OBJ_EVENT_GFX_POKEMON_747		(NUM_REGULAR_OBJ_EVENT_GFX + 746)
#define OBJ_EVENT_GFX_POKEMON_748		(NUM_REGULAR_OBJ_EVENT_GFX + 747)
#define OBJ_EVENT_GFX_POKEMON_749		(NUM_REGULAR_OBJ_EVENT_GFX + 748)
#define OBJ_EVENT_GFX_POKEMON_750		(NUM_REGULAR_OBJ_EVENT_GFX + 749)
#define OBJ_EVENT_GFX_POKEMON_751		(NUM_REGULAR_OBJ_EVENT_GFX + 750)
#define OBJ_EVENT_GFX_POKEMON_752		(NUM_REGULAR_OBJ_EVENT_GFX + 751)
#define OBJ_EVENT_GFX_POKEMON_753		(NUM_REGULAR_OBJ_EVENT_GFX + 752)
#define OBJ_EVENT_GFX_POKEMON_754		(NUM_REGULAR_OBJ_EVENT_GFX + 753)
#define OBJ_EVENT_GFX_POKEMON_755		(NUM_REGULAR_OBJ_EVENT_GFX + 754)
#define OBJ_EVENT_GFX_POKEMON_756		(NUM_REGULAR_OBJ_EVENT_GFX + 755)
#define OBJ_EVENT_GFX_POKEMON_757		(NUM_REGULAR_OBJ_EVENT_GFX + 756)
#define OBJ_EVENT_GFX_POKEMON_758		(NUM_REGULAR_OBJ_EVENT_GFX + 757)
#define OBJ_EVENT_GFX_POKEMON_759		(NUM_REGULAR_OBJ_EVENT_GFX + 758)
#define OBJ_EVENT_GFX_POKEMON_760		(NUM_REGULAR_OBJ_EVENT_GFX + 759)
#define OBJ_EVENT_GFX_POKEMON_761		(NUM_REGULAR_OBJ_EVENT_GFX + 760)
#define OBJ_EVENT_GFX_POKEMON_762		(NUM_REGULAR_OBJ_EVENT_GFX + 761)
#define OBJ_EVENT_GFX_POKEMON_763		(NUM_REGULAR_OBJ_EVENT_GFX + 762)
#define OBJ_EVENT_GFX_POKEMON_764		(NUM_REGULAR_OBJ_EVENT_GFX + 763)
#define OBJ_EVENT_GFX_POKEMON_765		(NUM_REGULAR_OBJ_EVENT_GFX + 764)
#define OBJ_EVENT_GFX_POKEMON_766		(NUM_REGULAR_OBJ_EVENT_GFX + 765)
#define OBJ_EVENT_GFX_POKEMON_767		(NUM_REGULAR_OBJ_EVENT_GFX + 766)
#define OBJ_EVENT_GFX_POKEMON_768		(NUM_REGULAR_OBJ_EVENT_GFX + 767)
#define OBJ_EVENT_GFX_POKEMON_769		(NUM_REGULAR_OBJ_EVENT_GFX + 768)
#define OBJ_EVENT_GFX_POKEMON_770		(NUM_REGULAR_OBJ_EVENT_GFX + 769)
#define OBJ_EVENT_GFX_POKEMON_771		(NUM_REGULAR_OBJ_EVENT_GFX + 770)
#define OBJ_EVENT_GFX_POKEMON_772		(NUM_REGULAR_OBJ_EVENT_GFX + 771)
#define OBJ_EVENT_GFX_POKEMON_773		(NUM_REGULAR_OBJ_EVENT_GFX + 772)
#define OBJ_EVENT_GFX_POKEMON_774		(NUM_REGULAR_OBJ_EVENT_GFX + 773)
#define OBJ_EVENT_GFX_POKEMON_775		(NUM_REGULAR_OBJ_EVENT_GFX + 774)
#define OBJ_EVENT_GFX_POKEMON_776		(NUM_REGULAR_OBJ_EVENT_GFX + 775)
#define OBJ_EVENT_GFX_POKEMON_777		(NUM_REGULAR_OBJ_EVENT_GFX + 776)
#define OBJ_EVENT_GFX_POKEMON_778		(NUM_REGULAR_OBJ_EVENT_GFX + 777)
#define OBJ_EVENT_GFX_POKEMON_779		(NUM_REGULAR_OBJ_EVENT_GFX + 778)
#define OBJ_EVENT_GFX_POKEMON_780		(NUM_REGULAR_OBJ_EVENT_GFX + 779)
#define OBJ_EVENT_GFX_POKEMON_781		(NUM_REGULAR_OBJ_EVENT_GFX + 780)
#define OBJ_EVENT_GFX_POKEMON_782		(NUM_REGULAR_OBJ_EVENT_GFX + 781)
#define OBJ_EVENT_GFX_POKEMON_783		(NUM_REGULAR_OBJ_EVENT_GFX + 782)
#define OBJ_EVENT_GFX_POKEMON_784		(NUM_REGULAR_OBJ_EVENT_GFX + 783)
#define OBJ_EVENT_GFX_POKEMON_785		(NUM_REGULAR_OBJ_EVENT_GFX + 784)
#define OBJ_EVENT_GFX_POKEMON_786		(NUM_REGULAR_OBJ_EVENT_GFX + 785)
#define OBJ_EVENT_GFX_POKEMON_787		(NUM_REGULAR_OBJ_EVENT_GFX + 786)
#define OBJ_EVENT_GFX_POKEMON_788		(NUM_REGULAR_OBJ_EVENT_GFX + 787)
#define OBJ_EVENT_GFX_POKEMON_789		(NUM_REGULAR_OBJ_EVENT_GFX + 788)
#define OBJ_EVENT_GFX_POKEMON_790		(NUM_REGULAR_OBJ_EVENT_GFX + 789)
#define OBJ_EVENT_GFX_POKEMON_791		(NUM_REGULAR_OBJ_EVENT_GFX + 790)
#define OBJ_EVENT_GFX_POKEMON_792		(NUM_REGULAR_OBJ_EVENT_GFX + 791)
#define OBJ_EVENT_GFX_POKEMON_793		(NUM_REGULAR_OBJ_EVENT_GFX + 792)
#define OBJ_EVENT_GFX_POKEMON_794		(NUM_REGULAR_OBJ_EVENT_GFX + 793)
#define OBJ_EVENT_GFX_POKEMON_795		(NUM_REGULAR_OBJ_EVENT_GFX + 794)
#define OBJ_EVENT_GFX_POKEMON_796		(NUM_REGULAR_OBJ_EVENT_GFX + 795)
#define OBJ_EVENT_GFX_POKEMON_797		(NUM_REGULAR_OBJ_EVENT_GFX + 796)
#define OBJ_EVENT_GFX_POKEMON_798		(NUM_REGULAR_OBJ_EVENT_GFX + 797)
#define OBJ_EVENT_GFX_POKEMON_799		(NUM_REGULAR_OBJ_EVENT_GFX + 798)
#define OBJ_EVENT_GFX_POKEMON_800		(NUM_REGULAR_OBJ_EVENT_GFX + 799)
#define OBJ_EVENT_GFX_POKEMON_801		(NUM_REGULAR_OBJ_EVENT_GFX + 800)
#define OBJ_EVENT_GFX_POKEMON_802		(NUM_REGULAR_OBJ_EVENT_GFX + 801)
#define OBJ_EVENT_GFX_POKEMON_803		(NUM_REGULAR_OBJ_EVENT_GFX + 802)
#define OBJ_EVENT_GFX_POKEMON_804		(NUM_REGULAR_OBJ_EVENT_GFX + 803)
#define OBJ_EVENT_GFX_POKEMON_805		(NUM_REGULAR_OBJ_EVENT_GFX + 804)
#define OBJ_EVENT_GFX_POKEMON_806		(NUM_REGULAR_OBJ_EVENT_GFX + 805)
#define OBJ_EVENT_GFX_POKEMON_807		(NUM_REGULAR_OBJ_EVENT_GFX + 806)
#define OBJ_EVENT_GFX_POKEMON_808		(NUM_REGULAR_OBJ_EVENT_GFX + 807)
#define OBJ_EVENT_GFX_POKEMON_809		(NUM_REGULAR_OBJ_EVENT_GFX + 808)

// NOTE: By default, the max value for NUM_OBJ_EVENT_GFX is 239.
//
// Object event graphics ids are 1 byte in size (max value of 255), and the dynamic
// graphics ids that start after NUM_OBJ_EVENT_GFX reach this limit. No graphics id
// uses the value 239 itself, so removing the "+ 1" in OBJ_EVENT_GFX_VARS would
// allow increasing NUM_OBJ_EVENT_GFX to 240. There are also a handful of unused
// object graphics that can be removed. If more graphics are needed, anything that
// stores graphics ids will need to be increased in size. See wiki entry below:
// https://github.com/pret/pokeemerald/wiki/Feature-Branches#overworld-expansion
#define NUM_OBJ_EVENT_GFX               (OBJ_EVENT_GFX_POKEMON_809 + 1)


// These are dynamic object gfx ids.
// They correspond with the values of the VAR_OBJ_GFX_ID_X vars.
// More info about them in include/constants/vars.h
#define OBJ_EVENT_GFX_VARS   (NUM_OBJ_EVENT_GFX + 1)
#define OBJ_EVENT_GFX_VAR_0  (OBJ_EVENT_GFX_VARS + 0x0) // 240
#define OBJ_EVENT_GFX_VAR_1  (OBJ_EVENT_GFX_VARS + 0x1)
#define OBJ_EVENT_GFX_VAR_2  (OBJ_EVENT_GFX_VARS + 0x2)
#define OBJ_EVENT_GFX_VAR_3  (OBJ_EVENT_GFX_VARS + 0x3)
#define OBJ_EVENT_GFX_VAR_4  (OBJ_EVENT_GFX_VARS + 0x4)
#define OBJ_EVENT_GFX_VAR_5  (OBJ_EVENT_GFX_VARS + 0x5)
#define OBJ_EVENT_GFX_VAR_6  (OBJ_EVENT_GFX_VARS + 0x6)
#define OBJ_EVENT_GFX_VAR_7  (OBJ_EVENT_GFX_VARS + 0x7)
#define OBJ_EVENT_GFX_VAR_8  (OBJ_EVENT_GFX_VARS + 0x8)
#define OBJ_EVENT_GFX_VAR_9  (OBJ_EVENT_GFX_VARS + 0x9)
#define OBJ_EVENT_GFX_VAR_A  (OBJ_EVENT_GFX_VARS + 0xA)
#define OBJ_EVENT_GFX_VAR_B  (OBJ_EVENT_GFX_VARS + 0xB)
#define OBJ_EVENT_GFX_VAR_C  (OBJ_EVENT_GFX_VARS + 0xC)
#define OBJ_EVENT_GFX_VAR_D  (OBJ_EVENT_GFX_VARS + 0xD)
#define OBJ_EVENT_GFX_VAR_E  (OBJ_EVENT_GFX_VARS + 0xE)
#define OBJ_EVENT_GFX_VAR_F  (OBJ_EVENT_GFX_VARS + 0xF) // 255

#define SHADOW_SIZE_S   0
#define SHADOW_SIZE_M   1
#define SHADOW_SIZE_L   2
#define SHADOW_SIZE_XL  3

#define F_INANIMATE                        (1 << 6)
#define F_DISABLE_REFLECTION_PALETTE_LOAD  (1 << 7)

#define TRACKS_NONE       0
#define TRACKS_FOOT       1
#define TRACKS_BIKE_TIRE  2

#define FIRST_DECORATION_SPRITE_GFX OBJ_EVENT_GFX_PICHU_DOLL

// Special object event local ids
#define OBJ_EVENT_ID_PLAYER 0xFF
#define OBJ_EVENT_ID_CAMERA 0x7F

// Object event local ids referenced in C files
#define LOCALID_ROUTE111_PLAYER_FALLING 45
#define LOCALID_BIRTH_ISLAND_EXTERIOR_ROCK 1
#define LOCALID_FARAWAY_ISLAND_MEW 1
#define LOCALID_UNION_ROOM_PLAYER_4 2
#define LOCALID_UNION_ROOM_PLAYER_8 3
#define LOCALID_UNION_ROOM_PLAYER_7 4
#define LOCALID_UNION_ROOM_PLAYER_6 5
#define LOCALID_UNION_ROOM_PLAYER_5 6
#define LOCALID_UNION_ROOM_PLAYER_3 7
#define LOCALID_UNION_ROOM_PLAYER_2 8
#define LOCALID_UNION_ROOM_PLAYER_1 9
#define LOCALID_BATTLE_TOWER_LOBBY_REPORTER 5
#define LOCALID_TRUCK_BOX_TOP 1
#define LOCALID_TRUCK_BOX_BOTTOM_L 2
#define LOCALID_TRUCK_BOX_BOTTOM_R 3
#define LOCALID_OLDALE_MART_CLERK 1
#define LOCALID_LAVARIDGE_MART_CLERK 1
#define LOCALID_FALLARBOR_MART_CLERK 1
#define LOCALID_VERDANTURF_MART_CLERK 1
#define LOCALID_PETALBURG_MART_CLERK 1
#define LOCALID_SLATEPORT_MART_CLERK 1
#define LOCALID_MAUVILLE_MART_CLERK 1
#define LOCALID_RUSTBORO_MART_CLERK 1
#define LOCALID_FORTREE_MART_CLERK 1
#define LOCALID_MOSSDEEP_MART_CLERK 1
#define LOCALID_SOOTOPOLIS_MART_CLERK 1
#define LOCALID_BATTLE_FRONTIER_MART_CLERK 1
#define LOCALID_SLATEPORT_ENERGY_GURU 25

#endif  // GUARD_CONSTANTS_EVENT_OBJECTS_H
