#ifndef GUARD_CONSTANTS_EVENT_OBJECT_VAR_VALUES_H
#define GUARD_CONSTANTS_EVENT_OBJECT_VAR_VALUES_H

#include "vars.h"

#define INTRO_SEQUENCE_STATE_MALE 1
#define INTRO_SEQUENCE_STATE_FEMALE 2
#define INTRO_SEQUENCE_STATE_ENTERING_HOUSE 3

#define BIRCH_ATTACK_INACTIVE 0

#endif // GUARD_CONSTANTS_EVENT_OBJECT_VAR_VALUES_H