#ifndef GUARD_CONSTANTS_FIELD_SPECIALS_H
#define GUARD_CONSTANTS_FIELD_SPECIALS_H

// PC Locations
#define PC_LOCATION_OTHER           0
#define PC_LOCATION_BRENDANS_HOUSE  1
#define PC_LOCATION_MAYS_HOUSE      2

// SS Tidal Locations
#define SS_TIDAL_LOCATION_OTHER     0
#define SS_TIDAL_LOCATION_SLATEPORT 1
#define SS_TIDAL_LOCATION_LILYCOVE  2
#define SS_TIDAL_LOCATION_ROUTE124  3
#define SS_TIDAL_LOCATION_ROUTE131  4

// Scrollable Multichoice Menus
#define SCROLL_MULTI_NONE                                  0
#define SCROLL_MULTI_GLASS_WORKSHOP_VENDOR                 1
#define SCROLL_MULTI_POKEMON_FAN_CLUB_RATER                2
#define SCROLL_MULTI_BF_EXCHANGE_CORNER_DECOR_VENDOR_1     3
#define SCROLL_MULTI_BF_EXCHANGE_CORNER_DECOR_VENDOR_2     4
#define SCROLL_MULTI_BF_EXCHANGE_CORNER_VITAMIN_VENDOR     5
#define SCROLL_MULTI_BF_EXCHANGE_CORNER_HOLD_ITEM_VENDOR   6
#define SCROLL_MULTI_BERRY_POWDER_VENDOR                   7
#define SCROLL_MULTI_BF_RECEPTIONIST                       8
#define SCROLL_MULTI_BF_MOVE_TUTOR_1                       9
#define SCROLL_MULTI_BF_MOVE_TUTOR_2                      10
#define SCROLL_MULTI_SS_TIDAL_DESTINATION                 11
#define SCROLL_MULTI_BATTLE_TENT_RULES                    12

#define MAX_SCROLL_MULTI_ON_SCREEN 6
#define MAX_SCROLL_MULTI_LENGTH 16

// Dept Store Floor Numbers
#define DEPT_STORE_FLOORNUM_B4F       0
#define DEPT_STORE_FLOORNUM_B3F       1
#define DEPT_STORE_FLOORNUM_B2F       2
#define DEPT_STORE_FLOORNUM_B1F       3
#define DEPT_STORE_FLOORNUM_1F        4
#define DEPT_STORE_FLOORNUM_2F        5
#define DEPT_STORE_FLOORNUM_3F        6
#define DEPT_STORE_FLOORNUM_4F        7
#define DEPT_STORE_FLOORNUM_5F        8
#define DEPT_STORE_FLOORNUM_6F        9
#define DEPT_STORE_FLOORNUM_7F       10
#define DEPT_STORE_FLOORNUM_8F       11
#define DEPT_STORE_FLOORNUM_9F       12
#define DEPT_STORE_FLOORNUM_10F      13
#define DEPT_STORE_FLOORNUM_11F      14
#define DEPT_STORE_FLOORNUM_ROOFTOP  15

#endif // GUARD_CONSTANTS_FIELD_SPECIALS_H
