#ifndef GUARD_FIELD_EFFECT_CONSTANTS_H
#define GUARD_FIELD_EFFECT_CONSTANTS_H

#define FLDEFF_EXCLAMATION_MARK_ICON     0 
#define FLDEFF_USE_CUT_ON_GRASS          1
#define FLDEFF_USE_CUT_ON_TREE           2
#define FLDEFF_SHADOW                    3
#define FLDEFF_TALL_GRASS                4
#define FLDEFF_RIPPLE                    5
#define FLDEFF_FIELD_MOVE_SHOW_MON       6
#define FLDEFF_ASH                       7
#define FLDEFF_SURF_BLOB                 8
#define FLDEFF_USE_SURF                  9
#define FLDEFF_DUST                      10
#define FLDEFF_USE_SECRET_POWER_CAVE     11
#define FLDEFF_JUMP_TALL_GRASS           12
#define FLDEFF_SAND_FOOTPRINTS           13
#define FLDEFF_JUMP_BIG_SPLASH           14
#define FLDEFF_SPLASH                    15
#define FLDEFF_JUMP_SMALL_SPLASH         16
#define FLDEFF_LONG_GRASS                17
#define FLDEFF_JUMP_LONG_GRASS           18
#define FLDEFF_UNKNOWN_19                19
#define FLDEFF_UNKNOWN_20                20
#define FLDEFF_UNKNOWN_21                21
#define FLDEFF_UNKNOWN_22                22
#define FLDEFF_BERRY_TREE_GROWTH_SPARKLE 23
#define FLDEFF_DEEP_SAND_FOOTPRINTS      24
#define FLDEFF_POKECENTER_HEAL           25
#define FLDEFF_USE_SECRET_POWER_TREE     26
#define FLDEFF_USE_SECRET_POWER_SHRUB    27
#define FLDEFF_TREE_DISGUISE             28
#define FLDEFF_MOUNTAIN_DISGUISE         29
#define FLDEFF_NPCFLY_OUT                30
#define FLDEFF_USE_FLY                   31
#define FLDEFF_FLY_IN                    32
#define FLDEFF_QUESTION_MARK_ICON        33
#define FLDEFF_FEET_IN_FLOWING_WATER     34
#define FLDEFF_BIKE_TIRE_TRACKS          35
#define FLDEFF_SAND_DISGUISE             36
#define FLDEFF_USE_ROCK_SMASH            37
#define FLDEFF_USE_DIG                   38
#define FLDEFF_SAND_PILE                 39
#define FLDEFF_USE_STRENGTH              40
#define FLDEFF_SHORT_GRASS               41
#define FLDEFF_HOT_SPRINGS_WATER         42
#define FLDEFF_USE_WATERFALL             43
#define FLDEFF_USE_DIVE                  44
#define FLDEFF_POKEBALL                  45
#define FLDEFF_HEART_ICON                46
#define FLDEFF_NOP_47                    47
#define FLDEFF_NOP_48                    48
#define FLDEFF_POP_OUT_OF_ASH            49
#define FLDEFF_LAVARIDGE_GYM_WARP        50
#define FLDEFF_SWEET_SCENT               51
#define FLDEFF_SAND_PILLAR               52
#define FLDEFF_BUBBLES                   53
#define FLDEFF_SPARKLE                   54
#define FLDEFF_SECRET_POWER_CAVE         55
#define FLDEFF_SECRET_POWER_TREE         56
#define FLDEFF_SECRET_POWER_SHRUB        57
#define FLDEFF_CUT_GRASS                 58
#define FLDEFF_FIELD_MOVE_SHOW_MON_INIT  59
#define FLDEFF_USE_TOMB_PUZZLE_EFFECT    60
#define FLDEFF_PCTURN_ON                 61
#define FLDEFF_HALL_OF_FAME_RECORD       62
#define FLDEFF_USE_TELEPORT              63
#define FLDEFF_RAYQUAZA                  64
#define FLDEFF_65                        65
#define FLDEFF_MOVE_DEOXYS_ROCK          66

#endif
