#ifndef GUARD_CONSTANTS_FIELD_POISON_H
#define GUARD_CONSTANTS_FIELD_POISON_H

#define FLDPSN_NONE  0
#define FLDPSN_PSN   1
#define FLDPSN_FNT   2

#define FLDPSN_NO_WHITEOUT        0
#define FLDPSN_WHITEOUT           1
#define FLDPSN_FRONTIER_WHITEOUT  2

#endif //GUARD_CONSTANTS_FIELD_POISON_H
