#ifndef GUARD_CONSTANTS_FOLLOWERS_H
#define GUARD_CONSTANTS_FOLLOWERS_H

#define FOLLOWER_HAPPY_MESSAGE_COUNT    31
#define FOLLOWER_NEUTRAL_MESSAGE_COUNT  14
#define FOLLOWER_SAD_MESSAGE_COUNT       3
#define FOLLOWER_UPSET_MESSAGE_COUNT     3
#define FOLLOWER_ANGRY_MESSAGE_COUNT     5
#define FOLLOWER_PENSIVE_MESSAGE_COUNT  20
#define FOLLOWER_LOVE_MESSAGE_COUNT     10
#define FOLLOWER_SURPRISE_MESSAGE_COUNT 20
#define FOLLOWER_CURIOUS_MESSAGE_COUNT   7
#define FOLLOWER_MUSIC_MESSAGE_COUNT    14
#define FOLLOWER_POISONED_MESSAGE_COUNT  1

#endif //GUARD_CONSTANTS_FOLLOWERS_H
