#ifndef GUARD_CONSTANTS_GAME_STAT_H
#define GUARD_CONSTANTS_GAME_STAT_H

#define GAME_STAT_SAVED_GAME                 0
#define GAME_STAT_FIRST_HOF_PLAY_TIME        1
#define GAME_STAT_STARTED_TRENDS             2
#define GAME_STAT_PLANTED_BERRIES            3
#define GAME_STAT_TRADED_BIKES               4
#define GAME_STAT_STEPS                      5
#define GAME_STAT_GOT_INTERVIEWED            6
#define GAME_STAT_TOTAL_BATTLES              7
#define GAME_STAT_WILD_BATTLES               8
#define GAME_STAT_TRAINER_BATTLES            9
#define GAME_STAT_ENTERED_HOF               10
#define GAME_STAT_POKEMON_CAPTURES          11
#define GAME_STAT_FISHING_CAPTURES          12
#define GAME_STAT_HATCHED_EGGS              13
#define GAME_STAT_EVOLVED_POKEMON           14
#define GAME_STAT_USED_POKECENTER           15
#define GAME_STAT_RESTED_AT_HOME            16
#define GAME_STAT_ENTERED_SAFARI_ZONE       17
#define GAME_STAT_USED_CUT                  18
#define GAME_STAT_USED_ROCK_SMASH           19
#define GAME_STAT_MOVED_SECRET_BASE         20
#define GAME_STAT_POKEMON_TRADES            21
#define GAME_STAT_UNKNOWN_22                22
#define GAME_STAT_LINK_BATTLE_WINS          23
#define GAME_STAT_LINK_BATTLE_LOSSES        24
#define GAME_STAT_LINK_BATTLE_DRAWS         25
#define GAME_STAT_USED_SPLASH               26
#define GAME_STAT_USED_STRUGGLE             27
#define GAME_STAT_SLOT_JACKPOTS             28
#define GAME_STAT_CONSECUTIVE_ROULETTE_WINS 29
#define GAME_STAT_ENTERED_BATTLE_TOWER      30
#define GAME_STAT_UNKNOWN_31                31
#define GAME_STAT_BATTLE_TOWER_BEST_STREAK  32
#define GAME_STAT_POKEBLOCKS                33
#define GAME_STAT_POKEBLOCKS_WITH_FRIENDS   34
#define GAME_STAT_WON_LINK_CONTEST          35
#define GAME_STAT_ENTERED_CONTEST           36
#define GAME_STAT_WON_CONTEST               37
#define GAME_STAT_SHOPPED                   38
#define GAME_STAT_USED_ITEMFINDER           39
#define GAME_STAT_GOT_RAINED_ON             40
#define GAME_STAT_CHECKED_POKEDEX           41
#define GAME_STAT_RECEIVED_RIBBONS          42
#define GAME_STAT_JUMPED_DOWN_LEDGES        43
#define GAME_STAT_WATCHED_TV                44
#define GAME_STAT_CHECKED_CLOCK             45
#define GAME_STAT_WON_POKEMON_LOTTERY       46
#define GAME_STAT_USED_DAYCARE              47
#define GAME_STAT_RODE_CABLE_CAR            48
#define GAME_STAT_ENTERED_HOT_SPRINGS       49
#define GAME_STAT_NUM_UNION_ROOM_BATTLES    50
#define GAME_STAT_51                        51

#define NUM_USED_GAME_STATS                 52
#define NUM_GAME_STATS                      64

#endif // GUARD_CONSTANTS_GAME_STAT_H
