#ifndef GUARD_CONSTANTS_ITEMS_H
#define GUARD_CONSTANTS_ITEMS_H

#include "metaprogram.h"
#include "constants/tms_hms.h"
#include "constants/berries.h"

enum __attribute__((packed)) Item
{
    ITEM_NONE = 0,

    // Poké Balls
    ITEM_POKE_BALL = 1,
    ITEM_GREAT_BALL = 2,
    ITEM_ULTRA_BALL = 3,
    ITEM_MASTER_BALL = 4,
    ITEM_PREMIER_BALL = 5,
    ITEM_HEAL_BALL = 6,
    ITEM_NET_BALL = 7,
    ITEM_NEST_BALL = 8,
    ITEM_DIVE_BALL = 9,
    ITEM_DUSK_BALL = 10,
    ITEM_TIMER_BALL = 11,
    ITEM_QUICK_BALL = 12,
    ITEM_REPEAT_BALL = 13,
    ITEM_LUXURY_BALL = 14,
    ITEM_LEVEL_BALL = 15,
    ITEM_LURE_BALL = 16,
    ITEM_MOON_BALL = 17,
    ITEM_FRIEND_BALL = 18,
    ITEM_LOVE_BALL = 19,
    ITEM_FAST_BALL = 20,
    ITEM_HEAVY_BALL = 21,
    ITEM_DREAM_BALL = 22,
    ITEM_SAFARI_BALL = 23,
    ITEM_SPORT_BALL = 24,
    ITEM_PARK_BALL = 25,
    ITEM_BEAST_BALL = 26,
    ITEM_CHERISH_BALL = 27,

    // Medicine
    ITEM_POTION = 28,
    ITEM_SUPER_POTION = 29,
    ITEM_HYPER_POTION = 30,
    ITEM_MAX_POTION = 31,
    ITEM_FULL_RESTORE = 32,
    ITEM_REVIVE = 33,
    ITEM_MAX_REVIVE = 34,
    ITEM_FRESH_WATER = 35,
    ITEM_SODA_POP = 36,
    ITEM_LEMONADE = 37,
    ITEM_MOOMOO_MILK = 38,
    ITEM_ENERGY_POWDER = 39,
    ITEM_ENERGYPOWDER = ITEM_ENERGY_POWDER, // Pre-Gen VI name
    ITEM_ENERGY_ROOT = 40,
    ITEM_HEAL_POWDER = 41,
    ITEM_REVIVAL_HERB = 42,
    ITEM_ANTIDOTE = 43,
    ITEM_PARALYZE_HEAL = 44,
    ITEM_PARLYZ_HEAL = ITEM_PARALYZE_HEAL, // Pre-Gen VI name
    ITEM_BURN_HEAL = 45,
    ITEM_ICE_HEAL = 46,
    ITEM_AWAKENING = 47,
    ITEM_FULL_HEAL = 48,
    ITEM_ETHER = 49,
    ITEM_MAX_ETHER = 50,
    ITEM_ELIXIR = 51,
    ITEM_ELIXER = ITEM_ELIXIR, // Pre-Gen III name
    ITEM_MAX_ELIXIR = 52,
    ITEM_MAX_ELIXER = ITEM_MAX_ELIXIR, // Pre-Gen III name
    ITEM_BERRY_JUICE = 53,
    ITEM_SACRED_ASH = 54,
    ITEM_SWEET_HEART = 55,
    ITEM_MAX_HONEY = 56,

    // Regional Specialties
    ITEM_PEWTER_CRUNCHIES = 57,
    ITEM_RAGE_CANDY_BAR = 58,
    ITEM_RAGECANDYBAR = ITEM_RAGE_CANDY_BAR, // Pre-Gen VI name
    ITEM_LAVA_COOKIE = 59,
    ITEM_OLD_GATEAU = 60,
    ITEM_CASTELIACONE = 61,
    ITEM_LUMIOSE_GALETTE = 62,
    ITEM_SHALOUR_SABLE = 63,
    ITEM_BIG_MALASADA = 64,

    // Vitamins
    ITEM_HP_UP = 65,
    ITEM_PROTEIN = 66,
    ITEM_IRON = 67,
    ITEM_CALCIUM = 68,
    ITEM_ZINC = 69,
    ITEM_CARBOS = 70,
    ITEM_PP_UP = 71,
    ITEM_PP_MAX = 72,

    // EV Feathers
    ITEM_HEALTH_FEATHER = 73,
    ITEM_HEALTH_WING = ITEM_HEALTH_FEATHER, // Pre-Gen VIII name
    ITEM_MUSCLE_FEATHER = 74,
    ITEM_MUSCLE_WING = ITEM_MUSCLE_FEATHER, // Pre-Gen VIII name
    ITEM_RESIST_FEATHER = 75,
    ITEM_RESIST_WING = ITEM_RESIST_FEATHER, // Pre-Gen VIII name
    ITEM_GENIUS_FEATHER = 76,
    ITEM_GENIUS_WING = ITEM_GENIUS_FEATHER, // Pre-Gen VIII name
    ITEM_CLEVER_FEATHER = 77,
    ITEM_CLEVER_WING = ITEM_CLEVER_FEATHER, // Pre-Gen VIII name
    ITEM_SWIFT_FEATHER = 78,
    ITEM_SWIFT_WING = ITEM_SWIFT_FEATHER, // Pre-Gen VIII name

    // Ability Modifiers
    ITEM_ABILITY_CAPSULE = 79,
    ITEM_ABILITY_PATCH = 80,

    // Mints
    ITEM_LONELY_MINT = 81,
    ITEM_ADAMANT_MINT = 82,
    ITEM_NAUGHTY_MINT = 83,
    ITEM_BRAVE_MINT = 84,
    ITEM_BOLD_MINT = 85,
    ITEM_IMPISH_MINT = 86,
    ITEM_LAX_MINT = 87,
    ITEM_RELAXED_MINT = 88,
    ITEM_MODEST_MINT = 89,
    ITEM_MILD_MINT = 90,
    ITEM_RASH_MINT = 91,
    ITEM_QUIET_MINT = 92,
    ITEM_CALM_MINT = 93,
    ITEM_GENTLE_MINT = 94,
    ITEM_CAREFUL_MINT = 95,
    ITEM_SASSY_MINT = 96,
    ITEM_TIMID_MINT = 97,
    ITEM_HASTY_MINT = 98,
    ITEM_JOLLY_MINT = 99,
    ITEM_NAIVE_MINT = 100,
    ITEM_SERIOUS_MINT = 101,

    // Candy
    ITEM_RARE_CANDY = 102,
    ITEM_EXP_CANDY_XS = 103,
    ITEM_EXP_CANDY_S = 104,
    ITEM_EXP_CANDY_M = 105,
    ITEM_EXP_CANDY_L = 106,
    ITEM_EXP_CANDY_XL = 107,
    ITEM_DYNAMAX_CANDY = 108,

    // Medicinal Flutes
    ITEM_BLUE_FLUTE = 109,
    ITEM_YELLOW_FLUTE = 110,
    ITEM_RED_FLUTE = 111,

    // Encounter-modifying Flutes
    ITEM_BLACK_FLUTE = 112,
    ITEM_WHITE_FLUTE = 113,

    // Encounter Modifiers
    ITEM_REPEL = 114,
    ITEM_SUPER_REPEL = 115,
    ITEM_MAX_REPEL = 116,
    ITEM_LURE = 117,
    ITEM_SUPER_LURE = 118,
    ITEM_MAX_LURE = 119,

    ITEM_ESCAPE_ROPE = 120,

    // X Items
    ITEM_X_ATTACK = 121,
    ITEM_X_DEFENSE = 122,
    ITEM_X_DEFEND = ITEM_X_DEFENSE, // Pre-Gen VI name
    ITEM_X_SP_ATK = 123,
    ITEM_X_SPECIAL = ITEM_X_SP_ATK, // Pre-Gen VI name
    ITEM_X_SP_DEF = 124,
    ITEM_X_SPEED = 125,
    ITEM_X_ACCURACY = 126,

    ITEM_DIRE_HIT = 127,
    ITEM_GUARD_SPEC = 128,

    // Escape Items
    ITEM_POKE_DOLL = 129,
    ITEM_FLUFFY_TAIL = 130,
    ITEM_POKE_TOY = 131,

    ITEM_MAX_MUSHROOMS = 132,

    // Treasures
    ITEM_BOTTLE_CAP = 133,
    ITEM_GOLD_BOTTLE_CAP = 134,
    ITEM_NUGGET = 135,
    ITEM_BIG_NUGGET = 136,
    ITEM_TINY_MUSHROOM = 137,
    ITEM_TINYMUSHROOM = ITEM_TINY_MUSHROOM, // Pre-Gen VI name
    ITEM_BIG_MUSHROOM = 138,
    ITEM_BALM_MUSHROOM = 139,
    ITEM_BALMMUSHROOM = ITEM_BALM_MUSHROOM, // Pre-Gen VI name
    ITEM_PEARL = 140,
    ITEM_BIG_PEARL = 141,
    ITEM_PEARL_STRING = 142,
    ITEM_STARDUST = 143,
    ITEM_STAR_PIECE = 144,
    ITEM_COMET_SHARD = 145,
    ITEM_SHOAL_SALT = 146,
    ITEM_SHOAL_SHELL = 147,
    ITEM_RED_SHARD = 148,
    ITEM_BLUE_SHARD = 149,
    ITEM_YELLOW_SHARD = 150,
    ITEM_GREEN_SHARD = 151,
    ITEM_HEART_SCALE = 152,
    ITEM_HONEY = 153,
    ITEM_RARE_BONE = 154,
    ITEM_ODD_KEYSTONE = 155,
    ITEM_PRETTY_FEATHER = 156,
    ITEM_PRETTY_WING = ITEM_PRETTY_FEATHER, // Pre-Gen VIII name
    ITEM_RELIC_COPPER = 157,
    ITEM_RELIC_SILVER = 158,
    ITEM_RELIC_GOLD = 159,
    ITEM_RELIC_VASE = 160,
    ITEM_RELIC_BAND = 161,
    ITEM_RELIC_STATUE = 162,
    ITEM_RELIC_CROWN = 163,
    ITEM_STRANGE_SOUVENIR = 164,

    // Fossils
    ITEM_HELIX_FOSSIL = 165,
    ITEM_DOME_FOSSIL = 166,
    ITEM_OLD_AMBER = 167,
    ITEM_ROOT_FOSSIL = 168,
    ITEM_CLAW_FOSSIL = 169,
    ITEM_ARMOR_FOSSIL = 170,
    ITEM_SKULL_FOSSIL = 171,
    ITEM_COVER_FOSSIL = 172,
    ITEM_PLUME_FOSSIL = 173,
    ITEM_JAW_FOSSIL = 174,
    ITEM_SAIL_FOSSIL = 175,
    ITEM_FOSSILIZED_BIRD = 176,
    ITEM_FOSSILIZED_FISH = 177,
    ITEM_FOSSILIZED_DRAKE = 178,
    ITEM_FOSSILIZED_DINO = 179,

    // Mulch
    ITEM_GROWTH_MULCH = 180,
    ITEM_DAMP_MULCH = 181,
    ITEM_STABLE_MULCH = 182,
    ITEM_GOOEY_MULCH = 183,
    ITEM_RICH_MULCH = 184,
    ITEM_SURPRISE_MULCH = 185,
    ITEM_BOOST_MULCH = 186,
    ITEM_AMAZE_MULCH = 187,

    // Apricorns
    ITEM_RED_APRICORN = 188,
    ITEM_BLUE_APRICORN = 189,
    ITEM_BLU_APRICORN = ITEM_BLUE_APRICORN, // Pre-Gen VI name
    ITEM_YELLOW_APRICORN = 190,
    ITEM_YLW_APRICORN = ITEM_YELLOW_APRICORN, // Pre-Gen VI name
    ITEM_GREEN_APRICORN = 191,
    ITEM_GRN_APRICORN = ITEM_GREEN_APRICORN, // Pre-Gen VI name
    ITEM_PINK_APRICORN = 192,
    ITEM_PNK_APRICORN = ITEM_PINK_APRICORN, // Pre-Gen VI name
    ITEM_WHITE_APRICORN = 193,
    ITEM_WHT_APRICORN = ITEM_WHITE_APRICORN, // Pre-Gen VI name
    ITEM_BLACK_APRICORN = 194,
    ITEM_BLK_APRICORN = ITEM_BLACK_APRICORN, // Pre-Gen VI name

    ITEM_WISHING_PIECE = 195,
    ITEM_GALARICA_TWIG = 196,
    ITEM_ARMORITE_ORE = 197,
    ITEM_DYNITE_ORE = 198,

    // Mail
    FIRST_MAIL_INDEX = 199,
    ITEM_ORANGE_MAIL = FIRST_MAIL_INDEX,
    ITEM_HARBOR_MAIL = 200,
    ITEM_GLITTER_MAIL = 201,
    ITEM_MECH_MAIL = 202,
    ITEM_WOOD_MAIL = 203,
    ITEM_WAVE_MAIL = 204,
    ITEM_BEAD_MAIL = 205,
    ITEM_SHADOW_MAIL = 206,
    ITEM_TROPIC_MAIL = 207,
    ITEM_DREAM_MAIL = 208,
    ITEM_FAB_MAIL = 209,
    ITEM_RETRO_MAIL = 210,

    // Evolution Items
    ITEM_FIRE_STONE = 211,
    ITEM_WATER_STONE = 212,
    ITEM_THUNDER_STONE = 213,
    ITEM_THUNDERSTONE = ITEM_THUNDER_STONE, // Pre-Gen VI name
    ITEM_LEAF_STONE = 214,
    ITEM_ICE_STONE = 215,
    ITEM_SUN_STONE = 216,
    ITEM_MOON_STONE = 217,
    ITEM_SHINY_STONE = 218,
    ITEM_DUSK_STONE = 219,
    ITEM_DAWN_STONE = 220,
    ITEM_SWEET_APPLE = 221,
    ITEM_TART_APPLE = 222,
    ITEM_CRACKED_POT = 223,
    ITEM_CHIPPED_POT = 224,
    ITEM_GALARICA_CUFF = 225,
    ITEM_GALARICA_WREATH = 226,
    ITEM_DRAGON_SCALE = 227,
    ITEM_UPGRADE = 228,
    ITEM_UP_GRADE = ITEM_UPGRADE, // Pre-Gen VIII name
    ITEM_PROTECTOR = 229,
    ITEM_ELECTIRIZER = 230,
    ITEM_MAGMARIZER = 231,
    ITEM_DUBIOUS_DISC = 232,
    ITEM_REAPER_CLOTH = 233,
    ITEM_PRISM_SCALE = 234,
    ITEM_WHIPPED_DREAM = 235,
    ITEM_SACHET = 236,
    ITEM_OVAL_STONE = 237,
    ITEM_STRAWBERRY_SWEET = 238,
    ITEM_LOVE_SWEET = 239,
    ITEM_BERRY_SWEET = 240,
    ITEM_CLOVER_SWEET = 241,
    ITEM_FLOWER_SWEET = 242,
    ITEM_STAR_SWEET = 243,
    ITEM_RIBBON_SWEET = 244,

    ITEM_EVERSTONE = 245,

    // Nectars
    ITEM_RED_NECTAR = 246,
    ITEM_YELLOW_NECTAR = 247,
    ITEM_PINK_NECTAR = 248,
    ITEM_PURPLE_NECTAR = 249,

    // Plates
    ITEM_FLAME_PLATE = 250,
    ITEM_SPLASH_PLATE = 251,
    ITEM_ZAP_PLATE = 252,
    ITEM_MEADOW_PLATE = 253,
    ITEM_ICICLE_PLATE = 254,
    ITEM_FIST_PLATE = 255,
    ITEM_TOXIC_PLATE = 256,
    ITEM_EARTH_PLATE = 257,
    ITEM_SKY_PLATE = 258,
    ITEM_MIND_PLATE = 259,
    ITEM_INSECT_PLATE = 260,
    ITEM_STONE_PLATE = 261,
    ITEM_SPOOKY_PLATE = 262,
    ITEM_DRACO_PLATE = 263,
    ITEM_DREAD_PLATE = 264,
    ITEM_IRON_PLATE = 265,
    ITEM_PIXIE_PLATE = 266,

    // Drives
    ITEM_DOUSE_DRIVE = 267,
    ITEM_SHOCK_DRIVE = 268,
    ITEM_BURN_DRIVE = 269,
    ITEM_CHILL_DRIVE = 270,

    // Memories
    ITEM_FIRE_MEMORY = 271,
    ITEM_WATER_MEMORY = 272,
    ITEM_ELECTRIC_MEMORY = 273,
    ITEM_GRASS_MEMORY = 274,
    ITEM_ICE_MEMORY = 275,
    ITEM_FIGHTING_MEMORY = 276,
    ITEM_POISON_MEMORY = 277,
    ITEM_GROUND_MEMORY = 278,
    ITEM_FLYING_MEMORY = 279,
    ITEM_PSYCHIC_MEMORY = 280,
    ITEM_BUG_MEMORY = 281,
    ITEM_ROCK_MEMORY = 282,
    ITEM_GHOST_MEMORY = 283,
    ITEM_DRAGON_MEMORY = 284,
    ITEM_DARK_MEMORY = 285,
    ITEM_STEEL_MEMORY = 286,
    ITEM_FAIRY_MEMORY = 287,

    ITEM_RUSTED_SWORD = 288,
    ITEM_RUSTED_SHIELD = 289,

    // Colored Orbs
    ITEM_RED_ORB = 290,
    ITEM_BLUE_ORB = 291,

    // Mega Stones
    ITEM_VENUSAURITE = 292,
    ITEM_CHARIZARDITE_X = 293,
    ITEM_CHARIZARDITE_Y = 294,
    ITEM_BLASTOISINITE = 295,
    ITEM_BEEDRILLITE = 296,
    ITEM_PIDGEOTITE = 297,
    ITEM_ALAKAZITE = 298,
    ITEM_SLOWBRONITE = 299,
    ITEM_GENGARITE = 300,
    ITEM_KANGASKHANITE = 301,
    ITEM_PINSIRITE = 302,
    ITEM_GYARADOSITE = 303,
    ITEM_AERODACTYLITE = 304,
    ITEM_MEWTWONITE_X = 305,
    ITEM_MEWTWONITE_Y = 306,
    ITEM_AMPHAROSITE = 307,
    ITEM_STEELIXITE = 308,
    ITEM_SCIZORITE = 309,
    ITEM_HERACRONITE = 310,
    ITEM_HOUNDOOMINITE = 311,
    ITEM_TYRANITARITE = 312,
    ITEM_SCEPTILITE = 313,
    ITEM_BLAZIKENITE = 314,
    ITEM_SWAMPERTITE = 315,
    ITEM_GARDEVOIRITE = 316,
    ITEM_SABLENITE = 317,
    ITEM_MAWILITE = 318,
    ITEM_AGGRONITE = 319,
    ITEM_MEDICHAMITE = 320,
    ITEM_MANECTITE = 321,
    ITEM_SHARPEDONITE = 322,
    ITEM_CAMERUPTITE = 323,
    ITEM_ALTARIANITE = 324,
    ITEM_BANETTITE = 325,
    ITEM_ABSOLITE = 326,
    ITEM_GLALITITE = 327,
    ITEM_SALAMENCITE = 328,
    ITEM_METAGROSSITE = 329,
    ITEM_LATIASITE = 330,
    ITEM_LATIOSITE = 331,
    ITEM_LOPUNNITE = 332,
    ITEM_GARCHOMPITE = 333,
    ITEM_LUCARIONITE = 334,
    ITEM_ABOMASITE = 335,
    ITEM_GALLADITE = 336,
    ITEM_AUDINITE = 337,
    ITEM_DIANCITE = 338,

    // Gems
    ITEM_NORMAL_GEM = 339,
    ITEM_FIRE_GEM = 340,
    ITEM_WATER_GEM = 341,
    ITEM_ELECTRIC_GEM = 342,
    ITEM_GRASS_GEM = 343,
    ITEM_ICE_GEM = 344,
    ITEM_FIGHTING_GEM = 345,
    ITEM_POISON_GEM = 346,
    ITEM_GROUND_GEM = 347,
    ITEM_FLYING_GEM = 348,
    ITEM_PSYCHIC_GEM = 349,
    ITEM_BUG_GEM = 350,
    ITEM_ROCK_GEM = 351,
    ITEM_GHOST_GEM = 352,
    ITEM_DRAGON_GEM = 353,
    ITEM_DARK_GEM = 354,
    ITEM_STEEL_GEM = 355,
    ITEM_FAIRY_GEM = 356,

    // Z-Crystals
    ITEM_NORMALIUM_Z = 357,
    ITEM_FIRIUM_Z = 358,
    ITEM_WATERIUM_Z = 359,
    ITEM_ELECTRIUM_Z = 360,
    ITEM_GRASSIUM_Z = 361,
    ITEM_ICIUM_Z = 362,
    ITEM_FIGHTINIUM_Z = 363,
    ITEM_POISONIUM_Z = 364,
    ITEM_GROUNDIUM_Z = 365,
    ITEM_FLYINIUM_Z = 366,
    ITEM_PSYCHIUM_Z = 367,
    ITEM_BUGINIUM_Z = 368,
    ITEM_ROCKIUM_Z = 369,
    ITEM_GHOSTIUM_Z = 370,
    ITEM_DRAGONIUM_Z = 371,
    ITEM_DARKINIUM_Z = 372,
    ITEM_STEELIUM_Z = 373,
    ITEM_FAIRIUM_Z = 374,
    ITEM_PIKANIUM_Z = 375,
    ITEM_EEVIUM_Z = 376,
    ITEM_SNORLIUM_Z = 377,
    ITEM_MEWNIUM_Z = 378,
    ITEM_DECIDIUM_Z = 379,
    ITEM_INCINIUM_Z = 380,
    ITEM_PRIMARIUM_Z = 381,
    ITEM_LYCANIUM_Z = 382,
    ITEM_MIMIKIUM_Z = 383,
    ITEM_KOMMONIUM_Z = 384,
    ITEM_TAPUNIUM_Z = 385,
    ITEM_SOLGANIUM_Z = 386,
    ITEM_LUNALIUM_Z = 387,
    ITEM_MARSHADIUM_Z = 388,
    ITEM_ALORAICHIUM_Z = 389,
    ITEM_PIKASHUNIUM_Z = 390,
    ITEM_ULTRANECROZIUM_Z = 391,

    // Species-specific Held Items
    ITEM_LIGHT_BALL = 392,
    ITEM_LEEK = 393,
    ITEM_STICK = ITEM_LEEK, // Pre-Gen VIII name
    ITEM_THICK_CLUB = 394,
    ITEM_LUCKY_PUNCH = 395,
    ITEM_METAL_POWDER = 396,
    ITEM_QUICK_POWDER = 397,
    ITEM_DEEP_SEA_SCALE = 398,
    ITEM_DEEPSEASCALE = ITEM_DEEP_SEA_SCALE, // Pre-Gen VI name
    ITEM_DEEP_SEA_TOOTH = 399,
    ITEM_DEEPSEATOOTH = ITEM_DEEP_SEA_TOOTH, // Pre-Gen VI name
    ITEM_SOUL_DEW = 400,
    ITEM_ADAMANT_ORB = 401,
    ITEM_LUSTROUS_ORB = 402,
    ITEM_GRISEOUS_ORB = 403,

    // Incenses
    ITEM_SEA_INCENSE = 404,
    ITEM_LAX_INCENSE = 405,
    ITEM_ODD_INCENSE = 406,
    ITEM_ROCK_INCENSE = 407,
    ITEM_FULL_INCENSE = 408,
    ITEM_WAVE_INCENSE = 409,
    ITEM_ROSE_INCENSE = 410,
    ITEM_LUCK_INCENSE = 411,
    ITEM_PURE_INCENSE = 412,

    // Contest Scarves
    ITEM_RED_SCARF = 413,
    ITEM_BLUE_SCARF = 414,
    ITEM_PINK_SCARF = 415,
    ITEM_GREEN_SCARF = 416,
    ITEM_YELLOW_SCARF = 417,

    // EV Gain Modifiers
    ITEM_MACHO_BRACE = 418,
    ITEM_POWER_WEIGHT = 419,
    ITEM_POWER_BRACER = 420,
    ITEM_POWER_BELT = 421,
    ITEM_POWER_LENS = 422,
    ITEM_POWER_BAND = 423,
    ITEM_POWER_ANKLET = 424,

    // Type-boosting Held Items
    ITEM_SILK_SCARF = 425,
    ITEM_CHARCOAL = 426,
    ITEM_MYSTIC_WATER = 427,
    ITEM_MAGNET = 428,
    ITEM_MIRACLE_SEED = 429,
    ITEM_NEVER_MELT_ICE = 430,
    ITEM_NEVERMELTICE = ITEM_NEVER_MELT_ICE, // Pre-Gen VI name
    ITEM_BLACK_BELT = 431,
    ITEM_BLACKBELT = ITEM_BLACK_BELT, // Gen II name
    ITEM_POISON_BARB = 432,
    ITEM_SOFT_SAND = 433,
    ITEM_SHARP_BEAK = 434,
    ITEM_TWISTED_SPOON = 435,
    ITEM_TWISTEDSPOON = ITEM_TWISTED_SPOON, // Pre-Gen VI name
    ITEM_SILVER_POWDER = 436,
    ITEM_SILVERPOWDER = ITEM_SILVER_POWDER, // Pre-Gen VI name
    ITEM_HARD_STONE = 437,
    ITEM_SPELL_TAG = 438,
    ITEM_DRAGON_FANG = 439,
    ITEM_BLACK_GLASSES = 440,
    ITEM_BLACKGLASSES = ITEM_BLACK_GLASSES, // Pre-Gen VI name
    ITEM_METAL_COAT = 441,

    // Choice Items
    ITEM_CHOICE_BAND = 442,
    ITEM_CHOICE_SPECS = 443,
    ITEM_CHOICE_SCARF = 444,

    // Status Orbs
    ITEM_FLAME_ORB = 445,
    ITEM_TOXIC_ORB = 446,

    // Weather Rocks
    ITEM_DAMP_ROCK = 447,
    ITEM_HEAT_ROCK = 448,
    ITEM_SMOOTH_ROCK = 449,
    ITEM_ICY_ROCK = 450,

    // Terrain Seeds
    ITEM_ELECTRIC_SEED = 451,
    ITEM_PSYCHIC_SEED = 452,
    ITEM_MISTY_SEED = 453,
    ITEM_GRASSY_SEED = 454,

    // Type-activated Stat Modifiers
    ITEM_ABSORB_BULB = 455,
    ITEM_CELL_BATTERY = 456,
    ITEM_LUMINOUS_MOSS = 457,
    ITEM_SNOWBALL = 458,

    // Misc. Held Items
    ITEM_BRIGHT_POWDER = 459,
    ITEM_BRIGHTPOWDER = ITEM_BRIGHT_POWDER, // Pre-Gen VI name
    ITEM_WHITE_HERB = 460,
    ITEM_EXP_SHARE = 461,
    ITEM_EXP_ALL = ITEM_EXP_SHARE, // Gen I name
    ITEM_QUICK_CLAW = 462,
    ITEM_SOOTHE_BELL = 463,
    ITEM_MENTAL_HERB = 464,
    ITEM_KINGS_ROCK = 465,
    ITEM_AMULET_COIN = 466,
    ITEM_CLEANSE_TAG = 467,
    ITEM_SMOKE_BALL = 468,
    ITEM_FOCUS_BAND = 469,
    ITEM_LUCKY_EGG = 470,
    ITEM_SCOPE_LENS = 471,
    ITEM_LEFTOVERS = 472,
    ITEM_SHELL_BELL = 473,
    ITEM_WIDE_LENS = 474,
    ITEM_MUSCLE_BAND = 475,
    ITEM_WISE_GLASSES = 476,
    ITEM_EXPERT_BELT = 477,
    ITEM_LIGHT_CLAY = 478,
    ITEM_LIFE_ORB = 479,
    ITEM_POWER_HERB = 480,
    ITEM_FOCUS_SASH = 481,
    ITEM_ZOOM_LENS = 482,
    ITEM_METRONOME = 483,
    ITEM_IRON_BALL = 484,
    ITEM_LAGGING_TAIL = 485,
    ITEM_DESTINY_KNOT = 486,
    ITEM_BLACK_SLUDGE = 487,
    ITEM_GRIP_CLAW = 488,
    ITEM_STICKY_BARB = 489,
    ITEM_SHED_SHELL = 490,
    ITEM_BIG_ROOT = 491,
    ITEM_RAZOR_CLAW = 492,
    ITEM_RAZOR_FANG = 493,
    ITEM_EVIOLITE = 494,
    ITEM_FLOAT_STONE = 495,
    ITEM_ROCKY_HELMET = 496,
    ITEM_AIR_BALLOON = 497,
    ITEM_RED_CARD = 498,
    ITEM_RING_TARGET = 499,
    ITEM_BINDING_BAND = 500,
    ITEM_EJECT_BUTTON = 501,
    ITEM_WEAKNESS_POLICY = 502,
    ITEM_ASSAULT_VEST = 503,
    ITEM_SAFETY_GOGGLES = 504,
    ITEM_ADRENALINE_ORB = 505,
    ITEM_TERRAIN_EXTENDER = 506,
    ITEM_PROTECTIVE_PADS = 507,
    ITEM_THROAT_SPRAY = 508,
    ITEM_EJECT_PACK = 509,
    ITEM_HEAVY_DUTY_BOOTS = 510,
    ITEM_BLUNDER_POLICY = 511,
    ITEM_ROOM_SERVICE = 512,
    ITEM_UTILITY_UMBRELLA = 513,

    // Berries
    FIRST_BERRY_INDEX = 514,
    ITEM_CHERI_BERRY = FIRST_BERRY_INDEX,
    ITEM_CHESTO_BERRY = 515,
    ITEM_PECHA_BERRY = 516,
    ITEM_RAWST_BERRY = 517,
    ITEM_ASPEAR_BERRY = 518,
    ITEM_LEPPA_BERRY = 519,
    ITEM_ORAN_BERRY = 520,
    ITEM_PERSIM_BERRY = 521,
    ITEM_LUM_BERRY = 522,
    ITEM_SITRUS_BERRY = 523,
    ITEM_FIGY_BERRY = 524,
    ITEM_WIKI_BERRY = 525,
    ITEM_MAGO_BERRY = 526,
    ITEM_AGUAV_BERRY = 527,
    ITEM_IAPAPA_BERRY = 528,
    ITEM_RAZZ_BERRY = 529,
    ITEM_BLUK_BERRY = 530,
    ITEM_NANAB_BERRY = 531,
    ITEM_WEPEAR_BERRY = 532,
    ITEM_PINAP_BERRY = 533,
    ITEM_POMEG_BERRY = 534,
    ITEM_KELPSY_BERRY = 535,
    ITEM_QUALOT_BERRY = 536,
    ITEM_HONDEW_BERRY = 537,
    ITEM_GREPA_BERRY = 538,
    ITEM_TAMATO_BERRY = 539,
    ITEM_CORNN_BERRY = 540,
    ITEM_MAGOST_BERRY = 541,
    ITEM_RABUTA_BERRY = 542,
    ITEM_NOMEL_BERRY = 543,
    ITEM_SPELON_BERRY = 544,
    ITEM_PAMTRE_BERRY = 545,
    ITEM_WATMEL_BERRY = 546,
    ITEM_DURIN_BERRY = 547,
    ITEM_BELUE_BERRY = 548,
    ITEM_CHILAN_BERRY = 549,
    ITEM_OCCA_BERRY = 550,
    ITEM_PASSHO_BERRY = 551,
    ITEM_WACAN_BERRY = 552,
    ITEM_RINDO_BERRY = 553,
    ITEM_YACHE_BERRY = 554,
    ITEM_CHOPLE_BERRY = 555,
    ITEM_KEBIA_BERRY = 556,
    ITEM_SHUCA_BERRY = 557,
    ITEM_COBA_BERRY = 558,
    ITEM_PAYAPA_BERRY = 559,
    ITEM_TANGA_BERRY = 560,
    ITEM_CHARTI_BERRY = 561,
    ITEM_KASIB_BERRY = 562,
    ITEM_HABAN_BERRY = 563,
    ITEM_COLBUR_BERRY = 564,
    ITEM_BABIRI_BERRY = 565,
    ITEM_ROSELI_BERRY = 566,
    ITEM_LIECHI_BERRY = 567,
    ITEM_GANLON_BERRY = 568,
    ITEM_SALAC_BERRY = 569,
    ITEM_PETAYA_BERRY = 570,
    ITEM_APICOT_BERRY = 571,
    ITEM_LANSAT_BERRY = 572,
    ITEM_STARF_BERRY = 573,
    ITEM_ENIGMA_BERRY = 574,
    ITEM_MICLE_BERRY = 575,
    ITEM_CUSTAP_BERRY = 576,
    ITEM_JABOCA_BERRY = 577,
    ITEM_ROWAP_BERRY = 578,
    ITEM_KEE_BERRY = 579,
    ITEM_MARANGA_BERRY = 580,
    ITEM_ENIGMA_BERRY_E_READER = 581,
    LAST_BERRY_INDEX =  ITEM_ENIGMA_BERRY_E_READER,

    // TMs/HMs
    ITEM_TM01 = 582,
    ITEM_TM02 = 583,
    ITEM_TM03 = 584,
    ITEM_TM04 = 585,
    ITEM_TM05 = 586,
    ITEM_TM06 = 587,
    ITEM_TM07 = 588,
    ITEM_TM08 = 589,
    ITEM_TM09 = 590,
    ITEM_TM10 = 591,
    ITEM_TM11 = 592,
    ITEM_TM12 = 593,
    ITEM_TM13 = 594,
    ITEM_TM14 = 595,
    ITEM_TM15 = 596,
    ITEM_TM16 = 597,
    ITEM_TM17 = 598,
    ITEM_TM18 = 599,
    ITEM_TM19 = 600,
    ITEM_TM20 = 601,
    ITEM_TM21 = 602,
    ITEM_TM22 = 603,
    ITEM_TM23 = 604,
    ITEM_TM24 = 605,
    ITEM_TM25 = 606,
    ITEM_TM26 = 607,
    ITEM_TM27 = 608,
    ITEM_TM28 = 609,
    ITEM_TM29 = 610,
    ITEM_TM30 = 611,
    ITEM_TM31 = 612,
    ITEM_TM32 = 613,
    ITEM_TM33 = 614,
    ITEM_TM34 = 615,
    ITEM_TM35 = 616,
    ITEM_TM36 = 617,
    ITEM_TM37 = 618,
    ITEM_TM38 = 619,
    ITEM_TM39 = 620,
    ITEM_TM40 = 621,
    ITEM_TM41 = 622,
    ITEM_TM42 = 623,
    ITEM_TM43 = 624,
    ITEM_TM44 = 625,
    ITEM_TM45 = 626,
    ITEM_TM46 = 627,
    ITEM_TM47 = 628,
    ITEM_TM48 = 629,
    ITEM_TM49 = 630,
    ITEM_TM50 = 631,
    ITEM_TM51 = 632,
    ITEM_TM52 = 633,
    ITEM_TM53 = 634,
    ITEM_TM54 = 635,
    ITEM_TM55 = 636,
    ITEM_TM56 = 637,
    ITEM_TM57 = 638,
    ITEM_TM58 = 639,
    ITEM_TM59 = 640,
    ITEM_TM60 = 641,
    ITEM_TM61 = 642,
    ITEM_TM62 = 643,
    ITEM_TM63 = 644,
    ITEM_TM64 = 645,
    ITEM_TM65 = 646,
    ITEM_TM66 = 647,
    ITEM_TM67 = 648,
    ITEM_TM68 = 649,
    ITEM_TM69 = 650,
    ITEM_TM70 = 651,
    ITEM_TM71 = 652,
    ITEM_TM72 = 653,
    ITEM_TM73 = 654,
    ITEM_TM74 = 655,
    ITEM_TM75 = 656,
    ITEM_TM76 = 657,
    ITEM_TM77 = 658,
    ITEM_TM78 = 659,
    ITEM_TM79 = 660,
    ITEM_TM80 = 661,
    ITEM_TM81 = 662,
    ITEM_TM82 = 663,
    ITEM_TM83 = 664,
    ITEM_TM84 = 665,
    ITEM_TM85 = 666,
    ITEM_TM86 = 667,
    ITEM_TM87 = 668,
    ITEM_TM88 = 669,
    ITEM_TM89 = 670,
    ITEM_TM90 = 671,
    ITEM_TM91 = 672,
    ITEM_TM92 = 673,
    ITEM_TM93 = 674,
    ITEM_TM94 = 675,
    ITEM_TM95 = 676,
    ITEM_TM96 = 677,
    ITEM_TM97 = 678,
    ITEM_TM98 = 679,
    ITEM_TM99 = 680,
    ITEM_TM100 = 681,

    ITEM_HM01 = 682,
    ITEM_HM02 = 683,
    ITEM_HM03 = 684,
    ITEM_HM04 = 685,
    ITEM_HM05 = 686,
    ITEM_HM06 = 687,
    ITEM_HM07 = 688,
    ITEM_HM08 = 689,


    /* Expands to:
     *   ITEM_TM_FOCUS_PUNCH = ITEM_TM01,
     *   ...
     *   ITEM_HM_CUT = ITM_HM01,
     *   ... */
    #define ENUM_TM(n, id) CAT(ITEM_TM_, id) = CAT(ITEM_TM, n),
    #define ENUM_HM(n, id) CAT(ITEM_HM_, id) = CAT(ITEM_HM, n),
    #define TO_TMHM_NUMS(a, ...) (__VA_ARGS__)
    RECURSIVELY(R_ZIP(ENUM_TM, TO_TMHM_NUMS NUMBERS_256, (FOREACH_TM(APPEND_COMMA))))
    RECURSIVELY(R_ZIP(ENUM_HM, TO_TMHM_NUMS NUMBERS_256, (FOREACH_HM(APPEND_COMMA))))
    #undef ENUM_TM
    #undef ENUM_HM
    #undef TO_TMHM_NUMS

    // Charms
    ITEM_OVAL_CHARM = 690,
    ITEM_SHINY_CHARM = 691,
    ITEM_CATCHING_CHARM = 692,
    ITEM_EXP_CHARM = 693,

    // Form-changing Key Items
    ITEM_ROTOM_CATALOG = 694,
    ITEM_GRACIDEA = 695,
    ITEM_REVEAL_GLASS = 696,
    ITEM_DNA_SPLICERS = 697,
    ITEM_ZYGARDE_CUBE = 698,
    ITEM_PRISON_BOTTLE = 699,
    ITEM_N_SOLARIZER = 700,
    ITEM_N_LUNARIZER = 701,
    ITEM_REINS_OF_UNITY = 702,

    // Battle Mechanic Key Items
    ITEM_MEGA_RING = 703,
    ITEM_Z_POWER_RING = 704,
    ITEM_DYNAMAX_BAND = 705,

    // Misc. Key Items
    ITEM_BICYCLE = 706,
    ITEM_MACH_BIKE = 707,
    ITEM_ACRO_BIKE = 708,
    ITEM_OLD_ROD = 709,
    ITEM_GOOD_ROD = 710,
    ITEM_SUPER_ROD = 711,
    ITEM_DOWSING_MACHINE = 712,
    ITEM_ITEMFINDER = ITEM_DOWSING_MACHINE, // Pre-Gen IV name
    ITEM_DOWSING_MCHN = ITEM_DOWSING_MACHINE, // Gen IV-V name
    ITEM_TOWN_MAP = 713,
    ITEM_VS_SEEKER = 714,
    ITEM_TM_CASE = 715,
    ITEM_BERRY_POUCH = 716,
    ITEM_POKEMON_BOX_LINK = 717,
    ITEM_POKEMON_BOX = ITEM_POKEMON_BOX_LINK, // Pre-Gen VIII name
    ITEM_COIN_CASE = 718,
    ITEM_POWDER_JAR = 719,
    ITEM_WAILMER_PAIL = 720,
    ITEM_POKE_RADAR = 721,
    ITEM_POKEBLOCK_CASE = 722,
    ITEM_SOOT_SACK = 723,
    ITEM_POKE_FLUTE = 724,
    ITEM_FAME_CHECKER = 725,
    ITEM_TEACHY_TV = 726,

    // Story Key Items
    ITEM_SS_TICKET = 727,
    ITEM_EON_TICKET = 728,
    ITEM_MYSTIC_TICKET = 729,
    ITEM_AURORA_TICKET = 730,
    ITEM_OLD_SEA_MAP = 731,
    ITEM_LETTER = 732,
    ITEM_DEVON_PARTS = 733,
    ITEM_DEVON_GOODS = ITEM_DEVON_PARTS, // Pre-Gen VI name
    ITEM_GO_GOGGLES = 734,
    ITEM_DEVON_SCOPE = 735,
    ITEM_BASEMENT_KEY = 736,
    ITEM_SCANNER = 737,
    ITEM_STORAGE_KEY = 738,
    ITEM_KEY_TO_ROOM_1 = 739,
    ITEM_RM_1_KEY = ITEM_KEY_TO_ROOM_1, // Pre-Gen VI name
    ITEM_KEY_TO_ROOM_2 = 740,
    ITEM_RM_2_KEY = ITEM_KEY_TO_ROOM_2, // Pre-Gen VI name
    ITEM_KEY_TO_ROOM_4 = 741,
    ITEM_RM_4_KEY = ITEM_KEY_TO_ROOM_4, // Pre-Gen VI name
    ITEM_KEY_TO_ROOM_6 = 742,
    ITEM_RM_6_KEY = ITEM_KEY_TO_ROOM_6, // Pre-Gen VI name
    ITEM_METEORITE = 743,
    ITEM_MAGMA_EMBLEM = 744,
    ITEM_CONTEST_PASS = 745,
    ITEM_PARCEL = 746,
    ITEM_OAKS_PARCEL = ITEM_PARCEL, // Pre-Gen IV name
    ITEM_SECRET_KEY = 747,
    ITEM_BIKE_VOUCHER = 748,
    ITEM_GOLD_TEETH = 749,
    ITEM_CARD_KEY = 750,
    ITEM_LIFT_KEY = 751,
    ITEM_SILPH_SCOPE = 752,
    ITEM_TRI_PASS = 753,
    ITEM_RAINBOW_PASS = 754,
    ITEM_TEA = 755,
    ITEM_RUBY = 756,
    ITEM_SAPPHIRE = 757,

    // GEN IX ITEMS
    ITEM_ABILITY_SHIELD = 758,
    ITEM_CLEAR_AMULET = 759,
    ITEM_PUNCHING_GLOVE = 760,
    ITEM_COVERT_CLOAK = 761,
    ITEM_LOADED_DICE = 762,
    ITEM_AUSPICIOUS_ARMOR = 763,
    ITEM_BOOSTER_ENERGY = 764,
    ITEM_BIG_BAMBOO_SHOOT = 765,
    ITEM_GIMMIGHOUL_COIN = 766,
    ITEM_LEADERS_CREST = 767,
    ITEM_MALICIOUS_ARMOR = 768,
    ITEM_MIRROR_HERB = 769,
    ITEM_SCROLL_OF_DARKNESS = 770,
    ITEM_SCROLL_OF_WATERS = 771,
    ITEM_TERA_ORB = 772,
    ITEM_TINY_BAMBOO_SHOOT = 773,

    ITEM_BUG_TERA_SHARD = 774,
    ITEM_DARK_TERA_SHARD = 775,
    ITEM_DRAGON_TERA_SHARD = 776,
    ITEM_ELECTRIC_TERA_SHARD = 777,
    ITEM_FAIRY_TERA_SHARD = 778,
    ITEM_FIGHTING_TERA_SHARD = 779,
    ITEM_FIRE_TERA_SHARD = 780,
    ITEM_FLYING_TERA_SHARD = 781,
    ITEM_GHOST_TERA_SHARD = 782,
    ITEM_GRASS_TERA_SHARD = 783,
    ITEM_GROUND_TERA_SHARD = 784,
    ITEM_ICE_TERA_SHARD = 785,
    ITEM_NORMAL_TERA_SHARD = 786,
    ITEM_POISON_TERA_SHARD = 787,
    ITEM_PSYCHIC_TERA_SHARD = 788,
    ITEM_ROCK_TERA_SHARD = 789,
    ITEM_STEEL_TERA_SHARD = 790,
    ITEM_WATER_TERA_SHARD = 791,

    ITEM_ADAMANT_CRYSTAL = 792,
    ITEM_GRISEOUS_CORE = 793,
    ITEM_LUSTROUS_GLOBE = 794,

    ITEM_BLACK_AUGURITE = 795,
    ITEM_LINKING_CORD = 796,
    ITEM_PEAT_BLOCK = 797,
    ITEM_BERSERK_GENE = 798,

    ITEM_FAIRY_FEATHER = 799,
    ITEM_SYRUPY_APPLE = 800,
    ITEM_UNREMARKABLE_TEACUP = 801,
    ITEM_MASTERPIECE_TEACUP = 802,
    ITEM_CORNERSTONE_MASK = 803,
    ITEM_WELLSPRING_MASK = 804,
    ITEM_HEARTHFLAME_MASK = 805,
    ITEM_HEALTH_MOCHI = 806,
    ITEM_MUSCLE_MOCHI = 807,
    ITEM_RESIST_MOCHI = 808,
    ITEM_GENIUS_MOCHI = 809,
    ITEM_CLEVER_MOCHI = 810,
    ITEM_SWIFT_MOCHI = 811,
    ITEM_FRESH_START_MOCHI = 812,
    ITEM_GLIMMERING_CHARM = 813,
    ITEM_METAL_ALLOY = 814,
    ITEM_STELLAR_TERA_SHARD = 815,

    ITEM_JUBILIFE_MUFFIN = 816,
    ITEM_REMEDY = 817,
    ITEM_FINE_REMEDY = 818,
    ITEM_SUPERB_REMEDY = 819,
    ITEM_AUX_EVASION = 820,
    ITEM_AUX_GUARD = 821,
    ITEM_AUX_POWER = 822,
    ITEM_AUX_POWERGUARD = 823,
    ITEM_CHOICE_DUMPLING = 824,
    ITEM_SWAP_SNACK = 825,
    ITEM_TWICE_SPICED_RADISH = 826,
    ITEM_POKESHI_DOLL = 827,

    ITEM_STRANGE_BALL = 828,

    // Legends Z-A Mega Stones
    ITEM_CLEFABLITE = 829,
    ITEM_VICTREEBELITE = 830,
    ITEM_STARMINITE = 831,
    ITEM_DRAGONINITE = 832,
    ITEM_MEGANIUMITE = 833,
    ITEM_FERALIGITE = 834,
    ITEM_SKARMORITE = 835,
    ITEM_FROSLASSITE = 836,
    ITEM_EMBOARITE = 837,
    ITEM_EXCADRITE = 838,
    ITEM_SCOLIPITE = 839,
    ITEM_SCRAFTINITE = 840,
    ITEM_EELEKTROSSITE = 841,
    ITEM_CHANDELURITE = 842,
    ITEM_CHESNAUGHTITE = 843,
    ITEM_DELPHOXITE = 844,
    ITEM_GRENINJITE = 845,
    ITEM_PYROARITE = 846,
    ITEM_FLOETTITE = 847,
    ITEM_MALAMARITE = 848,
    ITEM_BARBARACITE = 849,
    ITEM_DRAGALGITE = 850,
    ITEM_HAWLUCHANITE = 851,
    ITEM_ZYGARDITE = 852,
    ITEM_DRAMPANITE = 853,
    ITEM_FALINKSITE = 854,

    // Legends Z-A: Mega Dimension DLC Mega Stones
    ITEM_HEATRANITE = 855,
    ITEM_DARKRANITE = 856,
    ITEM_ZERAORITE = 857,
    ITEM_RAICHUNITE_X = 858,
    ITEM_RAICHUNITE_Y = 859,
    ITEM_CHIMECHITE = 860,
    ITEM_ABSOLITE_Z = 861,
    ITEM_STARAPTITE = 862,
    ITEM_GARCHOMPITE_Z = 863,
    ITEM_LUCARIONITE_Z = 864,
    ITEM_GOLURKITE = 865,
    ITEM_MEOWSTICITE = 866,
    ITEM_CRABOMINITE = 867,
    ITEM_GOLISOPITE = 868,
    ITEM_MAGEARNITE = 869,
    ITEM_SCOVILLAINITE = 870,
    ITEM_BAXCALIBRITE = 871,
    ITEM_TATSUGIRINITE = 872,
    ITEM_GLIMMORANITE = 873,

    ITEMS_COUNT,
    ITEM_FIELD_ARROW = ITEMS_COUNT,
};

// A special item id associated with "Cancel"/"Exit" etc. in a list of items or decorations
// Its icon is defined at ITEMS_COUNT as the "return to field" arrow
#define ITEM_LIST_END 0xFFFF

#if B_CONFUSE_BERRIES_HEAL >= GEN_8
    #define CONFUSE_BERRY_HEAL_FRACTION 3
#elif B_CONFUSE_BERRIES_HEAL == GEN_7
    #define CONFUSE_BERRY_HEAL_FRACTION 2
#else
    #define CONFUSE_BERRY_HEAL_FRACTION 8
#endif

#define CONFUSE_BERRY_HP_FRACTION ((B_CONFUSE_BERRIES_HEAL >= GEN_7) ? 4 : 2)

#define UNPACK_BERRY_ID(_berry) BERRY_ID_##_berry,

enum BerryId
{
    BERRY_ID_NONE,
    FOREACH_BERRY(UNPACK_BERRY_ID)
    BERRY_ID_ENGIMA_E_READER,
    NUM_BERRIES = BERRY_ID_ENGIMA_E_READER,
};

#undef UNPACK_BERRY_ID

#define ITEM_TO_MAIL(itemId) ((itemId) - FIRST_MAIL_INDEX)
#define MAIL_NONE 0xFF
#define ITEM_TO_MULCH(itemId)(((itemId) - ITEM_GROWTH_MULCH) + 1)

#define MAX_BAG_ITEM_CAPACITY         999
#define MAX_PC_ITEM_CAPACITY          999
#define MAX_PYRAMID_BAG_ITEM_CAPACITY  99 // Values higher than 255 require free SaveBlock2 space.

#define MAX_ITEM_DIGITS         ((MAX_BAG_ITEM_CAPACITY > 99) ? 3 : 2)
#define MAX_PYRAMID_ITEM_DIGITS ((MAX_PYRAMID_BAG_ITEM_CAPACITY > 99) ? 3 : 2)

// Secondary IDs for rods
#define OLD_ROD   0
#define GOOD_ROD  1
#define SUPER_ROD 2

// Secondary IDs for bikes
#define MACH_BIKE 0
#define ACRO_BIKE 1
#define STANDARD_BIKE 2

// Item parameters for EXP Candies
#define EXP_100   1
#define EXP_800   2
#define EXP_3000  3
#define EXP_10000 4
#define EXP_30000 5

// Item type IDs (used to determine the exit callback)
enum ItemType
{
    ITEM_USE_MAIL,
    ITEM_USE_PARTY_MENU,
    ITEM_USE_FIELD,
    ITEM_USE_PBLOCK_CASE,
    ITEM_USE_BAG_MENU, // No exit callback, stays in bag menu
    ITEM_USE_PARTY_MENU_MOVES,
    ITEM_USE_BATTLER, // Auto-select in Singles but lets you choose from party menu in Doubles
};

// Item battle script IDs (need to be non-zero)
enum EffectItem
{
    EFFECT_ITEM_ENIGMA_BERRY_EREADER = 1, // dummy constant
    EFFECT_ITEM_RESTORE_HP = 1, // needs to be non-zero
    EFFECT_ITEM_CURE_STATUS,
    EFFECT_ITEM_HEAL_AND_CURE_STATUS,
    EFFECT_ITEM_INCREASE_STAT,
    EFFECT_ITEM_SET_MIST,
    EFFECT_ITEM_SET_FOCUS_ENERGY,
    EFFECT_ITEM_ESCAPE,
    EFFECT_ITEM_THROW_BALL,
    EFFECT_ITEM_REVIVE,
    EFFECT_ITEM_RESTORE_PP,
    EFFECT_ITEM_INCREASE_ALL_STATS,
    EFFECT_ITEM_USE_POKE_FLUTE,
};

#endif  // GUARD_CONSTANTS_ITEMS_H
