#ifndef GUARD_CONSTANTS_ITEM_DATA_CONSTANTS_H
#define GUARD_CONSTANTS_ITEM_DATA_CONSTANTS_H


#define POCKET_ITEMS,      0x01
#define POCKET_POKE_BALLS, 0x02
#define POCKET_TM_HM,      0x03
#define POCKET_BERRIES,    0x04
#define POCKET_KEY_ITEMS,  0x05


#endif  // GUARD_CONSTANTS_ITEM_DATA_CONSTANTS_H
