#ifndef GUARD_CONSTANTS_MAP_TYPES_H
#define GUARD_CONSTANTS_MAP_TYPES_H

enum MapType
{
    MAP_TYPE_NONE,
    MAP_TYPE_TOWN,
    MAP_TYPE_CITY,
    MAP_TYPE_ROUTE,
    MAP_TYPE_UNDERGROUND,
    MAP_TYPE_UNDERWATER,
    MAP_TYPE_OCEAN_ROUTE,
    MAP_TYPE_UNKNOWN, // Not used by any map.
    MAP_TYPE_INDOOR,
    MAP_TYPE_SECRET_BASE,
};

enum MapBattleScene
{
    MAP_BATTLE_SCENE_NORMAL,
    MAP_BATTLE_SCENE_GYM,
    MAP_BATTLE_SCENE_MAGMA,
    MAP_BATTLE_SCENE_AQUA,
    MAP_BATTLE_SCENE_SIDNEY,
    MAP_BATTLE_SCENE_PHOEBE,
    MAP_BATTLE_SCENE_GLACIA,
    MAP_BATTLE_SCENE_DRAKE,
    MAP_BATTLE_SCENE_FRONTIER,
};

#define MAP_BATTLE_SCENE_INDOOR_1 MAP_BATTLE_SCENE_NORMAL
#define MAP_BATTLE_SCENE_INDOOR_2 MAP_BATTLE_SCENE_NORMAL
#define MAP_BATTLE_SCENE_LORELEI  MAP_BATTLE_SCENE_NORMAL
#define MAP_BATTLE_SCENE_BRUNO    MAP_BATTLE_SCENE_NORMAL
#define MAP_BATTLE_SCENE_AGATHA   MAP_BATTLE_SCENE_NORMAL
#define MAP_BATTLE_SCENE_LANCE    MAP_BATTLE_SCENE_NORMAL
#define MAP_BATTLE_SCENE_LINK     MAP_BATTLE_SCENE_NORMAL

#define FLOOR_ROOFTOP  127

#endif  // GUARD_CONSTANTS_MAP_TYPES_H
