#ifndef GUARD_CONSTANTS_MASS_OUTBREAK_H
#define GUARD_CONSTANTS_MASS_OUTBREAK_H

enum MassOutbreakIndex
{
    OUTBREAK_ID_ROUTE102,
    OUTBREAK_ID_ROUTE114,
    OUTBREAK_ID_ROUTE117,
    OUTBREAK_ID_ROUTE120,
    OUTBREAK_ID_ROUTE116,
    OUTBREAK_COUNT
};

enum MassOutbreakData
{
    OUTBREAK_DATA_SPECIES,
    OUTBREAK_DATA_MOVE1,
    OUTBREAK_DATA_MOVE2,
    OUTBREAK_DATA_MOVE3,
    OUTBREAK_DATA_MOVE4,
    OUTBREAK_DATA_LEVEL,
    OUTBREAK_DATA_PROBABILITY,
    OUTBREAK_DATA_DAYS_LEFT,
    OUTBREAK_DATA_MAP
};

#endif // GUARD_MASS_OUTBREAK_H

