#ifndef GUARD_CONSTANTS_MAUVILLE_OLD_MAN_H
#define GUARD_CONSTANTS_MAUVILLE_OLD_MAN_H

#define MAUVILLE_MAN_BARD           0
#define MAUVILLE_MAN_HIPSTER        1
#define MAUVILLE_MAN_TRADER         2
#define MAUVILLE_MAN_STORYTELLER    3
#define MAUVILLE_MAN_GIDDY          4
#define MAUVILLE_MAN_UNUSED1        5
#define MAUVILLE_MAN_UNUSED2        6

#endif // GUARD_CONSTANTS_MAUVILLE_OLD_MAN_H
