#ifndef GUARD_CONSTANTS_MEVENT_H
#define GUARD_CONSTANTS_MEVENT_H

// mevent2.c
#define GET_NUM_STAMPS   0
#define GET_MAX_STAMPS   1
#define GET_CARD_BATTLES_WON  2

#define GET_NUM_STAMPS_INTERNAL   3
#define GET_MAX_STAMPS_INTERNAL   4
#define GET_CARD_BATTLES_WON_INTERNAL  0

#define REQUIRED_CARD_BATTLES 3

#endif //GUARD_MEVENT_H
