#ifndef GUARD_CONSTANTS_PARTY_MENU_H
#define GUARD_CONSTANTS_PARTY_MENU_H

#define AILMENT_NONE  0
#define AILMENT_PSN   1
#define AILMENT_PRZ   2
#define AILMENT_SLP   3
#define AILMENT_FRZ   4
#define AILMENT_BRN   5
#define AILMENT_PKRS  6
#define AILMENT_FNT   7

#define PARTY_CHOOSE_MON        0
#define PARTY_MUST_CHOOSE_MON   1
#define PARTY_CANT_SWITCH       2
#define PARTY_USE_ITEM_ON       3
#define PARTY_ABILITY_PREVENTS  4
#define PARTY_GIVE_ITEM         5

#define TUTOR_MOVE_MEGA_PUNCH      0
#define TUTOR_MOVE_SWORDS_DANCE    1
#define TUTOR_MOVE_MEGA_KICK       2
#define TUTOR_MOVE_BODY_SLAM       3
#define TUTOR_MOVE_DOUBLE_EDGE     4
#define TUTOR_MOVE_COUNTER         5
#define TUTOR_MOVE_SEISMIC_TOSS    6
#define TUTOR_MOVE_MIMIC           7
#define TUTOR_MOVE_METRONOME       8
#define TUTOR_MOVE_SOFT_BOILED     9
#define TUTOR_MOVE_DREAM_EATER     10
#define TUTOR_MOVE_THUNDER_WAVE    11
#define TUTOR_MOVE_EXPLOSION       12
#define TUTOR_MOVE_ROCK_SLIDE      13
#define TUTOR_MOVE_SUBSTITUTE      14
#define TUTOR_MOVE_DYNAMIC_PUNCH   15
#define TUTOR_MOVE_ROLLOUT         16
#define TUTOR_MOVE_PSYCH_UP        17
#define TUTOR_MOVE_SNORE           18
#define TUTOR_MOVE_ICY_WIND        19
#define TUTOR_MOVE_ENDURE          20
#define TUTOR_MOVE_MUD_SLAP        21
#define TUTOR_MOVE_ICE_PUNCH       22
#define TUTOR_MOVE_SWAGGER         23
#define TUTOR_MOVE_SLEEP_TALK      24
#define TUTOR_MOVE_SWIFT           25
#define TUTOR_MOVE_DEFENSE_CURL    26
#define TUTOR_MOVE_THUNDER_PUNCH   27
#define TUTOR_MOVE_FIRE_PUNCH      28
#define TUTOR_MOVE_FURY_CUTTER     29
#define TUTOR_MOVE_COUNT           30

#endif // GUARD_CONSTANTS_PARTY_MENU_H
