#ifndef GUARD_CONSTANTS_POKEMON_SIZE_RECORD_H
#define GUARD_CONSTANTS_POKEMON_SIZE_RECORD_H

enum
{
    COMPARE_SIZE_NONE,
    COMPARE_SIZE_INCORRECT_SPECIES,
    COMPARE_SIZE_SMALLER,
    COMPARE_SIZE_LARGER,
};

#endif // GUARD_CONSTANTS_POKEMON_SIZE_RECORD_H
