#ifndef GUARD_CONSTANTS_POKEMON_DEBUG_H
#define GUARD_CONSTANTS_POKEMON_DEBUG_H

//Defines
#define DEBUG_MON_X 144 + 32
#define DEBUG_MON_Y 11 + 40
#define DEBUG_MON_BACK_X 62
#define DEBUG_MON_BACK_Y 80
#define DEBUG_ICON_X 19
#define DEBUG_ICON_Y 19
#define DEBUG_MON_SHINY 0
#define DEBUG_MON_NORMAL 9

#define MODIFY_DIGITS_MAX 4
#define MODIFY_DIGITS_ARROW_X 41
#define MODIFY_DIGITS_ARROW1_Y 12
#define MODIFY_DIGITS_ARROW2_Y 36

#define GENDER_MALE 0
#define GENDER_FEMALE 1
#define MON_PIC_BACK 0
#define MON_PIC_FRONT 1

//Windows
#define WIN_NAME_NUMBERS 0
#define WIN_INSTRUCTIONS 1
#define WIN_ANIM_INFORMATION_FRONT 2
#define WIN_ANIM_INFORMATION_BACK 3
#define WIN_END 4

//Battle backgrounds
#define MAP_BATTLE_SCENE_NORMAL       0
#define MAP_BATTLE_SCENE_GYM          1
#define MAP_BATTLE_SCENE_MAGMA        2
#define MAP_BATTLE_SCENE_AQUA         3
#define MAP_BATTLE_SCENE_SIDNEY       4
#define MAP_BATTLE_SCENE_PHOEBE       5
#define MAP_BATTLE_SCENE_GLACIA       6
#define MAP_BATTLE_SCENE_DRAKE        7
#define MAP_BATTLE_SCENE_FRONTIER     8
#define MAP_BATTLE_SCENE_LEADER       9
#define MAP_BATTLE_SCENE_WALLACE      10
#define MAP_BATTLE_SCENE_GROUDON      11
#define MAP_BATTLE_SCENE_KYOGRE       12
#define MAP_BATTLE_SCENE_RAYQUAZA     13

#endif // GUARD_CONSTANTS_POKEMON_DEBUG_H