#ifndef GUARD_CONSTANTS_POKEMON_SPRITE_VISUALIZER_H
#define GUARD_CONSTANTS_POKEMON_SPRITE_VISUALIZER_H

//Defines
#define VISUALIZER_MON_BACK_X 62
#define VISUALIZER_MON_BACK_Y 80
#define VISUALIZER_ICON_X 224
#define VISUALIZER_ICON_Y 144
#define VISUALIZER_FOLLOWER_X 176
#define VISUALIZER_FOLLOWER_Y 128

#define MODIFY_DIGITS_MAX 4
#define MODIFY_DIGITS_ARROW_X 129
#define MODIFY_DIGITS_ARROW1_Y 94
#define MODIFY_DIGITS_ARROW2_Y 113

#define OPTIONS_ARROW_1_X 4
#define OPTIONS_ARROW_2_X 236
#define OPTIONS_ARROW_Y 119

#define GENDER_MALE 0
#define GENDER_FEMALE 1
#define MON_PIC_BACK 0
#define MON_PIC_FRONT 1

//Sprite offset
#define MAX_Y_OFFSET 20

//Windows
#define WIN_NAME_NUMBERS 0
#define WIN_INSTRUCTIONS 1
#define WIN_BOTTOM_LEFT 2
#define WIN_BOTTOM_RIGHT 3
#define WIN_FOOTPRINT 4
#define WIN_END 5

//Background positions
#define BACKGROUND_1_CHAR_BASE  1
#define BACKGROUND_1_MAP_BASE  28
#define BACKGROUND_3_CHAR_BASE  2
#define BACKGROUND_3_MAP_BASE  26

//Submenus
#define SUBMENU_SPECIES          0
#define SUBMENU_ANIMS_BG         1
#define SUBMENU_SPRITE_COORDS    2
#define SUBMENU_SHADOW_COORDS    3
#define SUBMENU_MOVE_BACKGROUNDS 4

#endif // GUARD_CONSTANTS_POKEMON_SPRITE_VISUALIZER_H
