#ifndef GUARD_CONSTANTS_RANDOM_MON_GENERATION_H
#define GUARD_CONSTANTS_RANDOM_MON_GENERATION_H

enum
{
    SPECIES_GENERATOR_NO_SUPERMONS,
    SPECIES_GENERATOR_LIMITED_POOL,
    SPECIES_GENERATOR_BST_RESTRICTED,
    RANDOM_SPECIES_OPTIONS_COUNT,
};

enum
{
    ITEM_GENERATOR_STANDARD,
    ITEM_GENERATOR_LIMITED_POOL,
    RANDOM_ITEM_OPTIONS_COUNT,
};

#endif // GUARD_CONSTANTS_RANDOM_MON_GENERATION_H
