#ifndef GUARD_SCRIPT_MENU_CONSTANTS_H
#define GUARD_SCRIPT_MENU_CONSTANTS_H

#define MULTICHOICE(name) {name, ARRAY_COUNT(name)}

#define MAX_MULTICHOICE_WIDTH 28

#define MULTI_B_PRESSED  127

// Multichoice Ids
enum
{
    MULTI_BRINEY_ON_DEWFORD,
    MULTI_PC,                           // Exit only, populated by CreatePCMultichoice
    MULTI_ENTERINFO,
    MULTI_CONTEST_INFO,
    MULTI_CONTEST_TYPE,
    MULTI_BASE_PC_NO_REGISTRY,
    MULTI_BASE_PC_WITH_REGISTRY,
    MULTI_REGISTER_MENU,
    MULTI_SSTIDAL_LILYCOVE,             // Exit only, populated by CreateLilycoveSSTidalMultichoice
    MULTI_UNUSED_9,
    MULTI_UNUSED_10,
    MULTI_FRONTIER_PASS_INFO,
    MULTI_BIKE,
    MULTI_STATUS_INFO,
    MULTI_BRINEY_OFF_DEWFORD,
    MULTI_UNUSED_15,
    MULTI_VIEWED_PAINTINGS,
    MULTI_YESNOINFO,
    MULTI_BATTLE_MODE,
    MULTI_UNUSED_19,
    MULTI_YESNOINFO_2,
    MULTI_UNUSED_21,
    MULTI_UNUSED_22,
    MULTI_CHALLENGEINFO,
    MULTI_LEVEL_MODE,
    MULTI_MECHADOLL1_Q1,
    MULTI_MECHADOLL1_Q2,
    MULTI_MECHADOLL1_Q3,
    MULTI_MECHADOLL2_Q1,
    MULTI_MECHADOLL2_Q2,
    MULTI_MECHADOLL2_Q3,
    MULTI_MECHADOLL3_Q1,
    MULTI_MECHADOLL3_Q2,
    MULTI_MECHADOLL3_Q3,
    MULTI_MECHADOLL4_Q1,
    MULTI_MECHADOLL4_Q2,
    MULTI_MECHADOLL4_Q3,
    MULTI_MECHADOLL5_Q1,
    MULTI_MECHADOLL5_Q2,
    MULTI_MECHADOLL5_Q3,
    MULTI_UNUSED_40,
    MULTI_UNUSED_41,
    MULTI_VENDING_MACHINE,
    MULTI_MACH_BIKE_INFO,
    MULTI_ACRO_BIKE_INFO,
    MULTI_SATISFACTION,
    MULTI_STERN_DEEPSEA,
    MULTI_UNUSED_ASH_VENDOR,            // Replaced by scrollable multichoice
    MULTI_GAME_CORNER_DOLLS,
    MULTI_GAME_CORNER_COINS,
    MULTI_HOWS_FISHING,
    MULTI_UNUSED_51,
    MULTI_SSTIDAL_SLATEPORT_WITH_BF,
    MULTI_SSTIDAL_BATTLE_FRONTIER,
    MULTI_RIGHTLEFT,
    MULTI_GAME_CORNER_TMS,
    MULTI_SSTIDAL_SLATEPORT_NO_BF,
    MULTI_FLOORS,
    MULTI_SHARDS_R,
    MULTI_SHARDS_Y,
    MULTI_SHARDS_RY,
    MULTI_SHARDS_B,
    MULTI_SHARDS_RB,
    MULTI_SHARDS_YB,
    MULTI_SHARDS_RYB,
    MULTI_SHARDS_G,
    MULTI_SHARDS_RG,
    MULTI_SHARDS_YG,
    MULTI_SHARDS_RYG,
    MULTI_SHARDS_BG,
    MULTI_SHARDS_RBG,
    MULTI_SHARDS_YBG,
    MULTI_SHARDS_RYBG,
    MULTI_TOURNEY_WITH_RECORD,
    MULTI_CABLE_CLUB_NO_RECORD_MIX,
    MULTI_WIRELESS_NO_RECORD_BERRY,
    MULTI_CABLE_CLUB_WITH_RECORD_MIX,
    MULTI_WIRELESS_NO_BERRY,
    MULTI_WIRELESS_NO_RECORD,
    MULTI_WIRELESS_ALL_SERVICES,
    MULTI_WIRELESS_MINIGAME,
    MULTI_LINK_LEADER,
    MULTI_CONTEST_RANK,
    MULTI_FRONTIER_ITEM_CHOOSE,
    MULTI_LINK_CONTEST_INFO,
    MULTI_LINK_CONTEST_MODE,
    MULTI_FORCED_START_MENU,
    MULTI_FRONTIER_GAMBLER_BET,
    MULTI_TENT,
    MULTI_UNUSED_SSTIDAL_1,             // These 4 were replaced by CreateLilycoveSSTidalMultichoice
    MULTI_UNUSED_SSTIDAL_2,
    MULTI_UNUSED_SSTIDAL_3,
    MULTI_UNUSED_SSTIDAL_4,
    MULTI_FOSSIL,
    MULTI_YESNO,
    MULTI_FRONTIER_RULES,
    MULTI_BATTLE_ARENA_RULES,
    MULTI_BATTLE_TOWER_RULES,
    MULTI_BATTLE_DOME_RULES,
    MULTI_BATTLE_FACTORY_RULES,
    MULTI_BATTLE_PALACE_RULES,
    MULTI_BATTLE_PYRAMID_RULES,
    MULTI_BATTLE_PIKE_RULES,
    MULTI_GO_ON_RECORD_REST_RETIRE,
    MULTI_GO_ON_REST_RETIRE,
    MULTI_GO_ON_RECORD_RETIRE,
    MULTI_GO_ON_RETIRE,
    MULTI_TOURNEY_NO_RECORD,
    MULTI_TV_LATI,
    MULTI_BATTLE_TOWER_FEELINGS,
    MULTI_WHERES_RAYQUAZA,
    MULTI_SLATEPORT_TENT_RULES,
    MULTI_FALLARBOR_TENT_RULES,
    MULTI_TAG_MATCH_TYPE,
    MULTI_BERRY_PLOT,
    MULTI_BIKE_SHOP,
    MULTI_EEVEELUTIONS,
    MULTI_ISLAND_23,
    MULTI_ISLAND_13,
    MULTI_ISLAND_12,
    MULTI_SEVII_NAVEL,
    MULTI_SEVII_BIRTH,
    MULTI_SEVII_NAVEL_BIRTH,
    MULTI_SEAGALLOP_123,
    MULTI_SEAGALLOP_V23,
    MULTI_SEAGALLOP_V13,
    MULTI_SEAGALLOP_V12,
    MULTI_SEAGALLOP_VERMILION,
    MULTI_GAME_CORNER_POKEMON_PRIZES,
    MULTI_GAME_CORNER_TMPRIZES,
    MULTI_GAME_CORNER_BATTLE_ITEM_PRIZES,
    MULTI_DEPT_STORE_ELEVATOR,
    MULTI_GAME_CORNER_COIN_PURCHASE_COUNTER,
    MULTI_LINKED_DIRECT_UNION,
    MULTI_CELADON_VENDING_MACHINE,
    MULTI_THIRSTY_GIRL_FRESH_WATER,
    MULTI_THIRSTY_GIRL_SODA_POP,
    MULTI_THIRSTY_GIRL_FRESH_WATER_SODA_POP,
    MULTI_THIRSTY_GIRL_LEMONADE,
    MULTI_THIRSTY_GIRL_FRESH_WATER_LEMONADE,
    MULTI_THIRSTY_GIRL_SODA_POP_LEMONADE,
    MULTI_THIRSTY_GIRL_FRESH_WATER_SODA_POP_LEMONADE,
    MULTI_ROCKET_HIDEOUT_ELEVATOR,
    MULTI_HELIX,
    MULTI_DOME,
    MULTI_AMBER,
    MULTI_HELIX_AMBER,
    MULTI_DOME_AMBER,
    MULTI_MUSHROOMS,
    MULTI_ROOFTOP_B1F,
    MULTI_TRAINER_TOWER_MODE,
    MULTI_TRAINER_CARD_ICON_TINT,
    MULTI_HOF_QUIT,
    MULTI_EGGS_QUIT,
    MULTI_VICTORIES_QUIT,
    MULTI_HOF_EGGS_QUIT,
    MULTI_HOF_VICTORIES_QUIT,
    MULTI_EGGS_VICTORIES_QUIT,
    MULTI_HOF_EGGS_VICTORIES_QUIT,
};

#define MULTI_NONE 255

// Lilycove SS Tidal Multichoice Selections
#define SSTIDAL_SELECTION_SLATEPORT        0
#define SSTIDAL_SELECTION_BATTLE_FRONTIER  1
#define SSTIDAL_SELECTION_SOUTHERN_ISLAND  2
#define SSTIDAL_SELECTION_NAVEL_ROCK       3
#define SSTIDAL_SELECTION_BIRTH_ISLAND     4
#define SSTIDAL_SELECTION_FARAWAY_ISLAND   5
#define SSTIDAL_SELECTION_EXIT             6
#define SSTIDAL_SELECTION_COUNT            7

// Std String Ids
#define STDSTRING_COOL             0
#define STDSTRING_BEAUTY           1
#define STDSTRING_CUTE             2
#define STDSTRING_SMART            3
#define STDSTRING_TOUGH            4
#define STDSTRING_NORMAL           5
#define STDSTRING_SUPER            6
#define STDSTRING_HYPER            7
#define STDSTRING_MASTER           8
#define STDSTRING_COOL2            9
#define STDSTRING_BEAUTY2          10
#define STDSTRING_CUTE2            11
#define STDSTRING_SMART2           12
#define STDSTRING_TOUGH2           13
#define STDSTRING_ITEMS            14
#define STDSTRING_KEYITEMS         15
#define STDSTRING_POKEBALLS        16
#define STDSTRING_TMHMS            17
#define STDSTRING_BERRIES          18
#define STDSTRING_SINGLE           19
#define STDSTRING_DOUBLE           20
#define STDSTRING_MULTI            21
#define STDSTRING_MULTI_LINK       22
#define STDSTRING_BATTLE_TOWER     23
#define STDSTRING_BATTLE_DOME      24
#define STDSTRING_BATTLE_FACTORY   25
#define STDSTRING_BATTLE_PALACE    26
#define STDSTRING_BATTLE_ARENA     27
#define STDSTRING_BATTLE_PIKE      28
#define STDSTRING_BATTLE_PYRAMID   29
#define STDSTRING_BOULDER_BADGE    30
#define STDSTRING_CASCADE_BADGE    31
#define STDSTRING_THUNDER_BADGE    32
#define STDSTRING_RAINBOW_BADGE    33
#define STDSTRING_SOUL_BADGE       34
#define STDSTRING_MARSH_BADGE      35
#define STDSTRING_VOLCANO_BADGE    36
#define STDSTRING_EARTH_BADGE      37
#define STDSTRING_COINS            38

// Dynamic Multichoice Callbacks

enum 
{
    DYN_MULTICHOICE_CB_DEBUG,
    DYN_MULTICHOICE_CB_SHOW_ITEM,
    DYN_MULTICHOICE_CB_SHOW_PKMN,
    //add new callback choices after this comment!
    
    DYN_MULTICHOICE_CB_NONE,
};


#endif //GUARD_SCRIPT_MENU_CONSTANTS_H
