#ifndef GUARD_CONSTANTS_SEAGALLOP_H
#define GUARD_CONSTANTS_SEAGALLOP_H

#define SEAGALLOP_VERMILION_CITY   0
#define SEAGALLOP_ONE_ISLAND       1
#define SEAGALLOP_TWO_ISLAND       2
#define SEAGALLOP_THREE_ISLAND     3
#define SEAGALLOP_FOUR_ISLAND      4
#define SEAGALLOP_FIVE_ISLAND      5
#define SEAGALLOP_SIX_ISLAND       6
#define SEAGALLOP_SEVEN_ISLAND     7
#define SEAGALLOP_CINNABAR_ISLAND  8
#define SEAGALLOP_NAVEL_ROCK       9
#define SEAGALLOP_BIRTH_ISLAND    10

#define SEAGALLOP_MORE           254

#endif //GUARD_CONSTANTS_SEAGALLOP_H
