#ifndef GUARD_CONSTANTS_SLOT_MACHINE_H
#define GUARD_CONSTANTS_SLOT_MACHINE_H

#define SLOT_MACHINE_COUNT 12

// Slot machine IDs
#define SLOT_MACHINE_UNLUCKIEST 0
#define SLOT_MACHINE_UNLUCKIER  1
#define SLOT_MACHINE_UNLUCKY    2
#define SLOT_MACHINE_LUCKY      3
#define SLOT_MACHINE_LUCKIER    4
#define SLOT_MACHINE_LUCKIEST   5
#define NUM_SLOT_MACHINE_IDS    6

#endif // GUARD_CONSTANTS_SLOT_MACHINE_H
