#ifndef GUARD_CONSTANTS_SPECIES_H
#define GUARD_CONSTANTS_SPECIES_H

#include "constants/pokemon_config.h"

#define SPECIES_NONE 0
#define SPECIES_BULBASAUR 1
#define SPECIES_IVYSAUR 2
#define SPECIES_VENUSAUR 3
#define SPECIES_CHARMANDER 4
#define SPECIES_CHARMELEON 5
#define SPECIES_CHARIZARD 6
#define SPECIES_SQUIRTLE 7
#define SPECIES_WARTORTLE 8
#define SPECIES_BLASTOISE 9
#define SPECIES_CATERPIE 10
#define SPECIES_METAPOD 11
#define SPECIES_BUTTERFREE 12
#define SPECIES_WEEDLE 13
#define SPECIES_KAKUNA 14
#define SPECIES_BEEDRILL 15
#define SPECIES_PIDGEY 16
#define SPECIES_PIDGEOTTO 17
#define SPECIES_PIDGEOT 18
#define SPECIES_RATTATA 19
#define SPECIES_RATICATE 20
#define SPECIES_SPEAROW 21
#define SPECIES_FEAROW 22
#define SPECIES_EKANS 23
#define SPECIES_ARBOK 24
#define SPECIES_PIKACHU 25
#define SPECIES_RAICHU 26
#define SPECIES_SANDSHREW 27
#define SPECIES_SANDSLASH 28
#define SPECIES_NIDORAN_F 29
#define SPECIES_NIDORINA 30
#define SPECIES_NIDOQUEEN 31
#define SPECIES_NIDORAN_M 32
#define SPECIES_NIDORINO 33
#define SPECIES_NIDOKING 34
#define SPECIES_CLEFAIRY 35
#define SPECIES_CLEFABLE 36
#define SPECIES_VULPIX 37
#define SPECIES_NINETALES 38
#define SPECIES_JIGGLYPUFF 39
#define SPECIES_WIGGLYTUFF 40
#define SPECIES_ZUBAT 41
#define SPECIES_GOLBAT 42
#define SPECIES_ODDISH 43
#define SPECIES_GLOOM 44
#define SPECIES_VILEPLUME 45
#define SPECIES_PARAS 46
#define SPECIES_PARASECT 47
#define SPECIES_VENONAT 48
#define SPECIES_VENOMOTH 49
#define SPECIES_DIGLETT 50
#define SPECIES_DUGTRIO 51
#define SPECIES_MEOWTH 52
#define SPECIES_PERSIAN 53
#define SPECIES_PSYDUCK 54
#define SPECIES_GOLDUCK 55
#define SPECIES_MANKEY 56
#define SPECIES_PRIMEAPE 57
#define SPECIES_GROWLITHE 58
#define SPECIES_ARCANINE 59
#define SPECIES_POLIWAG 60
#define SPECIES_POLIWHIRL 61
#define SPECIES_POLIWRATH 62
#define SPECIES_ABRA 63
#define SPECIES_KADABRA 64
#define SPECIES_ALAKAZAM 65
#define SPECIES_MACHOP 66
#define SPECIES_MACHOKE 67
#define SPECIES_MACHAMP 68
#define SPECIES_BELLSPROUT 69
#define SPECIES_WEEPINBELL 70
#define SPECIES_VICTREEBEL 71
#define SPECIES_TENTACOOL 72
#define SPECIES_TENTACRUEL 73
#define SPECIES_GEODUDE 74
#define SPECIES_GRAVELER 75
#define SPECIES_GOLEM 76
#define SPECIES_PONYTA 77
#define SPECIES_RAPIDASH 78
#define SPECIES_SLOWPOKE 79
#define SPECIES_SLOWBRO 80
#define SPECIES_MAGNEMITE 81
#define SPECIES_MAGNETON 82
#define SPECIES_FARFETCHD 83
#define SPECIES_DODUO 84
#define SPECIES_DODRIO 85
#define SPECIES_SEEL 86
#define SPECIES_DEWGONG 87
#define SPECIES_GRIMER 88
#define SPECIES_MUK 89
#define SPECIES_SHELLDER 90
#define SPECIES_CLOYSTER 91
#define SPECIES_GASTLY 92
#define SPECIES_HAUNTER 93
#define SPECIES_GENGAR 94
#define SPECIES_ONIX 95
#define SPECIES_DROWZEE 96
#define SPECIES_HYPNO 97
#define SPECIES_KRABBY 98
#define SPECIES_KINGLER 99
#define SPECIES_VOLTORB 100
#define SPECIES_ELECTRODE 101
#define SPECIES_EXEGGCUTE 102
#define SPECIES_EXEGGUTOR 103
#define SPECIES_CUBONE 104
#define SPECIES_MAROWAK 105
#define SPECIES_HITMONLEE 106
#define SPECIES_HITMONCHAN 107
#define SPECIES_LICKITUNG 108
#define SPECIES_KOFFING 109
#define SPECIES_WEEZING 110
#define SPECIES_RHYHORN 111
#define SPECIES_RHYDON 112
#define SPECIES_CHANSEY 113
#define SPECIES_TANGELA 114
#define SPECIES_KANGASKHAN 115
#define SPECIES_HORSEA 116
#define SPECIES_SEADRA 117
#define SPECIES_GOLDEEN 118
#define SPECIES_SEAKING 119
#define SPECIES_STARYU 120
#define SPECIES_STARMIE 121
#define SPECIES_MR_MIME 122
#define SPECIES_SCYTHER 123
#define SPECIES_JYNX 124
#define SPECIES_ELECTABUZZ 125
#define SPECIES_MAGMAR 126
#define SPECIES_PINSIR 127
#define SPECIES_TAUROS 128
#define SPECIES_MAGIKARP 129
#define SPECIES_GYARADOS 130
#define SPECIES_LAPRAS 131
#define SPECIES_DITTO 132
#define SPECIES_EEVEE 133
#define SPECIES_VAPOREON 134
#define SPECIES_JOLTEON 135
#define SPECIES_FLAREON 136
#define SPECIES_PORYGON 137
#define SPECIES_OMANYTE 138
#define SPECIES_OMASTAR 139
#define SPECIES_KABUTO 140
#define SPECIES_KABUTOPS 141
#define SPECIES_AERODACTYL 142
#define SPECIES_SNORLAX 143
#define SPECIES_ARTICUNO 144
#define SPECIES_ZAPDOS 145
#define SPECIES_MOLTRES 146
#define SPECIES_DRATINI 147
#define SPECIES_DRAGONAIR 148
#define SPECIES_DRAGONITE 149
#define SPECIES_MEWTWO 150
#define SPECIES_MEW 151
#define SPECIES_CHIKORITA 152
#define SPECIES_BAYLEEF 153
#define SPECIES_MEGANIUM 154
#define SPECIES_CYNDAQUIL 155
#define SPECIES_QUILAVA 156
#define SPECIES_TYPHLOSION 157
#define SPECIES_TOTODILE 158
#define SPECIES_CROCONAW 159
#define SPECIES_FERALIGATR 160
#define SPECIES_SENTRET 161
#define SPECIES_FURRET 162
#define SPECIES_HOOTHOOT 163
#define SPECIES_NOCTOWL 164
#define SPECIES_LEDYBA 165
#define SPECIES_LEDIAN 166
#define SPECIES_SPINARAK 167
#define SPECIES_ARIADOS 168
#define SPECIES_CROBAT 169
#define SPECIES_CHINCHOU 170
#define SPECIES_LANTURN 171
#define SPECIES_PICHU 172
#define SPECIES_CLEFFA 173
#define SPECIES_IGGLYBUFF 174
#define SPECIES_TOGEPI 175
#define SPECIES_TOGETIC 176
#define SPECIES_NATU 177
#define SPECIES_XATU 178
#define SPECIES_MAREEP 179
#define SPECIES_FLAAFFY 180
#define SPECIES_AMPHAROS 181
#define SPECIES_BELLOSSOM 182
#define SPECIES_MARILL 183
#define SPECIES_AZUMARILL 184
#define SPECIES_SUDOWOODO 185
#define SPECIES_POLITOED 186
#define SPECIES_HOPPIP 187
#define SPECIES_SKIPLOOM 188
#define SPECIES_JUMPLUFF 189
#define SPECIES_AIPOM 190
#define SPECIES_SUNKERN 191
#define SPECIES_SUNFLORA 192
#define SPECIES_YANMA 193
#define SPECIES_WOOPER 194
#define SPECIES_QUAGSIRE 195
#define SPECIES_ESPEON 196
#define SPECIES_UMBREON 197
#define SPECIES_MURKROW 198
#define SPECIES_SLOWKING 199
#define SPECIES_MISDREAVUS 200
#define SPECIES_UNOWN 201
#define SPECIES_WOBBUFFET 202
#define SPECIES_GIRAFARIG 203
#define SPECIES_PINECO 204
#define SPECIES_FORRETRESS 205
#define SPECIES_DUNSPARCE 206
#define SPECIES_GLIGAR 207
#define SPECIES_STEELIX 208
#define SPECIES_SNUBBULL 209
#define SPECIES_GRANBULL 210
#define SPECIES_QWILFISH 211
#define SPECIES_SCIZOR 212
#define SPECIES_SHUCKLE 213
#define SPECIES_HERACROSS 214
#define SPECIES_SNEASEL 215
#define SPECIES_TEDDIURSA 216
#define SPECIES_URSARING 217
#define SPECIES_SLUGMA 218
#define SPECIES_MAGCARGO 219
#define SPECIES_SWINUB 220
#define SPECIES_PILOSWINE 221
#define SPECIES_CORSOLA 222
#define SPECIES_REMORAID 223
#define SPECIES_OCTILLERY 224
#define SPECIES_DELIBIRD 225
#define SPECIES_MANTINE 226
#define SPECIES_SKARMORY 227
#define SPECIES_HOUNDOUR 228
#define SPECIES_HOUNDOOM 229
#define SPECIES_KINGDRA 230
#define SPECIES_PHANPY 231
#define SPECIES_DONPHAN 232
#define SPECIES_PORYGON2 233
#define SPECIES_STANTLER 234
#define SPECIES_SMEARGLE 235
#define SPECIES_TYROGUE 236
#define SPECIES_HITMONTOP 237
#define SPECIES_SMOOCHUM 238
#define SPECIES_ELEKID 239
#define SPECIES_MAGBY 240
#define SPECIES_MILTANK 241
#define SPECIES_BLISSEY 242
#define SPECIES_RAIKOU 243
#define SPECIES_ENTEI 244
#define SPECIES_SUICUNE 245
#define SPECIES_LARVITAR 246
#define SPECIES_PUPITAR 247
#define SPECIES_TYRANITAR 248
#define SPECIES_LUGIA 249
#define SPECIES_HO_OH 250
#define SPECIES_CELEBI 251
#define SPECIES_TREECKO 252
#define SPECIES_GROVYLE 253
#define SPECIES_SCEPTILE 254
#define SPECIES_TORCHIC 255
#define SPECIES_COMBUSKEN 256
#define SPECIES_BLAZIKEN 257
#define SPECIES_MUDKIP 258
#define SPECIES_MARSHTOMP 259
#define SPECIES_SWAMPERT 260
#define SPECIES_POOCHYENA 261
#define SPECIES_MIGHTYENA 262
#define SPECIES_ZIGZAGOON 263
#define SPECIES_LINOONE 264
#define SPECIES_WURMPLE 265
#define SPECIES_SILCOON 266
#define SPECIES_BEAUTIFLY 267
#define SPECIES_CASCOON 268
#define SPECIES_DUSTOX 269
#define SPECIES_LOTAD 270
#define SPECIES_LOMBRE 271
#define SPECIES_LUDICOLO 272
#define SPECIES_SEEDOT 273
#define SPECIES_NUZLEAF 274
#define SPECIES_SHIFTRY 275
#define SPECIES_TAILLOW 276
#define SPECIES_SWELLOW 277
#define SPECIES_WINGULL 278
#define SPECIES_PELIPPER 279
#define SPECIES_RALTS 280
#define SPECIES_KIRLIA 281
#define SPECIES_GARDEVOIR 282
#define SPECIES_SURSKIT 283
#define SPECIES_MASQUERAIN 284
#define SPECIES_SHROOMISH 285
#define SPECIES_BRELOOM 286
#define SPECIES_SLAKOTH 287
#define SPECIES_VIGOROTH 288
#define SPECIES_SLAKING 289
#define SPECIES_NINCADA 290
#define SPECIES_NINJASK 291
#define SPECIES_SHEDINJA 292
#define SPECIES_WHISMUR 293
#define SPECIES_LOUDRED 294
#define SPECIES_EXPLOUD 295
#define SPECIES_MAKUHITA 296
#define SPECIES_HARIYAMA 297
#define SPECIES_AZURILL 298
#define SPECIES_NOSEPASS 299
#define SPECIES_SKITTY 300
#define SPECIES_DELCATTY 301
#define SPECIES_SABLEYE 302
#define SPECIES_MAWILE 303
#define SPECIES_ARON 304
#define SPECIES_LAIRON 305
#define SPECIES_AGGRON 306
#define SPECIES_MEDITITE 307
#define SPECIES_MEDICHAM 308
#define SPECIES_ELECTRIKE 309
#define SPECIES_MANECTRIC 310
#define SPECIES_PLUSLE 311
#define SPECIES_MINUN 312
#define SPECIES_VOLBEAT 313
#define SPECIES_ILLUMISE 314
#define SPECIES_ROSELIA 315
#define SPECIES_GULPIN 316
#define SPECIES_SWALOT 317
#define SPECIES_CARVANHA 318
#define SPECIES_SHARPEDO 319
#define SPECIES_WAILMER 320
#define SPECIES_WAILORD 321
#define SPECIES_NUMEL 322
#define SPECIES_CAMERUPT 323
#define SPECIES_TORKOAL 324
#define SPECIES_SPOINK 325
#define SPECIES_GRUMPIG 326
#define SPECIES_SPINDA 327
#define SPECIES_TRAPINCH 328
#define SPECIES_VIBRAVA 329
#define SPECIES_FLYGON 330
#define SPECIES_CACNEA 331
#define SPECIES_CACTURNE 332
#define SPECIES_SWABLU 333
#define SPECIES_ALTARIA 334
#define SPECIES_ZANGOOSE 335
#define SPECIES_SEVIPER 336
#define SPECIES_LUNATONE 337
#define SPECIES_SOLROCK 338
#define SPECIES_BARBOACH 339
#define SPECIES_WHISCASH 340
#define SPECIES_CORPHISH 341
#define SPECIES_CRAWDAUNT 342
#define SPECIES_BALTOY 343
#define SPECIES_CLAYDOL 344
#define SPECIES_LILEEP 345
#define SPECIES_CRADILY 346
#define SPECIES_ANORITH 347
#define SPECIES_ARMALDO 348
#define SPECIES_FEEBAS 349
#define SPECIES_MILOTIC 350
#define SPECIES_CASTFORM 351
#define SPECIES_KECLEON 352
#define SPECIES_SHUPPET 353
#define SPECIES_BANETTE 354
#define SPECIES_DUSKULL 355
#define SPECIES_DUSCLOPS 356
#define SPECIES_TROPIUS 357
#define SPECIES_CHIMECHO 358
#define SPECIES_ABSOL 359
#define SPECIES_WYNAUT 360
#define SPECIES_SNORUNT 361
#define SPECIES_GLALIE 362
#define SPECIES_SPHEAL 363
#define SPECIES_SEALEO 364
#define SPECIES_WALREIN 365
#define SPECIES_CLAMPERL 366
#define SPECIES_HUNTAIL 367
#define SPECIES_GOREBYSS 368
#define SPECIES_RELICANTH 369
#define SPECIES_LUVDISC 370
#define SPECIES_BAGON 371
#define SPECIES_SHELGON 372
#define SPECIES_SALAMENCE 373
#define SPECIES_BELDUM 374
#define SPECIES_METANG 375
#define SPECIES_METAGROSS 376
#define SPECIES_REGIROCK 377
#define SPECIES_REGICE 378
#define SPECIES_REGISTEEL 379
#define SPECIES_LATIAS 380
#define SPECIES_LATIOS 381
#define SPECIES_KYOGRE 382
#define SPECIES_GROUDON 383
#define SPECIES_RAYQUAZA 384
#define SPECIES_JIRACHI 385
#define SPECIES_DEOXYS 386
#define SPECIES_TURTWIG 387
#define SPECIES_GROTLE 388
#define SPECIES_TORTERRA 389
#define SPECIES_CHIMCHAR 390
#define SPECIES_MONFERNO 391
#define SPECIES_INFERNAPE 392
#define SPECIES_PIPLUP 393
#define SPECIES_PRINPLUP 394
#define SPECIES_EMPOLEON 395
#define SPECIES_STARLY 396
#define SPECIES_STARAVIA 397
#define SPECIES_STARAPTOR 398
#define SPECIES_BIDOOF 399
#define SPECIES_BIBAREL 400
#define SPECIES_KRICKETOT 401
#define SPECIES_KRICKETUNE 402
#define SPECIES_SHINX 403
#define SPECIES_LUXIO 404
#define SPECIES_LUXRAY 405
#define SPECIES_BUDEW 406
#define SPECIES_ROSERADE 407
#define SPECIES_CRANIDOS 408
#define SPECIES_RAMPARDOS 409
#define SPECIES_SHIELDON 410
#define SPECIES_BASTIODON 411
#define SPECIES_BURMY 412
#define SPECIES_WORMADAM 413
#define SPECIES_MOTHIM 414
#define SPECIES_COMBEE 415
#define SPECIES_VESPIQUEN 416
#define SPECIES_PACHIRISU 417
#define SPECIES_BUIZEL 418
#define SPECIES_FLOATZEL 419
#define SPECIES_CHERUBI 420
#define SPECIES_CHERRIM 421
#define SPECIES_SHELLOS 422
#define SPECIES_GASTRODON 423
#define SPECIES_AMBIPOM 424
#define SPECIES_DRIFLOON 425
#define SPECIES_DRIFBLIM 426
#define SPECIES_BUNEARY 427
#define SPECIES_LOPUNNY 428
#define SPECIES_MISMAGIUS 429
#define SPECIES_HONCHKROW 430
#define SPECIES_GLAMEOW 431
#define SPECIES_PURUGLY 432
#define SPECIES_CHINGLING 433
#define SPECIES_STUNKY 434
#define SPECIES_SKUNTANK 435
#define SPECIES_BRONZOR 436
#define SPECIES_BRONZONG 437
#define SPECIES_BONSLY 438
#define SPECIES_MIME_JR 439
#define SPECIES_HAPPINY 440
#define SPECIES_CHATOT 441
#define SPECIES_SPIRITOMB 442
#define SPECIES_GIBLE 443
#define SPECIES_GABITE 444
#define SPECIES_GARCHOMP 445
#define SPECIES_MUNCHLAX 446
#define SPECIES_RIOLU 447
#define SPECIES_LUCARIO 448
#define SPECIES_HIPPOPOTAS 449
#define SPECIES_HIPPOWDON 450
#define SPECIES_SKORUPI 451
#define SPECIES_DRAPION 452
#define SPECIES_CROAGUNK 453
#define SPECIES_TOXICROAK 454
#define SPECIES_CARNIVINE 455
#define SPECIES_FINNEON 456
#define SPECIES_LUMINEON 457
#define SPECIES_MANTYKE 458
#define SPECIES_SNOVER 459
#define SPECIES_ABOMASNOW 460
#define SPECIES_WEAVILE 461
#define SPECIES_MAGNEZONE 462
#define SPECIES_LICKILICKY 463
#define SPECIES_RHYPERIOR 464
#define SPECIES_TANGROWTH 465
#define SPECIES_ELECTIVIRE 466
#define SPECIES_MAGMORTAR 467
#define SPECIES_TOGEKISS 468
#define SPECIES_YANMEGA 469
#define SPECIES_LEAFEON 470
#define SPECIES_GLACEON 471
#define SPECIES_GLISCOR 472
#define SPECIES_MAMOSWINE 473
#define SPECIES_PORYGON_Z 474
#define SPECIES_GALLADE 475
#define SPECIES_PROBOPASS 476
#define SPECIES_DUSKNOIR 477
#define SPECIES_FROSLASS 478
#define SPECIES_ROTOM 479
#define SPECIES_UXIE 480
#define SPECIES_MESPRIT 481
#define SPECIES_AZELF 482
#define SPECIES_DIALGA 483
#define SPECIES_PALKIA 484
#define SPECIES_HEATRAN 485
#define SPECIES_REGIGIGAS 486
#define SPECIES_GIRATINA 487
#define SPECIES_CRESSELIA 488
#define SPECIES_PHIONE 489
#define SPECIES_MANAPHY 490
#define SPECIES_DARKRAI 491
#define SPECIES_SHAYMIN 492
#define SPECIES_ARCEUS 493
#define SPECIES_VICTINI 494
#define SPECIES_SNIVY 495
#define SPECIES_SERVINE 496
#define SPECIES_SERPERIOR 497
#define SPECIES_TEPIG 498
#define SPECIES_PIGNITE 499
#define SPECIES_EMBOAR 500
#define SPECIES_OSHAWOTT 501
#define SPECIES_DEWOTT 502
#define SPECIES_SAMUROTT 503
#define SPECIES_PATRAT 504
#define SPECIES_WATCHOG 505
#define SPECIES_LILLIPUP 506
#define SPECIES_HERDIER 507
#define SPECIES_STOUTLAND 508
#define SPECIES_PURRLOIN 509
#define SPECIES_LIEPARD 510
#define SPECIES_PANSAGE 511
#define SPECIES_SIMISAGE 512
#define SPECIES_PANSEAR 513
#define SPECIES_SIMISEAR 514
#define SPECIES_PANPOUR 515
#define SPECIES_SIMIPOUR 516
#define SPECIES_MUNNA 517
#define SPECIES_MUSHARNA 518
#define SPECIES_PIDOVE 519
#define SPECIES_TRANQUILL 520
#define SPECIES_UNFEZANT 521
#define SPECIES_BLITZLE 522
#define SPECIES_ZEBSTRIKA 523
#define SPECIES_ROGGENROLA 524
#define SPECIES_BOLDORE 525
#define SPECIES_GIGALITH 526
#define SPECIES_WOOBAT 527
#define SPECIES_SWOOBAT 528
#define SPECIES_DRILBUR 529
#define SPECIES_EXCADRILL 530
#define SPECIES_AUDINO 531
#define SPECIES_TIMBURR 532
#define SPECIES_GURDURR 533
#define SPECIES_CONKELDURR 534
#define SPECIES_TYMPOLE 535
#define SPECIES_PALPITOAD 536
#define SPECIES_SEISMITOAD 537
#define SPECIES_THROH 538
#define SPECIES_SAWK 539
#define SPECIES_SEWADDLE 540
#define SPECIES_SWADLOON 541
#define SPECIES_LEAVANNY 542
#define SPECIES_VENIPEDE 543
#define SPECIES_WHIRLIPEDE 544
#define SPECIES_SCOLIPEDE 545
#define SPECIES_COTTONEE 546
#define SPECIES_WHIMSICOTT 547
#define SPECIES_PETILIL 548
#define SPECIES_LILLIGANT 549
#define SPECIES_BASCULIN 550
#define SPECIES_SANDILE 551
#define SPECIES_KROKOROK 552
#define SPECIES_KROOKODILE 553
#define SPECIES_DARUMAKA 554
#define SPECIES_DARMANITAN 555
#define SPECIES_MARACTUS 556
#define SPECIES_DWEBBLE 557
#define SPECIES_CRUSTLE 558
#define SPECIES_SCRAGGY 559
#define SPECIES_SCRAFTY 560
#define SPECIES_SIGILYPH 561
#define SPECIES_YAMASK 562
#define SPECIES_COFAGRIGUS 563
#define SPECIES_TIRTOUGA 564
#define SPECIES_CARRACOSTA 565
#define SPECIES_ARCHEN 566
#define SPECIES_ARCHEOPS 567
#define SPECIES_TRUBBISH 568
#define SPECIES_GARBODOR 569
#define SPECIES_ZORUA 570
#define SPECIES_ZOROARK 571
#define SPECIES_MINCCINO 572
#define SPECIES_CINCCINO 573
#define SPECIES_GOTHITA 574
#define SPECIES_GOTHORITA 575
#define SPECIES_GOTHITELLE 576
#define SPECIES_SOLOSIS 577
#define SPECIES_DUOSION 578
#define SPECIES_REUNICLUS 579
#define SPECIES_DUCKLETT 580
#define SPECIES_SWANNA 581
#define SPECIES_VANILLITE 582
#define SPECIES_VANILLISH 583
#define SPECIES_VANILLUXE 584
#define SPECIES_DEERLING 585
#define SPECIES_SAWSBUCK 586
#define SPECIES_EMOLGA 587
#define SPECIES_KARRABLAST 588
#define SPECIES_ESCAVALIER 589
#define SPECIES_FOONGUS 590
#define SPECIES_AMOONGUSS 591
#define SPECIES_FRILLISH 592
#define SPECIES_JELLICENT 593
#define SPECIES_ALOMOMOLA 594
#define SPECIES_JOLTIK 595
#define SPECIES_GALVANTULA 596
#define SPECIES_FERROSEED 597
#define SPECIES_FERROTHORN 598
#define SPECIES_KLINK 599
#define SPECIES_KLANG 600
#define SPECIES_KLINKLANG 601
#define SPECIES_TYNAMO 602
#define SPECIES_EELEKTRIK 603
#define SPECIES_EELEKTROSS 604
#define SPECIES_ELGYEM 605
#define SPECIES_BEHEEYEM 606
#define SPECIES_LITWICK 607
#define SPECIES_LAMPENT 608
#define SPECIES_CHANDELURE 609
#define SPECIES_AXEW 610
#define SPECIES_FRAXURE 611
#define SPECIES_HAXORUS 612
#define SPECIES_CUBCHOO 613
#define SPECIES_BEARTIC 614
#define SPECIES_CRYOGONAL 615
#define SPECIES_SHELMET 616
#define SPECIES_ACCELGOR 617
#define SPECIES_STUNFISK 618
#define SPECIES_MIENFOO 619
#define SPECIES_MIENSHAO 620
#define SPECIES_DRUDDIGON 621
#define SPECIES_GOLETT 622
#define SPECIES_GOLURK 623
#define SPECIES_PAWNIARD 624
#define SPECIES_BISHARP 625
#define SPECIES_BOUFFALANT 626
#define SPECIES_RUFFLET 627
#define SPECIES_BRAVIARY 628
#define SPECIES_VULLABY 629
#define SPECIES_MANDIBUZZ 630
#define SPECIES_HEATMOR 631
#define SPECIES_DURANT 632
#define SPECIES_DEINO 633
#define SPECIES_ZWEILOUS 634
#define SPECIES_HYDREIGON 635
#define SPECIES_LARVESTA 636
#define SPECIES_VOLCARONA 637
#define SPECIES_COBALION 638
#define SPECIES_TERRAKION 639
#define SPECIES_VIRIZION 640
#define SPECIES_TORNADUS 641
#define SPECIES_THUNDURUS 642
#define SPECIES_RESHIRAM 643
#define SPECIES_ZEKROM 644
#define SPECIES_LANDORUS 645
#define SPECIES_KYUREM 646
#define SPECIES_KELDEO 647
#define SPECIES_MELOETTA 648
#define SPECIES_GENESECT 649
#define SPECIES_CHESPIN 650
#define SPECIES_QUILLADIN 651
#define SPECIES_CHESNAUGHT 652
#define SPECIES_FENNEKIN 653
#define SPECIES_BRAIXEN 654
#define SPECIES_DELPHOX 655
#define SPECIES_FROAKIE 656
#define SPECIES_FROGADIER 657
#define SPECIES_GRENINJA 658
#define SPECIES_BUNNELBY 659
#define SPECIES_DIGGERSBY 660
#define SPECIES_FLETCHLING 661
#define SPECIES_FLETCHINDER 662
#define SPECIES_TALONFLAME 663
#define SPECIES_SCATTERBUG 664
#define SPECIES_SPEWPA 665
#define SPECIES_VIVILLON 666 // Icy Snow Pattern
#define SPECIES_LITLEO 667
#define SPECIES_PYROAR 668
#define SPECIES_FLABEBE 669 // Red Flower
#define SPECIES_FLOETTE 670
#define SPECIES_FLORGES 671
#define SPECIES_SKIDDO 672
#define SPECIES_GOGOAT 673
#define SPECIES_PANCHAM 674
#define SPECIES_PANGORO 675
#define SPECIES_FURFROU 676
#define SPECIES_ESPURR 677
#define SPECIES_MEOWSTIC 678
#define SPECIES_HONEDGE 679
#define SPECIES_DOUBLADE 680
#define SPECIES_AEGISLASH 681
#define SPECIES_SPRITZEE 682
#define SPECIES_AROMATISSE 683
#define SPECIES_SWIRLIX 684
#define SPECIES_SLURPUFF 685
#define SPECIES_INKAY 686
#define SPECIES_MALAMAR 687
#define SPECIES_BINACLE 688
#define SPECIES_BARBARACLE 689
#define SPECIES_SKRELP 690
#define SPECIES_DRAGALGE 691
#define SPECIES_CLAUNCHER 692
#define SPECIES_CLAWITZER 693
#define SPECIES_HELIOPTILE 694
#define SPECIES_HELIOLISK 695
#define SPECIES_TYRUNT 696
#define SPECIES_TYRANTRUM 697
#define SPECIES_AMAURA 698
#define SPECIES_AURORUS 699
#define SPECIES_SYLVEON 700
#define SPECIES_HAWLUCHA 701
#define SPECIES_DEDENNE 702
#define SPECIES_CARBINK 703
#define SPECIES_GOOMY 704
#define SPECIES_SLIGGOO 705
#define SPECIES_GOODRA 706
#define SPECIES_KLEFKI 707
#define SPECIES_PHANTUMP 708
#define SPECIES_TREVENANT 709
#define SPECIES_PUMPKABOO 710
#define SPECIES_GOURGEIST 711
#define SPECIES_BERGMITE 712
#define SPECIES_AVALUGG 713
#define SPECIES_NOIBAT 714
#define SPECIES_NOIVERN 715
#define SPECIES_XERNEAS 716
#define SPECIES_YVELTAL 717
#define SPECIES_ZYGARDE 718
#define SPECIES_DIANCIE 719
#define SPECIES_HOOPA 720
#define SPECIES_VOLCANION 721
#define SPECIES_ROWLET 722
#define SPECIES_DARTRIX 723
#define SPECIES_DECIDUEYE 724
#define SPECIES_LITTEN 725
#define SPECIES_TORRACAT 726
#define SPECIES_INCINEROAR 727
#define SPECIES_POPPLIO 728
#define SPECIES_BRIONNE 729
#define SPECIES_PRIMARINA 730
#define SPECIES_PIKIPEK 731
#define SPECIES_TRUMBEAK 732
#define SPECIES_TOUCANNON 733
#define SPECIES_YUNGOOS 734
#define SPECIES_GUMSHOOS 735
#define SPECIES_GRUBBIN 736
#define SPECIES_CHARJABUG 737
#define SPECIES_VIKAVOLT 738
#define SPECIES_CRABRAWLER 739
#define SPECIES_CRABOMINABLE 740
#define SPECIES_ORICORIO 741
#define SPECIES_CUTIEFLY 742
#define SPECIES_RIBOMBEE 743
#define SPECIES_ROCKRUFF 744
#define SPECIES_LYCANROC 745
#define SPECIES_WISHIWASHI 746
#define SPECIES_MAREANIE 747
#define SPECIES_TOXAPEX 748
#define SPECIES_MUDBRAY 749
#define SPECIES_MUDSDALE 750
#define SPECIES_DEWPIDER 751
#define SPECIES_ARAQUANID 752
#define SPECIES_FOMANTIS 753
#define SPECIES_LURANTIS 754
#define SPECIES_MORELULL 755
#define SPECIES_SHIINOTIC 756
#define SPECIES_SALANDIT 757
#define SPECIES_SALAZZLE 758
#define SPECIES_STUFFUL 759
#define SPECIES_BEWEAR 760
#define SPECIES_BOUNSWEET 761
#define SPECIES_STEENEE 762
#define SPECIES_TSAREENA 763
#define SPECIES_COMFEY 764
#define SPECIES_ORANGURU 765
#define SPECIES_PASSIMIAN 766
#define SPECIES_WIMPOD 767
#define SPECIES_GOLISOPOD 768
#define SPECIES_SANDYGAST 769
#define SPECIES_PALOSSAND 770
#define SPECIES_PYUKUMUKU 771
#define SPECIES_TYPE_NULL 772
#define SPECIES_SILVALLY 773
#define SPECIES_MINIOR 774
#define SPECIES_KOMALA 775
#define SPECIES_TURTONATOR 776
#define SPECIES_TOGEDEMARU 777
#define SPECIES_MIMIKYU 778
#define SPECIES_BRUXISH 779
#define SPECIES_DRAMPA 780
#define SPECIES_DHELMISE 781
#define SPECIES_JANGMO_O 782
#define SPECIES_HAKAMO_O 783
#define SPECIES_KOMMO_O 784
#define SPECIES_TAPU_KOKO 785
#define SPECIES_TAPU_LELE 786
#define SPECIES_TAPU_BULU 787
#define SPECIES_TAPU_FINI 788
#define SPECIES_COSMOG 789
#define SPECIES_COSMOEM 790
#define SPECIES_SOLGALEO 791
#define SPECIES_LUNALA 792
#define SPECIES_NIHILEGO 793
#define SPECIES_BUZZWOLE 794
#define SPECIES_PHEROMOSA 795
#define SPECIES_XURKITREE 796
#define SPECIES_CELESTEELA 797
#define SPECIES_KARTANA 798
#define SPECIES_GUZZLORD 799
#define SPECIES_NECROZMA 800
#define SPECIES_MAGEARNA 801
#define SPECIES_MARSHADOW 802
#define SPECIES_POIPOLE 803
#define SPECIES_NAGANADEL 804
#define SPECIES_STAKATAKA 805
#define SPECIES_BLACEPHALON 806
#define SPECIES_ZERAORA 807
#define SPECIES_MELTAN 808
#define SPECIES_MELMETAL 809
#define SPECIES_GROOKEY 810
#define SPECIES_THWACKEY 811
#define SPECIES_RILLABOOM 812
#define SPECIES_SCORBUNNY 813
#define SPECIES_RABOOT 814
#define SPECIES_CINDERACE 815
#define SPECIES_SOBBLE 816
#define SPECIES_DRIZZILE 817
#define SPECIES_INTELEON 818
#define SPECIES_SKWOVET 819
#define SPECIES_GREEDENT 820
#define SPECIES_ROOKIDEE 821
#define SPECIES_CORVISQUIRE 822
#define SPECIES_CORVIKNIGHT 823
#define SPECIES_BLIPBUG 824
#define SPECIES_DOTTLER 825
#define SPECIES_ORBEETLE 826
#define SPECIES_NICKIT 827
#define SPECIES_THIEVUL 828
#define SPECIES_GOSSIFLEUR 829
#define SPECIES_ELDEGOSS 830
#define SPECIES_WOOLOO 831
#define SPECIES_DUBWOOL 832
#define SPECIES_CHEWTLE 833
#define SPECIES_DREDNAW 834
#define SPECIES_YAMPER 835
#define SPECIES_BOLTUND 836
#define SPECIES_ROLYCOLY 837
#define SPECIES_CARKOL 838
#define SPECIES_COALOSSAL 839
#define SPECIES_APPLIN 840
#define SPECIES_FLAPPLE 841
#define SPECIES_APPLETUN 842
#define SPECIES_SILICOBRA 843
#define SPECIES_SANDACONDA 844
#define SPECIES_CRAMORANT 845
#define SPECIES_ARROKUDA 846
#define SPECIES_BARRASKEWDA 847
#define SPECIES_TOXEL 848
#define SPECIES_TOXTRICITY 849
#define SPECIES_SIZZLIPEDE 850
#define SPECIES_CENTISKORCH 851
#define SPECIES_CLOBBOPUS 852
#define SPECIES_GRAPPLOCT 853
#define SPECIES_SINISTEA 854
#define SPECIES_POLTEAGEIST 855
#define SPECIES_HATENNA 856
#define SPECIES_HATTREM 857
#define SPECIES_HATTERENE 858
#define SPECIES_IMPIDIMP 859
#define SPECIES_MORGREM 860
#define SPECIES_GRIMMSNARL 861
#define SPECIES_OBSTAGOON 862
#define SPECIES_PERRSERKER 863
#define SPECIES_CURSOLA 864
#define SPECIES_SIRFETCHD 865
#define SPECIES_MR_RIME 866
#define SPECIES_RUNERIGUS 867
#define SPECIES_MILCERY 868
#define SPECIES_ALCREMIE 869
#define SPECIES_FALINKS 870
#define SPECIES_PINCURCHIN 871
#define SPECIES_SNOM 872
#define SPECIES_FROSMOTH 873
#define SPECIES_STONJOURNER 874
#define SPECIES_EISCUE 875
#define SPECIES_INDEEDEE 876
#define SPECIES_MORPEKO 877
#define SPECIES_CUFANT 878
#define SPECIES_COPPERAJAH 879
#define SPECIES_DRACOZOLT 880
#define SPECIES_ARCTOZOLT 881
#define SPECIES_DRACOVISH 882
#define SPECIES_ARCTOVISH 883
#define SPECIES_DURALUDON 884
#define SPECIES_DREEPY 885
#define SPECIES_DRAKLOAK 886
#define SPECIES_DRAGAPULT 887
#define SPECIES_ZACIAN 888
#define SPECIES_ZAMAZENTA 889
#define SPECIES_ETERNATUS 890
#define SPECIES_KUBFU 891
#define SPECIES_URSHIFU 892
#define SPECIES_ZARUDE 893
#define SPECIES_REGIELEKI 894
#define SPECIES_REGIDRAGO 895
#define SPECIES_GLASTRIER 896
#define SPECIES_SPECTRIER 897
#define SPECIES_CALYREX 898
#define SPECIES_WYRDEER 899
#define SPECIES_KLEAVOR 900
#define SPECIES_URSALUNA 901
#define SPECIES_BASCULEGION 902
#define SPECIES_SNEASLER 903
#define SPECIES_OVERQWIL 904
#define SPECIES_ENAMORUS 905

// Megas
#define SPECIES_VENUSAUR_MEGA                FORMS_START + 1
#define SPECIES_CHARIZARD_MEGA_X             FORMS_START + 2
#define SPECIES_CHARIZARD_MEGA_Y             FORMS_START + 3
#define SPECIES_BLASTOISE_MEGA               FORMS_START + 4
#define SPECIES_BEEDRILL_MEGA                FORMS_START + 5
#define SPECIES_PIDGEOT_MEGA                 FORMS_START + 6
#define SPECIES_ALAKAZAM_MEGA                FORMS_START + 7
#define SPECIES_SLOWBRO_MEGA                 FORMS_START + 8
#define SPECIES_GENGAR_MEGA                  FORMS_START + 9
#define SPECIES_KANGASKHAN_MEGA              FORMS_START + 10
#define SPECIES_PINSIR_MEGA                  FORMS_START + 11
#define SPECIES_GYARADOS_MEGA                FORMS_START + 12
#define SPECIES_AERODACTYL_MEGA              FORMS_START + 13
#define SPECIES_MEWTWO_MEGA_X                FORMS_START + 14
#define SPECIES_MEWTWO_MEGA_Y                FORMS_START + 15
#define SPECIES_AMPHAROS_MEGA                FORMS_START + 16
#define SPECIES_STEELIX_MEGA                 FORMS_START + 17
#define SPECIES_SCIZOR_MEGA                  FORMS_START + 18
#define SPECIES_HERACROSS_MEGA               FORMS_START + 19
#define SPECIES_HOUNDOOM_MEGA                FORMS_START + 20
#define SPECIES_TYRANITAR_MEGA               FORMS_START + 21
#define SPECIES_SCEPTILE_MEGA                FORMS_START + 22
#define SPECIES_BLAZIKEN_MEGA                FORMS_START + 23
#define SPECIES_SWAMPERT_MEGA                FORMS_START + 24
#define SPECIES_GARDEVOIR_MEGA               FORMS_START + 25
#define SPECIES_SABLEYE_MEGA                 FORMS_START + 26
#define SPECIES_MAWILE_MEGA                  FORMS_START + 27
#define SPECIES_AGGRON_MEGA                  FORMS_START + 28
#define SPECIES_MEDICHAM_MEGA                FORMS_START + 29
#define SPECIES_MANECTRIC_MEGA               FORMS_START + 30
#define SPECIES_SHARPEDO_MEGA                FORMS_START + 31
#define SPECIES_CAMERUPT_MEGA                FORMS_START + 32
#define SPECIES_ALTARIA_MEGA                 FORMS_START + 33
#define SPECIES_BANETTE_MEGA                 FORMS_START + 34
#define SPECIES_ABSOL_MEGA                   FORMS_START + 35
#define SPECIES_GLALIE_MEGA                  FORMS_START + 36
#define SPECIES_SALAMENCE_MEGA               FORMS_START + 37
#define SPECIES_METAGROSS_MEGA               FORMS_START + 38
#define SPECIES_LATIAS_MEGA                  FORMS_START + 39
#define SPECIES_LATIOS_MEGA                  FORMS_START + 40
#define SPECIES_LOPUNNY_MEGA                 FORMS_START + 41
#define SPECIES_GARCHOMP_MEGA                FORMS_START + 42
#define SPECIES_LUCARIO_MEGA                 FORMS_START + 43
#define SPECIES_ABOMASNOW_MEGA               FORMS_START + 44
#define SPECIES_GALLADE_MEGA                 FORMS_START + 45
#define SPECIES_AUDINO_MEGA                  FORMS_START + 46
#define SPECIES_DIANCIE_MEGA                 FORMS_START + 47

// Special Mega + Primals
#define SPECIES_RAYQUAZA_MEGA                FORMS_START + 48
#define SPECIES_KYOGRE_PRIMAL                FORMS_START + 49
#define SPECIES_GROUDON_PRIMAL               FORMS_START + 50

// Alolan Forms
#define SPECIES_RATTATA_ALOLAN               FORMS_START + 51
#define SPECIES_RATICATE_ALOLAN              FORMS_START + 52
#define SPECIES_RAICHU_ALOLAN                FORMS_START + 53
#define SPECIES_SANDSHREW_ALOLAN             FORMS_START + 54
#define SPECIES_SANDSLASH_ALOLAN             FORMS_START + 55
#define SPECIES_VULPIX_ALOLAN                FORMS_START + 56
#define SPECIES_NINETALES_ALOLAN             FORMS_START + 57
#define SPECIES_DIGLETT_ALOLAN               FORMS_START + 58
#define SPECIES_DUGTRIO_ALOLAN               FORMS_START + 59
#define SPECIES_MEOWTH_ALOLAN                FORMS_START + 60
#define SPECIES_PERSIAN_ALOLAN               FORMS_START + 61
#define SPECIES_GEODUDE_ALOLAN               FORMS_START + 62
#define SPECIES_GRAVELER_ALOLAN              FORMS_START + 63
#define SPECIES_GOLEM_ALOLAN                 FORMS_START + 64
#define SPECIES_GRIMER_ALOLAN                FORMS_START + 65
#define SPECIES_MUK_ALOLAN                   FORMS_START + 66
#define SPECIES_EXEGGUTOR_ALOLAN             FORMS_START + 67
#define SPECIES_MAROWAK_ALOLAN               FORMS_START + 68

// Galarian Forms
#define SPECIES_MEOWTH_GALARIAN              FORMS_START + 69
#define SPECIES_PONYTA_GALARIAN              FORMS_START + 70
#define SPECIES_RAPIDASH_GALARIAN            FORMS_START + 71
#define SPECIES_SLOWPOKE_GALARIAN            FORMS_START + 72
#define SPECIES_SLOWBRO_GALARIAN             FORMS_START + 73
#define SPECIES_FARFETCHD_GALARIAN           FORMS_START + 74
#define SPECIES_WEEZING_GALARIAN             FORMS_START + 75
#define SPECIES_MR_MIME_GALARIAN             FORMS_START + 76
#define SPECIES_ARTICUNO_GALARIAN            FORMS_START + 77
#define SPECIES_ZAPDOS_GALARIAN              FORMS_START + 78
#define SPECIES_MOLTRES_GALARIAN             FORMS_START + 79
#define SPECIES_SLOWKING_GALARIAN            FORMS_START + 80
#define SPECIES_CORSOLA_GALARIAN             FORMS_START + 81
#define SPECIES_ZIGZAGOON_GALARIAN           FORMS_START + 82
#define SPECIES_LINOONE_GALARIAN             FORMS_START + 83
#define SPECIES_DARUMAKA_GALARIAN            FORMS_START + 84
#define SPECIES_DARMANITAN_GALARIAN          FORMS_START + 85
#define SPECIES_YAMASK_GALARIAN              FORMS_START + 86
#define SPECIES_STUNFISK_GALARIAN            FORMS_START + 87

//Hisuian Forms
#define SPECIES_GROWLITHE_HISUIAN            FORMS_START + 88
#define SPECIES_ARCANINE_HISUIAN             FORMS_START + 89
#define SPECIES_VOLTORB_HISUIAN              FORMS_START + 90
#define SPECIES_ELECTRODE_HISUIAN            FORMS_START + 91
#define SPECIES_TYPHLOSION_HISUIAN           FORMS_START + 92
#define SPECIES_QWILFISH_HISUIAN             FORMS_START + 93
#define SPECIES_SNEASEL_HISUIAN              FORMS_START + 94
#define SPECIES_SAMUROTT_HISUIAN             FORMS_START + 95
#define SPECIES_LILLIGANT_HISUIAN            FORMS_START + 96
#define SPECIES_ZORUA_HISUIAN                FORMS_START + 97
#define SPECIES_ZOROARK_HISUIAN              FORMS_START + 98
#define SPECIES_BRAVIARY_HISUIAN             FORMS_START + 99
#define SPECIES_SLIGGOO_HISUIAN              FORMS_START + 100
#define SPECIES_GOODRA_HISUIAN               FORMS_START + 101
#define SPECIES_AVALUGG_HISUIAN              FORMS_START + 102
#define SPECIES_DECIDUEYE_HISUIAN            FORMS_START + 103

// Misc Forms

// Cosplay Pikachu
#define SPECIES_PIKACHU_COSPLAY              FORMS_START + 104
#define SPECIES_PIKACHU_ROCK_STAR            FORMS_START + 105
#define SPECIES_PIKACHU_BELLE                FORMS_START + 106
#define SPECIES_PIKACHU_POP_STAR             FORMS_START + 107
#define SPECIES_PIKACHU_PH_D                 FORMS_START + 108
#define SPECIES_PIKACHU_LIBRE                FORMS_START + 109

// Cap Pikachu
#define SPECIES_PIKACHU_ORIGINAL_CAP         FORMS_START + 110
#define SPECIES_PIKACHU_HOENN_CAP            FORMS_START + 111
#define SPECIES_PIKACHU_SINNOH_CAP           FORMS_START + 112
#define SPECIES_PIKACHU_UNOVA_CAP            FORMS_START + 113
#define SPECIES_PIKACHU_KALOS_CAP            FORMS_START + 114
#define SPECIES_PIKACHU_ALOLA_CAP            FORMS_START + 115
#define SPECIES_PIKACHU_PARTNER_CAP          FORMS_START + 116
#define SPECIES_PIKACHU_WORLD_CAP            FORMS_START + 117

// Pichu
#define SPECIES_PICHU_SPIKY_EARED            FORMS_START + 118

// Unown
#define SPECIES_UNOWN_B                      FORMS_START + 119
#define SPECIES_UNOWN_C                      FORMS_START + 120
#define SPECIES_UNOWN_D                      FORMS_START + 121
#define SPECIES_UNOWN_E                      FORMS_START + 122
#define SPECIES_UNOWN_F                      FORMS_START + 123
#define SPECIES_UNOWN_G                      FORMS_START + 124
#define SPECIES_UNOWN_H                      FORMS_START + 125
#define SPECIES_UNOWN_I                      FORMS_START + 126
#define SPECIES_UNOWN_J                      FORMS_START + 127
#define SPECIES_UNOWN_K                      FORMS_START + 128
#define SPECIES_UNOWN_L                      FORMS_START + 129
#define SPECIES_UNOWN_M                      FORMS_START + 130
#define SPECIES_UNOWN_N                      FORMS_START + 131
#define SPECIES_UNOWN_O                      FORMS_START + 132
#define SPECIES_UNOWN_P                      FORMS_START + 133
#define SPECIES_UNOWN_Q                      FORMS_START + 134
#define SPECIES_UNOWN_R                      FORMS_START + 135
#define SPECIES_UNOWN_S                      FORMS_START + 136
#define SPECIES_UNOWN_T                      FORMS_START + 137
#define SPECIES_UNOWN_U                      FORMS_START + 138
#define SPECIES_UNOWN_V                      FORMS_START + 139
#define SPECIES_UNOWN_W                      FORMS_START + 140
#define SPECIES_UNOWN_X                      FORMS_START + 141
#define SPECIES_UNOWN_Y                      FORMS_START + 142
#define SPECIES_UNOWN_Z                      FORMS_START + 143
#define SPECIES_UNOWN_EMARK                  FORMS_START + 144
#define SPECIES_UNOWN_QMARK                  FORMS_START + 145

// Castform
#define SPECIES_CASTFORM_SUNNY               FORMS_START + 146
#define SPECIES_CASTFORM_RAINY               FORMS_START + 147
#define SPECIES_CASTFORM_SNOWY               FORMS_START + 148

// Deoxys
#define SPECIES_DEOXYS_ATTACK                FORMS_START + 149
#define SPECIES_DEOXYS_DEFENSE               FORMS_START + 150
#define SPECIES_DEOXYS_SPEED                 FORMS_START + 151

// Burmy
#define SPECIES_BURMY_SANDY_CLOAK            FORMS_START + 152
#define SPECIES_BURMY_TRASH_CLOAK            FORMS_START + 153

// Wormadam
#define SPECIES_WORMADAM_SANDY_CLOAK         FORMS_START + 154
#define SPECIES_WORMADAM_TRASH_CLOAK         FORMS_START + 155

// Cherrim
#define SPECIES_CHERRIM_SUNSHINE             FORMS_START + 156

// Shellos
#define SPECIES_SHELLOS_EAST_SEA             FORMS_START + 157

// Gastrodon
#define SPECIES_GASTRODON_EAST_SEA           FORMS_START + 158

// Rotom
#define SPECIES_ROTOM_HEAT                   FORMS_START + 159
#define SPECIES_ROTOM_WASH                   FORMS_START + 160
#define SPECIES_ROTOM_FROST                  FORMS_START + 161
#define SPECIES_ROTOM_FAN                    FORMS_START + 162
#define SPECIES_ROTOM_MOW                    FORMS_START + 163

// Origin Forme
#define SPECIES_DIALGA_ORIGIN                FORMS_START + 164
#define SPECIES_PALKIA_ORIGIN                FORMS_START + 165
#define SPECIES_GIRATINA_ORIGIN              FORMS_START + 166

// Shaymin
#define SPECIES_SHAYMIN_SKY                  FORMS_START + 167

// Arceus
#define SPECIES_ARCEUS_FIGHTING              FORMS_START + 168
#define SPECIES_ARCEUS_FLYING                FORMS_START + 169
#define SPECIES_ARCEUS_POISON                FORMS_START + 170
#define SPECIES_ARCEUS_GROUND                FORMS_START + 171
#define SPECIES_ARCEUS_ROCK                  FORMS_START + 172
#define SPECIES_ARCEUS_BUG                   FORMS_START + 173
#define SPECIES_ARCEUS_GHOST                 FORMS_START + 174
#define SPECIES_ARCEUS_STEEL                 FORMS_START + 175
#define SPECIES_ARCEUS_FIRE                  FORMS_START + 176
#define SPECIES_ARCEUS_WATER                 FORMS_START + 177
#define SPECIES_ARCEUS_GRASS                 FORMS_START + 178
#define SPECIES_ARCEUS_ELECTRIC              FORMS_START + 179
#define SPECIES_ARCEUS_PSYCHIC               FORMS_START + 180
#define SPECIES_ARCEUS_ICE                   FORMS_START + 181
#define SPECIES_ARCEUS_DRAGON                FORMS_START + 182
#define SPECIES_ARCEUS_DARK                  FORMS_START + 183
#define SPECIES_ARCEUS_FAIRY                 FORMS_START + 184

// Basculin
#define SPECIES_BASCULIN_BLUE_STRIPED        FORMS_START + 185
#define SPECIES_BASCULIN_WHITE_STRIPED       FORMS_START + 186

// Darmanitan
#define SPECIES_DARMANITAN_ZEN_MODE          FORMS_START + 187
#define SPECIES_DARMANITAN_ZEN_MODE_GALARIAN FORMS_START + 188

// Deerling
#define SPECIES_DEERLING_SUMMER              FORMS_START + 189
#define SPECIES_DEERLING_AUTUMN              FORMS_START + 190
#define SPECIES_DEERLING_WINTER              FORMS_START + 191

// Sawsbuck
#define SPECIES_SAWSBUCK_SUMMER              FORMS_START + 192
#define SPECIES_SAWSBUCK_AUTUMN              FORMS_START + 193
#define SPECIES_SAWSBUCK_WINTER              FORMS_START + 194

// Therian Forms
#define SPECIES_TORNADUS_THERIAN             FORMS_START + 195
#define SPECIES_THUNDURUS_THERIAN            FORMS_START + 196
#define SPECIES_LANDORUS_THERIAN             FORMS_START + 197
#define SPECIES_ENAMORUS_THERIAN             FORMS_START + 198

// Kyurem
#define SPECIES_KYUREM_WHITE                 FORMS_START + 199
#define SPECIES_KYUREM_BLACK                 FORMS_START + 200

// Keldeo
#define SPECIES_KELDEO_RESOLUTE              FORMS_START + 201

// Meloetta
#define SPECIES_MELOETTA_PIROUETTE           FORMS_START + 202

// Genesect
#define SPECIES_GENESECT_DOUSE_DRIVE         FORMS_START + 203
#define SPECIES_GENESECT_SHOCK_DRIVE         FORMS_START + 204
#define SPECIES_GENESECT_BURN_DRIVE          FORMS_START + 205
#define SPECIES_GENESECT_CHILL_DRIVE         FORMS_START + 206

// Greninja
#define SPECIES_GRENINJA_BATTLE_BOND         FORMS_START + 207
#define SPECIES_GRENINJA_ASH                 FORMS_START + 208

// Vivillon
#define SPECIES_VIVILLON_POLAR               FORMS_START + 209
#define SPECIES_VIVILLON_TUNDRA              FORMS_START + 210
#define SPECIES_VIVILLON_CONTINENTAL         FORMS_START + 211
#define SPECIES_VIVILLON_GARDEN              FORMS_START + 212
#define SPECIES_VIVILLON_ELEGANT             FORMS_START + 213
#define SPECIES_VIVILLON_MEADOW              FORMS_START + 214
#define SPECIES_VIVILLON_MODERN              FORMS_START + 215
#define SPECIES_VIVILLON_MARINE              FORMS_START + 216
#define SPECIES_VIVILLON_ARCHIPELAGO         FORMS_START + 217
#define SPECIES_VIVILLON_HIGH_PLAINS         FORMS_START + 218
#define SPECIES_VIVILLON_SANDSTORM           FORMS_START + 219
#define SPECIES_VIVILLON_RIVER               FORMS_START + 220
#define SPECIES_VIVILLON_MONSOON             FORMS_START + 221
#define SPECIES_VIVILLON_SAVANNA             FORMS_START + 222
#define SPECIES_VIVILLON_SUN                 FORMS_START + 223
#define SPECIES_VIVILLON_OCEAN               FORMS_START + 224
#define SPECIES_VIVILLON_JUNGLE              FORMS_START + 225
#define SPECIES_VIVILLON_FANCY               FORMS_START + 226
#define SPECIES_VIVILLON_POKE_BALL           FORMS_START + 227

// Flabébé
#define SPECIES_FLABEBE_YELLOW_FLOWER        FORMS_START + 228
#define SPECIES_FLABEBE_ORANGE_FLOWER        FORMS_START + 229
#define SPECIES_FLABEBE_BLUE_FLOWER          FORMS_START + 230
#define SPECIES_FLABEBE_WHITE_FLOWER         FORMS_START + 231

// Floette
#define SPECIES_FLOETTE_YELLOW_FLOWER        FORMS_START + 232
#define SPECIES_FLOETTE_ORANGE_FLOWER        FORMS_START + 233
#define SPECIES_FLOETTE_BLUE_FLOWER          FORMS_START + 234
#define SPECIES_FLOETTE_WHITE_FLOWER         FORMS_START + 235
#define SPECIES_FLOETTE_ETERNAL_FLOWER       FORMS_START + 236

// Florges
#define SPECIES_FLORGES_YELLOW_FLOWER        FORMS_START + 237
#define SPECIES_FLORGES_ORANGE_FLOWER        FORMS_START + 238
#define SPECIES_FLORGES_BLUE_FLOWER          FORMS_START + 239
#define SPECIES_FLORGES_WHITE_FLOWER         FORMS_START + 240

// Furfrou
#define SPECIES_FURFROU_HEART_TRIM           FORMS_START + 241
#define SPECIES_FURFROU_STAR_TRIM            FORMS_START + 242
#define SPECIES_FURFROU_DIAMOND_TRIM         FORMS_START + 243
#define SPECIES_FURFROU_DEBUTANTE_TRIM       FORMS_START + 244
#define SPECIES_FURFROU_MATRON_TRIM          FORMS_START + 245
#define SPECIES_FURFROU_DANDY_TRIM           FORMS_START + 246
#define SPECIES_FURFROU_LA_REINE_TRIM        FORMS_START + 247
#define SPECIES_FURFROU_KABUKI_TRIM          FORMS_START + 248
#define SPECIES_FURFROU_PHARAOH_TRIM         FORMS_START + 249

// Meowstic
#define SPECIES_MEOWSTIC_FEMALE              FORMS_START + 250

// Aegislash
#define SPECIES_AEGISLASH_BLADE              FORMS_START + 251

// Pumpkaboo
#define SPECIES_PUMPKABOO_SMALL              FORMS_START + 252
#define SPECIES_PUMPKABOO_LARGE              FORMS_START + 253
#define SPECIES_PUMPKABOO_SUPER              FORMS_START + 254

// Gourgeist
#define SPECIES_GOURGEIST_SMALL              FORMS_START + 255
#define SPECIES_GOURGEIST_LARGE              FORMS_START + 256
#define SPECIES_GOURGEIST_SUPER              FORMS_START + 257

// Xerneas
#define SPECIES_XERNEAS_ACTIVE               FORMS_START + 258

// Zygarde
#define SPECIES_ZYGARDE_10                   FORMS_START + 259
#define SPECIES_ZYGARDE_10_POWER_CONSTRUCT   FORMS_START + 260
#define SPECIES_ZYGARDE_50_POWER_CONSTRUCT   FORMS_START + 261
#define SPECIES_ZYGARDE_COMPLETE             FORMS_START + 262

// Hoopa
#define SPECIES_HOOPA_UNBOUND                FORMS_START + 263

// Oricorio
#define SPECIES_ORICORIO_POM_POM             FORMS_START + 264
#define SPECIES_ORICORIO_PAU                 FORMS_START + 265
#define SPECIES_ORICORIO_SENSU               FORMS_START + 266

// Rockruff
#define SPECIES_ROCKRUFF_OWN_TEMPO           FORMS_START + 267

// Lycanroc
#define SPECIES_LYCANROC_MIDNIGHT            FORMS_START + 268
#define SPECIES_LYCANROC_DUSK                FORMS_START + 269

// Wishiwashi
#define SPECIES_WISHIWASHI_SCHOOL            FORMS_START + 270

// Silvally
#define SPECIES_SILVALLY_FIGHTING            FORMS_START + 271
#define SPECIES_SILVALLY_FLYING              FORMS_START + 272
#define SPECIES_SILVALLY_POISON              FORMS_START + 273
#define SPECIES_SILVALLY_GROUND              FORMS_START + 274
#define SPECIES_SILVALLY_ROCK                FORMS_START + 275
#define SPECIES_SILVALLY_BUG                 FORMS_START + 276
#define SPECIES_SILVALLY_GHOST               FORMS_START + 277
#define SPECIES_SILVALLY_STEEL               FORMS_START + 278
#define SPECIES_SILVALLY_FIRE                FORMS_START + 279
#define SPECIES_SILVALLY_WATER               FORMS_START + 280
#define SPECIES_SILVALLY_GRASS               FORMS_START + 281
#define SPECIES_SILVALLY_ELECTRIC            FORMS_START + 282
#define SPECIES_SILVALLY_PSYCHIC             FORMS_START + 283
#define SPECIES_SILVALLY_ICE                 FORMS_START + 284
#define SPECIES_SILVALLY_DRAGON              FORMS_START + 285
#define SPECIES_SILVALLY_DARK                FORMS_START + 286
#define SPECIES_SILVALLY_FAIRY               FORMS_START + 287

// Minior
#define SPECIES_MINIOR_METEOR_ORANGE         FORMS_START + 288
#define SPECIES_MINIOR_METEOR_YELLOW         FORMS_START + 289
#define SPECIES_MINIOR_METEOR_GREEN          FORMS_START + 290
#define SPECIES_MINIOR_METEOR_BLUE           FORMS_START + 291
#define SPECIES_MINIOR_METEOR_INDIGO         FORMS_START + 292
#define SPECIES_MINIOR_METEOR_VIOLET         FORMS_START + 293
#define SPECIES_MINIOR_CORE_RED              FORMS_START + 294
#define SPECIES_MINIOR_CORE_ORANGE           FORMS_START + 295
#define SPECIES_MINIOR_CORE_YELLOW           FORMS_START + 296
#define SPECIES_MINIOR_CORE_GREEN            FORMS_START + 297
#define SPECIES_MINIOR_CORE_BLUE             FORMS_START + 298
#define SPECIES_MINIOR_CORE_INDIGO           FORMS_START + 299
#define SPECIES_MINIOR_CORE_VIOLET           FORMS_START + 300

// Mimikyu
#define SPECIES_MIMIKYU_BUSTED               FORMS_START + 301

// Necrozma
#define SPECIES_NECROZMA_DUSK_MANE           FORMS_START + 302
#define SPECIES_NECROZMA_DAWN_WINGS          FORMS_START + 303
#define SPECIES_NECROZMA_ULTRA               FORMS_START + 304

// Magearna
#define SPECIES_MAGEARNA_ORIGINAL_COLOR      FORMS_START + 305

// Cramorant
#define SPECIES_CRAMORANT_GULPING            FORMS_START + 306
#define SPECIES_CRAMORANT_GORGING            FORMS_START + 307

// Toxtricity
#define SPECIES_TOXTRICITY_LOW_KEY           FORMS_START + 308

// Sinistea
#define SPECIES_SINISTEA_ANTIQUE             FORMS_START + 309

// Polteageist
#define SPECIES_POLTEAGEIST_ANTIQUE          FORMS_START + 310

// Alcremie
#define SPECIES_ALCREMIE_RUBY_CREAM          FORMS_START + 311
#define SPECIES_ALCREMIE_MATCHA_CREAM        FORMS_START + 312
#define SPECIES_ALCREMIE_MINT_CREAM          FORMS_START + 313
#define SPECIES_ALCREMIE_LEMON_CREAM         FORMS_START + 314
#define SPECIES_ALCREMIE_SALTED_CREAM        FORMS_START + 315
#define SPECIES_ALCREMIE_RUBY_SWIRL          FORMS_START + 316
#define SPECIES_ALCREMIE_CARAMEL_SWIRL       FORMS_START + 317
#define SPECIES_ALCREMIE_RAINBOW_SWIRL       FORMS_START + 318

// Eiscue
#define SPECIES_EISCUE_NOICE_FACE            FORMS_START + 319

// Indeedee
#define SPECIES_INDEEDEE_FEMALE              FORMS_START + 320

// Morpeko
#define SPECIES_MORPEKO_HANGRY               FORMS_START + 321

// Zacian
#define SPECIES_ZACIAN_CROWNED_SWORD         FORMS_START + 322

// Zamazenta
#define SPECIES_ZAMAZENTA_CROWNED_SHIELD     FORMS_START + 323

// Eternatus
#define SPECIES_ETERNATUS_ETERNAMAX          FORMS_START + 324

// Urshifu
#define SPECIES_URSHIFU_RAPID_STRIKE_STYLE   FORMS_START + 325

// Zarude
#define SPECIES_ZARUDE_DADA                  FORMS_START + 326

// Calyrex
#define SPECIES_CALYREX_ICE_RIDER            FORMS_START + 327
#define SPECIES_CALYREX_SHADOW_RIDER         FORMS_START + 328

#define FORMS_START SPECIES_ENAMORUS
#define SPECIES_EGG SPECIES_CALYREX_SHADOW_RIDER + 1

#define NUM_SPECIES SPECIES_EGG

#endif  // GUARD_CONSTANTS_SPECIES_H
