#ifndef GUARD_CONSTANTS_SPECIES_H
#define GUARD_CONSTANTS_SPECIES_H

#define SPECIES_NONE 0
#define SPECIES_BULBASAUR 1
#define SPECIES_IVYSAUR 2
#define SPECIES_VENUSAUR 3
#define SPECIES_CHARMANDER 4
#define SPECIES_CHARMELEON 5
#define SPECIES_CHARIZARD 6
#define SPECIES_SQUIRTLE 7
#define SPECIES_WARTORTLE 8
#define SPECIES_BLASTOISE 9
#define SPECIES_CATERPIE 10
#define SPECIES_METAPOD 11
#define SPECIES_BUTTERFREE 12
#define SPECIES_WEEDLE 13
#define SPECIES_KAKUNA 14
#define SPECIES_BEEDRILL 15
#define SPECIES_PIDGEY 16
#define SPECIES_PIDGEOTTO 17
#define SPECIES_PIDGEOT 18
#define SPECIES_RATTATA 19
#define SPECIES_RATICATE 20
#define SPECIES_SPEAROW 21
#define SPECIES_FEAROW 22
#define SPECIES_EKANS 23
#define SPECIES_ARBOK 24
#define SPECIES_PIKACHU 25
#define SPECIES_RAICHU 26
#define SPECIES_SANDSHREW 27
#define SPECIES_SANDSLASH 28
#define SPECIES_NIDORAN_F 29
#define SPECIES_NIDORINA 30
#define SPECIES_NIDOQUEEN 31
#define SPECIES_NIDORAN_M 32
#define SPECIES_NIDORINO 33
#define SPECIES_NIDOKING 34
#define SPECIES_CLEFAIRY 35
#define SPECIES_CLEFABLE 36
#define SPECIES_VULPIX 37
#define SPECIES_NINETALES 38
#define SPECIES_JIGGLYPUFF 39
#define SPECIES_WIGGLYTUFF 40
#define SPECIES_ZUBAT 41
#define SPECIES_GOLBAT 42
#define SPECIES_ODDISH 43
#define SPECIES_GLOOM 44
#define SPECIES_VILEPLUME 45
#define SPECIES_PARAS 46
#define SPECIES_PARASECT 47
#define SPECIES_VENONAT 48
#define SPECIES_VENOMOTH 49
#define SPECIES_DIGLETT 50
#define SPECIES_DUGTRIO 51
#define SPECIES_MEOWTH 52
#define SPECIES_PERSIAN 53
#define SPECIES_PSYDUCK 54
#define SPECIES_GOLDUCK 55
#define SPECIES_MANKEY 56
#define SPECIES_PRIMEAPE 57
#define SPECIES_GROWLITHE 58
#define SPECIES_ARCANINE 59
#define SPECIES_POLIWAG 60
#define SPECIES_POLIWHIRL 61
#define SPECIES_POLIWRATH 62
#define SPECIES_ABRA 63
#define SPECIES_KADABRA 64
#define SPECIES_ALAKAZAM 65
#define SPECIES_MACHOP 66
#define SPECIES_MACHOKE 67
#define SPECIES_MACHAMP 68
#define SPECIES_BELLSPROUT 69
#define SPECIES_WEEPINBELL 70
#define SPECIES_VICTREEBEL 71
#define SPECIES_TENTACOOL 72
#define SPECIES_TENTACRUEL 73
#define SPECIES_GEODUDE 74
#define SPECIES_GRAVELER 75
#define SPECIES_GOLEM 76
#define SPECIES_PONYTA 77
#define SPECIES_RAPIDASH 78
#define SPECIES_SLOWPOKE 79
#define SPECIES_SLOWBRO 80
#define SPECIES_MAGNEMITE 81
#define SPECIES_MAGNETON 82
#define SPECIES_FARFETCHD 83
#define SPECIES_DODUO 84
#define SPECIES_DODRIO 85
#define SPECIES_SEEL 86
#define SPECIES_DEWGONG 87
#define SPECIES_GRIMER 88
#define SPECIES_MUK 89
#define SPECIES_SHELLDER 90
#define SPECIES_CLOYSTER 91
#define SPECIES_GASTLY 92
#define SPECIES_HAUNTER 93
#define SPECIES_GENGAR 94
#define SPECIES_ONIX 95
#define SPECIES_DROWZEE 96
#define SPECIES_HYPNO 97
#define SPECIES_KRABBY 98
#define SPECIES_KINGLER 99
#define SPECIES_VOLTORB 100
#define SPECIES_ELECTRODE 101
#define SPECIES_EXEGGCUTE 102
#define SPECIES_EXEGGUTOR 103
#define SPECIES_CUBONE 104
#define SPECIES_MAROWAK 105
#define SPECIES_HITMONLEE 106
#define SPECIES_HITMONCHAN 107
#define SPECIES_LICKITUNG 108
#define SPECIES_KOFFING 109
#define SPECIES_WEEZING 110
#define SPECIES_RHYHORN 111
#define SPECIES_RHYDON 112
#define SPECIES_CHANSEY 113
#define SPECIES_TANGELA 114
#define SPECIES_KANGASKHAN 115
#define SPECIES_HORSEA 116
#define SPECIES_SEADRA 117
#define SPECIES_GOLDEEN 118
#define SPECIES_SEAKING 119
#define SPECIES_STARYU 120
#define SPECIES_STARMIE 121
#define SPECIES_MR_MIME 122
#define SPECIES_SCYTHER 123
#define SPECIES_JYNX 124
#define SPECIES_ELECTABUZZ 125
#define SPECIES_MAGMAR 126
#define SPECIES_PINSIR 127
#define SPECIES_TAUROS 128
#define SPECIES_MAGIKARP 129
#define SPECIES_GYARADOS 130
#define SPECIES_LAPRAS 131
#define SPECIES_DITTO 132
#define SPECIES_EEVEE 133
#define SPECIES_VAPOREON 134
#define SPECIES_JOLTEON 135
#define SPECIES_FLAREON 136
#define SPECIES_PORYGON 137
#define SPECIES_OMANYTE 138
#define SPECIES_OMASTAR 139
#define SPECIES_KABUTO 140
#define SPECIES_KABUTOPS 141
#define SPECIES_AERODACTYL 142
#define SPECIES_SNORLAX 143
#define SPECIES_ARTICUNO 144
#define SPECIES_ZAPDOS 145
#define SPECIES_MOLTRES 146
#define SPECIES_DRATINI 147
#define SPECIES_DRAGONAIR 148
#define SPECIES_DRAGONITE 149
#define SPECIES_MEWTWO 150
#define SPECIES_MEW 151
#define SPECIES_CHIKORITA 152
#define SPECIES_BAYLEEF 153
#define SPECIES_MEGANIUM 154
#define SPECIES_CYNDAQUIL 155
#define SPECIES_QUILAVA 156
#define SPECIES_TYPHLOSION 157
#define SPECIES_TOTODILE 158
#define SPECIES_CROCONAW 159
#define SPECIES_FERALIGATR 160
#define SPECIES_SENTRET 161
#define SPECIES_FURRET 162
#define SPECIES_HOOTHOOT 163
#define SPECIES_NOCTOWL 164
#define SPECIES_LEDYBA 165
#define SPECIES_LEDIAN 166
#define SPECIES_SPINARAK 167
#define SPECIES_ARIADOS 168
#define SPECIES_CROBAT 169
#define SPECIES_CHINCHOU 170
#define SPECIES_LANTURN 171
#define SPECIES_PICHU 172
#define SPECIES_CLEFFA 173
#define SPECIES_IGGLYBUFF 174
#define SPECIES_TOGEPI 175
#define SPECIES_TOGETIC 176
#define SPECIES_NATU 177
#define SPECIES_XATU 178
#define SPECIES_MAREEP 179
#define SPECIES_FLAAFFY 180
#define SPECIES_AMPHAROS 181
#define SPECIES_BELLOSSOM 182
#define SPECIES_MARILL 183
#define SPECIES_AZUMARILL 184
#define SPECIES_SUDOWOODO 185
#define SPECIES_POLITOED 186
#define SPECIES_HOPPIP 187
#define SPECIES_SKIPLOOM 188
#define SPECIES_JUMPLUFF 189
#define SPECIES_AIPOM 190
#define SPECIES_SUNKERN 191
#define SPECIES_SUNFLORA 192
#define SPECIES_YANMA 193
#define SPECIES_WOOPER 194
#define SPECIES_QUAGSIRE 195
#define SPECIES_ESPEON 196
#define SPECIES_UMBREON 197
#define SPECIES_MURKROW 198
#define SPECIES_SLOWKING 199
#define SPECIES_MISDREAVUS 200
#define SPECIES_UNOWN 201
#define SPECIES_WOBBUFFET 202
#define SPECIES_GIRAFARIG 203
#define SPECIES_PINECO 204
#define SPECIES_FORRETRESS 205
#define SPECIES_DUNSPARCE 206
#define SPECIES_GLIGAR 207
#define SPECIES_STEELIX 208
#define SPECIES_SNUBBULL 209
#define SPECIES_GRANBULL 210
#define SPECIES_QWILFISH 211
#define SPECIES_SCIZOR 212
#define SPECIES_SHUCKLE 213
#define SPECIES_HERACROSS 214
#define SPECIES_SNEASEL 215
#define SPECIES_TEDDIURSA 216
#define SPECIES_URSARING 217
#define SPECIES_SLUGMA 218
#define SPECIES_MAGCARGO 219
#define SPECIES_SWINUB 220
#define SPECIES_PILOSWINE 221
#define SPECIES_CORSOLA 222
#define SPECIES_REMORAID 223
#define SPECIES_OCTILLERY 224
#define SPECIES_DELIBIRD 225
#define SPECIES_MANTINE 226
#define SPECIES_SKARMORY 227
#define SPECIES_HOUNDOUR 228
#define SPECIES_HOUNDOOM 229
#define SPECIES_KINGDRA 230
#define SPECIES_PHANPY 231
#define SPECIES_DONPHAN 232
#define SPECIES_PORYGON2 233
#define SPECIES_STANTLER 234
#define SPECIES_SMEARGLE 235
#define SPECIES_TYROGUE 236
#define SPECIES_HITMONTOP 237
#define SPECIES_SMOOCHUM 238
#define SPECIES_ELEKID 239
#define SPECIES_MAGBY 240
#define SPECIES_MILTANK 241
#define SPECIES_BLISSEY 242
#define SPECIES_RAIKOU 243
#define SPECIES_ENTEI 244
#define SPECIES_SUICUNE 245
#define SPECIES_LARVITAR 246
#define SPECIES_PUPITAR 247
#define SPECIES_TYRANITAR 248
#define SPECIES_LUGIA 249
#define SPECIES_HO_OH 250
#define SPECIES_CELEBI 251
#define SPECIES_TREECKO 252
#define SPECIES_GROVYLE 253
#define SPECIES_SCEPTILE 254
#define SPECIES_TORCHIC 255
#define SPECIES_COMBUSKEN 256
#define SPECIES_BLAZIKEN 257
#define SPECIES_MUDKIP 258
#define SPECIES_MARSHTOMP 259
#define SPECIES_SWAMPERT 260
#define SPECIES_POOCHYENA 261
#define SPECIES_MIGHTYENA 262
#define SPECIES_ZIGZAGOON 263
#define SPECIES_LINOONE 264
#define SPECIES_WURMPLE 265
#define SPECIES_SILCOON 266
#define SPECIES_BEAUTIFLY 267
#define SPECIES_CASCOON 268
#define SPECIES_DUSTOX 269
#define SPECIES_LOTAD 270
#define SPECIES_LOMBRE 271
#define SPECIES_LUDICOLO 272
#define SPECIES_SEEDOT 273
#define SPECIES_NUZLEAF 274
#define SPECIES_SHIFTRY 275
#define SPECIES_TAILLOW 276
#define SPECIES_SWELLOW 277
#define SPECIES_WINGULL 278
#define SPECIES_PELIPPER 279
#define SPECIES_RALTS 280
#define SPECIES_KIRLIA 281
#define SPECIES_GARDEVOIR 282
#define SPECIES_SURSKIT 283
#define SPECIES_MASQUERAIN 284
#define SPECIES_SHROOMISH 285
#define SPECIES_BRELOOM 286
#define SPECIES_SLAKOTH 287
#define SPECIES_VIGOROTH 288
#define SPECIES_SLAKING 289
#define SPECIES_NINCADA 290
#define SPECIES_NINJASK 291
#define SPECIES_SHEDINJA 292
#define SPECIES_WHISMUR 293
#define SPECIES_LOUDRED 294
#define SPECIES_EXPLOUD 295
#define SPECIES_MAKUHITA 296
#define SPECIES_HARIYAMA 297
#define SPECIES_AZURILL 298
#define SPECIES_NOSEPASS 299
#define SPECIES_SKITTY 300
#define SPECIES_DELCATTY 301
#define SPECIES_SABLEYE 302
#define SPECIES_MAWILE 303
#define SPECIES_ARON 304
#define SPECIES_LAIRON 305
#define SPECIES_AGGRON 306
#define SPECIES_MEDITITE 307
#define SPECIES_MEDICHAM 308
#define SPECIES_ELECTRIKE 309
#define SPECIES_MANECTRIC 310
#define SPECIES_PLUSLE 311
#define SPECIES_MINUN 312
#define SPECIES_VOLBEAT 313
#define SPECIES_ILLUMISE 314
#define SPECIES_ROSELIA 315
#define SPECIES_GULPIN 316
#define SPECIES_SWALOT 317
#define SPECIES_CARVANHA 318
#define SPECIES_SHARPEDO 319
#define SPECIES_WAILMER 320
#define SPECIES_WAILORD 321
#define SPECIES_NUMEL 322
#define SPECIES_CAMERUPT 323
#define SPECIES_TORKOAL 324
#define SPECIES_SPOINK 325
#define SPECIES_GRUMPIG 326
#define SPECIES_SPINDA 327
#define SPECIES_TRAPINCH 328
#define SPECIES_VIBRAVA 329
#define SPECIES_FLYGON 330
#define SPECIES_CACNEA 331
#define SPECIES_CACTURNE 332
#define SPECIES_SWABLU 333
#define SPECIES_ALTARIA 334
#define SPECIES_ZANGOOSE 335
#define SPECIES_SEVIPER 336
#define SPECIES_LUNATONE 337
#define SPECIES_SOLROCK 338
#define SPECIES_BARBOACH 339
#define SPECIES_WHISCASH 340
#define SPECIES_CORPHISH 341
#define SPECIES_CRAWDAUNT 342
#define SPECIES_BALTOY 343
#define SPECIES_CLAYDOL 344
#define SPECIES_LILEEP 345
#define SPECIES_CRADILY 346
#define SPECIES_ANORITH 347
#define SPECIES_ARMALDO 348
#define SPECIES_FEEBAS 349
#define SPECIES_MILOTIC 350
#define SPECIES_CASTFORM 351
#define SPECIES_KECLEON 352
#define SPECIES_SHUPPET 353
#define SPECIES_BANETTE 354
#define SPECIES_DUSKULL 355
#define SPECIES_DUSCLOPS 356
#define SPECIES_TROPIUS 357
#define SPECIES_CHIMECHO 358
#define SPECIES_ABSOL 359
#define SPECIES_WYNAUT 360
#define SPECIES_SNORUNT 361
#define SPECIES_GLALIE 362
#define SPECIES_SPHEAL 363
#define SPECIES_SEALEO 364
#define SPECIES_WALREIN 365
#define SPECIES_CLAMPERL 366
#define SPECIES_HUNTAIL 367
#define SPECIES_GOREBYSS 368
#define SPECIES_RELICANTH 369
#define SPECIES_LUVDISC 370
#define SPECIES_BAGON 371
#define SPECIES_SHELGON 372
#define SPECIES_SALAMENCE 373
#define SPECIES_BELDUM 374
#define SPECIES_METANG 375
#define SPECIES_METAGROSS 376
#define SPECIES_REGIROCK 377
#define SPECIES_REGICE 378
#define SPECIES_REGISTEEL 379
#define SPECIES_LATIAS 380
#define SPECIES_LATIOS 381
#define SPECIES_KYOGRE 382
#define SPECIES_GROUDON 383
#define SPECIES_RAYQUAZA 384
#define SPECIES_JIRACHI 385
#define SPECIES_DEOXYS 386
#define SPECIES_TURTWIG 387
#define SPECIES_GROTLE 388
#define SPECIES_TORTERRA 389
#define SPECIES_CHIMCHAR 390
#define SPECIES_MONFERNO 391
#define SPECIES_INFERNAPE 392
#define SPECIES_PIPLUP 393
#define SPECIES_PRINPLUP 394
#define SPECIES_EMPOLEON 395
#define SPECIES_STARLY 396
#define SPECIES_STARAVIA 397
#define SPECIES_STARAPTOR 398
#define SPECIES_BIDOOF 399
#define SPECIES_BIBAREL 400
#define SPECIES_KRICKETOT 401
#define SPECIES_KRICKETUNE 402
#define SPECIES_SHINX 403
#define SPECIES_LUXIO 404
#define SPECIES_LUXRAY 405
#define SPECIES_BUDEW 406
#define SPECIES_ROSERADE 407
#define SPECIES_CRANIDOS 408
#define SPECIES_RAMPARDOS 409
#define SPECIES_SHIELDON 410
#define SPECIES_BASTIODON 411
#define SPECIES_BURMY 412
#define SPECIES_WORMADAM 413
#define SPECIES_MOTHIM 414
#define SPECIES_COMBEE 415
#define SPECIES_VESPIQUEN 416
#define SPECIES_PACHIRISU 417
#define SPECIES_BUIZEL 418
#define SPECIES_FLOATZEL 419
#define SPECIES_CHERUBI 420
#define SPECIES_CHERRIM 421
#define SPECIES_SHELLOS 422
#define SPECIES_GASTRODON 423
#define SPECIES_AMBIPOM 424
#define SPECIES_DRIFLOON 425
#define SPECIES_DRIFBLIM 426
#define SPECIES_BUNEARY 427
#define SPECIES_LOPUNNY 428
#define SPECIES_MISMAGIUS 429
#define SPECIES_HONCHKROW 430
#define SPECIES_GLAMEOW 431
#define SPECIES_PURUGLY 432
#define SPECIES_CHINGLING 433
#define SPECIES_STUNKY 434
#define SPECIES_SKUNTANK 435
#define SPECIES_BRONZOR 436
#define SPECIES_BRONZONG 437
#define SPECIES_BONSLY 438
#define SPECIES_MIME_JR 439
#define SPECIES_HAPPINY 440
#define SPECIES_CHATOT 441
#define SPECIES_SPIRITOMB 442
#define SPECIES_GIBLE 443
#define SPECIES_GABITE 444
#define SPECIES_GARCHOMP 445
#define SPECIES_MUNCHLAX 446
#define SPECIES_RIOLU 447
#define SPECIES_LUCARIO 448
#define SPECIES_HIPPOPOTAS 449
#define SPECIES_HIPPOWDON 450
#define SPECIES_SKORUPI 451
#define SPECIES_DRAPION 452
#define SPECIES_CROAGUNK 453
#define SPECIES_TOXICROAK 454
#define SPECIES_CARNIVINE 455
#define SPECIES_FINNEON 456
#define SPECIES_LUMINEON 457
#define SPECIES_MANTYKE 458
#define SPECIES_SNOVER 459
#define SPECIES_ABOMASNOW 460
#define SPECIES_WEAVILE 461
#define SPECIES_MAGNEZONE 462
#define SPECIES_LICKILICKY 463
#define SPECIES_RHYPERIOR 464
#define SPECIES_TANGROWTH 465
#define SPECIES_ELECTIVIRE 466
#define SPECIES_MAGMORTAR 467
#define SPECIES_TOGEKISS 468
#define SPECIES_YANMEGA 469
#define SPECIES_LEAFEON 470
#define SPECIES_GLACEON 471
#define SPECIES_GLISCOR 472
#define SPECIES_MAMOSWINE 473
#define SPECIES_PORYGON_Z 474
#define SPECIES_GALLADE 475
#define SPECIES_PROBOPASS 476
#define SPECIES_DUSKNOIR 477
#define SPECIES_FROSLASS 478
#define SPECIES_ROTOM 479
#define SPECIES_UXIE 480
#define SPECIES_MESPRIT 481
#define SPECIES_AZELF 482
#define SPECIES_DIALGA 483
#define SPECIES_PALKIA 484
#define SPECIES_HEATRAN 485
#define SPECIES_REGIGIGAS 486
#define SPECIES_GIRATINA 487
#define SPECIES_CRESSELIA 488
#define SPECIES_PHIONE 489
#define SPECIES_MANAPHY 490
#define SPECIES_DARKRAI 491
#define SPECIES_SHAYMIN 492
#define SPECIES_ARCEUS 493
#define SPECIES_VICTINI 494
#define SPECIES_SNIVY 495
#define SPECIES_SERVINE 496
#define SPECIES_SERPERIOR 497
#define SPECIES_TEPIG 498
#define SPECIES_PIGNITE 499
#define SPECIES_EMBOAR 500
#define SPECIES_OSHAWOTT 501
#define SPECIES_DEWOTT 502
#define SPECIES_SAMUROTT 503
#define SPECIES_PATRAT 504
#define SPECIES_WATCHOG 505
#define SPECIES_LILLIPUP 506
#define SPECIES_HERDIER 507
#define SPECIES_STOUTLAND 508
#define SPECIES_PURRLOIN 509
#define SPECIES_LIEPARD 510
#define SPECIES_PANSAGE 511
#define SPECIES_SIMISAGE 512
#define SPECIES_PANSEAR 513
#define SPECIES_SIMISEAR 514
#define SPECIES_PANPOUR 515
#define SPECIES_SIMIPOUR 516
#define SPECIES_MUNNA 517
#define SPECIES_MUSHARNA 518
#define SPECIES_PIDOVE 519
#define SPECIES_TRANQUILL 520
#define SPECIES_UNFEZANT 521
#define SPECIES_BLITZLE 522
#define SPECIES_ZEBSTRIKA 523
#define SPECIES_ROGGENROLA 524
#define SPECIES_BOLDORE 525
#define SPECIES_GIGALITH 526
#define SPECIES_WOOBAT 527
#define SPECIES_SWOOBAT 528
#define SPECIES_DRILBUR 529
#define SPECIES_EXCADRILL 530
#define SPECIES_AUDINO 531
#define SPECIES_TIMBURR 532
#define SPECIES_GURDURR 533
#define SPECIES_CONKELDURR 534
#define SPECIES_TYMPOLE 535
#define SPECIES_PALPITOAD 536
#define SPECIES_SEISMITOAD 537
#define SPECIES_THROH 538
#define SPECIES_SAWK 539
#define SPECIES_SEWADDLE 540
#define SPECIES_SWADLOON 541
#define SPECIES_LEAVANNY 542
#define SPECIES_VENIPEDE 543
#define SPECIES_WHIRLIPEDE 544
#define SPECIES_SCOLIPEDE 545
#define SPECIES_COTTONEE 546
#define SPECIES_WHIMSICOTT 547
#define SPECIES_PETILIL 548
#define SPECIES_LILLIGANT 549
#define SPECIES_BASCULIN 550
#define SPECIES_SANDILE 551
#define SPECIES_KROKOROK 552
#define SPECIES_KROOKODILE 553
#define SPECIES_DARUMAKA 554
#define SPECIES_DARMANITAN 555
#define SPECIES_MARACTUS 556
#define SPECIES_DWEBBLE 557
#define SPECIES_CRUSTLE 558
#define SPECIES_SCRAGGY 559
#define SPECIES_SCRAFTY 560
#define SPECIES_SIGILYPH 561
#define SPECIES_YAMASK 562
#define SPECIES_COFAGRIGUS 563
#define SPECIES_TIRTOUGA 564
#define SPECIES_CARRACOSTA 565
#define SPECIES_ARCHEN 566
#define SPECIES_ARCHEOPS 567
#define SPECIES_TRUBBISH 568
#define SPECIES_GARBODOR 569
#define SPECIES_ZORUA 570
#define SPECIES_ZOROARK 571
#define SPECIES_MINCCINO 572
#define SPECIES_CINCCINO 573
#define SPECIES_GOTHITA 574
#define SPECIES_GOTHORITA 575
#define SPECIES_GOTHITELLE 576
#define SPECIES_SOLOSIS 577
#define SPECIES_DUOSION 578
#define SPECIES_REUNICLUS 579
#define SPECIES_DUCKLETT 580
#define SPECIES_SWANNA 581
#define SPECIES_VANILLITE 582
#define SPECIES_VANILLISH 583
#define SPECIES_VANILLUXE 584
#define SPECIES_DEERLING 585
#define SPECIES_SAWSBUCK 586
#define SPECIES_EMOLGA 587
#define SPECIES_KARRABLAST 588
#define SPECIES_ESCAVALIER 589
#define SPECIES_FOONGUS 590
#define SPECIES_AMOONGUSS 591
#define SPECIES_FRILLISH 592
#define SPECIES_JELLICENT 593
#define SPECIES_ALOMOMOLA 594
#define SPECIES_JOLTIK 595
#define SPECIES_GALVANTULA 596
#define SPECIES_FERROSEED 597
#define SPECIES_FERROTHORN 598
#define SPECIES_KLINK 599
#define SPECIES_KLANG 600
#define SPECIES_KLINKLANG 601
#define SPECIES_TYNAMO 602
#define SPECIES_EELEKTRIK 603
#define SPECIES_EELEKTROSS 604
#define SPECIES_ELGYEM 605
#define SPECIES_BEHEEYEM 606
#define SPECIES_LITWICK 607
#define SPECIES_LAMPENT 608
#define SPECIES_CHANDELURE 609
#define SPECIES_AXEW 610
#define SPECIES_FRAXURE 611
#define SPECIES_HAXORUS 612
#define SPECIES_CUBCHOO 613
#define SPECIES_BEARTIC 614
#define SPECIES_CRYOGONAL 615
#define SPECIES_SHELMET 616
#define SPECIES_ACCELGOR 617
#define SPECIES_STUNFISK 618
#define SPECIES_MIENFOO 619
#define SPECIES_MIENSHAO 620
#define SPECIES_DRUDDIGON 621
#define SPECIES_GOLETT 622
#define SPECIES_GOLURK 623
#define SPECIES_PAWNIARD 624
#define SPECIES_BISHARP 625
#define SPECIES_BOUFFALANT 626
#define SPECIES_RUFFLET 627
#define SPECIES_BRAVIARY 628
#define SPECIES_VULLABY 629
#define SPECIES_MANDIBUZZ 630
#define SPECIES_HEATMOR 631
#define SPECIES_DURANT 632
#define SPECIES_DEINO 633
#define SPECIES_ZWEILOUS 634
#define SPECIES_HYDREIGON 635
#define SPECIES_LARVESTA 636
#define SPECIES_VOLCARONA 637
#define SPECIES_COBALION 638
#define SPECIES_TERRAKION 639
#define SPECIES_VIRIZION 640
#define SPECIES_TORNADUS 641
#define SPECIES_THUNDURUS 642
#define SPECIES_RESHIRAM 643
#define SPECIES_ZEKROM 644
#define SPECIES_LANDORUS 645
#define SPECIES_KYUREM 646
#define SPECIES_KELDEO 647
#define SPECIES_MELOETTA 648
#define SPECIES_GENESECT 649
#define SPECIES_CHESPIN 650
#define SPECIES_QUILLADIN 651
#define SPECIES_CHESNAUGHT 652
#define SPECIES_FENNEKIN 653
#define SPECIES_BRAIXEN 654
#define SPECIES_DELPHOX 655
#define SPECIES_FROAKIE 656
#define SPECIES_FROGADIER 657
#define SPECIES_GRENINJA 658
#define SPECIES_BUNNELBY 659
#define SPECIES_DIGGERSBY 660
#define SPECIES_FLETCHLING 661
#define SPECIES_FLETCHINDER 662
#define SPECIES_TALONFLAME 663
#define SPECIES_SCATTERBUG 664
#define SPECIES_SPEWPA 665
#define SPECIES_VIVILLON 666 // Icy Snow Pattern
#define SPECIES_LITLEO 667
#define SPECIES_PYROAR 668
#define SPECIES_FLABEBE 669 // Red Flower
#define SPECIES_FLOETTE 670
#define SPECIES_FLORGES 671
#define SPECIES_SKIDDO 672
#define SPECIES_GOGOAT 673
#define SPECIES_PANCHAM 674
#define SPECIES_PANGORO 675
#define SPECIES_FURFROU 676
#define SPECIES_ESPURR 677
#define SPECIES_MEOWSTIC 678
#define SPECIES_HONEDGE 679
#define SPECIES_DOUBLADE 680
#define SPECIES_AEGISLASH 681
#define SPECIES_SPRITZEE 682
#define SPECIES_AROMATISSE 683
#define SPECIES_SWIRLIX 684
#define SPECIES_SLURPUFF 685
#define SPECIES_INKAY 686
#define SPECIES_MALAMAR 687
#define SPECIES_BINACLE 688
#define SPECIES_BARBARACLE 689
#define SPECIES_SKRELP 690
#define SPECIES_DRAGALGE 691
#define SPECIES_CLAUNCHER 692
#define SPECIES_CLAWITZER 693
#define SPECIES_HELIOPTILE 694
#define SPECIES_HELIOLISK 695
#define SPECIES_TYRUNT 696
#define SPECIES_TYRANTRUM 697
#define SPECIES_AMAURA 698
#define SPECIES_AURORUS 699
#define SPECIES_SYLVEON 700
#define SPECIES_HAWLUCHA 701
#define SPECIES_DEDENNE 702
#define SPECIES_CARBINK 703
#define SPECIES_GOOMY 704
#define SPECIES_SLIGGOO 705
#define SPECIES_GOODRA 706
#define SPECIES_KLEFKI 707
#define SPECIES_PHANTUMP 708
#define SPECIES_TREVENANT 709
#define SPECIES_PUMPKABOO 710
#define SPECIES_GOURGEIST 711
#define SPECIES_BERGMITE 712
#define SPECIES_AVALUGG 713
#define SPECIES_NOIBAT 714
#define SPECIES_NOIVERN 715
#define SPECIES_XERNEAS 716
#define SPECIES_YVELTAL 717
#define SPECIES_ZYGARDE 718
#define SPECIES_DIANCIE 719
#define SPECIES_HOOPA 720
#define SPECIES_VOLCANION 721
#define SPECIES_ROWLET 722
#define SPECIES_DARTRIX 723
#define SPECIES_DECIDUEYE 724
#define SPECIES_LITTEN 725
#define SPECIES_TORRACAT 726
#define SPECIES_INCINEROAR 727
#define SPECIES_POPPLIO 728
#define SPECIES_BRIONNE 729
#define SPECIES_PRIMARINA 730
#define SPECIES_PIKIPEK 731
#define SPECIES_TRUMBEAK 732
#define SPECIES_TOUCANNON 733
#define SPECIES_YUNGOOS 734
#define SPECIES_GUMSHOOS 735
#define SPECIES_GRUBBIN 736
#define SPECIES_CHARJABUG 737
#define SPECIES_VIKAVOLT 738
#define SPECIES_CRABRAWLER 739
#define SPECIES_CRABOMINABLE 740
#define SPECIES_ORICORIO 741
#define SPECIES_CUTIEFLY 742
#define SPECIES_RIBOMBEE 743
#define SPECIES_ROCKRUFF 744
#define SPECIES_LYCANROC 745
#define SPECIES_WISHIWASHI 746
#define SPECIES_MAREANIE 747
#define SPECIES_TOXAPEX 748
#define SPECIES_MUDBRAY 749
#define SPECIES_MUDSDALE 750
#define SPECIES_DEWPIDER 751
#define SPECIES_ARAQUANID 752
#define SPECIES_FOMANTIS 753
#define SPECIES_LURANTIS 754
#define SPECIES_MORELULL 755
#define SPECIES_SHIINOTIC 756
#define SPECIES_SALANDIT 757
#define SPECIES_SALAZZLE 758
#define SPECIES_STUFFUL 759
#define SPECIES_BEWEAR 760
#define SPECIES_BOUNSWEET 761
#define SPECIES_STEENEE 762
#define SPECIES_TSAREENA 763
#define SPECIES_COMFEY 764
#define SPECIES_ORANGURU 765
#define SPECIES_PASSIMIAN 766
#define SPECIES_WIMPOD 767
#define SPECIES_GOLISOPOD 768
#define SPECIES_SANDYGAST 769
#define SPECIES_PALOSSAND 770
#define SPECIES_PYUKUMUKU 771
#define SPECIES_TYPE_NULL 772
#define SPECIES_SILVALLY 773
#define SPECIES_MINIOR 774
#define SPECIES_KOMALA 775
#define SPECIES_TURTONATOR 776
#define SPECIES_TOGEDEMARU 777
#define SPECIES_MIMIKYU 778
#define SPECIES_BRUXISH 779
#define SPECIES_DRAMPA 780
#define SPECIES_DHELMISE 781
#define SPECIES_JANGMO_O 782
#define SPECIES_HAKAMO_O 783
#define SPECIES_KOMMO_O 784
#define SPECIES_TAPU_KOKO 785
#define SPECIES_TAPU_LELE 786
#define SPECIES_TAPU_BULU 787
#define SPECIES_TAPU_FINI 788
#define SPECIES_COSMOG 789
#define SPECIES_COSMOEM 790
#define SPECIES_SOLGALEO 791
#define SPECIES_LUNALA 792
#define SPECIES_NIHILEGO 793
#define SPECIES_BUZZWOLE 794
#define SPECIES_PHEROMOSA 795
#define SPECIES_XURKITREE 796
#define SPECIES_CELESTEELA 797
#define SPECIES_KARTANA 798
#define SPECIES_GUZZLORD 799
#define SPECIES_NECROZMA 800
#define SPECIES_MAGEARNA 801
#define SPECIES_MARSHADOW 802
#define SPECIES_POIPOLE 803
#define SPECIES_NAGANADEL 804
#define SPECIES_STAKATAKA 805
#define SPECIES_BLACEPHALON 806
#define SPECIES_ZERAORA 807
#define SPECIES_MELTAN 808
#define SPECIES_MELMETAL 809
#define SPECIES_GROOKEY 810
#define SPECIES_THWACKEY 811
#define SPECIES_RILLABOOM 812
#define SPECIES_SCORBUNNY 813
#define SPECIES_RABOOT 814
#define SPECIES_CINDERACE 815
#define SPECIES_SOBBLE 816
#define SPECIES_DRIZZILE 817
#define SPECIES_INTELEON 818
#define SPECIES_SKWOVET 819
#define SPECIES_GREEDENT 820
#define SPECIES_ROOKIDEE 821
#define SPECIES_CORVISQUIRE 822
#define SPECIES_CORVIKNIGHT 823
#define SPECIES_BLIPBUG 824
#define SPECIES_DOTTLER 825
#define SPECIES_ORBEETLE 826
#define SPECIES_NICKIT 827
#define SPECIES_THIEVUL 828
#define SPECIES_GOSSIFLEUR 829
#define SPECIES_ELDEGOSS 830
#define SPECIES_WOOLOO 831
#define SPECIES_DUBWOOL 832
#define SPECIES_CHEWTLE 833
#define SPECIES_DREDNAW 834
#define SPECIES_YAMPER 835
#define SPECIES_BOLTUND 836
#define SPECIES_ROLYCOLY 837
#define SPECIES_CARKOL 838
#define SPECIES_COALOSSAL 839
#define SPECIES_APPLIN 840
#define SPECIES_FLAPPLE 841
#define SPECIES_APPLETUN 842
#define SPECIES_SILICOBRA 843
#define SPECIES_SANDACONDA 844
#define SPECIES_CRAMORANT 845
#define SPECIES_ARROKUDA 846
#define SPECIES_BARRASKEWDA 847
#define SPECIES_TOXEL 848
#define SPECIES_TOXTRICITY 849
#define SPECIES_SIZZLIPEDE 850
#define SPECIES_CENTISKORCH 851
#define SPECIES_CLOBBOPUS 852
#define SPECIES_GRAPPLOCT 853
#define SPECIES_SINISTEA 854
#define SPECIES_POLTEAGEIST 855
#define SPECIES_HATENNA 856
#define SPECIES_HATTREM 857
#define SPECIES_HATTERENE 858
#define SPECIES_IMPIDIMP 859
#define SPECIES_MORGREM 860
#define SPECIES_GRIMMSNARL 861
#define SPECIES_OBSTAGOON 862
#define SPECIES_PERRSERKER 863
#define SPECIES_CURSOLA 864
#define SPECIES_SIRFETCHD 865
#define SPECIES_MR_RIME 866
#define SPECIES_RUNERIGUS 867
#define SPECIES_MILCERY 868
#define SPECIES_ALCREMIE 869
#define SPECIES_FALINKS 870
#define SPECIES_PINCURCHIN 871
#define SPECIES_SNOM 872
#define SPECIES_FROSMOTH 873
#define SPECIES_STONJOURNER 874
#define SPECIES_EISCUE 875
#define SPECIES_INDEEDEE 876
#define SPECIES_MORPEKO 877
#define SPECIES_CUFANT 878
#define SPECIES_COPPERAJAH 879
#define SPECIES_DRACOZOLT 880
#define SPECIES_ARCTOZOLT 881
#define SPECIES_DRACOVISH 882
#define SPECIES_ARCTOVISH 883
#define SPECIES_DURALUDON 884
#define SPECIES_DREEPY 885
#define SPECIES_DRAKLOAK 886
#define SPECIES_DRAGAPULT 887
#define SPECIES_ZACIAN 888
#define SPECIES_ZAMAZENTA 889
#define SPECIES_ETERNATUS 890
#define SPECIES_KUBFU 891
#define SPECIES_URSHIFU 892
#define SPECIES_ZARUDE 893
#define SPECIES_REGIELEKI 894
#define SPECIES_REGIDRAGO 895
#define SPECIES_GLASTRIER 896
#define SPECIES_SPECTRIER 897
#define SPECIES_CALYREX 898

#define FORMS_START SPECIES_CALYREX

// Megas
#define SPECIES_VENUSAUR_MEGA                FORMS_START + 1
#define SPECIES_CHARIZARD_MEGA_X             FORMS_START + 2
#define SPECIES_CHARIZARD_MEGA_Y             FORMS_START + 3
#define SPECIES_BLASTOISE_MEGA               FORMS_START + 4
#define SPECIES_BEEDRILL_MEGA                FORMS_START + 5
#define SPECIES_PIDGEOT_MEGA                 FORMS_START + 6
#define SPECIES_ALAKAZAM_MEGA                FORMS_START + 7
#define SPECIES_SLOWBRO_MEGA                 FORMS_START + 8
#define SPECIES_GENGAR_MEGA                  FORMS_START + 9
#define SPECIES_KANGASKHAN_MEGA              FORMS_START + 10
#define SPECIES_PINSIR_MEGA                  FORMS_START + 11
#define SPECIES_GYARADOS_MEGA                FORMS_START + 12
#define SPECIES_AERODACTYL_MEGA              FORMS_START + 13
#define SPECIES_MEWTWO_MEGA_X                FORMS_START + 14
#define SPECIES_MEWTWO_MEGA_Y                FORMS_START + 15
#define SPECIES_AMPHAROS_MEGA                FORMS_START + 16
#define SPECIES_STEELIX_MEGA                 FORMS_START + 17
#define SPECIES_SCIZOR_MEGA                  FORMS_START + 18
#define SPECIES_HERACROSS_MEGA               FORMS_START + 19
#define SPECIES_HOUNDOOM_MEGA                FORMS_START + 20
#define SPECIES_TYRANITAR_MEGA               FORMS_START + 21
#define SPECIES_SCEPTILE_MEGA                FORMS_START + 22
#define SPECIES_BLAZIKEN_MEGA                FORMS_START + 23
#define SPECIES_SWAMPERT_MEGA                FORMS_START + 24
#define SPECIES_GARDEVOIR_MEGA               FORMS_START + 25
#define SPECIES_SABLEYE_MEGA                 FORMS_START + 26
#define SPECIES_MAWILE_MEGA                  FORMS_START + 27
#define SPECIES_AGGRON_MEGA                  FORMS_START + 28
#define SPECIES_MEDICHAM_MEGA                FORMS_START + 29
#define SPECIES_MANECTRIC_MEGA               FORMS_START + 30
#define SPECIES_SHARPEDO_MEGA                FORMS_START + 31
#define SPECIES_CAMERUPT_MEGA                FORMS_START + 32
#define SPECIES_ALTARIA_MEGA                 FORMS_START + 33
#define SPECIES_BANETTE_MEGA                 FORMS_START + 34
#define SPECIES_ABSOL_MEGA                   FORMS_START + 35
#define SPECIES_GLALIE_MEGA                  FORMS_START + 36
#define SPECIES_SALAMENCE_MEGA               FORMS_START + 37
#define SPECIES_METAGROSS_MEGA               FORMS_START + 38
#define SPECIES_LATIAS_MEGA                  FORMS_START + 39
#define SPECIES_LATIOS_MEGA                  FORMS_START + 40
#define SPECIES_LOPUNNY_MEGA                 FORMS_START + 41
#define SPECIES_GARCHOMP_MEGA                FORMS_START + 42
#define SPECIES_LUCARIO_MEGA                 FORMS_START + 43
#define SPECIES_ABOMASNOW_MEGA               FORMS_START + 44
#define SPECIES_GALLADE_MEGA                 FORMS_START + 45
#define SPECIES_AUDINO_MEGA                  FORMS_START + 46
#define SPECIES_DIANCIE_MEGA                 FORMS_START + 47

// Special Mega + Primals
#define SPECIES_RAYQUAZA_MEGA                FORMS_START + 48
#define SPECIES_KYOGRE_PRIMAL                FORMS_START + 49
#define SPECIES_GROUDON_PRIMAL               FORMS_START + 50

// Alolan Forms
#define SPECIES_RATTATA_ALOLAN               FORMS_START + 51
#define SPECIES_RATICATE_ALOLAN              FORMS_START + 52
#define SPECIES_RAICHU_ALOLAN                FORMS_START + 53
#define SPECIES_SANDSHREW_ALOLAN             FORMS_START + 54
#define SPECIES_SANDSLASH_ALOLAN             FORMS_START + 55
#define SPECIES_VULPIX_ALOLAN                FORMS_START + 56
#define SPECIES_NINETALES_ALOLAN             FORMS_START + 57
#define SPECIES_DIGLETT_ALOLAN               FORMS_START + 58
#define SPECIES_DUGTRIO_ALOLAN               FORMS_START + 59
#define SPECIES_MEOWTH_ALOLAN                FORMS_START + 60
#define SPECIES_PERSIAN_ALOLAN               FORMS_START + 61
#define SPECIES_GEODUDE_ALOLAN               FORMS_START + 62
#define SPECIES_GRAVELER_ALOLAN              FORMS_START + 63
#define SPECIES_GOLEM_ALOLAN                 FORMS_START + 64
#define SPECIES_GRIMER_ALOLAN                FORMS_START + 65
#define SPECIES_MUK_ALOLAN                   FORMS_START + 66
#define SPECIES_EXEGGUTOR_ALOLAN             FORMS_START + 67
#define SPECIES_MAROWAK_ALOLAN               FORMS_START + 68

// Galarian Forms
#define SPECIES_MEOWTH_GALARIAN              FORMS_START + 69
#define SPECIES_PONYTA_GALARIAN              FORMS_START + 70
#define SPECIES_RAPIDASH_GALARIAN            FORMS_START + 71
#define SPECIES_SLOWPOKE_GALARIAN            FORMS_START + 72
#define SPECIES_SLOWBRO_GALARIAN             FORMS_START + 73
#define SPECIES_FARFETCHD_GALARIAN           FORMS_START + 74
#define SPECIES_WEEZING_GALARIAN             FORMS_START + 75
#define SPECIES_MR_MIME_GALARIAN             FORMS_START + 76
#define SPECIES_ARTICUNO_GALARIAN            FORMS_START + 77
#define SPECIES_ZAPDOS_GALARIAN              FORMS_START + 78
#define SPECIES_MOLTRES_GALARIAN             FORMS_START + 79
#define SPECIES_SLOWKING_GALARIAN            FORMS_START + 80
#define SPECIES_CORSOLA_GALARIAN             FORMS_START + 81
#define SPECIES_ZIGZAGOON_GALARIAN           FORMS_START + 82
#define SPECIES_LINOONE_GALARIAN             FORMS_START + 83
#define SPECIES_DARUMAKA_GALARIAN            FORMS_START + 84
#define SPECIES_DARMANITAN_GALARIAN          FORMS_START + 85
#define SPECIES_YAMASK_GALARIAN              FORMS_START + 86
#define SPECIES_STUNFISK_GALARIAN            FORMS_START + 87

// Misc Forms

// Cosplay Pikachu
#define SPECIES_PIKACHU_COSPLAY              FORMS_START + 88
#define SPECIES_PIKACHU_ROCK_STAR            FORMS_START + 89
#define SPECIES_PIKACHU_BELLE                FORMS_START + 90
#define SPECIES_PIKACHU_POP_STAR             FORMS_START + 91
#define SPECIES_PIKACHU_PH_D                 FORMS_START + 92
#define SPECIES_PIKACHU_LIBRE                FORMS_START + 93

// Cap Pikachu
#define SPECIES_PIKACHU_ORIGINAL_CAP         FORMS_START + 94
#define SPECIES_PIKACHU_HOENN_CAP            FORMS_START + 95
#define SPECIES_PIKACHU_SINNOH_CAP           FORMS_START + 96
#define SPECIES_PIKACHU_UNOVA_CAP            FORMS_START + 97
#define SPECIES_PIKACHU_KALOS_CAP            FORMS_START + 98
#define SPECIES_PIKACHU_ALOLA_CAP            FORMS_START + 99
#define SPECIES_PIKACHU_PARTNER_CAP          FORMS_START + 100
#define SPECIES_PIKACHU_WORLD_CAP            FORMS_START + 101

// Pichu
#define SPECIES_PICHU_SPIKY_EARED            FORMS_START + 102

// Unown
#define SPECIES_UNOWN_B                      FORMS_START + 103
#define SPECIES_UNOWN_C                      FORMS_START + 104
#define SPECIES_UNOWN_D                      FORMS_START + 105
#define SPECIES_UNOWN_E                      FORMS_START + 106
#define SPECIES_UNOWN_F                      FORMS_START + 107
#define SPECIES_UNOWN_G                      FORMS_START + 108
#define SPECIES_UNOWN_H                      FORMS_START + 109
#define SPECIES_UNOWN_I                      FORMS_START + 110
#define SPECIES_UNOWN_J                      FORMS_START + 111
#define SPECIES_UNOWN_K                      FORMS_START + 112
#define SPECIES_UNOWN_L                      FORMS_START + 113
#define SPECIES_UNOWN_M                      FORMS_START + 114
#define SPECIES_UNOWN_N                      FORMS_START + 115
#define SPECIES_UNOWN_O                      FORMS_START + 116
#define SPECIES_UNOWN_P                      FORMS_START + 117
#define SPECIES_UNOWN_Q                      FORMS_START + 118
#define SPECIES_UNOWN_R                      FORMS_START + 119
#define SPECIES_UNOWN_S                      FORMS_START + 120
#define SPECIES_UNOWN_T                      FORMS_START + 121
#define SPECIES_UNOWN_U                      FORMS_START + 122
#define SPECIES_UNOWN_V                      FORMS_START + 123
#define SPECIES_UNOWN_W                      FORMS_START + 124
#define SPECIES_UNOWN_X                      FORMS_START + 125
#define SPECIES_UNOWN_Y                      FORMS_START + 126
#define SPECIES_UNOWN_Z                      FORMS_START + 127
#define SPECIES_UNOWN_EMARK                  FORMS_START + 128
#define SPECIES_UNOWN_QMARK                  FORMS_START + 129

// Castform
#define SPECIES_CASTFORM_SUNNY               FORMS_START + 130
#define SPECIES_CASTFORM_RAINY               FORMS_START + 131
#define SPECIES_CASTFORM_SNOWY               FORMS_START + 132

// Deoxys
#define SPECIES_DEOXYS_ATTACK                FORMS_START + 133
#define SPECIES_DEOXYS_DEFENSE               FORMS_START + 134
#define SPECIES_DEOXYS_SPEED                 FORMS_START + 135

// Burmy
#define SPECIES_BURMY_SANDY_CLOAK            FORMS_START + 136
#define SPECIES_BURMY_TRASH_CLOAK            FORMS_START + 137

// Wormadam
#define SPECIES_WORMADAM_SANDY_CLOAK         FORMS_START + 138
#define SPECIES_WORMADAM_TRASH_CLOAK         FORMS_START + 139

// Cherrim
#define SPECIES_CHERRIM_SUNSHINE             FORMS_START + 140

// Shellos
#define SPECIES_SHELLOS_EAST_SEA             FORMS_START + 141

// Gastrodon
#define SPECIES_GASTRODON_EAST_SEA           FORMS_START + 142

// Rotom
#define SPECIES_ROTOM_HEAT                   FORMS_START + 143
#define SPECIES_ROTOM_WASH                   FORMS_START + 144
#define SPECIES_ROTOM_FROST                  FORMS_START + 145
#define SPECIES_ROTOM_FAN                    FORMS_START + 146
#define SPECIES_ROTOM_MOW                    FORMS_START + 147

// Giratina
#define SPECIES_GIRATINA_ORIGIN              FORMS_START + 148

// Shaymin
#define SPECIES_SHAYMIN_SKY                  FORMS_START + 149

// Arceus
#define SPECIES_ARCEUS_FIGHTING              FORMS_START + 150
#define SPECIES_ARCEUS_FLYING                FORMS_START + 151
#define SPECIES_ARCEUS_POISON                FORMS_START + 152
#define SPECIES_ARCEUS_GROUND                FORMS_START + 153
#define SPECIES_ARCEUS_ROCK                  FORMS_START + 154
#define SPECIES_ARCEUS_BUG                   FORMS_START + 155
#define SPECIES_ARCEUS_GHOST                 FORMS_START + 156
#define SPECIES_ARCEUS_STEEL                 FORMS_START + 157
#define SPECIES_ARCEUS_FIRE                  FORMS_START + 158
#define SPECIES_ARCEUS_WATER                 FORMS_START + 159
#define SPECIES_ARCEUS_GRASS                 FORMS_START + 160
#define SPECIES_ARCEUS_ELECTRIC              FORMS_START + 161
#define SPECIES_ARCEUS_PSYCHIC               FORMS_START + 162
#define SPECIES_ARCEUS_ICE                   FORMS_START + 163
#define SPECIES_ARCEUS_DRAGON                FORMS_START + 164
#define SPECIES_ARCEUS_DARK                  FORMS_START + 165
#define SPECIES_ARCEUS_FAIRY                 FORMS_START + 166

// Basculin
#define SPECIES_BASCULIN_BLUE_STRIPED        FORMS_START + 167

// Darmanitan
#define SPECIES_DARMANITAN_ZEN_MODE          FORMS_START + 168
#define SPECIES_DARMANITAN_ZEN_MODE_GALARIAN FORMS_START + 169

// Deerling
#define SPECIES_DEERLING_SUMMER              FORMS_START + 170
#define SPECIES_DEERLING_AUTUMN              FORMS_START + 171
#define SPECIES_DEERLING_WINTER              FORMS_START + 172

// Sawsbuck
#define SPECIES_SAWSBUCK_SUMMER              FORMS_START + 173
#define SPECIES_SAWSBUCK_AUTUMN              FORMS_START + 174
#define SPECIES_SAWSBUCK_WINTER              FORMS_START + 175

// Therian Forms
#define SPECIES_TORNADUS_THERIAN             FORMS_START + 176
#define SPECIES_THUNDURUS_THERIAN            FORMS_START + 177
#define SPECIES_LANDORUS_THERIAN             FORMS_START + 178

// Kyurem
#define SPECIES_KYUREM_WHITE                 FORMS_START + 179
#define SPECIES_KYUREM_BLACK                 FORMS_START + 180

// Keldeo
#define SPECIES_KELDEO_RESOLUTE              FORMS_START + 181

// Meloetta
#define SPECIES_MELOETTA_PIROUETTE           FORMS_START + 182

// Genesect
#define SPECIES_GENESECT_DOUSE_DRIVE         FORMS_START + 183
#define SPECIES_GENESECT_SHOCK_DRIVE         FORMS_START + 184
#define SPECIES_GENESECT_BURN_DRIVE          FORMS_START + 185
#define SPECIES_GENESECT_CHILL_DRIVE         FORMS_START + 186

// Greninja
#define SPECIES_GRENINJA_BATTLE_BOND         FORMS_START + 187
#define SPECIES_GRENINJA_ASH                 FORMS_START + 188

// Vivillon
#define SPECIES_VIVILLON_POLAR               FORMS_START + 189
#define SPECIES_VIVILLON_TUNDRA              FORMS_START + 190
#define SPECIES_VIVILLON_CONTINENTAL         FORMS_START + 191
#define SPECIES_VIVILLON_GARDEN              FORMS_START + 192
#define SPECIES_VIVILLON_ELEGANT             FORMS_START + 193
#define SPECIES_VIVILLON_MEADOW              FORMS_START + 194
#define SPECIES_VIVILLON_MODERN              FORMS_START + 195
#define SPECIES_VIVILLON_MARINE              FORMS_START + 196
#define SPECIES_VIVILLON_ARCHIPELAGO         FORMS_START + 197
#define SPECIES_VIVILLON_HIGH_PLAINS         FORMS_START + 198
#define SPECIES_VIVILLON_SANDSTORM           FORMS_START + 199
#define SPECIES_VIVILLON_RIVER               FORMS_START + 200
#define SPECIES_VIVILLON_MONSOON             FORMS_START + 201
#define SPECIES_VIVILLON_SAVANNA             FORMS_START + 202
#define SPECIES_VIVILLON_SUN                 FORMS_START + 203
#define SPECIES_VIVILLON_OCEAN               FORMS_START + 204
#define SPECIES_VIVILLON_JUNGLE              FORMS_START + 205
#define SPECIES_VIVILLON_FANCY               FORMS_START + 206
#define SPECIES_VIVILLON_POKE_BALL           FORMS_START + 207

// Flabébé
#define SPECIES_FLABEBE_YELLOW_FLOWER        FORMS_START + 208
#define SPECIES_FLABEBE_ORANGE_FLOWER        FORMS_START + 209
#define SPECIES_FLABEBE_BLUE_FLOWER          FORMS_START + 210
#define SPECIES_FLABEBE_WHITE_FLOWER         FORMS_START + 211

// Floette
#define SPECIES_FLOETTE_YELLOW_FLOWER        FORMS_START + 212
#define SPECIES_FLOETTE_ORANGE_FLOWER        FORMS_START + 213
#define SPECIES_FLOETTE_BLUE_FLOWER          FORMS_START + 214
#define SPECIES_FLOETTE_WHITE_FLOWER         FORMS_START + 215
#define SPECIES_FLOETTE_ETERNAL_FLOWER       FORMS_START + 216

// Florges
#define SPECIES_FLORGES_YELLOW_FLOWER        FORMS_START + 217
#define SPECIES_FLORGES_ORANGE_FLOWER        FORMS_START + 218
#define SPECIES_FLORGES_BLUE_FLOWER          FORMS_START + 219
#define SPECIES_FLORGES_WHITE_FLOWER         FORMS_START + 220

// Furfrou
#define SPECIES_FURFROU_HEART_TRIM           FORMS_START + 221
#define SPECIES_FURFROU_STAR_TRIM            FORMS_START + 222
#define SPECIES_FURFROU_DIAMOND_TRIM         FORMS_START + 223
#define SPECIES_FURFROU_DEBUTANTE_TRIM       FORMS_START + 224
#define SPECIES_FURFROU_MATRON_TRIM          FORMS_START + 225
#define SPECIES_FURFROU_DANDY_TRIM           FORMS_START + 226
#define SPECIES_FURFROU_LA_REINE_TRIM        FORMS_START + 227
#define SPECIES_FURFROU_KABUKI_TRIM          FORMS_START + 228
#define SPECIES_FURFROU_PHARAOH_TRIM         FORMS_START + 229

// Meowstic
#define SPECIES_MEOWSTIC_FEMALE              FORMS_START + 230

// Aegislash
#define SPECIES_AEGISLASH_BLADE              FORMS_START + 231

// Pumpkaboo
#define SPECIES_PUMPKABOO_SMALL              FORMS_START + 232
#define SPECIES_PUMPKABOO_LARGE              FORMS_START + 233
#define SPECIES_PUMPKABOO_SUPER              FORMS_START + 234

// Gourgeist
#define SPECIES_GOURGEIST_SMALL              FORMS_START + 235
#define SPECIES_GOURGEIST_LARGE              FORMS_START + 236
#define SPECIES_GOURGEIST_SUPER              FORMS_START + 237

// Xerneas
#define SPECIES_XERNEAS_ACTIVE               FORMS_START + 238

// Zygarde
#define SPECIES_ZYGARDE_10                   FORMS_START + 239
#define SPECIES_ZYGARDE_10_POWER_CONSTRUCT   FORMS_START + 240
#define SPECIES_ZYGARDE_50_POWER_CONSTRUCT   FORMS_START + 241
#define SPECIES_ZYGARDE_COMPLETE             FORMS_START + 242

// Hoopa
#define SPECIES_HOOPA_UNBOUND                FORMS_START + 243

// Oricorio
#define SPECIES_ORICORIO_POM_POM             FORMS_START + 244
#define SPECIES_ORICORIO_PAU                 FORMS_START + 245
#define SPECIES_ORICORIO_SENSU               FORMS_START + 246

// Rockruff
#define SPECIES_ROCKRUFF_OWN_TEMPO           FORMS_START + 247

// Lycanroc
#define SPECIES_LYCANROC_MIDNIGHT            FORMS_START + 248
#define SPECIES_LYCANROC_DUSK                FORMS_START + 249

// Wishiwashi
#define SPECIES_WISHIWASHI_SCHOOL            FORMS_START + 250

// Silvally
#define SPECIES_SILVALLY_FIGHTING            FORMS_START + 251
#define SPECIES_SILVALLY_FLYING              FORMS_START + 252
#define SPECIES_SILVALLY_POISON              FORMS_START + 253
#define SPECIES_SILVALLY_GROUND              FORMS_START + 254
#define SPECIES_SILVALLY_ROCK                FORMS_START + 255
#define SPECIES_SILVALLY_BUG                 FORMS_START + 256
#define SPECIES_SILVALLY_GHOST               FORMS_START + 257
#define SPECIES_SILVALLY_STEEL               FORMS_START + 258
#define SPECIES_SILVALLY_FIRE                FORMS_START + 259
#define SPECIES_SILVALLY_WATER               FORMS_START + 260
#define SPECIES_SILVALLY_GRASS               FORMS_START + 261
#define SPECIES_SILVALLY_ELECTRIC            FORMS_START + 262
#define SPECIES_SILVALLY_PSYCHIC             FORMS_START + 263
#define SPECIES_SILVALLY_ICE                 FORMS_START + 264
#define SPECIES_SILVALLY_DRAGON              FORMS_START + 265
#define SPECIES_SILVALLY_DARK                FORMS_START + 266
#define SPECIES_SILVALLY_FAIRY               FORMS_START + 267

// Minior
#define SPECIES_MINIOR_METEOR_ORANGE         FORMS_START + 268
#define SPECIES_MINIOR_METEOR_YELLOW         FORMS_START + 269
#define SPECIES_MINIOR_METEOR_GREEN          FORMS_START + 270
#define SPECIES_MINIOR_METEOR_BLUE           FORMS_START + 271
#define SPECIES_MINIOR_METEOR_INDIGO         FORMS_START + 272
#define SPECIES_MINIOR_METEOR_VIOLET         FORMS_START + 273
#define SPECIES_MINIOR_CORE_RED              FORMS_START + 274
#define SPECIES_MINIOR_CORE_ORANGE           FORMS_START + 275
#define SPECIES_MINIOR_CORE_YELLOW           FORMS_START + 276
#define SPECIES_MINIOR_CORE_GREEN            FORMS_START + 277
#define SPECIES_MINIOR_CORE_BLUE             FORMS_START + 278
#define SPECIES_MINIOR_CORE_INDIGO           FORMS_START + 279
#define SPECIES_MINIOR_CORE_VIOLET           FORMS_START + 280

// Mimikyu
#define SPECIES_MIMIKYU_BUSTED               FORMS_START + 281

// Necrozma
#define SPECIES_NECROZMA_DUSK_MANE           FORMS_START + 282
#define SPECIES_NECROZMA_DAWN_WINGS          FORMS_START + 283
#define SPECIES_NECROZMA_ULTRA               FORMS_START + 284

// Magearna
#define SPECIES_MAGEARNA_ORIGINAL_COLOR      FORMS_START + 285

// Cramorant
#define SPECIES_CRAMORANT_GULPING            FORMS_START + 286
#define SPECIES_CRAMORANT_GORGING            FORMS_START + 287

// Toxtricity
#define SPECIES_TOXTRICITY_LOW_KEY           FORMS_START + 288

// Sinistea
#define SPECIES_SINISTEA_ANTIQUE             FORMS_START + 289

// Polteageist
#define SPECIES_POLTEAGEIST_ANTIQUE          FORMS_START + 290

// Alcremie
#define SPECIES_ALCREMIE_RUBY_CREAM          FORMS_START + 291
#define SPECIES_ALCREMIE_MATCHA_CREAM        FORMS_START + 292
#define SPECIES_ALCREMIE_MINT_CREAM          FORMS_START + 293
#define SPECIES_ALCREMIE_LEMON_CREAM         FORMS_START + 294
#define SPECIES_ALCREMIE_SALTED_CREAM        FORMS_START + 295
#define SPECIES_ALCREMIE_RUBY_SWIRL          FORMS_START + 296
#define SPECIES_ALCREMIE_CARAMEL_SWIRL       FORMS_START + 297
#define SPECIES_ALCREMIE_RAINBOW_SWIRL       FORMS_START + 298

// Eiscue
#define SPECIES_EISCUE_NOICE_FACE            FORMS_START + 299

// Indeedee
#define SPECIES_INDEEDEE_FEMALE              FORMS_START + 300

// Morpeko
#define SPECIES_MORPEKO_HANGRY               FORMS_START + 301

// Zacian
#define SPECIES_ZACIAN_CROWNED_SWORD         FORMS_START + 302

// Zamazenta
#define SPECIES_ZAMAZENTA_CROWNED_SHIELD     FORMS_START + 303

// Eternatus
#define SPECIES_ETERNATUS_ETERNAMAX          FORMS_START + 304

// Urshifu
#define SPECIES_URSHIFU_RAPID_STRIKE_STYLE   FORMS_START + 305

// Zarude
#define SPECIES_ZARUDE_DADA                  FORMS_START + 306

// Calyrex
#define SPECIES_CALYREX_ICE_RIDER            FORMS_START + 307
#define SPECIES_CALYREX_SHADOW_RIDER         FORMS_START + 308

#define SPECIES_EGG SPECIES_CALYREX_SHADOW_RIDER + 1
#define NUM_SPECIES SPECIES_EGG

// National Dex Index Defines

#define NATIONAL_DEX_NONE 0
#define NATIONAL_DEX_BULBASAUR 1
#define NATIONAL_DEX_IVYSAUR 2
#define NATIONAL_DEX_VENUSAUR 3
#define NATIONAL_DEX_CHARMANDER 4
#define NATIONAL_DEX_CHARMELEON 5
#define NATIONAL_DEX_CHARIZARD 6
#define NATIONAL_DEX_SQUIRTLE 7
#define NATIONAL_DEX_WARTORTLE 8
#define NATIONAL_DEX_BLASTOISE 9
#define NATIONAL_DEX_CATERPIE 10
#define NATIONAL_DEX_METAPOD 11
#define NATIONAL_DEX_BUTTERFREE 12
#define NATIONAL_DEX_WEEDLE 13
#define NATIONAL_DEX_KAKUNA 14
#define NATIONAL_DEX_BEEDRILL 15
#define NATIONAL_DEX_PIDGEY 16
#define NATIONAL_DEX_PIDGEOTTO 17
#define NATIONAL_DEX_PIDGEOT 18
#define NATIONAL_DEX_RATTATA 19
#define NATIONAL_DEX_RATICATE 20
#define NATIONAL_DEX_SPEAROW 21
#define NATIONAL_DEX_FEAROW 22
#define NATIONAL_DEX_EKANS 23
#define NATIONAL_DEX_ARBOK 24
#define NATIONAL_DEX_PIKACHU 25
#define NATIONAL_DEX_RAICHU 26
#define NATIONAL_DEX_SANDSHREW 27
#define NATIONAL_DEX_SANDSLASH 28
#define NATIONAL_DEX_NIDORAN_F 29
#define NATIONAL_DEX_NIDORINA 30
#define NATIONAL_DEX_NIDOQUEEN 31
#define NATIONAL_DEX_NIDORAN_M 32
#define NATIONAL_DEX_NIDORINO 33
#define NATIONAL_DEX_NIDOKING 34
#define NATIONAL_DEX_CLEFAIRY 35
#define NATIONAL_DEX_CLEFABLE 36
#define NATIONAL_DEX_VULPIX 37
#define NATIONAL_DEX_NINETALES 38
#define NATIONAL_DEX_JIGGLYPUFF 39
#define NATIONAL_DEX_WIGGLYTUFF 40
#define NATIONAL_DEX_ZUBAT 41
#define NATIONAL_DEX_GOLBAT 42
#define NATIONAL_DEX_ODDISH 43
#define NATIONAL_DEX_GLOOM 44
#define NATIONAL_DEX_VILEPLUME 45
#define NATIONAL_DEX_PARAS 46
#define NATIONAL_DEX_PARASECT 47
#define NATIONAL_DEX_VENONAT 48
#define NATIONAL_DEX_VENOMOTH 49
#define NATIONAL_DEX_DIGLETT 50
#define NATIONAL_DEX_DUGTRIO 51
#define NATIONAL_DEX_MEOWTH 52
#define NATIONAL_DEX_PERSIAN 53
#define NATIONAL_DEX_PSYDUCK 54
#define NATIONAL_DEX_GOLDUCK 55
#define NATIONAL_DEX_MANKEY 56
#define NATIONAL_DEX_PRIMEAPE 57
#define NATIONAL_DEX_GROWLITHE 58
#define NATIONAL_DEX_ARCANINE 59
#define NATIONAL_DEX_POLIWAG 60
#define NATIONAL_DEX_POLIWHIRL 61
#define NATIONAL_DEX_POLIWRATH 62
#define NATIONAL_DEX_ABRA 63
#define NATIONAL_DEX_KADABRA 64
#define NATIONAL_DEX_ALAKAZAM 65
#define NATIONAL_DEX_MACHOP 66
#define NATIONAL_DEX_MACHOKE 67
#define NATIONAL_DEX_MACHAMP 68
#define NATIONAL_DEX_BELLSPROUT 69
#define NATIONAL_DEX_WEEPINBELL 70
#define NATIONAL_DEX_VICTREEBEL 71
#define NATIONAL_DEX_TENTACOOL 72
#define NATIONAL_DEX_TENTACRUEL 73
#define NATIONAL_DEX_GEODUDE 74
#define NATIONAL_DEX_GRAVELER 75
#define NATIONAL_DEX_GOLEM 76
#define NATIONAL_DEX_PONYTA 77
#define NATIONAL_DEX_RAPIDASH 78
#define NATIONAL_DEX_SLOWPOKE 79
#define NATIONAL_DEX_SLOWBRO 80
#define NATIONAL_DEX_MAGNEMITE 81
#define NATIONAL_DEX_MAGNETON 82
#define NATIONAL_DEX_FARFETCHD 83
#define NATIONAL_DEX_DODUO 84
#define NATIONAL_DEX_DODRIO 85
#define NATIONAL_DEX_SEEL 86
#define NATIONAL_DEX_DEWGONG 87
#define NATIONAL_DEX_GRIMER 88
#define NATIONAL_DEX_MUK 89
#define NATIONAL_DEX_SHELLDER 90
#define NATIONAL_DEX_CLOYSTER 91
#define NATIONAL_DEX_GASTLY 92
#define NATIONAL_DEX_HAUNTER 93
#define NATIONAL_DEX_GENGAR 94
#define NATIONAL_DEX_ONIX 95
#define NATIONAL_DEX_DROWZEE 96
#define NATIONAL_DEX_HYPNO 97
#define NATIONAL_DEX_KRABBY 98
#define NATIONAL_DEX_KINGLER 99
#define NATIONAL_DEX_VOLTORB 100
#define NATIONAL_DEX_ELECTRODE 101
#define NATIONAL_DEX_EXEGGCUTE 102
#define NATIONAL_DEX_EXEGGUTOR 103
#define NATIONAL_DEX_CUBONE 104
#define NATIONAL_DEX_MAROWAK 105
#define NATIONAL_DEX_HITMONLEE 106
#define NATIONAL_DEX_HITMONCHAN 107
#define NATIONAL_DEX_LICKITUNG 108
#define NATIONAL_DEX_KOFFING 109
#define NATIONAL_DEX_WEEZING 110
#define NATIONAL_DEX_RHYHORN 111
#define NATIONAL_DEX_RHYDON 112
#define NATIONAL_DEX_CHANSEY 113
#define NATIONAL_DEX_TANGELA 114
#define NATIONAL_DEX_KANGASKHAN 115
#define NATIONAL_DEX_HORSEA 116
#define NATIONAL_DEX_SEADRA 117
#define NATIONAL_DEX_GOLDEEN 118
#define NATIONAL_DEX_SEAKING 119
#define NATIONAL_DEX_STARYU 120
#define NATIONAL_DEX_STARMIE 121
#define NATIONAL_DEX_MR_MIME 122
#define NATIONAL_DEX_SCYTHER 123
#define NATIONAL_DEX_JYNX 124
#define NATIONAL_DEX_ELECTABUZZ 125
#define NATIONAL_DEX_MAGMAR 126
#define NATIONAL_DEX_PINSIR 127
#define NATIONAL_DEX_TAUROS 128
#define NATIONAL_DEX_MAGIKARP 129
#define NATIONAL_DEX_GYARADOS 130
#define NATIONAL_DEX_LAPRAS 131
#define NATIONAL_DEX_DITTO 132
#define NATIONAL_DEX_EEVEE 133
#define NATIONAL_DEX_VAPOREON 134
#define NATIONAL_DEX_JOLTEON 135
#define NATIONAL_DEX_FLAREON 136
#define NATIONAL_DEX_PORYGON 137
#define NATIONAL_DEX_OMANYTE 138
#define NATIONAL_DEX_OMASTAR 139
#define NATIONAL_DEX_KABUTO 140
#define NATIONAL_DEX_KABUTOPS 141
#define NATIONAL_DEX_AERODACTYL 142
#define NATIONAL_DEX_SNORLAX 143
#define NATIONAL_DEX_ARTICUNO 144
#define NATIONAL_DEX_ZAPDOS 145
#define NATIONAL_DEX_MOLTRES 146
#define NATIONAL_DEX_DRATINI 147
#define NATIONAL_DEX_DRAGONAIR 148
#define NATIONAL_DEX_DRAGONITE 149
#define NATIONAL_DEX_MEWTWO 150
#define NATIONAL_DEX_MEW 151

#define KANTO_DEX_COUNT NATIONAL_DEX_MEW

#define NATIONAL_DEX_CHIKORITA 152
#define NATIONAL_DEX_BAYLEEF 153
#define NATIONAL_DEX_MEGANIUM 154
#define NATIONAL_DEX_CYNDAQUIL 155
#define NATIONAL_DEX_QUILAVA 156
#define NATIONAL_DEX_TYPHLOSION 157
#define NATIONAL_DEX_TOTODILE 158
#define NATIONAL_DEX_CROCONAW 159
#define NATIONAL_DEX_FERALIGATR 160
#define NATIONAL_DEX_SENTRET 161
#define NATIONAL_DEX_FURRET 162
#define NATIONAL_DEX_HOOTHOOT 163
#define NATIONAL_DEX_NOCTOWL 164
#define NATIONAL_DEX_LEDYBA 165
#define NATIONAL_DEX_LEDIAN 166
#define NATIONAL_DEX_SPINARAK 167
#define NATIONAL_DEX_ARIADOS 168
#define NATIONAL_DEX_CROBAT 169
#define NATIONAL_DEX_CHINCHOU 170
#define NATIONAL_DEX_LANTURN 171
#define NATIONAL_DEX_PICHU 172
#define NATIONAL_DEX_CLEFFA 173
#define NATIONAL_DEX_IGGLYBUFF 174
#define NATIONAL_DEX_TOGEPI 175
#define NATIONAL_DEX_TOGETIC 176
#define NATIONAL_DEX_NATU 177
#define NATIONAL_DEX_XATU 178
#define NATIONAL_DEX_MAREEP 179
#define NATIONAL_DEX_FLAAFFY 180
#define NATIONAL_DEX_AMPHAROS 181
#define NATIONAL_DEX_BELLOSSOM 182
#define NATIONAL_DEX_MARILL 183
#define NATIONAL_DEX_AZUMARILL 184
#define NATIONAL_DEX_SUDOWOODO 185
#define NATIONAL_DEX_POLITOED 186
#define NATIONAL_DEX_HOPPIP 187
#define NATIONAL_DEX_SKIPLOOM 188
#define NATIONAL_DEX_JUMPLUFF 189
#define NATIONAL_DEX_AIPOM 190
#define NATIONAL_DEX_SUNKERN 191
#define NATIONAL_DEX_SUNFLORA 192
#define NATIONAL_DEX_YANMA 193
#define NATIONAL_DEX_WOOPER 194
#define NATIONAL_DEX_QUAGSIRE 195
#define NATIONAL_DEX_ESPEON 196
#define NATIONAL_DEX_UMBREON 197
#define NATIONAL_DEX_MURKROW 198
#define NATIONAL_DEX_SLOWKING 199
#define NATIONAL_DEX_MISDREAVUS 200
#define NATIONAL_DEX_UNOWN 201
#define NATIONAL_DEX_WOBBUFFET 202
#define NATIONAL_DEX_GIRAFARIG 203
#define NATIONAL_DEX_PINECO 204
#define NATIONAL_DEX_FORRETRESS 205
#define NATIONAL_DEX_DUNSPARCE 206
#define NATIONAL_DEX_GLIGAR 207
#define NATIONAL_DEX_STEELIX 208
#define NATIONAL_DEX_SNUBBULL 209
#define NATIONAL_DEX_GRANBULL 210
#define NATIONAL_DEX_QWILFISH 211
#define NATIONAL_DEX_SCIZOR 212
#define NATIONAL_DEX_SHUCKLE 213
#define NATIONAL_DEX_HERACROSS 214
#define NATIONAL_DEX_SNEASEL 215
#define NATIONAL_DEX_TEDDIURSA 216
#define NATIONAL_DEX_URSARING 217
#define NATIONAL_DEX_SLUGMA 218
#define NATIONAL_DEX_MAGCARGO 219
#define NATIONAL_DEX_SWINUB 220
#define NATIONAL_DEX_PILOSWINE 221
#define NATIONAL_DEX_CORSOLA 222
#define NATIONAL_DEX_REMORAID 223
#define NATIONAL_DEX_OCTILLERY 224
#define NATIONAL_DEX_DELIBIRD 225
#define NATIONAL_DEX_MANTINE 226
#define NATIONAL_DEX_SKARMORY 227
#define NATIONAL_DEX_HOUNDOUR 228
#define NATIONAL_DEX_HOUNDOOM 229
#define NATIONAL_DEX_KINGDRA 230
#define NATIONAL_DEX_PHANPY 231
#define NATIONAL_DEX_DONPHAN 232
#define NATIONAL_DEX_PORYGON2 233
#define NATIONAL_DEX_STANTLER 234
#define NATIONAL_DEX_SMEARGLE 235
#define NATIONAL_DEX_TYROGUE 236
#define NATIONAL_DEX_HITMONTOP 237
#define NATIONAL_DEX_SMOOCHUM 238
#define NATIONAL_DEX_ELEKID 239
#define NATIONAL_DEX_MAGBY 240
#define NATIONAL_DEX_MILTANK 241
#define NATIONAL_DEX_BLISSEY 242
#define NATIONAL_DEX_RAIKOU 243
#define NATIONAL_DEX_ENTEI 244
#define NATIONAL_DEX_SUICUNE 245
#define NATIONAL_DEX_LARVITAR 246
#define NATIONAL_DEX_PUPITAR 247
#define NATIONAL_DEX_TYRANITAR 248
#define NATIONAL_DEX_LUGIA 249
#define NATIONAL_DEX_HO_OH 250
#define NATIONAL_DEX_CELEBI 251

#define JOHTO_DEX_COUNT NATIONAL_DEX_CELEBI

#define NATIONAL_DEX_TREECKO 252
#define NATIONAL_DEX_GROVYLE 253
#define NATIONAL_DEX_SCEPTILE 254
#define NATIONAL_DEX_TORCHIC 255
#define NATIONAL_DEX_COMBUSKEN 256
#define NATIONAL_DEX_BLAZIKEN 257
#define NATIONAL_DEX_MUDKIP 258
#define NATIONAL_DEX_MARSHTOMP 259
#define NATIONAL_DEX_SWAMPERT 260
#define NATIONAL_DEX_POOCHYENA 261
#define NATIONAL_DEX_MIGHTYENA 262
#define NATIONAL_DEX_ZIGZAGOON 263
#define NATIONAL_DEX_LINOONE 264
#define NATIONAL_DEX_WURMPLE 265
#define NATIONAL_DEX_SILCOON 266
#define NATIONAL_DEX_BEAUTIFLY 267
#define NATIONAL_DEX_CASCOON 268
#define NATIONAL_DEX_DUSTOX 269
#define NATIONAL_DEX_LOTAD 270
#define NATIONAL_DEX_LOMBRE 271
#define NATIONAL_DEX_LUDICOLO 272
#define NATIONAL_DEX_SEEDOT 273
#define NATIONAL_DEX_NUZLEAF 274
#define NATIONAL_DEX_SHIFTRY 275
#define NATIONAL_DEX_TAILLOW 276
#define NATIONAL_DEX_SWELLOW 277
#define NATIONAL_DEX_WINGULL 278
#define NATIONAL_DEX_PELIPPER 279
#define NATIONAL_DEX_RALTS 280
#define NATIONAL_DEX_KIRLIA 281
#define NATIONAL_DEX_GARDEVOIR 282
#define NATIONAL_DEX_SURSKIT 283
#define NATIONAL_DEX_MASQUERAIN 284
#define NATIONAL_DEX_SHROOMISH 285
#define NATIONAL_DEX_BRELOOM 286
#define NATIONAL_DEX_SLAKOTH 287
#define NATIONAL_DEX_VIGOROTH 288
#define NATIONAL_DEX_SLAKING 289
#define NATIONAL_DEX_NINCADA 290
#define NATIONAL_DEX_NINJASK 291
#define NATIONAL_DEX_SHEDINJA 292
#define NATIONAL_DEX_WHISMUR 293
#define NATIONAL_DEX_LOUDRED 294
#define NATIONAL_DEX_EXPLOUD 295
#define NATIONAL_DEX_MAKUHITA 296
#define NATIONAL_DEX_HARIYAMA 297
#define NATIONAL_DEX_AZURILL 298
#define NATIONAL_DEX_NOSEPASS 299
#define NATIONAL_DEX_SKITTY 300
#define NATIONAL_DEX_DELCATTY 301
#define NATIONAL_DEX_SABLEYE 302
#define NATIONAL_DEX_MAWILE 303
#define NATIONAL_DEX_ARON 304
#define NATIONAL_DEX_LAIRON 305
#define NATIONAL_DEX_AGGRON 306
#define NATIONAL_DEX_MEDITITE 307
#define NATIONAL_DEX_MEDICHAM 308
#define NATIONAL_DEX_ELECTRIKE 309
#define NATIONAL_DEX_MANECTRIC 310
#define NATIONAL_DEX_PLUSLE 311
#define NATIONAL_DEX_MINUN 312
#define NATIONAL_DEX_VOLBEAT 313
#define NATIONAL_DEX_ILLUMISE 314
#define NATIONAL_DEX_ROSELIA 315
#define NATIONAL_DEX_GULPIN 316
#define NATIONAL_DEX_SWALOT 317
#define NATIONAL_DEX_CARVANHA 318
#define NATIONAL_DEX_SHARPEDO 319
#define NATIONAL_DEX_WAILMER 320
#define NATIONAL_DEX_WAILORD 321
#define NATIONAL_DEX_NUMEL 322
#define NATIONAL_DEX_CAMERUPT 323
#define NATIONAL_DEX_TORKOAL 324
#define NATIONAL_DEX_SPOINK 325
#define NATIONAL_DEX_GRUMPIG 326
#define NATIONAL_DEX_SPINDA 327
#define NATIONAL_DEX_TRAPINCH 328
#define NATIONAL_DEX_VIBRAVA 329
#define NATIONAL_DEX_FLYGON 330
#define NATIONAL_DEX_CACNEA 331
#define NATIONAL_DEX_CACTURNE 332
#define NATIONAL_DEX_SWABLU 333
#define NATIONAL_DEX_ALTARIA 334
#define NATIONAL_DEX_ZANGOOSE 335
#define NATIONAL_DEX_SEVIPER 336
#define NATIONAL_DEX_LUNATONE 337
#define NATIONAL_DEX_SOLROCK 338
#define NATIONAL_DEX_BARBOACH 339
#define NATIONAL_DEX_WHISCASH 340
#define NATIONAL_DEX_CORPHISH 341
#define NATIONAL_DEX_CRAWDAUNT 342
#define NATIONAL_DEX_BALTOY 343
#define NATIONAL_DEX_CLAYDOL 344
#define NATIONAL_DEX_LILEEP 345
#define NATIONAL_DEX_CRADILY 346
#define NATIONAL_DEX_ANORITH 347
#define NATIONAL_DEX_ARMALDO 348
#define NATIONAL_DEX_FEEBAS 349
#define NATIONAL_DEX_MILOTIC 350
#define NATIONAL_DEX_CASTFORM 351
#define NATIONAL_DEX_KECLEON 352
#define NATIONAL_DEX_SHUPPET 353
#define NATIONAL_DEX_BANETTE 354
#define NATIONAL_DEX_DUSKULL 355
#define NATIONAL_DEX_DUSCLOPS 356
#define NATIONAL_DEX_TROPIUS 357
#define NATIONAL_DEX_CHIMECHO 358
#define NATIONAL_DEX_ABSOL 359
#define NATIONAL_DEX_WYNAUT 360
#define NATIONAL_DEX_SNORUNT 361
#define NATIONAL_DEX_GLALIE 362
#define NATIONAL_DEX_SPHEAL 363
#define NATIONAL_DEX_SEALEO 364
#define NATIONAL_DEX_WALREIN 365
#define NATIONAL_DEX_CLAMPERL 366
#define NATIONAL_DEX_HUNTAIL 367
#define NATIONAL_DEX_GOREBYSS 368
#define NATIONAL_DEX_RELICANTH 369
#define NATIONAL_DEX_LUVDISC 370
#define NATIONAL_DEX_BAGON 371
#define NATIONAL_DEX_SHELGON 372
#define NATIONAL_DEX_SALAMENCE 373
#define NATIONAL_DEX_BELDUM 374
#define NATIONAL_DEX_METANG 375
#define NATIONAL_DEX_METAGROSS 376
#define NATIONAL_DEX_REGIROCK 377
#define NATIONAL_DEX_REGICE 378
#define NATIONAL_DEX_REGISTEEL 379
#define NATIONAL_DEX_LATIAS 380
#define NATIONAL_DEX_LATIOS 381
#define NATIONAL_DEX_KYOGRE 382
#define NATIONAL_DEX_GROUDON 383
#define NATIONAL_DEX_RAYQUAZA 384
#define NATIONAL_DEX_JIRACHI 385
#define NATIONAL_DEX_DEOXYS 386
#define NATIONAL_DEX_TURTWIG 387
#define NATIONAL_DEX_GROTLE 388
#define NATIONAL_DEX_TORTERRA 389
#define NATIONAL_DEX_CHIMCHAR 390
#define NATIONAL_DEX_MONFERNO 391
#define NATIONAL_DEX_INFERNAPE 392
#define NATIONAL_DEX_PIPLUP 393
#define NATIONAL_DEX_PRINPLUP 394
#define NATIONAL_DEX_EMPOLEON 395
#define NATIONAL_DEX_STARLY 396
#define NATIONAL_DEX_STARAVIA 397
#define NATIONAL_DEX_STARAPTOR 398
#define NATIONAL_DEX_BIDOOF 399
#define NATIONAL_DEX_BIBAREL 400
#define NATIONAL_DEX_KRICKETOT 401
#define NATIONAL_DEX_KRICKETUNE 402
#define NATIONAL_DEX_SHINX 403
#define NATIONAL_DEX_LUXIO 404
#define NATIONAL_DEX_LUXRAY 405
#define NATIONAL_DEX_BUDEW 406
#define NATIONAL_DEX_ROSERADE 407
#define NATIONAL_DEX_CRANIDOS 408
#define NATIONAL_DEX_RAMPARDOS 409
#define NATIONAL_DEX_SHIELDON 410
#define NATIONAL_DEX_BASTIODON 411
#define NATIONAL_DEX_BURMY 412
#define NATIONAL_DEX_WORMADAM 413
#define NATIONAL_DEX_MOTHIM 414
#define NATIONAL_DEX_COMBEE 415
#define NATIONAL_DEX_VESPIQUEN 416
#define NATIONAL_DEX_PACHIRISU 417
#define NATIONAL_DEX_BUIZEL 418
#define NATIONAL_DEX_FLOATZEL 419
#define NATIONAL_DEX_CHERUBI 420
#define NATIONAL_DEX_CHERRIM 421
#define NATIONAL_DEX_SHELLOS 422
#define NATIONAL_DEX_GASTRODON 423
#define NATIONAL_DEX_AMBIPOM 424
#define NATIONAL_DEX_DRIFLOON 425
#define NATIONAL_DEX_DRIFBLIM 426
#define NATIONAL_DEX_BUNEARY 427
#define NATIONAL_DEX_LOPUNNY 428
#define NATIONAL_DEX_MISMAGIUS 429
#define NATIONAL_DEX_HONCHKROW 430
#define NATIONAL_DEX_GLAMEOW 431
#define NATIONAL_DEX_PURUGLY 432
#define NATIONAL_DEX_CHINGLING 433
#define NATIONAL_DEX_STUNKY 434
#define NATIONAL_DEX_SKUNTANK 435
#define NATIONAL_DEX_BRONZOR 436
#define NATIONAL_DEX_BRONZONG 437
#define NATIONAL_DEX_BONSLY 438
#define NATIONAL_DEX_MIME_JR 439
#define NATIONAL_DEX_HAPPINY 440
#define NATIONAL_DEX_CHATOT 441
#define NATIONAL_DEX_SPIRITOMB 442
#define NATIONAL_DEX_GIBLE 443
#define NATIONAL_DEX_GABITE 444
#define NATIONAL_DEX_GARCHOMP 445
#define NATIONAL_DEX_MUNCHLAX 446
#define NATIONAL_DEX_RIOLU 447
#define NATIONAL_DEX_LUCARIO 448
#define NATIONAL_DEX_HIPPOPOTAS 449
#define NATIONAL_DEX_HIPPOWDON 450
#define NATIONAL_DEX_SKORUPI 451
#define NATIONAL_DEX_DRAPION 452
#define NATIONAL_DEX_CROAGUNK 453
#define NATIONAL_DEX_TOXICROAK 454
#define NATIONAL_DEX_CARNIVINE 455
#define NATIONAL_DEX_FINNEON 456
#define NATIONAL_DEX_LUMINEON 457
#define NATIONAL_DEX_MANTYKE 458
#define NATIONAL_DEX_SNOVER 459
#define NATIONAL_DEX_ABOMASNOW 460
#define NATIONAL_DEX_WEAVILE 461
#define NATIONAL_DEX_MAGNEZONE 462
#define NATIONAL_DEX_LICKILICKY 463
#define NATIONAL_DEX_RHYPERIOR 464
#define NATIONAL_DEX_TANGROWTH 465
#define NATIONAL_DEX_ELECTIVIRE 466
#define NATIONAL_DEX_MAGMORTAR 467
#define NATIONAL_DEX_TOGEKISS 468
#define NATIONAL_DEX_YANMEGA 469
#define NATIONAL_DEX_LEAFEON 470
#define NATIONAL_DEX_GLACEON 471
#define NATIONAL_DEX_GLISCOR 472
#define NATIONAL_DEX_MAMOSWINE 473
#define NATIONAL_DEX_PORYGON_Z 474
#define NATIONAL_DEX_GALLADE 475
#define NATIONAL_DEX_PROBOPASS 476
#define NATIONAL_DEX_DUSKNOIR 477
#define NATIONAL_DEX_FROSLASS 478
#define NATIONAL_DEX_ROTOM 479
#define NATIONAL_DEX_UXIE 480
#define NATIONAL_DEX_MESPRIT 481
#define NATIONAL_DEX_AZELF 482
#define NATIONAL_DEX_DIALGA 483
#define NATIONAL_DEX_PALKIA 484
#define NATIONAL_DEX_HEATRAN 485
#define NATIONAL_DEX_REGIGIGAS 486
#define NATIONAL_DEX_GIRATINA 487
#define NATIONAL_DEX_CRESSELIA 488
#define NATIONAL_DEX_PHIONE 489
#define NATIONAL_DEX_MANAPHY 490
#define NATIONAL_DEX_DARKRAI 491
#define NATIONAL_DEX_SHAYMIN 492
#define NATIONAL_DEX_ARCEUS 493
#define NATIONAL_DEX_VICTINI 494
#define NATIONAL_DEX_SNIVY 495
#define NATIONAL_DEX_SERVINE 496
#define NATIONAL_DEX_SERPERIOR 497
#define NATIONAL_DEX_TEPIG 498
#define NATIONAL_DEX_PIGNITE 499
#define NATIONAL_DEX_EMBOAR 500
#define NATIONAL_DEX_OSHAWOTT 501
#define NATIONAL_DEX_DEWOTT 502
#define NATIONAL_DEX_SAMUROTT 503
#define NATIONAL_DEX_PATRAT 504
#define NATIONAL_DEX_WATCHOG 505
#define NATIONAL_DEX_LILLIPUP 506
#define NATIONAL_DEX_HERDIER 507
#define NATIONAL_DEX_STOUTLAND 508
#define NATIONAL_DEX_PURRLOIN 509
#define NATIONAL_DEX_LIEPARD 510
#define NATIONAL_DEX_PANSAGE 511
#define NATIONAL_DEX_SIMISAGE 512
#define NATIONAL_DEX_PANSEAR 513
#define NATIONAL_DEX_SIMISEAR 514
#define NATIONAL_DEX_PANPOUR 515
#define NATIONAL_DEX_SIMIPOUR 516
#define NATIONAL_DEX_MUNNA 517
#define NATIONAL_DEX_MUSHARNA 518
#define NATIONAL_DEX_PIDOVE 519
#define NATIONAL_DEX_TRANQUILL 520
#define NATIONAL_DEX_UNFEZANT 521
#define NATIONAL_DEX_BLITZLE 522
#define NATIONAL_DEX_ZEBSTRIKA 523
#define NATIONAL_DEX_ROGGENROLA 524
#define NATIONAL_DEX_BOLDORE 525
#define NATIONAL_DEX_GIGALITH 526
#define NATIONAL_DEX_WOOBAT 527
#define NATIONAL_DEX_SWOOBAT 528
#define NATIONAL_DEX_DRILBUR 529
#define NATIONAL_DEX_EXCADRILL 530
#define NATIONAL_DEX_AUDINO 531
#define NATIONAL_DEX_TIMBURR 532
#define NATIONAL_DEX_GURDURR 533
#define NATIONAL_DEX_CONKELDURR 534
#define NATIONAL_DEX_TYMPOLE 535
#define NATIONAL_DEX_PALPITOAD 536
#define NATIONAL_DEX_SEISMITOAD 537
#define NATIONAL_DEX_THROH 538
#define NATIONAL_DEX_SAWK 539
#define NATIONAL_DEX_SEWADDLE 540
#define NATIONAL_DEX_SWADLOON 541
#define NATIONAL_DEX_LEAVANNY 542
#define NATIONAL_DEX_VENIPEDE 543
#define NATIONAL_DEX_WHIRLIPEDE 544
#define NATIONAL_DEX_SCOLIPEDE 545
#define NATIONAL_DEX_COTTONEE 546
#define NATIONAL_DEX_WHIMSICOTT 547
#define NATIONAL_DEX_PETILIL 548
#define NATIONAL_DEX_LILLIGANT 549
#define NATIONAL_DEX_BASCULIN 550
#define NATIONAL_DEX_SANDILE 551
#define NATIONAL_DEX_KROKOROK 552
#define NATIONAL_DEX_KROOKODILE 553
#define NATIONAL_DEX_DARUMAKA 554
#define NATIONAL_DEX_DARMANITAN 555
#define NATIONAL_DEX_MARACTUS 556
#define NATIONAL_DEX_DWEBBLE 557
#define NATIONAL_DEX_CRUSTLE 558
#define NATIONAL_DEX_SCRAGGY 559
#define NATIONAL_DEX_SCRAFTY 560
#define NATIONAL_DEX_SIGILYPH 561
#define NATIONAL_DEX_YAMASK 562
#define NATIONAL_DEX_COFAGRIGUS 563
#define NATIONAL_DEX_TIRTOUGA 564
#define NATIONAL_DEX_CARRACOSTA 565
#define NATIONAL_DEX_ARCHEN 566
#define NATIONAL_DEX_ARCHEOPS 567
#define NATIONAL_DEX_TRUBBISH 568
#define NATIONAL_DEX_GARBODOR 569
#define NATIONAL_DEX_ZORUA 570
#define NATIONAL_DEX_ZOROARK 571
#define NATIONAL_DEX_MINCCINO 572
#define NATIONAL_DEX_CINCCINO 573
#define NATIONAL_DEX_GOTHITA 574
#define NATIONAL_DEX_GOTHORITA 575
#define NATIONAL_DEX_GOTHITELLE 576
#define NATIONAL_DEX_SOLOSIS 577
#define NATIONAL_DEX_DUOSION 578
#define NATIONAL_DEX_REUNICLUS 579
#define NATIONAL_DEX_DUCKLETT 580
#define NATIONAL_DEX_SWANNA 581
#define NATIONAL_DEX_VANILLITE 582
#define NATIONAL_DEX_VANILLISH 583
#define NATIONAL_DEX_VANILLUXE 584
#define NATIONAL_DEX_DEERLING 585
#define NATIONAL_DEX_SAWSBUCK 586
#define NATIONAL_DEX_EMOLGA 587
#define NATIONAL_DEX_KARRABLAST 588
#define NATIONAL_DEX_ESCAVALIER 589
#define NATIONAL_DEX_FOONGUS 590
#define NATIONAL_DEX_AMOONGUSS 591
#define NATIONAL_DEX_FRILLISH 592
#define NATIONAL_DEX_JELLICENT 593
#define NATIONAL_DEX_ALOMOMOLA 594
#define NATIONAL_DEX_JOLTIK 595
#define NATIONAL_DEX_GALVANTULA 596
#define NATIONAL_DEX_FERROSEED 597
#define NATIONAL_DEX_FERROTHORN 598
#define NATIONAL_DEX_KLINK 599
#define NATIONAL_DEX_KLANG 600
#define NATIONAL_DEX_KLINKLANG 601
#define NATIONAL_DEX_TYNAMO 602
#define NATIONAL_DEX_EELEKTRIK 603
#define NATIONAL_DEX_EELEKTROSS 604
#define NATIONAL_DEX_ELGYEM 605
#define NATIONAL_DEX_BEHEEYEM 606
#define NATIONAL_DEX_LITWICK 607
#define NATIONAL_DEX_LAMPENT 608
#define NATIONAL_DEX_CHANDELURE 609
#define NATIONAL_DEX_AXEW 610
#define NATIONAL_DEX_FRAXURE 611
#define NATIONAL_DEX_HAXORUS 612
#define NATIONAL_DEX_CUBCHOO 613
#define NATIONAL_DEX_BEARTIC 614
#define NATIONAL_DEX_CRYOGONAL 615
#define NATIONAL_DEX_SHELMET 616
#define NATIONAL_DEX_ACCELGOR 617
#define NATIONAL_DEX_STUNFISK 618
#define NATIONAL_DEX_MIENFOO 619
#define NATIONAL_DEX_MIENSHAO 620
#define NATIONAL_DEX_DRUDDIGON 621
#define NATIONAL_DEX_GOLETT 622
#define NATIONAL_DEX_GOLURK 623
#define NATIONAL_DEX_PAWNIARD 624
#define NATIONAL_DEX_BISHARP 625
#define NATIONAL_DEX_BOUFFALANT 626
#define NATIONAL_DEX_RUFFLET 627
#define NATIONAL_DEX_BRAVIARY 628
#define NATIONAL_DEX_VULLABY 629
#define NATIONAL_DEX_MANDIBUZZ 630
#define NATIONAL_DEX_HEATMOR 631
#define NATIONAL_DEX_DURANT 632
#define NATIONAL_DEX_DEINO 633
#define NATIONAL_DEX_ZWEILOUS 634
#define NATIONAL_DEX_HYDREIGON 635
#define NATIONAL_DEX_LARVESTA 636
#define NATIONAL_DEX_VOLCARONA 637
#define NATIONAL_DEX_COBALION 638
#define NATIONAL_DEX_TERRAKION 639
#define NATIONAL_DEX_VIRIZION 640
#define NATIONAL_DEX_TORNADUS 641
#define NATIONAL_DEX_THUNDURUS 642
#define NATIONAL_DEX_RESHIRAM 643
#define NATIONAL_DEX_ZEKROM 644
#define NATIONAL_DEX_LANDORUS 645
#define NATIONAL_DEX_KYUREM 646
#define NATIONAL_DEX_KELDEO 647
#define NATIONAL_DEX_MELOETTA 648
#define NATIONAL_DEX_GENESECT 649
#define NATIONAL_DEX_CHESPIN 650
#define NATIONAL_DEX_QUILLADIN 651
#define NATIONAL_DEX_CHESNAUGHT 652
#define NATIONAL_DEX_FENNEKIN 653
#define NATIONAL_DEX_BRAIXEN 654
#define NATIONAL_DEX_DELPHOX 655
#define NATIONAL_DEX_FROAKIE 656
#define NATIONAL_DEX_FROGADIER 657
#define NATIONAL_DEX_GRENINJA 658
#define NATIONAL_DEX_BUNNELBY 659
#define NATIONAL_DEX_DIGGERSBY 660
#define NATIONAL_DEX_FLETCHLING 661
#define NATIONAL_DEX_FLETCHINDER 662
#define NATIONAL_DEX_TALONFLAME 663
#define NATIONAL_DEX_SCATTERBUG 664
#define NATIONAL_DEX_SPEWPA 665
#define NATIONAL_DEX_VIVILLON 666
#define NATIONAL_DEX_LITLEO 667
#define NATIONAL_DEX_PYROAR 668
#define NATIONAL_DEX_FLABEBE 669
#define NATIONAL_DEX_FLOETTE 670
#define NATIONAL_DEX_FLORGES 671
#define NATIONAL_DEX_SKIDDO 672
#define NATIONAL_DEX_GOGOAT 673
#define NATIONAL_DEX_PANCHAM 674
#define NATIONAL_DEX_PANGORO 675
#define NATIONAL_DEX_FURFROU 676
#define NATIONAL_DEX_ESPURR 677
#define NATIONAL_DEX_MEOWSTIC 678
#define NATIONAL_DEX_HONEDGE 679
#define NATIONAL_DEX_DOUBLADE 680
#define NATIONAL_DEX_AEGISLASH 681
#define NATIONAL_DEX_SPRITZEE 682
#define NATIONAL_DEX_AROMATISSE 683
#define NATIONAL_DEX_SWIRLIX 684
#define NATIONAL_DEX_SLURPUFF 685
#define NATIONAL_DEX_INKAY 686
#define NATIONAL_DEX_MALAMAR 687
#define NATIONAL_DEX_BINACLE 688
#define NATIONAL_DEX_BARBARACLE 689
#define NATIONAL_DEX_SKRELP 690
#define NATIONAL_DEX_DRAGALGE 691
#define NATIONAL_DEX_CLAUNCHER 692
#define NATIONAL_DEX_CLAWITZER 693
#define NATIONAL_DEX_HELIOPTILE 694
#define NATIONAL_DEX_HELIOLISK 695
#define NATIONAL_DEX_TYRUNT 696
#define NATIONAL_DEX_TYRANTRUM 697
#define NATIONAL_DEX_AMAURA 698
#define NATIONAL_DEX_AURORUS 699
#define NATIONAL_DEX_SYLVEON 700
#define NATIONAL_DEX_HAWLUCHA 701
#define NATIONAL_DEX_DEDENNE 702
#define NATIONAL_DEX_CARBINK 703
#define NATIONAL_DEX_GOOMY 704
#define NATIONAL_DEX_SLIGGOO 705
#define NATIONAL_DEX_GOODRA 706
#define NATIONAL_DEX_KLEFKI 707
#define NATIONAL_DEX_PHANTUMP 708
#define NATIONAL_DEX_TREVENANT 709
#define NATIONAL_DEX_PUMPKABOO 710
#define NATIONAL_DEX_GOURGEIST 711
#define NATIONAL_DEX_BERGMITE 712
#define NATIONAL_DEX_AVALUGG 713
#define NATIONAL_DEX_NOIBAT 714
#define NATIONAL_DEX_NOIVERN 715
#define NATIONAL_DEX_XERNEAS 716
#define NATIONAL_DEX_YVELTAL 717
#define NATIONAL_DEX_ZYGARDE 718
#define NATIONAL_DEX_DIANCIE 719
#define NATIONAL_DEX_HOOPA 720
#define NATIONAL_DEX_VOLCANION 721
#define NATIONAL_DEX_ROWLET 722
#define NATIONAL_DEX_DARTRIX 723
#define NATIONAL_DEX_DECIDUEYE 724
#define NATIONAL_DEX_LITTEN 725
#define NATIONAL_DEX_TORRACAT 726
#define NATIONAL_DEX_INCINEROAR 727
#define NATIONAL_DEX_POPPLIO 728
#define NATIONAL_DEX_BRIONNE 729
#define NATIONAL_DEX_PRIMARINA 730
#define NATIONAL_DEX_PIKIPEK 731
#define NATIONAL_DEX_TRUMBEAK 732
#define NATIONAL_DEX_TOUCANNON 733
#define NATIONAL_DEX_YUNGOOS 734
#define NATIONAL_DEX_GUMSHOOS 735
#define NATIONAL_DEX_GRUBBIN 736
#define NATIONAL_DEX_CHARJABUG 737
#define NATIONAL_DEX_VIKAVOLT 738
#define NATIONAL_DEX_CRABRAWLER 739
#define NATIONAL_DEX_CRABOMINABLE 740
#define NATIONAL_DEX_ORICORIO 741
#define NATIONAL_DEX_CUTIEFLY 742
#define NATIONAL_DEX_RIBOMBEE 743
#define NATIONAL_DEX_ROCKRUFF 744
#define NATIONAL_DEX_LYCANROC 745
#define NATIONAL_DEX_WISHIWASHI 746
#define NATIONAL_DEX_MAREANIE 747
#define NATIONAL_DEX_TOXAPEX 748
#define NATIONAL_DEX_MUDBRAY 749
#define NATIONAL_DEX_MUDSDALE 750
#define NATIONAL_DEX_DEWPIDER 751
#define NATIONAL_DEX_ARAQUANID 752
#define NATIONAL_DEX_FOMANTIS 753
#define NATIONAL_DEX_LURANTIS 754
#define NATIONAL_DEX_MORELULL 755
#define NATIONAL_DEX_SHIINOTIC 756
#define NATIONAL_DEX_SALANDIT 757
#define NATIONAL_DEX_SALAZZLE 758
#define NATIONAL_DEX_STUFFUL 759
#define NATIONAL_DEX_BEWEAR 760
#define NATIONAL_DEX_BOUNSWEET 761
#define NATIONAL_DEX_STEENEE 762
#define NATIONAL_DEX_TSAREENA 763
#define NATIONAL_DEX_COMFEY 764
#define NATIONAL_DEX_ORANGURU 765
#define NATIONAL_DEX_PASSIMIAN 766
#define NATIONAL_DEX_WIMPOD 767
#define NATIONAL_DEX_GOLISOPOD 768
#define NATIONAL_DEX_SANDYGAST 769
#define NATIONAL_DEX_PALOSSAND 770
#define NATIONAL_DEX_PYUKUMUKU 771
#define NATIONAL_DEX_TYPE_NULL 772
#define NATIONAL_DEX_SILVALLY 773
#define NATIONAL_DEX_MINIOR 774
#define NATIONAL_DEX_KOMALA 775
#define NATIONAL_DEX_TURTONATOR 776
#define NATIONAL_DEX_TOGEDEMARU 777
#define NATIONAL_DEX_MIMIKYU 778
#define NATIONAL_DEX_BRUXISH 779
#define NATIONAL_DEX_DRAMPA 780
#define NATIONAL_DEX_DHELMISE 781
#define NATIONAL_DEX_JANGMO_O 782
#define NATIONAL_DEX_HAKAMO_O 783
#define NATIONAL_DEX_KOMMO_O 784
#define NATIONAL_DEX_TAPU_KOKO 785
#define NATIONAL_DEX_TAPU_LELE 786
#define NATIONAL_DEX_TAPU_BULU 787
#define NATIONAL_DEX_TAPU_FINI 788
#define NATIONAL_DEX_COSMOG 789
#define NATIONAL_DEX_COSMOEM 790
#define NATIONAL_DEX_SOLGALEO 791
#define NATIONAL_DEX_LUNALA 792
#define NATIONAL_DEX_NIHILEGO 793
#define NATIONAL_DEX_BUZZWOLE 794
#define NATIONAL_DEX_PHEROMOSA 795
#define NATIONAL_DEX_XURKITREE 796
#define NATIONAL_DEX_CELESTEELA 797
#define NATIONAL_DEX_KARTANA 798
#define NATIONAL_DEX_GUZZLORD 799
#define NATIONAL_DEX_NECROZMA 800
#define NATIONAL_DEX_MAGEARNA 801
#define NATIONAL_DEX_MARSHADOW 802
#define NATIONAL_DEX_POIPOLE 803
#define NATIONAL_DEX_NAGANADEL 804
#define NATIONAL_DEX_STAKATAKA 805
#define NATIONAL_DEX_BLACEPHALON 806
#define NATIONAL_DEX_ZERAORA 807
#define NATIONAL_DEX_MELTAN 808
#define NATIONAL_DEX_MELMETAL 809
#define NATIONAL_DEX_GROOKEY 810
#define NATIONAL_DEX_THWACKEY 811
#define NATIONAL_DEX_RILLABOOM 812
#define NATIONAL_DEX_SCORBUNNY 813
#define NATIONAL_DEX_RABOOT 814
#define NATIONAL_DEX_CINDERACE 815
#define NATIONAL_DEX_SOBBLE 816
#define NATIONAL_DEX_DRIZZILE 817
#define NATIONAL_DEX_INTELEON 818
#define NATIONAL_DEX_SKWOVET 819
#define NATIONAL_DEX_GREEDENT 820
#define NATIONAL_DEX_ROOKIDEE 821
#define NATIONAL_DEX_CORVISQUIRE 822
#define NATIONAL_DEX_CORVIKNIGHT 823
#define NATIONAL_DEX_BLIPBUG 824
#define NATIONAL_DEX_DOTTLER 825
#define NATIONAL_DEX_ORBEETLE 826
#define NATIONAL_DEX_NICKIT 827
#define NATIONAL_DEX_THIEVUL 828
#define NATIONAL_DEX_GOSSIFLEUR 829
#define NATIONAL_DEX_ELDEGOSS 830
#define NATIONAL_DEX_WOOLOO 831
#define NATIONAL_DEX_DUBWOOL 832
#define NATIONAL_DEX_CHEWTLE 833
#define NATIONAL_DEX_DREDNAW 834
#define NATIONAL_DEX_YAMPER 835
#define NATIONAL_DEX_BOLTUND 836
#define NATIONAL_DEX_ROLYCOLY 837
#define NATIONAL_DEX_CARKOL 838
#define NATIONAL_DEX_COALOSSAL 839
#define NATIONAL_DEX_APPLIN 840
#define NATIONAL_DEX_FLAPPLE 841
#define NATIONAL_DEX_APPLETUN 842
#define NATIONAL_DEX_SILICOBRA 843
#define NATIONAL_DEX_SANDACONDA 844
#define NATIONAL_DEX_CRAMORANT 845
#define NATIONAL_DEX_ARROKUDA 846
#define NATIONAL_DEX_BARRASKEWDA 847
#define NATIONAL_DEX_TOXEL 848
#define NATIONAL_DEX_TOXTRICITY 849
#define NATIONAL_DEX_SIZZLIPEDE 850
#define NATIONAL_DEX_CENTISKORCH 851
#define NATIONAL_DEX_CLOBBOPUS 852
#define NATIONAL_DEX_GRAPPLOCT 853
#define NATIONAL_DEX_SINISTEA 854
#define NATIONAL_DEX_POLTEAGEIST 855
#define NATIONAL_DEX_HATENNA 856
#define NATIONAL_DEX_HATTREM 857
#define NATIONAL_DEX_HATTERENE 858
#define NATIONAL_DEX_IMPIDIMP 859
#define NATIONAL_DEX_MORGREM 860
#define NATIONAL_DEX_GRIMMSNARL 861
#define NATIONAL_DEX_OBSTAGOON 862
#define NATIONAL_DEX_PERRSERKER 863
#define NATIONAL_DEX_CURSOLA 864
#define NATIONAL_DEX_SIRFETCHD 865
#define NATIONAL_DEX_MR_RIME 866
#define NATIONAL_DEX_RUNERIGUS 867
#define NATIONAL_DEX_MILCERY 868
#define NATIONAL_DEX_ALCREMIE 869
#define NATIONAL_DEX_FALINKS 870
#define NATIONAL_DEX_PINCURCHIN 871
#define NATIONAL_DEX_SNOM 872
#define NATIONAL_DEX_FROSMOTH 873
#define NATIONAL_DEX_STONJOURNER 874
#define NATIONAL_DEX_EISCUE 875
#define NATIONAL_DEX_INDEEDEE 876
#define NATIONAL_DEX_MORPEKO 877
#define NATIONAL_DEX_CUFANT 878
#define NATIONAL_DEX_COPPERAJAH 879
#define NATIONAL_DEX_DRACOZOLT 880
#define NATIONAL_DEX_ARCTOZOLT 881
#define NATIONAL_DEX_DRACOVISH 882
#define NATIONAL_DEX_ARCTOVISH 883
#define NATIONAL_DEX_DURALUDON 884
#define NATIONAL_DEX_DREEPY 885
#define NATIONAL_DEX_DRAKLOAK 886
#define NATIONAL_DEX_DRAGAPULT 887
#define NATIONAL_DEX_ZACIAN 888
#define NATIONAL_DEX_ZAMAZENTA 889
#define NATIONAL_DEX_ETERNATUS 890
#define NATIONAL_DEX_KUBFU 891
#define NATIONAL_DEX_URSHIFU 892
#define NATIONAL_DEX_ZARUDE 893
#define NATIONAL_DEX_REGIELEKI 894
#define NATIONAL_DEX_REGIDRAGO 895
#define NATIONAL_DEX_GLASTRIER 896
#define NATIONAL_DEX_SPECTRIER 897
#define NATIONAL_DEX_CALYREX 898

#define NATIONAL_DEX_COUNT NATIONAL_DEX_CALYREX
#define POKEMON_SLOTS_NUMBER (NATIONAL_DEX_COUNT + 1)

// Hoenn Dex(ORAS) Index Defines
#define HOENN_DEX_NONE 0
#define HOENN_DEX_TREECKO 1
#define HOENN_DEX_GROVYLE 2
#define HOENN_DEX_SCEPTILE 3
#define HOENN_DEX_TORCHIC 4
#define HOENN_DEX_COMBUSKEN 5
#define HOENN_DEX_BLAZIKEN 6
#define HOENN_DEX_MUDKIP 7
#define HOENN_DEX_MARSHTOMP 8
#define HOENN_DEX_SWAMPERT 9
#define HOENN_DEX_POOCHYENA 10
#define HOENN_DEX_MIGHTYENA 11
#define HOENN_DEX_ZIGZAGOON 12
#define HOENN_DEX_LINOONE 13
#define HOENN_DEX_WURMPLE 14
#define HOENN_DEX_SILCOON 15
#define HOENN_DEX_BEAUTIFLY 16
#define HOENN_DEX_CASCOON 17
#define HOENN_DEX_DUSTOX 18
#define HOENN_DEX_LOTAD 19
#define HOENN_DEX_LOMBRE 20
#define HOENN_DEX_LUDICOLO 21
#define HOENN_DEX_SEEDOT 22
#define HOENN_DEX_NUZLEAF 23
#define HOENN_DEX_SHIFTRY 24
#define HOENN_DEX_TAILLOW 25
#define HOENN_DEX_SWELLOW 26
#define HOENN_DEX_WINGULL 27
#define HOENN_DEX_PELIPPER 28
#define HOENN_DEX_RALTS 29
#define HOENN_DEX_KIRLIA 30
#define HOENN_DEX_GARDEVOIR 31
#define HOENN_DEX_GALLADE 32
#define HOENN_DEX_SURSKIT 33
#define HOENN_DEX_MASQUERAIN 34
#define HOENN_DEX_SHROOMISH 35
#define HOENN_DEX_BRELOOM 36
#define HOENN_DEX_SLAKOTH 37
#define HOENN_DEX_VIGOROTH 38
#define HOENN_DEX_SLAKING 39
#define HOENN_DEX_ABRA 40
#define HOENN_DEX_KADABRA 41
#define HOENN_DEX_ALAKAZAM 42
#define HOENN_DEX_NINCADA 43
#define HOENN_DEX_NINJASK 44
#define HOENN_DEX_SHEDINJA 45
#define HOENN_DEX_WHISMUR 46
#define HOENN_DEX_LOUDRED 47
#define HOENN_DEX_EXPLOUD 48
#define HOENN_DEX_MAKUHITA 49
#define HOENN_DEX_HARIYAMA 50
#define HOENN_DEX_GOLDEEN 51
#define HOENN_DEX_SEAKING 52
#define HOENN_DEX_MAGIKARP 53
#define HOENN_DEX_GYARADOS 54
#define HOENN_DEX_AZURILL 55
#define HOENN_DEX_MARILL 56
#define HOENN_DEX_AZUMARILL 57
#define HOENN_DEX_GEODUDE 58
#define HOENN_DEX_GRAVELER 59
#define HOENN_DEX_GOLEM 60
#define HOENN_DEX_NOSEPASS 61
#define HOENN_DEX_PROBOPASS 62
#define HOENN_DEX_SKITTY 63
#define HOENN_DEX_DELCATTY 64
#define HOENN_DEX_ZUBAT 65
#define HOENN_DEX_GOLBAT 66
#define HOENN_DEX_CROBAT 67
#define HOENN_DEX_TENTACOOL 68
#define HOENN_DEX_TENTACRUEL 69
#define HOENN_DEX_SABLEYE 70
#define HOENN_DEX_MAWILE 71
#define HOENN_DEX_ARON 72
#define HOENN_DEX_LAIRON 73
#define HOENN_DEX_AGGRON 74
#define HOENN_DEX_MACHOP 75
#define HOENN_DEX_MACHOKE 76
#define HOENN_DEX_MACHAMP 77
#define HOENN_DEX_MEDITITE 78
#define HOENN_DEX_MEDICHAM 79
#define HOENN_DEX_ELECTRIKE 80
#define HOENN_DEX_MANECTRIC 81
#define HOENN_DEX_PLUSLE 82
#define HOENN_DEX_MINUN 83
#define HOENN_DEX_MAGNEMITE 84
#define HOENN_DEX_MAGNETON 85
#define HOENN_DEX_MAGNEZONE 86
#define HOENN_DEX_VOLTORB 87
#define HOENN_DEX_ELECTRODE 88
#define HOENN_DEX_VOLBEAT 89
#define HOENN_DEX_ILLUMISE 90
#define HOENN_DEX_ODDISH 91
#define HOENN_DEX_GLOOM 92
#define HOENN_DEX_VILEPLUME 93
#define HOENN_DEX_BELLOSSOM 94
#define HOENN_DEX_DODUO 95
#define HOENN_DEX_DODRIO 96
#define HOENN_DEX_BUDEW 97
#define HOENN_DEX_ROSELIA 98
#define HOENN_DEX_ROSERADE 99
#define HOENN_DEX_GULPIN 100
#define HOENN_DEX_SWALOT 101
#define HOENN_DEX_CARVANHA 102
#define HOENN_DEX_SHARPEDO 103
#define HOENN_DEX_WAILMER 104
#define HOENN_DEX_WAILORD 105
#define HOENN_DEX_NUMEL 106
#define HOENN_DEX_CAMERUPT 107
#define HOENN_DEX_SLUGMA 108
#define HOENN_DEX_MAGCARGO 109
#define HOENN_DEX_TORKOAL 110
#define HOENN_DEX_GRIMER 111
#define HOENN_DEX_MUK 112
#define HOENN_DEX_KOFFING 113
#define HOENN_DEX_WEEZING 114
#define HOENN_DEX_SPOINK 115
#define HOENN_DEX_GRUMPIG 116
#define HOENN_DEX_SANDSHREW 117
#define HOENN_DEX_SANDSLASH 118
#define HOENN_DEX_SPINDA 119
#define HOENN_DEX_SKARMORY 120
#define HOENN_DEX_TRAPINCH 121
#define HOENN_DEX_VIBRAVA 122
#define HOENN_DEX_FLYGON 123
#define HOENN_DEX_CACNEA 124
#define HOENN_DEX_CACTURNE 125
#define HOENN_DEX_SWABLU 126
#define HOENN_DEX_ALTARIA 127
#define HOENN_DEX_ZANGOOSE 128
#define HOENN_DEX_SEVIPER 129
#define HOENN_DEX_LUNATONE 130
#define HOENN_DEX_SOLROCK 131
#define HOENN_DEX_BARBOACH 132
#define HOENN_DEX_WHISCASH 133
#define HOENN_DEX_CORPHISH 134
#define HOENN_DEX_CRAWDAUNT 135
#define HOENN_DEX_BALTOY 136
#define HOENN_DEX_CLAYDOL 137
#define HOENN_DEX_LILEEP 138
#define HOENN_DEX_CRADILY 139
#define HOENN_DEX_ANORITH 140
#define HOENN_DEX_ARMALDO 141
#define HOENN_DEX_IGGLYBUFF 142
#define HOENN_DEX_JIGGLYPUFF 143
#define HOENN_DEX_WIGGLYTUFF 144
#define HOENN_DEX_FEEBAS 145
#define HOENN_DEX_MILOTIC 146
#define HOENN_DEX_CASTFORM 147
#define HOENN_DEX_STARYU 148
#define HOENN_DEX_STARMIE 149
#define HOENN_DEX_KECLEON 150
#define HOENN_DEX_SHUPPET 151
#define HOENN_DEX_BANETTE 152
#define HOENN_DEX_DUSKULL 153
#define HOENN_DEX_DUSCLOPS 154
#define HOENN_DEX_DUSKNOIR 155
#define HOENN_DEX_TROPIUS 156
#define HOENN_DEX_CHINGLING 157
#define HOENN_DEX_CHIMECHO 158
#define HOENN_DEX_ABSOL 159
#define HOENN_DEX_VULPIX 160
#define HOENN_DEX_NINETALES 161
#define HOENN_DEX_PICHU 162
#define HOENN_DEX_PIKACHU 163
#define HOENN_DEX_RAICHU 164
#define HOENN_DEX_PSYDUCK 165
#define HOENN_DEX_GOLDUCK 166
#define HOENN_DEX_WYNAUT 167
#define HOENN_DEX_WOBBUFFET 168
#define HOENN_DEX_NATU 169
#define HOENN_DEX_XATU 170
#define HOENN_DEX_GIRAFARIG 171
#define HOENN_DEX_PHANPY 172
#define HOENN_DEX_DONPHAN 173
#define HOENN_DEX_PINSIR 174
#define HOENN_DEX_HERACROSS 175
#define HOENN_DEX_RHYHORN 176
#define HOENN_DEX_RHYDON 177
#define HOENN_DEX_RHYPERIOR 178
#define HOENN_DEX_SNORUNT 179
#define HOENN_DEX_GLALIE 180
#define HOENN_DEX_FROSLASS 181
#define HOENN_DEX_SPHEAL 182
#define HOENN_DEX_SEALEO 183
#define HOENN_DEX_WALREIN 184
#define HOENN_DEX_CLAMPERL 185
#define HOENN_DEX_HUNTAIL 186
#define HOENN_DEX_GOREBYSS 187
#define HOENN_DEX_RELICANTH 188
#define HOENN_DEX_CORSOLA 189
#define HOENN_DEX_CHINCHOU 190
#define HOENN_DEX_LANTURN 191
#define HOENN_DEX_LUVDISC 192
#define HOENN_DEX_HORSEA 193
#define HOENN_DEX_SEADRA 194
#define HOENN_DEX_KINGDRA 195
#define HOENN_DEX_BAGON 196
#define HOENN_DEX_SHELGON 197
#define HOENN_DEX_SALAMENCE 198
#define HOENN_DEX_BELDUM 199
#define HOENN_DEX_METANG 200
#define HOENN_DEX_METAGROSS 201
#define HOENN_DEX_REGIROCK 202
#define HOENN_DEX_REGICE 203
#define HOENN_DEX_REGISTEEL 204
#define HOENN_DEX_LATIAS 205
#define HOENN_DEX_LATIOS 206
#define HOENN_DEX_KYOGRE 207
#define HOENN_DEX_GROUDON 208
#define HOENN_DEX_RAYQUAZA 209
#define HOENN_DEX_JIRACHI 210
#define HOENN_DEX_DEOXYS 211

#define HOENN_DEX_COUNT 212

// species flags
#define F_ULTRA_BEAST   (1 << 0)
#define F_ALOLAN_FORM   (1 << 1)
#define F_GALARIAN_FORM (1 << 2)

#endif  // GUARD_CONSTANTS_SPECIES_H
