#ifndef GUARD_CONSTANTS_SPRITE_TAGS_H
#define GUARD_CONSTANTS_SPRITE_TAGS_H

enum SpriteTag {
    // pokemon_storage_system.c
    GFX_TAG_MON_STORAGE_SYSTEM_CURSOR,
    GFX_TAG_MON_STORAGE_SYSTEM_CURSOR_SHADOW,
    GFX_TAG_MON_STORAGE_SYSTEM_DISPLAY_MON,
    GFX_TAG_MON_STORAGE_SYSTEM_BOX_TITLE,
    GFX_TAG_MON_STORAGE_SYSTEM_BOX_TITLE_ALT,
    GFX_TAG_MON_STORAGE_SYSTEM_WAVEFORM,
    GFX_TAG_MON_STORAGE_SYSTEM_ARROW,
    GFX_TAG_MON_STORAGE_SYSTEM_ITEM_ICON_0,
    GFX_TAG_MON_STORAGE_SYSTEM_ITEM_ICON_1, // Used implicitly in CreateItemIconSprites
    GFX_TAG_MON_STORAGE_SYSTEM_ITEM_ICON_2, // Used implicitly in CreateItemIconSprites
    GFX_TAG_MON_STORAGE_SYSTEM_CHOOSE_BOX_MENU,
    GFX_TAG_MON_STORAGE_SYSTEM_CHOOSE_BOX_MENU_SIDES, // Used implicitly in LoadChooseBoxMenuGfx
    GFX_TAG_MON_STORAGE_SYSTEM_12, // Unused
    GFX_TAG_MON_STORAGE_SYSTEM_MARKING_MENU,
    GFX_TAG_MON_STORAGE_SYSTEM_14, // Unused
    GFX_TAG_MON_STORAGE_SYSTEM_15, // Unused
    GFX_TAG_MON_STORAGE_SYSTEM_MARKING_COMBO,
    GFX_TAG_MON_STORAGE_SYSTEM_17, // Unused
    GFX_TAG_MON_STORAGE_SYSTEM_MON_ICON,

    // naming_screen.c
    GFX_TAG_NAMING_SCREEN_BACK_BUTTON = 0,
    GFX_TAG_NAMING_SCREEN_OK_BUTTON,
    GFX_TAG_NAMING_SCREEN_PAGE_SWAP_FRAME,
    GFX_TAG_NAMING_SCREEN_PAGE_SWAP_BUTTON,
    GFX_TAG_NAMING_SCREEN_PAGE_SWAP_UPPER,
    GFX_TAG_NAMING_SCREEN_PAGE_SWAP_LOWER,
    GFX_TAG_NAMING_SCREEN_PAGE_SWAP_OTHERS,
    GFX_TAG_NAMING_SCREEN_CURSOR,
    GFX_TAG_NAMING_SCREEN_CURSOR_SQUISHED,
    GFX_TAG_NAMING_SCREEN_CURSOR_FILLED,
    GFX_TAG_NAMING_SCREEN_INPUT_ARROW,
    GFX_TAG_NAMING_SCREEN_UNDERSCORE,

    PAL_TAG_NAMING_SCREEN_MENU = 0, // Also the PC icon
    PAL_TAG_NAMING_SCREEN_PAGE_SWAP_UPPER,
    PAL_TAG_NAMING_SCREEN_PAGE_SWAP_LOWER,
    PAL_TAG_NAMING_SCREEN_PAGE_SWAP_OTHERS, // Also the input arrow/underscore
    PAL_TAG_NAMING_SCREEN_PAGE_SWAP,
    PAL_TAG_NAMING_SCREEN_CURSOR,
    PAL_TAG_NAMING_SCREEN_BACK_BUTTON,
    PAL_TAG_NAMING_SCREEN_OK_BUTTON,

    // slot_machine.c
    GFX_TAG_SLOT_MACHINE_7_RED = 0,
    GFX_TAG_SLOT_MACHINE_7_BLUE,
    GFX_TAG_SLOT_MACHINE_AZURILL,
    GFX_TAG_SLOT_MACHINE_LOTAD,
    GFX_TAG_SLOT_MACHINE_CHERRY,
    GFX_TAG_SLOT_MACHINE_POWER,
    GFX_TAG_SLOT_MACHINE_REPLAY,
    GFX_TAG_SLOT_MACHINE_NUM_0,
    GFX_TAG_SLOT_MACHINE_NUM_1,
    GFX_TAG_SLOT_MACHINE_NUM_2,
    GFX_TAG_SLOT_MACHINE_NUM_3,
    GFX_TAG_SLOT_MACHINE_NUM_4,
    GFX_TAG_SLOT_MACHINE_NUM_5,
    GFX_TAG_SLOT_MACHINE_NUM_6,
    GFX_TAG_SLOT_MACHINE_NUM_7,
    GFX_TAG_SLOT_MACHINE_NUM_8,
    GFX_TAG_SLOT_MACHINE_NUM_9,
    GFX_TAG_SLOT_MACHINE_REEL_BG,
    GFX_TAG_SLOT_MACHINE_STOP,
    GFX_TAG_SLOT_MACHINE_BONUS,
    GFX_TAG_SLOT_MACHINE_BIG,
    GFX_TAG_SLOT_MACHINE_REG,

    PAL_TAG_SLOT_MACHINE_REEL = 0,
    PAL_TAG_SLOT_MACHINE_REEL_TIME_PIKACHU,
    PAL_TAG_SLOT_MACHINE_REEL_TIME_MISC,
    PAL_TAG_SLOT_MACHINE_REEL_TIME_MACHINE,
    PAL_TAG_SLOT_MACHINE_MISC,
    PAL_TAG_SLOT_MACHINE_EXPLOSION,
    PAL_TAG_SLOT_MACHINE_DIG_DISPLAY,
    PAL_TAG_SLOT_MACHINE_PIKA_AURA,

    // roulette.c
    PAL_TAG_ROULETTE_SHADOW = 1,
    PAL_TAG_ROULETTE_BALL,
    PAL_TAG_ROULETTE_BALL_COUNTER,
    PAL_TAG_ROULETTE_CURSOR,
    PAL_TAG_ROULETTE_INTERFACE,
    PAL_TAG_ROULETTE_SHROOMISH,
    PAL_TAG_ROULETTE_TAILLOW,
    PAL_TAG_ROULETTE_GRID_ICONS,
    PAL_TAG_ROULETTE_WYNAUT,
    PAL_TAG_ROULETTE_AZURILL,
    PAL_TAG_ROULETTE_SKITTY,
    PAL_TAG_ROULETTE_MAKUHITA,

    GFX_TAG_ROULETTE_WHEEL_ICONS = 0,
    GFX_TAG_ROULETTE_HEADERS = 4,
    GFX_TAG_ROULETTE_GRID_ICONS,
    GFX_TAG_ROULETTE_WHEEL_CENTER,
    GFX_TAG_ROULETTE_CREDIT,
    GFX_TAG_ROULETTE_CREDIT_DIGIT,
    GFX_TAG_ROULETTE_MULTIPLIER,
    GFX_TAG_ROULETTE_BALL_COUNTER,
    GFX_TAG_ROULETTE_CURSOR,
    GFX_TAG_ROULETTE_BALL,
    GFX_TAG_ROULETTE_SHROOMISH_TAILLOW,
    GFX_TAG_ROULETTE_SHADOW,

    // pokemon_jump.c
    TAG_POKEMON_JUMP_MON1 = 0,
    TAG_POKEMON_JUMP_MON2, // MON2-5 used implicitly by adding multiplayer id to tag
    TAG_POKEMON_JUMP_MON3,
    TAG_POKEMON_JUMP_MON4,
    TAG_POKEMON_JUMP_MON5,

    GFX_TAG_POKEMON_JUMP_VINE1,
    GFX_TAG_POKEMON_JUMP_VINE2,
    GFX_TAG_POKEMON_JUMP_VINE3,
    GFX_TAG_POKEMON_JUMP_VINE4,
    GFX_TAG_POKEMON_JUMP_COUNTDOWN,
    GFX_TAG_POKEMON_JUMP_STAR,

    PAL_TAG_POKEMON_JUMP_1 = 5,
    PAL_TAG_POKEMON_JUMP_2,
    PAL_TAG_POKEMON_JUMP_COUNTDOWN,

    // pokenav_list.c
    GFX_TAG_POKENAV_LIST_ARROW = 10,
    PAL_TAG_POKENAV_LIST_ARROW = 20,

    TAG_POKEMON_JUMP_DIGITS = 800,

    // dodrio_berry_picking.c
    GFX_TAG_DODRIO_BERRY_PICKING_DODRIO = 0,
    GFX_TAG_DODRIO_BERRY_PICKING_STATUS,
    GFX_TAG_DODRIO_BERRY_PICKING_BERRIES,
    GFX_TAG_DODRIO_BERRY_PICKING_CLOUD = 5,
    GFX_TAG_DODRIO_BERRY_PICKING_COUNTDOWN = 7,

    PAL_TAG_DODRIO_BERRY_PICKING_DODRIO_NORMAL = 0,
    PAL_TAG_DODRIO_BERRY_PICKING_DODRIO_SHINY,
    PAL_TAG_DODRIO_BERRY_PICKING_STATUS,
    PAL_TAG_DODRIO_BERRY_PICKING_BERRIES,
    PAL_TAG_DODRIO_BERRY_PICKING_CLOUD = 6,
    PAL_TAG_DODRIO_BERRY_PICKING_COUNTDOWN = 8,

    // berry_crush.c
    TAG_BERRY_CRUSH_CRUSHER_BASE = 1,
    PAL_TAG_BERRY_CRUSH_EFFECT,
    GFX_TAG_BERRY_CRUSH_IMPACT = 2,
    GFX_TAG_BERRY_CRUSH_SPARKLE,
    TAG_BERRY_CRUSH_TIMER_DIGITS,
    TAG_BERRY_CRUSH_PLAYER1_BERRY,
    TAG_BERRY_CRUSH_PLAYER2_BERRY,
    TAG_BERRY_CRUSH_PLAYER3_BERRY,
    TAG_BERRY_CRUSH_PLAYER4_BERRY,
    TAG_BERRY_CRUSH_PLAYER5_BERRY,

    TAG_BERRY_CRUSH_COUNTDOWN = 4096,

    // battle_dome.c
    TAG_BATTLE_DOME_TOURNEY_TREE_BUTTONS = 0,

    // use_pokeblock.c
    TAG_USE_POKEBLOCK_MENU_UP_DOWN = 0,
    TAG_USE_POKEBLOCK_MENU_CONDITION,

    // easy_chat.c
    TAG_EASY_CHAT_TRIANGLE_CURSOR = 0,
    TAG_EASY_CHAT_RECTANGLE_CURSOR,

    PAL_TAG_EASY_CHAT_MISC_UI,
    PAL_TAG_EASY_CHAT_RS_INTERVIEW_FRAME,

    GFX_TAG_EASY_CHAT_SCROLL_INDICATOR = 2,
    GFX_TAG_EASY_CHAT_START_SELECT_BUTTONS,
    GFX_TAG_EASY_CHAT_MODE_WINDOW,
    GFX_TAG_EASY_CHAT_RS_INTERVIEW_FRAME,
    GFX_TAG_EASY_CHAT_BUTTON_WINDOW,

    // region_map.c
    TAG_REGION_MAP_CURSOR = 0,
    TAG_REGION_MAP_PLAYER_ICON,
    TAG_REGION_MAP_FLY_ICON,

    // frontier_pass.c
    TAG_FRONTIER_PASS_CURSOR = 0,
    TAG_FRONTIER_PASS_MAP_INDICATOR,
    TAG_FRONTIER_PASS_MEDAL_SILVER,
    TAG_FRONTIER_PASS_MEDAL_GOLD,
    TAG_FRONTIER_PASS_HEAD_MALE,
    TAG_FRONTIER_PASS_HEAD_FEMALE,

    // union_room_chat.c
    GFX_TAG_UNION_ROOM_CHAT_KEYBOARD_CURSOR = 0,
    GFX_TAG_UNION_ROOM_CHAT_TEXT_ENTRY_ARROW,
    GFX_TAG_UNION_ROOM_CHAT_TEXT_ENTRY_CURSOR,
    GFX_TAG_UNION_ROOM_CHAT_RBUTTON_ICON,
    GFX_TAG_UNION_ROOM_CHAT_RBUTTON_LABELS,

    // Shared by GFX_TAG_UNION_ROOM_CHAT_* above
    PAL_TAG_UNION_ROOM_CHAT_INTERFACE = 0,

    // pokenav_menu_handler_gfx.c
    GFX_TAG_POKENAV_MENU_BLUE_LIGHT = 1,
    GFX_TAG_POKENAV_MENU_OPTIONS = 3,

    PAL_TAG_POKENAV_MENU_BLUE_LIGHT = 3,
    PAL_TAG_POKENAV_MENU_OPTIONS_DEFAULT, // Includes green for Smart/Region Map and yellow for Tough
    PAL_TAG_POKENAV_MENU_OPTIONS_BLUE,
    PAL_TAG_POKENAV_MENU_OPTIONS_PINK,
    PAL_TAG_POKENAV_MENU_OPTIONS_BEIGE,
    PAL_TAG_POKENAV_MENU_OPTIONS_RED,

    PAL_TAG_POKENAV_MENU_OPTIONS_START = PAL_TAG_POKENAV_MENU_OPTIONS_DEFAULT,

    // pokenav_region_map.c
    GFX_TAG_POKENAV_MAP_CITY_ZOOM = 6,
    PAL_TAG_POKENAV_MAP_CITY_ZOOM = 11,

    // pokenav_match_call_gfx.c
    GFX_TAG_POKENAV_MATCH_CALL_CURSOR = 7,
    GFX_TAG_POKENAV_MATCH_CALL_TRAINER_PIC,

    PAL_TAG_POKENAV_MATCH_CALL_CURSOR = 12,
    PAL_TAG_POKENAV_MATCH_CALL_TRAINER_PIC,

    // pokenav_ribbons_summary.c
    GFX_TAG_POKENAV_RIBBONS_SUMMARY_RIBBON_ICONS_BIG = 9,

    PAL_TAG_POKENAV_RIBBONS_SUMMARY_RIBBON_ICONS_1 = 15,
    PAL_TAG_POKENAV_RIBBONS_SUMMARY_RIBBON_ICONS_2,
    PAL_TAG_POKENAV_RIBBONS_SUMMARY_RIBBON_ICONS_3,
    PAL_TAG_POKENAV_RIBBONS_SUMMARY_RIBBON_ICONS_4,
    PAL_TAG_POKENAV_RIBBONS_SUMMARY_RIBBON_ICONS_5,

    // pokenav_conditions_gfx.c
    TAG_POKENAV_CONDITION_MON = 100,
    TAG_POKENAV_CONDITION_BALL,
    TAG_POKENAV_CONDITION_CANCEL,
    TAG_POKENAV_CONDITION_BALL_PLACEHOLDER,
    TAG_POKENAV_CONDITION_SPARKLE,
    TAG_POKENAV_CONDITION_MON_MARKINGS,
    TAG_POKENAV_CONDITION_MARKINGS_MENU,
    TAG_POKENAV_CONDITION_MARKINGS_MENU_2, // Used implicitly by CreateMonMarkingsMenuSprites

    // item_menu_icons.c
    TAG_ITEM_MENU_ICONS_BAG = 100,
    TAG_ITEM_MENU_ICONS_ROTATING_BALL,
    TAG_ITEM_MENU_ICONS_ITEM_ICON,
    TAG_ITEM_MENU_ICONS_ITEM_ICON_ALT,

    // battle_factory_screen.c
    TAG_BATTLE_FACTORY_SCREEN_BALL_GRAY = 100,
    GFX_TAG_BATTLE_FACTORY_SCREEN_ARROW,
    GFX_TAG_BATTLE_FACTORY_SCREEN_MENU_HIGHLIGHT_LEFT,
    GFX_TAG_BATTLE_FACTORY_SCREEN_MENU_HIGHLIGHT_RIGHT,
    GFX_TAG_BATTLE_FACTORY_SCREEN_ACTION_BOX_LEFT,
    GFX_TAG_BATTLE_FACTORY_SCREEN_ACTION_BOX_RIGHT,
    GFX_TAG_BATTLE_FACTORY_SCREEN_ACTION_HIGHLIGHT_LEFT,
    GFX_TAG_BATTLE_FACTORY_SCREEN_ACTION_HIGHLIGHT_MIDDLE,
    GFX_TAG_BATTLE_FACTORY_SCREEN_ACTION_HIGHLIGHT_RIGHT,
    GFX_TAG_BATTLE_FACTORY_SCREEN_MON_PIC_BG_ANIM,

    PAL_TAG_BATTLE_FACTORY_SCREEN_BALL_SELECTED = 101,
    PAL_TAG_BATTLE_FACTORY_SCREEN_INTERFACE,
    PAL_TAG_BATTLE_FACTORY_SCREEN_MON_PIC_BG,

    // item_menu.c
    TAG_ITEM_MENU_POCKET_SCROLL_ARROW = 110,
    TAG_ITEM_MENU_SCROLL_ARROW = 111,

    // battle_arena.c
    TAG_BATTLE_ARENA_JUDGMENT_ICON = 1000,

    // evolution_graphics.c
    TAG_EVOLUTION_SCENE_SPARKLE = 1001,

    // hall_of_fame.c
    TAG_HALL_OF_FAME_CONFETTI = 1001,

    // credits.c
    TAG_CREDITS_MON_BG = 1001,

    // intro_credits_graphics.c
    TAG_INTROCRED_BICYCLE = 1001,
    TAG_INTROCRED_BRENDAN,
    TAG_INTROCRED_MAY,
    TAG_INTROCRED_FLYGON_LATIOS,
    TAG_INTROCRED_FLYGON_LATIAS,

    TAG_INTROCRED_MOVING_SCENERY = 2000, // Used for the Clouds/Trees/Houses sprites that pass by in the background

    // party_menu.c
    TAG_PARTY_MENU_POKEBALL = 1200,
    TAG_PARTY_MENU_POKEBALL_SMALL,
    TAG_PARTY_MENU_STATUS_ICONS,

    // intro.c
    TAG_INTRO_VOLBEAT = 1500,
    TAG_INTRO_TORCHIC,
    TAG_INTRO_MANECTRIC,
    TAG_INTRO_LIGHTNING,
    TAG_INTRO_BUBBLES,
    TAG_INTRO_SPARKLE,

    GFX_TAG_INTRO_DROPS_LOGO = 2000,

    PAL_TAG_INTRO_DROPS = 2000,
    PAL_TAG_INTRO_LOGO,

    TAG_INTRO_FLYGON_SILHOUETTE,
    TAG_INTRO_RAYQUAZA_ORB,

    // shop.c
    TAG_SHOP_MENU_SCROLL_ARROW = 2100,
    TAG_SHOP_MENU_ITEM_ICON_BASE = 2110,

    // decoration.c
    PAL_TAG_PLACE_DECORATION_PLAYER = 8,
    PAL_TAG_PLACE_DECORATION_SELECTOR = 3045,

    // mirage_tower.c
    TAG_MIRAGE_TOWER_CEILING_CRUMBLE = 4000,

    // reset_rtc_screen.c
    PAL_TAG_RESET_RTC_SCREEN_ARROW = 4096,

    // starter_choose.c
    TAG_STARTER_CHOOSE_POKEBALL_SELECT = 4096,
    TAG_STARTER_CHOOSE_STARTER_CIRCLE,

    // wallclock.c
    GFX_TAG_WALL_CLOCK_HAND = 4096,
    PAL_TAG_WALL_CLOCK_MALE = 4096,
    PAL_TAG_WALL_CLOCK_FEMALE,

    // event_object_movement.c
    // field_effect.c
    // field_effect_helpers.c
    PAL_TAG_FLDEFF_RECORD_MIX_LIGHTS = 4096,
    PAL_TAG_FLDEFF_CUT_GRASS = 4096,
    PAL_TAG_FLDEFF_SECRET_POWER_TREE = 4099,
    PAL_TAG_FLDEFF_GENERAL_0,
    PAL_TAG_FLDEFF_GENERAL_1,
    PAL_TAG_FLDEFF_NEW_GAME_BIRCH,
    PAL_TAG_FLDEFF_POKEBALL_GLOW,
    PAL_TAG_FLDEFF_SECRET_POWER_PLANT,
    PAL_TAG_FLDEFF_POKEBALL_TRAIL,
    PAL_TAG_FLDEFF_UNUSED_MUGSHOT,
    PAL_TAG_FLDEFF_ASH = 4109,
    PAL_TAG_FLDEFF_SAND_PILLAR,
    PAL_TAG_FLDEFF_SMALL_SPARKLE,
    PAL_TAG_FLDEFF_HOF_MONITOR,
    PAL_TAG_FLDEFF_UNKNOWN,

    // battle_pyramid_bag.c
    TAG_BATTLE_PYRAMID_BAG_MENU_SCROLL_ARROW = 2910,
    TAG_BATTLE_PYRAMID_BAG = 4132,
    TAG_BATTLE_PYRAMID_BAG_MENU_ITEM_ICON,
    TAG_BATTLE_PYRAMID_BAG_MENU_ITEM_ICON_ALT,

    // event_object_movement.c
    PAL_TAG_OBJ_EVENT_BRENDAN = 4352,
    PAL_TAG_OBJ_EVENT_BRENDAN_REFLECTION,
    PAL_TAG_OBJ_EVENT_BRIDGE_REFLECTION,
    PAL_TAG_OBJ_EVENT_NPC_1,
    PAL_TAG_OBJ_EVENT_NPC_2,
    PAL_TAG_OBJ_EVENT_NPC_3,
    PAL_TAG_OBJ_EVENT_NPC_4,
    PAL_TAG_OBJ_EVENT_NPC_1_REFLECTION,
    PAL_TAG_OBJ_EVENT_NPC_2_REFLECTION,
    PAL_TAG_OBJ_EVENT_NPC_3_REFLECTION,
    PAL_TAG_OBJ_EVENT_NPC_4_REFLECTION,
    PAL_TAG_OBJ_EVENT_QUINTY_PLUMP,
    PAL_TAG_OBJ_EVENT_QUINTY_PLUMP_REFLECTION,
    PAL_TAG_OBJ_EVENT_TRUCK,
    PAL_TAG_OBJ_EVENT_VIGOROTH,
    PAL_TAG_OBJ_EVENT_ZIGZAGOON,
    PAL_TAG_OBJ_EVENT_MAY,
    PAL_TAG_OBJ_EVENT_MAY_REFLECTION,
    PAL_TAG_OBJ_EVENT_MOVING_BOX,
    PAL_TAG_OBJ_EVENT_CABLE_CAR,
    PAL_TAG_OBJ_EVENT_SSTIDAL,
    PAL_TAG_OBJ_EVENT_PLAYER_UNDERWATER,
    PAL_TAG_OBJ_EVENT_KYOGRE,
    PAL_TAG_OBJ_EVENT_KYOGRE_REFLECTION,
    PAL_TAG_OBJ_EVENT_GROUDON,
    PAL_TAG_OBJ_EVENT_GROUDON_REFLECTION,
    PAL_TAG_OBJ_EVENT_BIRTH_ISLAND_STONE_FRAGMENT,
    PAL_TAG_OBJ_EVENT_SUBMARINE_SHADOW,
    PAL_TAG_OBJ_EVENT_POOCHYENA,
    PAL_TAG_OBJ_EVENT_RED_LEAF,
    PAL_TAG_OBJ_EVENT_DEOXYS,
    PAL_TAG_OBJ_EVENT_BIRTH_ISLAND_STONE,
    PAL_TAG_OBJ_EVENT_HO_OH,
    PAL_TAG_OBJ_EVENT_LUGIA,
    PAL_TAG_OBJ_EVENT_RS_BRENDAN,
    PAL_TAG_OBJ_EVENT_RS_MAY,
    PAL_TAG_OBJ_EVENT_NONE = 4607,

    // field_weather.c
    // field_weather_effect.c
    TAG_WEATHER_START,
    GFX_TAG_WEATHER_CLOUD = TAG_WEATHER_START,
    GFX_TAG_WEATHER_FOG_H,
    GFX_TAG_WEATHER_ASH,
    GFX_TAG_WEATHER_FOG_D,
    GFX_TAG_WEATHER_SANDSTORM,
    GFX_TAG_WEATHER_BUBBLE,
    GFX_TAG_WEATHER_RAIN,

    PAL_TAG_WEATHER = TAG_WEATHER_START,
    PAL_TAG_WEATHER_2,

    // rotating_gate.c
    GFX_TAG_ROTATING_GATE = 4864,

    // player_pc.c
    TAG_PLAYER_PC_MENU_ITEM_ICON = 5110,
    TAG_PLAYER_PC_MENU_SCROLL_ARROW = 5112,

    // secret_base.c
    TAG_SECRET_BASE_REGISTRY_MENU_SCROLL_ARROW = 5112,

    // move_relearner.c
    TAG_MOVE_RELEARNER_MODE_ARROWS = 5325,
    TAG_MOVE_RELEARNER_LIST_ARROWS = 5425,
    GFX_TAG_MOVE_RELEARNER_UI = 5525,
    PAL_TAG_MOVE_RELEARNER_UI = 5526,

    // field_specials.c
    TAG_FIELD_SPECIALS_ITEM_ICON = 5500, // Only used in the Frontier Exchange Corner menu

    GFX_TAG_FIELD_SPECIALS_MULTICHOICE_SCROLL_ARROWS = 2000,
    PAL_TAG_FIELD_SPECIALS_MULTICHOICE_SCROLL_ARROWS = 100,

    // trade.c
    GFX_TAG_TRADE_MENU_TEXT = 200, // Used as a base tag in CB2_CreateTradeMenu and CB2_ReturnToTradeMenu
    GFX_TAG_TRADE_CURSOR = 300,
    GFX_TAG_TRADE_LINK_MON_GLOW = 5550,
    GFX_TAG_TRADE_LINK_MON_SHADOW = 5552,
    GFX_TAG_TRADE_CABLE_END = 5554,
    GFX_TAG_TRADE_GBA_SCREEN = 5556,
    GFX_TAG_TRADE_POKEBALL = 5557,

    PAL_TAG_TRADE_CURSOR = 2345,
    PAL_TAG_TRADE_MENU_TEXT = 4925,
    PAL_TAG_TRADE_LINK_MON = 5551,
    PAL_TAG_TRADE_GBA = 5555,
    PAL_TAG_TRADE_POKEBALL = 5558,

    // minigame_countdown.c
    TAG_MINIGAME_STATIC_COUNTDOWN = 8192,

    // battle_bg.c
    // battle_main.c
    TAG_LINK_BATTLE_VS_LETTERS = 10000,

    // item_menu_icons.c
    GFX_TAG_BERRY_CHECK_FLAVOR_CIRCLE = 10000,
    PAL_TAG_BERRY_CHECK_PIC = 30020,

    // money.c
    TAG_MONEY_BOX_LABEL = 10018,

    // Various battle anims
    ANIM_SPRITES_START = 10000,
    TAG_BATTLE_ANIM_BONE = ANIM_SPRITES_START,
    TAG_BATTLE_ANIM_SPARK,
    TAG_BATTLE_ANIM_PENCIL,
    TAG_BATTLE_ANIM_AIR_WAVE,
    TAG_BATTLE_ANIM_ORB,
    TAG_BATTLE_ANIM_SWORD,
    TAG_BATTLE_ANIM_SEED,
    TAG_BATTLE_ANIM_EXPLOSION_6,
    TAG_BATTLE_ANIM_PINK_ORB,            // unused
    TAG_BATTLE_ANIM_GUST,
    TAG_BATTLE_ANIM_ICE_CUBE,
    TAG_BATTLE_ANIM_SPARK_2,
    TAG_BATTLE_ANIM_ORANGE,              // unused
    TAG_BATTLE_ANIM_YELLOW_BALL,
    TAG_BATTLE_ANIM_LOCK_ON,
    TAG_BATTLE_ANIM_TIED_BAG,
    TAG_BATTLE_ANIM_BLACK_SMOKE,
    TAG_BATTLE_ANIM_BLACK_BALL,
    TAG_BATTLE_ANIM_CONVERSION,
    TAG_BATTLE_ANIM_GLASS,               // unused
    TAG_BATTLE_ANIM_HORN_HIT,
    TAG_BATTLE_ANIM_HIT,
    TAG_BATTLE_ANIM_HIT_2,
    TAG_BATTLE_ANIM_BLUE_SHARDS,         // unused
    TAG_BATTLE_ANIM_CLOSING_EYE,         // unused
    TAG_BATTLE_ANIM_WAVING_HAND,         // unused
    TAG_BATTLE_ANIM_HIT_DUPLICATE,       // unused
    TAG_BATTLE_ANIM_LEER,
    TAG_BATTLE_ANIM_BLUE_BURST,          // unused
    TAG_BATTLE_ANIM_SMALL_EMBER,
    TAG_BATTLE_ANIM_GRAY_SMOKE,
    TAG_BATTLE_ANIM_BLUE_STAR,
    TAG_BATTLE_ANIM_BUBBLE_BURST,
    TAG_BATTLE_ANIM_FIRE,
    TAG_BATTLE_ANIM_SPINNING_FIRE,       // unused
    TAG_BATTLE_ANIM_FIRE_PLUME,
    TAG_BATTLE_ANIM_LIGHTNING_2,         // unused
    TAG_BATTLE_ANIM_LIGHTNING,
    TAG_BATTLE_ANIM_CLAW_SLASH_2,        // unused
    TAG_BATTLE_ANIM_CLAW_SLASH,
    TAG_BATTLE_ANIM_SCRATCH_3,           // unused
    TAG_BATTLE_ANIM_SCRATCH_2,           // unused
    TAG_BATTLE_ANIM_BUBBLE_BURST_2,      // unused
    TAG_BATTLE_ANIM_ICE_CHUNK,
    TAG_BATTLE_ANIM_GLASS_2,             // unused
    TAG_BATTLE_ANIM_PINK_HEART_2,        // unused
    TAG_BATTLE_ANIM_SAP_DRIP,            // unused
    TAG_BATTLE_ANIM_SAP_DRIP_2,          // unused
    TAG_BATTLE_ANIM_SPARKLE_1,
    TAG_BATTLE_ANIM_SPARKLE_2,
    TAG_BATTLE_ANIM_HUMANOID_FOOT,
    TAG_BATTLE_ANIM_MONSTER_FOOT,
    TAG_BATTLE_ANIM_HUMANOID_HAND,       // unused
    TAG_BATTLE_ANIM_NOISE_LINE,
    TAG_BATTLE_ANIM_YELLOW_UNK,          // unused
    TAG_BATTLE_ANIM_RED_FIST,            // unused
    TAG_BATTLE_ANIM_SLAM_HIT,
    TAG_BATTLE_ANIM_RING,                // unused
    TAG_BATTLE_ANIM_ROCKS,
    TAG_BATTLE_ANIM_Z,                   // unused
    TAG_BATTLE_ANIM_YELLOW_UNK_2,        // unused
    TAG_BATTLE_ANIM_AIR_SLASH,           // unused
    TAG_BATTLE_ANIM_SPINNING_GREEN_ORBS, // unused
    TAG_BATTLE_ANIM_LEAF,
    TAG_BATTLE_ANIM_FINGER,
    TAG_BATTLE_ANIM_POISON_POWDER,
    TAG_BATTLE_ANIM_BROWN_TRIANGLE,      // unused
    TAG_BATTLE_ANIM_SLEEP_POWDER,
    TAG_BATTLE_ANIM_STUN_SPORE,
    TAG_BATTLE_ANIM_POWDER,              // unused
    TAG_BATTLE_ANIM_SPARKLE_3,
    TAG_BATTLE_ANIM_SPARKLE_4,
    TAG_BATTLE_ANIM_MUSIC_NOTES,
    TAG_BATTLE_ANIM_DUCK,
    TAG_BATTLE_ANIM_MUD_SAND,
    TAG_BATTLE_ANIM_ALERT,
    TAG_BATTLE_ANIM_BLUE_FLAMES,         // unused
    TAG_BATTLE_ANIM_BLUE_FLAMES_2,       // unused
    TAG_BATTLE_ANIM_SHOCK_4,             // unused
    TAG_BATTLE_ANIM_SHOCK,
    TAG_BATTLE_ANIM_BELL_2,              // unused
    TAG_BATTLE_ANIM_PINK_GLOVE,          // unused
    TAG_BATTLE_ANIM_BLUE_LINES,          // unused
    TAG_BATTLE_ANIM_IMPACT_3,            // unused
    TAG_BATTLE_ANIM_IMPACT_2,            // unused
    TAG_BATTLE_ANIM_RETICLE,             // unused
    TAG_BATTLE_ANIM_BREATH,
    TAG_BATTLE_ANIM_ANGER,
    TAG_BATTLE_ANIM_SNOWBALL,            // unused
    TAG_BATTLE_ANIM_VINE,                // unused
    TAG_BATTLE_ANIM_SWORD_2,             // unused
    TAG_BATTLE_ANIM_CLAPPING,            // unused
    TAG_BATTLE_ANIM_RED_TUBE,            // unused
    TAG_BATTLE_ANIM_AMNESIA,
    TAG_BATTLE_ANIM_STRING_2,            // unused
    TAG_BATTLE_ANIM_PENCIL_2,            // unused
    TAG_BATTLE_ANIM_PETAL,               // unused
    TAG_BATTLE_ANIM_BENT_SPOON,
    TAG_BATTLE_ANIM_WEB,                 // unused
    TAG_BATTLE_ANIM_MILK_BOTTLE,
    TAG_BATTLE_ANIM_COIN,
    TAG_BATTLE_ANIM_CRACKED_EGG,         // unused
    TAG_BATTLE_ANIM_HATCHED_EGG,         // unused
    TAG_BATTLE_ANIM_FRESH_EGG,           // unused
    TAG_BATTLE_ANIM_FANGS,               // unused
    TAG_BATTLE_ANIM_EXPLOSION_2,         // unused
    TAG_BATTLE_ANIM_EXPLOSION_3,         // unused
    TAG_BATTLE_ANIM_WATER_DROPLET,       // unused
    TAG_BATTLE_ANIM_WATER_DROPLET_2,     // unused
    TAG_BATTLE_ANIM_SEED_2,              // unused
    TAG_BATTLE_ANIM_SPROUT,              // unused
    TAG_BATTLE_ANIM_RED_WAND,            // unused
    TAG_BATTLE_ANIM_PURPLE_GREEN_UNK,    // unused
    TAG_BATTLE_ANIM_WATER_COLUMN,        // unused
    TAG_BATTLE_ANIM_MUD_UNK,             // unused
    TAG_BATTLE_ANIM_RAIN_DROPS,
    TAG_BATTLE_ANIM_FURY_SWIPES,         // unused
    TAG_BATTLE_ANIM_VINE_2,              // unused
    TAG_BATTLE_ANIM_TEETH,               // unused
    TAG_BATTLE_ANIM_BONE_2,              // unused
    TAG_BATTLE_ANIM_WHITE_BAG,           // unused
    TAG_BATTLE_ANIM_UNKNOWN,             // unused
    TAG_BATTLE_ANIM_PURPLE_CORAL,        // unused
    TAG_BATTLE_ANIM_PURPLE_DROPLET,      // unused
    TAG_BATTLE_ANIM_SHOCK_2,             // unused
    TAG_BATTLE_ANIM_CLOSING_EYE_2,       // unused
    TAG_BATTLE_ANIM_METAL_BALL,          // unused
    TAG_BATTLE_ANIM_MONSTER_DOLL,        // unused
    TAG_BATTLE_ANIM_WHIRLWIND,           // unused
    TAG_BATTLE_ANIM_WHIRLWIND_2,         // unused
    TAG_BATTLE_ANIM_EXPLOSION_4,         // unused
    TAG_BATTLE_ANIM_EXPLOSION_5 ,        // unused
    TAG_BATTLE_ANIM_TONGUE,              // unused
    TAG_BATTLE_ANIM_SMOKE,               // unused
    TAG_BATTLE_ANIM_SMOKE_2,             // unused
    TAG_BATTLE_ANIM_IMPACT,
    TAG_BATTLE_ANIM_CIRCLE_IMPACT,
    TAG_BATTLE_ANIM_SCRATCH,
    TAG_BATTLE_ANIM_CUT,
    TAG_BATTLE_ANIM_SHARP_TEETH,
    TAG_BATTLE_ANIM_RAINBOW_RINGS,
    TAG_BATTLE_ANIM_ICE_CRYSTALS,
    TAG_BATTLE_ANIM_ICE_SPIKES,
    TAG_BATTLE_ANIM_HANDS_AND_FEET,
    TAG_BATTLE_ANIM_MIST_CLOUD,
    TAG_BATTLE_ANIM_CLAMP,
    TAG_BATTLE_ANIM_BUBBLE,
    TAG_BATTLE_ANIM_ORBS,
    TAG_BATTLE_ANIM_WATER_IMPACT,
    TAG_BATTLE_ANIM_WATER_ORB,
    TAG_BATTLE_ANIM_POISON_BUBBLE,
    TAG_BATTLE_ANIM_TOXIC_BUBBLE,
    TAG_BATTLE_ANIM_SPIKES,
    TAG_BATTLE_ANIM_HORN_HIT_2,
    TAG_BATTLE_ANIM_AIR_WAVE_2,
    TAG_BATTLE_ANIM_SMALL_BUBBLES,
    TAG_BATTLE_ANIM_ROUND_SHADOW,
    TAG_BATTLE_ANIM_SUNLIGHT,
    TAG_BATTLE_ANIM_SPORE,
    TAG_BATTLE_ANIM_FLOWER,
    TAG_BATTLE_ANIM_RAZOR_LEAF,
    TAG_BATTLE_ANIM_NEEDLE,
    TAG_BATTLE_ANIM_WHIRLWIND_LINES,
    TAG_BATTLE_ANIM_GOLD_RING,
    TAG_BATTLE_ANIM_PURPLE_RING,
    TAG_BATTLE_ANIM_BLUE_RING,
    TAG_BATTLE_ANIM_GREEN_LIGHT_WALL,
    TAG_BATTLE_ANIM_BLUE_LIGHT_WALL,
    TAG_BATTLE_ANIM_RED_LIGHT_WALL,
    TAG_BATTLE_ANIM_GRAY_LIGHT_WALL,
    TAG_BATTLE_ANIM_ORANGE_LIGHT_WALL,
    TAG_BATTLE_ANIM_BLACK_BALL_2,
    TAG_BATTLE_ANIM_PURPLE_GAS_CLOUD,
    TAG_BATTLE_ANIM_SPARK_H,
    TAG_BATTLE_ANIM_YELLOW_STAR,
    TAG_BATTLE_ANIM_LARGE_FRESH_EGG,
    TAG_BATTLE_ANIM_SHADOW_BALL,
    TAG_BATTLE_ANIM_LICK,
    TAG_BATTLE_ANIM_VOID_LINES,
    TAG_BATTLE_ANIM_STRING,
    TAG_BATTLE_ANIM_WEB_THREAD,
    TAG_BATTLE_ANIM_SPIDER_WEB,
    TAG_BATTLE_ANIM_LIGHTBULB,           // unused
    TAG_BATTLE_ANIM_SLASH,
    TAG_BATTLE_ANIM_FOCUS_ENERGY,
    TAG_BATTLE_ANIM_SPHERE_TO_CUBE,
    TAG_BATTLE_ANIM_TENDRILS,
    TAG_BATTLE_ANIM_EYE,
    TAG_BATTLE_ANIM_WHITE_SHADOW,
    TAG_BATTLE_ANIM_TEAL_ALERT,
    TAG_BATTLE_ANIM_OPENING_EYE,
    TAG_BATTLE_ANIM_ROUND_WHITE_HALO,
    TAG_BATTLE_ANIM_FANG_ATTACK,
    TAG_BATTLE_ANIM_PURPLE_HAND_OUTLINE,
    TAG_BATTLE_ANIM_MOON,
    TAG_BATTLE_ANIM_GREEN_SPARKLE,
    TAG_BATTLE_ANIM_SPIRAL,
    TAG_BATTLE_ANIM_SNORE_Z,
    TAG_BATTLE_ANIM_EXPLOSION,
    TAG_BATTLE_ANIM_NAIL,
    TAG_BATTLE_ANIM_GHOSTLY_SPIRIT,
    TAG_BATTLE_ANIM_WARM_ROCK,
    TAG_BATTLE_ANIM_BREAKING_EGG,
    TAG_BATTLE_ANIM_THIN_RING,
    TAG_BATTLE_ANIM_PUNCH_IMPACT,        // unused
    TAG_BATTLE_ANIM_BELL,
    TAG_BATTLE_ANIM_MUSIC_NOTES_2,
    TAG_BATTLE_ANIM_SPEED_DUST,
    TAG_BATTLE_ANIM_TORN_METAL,
    TAG_BATTLE_ANIM_THOUGHT_BUBBLE,
    TAG_BATTLE_ANIM_MAGENTA_HEART,
    TAG_BATTLE_ANIM_ELECTRIC_ORBS,
    TAG_BATTLE_ANIM_CIRCLE_OF_LIGHT,
    TAG_BATTLE_ANIM_ELECTRICITY,
    TAG_BATTLE_ANIM_FINGER_2,
    TAG_BATTLE_ANIM_MOVEMENT_WAVES,
    TAG_BATTLE_ANIM_RED_HEART,
    TAG_BATTLE_ANIM_RED_ORB,
    TAG_BATTLE_ANIM_EYE_SPARKLE,
    TAG_BATTLE_ANIM_PINK_HEART,
    TAG_BATTLE_ANIM_ANGEL,
    TAG_BATTLE_ANIM_DEVIL,
    TAG_BATTLE_ANIM_SWIPE,
    TAG_BATTLE_ANIM_ROOTS,
    TAG_BATTLE_ANIM_ITEM_BAG,
    TAG_BATTLE_ANIM_JAGGED_MUSIC_NOTE,
    TAG_BATTLE_ANIM_POKEBALL,
    TAG_BATTLE_ANIM_SPOTLIGHT,
    TAG_BATTLE_ANIM_LETTER_Z,
    TAG_BATTLE_ANIM_RAPID_SPIN,
    TAG_BATTLE_ANIM_TRI_ATTACK_TRIANGLE,
    TAG_BATTLE_ANIM_WISP_ORB,
    TAG_BATTLE_ANIM_WISP_FIRE,
    TAG_BATTLE_ANIM_GOLD_STARS,
    TAG_BATTLE_ANIM_ECLIPSING_ORB,
    TAG_BATTLE_ANIM_GRAY_ORB,
    TAG_BATTLE_ANIM_BLUE_ORB,
    TAG_BATTLE_ANIM_RED_ORB_2,
    TAG_BATTLE_ANIM_PINK_PETAL,
    TAG_BATTLE_ANIM_PAIN_SPLIT,
    TAG_BATTLE_ANIM_CONFETTI,
    TAG_BATTLE_ANIM_GREEN_STAR,
    TAG_BATTLE_ANIM_PINK_CLOUD,
    TAG_BATTLE_ANIM_SWEAT_DROP,
    TAG_BATTLE_ANIM_GUARD_RING,
    TAG_BATTLE_ANIM_PURPLE_SCRATCH,
    TAG_BATTLE_ANIM_PURPLE_SWIPE,
    TAG_BATTLE_ANIM_TAG_HAND,
    TAG_BATTLE_ANIM_SMALL_RED_EYE,
    TAG_BATTLE_ANIM_HOLLOW_ORB,
    TAG_BATTLE_ANIM_X_SIGN,
    TAG_BATTLE_ANIM_BLUEGREEN_ORB,
    TAG_BATTLE_ANIM_PAW_PRINT,
    TAG_BATTLE_ANIM_PURPLE_FLAME,
    TAG_BATTLE_ANIM_RED_BALL,
    TAG_BATTLE_ANIM_SMELLINGSALT_EFFECT,
    TAG_BATTLE_ANIM_METEOR,
    TAG_BATTLE_ANIM_FLAT_ROCK,
    TAG_BATTLE_ANIM_MAGNIFYING_GLASS,
    TAG_BATTLE_ANIM_BROWN_ORB,
    TAG_BATTLE_ANIM_METAL_SOUND_WAVES,
    TAG_BATTLE_ANIM_FLYING_DIRT,
    TAG_BATTLE_ANIM_ICICLE_SPEAR,
    TAG_BATTLE_ANIM_HAIL,
    TAG_BATTLE_ANIM_GLOWY_RED_ORB,
    TAG_BATTLE_ANIM_GLOWY_GREEN_ORB,
    TAG_BATTLE_ANIM_GREEN_SPIKE,
    TAG_BATTLE_ANIM_WHITE_CIRCLE_OF_LIGHT,
    TAG_BATTLE_ANIM_GLOWY_BLUE_ORB,
    TAG_BATTLE_ANIM_POKEBLOCK,
    TAG_BATTLE_ANIM_WHITE_FEATHER,
    TAG_BATTLE_ANIM_SPARKLE_6,
    TAG_BATTLE_ANIM_SPLASH,
    TAG_BATTLE_ANIM_SWEAT_BEAD,
    TAG_BATTLE_ANIM_GEM_1,               // unused
    TAG_BATTLE_ANIM_GEM_2,               // unused
    TAG_BATTLE_ANIM_GEM_3,               // unused
    TAG_BATTLE_ANIM_SLAM_HIT_2,
    TAG_BATTLE_ANIM_RECYCLE,
    TAG_BATTLE_ANIM_RED_PARTICLES,       // unused
    TAG_BATTLE_ANIM_PROTECT,
    TAG_BATTLE_ANIM_DIRT_MOUND,
    TAG_BATTLE_ANIM_SHOCK_3,
    TAG_BATTLE_ANIM_WEATHER_BALL,
    TAG_BATTLE_ANIM_BIRD,
    TAG_BATTLE_ANIM_CROSS_IMPACT,
    TAG_BATTLE_ANIM_SLASH_2,
    TAG_BATTLE_ANIM_WHIP_HIT,
    TAG_BATTLE_ANIM_BLUE_RING_2,

    // battle_transition_frontier.c
    TAG_B_TRANSITION_FRONTIER_LOGO_CIRCLES = 11920,

    // egg_hatch.c
    GFX_TAG_EGG = 12345,
    GFX_TAG_EGG_SHARD = 23456,

    PAL_TAG_EGG = 54321,

    // berry_blender.c
    GFX_TAG_BERRY_BLENDER_COUNTDOWN_NUMBERS = 12345,
    GFX_TAG_BERRY_BLENDER_START,
    GFX_TAG_BERRY_BLENDER_PARTICLES = 23456,
    GFX_TAG_BERRY_BLENDER_PLAYER_ARROW = 46545,
    GFX_TAG_BERRY_BLENDER_SCORE_SYMBOLS = 48888,

    PAL_TAG_BERRY_BLENDER_PLAYER_ARROW = 12312,
    PAL_TAG_BERRY_BLENDER_MISC = 46546,

    // pokeblock.c
    TAG_POKEBLOCK_CASE = 14800,
    TAG_POKEBLOCK_CASE_SCROLL_ARROW = 1110,

    // pokeblock_feed.c
    TAG_POKEBLOCK = 14818,

    // contest.c
    PAL_TAG_CONTEST_SYMBOLS = 44000,
    GFX_TAG_CONTEST_JUDGE_SYMBOLS = 44000,
    GFX_TAG_CONTEST_FACES,
    TAG_CONTEST_APPLAUSE_METER,

    TAG_CONTEST_SLIDER_HEART = 20000,
    TAG_CONTEST_JUDGE,
    PAL_TAG_CONTEST_NEXT_TURN,
    GFX_TAG_CONTEST_NEXT_TURN_1 = 20002,
    GFX_TAG_CONTEST_NEXT_TURN_2,
    GFX_TAG_CONTEST_NEXT_TURN_3,
    GFX_TAG_CONTEST_NEXT_TURN_4,

    TAG_CONTEST_BLINK_EFFECT_CONTESTANT0 = 33000,
    TAG_CONTEST_BLINK_EFFECT_CONTESTANT1,
    TAG_CONTEST_BLINK_EFFECT_CONTESTANT2,
    TAG_CONTEST_BLINK_EFFECT_CONTESTANT3,

    // pokemon_summary_screen.c
    TAG_MON_SUMMARY_SCREEN_MOVE_SELECTOR = 30000,
    TAG_MON_SUMMARY_SCREEN_MON_STATUS,
    TAG_MON_SUMMARY_SCREEN_MOVE_TYPES,
    TAG_MON_SUMMARY_SCREEN_MON_MARKINGS,

    // rayquaza_scene.c
    TAG_RAYQUAZA_SCENE_DUOFIGHT_GROUDON = 30505,
    TAG_RAYQUAZA_SCENE_DUOFIGHT_GROUDON_SHOULDER,
    TAG_RAYQUAZA_SCENE_DUOFIGHT_GROUDON_CLAW,
    TAG_RAYQUAZA_SCENE_DUOFIGHT_KYOGRE,
    TAG_RAYQUAZA_SCENE_DUOFIGHT_KYOGRE_PECTORAL_FIN,
    TAG_RAYQUAZA_SCENE_DUOFIGHT_KYOGRE_DORSAL_FIN,
    TAG_RAYQUAZA_SCENE_FLIGHT_SMOKE = 30555,
    TAG_RAYQUAZA_SCENE_DESCENDS_RAYQUAZA,
    TAG_RAYQUAZA_SCENE_DESCENDS_RAYQUAZA_TAIL,
    TAG_RAYQUAZA_SCENE_CHASE_GROUDON = 30565,
    TAG_RAYQUAZA_SCENE_CHASE_GROUDON_TAIL,
    TAG_RAYQUAZA_SCENE_CHASE_KYOGRE = 30568,
    TAG_RAYQUAZA_SCENE_CHASE_RAYQUAZA,
    TAG_RAYQUAZA_SCENE_CHASE_RAYQUAZA_TAIL,
    TAG_RAYQUAZA_SCENE_CHASE_SPLASH,

    // pokeball.c
    TAG_POKE_BALL = 55000,
    TAG_GREAT_BALL,
    TAG_SAFARI_BALL,
    TAG_ULTRA_BALL,
    TAG_MASTER_BALL,
    TAG_NET_BALL,
    TAG_DIVE_BALL,
    TAG_NEST_BALL,
    TAG_REPEAT_BALL,
    TAG_TIMER_BALL,
    TAG_LUXURY_BALL,
    TAG_PREMIER_BALL,

    // battle_anim_smokescreen.c
    TAG_BATTLE_ANIM_SMOKESCREEN = 55019,

    // battle_anim_throw.c
    TAG_PARTICLES_POKEBALL,
    TAG_PARTICLES_GREATBALL,
    TAG_PARTICLES_SAFARIBALL,
    TAG_PARTICLES_ULTRABALL,
    TAG_PARTICLES_MASTERBALL,
    TAG_PARTICLES_NETBALL,
    TAG_PARTICLES_DIVEBALL,
    TAG_PARTICLES_NESTBALL,
    TAG_PARTICLES_REPEATBALL,
    TAG_PARTICLES_TIMERBALL,
    TAG_PARTICLES_LUXURYBALL,
    TAG_PARTICLES_PREMIERBALL,

    // battle_controller_player.c
    PAL_TAG_CONTROLLER_PLAYER_BACK_PIC,
    // battle_controller_player_partner.c
    PAL_TAG_CONTROLLER_PLAYER_PARTNER_BACK_PIC,
    // battle_controller_wally.c
    PAL_TAG_CONTROLLER_WALLY_BACK_PIC = PAL_TAG_CONTROLLER_PLAYER_BACK_PIC,
    // battle_controller_link_partner.c
    PAL_TAG_CONTROLLER_LINK_PARTNER_BACK_PIC = PAL_TAG_CONTROLLER_PLAYER_PARTNER_BACK_PIC,
    // battle_controller_recorded_player.c
    PAL_TAG_CONTROLLER_RECORDED_PLAYER_BACK_PIC = PAL_TAG_CONTROLLER_LINK_PARTNER_BACK_PIC,

    // battle_interface.c
    GFX_TAG_HEALTHBOX_PLAYER1 = 55039,
    GFX_TAG_HEALTHBOX_PLAYER2,
    GFX_TAG_HEALTHBOX_OPPONENT1,
    GFX_TAG_HEALTHBOX_OPPONENT2,

    GFX_TAG_HEALTHBAR_PLAYER1 = 55044,
    GFX_TAG_HEALTHBAR_OPPONENT1,
    GFX_TAG_HEALTHBAR_PLAYER2,
    GFX_TAG_HEALTHBAR_OPPONENT2,

    PAL_TAG_HEALTHBOX_LVLUP_1 = 55049,
    PAL_TAG_HEALTHBOX_LVLUP_2,
    GFX_TAG_HEALTHBOX_SAFARI,
    GFX_TAG_STATUS_SUMMARY_BAR,

    PAL_TAG_STATUS_SUMMARY_BAR = 55056,
    PAL_TAG_STATUS_SUMMARY_BALLS = 55058,

    GFX_TAG_STATUS_SUMMARY_BALLS = 55060,

    PAL_TAG_HEALTHBAR = GFX_TAG_HEALTHBAR_PLAYER1,
    PAL_TAG_HEALTHBOX = GFX_TAG_HEALTHBOX_PLAYER1,

    // party_menu.c
    TAG_PARTY_MENU_HELD_ITEM = 55120,

    // battle_anim_smokescreen.c
    PAL_TAG_ENEMY_SHADOW = PAL_TAG_HEALTHBOX,
    GFX_TAG_ENEMY_SHADOW = 55129,

    // battle_script_commands.c
    TAG_LVLUP_BANNER_MON_ICON,

    // pokemon_icon.c
    // pokemon_storage_system.c
    POKE_ICON_BASE_PAL_TAG = 56000,
    PAL_TAG_MON_ICON_0 = POKE_ICON_BASE_PAL_TAG,
    PAL_TAG_MON_ICON_1,
    PAL_TAG_MON_ICON_2,
    PAL_TAG_MON_ICON_3, // Unused
    PAL_TAG_MON_ICON_4, // Unused
    PAL_TAG_MON_ICON_5, // Unused

    // pokemon_storage_system.c
    PAL_TAG_MON_STORAGE_SYSTEM_DISPLAY_MON,
    PAL_TAG_MON_STORAGE_SYSTEM_MISC_1,
    PAL_TAG_MON_STORAGE_SYSTEM_MARKING_COMBO,
    PAL_TAG_MON_STORAGE_SYSTEM_BOX_TITLE,
    PAL_TAG_MON_STORAGE_SYSTEM_MISC_2,
    PAL_TAG_MON_STORAGE_SYSTEM_ITEM_ICON_0,
    PAL_TAG_MON_STORAGE_SYSTEM_ITEM_ICON_1, // Used implicitly in CreateItemIconSprites
    PAL_TAG_MON_STORAGE_SYSTEM_ITEM_ICON_2, // Used implicitly in CreateItemIconSprites
    PAL_TAG_MON_STORAGE_SYSTEM_MARKING_MENU,

    TAG_NONE = 65535,
};

// Battle anim sprite tags start at 10000 thus must be subtracted of 10000 to account for the true index.
#define GET_TRUE_SPRITE_INDEX(i) ((i - ANIM_SPRITES_START))

#endif //GUARD_CONSTANTS_SPRITE_TAGS_H
