#ifndef GUARD_CONSTANTS_TRAINER_SLIDE_H
#define GUARD_CONSTANTS_TRAINER_SLIDE_H

enum TrainerSlideType
{
    TRAINER_SLIDE_NONE,
    TRAINER_SLIDE_BEFORE_FIRST_TURN,
    TRAINER_SLIDE_DEFENDER_TAKES_FIRST_CRITICAL_HIT,
    TRAINER_SLIDE_ATTACKER_LANDS_FIRST_CRITICAL_HIT,
    TRAINER_SLIDE_DEFENDER_TAKES_FIRST_SUPER_EFFECTIVE_HIT,
    TRAINER_SLIDE_DEFENDER_TAKES_FIRST_STAB_MOVE,
    TRAINER_SLIDE_DEFENDER_TAKES_FIRST_DOWN,
    TRAINER_SLIDE_SELF_MON_UNAFFECTED,
    TRAINER_SLIDE_SELF_LAST_SWITCHIN,
    TRAINER_SLIDE_SELF_LAST_HALF_HP,
    TRAINER_SLIDE_SELF_LAST_LOW_HP,
    TRAINER_SLIDE_ATTACKER_MEGA_EVOLUTION,
    TRAINER_SLIDE_ATTACKER_Z_MOVE,
    TRAINER_SLIDE_ATTACKER_DYNAMAX,
    TRAINER_SLIDE_ATTACKER_TERA,
    TRAINER_SLIDE_ATTACKER_LANDS_FIRST_SUPER_EFFECTIVE_HIT,
    TRAINER_SLIDE_ATTACKER_LANDS_FIRST_STAB_MOVE,
    TRAINER_SLIDE_ATTACKER_LANDS_FIRST_DOWN,
    TRAINER_SLIDE_OPPONENT_MON_UNAFFECTED,
    TRAINER_SLIDE_OPPONENT_LAST_SWITCHIN,
    TRAINER_SLIDE_OPPONENT_LAST_HALF_HP,
    TRAINER_SLIDE_OPPONENT_LAST_LOW_HP,
    TRAINER_SLIDE_OPPONENT_MEGA_EVOLUTION,
    TRAINER_SLIDE_OPPONENT_Z_MOVE,
    TRAINER_SLIDE_OPPONENT_DYNAMAX,
    TRAINER_SLIDE_OPPONENT_TERA,
    TRAINER_SLIDE_COUNT,
};

#define TRAINER_SLIDES_PER_ARRAY 8
#define TRAINER_SLIDE_ARRAY_SIZE ((TRAINER_SLIDE_COUNT + TRAINER_SLIDES_PER_ARRAY - 1) / TRAINER_SLIDES_PER_ARRAY)

enum TrainerSlideTargets
{
    TRAINER_SLIDE_TARGET_NONE,
    TRAINER_SLIDE_TARGET_TRAINER_A,
    TRAINER_SLIDE_TARGET_TRAINER_B,
    TRAINER_SLIDE_TARGET_TRAINER_PARTNER,
};

#endif // GUARD_CONSTANTS_TRAINER_SLIDE_H
