#ifndef GUARD_VAR_STATES_H
#define GUARD_VAR_STATES_H

#define LITTLEROOT_INTRO_STATE_NONE 0
#define LITTLEROOT_INTRO_STATE_MALE 1
#define LITTLEROOT_INTRO_STATE_FEMALE 2
#define LITTLEROOT_INTRO_STATE_ENTERED_HOUSE 3
#define LITTLEROOT_INTRO_STATE_GO_SEE_ROOM 4
#define LITTLEROOT_INTRO_STATE_5 5
#define LITTLEROOT_INTRO_STATE_6 6
#define LITTLEROOT_INTRO_STATE_7 7

// Shared by both VAR_LITTLEROOT_HOUSES_STATE and VAR_LITTLEROOT_HOUSES_STATE_2.
#define HOUSES_STATE_1 1
#define HOUSES_STATE_2 2
#define HOUSES_STATE_3 3
#define HOUSES_STATE_4 4
#define HOUSES_STATE_5 5

#define PROF_BIRCH_STATE_CANT_LEAVE 0
#define PROF_BIRCH_STATE_FIND_BIRCH 1
#define PROF_BIRCH_STATE_SAVE_BIRCH 2
#define PROF_BIRCH_STATE_BIRCH_SAVED 3
#define PROF_BIRCH_STATE_HAS_SHOES 4

#define NATIONAL_DEX_STATE_0 0
#define NATIONAL_DEX_STATE_1 1
#define NATIONAL_DEX_STATE_2 2
#define NATIONAL_DEX_STATE_3 3
#define NATIONAL_DEX_STATE_4 4
#define NATIONAL_DEX_STATE_5 5
#define NATIONAL_DEX_STATE_6 6

#endif // GUARD_VAR_STATES_H