
Route115_Text_NeverKnowWhenCavePokemonWillAppear:
	.string "Explorer une caverne, c’est pas comme\n"
	.string "marcher dans la rue.\p"
	.string "On ne sait jamais quand les POKéMON\n"
	.string "sauvages apparaissent. Ça fait peur!$"

Route115_Text_RouteSignRustboro:
	.string "ROUTE 115\n"
	.string "{DOWN_ARROW} MEROUVILLE$"

Route115_Text_MeteorFallsSign:
	.string "SITE METEORE\n"
	.string "VERS AUTEQUIA$"
