LilycoveCity_ContestHall: @ 84836C4
	.4byte LilycoveCity_ContestHall_Layout
	.4byte LilycoveCity_ContestHall_MapEvents
	.4byte LilycoveCity_ContestHall_MapScripts
	.4byte 0x0
	.2byte MUS_CONLOBBY
	.2byte 106
	.byte MAPSEC_LILYCOVE_CITY
	.byte 0
	.byte WEATHER_NONE
	.byte MAP_TYPE_INDOOR
	.2byte 0
	map_header_flags allow_bike=0, allow_escape_rope=0, allow_run=0, show_map_name=0
	.byte MAP_BATTLE_SCENE_NORMAL

