BattlePyramidSquare08_EventObjects: @ 853A984
	object_event 1, EVENT_OBJ_GFX_LITTLE_GIRL_2, 0, 0, 1, 2, 4, 18, 17, 0, 1, 5, BattleFrontier_BattlePyramidEmptySquare_EventScript_252C4F, 0, 0, 0
	object_event 2, EVENT_OBJ_GFX_LITTLE_GIRL_2, 0, 0, 6, 5, 4, 15, 17, 0, 1, 5, BattleFrontier_BattlePyramidEmptySquare_EventScript_252C4F, 0, 0, 0
	object_event 3, EVENT_OBJ_GFX_LITTLE_GIRL_2, 0, 0, 1, 5, 4, 16, 17, 0, 1, 5, BattleFrontier_BattlePyramidEmptySquare_EventScript_252C4F, 0, 0, 0
	object_event 4, EVENT_OBJ_GFX_LITTLE_GIRL_2, 0, 0, 6, 2, 4, 15, 17, 0, 1, 5, BattleFrontier_BattlePyramidEmptySquare_EventScript_252C4F, 0, 0, 0
	object_event 5, EVENT_OBJ_GFX_ITEM_BALL, 0, 0, 4, 3, 4, 1, 17, 0, 0, 0, BattleFrontier_BattlePyramidEmptySquare_EventScript_252C6A, 0, 0, 0
	object_event 6, EVENT_OBJ_GFX_ITEM_BALL, 0, 0, 3, 6, 4, 1, 17, 0, 0, 0, BattleFrontier_BattlePyramidEmptySquare_EventScript_252C6A, 0, 0, 0
	object_event 7, EVENT_OBJ_GFX_ITEM_BALL, 0, 0, 1, 0, 4, 1, 17, 0, 0, 0, BattleFrontier_BattlePyramidEmptySquare_EventScript_252C6A, 0, 0, 0

BattlePyramidSquare08_MapEvents:: @ 853AA2C
	map_events BattlePyramidSquare08_EventObjects, 0x0, 0x0, 0x0

