BattlePyramidSquare13_MapObjects: @ 853AD30
	object_event 1, MAP_OBJ_GFX_FAT_MAN, 0, 0, 5, 1, 4, 8, 17, 0, 1, 6, gUnknown_08252C4F, 0, 0, 0
	object_event 2, MAP_OBJ_GFX_FAT_MAN, 0, 0, 5, 6, 4, 7, 17, 0, 1, 6, gUnknown_08252C4F, 0, 0, 0
	object_event 3, MAP_OBJ_GFX_FAT_MAN, 0, 0, 1, 1, 4, 8, 17, 0, 1, 6, gUnknown_08252C4F, 0, 0, 0
	object_event 4, MAP_OBJ_GFX_FAT_MAN, 0, 0, 1, 6, 4, 7, 17, 0, 1, 6, gUnknown_08252C4F, 0, 0, 0
	object_event 5, MAP_OBJ_GFX_ITEM_BALL, 0, 0, 3, 1, 4, 1, 17, 0, 0, 0, gUnknown_08252C6A, 0, 0, 0
	object_event 6, MAP_OBJ_GFX_ITEM_BALL, 0, 0, 7, 0, 4, 1, 17, 0, 0, 0, gUnknown_08252C6A, 0, 0, 0
	object_event 7, MAP_OBJ_GFX_ITEM_BALL, 0, 0, 0, 3, 4, 1, 17, 0, 0, 0, gUnknown_08252C6A, 0, 0, 0

BattlePyramidSquare13_MapEvents:: @ 853ADD8
	map_events BattlePyramidSquare13_MapObjects, 0x0, 0x0, 0x0

