BattlePyramidSquare14_MapObjects: @ 853ADEC
	object_event 1, MAP_OBJ_GFX_WOMAN_2, 0, 0, 7, 1, 4, 17, 17, 0, 1, 7, gUnknown_08252C4F, 0, 0, 0
	object_event 2, MAP_OBJ_GFX_WOMAN_2, 0, 0, 1, 1, 4, 18, 17, 0, 1, 6, gUnknown_08252C4F, 0, 0, 0
	object_event 3, MAP_OBJ_GFX_WOMAN_2, 0, 0, 6, 5, 4, 15, 17, 0, 1, 6, gUnknown_08252C4F, 0, 0, 0
	object_event 4, MAP_OBJ_GFX_WOMAN_2, 0, 0, 0, 5, 4, 16, 17, 0, 1, 7, gUnknown_08252C4F, 0, 0, 0
	object_event 5, MAP_OBJ_GFX_ITEM_BALL, 0, 0, 5, 3, 4, 1, 17, 0, 0, 0, gUnknown_08252C6A, 0, 0, 0
	object_event 6, MAP_OBJ_GFX_ITEM_BALL, 0, 0, 0, 7, 4, 1, 17, 0, 0, 0, gUnknown_08252C6A, 0, 0, 0
	object_event 7, MAP_OBJ_GFX_ITEM_BALL, 0, 0, 7, 5, 4, 1, 17, 0, 0, 0, gUnknown_08252C6A, 0, 0, 0

BattlePyramidSquare14_MapEvents:: @ 853AE94
	map_events BattlePyramidSquare14_MapObjects, 0x0, 0x0, 0x0

