BattleFrontier_BattleTowerCorridor2_MapObjects: @ 853BF50
	object_event 1, 255, 0, 0, 1, 1, 0, 8, 17, 0, 0, 0, 0x0, 0, 0, 0
	object_event 2, MAP_OBJ_GFX_TEALA, 0, 0, 14, 3, 3, 7, 17, 0, 0, 0, 0x0, 0, 0, 0
	object_event 3, MAP_OBJ_GFX_TEALA, 0, 0, 1, 3, 3, 7, 17, 0, 0, 0, 0x0, 0, 0, 0
	object_event 4, 254, 0, 0, 14, 1, 0, 8, 17, 0, 0, 0, 0x0, 0, 0, 0

BattleFrontier_BattleTowerCorridor2_MapEvents:: @ 853BFB0
	map_events BattleFrontier_BattleTowerCorridor2_MapObjects, 0x0, 0x0, 0x0

