BattlePyramidSquare01_EventObjects: @ 853A460
	object_event 1, EVENT_OBJ_GFX_LITTLE_BOY_1, 0, 2, 3, 4, 18, 1, 1, 1, 3, BattleFrontier_BattlePyramidEmptySquare_EventScript_252C4F, 0
	object_event 2, EVENT_OBJ_GFX_GIRL_3, 0, 5, 3, 4, 17, 1, 1, 1, 3, BattleFrontier_BattlePyramidEmptySquare_EventScript_252C4F, 0
	object_event 3, EVENT_OBJ_GFX_BOY_4, 0, 2, 6, 4, 16, 1, 1, 1, 5, BattleFrontier_BattlePyramidEmptySquare_EventScript_252C4F, 0
	object_event 4, EVENT_OBJ_GFX_BOY_2, 0, 6, 6, 4, 9, 1, 1, 1, 4, BattleFrontier_BattlePyramidEmptySquare_EventScript_252C4F, 0
	object_event 5, EVENT_OBJ_GFX_ITEM_BALL, 0, 4, 1, 4, 1, 1, 1, 0, 0, BattleFrontier_BattlePyramidEmptySquare_EventScript_252C6A, 0
	object_event 6, EVENT_OBJ_GFX_ITEM_BALL, 0, 7, 4, 4, 1, 1, 1, 0, 0, BattleFrontier_BattlePyramidEmptySquare_EventScript_252C6A, 0
	object_event 7, EVENT_OBJ_GFX_ITEM_BALL, 0, 0, 4, 4, 1, 1, 1, 0, 0, BattleFrontier_BattlePyramidEmptySquare_EventScript_252C6A, 0

BattlePyramidSquare01_MapEvents:: @ 853A508
	map_events BattlePyramidSquare01_EventObjects, 0x0, 0x0, 0x0

