LilycoveCity_CoveLilyMotel_2F_EventObjects: @ 8531188
	object_event 1, EVENT_OBJ_GFX_MAN_4, 0, 4, 6, 3, 9, 0, 0, 0, LilycoveCity_CoveLilyMotel_2F_EventScript_2186D3, 925
	object_event 2, EVENT_OBJ_GFX_SCIENTIST_1, 0, 1, 4, 3, 10, 0, 0, 0, LilycoveCity_CoveLilyMotel_2F_EventScript_218729, 925
	object_event 3, EVENT_OBJ_GFX_FAT_MAN, 0, 7, 7, 3, 10, 0, 0, 0, LilycoveCity_CoveLilyMotel_2F_EventScript_218732, 925
	object_event 4, EVENT_OBJ_GFX_MAN_5, 0, 10, 3, 3, 9, 0, 0, 0, LilycoveCity_CoveLilyMotel_2F_EventScript_218720, 925
	object_event 5, EVENT_OBJ_GFX_BOY_5, 0, 7, 3, 3, 8, 17, 0, 0, LilycoveCity_CoveLilyMotel_2F_EventScript_218744, 925
	object_event 6, EVENT_OBJ_GFX_WOMAN_3, 0, 4, 4, 3, 9, 17, 0, 0, LilycoveCity_CoveLilyMotel_2F_EventScript_21873B, 925
	object_event 7, EVENT_OBJ_GFX_SCOTT, 0, 1, 7, 3, 10, 0, 0, 0, LilycoveCity_CoveLilyMotel_2F_EventScript_21874D, 787

LilycoveCity_CoveLilyMotel_2F_MapWarps: @ 8531230
	warp_def 2, 1, 0, 2, MAP_LILYCOVE_CITY_COVE_LILY_MOTEL_1F

LilycoveCity_CoveLilyMotel_2F_MapEvents:: @ 8531238
	map_events LilycoveCity_CoveLilyMotel_2F_EventObjects, LilycoveCity_CoveLilyMotel_2F_MapWarps, 0x0, 0x0

