PacifidlogTown_House1_EventObjects: @ 852EBA0
	object_event 1, EVENT_OBJ_GFX_MAN_6, 0, 0, 3, 5, 3, 8, 0, 0, 0, 0, PacifidlogTown_House1_EventScript_20365D, 0, 0, 0
	object_event 2, EVENT_OBJ_GFX_WOMAN_5, 0, 0, 6, 4, 3, 9, 0, 0, 0, 0, PacifidlogTown_House1_EventScript_203666, 0, 0, 0

PacifidlogTown_House1_MapWarps: @ 852EBD0
	warp_def 4, 8, 0, 1, PACIFIDLOG_TOWN
	warp_def 5, 8, 0, 1, PACIFIDLOG_TOWN

PacifidlogTown_House1_MapEvents:: @ 852EBE0
	map_events PacifidlogTown_House1_EventObjects, PacifidlogTown_House1_MapWarps, 0x0, 0x0

