Route133_EventObjects: @ 852CC94
	object_event 1, EVENT_OBJ_GFX_SWIMMER_M, 0, 0, 68, 27, 1, 25, 32, 0, 1, 3, Route133_EventScript_1F75A3, 0, 0, 0
	object_event 2, EVENT_OBJ_GFX_SWIMMER_F, 0, 0, 13, 3, 1, 8, 0, 0, 1, 3, Route133_EventScript_1F75D1, 0, 0, 0
	object_event 3, EVENT_OBJ_GFX_SWIMMER_F, 0, 0, 68, 28, 1, 26, 32, 0, 1, 3, Route133_EventScript_1F75BA, 0, 0, 0
	object_event 4, EVENT_OBJ_GFX_ITEM_BALL, 0, 0, 53, 12, 3, 1, 0, 0, 0, 0, Route133_EventScript_291073, 1037, 0, 0
	object_event 5, EVENT_OBJ_GFX_ITEM_BALL, 0, 0, 8, 10, 3, 1, 0, 0, 0, 0, Route133_EventScript_291080, 1038, 0, 0
	object_event 6, EVENT_OBJ_GFX_MAN_6, 0, 0, 7, 14, 3, 18, 17, 0, 1, 2, Route133_EventScript_1F75FF, 0, 0, 0
	object_event 7, EVENT_OBJ_GFX_MAN_4, 0, 0, 37, 15, 3, 18, 0, 0, 1, 4, Route133_EventScript_1F75E8, 0, 0, 0
	object_event 8, EVENT_OBJ_GFX_OLD_WOMAN_1, 0, 0, 56, 11, 3, 8, 17, 0, 1, 3, Route133_EventScript_1F7616, 0, 0, 0
	object_event 9, EVENT_OBJ_GFX_OLD_MAN_1, 0, 0, 56, 15, 3, 16, 17, 0, 1, 3, Route133_EventScript_1F762D, 0, 0, 0
	object_event 10, EVENT_OBJ_GFX_ITEM_BALL, 0, 0, 48, 28, 3, 1, 17, 0, 0, 0, Route133_EventScript_29108D, 1157, 0, 0

Route133_MapEvents:: @ 852CD84
	map_events Route133_EventObjects, 0x0, 0x0, 0x0

