RustboroCity_Flat2_3F_EventObjects: @ 8530B74
	object_event 1, EVENT_OBJ_GFX_MAN_7, 0, 0, 7, 3, 3, 5, 2, 0, 0, 0, RustboroCity_Flat2_3F_EventScript_216117, 0, 0, 0
	object_event 2, EVENT_OBJ_GFX_WOMAN_1, 0, 0, 12, 2, 3, 8, 0, 0, 0, 0, RustboroCity_Flat2_3F_EventScript_216120, 0, 0, 0

RustboroCity_Flat2_3F_MapWarps: @ 8530BA4
	warp_def 1, 1, 0, 1, RUSTBORO_CITY_FLAT_2_2F

RustboroCity_Flat2_3F_MapEvents:: @ 8530BAC
	map_events RustboroCity_Flat2_3F_EventObjects, RustboroCity_Flat2_3F_MapWarps, 0x0, 0x0

