SecretBase_YellowCave1_MapObjects: @ 8537D70
	object_event 1, 255, 0, 0, 3, 1, 3, 8, 0, 0, 0, 0, SecretBase_YellowCave1_EventScript_275D64, 173, 0, 0
	object_event 2, MAP_OBJ_GFX_HIPSTER, 0, 0, 0, 0, 3, 8, 0, 0, 0, 0, 0x0, 174, 0, 0
	object_event 3, MAP_OBJ_GFX_TRADER, 0, 0, 0, 1, 3, 8, 0, 0, 0, 0, 0x0, 175, 0, 0
	object_event 4, MAP_OBJ_GFX_STORYTELLER, 0, 0, 0, 2, 3, 8, 0, 0, 0, 0, 0x0, 176, 0, 0
	object_event 5, MAP_OBJ_GFX_GIDDY, 0, 0, 0, 3, 3, 8, 0, 0, 0, 0, 0x0, 177, 0, 0
	object_event 6, MAP_OBJ_GFX_PLACEHOLDER_1, 0, 0, 0, 4, 3, 8, 0, 0, 0, 0, 0x0, 178, 0, 0
	object_event 7, MAP_OBJ_GFX_PLACEHOLDER_2, 0, 0, 0, 5, 3, 8, 0, 0, 0, 0, 0x0, 179, 0, 0
	object_event 8, 246, 0, 0, 0, 6, 3, 8, 0, 0, 0, 0, 0x0, 180, 0, 0
	object_event 9, 247, 0, 0, 1, 0, 3, 8, 0, 0, 0, 0, 0x0, 181, 0, 0
	object_event 10, 248, 0, 0, 1, 1, 3, 8, 0, 0, 0, 0, 0x0, 182, 0, 0
	object_event 11, 249, 0, 0, 1, 2, 3, 8, 0, 0, 0, 0, 0x0, 183, 0, 0
	object_event 12, 250, 0, 0, 1, 3, 3, 8, 0, 0, 0, 0, 0x0, 184, 0, 0
	object_event 13, 251, 0, 0, 1, 4, 3, 8, 0, 0, 0, 0, 0x0, 185, 0, 0
	object_event 14, 252, 0, 0, 1, 5, 3, 8, 0, 0, 0, 0, 0x0, 186, 0, 0
	object_event 15, 253, 0, 0, 1, 6, 3, 8, 0, 0, 0, 0, 0x0, 187, 0, 0

SecretBase_YellowCave1_MapWarps: @ 8537ED8
	warp_def 5, 7, 0, 126, NONE

SecretBase_YellowCave1_MapEvents:: @ 8537EE0
	map_events SecretBase_YellowCave1_MapObjects, SecretBase_YellowCave1_MapWarps, 0x0, 0x0

