SlateportCity_House1_MapObjects: @ 852F538
	object_event 1, MAP_OBJ_GFX_OLD_MAN_1, 0, 0, 7, 5, 3, 8, 0, 0, 0, 0, SlateportCity_House1_EventScript_209AA5, 0, 0, 0

SlateportCity_House1_MapWarps: @ 852F550
	warp_def 3, 7, 0, 6, SLATEPORT_CITY
	warp_def 4, 7, 0, 6, SLATEPORT_CITY

SlateportCity_House1_MapEvents:: @ 852F560
	map_events SlateportCity_House1_MapObjects, SlateportCity_House1_MapWarps, 0x0, 0x0

