Underwater1_MapBGEvents: @ 852CEB4
	bg_event 42, 51, 0, 7, 0, ITEM_CARBOS, 8, 0
	bg_event 14, 40, 0, 7, 0, ITEM_GREEN_SHARD, 9, 0
	bg_event 66, 34, 3, 7, 0, ITEM_PEARL, 10, 0
	bg_event 64, 54, 3, 7, 0, ITEM_BIG_PEARL, 11, 0
	bg_event 70, 64, 3, 7, 0, ITEM_HEART_SCALE, 13, 0
	bg_event 42, 5, 3, 7, 0, ITEM_CALCIUM, 36, 0
	bg_event 45, 36, 3, 7, 0, ITEM_HEART_SCALE, 38, 0

Underwater1_MapEvents:: @ 852CF08
	map_events 0x0, 0x0, 0x0, Underwater1_MapBGEvents

