VerdanturfTown_BattleTentBattleRoom_EventObjects: @ 852E734
	object_event 1, EVENT_OBJ_GFX_TRADER, 0, 2, 8, 3, 7, 1, 1, 0, 0, 0x0, 0
	object_event 2, EVENT_OBJ_GFX_HIPSTER, 0, 11, 1, 3, 8, 1, 1, 0, 0, 0x0, 0
	object_event 3, EVENT_OBJ_GFX_OLD_MAN_1, 0, 2, 4, 0, 10, 1, 1, 0, 0, 0x0, 0

VerdanturfTown_BattleTentBattleRoom_MapEvents:: @ 852E77C
	map_events VerdanturfTown_BattleTentBattleRoom_EventObjects, 0x0, 0x0, 0x0

