BattleDome_Text_Potential1::
	.string "The best candidate to be a champ!$"

BattleDome_Text_Potential2::
	.string "A sure-finalist team.$"

BattleDome_Text_Potential3::
	.string "A likely top-three finisher.$"

BattleDome_Text_Potential4::
	.string "A candidate to finish first.$"

BattleDome_Text_Potential5::
	.string "A team with top-class potential.$"

BattleDome_Text_Potential6::
	.string "The dark horse team this tournament.$"

BattleDome_Text_Potential7::
	.string "A better-than-average team.$"

BattleDome_Text_Potential8::
	.string "This tournament's average team.$"

BattleDome_Text_Potential9::
	.string "A team with average potential.$"

BattleDome_Text_Potential10::
	.string "A weaker-than-average team.$"

BattleDome_Text_Potential11::
	.string "A team looking for its first win.$"

BattleDome_Text_Potential12::
	.string "One win will make this team proud.$"

BattleDome_Text_Potential13::
	.string "Overall, a weak team.$"

BattleDome_Text_Potential14::
	.string "A team with very low potential.$"

BattleDome_Text_Potential15::
	.string "A team unlikely to win the tournament.$"

BattleDome_Text_Potential16::
	.string "The team most unlikely to win.$"

BattleDome_Text_PotentialDomeAceTucker::
	.string "The perfect, invincible superstar!$"

BattleDome_Text_StyleRiskDisaster::
	.string "Willing to risk total disaster at times.$"

BattleDome_Text_StyleEndureLongBattles::
	.string "Skilled at enduring long battles.$"

BattleDome_Text_StyleVariesTactics::
	.string "Varies tactics to suit the opponent.$"

BattleDome_Text_StyleToughWinningPattern::
	.string "Has a tough winning pattern.$"

BattleDome_Text_StyleUsesVeryRareMove::
	.string "Occasionally uses a very rare move.$"

BattleDome_Text_StyleUsesStartlingMoves::
	.string "Uses startling and disruptive moves.$"

BattleDome_Text_StyleConstantlyWatchesHP::
	.string "Constantly watches HP in battle.$"

BattleDome_Text_StyleStoresAndLoosesPower::
	.string "Good at storing then loosing power.$"

BattleDome_Text_StyleEnfeeblesFoes::
	.string "Skilled at enfeebling foes.$"

BattleDome_Text_StylePrefersLuckTactics::
	.string "Prefers tactics that rely on luck.$"

BattleDome_Text_StyleRegalAtmosphere::
	.string "Attacks with a regal atmosphere.$"

BattleDome_Text_StylePowerfulLowPPMoves::
	.string "Attacks with powerful, low-PP moves.$"

BattleDome_Text_StyleEnfeebleThenAttack::
	.string "Skilled at enfeebling, then attacking.$"

BattleDome_Text_StyleBattlesWhileEnduring::
	.string "Battles while enduring all attacks.$"

BattleDome_Text_StyleUpsetsFoesEmotionally::
	.string "Skilled at upsetting foes emotionally.$"

BattleDome_Text_StyleStrongAndStraightforward::
	.string "Uses strong and straightforward moves.$"

BattleDome_Text_StyleAggressivelyStrongMoves::
	.string "Aggressively uses strong moves.$"

BattleDome_Text_StyleCleverlyDodgesAttacks::
	.string "Battles while cleverly dodging attacks.$"

BattleDome_Text_StyleUsesUpsettingMoves::
	.string "Skilled at using upsetting attacks.$"

BattleDome_Text_StyleUsesPopularMoves::
	.string "Uses many popular moves.$"

BattleDome_Text_StyleHasPowerfulComboMoves::
	.string "Has moves for powerful combinations.$"

BattleDome_Text_StyleUsesHighProbabilityMoves::
	.string "Uses high-probability attacks.$"

BattleDome_Text_StyleAggressivelySpectacularMoves::
	.string "Aggressively uses spectacular moves.$"

BattleDome_Text_StyleEmphasizesOffenseOverDefense::
	.string "Emphasizes offense over defense.$"

BattleDome_Text_StyleEmphasizesDefenseOverOffense::
	.string "Emphasizes defense over offense.$"

BattleDome_Text_StyleAttacksQuicklyStrongMoves::
	.string "Attacks quickly with strong moves.$"

BattleDome_Text_StyleUsesAddedEffectMoves::
	.string "Often uses moves with added effects.$"

BattleDome_Text_StyleUsesBalancedMixOfMoves::
	.string "Uses a well-balanced mix of moves.$"

BattleDome_Text_StyleSampleMessage1::
	.string "This is sample message 1.$"

BattleDome_Text_StyleSampleMessage2::
	.string "This is sample message 2.$"

BattleDome_Text_StyleSampleMessage3::
	.string "This is sample message 3.$"

BattleDome_Text_StyleSampleMessage4::
	.string "This is sample message 4.$"

BattleDome_Text_EmphasizesHPAndAtk::
	.string "Emphasizes HP and ATTACK.$"

BattleDome_Text_EmphasizesHPAndDef::
	.string "Emphasizes HP and DEFENSE.$"

BattleDome_Text_EmphasizesHPAndSpeed::
	.string "Emphasizes HP and SPEED.$"

BattleDome_Text_EmphasizesHPAndSpAtk::
	.string "Emphasizes HP and SP. ATTACK.$"

BattleDome_Text_EmphasizesHPAndSpDef::
	.string "Emphasizes HP and SP. DEFENSE.$"

gBattleDomeOpponentStatsText6::
	.string "Emphasizes ATTACK and DEFENSE.$"

gBattleDomeOpponentStatsText7::
	.string "Emphasizes ATTACK and SPEED.$"

gBattleDomeOpponentStatsText8::
	.string "Emphasizes ATTACK and SP. ATTACK.$"

gBattleDomeOpponentStatsText9::
	.string "Emphasizes ATTACK and SP. DEFENSE.$"

gBattleDomeOpponentStatsText10::
	.string "Emphasizes DEFENSE and SPEED.$"

gBattleDomeOpponentStatsText11::
	.string "Emphasizes DEFENSE and SP. ATTACK.$"

gBattleDomeOpponentStatsText12::
	.string "Emphasizes DEFENSE and SP. DEFENSE.$"

gBattleDomeOpponentStatsText13::
	.string "Emphasizes SPEED and SP. ATTACK.$"

gBattleDomeOpponentStatsText14::
	.string "Emphasizes SPEED and SP. DEFENSE.$"

gBattleDomeOpponentStatsText15::
	.string "Emphasizes SP. ATTACK and SP. DEFENSE.$"

BattleDome_Text_EmphasizesHP::
	.string "Emphasizes HP.$"

gBattleDomeOpponentStatsText17::
	.string "Emphasizes ATTACK.$"

gBattleDomeOpponentStatsText18::
	.string "Emphasizes DEFENSE.$"

gBattleDomeOpponentStatsText19::
	.string "Emphasizes SPEED.$"

gBattleDomeOpponentStatsText20::
	.string "Emphasizes SP. ATTACK.$"

gBattleDomeOpponentStatsText21::
	.string "Emphasizes SP. DEFENSE.$"

BattleDome_Text_NeglectsHPAndAtk::
	.string "Neglects HP and ATTACK.$"

gBattleDomeOpponentStatsText23::
	.string "Neglects HP and DEFENSE.$"

gBattleDomeOpponentStatsText24::
	.string "Neglects HP and SPEED.$"

gBattleDomeOpponentStatsText25::
	.string "Neglects HP and SP. ATTACK.$"

gBattleDomeOpponentStatsText26::
	.string "Neglects HP and SP. DEFENSE.$"

gBattleDomeOpponentStatsText27::
	.string "Neglects ATTACK and DEFENSE.$"

gBattleDomeOpponentStatsText28::
	.string "Neglects ATTACK and SPEED.$"

gBattleDomeOpponentStatsText29::
	.string "Neglects ATTACK and SP. ATTACK.$"

gBattleDomeOpponentStatsText30::
	.string "Neglects ATTACK and SP. DEFENSE.$"

gBattleDomeOpponentStatsText31::
	.string "Neglects DEFENSE and SPEED.$"

gBattleDomeOpponentStatsText32::
	.string "Neglects DEFENSE and SP. ATTACK.$"

gBattleDomeOpponentStatsText33::
	.string "Neglects DEFENSE and SP. DEFENSE.$"

gBattleDomeOpponentStatsText34::
	.string "Neglects SPEED and SP. ATTACK.$"

gBattleDomeOpponentStatsText35::
	.string "Neglects SPEED and SP. DEFENSE.$"

gBattleDomeOpponentStatsText36::
	.string "Neglects SP. ATTACK and SP. DEFENSE.$"

BattleDome_Text_NeglectsHP::
	.string "Neglects HP.$"

gBattleDomeOpponentStatsText38::
	.string "Neglects ATTACK.$"

gBattleDomeOpponentStatsText39::
	.string "Neglects DEFENSE.$"

gBattleDomeOpponentStatsText40::
	.string "Neglects SPEED.$"

gBattleDomeOpponentStatsText41::
	.string "Neglects SP. ATTACK.$"

gBattleDomeOpponentStatsText42::
	.string "Neglects SP. DEFENSE.$"

BattleDome_Text_RaisesMonsWellBalanced::
	.string "Raises POKéMON in a well-balanced way.$"

gBattleDomeWinText1::
	.string "Let the battle begin!$"

gBattleDomeWinText2::
	.string "{STR_VAR_1} won using {STR_VAR_2}!$"

gBattleDomeWinText3::
	.string "{STR_VAR_1} became the champ!$"

gBattleDomeWinText4::
	.string "{STR_VAR_1} won by default!$"

gBattleDomeWinText5::
	.string "{STR_VAR_1} won outright by default!$"

gBattleDomeWinText6::
	.string "{STR_VAR_1} won without using a move!$"

gBattleDomeWinText7::
	.string "{STR_VAR_1} won outright with no moves!$"

gBattleDomeMatchNumberText1::
	.string "Round 1, Match 1$"

gBattleDomeMatchNumberText2::
	.string "Round 1, Match 2$"

gBattleDomeMatchNumberText3::
	.string "Round 1, Match 3$"

gBattleDomeMatchNumberText4::
	.string "Round 1, Match 4$"

gBattleDomeMatchNumberText5::
	.string "Round 1, Match 5$"

gBattleDomeMatchNumberText6::
	.string "Round 1, Match 6$"

gBattleDomeMatchNumberText7::
	.string "Round 1, Match 7$"

gBattleDomeMatchNumberText8::
	.string "Round 1, Match 8$"

gBattleDomeMatchNumberText9::
	.string "Round 2, Match 1$"

gBattleDomeMatchNumberText10::
	.string "Round 2, Match 2$"

gBattleDomeMatchNumberText11::
	.string "Round 2, Match 3$"

gBattleDomeMatchNumberText12::
	.string "Round 2, Match 4$"

gBattleDomeMatchNumberText13::
	.string "Semifinal Match 1$"

gBattleDomeMatchNumberText14::
	.string "Semifinal Match 2$"

gBattleDomeMatchNumberText15::
	.string "Final Match$"
