FallarborTown_BattleTentLobby_Text_WelcomeToBattleTent:
	.string "I welcome you to the Battle Tent\n"
	.string "Fallabor Site!\p"
	.string "I am your guide to the Set KO Tourney!$"

FallarborTown_BattleTentLobby_Text_TakeChallenge:
	.string "Now, do you wish to take the challenge\n"
	.string "of a Set KO Tourney?$"

FallarborTown_BattleTentLobby_Text_AwaitAnotherChallenge:
	.string "We await your challenge on\n"
	.string "another occasion!$"

FallarborTown_BattleTentLobby_Text_ExplainFallarborTent:
	.string "In the Fallabor Battle Tent,\n"
	.string "we undertake the Set KO Tourney.\p"
	.string "All participants enter with a team of\n"
	.string "three Pokémon.\p"
	.string "The three Pokémon must be lined up\n"
	.string "in the order that they are to appear in.\p"
	.string "During battle, the Pokémon will appear\n"
	.string "one at a time in the preset order.\p"
	.string "Once a Pokémon enters battle, it must\n"
	.string "remain out until the match is decided.\p"
	.string "If a match remains undecided in\n"
	.string "three turns, it goes to judging.\p"
	.string "If you wish to interrupt your challenge,\n"
	.string "please save the game.\p"
	.string "If you don't save, you will not be able\n"
	.string "to continue with your challenge.\p"
	.string "If you pull off the feat of beating\n"
	.string "three Trainers in succession,\l"
	.string "we will present you with a fine prize.$"

FallarborTown_BattleTentLobby_Text_SaveBeforeChallenge:
	.string "Before showing you to the Battle\n"
	.string "Tent, I must save. Is that okay?$"

@ Unused
FallarborTown_BattleTentLobby_Text_WhichLevelMode:
	.string "We offer two levels of challenge,\n"
	.string "Level 50 and Open Level.\l"
	.string "Which is your choice?$"

FallarborTown_BattleTentLobby_Text_SelectThreeMons:
	.string "Very well, now select your\n"
	.string "three Pokémon, please.$"

FallarborTown_BattleTentLobby_Text_NotEnoughValidMonsLv50:
	.string "My dear challenger!\p"
	.string "You do not have the three Pokémon\n"
	.string "required for entry.\p"
	.string "They also must not hold the same\n"
	.string "kinds of items.\p"
	.string "Eggs{STR_VAR_1} ineligible.\p"
	.string "When you have made your preparations,\n"
	.string "please do return.$"

FallarborTown_BattleTentLobby_Text_NotEnoughValidMonsLvOpen:
	.string "My dear challenger!\p"
	.string "You do not have the three Pokémon\n"
	.string "required for entry.\p"
	.string "To qualify, you must bring three\n"
	.string "different kinds of Pokémon.\p"
	.string "They also must not hold the same\n"
	.string "kinds of items.\p"
	.string "Eggs{STR_VAR_1} ineligible.\p"
	.string "When you have made your preparations,\n"
	.string "please do return.$"

FallarborTown_BattleTentLobby_Text_GuideYouToBattleTent:
	.string "I shall now guide you to\n"
	.string "the Battle Tent.$"

FallarborTown_BattleTentLobby_Text_DidntSaveBeforeQuitting:
	.string "My dear challenger!\p"
	.string "You did not save the game before\n"
	.string "shutting down, did you?\p"
	.string "It is unfortunate, but that has\n"
	.string "resulted in your disqualification\l"
	.string "from your challenge.\p"
	.string "You may, of course, start with a fresh\n"
	.string "challenge.$"

FallarborTown_BattleTentLobby_Text_BeatThreeTrainers:
	.string "How splendid! You have beaten\n"
	.string "three Trainers in succession!$"

FallarborTown_BattleTentLobby_Text_WaitWhileSaveGame:
	.string "Please wait while I save the game.$"

FallarborTown_BattleTentLobby_Text_PresentYouWithPrize:
	.string "In commemoration of your 3-win streak,\n"
	.string "we present you with this prize.$"

FallarborTown_BattleTentLobby_Text_ReceivedPrize:
	.string "{PLAYER} received the prize\n"
	.string "{STR_VAR_1}.$"

FallarborTown_BattleTentLobby_Text_BagFullReturnForPrize:
	.string "Oh?\n"
	.string "Your Bag seems to be full.\p"
	.string "I urge you to clear space and\n"
	.string "return for your prize.$"

FallarborTown_BattleTentLobby_Text_ThankYouWaitWhileSaving:
	.string "Thank you so much for participating!\p"
	.string "Please wait while I save the game.$"

FallarborTown_BattleTentLobby_Text_AwaitAnotherChallenge2:
	.string "We await your challenge on\n"
	.string "another occasion!$"

FallarborTown_BattleTentLobby_Text_LookingForwardToArrival:
	.string "We have been looking forward to\n"
	.string "your arrival.\p"
	.string "Before I show you to the Battle Tent,\n"
	.string "I must save the game. Please wait.$"

VerdanturfTown_BattleTentLobby_Text_WelcomeToBattleTent:
	.string "I welcome you to the Battle Tent\n"
	.string "Verdanturf Site!\p"
	.string "Here, the Trainer's trust toward\n"
	.string "Pokémon is tested.$"

VerdanturfTown_BattleTentLobby_Text_TakeChallenge:
	.string "Do you wish to take the Verdanturf\n"
	.string "Battle Tent challenge?$"

VerdanturfTown_BattleTentLobby_Text_ExplainVerdanturfTent:
	.string "In the Verdanturf Battle Tent,\n"
	.string "there is one crucial rule that must\l"
	.string "be obeyed.\p"
	.string "Trainers are permitted only to switch\n"
	.string "their Pokémon in and out.\p"
	.string "Trainers are otherwise forbidden to\n"
	.string "command their Pokémon.\p"
	.string "The Pokémon are to behave according\n"
	.string "to their nature and battle on their own.\p"
	.string "You must put your trust in your\n"
	.string "Pokémon and watch over them.\p"
	.string "If you achieve the honor of beating\n"
	.string "three Trainers in succession,\l"
	.string "we will present you with a prize.\p"
	.string "If you want to interrupt your\n"
	.string "challenge, please save the game.\p"
	.string "If you don't save before interrupting,\n"
	.string "you will be disqualified.$"

VerdanturfTown_BattleTentLobby_Text_ReturnFortified:
	.string "When you have fortified your heart\n"
	.string "and Pokémon, you must return.$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_WhichLevelMode:
	.string "There are two levels of difficulty,\n"
	.string "Level 50 and Open Level.\l"
	.string "Which is your choice of a challenge?$"

VerdanturfTown_BattleTentLobby_Text_NotEnoughValidMonsLv50:
	.string "Sigh…\p"
	.string "You do not have the three Pokémon\n"
	.string "required for the challenge.\p"
	.string "To enter, you must provide three\n"
	.string "different kinds of Pokémon.\p"
	.string "They also must not be holding\n"
	.string "the same kinds of items.\p"
	.string "Eggs{STR_VAR_1} ineligible.\p"
	.string "Come back when you have made\n"
	.string "your preparations.$"

VerdanturfTown_BattleTentLobby_Text_NotEnoughValidMonsLvOpen:
	.string "Sigh…\p"
	.string "You do not have the three Pokémon\n"
	.string "required for the challenge.\p"
	.string "To enter, you must provide three\n"
	.string "different kinds of Pokémon.\p"
	.string "They also must not be holding\n"
	.string "the same kinds of items.\p"
	.string "Eggs{STR_VAR_1} ineligible.\p"
	.string "Come back when you have made\n"
	.string "your preparations.$"

VerdanturfTown_BattleTentLobby_Text_SelectThreeMons:
	.string "Good. Now, you must select your\n"
	.string "three Pokémon.$"

VerdanturfTown_BattleTentLobby_Text_SaveBeforeChallenge:
	.string "I must save before I show you to\n"
	.string "the Battle Tent. Is that okay?$"

VerdanturfTown_BattleTentLobby_Text_NowFollowMe:
	.string "Good.\n"
	.string "Now, follow me.$"

VerdanturfTown_BattleTentLobby_Text_ResultsWillBeRecorded:
	.string "I feel privileged for having seen\n"
	.string "your Pokémon's exploits.\p"
	.string "The results will be recorded.\n"
	.string "I must ask you to briefly wait.$"

VerdanturfTown_BattleTentLobby_Text_AchievedThreeWinStreak:
	.string "To achieve a 3-win streak…\p"
	.string "The bonds that bind your heart with\n"
	.string "your Pokémon seem firm and true.$"

VerdanturfTown_BattleTentLobby_Text_FeatWillBeRecorded:
	.string "Your feat will be recorded.\n"
	.string "I must ask you to briefly wait.$"

VerdanturfTown_BattleTentLobby_Text_PresentYouWithPrize:
	.string "For the feat of your 3-win streak,\n"
	.string "we present you with this prize.$"

SlateportCity_BattleTentLobby_Text_WelcomeToBattleTent:
	.string "Welcome to the Battle Tent\n"
	.string "Slateport Site!\p"
	.string "I am your guide to the Battle Swap\n"
	.string "Tournament.$"

SlateportCity_BattleTentLobby_Text_TakeChallenge:
	.string "Would you like to take the Battle\n"
	.string "Swap challenge?$"

SlateportCity_BattleTentLobby_Text_ExplainSlateportTent:
	.string "Here at the Slateport Battle Tent,\n"
	.string "we hold Battle Swap events\l"
	.string "using rental Pokémon.\p"
	.string "First, you will be loaned three\n"
	.string "Pokémon specifically for this event.\p"
	.string "Using the supplied rental Pokémon,\n"
	.string "you must conduct a Single Battle.\p"
	.string "If you win, you are permitted to trade\n"
	.string "one of your rental Pokémon.\p"
	.string "Repeat this cycle of battling and\n"
	.string "trading--if you win three times in\l"
	.string "a row, you will earn a fine prize.\p"
	.string "If you want to interrupt your\n"
	.string "challenge, please save the game.\p"
	.string "If you don't save before interrupting,\n"
	.string "you will be disqualified.$"

SlateportCity_BattleTentLobby_Text_LookForwardToNextVisit:
	.string "We look forward to your next visit.$"

@ Unused
SlateportCity_BattleTentLobby_Text_WhichLevelMode:
	.string "Which level do you wish to challenge?\n"
	.string "Level 50 or Level 100?$"

SlateportCity_BattleTentLobby_Text_SaveBeforeChallenge:
	.string "Before you begin your challenge,\n"
	.string "I need to save data. Is that okay?$"

@ Unused
SlateportCity_BattleTentLobby_Text_HoldMonsForSafekeeping:
	.string "Okay, I will hold your Pokémon for\n"
	.string "safekeeping while you compete.$"

SlateportCity_BattleTentLobby_Text_StepThisWay:
	.string "Please step this way.$"

SlateportCity_BattleTentLobby_Text_ReturnRentalMonsSaveResults:
	.string "Thank you for participating!\p"
	.string "I will return your Pokémon in exchange\n"
	.string "for our rental Pokémon.\p"
	.string "I must also save your event results.\n"
	.string "Please wait.$"

@ Unused
SlateportCity_BattleTentLobby_Text_ReturnMonsExchangeRentals:
	.string "I will return your Pokémon in exchange\n"
	.string "for our rental Pokémon.$"

SlateportCity_BattleTentLobby_Text_WonThreeMatchesReturnMons:
	.string "Congratulations!\n"
	.string "You've won three straight matches!\p"
	.string "I will return your Pokémon in exchange\n"
	.string "for our rental Pokémon.\p"
	.string "I must also save your event results.\n"
	.string "Please wait.$"

SlateportCity_BattleTentLobby_Text_AwardYouThisPrize:
	.string "In recognition of your 3-win streak,\n"
	.string "we award you this prize.$"

SlateportCity_BattleTentLobby_Text_NoRoomInBagMakeRoom:
	.string "Oh?\n"
	.string "You seem to have no room for this.\p"
	.string "Please make room in your Bag and\n"
	.string "let me know.$"

SlateportCity_BattleTentLobby_Text_BeenWaitingForYou:
	.string "We've been waiting for you!\p"
	.string "Before we resume your challenge,\n"
	.string "I must save the game.$"

SlateportCity_BattleTentLobby_Text_DidntSaveBeforeQuitting:
	.string "I'm sorry to say this, but you didn't\n"
	.string "save before you quit playing last time.\p"
	.string "As a result, you have been disqualified\n"
	.string "from your challenge.$"

@ Unused
SlateportCity_BattleTentLobby_Text_ReturnPersonalMons:
	.string "We'll return your personal Pokémon.$"

@ Unused
SlateportCity_BattleTentLobby_Text_ReceivedPrize:
	.string "{PLAYER} received the prize\n"
	.string "{STR_VAR_1}.$"

@ Unused
SlateportCity_BattleTentLobby_Text_RulesAreListed:
	.string "The Battle Swap rules are listed.$"

@ Unused
SlateportCity_BattleTentLobby_Text_ReadWhichHeading:
	.string "Which heading do you want to read?$"

SlateportCity_BattleTentLobby_Text_ExplainBasicRules:
	.string "In a Battle Swap event, you may use\n"
	.string "only three Pokémon.\p"
	.string "Whether you are renting or swapping,\n"
	.string "your team may not have two or more\l"
	.string "of the same Pokémon.$"

SlateportCity_BattleTentLobby_Text_ExplainSwapPartnerRules:
	.string "You may swap Pokémon only with\n"
	.string "the Trainer you have just defeated.\p"
	.string "You may swap for only those Pokémon\n"
	.string "used by the beaten Trainer.$"

SlateportCity_BattleTentLobby_Text_ExplainSwapNumberRules:
	.string "After every battle you win, you may\n"
	.string "swap for one of your defeated\l"
	.string "opponent's Pokémon.\p"
	.string "You will not be able to swap Pokémon\n"
	.string "with the third Trainer in the event.$"

SlateportCity_BattleTentLobby_Text_ExplainSwapNotes:
	.string "There are two key points to be aware\n"
	.string "of when swapping Pokémon.\p"
	.string "First, when swapping, you can't check\n"
	.string "the stats of the Pokémon you are\l"
	.string "about to receive.\p"
	.string "Second, the Pokémon on your team\n"
	.string "are lined up in sequence, depending on\l"
	.string "the order in which you rented them.\p"
	.string "This sequence remains unchanged\n"
	.string "even when swaps are made.$"

SlateportCity_BattleTentLobby_Text_ExplainMonRules:
	.string "The Pokémon of the Slateport\n"
	.string "Battle Tent are all rentals.\p"
	.string "All rental Pokémon are kept at\n"
	.string "Level 30.$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_RulesAreListed2:
	.string "The Verdanturf Battle Tent\n"
	.string "rules are listed.$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_ReadWhichHeading:
	.string "Which heading do you want to read?$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_ExplainBasicRules:
	.string "Here at the Verdanturf Battle Tent,\n"
	.string "Pokémon are required to think and\l"
	.string "battle by themselves.\p"
	.string "Unlike in the wild, Pokémon that live\n"
	.string "with people behave differently\l"
	.string "depending on their nature.$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_ExplainNatureRules:
	.string "Depending on its nature, a Pokémon\n"
	.string "may prefer to attack no matter what.\p"
	.string "Another Pokémon may prefer to protect\n"
	.string "itself from any harm.\p"
	.string "Yet another may enjoy vexing or\n"
	.string "confounding its foes.\p"
	.string "Depending on its nature, a Pokémon\n"
	.string "will have favorite moves that it is good\l"
	.string "at using.\p"
	.string "It may also dislike certain moves that\n"
	.string "it has trouble using.$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_ExplainMoveRules:
	.string "There are offensive moves that inflict\n"
	.string "direct damage on the foe.\p"
	.string "There are defensive moves that are\n"
	.string "used to prepare for enemy attacks or\l"
	.string "used to heal HP and so on.\p"
	.string "There are also other somewhat-odd\n"
	.string "moves that may enfeeble the foes with\l"
	.string "stat problems including poison and \l"
	.string "paralysis.\p"
	.string "Pokémon will consider using moves in\n"
	.string "these three categories.$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_ExplainUnderpoweredRules:
	.string "When not under command by its Trainer,\n"
	.string "a Pokémon may be unable to effectively\l"
	.string "use certain moves.\p"
	.string "A Pokémon is not good at using any\n"
	.string "move that it dislikes.\p"
	.string "If a Pokémon only knows moves that\n"
	.string "do not match its nature, it will often\l"
	.string "be unable to live up to its potential.$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_ExplainWhenInDangerRules:
	.string "Depending on its nature, a Pokémon may\n"
	.string "start using moves that don't match its\l"
	.string "nature when it is in trouble.\p"
	.string "If a Pokémon begins behaving oddly\n"
	.string "in a pinch, watch it carefully.$"

BattleTentLobby_Text_ExplainLevelRules:
	.string "At this Battle Tent, the levels of\n"
	.string "your opponents will be adjusted to\l"
	.string "match the levels of your Pokémon.\p"
	.string "However, no Trainer you face will\n"
	.string "have any Pokémon below Level 30.$"

VerdanturfTown_BattleTentLobby_Text_RulesAreListed:
	.string "The Verdanturf Battle Tent\n"
	.string "rules are listed.$"
