gBerryDescriptionPart1_Cheri:: @ 8589AE4
	.string "Blooms with delicate pretty flowers.$"

gBerryDescriptionPart2_Cheri:: @ 8589B09
	.string "The bright red BERRY is very spicy.$"

gBerryDescriptionPart1_Chesto:: @ 8589B2D
	.string "The BERRY's thick skin and fruit are$"

gBerryDescriptionPart2_Chesto:: @ 8589B52
	.string "very tough. It is dry-tasting all over.$"

gBerryDescriptionPart1_Pecha:: @ 8589B7A
	.string "Very sweet and delicious.$"

gBerryDescriptionPart2_Pecha:: @ 8589B94
	.string "Also very tender - handle with care.$"

gBerryDescriptionPart1_Rawst:: @ 8589BB9
	.string "If the leaves grow long and curly,$"

gBerryDescriptionPart2_Rawst:: @ 8589BDC
	.string "the BERRY seems to grow very bitter.$"

gBerryDescriptionPart1_Aspear:: @ 8589C01
	.string "The hard BERRY is dense with a rich$"

gBerryDescriptionPart2_Aspear:: @ 8589C25
	.string "juice. It is quite sour.$"

gBerryDescriptionPart1_Leppa:: @ 8589C3E
	.string "Grows slower than CHERI and others.$"

gBerryDescriptionPart2_Leppa:: @ 8589C62
	.string "The smaller the BERRY, the tastier.$"

gBerryDescriptionPart1_Oran:: @ 8589C86
	.string "A peculiar BERRY with a mix of flavors.$"

gBerryDescriptionPart2_Oran:: @ 8589CAE
	.string "BERRIES grow in half a day.$"

gBerryDescriptionPart1_Persim:: @ 8589CCA
	.string "Loves sunlight. The BERRY's color$"

gBerryDescriptionPart2_Persim:: @ 8589CEC
	.string "grows vivid when exposed to the sun.$"

gBerryDescriptionPart1_Lum:: @ 8589D11
	.string "Slow to grow. If raised with loving$"

gBerryDescriptionPart2_Lum:: @ 8589D35
	.string "care, it may grow two BERRIES.$"

gBerryDescriptionPart1_Sitrus:: @ 8589D54
	.string "Closely related to ORAN. The large$"

gBerryDescriptionPart2_Sitrus:: @ 8589D77
	.string "BERRY has a well-rounded flavor.$"

gBerryDescriptionPart1_Figy:: @ 8589D98
	.string "The BERRY, which looks chewed up,$"

gBerryDescriptionPart2_Figy:: @ 8589DBA
	.string "brims with spicy substances.$"

gBerryDescriptionPart1_Wiki:: @ 8589DD7
	.string "The BERRY is said to have grown lumpy$"

gBerryDescriptionPart2_Wiki:: @ 8589DFD
	.string "to help POKéMON grip it.$"

gBerryDescriptionPart1_Mago:: @ 8589E16
	.string "The BERRY turns curvy as it grows.$"

gBerryDescriptionPart2_Mago:: @ 8589E39
	.string "The curvier, the sweeter and tastier.$"

gBerryDescriptionPart1_Aguav:: @ 8589E5F
	.string "The flower is dainty. It is rare in its$"

gBerryDescriptionPart2_Aguav:: @ 8589E87
	.string "ability to grow without light.$"

gBerryDescriptionPart1_Iapapa:: @ 8589EA6
	.string "The BERRY is very big and sour.$"

gBerryDescriptionPart2_Iapapa:: @ 8589EC6
	.string "It takes at least a day to grow.$"

gBerryDescriptionPart1_Razz:: @ 8589EE7
	.string "The red BERRY tastes slightly spicy.$"

gBerryDescriptionPart2_Razz:: @ 8589F0C
	.string "It grows quickly in just four hours.$"

gBerryDescriptionPart1_Bluk:: @ 8589F31
	.string "The BERRY is blue on the outside, but$"

gBerryDescriptionPart2_Bluk:: @ 8589F57
	.string "it blackens the mouth when eaten.$"

gBerryDescriptionPart1_Nanab:: @ 8589F79
	.string "This BERRY was the seventh$"

gBerryDescriptionPart2_Nanab:: @ 8589F94
	.string "discovered in the world. It is sweet.$"

gBerryDescriptionPart1_Wepear:: @ 8589FBA
	.string "The flower is small and white. It has a$"

gBerryDescriptionPart2_Wepear:: @ 8589FE2
	.string "delicate balance of bitter and sour.$"

gBerryDescriptionPart1_Pinap:: @ 858A007
	.string "Weak against wind and cold.$"

gBerryDescriptionPart2_Pinap:: @ 858A023
	.string "The fruit is spicy and the skin, sour.$"

gBerryDescriptionPart1_Pomeg:: @ 858A04A
	.string "However much it is watered,$"

gBerryDescriptionPart2_Pomeg:: @ 858A066
	.string "it only grows up to six BERRIES.$"

gBerryDescriptionPart1_Kelpsy:: @ 858A087
	.string "A rare variety shaped like a root.$"

gBerryDescriptionPart2_Kelpsy:: @ 858A0AA
	.string "Grows a very large flower.$"

gBerryDescriptionPart1_Qualot:: @ 858A0C5
	.string "Loves water. Grows strong even in$"

gBerryDescriptionPart2_Qualot:: @ 858A0E7
	.string "locations with constant rainfall.$"

gBerryDescriptionPart1_Hondew:: @ 858A109
	.string "A BERRY that is very valuable and$"

gBerryDescriptionPart2_Hondew:: @ 858A12B
	.string "rarely seen. It is very delicious.$"

gBerryDescriptionPart1_Grepa:: @ 858A14E
	.string "Despite its tenderness and round$"

gBerryDescriptionPart2_Grepa:: @ 858A16F
	.string "shape, the BERRY is unimaginably sour.$"

gBerryDescriptionPart1_Tamato:: @ 858A196
	.string "The BERRY is lip-bendingly spicy.$"

gBerryDescriptionPart2_Tamato:: @ 858A1B8
	.string "It takes time to grow.$"

gBerryDescriptionPart1_Cornn:: @ 858A1CF
	.string "A BERRY from an ancient era. May not$"

gBerryDescriptionPart2_Cornn:: @ 858A1F4
	.string "grow unless planted in quantity.$"

gBerryDescriptionPart1_Magost:: @ 858A215
	.string "A BERRY that is widely said to have$"

gBerryDescriptionPart2_Magost:: @ 858A239
	.string "a finely balanced flavor.$"

gBerryDescriptionPart1_Rabuta:: @ 858A253
	.string "A rare variety that is overgrown with$"

gBerryDescriptionPart2_Rabuta:: @ 858A279
	.string "hair. It is quite bitter.$"

gBerryDescriptionPart1_Nomel:: @ 858A293
	.string "Quite sour. Just one bite makes it$"

gBerryDescriptionPart2_Nomel:: @ 858A2B6
	.string "impossible to taste for three days.$"

gBerryDescriptionPart1_Spelon:: @ 858A2DA
	.string "The vividly red BERRY is very spicy.$"

gBerryDescriptionPart2_Spelon:: @ 858A2FF
	.string "Its warts secrete a spicy substance.$"

gBerryDescriptionPart1_Pamtre:: @ 858A324
	.string "Drifts on the sea from somewhere.$"

gBerryDescriptionPart2_Pamtre:: @ 858A346
	.string "It is thought to grow elsewhere.$"

gBerryDescriptionPart1_Watmel:: @ 858A367
	.string "A huge BERRY, with some over 20$"

gBerryDescriptionPart2_Watmel:: @ 858A387
	.string "inches discovered. Exceedingly sweet.$"

gBerryDescriptionPart1_Durin:: @ 858A3AD
	.string "Bitter to even look at. It is so$"

gBerryDescriptionPart2_Durin:: @ 858A3CE
	.string "bitter, no one has ever eaten it as is.$"

gBerryDescriptionPart1_Belue:: @ 858A3F6
	.string "It is glossy and looks delicious, but$"

gBerryDescriptionPart2_Belue:: @ 858A41C
	.string "it is awfully sour. Takes time to grow.$"

gBerryDescriptionPart1_Liechi:: @ 858A444
	.string "A mysterious BERRY. It is rumored to$"

gBerryDescriptionPart2_Liechi:: @ 858A469
	.string "contain the power of the sea.$"

gBerryDescriptionPart1_Ganlon:: @ 858A487
	.string "A mysterious BERRY. It is rumored to$"

gBerryDescriptionPart2_Ganlon:: @ 858A4AC
	.string "contain the power of the land.$"

gBerryDescriptionPart1_Salac:: @ 858A4CB
	.string "A mysterious BERRY. It is rumored to$"

gBerryDescriptionPart2_Salac:: @ 858A4F0
	.string "contain the power of the sky.$"

gBerryDescriptionPart1_Petaya:: @ 858A50E
	.string "A mysterious BERRY. It is rumored to$"

gBerryDescriptionPart2_Petaya:: @ 858A533
	.string "contain the power of all living things.$"

gBerryDescriptionPart1_Apicot:: @ 858A55B
	.string "A very mystifying BERRY. No telling$"

gBerryDescriptionPart2_Apicot:: @ 858A57F
	.string "what may happen or how it can be used.$"

gBerryDescriptionPart1_Lansat:: @ 858A5A6
	.string "Said to be a legendary BERRY.$"

gBerryDescriptionPart2_Lansat:: @ 858A5C4
	.string "Holding it supposedly brings joy.$"

gBerryDescriptionPart1_Starf:: @ 858A5E6
	.string "So strong, it was abandoned at the$"

gBerryDescriptionPart2_Starf:: @ 858A609
	.string "world's edge. Considered a mirage.$"

gBerryDescriptionPart1_Enigma:: @ 858A62C
	.string "A completely enigmatic BERRY.$"

gBerryDescriptionPart2_Enigma:: @ 858A64A
	.string "Appears to have the power of stars.$"

