gText_Birch_Welcome::
	.string "I see you're finally awake.\p"
	.string "It's me joel, the worse mod ever chowder!\p"
	.string "You've talked too much shit to me.\p"
	.string "So now it's time I get my revenge!\p"
	.string "By making you play a shitty ROM HACK of\n" 
	.string "Pokemon Emerald\p"
	.string "$"

gText_Birch_Pokemon::
	.string "This is what we call a “POKéMON.”\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "This world is widely inhabited by\n"
	.string "creatures known as POKéMON.\p"
	.string "We humans live alongside POKéMON,\n"
	.string "at times as friendly playmates, and\l"
	.string "at times as cooperative workmates.\p"
	.string "And sometimes, we band together\n"
	.string "and battle others like us.\p"
	.string "But despite our closeness, we don't\n"
	.string "know everything about POKéMON.\p"
	.string "In fact, there are many, many\n"
	.string "secrets surrounding POKéMON.\p"
	.string "To unravel POKéMON mysteries,\n"
	.string "I've been undertaking research.\l"
	.string "That's what I do.\p"
	.string "$"

gText_Birch_AndYouAre:: 
	.string "  $" 

gText_Birch_BoyOrGirl::   
	.string "Are you a boy?\n"  
	.string "Or are you a girl?$"  

gText_Birch_WhatsYourName::  
	.string "Bruh\n"  
	.string "What's your name?$"  

gText_Birch_SoItsPlayer::
	.string "So it's {PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
	.string "Ah, okay!\p"
	.string "You're {PLAYER}{KUN} who's moving to my\n"
	.string "hometown of LITTLEROOT.\l"
	.string "I get it now!\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "All right, are you ready?\p"
	.string "Your very own adventure is about\n"
	.string "to unfold.\p"
	.string "Take courage, and leap into the\n"
	.string "world of POKéMON where dreams,\l"
	.string "adventure, and friendships await!\p"
	.string "Imagine being swedish.\n"
	.string "ENJOY BRAZIL LOSER!\p"
	.string "$"
