gText_Birch_Welcome::
	.string "Bonjour! Désolé pour l’attente!\p"
	.string "Bienvenue dans le monde\n"
	.string "des POKéMON!\p"
	.string "Je m’appelle SEKO.\p"
	.string "Mais tout le monde ici m’appelle\n"
	.string "le PROFESSEUR POKéMON.\p"
	.string "$"

gText_Birch_Pokemon::
	.string "This is what we call a “POKéMON.”\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "Ce monde est peuplé de créatures\n"
	.string "appelées POKéMON.\p"
	.string "Nous, les humains, vivons avec les\n"
	.string "POKéMON. Il nous arrive de jouer\l"
	.string "ou de travailler ensemble.\p"
	.string "Et parfois, nous nous réunissons\n"
	.string "pour nous affronter au cours de\l"
	.string "formidables combats de POKéMON.\p"
	.string "Mais malgré nos liens, nous ne\n"
	.string "savons pas tout sur les POKéMON.\p"
	.string "En réalité, il existe d’innombrables\n"
	.string "secrets concernant les POKéMON.\p"
	.string "Pour percer les mystères des\n"
	.string "POKéMON, je les étudie. C’est\l"
	.string "mon métier, je suis chercheur.\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "Et toi, qui es-tu?$"

gText_Birch_BoyOrGirl::
	.string "Es-tu un garçon?\n"
	.string "Ou es-tu une fille?$"

gText_Birch_WhatsYourName::
	.string "Très bien.\n"
	.string "Comment t’appelles-tu?$"

gText_Birch_SoItsPlayer::
	.string "Tu t’appelles {PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
	.string "Ah, mais c’est vrai!\p"
	.string "Tu es {PLAYER}{KUN}! Tu viens d’arriver\n"
	.string "à BOURG-EN-VOL, là où j’habite.\p"
	.string "Je m’en souviens, maintenant!\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "Bon, comment te sens-tu?\p"
	.string "Tu es sur le point de commencer\n"
	.string "une aventure unique.\p"
	.string "Fais preuve de courage et plonge\n"
	.string "dans le monde des POKéMON où\l"
	.string "tu vivras de belles aventures,\l"
	.string "remplies de rêves et d’amitiés!\p"
	.string "Bien, rejoins-moi plus tard.\n"
	.string "Viens me voir au LABO POKéMON.\p"
	.string "$"
