gContestPaintingCool1:: @ 827EA7F
	.string "Nonstop supercool--\nthe inestimable {STR_VAR_1}$"

gContestPaintingCool2:: @ 827EAA6
	.string "Hey, there!\nThe good-looking POKéMON {STR_VAR_1}$"

gContestPaintingCool3:: @ 827EACE
	.string "The marvelous, wonderful, and\nvery great {STR_VAR_1}$"

gContestPaintingBeauty1:: @ 827EAFA
	.string "This century’s last Venus--\nthe beautiful {STR_VAR_1}$"

gContestPaintingBeauty2:: @ 827EB27
	.string "{STR_VAR_1}’s dazzling,\nglittering smile$"

gContestPaintingBeauty3:: @ 827EB47
	.string "POKéMON CENTER’s super idol--\nthe incomparable {STR_VAR_1}$"

gContestPaintingCute1:: @ 827EB79
	.string "The lovely and sweet {STR_VAR_1}$"

gContestPaintingCute2:: @ 827EB91
	.string "The pretty {STR_VAR_1}’s\nwinning portrait$"

gContestPaintingCute3:: @ 827EBB2
	.string "Give us a wink!\nThe cutie POKéMON {STR_VAR_1}$"

gContestPaintingSmart1:: @ 827EBD7
	.string "The smartness maestro--\nthe wise POKéMON {STR_VAR_1}$"

gContestPaintingSmart2:: @ 827EC03
	.string "{STR_VAR_1}--the one chosen\nabove all POKéMON$"

gContestPaintingSmart3:: @ 827EC28
	.string "The excellent {STR_VAR_1}’s\nmoment of elegance$"

gContestPaintingTough1:: @ 827EC4E
	.string "The powerfully muscular\nspeedster {STR_VAR_1}$"

gContestPaintingTough2:: @ 827EC73
	.string "The strong, stronger, and\nstrongest {STR_VAR_1}$"

gContestPaintingTough3:: @ 827EC9A
	.string "The mighty tough\nhyper POKéMON {STR_VAR_1}$"	
