gGiftRibbonDescriptionPart1_2003RegionalTourney:: @ 8623A74
	.string "2003 Regional Tourney$"

gGiftRibbonDescriptionPart2_Champion:: @ 8623A8A
	.string "Champion Ribbon$"

gGiftRibbonDescriptionPart1_2003NationalTourney:: @ 8623A9A
	.string "2003 National Tourney$"

gGiftRibbonDescriptionPart1_2003GlobalCup:: @ 8623AB0
	.string "2003 Global Cup$"

gGiftRibbonDescriptionPart2_RunnerUp:: @ 8623AC0
	.string "Runner-up Ribbon$"

gGiftRibbonDescriptionPart2_Semifinalist:: @ 8623AD1
	.string "Semifinalist Ribbon$"

gGiftRibbonDescriptionPart1_2004RegionalTourney:: @ 8623AE5
	.string "2004 Regional Tourney$"

gGiftRibbonDescriptionPart1_2004NationalTourney:: @ 8623AFB
	.string "2004 National Tourney$"

gGiftRibbonDescriptionPart1_2004GlobalCup:: @ 8623B11
	.string "2004 Global Cup$"

gGiftRibbonDescriptionPart1_2005RegionalTourney:: @ 8623B21
	.string "2005 Regional Tourney$"

gGiftRibbonDescriptionPart1_2005NationalTourney:: @ 8623B37
	.string "2005 National Tourney$"

gGiftRibbonDescriptionPart1_2005GlobalCup:: @ 8623B4D
	.string "2005 Global Cup$"

gGiftRibbonDescriptionPart1_PokemonBattleCup:: @ 8623B5D
	.string "Pokémon Battle Cup$"

gGiftRibbonDescriptionPart2_Participation:: @ 8623B70
	.string "Participation Ribbon$"

gGiftRibbonDescriptionPart1_PokemonLeague:: @ 8623B85
	.string "Pokémon League$"

gGiftRibbonDescriptionPart1_AdvanceCup:: @ 8623B94
	.string "Advance Cup$"

gGiftRibbonDescriptionPart1_PokemonTournament:: @ 8623BA0
	.string "Pokémon Tournament$"

gGiftRibbonDescriptionPart2_Participation2:: @ 8623BB3
	.string "Participation Ribbon$"

gGiftRibbonDescriptionPart1_PokemonEvent:: @ 8623BC8
	.string "Pokémon Event$"

gGiftRibbonDescriptionPart1_PokemonFestival:: @ 8623BD6
	.string "Pokémon Festival$"

gGiftRibbonDescriptionPart1_DifficultyClearing:: @ 8623BE7
	.string "Difficulty-clearing$"

gGiftRibbonDescriptionPart2_Commemorative:: @ 8623BFB
	.string "Commemorative Ribbon$"

gGiftRibbonDescriptionPart1_ClearingAllChallenges:: @ 8623C10
	.string "Ribbon awarded for$"

gGiftRibbonDescriptionPart2_ClearingAllChallenges:: @ 8623C23
	.string "clearing all challenges.$"

gGiftRibbonDescriptionPart1_100StraightWin:: @ 8623C3C
	.string "100-straight Win$"

gGiftRibbonDescriptionPart1_DarknessTower:: @ 8623C4D
	.string "Darkness Tower Clear$"

gGiftRibbonDescriptionPart1_RedTower:: @ 8623C62
	.string "Red Tower Clear$"

gGiftRibbonDescriptionPart1_BlackironTower:: @ 8623C72
	.string "Blackiron Tower Clear$"

gGiftRibbonDescriptionPart1_FinalTower:: @ 8623C88
	.string "Final Tower Clear$"

gGiftRibbonDescriptionPart1_LegendMaking:: @ 8623C9A
	.string "Legend-making$"

gGiftRibbonDescriptionPart1_PokemonCenterTokyo:: @ 8623CA8
	.string "Pokémon Center Tokyo$"

gGiftRibbonDescriptionPart1_PokemonCenterOsaka:: @ 8623CBD
	.string "Pokémon Center Osaka$"

gGiftRibbonDescriptionPart1_PokemonCenterNagoya:: @ 8623CD2
	.string "Pokémon Center Nagoya$"

gGiftRibbonDescriptionPart1_PokemonCenterNY:: @ 8623CE8
	.string "Pokémon Center NY$"

gGiftRibbonDescriptionPart1_SummerHolidays:: @ 8623CFA
	.string "Summer Holidays Ribbon$"

gGiftRibbonDescriptionPart2_EmptyString:: @ 8623D11
	.string "$"

gGiftRibbonDescriptionPart1_WinterHolidays:: @ 8623D12
	.string "Winter Holidays Ribbon$"

gGiftRibbonDescriptionPart1_SpringHolidays:: @ 8623D29
	.string "Spring Holidays Ribbon$"

gGiftRibbonDescriptionPart1_Evergreen:: @ 8623D40
	.string "Evergreen Ribbon$"

gGiftRibbonDescriptionPart1_SpecialHoliday:: @ 8623D51
	.string "Special Holiday Ribbon$"

gGiftRibbonDescriptionPart1_HardWorker:: @ 8623D68
	.string "Hard Worker Ribbon$"

gGiftRibbonDescriptionPart1_LotsOfFriends:: @ 8623D7B
	.string "Lots of Friends Ribbon$"

gGiftRibbonDescriptionPart1_FullOfEnergy:: @ 8623D92
	.string "Full of Energy Ribbon$"

gGiftRibbonDescriptionPart1_LovedPokemon:: @ 8623DA8
	.string "A commemorative Ribbon$"

gGiftRibbonDescriptionPart2_LovedPokemon:: @ 8623DBF
	.string "for a loved Pokémon.$"

gGiftRibbonDescriptionPart1_LoveForPokemon:: @ 8623DD4
	.string "Ribbon that shows$"

gGiftRibbonDescriptionPart2_LoveForPokemon:: @ 8623DE6
	.string "love for Pokémon.$"

	.align 2
gGiftRibbonDescriptionPointers:: @ 8623DF8
	.4byte gGiftRibbonDescriptionPart1_2003RegionalTourney,   gGiftRibbonDescriptionPart2_Champion
	.4byte gGiftRibbonDescriptionPart1_2003NationalTourney,   gGiftRibbonDescriptionPart2_Champion
	.4byte gGiftRibbonDescriptionPart1_2003GlobalCup,         gGiftRibbonDescriptionPart2_Champion
	.4byte gGiftRibbonDescriptionPart1_2003RegionalTourney,   gGiftRibbonDescriptionPart2_RunnerUp
	.4byte gGiftRibbonDescriptionPart1_2003NationalTourney,   gGiftRibbonDescriptionPart2_RunnerUp
	.4byte gGiftRibbonDescriptionPart1_2003GlobalCup,         gGiftRibbonDescriptionPart2_RunnerUp
	.4byte gGiftRibbonDescriptionPart1_2003RegionalTourney,   gGiftRibbonDescriptionPart2_Semifinalist
	.4byte gGiftRibbonDescriptionPart1_2003NationalTourney,   gGiftRibbonDescriptionPart2_Semifinalist
	.4byte gGiftRibbonDescriptionPart1_2003GlobalCup,         gGiftRibbonDescriptionPart2_Semifinalist
	.4byte gGiftRibbonDescriptionPart1_2004RegionalTourney,   gGiftRibbonDescriptionPart2_Champion
	.4byte gGiftRibbonDescriptionPart1_2004NationalTourney,   gGiftRibbonDescriptionPart2_Champion
	.4byte gGiftRibbonDescriptionPart1_2004GlobalCup,         gGiftRibbonDescriptionPart2_Champion
	.4byte gGiftRibbonDescriptionPart1_2004RegionalTourney,   gGiftRibbonDescriptionPart2_RunnerUp
	.4byte gGiftRibbonDescriptionPart1_2004NationalTourney,   gGiftRibbonDescriptionPart2_RunnerUp
	.4byte gGiftRibbonDescriptionPart1_2004GlobalCup,         gGiftRibbonDescriptionPart2_RunnerUp
	.4byte gGiftRibbonDescriptionPart1_2004RegionalTourney,   gGiftRibbonDescriptionPart2_Semifinalist
	.4byte gGiftRibbonDescriptionPart1_2004NationalTourney,   gGiftRibbonDescriptionPart2_Semifinalist
	.4byte gGiftRibbonDescriptionPart1_2004GlobalCup,         gGiftRibbonDescriptionPart2_Semifinalist
	.4byte gGiftRibbonDescriptionPart1_2005RegionalTourney,   gGiftRibbonDescriptionPart2_Champion
	.4byte gGiftRibbonDescriptionPart1_2005NationalTourney,   gGiftRibbonDescriptionPart2_Champion
	.4byte gGiftRibbonDescriptionPart1_2005GlobalCup,         gGiftRibbonDescriptionPart2_Champion
	.4byte gGiftRibbonDescriptionPart1_2005RegionalTourney,   gGiftRibbonDescriptionPart2_RunnerUp
	.4byte gGiftRibbonDescriptionPart1_2005NationalTourney,   gGiftRibbonDescriptionPart2_RunnerUp
	.4byte gGiftRibbonDescriptionPart1_2005GlobalCup,         gGiftRibbonDescriptionPart2_RunnerUp
	.4byte gGiftRibbonDescriptionPart1_2005RegionalTourney,   gGiftRibbonDescriptionPart2_Semifinalist
	.4byte gGiftRibbonDescriptionPart1_2005NationalTourney,   gGiftRibbonDescriptionPart2_Semifinalist
	.4byte gGiftRibbonDescriptionPart1_2005GlobalCup,         gGiftRibbonDescriptionPart2_Semifinalist
	.4byte gGiftRibbonDescriptionPart1_PokemonBattleCup,      gGiftRibbonDescriptionPart2_Champion
	.4byte gGiftRibbonDescriptionPart1_PokemonBattleCup,      gGiftRibbonDescriptionPart2_RunnerUp
	.4byte gGiftRibbonDescriptionPart1_PokemonBattleCup,      gGiftRibbonDescriptionPart2_Semifinalist
	.4byte gGiftRibbonDescriptionPart1_PokemonBattleCup,      gGiftRibbonDescriptionPart2_Participation
	.4byte gGiftRibbonDescriptionPart1_PokemonLeague,         gGiftRibbonDescriptionPart2_Champion
	.4byte gGiftRibbonDescriptionPart1_PokemonLeague,         gGiftRibbonDescriptionPart2_RunnerUp
	.4byte gGiftRibbonDescriptionPart1_PokemonLeague,         gGiftRibbonDescriptionPart2_Semifinalist
	.4byte gGiftRibbonDescriptionPart1_PokemonLeague,         gGiftRibbonDescriptionPart2_Participation
	.4byte gGiftRibbonDescriptionPart1_AdvanceCup,            gGiftRibbonDescriptionPart2_Champion
	.4byte gGiftRibbonDescriptionPart1_AdvanceCup,            gGiftRibbonDescriptionPart2_RunnerUp
	.4byte gGiftRibbonDescriptionPart1_AdvanceCup,            gGiftRibbonDescriptionPart2_Semifinalist
	.4byte gGiftRibbonDescriptionPart1_AdvanceCup,            gGiftRibbonDescriptionPart2_Participation
	.4byte gGiftRibbonDescriptionPart1_PokemonTournament,     gGiftRibbonDescriptionPart2_Participation2
	.4byte gGiftRibbonDescriptionPart1_PokemonEvent,          gGiftRibbonDescriptionPart2_Participation2
	.4byte gGiftRibbonDescriptionPart1_PokemonFestival,       gGiftRibbonDescriptionPart2_Participation2
	.4byte gGiftRibbonDescriptionPart1_DifficultyClearing,    gGiftRibbonDescriptionPart2_Commemorative
	.4byte gGiftRibbonDescriptionPart1_ClearingAllChallenges, gGiftRibbonDescriptionPart2_ClearingAllChallenges
	.4byte gGiftRibbonDescriptionPart1_100StraightWin,        gGiftRibbonDescriptionPart2_Commemorative
	.4byte gGiftRibbonDescriptionPart1_DarknessTower,         gGiftRibbonDescriptionPart2_Commemorative
	.4byte gGiftRibbonDescriptionPart1_RedTower,              gGiftRibbonDescriptionPart2_Commemorative
	.4byte gGiftRibbonDescriptionPart1_BlackironTower,        gGiftRibbonDescriptionPart2_Commemorative
	.4byte gGiftRibbonDescriptionPart1_FinalTower,            gGiftRibbonDescriptionPart2_Commemorative
	.4byte gGiftRibbonDescriptionPart1_LegendMaking,          gGiftRibbonDescriptionPart2_Commemorative
	.4byte gGiftRibbonDescriptionPart1_PokemonCenterTokyo,    gGiftRibbonDescriptionPart2_Commemorative
	.4byte gGiftRibbonDescriptionPart1_PokemonCenterOsaka,    gGiftRibbonDescriptionPart2_Commemorative
	.4byte gGiftRibbonDescriptionPart1_PokemonCenterNagoya,   gGiftRibbonDescriptionPart2_Commemorative
	.4byte gGiftRibbonDescriptionPart1_PokemonCenterNY,       gGiftRibbonDescriptionPart2_Commemorative
	.4byte gGiftRibbonDescriptionPart1_SummerHolidays,        gGiftRibbonDescriptionPart2_EmptyString
	.4byte gGiftRibbonDescriptionPart1_WinterHolidays,        gGiftRibbonDescriptionPart2_EmptyString
	.4byte gGiftRibbonDescriptionPart1_SpringHolidays,        gGiftRibbonDescriptionPart2_EmptyString
	.4byte gGiftRibbonDescriptionPart1_Evergreen,             gGiftRibbonDescriptionPart2_EmptyString
	.4byte gGiftRibbonDescriptionPart1_SpecialHoliday,        gGiftRibbonDescriptionPart2_EmptyString
	.4byte gGiftRibbonDescriptionPart1_HardWorker,            gGiftRibbonDescriptionPart2_EmptyString
	.4byte gGiftRibbonDescriptionPart1_LotsOfFriends,         gGiftRibbonDescriptionPart2_EmptyString
	.4byte gGiftRibbonDescriptionPart1_FullOfEnergy,          gGiftRibbonDescriptionPart2_EmptyString
	.4byte gGiftRibbonDescriptionPart1_LovedPokemon,          gGiftRibbonDescriptionPart2_LovedPokemon
	.4byte gGiftRibbonDescriptionPart1_LoveForPokemon,        gGiftRibbonDescriptionPart2_LoveForPokemon
