@ Only contains a portion of the mauville_man text. The rest is in scripts/mauville_man.inc
gText_SoPretty::
	.string " so pretty!$"

gText_SoDarling::
	.string " so darling!$"

gText_SoRelaxed::
	.string " so relaxed!$"

gText_SoSunny::
	.string " so sunny!$"

gText_SoDesirable::
	.string " so desirable!$"

gText_SoExciting::
	.string " so exciting!$"

gText_SoAmusing::
	.string " so amusing!$"

gText_SoMagical::
	.string " so magical!$"

gOtherText_Is::
	.string " is$"

gOtherText_DontYouAgree::
	.string "\n"
	.string "Don't you agree?$"

gMauvilleManText_ISoWantToGoOnAVacation::
	.string "I so want to go on a vacation.\n"
	.string "Would you happen to know a nice place?$"

gMauvilleManText_IBoughtCrayonsWith120Colors::
	.string "I bought crayons with 120 colors!\n"
	.string "Don't you think that's nice?$"

gMauvilleManText_WouldntItBeNiceIfWeCouldFloat::
	.string "Wouldn't it be nice if we could float\n"
	.string "away on a cloud of bubbles?$"

gMauvilleManText_WhenYouWriteOnASandyBeach::
	.string "When you write on a sandy beach,\n"
	.string "they wash away. It makes me sad.$"

gMauvilleManText_WhatsTheBottomOfTheSeaLike::
	.string "What's the bottom of the sea like?\n"
	.string "Just once I would so love to go!$"

gMauvilleManText_WhenYouSeeTheSettingSunDoesIt::
	.string "When you see the setting sun, does it\n"
	.string "make you want to go home?$"

gMauvilleManText_LyingBackInTheGreenGrass::
	.string "Lying back in the green grass…\n"
	.string "Oh, it's so, so nice!$"

gMauvilleManText_SecretBasesAreSoWonderful::
	.string "SECRET BASES are so wonderful!\n"
	.string "Can't you feel the excitement?$"
