Mevent_Text_FillOutQuestionnaire:: @ 827339F
	.string "There is a questionnaire.\n"
	.string "Would you like to fill it out?$"

Mevent_Text_QuestionnaireThankYou:: @ 82733D8
	.string "Thank you for taking the time to\n"
	.string "fill out our questionnaire.\p"
	.string "Your feedback will be used for\n"
	.string "future reference.$"

Mevent_Text_YouKnowThoseWordsGift:: @ 8273446
	.string "Oh, hello!\n"
	.string "You know those words?\p"
	.string "That means you must know about\n"
	.string "the MYSTERY GIFT.\p"
	.string "From now on, you should be\n"
	.string "receiving MYSTERY GIFTS!$"

Mevent_Text_YouCanAccessMysteryGift:: @ 82734CC
	.string "Once you save your game, you can\n"
	.string "access the MYSTERY GIFT.$"

Mevent_Text_YouKnowThoseWordsEvent:: @ 8273506
	.string "Oh, hello!\n"
	.string "You know those words?\p"
	.string "That means you must know about\n"
	.string "the MYSTERY EVENT.$"

Mevent_Text_YouCanAccessMysteryEvent:: @ 8273559
	.string "Once you save your game, you can\n"
	.string "access the MYSTERY EVENT.$"

Mevent_Text_TheresATicketForYou:: @ 8273594
	.string "Thank you for using the MYSTERY\n"
	.string "EVENT System.\p"
	.string "You must be {PLAYER}.\n"
	.string "There is a ticket here for you.$"

Mevent_Text_TryUsingItAtLilycovePort:: @ 82735F2
	.string "It appears to be for use at\n"
	.string "the LILYCOVE CITY port.\p"
	.string "Why not give it a try and see what\n"
	.string "it is about?$"
