gBirchDexRatingText_AreYouCurious:: @ 82A5C9C
	.string "Prof. Birch: Ah, {PLAYER}{KUN}!\p"
	.string "Are you curious about how your\n"
	.string "Pokédex is coming along?$"

gBirchDexRatingText_Cancel: @ 82A5CEB
	.string "Hm? Oh, you haven't caught enough\n"
	.string "Pokémon to make it worthwhile.$"

gBirchDexRatingText_SoYouveSeenAndCaught:: @ 82A5D2C
	.string "Hmhm…\p"
	.string "So, you've seen {STR_VAR_1} Pokémon,\n"
	.string "and you've caught {STR_VAR_2} Pokémon…$"

gBirchDexRatingText_LessThan10:: @ 82A5D6C
	.string "Go into grassy areas more and look\n"
	.string "for Pokémon more carefully.$"

gBirchDexRatingText_LessThan20:: @ 82A5DAB
	.string "I guess you're getting the hang\n"
	.string "of it. But, it gets harder from here.$"

gBirchDexRatingText_LessThan30:: @ 82A5DF1
	.string "Some Pokémon only appear in\n"
	.string "certain areas.\l"
	.string "You must be persistent.$"

gBirchDexRatingText_LessThan40:: @ 82A5E34
	.string "Well, it could use more quantity,\n"
	.string "but this is looking more like\l"
	.string "a Pokédex now.$"

gBirchDexRatingText_LessThan50:: @ 82A5E83
	.string "This is coming along pretty good.\n"
	.string "Keep up the effort.$"

gBirchDexRatingText_LessThan60:: @ 82A5EB9
	.string "Are you using any Rods?\n"
	.string "There are many Pokémon in the sea.$"

gBirchDexRatingText_LessThan70:: @ 82A5EF4
	.string "Instead of just catching Pokémon,\n"
	.string "how about making them evolve, too?$"

gBirchDexRatingText_LessThan80:: @ 82A5F39
	.string "This is going to be a fantastic\n"
	.string "Pokédex.\l"
	.string "That's the feeling I'm getting.$"

gBirchDexRatingText_LessThan90:: @ 82A5F82
	.string "You've collected this many…\n"
	.string "Your talent is remarkable!$"

gBirchDexRatingText_LessThan100:: @ 82A5FB9
	.string "Have you visited the Safari Zone?\p"
	.string "I hear there are some Pokémon that\n"
	.string "can only be caught there.$"

gBirchDexRatingText_LessThan110:: @ 82A6018
	.string "You've finally reached\n"
	.string "the 100-kind mark.\p"
	.string "This is an impressive Pokédex!$"

gBirchDexRatingText_LessThan120:: @ 82A6061
	.string "There might be Pokémon that can be\n"
	.string "found using Rock Smash.$"

gBirchDexRatingText_LessThan130:: @ 82A609C
	.string "You should get some more Pokémon\n"
	.string "by trading with others.$"

gBirchDexRatingText_LessThan140:: @ 82A60D5
	.string "I've heard of Pokémon that evolve\n"
	.string "when they come to fully love their\l"
	.string "Trainers.$"

gBirchDexRatingText_LessThan150:: @ 82A6124
	.string "I had no idea that there were so\n"
	.string "many Pokémon species in the Hoenn\l"
	.string "region.$"

gBirchDexRatingText_LessThan160:: @ 82A616F
	.string "On occasion, some Pokémon appear\n"
	.string "in large numbers like outbreaks.\p"
	.string "Don't miss opportunities like\n"
	.string "those.$"

gBirchDexRatingText_LessThan170:: @ 82A61D6
	.string "One can get a very good idea about\n"
	.string "the Pokémon of the Hoenn region\l"
	.string "by looking through your Pokédex.$"

gBirchDexRatingText_LessThan180:: @ 82A623A
	.string "I would say you already qualify as\n"
	.string "a Pokémon Professor, and a good\l"
	.string "one, too!$"

gBirchDexRatingText_LessThan190:: @ 82A6287
	.string "With a Pokédex this complete,\n"
	.string "you're a real professional at this!$"

gBirchDexRatingText_LessThan200:: @ 82A62C9
	.string "You're very close to completing\n"
	.string "this Pokédex.\l"
	.string "I can feel it in my bones!$"

gBirchDexRatingText_DexCompleted:: @ 82A6312
	.string "Congratulations!\n"
	.string "Your Pokédex is complete!$"

gBirchDexRatingText_OnANationwideBasis:: @ 82A633D
	.string "Hmhm…\n"
	.string "On a nationwide basis…\p"
	.string "You've seen {STR_VAR_1} Pokémon,\n"
	.string "and you've caught {STR_VAR_2} Pokémon…$"
