SecretBase_Text_Trainer0Intro: @ 82748A0
    .string "Have you made a SECRET BASE already?\p"
    .string "I went here, there, everywhere before\n"
    .string "choosing this place.\p"
    .string "Since you're already here, how would\n"
    .string "you like to battle?$"

SecretBase_Text_Trainer0AcceptBattle: @ 8274939
    .string "Okay!\n"
    .string "Here we come!$"

SecretBase_Text_Trainer0DeclineBattle: @ 827494D
    .string "Hunh?\n"
    .string "Oh, you can't now…$"

SecretBase_Text_Trainer0Defeated:: @ 8274966
    .string "Waaargh! You're too strong!\n"
    .string "About me losing… Please keep it secret!$"

SecretBase_Text_Trainer0PostBattle: @ 82749AA
    .string "What do you think of my SECRET BASE?\n"
    .string "Come visit me again tomorrow.$"

SecretBase_Text_Trainer0PreChampion: @ 82749ED
    .string "Have you made a SECRET BASE already?\p"
    .string "I went here, there, everywhere before\n"
    .string "choosing this place.\p"
    .string "Feel free to hang out!$"

SecretBase_Text_Trainer5Intro: @ 8274A64
    .string "There're a lot of places where\n"
    .string "you can make a SECRET BASE.\p"
    .string "But I like this spot best.\n"
    .string "Don't you think it's nice?\p"
    .string "Oh, would you like to have a battle?$"

SecretBase_Text_Trainer5AcceptBattle: @ 8274AFA
    .string "Okay, here goes!$"

SecretBase_Text_Trainer5DeclineBattle: @ 8274B0B
    .string "Oh…\n"
    .string "You can't now, okay.$"

SecretBase_Text_Trainer5Defeated:: @ 8274B24
    .string "Hmmm… It's our loss…\n"
    .string "But don't tell anyone!\l"
    .string "It's a confidential secret!$"

SecretBase_Text_Trainer5PostBattle: @ 8274B6C
    .string "If you're in this area again,\n"
    .string "I hope you'll visit me.$"

SecretBase_Text_Trainer5PreChampion: @ 8274BA2
    .string "There're a lot of places where you can\n"
    .string "make a SECRET BASE.\p"
    .string "But I like this spot best.\n"
    .string "Don't you think it's nice?$"

SecretBase_Text_Trainer1Intro: @ 8274C13
    .string "This is a popular spot.\n"
    .string "It's always taken.\p"
    .string "Oh! Were you thinking about\n"
    .string "taking this spot, too?\p"
    .string "I'll tell you what, you can have this\n"
    .string "spot if you can beat me.$"

SecretBase_Text_Trainer1AcceptBattle: @ 8274CB0
    .string "Okay!\n"
    .string "I'm going to defend my SECRET BASE!$"

SecretBase_Text_Trainer1DeclineBattle: @ 8274CDA
    .string "Hunh? Is that right?\n"
    .string "You're not interested in this spot?$"

SecretBase_Text_Trainer1Defeated:: @ 8274D13
    .string "I can't keep going!\n"
    .string "I surrender!$"

SecretBase_Text_Trainer1PostBattle: @ 8274D34
    .string "Okay, when I move one day,\n"
    .string "this place will be yours!$"

SecretBase_Text_Trainer1PreChampion: @ 8274D69
    .string "This is a popular spot.\n"
    .string "It's always taken.\p"
    .string "I waited a long time for it to open.\n"
    .string "I finally got to use it!$"

SecretBase_Text_Trainer6Intro: @ 8274DD2
    .string "Welcome to my POKéMON LAB.\p"
    .string "I carry out research on battling in\n"
    .string "secrecy.\p"
    .string "Would you like to see how strong I am?$"

SecretBase_Text_Trainer6AcceptBattle: @ 8274E41
    .string "I'm going to go all out!$"

SecretBase_Text_Trainer6DeclineBattle: @ 8274E5A
    .string "Oh.\n"
    .string "Some other time, then!$"

SecretBase_Text_Trainer6Defeated:: @ 8274E75
    .string "Hmm… I've still got lots to learn.\n"
    .string "I have to study some more.$"

SecretBase_Text_Trainer6PostBattle: @ 8274EB3
    .string "Thanks for battling with me.\n"
    .string "Please come back again tomorrow.$"

SecretBase_Text_Trainer6PreChampion: @ 8274EF1
    .string "Welcome to my POKéMON LAB.\p"
    .string "I carry out research on battling in\n"
    .string "secrecy.$"

SecretBase_Text_Trainer2Intro: @ 8274F39
    .string "A big mansion is nice, but I like this\n"
    .string "sort of place more.\p"
    .string "I like it because all kinds of people\n"
    .string "come visit me.\p"
    .string "So, how would you like a battle?$"

SecretBase_Text_Trainer2AcceptBattle: @ 8274FCA
    .string "That's the way!$"

SecretBase_Text_Trainer2DeclineBattle: @ 8274FDA
    .string "When you're ready, give me a shout!$"

SecretBase_Text_Trainer2Defeated:: @ 8274FFE
    .string "Aww! Done in!\n"
    .string "But it's still fun to battle!$"

SecretBase_Text_Trainer2PostBattle: @ 827502A
    .string "Well, anyway, I should go buy some\n"
    .string "decorations and furniture.\p"
    .string "I want my SECRET BASE to be a place\n"
    .string "other people can enjoy.$"

SecretBase_Text_Trainer2PreChampion: @ 82750A4
    .string "A big mansion is nice, but I like this\n"
    .string "sort of place more.\p"
    .string "I like it because all kinds of people\n"
    .string "come visit me.$"

SecretBase_Text_Trainer7Intro: @ 8275114
    .string "I simply adore shopping for decorations\n"
    .string "and furniture.\p"
    .string "I also love raising POKéMON just\n"
    .string "as much.\p"
    .string "If you would be so kind, will you battle\n"
    .string "with my POKéMON?$"

SecretBase_Text_Trainer7AcceptBattle: @ 82751AF
    .string "Thank you.\n"
    .string "Shall we begin?$"

SecretBase_Text_Trainer7DeclineBattle: @ 82751CA
    .string "Oh.\n"
    .string "How disappointing…$"

SecretBase_Text_Trainer7Defeated:: @ 82751E1
    .string "I concede…$"

SecretBase_Text_Trainer7PostBattle: @ 82751EC
    .string "That was all in good fun!\n"
    .string "I should go enjoy shopping now.$"

SecretBase_Text_Trainer7PreChampion: @ 8275226
    .string "I simply adore shopping for decorations\n"
    .string "and furniture.\p"
    .string "I also love raising POKéMON just\n"
    .string "as much.$"

SecretBase_Text_Trainer3Intro: @ 8275287
    .string "Some people make their SECRET BASES in\n"
    .string "hard-to-find places.\l"
    .string "Do they want to just lie low?\p"
    .string "But since you found me, how about we\n"
    .string "have a battle?$"

SecretBase_Text_Trainer3AcceptBattle: @ 8275315
    .string "I'm not going down easily!$"

SecretBase_Text_Trainer3DeclineBattle: @ 8275330
    .string "Oh… Are you maybe tired from searching\n"
    .string "for this place?$"

SecretBase_Text_Trainer3Defeated:: @ 8275367
    .string "I went down…$"

SecretBase_Text_Trainer3PostBattle: @ 8275374
    .string "Where's your SECRET BASE?\n"
    .string "I should go visit you there.$"

SecretBase_Text_Trainer3PreChampion: @ 82753AB
    .string "Some people make their SECRET BASES in\n"
    .string "hard-to-find places.\l"
    .string "Do they want to just lie low?$"

SecretBase_Text_Trainer8Intro: @ 8275405
    .string "People have told me that you can get\n"
    .string "decorations in several ways.\p"
    .string "We should have a race to see who can\n"
    .string "get nicer decorations and furniture!\p"
    .string "In the meantime, want to battle?$"

SecretBase_Text_Trainer8AcceptBattle: @ 82754B2
    .string "This is my SECRET BASE.\n"
    .string "I can't lose!$"

SecretBase_Text_Trainer8DeclineBattle: @ 82754D8
    .string "I'll battle with you anytime.$"

SecretBase_Text_Trainer8Defeated:: @ 82754F6
    .string "Huh?\n"
    .string "Did I just lose?$"

SecretBase_Text_Trainer8PostBattle: @ 827550C
    .string "I won't lose at collecting decorations.\n"
    .string "Come visit again!$"

SecretBase_Text_Trainer8PreChampion: @ 8275546
    .string "People have told me that you can get\n"
    .string "decorations in several ways.\p"
    .string "We should have a race to see who can\n"
    .string "get nicer decorations and furniture!$"

SecretBase_Text_Trainer4Intro: @ 82755D2
    .string "I found a spot I liked, and I did it up\n"
    .string "with my favorite decorations.\p"
    .string "I raise my favorite POKéMON and grow\n"
    .string "stronger with it.\p"
    .string "That's what I do.\n"
    .string "Want to battle with me?$"

SecretBase_Text_Trainer4AcceptBattle: @ 8275679
    .string "Show me what you're made of!$"

SecretBase_Text_Trainer4DeclineBattle: @ 8275696
    .string "I guess there are times when you're not\n"
    .string "into it.$"

SecretBase_Text_Trainer4Defeated:: @ 82756C7
    .string "I know exactly what you're made of now.$"

SecretBase_Text_Trainer4PostBattle: @ 82756EF
    .string "We can both become stronger.\n"
    .string "Let's keep at it!$"

SecretBase_Text_Trainer4PreChampion: @ 827571E
    .string "I found a spot I liked, and I did it up\n"
    .string "with my favorite decorations.\p"
    .string "I raise my favorite POKéMON and grow\n"
    .string "stronger with it.\p"
    .string "Every day is a great day.$"

SecretBase_Text_Trainer9Intro: @ 82757B5
    .string "You can learn a lot about the taste\n"
    .string "and sense of people by the kinds of\l"
    .string "decorations they have, and how they\l"
    .string "display them.\p"
    .string "What do you think of my taste?\n"
    .string "Are you speechless?\p"
    .string "Want to see my taste in battling?$"

SecretBase_Text_Trainer9AcceptBattle: @ 8275884
    .string "There's no holding back!$"

SecretBase_Text_Trainer9DeclineBattle: @ 827589D
    .string "I'll be happy to demonstrate my style\n"
    .string "anytime.$"

SecretBase_Text_Trainer9Defeated:: @ 82758CC
    .string "You're supremely talented!\n"
    .string "Your power seems to be limitless…$"

SecretBase_Text_Trainer9PostBattle: @ 8275909
    .string "What did you think of my style?\n"
    .string "I'll keep on polishing it!$"

SecretBase_Text_Trainer9PreChampion: @ 8275944
    .string "You can learn a lot about the taste\n"
    .string "and sense of people by the kinds of\l"
    .string "decorations they have, and how they\l"
    .string "display them.\p"
    .string "What do you think of my taste?\n"
    .string "Are you speechless?$"
