Route102_Text_294513: @ 8294513
	.string "If you have POKéMON with you, then\n"
	.string "you're an official POKéMON TRAINER!\l"
	.string "You can't say no to my challenge!$"

Route102_Text_29457C: @ 829457C
	.string "Arrgh, I lost…\n"
	.string "I should have trained mine more…$"

Route102_Text_2945AC: @ 82945AC
	.string "Listen, you. If you're strong,\n"
	.string "you should have told me before!$"

Route102_Text_2945EB: @ 82945EB
	.string "I've been working hard at this since\n"
	.string "I saw you before.\p"
	.string "I'd like to battle you again, so can\n"
	.string "you register me in your POKéNAV?$"

Route102_Text_294668: @ 8294668
	.string "I'd like to battle you again, so can\n"
	.string "you register me in your POKéNAV?$"

Route102_Text_2946AE: @ 82946AE
	.string "Ever since I lost to you, I desperately\n"
	.string "trained my POKéMON.\l"
	.string "You can't say no to my challenge!$"

Route102_Text_29470C: @ 829470C
	.string "Arrgh, I lost…\n"
	.string "Is my training method not right?$"

Route102_Text_29473C: @ 829473C
	.string "If you're going to get stronger,\n"
	.string "I'll get stronger, too.$"

Route102_Text_294775: @ 8294775
	.string "Did you just become a TRAINER?\n"
	.string "We're both beginners!$"

Route102_Text_2947AA: @ 82947AA
	.string "I called you because I thought\n"
	.string "I could beat you…$"

Route102_Text_2947DB: @ 82947DB
	.string "I haven't won once yet…\n"
	.string "I wish I would win soon…$"

Route102_Text_29480C: @ 829480C
	.string "Hahah! Our eyes met!\n"
	.string "I'll take you on with my BUG POKéMON!$"

Route102_Text_294847: @ 8294847
	.string "Ow! Down and out!$"

Route102_Text_294859: @ 8294859
	.string "If you lock eyes with a TRAINER,\n"
	.string "you have to challenge! It's a rule!$"

Route102_Text_29489E: @ 829489E
	.string "I'm going to keep winning and aim\n"
	.string "to be the best TRAINER.\p"
	.string "Help me further my career!$"

Route102_Text_2948F3: @ 82948F3
	.string "I ended up furthering your career…$"

Route102_Text_294916: @ 8294916
	.string "To keep winning my way up, I see that\n"
	.string "I have to catch more POKéMON.$"

Route103_Text_29495A: @ 829495A
	.string "Did you feel the tug of our\n"
	.string "soul-soothing fragrance?$"

Route103_Text_29498F: @ 829498F
	.string "You weren't led astray by our aroma…$"

Route103_Text_2949B4: @ 82949B4
	.string "Aromatherapy is a form of mental\n"
	.string "healing that works with fragrances.$"

Route103_Text_2949F9: @ 82949F9
	.string "AMY: I'm AMY.\n"
	.string "And this is my little sister LIV.\l"
	.string "We battle together!$"

Route103_Text_294A3D: @ 8294A3D
	.string "AMY: Uh-oh, we lost.$"

Route103_Text_294A52: @ 8294A52
	.string "AMY: You have to think about all\n"
	.string "kinds of things when you're battling\l"
	.string "against two TRAINERS.$"

Route103_Text_294AAE: @ 8294AAE
	.string "AMY: Uh-oh, you have only one\n"
	.string "POKéMON with you.\l"
	.string "You can't battle us like that.$"

Route103_Text_294AFD: @ 8294AFD
	.string "LIV: We battle together as one\n"
	.string "team.$"

Route103_Text_294B22: @ 8294B22
	.string "LIV: Oh, we lost, big sister…$"

Route103_Text_294B40: @ 8294B40
	.string "LIV: We work perfectly together,\n"
	.string "me and my big sister…\p"
	.string "But we still lost…$"

Route103_Text_294B8A: @ 8294B8A
	.string "LIV: Really, we're a lot better…\n"
	.string "It's true! We'll show you next time!$"

Route103_Text_294BD0: @ 8294BD0
	.string "LIV: If you want to battle us,\n"
	.string "you have to have two POKéMON!\l"
	.string "It's not fair if you don't!$"

Route103_Text_294C29: @ 8294C29
	.string "AMY: I'm AMY.\n"
	.string "And this is my little sister LIV.\l"
	.string "We battle together!$"

Route103_Text_294C6D: @ 8294C6D
	.string "AMY: Aww, boo!\n"
	.string "We couldn't win again…$"

Route103_Text_294C93: @ 8294C93
	.string "AMY: You have to think about all\n"
	.string "kinds of things when you're battling\l"
	.string "against two TRAINERS.$"

Route103_Text_294CEF: @ 8294CEF
	.string "AMY: Uh-oh, you have only one\n"
	.string "POKéMON with you.\l"
	.string "You can't battle us like that.$"

Route103_Text_294D3E: @ 8294D3E
	.string "LIV: We battle together as one\n"
	.string "team.$"

Route103_Text_294D63: @ 8294D63
	.string "LIV: Awww, we lost again…\n"
	.string "Big sister…$"

Route103_Text_294D89: @ 8294D89
	.string "LIV: We work perfectly together,\n"
	.string "me and my big sister…\p"
	.string "But why did we lose again?$"

Route103_Text_294DDB: @ 8294DDB
	.string "LIV: If you want to battle us, you\n"
	.string "have to have two POKéMON!\l"
	.string "It's not fair if you don't!$"

Route103_Text_294E34: @ 8294E34
	.string "Gah! My fishing line's all snarled up!\n"
	.string "I'm getting frustrated and mean!\l"
	.string "That's it! Battle me!$"

Route103_Text_294E92: @ 8294E92
	.string "Gah! Lost it!\n"
	.string "I'm even more annoyed now!$"

Route103_Text_294EBB: @ 8294EBB
	.string "Gah, I'm still boiling mad…\n"
	.string "Grrrrr…$"

Route103_Text_294EDF: @ 8294EDF
	.string "My POKéMON is delightfully adorable!\n"
	.string "Don't be shy--I'll show you!$"

Route103_Text_294F21: @ 8294F21
	.string "Oh, my gosh!\n"
	.string "My darling POKéMON!$"

Route103_Text_294F42: @ 8294F42
	.string "My delightful POKéMON looks darling\n"
	.string "even when it's fainted!$"

Route103_Text_294F7E: @ 8294F7E
	.string "I'll get you to come out and look in\n"
	.string "on my delightful POKéMON again!$"

Route103_Text_294FC3: @ 8294FC3
	.string "Hi, you! My delightfully adorable\n"
	.string "POKéMON has become more darling!$"

Route103_Text_295006: @ 8295006
	.string "Oh!\n"
	.string "My darling POKéMON!$"

Route103_Text_29501E: @ 829501E
	.string "The more I spend time with it,\n"
	.string "the more adorable my POKéMON becomes.$"

Route103_Text_295063: @ 8295063
	.string "This sort of distance…\n"
	.string "You should just swim it!$"

Route103_Text_295093: @ 8295093
	.string "Oh, that's good going!$"

Route103_Text_2950AA: @ 82950AA
	.string "Oh, I understand where you're coming\n"
	.string "from now.\p"
	.string "If I had a POKéMON that trusty,\n"
	.string "I'd want to SURF on it, too!$"

Route103_Text_295116: @ 8295116
	.string "Watch where you're going!\n"
	.string "We're going to crash!$"

Route103_Text_295146: @ 8295146
	.string "Groan…$"

Route103_Text_29514D: @ 829514D
	.string "I'm a poor swimmer so I was practicing…\n"
	.string "Sorry for almost crashing into you.$"

Route103_Text_295199: @ 8295199
	.string "Whoa!\n"
	.string "How'd you get into a space this small?$"

Route103_Text_2951C6: @ 82951C6
	.string "Whoa!\n"
	.string "The kid can rock!$"

Route103_Text_2951DE: @ 82951DE
	.string "Do you like cramped quarters\n"
	.string "like this?$"

Route103_Text_295206: @ 8295206
	.string "Did my guitar's wailing draw you in?$"

Route103_Text_29522B: @ 829522B
	.string "My one-man show is ruined…$"

Route103_Text_295246: @ 8295246
	.string "I was playing my guitar where few\n"
	.string "people were around, but a lot of fans\l"
	.string "have gathered.\p"
	.string "Heh, maybe I should turn pro.$"

Route104_Text_2952BB: @ 82952BB
	.string "GINA: Okay, let's battle with our\n"
	.string "POKéMON!$"

Route104_Text_2952E6: @ 82952E6
	.string "GINA: Losing upsets me!$"

Route104_Text_2952FE: @ 82952FE
	.string "GINA: You are strong!\n"
	.string "We have to train lots more!$"

Route104_Text_295330: @ 8295330
	.string "GINA: Oh? Only one POKéMON?\n"
	.string "Then, we don't battle with you.\p"
	.string "If there's only one POKéMON, it will\n"
	.string "be lonesome. That's not nice.$"

Route104_Text_2953AF: @ 82953AF
	.string "MIA: We are twins, so we battle\n"
	.string "POKéMON together.$"

Route104_Text_2953E1: @ 82953E1
	.string "MIA: We battled together, but we\n"
	.string "both lost…$"

Route104_Text_29540D: @ 829540D
	.string "MIA: We will train our POKéMON more\n"
	.string "and be strong like you.$"

Route104_Text_295449: @ 8295449
	.string "MIA: You want to battle with us?\p"
	.string "It's a big no-no if you don't have two\n"
	.string "POKéMON with you.\l"
	.string "We're too strong for you!$"

Route104_Text_2954BD: @ 82954BD
	.string "Why keep it a secret?\n"
	.string "I'm the WATER POKéMON expert!\p"
	.string "Huh?\n"
	.string "You don't know me?$"

Route104_Text_295509: @ 8295509
	.string "I thought I wasn't too bad, if I may\n"
	.string "say so, but I guess not… Bleah…$"

Route104_Text_29554E: @ 829554E
	.string "I got too into fishing.\n"
	.string "I forgot I had to raise my POKéMON…$"

Route104_Text_29558A: @ 829558A
	.string "Leaving footprints in the sand is\n"
	.string "so fun!$"

Route104_Text_2955B4: @ 82955B4
	.string "Waah! I got sand in my runners!\n"
	.string "They're all gritty!$"

Route104_Text_2955E8: @ 82955E8
	.string "I want to leave my footprints in\n"
	.string "the sand everywhere, but they\l"
	.string "disappear quickly…$"

Route104_Text_29563A: @ 829563A
	.string "Should I…\n"
	.string "Or shouldn't I?\p"
	.string "Okay, sure, I will battle!$"

Route104_Text_29566F: @ 829566F
	.string "I shouldn't have battled…$"

Route104_Text_295689: @ 8295689
	.string "If you're faced with a decision and\n"
	.string "you let someone else choose for you,\l"
	.string "you will regret it, however things\l"
	.string "turn out.$"

Route104_Text_2956FF: @ 82956FF
	.string "You're strong, but should I register\n"
	.string "you in my POKéNAV?\l"
	.string "Maybe I shouldn't…\p"
	.string "Okay, sure, I will register you!$"

Route104_Text_29576B: @ 829576B
	.string "You're strong, but should I register\n"
	.string "you in my POKéNAV?\l"
	.string "Maybe I shouldn't…\p"
	.string "Okay, sure, I will register you!$"

Route104_Text_2957D7: @ 82957D7
	.string "Come on, battle with me!$"

Route104_Text_2957F0: @ 82957F0
	.string "Ohh…\n"
	.string "I thought I could win…$"

Route104_Text_29580C: @ 829580C
	.string "I made the decision to battle, so\n"
	.string "I can accept this loss with grace.\p"
	.string "I am still upset about losing!$"

Route104_Text_295870: @ 8295870
	.string "Oh, sure, I'll accept your challenge.\n"
	.string "I have a lot of money.$"

Route104_Text_2958AD: @ 82958AD
	.string "Why couldn't I win?$"

Route104_Text_2958C1: @ 82958C1
	.string "There are some things money can't buy.\n"
	.string "That's POKéMON…$"

Route104_Text_2958F8: @ 82958F8
	.string "Hm?\n"
	.string "Ah, you've obtained a POKéNAV.\p"
	.string "I will gladly register you.\n"
	.string "After all, I have plenty of money.$"

Route104_Text_29595A: @ 829595A
	.string "Hm?\n"
	.string "Ah, you've obtained a POKéNAV.\p"
	.string "I will gladly register you.\n"
	.string "After all, I have plenty of money.$"

Route104_Text_2959BC: @ 82959BC
	.string "After I lost to you, I learned a bunch\n"
	.string "of things about POKéMON.$"

Route104_Text_2959FC: @ 82959FC
	.string "I lost again?\n"
	.string "Why couldn't I win?$"

Route104_Text_295A1E: @ 8295A1E
	.string "I'm fabulously wealthy, but I can't\n"
	.string "seem to win at POKéMON…\p"
	.string "It's so deep, the world of POKéMON…$"

Route104_Text_295A7E: @ 8295A7E
	.string "We must have been fated to meet.\n"
	.string "May I ask you for a battle?$"

Route104_Text_295ABB: @ 8295ABB
	.string "Oh, my!$"

Route104_Text_295AC3: @ 8295AC3
	.string "“Hello” is the beginning of “good-bye.”\n"
	.string "I hope we meet again.$"

Route104_Text_295B01: @ 8295B01
	.string "Hello, we meet again.\p"
	.string "We seem to be drawn together. Let's\n"
	.string "register each other in our POKéNAVS.$"

Route104_Text_295B60: @ 8295B60
	.string "We should commemorate how we seem\n"
	.string "to be drawn to each other.\p"
	.string "Let's register each other in our\n"
	.string "POKéNAVS.$"

Route104_Text_295BC8: @ 8295BC8
	.string "Hello, we meet again.\n"
	.string "May I ask you for a battle?$"

Route104_Text_295BFA: @ 8295BFA
	.string "Oh, my…\n"
	.string "I did the best that I could…$"

Route104_Text_295C1F: @ 8295C1F
	.string "“Hello” is the beginning of “good-bye.”\n"
	.string "I hope we meet again.$"

Route104_Text_295C5D: @ 8295C5D
	.string "I fished up a tough-looking POKéMON!\p"
	.string "It has this magical quality to it!\n"
	.string "It surely looks tough, yes it does!$"

Route104_Text_295CC9: @ 8295CC9
	.string "What the…$"

Route104_Text_295CD3: @ 8295CD3
	.string "Hey, MAGIKARP, you sure don't live up\n"
	.string "to your name, do you?$"

Route105_Text_295D0F: @ 8295D0F
	.string "There's supposed to be a mystical\n"
	.string "rock around here.\l"
	.string "Do you know anything about it?$"

Route105_Text_295D62: @ 8295D62
	.string "I was thinking too much about that\n"
	.string "rock, while my POKéMON remained weak…$"

Route105_Text_295DAB: @ 8295DAB
	.string "I can spend hours and hours staring\n"
	.string "at a nice rock without growing bored.$"

Route105_Text_295DF5: @ 8295DF5
	.string "Whew! I was worried that a kid was\n"
	.string "drowning when I saw you.\p"
	.string "You seem to be okay, so what do you\n"
	.string "say to a battle?$"

Route105_Text_295E66: @ 8295E66
	.string "Glub… Glub…$"

Route105_Text_295E72: @ 8295E72
	.string "If you are drowning, the signal is to\n"
	.string "wave one arm toward the beach.$"

Route105_Text_295EB7: @ 8295EB7
	.string "Swimming the deep blue sea…\n"
	.string "It feels the greatest!$"

Route105_Text_295EEA: @ 8295EEA
	.string "I lost…\n"
	.string "Now I'm feeling blue…$"

Route105_Text_295F08: @ 8295F08
	.string "Why is the sea blue?\p"
	.string "I learned about that at the MUSEUM in\n"
	.string "SLATEPORT, but I forgot.$"

Route105_Text_295F5C: @ 8295F5C
	.string "My body feels lighter in the water.\n"
	.string "It's as if I've gotten slimmer!$"

Route105_Text_295FA0: @ 8295FA0
	.string "I'm floating…$"

Route105_Text_295FAE: @ 8295FAE
	.string "Your body weight is reduced to just\n"
	.string "one tenth in the water.\p"
	.string "That would make me…\n"
	.string "Whoops! I'm not telling you my weight!$"

Route105_Text_296025: @ 8296025
	.string "The blue, blue sky…\n"
	.string "The vast sea…\l"
	.string "It's so peaceful…$"

Route105_Text_296059: @ 8296059
	.string "I lost while I was lounging!$"

Route105_Text_296076: @ 8296076
	.string "I want to be told I'm relaxing to be\n"
	.string "with. Giggle.$"

Route105_Text_2960A9: @ 82960A9
	.string "I'm convinced that the sea keeps\n"
	.string "secrets from us.$"

Route105_Text_2960DB: @ 82960DB
	.string "Yes…\n"
	.string "I am no good at battling…$"

Route105_Text_2960FA: @ 82960FA
	.string "I'm sure there are many secrets to be\n"
	.string "discovered in the world's seas.\p"
	.string "I mean to find them all!$"

Route105_Text_296159: @ 8296159
	.string "Huh? I'm so weak, but you're willing\n"
	.string "to register me in your POKéNAV?$"

Route105_Text_29619E: @ 829619E
	.string "I've told you that I'm weak…\n"
	.string "Are you sure you want to do this?$"

Route105_Text_2961DD: @ 82961DD
	.string "Yes…\n"
	.string "I didn't think I could win.$"

Route105_Text_2961FE: @ 82961FE
	.string "I may be weak at battling, but my\n"
	.string "drive to explore can't be bested.\p"
	.string "I will travel the seas all around\n"
	.string "the world!$"

Route105_Text_29626F: @ 829626F
	.string "I'm exhausted from swimming.\n"
	.string "I'm just not used to it.\p"
	.string "I need a battle for a change of pace!$"

Route105_Text_2962CB: @ 82962CB
	.string "I lost because I battled at sea.$"

Route105_Text_2962EC: @ 82962EC
	.string "Yeah, for me, the sky is a much better\n"
	.string "match than the sea.$"

Route106_Text_296327: @ 8296327
	.string "Which do you prefer, fishing in the\n"
	.string "sea or a stream?$"

Route106_Text_29635C: @ 829635C
	.string "Like in deep-sea fishing, I lost\n"
	.string "spectacularly!$"

Route106_Text_29638C: @ 829638C
	.string "Fishing is the greatest whether it's\n"
	.string "in the sea or a stream.\l"
	.string "You agree with me, right?$"

Route106_Text_2963E3: @ 82963E3
	.string "Fishing's great, but so is battling.\n"
	.string "If you don't mind, can we meet again?$"

Route106_Text_29642E: @ 829642E
	.string "I caught a bunch of POKéMON fishing.\n"
	.string "I'll show you an impressive battle!$"

Route106_Text_296477: @ 8296477
	.string "I lost again spectacularly!$"

Route106_Text_296493: @ 8296493
	.string "Win or lose, POKéMON are the greatest!\n"
	.string "You agree with me, right?$"

Route106_Text_2964D4: @ 82964D4
	.string "What do people do if they need to go\n"
	.string "to a washroom?\p"
	.string "What if my ROD hooks a big one while\n"
	.string "I'm in the washroom? I just can't go…$"

Route106_Text_296553: @ 8296553
	.string "I lost because I'm trying to not go\n"
	.string "to the washroom…$"

Route106_Text_296588: @ 8296588
	.string "Oh, no! I've got this feeling I'll hook\n"
	.string "a big one!$"

Route106_Text_2965BB: @ 82965BB
	.string "Hahahah! I'm a lousy runner, but in\n"
	.string "the water you can't catch me!$"

Route106_Text_2965FD: @ 82965FD
	.string "I give up!$"

Route106_Text_296608: @ 8296608
	.string "I wouldn't lose in a swim race…$"

Route106_Text_296628: @ 8296628
	.string "The sea is my backyard. I'm not going\n"
	.string "to take it easy because you're a kid!$"

Route106_Text_296674: @ 8296674
	.string "Did you take it easy on me by any\n"
	.string "chance?$"

Route106_Text_29669E: @ 829669E
	.string "Drifting along with the waves…\n"
	.string "I love it! Why don't you give it a try?$"

Route107_Text_2966E5: @ 82966E5
	.string "Yawn…\p"
	.string "I must have drifted off to sleep while\n"
	.string "I was drifting in the waves.$"

Route107_Text_29672F: @ 829672F
	.string "Ahaha, I lost…\n"
	.string "I'll take a snooze, I think…$"

Route107_Text_29675B: @ 829675B
	.string "Floating and being rocked by\n"
	.string "the waves--it's like sleeping in\l"
	.string "a plush, comfy bed.$"

Route107_Text_2967AD: @ 82967AD
	.string "The sea is like my backyard.\n"
	.string "Let's battle!$"

Route107_Text_2967D8: @ 82967D8
	.string "I lost on my home field…\n"
	.string "I'm in shock!$"

Route107_Text_2967FF: @ 82967FF
	.string "I swim the seas with a heart full of\n"
	.string "dreams…\p"
	.string "It's a song!\n"
	.string "Anyways, I'm swimming some more.$"

Route107_Text_29685A: @ 829685A
	.string "You've shocked me to the bone!\n"
	.string "Well, so you won't forget me…$"

Route107_Text_296897: @ 8296897
	.string "Swimming in the big, wide sea,\n"
	.string "my POKéMON has grown stronger!$"

Route107_Text_2968D5: @ 82968D5
	.string "What a shock!\p"
	.string "My POKéMON has gotten stronger, but\n"
	.string "I stayed weak as a TRAINER!$"

Route107_Text_296923: @ 8296923
	.string "What you learn in battle makes you\n"
	.string "a stronger TRAINER.\l"
	.string "The waves taught me that.$"

Route107_Text_296974: @ 8296974
	.string "Do you know a little town called\n"
	.string "DEWFORD?$"

Route107_Text_29699E: @ 829699E
	.string "I hate this!$"

Route107_Text_2969AB: @ 82969AB
	.string "A weird saying is getting really\n"
	.string "trendy at DEWFORD HALL.$"

Route107_Text_2969E4: @ 82969E4
	.string "Did you want to battle me?\n"
	.string "Sure, I'll go with you!$"

Route107_Text_296A17: @ 8296A17
	.string "I wasn't good enough for you.$"

Route107_Text_296A35: @ 8296A35
	.string "I think you're going to keep getting\n"
	.string "better. I'll go for it, too!$"

Route107_Text_296A77: @ 8296A77
	.string "LISA: We challenge you as a sister\n"
	.string "and brother!$"

Route107_Text_296AA7: @ 8296AA7
	.string "LISA: Awesome.\n"
	.string "You're in a different class of tough.$"

Route107_Text_296ADC: @ 8296ADC
	.string "LISA: Do you have any friends who\n"
	.string "would go to the beach with you?$"

Route107_Text_296B1E: @ 8296B1E
	.string "LISA: If you want to battle with us,\n"
	.string "bring more POKéMON.$"

Route107_Text_296B57: @ 8296B57
	.string "RAY: We always battle POKéMON,\n"
	.string "me and my sister.\p"
	.string "I always lose, but we can beat you\n"
	.string "2-on-2!$"

Route107_Text_296BB3: @ 8296BB3
	.string "RAY: Wowee, you're at a higher level\n"
	.string "than us!$"

Route107_Text_296BE1: @ 8296BE1
	.string "RAY: My sister gave me my POKéMON.\n"
	.string "I raised it, and now it's my important\l"
	.string "partner!$"

Route107_Text_296C34: @ 8296C34
	.string "RAY: If you want to battle us,\n"
	.string "go bring some more POKéMON!$"

Route107_Text_296C6F: @ 8296C6F
	.string "I'm in the middle of a triathlon,\n"
	.string "but I'm nowhere near tired!$"

Route107_Text_296CAD: @ 8296CAD
	.string "That exhausted me…$"

Route107_Text_296CC0: @ 8296CC0
	.string "I still have swimming and running left\n"
	.string "to do after this.\p"
	.string "Am I going to be okay?$"

Route108_Text_296D10: @ 8296D10
	.string "My dream is to swim the world's seven\n"
	.string "seas!$"

Route108_Text_296D3C: @ 8296D3C
	.string "I won't be able to swim the seven seas\n"
	.string "like this…$"

Route108_Text_296D6E: @ 8296D6E
	.string "Playing with marine POKéMON is one of\n"
	.string "the pleasures of swimming!$"

Route108_Text_296DAF: @ 8296DAF
	.string "Ahoy, there! Are you going out to\n"
	.string "the ABANDONED SHIP, too?$"

Route108_Text_296DEA: @ 8296DEA
	.string "I'm sinking!\n"
	.string "Glub… Glub…$"

Route108_Text_296E03: @ 8296E03
	.string "Some people even go inside that\n"
	.string "ABANDONED SHIP.$"

Route108_Text_296E33: @ 8296E33
	.string "My liar of a boyfriend told me that\n"
	.string "I look great in a bikini…$"

Route108_Text_296E71: @ 8296E71
	.string "Oh, boo!$"

Route108_Text_296E7A: @ 8296E7A
	.string "Even if it's a lie, I love being told\n"
	.string "I look great…\l"
	.string "We girls are so complex…$"

Route108_Text_296EC7: @ 8296EC7
	.string "I love the sea!\n"
	.string "I forget all my worries when I swim!$"

Route108_Text_296EFC: @ 8296EFC
	.string "When I lose a battle, I get all\n"
	.string "stressed out!$"

Route108_Text_296F2A: @ 8296F2A
	.string "Work off your stress by swimming!\n"
	.string "It's so healthy!$"

Route108_Text_296F5D: @ 8296F5D
	.string "I love WATER-type POKéMON.\n"
	.string "I love other POKéMON, too!$"

Route108_Text_296F93: @ 8296F93
	.string "Waaah! I lost!\n"
	.string "Waaah! Waaah!$"

Route108_Text_296FB0: @ 8296FB0
	.string "Shouting is good for me!\n"
	.string "It uplifts me!$"

Route108_Text_296FD8: @ 8296FD8
	.string "I love tough TRAINERS, too!\n"
	.string "Register me in your POKéNAV!$"

Route108_Text_297011: @ 8297011
	.string "Win or lose, I love battling at sea!$"

Route108_Text_297036: @ 8297036
	.string "Waaah! I lost again!\n"
	.string "Waaah! Waaah!$"

Route108_Text_297059: @ 8297059
	.string "If you're faced with a challenge,\n"
	.string "try shouting at the sea!$"

Route108_Text_297094: @ 8297094
	.string "I take huge pride in my POKéMON.\n"
	.string "We'll show you one speedy battle!$"

Route108_Text_2970D7: @ 82970D7
	.string "That wasn't cute at all.$"

Route108_Text_2970F0: @ 82970F0
	.string "Since I'm at sea like this, I wouldn't\n"
	.string "mind putting on a pink, frilly swimsuit…$"

Route109_Text_297140: @ 8297140
	.string "Hiyah! Look at my chiseled abs!\n"
	.string "This is what you call “cut”!$"

Route109_Text_29717D: @ 829717D
	.string "Aiyah!\n"
	.string "Flubbed out!$"

Route109_Text_297191: @ 8297191
	.string "Hiyah!\p"
	.string "My sculpted abs have nothing to do\n"
	.string "with POKéMON battles!$"

Route109_Text_2971D1: @ 82971D1
	.string "Are you properly protected against\n"
	.string "the sun?$"

Route109_Text_2971FD: @ 82971FD
	.string "Ouch, ouch, ouch!$"

Route109_Text_29720F: @ 829720F
	.string "Cheeks are the most prone to burning!$"

Route109_Text_297235: @ 8297235
	.string "I've laid anchor in ports around\n"
	.string "the world, but SLATEPORT's the best.$"

Route109_Text_29727B: @ 829727B
	.string "You're the best!$"

Route109_Text_29728C: @ 829728C
	.string "In the best port was the best\n"
	.string "TRAINER…$"

Route109_Text_2972B3: @ 82972B3
	.string "Urrrrppp…\n"
	.string "Battle? With me?$"

Route109_Text_2972CE: @ 82972CE
	.string "Urp… Ooooooohhhhhh…\n"
	.string "Urrrrpppp…$"

Route109_Text_2972ED: @ 82972ED
	.string "I'm usually stronger than this!\n"
	.string "I'm just seasick as a dog!\p"
	.string "I'm a SAILOR, but…$"

Route109_Text_29733B: @ 829733B
	.string "I'm thirsty… I could go for a SODA POP\n"
	.string "at the SEASHORE HOUSE…$"

Route109_Text_297379: @ 8297379
	.string "Groan…$"

Route109_Text_297380: @ 8297380
	.string "I'm getting famished… My inner tube\n"
	.string "looks like a giant doughnut…$"

Route109_Text_2973C1: @ 82973C1
	.string "Will you have another match with me\n"
	.string "when I'm not all thirsty?$"

Route109_Text_2973FF: @ 82973FF
	.string "I'm hungry, but I've got enough pep in\n"
	.string "me for a battle!$"

Route109_Text_297437: @ 8297437
	.string "I lost…\n"
	.string "It's because I'm hungry…$"

Route109_Text_297458: @ 8297458
	.string "When you eat on a beach, everything\n"
	.string "seems to taste a little better.$"

Route109_Text_29749C: @ 829749C
	.string "Doesn't a beach umbrella look like\n"
	.string "a giant flower?$"

Route109_Text_2974CF: @ 82974CF
	.string "Mommy!$"

Route109_Text_2974D6: @ 82974D6
	.string "If you look at the beach from the sky,\n"
	.string "it looks like a big flower garden!$"

Route109_Text_297520: @ 8297520
	.string "Me?\n"
	.string "I'm here every day!$"

Route109_Text_297538: @ 8297538
	.string "I'm not losing to you again!\n"
	.string "That's why I have my inner tube!$"

Route109_Text_297576: @ 8297576
	.string "Mommy!$"

Route109_Text_29757D: @ 829757D
	.string "If I have an inner tube, me and my\n"
	.string "POKéMON's cuteness goes way up!$"

Route109_Text_2975C0: @ 82975C0
	.string "I can't swim without my inner tube,\n"
	.string "but I won't lose at POKéMON!$"

Route109_Text_297601: @ 8297601
	.string "Did I lose because I have an inner\n"
	.string "tube?$"

Route109_Text_29762A: @ 829762A
	.string "My inner tube is a fashion item.\n"
	.string "I can't be seen without it.$"

Route109_Text_297667: @ 8297667
	.string "Hi, big TRAINER.\n"
	.string "Will you battle with me?$"

Route109_Text_297691: @ 8297691
	.string "Oh, you're strong.$"

Route109_Text_2976A4: @ 82976A4
	.string "How did you get to be so strong?$"

Route109_Text_2976C5: @ 82976C5
	.string "Wahahah! This dude's going to catch\n"
	.string "himself a big one!$"

Route109_Text_2976FC: @ 82976FC
	.string "This dude just lost one…$"

Route109_Text_297715: @ 8297715
	.string "This dude thinks you're a big one.\n"
	.string "No, you're a big-one-to-be!$"

Route109_Text_297754: @ 8297754
	.string "PAUL: Well, this is a mood-breaker.\p"
	.string "I wish you wouldn't disturb our\n"
	.string "precious time together.$"

Route109_Text_2977B0: @ 82977B0
	.string "PAUL: Well, I give up.$"

Route109_Text_2977C7: @ 82977C7
	.string "PAUL: Well, don't tell anyone that\n"
	.string "we're here.\l"
	.string "This is just our private world of two!$"

Route109_Text_29781D: @ 829781D
	.string "PAUL: We're totally, deeply in love.\n"
	.string "That's why we make our POKéMON battle\l"
	.string "together.$"

Route109_Text_297872: @ 8297872
	.string "MEL: We're, like, totally in love.\n"
	.string "Our romance is heating up all of HOENN!$"

Route109_Text_2978BD: @ 82978BD
	.string "MEL: We lost, and it's my fault!\n"
	.string "PAUL will hate me!$"

Route109_Text_2978F1: @ 82978F1
	.string "MEL: Um, PAUL, are you angry with me?\n"
	.string "Please don't be angry.$"

Route109_Text_29792E: @ 829792E
	.string "MEL: We're, like, deeply and truly in love.\n"
	.string "That's why we make our POKéMON\l"
	.string "battle together.$"

Route109_Text_29798A: @ 829798A
	.string "Tadaah! See?\n"
	.string "My inner tube's round!$"

Route109_Text_2979AE: @ 82979AE
	.string "Oh, oh!\n"
	.string "Too bad!$"

Route109_Text_2979BF: @ 82979BF
	.string "After I showed you my round inner\n"
	.string "tube, too…$"

Route109_Text_2979EC: @ 82979EC
	.string "I can't swim, so I'm pretending\n"
	.string "to swim.$"

Route109_Text_297A15: @ 8297A15
	.string "I thought so!\n"
	.string "I didn't think we could win.$"

Route109_Text_297A40: @ 8297A40
	.string "When I learn how to swim, I think\n"
	.string "my POKéMON will become tougher.$"

Route109_Text_297A82: @ 8297A82
	.string "For a guy as macho as me, this kind\n"
	.string "of POKéMON is the perfect match!$"

Route109_Text_297AC7: @ 8297AC7
	.string "I'm cool even in defeat, hey?$"

Route109_Text_297AE5: @ 8297AE5
	.string "For a guy as macho as me, a port\n"
	.string "is the perfect setting!\p"
	.string "I guess I'll head for SLATEPORT.$"

Route110_Text_297B3F: @ 8297B3F
	.string "Whoa! Watch it!\n"
	.string "I guess you're not used to BIKE racing.$"

Route110_Text_297B77: @ 8297B77
	.string "Whoa!\n"
	.string "My brakes failed!$"

Route110_Text_297B8F: @ 8297B8F
	.string "Flat tires and brake problems can\n"
	.string "cause serious injury!\l"
	.string "Inspect your BIKE for problems!$"

Route110_Text_297BE7: @ 8297BE7
	.string "Yo, you!\n"
	.string "Can you keep up with my speed?$"

Route110_Text_297C0F: @ 8297C0F
	.string "Crash and burn!$"

Route110_Text_297C1F: @ 8297C1F
	.string "Speed alone won't let me win at POKéMON.\n"
	.string "I need to reconsider this…$"

Route110_Text_297C63: @ 8297C63
	.string "Don't panic if your BIKE's going fast!$"

Route110_Text_297C8A: @ 8297C8A
	.string "I shouldn't panic during POKéMON\n"
	.string "battles…$"

Route110_Text_297CB4: @ 8297CB4
	.string "There's no need to panic or stress.\n"
	.string "Take it easy. There's plenty of time.$"

Route110_Text_297CFE: @ 8297CFE
	.string "I'll keep chugging on without stressing.\n"
	.string "Give me a shout if you're up to it.$"

Route110_Text_297D4B: @ 8297D4B
	.string "Aren't you going a little too fast?\n"
	.string "Take it easy and let's battle.$"

Route110_Text_297D8E: @ 8297D8E
	.string "I didn't panic, but I still lost…$"

Route110_Text_297DB0: @ 8297DB0
	.string "There's no need to panic or stress.\n"
	.string "Take it easy. There's plenty of time.$"

Route110_Text_297DFA: @ 8297DFA
	.string "The triathlon is hard in the extreme.\p"
	.string "You have to complete the three events\n"
	.string "of swimming, cycling, and running.$"

Route110_Text_297E69: @ 8297E69
	.string "POKéMON battles are hard, too!$"

Route110_Text_297E88: @ 8297E88
	.string "I'm exhausted, so I need a break.\n"
	.string "It's important to get proper rest.$"

Route110_Text_297ECD: @ 8297ECD
	.string "You know, I like you!\n"
	.string "Let's have a rematch on CYCLING ROAD.$"

Route110_Text_297F09: @ 8297F09
	.string "Isn't it neat to hold a battle while\n"
	.string "cycling?$"

Route110_Text_297F37: @ 8297F37
	.string "Wow…\n"
	.string "How could you be so strong?$"

Route110_Text_297F58: @ 8297F58
	.string "Were you going after a record?\p"
	.string "I'm sorry if I held you up!$"

Route110_Text_297F93: @ 8297F93
	.string "I've been riding without stopping.\n"
	.string "My thighs are like rocks!$"

Route110_Text_297FD0: @ 8297FD0
	.string "I'm worried about muscle cramps…$"

Route110_Text_297FF1: @ 8297FF1
	.string "Oh, you have some GYM BADGES?\n"
	.string "No wonder you're so strong!$"

Route110_Text_29802B: @ 829802B
	.string "I have foreseen your intentions!\n"
	.string "I cannot possibly lose!$"

Route110_Text_298064: @ 8298064
	.string "I failed to prophesize my own demise!$"

Route110_Text_29808A: @ 829808A
	.string "I see your future…\p"
	.string "Hmm…\n"
	.string "I see a shining light…$"

Route110_Text_2980B9: @ 82980B9
	.string "Ahahahaha!\n"
	.string "I'll dazzle you with my wonders!$"

Route110_Text_2980E5: @ 82980E5
	.string "I wondrously lost!$"

Route110_Text_2980F8: @ 82980F8
	.string "You managed to win only because it was\n"
	.string "a wonder! Yes, a wonder!\l"
	.string "Don't think you can win all the time!$"

Route110_Text_29815E: @ 829815E
	.string "Could I see your POKéMON?\n"
	.string "Just one look, please?$"

Route110_Text_29818F: @ 829818F
	.string "I wanted to complete\n"
	.string "my collection…$"

Route110_Text_2981B3: @ 82981B3
	.string "When I see a POKéMON that I don't know,\n"
	.string "my passion as a collector is ignited!$"

Route110_Text_298201: @ 8298201
	.string "I like collecting MATCH CALL\n"
	.string "registrations, too…$"

Route110_Text_298232: @ 8298232
	.string "Hi, have you caught any new POKéMON?\p"
	.string "Could I see your POKéMON?\n"
	.string "Just one look, please?$"

Route110_Text_298288: @ 8298288
	.string "Your POKéMON…\n"
	.string "I envy you.$"

Route110_Text_2982A2: @ 82982A2
	.string "Oh, I long to make all rare POKéMON\n"
	.string "mine!$"

Route110_Text_2982CC: @ 82982CC
	.string "Hey!\n"
	.string "Don't sneak up behind me like that!$"

Route110_Text_2982F5: @ 82982F5
	.string "I lost!\n"
	.string "Drat!$"

Route110_Text_298303: @ 8298303
	.string "Fishing is all about concentration.\n"
	.string "You have to focus on the floater.$"

Route110_Text_298349: @ 8298349
	.string "Ahahaha! I would go anywhere to show\n"
	.string "off my delightful POKéMON.$"

Route110_Text_298389: @ 8298389
	.string "Oh, dear, this won't do.$"

Route110_Text_2983A2: @ 82983A2
	.string "Rather than battling, perhaps I should\n"
	.string "show off my POKéMON at the FAN CLUB.$"

Route110_Text_2983EE: @ 82983EE
	.string "That wasn't close to what I could\n"
	.string "do to show off my POKéMON.\p"
	.string "I'll have you as my captive audience\n"
	.string "as often as possible!$"

Route110_Text_298466: @ 8298466
	.string "Ahahahaha! I would be happy to show\n"
	.string "off my POKéMON as often as you like!$"

Route110_Text_2984AF: @ 82984AF
	.string "Oh, dear, this won't do.$"

Route110_Text_2984C8: @ 82984C8
	.string "I don't think that I could ever stop\n"
	.string "from showing off my POKéMON.\p"
	.string "But I like to battle, too!$"

Route110_Text_298525: @ 8298525
	.string "I found some cool POKéMON in the grass\n"
	.string "around here!$"

Route110_Text_298559: @ 8298559
	.string "Being cool isn't enough to win…$"

Route110_Text_298579: @ 8298579
	.string "It's hard to battle with POKéMON you\n"
	.string "just caught.$"

Route110_Text_2985AB: @ 82985AB
	.string "I fell off CYCLING ROAD…\p"
	.string "I'll get over my embarrassment by\n"
	.string "battling with you!$"

Route110_Text_2985F9: @ 82985F9
	.string "Oops!\n"
	.string "I ended up losing!$"

Route110_Text_298612: @ 8298612
	.string "Falling… Losing…\n"
	.string "This is so humiliating for me!$"

Route110_Text_298642: @ 8298642
	.string "Okay! Full-throttle time! If you can't\n"
	.string "groove, you get left behind!$"

Route110_Text_298686: @ 8298686
	.string "You got into the groove all right…$"

Route110_Text_2986A9: @ 82986A9
	.string "This isn't going to bring me down!\n"
	.string "Losing has made me a better man!$"

Route110_Text_2986ED: @ 82986ED
	.string "When cute POKéMON help each other…\n"
	.string "You won't see a more adorable sight!$"

Route110_Text_298735: @ 8298735
	.string "Have you no compassion or pity?$"

Route110_Text_298755: @ 8298755
	.string "Okay, okay, you've done the best you\n"
	.string "could, my pretties.$"

Route111_Text_29878E: @ 829878E
	.string "Oh, hey! Those GO-GOGGLES suit you.\n"
	.string "But I think they look better on me.\p"
	.string "Let's decide who they look better on\n"
	.string "with a battle!$"

Route111_Text_29880A: @ 829880A
	.string "I couldn't see what was happening at\n"
	.string "my sides because of the GO-GOGGLES.$"

Route111_Text_298853: @ 8298853
	.string "The GO-GOGGLES make it possible to\n"
	.string "get through sandstorms.\l"
	.string "That makes me happy!$"

Route111_Text_2988A3: @ 82988A3
	.string "I'm having a picnic in the desert.\p"
	.string "You can always find a TRAINER,\n"
	.string "so I can enjoy a battle here, too!$"

Route111_Text_298908: @ 8298908
	.string "Ohhh! You're mean!$"

Route111_Text_29891B: @ 829891B
	.string "When you're battling in a sandstorm,\n"
	.string "watch out for your POKéMON's HP.\p"
	.string "It can faint if you don't keep\n"
	.string "an eye on it!$"

Route111_Text_29898E: @ 829898E
	.string "Wearing these GO-GOGGLES makes me\n"
	.string "feel like a superhero.\l"
	.string "Right now, nobody can beat me!$"

Route111_Text_2989E6: @ 82989E6
	.string "I can't win on spirit alone…$"

Route111_Text_298A03: @ 8298A03
	.string "I'm going to be a real hero one day.\n"
	.string "I'm going to work harder to make me\l"
	.string "and my POKéMON stronger.$"

Route111_Text_298A65: @ 8298A65
	.string "I heard there are fossils to be found\n"
	.string "in the desert. Where could they be?$"

Route111_Text_298AAF: @ 8298AAF
	.string "I came up short…$"

Route111_Text_298AC0: @ 8298AC0
	.string "If they can find fossils in the desert,\n"
	.string "it must have been a sea before.$"

Route111_Text_298B08: @ 8298B08
	.string "For thirty years I have searched for\n"
	.string "ancient ruins!\l"
	.string "I am to be challenged?$"

Route111_Text_298B53: @ 8298B53
	.string "While I have searched for ruins,\n"
	.string "I've not searched for strong POKéMON.$"

Route111_Text_298B9A: @ 8298B9A
	.string "For thirty years I have searched for\n"
	.string "ancient ruins!\p"
	.string "No, wait, was that forty years?\n"
	.string "Which was it now?$"

Route111_Text_298C00: @ 8298C00
	.string "I haven't been searching for any\n"
	.string "tough POKéMON.\p"
	.string "But, for some reason, I sure do like\n"
	.string "POKéNAVS.$"

Route111_Text_298C5F: @ 8298C5F
	.string "For thirty years I have searched for\n"
	.string "ancient ruins!\p"
	.string "No, wait, was that forty years?\n"
	.string "Anyway, am I to be challenged?$"

Route111_Text_298CD2: @ 8298CD2
	.string "I've found no ruins, nor have I found\n"
	.string "any strong POKéMON…$"

Route111_Text_298D0C: @ 8298D0C
	.string "For thirty years I have searched for\n"
	.string "ancient ruins!\p"
	.string "No, wait, was that forty years\n"
	.string "I've searched?\p"
	.string "Hmm… It could even be fifty…\n"
	.string "How long have I been at this?$"

Route111_Text_298DA9: @ 8298DA9
	.string "I'm full of pep!\n"
	.string "And my POKéMON is peppy, too!$"

Route111_Text_298DD8: @ 8298DD8
	.string "My POKéMON lost its pep…$"

Route111_Text_298DF1: @ 8298DF1
	.string "When I see a TRAINER with a lot of pep,\n"
	.string "I can't help looking.$"

Route111_Text_298E2F: @ 8298E2F
	.string "I don't know where you're going,\n"
	.string "but would you like to battle?$"

Route111_Text_298E6E: @ 8298E6E
	.string "Oh, you're disgustingly good!$"

Route111_Text_298E8C: @ 8298E8C
	.string "I'm thinking that I should go to\n"
	.string "MT. CHIMNEY, but the view around\l"
	.string "here is very nice, too.$"

Route111_Text_298EE6: @ 8298EE6
	.string "To train myself, I challenge all\n"
	.string "whom I meet!$"

Route111_Text_298F14: @ 8298F14
	.string "Uncle! I give up!$"

Route111_Text_298F26: @ 8298F26
	.string "All I can do is keep training until\n"
	.string "I can defeat strong TRAINERS such\l"
	.string "as yourself.$"

Route111_Text_298F79: @ 8298F79
	.string "Show me how much you've toughened\n"
	.string "your POKéMON.$"

Route111_Text_298FA9: @ 8298FA9
	.string "I see, you've toughened them\n"
	.string "considerably.$"

Route111_Text_298FD4: @ 8298FD4
	.string "POKéMON and TRAINERS learn much\n"
	.string "through battling.\p"
	.string "What's important is to never give up\n"
	.string "even if you lose.$"

Route111_Text_29903D: @ 829903D
	.string "There is much to be learned from\n"
	.string "your training style.\p"
	.string "I request a rematch if it\n"
	.string "behooves you.$"

Route111_Text_29909B: @ 829909B
	.string "We're training here to elevate our\n"
	.string "game to the next level.\l"
	.string "Stay and train with us!$"

Route111_Text_2990EE: @ 82990EE
	.string "Ooh, you're decent!$"

Route111_Text_299102: @ 8299102
	.string "Since you're that strong, you should\n"
	.string "aim for the POKéMON LEAGUE.$"

Route111_Text_299143: @ 8299143
	.string "Oh, your POKéMON look like serious\n"
	.string "actors.\l"
	.string "I have to ask you for an engagement.$"

Route111_Text_299193: @ 8299193
	.string "They didn't just look strong,\n"
	.string "they are strong!$"

Route111_Text_2991C2: @ 82991C2
	.string "I thought I was raising my POKéMON\n"
	.string "diligently, but, oh no, there is still\l"
	.string "much to be done.$"

Route111_Text_29921D: @ 829921D
	.string "I wish I could become friends with\n"
	.string "more strong people like you!$"

Route111_Text_29925D: @ 829925D
	.string "You can make POKéMON stronger or\n"
	.string "weaker depending on the moves you\l"
	.string "teach them.\p"
	.string "What kinds of moves do your POKéMON\n"
	.string "know?$"

Route111_Text_2992D6: @ 82992D6
	.string "You've taught them good moves!$"

Route111_Text_2992F5: @ 82992F5
	.string "Maybe I should have stopped my\n"
	.string "POKéMON from evolving until they\l"
	.string "learned better moves…$"

Route111_Text_29934B: @ 829934B
	.string "I shouldn't have come to a place like\n"
	.string "this for a picnic!$"

Route111_Text_299384: @ 8299384
	.string "Aww!\n"
	.string "I really shouldn't have come!$"

Route111_Text_2993A7: @ 82993A7
	.string "In a sandstorm like this, I can't set\n"
	.string "the places for a picnic even with my\l"
	.string "GO-GOGGLES on…$"

Route111_Text_299401: @ 8299401
	.string "How tough are you?\n"
	.string "We shall expose that secret!$"

Route111_Text_299431: @ 8299431
	.string "Oh! Your strength!\n"
	.string "It is shrouded in mystery!$"

Route111_Text_29945F: @ 829945F
	.string "This desert hoards mysteries in\n"
	.string "its shifting sands!$"

Route111_Text_299493: @ 8299493
	.string "I'll give you some of my sandwich\n"
	.string "if you'll lose.$"

Route111_Text_2994C5: @ 82994C5
	.string "Tch! I thought a sandwich would be\n"
	.string "enough of a bribe…$"

Route111_Text_2994FB: @ 82994FB
	.string "My SANDSHREW loves eating\n"
	.string "my sandwiches.$"

Route111_Text_299524: @ 8299524
	.string "This is my favorite kind of POKéMON!$"

Route111_Text_299549: @ 8299549
	.string "Wait!\n"
	.string "Did you get a good look at my POKéMON?$"

Route111_Text_299576: @ 8299576
	.string "When having a battle, I get a kick out\n"
	.string "of showing off my POKéMON.\p"
	.string "I bet everyone feels that way when\n"
	.string "they enter a battle!$"

Route111_Text_2995F0: @ 82995F0
	.string "Show me how to put a little excitement\n"
	.string "into my life.$"

Route111_Text_299625: @ 8299625
	.string "Oh… My…\n"
	.string "That was too much excitement.$"

Route111_Text_29964B: @ 829964B
	.string "My pulse is still racing.\n"
	.string "You're one fabulous TRAINER.$"

Route111_Text_299682: @ 8299682
	.string "When you're as famished as I am,\n"
	.string "there is no room for pity!$"

Route111_Text_2996BE: @ 82996BE
	.string "Groan…$"

Route111_Text_2996C5: @ 82996C5
	.string "My stomach is grumbling!\n"
	.string "Maybe I can grill some BERRIES…$"

Route111_Text_2996FE: @ 82996FE
	.string "Did you come from MAUVILLE?\n"
	.string "Then you should be full of energy!$"

Route111_Text_29973D: @ 829973D
	.string "Ooh lala!\n"
	.string "That's a lot to take!$"

Route111_Text_29975D: @ 829975D
	.string "This road here…\n"
	.string "You have quite a ways to travel.$"

Route112_Text_29978E: @ 829978E
	.string "Hahahaha!\n"
	.string "How about we have a battle?\l"
	.string "You and me!\l"
	.string "Hahahaha!$"

Route112_Text_2997CA: @ 82997CA
	.string "I lost!\n"
	.string "Hahahaha!$"

Route112_Text_2997DC: @ 82997DC
	.string "Hahahahaha! Something flew up my nose!\n"
	.string "Hahahaha-hatchoo!$"

Route112_Text_299815: @ 8299815
	.string "My legs are solid from pounding up\n"
	.string "and down the mountains.\p"
	.string "They're not going to buckle easily,\n"
	.string "friend!$"

Route112_Text_29987C: @ 829987C
	.string "Ouch! My legs cramped up!$"

Route112_Text_299896: @ 8299896
	.string "Try hiking, and I mean really\n"
	.string "pounding, on these mountain trails\l"
	.string "with a heavy pack weighing dozens of\l"
	.string "pounds.\p"
	.string "That, my friend, will get your body\n"
	.string "into serious shape.$"

Route112_Text_29993C: @ 829993C
	.string "Ow, my legs have cramped up.\n"
	.string "Can you grab me some bandages from\l"
	.string "my backpack?\p"
	.string "No, that's my POKéNAV!\n"
	.string "Oh, fine, I'll register you.$"

Route112_Text_2999BD: @ 82999BD
	.string "I've been keeping fit by hiking.\n"
	.string "Power, I have in spades!$"

Route112_Text_2999F7: @ 82999F7
	.string "I got trumped in power?$"

Route112_Text_299A0F: @ 8299A0F
	.string "I hear there are some seriously tough\n"
	.string "TRAINERS on top of MT. CHIMNEY.\p"
	.string "I intend to get up there and give them\n"
	.string "a challenge!$"

Route112_Text_299A89: @ 8299A89
	.string "I'm strong.\n"
	.string "I won't cry if I lose.$"

Route112_Text_299AAC: @ 8299AAC
	.string "Waaaah!$"

Route112_Text_299AB4: @ 8299AB4
	.string "I'm not crying because I miss my mommy!\n"
	.string "Snivel…$"

Route112_Text_299AE4: @ 8299AE4
	.string "When you're out on a picnic, why,\n"
	.string "you simply have to sing!\l"
	.string "Come on, sing with me!$"

Route112_Text_299B36: @ 8299B36
	.string "Oh, you're so strong!$"

Route112_Text_299B4C: @ 8299B4C
	.string "It doesn't matter if you're good or bad\n"
	.string "at singing or POKéMON.\p"
	.string "If you have the most fun, you win!$"

Route112_Text_299BAE: @ 8299BAE
	.string "I caught hot POKéMON in FIERY PATH!\n"
	.string "Take a look!$"

Route112_Text_299BDF: @ 8299BDF
	.string "What a bumpy ride that was!$"

Route112_Text_299BFB: @ 8299BFB
	.string "I like the way you battle.\n"
	.string "It has a certain flair to it.$"

Route112_Text_299C34: @ 8299C34
	.string "Oh, aren't you an adorable TRAINER!\n"
	.string "Please, I need a romantic battle!\l"
	.string "I'm somewhat decent!$"

Route112_Text_299C8F: @ 8299C8F
	.string "Oh, how strong you are!\n"
	.string "You've given me quite a shock!$"

Route112_Text_299CC6: @ 8299CC6
	.string "Are you busy right now?\n"
	.string "I was thinking that maybe we can have\l"
	.string "a rematch right now…\l"
	.string "But it's all right if you're busy.$"

Route113_Text_299D3C: @ 8299D3C
	.string "Can you guess why it's so cool\n"
	.string "around here?$"

Route113_Text_299D68: @ 8299D68
	.string "Peeuuw!\n"
	.string "That stinks!$"

Route113_Text_299D7D: @ 8299D7D
	.string "The volcanic ash blocks the sun,\n"
	.string "so it doesn't get very warm.\p"
	.string "That's good for me--I can't stand heat!$"

Route113_Text_299DE3: @ 8299DE3
	.string "The volcano's eruption is proof that\n"
	.string "the earth is alive.$"

Route113_Text_299E1C: @ 8299E1C
	.string "You're some kind of strong!$"

Route113_Text_299E38: @ 8299E38
	.string "Ouch! Owww! I can't see!\n"
	.string "I got ashes in my eyelashes!\p"
	.string "Get it? Ashes and eyelashes?\p"
	.string "Okay, that was bad, sorry…$"

Route113_Text_299EA6: @ 8299EA6
	.string "I use this parasol to ward off this\n"
	.string "filthy, yucky volcanic ash from\l"
	.string "my dear NUMEL.$"

Route113_Text_299EF9: @ 8299EF9
	.string "Huff, huff…\n"
	.string "I am exhausted…$"

Route113_Text_299F15: @ 8299F15
	.string "You're very good at this.\n"
	.string "I must say I'm impressed!$"

Route113_Text_299F49: @ 8299F49
	.string "Here, slide under my parasol.\n"
	.string "Let me register you in my POKéNAV.$"

Route113_Text_299F8A: @ 8299F8A
	.string "Oh, hello, hasn't it been a while?\n"
	.string "May I invite you to battle?$"

Route113_Text_299FC9: @ 8299FC9
	.string "Oh, how super!$"

Route113_Text_299FD8: @ 8299FD8
	.string "You've remained very good at this.\n"
	.string "I must say I'm impressed!$"

Route113_Text_29A015: @ 829A015
	.string "From out of the ashes I leap! Hiyah!\n"
	.string "I challenge thee!$"

Route113_Text_29A04C: @ 829A04C
	.string "With honor I admit defeat!$"

Route113_Text_29A067: @ 829A067
	.string "I must refine the art of concealment.\n"
	.string "I bid thee farewell.$"

Route113_Text_29A0A2: @ 829A0A2
	.string "Yiiyaah! Witness the ancient ninja\n"
	.string "technique of POKéNAV registration!$"

Route113_Text_29A0E8: @ 829A0E8
	.string "From out of the ashes I leap! Hiyah!\n"
	.string "I challenge thee!$"

Route113_Text_29A11F: @ 829A11F
	.string "With honor I admit defeat!$"

Route113_Text_29A13A: @ 829A13A
	.string "My flawless concealment was let down\n"
	.string "by my immature battle skills…\p"
	.string "I bid thee farewell.$"

Route113_Text_29A192: @ 829A192
	.string "Thanks for finding me!\n"
	.string "But we still have to battle!$"

Route113_Text_29A1C6: @ 829A1C6
	.string "I'll use my ninjutsu on you…\n"
	.string "“VOLCANIC ASH SWIRL CLOAK”!\p"
	.string "…What?\n"
	.string "It's already over?$"

Route113_Text_29A219: @ 829A219
	.string "You know what's crummy about hiding?\n"
	.string "It's lonely if no one comes along.$"

Route113_Text_29A261: @ 829A261
	.string "TORI: Both of us, we collect ashes.\n"
	.string "We battle POKéMON, too.$"

Route113_Text_29A29D: @ 829A29D
	.string "TORI: We lost… It's boring, so I'm going\n"
	.string "to get some more ashes.$"

Route113_Text_29A2DE: @ 829A2DE
	.string "TORI: How much ash do we have?\n"
	.string "Enough for a WHITE FLUTE, I hope.$"

Route113_Text_29A31F: @ 829A31F
	.string "TORI: We want to battle 2-on-2.\n"
	.string "If we didn't, we would lose!$"

Route113_Text_29A35C: @ 829A35C
	.string "TIA: Both of us, we collect ashes.\n"
	.string "We battle POKéMON, too.$"

Route113_Text_29A397: @ 829A397
	.string "TIA: We couldn't win… It's boring,\n"
	.string "so I'm getting some more ashes.$"

Route113_Text_29A3DA: @ 829A3DA
	.string "TIA: We have a lot of ashes!\n"
	.string "I think enough for a WHITE FLUTE!$"

Route113_Text_29A419: @ 829A419
	.string "TIA: We want to battle 2-on-2.\n"
	.string "If we don't, we won't win!$"

Route113_Text_29A453: @ 829A453
	.string "Pfft, with these wings I can\n"
	.string "flick you away!$"

Route113_Text_29A480: @ 829A480
	.string "A… What?$"

Route113_Text_29A489: @ 829A489
	.string "I don't know what to say when I get\n"
	.string "beaten so easily…$"

Route113_Text_29A4BF: @ 829A4BF
	.string "The warmth here is making me drowsy.\n"
	.string "Battle with me so I can stay awake.$"

Route113_Text_29A508: @ 829A508
	.string "This is a dream.\n"
	.string "I'm sure of it…$"

Route113_Text_29A529: @ 829A529
	.string "Losing burns me up…\n"
	.string "I'm just going to sleep right here!\l"
	.string "Zzz!$"

Route113_Text_29A566: @ 829A566
	.string "Were you maybe in the middle\n"
	.string "of gathering volcanic ashes?$"

Route113_Text_29A5A0: @ 829A5A0
	.string "Ehehe.\n"
	.string "We got beaten cleanly.$"

Route113_Text_29A5BE: @ 829A5BE
	.string "I ought to hide under the ashes, too.$"

Route113_Text_29A5E4: @ 829A5E4
	.string "Y-you want to battle with me?\n"
	.string "Even though I just caught my POKéMON?$"

Route113_Text_29A628: @ 829A628
	.string "Y-you're all happy to win?\n"
	.string "Even though it's only me?$"

Route113_Text_29A65D: @ 829A65D
	.string "Oh, so now you want to say a word to\n"
	.string "the loser?\p"
	.string "Aren't you just the coolest?\n"
	.string "Humph!$"

Route114_Text_29A6B1: @ 829A6B1
	.string "Yodelayhihoo!\p"
	.string "… …\p"
	.string "You're supposed to shout\n"
	.string "“yodelayhihoo” since it doesn't\l"
	.string "echo here!$"

Route114_Text_29A707: @ 829A707
	.string "Yodelayhihoo!$"

Route114_Text_29A715: @ 829A715
	.string "When I was a wee tyke, I believed there\n"
	.string "was someone copying me and shouting\l"
	.string "back, “Yodelayhihoo.”$"

Route114_Text_29A777: @ 829A777
	.string "If you're not prepared, you shouldn't\n"
	.string "be up in the mountains!$"

Route114_Text_29A7B5: @ 829A7B5
	.string "The mountains are unforgiving…$"

Route114_Text_29A7D4: @ 829A7D4
	.string "In the winter, mountains turn deadly\n"
	.string "with blizzards and avalanches.$"

Route114_Text_29A818: @ 829A818
	.string "Camping's fun! You can fish, roast\n"
	.string "marshmallows, and tell spooky stories!\p"
	.string "But the best of all are the POKéMON\n"
	.string "battles!$"

Route114_Text_29A88F: @ 829A88F
	.string "Way too strong!$"

Route114_Text_29A89F: @ 829A89F
	.string "I think it's great that I can go\n"
	.string "camping with my POKéMON.$"

Route114_Text_29A8D9: @ 829A8D9
	.string "I need to exercise after a meal.\n"
	.string "Let's have a match!$"

Route114_Text_29A90E: @ 829A90E
	.string "Oh, no!$"

Route114_Text_29A916: @ 829A916
	.string "I just had a tasty meal.\n"
	.string "I'm getting drowsy…$"

Route114_Text_29A943: @ 829A943
	.string "Ufufufufufu…\n"
	.string "Want to battle against my POKéMON?$"

Route114_Text_29A973: @ 829A973
	.string "M-My POKéMON…$"

Route114_Text_29A981: @ 829A981
	.string "A big body that's all lumpy and hard,\n"
	.string "enormous horns, and vicious fangs…\p"
	.string "Ufufufufu…\n"
	.string "I wish I had a POKéMON like that…$"

Route114_Text_29A9F7: @ 829A9F7
	.string "Don't forget what you've done to me!\n"
	.string "I'll make it so you can't forget!$"

Route114_Text_29AA3E: @ 829AA3E
	.string "Ufufufufufu…\n"
	.string "Come on, battle my POKéMON…$"

Route114_Text_29AA67: @ 829AA67
	.string "I feel so lucky getting to see your\n"
	.string "POKéMON…$"

Route114_Text_29AA94: @ 829AA94
	.string "Ufufufufufu…\p"
	.string "When I see POKéMON battling, I get all\n"
	.string "shivery and shaky…$"

Route114_Text_29AADB: @ 829AADB
	.string "If you're lighting a campfire,\n"
	.string "make sure you have water handy.$"

Route114_Text_29AB1A: @ 829AB1A
	.string "Thanks for dousing my fire!$"

Route114_Text_29AB36: @ 829AB36
	.string "You really do have to be careful with\n"
	.string "any sort of fire in a forest.\p"
	.string "Don't ever underestimate the power\n"
	.string "of fire.$"

Route114_Text_29ABA6: @ 829ABA6
	.string "You set my spirit on fire.\n"
	.string "Let's register each other!$"

Route114_Text_29ABDC: @ 829ABDC
	.string "Have you learned to keep water handy\n"
	.string "for campfires?$"

Route114_Text_29AC10: @ 829AC10
	.string "I got hosed down before I could\n"
	.string "flare up, I guess.$"

Route114_Text_29AC43: @ 829AC43
	.string "You really do have to be careful with\n"
	.string "any sort of fire in a forest.\p"
	.string "Don't ever underestimate the power\n"
	.string "of fire.$"

Route114_Text_29ACB3: @ 829ACB3
	.string "If we were fishing, you wouldn't stand\n"
	.string "a chance against me.\l"
	.string "So, bring on your POKéMON!$"

Route114_Text_29AD0A: @ 829AD0A
	.string "If we were fishing, I would've won…$"

Route114_Text_29AD2E: @ 829AD2E
	.string "I think I'll try my luck at landing\n"
	.string "a big one at METEOR FALLS.\p"
	.string "There has to be something in there.\n"
	.string "I just know it.$"

Route114_Text_29ADA1: @ 829ADA1
	.string "I like to fish. But I also like to\n"
	.string "battle!\p"
	.string "If anyone challenges me, I'm there,\n"
	.string "even if I'm fishing.$"

Route114_Text_29AE05: @ 829AE05
	.string "I like to battle, but that doesn't\n"
	.string "mean I'm good at it…$"

Route114_Text_29AE3D: @ 829AE3D
	.string "This time I'll do it!\p"
	.string "I always think that, so I can't walk\n"
	.string "away from fishing or POKéMON.$"

Route114_Text_29AE96: @ 829AE96
	.string "TYRA: Well, sure.\n"
	.string "I'm in the mood for it.\l"
	.string "I'll teach you a little about POKéMON.$"

Route114_Text_29AEE7: @ 829AEE7
	.string "TYRA: What an amazing battle style!$"

Route114_Text_29AF0B: @ 829AF0B
	.string "TYRA: I was teaching my junior IVY\n"
	.string "about POKéMON.$"

Route114_Text_29AF3D: @ 829AF3D
	.string "TYRA: Giggle…\n"
	.string "If you want to battle with us, just one\l"
	.string "POKéMON isn't enough!$"

Route114_Text_29AF89: @ 829AF89
	.string "IVY: Who taught you about POKéMON?$"

Route114_Text_29AFAC: @ 829AFAC
	.string "IVY: What an amazing battle style!$"

Route114_Text_29AFCF: @ 829AFCF
	.string "IVY: I started training POKéMON\n"
	.string "because TYRA, my student mentor,\l"
	.string "taught me!$"

Route114_Text_29B01B: @ 829B01B
	.string "IVY: Do you only have one POKéMON?\n"
	.string "I think it must feel lonesome.$"

Route114_Text_29B05D: @ 829B05D
	.string "I landed a big one!\n"
	.string "A huge one, I tell you!$"

Route114_Text_29B089: @ 829B089
	.string "What was that about?\n"
	.string "Did mine lose in size?$"

Route114_Text_29B0B5: @ 829B0B5
	.string "Okay!\n"
	.string "I'll just fish me a bigger one!$"

Route114_Text_29B0DB: @ 829B0DB
	.string "Me!\n"
	.string "I'm not just a pretty face!$"

Route114_Text_29B0FB: @ 829B0FB
	.string "That wasn't cute in the least!$"

Route114_Text_29B11A: @ 829B11A
	.string "I don't want a POKéMON that's\n"
	.string "just cute.\p"
	.string "I adore cute ones that have a quirk\n"
	.string "or two!$"

Route114_Text_29B16F: @ 829B16F
	.string "Have you made your POKéMON evolve\n"
	.string "very much?$"

Route114_Text_29B19C: @ 829B19C
	.string "Oh, I see.\n"
	.string "That's good to know.$"

Route114_Text_29B1BC: @ 829B1BC
	.string "Some POKéMON change so much when\n"
	.string "they evolve, it's startling!$"

Route115_Text_29B1FA: @ 829B1FA
	.string "Hm…\n"
	.string "You seem rather capable…\l"
	.string "Let me keep you company!$"

Route115_Text_29B230: @ 829B230
	.string "You're much stronger than\n"
	.string "I'd imagined!$"

Route115_Text_29B258: @ 829B258
	.string "There is no such thing as a born genius.\n"
	.string "It all depends on effort!\l"
	.string "That is what I believe…$"

Route115_Text_29B2B3: @ 829B2B3
	.string "Hmm… A loss this thorough has been\n"
	.string "a distant memory.\p"
	.string "If you would allow it, I wish for\n"
	.string "another opportunity to do battle.$"

Route115_Text_29B32C: @ 829B32C
	.string "Hm… As always, your agility speaks\n"
	.string "for itself.\l"
	.string "Come, keep me company!$"

Route115_Text_29B372: @ 829B372
	.string "As strong as ever!$"

Route115_Text_29B385: @ 829B385
	.string "All it takes is effort!\p"
	.string "I lost because I haven't put in enough\n"
	.string "effort!$"

Route115_Text_29B3CC: @ 829B3CC
	.string "You!\p"
	.string "My MACHOP!\p"
	.string "Demand a battle!$"

Route115_Text_29B3ED: @ 829B3ED
	.string "Ouch, ouch, ouch!$"

Route115_Text_29B3FF: @ 829B3FF
	.string "My MACHOP crew!\p"
	.string "So long as they seek power, I will\n"
	.string "grow strong with them!$"

Route115_Text_29B449: @ 829B449
	.string "My strongest skill is busting bricks\n"
	.string "with my forehead!$"

Route115_Text_29B480: @ 829B480
	.string "Ugwaaaah!\n"
	.string "My head is busted!$"

Route115_Text_29B49D: @ 829B49D
	.string "I've been teaching my POKéMON karate.\p"
	.string "It looks like they'll get a lot better\n"
	.string "than me. I'm excited about that.$"

Route115_Text_29B50B: @ 829B50B
	.string "You impress me! Give me a rematch\n"
	.string "after I redo my training!$"

Route115_Text_29B547: @ 829B547
	.string "After you beat me, we trained hard to\n"
	.string "improve our skills.\l"
	.string "Come on, give us a rematch!$"

Route115_Text_29B59D: @ 829B59D
	.string "Ugwaaah!\n"
	.string "We lost again!$"

Route115_Text_29B5B5: @ 829B5B5
	.string "My POKéMON will grow stronger!\n"
	.string "I'll redouble my training!$"

Route115_Text_29B5EF: @ 829B5EF
	.string "This beach is my secret training spot!\n"
	.string "Don't come butting in!$"

Route115_Text_29B62D: @ 829B62D
	.string "I haven't trained enough!$"

Route115_Text_29B647: @ 829B647
	.string "The sand acts as a cushion to reduce\n"
	.string "impact and prevent injury.\l"
	.string "This is the perfect place to train.$"

Route115_Text_29B6AB: @ 829B6AB
	.string "Okay, fine, you're free to come here.\n"
	.string "In return, I'd like to battle you again.$"

Route115_Text_29B6FA: @ 829B6FA
	.string "Okay, let's get this battle on!$"

Route115_Text_29B71A: @ 829B71A
	.string "I can battle but my POKéMON…$"

Route115_Text_29B737: @ 829B737
	.string "Even when I lose, I still get some\n"
	.string "enjoyment out of it.\l"
	.string "It must be that I love POKéMON.$"

Route115_Text_29B78F: @ 829B78F
	.string "I have a rare POKéMON!\n"
	.string "Would you like me to show you?$"

Route115_Text_29B7C5: @ 829B7C5
	.string "You…\n"
	.string "You want my POKéMON, don't you?$"

Route115_Text_29B7EA: @ 829B7EA
	.string "I have this rare POKéMON.\n"
	.string "It's enough to keep me satisfied.$"

Route115_Text_29B826: @ 829B826
	.string "I'll battle while I'm running!\n"
	.string "Try to keep up with me!$"

Route115_Text_29B85D: @ 829B85D
	.string "Gasp, gasp…$"

Route115_Text_29B869: @ 829B869
	.string "I made the mistake of trying to battle\n"
	.string "while running!\p"
	.string "I should take a run to calm down…$"

Route115_Text_29B8C1: @ 829B8C1
	.string "Take that!\n"
	.string "Ultra POKéMON ninja attack!$"

Route115_Text_29B8E8: @ 829B8E8
	.string "Waaah!\n"
	.string "Our strategy failed!$"

Route115_Text_29B904: @ 829B904
	.string "But my POKéMON were ultra,\n"
	.string "weren't they?$"

Route115_Text_29B92D: @ 829B92D
	.string "My POKéMON have black belt-level\n"
	.string "strength!$"

Route115_Text_29B958: @ 829B958
	.string "This is too humiliating!$"

Route115_Text_29B971: @ 829B971
	.string "I rarely meet anyone who's better\n"
	.string "than me…\p"
	.string "I get it now!\n"
	.string "You're a GYM LEADER, aren't you?$"

Route115_Text_29B9CB: @ 829B9CB
	.string "Our eyes met!\n"
	.string "There's no getting away now!$"

Route115_Text_29B9F6: @ 829B9F6
	.string "Gah!\n"
	.string "Not bad!$"

Route115_Text_29BA04: @ 829BA04
	.string "Oh, well.\n"
	.string "I think I will TELEPORT home.$"

Route115_Text_29BA2C: @ 829BA2C
	.string "You've disturbed my meditation…\n"
	.string "You'll be punished for it.$"

Route115_Text_29BA67: @ 829BA67
	.string "You've broken my concentration!$"

Route115_Text_29BA87: @ 829BA87
	.string "I was meditating with my POKéMON.\n"
	.string "But this place isn't very peaceful…$"

Route116_Text_29BACD: @ 829BACD
	.string "If the tunnel doesn't go through, then\n"
	.string "I'll just go over the top.$"

Route116_Text_29BB0F: @ 829BB0F
	.string "Gasp… Gasp…\n"
	.string "Losing made me tired…$"

Route116_Text_29BB31: @ 829BB31
	.string "It's no big deal if there's no tunnel.\n"
	.string "To a HIKER, mountains are roads!$"

Route116_Text_29BB79: @ 829BB79
	.string "My POKéMON rule!\n"
	.string "Check them out!$"

Route116_Text_29BB9A: @ 829BB9A
	.string "Ouch! A scrape!\n"
	.string "I have to put on a bandage!$"

Route116_Text_29BBC6: @ 829BBC6
	.string "Bandages are signs of toughness!\n"
	.string "I've got another one!$"

Route116_Text_29BBFD: @ 829BBFD
	.string "My BUG POKéMON are tough!\n"
	.string "Let's battle!$"

Route116_Text_29BC25: @ 829BC25
	.string "I lost!\n"
	.string "I thought I had you!$"

Route116_Text_29BC42: @ 829BC42
	.string "BUG POKéMON evolve quickly.\n"
	.string "So they get strong quickly, too.$"

Route116_Text_29BC7F: @ 829BC7F
	.string "Let me teach you how strong my\n"
	.string "adorable POKéMON is!$"

Route116_Text_29BCB3: @ 829BCB3
	.string "You're a notch above me…$"

Route116_Text_29BCCC: @ 829BCCC
	.string "POKéMON that possess cuteness and\n"
	.string "power, that's ideal, I think.$"

Route116_Text_29BD0C: @ 829BD0C
	.string "We learn all sorts of things at the\n"
	.string "TRAINER'S SCHOOL.\p"
	.string "I want to test things out for real!$"

Route116_Text_29BD66: @ 829BD66
	.string "I slacked off in school…\n"
	.string "That's why I lost.$"

Route116_Text_29BD92: @ 829BD92
	.string "I'll have to redo some courses at\n"
	.string "the TRAINER'S SCHOOL.\l"
	.string "If I don't, ROXANNE will be steamed.$"

Route116_Text_29BDEF: @ 829BDEF
	.string "I learned at the TRAINER'S SCHOOL\n"
	.string "that a POKéNAV can register TRAINERS.\p"
	.string "I don't really get what that means,\n"
	.string "so can I just try it?$"

Route116_Text_29BE71: @ 829BE71
	.string "I learned at the TRAINER'S SCHOOL\n"
	.string "that a POKéNAV can register TRAINERS.\p"
	.string "I don't really get what that means,\n"
	.string "so can I just try it?$"

Route116_Text_29BEF3: @ 829BEF3
	.string "I've been studying seriously at the\n"
	.string "TRAINER'S SCHOOL.\l"
	.string "I won't lose like I did last time.$"

Route116_Text_29BF4C: @ 829BF4C
	.string "Hunh?\n"
	.string "I studied diligently.$"

Route116_Text_29BF68: @ 829BF68
	.string "I'll have to redo some courses at\n"
	.string "the TRAINER'S SCHOOL.\l"
	.string "If I don't, ROXANNE will be steamed.$"

Route116_Text_29BFC5: @ 829BFC5
	.string "I study at school, and I study on\n"
	.string "the way home, too!$"

Route116_Text_29BFFA: @ 829BFFA
	.string "I'm in shock--I lost?$"

Route116_Text_29C010: @ 829C010
	.string "Awww, I'll never become an elegant\n"
	.string "TRAINER like ROXANNE this way!$"

Route116_Text_29C052: @ 829C052
	.string "Oh, wow! Isn't that a POKéNAV?\n"
	.string "I have one, too! Please register me!$"

Route116_Text_29C096: @ 829C096
	.string "Oh, wow! Isn't that a POKéNAV?\n"
	.string "I have one, too! Please register me!$"

Route116_Text_29C0DA: @ 829C0DA
	.string "I studied a whole lot since I saw you.\n"
	.string "You must see my achievements!$"

Route116_Text_29C11F: @ 829C11F
	.string "I'm in shock.\n"
	.string "I lost again?$"

Route116_Text_29C13B: @ 829C13B
	.string "You've beaten ROXANNE?\n"
	.string "I can't beat you, then. Not yet.$"

Route116_Text_29C173: @ 829C173
	.string "Just so you know, I've never once been\n"
	.string "bested by anyone at anything.$"

Route116_Text_29C1B8: @ 829C1B8
	.string "Oh, my goodness.\n"
	.string "This is a new experience for me.$"

Route116_Text_29C1EA: @ 829C1EA
	.string "My life of luxury affords me all that\n"
	.string "I could possibly desire.\p"
	.string "However, when it comes to POKéMON,\n"
	.string "my wealth has no meaning.$"

Route116_Text_29C266: @ 829C266
	.string "When you lay your eyes on my POKéMON's\n"
	.string "gorgeous fur, their beauty will render\l"
	.string "you helpless!$"

Route116_Text_29C2C2: @ 829C2C2
	.string "Oh, baby, say it isn't so!$"

Route116_Text_29C2DD: @ 829C2DD
	.string "Oh, no, no, no!\n"
	.string "You've mussed up my POKéMON's fur!\l"
	.string "You've ruined my hairdo, too!\l"
	.string "I'll have to call my stylist now!$"

Route116_Text_29C350: @ 829C350
	.string "We'll rock you hard!$"

Route116_Text_29C365: @ 829C365
	.string "Aiyiyi!\n"
	.string "No contest at all!$"

Route116_Text_29C380: @ 829C380
	.string "I should try different POKéMON\n"
	.string "types, that's what I ought to do.$"

Route116_Text_29C3C1: @ 829C3C1
	.string "It's a dead end up here.\n"
	.string "I'm bored, so can we battle?$"

Route116_Text_29C3F7: @ 829C3F7
	.string "That was fun even though I lost.$"

Route116_Text_29C418: @ 829C418
	.string "Want to stay here and keep\n"
	.string "me company?$"

Route117_Text_29C43F: @ 829C43F
	.string "Listen, could I get you to battle\n"
	.string "the POKéMON I'm raising?$"

Route117_Text_29C47A: @ 829C47A
	.string "You've raised yours superbly…$"

Route117_Text_29C498: @ 829C498
	.string "POKéMON isn't all about power.\p"
	.string "Polishing a unique aspect of one's\n"
	.string "character is another way of enjoying\l"
	.string "POKéMON.$"

Route117_Text_29C508: @ 829C508
	.string "I'm going to redouble my training.\n"
	.string "Would you come look in on us?$"

Route117_Text_29C549: @ 829C549
	.string "The POKéMON I've been raising are\n"
	.string "looking good, just like before.$"

Route117_Text_29C58B: @ 829C58B
	.string "You know how to raise them properly.\n"
	.string "You might have DAY CARE skills…$"

Route117_Text_29C5D0: @ 829C5D0
	.string "Your POKéMON are growing good!\n"
	.string "You should enter them in CONTESTS.$"

Route117_Text_29C612: @ 829C612
	.string "Please, allow me to evaluate if you\n"
	.string "have raised your POKéMON properly.$"

Route117_Text_29C659: @ 829C659
	.string "Yes, they are growing properly.$"

Route117_Text_29C679: @ 829C679
	.string "Try raising POKéMON with more\n"
	.string "attention to their character traits.$"

Route117_Text_29C6BC: @ 829C6BC
	.string "I'm glad I met a superb TRAINER in you.\n"
	.string "I hope to see you again.$"

Route117_Text_29C6FD: @ 829C6FD
	.string "Allow me to reevaluate if you have\n"
	.string "raised your POKéMON properly.$"

Route117_Text_29C73E: @ 829C73E
	.string "They are growing admirably.$"

Route117_Text_29C75A: @ 829C75A
	.string "POKéMON seem to like different kinds\n"
	.string "of {POKEBLOCK}S, depending on their nature.$"

Route117_Text_29C7A5: @ 829C7A5
	.string "I'm in the middle of a triathlon, but,\n"
	.string "whatever, let's have a battle!$"

Route117_Text_29C7EB: @ 829C7EB
	.string "I ran out of energy!$"

Route117_Text_29C800: @ 829C800
	.string "I may have blown it…\p"
	.string "I might have dropped to last during\n"
	.string "that battle…$"

Route117_Text_29C846: @ 829C846
	.string "POKéMON have to be strong, too?\n"
	.string "I'd like you to train me!$"

Route117_Text_29C880: @ 829C880
	.string "I'm smack in the middle of a triathlon,\n"
	.string "but I'm comfortably ahead.\l"
	.string "Let's make this a quick battle!$"

Route117_Text_29C8E3: @ 829C8E3
	.string "I ran out of energy again!$"

Route117_Text_29C8FE: @ 829C8FE
	.string "I was tops in swimming and cycling,\n"
	.string "but I'm not quite that confident with\l"
	.string "POKéMON yet.$"

Route117_Text_29C955: @ 829C955
	.string "I do my triathlon training with POKéMON,\n"
	.string "so I'm pretty confident about my speed.$"

Route117_Text_29C9A6: @ 829C9A6
	.string "I need to get more practices in,\n"
	.string "I guess.$"

Route117_Text_29C9D0: @ 829C9D0
	.string "Training is meaningful only if you\n"
	.string "keep it up regularly.\p"
	.string "Okay! I'll resume my training!\n"
	.string "Tomorrow!$"

Route117_Text_29CA32: @ 829CA32
	.string "You appear to be training properly…\n"
	.string "If you'd like, I'll battle you later!$"

Route117_Text_29CA7C: @ 829CA7C
	.string "Are you keeping up with your training?\n"
	.string "I sure am!\l"
	.string "Let me show you the evidence!$"

Route117_Text_29CACC: @ 829CACC
	.string "I need to get more practices in,\n"
	.string "I guess.$"

Route117_Text_29CAF6: @ 829CAF6
	.string "I'll resume training tomorrow.\n"
	.string "Let's battle again sometime!$"

Route117_Text_29CB32: @ 829CB32
	.string "Once a BUG CATCHER!\n"
	.string "And now a BUG MANIAC!\p"
	.string "But my love for POKéMON remains\n"
	.string "unchanged!$"

Route117_Text_29CB87: @ 829CB87
	.string "My ineptitude also remains\n"
	.string "unchanged…$"

Route117_Text_29CBAD: @ 829CBAD
	.string "All I did was follow my heart, and now\n"
	.string "they call me a BUG MANIAC…\p"
	.string "Still, I am an expert on BUG POKéMON,\n"
	.string "so it's only natural that they call me\l"
	.string "a BUG MANIAC.$"

Route117_Text_29CC4A: @ 829CC4A
	.string "ANNA: I'm with my pretty junior student\n"
	.string "partner. I have to do good!$"

Route117_Text_29CC8E: @ 829CC8E
	.string "ANNA: I'm with my pretty junior student\n"
	.string "partner! Let me win!$"

Route117_Text_29CCCB: @ 829CCCB
	.string "ANNA: Your POKéMON have some good\n"
	.string "combinations.\p"
	.string "I'd say you're second only to us!$"

Route117_Text_29CD1D: @ 829CD1D
	.string "ANNA: We can't take this lying down!\n"
	.string "You will come back, won't you?$"

Route117_Text_29CD61: @ 829CD61
	.string "ANNA: If you want to battle us,\n"
	.string "bring two POKéMON with you.$"

Route117_Text_29CD9D: @ 829CD9D
	.string "MEG: I'm going to tag up with my super\n"
	.string "senior student partner and beat you!$"

Route117_Text_29CDE9: @ 829CDE9
	.string "MEG: Oh, no!\n"
	.string "I'm sorry, ANNA! I let you down…$"

Route117_Text_29CE17: @ 829CE17
	.string "MEG: I dragged ANNA down…\n"
	.string "If I didn't, she would have won!$"

Route117_Text_29CE52: @ 829CE52
	.string "MEG: Do you only have one POKéMON?\n"
	.string "We can't battle with you, then.\p"
	.string "We want to have a 2-on-2 battle.$"

Route117_Text_29CEB6: @ 829CEB6
	.string "ANNA: I can't keep losing in front of\n"
	.string "my junior partner, right?$"

Route117_Text_29CEF6: @ 829CEF6
	.string "ANNA: I couldn't get into the groove.$"

Route117_Text_29CF1C: @ 829CF1C
	.string "ANNA: Your POKéMON have some good\n"
	.string "combinations.\p"
	.string "I'd say you're second only to us!$"

Route117_Text_29CF6E: @ 829CF6E
	.string "ANNA: If you want to battle us,\n"
	.string "bring two POKéMON with you.$"

Route117_Text_29CFAA: @ 829CFAA
	.string "MEG: I'm going to tag up with my\n"
	.string "senior partner and win this time!$"

Route117_Text_29CFED: @ 829CFED
	.string "MEG: Too strong!$"

Route117_Text_29CFFE: @ 829CFFE
	.string "MEG: I battled together with my\n"
	.string "senior partner, but we lost…\p"
	.string "That's so discouraging…$"

Route117_Text_29D053: @ 829D053
	.string "MEG: Do you only have one POKéMON?\n"
	.string "We can't battle with you, then.\p"
	.string "We want to have a 2-on-2 battle.$"

Route117_Text_29D0B7: @ 829D0B7
	.string "Isn't it nice? To battle while looking\n"
	.string "at pretty flowers?$"

Route117_Text_29D0F1: @ 829D0F1
	.string "Oh, that's quite impressive!$"

Route117_Text_29D10E: @ 829D10E
	.string "It feels wonderful to go for a jog\n"
	.string "while looking at flowers.$"

Route117_Text_29D14B: @ 829D14B
	.string "Let me demonstrate the power\n"
	.string "hidden within a PSYCHIC POKéMON!$"

Route117_Text_29D189: @ 829D189
	.string "Astonishing!$"

Route117_Text_29D196: @ 829D196
	.string "PSYCHIC POKéMON are complex.\n"
	.string "You should try catching some.$"

Route117_Text_29D1D1: @ 829D1D1
	.string "Concentrate on getting the win.\n"
	.string "That's how I battle!$"

Route117_Text_29D206: @ 829D206
	.string "I don't waste any time being angry\n"
	.string "over a loss--I would rather train.$"

Route117_Text_29D24C: @ 829D24C
	.string "I think that if you worry about losing,\n"
	.string "you're more likely to lose.$"

Route118_Text_29D290: @ 829D290
	.string "The aroma of flowers has a magical\n"
	.string "power. It cleanses us body and soul.$"

Route118_Text_29D2D8: @ 829D2D8
	.string "Oh, dear me.\n"
	.string "I seem to have lost.$"

Route118_Text_29D2FA: @ 829D2FA
	.string "Flowers, POKéMON…\n"
	.string "I love whatever smells nice.\p"
	.string "Stinky things…\n"
	.string "I'll pass.$"

Route118_Text_29D343: @ 829D343
	.string "Sniff… That odor--it's a POKéNAV!\n"
	.string "We must register each other!$"

Route118_Text_29D382: @ 829D382
	.string "Were you drawn here by the sweet\n"
	.string "aroma?$"

Route118_Text_29D3AA: @ 829D3AA
	.string "The power of aroma…\n"
	.string "It didn't seem to do much.$"

Route118_Text_29D3D9: @ 829D3D9
	.string "If you use a sweet aroma properly,\n"
	.string "POKéMON will be attracted by it.$"

Route118_Text_29D41D: @ 829D41D
	.string "BIRD POKéMON that FLY elegantly in\n"
	.string "the sky… They're the best!$"

Route118_Text_29D45B: @ 829D45B
	.string "Urgh…\n"
	.string "I crashed…$"

Route118_Text_29D46C: @ 829D46C
	.string "You've got great POKéMON.\n"
	.string "I'll have to train mine better.$"

Route118_Text_29D4A6: @ 829D4A6
	.string "Take flight!\n"
	.string "My BIRD POKéMON!$"

Route118_Text_29D4C4: @ 829D4C4
	.string "They did take flight…$"

Route118_Text_29D4DA: @ 829D4DA
	.string "If they'd get stronger, they'd be able\n"
	.string "to fly more freely…$"

Route118_Text_29D515: @ 829D515
	.string "I'm a FISHERMAN, but also a TRAINER.\n"
	.string "I'm raising the POKéMON I caught.$"

Route118_Text_29D55C: @ 829D55C
	.string "I thought I was doing okay in my\n"
	.string "training…$"

Route118_Text_29D587: @ 829D587
	.string "I couldn't win by training POKéMON\n"
	.string "while I fished…\p"
	.string "Was I doing things in half measures?$"

Route118_Text_29D5DF: @ 829D5DF
	.string "For FISHERMEN, equipment is the key.\p"
	.string "But for TRAINERS, the key ingredients\n"
	.string "are POKéMON and heart, of course!$"

Route118_Text_29D64C: @ 829D64C
	.string "I was beaten in heart?$"

Route118_Text_29D663: @ 829D663
	.string "Come to think of it, fishing is a battle\n"
	.string "between a FISHERMAN and a POKéMON.$"

Route118_Text_29D6AF: @ 829D6AF
	.string "Let my melody rock your soul!$"

Route118_Text_29D6CD: @ 829D6CD
	.string "La-lalala…$"

Route118_Text_29D6D8: @ 829D6D8
	.string "An electric guitar doesn't always\n"
	.string "have to be noisy…\p"
	.string "It can be strummed to squeeze out\n"
	.string "this heart-stirring melody…$"

Route118_Text_29D74A: @ 829D74A
	.string "When I compose better melodies,\n"
	.string "you have to come listen, okay?$"

Route118_Text_29D789: @ 829D789
	.string "A melody from my POKéMON and me…\n"
	.string "Let us deliver it to your soul.$"

Route118_Text_29D7CA: @ 829D7CA
	.string "La-lalala…$"

Route118_Text_29D7D5: @ 829D7D5
	.string "When I play, my emotions should reach\n"
	.string "you through my electric guitar…$"

Route118_Text_29D81B: @ 829D81B
	.string "Go, go, go!\n"
	.string "POKéMON 1, 2, and 3!$"

Route118_Text_29D83C: @ 829D83C
	.string "Come in, POKéMON! Are you okay?\n"
	.string "POKéMON 1, 2, and 3?!$"

Route118_Text_29D872: @ 829D872
	.string "Isn't it cool that I have a POKéMON\n"
	.string "battle team?\p"
	.string "You can copy me--I don't mind!$"

Route119_Text_29D8C2: @ 829D8C2
	.string "We're the MIMIC CIRCLE!\n"
	.string "We MIMIC what you do!$"

Route119_Text_29D8F0: @ 829D8F0
	.string "Whoopsie!\n"
	.string "I lost!$"

Route119_Text_29D902: @ 829D902
	.string "What's so good about mimicry?\p"
	.string "Fufufu…\n"
	.string "You'll never understand…$"

Route119_Text_29D941: @ 829D941
	.string "So, we finally meet!\n"
	.string "My BUG POKéMON will keep you company!$"

Route119_Text_29D97C: @ 829D97C
	.string "I wish we'd never met…$"

Route119_Text_29D993: @ 829D993
	.string "I want to MIMIC you some more.\n"
	.string "Can you hurry up and move?$"

Route119_Text_29D9CD: @ 829D9CD
	.string "If you step forward, we step forward.\p"
	.string "If you turn right, we turn, too…$"

Route119_Text_29DA14: @ 829DA14
	.string "But if you win, I lose…$"

Route119_Text_29DA2C: @ 829DA2C
	.string "I can't MIMIC you winning the match.\n"
	.string "That's just impossible…\l"
	.string "It's burning me up…$"

Route119_Text_29DA7D: @ 829DA7D
	.string "Yep, you've finally caught me!\n"
	.string "Or were you trying to avoid me?$"

Route119_Text_29DABC: @ 829DABC
	.string "Whoop, that was a great match!$"

Route119_Text_29DADB: @ 829DADB
	.string "We're the MIMIC CIRCLE!\n"
	.string "I hope you enjoyed our performance.$"

Route119_Text_29DB17: @ 829DB17
	.string "You don't know who I am, do you?\p"
	.string "But, I also don't know you.\n"
	.string "So, we'll battle!$"

Route119_Text_29DB66: @ 829DB66
	.string "You're pretty strong!$"

Route119_Text_29DB7C: @ 829DB7C
	.string "Until you go away somewhere, we'll\n"
	.string "keep on mimicking your every move.$"

Route119_Text_29DBC2: @ 829DBC2
	.string "The MIMIC CIRCLE was formed by people\n"
	.string "who like to MIMIC.\p"
	.string "A battle starts the instant we meet!$"

Route119_Text_29DC20: @ 829DC20
	.string "I give up!$"

Route119_Text_29DC2B: @ 829DC2B
	.string "Won't you join our MIMIC CIRCLE?$"

Route119_Text_29DC4C: @ 829DC4C
	.string "Who has the knowledge and\n"
	.string "the technique for survival?\p"
	.string "POKéMON RANGERS, that's who!$"

Route119_Text_29DC9F: @ 829DC9F
	.string "I didn't have enough POKéMON\n"
	.string "know-how…$"

Route119_Text_29DCC6: @ 829DCC6
	.string "To break away from civilization and\n"
	.string "awaken the wild spirit within!\p"
	.string "That's our vision.$"

Route119_Text_29DD1C: @ 829DD1C
	.string "I hope you'll give me a rematch without\n"
	.string "mocking my lack of knowledge.$"

Route119_Text_29DD62: @ 829DD62
	.string "I'm going to regain my wild spirit by\n"
	.string "being together with POKéMON.$"

Route119_Text_29DDA5: @ 829DDA5
	.string "You've remained strong!$"

Route119_Text_29DDBD: @ 829DDBD
	.string "Believe in your POKéMON.\n"
	.string "Believe in yourself.\p"
	.string "The road will reveal itself to you.$"

Route119_Text_29DE0F: @ 829DE0F
	.string "Oh? Look at you.\p"
	.string "For someone on an adventure,\n"
	.string "you're traveling awfully light.$"

Route119_Text_29DE5D: @ 829DE5D
	.string "Accidents happen when you're not\n"
	.string "prepared!$"

Route119_Text_29DE88: @ 829DE88
	.string "You're traveling light but you have\n"
	.string "everything you need.\p"
	.string "You're on top of things mentally and\n"
	.string "physically, too.$"

Route119_Text_29DEF7: @ 829DEF7
	.string "Do you have a POKéNAV?\n"
	.string "It's a must-have tool for any TRAINER.\p"
	.string "Oh, you do have one!\n"
	.string "Let's register each other, then!$"

Route119_Text_29DF6B: @ 829DF6B
	.string "How's your journey with POKéMON\n"
	.string "going?$"

Route119_Text_29DF92: @ 829DF92
	.string "I'm still missing something…$"

Route119_Text_29DFAF: @ 829DFAF
	.string "In the same way that you, as a TRAINER,\n"
	.string "rely on your POKéMON, your POKéMON\l"
	.string "rely on you.$"

Route119_Text_29E007: @ 829E007
	.string "The vast sky holds untold promise!\p"
	.string "Nothing can compare to the sheer\n"
	.string "exhilaration of flight!$"

Route119_Text_29E063: @ 829E063
	.string "Down and out!$"

Route119_Text_29E071: @ 829E071
	.string "My BIRD POKéMON made my dreams of\n"
	.string "flying come true!$"

Route119_Text_29E0A5: @ 829E0A5
	.string "I'll show you the true potential of me\n"
	.string "and my BIRD POKéMON!$"

Route119_Text_29E0E1: @ 829E0E1
	.string "We lacked potential…$"

Route119_Text_29E0F6: @ 829E0F6
	.string "Ever since I was a little kid, I always\n"
	.string "admired BIRD POKéMON…$"

Route119_Text_29E134: @ 829E134
	.string "To lurk in shadows, and live in\n"
	.string "darkness… That is my destiny.\p"
	.string "I emerge to challenge you!$"

Route119_Text_29E18D: @ 829E18D
	.string "I admit defeat!$"

Route119_Text_29E19D: @ 829E19D
	.string "Those defeated in battle withdraw\n"
	.string "quietly back into the shadows.\l"
	.string "That, too, is destiny…$"

Route119_Text_29E1F5: @ 829E1F5
	.string "If you're not on your guard,\n"
	.string "you're in for some pain!$"

Route119_Text_29E22B: @ 829E22B
	.string "You're surprisingly good!$"

Route119_Text_29E245: @ 829E245
	.string "My surprise attack ended in\n"
	.string "failure…$"

Route119_Text_29E26A: @ 829E26A
	.string "To hide a tree, use a forest!$"

Route119_Text_29E288: @ 829E288
	.string "I bow to your superiority.$"

Route119_Text_29E2A3: @ 829E2A3
	.string "To hide a tree, use a forest!\n"
	.string "To hide a POKéMON, use a POKéMON!\p"
	.string "There is no deep, hidden meaning\n"
	.string "to that.$"

Route119_Text_29E30D: @ 829E30D
	.string "You spoke to me…\n"
	.string "So you want to challenge me!\p"
	.string "Sure! I'll try out the POKéMON I caught\n"
	.string "while SURFING!$"

Route119_Text_29E372: @ 829E372
	.string "I don't have a clue about what it\n"
	.string "takes to win.$"

Route119_Text_29E3A2: @ 829E3A2
	.string "Go for a SURF on my POKéMON…\p"
	.string "Then fish off its back…\p"
	.string "It's an indescribably luxuriant moment!$"

Route119_Text_29E3FF: @ 829E3FF
	.string "Hit me with a power chord!\n"
	.string "Victory is mine!\l"
	.string "It's our time to shine, whoa, yeah!$"

Route119_Text_29E44F: @ 829E44F
	.string "You showed me who's the boss!\n"
	.string "We'll have to take the loss, oh, no!$"

Route119_Text_29E492: @ 829E492
	.string "Hit me with another power chord!\n"
	.string "Leave me alone!\l"
	.string "Your win you have to atone!$"

Route119_Text_29E4DF: @ 829E4DF
	.string "Hohoho!\n"
	.string "I like kid TRAINERS!\l"
	.string "Let's have a good one!$"

Route119_Text_29E513: @ 829E513
	.string "You're pretty amazing!\n"
	.string "Hohoho!$"

Route119_Text_29E532: @ 829E532
	.string "Hohoho!\n"
	.string "I'll try emulating the pep of kid\l"
	.string "TRAINERS like you!$"

Route119_Text_29E56F: @ 829E56F
	.string "Wherever and whenever I may be,\n"
	.string "I always have my parasol in hand.$"

Route119_Text_29E5B1: @ 829E5B1
	.string "Oh, but…\n"
	.string "That's not fair.$"

Route119_Text_29E5CB: @ 829E5CB
	.string "You're asking if my parasol is heavy?\n"
	.string "Your BAG is filled with more junk than\l"
	.string "I ever carry around.$"

Route120_Text_29E62D: @ 829E62D
	.string "Do you have any moves that can strike\n"
	.string "a flying POKéMON?$"

Route120_Text_29E665: @ 829E665
	.string "You soared above me!$"

Route120_Text_29E67A: @ 829E67A
	.string "The move FLY is convenient,\n"
	.string "don't you think?\p"
	.string "While the POKéMON is flying,\n"
	.string "almost no moves can strike it.$"

Route120_Text_29E6E3: @ 829E6E3
	.string "My POKéMON is strong!\n"
	.string "How about yours?$"

Route120_Text_29E70A: @ 829E70A
	.string "Your POKéMON were stronger…$"

Route120_Text_29E726: @ 829E726
	.string "A POKéMON that grows steadily is one\n"
	.string "you can count on.$"

Route120_Text_29E75D: @ 829E75D
	.string "You can be counted on to get better.\n"
	.string "I'd like to register you in my POKéNAV!$"

Route120_Text_29E7AA: @ 829E7AA
	.string "A POKéMON that grows steadily is one\n"
	.string "you can count on.$"

Route120_Text_29E7E1: @ 829E7E1
	.string "Your POKéMON are seriously strong.$"

Route120_Text_29E804: @ 829E804
	.string "My POKéMON are growing stronger.\n"
	.string "I have to grow stronger, too.$"

Route120_Text_29E843: @ 829E843
	.string "I'll check your POKéMON and see if\n"
	.string "they're fit for the outdoors.$"

Route120_Text_29E884: @ 829E884
	.string "With POKéMON that strong, you're in\n"
	.string "no danger of needing rescue!$"

Route120_Text_29E8C5: @ 829E8C5
	.string "To travel wherever your heart desires\n"
	.string "with POKéMON…\l"
	.string "That's the joy of being a TRAINER.$"

Route120_Text_29E91C: @ 829E91C
	.string "How's your physical fitness?\n"
	.string "If you're not fit, you could have a\l"
	.string "rough time in critical situations.$"

Route120_Text_29E980: @ 829E980
	.string "I'm totally fit, but…$"

Route120_Text_29E996: @ 829E996
	.string "Fitness training is in my routine.\n"
	.string "I always run with my POKéMON.$"

Route120_Text_29E9D7: @ 829E9D7
	.string "… … … … … …\n"
	.string "… … … … … …\l"
	.string "Want to battle?$"

Route120_Text_29E9FF: @ 829E9FF
	.string "Lost it…$"

Route120_Text_29EA08: @ 829EA08
	.string "… … … … … …\n"
	.string "… … … … … …\l"
	.string "I'll try harder…$"

Route120_Text_29EA31: @ 829EA31
	.string "… … … … … …\n"
	.string "… … … … … …\l"
	.string "Do you have a POKéNAV…?$"

Route120_Text_29EA61: @ 829EA61
	.string "… … … … … …\n"
	.string "… … … … … …\l"
	.string "Want to battle again?$"

Route120_Text_29EA8F: @ 829EA8F
	.string "… … … … … …\n"
	.string "I lost again…$"

Route120_Text_29EAA9: @ 829EAA9
	.string "… … … … … …\n"
	.string "… … … … … …\l"
	.string "I'll try harder…\l"
	.string "For my precious BUG POKéMON…$"

Route120_Text_29EAEF: @ 829EAEF
	.string "POKéMON have many special abilities.\n"
	.string "If you want to become a first-class\l"
	.string "TRAINER, learn about them.$"

Route120_Text_29EB53: @ 829EB53
	.string "You're obviously thinking.$"

Route120_Text_29EB6E: @ 829EB6E
	.string "The special abilities of POKéMON\n"
	.string "will make battle styles change.$"

Route120_Text_29EBAF: @ 829EBAF
	.string "Who might you be?\p"
	.string "Are you perhaps searching for ancient\n"
	.string "ruins that are rumored to possibly\l"
	.string "exist according to legend?$"

Route120_Text_29EC25: @ 829EC25
	.string "What a disgraceful setback…$"

Route120_Text_29EC41: @ 829EC41
	.string "That giant rock… I would like to\n"
	.string "believe it may indeed contain ancient\l"
	.string "ruins. But I see no entrance.$"

Route120_Text_29ECA6: @ 829ECA6
	.string "Why am I carrying this parasol?\p"
	.string "I'll tell you if you can win against me.$"

Route120_Text_29ECEF: @ 829ECEF
	.string "A parasol can't ward off POKéMON\n"
	.string "attacks…$"

Route120_Text_29ED19: @ 829ED19
	.string "I don't think strong sunlight is good\n"
	.string "for my POKéMON.\l"
	.string "So I shield them with my parasol.$"

Route120_Text_29ED71: @ 829ED71
	.string "Me, POKéMON, and my parasol…\p"
	.string "If any one of them is missing,\n"
	.string "the picture of beauty will be ruined.$"

Route120_Text_29EDD3: @ 829EDD3
	.string "You've completely ruined my beauty…$"

Route120_Text_29EDF7: @ 829EDF7
	.string "A parasol wouldn't suit you at all.\p"
	.string "Why, something like this would only\n"
	.string "get in your way.$"

Route120_Text_29EE50: @ 829EE50
	.string "I will adopt the movements of POKéMON\n"
	.string "and create new ninja techniques.$"

Route120_Text_29EE97: @ 829EE97
	.string "The creation of new ninja techniques\n"
	.string "is but a distant dream…$"

Route120_Text_29EED4: @ 829EED4
	.string "Perhaps I ought to apprentice under\n"
	.string "a ninja sensei.$"

Route120_Text_29EF08: @ 829EF08
	.string "We ninja conceal ourselves under our\n"
	.string "camouflage cloaks.\l"
	.string "I bet you didn't know where I was!$"

Route120_Text_29EF63: @ 829EF63
	.string "I lost!\n"
	.string "I should camouflage my shame!$"

Route120_Text_29EF89: @ 829EF89
	.string "Our camouflage cloaks are all\n"
	.string "handmade.$"

Route120_Text_29EFB1: @ 829EFB1
	.string "If you don't pay attention,\n"
	.string "you could get hurt!$"

Route120_Text_29EFE1: @ 829EFE1
	.string "Ouch!\n"
	.string "I was the one to get hurt.$"

Route120_Text_29F002: @ 829F002
	.string "I wonder… Should I evolve my POKéMON?\n"
	.string "They're cute the way they are, though.$"

Route120_Text_29F04F: @ 829F04F
	.string "Your party POKéMON…\n"
	.string "Do you have different types?$"

Route120_Text_29F080: @ 829F080
	.string "I've seen your policy in action!$"

Route120_Text_29F0A1: @ 829F0A1
	.string "I think it's awesome you're so strong\n"
	.string "battling with your favorite POKéMON.$"

Route121_Text_29F0EC: @ 829F0EC
	.string "Will you play with my delightfully\n"
	.string "pretty POKéMON?$"

Route121_Text_29F11F: @ 829F11F
	.string "This isn't what I meant!$"

Route121_Text_29F138: @ 829F138
	.string "I'm going to a CONTEST in LILYCOVE.\p"
	.string "My POKéMON should have no problem\n"
	.string "sweeping the MASTER CLASS.$"

Route121_Text_29F199: @ 829F199
	.string "With my POKéMON, I have traveled\n"
	.string "to the world's four corners.\p"
	.string "You might say I have some confidence\n"
	.string "in my abilities.$"

Route121_Text_29F20D: @ 829F20D
	.string "Ah, well played.$"

Route121_Text_29F21E: @ 829F21E
	.string "I would like to circle the globe once\n"
	.string "again with my POKéMON.$"

Route121_Text_29F25B: @ 829F25B
	.string "Your POKéMON prowess is remarkable.\n"
	.string "Allow me to register you as a memento.$"

Route121_Text_29F2A6: @ 829F2A6
	.string "With my POKéMON, I have traveled\n"
	.string "to the world's four corners.\p"
	.string "You might say I have some confidence\n"
	.string "in my abilities.$"

Route121_Text_29F31A: @ 829F31A
	.string "Ah, well played.$"

Route121_Text_29F32B: @ 829F32B
	.string "Your POKéMON and you…\p"
	.string "Your prowess together will be\n"
	.string "considered strong, even overseas.$"

Route121_Text_29F381: @ 829F381
	.string "There are powers beyond our\n"
	.string "understanding in the world…$"

Route121_Text_29F3B9: @ 829F3B9
	.string "I have lost…$"

Route121_Text_29F3C6: @ 829F3C6
	.string "MT. PYRE…\n"
	.string "There is a mysterious power\l"
	.string "at work there…$"

Route121_Text_29F3FB: @ 829F3FB
	.string "KATE: Together, we're fearless!\n"
	.string "We'll demonstrate how tough we are!$"

Route121_Text_29F43F: @ 829F43F
	.string "KATE: I blew it in front of my junior\n"
	.string "student partner…$"

Route121_Text_29F476: @ 829F476
	.string "KATE: When someone's relying on me,\n"
	.string "I get this urge to look cool in front\l"
	.string "of them…$"

Route121_Text_29F4C9: @ 829F4C9
	.string "KATE: If you've only got one POKéMON,\n"
	.string "we can't battle with you.\p"
	.string "That would be bullying.$"

Route121_Text_29F521: @ 829F521
	.string "JOY: Together, we're fearless!\n"
	.string "We'll demonstrate how tough we are!$"

Route121_Text_29F564: @ 829F564
	.string "JOY: Please forgive me, KATE!$"

Route121_Text_29F582: @ 829F582
	.string "JOY: Ehehe, I'll have to train with KATE,\n"
	.string "my senior student partner, again.$"

Route121_Text_29F5CE: @ 829F5CE
	.string "JOY: You need at least two POKéMON\n"
	.string "if you're going to challenge us!$"

Route121_Text_29F612: @ 829F612
	.string "Stop! Have a good look at my precious\n"
	.string "POKéMON!$"

Route121_Text_29F641: @ 829F641
	.string "Oh, how dare you!\n"
	.string "Don't take it so seriously!$"

Route121_Text_29F66F: @ 829F66F
	.string "Maybe I'll go catch more POKéMON at\n"
	.string "the SAFARI.$"

Route121_Text_29F69F: @ 829F69F
	.string "I took it easy on you this time!\n"
	.string "It won't be that way the next time!$"

Route121_Text_29F6E4: @ 829F6E4
	.string "My precious POKéMON grew!\n"
	.string "Have a good look!$"

Route121_Text_29F710: @ 829F710
	.string "Oh, how dare you!\n"
	.string "You still won't take it easy!$"

Route121_Text_29F740: @ 829F740
	.string "Maybe I'll go catch more POKéMON at\n"
	.string "the SAFARI.$"

Route121_Text_29F770: @ 829F770
	.string "I have this routine.\n"
	.string "Defeat five TRAINERS a day.\l"
	.string "Guess what? You're number five!$"

Route121_Text_29F7C1: @ 829F7C1
	.string "No!\n"
	.string "You're horrid!$"

Route121_Text_29F7D4: @ 829F7D4
	.string "I didn't expect to lose this easily…\n"
	.string "I'll win next time!$"

Route121_Text_29F80D: @ 829F80D
	.string "That was total humiliation!\n"
	.string "I won't forget you…\l"
	.string "Hand over your POKéNAV!$"

Route121_Text_29F855: @ 829F855
	.string "I have this new routine.\n"
	.string "Defeat ten TRAINERS a day.\l"
	.string "Guess what? You're number ten!$"

Route121_Text_29F8A8: @ 829F8A8
	.string "Wait! That's nasty!\n"
	.string "I demand a rematch!$"

Route121_Text_29F8D0: @ 829F8D0
	.string "An opponent I just can't beat…\n"
	.string "Snivel…\l"
	.string "I can't believe this is happening…$"

Route121_Text_29F91A: @ 829F91A
	.string "Can't you see that I have all this\n"
	.string "stuff with me?\p"
	.string "Despite that, you still insist that\n"
	.string "we battle?$"

Route121_Text_29F97B: @ 829F97B
	.string "Of course I lost!\n"
	.string "I'm holding stuff in both hands!$"

Route121_Text_29F9AE: @ 829F9AE
	.string "I bought too much stuff at\n"
	.string "the LILYCOVE DEPT. STORE.\p"
	.string "It's up the road from here.\n"
	.string "I wish I had a BAG like yours.$"

Route121_Text_29FA1E: @ 829FA1E
	.string "There's nothing I love more than\n"
	.string "checking out other people's POKéMON!$"

Route121_Text_29FA64: @ 829FA64
	.string "Super awesome!$"

Route121_Text_29FA73: @ 829FA73
	.string "They're great, your POKéMON!\n"
	.string "How do you raise them?$"

Route121_Text_29FAA7: @ 829FAA7
	.string "I want everybody to see the POKéMON\n"
	.string "I've raised!$"

Route121_Text_29FAD8: @ 829FAD8
	.string "Wow!\n"
	.string "Spectacular!$"

Route121_Text_29FAEA: @ 829FAEA
	.string "I raise every POKéMON with the same\n"
	.string "love and care--I don't pick favorites.$"

Route121_Text_29FB35: @ 829FB35
	.string "My POKéMON have never tasted defeat!\n"
	.string "On their next win, I'm entering them\l"
	.string "in CONTESTS.$"

Route121_Text_29FB8C: @ 829FB8C
	.string "Oh, now what happened here?$"

Route121_Text_29FBA8: @ 829FBA8
	.string "I may have to train my gang some more\n"
	.string "before entering any CONTEST.$"

Route123_Text_29FBEB: @ 829FBEB
	.string "Want to determine how strong you are?\n"
	.string "I'll be the test!$"

Route123_Text_29FC23: @ 829FC23
	.string "You passed with flying colors!$"

Route123_Text_29FC42: @ 829FC42
	.string "To best even me…\n"
	.string "Your strength is marvelous!$"

Route123_Text_29FC6F: @ 829FC6F
	.string "You seem to have a big collection\n"
	.string "of GYM BADGES.\p"
	.string "Let me see if you're actually worthy of\n"
	.string "those BADGES!$"

Route123_Text_29FCD6: @ 829FCD6
	.string "Oh, you're worthy, all right!$"

Route123_Text_29FCF4: @ 829FCF4
	.string "You did your BADGES proud in that\n"
	.string "match!$"

Route123_Text_29FD1D: @ 829FD1D
	.string "They say that good times are filled\n"
	.string "with good aromas.$"

Route123_Text_29FD53: @ 829FD53
	.string "Oh…\n"
	.string "I smell the bitter scent of misery…$"

Route123_Text_29FD7B: @ 829FD7B
	.string "The BERRY MASTER's garden is filled\n"
	.string "with uplifting fragrances.$"

Route123_Text_29FDBA: @ 829FDBA
	.string "Being a psychic is about willpower.\p"
	.string "I've willed myself not to lose to\n"
	.string "anyone. That makes me strong!$"

Route123_Text_29FE1E: @ 829FE1E
	.string "I feel sad…$"

Route123_Text_29FE2A: @ 829FE2A
	.string "Being a psychic is about willpower.\n"
	.string "I thought I wouldn't lose to you…$"

Route123_Text_29FE70: @ 829FE70
	.string "I sense it!\n"
	.string "You and I shall battle again!\l"
	.string "I can't tell if I'll win, though…\p"
	.string "Let's see your POKéNAV.$"

Route123_Text_29FED4: @ 829FED4
	.string "I've convinced myself that I won't\n"
	.string "lose anymore. That makes me strong!$"

Route123_Text_29FF1B: @ 829FF1B
	.string "I feel sad…$"

Route123_Text_29FF27: @ 829FF27
	.string "I should train at MT. PYRE…\n"
	.string "I'll never beat you this way…$"

Route123_Text_29FF61: @ 829FF61
	.string "Don't be too happy if your POKéMON\n"
	.string "develop psychic powers.\p"
	.string "You need to refine those powers to\n"
	.string "make them really useful.$"

Route123_Text_29FFD8: @ 829FFD8
	.string "Overwhelmed!$"

Route123_Text_29FFE5: @ 829FFE5
	.string "We all have psychic powers.\n"
	.string "We've just forgotten how to use them.$"

Route123_Text_2A0027: @ 82A0027
	.string "I would like to face you again.\n"
	.string "Is that okay with you?$"

Route123_Text_2A005E: @ 82A005E
	.string "Have you awoken the psychic powers\n"
	.string "within you?$"

Route123_Text_2A008D: @ 82A008D
	.string "Astounding!$"

Route123_Text_2A0099: @ 82A0099
	.string "Your power with POKéMON…\n"
	.string "That could be a psychic power, too.$"

Route123_Text_2A00D6: @ 82A00D6
	.string "MIU: Hello, TRAINER. I hope your\n"
	.string "POKéMON won't cry when they lose.$"

Route123_Text_2A0119: @ 82A0119
	.string "MIU: Uh-oh, we lost.$"

Route123_Text_2A012E: @ 82A012E
	.string "MIU: TRAINER, your POKéMON are\n"
	.string "strong because you are friends.$"

Route123_Text_2A016D: @ 82A016D
	.string "MIU: It's no fun to battle if you\n"
	.string "don't have two POKéMON.$"

Route123_Text_2A01A7: @ 82A01A7
	.string "YUKI: Okay!\n"
	.string "We're beating the TRAINER's POKéMON!$"

Route123_Text_2A01D8: @ 82A01D8
	.string "YUKI: Uh-oh, we lost.$"

Route123_Text_2A01EE: @ 82A01EE
	.string "YUKI: Why are you so strong?\n"
	.string "We've never lost before.$"

Route123_Text_2A0224: @ 82A0224
	.string "YUKI: It's no fun to battle if you\n"
	.string "don't have two POKéMON.$"

Route123_Text_2A025F: @ 82A025F
	.string "MT. PYRE…\n"
	.string "Where the spirits of POKéMON sleep…\l"
	.string "Will your POKéMON sleep?$"

Route123_Text_2A02A6: @ 82A02A6
	.string "Overflowing with vitality…$"

Route123_Text_2A02C1: @ 82A02C1
	.string "MT. PYRE…\n"
	.string "Where the spirits of POKéMON sleep…\p"
	.string "It must overflow with a power that\n"
	.string "soothes spirits…$"

Route123_Text_2A0323: @ 82A0323
	.string "I'll turn your lights out while\n"
	.string "I rip through this tune!$"

Route123_Text_2A035C: @ 82A035C
	.string "Hey, hold it!\n"
	.string "I was still playing the intro!$"

Route123_Text_2A0389: @ 82A0389
	.string "You're rock steady.\n"
	.string "I'd like to write a tune about you.$"

Route123_Text_2A03C1: @ 82A03C1
	.string "The next time, lend your ears to\n"
	.string "the full tune, will you?$"

Route123_Text_2A03FB: @ 82A03FB
	.string "Today's the day I'm going to do it!\n"
	.string "I'll turn out your lights before\l"
	.string "I finish singing my song!$"

Route123_Text_2A045A: @ 82A045A
	.string "Hey, hold it!\n"
	.string "I haven't even hit the chorus!$"

Route123_Text_2A0487: @ 82A0487
	.string "I thought you'd be so enthralled\n"
	.string "by my tune, you'd lose.$"

Route123_Text_2A04C0: @ 82A04C0
	.string "This is my awesome BUG POKéMON!\n"
	.string "My big brother got it for me.$"

Route123_Text_2A04FE: @ 82A04FE
	.string "Waaaah!\n"
	.string "You meanie!$"

Route123_Text_2A0512: @ 82A0512
	.string "Don't tell my brother I lost.\n"
	.string "You have to keep it a secret!$"

Route123_Text_2A054E: @ 82A054E
	.string "My confidence will get a boost by\n"
	.string "beating someone obviously strong!$"

Route123_Text_2A0592: @ 82A0592
	.string "There goes my confidence…$"

Route123_Text_2A05AC: @ 82A05AC
	.string "They say that you can't judge a person\n"
	.string "by their appearance.\p"
	.string "But often, their looks don't lie…$"

Route123_Text_2A060A: @ 82A060A
	.string "Hello, child!\n"
	.string "Can you spare some time?$"

Route123_Text_2A0631: @ 82A0631
	.string "Ah, a mighty capable child!\n"
	.string "Let me contribute to your allowance.$"

Route123_Text_2A0672: @ 82A0672
	.string "Contribute to your allowance?\n"
	.string "Wasn't the prize money enough?$"

Route123_Text_2A06AF: @ 82A06AF
	.string "I have to tell you, BIRD POKéMON\n"
	.string "are my obsession!\p"
	.string "Birds are cool!\n"
	.string "They're the best!$"

Route123_Text_2A0704: @ 82A0704
	.string "Even in defeat, BIRD POKéMON are cool!$"

Route123_Text_2A072B: @ 82A072B
	.string "I gather BIRD POKéMON feathers that\n"
	.string "scatter during battles.\p"
	.string "I'm going to make a hat with\n"
	.string "BIRD POKéMON feathers.$"

Route123_Text_2A079B: @ 82A079B
	.string "When there are no TRAINERS around,\n"
	.string "I let my POKéMON battle each other.\l"
	.string "I watch them.$"

Route123_Text_2A07F0: @ 82A07F0
	.string "I kind of like your POKéMON.$"

Route123_Text_2A080D: @ 82A080D
	.string "Hehe, I'm swiping your battling ideas!\n"
	.string "I think they'll make me better.$"

Route123_Text_2A0854: @ 82A0854
	.string "I lay in ambush, and a TRAINER has\n"
	.string "landed in my trap!$"

Route123_Text_2A088A: @ 82A088A
	.string "If you don't lose, how am I supposed\n"
	.string "to have fun playing ninja?$"

Route123_Text_2A08CA: @ 82A08CA
	.string "I'm going to ambush a weaker-looking\n"
	.string "TRAINER next time.$"

Route123_Text_2A0902: @ 82A0902
	.string "I just bought this parasol.\n"
	.string "My cuteness should be up by a third!$"

Route123_Text_2A0943: @ 82A0943
	.string "You're better than me by about\n"
	.string "five times!$"

Route123_Text_2A096E: @ 82A096E
	.string "Using accessories effectively is\n"
	.string "the secret behind fashion appeal.$"

Route124_Text_2A09B1: @ 82A09B1
	.string "Hey, are you lost at sea?\p"
	.string "If you can beat my POKéMON,\n"
	.string "I can serve as your pilot.$"

Route124_Text_2A0A02: @ 82A0A02
	.string "I lost my bearings in battle!$"

Route124_Text_2A0A20: @ 82A0A20
	.string "Many people lose their bearings at sea.\p"
	.string "If you're that sort, you should refer\n"
	.string "to the POKéNAV's MAP.$"

Route124_Text_2A0A84: @ 82A0A84
	.string "Hm! You're riding a POKéMON instead\n"
	.string "of swimming yourself…\p"
	.string "I am envious!$"

Route124_Text_2A0ACC: @ 82A0ACC
	.string "Oh!\n"
	.string "I can't…$"

Route124_Text_2A0AD9: @ 82A0AD9
	.string "I'm getting chilled…\n"
	.string "I've been in the water too long…\p"
	.string "I wish I could ride a POKéMON like you…$"

Route124_Text_2A0B37: @ 82A0B37
	.string "If you just float in the sea like\n"
	.string "this, POKéMON come around to play.$"

Route124_Text_2A0B7C: @ 82A0B7C
	.string "Oh, darn.\n"
	.string "I've gone and lost.$"

Route124_Text_2A0B9A: @ 82A0B9A
	.string "While swimming, I noticed that some\n"
	.string "POKéMON attack, and some just watch.\p"
	.string "I guess POKéMON have personalities\n"
	.string "of their own.$"

Route124_Text_2A0C14: @ 82A0C14
	.string "It's only on a whim, but maybe I'll get\n"
	.string "you to register me in your POKéNAV.$"

Route124_Text_2A0C60: @ 82A0C60
	.string "If you just float in the sea like this,\n"
	.string "TRAINERS challenge you!$"

Route124_Text_2A0CA0: @ 82A0CA0
	.string "That's strange…\n"
	.string "I lost again…$"

Route124_Text_2A0CBE: @ 82A0CBE
	.string "This has nothing to do with anything,\n"
	.string "but maybe I'll visit the TRICK HOUSE.$"

Route124_Text_2A0D0A: @ 82A0D0A
	.string "I'm growing bored of swimming…\n"
	.string "How about a battle?$"

Route124_Text_2A0D3D: @ 82A0D3D
	.string "I had no idea that you were\n"
	.string "this strong!$"

Route124_Text_2A0D66: @ 82A0D66
	.string "All the effort you put in must have\n"
	.string "made you this strong.$"

Route124_Text_2A0DA0: @ 82A0DA0
	.string "Fufufufu… I dive deep underwater\n"
	.string "to go deep under cover.\l"
	.string "Plumbing the depths is where I excel!$"

Route124_Text_2A0DFF: @ 82A0DFF
	.string "Glub, glub, glub…\n"
	.string "I'm sinking…$"

Route124_Text_2A0E1E: @ 82A0E1E
	.string "I have it on good authority that\n"
	.string "there's a DIVE spot around here.\p"
	.string "It gives me the urge to go deep\n"
	.string "again…$"

Route124_Text_2A0E87: @ 82A0E87
	.string "LILA: Sigh…\p"
	.string "Here I am in the sea, but who's with me?\n"
	.string "My little brother!\p"
	.string "Let's battle so I won't have to dwell\n"
	.string "on that!$"

Route124_Text_2A0EFE: @ 82A0EFE
	.string "LILA: ROY! It's your fault we lost!\n"
	.string "You're in for it later!$"

Route124_Text_2A0F3A: @ 82A0F3A
	.string "LILA: Sigh…\p"
	.string "If only it wasn't my little brother\n"
	.string "next to me, but a nice boyfriend…$"

Route124_Text_2A0F8C: @ 82A0F8C
	.string "LILA: You're planning to battle us?\n"
	.string "Not unless you have two POKéMON.$"

Route124_Text_2A0FD1: @ 82A0FD1
	.string "ROY: My big sister is tough at POKéMON!\p"
	.string "Don't cry when you lose!$"

Route124_Text_2A1012: @ 82A1012
	.string "ROY: Uh-oh…\n"
	.string "My big sister will chew me out…$"

Route124_Text_2A103E: @ 82A103E
	.string "ROY: My big sister is really scary\n"
	.string "when she gets angry.\p"
	.string "That's why she doesn't have a\n"
	.string "boyfriend.$"

Route124_Text_2A109F: @ 82A109F
	.string "ROY: Will you battle with us again?\n"
	.string "But take it easy next time, okay?$"

Route124_Text_2A10E5: @ 82A10E5
	.string "ROY: Did you want to battle us?\n"
	.string "Bring two POKéMON, then.$"

Route124_Text_2A111E: @ 82A111E
	.string "LILA: Sigh…\p"
	.string "Here I am in the sea, but who's with me?\n"
	.string "My little brother!\p"
	.string "Oh, hi, it's been a while. Let's battle\n"
	.string "so I won't have to dwell on things!$"

Route124_Text_2A11B2: @ 82A11B2
	.string "LILA: ROY!\n"
	.string "It's your fault we lost again!\p"
	.string "We're having a training session later!$"

Route124_Text_2A1203: @ 82A1203
	.string "LILA: Sigh…\p"
	.string "If I had a nice boyfriend, we'd beat\n"
	.string "anyone with lovely combinations…$"

Route124_Text_2A1255: @ 82A1255
	.string "LILA: You're planning to battle us?\n"
	.string "Not unless you have two POKéMON.$"

Route124_Text_2A129A: @ 82A129A
	.string "ROY: If we lose, I'll catch heck.\n"
	.string "I'm going to go totally all out!$"

Route124_Text_2A12DD: @ 82A12DD
	.string "ROY: Uh-oh…\n"
	.string "My big sister will chew me out again.$"

Route124_Text_2A130F: @ 82A130F
	.string "ROY: My big sister is really scary\n"
	.string "when she gets angry.\p"
	.string "She's going to make me train really\n"
	.string "hard with POKéMON later…$"

Route124_Text_2A1384: @ 82A1384
	.string "ROY: Did you want to battle us?\n"
	.string "Bring two POKéMON, then.$"

Route124_Text_2A13BD: @ 82A13BD
	.string "Here I am swimming by my lonesome\n"
	.string "on this wide, beautiful sea.\p"
	.string "There's no other word for it.\n"
	.string "This is pathetic!$"

Route124_Text_2A142C: @ 82A142C
	.string "I'm feeling blue.\n"
	.string "Blue as the sky…$"

Route124_Text_2A144F: @ 82A144F
	.string "I should chat up lady SWIMMERS\n"
	.string "and invite them on a long swim.$"

Route124_Text_2A148E: @ 82A148E
	.string "I'm not going to lose to some\n"
	.string "surfer TRAINER.$"

Route124_Text_2A14BC: @ 82A14BC
	.string "I've only got sweat in my eyes!\n"
	.string "I am not crying!$"

Route124_Text_2A14ED: @ 82A14ED
	.string "You can find pretty colored shards\n"
	.string "of things around here.$"

Route125_Text_2A1527: @ 82A1527
	.string "I heard you approaching, so I hung\n"
	.string "around for you!$"

Route125_Text_2A155A: @ 82A155A
	.string "I surrender!$"

Route125_Text_2A1567: @ 82A1567
	.string "Sound travels faster in water than\n"
	.string "it does through air.$"

Route125_Text_2A159F: @ 82A159F
	.string "Hey, there!\n"
	.string "Check out my sweet POKéMON!$"

Route125_Text_2A15C7: @ 82A15C7
	.string "I floundered…$"

Route125_Text_2A15D5: @ 82A15D5
	.string "I was blown away by HORSEA's charm,\n"
	.string "so I started swimming, too.$"

Route125_Text_2A1615: @ 82A1615
	.string "I'm tired of swimming.\n"
	.string "Are you up for a battle with me?$"

Route125_Text_2A164D: @ 82A164D
	.string "You're too much!$"

Route125_Text_2A165E: @ 82A165E
	.string "Whew…\n"
	.string "Which way is it to MOSSDEEP CITY?$"

Route125_Text_2A1686: @ 82A1686
	.string "How would you like to take on the\n"
	.string "WATER-type POKéMON I raised?$"

Route125_Text_2A16C5: @ 82A16C5
	.string "Lost it…$"

Route125_Text_2A16CE: @ 82A16CE
	.string "Your power… You're the real deal.\n"
	.string "I'm amazed!$"

Route125_Text_2A16FC: @ 82A16FC
	.string "Ahoy! I'm a buff, tough SAILOR!\n"
	.string "I've braved the world's seas!$"

Route125_Text_2A173A: @ 82A173A
	.string "Gwrroooar!\n"
	.string "I couldn't win!$"

Route125_Text_2A1755: @ 82A1755
	.string "The tide ebbs and flows inside the\n"
	.string "SHOAL CAVE.\p"
	.string "By the way, it's about six hours from\n"
	.string "high tide to low tide. Did you know?$"

Route125_Text_2A17CF: @ 82A17CF
	.string "Register me in your POKéNAV,\n"
	.string "and I'll tell you something good.$"

Route125_Text_2A180E: @ 82A180E
	.string "It's high time I get my payback\n"
	.string "from you! Come on, we're battling!$"

Route125_Text_2A1851: @ 82A1851
	.string "I couldn't win!\n"
	.string "I flat out couldn't win!$"

Route125_Text_2A187A: @ 82A187A
	.string "The SHOAL CAVE…\p"
	.string "There are places you can and can't\n"
	.string "get to depending on the rise and fall\l"
	.string "of the tide.\p"
	.string "By the way, it's about six hours from\n"
	.string "high tide to low tide. Don't forget!$"

Route125_Text_2A192B: @ 82A192B
	.string "KIM: A funny old man lives in the\n"
	.string "SHOAL CAVE. Someone told me.\l"
	.string "Are you going to see him, too?$"

Route125_Text_2A1989: @ 82A1989
	.string "KIM: I thought we would win.$"

Route125_Text_2A19A6: @ 82A19A6
	.string "KIM: A funny old man lives in the\n"
	.string "SHOAL CAVE, doesn't he?\p"
	.string "Let's go see him, IRIS!$"

Route125_Text_2A19F8: @ 82A19F8
	.string "KIM: No, no, no! You need two POKéMON,\n"
	.string "or it's just no good!$"

Route125_Text_2A1A35: @ 82A1A35
	.string "IRIS: KIM, can you tell me what we're\n"
	.string "looking for out here?$"

Route125_Text_2A1A71: @ 82A1A71
	.string "IRIS: Oh, we came sort of close.$"

Route125_Text_2A1A92: @ 82A1A92
	.string "IRIS: KIM, are we really going into\n"
	.string "the SHOAL CAVE?\l"
	.string "We'll get all wet.$"

Route125_Text_2A1AD9: @ 82A1AD9
	.string "IRIS: Oh, we could never, ever do\n"
	.string "anything like a 2-on-1 battle.$"

Route125_Text_2A1B1A: @ 82A1B1A
	.string "Why would a BIRDKEEPER like me\n"
	.string "come out to the sea?$"

Route125_Text_2A1B4E: @ 82A1B4E
	.string "Okay.\n"
	.string "I'll tell you why I'm here.$"

Route125_Text_2A1B70: @ 82A1B70
	.string "I put a message in a bottle and put\n"
	.string "it out to sea.\p"
	.string "I'm sure that a girl SWIMMER will\n"
	.string "find it!$"

Route125_Text_2A1BCE: @ 82A1BCE
	.string "Hey! Was it you throwing garbage\n"
	.string "into the sea?$"

Route125_Text_2A1BFD: @ 82A1BFD
	.string "Oh, you weren't throwing trash into\n"
	.string "the sea.$"

Route125_Text_2A1C2A: @ 82A1C2A
	.string "I found an unsightly bottle bobbing\n"
	.string "in the waves earlier.\p"
	.string "It angers me that someone would\n"
	.string "pollute the sea!$"

Route126_Text_2A1C95: @ 82A1C95
	.string "Swimming is a full-body workout!\n"
	.string "You will get fit!$"

Route126_Text_2A1CC8: @ 82A1CC8
	.string "I admit it!\n"
	.string "You win!$"

Route126_Text_2A1CDD: @ 82A1CDD
	.string "Thanks to my daily swimming routine…\n"
	.string "Look! Feast your eyes on this physique!$"

Route126_Text_2A1D2A: @ 82A1D2A
	.string "This towering white mountain of rock\n"
	.string "is SOOTOPOLIS CITY.$"

Route126_Text_2A1D63: @ 82A1D63
	.string "I was done in?$"

Route126_Text_2A1D72: @ 82A1D72
	.string "I can't find the entrance to\n"
	.string "SOOTOPOLIS. Where could it be?$"

Route126_Text_2A1DAE: @ 82A1DAE
	.string "Ufufufufu!\n"
	.string "I'm a mermaid!$"

Route126_Text_2A1DC8: @ 82A1DC8
	.string "My fantasy burst as if it were a bubble!\n"
	.string "Blub, blub, blub…$"

Route126_Text_2A1E03: @ 82A1E03
	.string "You thrashed me… I want to\n"
	.string "disappear in a wave of despair…$"

Route126_Text_2A1E3E: @ 82A1E3E
	.string "Hello, kiddo!\n"
	.string "Want a battle with me?$"

Route126_Text_2A1E63: @ 82A1E63
	.string "Oh, noooooh!$"

Route126_Text_2A1E70: @ 82A1E70
	.string "I love frolicking with POKéMON in\n"
	.string "the sea like this!$"

Route126_Text_2A1EA5: @ 82A1EA5
	.string "Check out this sculpted body!\n"
	.string "I'm more cut than a BLACK BELT!$"

Route126_Text_2A1EE3: @ 82A1EE3
	.string "Whoops! Too strong!\n"
	.string "Not bad! Not bad at all!$"

Route126_Text_2A1F10: @ 82A1F10
	.string "Losing to you stimulated my senses!\n"
	.string "I'll train myself and POKéMON harder!$"

Route126_Text_2A1F5A: @ 82A1F5A
	.string "Yep, you're not bad at all!\n"
	.string "I'd like to get to know you more!$"

Route126_Text_2A1F98: @ 82A1F98
	.string "Check out this beautiful body!\n"
	.string "I'm more shapely than a SWIMMER!$"

Route126_Text_2A1FD8: @ 82A1FD8
	.string "Whoops! Really too strong!\n"
	.string "Not bad! Not bad at all!$"

Route126_Text_2A200C: @ 82A200C
	.string "I'm going to train even harder!\n"
	.string "You're a great motivator!\l"
	.string "You have to come back again!$"

Route126_Text_2A2063: @ 82A2063
	.string "I couldn't even swim last year,\n"
	.string "but now I'm a decent SWIMMER.\p"
	.string "I think I'm capable of anything now.$"

Route126_Text_2A20C6: @ 82A20C6
	.string "Sheesh, getting greedy didn't do\n"
	.string "a thing for me.$"

Route126_Text_2A20F7: @ 82A20F7
	.string "If you practice at something,\n"
	.string "you will get better at it.\p"
	.string "You're young--don't be afraid to\n"
	.string "try all sorts of things!$"

Route126_Text_2A216A: @ 82A216A
	.string "If seawater gets up your nose,\n"
	.string "doesn't it feel terrible?$"

Route126_Text_2A21A3: @ 82A21A3
	.string "Ack! Why, you…\n"
	.string "Glub!$"

Route126_Text_2A21B8: @ 82A21B8
	.string "Ooh, I choked on some water!\n"
	.string "It's bitter! It's salty!!$"

Route126_Text_2A21EF: @ 82A21EF
	.string "I'm throwing my whole heart\n"
	.string "into this!$"

Route126_Text_2A2216: @ 82A2216
	.string "You had more heart!$"

Route126_Text_2A222A: @ 82A222A
	.string "I need to cool down now…\n"
	.string "I think I'll go for a dive.$"

Route127_Text_2A225F: @ 82A225F
	.string "I can see it in your face.\n"
	.string "You want to challenge me.$"

Route127_Text_2A2294: @ 82A2294
	.string "Awawawawawa…$"

Route127_Text_2A22A1: @ 82A22A1
	.string "A well-played match leaves me feeling\n"
	.string "refreshed and serene.$"

Route127_Text_2A22DD: @ 82A22DD
	.string "Do you have a rival whom you just\n"
	.string "hate to lose against?$"

Route127_Text_2A2315: @ 82A2315
	.string "Arrrgh!\n"
	.string "I hate losing!$"

Route127_Text_2A232C: @ 82A232C
	.string "If you have a rival, don't you get the\n"
	.string "feeling that you have to keep getting\l"
	.string "better?$"

Route127_Text_2A2381: @ 82A2381
	.string "Through fishing, I have attained a\n"
	.string "state of becalmed serenity…\p"
	.string "Please, allow me to demonstrate…$"

Route127_Text_2A23E1: @ 82A23E1
	.string "Though I have lost, my heart remains\n"
	.string "calm…$"

Route127_Text_2A240C: @ 82A240C
	.string "It matters not that I catch nothing.\n"
	.string "The line remains in the water…$"

Route127_Text_2A2450: @ 82A2450
	.string "Whoops! Don't tell me I snagged\n"
	.string "a SURFING POKéMON?$"

Route127_Text_2A2483: @ 82A2483
	.string "I can't keep up!$"

Route127_Text_2A2494: @ 82A2494
	.string "It'd be a handful if I hooked\n"
	.string "your tough POKéMON!$"

Route127_Text_2A24C6: @ 82A24C6
	.string "Well, hey! This is a match between\n"
	.string "a POKéMON fan and a fishing buff!$"

Route127_Text_2A250B: @ 82A250B
	.string "No! My line's all tangled!\n"
	.string "The party's over!$"

Route127_Text_2A2538: @ 82A2538
	.string "My fishing line's doing a dance!\n"
	.string "The tangle tango! Hahaha, snarl!$"

Route127_Text_2A257A: @ 82A257A
	.string "BIRD POKéMON have excellent vision.\n"
	.string "They spot prey from great heights.$"

Route127_Text_2A25C1: @ 82A25C1
	.string "Whew… I give up.$"

Route127_Text_2A25D2: @ 82A25D2
	.string "There're lots of diving spots in\n"
	.string "the sea around here.\p"
	.string "You can spot them easily from the sky\n"
	.string "because of their darker color.$"

Route127_Text_2A264D: @ 82A264D
	.string "Run in your bare feet.\n"
	.string "That will toughen up your soles!$"

Route127_Text_2A2685: @ 82A2685
	.string "Yowch!\n"
	.string "I got a pebble under a toenail!$"

Route127_Text_2A26AC: @ 82A26AC
	.string "Going barefoot feels great.\n"
	.string "But your RUNNING SHOES are cool, too.$"

Route127_Text_2A26EE: @ 82A26EE
	.string "This is what I do to people who beat me!\n"
	.string "I hope we can do this again.$"

Route127_Text_2A2734: @ 82A2734
	.string "I still run in my bare feet daily.\n"
	.string "My soles are tough!$"

Route127_Text_2A276B: @ 82A276B
	.string "Yowch!\n"
	.string "Pebbles dug into my arches!$"

Route127_Text_2A278E: @ 82A278E
	.string "Want to go barefoot for a while?\n"
	.string "So I can try your RUNNING SHOES?$"

Route127_Text_2A27D0: @ 82A27D0
	.string "We should have a slow and methodical\n"
	.string "match.$"

Route127_Text_2A27FC: @ 82A27FC
	.string "You didn't give me the chance to\n"
	.string "do any strategizing.$"

Route127_Text_2A2832: @ 82A2832
	.string "When I'm surrounded by the blue sea\n"
	.string "and sky, it feels as if time slows down.$"

Route128_Text_2A287F: @ 82A287F
	.string "EVER GRANDE CITY is still a long ways\n"
	.string "away…$"

Route128_Text_2A28AB: @ 82A28AB
	.string "My first victory seems to be far\n"
	.string "away, too…$"

Route128_Text_2A28D7: @ 82A28D7
	.string "My whole life has been about losing,\n"
	.string "but I will never give up!$"

Route128_Text_2A2916: @ 82A2916
	.string "I know I'm not good now, but I think\n"
	.string "I can win eventually.\p"
	.string "Please register me in your POKéNAV.$"

Route128_Text_2A2975: @ 82A2975
	.string "I'm still feeling good. I'll keep on\n"
	.string "swimming to EVER GRANDE CITY.$"

Route128_Text_2A29B8: @ 82A29B8
	.string "I've yet to taste my first victory…$"

Route128_Text_2A29DC: @ 82A29DC
	.string "I'll eventually reach EVER GRANDE CITY\n"
	.string "where I can eventually win…$"

Route128_Text_2A2A1F: @ 82A2A1F
	.string "You have to swim, cycle, and then run\n"
	.string "a marathon in a triathlon.\p"
	.string "It's a grueling race that consists\n"
	.string "of three events.$"

Route128_Text_2A2A94: @ 82A2A94
	.string "A POKéMON battle is grueling, too…$"

Route128_Text_2A2AB7: @ 82A2AB7
	.string "I have to ride a BIKE next, but…\n"
	.string "I'm about to throw in the towel…$"

Route128_Text_2A2AF9: @ 82A2AF9
	.string "Well, I may as well make the best\n"
	.string "of this. I'd like a rematch sometime.$"

Route128_Text_2A2B41: @ 82A2B41
	.string "A triathlon is long. But I guess the\n"
	.string "road to become the POKéMON CHAMPION\l"
	.string "is also a long and grueling one.$"

Route128_Text_2A2BAB: @ 82A2BAB
	.string "A POKéMON battle really is harsh\n"
	.string "and unforgiving…$"

Route128_Text_2A2BDD: @ 82A2BDD
	.string "You should give serious thought to\n"
	.string "challenges on VICTORY ROAD.$"

Route128_Text_2A2C1C: @ 82A2C1C
	.string "We've been working so hard to mount\n"
	.string "a POKéMON LEAGUE challenge…\p"
	.string "We can't afford to lose now!$"

Route128_Text_2A2C79: @ 82A2C79
	.string "Oh!\n"
	.string "How could this happen?!$"

Route128_Text_2A2C95: @ 82A2C95
	.string "After all I've done to get here,\n"
	.string "I won't give up after one setback.$"

Route128_Text_2A2CD9: @ 82A2CD9
	.string "There is no stronger TRAINER than I!$"

Route128_Text_2A2CFE: @ 82A2CFE
	.string "This can't be!$"

Route128_Text_2A2D0D: @ 82A2D0D
	.string "There probably is no stronger TRAINER\n"
	.string "than you!$"

Route128_Text_2A2D3D: @ 82A2D3D
	.string "I want to visit EVER GRANDE, so I\n"
	.string "caught myself a POKéMON that knows\l"
	.string "the move WATERFALL to crest the falls.$"

Route128_Text_2A2DA9: @ 82A2DA9
	.string "I'm crestfallen!$"

Route128_Text_2A2DBA: @ 82A2DBA
	.string "Awww, phooey!\p"
	.string "My POKéMON knows WATERFALL, but\n"
	.string "I don't have the SOOTOPOLIS GYM BADGE!$"

Route128_Text_2A2E0F: @ 82A2E0F
	.string "You're looking awfully tough.\n"
	.string "I wonder if I can win?$"

Route128_Text_2A2E44: @ 82A2E44
	.string "Ouch!\n"
	.string "I guess it was impossible to win.$"

Route128_Text_2A2E6C: @ 82A2E6C
	.string "There are tough TRAINERS galore\n"
	.string "around EVER GRANDE.\p"
	.string "Do you think I may be out\n"
	.string "of my league?$"

Route128_Text_2A2EC8: @ 82A2EC8
	.string "The sunlight seems to be more harsh\n"
	.string "in this area.$"

Route128_Text_2A2EFA: @ 82A2EFA
	.string "I couldn't see very well because of\n"
	.string "the sun's glare.$"

Route128_Text_2A2F2F: @ 82A2F2F
	.string "I should go back soon.\n"
	.string "I need to reapply my sunscreen.$"

Route129_Text_2A2F66: @ 82A2F66
	.string "This is my first triathlon.\n"
	.string "I'm all tense and nervous!$"

Route129_Text_2A2F9D: @ 82A2F9D
	.string "Wroooaaar!\n"
	.string "I failed to win!$"

Route129_Text_2A2FB9: @ 82A2FB9
	.string "If I'm all tensed up, I won't be able to\n"
	.string "give it my all.$"

Route129_Text_2A2FF2: @ 82A2FF2
	.string "I'm in the middle of a triathlon,\n"
	.string "but, sure, why don't we battle?$"

Route129_Text_2A3034: @ 82A3034
	.string "I was sure I'd win!$"

Route129_Text_2A3048: @ 82A3048
	.string "Do you know what's the greatest thing\n"
	.string "about triathlons?\p"
	.string "Testing the limits of your own\n"
	.string "strength and endurance against\l"
	.string "Mother Nature!$"

Route129_Text_2A30CD: @ 82A30CD
	.string "Say hey, hey!\n"
	.string "Let's get on with it!$"

Route129_Text_2A30F1: @ 82A30F1
	.string "Beat, I'm beaten.\n"
	.string "That's it, done!$"

Route129_Text_2A3114: @ 82A3114
	.string "There's nothing for a loser.\n"
	.string "Time for me to beat it home.$"

Route129_Text_2A314E: @ 82A314E
	.string "What's the hurry?\n"
	.string "Let's take it slow and easy.$"

Route129_Text_2A317D: @ 82A317D
	.string "Oh, my.\n"
	.string "I wanted to relax a little more…$"

Route129_Text_2A31A6: @ 82A31A6
	.string "Don't you hate making mistakes when\n"
	.string "you're in a rush?\p"
	.string "That's why I try to take things\n"
	.string "slowly.$"

Route129_Text_2A3204: @ 82A3204
	.string "Surfing isn't as easy as it seems,\n"
	.string "isn't that right?$"

Route129_Text_2A3239: @ 82A3239
	.string "Winning sure isn't easy.$"

Route129_Text_2A3252: @ 82A3252
	.string "You have your sights on the POKéMON\n"
	.string "LEAGUE? Keep at it!$"

Route130_Text_2A328A: @ 82A328A
	.string "What a surprise! I didn't expect to\n"
	.string "see a TRAINER out in the sea.\p"
	.string "I think we should battle!$"

Route130_Text_2A32E6: @ 82A32E6
	.string "This kid's awfully tough…$"

Route130_Text_2A3300: @ 82A3300
	.string "Your eyes have that look of someone\n"
	.string "who's experienced harsh challenges\l"
	.string "and won. It suits you well!$"

Route130_Text_2A3363: @ 82A3363
	.string "In the deep blue sea,\n"
	.string "my shattered blue heart finds\l"
	.string "comfort among waves.$"

Route130_Text_2A33AC: @ 82A33AC
	.string "Like the vast blue sea,\n"
	.string "the world of POKéMON spans\l"
	.string "depths beyond belief.$"

Route130_Text_2A33F5: @ 82A33F5
	.string "The world's children dream\n"
	.string "of one day becoming\l"
	.string "the POKéMON CHAMPION.$"

Route130_Text_2A343A: @ 82A343A
	.string "Floating on the open sea like this…\n"
	.string "It's peaceful.$"

Route130_Text_2A346D: @ 82A346D
	.string "I needed to be a little less peaceful!$"

Route130_Text_2A3494: @ 82A3494
	.string "Swimming and battling like this…\n"
	.string "I'm one happy guy…$"

Route131_Text_2A34C8: @ 82A34C8
	.string "The sea is teeming with POKéMON.\n"
	.string "It's not easy swimming, I tell you.$"

Route131_Text_2A350D: @ 82A350D
	.string "POKéMON raised by TRAINERS are\n"
	.string "seriously tough…$"

Route131_Text_2A353D: @ 82A353D
	.string "Gasp… Gasp…\n"
	.string "I'm wiped out…\p"
	.string "The going's easy. It's the leaving\n"
	.string "that's the hard part.\p"
	.string "Will I have any energy left to make\n"
	.string "the return trip?$"

Route131_Text_2A35C6: @ 82A35C6
	.string "The sea… The sea… The sea…\n"
	.string "The sea as far as these eyes can see!\l"
	.string "I'm sick and tired of the sea!$"

Route131_Text_2A3626: @ 82A3626
	.string "Bleah!$"

Route131_Text_2A362D: @ 82A362D
	.string "Bored I am by the sea, but swim I must.\p"
	.string "I'm a born swimmer!\n"
	.string "That's what I am.$"

Route131_Text_2A367B: @ 82A367B
	.string "Hi, sweetie, wait!\n"
	.string "We should battle, you and I!$"

Route131_Text_2A36AB: @ 82A36AB
	.string "You're tough in spite of the way\n"
	.string "you look!$"

Route131_Text_2A36D6: @ 82A36D6
	.string "Did you see a guy over there who whines\n"
	.string "that he's bored of the sea?\p"
	.string "That's all talk.\n"
	.string "He's hopelessly in love with the sea!$"

Route131_Text_2A3751: @ 82A3751
	.string "Why do men love bathing suits so much?\p"
	.string "They all ogle me!$"

Route131_Text_2A378A: @ 82A378A
	.string "I'm out of my depth!$"

Route131_Text_2A379F: @ 82A379F
	.string "Maybe it's not my bathing suit that\n"
	.string "makes men look. It must be my beauty!$"

Route131_Text_2A37E9: @ 82A37E9
	.string "RELI: We'll work together as siblings\n"
	.string "to take you on!$"

Route131_Text_2A381F: @ 82A381F
	.string "RELI: We couldn't win even though we\n"
	.string "worked together…$"

Route131_Text_2A3855: @ 82A3855
	.string "RELI: The people of PACIFIDLOG are\n"
	.string "together with the sea and POKéMON from\l"
	.string "the time they are born.$"

Route131_Text_2A38B7: @ 82A38B7
	.string "RELI: You don't have two POKéMON?\n"
	.string "We can't enjoy a battle, then.$"

Route131_Text_2A38F8: @ 82A38F8
	.string "IAN: I'm doing my best together with\n"
	.string "my sis!$"

Route131_Text_2A3925: @ 82A3925
	.string "IAN: I did my best with my sis,\n"
	.string "but we still couldn't win…$"

Route131_Text_2A3960: @ 82A3960
	.string "IAN: You know how PACIFIDLOG is\n"
	.string "a floating town?\p"
	.string "So, wherever there is the sea,\n"
	.string "that's a part of PACIFIDLOG!$"

Route131_Text_2A39CD: @ 82A39CD
	.string "IAN: If you have two POKéMON,\n"
	.string "we'll take you on!$"

Route131_Text_2A39FE: @ 82A39FE
	.string "If you can beat me, I'll give you some\n"
	.string "great information!$"

Route131_Text_2A3A38: @ 82A3A38
	.string "Oh?\n"
	.string "Did I lose?$"

Route131_Text_2A3A48: @ 82A3A48
	.string "There is an odd place nearby.\n"
	.string "There's a huge tower there.\l"
	.string "Why don't you go take a look?$"

Route131_Text_2A3AA0: @ 82A3AA0
	.string "The people of PACIFIDLOG are\n"
	.string "a peaceful bunch.\p"
	.string "They never get angry.\n"
	.string "That goes for me, too.$"

Route131_Text_2A3AFC: @ 82A3AFC
	.string "Oops!$"

Route131_Text_2A3B02: @ 82A3B02
	.string "Tch! …Oh, wait.\n"
	.string "I'm not angry. Honestly!\p"
	.string "But, boy, you're strong!\n"
	.string "Hahaha!$"

Route132_Text_2A3B4C: @ 82A3B4C
	.string "I used to catch colds all the time as\n"
	.string "a kid, but I became totally fit after\l"
	.string "I started swimming.$"

Route132_Text_2A3BAC: @ 82A3BAC
	.string "I crave more power…$"

Route132_Text_2A3BC0: @ 82A3BC0
	.string "TRAINERS travel the fields and\n"
	.string "mountains, so they must be fit, too.$"

Route132_Text_2A3C04: @ 82A3C04
	.string "I try not to swim where the currents\n"
	.string "are too strong.$"

Route132_Text_2A3C39: @ 82A3C39
	.string "Oh, please, no!$"

Route132_Text_2A3C49: @ 82A3C49
	.string "If I get swept away, I'll lose all my\n"
	.string "sense of place…$"

Route132_Text_2A3C7F: @ 82A3C7F
	.string "Win or lose, you'll never know until\n"
	.string "you try!$"

Route132_Text_2A3CAD: @ 82A3CAD
	.string "Waah!\n"
	.string "I sank in defeat!$"

Route132_Text_2A3CC5: @ 82A3CC5
	.string "I never battle when I know I'll win.\n"
	.string "I like to battle at the razor's edge of\l"
	.string "victory and defeat!$"

Route132_Text_2A3D26: @ 82A3D26
	.string "I contemplate POKéMON 24 hours a day.\n"
	.string "How could you possibly beat me?$"

Route132_Text_2A3D6C: @ 82A3D6C
	.string "I lose.\n"
	.string "I will concede defeat.$"

Route132_Text_2A3D8B: @ 82A3D8B
	.string "Urggh…\n"
	.string "You're a POKéMON fanatic, aren't you?\p"
	.string "You must contemplate POKéMON 24 hours\n"
	.string "a day, don't you?$"

Route132_Text_2A3DF0: @ 82A3DF0
	.string "I'm always with my husband,\n"
	.string "but I can win even without him.$"

Route132_Text_2A3E2C: @ 82A3E2C
	.string "Oh, I guess I wasn't good enough.$"

Route132_Text_2A3E4E: @ 82A3E4E
	.string "That young man over there looks just\n"
	.string "like my husband when he was young.\p"
	.string "He's making me blush!$"

Route132_Text_2A3EAC: @ 82A3EAC
	.string "Someone's been watching me intently.\n"
	.string "Was it you?$"

Route132_Text_2A3EDD: @ 82A3EDD
	.string "Wow!\n"
	.string "That's pretty strong, all right!$"

Route132_Text_2A3F03: @ 82A3F03
	.string "I can't shake this feeling that\n"
	.string "someone's watching me.\p"
	.string "I can't concentrate!$"

Route132_Text_2A3F4F: @ 82A3F4F
	.string "Now where could my wife have gone?\n"
	.string "I'm always with her.\l"
	.string "I wonder if I can win on my own.$"

Route132_Text_2A3FA8: @ 82A3FA8
	.string "Ah, I see that I couldn't manage\n"
	.string "to win on my own after all.$"

Route132_Text_2A3FE5: @ 82A3FE5
	.string "My wife must be looking for me.\n"
	.string "I'd best go find her right away.$"

Route132_Text_2A4026: @ 82A4026
	.string "I liked training here by myself.\n"
	.string "It's awful that all these people came!$"

Route132_Text_2A406E: @ 82A406E
	.string "Okay! I won't complain about other\n"
	.string "people being here.$"

Route132_Text_2A40A4: @ 82A40A4
	.string "I suppose I can partner up with that\n"
	.string "old man and challenge that other team.$"

Route133_Text_2A40F0: @ 82A40F0
	.string "Did the currents carry you here, too?\n"
	.string "This must have been fated.\l"
	.string "Let's battle!$"

Route133_Text_2A413F: @ 82A413F
	.string "Strong!\n"
	.string "Too much so!$"

Route133_Text_2A4154: @ 82A4154
	.string "It's just my luck that a tough TRAINER\n"
	.string "like you would drift here…\l"
	.string "I must be cursed…$"

Route133_Text_2A41A8: @ 82A41A8
	.string "I've led a life of woe and misery…\n"
	.string "I've been cast away, and this is where\l"
	.string "I've drifted…$"

Route133_Text_2A4200: @ 82A4200
	.string "Another loss…$"

Route133_Text_2A420E: @ 82A420E
	.string "A life adrift…\n"
	.string "I don't want it anymore!$"

Route133_Text_2A4236: @ 82A4236
	.string "Welcome!\n"
	.string "I've been expecting you!$"

Route133_Text_2A4258: @ 82A4258
	.string "No! Please!$"

Route133_Text_2A4264: @ 82A4264
	.string "A strong child TRAINER…\n"
	.string "That's so annoying!$"

Route133_Text_2A4290: @ 82A4290
	.string "I want to win like everyone else, but I\n"
	.string "won't raise POKéMON like everyone else.$"

Route133_Text_2A42E0: @ 82A42E0
	.string "Darn it!\n"
	.string "My way is still too slack!$"

Route133_Text_2A4304: @ 82A4304
	.string "It's way more fun to do things the way\n"
	.string "I want than to be like everybody else.\l"
	.string "I mean, that's obvious!$"

Route133_Text_2A436A: @ 82A436A
	.string "I came all the way out here with my\n"
	.string "BIRD POKéMON.$"

Route133_Text_2A439C: @ 82A439C
	.string "You…\n"
	.string "You're stunningly cool!$"

Route133_Text_2A43B9: @ 82A43B9
	.string "I'd like to go back to FORTREE,\n"
	.string "but I've grown to like this place, too.$"

Route133_Text_2A4401: @ 82A4401
	.string "I must have battled thousands\n"
	.string "of times. I've lost count.$"

Route133_Text_2A443A: @ 82A443A
	.string "I may have lost thousands of times,\n"
	.string "but a loss still stings.$"

Route133_Text_2A4477: @ 82A4477
	.string "Keep at this, youngster. So you can\n"
	.string "become like my husband and me.$"

Route133_Text_2A44BA: @ 82A44BA
	.string "Young people are too happy to go with\n"
	.string "the flow. They're without direction.$"

Route133_Text_2A4505: @ 82A4505
	.string "You have a firm sense of purpose.$"

Route133_Text_2A4527: @ 82A4527
	.string "Don't let others lead you astray.\n"
	.string "Don't lose direction as you grow older.$"

Route134_Text_2A4571: @ 82A4571
	.string "Even those POKéMON that can swim are\n"
	.string "carried along by the rapid currents.$"

Route134_Text_2A45BB: @ 82A45BB
	.string "Aiyeeeeh!$"

Route134_Text_2A45C5: @ 82A45C5
	.string "I think POKéMON enjoy the fast-running\n"
	.string "currents around these parts.$"

Route134_Text_2A4609: @ 82A4609
	.string "My LUVDISC are looking for a fun\n"
	.string "match. Will you join us?$"

Route134_Text_2A4643: @ 82A4643
	.string "Oopsie!$"

Route134_Text_2A464B: @ 82A464B
	.string "There's a collector who's after\n"
	.string "the SCALES of LUVDISC.$"

Route134_Text_2A4682: @ 82A4682
	.string "Okeydokey! That's enough rest, gang!\n"
	.string "It's time for a match!$"

Route134_Text_2A46BE: @ 82A46BE
	.string "Tuckered out again…$"

Route134_Text_2A46D2: @ 82A46D2
	.string "My BIRD POKéMON get tired quickly after\n"
	.string "a long flight…$"

Route134_Text_2A4709: @ 82A4709
	.string "You're a POKéMON TRAINER.\n"
	.string "No need for words. We battle now.$"

Route134_Text_2A4745: @ 82A4745
	.string "… … … … … …\n"
	.string "… … … … … …$"

Route134_Text_2A475D: @ 82A475D
	.string "It was I who challenged you, and yet\n"
	.string "I lost. I am deeply shamed…$"

Route134_Text_2A479E: @ 82A479E
	.string "The savage tide in this area serves to\n"
	.string "make us stronger than ever.$"

Route134_Text_2A47E1: @ 82A47E1
	.string "I willingly concede defeat.$"

Route134_Text_2A47FD: @ 82A47FD
	.string "We will return for more training at\n"
	.string "METEOR FALLS.\p"
	.string "If you'd like, you should go, too.\n"
	.string "It will definitely toughen you up!$"

Route134_Text_2A4875: @ 82A4875
	.string "O-our boat!\n"
	.string "The tide carried it away!$"

Route134_Text_2A489B: @ 82A489B
	.string "Awawawawah!\n"
	.string "Please, stop! Please!$"

Route134_Text_2A48BD: @ 82A48BD
	.string "If we can't SURF, how are we supposed\n"
	.string "to get home?\p"
	.string "Actually, I know a fainted POKéMON\n"
	.string "can still SURF, but it feels wrong.$"

Route134_Text_2A4937: @ 82A4937
	.string "Can your POKéMON dodge our\n"
	.string "lightning-quick attacks?$"

Route134_Text_2A496B: @ 82A496B
	.string "I never knew such a technique existed!\n"
	.string "You've defeated us thoroughly.$"

Route134_Text_2A49B1: @ 82A49B1
	.string "I haven't lost my passion for speed.\n"
	.string "I will try harder.$"

Route134_Text_2A49E9: @ 82A49E9
	.string "My POKéMON can't be taken down\n"
	.string "easily!$"

Route134_Text_2A4A10: @ 82A4A10
	.string "You're kidding!\n"
	.string "Explain how I lost!$"

Route134_Text_2A4A34: @ 82A4A34
	.string "Haha!\n"
	.string "You won, all right!\p"
	.string "I'll work my way back up by taking on\n"
	.string "TRAINERS I happen to meet!$"

Route134_Text_2A4A8F: @ 82A4A8F
	.string "Listen, have you seen another SAILOR\n"
	.string "around here?$"

Route134_Text_2A4AC1: @ 82A4AC1
	.string "Now, that's something!$"

Route134_Text_2A4AD8: @ 82A4AD8
	.string "Our boat drifted out to sea.\p"
	.string "My buddy's a timid fellow, so I'm\n"
	.string "worried about him.$"
