
LilycoveCity_PokemonTrainerFanClub_Text_OhWowItsPlayer:
	.string "¡Anda!\n"
	.string "¡Si es {PLAYER}!$"

LilycoveCity_PokemonTrainerFanClub_Text_HeardAboutYouImYourFan:
	.string "¡Ya me han contado todo!\n"
	.string "Tú eres muy fuerte, ¿verdad?\p"
	.string "Aquí siempre estamos discutiendo\n"
	.string "sobre quién es el más fuerte.\p"
	.string "Así que cuando me hablaron de ti\n"
	.string "decidí ser tu fan número uno.\p"
	.string "Confío en que sigas luchando\n"
	.string "contra ENTRENADORES duros.\p"
	.string "De ese modo podré seguir disfrutando\n"
	.string "de tus emocionantes combates.\p"
	.string "Y todo el mundo se dará cuenta\n"
	.string "de lo grande que eres.\p"
	.string "¡Recuerda que yo siempre te estaré\n"
	.string "apoyando, {PLAYER}!$"

LilycoveCity_PokemonTrainerFanClub_Text_YoureOneWeWantToWin:
	.string "¡Hola, {PLAYER}!\n"
	.string "¡Nosotros vamos a estar animándote\l"
	.string "desde aquí!$"

LilycoveCity_PokemonTrainerFanClub_Text_OthersDontKnowYoureTheBest:
	.string "¡Los demás no tienen ni idea\n"
	.string "de que no hay nadie mejor que tú!\p"
	.string "¿A que sí, {PLAYER}?\n"
	.string "¡Enséñales lo que vales!$"

LilycoveCity_PokemonTrainerFanClub_Text_TrainersPowerIsOutOfTheOrdinary:
	.string "Odio tener que decir esto, pero el\n"
	.string "ENTRENADOR que está en boca\l"
	.string "de todos es {STR_VAR_1}, eso está claro.\p"
	.string "La fuerza de ese ENTRENADOR…\n"
	.string "es algo que no es normal…$"

LilycoveCity_PokemonTrainerFanClub_Text_TrainerIsBestNoOneWantsToListen:
	.string "Qué pesadez… He estado diciendo\n"
	.string "a todos que el mejor es {STR_VAR_1}…\p"
	.string "Pero nadie me escucha…$"

LilycoveCity_PokemonTrainerFanClub_Text_HearingAboutToughNewTrainer:
	.string "He estado oyendo algo de un nuevo\n"
	.string "ENTRENADOR muy fuerte…\p"
	.string "Se supone que puede incluso vencer\n"
	.string "a los LÍDERES de los GIMNASIOS.\p"
	.string "¿Tú sabes algo de eso?$"

LilycoveCity_PokemonTrainerFanClub_Text_ImPullingForYou:
	.string "¡Oh, {PLAYER}!\p"
	.string "¡Adelante!\n"
	.string "¡Sé que puedes ganar!$"

LilycoveCity_PokemonTrainerFanClub_Text_BrawlyNoImYourFan:
	.string "Ufff…\n"
	.string "MARCIAL…\p"
	.string "¡Eh, no, espera!\n"
	.string "¡Eso no está bien! ¡No, no, no!\p"
	.string "¡Yo he sido siempre tu mayor fan!\p"
	.string "¡No me defraudes!\n"
	.string "¡Ve a por todas!$"

LilycoveCity_PokemonTrainerFanClub_Text_ICantHelpLikingBrawly:
	.string "No puedo evitarlo, sólo me gusta\n"
	.string "MARCIAL…$"

LilycoveCity_PokemonTrainerFanClub_Text_NobodyUnderstandsBrawly:
	.string "Nadie comprende lo bueno\n"
	.string "que es MARCIAL…\p"
	.string "¡Pero a mí me da igual!\p"
	.string "¡Aunque sea la única persona que lo\n"
	.string "haga, seguiré apoyando a MARCIAL!$"

LilycoveCity_PokemonTrainerFanClub_Text_MyFavoriteTrainerIsBrawly:
	.string "Digan lo que digan los demás, mi\n"
	.string "ENTRENADOR favorito es MARCIAL:\l"
	.string "el LÍDER del GIMNASIO de AZULIZA.$"

LilycoveCity_PokemonTrainerFanClub_Text_YouveSurpassedYourFather:
	.string "¡Has conseguido superar a tu padre\n"
	.string "en todos los aspectos!\p"
	.string "¡Te lo digo yo, así que ni te atrevas\n"
	.string "a dudarlo!$"

LilycoveCity_PokemonTrainerFanClub_Text_YourFatherNeverGaveUpSoKeepOnBattling:
	.string "Incluso cuando las cosas no estaban\n"
	.string "nada fáciles, tu padre nunca se rindió.\p"
	.string "Eso lo sé a ciencia cierta.\p"
	.string "¡Así que no te rindas aunque pierdas!\n"
	.string "¡Sigue luchando!$"

LilycoveCity_PokemonTrainerFanClub_Text_LongWayToGoComparedToNorman:
	.string "NORMAN luchó con más fuerza,\n"
	.string "personalidad y estilo que tú.\p"
	.string "Muchos dicen que eres fuerte…,\p"
	.string "pero todavía te queda mucho que\n"
	.string "aprender para ser como tu padre.$"

LilycoveCity_PokemonTrainerFanClub_Text_YouAndNormanAreDifferent:
	.string "Estás empezando a inspirar tanto\n"
	.string "respeto como NORMAN.\p"
	.string "Pero un abismo os separa…\p"
	.string "No te puedo decir de qué se trata…\n"
	.string "¡Averígualo tú!$"

LilycoveCity_PokemonTrainerFanClub_Text_WeDiscussStrongestTrainers:
	.string "Todos los que estamos aquí somos\n"
	.string "grandes seguidores de los combates\l"
	.string "entre POKéMON.\p"
	.string "Siempre estamos discutiendo quién\n"
	.string "es el mejor ENTRENADOR de todos.\p"
	.string "¡Si algún día alcanzas la fama, puede\n"
	.string "que nos hagamos fans tuyos!$"

LilycoveCity_PokemonTrainerFanClub_Text_OhWoweeItsPlayer:
	.string "¡Oh, guauuuu! ¡Es {PLAYER}!\n"
	.string "¡En carne y hueso!\p"
	.string "¡Por favor, dame la mano!\n"
	.string "¡Y un autógrafo!$"

LilycoveCity_PokemonTrainerFanClub_Text_AlwaysCheerForYou:
	.string "¡Yo siempre te apoyo, {PLAYER}!\n"
	.string "¡Siempre, siempre, siempre!\p"
	.string "¡Sé que no vas a perder, {PLAYER}!\n"
	.string "¡Porque eres muy, muy fuerte!$"

LilycoveCity_PokemonTrainerFanClub_Text_EveryoneThinksTrainerIsCool:
	.string "{STR_VAR_1} es tan guay…\p"
	.string "Y todo el mundo está de acuerdo,\n"
	.string "¿sabes?$"

LilycoveCity_PokemonTrainerFanClub_Text_TrainerIsReallyCoolItsJustMe:
	.string "{STR_VAR_1} es muy guay, ¿verdad?\p"
	.string "Aunque nadie esté conmigo, yo voy\n"
	.string "a animar a mi ENTRENADOR favorito.$"

LilycoveCity_PokemonTrainerFanClub_Text_WishThereWasTrainerLikeThat:
	.string "Mi ENTRENADOR preferido es…\p"
	.string "superguay…,\p"
	.string "superfuerte…\p"
	.string "y supersimpático.\p"
	.string "Ojalá existiera de verdad…$"

LilycoveCity_PokemonTrainerFanClub_Text_WantToBeStrongLikeYou:
	.string "¡Eh! ¡Es {PLAYER}!\n"
	.string "¡Cómo mola!\p"
	.string "Cuando sea mayor, quiero ser\n"
	.string "tan fuerte como tú, {PLAYER}.$"

LilycoveCity_PokemonTrainerFanClub_Text_OnlyOneWhoCheersForYou:
	.string "Aunque sea el único…,\p"
	.string "siempre te voy a animar a ti, {PLAYER}.\p"
	.string "¡Porque yo creo en ti, {PLAYER}!\n"
	.string "¡Eres mi ídolo!$"

LilycoveCity_PokemonTrainerFanClub_Text_TrainerIsWickedlyCool:
	.string "{STR_VAR_1} es tan guay…\n"
	.string "Ojalá me dejara darle la mano…$"

LilycoveCity_PokemonTrainerFanClub_Text_NeverGoingToStopBeingTrainersFan:
	.string "Aunque sea el único…,\p"
	.string "¡nunca dejaré de ser fan\n"
	.string "de {STR_VAR_1}!\p"
	.string "¡Porque {STR_VAR_1} nunca pierde!$"

LilycoveCity_PokemonTrainerFanClub_Text_YoureAmazingAfterAll:
	.string "¡{PLAYER}!\n"
	.string "¡Eres increíble!\p"
	.string "Desde que te vi, supe que eras\n"
	.string "alguien realmente grande.\p"
	.string "Yo nunca me equivoco…$"

LilycoveCity_PokemonTrainerFanClub_Text_ImInYourCorner:
	.string "¿A quién le importa lo que piensen\n"
	.string "los demás? ¡Yo te apoyo a ti!\p"
	.string "No te preocupes. Tú sal ahí fuera\n"
	.string "y lucha igual que siempre.$"

LilycoveCity_PokemonTrainerFanClub_Text_ThinkTrainerIsNumberOne:
	.string "La verdad es que no se te da mal\n"
	.string "entrenar.\p"
	.string "Pero también creo que no hay nadie\n"
	.string "mejor que {STR_VAR_1} ahora mismo.\p"
	.string "Es sólo mi opinión, de todas formas.\n"
	.string "No dejes que te influya.$"

LilycoveCity_PokemonTrainerFanClub_Text_YoureMaybeStrongerThanTrainer:
	.string "Vaya, eres muy fuerte. Quizás incluso\n"
	.string "más fuerte que {STR_VAR_1}.\p"
	.string "Pero {STR_VAR_1} necesita apoyo.\p"
	.string "Si no se lo doy yo, ¿quién lo hará?$"

LilycoveCity_PokemonTrainerFanClub_Text_YouChangedMyMind:
	.string "¡Me has hecho cambiar de opinión!\n"
	.string "¡Eres muy, muy fuerte!\p"
	.string "¡Quiero que me digas cómo lo has\n"
	.string "hecho para mejorar tanto!$"

LilycoveCity_PokemonTrainerFanClub_Text_YouBattleAttractivelyInToughSituation:
	.string "Siempre te las arreglas para luchar\n"
	.string "mejor en circunstancias difíciles.\p"
	.string "¡Estoy deseando ver tu próximo\n"
	.string "combate!$"

LilycoveCity_PokemonTrainerFanClub_Text_TrainerIsStandout:
	.string "Hay muchos ENTRENADORES que están\n"
	.string "bien, pero {STR_VAR_1} sobresale.\p"
	.string "Su fuerza es algo sobrenatural…\p"
	.string "Tú no lo haces mal, pero no te puedes\n"
	.string "comparar con {STR_VAR_1}.$"

LilycoveCity_PokemonTrainerFanClub_Text_NoOneCanKnockYouButTrainerStronger:
	.string "Eres muy popular…\p"
	.string "Eres fuerte y te preocupas por tus\n"
	.string "POKéMON. Nadie puede vencerte.\p"
	.string "Pero ¿sabes?, yo creo en {STR_VAR_1}.\p"
	.string "{STR_VAR_1} es sin duda más fuerte,\n"
	.string "¡no hay lugar a dudas!$"

LilycoveCity_PokemonTrainerFanClub_Text_YouImpressive:
	.string "Tú…\p"
	.string "¡eres genial!$"

LilycoveCity_PokemonTrainerFanClub_Text_OnlyIRecognizeYourTrueWorth:
	.string "Da igual si sólo yo soy capaz\n"
	.string "de reconocer lo que vales.\p"
	.string "Los demás no pueden comprender\n"
	.string "el poder oculto que hay en ti.$"

LilycoveCity_PokemonTrainerFanClub_Text_HaventRealizedPotential:
	.string "Sí, puedo ver lo fuerte que eres\n"
	.string "con sólo mirarte a los ojos.\p"
	.string "Pero…\p"
	.string "¡todavía no eres consciente\n"
	.string "de tu enorme potencial!$"

LilycoveCity_PokemonTrainerFanClub_Text_YourePowerfulButNotTrueStrength:
	.string "Tienes razón, eres muy fuerte.\p"
	.string "Pero te puedo decir que…\p"
	.string "¡todavía no es suficiente!\p"
	.string "La verdadera fortaleza reside en…\p"
	.string "Ejem…\p"
	.string "Bueno, no tengo ni idea.$"
