
ShoalCave_LowTideLowerRoom_Text_CanOvercomeColdWithFocus:
	.string "Il freddo penetrante di queste parti\n"
	.string "non giova senz’altro all’allenamento.\p"
	.string "Ma con la giusta concentrazione,\n"
	.string "ci si può riuscire!\p"
	.string "Questa BANDANA ti aiuterà a\n"
	.string "concentrarti e a sopportare il freddo!$"

ShoalCave_LowTideLowerRoom_Text_EverythingStartsWithFocus:
	.string "La concentrazione è tutto!$"
