
EverGrandeCity_HallOfFame_Text_HereWeHonorLeagueChampions:
	.string "PLUBIO: Mira esta sala…\p"
	.string "Aquí grabamos los nombres de los\n"
	.string "POKéMON que vencieron en combate.\p"
	.string "Aquí es donde los CAMPEONES\n"
	.string "de la LIGA reciben todos los honores.$"

EverGrandeCity_HallOfFame_Text_LetsRecordYouAndYourPartnersNames:
	.string "PLUBIO: Muy bien, grabemos tu nombre\n"
	.string "y el de los compañeros que lucharon\l"
	.string "contigo para que todos recuerden\l"
	.string "que venciste en la LIGA POKéMON.$"

