
EverGrandeCity_HallOfFame_Text_HereWeHonorLeagueChampions:
	.string "ADRIANO: In questa sala…\p"
	.string "conserviamo i dati dei POKéMON\n"
	.string "che hanno superato agguerrite lotte.\p"
	.string "Ed è qui che rendiamo omaggio\n"
	.string "ai CAMPIONI della LEGA.$"

EverGrandeCity_HallOfFame_Text_LetsRecordYouAndYourPartnersNames:
	.string "ADRIANO: Ora registriamo il tuo nome\n"
	.string "come ALLENATORE che ha trionfato\l"
	.string "sulla LEGA POKéMON, ed i nomi dei tuoi\l"
	.string "compagni che hanno lottato con te.$"

