
EverGrandeCity_SidneysRoom_Text_IntroSpeech:
	.string "¡Te doy la bienvenida!\n"
	.string "Soy SIXTO, del ALTO MANDO.\p"
	.string "Me gusta esa mirada que tienes…\n"
	.string "Pareces estar a mi altura…\l"
	.string "Sí, sí, esto pinta bien…\p"
	.string "¡Muy bien! Tú y yo vamos a disfrutar\n"
	.string "de un gran combate al más puro estilo\l"
	.string "LIGA POKéMON.$"

EverGrandeCity_SidneysRoom_Text_Defeat:
	.string "Bueno, ¿qué te parece? He perdido…\n"
	.string "Pero al menos me lo he pasado bien.$"

EverGrandeCity_SidneysRoom_Text_PostBattleSpeech:
	.string "Escucha lo que tengo que decirte…\p"
	.string "Tienes lo que necesitas para llegar\n"
	.string "lejos. Ahora ve a la siguiente sala\l"
	.string "y disfruta de un nuevo combate.$"

