MauvilleCity_GameCorner:
	.4byte MauvilleCity_GameCorner_Layout
	.4byte MauvilleCity_GameCorner_MapEvents
	.4byte MauvilleCity_GameCorner_MapScripts
	.4byte 0x0
	.2byte MUS_CASINO
	.2byte LAYOUT_MAUVILLE_CITY_GAME_CORNER
	.byte MAPSEC_MAUVILLE_CITY
	.byte 0
	.byte WEATHER_NONE
	.byte MAP_TYPE_INDOOR
	.2byte 0
	map_header_flags allow_bike=0, allow_escape_rope=0, allow_run=0, show_map_name=0
	.byte MAP_BATTLE_SCENE_NORMAL

