
MauvilleCity_GameCorner_Text_ThisIsMauvilleGameCorner:
	.string "Ti trovi nel CASINÒ di CICLAMIPOLI.$"

MauvilleCity_GameCorner_Text_NeedCoinCaseForCoins:
	.string "Vuoi dei GETTONI per giocare?\p"
	.string "Ma come faccio a darteli se non hai\n"
	.string "il SALVADANAIO?$"

MauvilleCity_GameCorner_Text_WereYouLookingForCoins:
	.string "Ti servono GETTONI?\p"
	.string "50 GETTONI costano ¥1.000.\n"
	.string "Quanti ne vuoi?$"

MauvilleCity_GameCorner_Text_ThankYouHereAreYourCoins:
	.string "Grazie mille!\n"
	.string "Eccoti i GETTONI!$"

MauvilleCity_GameCorner_Text_DontHaveEnoughMoney:
	.string "Uhm… non hai denaro a sufficienza…$"

MauvilleCity_GameCorner_Text_CoinCaseIsFull:
	.string "Oh, il tuo SALVADANAIO è pieno.$"

MauvilleCity_GameCorner_Text_DontNeedCoinsThen:
	.string "Oh… nessun GETTONE?\n"
	.string "Beh, in bocca al lupo lo stesso!$"

MauvilleCity_GameCorner_Text_ExchangeCoinsForPrizes:
	.string "Ti do il benvenuto!\p"
	.string "Qui puoi scambiare GETTONI\n"
	.string "con fantastici premi.$"

MauvilleCity_GameCorner_Text_WhichPrize:
	.string "Che premio scegli?$"

MauvilleCity_GameCorner_Text_SoYourChoiceIsTheTMX:
	.string "Quindi scegli la {STR_VAR_1}\n"
	.string "contenente {STR_VAR_2}?$"

MauvilleCity_GameCorner_Text_SendToYourHomePC:
	.string "Grazie! La consegna avverrà\n"
	.string "sul tuo PC di casa.$"

MauvilleCity_GameCorner_Text_NotEnoughCoins:
	.string "Non hai abbastanza GETTONI.$"

@ Unused
MauvilleCity_GameCorner_Text_NoRoomForPlacingDecor:
	.string "There isn’t any room available for\n"
	.string "placing {STR_VAR_1}.$"

MauvilleCity_GameCorner_Text_OhIsThatSo:
	.string "Oh, davvero? \n"
	.string "Torna quando vuoi ritirare un premio\l"
	.string "con i GETTONI.$"

MauvilleCity_GameCorner_Text_SoYourChoiceIsX:
	.string "Quindi scegli {STR_VAR_1}?$"

MauvilleCity_GameCorner_Text_HereYouGo:
	.string "Ecco qui!$"

@ Unused
MauvilleCity_GameCorner_Text_CantCarryAnyMore:
	.string "Oh, you can’t carry any more than that.$"

MauvilleCity_GameCorner_Text_GotTwoOfSameDollWantOne:
	.string "Ho fatto un errore ed ho preso due\n"
	.string "BAMBOLE dello stesso tipo.\p"
	.string "Ne vuoi una?$"

MauvilleCity_GameCorner_Text_HereYouGo2:
	.string "Ecco qui!$"

MauvilleCity_GameCorner_Text_YouWantItButNotNow:
	.string "Uh?!\n"
	.string "La vuoi, ma non ora?$"

MauvilleCity_GameCorner_Text_DontBeNegative:
	.string "Perché non la vuoi?\n"
	.string "È un regalo!$"

MauvilleCity_GameCorner_Text_CantWinJackpot:
	.string "C’è in palio un premio che mi interessa,\n"
	.string "ma non riesco a vincere il jackpot.$"

MauvilleCity_GameCorner_Text_NeedCoinCaseGoNextDoor:
	.string "Ehi, per giocare ti serve\n"
	.string "un SALVADANAIO.\p"
	.string "La signorina che abita accanto\n"
	.string "dovrebbe averne uno. Vai a trovarla!$"

MauvilleCity_GameCorner_Text_LuckOnlyLastSoLongTakeCoins:
	.string "La mia fortuna non può durare a lungo.\n"
	.string "Questo è troppo per me.\l"
	.string "Eccoti dei GETTONI!$"

MauvilleCity_GameCorner_Text_MauvilleSomethingForEveryone:
	.string "CICLAMIPOLI ha tante attrazioni!\p"
	.string "Per me la migliore di tutte è il CASINÒ.$"

MauvilleCity_GameCorner_Text_RouletteTablesDifferentRates:
	.string "I tavoli della ROULETTE hanno puntate\n"
	.string "diverse.\p"
	.string "Prima di sceglierne uno, controlla\n"
	.string "quanti GETTONI hai.$"

MauvilleCity_GameCorner_Text_EasyToLoseTrackOfTime:
	.string "Qui si perde la cognizione del tempo. \n"
	.string "Dovrei ritornare al lavoro.$"

MauvilleCity_GameCorner_Text_CoinsAreNeededToPlay:
	.string "Per giocare al CASINÒ sono necessari\n"
	.string "i GETTONI.$"

MauvilleCity_GameCorner_Text_RouletteOnlyLuck:
	.string "Vincere alla ROULETTE è come fare\n"
	.string "un terno al lotto.\p"
	.string "È tutta una questione di fortuna.$"

MauvilleCity_GameCorner_Text_UpTo3CoinsCanBeUsed:
	.string "Per giocare alle SLOT si possono\n"
	.string "usare fino a tre GETTONI.$"

MauvilleCity_GameCorner_Text_DifficultToStopOn7:
	.string "È difficile fermare la SLOT proprio sul\n"
	.string "“7”.\p"
	.string "Se si ferma sul “7” durante\n"
	.string "il REEL TIME nel gioco bonus,\l"
	.string "riceverai GETTONI extra.$"

MauvilleCity_GameCorner_Text_HeresSomeSlotsInfo:
	.string "Eccoti alcune informazioni utili\n"
	.string "sulle SLOT.\p"
	.string "Più tris di lampi fai, più possibilità\n"
	.string "di REEL TIME avrai.\p"
	.string "In un gioco con ben cinque possibilità\n"
	.string "di REEL TIME…\p"
	.string "potrai ricevere quattro premi bonus\n"
	.string "normali e il BIG BONUS finale.\p"
	.string "Il totale dei bonus è di 660 GETTONI,\n"
	.string "una somma difficile da vincere.$"

MauvilleCity_GameCorner_Text_CantPlayWithNoCoinCase:
	.string "Non puoi giocare senza un SALVADANAIO.$"
