
SlateportCity_NameRatersHouse_Text_PleasedToRateMonNickname:
	.string "¡Je, je! ¡Hola! ¡Soy el INSPECTOR\n"
	.string "de los MOTES! ¡El adivinador de nombres!\p"
	.string "Estaré encantado de evaluar\n"
	.string "el nombre de tu POKéMON, je, je.$"

SlateportCity_NameRatersHouse_Text_CritiqueWhichMonNickname:
	.string "¿Qué nombre de POKéMON\n"
	.string "quieres que adivine y evalúe?$"

SlateportCity_NameRatersHouse_Text_FineNameSuggestBetterOne:
	.string "Mmmmm… {STR_VAR_1}, ¿a que sí?\n"
	.string "No está mal, no está mal…\p"
	.string "Pero ¿no crees que podríamos\n"
	.string "encontrar un nombre aún mejor?$"

SlateportCity_NameRatersHouse_Text_WhatShallNewNameBe:
	.string "Así me gusta. A ver…\n"
	.string "¿Cuál será el nuevo nombre?$"

SlateportCity_NameRatersHouse_Text_MonShallBeKnownAsName:
	.string "¡Ya está! ¡A partir de ahora, el nombre\n"
	.string "de este POKéMON será {STR_VAR_1}!\p"
	.string "Es un nombre mucho mejor que\n"
	.string "el anterior, ¡qué suerte tienes!$"

SlateportCity_NameRatersHouse_Text_DoVisitAgain:
	.string "Entiendo…\n"
	.string "Entonces vuelve cuando quieras.$"

SlateportCity_NameRatersHouse_Text_NameNoDifferentYetSuperior:
	.string "¡Ya está! ¡A partir de ahora, el nombre\n"
	.string "de este POKéMON será {STR_VAR_1}!\p"
	.string "No parece muy diferente del anterior\n"
	.string "y, sin embargo, es muchísimo mejor.\l"
	.string "¡Qué suerte tienes!$"

SlateportCity_NameRatersHouse_Text_MagnificentName:
	.string "Mmmm… ¡Será {STR_VAR_1}!\p"
	.string "¡He aquí un mote magnífico!\n"
	.string "¡Absolutamente irreprochable!\p"
	.string "Harás bien en querer mucho\n"
	.string "a tu {STR_VAR_1} de ahora en adelante.$"

SlateportCity_NameRatersHouse_Text_ThatIsMerelyAnEgg:
	.string "Pero vamos a ver…\n"
	.string "¡Esto es sólo un HUEVO!$"
