
MtPyre_1F_Text_TakeThisForYourOwnGood:
	.string "En el MONTE PÍRICO te puedes encontrar\n"
	.string "con todo tipo de criaturas…\p"
	.string "Nunca se sabe qué puede pasar,\n"
	.string "así que toma esto por tu bien.$"

MtPyre_1F_Text_ExplainCleanseTag:
	.string "Dale este AMULETO a algún\n"
	.string "POKéMON.\p"
	.string "Te ayudará a mantener alejados\n"
	.string "a los POKéMON salvajes.$"

MtPyre_1F_Text_ComeToPayRespects:
	.string "¿Has venido a presentar tus respetos\n"
	.string "a las almas de los POKéMON que ya\l"
	.string "no están con nosotros?\p"
	.string "Recuerda que has de cuidar de tus\n"
	.string "POKéMON con mucho cariño.$"

MtPyre_1F_Text_RestingPlaceOfZigzagoon:
	.string "Aquí descansa en paz mi ZIGZAGOON.\n"
	.string "Yo lo quería tanto…$"
