SootopolisCity_PokemonCenter_1F: @ 8483A60
	.4byte PokemonCenter_1F_Layout
	.4byte SootopolisCity_PokemonCenter_1F_MapEvents
	.4byte SootopolisCity_PokemonCenter_1F_MapScripts
	.4byte 0x0
	.2byte MUS_POKECEN
	.2byte 61
	.byte MAPSEC_SOOTOPOLIS_CITY
	.byte 0
	.byte WEATHER_NONE
	.byte MAP_TYPE_INDOOR
	.2byte 0
	map_header_flags allow_bike=0, allow_escape_rope=0, allow_run=0, show_map_name=0
	.byte MAP_BATTLE_SCENE_NORMAL

