
SootopolisCity_PokemonCenter_1F_Text_WallaceToughestInHoenn:
	.string "Dicen que PLUBIO es el mejor\n"
	.string "ENTRENADOR de HOENN.\p"
	.string "El GIMNASIO de este lugar está\n"
	.string "dirigido por el maestro de PLUBIO.\p"
	.string "Pero los del ALTO MANDO… son aún\n"
	.string "más fuertes que el mentor de PLUBIO.\p"
	.string "No me lo puedo ni imaginar…$"

SootopolisCity_PokemonCenter_1F_Text_EveryoneTakenRefuge:
	.string "Todo el mundo se ha escondido\n"
	.string "en su casa y no quiere salir.\p"
	.string "Yo desde luego no tengo ninguna\n"
	.string "intención de aventurarme ahí fuera.$"

SootopolisCity_PokemonCenter_1F_Text_AlwaysBeFriendsWithPokemon:
	.string "Pase lo que pase, yo siempre seré\n"
	.string "amiga de los POKéMON.\p"
	.string "¡Es que me divierto tanto con ellos!$"

SootopolisCity_PokemonCenter_1F_Text_ArentPokemonOurFriends:
	.string "Los POKéMON son nuestros amigos, ¿no?\p"
	.string "Entonces, ¿a qué viene un\n"
	.string "comportamiento tan salvaje?$"
