
SootopolisCity_PokemonCenter_1F_Text_WallaceToughestInHoenn:
	.string "On raconte que MARC est le DRESSEUR\n"
	.string "le plus fort de tout HOENN.\p"
	.string "L’ARENE de cette ville est dirigée par\n"
	.string "celui qui lui a tout appris.\p"
	.string "Mais le CONSEIL 4…\p"
	.string "On dit qu’ils sont encore plus forts\n"
	.string "que le mentor de MARC.\p"
	.string "Mais jusqu’à quel point?$"

SootopolisCity_PokemonCenter_1F_Text_EveryoneTakenRefuge:
	.string "Tout le monde en ville s’est réfugié\n"
	.string "chez soi et personne ne veut sortir.\p"
	.string "Même moi je ferais bien de ne pas\n"
	.string "m’aventurer dehors.$"

SootopolisCity_PokemonCenter_1F_Text_AlwaysBeFriendsWithPokemon:
	.string "Peu importe ce qui se passera, où\n"
	.string "et quand ça se passera, je resterai\l"
	.string "toujours amie avec les POKéMON.\p"
	.string "Car c’est cool d’être avec les POKéMON!$"

SootopolisCity_PokemonCenter_1F_Text_ArentPokemonOurFriends:
	.string "Je ne sais pas pourquoi…\n"
	.string "mais… j’ai vraiment peur…$"
