AquaHideout_B1F_Text_Grunt2Intro:
	.string "Se vuoi conoscere il segreto del nostro\n"
	.string "RIFUGIO, devi battermi!$"

AquaHideout_B1F_Text_Grunt2Defeat:
	.string "Proprio non riesco a vincere…$"

AquaHideout_B1F_Text_Grunt2PostBattle:
	.string "Il segreto del nostro RIFUGIO?\p"
	.string "Beh, diciamo che…\n"
	.string "in fondo c’è un sottomarino!\p"
	.string "Ma per ora… shshshsh…$"

AquaHideout_B1F_Text_Grunt3Intro:
	.string "Rifornimento carburante, OK!\n"
	.string "Rifornimento merendine, OK!\p"
	.string "Non ci resta che mettere KO\n"
	.string "i ficcanaso!$"

AquaHideout_B1F_Text_Grunt3Defeat:
	.string "Che sconfitta a tutto tondo!$"

AquaHideout_B1F_Text_Grunt3PostBattle:
	.string "Niente panico!\n"
	.string "Tutto secondo i piani!\p"
	.string "La mia missione era solo quella\n"
	.string "di farti perdere tempo!$"

AquaHideout_B1F_Text_Grunt5Intro:
	.string "Che sonno… fare la sentinella al\n"
	.string "RIFUGIO mi annoia… Facciamo una sfida!$"

AquaHideout_B1F_Text_Grunt5Defeat:
	.string "Che sonno… oh, ho perso…$"

AquaHideout_B1F_Text_Grunt5PostBattle:
	.string "Se vai troppo di fretta, altre RECLUTE\n"
	.string "del TEAM IDRO ti staranno alle costole.$"

AquaHideout_B1F_Text_Grunt7Intro:
	.string "Ehi!\n"
	.string "Dico a te!\p"
	.string "Secondo te è più bella l’uniforme del\n"
	.string "TEAM IDRO o quella del TEAM MAGMA?$"

AquaHideout_B1F_Text_Grunt7Defeat:
	.string "Che bel modo di perdere…$"

AquaHideout_B1F_Text_Grunt7PostBattle:
	.string "Con una bella uniforme si fa una bella\n"
	.string "figura anche se si perde, vero?$"
