#ifndef GUARD_CONFIG_TEST_H
#define GUARD_CONFIG_TEST_H

#undef B_EXPANDED_MOVE_NAMES
#define B_EXPANDED_MOVE_NAMES TRUE
#undef I_EXPANDED_ITEM_NAMES
#define I_EXPANDED_ITEM_NAMES TRUE

#endif // GUARD_CONFIG_TEST_H
