ShoalCave_LowTideStairsRoom: @ 8484400
	.4byte ShoalCave_LowTideStairsRoom_Layout
	.4byte ShoalCave_LowTideStairsRoom_MapEvents
	.4byte ShoalCave_LowTideStairsRoom_MapScripts
	.4byte 0x0
	.2byte MUS_M_DUNGON
	.2byte 166
	.byte MAPSEC_SHOAL_CAVE
	.byte 0
	.byte WEATHER_NONE
	.byte MAP_TYPE_UNDERGROUND
	.2byte 0
	map_header_flags allow_bike=1, allow_escape_rope=1, allow_run=1, show_map_name=1
	.byte MAP_BATTLE_SCENE_NORMAL

