
RusturfTunnel_Text_ComeAndGetSome:
	.string "¿Y esto? ¿Vienes a por mí?\n"
	.string "¡Pues te voy a dar una buena!$"

RusturfTunnel_Text_Peeko:
	.string "PEEKO: Pi, pikooo…$"

RusturfTunnel_Text_GruntIntro:
	.string "¡Por todos los POKéMON!\p"
	.string "¡Este POKéMON que he secuestrado\n"
	.string "ha resultado ser una carga inútil!\p"
	.string "Y pensar que me he escapado a todo\n"
	.string "correr por esta birria de túnel…\p"
	.string "¡Eh, tú!\n"
	.string "¿Quieres luchar conmigo?$"

RusturfTunnel_Text_GruntDefeat:
	.string "¡Brrrr! ¡Mi brillante carrera criminal\n"
	.string "ha llegado a su fin!$"

RusturfTunnel_Text_GruntTakePackage:
	.string "Aquí falla algo…\p"
	.string "El JEFE me había dicho que sería\n"
	.string "un trabajo chupado.\p"
	.string "Sólo tenía que robar un paquete\n"
	.string "en DEVON…\p"
	.string "¡Pof!\n"
	.string "¡Pues, si tanto lo quieres, para ti!$"

RusturfTunnel_Text_PeekoGladToSeeYouSafe:
	.string "¡PEEKO! ¡Estás sano y salvo!$"

RusturfTunnel_Text_ThankYouLetsGoHomePeeko:
	.string "¡PEEKO te debe la vida!\p"
	.string "Mi nombre es SR. ARENQUE.\n"
	.string "¿Y tú eres…?\p"
	.string "Ajá…\p"
	.string "¡Ah, {PLAYER}{KUN}!\n"
	.string "¡Muchísimas gracias!\p"
	.string "Bueno, si te puedo ayudar en lo que\n"
	.string "sea, no dudes en decírmelo.\p"
	.string "Me puedes encontrar en mi casita de\n"
	.string "la playa, cerca del BOSQUE PETALIA.\p"
	.string "Ven, PEEKO. Tenemos que volver a casa.\p"
	.string "PEEKO: ¡Piko!$"

RusturfTunnel_Text_WhyCantTheyKeepDigging:
	.string "Uf…\p"
	.string "¿Por qué no se puede seguir excavando?\n"
	.string "¿La roca está muy dura?\p"
	.string "Mi chica vive en PUEBLO VERDEGAL,\n"
	.string "un poco más lejos de aquí…\p"
	.string "Si un túnel uniera CIUDAD FÉRRICA\n"
	.string "y VERDEGAL, podría visitarla cada día…\p"
	.string "Pero no estamos adelantando nada.\n"
	.string "¿Qué puedo hacer yo?$"

RusturfTunnel_Text_ToGetToVerdanturf:
	.string "Para ir de CIUDAD FÉRRICA a VERDEGAL,\n"
	.string "tienes que ir primero a AZULIZA y luego\l"
	.string "pasar por CIUDAD PORTUAL y MALVALONA.$"

RusturfTunnel_Text_YouShatteredBoulderTakeHM:
	.string "¡Guau! Has destrozado la roca que\n"
	.string "bloqueaba el camino…\p"
	.string "Para demostrarte mi agradecimiento,\n"
	.string "quiero darte esta MO.$"

RusturfTunnel_Text_ExplainStrength:
	.string "Esta MO contiene FUERZA.\p"
	.string "Si un POKéMON musculoso aprendiera\n"
	.string "este movimiento, podría mover incluso\l"
	.string "las rocas más grandes.$"

RusturfTunnel_Text_WandaReunion:
	.string "¡CLARA!\n"
	.string "¡Ahora puedo verte todos los días!\p"
	.string "CLARA: ¡Cariño, es maravilloso!\p"
	.string "Anda, ven a descansar un rato\n"
	.string "a casa. Has trabajado tanto…$"

RusturfTunnel_Text_BoyfriendOnOtherSideOfRock:
	.string "Mi novio me espera al otro lado\n"
	.string "de esta enorme roca.\p"
	.string "Está trabajando duro en el túnel,\n"
	.string "pero no es sólo para verme a mí.\p"
	.string "Lo está haciendo por el beneficio\n"
	.string "de todos. ¡Es tan generoso…!$"

RusturfTunnel_Text_MikeIntro:
	.string "¿Cómo se llama a los hombres que pasan\n"
	.string "todo el tiempo en las montañas?\l"
	.string "Montañeros, ¿verdad?\p"
	.string "Entonces ¿por qué no llaman a los\n"
	.string "POKéMON que viven en las montañas\l"
	.string "POKéMONtañeros?$"

RusturfTunnel_Text_MikeDefeat:
	.string "Mis POKéMON…\n"
	.string "se han quedado sin fuerzas…$"

RusturfTunnel_Text_MikePostBattle:
	.string "Aquí decidieron detener el avance del\n"
	.string "progreso para proteger a los POKéMON.\l"
	.string "¡Ésta sí que es una historia bonita!$"
