
Route110_Text_WeCantTalkAboutAquaActivities:
	.string "Las actividades del EQUIPO AQUA\n"
	.string "deben permanecer secretas por ahora.$"

Route110_Text_KickUpARuckus:
	.string "¡Quiero ir a CIUDAD PORTUAL\n"
	.string "a montar un buen jaleo!$"

Route110_Text_MyFirstJobInAqua:
	.string "Es mi primer trabajillo como miembro\n"
	.string "del EQUIPO AQUA. ¡Qué nervios!$"

Route110_Text_AquaActionsBringSmiles:
	.string "¡El EQUIPO AQUA debería hacer\n"
	.string "feliz a la gente!$"

Route110_Text_MayLetsBattle:
	.string "AURA: ¡Hola, {PLAYER}{KUN}, cuánto tiempo!\p"
	.string "Mientras buscaba otros POKéMON,\n"
	.string "el que ya tenía ha mejorado mucho.\p"
	.string "Así que…\n"
	.string "¿nos echamos un combate?$"

Route110_Text_MayDefeated:
	.string "¡Vaya!\n"
	.string "¡Eres mejor de lo que esperaba!$"

Route110_Text_MayTakeThis:
	.string "AURA: {PLAYER}{KUN}, has estado entrenando\n"
	.string "mucho, ¿a que sí?\p"
	.string "Te mereces una recompensa.\n"
	.string "¡Toma esto!$"

Route110_Text_MayExplainItemfinder:
	.string "AURA: Es un BUSCAOBJETOS.\p"
	.string "Pruébalo. Cuando encuentra un objeto\n"
	.string "invisible, emite un sonido.\p"
	.string "Muy bien, {PLAYER}{KUN}, nos vemos.\p"
	.string "Y, aunque te suene pretencioso,\n"
	.string "te recomiendo que entrenes mucho\l"
	.string "antes de nuestro próximo combate.$"

Route110_Text_BrendanLetsBattle:
	.string "BRUNO: Oye, {PLAYER}.\n"
	.string "Qué suerte, tú por aquí…\l"
	.string "¿Cómo te va?\p"
	.string "¿Has estado entrenando tus POKéMON?\n"
	.string "Vamos a comprobarlo…$"

Route110_Text_BrendanDefeated:
	.string "Mmm…\n"
	.string "No se te da nada mal.$"

Route110_Text_BrendanTakeThis:
	.string "BRUNO: {PLAYER}, has estado\n"
	.string "entrenando en secreto…\p"
	.string "¡Da igual!\n"
	.string "Toma esto…$"

Route110_Text_BrendanExplainItemfinder:
	.string "BRUNO: Esto es un BUSCAOBJETOS.\p"
	.string "Úsalo para localizar objetos invisibles.\n"
	.string "Si encuentra algo, emite un sonido.\p"
	.string "Bueno, me voy a buscar más\n"
	.string "POKéMON.$"

Route110_Text_RideBikeAtFullSpeed:
	.string "¿A que molaría montar en BICI a toda\n"
	.string "velocidad por el CAMINO de BICIS?$"

Route110_Text_HairStreamsBehindMe:
	.string "¡Me encanta dejar flotar mi cabello\n"
	.string "al viento!\p"
	.string "Me lo he dejado largo sólo para eso.$"

Route110_Text_YouGotBikeFromRydel:
	.string "¡Eh, ésa es una BICI de ANACLETO!\p"
	.string "Es más que evidente.\n"
	.string "Si lo pone en la bicicleta…\p"
	.string "ANACLETO, ANACLETO, ANACLETO,\n"
	.string "ANACLETO, ANACLETO, ANACLETO, \p"
	.string "ANACLETO, ANACLETO, ANACLETO,\n"
	.string "ANACLETO, ANACLETO, ANACLETO, \p"
	.string "ANACLETO, ANACLETO, ANACLETO,\n"
	.string "ANACLETO, ANACLETO, ANACLETO, \p"
	.string "ANACLETO, ANACLETO, ANACLETO,\n"
	.string "ANACLETO, ANACLETO, ANACLETO, \p"
	.string "ANACLETO, ANACLETO, ANACLETO…\n"
	.string "Está más repetido que un cromo.\p"
	.string "¡Deberías cobrar por hacer tanta\n"
	.string "publicidad!$"

Route110_Text_TwoRoads:
	.string "Hay dos caminos: uno que va por\n"
	.string "arriba y otro que va por abajo.\p"
	.string "Uno es para la gente y el otro para\n"
	.string "los POKéMON. Es como tiene que ser.$"

Route110_Text_WalkOnTheLowRoad:
	.string "No tengo BICI, así que me voy\n"
	.string "a pasear por el camino de abajo.$"

Route110_Text_BikeTechniques:
	.string "Cuando aprendes a hacer virguerías\n"
	.string "con la BICI, te lo pasas aún mejor.\p"
	.string "Además, hay sitios a los que sólo\n"
	.string "se llega con determinadas técnicas.$"

Route110_Text_WhichShouldIChoose:
	.string "¿Qué hago?\p"
	.string "¿Voy directamente a MALVALONA por\n"
	.string "el CAMINO de BICIS o cojo el camino\l"
	.string "de abajo y busco POKéMON?$"

Route110_Text_CyclingChallengeResultSummary:
	.string "Número de colisiones:\n"
	.string "¡{STR_VAR_1}!\p"
	.string "Tiempo total transcurrido:\n"
	.string "¡{STR_VAR_2}!$"

Route110_Text_ChallengeReactionBest:
	.string "¡Bravo! ¡Una actuación espléndida!\p"
	.string "Se ve que llevas el ciclismo\n"
	.string "en el corazón.\l"
	.string "¡Me has llegado al alma!$"

Route110_Text_ChallengeReactionGood:
	.string "Tienes una técnica notable.\p"
	.string "Te sugiero que frenes sólo lo justo\n"
	.string "para evitar colisiones.$"

Route110_Text_ChallengeReactionOk:
	.string "Creo que todavía tienes que\n"
	.string "mejorar bastante…\p"
	.string "¡Pero en cualquier caso nunca dejes\n"
	.string "de divertirte montando en bici!$"

Route110_Text_ChallengeReactionBad:
	.string "Guau… Nunca había visto nada\n"
	.string "tan desastroso…\p"
	.string "Está claro que tienes que practicar\n"
	.string "un montonazo.$"

Route110_Text_ChallengeReactionWorst:
	.string "No tengo palabras…\p"
	.string "Me temo que lo tuyo no es montar\n"
	.string "en bici.\p"
	.string "Yo que tú devolvía esa BICI a ANACLETO.$"

Route110_Text_RatedForNumberOfCollisions:
	.string "Éste es el CAMINO de BICIS.\p"
	.string "Si vas de MALVALONA a CIUDAD PORTUAL\n"
	.string "con una BICI CARRERA, te puntuarán por\l"
	.string "el número de colisiones que sufras\l"
	.string "y el tiempo total que tardes.$"

Route110_Text_AlwaysAimHigher:
	.string "Independientemente de los resultados,\n"
	.string "creo que se puede esperar mucho\l"
	.string "de ti. ¡Sigue así!$"

Route110_Text_AcroBikesDoNotQualify:
	.string "En este CAMINO de BICIS, se puntúa\n"
	.string "a los que montan BICIS CARRERA por\l"
	.string "el número de colisiones y su velocidad.\p"
	.string "No se puntúa a la gente que monta una\n"
	.string "BICI ACROBÁTICA porque con ella es\l"
	.string "más fácil girar, así que no sería justo.$"

Route110_Text_SlateportCitySign:
	.string "RUTA 110\n"
	.string "{DOWN_ARROW} CIUDAD PORTUAL$"

Route110_Text_CyclingRoadSign:
	.string "CAMINO de BICIS de la COSTA$"

Route110_Text_AquaWasHere:
	.string "“¡El EQUIPO AQUA estuvo aquí!”\p"
	.string "Eso es lo que ponía en el cartel,\n"
	.string "pero alguien ha escrito encima.\p"
	.string "Ahora dice: “¡EQUIPO MAGMA AL PODER!”.$"

Route110_Text_Route103Sign:
	.string "RUTA 110\n"
	.string "{LEFT_ARROW} RUTA 103$"

Route110_Text_SeasideParkingSign:
	.string "APARCAMIENTO de la COSTA$"

Route110_Text_MauvilleCitySign:
	.string "RUTA 110\n"
	.string "{UP_ARROW} CIUDAD MALVALONA$"

Route110_Text_TrainerTipsPrlzSleep:
	.string "PISTAS para ENTRENADORES\p"
	.string "Puedes sacar ventaja a tu enemigo\n"
	.string "si lo paralizas o le haces dormir.\p"
	.string "Es una técnica muy importante\n"
	.string "en cualquier combate POKéMON.$"

Route110_Text_TrainerTipsRegisterItems:
	.string "PISTAS para ENTRENADORES\p"
	.string "Puedes reorganizar los objetos de la\n"
	.string "MOCHILA pulsando el Botón SELECT.$"

Route110_Text_TrickHouseSign:
	.string "“Tres pasos a la {RIGHT_ARROW} y dos hacia {UP_ARROW}\n"
	.string "para llegar a la fantástica\l"
	.string "CASA TRETA.”$"

Route110_Text_BestRecord:
	.string "EL MEJOR RÉCORD HASTA LA FECHA:\p"
	.string "N.º de colisiones: {STR_VAR_1}\p"
	.string "Tiempo transcurrido: {STR_VAR_2}$"

Route110_Text_ThereIsNoRecord:
	.string "EL MEJOR RÉCORD HASTA LA FECHA:\p"
	.string "Parece que nadie ha aceptado\n"
	.string "el desafío. No consta ningún récord.$"

Route110_Text_ImagineSeeingYouHere:
	.string "PROF. ABEDUL: ¡Eh, {PLAYER}{KUN}!\n"
	.string "¡Qué sorpresa verte por aquí!\p"
	.string "A todo esto, ¿dónde estará mi {RIVAL}?$"

Route110_Text_HeardYouInstallMatchCall:
	.string "¡Ah, ya!\n"
	.string "Vuestros caminos se han separado.\l"
	.string "Bueno, no importa.\p"
	.string "Ah, sí. He oído que tu POKéNAV\n"
	.string "tiene la AGENDA del MÓVIL activada.\p"
	.string "Por lo tanto, debería registrarte\n"
	.string "en mi POKéNAV, ¿no crees?\p"
	.string "Así, aunque estemos lejos, podré\n"
	.string "seguir evaluando tu POKéDEX.\p"
	.string "Je, je…$"

Route110_Text_RegisteredBirchInPokenav:
	.string "Acabas de registrar al PROF. ABEDUL\n"
	.string "en el POKéNAV.$"

Route110_Text_KeepAnEyeOutForRival:
	.string "PROF. ABEDUL: {PLAYER}{KUN}…\p"
	.string "Vigila de cerca a mi {RIVAL},\n"
	.string "por favor…\p"
	.string "Bueno, será mejor que me vaya.\n"
	.string "¡Hasta la vista, {PLAYER}{KUN}!$"
