
LilycoveCity_DepartmentStore_3F_Text_ItemsBestForTougheningPokemon:
	.string "Gli strumenti sono la cosa più efficace\n"
	.string "per rafforzare i POKéMON.\p"
	.string "La PROTEINA migliora l’ATTACCO e\n"
	.string "il CALCIO potenzia l’ATT. SP.$"

LilycoveCity_DepartmentStore_3F_Text_WantMoreEndurance:
	.string "Voglio migliorare la resistenza\n"
	.string "del mio POKéMON.\p"
	.string "Sono indeciso se migliorare la DIFESA\n"
	.string "con il FERRO o la DIF. SP. con lo ZINCO.$"

LilycoveCity_DepartmentStore_3F_Text_GaveCarbosToSpeedUpMon:
	.string "Ho dato del CARBURANTE al mio POKéMON\n"
	.string "ed è aumentata la sua VELOCITÀ.$"
