
LilycoveCity_DepartmentStore_3F_Text_ItemsBestForTougheningPokemon:
	.string "Si quieres hacer mejorar rápidamente\n"
	.string "a tus POKéMON, usa objetos.\p"
	.string "La PROTEÍNA mejora el ATAQUE\n"
	.string "y el CALCIO aumenta el AT. ESP.$"

LilycoveCity_DepartmentStore_3F_Text_WantMoreEndurance:
	.string "Quiero que mi POKéMON tenga\n"
	.string "más resistencia.\p"
	.string "Ahora no sé si mejorar la DEFENSA\n"
	.string "usando HIERRO o la DEF. ESP. con ZINC.$"

LilycoveCity_DepartmentStore_3F_Text_GaveCarbosToSpeedUpMon:
	.string "He dado CARBURANTE a mi POKéMON\n"
	.string "y su VELOCIDAD ha aumentado.$"
