
Route111_Text_BattleOurFamily:
	.string "Salve! Sei in viaggio?\p"
	.string "Che ne diresti di sfidare tutti e\n"
	.string "quattro i membri della nostra famiglia,\l"
	.string "uno dopo l’altro?$"

Route111_Text_IsThatSo:
	.string "Davvero?\n"
	.string "Torna se cambi idea!$"

Route111_Text_VictorIntro:
	.string "Sì, mi piace la tua grinta!$"

Route111_Text_VictorDefeat:
	.string "Ahi!\n"
	.string "Sei più forte di quanto immaginassi!$"

Route111_Text_VictorPostBattle:
	.string "Ehi, avete visto che forza di\n"
	.string "un ALLENATORE!$"

Route111_Text_VictoriaIntro:
	.string "Ma sei veramente giovane!\p"
	.string "Abbastanza forte da tenere testa a\n"
	.string "mio marito, però!\p"
	.string "Adesso è il mio turno!$"

Route111_Text_VictoriaDefeat:
	.string "Incredibile!\n"
	.string "Impossibile che tu sia così forte!$"

Route111_Text_VictoriaPostBattle:
	.string "Quest’ALLENATORE è forte!\n"
	.string "Davvero forte, vi dico!$"

Route111_Text_ViviIntro:
	.string "Sei più forte di mamma? Wow!\p"
	.string "Ma lo sono anch’io!\n"
	.string "Ti farò vedere io!$"

Route111_Text_ViviDefeat:
	.string "Oh, e così avrei perso?$"

Route111_Text_ViviPostBattle:
	.string "Che rabbia!\p"
	.string "Mi viene da piangere… nonna!$"

Route111_Text_VickyIntro:
	.string "Come osi far piangere la mia nipotina?\p"
	.string "Te la farò pagare!\n"
	.string "Preparati alla disfatta!$"

Route111_Text_VickyDefeat:
	.string "Ehi! Che forza!\n"
	.string "Aveva ragione mia nipote…$"

Route111_Text_VickyPostBattle:
	.string "Se non vai di fretta, resta a farci\n"
	.string "compagnia per un po’.$"

Route111_Text_ToughToKeepWinningUpTheRanks:
	.string "Devi allenare i tuoi POKéMON di più,\n"
	.string "altrimenti sarà difficile continuare a\l"
	.string "vincere a livelli superiori.\p"
	.string "Ho sentito dire che i SUPERQUATTRO \n"
	.string "della LEGA POKéMON sono più forti \l"
	.string "di qualsiasi CAPOPALESTRA.$"

Route111_Text_WinstrateFamilyDestroyedMe:
	.string "Ho sfidato la FAMIGLIA VINCI,\n"
	.string "ma quattro lotte una dopo l’altra sono\l"
	.string "troppe per me… mi hanno annientato.$"

Route111_Text_RouteSignMauville:
	.string "PERCORSO 111\n"
	.string "{DOWN_ARROW} CICLAMIPOLI$"

Route111_Text_WinstrateHouseSign:
	.string "CASA della FAMIGLIA VINCI\n"
	.string "“Una famiglia, un unico cuore!”.$"

Route111_Text_RouteSign112:
	.string "PERCORSO 111\n"
	.string "{LEFT_ARROW} PERCORSO 112$"

Route111_Text_RouteSign113:
	.string "PERCORSO 111\n"
	.string "{LEFT_ARROW} PERCORSO 113$"

Route111_Text_OldLadysRestStopSign:
	.string "OSTELLO della NONNINA\n"
	.string "“Dai sollievo alle tue stanche membra”.$"

Route111_Text_TrainerTipsSpAtkSpDef:
	.string "CONSIGLI UTILI\p"
	.string "Uno degli indicatori della potenza dei\n"
	.string "POKéMON è ATT. SP.\l"
	.string "Significa “ATTACCO SPECIALE”.\p"
	.string "DIF. SP. significa, invece,\n"
	.string "“DIFESA SPECIALE”.$"

Route111_Text_ShouldBeMirageTowerAroundHere:
	.string "Dovrebbe esserci una torre fatta di\n"
	.string "sabbia da queste parti.\p"
	.string "È strano, a volte si vede, a volte no.\p"
	.string "Per questo si chiama TORRE MIRAGGIO.$"

Route111_Text_MirageTowerClearlyVisible:
	.string "La vedo!\n"
	.string "È la torre di sabbia!\p"
	.string "La torre di sabbia! Dicono sia un\n"
	.string "miraggio, ma ora è ben visibile!\p"
	.string "Sembra così instabile, però… potrebbe\n"
	.string "sbriciolarsi da un momento all’altro…\p"
	.string "Vorrei entrarci, ma non penso di avere\n"
	.string "abbastanza coraggio…$"

Route111_Text_ThatWasShockingSandRainedDown:
	.string "Wow!\n"
	.string "Che spavento!\p"
	.string "All’improvviso c’era sabbia\n"
	.string "dappertutto.\p"
	.string "Com’era dentro?\n"
	.string "C’erano fantasmi di sabbia?$"

Route111_Text_MirageTowerHasntBeenSeenSince:
	.string "La torre di sabbia non si è vista\n"
	.string "dall’ultima volta che abbiamo parlato.\p"
	.string "Forse era proprio la TORRE\n"
	.string "MIRAGGIO…$"

Route111_Text_ClawFossilDisappeared:
	.string "Il FOSSILUNGHIA è sparito\n"
	.string "nella sabbia…$"

Route111_Text_RootFossilDisappeared:
	.string "Il RADIFOSSILE è sparito\n"
	.string "nella sabbia…$"

Route111_Text_MauvilleUncleToldMeToTakeRockSmash:
	.string "Oh, no!\p"
	.string "Mio zio di CICLAMIPOLI mi ha consigliato\n"
	.string "di portare con me SPACCAROCCIA se\l"
	.string "voglio dirigermi verso il PERCORSO 111!\p"
	.string "Mio zio? Vive vicino al NEGOZIO\n"
	.string "di BICI di CICLAMIPOLI.$"

Route111_Text_TrainerHillSign:
	.string "{RIGHT_ARROW} ENTRATA del MONTE ALLENATORI\p"
	.string "“Fino alla vetta, ALLENATORI\n"
	.string "appassionati!”.$"
