MatchCall_WildBattleText1::
	.string "Salut, {PLAYER}{KUN}!\n"
	.string "C’est {STR_VAR_1}.\p"
	.string "J’ai vu un {STR_VAR_2}, il y a peu.\n"
	.string "Mais impossible de l’attraper!\p"
	.string "J’étais à deux doigts de réussir,\n"
	.string "pourtant! Allez, au revoir!$"

MatchCall_WildBattleText2::
	.string "Bonjour, {PLAYER}{KUN}.\n"
	.string "C’est {STR_VAR_1}.\p"
	.string "Il n’y a pas très longtemps, j’ai\n"
	.string "essayé d’attraper un {STR_VAR_2}.\p"
	.string "Mais il s’est enfui!\n"
	.string "Tu parles que j’ai été déçue!\p"
	.string "Au revoir!$"

MatchCall_WildBattleText3::
	.string "Salut, {PLAYER}!\n"
	.string "C’est moi, {STR_VAR_1}.\p"
	.string "Je viens d’essayer d’attraper\n"
	.string "un {STR_VAR_2}, mais je l’ai raté.\p"
	.string "C’est rageant, j’étais à\n"
	.string "deux doigts d’y arriver!\p"
	.string "Bon, ça m’a gâché la journée…\n"
	.string "Allez, à plus!$"

MatchCall_WildBattleText4::
	.string "Allô, {PLAYER}{KUN}?\n"
	.string "Ici {STR_VAR_1}. Bonjour!\p"
	.string "Tu connais le POKéMON {STR_VAR_2}?\n"
	.string "J’ai failli en attraper un…\l"
	.string "Je pensais vraiment l’avoir!\p"
	.string "Si j’en revois un, je ne le\n"
	.string "louperai pas!\p"
	.string "Allez, à plus!$"

MatchCall_WildBattleText5::
	.string "Salut, {PLAYER}{KUN}!\n"
	.string "{STR_VAR_1} à l’appareil.\l"
	.string "Alors, des nouveaux POKéMON?\p"
	.string "Moi, j’ai failli en attraper un\n"
	.string "récemment, mais il s’est enfui.\p"
	.string "Bon, à plus!$"

MatchCall_WildBattleText6::
	.string "Salut, {PLAYER}{KUN}.\n"
	.string "Ici {STR_VAR_1}.\l"
	.string "Tu as attrapé des POKéMON?\p"
	.string "L’autre jour, j’en ai presque eu un,\n"
	.string "mais il m’a filé entre les doigts!\p"
	.string "Allez, à bientôt!$"

MatchCall_WildBattleText7::
	.string "{PLAYER}{KUN}, c’est toi?\n"
	.string "Salut, {STR_VAR_1} à l’appareil.\p"
	.string "Tu sais quoi? Je n’arrive pas\n"
	.string "à attraper de {STR_VAR_2}…\p"
	.string "Sacré nom d’un chien!\n"
	.string "Il n’y a rien à faire!$"

MatchCall_WildBattleText8::
	.string "Ça va, {PLAYER}{KUN}?\n"
	.string "C’est {STR_VAR_1}.\p"
	.string "Tu attrapes beaucoup de\n"
	.string "POKéMON en ce moment?\p"
	.string "J’ai failli en attraper un il n’y a\n"
	.string "pas longtemps, mais j’ai échoué.\p"
	.string "Je ne baisse pas les bras!\n"
	.string "A bientôt!$"

MatchCall_WildBattleText9::
	.string "Salut, {PLAYER}{KUN}!\n"
	.string "C’est {STR_VAR_1}!\p"
	.string "Alors, tu agrandis ta collection\n"
	.string "de POKéMON?\p"
	.string "J’en ai par-dessus la tête des\n"
	.string "POKéMON! Ils m’échappent tous!\p"
	.string "A plus!$"

MatchCall_WildBattleText10::
	.string "Coucou, {PLAYER}{KUN}…\n"
	.string "C’est moi, {STR_VAR_1}.\p"
	.string "Je voulais te dire… J’ai failli\n"
	.string "attraper un {STR_VAR_2}…\p"
	.string "Mais je l’ai laissé filer…\p"
	.string "Il faut que je persévère, je sais.\n"
	.string "A bientôt, j’espère.$"

MatchCall_WildBattleText11::
	.string "{PLAYER}{KUN}?\n"
	.string "Bonjour, c’est {STR_VAR_1}.\l"
	.string "Comment ça va?\p"
	.string "J’ai essayé d’attraper un\n"
	.string "{STR_VAR_2} sauvage, mais il a filé!\p"
	.string "Je perds un peu confiance…$"

MatchCall_WildBattleText12::
	.string "Bonjour, {PLAYER}{KUN}.\n"
	.string "C’est {STR_VAR_1}.\l"
	.string "Tu attrapes toujours des POKéMON?\p"
	.string "J’essaie de m’y mettre, mais\n"
	.string "c’est loin d’être facile!\p"
	.string "Les POKéMON sont malins!$"

MatchCall_WildBattleText13::
	.string "Bonjour, {PLAYER}{KUN}!\n"
	.string "C’est {STR_VAR_1} qui appelle!\l"
	.string "Tu as de nouveaux POKéMON?\p"
	.string "J’ai moi-même essayé, mais\n"
	.string "ce fut un échec, je dois dire.\p"
	.string "Les POKéMON sont malins!$"

MatchCall_WildBattleText14::
	.string "Bonjour, {PLAYER}{KUN}, comment vas-tu?\n"
	.string "C’est {STR_VAR_1}.\p"
	.string "Je viens d’essayer d’attraper un\n"
	.string "joli petit {STR_VAR_2}.\p"
	.string "Mais il s’est enfui!\n"
	.string "Crois-moi, j’ai été déçue!\p"
	.string "Au revoir!$"

MatchCall_WildBattleText15::
	.string "Bonjour, {PLAYER}!\n"
	.string "Ici {STR_VAR_1}!\p"
	.string "Je pense me mettre à attraper\n"
	.string "des POKéMON, tu sais.\p"
	.string "Mais le problème, c’est que je n’en\n"
	.string "vois aucun!\p"
	.string "C’est étrange, non?\n"
	.string "Bon, je te laisse. Au revoir!$"

MatchCall_NegativeBattleText1::
	.string "Salut, {PLAYER}{KUN}!\n"
	.string "C’est {STR_VAR_1}.\p"
	.string "J’ai essayé de me battre contre un\n"
	.string "autre DRESSEUR, mais j’ai perdu.\p"
	.string "J’étais très déçu, tu sais.\n"
	.string "Allez, salut!$"

MatchCall_NegativeBattleText2::
	.string "Bonjour, {PLAYER}{KUN}.\n"
	.string "C’est {STR_VAR_1}.\p"
	.string "J’ai affronté quelqu’un d’autre\n"
	.string "après notre combat.\p"
	.string "J’ai été pas mal, mais j’ai perdu.\n"
	.string "Je ferai mieux la prochaine fois.$"

MatchCall_NegativeBattleText3::
	.string "Salut, {PLAYER}!\n"
	.string "C’est moi, {STR_VAR_1}.\p"
	.string "Je viens de perdre un combat.\p"
	.string "Je suppose que mon équipe\n"
	.string "n’est pas encore au point!$"

MatchCall_NegativeBattleText4::
	.string "Salut, {PLAYER}.\n"
	.string "{STR_VAR_1} à l’appareil.\p"
	.string "J’ai refait un combat hier, mais\n"
	.string "je n’en suis pas sorti vainqueur.\p"
	.string "Je dois entraîner mon équipe\n"
	.string "davantage. Allez, à plus!$"

MatchCall_NegativeBattleText5::
	.string "Salut, {PLAYER}!\n"
	.string "{STR_VAR_1} à l’appareil.\p"
	.string "Tout se passe bien?\p"
	.string "J’ai fait quelques combats, mais\n"
	.string "je n’ai pas gagné souvent.\p"
	.string "Je ne suis pas encore au point!\n"
	.string "Bon, à plus!$"

MatchCall_NegativeBattleText6::
	.string "Salut, {PLAYER}.\n"
	.string "Ici {STR_VAR_1}.\p"
	.string "Tout va comme tu veux?\p"
	.string "Je mets toute mon énergie\n"
	.string "au combat, mais je perds souvent.\p"
	.string "Je ne suis pas encore dans l’esprit.\n"
	.string "Allez, à bientôt!$"

MatchCall_NegativeBattleText7::
	.string "Ici {STR_VAR_1}.\n"
	.string "Comment ça se passe?\p"
	.string "J’ai perdu un combat hier.\n"
	.string "Je n’arrête pas d’y penser.\p"
	.string "Il faut que je me reprenne…\n"
	.string "Salut!$"

MatchCall_NegativeBattleText8::
	.string "Ça va, {PLAYER}{KUN}?\n"
	.string "C’est {STR_VAR_1}.\p"
	.string "Comment vont tes POKéMON?\n"
	.string "J’ai perdu un combat, l’autre jour.\p"
	.string "Je ne baisse pas les bras!\n"
	.string "Allez, à bientôt!$"

MatchCall_NegativeBattleText9::
	.string "Salut, {PLAYER}{KUN}!\n"
	.string "C’est {STR_VAR_1}!\p"
	.string "Ecoute, j’ai quelque chose à\n"
	.string "te dire!\p"
	.string "J’ai fait un combat de POKéMON hier\n"
	.string "et j’ai perdu au dernier moment.\p"
	.string "Qu’est-ce que c’est frustrant!$"

MatchCall_NegativeBattleText10::
	.string "Coucou, {PLAYER}{KUN}…\n"
	.string "C’est moi, {STR_VAR_1}.\p"
	.string "J’ai fait un combat aujourd’hui.\n"
	.string "Mais j’ai perdu…\p"
	.string "Mes POKéMON ne sont pas encore\n"
	.string "au top niveau. A bientôt, j’espère.$"

MatchCall_NegativeBattleText11::
	.string "{PLAYER}{KUN}?\n"
	.string "Bonjour, c’est {STR_VAR_1}.\l"
	.string "Comment vont tes POKéMON?\p"
	.string "Moi, je viens de perdre un combat.\n"
	.string "C’est pas la joie…\p"
	.string "Bon, au revoir!$"

MatchCall_NegativeBattleText12::
	.string "Bonjour, {PLAYER}{KUN}.\n"
	.string "C’est {STR_VAR_1}.\l"
	.string "Tu continues les combats?\p"
	.string "Je perds souvent ces derniers\n"
	.string "temps. \p"
	.string "Je dois renforcer mon équipe!\n"
	.string "A bientôt.$"

MatchCall_NegativeBattleText13::
	.string "Bonjour, {PLAYER}{KUN}!\n"
	.string "C’est {STR_VAR_1} qui appelle!\p"
	.string "J’espère que tu te portes bien.\p"
	.string "J’ai fait un combat tout\n"
	.string "récemment.\p"
	.string "Prends-en de la graine, {PLAYER}{KUN}!\n"
	.string "Il faut garder la forme! Au revoir!$"

MatchCall_NegativeBattleText14::
	.string "Bonjour, {PLAYER}{KUN}.\n"
	.string "C’est {STR_VAR_1}.\p"
	.string "Tout se passe comme tu veux?\p"
	.string "Tu sais, tu devrais rentrer\n"
	.string "chez toi de temps en temps.\p"
	.string "Au revoir!$"

MatchCall_PositiveBattleText1::
	.string "Salut, {PLAYER}{KUN}!\n"
	.string "C’est {STR_VAR_1}.\p"
	.string "J’ai combattu contre un autre\n"
	.string "DRESSEUR et j’ai gagné!\p"
	.string "Mon {STR_VAR_2} s’est vraiment\n"
	.string "démené! C’est super!$"

MatchCall_PositiveBattleText2::
	.string "Salut, {PLAYER}{KUN}!\n"
	.string "C’est {STR_VAR_1}!\p"
	.string "J’ai gagné un combat hier,\n"
	.string "c’était super!$"

MatchCall_PositiveBattleText3::
	.string "Salut, {PLAYER}!\n"
	.string "C’est moi, {STR_VAR_1}.\l"
	.string "Ça va, les combats?\p"
	.string "Moi, j’en ai fait un l’autre jour\n"
	.string "et mon {STR_VAR_2} a été épatant!\p"
	.string "Si on refait un combat, je ne\n"
	.string "perdrai pas, {PLAYER}!$"

MatchCall_PositiveBattleText4::
	.string "Salut, {PLAYER}.\n"
	.string "C’est {STR_VAR_1}.\p"
	.string "J’ai fait un combat, aujourd’hui.\n"
	.string "J’ai gagné, mais de justesse!\p"
	.string "Mon {STR_VAR_2} a été super, en\n"
	.string "tout cas.$"

MatchCall_PositiveBattleText5::
	.string "Salut, {PLAYER}{KUN}!\n"
	.string "{STR_VAR_1} à l’appareil.\p"
	.string "Comment va la vie?\n"
	.string "Toujours à faire des combats?\p"
	.string "Tiens, j’en ai gagné un il n’y a pas\n"
	.string "longtemps grâce à mon {STR_VAR_2}!\p"
	.string "La prochaine fois, c’est toi que\n"
	.string "je battrai! Bon, à plus!$"

MatchCall_PositiveBattleText6::
	.string "Salut, {PLAYER}{KUN}.\n"
	.string "Ici {STR_VAR_1}.\p"
	.string "Comment va?\p"
	.string "Pour moi tout baigne, je viens\n"
	.string "de gagner un combat.\p"
	.string "Si jamais on se recroise,\n"
	.string "je ne perdrai pas!$"

MatchCall_PositiveBattleText7::
	.string "{PLAYER}{KUN}?\n"
	.string "Ici {STR_VAR_1}.\p"
	.string "J’adore mon {STR_VAR_2}, il vient\n"
	.string "juste de me faire gagner!\p"
	.string "J’ai hâte de refaire un combat\n"
	.string "contre toi.$"

MatchCall_PositiveBattleText8::
	.string "Ça va, {PLAYER}{KUN}?\n"
	.string "C’est {STR_VAR_1}.\p"
	.string "J’espère que tu vas bien. Tu sais,\n"
	.string "je viens de gagner un combat!\p"
	.string "Mon {STR_VAR_2} a été brillant!\n"
	.string "Il fallait que je te le dise!\p"
	.string "Au revoir!$"

MatchCall_PositiveBattleText9::
	.string "Salut, {PLAYER}{KUN}!\n"
	.string "C’est {STR_VAR_1}!\p"
	.string "Comment vont tes POKéMON?\n"
	.string "Nous, on vient de gagner un combat!\p"
	.string "Mon {STR_VAR_2} a été absolument\n"
	.string "spectaculaire.\p"
	.string "Quel dommage que tu n’aies pas\n"
	.string "vu ça! Au revoir!$"

MatchCall_PositiveBattleText10::
	.string "Coucou, {PLAYER}{KUN}…\n"
	.string "C’est moi, {STR_VAR_1}.\p"
	.string "Comment va la vie?\p"
	.string "Mes POKéMON sont en super forme,\n"
	.string "ces derniers temps.\p"
	.string "Ils viennent de me faire gagner un\n"
	.string "combat. A bientôt, j’espère.$"

MatchCall_PositiveBattleText11::
	.string "{PLAYER}{KUN}?\n"
	.string "Bonjour, c’est {STR_VAR_1}.\p"
	.string "Tu as fait des combats, récemment?\n"
	.string "Moi, j’en ai gagné un aujourd’hui!\p"
	.string "Je suis sur la bonne voie!\n"
	.string "Allez, au revoir!$"

MatchCall_PositiveBattleText12::
	.string "Bonjour, {PLAYER}{KUN}.\n"
	.string "C’est {STR_VAR_1}.\p"
	.string "Tout va bien, mon petit?\n"
	.string "Je suis frais comme un gardon!\p"
	.string "Je n’arrête pas de gagner des\n"
	.string "combats, tous les jours!\l"
	.string "Contre des jeunes gens, en plus!$"

MatchCall_PositiveBattleText13::
	.string "Bonjour, {PLAYER}{KUN}!\n"
	.string "C’est {STR_VAR_1} qui appelle!\p"
	.string "J’espère que tout va bien.\n"
	.string "Moi j’ai la pêche!\p"
	.string "J’enchaîne les victoires aux\n"
	.string "combats! Et les petits jeunes\l"
	.string "ne me font pas peur, tu sais!\p"
	.string "Au revoir!$"

MatchCall_PositiveBattleText14::
	.string "Bonjour, {PLAYER}{KUN}.\n"
	.string "C’est {STR_VAR_1}.\p"
	.string "J’ai fait un combat il y a peu et\n"
	.string "mon {STR_VAR_2} a été formidable!\p"
	.string "J’aurais aimé que tu voies ça,\n"
	.string "{PLAYER}{KUN}. Au revoir!$"

MatchCall_SameRouteBattleRequestText1::
	.string "Salut, {PLAYER}!\n"
	.string "C’est {STR_VAR_1}.\p"
	.string "Quoi, tu es près de…\n"
	.string "{STR_VAR_2}, tu dis?\p"
	.string "Mais il faut qu’on fasse un combat!\n"
	.string "Je t’attends, à tout de suite!$"

MatchCall_SameRouteBattleRequestText2::
	.string "Salut, {PLAYER}!\n"
	.string "C’est {STR_VAR_1}.\p"
	.string "{STR_VAR_2}? C’est là que tu\n"
	.string "es?\p"
	.string "On fait un combat?\n"
	.string "Allez, je t’attends!$"

MatchCall_SameRouteBattleRequestText3::
	.string "Salut, {PLAYER}!\n"
	.string "C’est moi, {STR_VAR_1}.\p"
	.string "{STR_VAR_2}, tu dis?\n"
	.string "C’est là que tu te trouves?\p"
	.string "Que le monde est petit!\n"
	.string "On fait un combat?\p"
	.string "Cette fois, je ne perdrai pas!\n"
	.string "Je ne bouge pas, je t’attends!$"

MatchCall_SameRouteBattleRequestText4::
	.string "Allô, {PLAYER}{KUN}?\n"
	.string "Ici {STR_VAR_1}. Bonjour!\p"
	.string "Où tu es?\n"
	.string "{STR_VAR_2}? Ah, oui?\p"
	.string "Il faut absolument qu’on fasse un\n"
	.string "combat, alors! Je t’attends!$"

MatchCall_SameRouteBattleRequestText5::
	.string "Salut, {PLAYER}{KUN}!\n"
	.string "{STR_VAR_1} à l’appareil.\l"
	.string "Ça roule?\p"
	.string "Où es-tu?\n"
	.string "{STR_VAR_2}?\p"
	.string "Si on en profitait pour refaire un\n"
	.string "combat?\p"
	.string "J’espère bien que tu vas venir!\n"
	.string "Je t’attends!$"

MatchCall_SameRouteBattleRequestText6::
	.string "Salut, {PLAYER}{KUN}.\n"
	.string "Ici {STR_VAR_1}.\l"
	.string "Je viens aux nouvelles.\p"
	.string "{STR_VAR_2}, vraiment? On\n"
	.string "est tout près, alors!\p"
	.string "C’est l’occasion ou jamais de\n"
	.string "refaire un combat!\p"
	.string "Je trépigne d’impatience.\n"
	.string "A tout de suite, je t’attends!$"

MatchCall_SameRouteBattleRequestText7::
	.string "Heu… {PLAYER}{KUN}?\n"
	.string "Ici {STR_VAR_1}…\p"
	.string "{STR_VAR_2}? Tu es dans le\n"
	.string "coin, alors!\p"
	.string "Faisons un combat!\n"
	.string "Tu viens?\p"
	.string "Je vais te montrer mes POKéMON.\n"
	.string "Dépêche-toi, je t’attends.$"

MatchCall_SameRouteBattleRequestText8::
	.string "Ça va, {PLAYER}{KUN}?\n"
	.string "C’est {STR_VAR_1}.\p"
	.string "Tu es près de…\n"
	.string "{STR_VAR_2}, c’est ça?\p"
	.string "Ça te dirait de faire un petit\n"
	.string "combat contre moi?\p"
	.string "Allez, je t’attends.\n"
	.string "A très bientôt!$"

MatchCall_SameRouteBattleRequestText9::
	.string "Salut, {PLAYER}{KUN}!\n"
	.string "C’est {STR_VAR_1}!\p"
	.string "La forme?\n"
	.string "{STR_VAR_2}? Pas possible!\p"
	.string "Ne ratons pas cette occasion.\n"
	.string "On fait un combat?\p"
	.string "Bon allez, je t’attends!$"

MatchCall_SameRouteBattleRequestText10::
	.string "Coucou, {PLAYER}{KUN}…\n"
	.string "C’est moi, {STR_VAR_1}.\p"
	.string "Tu es où? Près de… \n"
	.string "{STR_VAR_2}?!? J’y suis!\p"
	.string "J’ai très envie de te voir.\n"
	.string "On fait un combat?\p"
	.string "Je suis prête!\n"
	.string "Ne me fais pas attendre…$"

MatchCall_SameRouteBattleRequestText11::
	.string "{PLAYER}{KUN}?\n"
	.string "Bonjour, c’est {STR_VAR_1}.\p"
	.string "Où est-ce que tu es?\n"
	.string "{STR_VAR_2}?\p"
	.string "Il faut qu’on se rencontre pour\n"
	.string "un combat, qu’en dis-tu?\p"
	.string "D’accord, je ne bouge pas.\n"
	.string "A tout de suite!$"

MatchCall_SameRouteBattleRequestText12::
	.string "Bonjour, {PLAYER}{KUN}.\n"
	.string "C’est {STR_VAR_1}.\l"
	.string "Où es-tu, mon petit?\p"
	.string "{STR_VAR_2}?\n"
	.string "Je ne suis pas loin!\p"
	.string "Et si on faisait un combat?\n"
	.string "C’est l’occasion ou jamais!\p"
	.string "Je t’attends, mon petit.\n"
	.string "A bientôt!$"

MatchCall_SameRouteBattleRequestText13::
	.string "Bonjour, {PLAYER}{KUN}!\n"
	.string "C’est {STR_VAR_1} qui appelle!\p"
	.string "Où te trouves-tu?\n"
	.string "{STR_VAR_2}?\p"
	.string "Ecoute, je suis tout près. Tu viens\n"
	.string "me voir pour faire un combat?\p"
	.string "Bien, je t’attends.\n"
	.string "A tout de suite.$"

MatchCall_SameRouteBattleRequestText14::
	.string "Bonjour, {PLAYER}{KUN}.\n"
	.string "C’est {STR_VAR_1}.\p"
	.string "Où ça? {STR_VAR_2}?\n"
	.string "Mais c’est tout près!\p"
	.string "Tu ne crois pas qu’on devrait se\n"
	.string "rencontrer pour un combat?\p"
	.string "D’accord, je t’attends.\n"
	.string "Au revoir!$"

MatchCall_DifferentRouteBattleRequestText1::
	.string "Salut, {PLAYER}!\n"
	.string "C’est {STR_VAR_1}.\p"
	.string "Tu sais quoi? J’ai envie de faire un\n"
	.string "combat contre toi!\p"
	.string "Bon, je suis aux alentours de\n"
	.string "{STR_VAR_2}. A bientôt!$"

MatchCall_DifferentRouteBattleRequestText2::
	.string "Salut, {PLAYER}!\n"
	.string "C’est {STR_VAR_1}.\p"
	.string "Dis, tu veux bien refaire un\n"
	.string "combat contre moi?\p"
	.string "Tu me trouveras près de\n"
	.string "{STR_VAR_2}. A plus!$"

MatchCall_DifferentRouteBattleRequestText3::
	.string "Salut, {PLAYER}!\n"
	.string "C’est moi, {STR_VAR_1}.\p"
	.string "Mes POKéMON ont bien progressé\n"
	.string "depuis la dernière fois.\p"
	.string "J’aimerais bien qu’ils se mesurent\n"
	.string "de nouveau aux tiens, {PLAYER}.\p"
	.string "On refait un combat?\p"
	.string "D’accord, je suis près de\n"
	.string "{STR_VAR_2}.$"

MatchCall_DifferentRouteBattleRequestText4::
	.string "Allô, {PLAYER}{KUN}?\n"
	.string "Ici {STR_VAR_1}. Bonjour!\l"
	.string "Ça va, toi?\p"
	.string "Mes POKéMON sont bien meilleurs,\n"
	.string "tu sais.\p"
	.string "Tu veux bien qu’on refasse un\n"
	.string "combat?\p"
	.string "D’accord, je t’attends aux\n"
	.string "alentours de {STR_VAR_2}.$"

MatchCall_DifferentRouteBattleRequestText5::
	.string "Salut, {PLAYER}{KUN}!\n"
	.string "{STR_VAR_1} à l’appareil.\p"
	.string "Mes POKéMON ont bien progressé,\n"
	.string "je suis drôlement fier d’eux.\p"
	.string "J’aimerais refaire un combat\n"
	.string "contre toi.\p"
	.string "Je t’attends du côté de\n"
	.string "{STR_VAR_2}, alors. A plus!$"

MatchCall_DifferentRouteBattleRequestText6::
	.string "Salut, {PLAYER}{KUN}.\n"
	.string "Ici {STR_VAR_1}.\l"
	.string "J’espère que ça roule pour toi.\p"
	.string "Je me disais que j’aimerais bien\n"
	.string "faire un autre combat contre toi.\p"
	.string "Ecoute, si ça te dit, on peut se\n"
	.string "voir près de {STR_VAR_2}.\p"
	.string "Peut-être à tout à l’heure!$"

MatchCall_DifferentRouteBattleRequestText7::
	.string "Heu… {PLAYER}{KUN}?\n"
	.string "Ici {STR_VAR_1}…\l"
	.string "Alors? Tes POKéMON vont bien?\p"
	.string "Les miens sont de plus en plus\n"
	.string "forts! J’aimerais que tu les voies.\p"
	.string "Je suis près de {STR_VAR_2}.\n"
	.string "Passe, si tu veux combattre.\p"
	.string "Au revoir.$"

MatchCall_DifferentRouteBattleRequestText8::
	.string "Ça va, {PLAYER}{KUN}?\n"
	.string "C’est {STR_VAR_1}.\p"
	.string "J’espère que tout va bien pour toi.\n"
	.string "Mes POKéMON sont en super forme.\p"
	.string "Si tu passes dans le coin,\n"
	.string "j’aimerais bien qu’on combatte.\p"
	.string "Je suis près de {STR_VAR_2}.\n"
	.string "A bientôt, j’espère!$"

MatchCall_DifferentRouteBattleRequestText9::
	.string "Salut, {PLAYER}{KUN}!\n"
	.string "C’est {STR_VAR_1}!\l"
	.string "Comment vont tes POKéMON?\p"
	.string "Les miens progressent à vue\n"
	.string "d’œil, {PLAYER}{KUN}.\p"
	.string "Je suis près de {STR_VAR_2}.\n"
	.string "Passe faire un combat, si tu veux.\p"
	.string "J’espère te voir bientôt!$"

MatchCall_DifferentRouteBattleRequestText10::
	.string "Coucou, {PLAYER}{KUN}…\n"
	.string "C’est moi, {STR_VAR_1}.\l"
	.string "Comment vas-tu?\p"
	.string "Mes POKéMON ont fait d’énormes\n"
	.string "progrès.\p"
	.string "J’aimerais beaucoup refaire un\n"
	.string "combat contre toi, {PLAYER}{KUN}.\p"
	.string "Je suis près de {STR_VAR_2}.\n"
	.string "Passe me voir à l’occasion.$"

MatchCall_DifferentRouteBattleRequestText11::
	.string "{PLAYER}{KUN}?\n"
	.string "Bonjour, c’est {STR_VAR_1}.\p"
	.string "Mes POKéMON débordent de vie.\n"
	.string "Je pense qu’ils ont envie de revoir\l"
	.string "tes POKéMON, {PLAYER}{KUN}.\p"
	.string "Je suis vers {STR_VAR_2}.\n"
	.string "J’espère que tu vas passer.$"

MatchCall_DifferentRouteBattleRequestText12::
	.string "Bonjour, {PLAYER}{KUN}.\n"
	.string "C’est {STR_VAR_1}.\p"
	.string "Je voulais te dire que mes POKéMON\n"
	.string "sont devenus très forts.\p"
	.string "J’aimerais bien qu’on refasse un\n"
	.string "combat tous les deux, {PLAYER}{KUN}.\p"
	.string "On est aux alentours de\n"
	.string "{STR_VAR_2}. A bientôt!$"

MatchCall_DifferentRouteBattleRequestText13::
	.string "Bonjour, {PLAYER}{KUN}!\n"
	.string "C’est {STR_VAR_1} qui appelle!\l"
	.string "Comment vont tes POKéMON?\p"
	.string "Mes POKéMON vont tellement bien\n"
	.string "qu’ils battraient n’importe qui!\p"
	.string "J’aimerais faire un nouveau combat\n"
	.string "contre toi, pour les tester.\p"
	.string "Si tu passes près de\n"
	.string "{STR_VAR_2}, viens nous voir.$"

MatchCall_DifferentRouteBattleRequestText14::
	.string "Bonjour, {PLAYER}{KUN}.\n"
	.string "C’est {STR_VAR_1}.\l"
	.string "J’espère que tu vas bien.\p"
	.string "Oui, mes POKéMON ont beaucoup\n"
	.string "appris depuis la dernière fois.\p"
	.string "Tu ne crois pas qu’on devrait\n"
	.string "refaire un combat, {PLAYER}{KUN}?\p"
	.string "On est près de {STR_VAR_2},\n"
	.string "en ce moment.\p"
	.string "J’espère que tu vas venir nous\n"
	.string "voir bientôt!$"

MatchCall_PersonalizedText1::
	.string "C’est {STR_VAR_1}, l’amoureux de la\n"
	.string "montagne!\p"
	.string "Tu as passé du temps en montagne\n"
	.string "depuis la dernière fois?\p"
	.string "J’y suis souvent mais je te croise\n"
	.string "rarement…\p"
	.string "La prochaine fois, on pourrait se\n"
	.string "voir près de {STR_VAR_2}.$"

MatchCall_PersonalizedText2::
	.string "C’est {STR_VAR_1}.\n"
	.string "Bonjour.\p"
	.string "J’ai parlé de toi à un nouveau\n"
	.string "DRESSEUR.\p"
	.string "J’ai dit que je connaissais un bon\n"
	.string "DRESSEUR qui s’occupe de ses\l"
	.string "POKéMON avec grand soin.\p"
	.string "D’ici peu, tout le monde t’admirera.\n"
	.string "Tu vas devenir célèbre!\p"
	.string "J’espère qu’on se reverra!$"

MatchCall_PersonalizedText3::
	.string "C’est {STR_VAR_1}. Bonjour!\p"
	.string "Je me trouve dans un endroit\n"
	.string "magnifique aux senteurs exquises!\p"
	.string "Quelqu’un a dû planter des BAIES.\p"
	.string "Au revoir!$"

MatchCall_PersonalizedText4::
	.string "Bonjour! Trente ans de fouilles,\n"
	.string "{STR_VAR_1} à ton service!\p"
	.string "On dirait que tu as la bougeotte,\n"
	.string "tu es toujours en vadrouille.\p"
	.string "Tu as découvert des ruines en\n"
	.string "chemin? Si tu en vois, pense à moi!\p"
	.string "Je te laisse, j’ai des ruines à\n"
	.string "fouiller.$"

MatchCall_PersonalizedText5::
	.string "C’est {STR_VAR_1}!\p"
	.string "Devine ce que je fais!\n"
	.string "J’admire les vagues sur la plage!\p"
	.string "Oh… Les reflets du soleil sur l’eau\n"
	.string "sont magnifiques. Ça scintille!\l"
	.string "Je commence à avoir faim. Au revoir!$"

MatchCall_PersonalizedText6::
	.string "Miam, miam…\n"
	.string "Oh, salut! C’est {STR_VAR_1}.\l"
	.string "J’adore manger sur la plage.\p"
	.string "Mes POKéMON et moi allons bien.\n"
	.string "On est gonflés à bloc!\l"
	.string "Je vais faire trempette. Au revoir!$"

MatchCall_PersonalizedText7::
	.string "Salut, c’est {STR_VAR_1}…\p"
	.string "Cette histoire de TOPDRESSEUR\n"
	.string "m’est un peu montée à la tête…\p"
	.string "Tout le monde croit que je suis un\n"
	.string "DRESSEUR parfait. Je ne veux pas\l"
	.string "les décevoir.\p"
	.string "Je suppose que c’est le revers\n"
	.string "de la médaille.\p"
	.string "Il faut que je m’entraîne dur…\n"
	.string "Et avec le sourire, en plus!\p"
	.string "Il n’y a vraiment qu’à toi que je\n"
	.string "pouvais dire ça.\p"
	.string "Merci, ça m’a fait du bien de te\n"
	.string "parler!$"

MatchCall_PersonalizedText8::
	.string "Salut, toi! C’est {STR_VAR_1}!\n"
	.string "Ça va?\p"
	.string "J’essaie de bien m’occuper de mes\n"
	.string "POKéMON. Tu es mon modèle.\p"
	.string "La prochaine fois qu’on se battra,\n"
	.string "je ferai tout pour gagner.\p"
	.string "C’est super d’avoir des amis\n"
	.string "DRESSEURS! A bientôt!$"

MatchCall_PersonalizedText9::
	.string "C’est {STR_VAR_1}…\n"
	.string "Attention, derrière toi…\l"
	.string "Il y avait quelque chose, non?\p"
	.string "La puissance des POKéMON qui\n"
	.string "reposent au MONT MEMORIA…\p"
	.string "Elle me parle de toi…\p"
	.string "Tu dois partir immédiatement!\n"
	.string "Surtout, ne te retourne pas…\p"
	.string "Au revoir…$"

MatchCall_PersonalizedText10::
	.string "C’est {STR_VAR_1}.\n"
	.string "Comment tu vas?\p"
	.string "C’est pratique de pouvoir garder\n"
	.string "le contact comme ça!\p"
	.string "Avant, quand je voulais parler avec\n"
	.string "quelqu’un, je devais demander à\l"
	.string "mon père de me déposer en voiture…\p"
	.string "Bon, je te laisse.\n"
	.string "Contente d’avoir parlé avec toi!$"

MatchCall_PersonalizedText11::
	.string "C’est {STR_VAR_1}!\n"
	.string "J’ai quelque chose à te dire.\p"
	.string "J’aime beaucoup le PARC SAFARI,\n"
	.string "mais je m’y perds tout le temps!\p"
	.string "Les herbes sont trop hautes!\n"
	.string "En plus, c’est immense!\p"
	.string "J’avais besoin de confier ça à\n"
	.string "quelqu’un!\p"
	.string "Bon, je retourne au PARC SAFARI!\n"
	.string "Au revoir!$"

MatchCall_PersonalizedText12::
	.string "Bonjour, ici {STR_VAR_1}.\n"
	.string "Oui, je suis riche. C’est bien vrai.\p"
	.string "Je suis encore plus riche que la\n"
	.string "dernière fois.\p"
	.string "Sinon, mes POKéMON vont bien.\n"
	.string "Ils ont beaucoup progressé.\p"
	.string "J’ai l’impression que ce monde\n"
	.string "a été créé pour moi!\p"
	.string "Je sais ce que tu penses.\n"
	.string "Mais c’est vrai!\p"
	.string "Je te prie de m’excuser.\n"
	.string "Je dois me rendre à une réception.$"

MatchCall_PersonalizedText13::
	.string "C’est moi, {STR_VAR_1}…\p"
	.string "Devine ce que je vois…\n"
	.string "Deux {STR_VAR_2} en plein combat!\p"
	.string "Je vais essayer d’attraper le\n"
	.string "gagnant… Oui, tiens…\p"
	.string "Bon… Il faut que j’y aille.\n"
	.string "Je te laisse.$"

MatchCall_PersonalizedText14::
	.string "C’est {STR_VAR_1}!\p"
	.string "Tu sais, j’en ai un peu marre de\n"
	.string "l’EPAVE.\p"
	.string "Mais puisque j’y suis et que\n"
	.string "j’aimerais te battre une fois, je\l"
	.string "vais y rester encore un peu.\p"
	.string "Je ne veux pas te forcer, mais\n"
	.string "pourquoi tu ne viens pas?\p"
	.string "Je pense qu’aujourd’hui je vais\n"
	.string "défier l’homme d’à côté. J’ai\l"
	.string "envie d’un petit combat.\p"
	.string "Au revoir!$"

MatchCall_PersonalizedText15::
	.string "C’est {STR_VAR_1}!\n"
	.string "Le garçon amphibie!\p"
	.string "Tu sais ce que je crois?\p"
	.string "Que c’est en mer qu’on trouve les\n"
	.string "meilleurs DRESSEURS!\p"
	.string "Tu devrais prendre exemple sur moi\n"
	.string "et venir t’entraîner en mer…\p"
	.string "Waouh!!! Une vague géante arrive!\n"
	.string "Je vais la surfer!\p"
	.string "C’est génial de s’entraîner ici!\n"
	.string "Il faut que je te laisse!$"

MatchCall_PersonalizedText16::
	.string "C’est {STR_VAR_1}! J’ai donné des\n"
	.string "cours de karaté à mes POKéMON.\p"
	.string "Ils sont devenus meilleurs que moi!\n"
	.string "Ils apprennent vite!\p"
	.string "Mais grâce à eux, je ne perdrai\n"
	.string "plus un seul combat de POKéMON!\p"
	.string "Il faut qu’on en refasse un,\n"
	.string "au fait! Yah!!!$"

MatchCall_PersonalizedText17::
	.string "C’est moi, {STR_VAR_1}.\n"
	.string "Comment se déroule ton voyage?\p"
	.string "Waouh, vraiment?\n"
	.string "Ça a l’air super intéressant!\p"
	.string "Je pourrais bien en faire une\n"
	.string "chanson!\p"
	.string "…\n"
	.string "J’ai un début de mélodie en tête.\p"
	.string "Il faut que j’aille mettre tout ça\n"
	.string "par écrit, sinon je vais oublier!$"

MatchCall_PersonalizedText18::
	.string "C’est {STR_VAR_1}…\n"
	.string "Voici ma nouvelle chanson.\p"
	.string "Tralala, {STR_VAR_2}, {STR_VAR_2}!\n"
	.string "Mon petit {STR_VAR_2}!\l"
	.string "Mon mignon {STR_VAR_2}!\l"
	.string "Tralala, {STR_VAR_1}, {STR_VAR_2}…\l"
	.string "{STR_VAR_1} et {STR_VAR_2}…\p"
	.string "C’est le refrain!$"

MatchCall_PersonalizedText19::
	.string "C’est moi {STR_VAR_1},\n"
	.string "le pro du camping!\p"
	.string "La dernière fois, je n’ai pas réussi\n"
	.string "à te battre.\p"
	.string "On ne peut pas être bon en tout!\p"
	.string "Mais quand je fais du camping,\n"
	.string "j’aime bien faire des combats.\p"
	.string "Viens nous voir à l’occasion!\n"
	.string "Sur ce, je vais camper. Salut!$"

MatchCall_PersonalizedText20::
	.string "C’est moi, {STR_VAR_1}!\p"
	.string "Pour être honnête, j’aimerais bien\n"
	.string "aller randonner ailleurs.\p"
	.string "Mais il y a tellement de jolies\n"
	.string "filles sur le MONT CHIMNEE…\p"
	.string "Si tu connais des montagnes avec\n"
	.string "plein de jolies filles, dis-le-moi!\p"
	.string "Hé, hé, hé! Au revoir!$"

MatchCall_PersonalizedText21::
	.string "… … … … … …\n"
	.string "… … … … … …\l"
	.string "C’est {STR_VAR_1}…\p"
	.string "… … … … … …\n"
	.string "… … … … … …\l"
	.string "C’est tout pour aujourd’hui…$"

MatchCall_PersonalizedText22::
	.string "C’est {STR_VAR_1}. J’avais envie\n"
	.string "de te parler.\p"
	.string "De jour en jour, mon désir de te\n"
	.string "battre grandit.\p"
	.string "Mais tu dois avoir beaucoup de\n"
	.string "rivaux…\p"
	.string "J’espère avoir bientôt la chance\n"
	.string "d’être ton adversaire. Au revoir!$"

MatchCall_PersonalizedText23::
	.string "C’est {STR_VAR_1}.\p"
	.string "Tu sais, quand un bon DRESSEUR\n"
	.string "passe près de moi, je le sens.\p"
	.string "Où es-tu en ce moment, {PLAYER}{KUN}?\n"
	.string "Je crois avoir senti ta présence…\p"
	.string "J’espère te voir bientôt.\n"
	.string "Au revoir!$"

MatchCall_PersonalizedText24::
	.string "Bonjour, c’est {STR_VAR_1}.\n"
	.string "Tu as l’air d’aller bien, {PLAYER}{KUN}.\p"
	.string "J’ai beaucoup voyagé, je suis allé\n"
	.string "un peu partout…\l"
	.string "C’est cette région que je préfère.\p"
	.string "Je compte y rester encore un peu.\n"
	.string "J’espère qu’on se reverra avant\l"
	.string "que je parte.\p"
	.string "Je n’ai pas oublié tes techniques\n"
	.string "impressionnantes.\p"
	.string "J’espère qu’on aura le temps de\n"
	.string "refaire un combat.$"

MatchCall_PersonalizedText25::
	.string "Sniff… C’est… {STR_VAR_1}…\n"
	.string "Sniff…\p"
	.string "ROXANNE m’a grondé en classe\n"
	.string "aujourd’hui.\p"
	.string "Mais je l’aime bien quand même.\p"
	.string "Elle me permet de prendre\n"
	.string "conscience de mes erreurs.\p"
	.string "Bien sûr que je retourne à\n"
	.string "l’ECOLE DE DRESSEURS demain!\p"
	.string "Au revoir!$"

MatchCall_PersonalizedText26::
	.string "C’est {STR_VAR_1}!\p"
	.string "ROXANNE m’a permis de me battre\n"
	.string "contre elle hier.\p"
	.string "J’ai perdu… Faut pas poser\n"
	.string "ce genre de questions!\p"
	.string "Mais j’étais contente qu’elle me\n"
	.string "laisse me mesurer à elle.\p"
	.string "Je l’admire encore plus maintenant!\p"
	.string "Je vais travailler encore plus dur!\n"
	.string "D’ailleurs, il faut que j’y aille!$"

MatchCall_PersonalizedText27::
	.string "Bonjour, c’est ANNA! Je suis avec\n"
	.string "ma charmante partenaire, EVA.\p"
	.string "J’adore m’occuper d’EVA et de\n"
	.string "mes POKéMON. Ils sont mignons!\p"
	.string "C’est comme s’ils faisaient partie\n"
	.string "de ma famille!\p"
	.string "Salut, EVA!\n"
	.string "Tu as acheté le pain?\p"
	.string "Quoi? Mais non, je ne te traite pas\n"
	.string "comme une esclave, voyons!\p"
	.string "Tu as perdu, alors c’est à toi\n"
	.string "d’acheter le pain, c’est tout!\p"
	.string "Je t’aime trop! Je ne te traiterai\n"
	.string "jamais comme une esclave!\p"
	.string "Je dois y aller,\n"
	.string "on va manger!$"

MatchCall_PersonalizedText28::
	.string "J’adore les POKéMON!\n"
	.string "C’est {STR_VAR_1} du FAN CLUB!\p"
	.string "Un truc incroyable s’est passé!\n"
	.string "Mes petits POKéMON…\p"
	.string "Oups! Je ne peux pas en dire plus,\n"
	.string "c’est un secret! De toute façon,\l"
	.string "je ne trouverais pas les mots.\p"
	.string "Oh, mon petit {STR_VAR_2} me\n"
	.string "réclame un {POKEBLOCK}!\p"
	.string "Ce n’est pas beau de réclamer!!!\n"
	.string "Mais il est si mignon, celui-là…\p"
	.string "Désolé, le devoir m’appelle! Je\n"
	.string "t’en dirai plus la prochaine fois!$"

MatchCall_PersonalizedText29::
	.string "Oh, oh!\p"
	.string "C’est {STR_VAR_1}! J’ai plein de\n"
	.string "choses à te raconter!\p"
	.string "Tiens, écoute ça! C’est sur mon\n"
	.string "tout petit {STR_VAR_2} chéri.\p"
	.string "Dès que quelqu’un s’approche,\n"
	.string "il saute dans mes bras, le pauvre\l"
	.string "petit bébé!\p"
	.string "Oh… Si ce n’est pas ça le bonheur,\n"
	.string "je me demande ce que c’est…\p"
	.string "Je suis si heureuse!\p"
	.string "Il fallait absolument que je parle\n"
	.string "de ça à quelqu’un.\p"
	.string "Bon, je dois te laisser.\n"
	.string "Au revoir!$"

MatchCall_PersonalizedText30::
	.string "Je suis… {STR_VAR_1}.\n"
	.string "Les gens m’appellent l’EXPERT.\p"
	.string "Il y a une chose que je sais. Sans\n"
	.string "mes POKéMON, je ne serais rien.\p"
	.string "Sans eux, aucun DRESSEUR ne\n"
	.string "pourrait devenir un EXPERT.\p"
	.string "Oh! Des fois je dis des trucs\n"
	.string "profonds, dis donc!\p"
	.string "Sur ces bonnes paroles, je te\n"
	.string "dis au revoir!$"

MatchCall_PersonalizedText31::
	.string "C’est {STR_VAR_1}.\n"
	.string "Je suis contente de te parler!\p"
	.string "Je fais trempette dans les sources\n"
	.string "chaudes, le bonheur!\p"
	.string "J’ai combattu contre beaucoup\n"
	.string "de DRESSEURS mais tu restes\l"
	.string "le meilleur.\p"
	.string "Et je suis sûre que tu as encore\n"
	.string "progressé depuis la dernière fois!$"

MatchCall_PersonalizedText32::
	.string "Hé, salut! C’est {STR_VAR_1}!\n"
	.string "Quoi de neuf?\p"
	.string "C’est peut-être une impression,\n"
	.string "mais quand je gagne, je me sens\l"
	.string "mieux dans mes baskets.\p"
	.string "Non, vraiment!\n"
	.string "Comment expliquer…\l"
	.string "On dirait qu’elles sont plus larges…\l"
	.string "Et plus moelleuses, aussi.\p"
	.string "Pendant notre combat, {PLAYER}{KUN},\n"
	.string "mes baskets étaient trop serrées!\p"
	.string "… … … … … …\n"
	.string "Quoi, tu m’as cru? Hé, hé, hé!\l"
	.string "Tu crois tout ce qu’on te dit, toi!$"

MatchCall_PersonalizedText33::
	.string "Salut, toi!\n"
	.string "C’est {STR_VAR_1}!\p"
	.string "Comme d’habitude, je m’adonne\n"
	.string "aux plaisirs de la pêche!\p"
	.string "C’est dommage qu’on ne puisse\n"
	.string "pêcher que dans la mer et la\l"
	.string "rivière.\p"
	.string "Oui, dans les lacs aussi. Mais\n"
	.string "j’aimerais pouvoir pêcher partout!\p"
	.string "Oh, je dois te laisser! Ha, ha, ha!\n"
	.string "Ça mord sur une autre ligne!\p"
	.string "Je veux dire, j’ai une prise!\n"
	.string "Au revoir!$"

MatchCall_PersonalizedText34::
	.string "Bonjour, c’est {STR_VAR_1}.\n"
	.string "Tout baigne?\p"
	.string "Tu sais, quand j’étais petit,\n"
	.string "j’étais plutôt du genre tranquille.\p"
	.string "J’aimais prendre mon temps,\n"
	.string "je fuyais le stress.\p"
	.string "Eh bien maintenant, je suis un\n"
	.string "TRIATHLETE.\p"
	.string "Tu ne sais jamais ce que la vie te\n"
	.string "réserve.\p"
	.string "Aujourd’hui, tu es un DRESSEUR.\n"
	.string "Mais que seras-tu demain?\p"
	.string "Tu pourrais très bien avoir envie\n"
	.string "d’enseigner? Ou de peindre?\p"
	.string "Penses-y!\n"
	.string "Allez, à plus.$"

MatchCall_PersonalizedText35::
	.string "C’est {STR_VAR_1}!\n"
	.string "Je suis à vélo.\p"
	.string "J’adore nager et courir, mais le\n"
	.string "vélo, c’est mon dada!\p"
	.string "A vélo, je ne fais qu’un avec le\n"
	.string "vent.\p"
	.string "Je me sens euphorique!\n"
	.string "C’est comme si je volais!\p"
	.string "Je veux réaliser un nouveau record\n"
	.string "sur la PISTE CYCLABLE, aujourd’hui!\p"
	.string "Toi aussi, tu devrais essayer!\n"
	.string "Au revoir!$"

MatchCall_PersonalizedText36::
	.string "Salut, c’est {STR_VAR_1}! Je suis en\n"
	.string "plein triathlon!\p"
	.string "Mais c’est pas ça qui m’empêche\n"
	.string "d’appeler les amis!\p"
	.string "Tu sais, j’adore m’entraîner avec\n"
	.string "les POKéMON!\p"
	.string "On se comprend sans dire un seul\n"
	.string "mot. C’est simple, on ne fait qu’un!\p"
	.string "Ça me transporte de joie!\p"
	.string "Mince… Il faut que je raccroche…\n"
	.string "C’est… pas facile…\l"
	.string "Je m’essouffle… Au revoir…$"

MatchCall_PersonalizedText37::
	.string "Salut, {STR_VAR_1}.\n"
	.string "Si tu veux améliorer ton endurance,\l"
	.string "entraîne-toi en altitude!\p"
	.string "Essaie de gravir une montagne en\n"
	.string "courant. Tu vas vite t’essouffler!\p"
	.string "Justement, je commence à\n"
	.string "manquer d’oxygène! Je te laisse!$"

MatchCall_PersonalizedText38::
	.string "C’est {STR_VAR_1}. Bonjour!\p"
	.string "Je n’arrête pas de nager, mais je ne\n"
	.string "trouve pas ETERNARA.\p"
	.string "J’ai l’impression de tourner en\n"
	.string "rond.\p"
	.string "Non, non, c’est impossible…\n"
	.string "Allez, à bientôt!$"

MatchCall_PersonalizedText39::
	.string "Salut, {STR_VAR_1}…\n"
	.string "Blop!\p"
	.string "Bloup, bloup, bloup…\p"
	.string "Blop!\p"
	.string "Désolé, j’ai mis de la crème solaire.\p"
	.string "Mon POKéNAV m’a glissé des mains\n"
	.string "et il est tombé dans l’eau!\p"
	.string "Le POKéNAV de DEVON est solide!\n"
	.string "En tout cas, il est étanche!\p"
	.string "Bon, je vais faire bronzette!\n"
	.string "Désolé, je dois te laisser.$"

MatchCall_PersonalizedText40::
	.string "Bonjour, c’est {STR_VAR_1}.\p"
	.string "Mon épreuve de triathlon préférée,\n"
	.string "c’est la nage.\p"
	.string "Mais j’ai peur d’un truc. Je ne\n"
	.string "risque pas de ressembler à un\l"
	.string "pruneau à force d’être dans l’eau?\p"
	.string "J’aime le triathlon! J’aime dépasser\n"
	.string "mes peurs! Au revoir!$"

MatchCall_PersonalizedText41::
	.string "Salut, {PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} à l’appareil.\p"
	.string "Comment vont tes POKéMON?\p"
	.string "Mes POKéMON DRAGON pètent le feu!\n"
	.string "A la prochaine!$"

MatchCall_PersonalizedText42::
	.string "C’est {STR_VAR_1}.\p"
	.string "Mon {STR_VAR_2} a beaucoup changé\n"
	.string "depuis la dernière fois.\p"
	.string "Tu ne pourras plus me battre.\n"
	.string "Vivement qu’on se revoie!\p"
	.string "Au revoir!$"

MatchCall_PersonalizedText43::
	.string "C’est {STR_VAR_1} à l’appareil.\p"
	.string "J’ai continué mes recherches sur\n"
	.string "l’art de la dissimulation.\p"
	.string "J’ai fait tellement de progrès que\n"
	.string "plus personne ne me voit!\l"
	.string "Je me sens terriblement seul…\p"
	.string "Comme la fumée, je me dissipe!\n"
	.string "Au revoir!$"

MatchCall_PersonalizedText44::
	.string "C’est {STR_VAR_1}.\n"
	.string "Je n’ai pas arrêté de m’entraîner\l"
	.string "depuis la dernière fois.\p"
	.string "Mon {STR_VAR_2} est devenu super\n"
	.string "fort.\p"
	.string "Je m’entraîne sur la plage. Je\n"
	.string "trouve ça plus efficace. Au revoir!$"

MatchCall_PersonalizedText45::
	.string "Comment ça va?\n"
	.string "C’est {STR_VAR_1}.\p"
	.string "Ces cendres volcaniques n’en\n"
	.string "finissent pas de tomber!\p"
	.string "Si ça continue, on ne verra plus les\n"
	.string "motifs de mon parasol…\p"
	.string "J’espère te voir bientôt!$"

MatchCall_PersonalizedText46::
	.string "Bonjour, c’est {STR_VAR_1}.\p"
	.string "Tu sais que c’est plus facile de\n"
	.string "faire la planche dans la mer que\l"
	.string "dans la piscine?\p"
	.string "On y flotte beaucoup mieux.\p"
	.string "Mais quand tu fais la planche,\n"
	.string "fais attention de ne pas te laisser\l"
	.string "emporter au large.\p"
	.string "Mais au fait, où je suis là???\n"
	.string "Heu… Il faut que je te laisse!$"

MatchCall_PersonalizedText47::
	.string "Bonjour {PLAYER}{KUN}!\n"
	.string "C’est {STR_VAR_1}.\l"
	.string "Je suis en montagne.\p"
	.string "Mais le sol est plein de bosses.\n"
	.string "Je ne peux pas planter ma tente…\p"
	.string "Oh, j’ai une super idée!\p"
	.string "Je vais demander à mes POKéMON\n"
	.string "de damer le sol!\p"
	.string "Je vais essayer!\n"
	.string "Au revoir!$"

MatchCall_PersonalizedText48::
	.string "Bonjour, c’est {STR_VAR_1}!\p"
	.string "J’élève des POKéMON avec AWA!\n"
	.string "On prend ça très au sérieux!\p"
	.string "Si on y met encore plus d’énergie,\n"
	.string "on deviendra les meilleures!$"

MatchCall_PersonalizedText49::
	.string "Ici {STR_VAR_1}!\p"
	.string "Je suis un MARIN, même si je ne suis\n"
	.string "pas en mer en ce moment…\p"
	.string "Un MARIN à terre, c’est comme un\n"
	.string "poisson sans eau!\p"
	.string "Dès que je rejoins la terre ferme,\n"
	.string "je deviens un peu nostalgique.\p"
	.string "Allez, à la prochaine!$"

MatchCall_PersonalizedText50::
	.string "C’est {STR_VAR_1}.\n"
	.string "Tu as de nouveaux POKéMON?\p"
	.string "Si tu en attrapes un nouveau,\n"
	.string "viens me le montrer!\p"
	.string "Je promets de ne pas être jaloux.\n"
	.string "A bientôt, j’espère!$"

MatchCall_PersonalizedText51::
	.string "C’est {STR_VAR_1}.\p"
	.string "Elèves-tu tes POKéMON\n"
	.string "correctement?\p"
	.string "Là où je me trouve, l’air est pur.\n"
	.string "C’est ce qu’il y a de mieux pour les\l"
	.string "POKéMON.\p"
	.string "Si tu veux les élever de façon\n"
	.string "optimale, viens sur la\l"
	.string "{STR_VAR_2}!$"

MatchCall_PersonalizedText52::
	.string "Bonjour, c’est {STR_VAR_1}.\p"
	.string "J’ai donné un {POKEBLOCK} à mon\n"
	.string "{STR_VAR_2}. Il a beaucoup aimé.\p"
	.string "Les POKéMON ont tous leurs\n"
	.string "préférences en matière de {POKEBLOCK}S.\p"
	.string "Je trouve ça fascinant.\n"
	.string "Au revoir.$"

MatchCall_PersonalizedText53::
	.string "C’est {STR_VAR_1}.\p"
	.string "Grâce aux POKéMON, tu peux\n"
	.string "survivre en pleine nature.\p"
	.string "Je crois que les gens devraient\n"
	.string "coopérer plus avec les POKéMON.\p"
	.string "On a tout à y gagner.\n"
	.string "Les POKéMON, c’est l’avenir.\p"
	.string "Mais tu ne fais pas partie des gens\n"
	.string "à convaincre. Tu penses POKéMON!$"

MatchCall_PersonalizedText54::
	.string "Salut, c’est {STR_VAR_1}.\n"
	.string "Je suis toujours prête! Et toi?\p"
	.string "{PLAYER}{KUN}, as-tu assez d’objets?\n"
	.string "Tes POKéMON sont-ils en forme?\p"
	.string "Pour éviter les mauvaises\n"
	.string "surprises, il faut être toujours\l"
	.string "prêt! C’est le secret!\p"
	.string "Je vais vérifier mes provisions!\n"
	.string "La vigilance épargne bien des\l"
	.string "problèmes!$"

MatchCall_PersonalizedText55::
	.string "C’est {STR_VAR_1}!\n"
	.string "Oui, {STR_VAR_1}!\p"
	.string "Il y a beaucoup de passage sur\n"
	.string "{STR_VAR_2}. Je me bats\l"
	.string "contre un tas de DRESSEURS.\p"
	.string "Aujourd’hui, j’ai gagné cinq\n"
	.string "combats et n’en ai perdu que trois!\p"
	.string "Tu as passé une bonne journée?\n"
	.string "Bon, tu me raconteras ça plus tard!$"

MatchCall_PersonalizedText56::
	.string "C’est moi, {STR_VAR_1}.\p"
	.string "Mes POKéMON INSECTE sont\n"
	.string "franchement cool, non?\p"
	.string "Je les ai ramenés à l’école pour les\n"
	.string "montrer à une fille.\p"
	.string "Eh ben, elle s’est mise à\n"
	.string "hurler! Trop bête, la fille!\p"
	.string "Moi, je pensais qu’elle les\n"
	.string "aimerait… C’est dommage.\p"
	.string "Sniff…\n"
	.string "Au revoir!$"

MatchCall_PersonalizedText57::
	.string "Ouf…\p"
	.string "Bonjour! C’est {STR_VAR_1}!\p"
	.string "Parler…\n"
	.string "tout en escaladant…\l"
	.string "ce n’est pas facile… Ha! Ha!\p"
	.string "Arg! Ouf…\n"
	.string "Ça grimpe!\l"
	.string "On parlera… une autre fois…\l"
	.string "Ouf…$"

MatchCall_PersonalizedText58::
	.string "Oh, salut!\p"
	.string "Je cherche des trésors avec\n"
	.string "RITA!\p"
	.string "On n’est pas sûrs de trouver quoi\n"
	.string "que ce soit, tu sais…\p"
	.string "Le plus important pour moi,\n"
	.string "c’est d’être avec RITA.\p"
	.string "Quoi encore, RITA!?!\n"
	.string "Pourquoi tu fais cette tête-là?\p"
	.string "Mais non, je ne t’ignore pas, ma\n"
	.string "puce! Il n’y a que toi dans ma vie!\p"
	.string "Je dois raccrocher, {PLAYER}…$"

MatchCall_PersonalizedText59::
	.string "C’est {STR_VAR_1}!\p"
	.string "Je suis retourné à l’ARENE de\n"
	.string "MYOKARA pour m’entraîner.\p"
	.string "BASTIEN, le CHAMPION D’ARENE,\n"
	.string "est devenu bien meilleur.\p"
	.string "Il a parlé des vagues sauvages…\n"
	.string "Ou un truc dans le genre.\p"
	.string "Mais il est toujours aussi cool.\n"
	.string "Et il plaît toujours autant aux\l"
	.string "filles! Il en a de la chance.\p"
	.string "Tiens… Je me demande si son ami\n"
	.string "ALDO est comme lui.\p"
	.string "C’est sûrement aussi le genre à\n"
	.string "faire craquer les filles…\p"
	.string "Bon, il faut que j’arrête.\n"
	.string "La jalousie est un vilain défaut!\p"
	.string "Allez, oublie ce que je viens de\n"
	.string "dire!$"

MatchCall_PersonalizedText60::
	.string "C’est un plaisir de discuter avec\n"
	.string "un jeune DRESSEUR comme toi.\p"
	.string "Ta passion pour les POKéMON va\n"
	.string "durer, c’est évident.\p"
	.string "Tu pourrais peut-être devenir\n"
	.string "notre partenaire?\p"
	.string "Bien sûr, {PLAYER}{KUN}.\n"
	.string "La compagnie de tes fidèles\l"
	.string "POKéMON te suffit amplement.\p"
	.string "Tu sais comment faire durer une\n"
	.string "relation.\p"
	.string "Ha, ha, ha!\n"
	.string "Ne te décourage jamais!$"

MatchCall_PersonalizedText61::
	.string "Bonjour, c’est {STR_VAR_1}!\n"
	.string "Nous venons de gagner un combat!\p"
	.string "Nous ne gagnons pas souvent, mais\n"
	.string "c’était contre un NAGEUR facile.\p"
	.string "Ma sœur était hors d’elle!\p"
	.string "Elle voulait jouer à la fille faible\n"
	.string "et sans défense pour le séduire!\p"
	.string "Qu’on gagne ou qu’on perde, elle\n"
	.string "n’est jamais contente!\p"
	.string "{PLAYER}{KUN}, tu ne pourrais pas\n"
	.string "essayer de lui parler?\p"
	.string "Allez, au revoir!$"

MatchCall_PersonalizedText62::
	.string "Bonjour, c’est {STR_VAR_1}.\n"
	.string "Je suis parti en mer hier.\p"
	.string "Je pensais y trouver quelque\n"
	.string "épave à explorer.\p"
	.string "Mais la marée m’a ramené chez moi\n"
	.string "sur la terre ferme.\p"
	.string "Je suis toujours mauvais au\n"
	.string "combat… Mais je persévère!\p"
	.string "Je serai sûrement meilleur quand\n"
	.string "j’aurai trouvé des ruines!\p"
	.string "C’est tout ce que je voulais te\n"
	.string "dire! Au revoir!$"

MatchCall_PersonalizedText63::
	.string "Ohé, du bateau!\n"
	.string "C’est moi, {STR_VAR_1}!\l"
	.string "Je suis sur le CHENAL 108 en ce\l"
	.string "moment! Enfin, comme d’habitude!\p"
	.string "Aujourd’hui, j’ai vu une NAGEUSE\n"
	.string "de rêve!\p"
	.string "J’ai crié pour attirer son\n"
	.string "attention, tu me connais!\p"
	.string "Elle m’a fusillé du regard!\p"
	.string "C’était les nouvelles du\n"
	.string "CHENAL 108 par {STR_VAR_1}!$"

MatchCall_PersonalizedText64::
	.string "C’est {STR_VAR_1}!\p"
	.string "Je suis très occupée, mais je\n"
	.string "voulais te dire que j’avais battu\l"
	.string "cinq DRESSEURS aujourd’hui.\p"
	.string "Si je continue comme ça, je te\n"
	.string "battrai sûrement la prochaine fois.\p"
	.string "Je crois que toi et moi sommes de\n"
	.string "bons adversaires!$"

MatchCall_BattleFrontierStreakText1::
	.string "Bonjour! C’est {STR_VAR_1}.\n"
	.string "Je suis au courant!\p"
	.string "Tu as obtenu {STR_VAR_3} victoires à la\n"
	.string "suite! Où? {STR_VAR_2}!\p"
	.string "Eh bien, chapeau! Au revoir!$"

MatchCall_BattleFrontierStreakText2::
	.string "Bonjour, c’est {STR_VAR_1}.\n"
	.string "Je suis au courant!\p"
	.string "{STR_VAR_3} victoires consécutives! Mais\n"
	.string "où? {STR_VAR_2}! Excellent.\p"
	.string "Il faut que je prenne exemple sur\n"
	.string "toi. Au revoir!$"

MatchCall_BattleFrontierStreakText3::
	.string "Salut, {PLAYER}!\n"
	.string "C’est moi, {STR_VAR_1}.\p"
	.string "J’ai eu vent de tes exploits! Mais\n"
	.string "où? {STR_VAR_2}? Joli!\p"
	.string "{STR_VAR_3} victoires consécutives…\n"
	.string "Quel record!\p"
	.string "Je ferais bien de prendre exemple\n"
	.string "sur toi! Au revoir!$"

MatchCall_BattleFrontierStreakText4::
	.string "Allô, {PLAYER}{KUN}?\n"
	.string "Ici {STR_VAR_1}. Bonjour!\p"
	.string "Il paraît que tu as obtenu {STR_VAR_3}\n"
	.string "victoires consécutives. Mais où?\l"
	.string "{STR_VAR_2}?\p"
	.string "Bon, il faut que je me remette\n"
	.string "sérieusement à l’entraînement!$"

MatchCall_BattleFrontierStreakText5::
	.string "Salut, {PLAYER}{KUN}!\n"
	.string "{STR_VAR_1} à l’appareil.\p"
	.string "Je sais que tu as gagné {STR_VAR_3}\n"
	.string "combats à la suite, mais où?\l"
	.string "{STR_VAR_2}! Incroyable!\p"
	.string "Il faut que je me concentre plus\n"
	.string "sur mes POKéMON. A bientôt!$"

MatchCall_BattleFrontierStreakText6::
	.string "Salut, {PLAYER}{KUN}.\n"
	.string "Ici {STR_VAR_1}. Comment vas-tu?\p"
	.string "Je sais que tu as obtenu {STR_VAR_3}\n"
	.string "victoires à la suite dans la ZONE\l"
	.string "DE COMBAT. Où exactement? {STR_VAR_3}!\p"
	.string "Je devrais en prendre de la graine\n"
	.string "et élever mon équipe mieux que ça.$"

MatchCall_BattleFrontierStreakText7::
	.string "Heu… {PLAYER}{KUN}?\n"
	.string "Ici {STR_VAR_1}…\p"
	.string "Tu as combattu dans la ZONE DE\n"
	.string "COMBAT, non? {STR_VAR_2}?\p"
	.string "C’est vrai que tu as gagné {STR_VAR_3}\n"
	.string "combats à la suite?\p"
	.string "Je viens d’apercevoir un POKéMON\n"
	.string "rare! Je te laisse!$"

MatchCall_BattleFrontierStreakText8::
	.string "Ça va, {PLAYER}{KUN}?\n"
	.string "C’est {STR_VAR_1}.\l"
	.string "Ça a l’air d’aller pour toi.\p"
	.string "Tu as gagné {STR_VAR_3} combats à la suite\n"
	.string "dans la ZONE DE COMBAT.\l"
	.string "{STR_VAR_2}, n’est-ce pas?\p"
	.string "C’est très impressionnant!\n"
	.string "Continue sur cette voie.$"

MatchCall_BattleFrontierStreakText9::
	.string "Salut, {PLAYER}{KUN}!\n"
	.string "C’est {STR_VAR_1}!\p"
	.string "On m’a parlé de tes {STR_VAR_3} victoires\n"
	.string "à la suite dans la ZONE DE COMBAT!\l"
	.string "{STR_VAR_2}, c’est ça?\p"
	.string "C’est formidable!\n"
	.string "Bon, je ferais bien de t’imiter!$"

MatchCall_BattleFrontierStreakText10::
	.string "Coucou, {PLAYER}{KUN}…\n"
	.string "C’est moi, {STR_VAR_1}.\p"
	.string "C’est vrai que tu as gagné {STR_VAR_3}\n"
	.string "combats à la suite dans la ZONE DE\l"
	.string "COMBAT? {STR_VAR_2}!?!\p"
	.string "Je vais essayer de suivre ton\n"
	.string "exemple. Je dois m’améliorer.$"

MatchCall_BattleFrontierStreakText11::
	.string "{PLAYER}{KUN}?\n"
	.string "Bonjour, c’est {STR_VAR_1}.\p"
	.string "On va devoir t’appeler sa Majesté\n"
	.string "{STR_VAR_2} bientôt, non?\p"
	.string "Tu as gagné {STR_VAR_3} combats à la\n"
	.string "suite!\p"
	.string "C’est vraiment bien!\n"
	.string "Je devrais essayer, moi aussi!$"

MatchCall_BattleFrontierStreakText12::
	.string "Bonjour, {PLAYER}{KUN}.\n"
	.string "C’est {STR_VAR_1}.\l"
	.string "Ça va?\p"
	.string "Tu as gagné {STR_VAR_3} combats à\n"
	.string "la suite dans un endroit appelé\l"
	.string "{STR_VAR_2}, il paraît.\p"
	.string "C’est assez impressionnant.\n"
	.string "Au revoir!$"

MatchCall_BattleFrontierStreakText13::
	.string "Bonjour, {PLAYER}{KUN}!\n"
	.string "C’est {STR_VAR_1} qui appelle!\l"
	.string "J’espère que tout va bien.\p"
	.string "Il paraît que tu as gagné {STR_VAR_3}\n"
	.string "combats à la suite dans un endroit\l"
	.string "du nom de {STR_VAR_2}.\p"
	.string "Quelle énergie! Je t’admire.\n"
	.string "A bientôt.$"

MatchCall_BattleFrontierStreakText14::
	.string "Bonjour, {PLAYER}{KUN}.\n"
	.string "C’est {STR_VAR_1}.\p"
	.string "On m’a parlé de toi! Tu as gagné {STR_VAR_3}\n"
	.string "combats à la suite dans la ZONE DE\l"
	.string "COMBAT! {STR_VAR_2}!?!\p"
	.string "Tu es un modèle pour moi!\n"
	.string "Au revoir!$"

MatchCall_BattleFrontierRecordStreakText1::
	.string "Bonjour, c’est {STR_VAR_1}.\n"
	.string "Je suis au courant!\p"
	.string "Tu as fait des tiennes dans la ZONE\n"
	.string "DE COMBAT! {STR_VAR_2}?\l"
	.string "Magnifique!\p"
	.string "{STR_VAR_3} victoires consécutives,\n"
	.string "n’est-ce pas? Bravo!\l"
	.string "Allez, au revoir!$"

MatchCall_BattleFrontierRecordStreakText2::
	.string "Bonjour, c’est {STR_VAR_1}!\n"
	.string "J’ai entendu parler de toi!\p"
	.string "Dans quel bâtiment de la ZONE DE\n"
	.string "COMBAT as-tu gagné {STR_VAR_3} combats\l"
	.string "à la suite? {STR_VAR_2}!\p"
	.string "C’est très fort, ça!\n"
	.string "Je devrais prendre exemple!$"

MatchCall_BattleFrontierRecordStreakText3::
	.string "Salut, {PLAYER}!\n"
	.string "C’est moi, {STR_VAR_1}.\p"
	.string "Tu as fait des ravages dans la ZONE\n"
	.string "DE COMBAT? {STR_VAR_2}?\l"
	.string "Je ne savais pas.\p"
	.string "Mais je sais que tu as obtenu\n"
	.string "{STR_VAR_3} victoires consécutives…\p"
	.string "Bon, il faut que je me reprenne!\n"
	.string "Au revoir!$"

MatchCall_BattleFrontierRecordStreakText4::
	.string "Allô, {PLAYER}{KUN}?\n"
	.string "Ici {STR_VAR_1}. Bonjour, ça va?\p"
	.string "Tu as obtenu {STR_VAR_3} victoires\n"
	.string "consécutives dans la ZONE DE\l"
	.string "COMBAT, non? {STR_VAR_2}?\p"
	.string "Je vais de ce pas m’entraîner,\n"
	.string "tiens… Au revoir!$"

MatchCall_BattleFrontierRecordStreakText5::
	.string "Salut, {PLAYER}{KUN}!\n"
	.string "{STR_VAR_1} à l’appareil.\p"
	.string "C’est vrai que tu as gagné {STR_VAR_3}\n"
	.string "combats à la suite dans ce\l"
	.string "bâtiment… {STR_VAR_2}?\p"
	.string "Moi? On fait aller.\n"
	.string "A bientôt!$"

MatchCall_BattleFrontierRecordStreakText6::
	.string "Salut, {PLAYER}{KUN}.\n"
	.string "Ici {STR_VAR_1}. Comment ça va?\p"
	.string "Il paraît que tu as obtenu {STR_VAR_3}\n"
	.string "victoires à la suite dans ce\l"
	.string "bâtiment… {STR_VAR_2}.\p"
	.string "Je ne peux pas en dire autant de\n"
	.string "moi. Au revoir!$"

MatchCall_BattleFrontierRecordStreakText7::
	.string "Heu… {PLAYER}{KUN}?\n"
	.string "Ici {STR_VAR_1}…\p"
	.string "C’est vrai que tu as relevé le défi\n"
	.string "de ce bâtiment, là…\l"
	.string "{STR_VAR_2}?\p"
	.string "Et que tu as gagné {STR_VAR_3}\n"
	.string "combats à la suite?\p"
	.string "Je viens de voir un POKéMON rare!\n"
	.string "Je te laisse!$"

MatchCall_BattleFrontierRecordStreakText8::
	.string "Ça va, {PLAYER}{KUN}?\n"
	.string "C’est {STR_VAR_1}.\l"
	.string "Ça a l’air d’aller pour toi.\p"
	.string "Tu as gagné {STR_VAR_3} combats à la\n"
	.string "suite dans la ZONE DE COMBAT.\l"
	.string "Mais où? {STR_VAR_2}!\p"
	.string "C’est très impressionnant!\n"
	.string "Continue sur cette voie.$"

MatchCall_BattleFrontierRecordStreakText9::
	.string "Salut, {PLAYER}{KUN}!\n"
	.string "C’est {STR_VAR_1}!\p"
	.string "J’ai appris que tu avais obtenu\n"
	.string "{STR_VAR_3} victoires consécutives au\l"
	.string "bâtiment {STR_VAR_2}!\p"
	.string "C’est formidable!\n"
	.string "Bon, je ferais bien de t’imiter!$"

MatchCall_BattleFrontierRecordStreakText10::
	.string "Coucou, {PLAYER}{KUN}…\n"
	.string "C’est moi, {STR_VAR_1}.\p"
	.string "Dans quel bâtiment de la ZONE DE\n"
	.string "COMBAT as-tu gagné {STR_VAR_3} combats\l"
	.string "à la suite? {STR_VAR_2}?\p"
	.string "Je vais essayer de suivre ton\n"
	.string "exemple. Je dois m’améliorer.$"

MatchCall_BattleFrontierRecordStreakText11::
	.string "{PLAYER}{KUN}?\n"
	.string "Bonjour, c’est {STR_VAR_1}.\p"
	.string "On va devoir t’appeler sa Majesté\n"
	.string "{STR_VAR_2} bientôt, non?\p"
	.string "Tu as gagné {STR_VAR_3} combats à la\n"
	.string "suite, non?\p"
	.string "C’est vraiment bien!\n"
	.string "Je devrais essayer, moi aussi!$"

MatchCall_BattleFrontierRecordStreakText12::
	.string "Bonjour, {PLAYER}{KUN}.\n"
	.string "C’est {STR_VAR_1}.\l"
	.string "Ça va?\p"
	.string "Dis, as-tu gagné {STR_VAR_3} combats à\n"
	.string "la suite dans un endroit appelé\l"
	.string "{STR_VAR_2}? C’était toi!\p"
	.string "C’est assez impressionnant.\n"
	.string "Au revoir!$"

MatchCall_BattleFrontierRecordStreakText13::
	.string "Bonjour, {PLAYER}{KUN}!\n"
	.string "C’est {STR_VAR_1} qui appelle!\l"
	.string "J’espère que tout va bien.\p"
	.string "Aurais-tu par hasard gagné {STR_VAR_3}\n"
	.string "combats à la suite dans un endroit\l"
	.string "du nom de {STR_VAR_2}?\p"
	.string "Quelle énergie! Je t’admire.\n"
	.string "A bientôt.$"

MatchCall_BattleFrontierRecordStreakText14::
	.string "Bonjour, {PLAYER}{KUN}.\n"
	.string "C’est {STR_VAR_1}.\l"
	.string "J’ai entendu parler de toi!\p"
	.string "Tu viens de gagner {STR_VAR_3} combats à\n"
	.string "la suite dans un endroit appelé\l"
	.string "{STR_VAR_2}, n’est-ce pas?\p"
	.string "Tu es un modèle pour moi!\n"
	.string "Au revoir!$"

MatchCall_BattleDomeText1::
	.string "{PLAYER}?\n"
	.string "Bonjour, c’est {STR_VAR_1}!\l"
	.string "Je suis au courant!\p"
	.string "Tu as remporté {STR_VAR_3} fois le titre\n"
	.string "du bâtiment {STR_VAR_2}!\p"
	.string "C’est incroyable. Je devrais avoir\n"
	.string "honte de moi! Au revoir!$"

MatchCall_BattleDomeText2::
	.string "Bonjour, c’est {STR_VAR_1}!\n"
	.string "Je suis au courant!\p"
	.string "Tu as remporté {STR_VAR_3} fois le titre\n"
	.string "du bâtiment {STR_VAR_2}!\p"
	.string "C’est super! J’aimerais bien\n"
	.string "remporter ce titre au moins\l"
	.string "une fois!$"

MatchCall_BattleDomeText3::
	.string "Salut, {PLAYER}!\n"
	.string "C’est moi, {STR_VAR_1}.\l"
	.string "Comment ça va?\p"
	.string "Il paraît que tu as remporté {STR_VAR_3}\n"
	.string "fois le titre du bâtiment\l"
	.string "{STR_VAR_2}!\p"
	.string "Ne t’arrête pas là!\n"
	.string "Au revoir!$"

MatchCall_BattleDomeText4::
	.string "Allô, {PLAYER}{KUN}?\n"
	.string "Ici {STR_VAR_1}. Bonjour!\p"
	.string "J’ai entendu dire que tu as\n"
	.string "remporté le titre du bâtiment\l"
	.string "{STR_VAR_2} {STR_VAR_3} fois.\p"
	.string "Je vois que tes efforts portent\n"
	.string "leurs fruits! Je dois persévérer!$"

MatchCall_BattleDomeText5::
	.string "Salut, {PLAYER}{KUN}!\n"
	.string "{STR_VAR_1} à l’appareil.\p"
	.string "On m’a dit que tu avais remporté\n"
	.string "{STR_VAR_3} fois haut la main le titre du\l"
	.string "bâtiment {STR_VAR_2}.\p"
	.string "Moi aussi, je devrais m’y mettre!\n"
	.string "A bientôt!$"

MatchCall_BattleDomeText6::
	.string "Salut, {PLAYER}{KUN}?\n"
	.string "{STR_VAR_1} à l’appareil. Ça va?\p"
	.string "Je sais que tu as remporté le titre\n"
	.string "du bâtiment {STR_VAR_2}\l"
	.string "{STR_VAR_3} fois.\p"
	.string "Je ferais bien de me concentrer sur\n"
	.string "mes POKéMON.$"

MatchCall_BattleDomeText7::
	.string "{PLAYER}{KUN}?\n"
	.string "Ici {STR_VAR_1}.\p"
	.string "Tu as obtenu le titre du bâtiment\n"
	.string "{STR_VAR_2} {STR_VAR_3} fois,\l"
	.string "n’est-ce pas?\p"
	.string "Pas mal du tout. Au fait, as-tu\n"
	.string "attrapé des POKéMON rares\l"
	.string "aujourd’hui?\p"
	.string "Vraiment?\n"
	.string "Bien, au revoir.$"

MatchCall_BattleDomeText8::
	.string "Ça va, {PLAYER}{KUN}?\n"
	.string "C’est {STR_VAR_1}.\l"
	.string "Ça a l’air d’aller pour toi.\p"
	.string "J’ai appris que tu avais remporté le\n"
	.string "titre du bâtiment\l"
	.string "{STR_VAR_2} {STR_VAR_3} fois.\p"
	.string "Je vais élever mes POKéMON de la\n"
	.string "même façon que toi. Au revoir!$"

MatchCall_BattleDomeText9::
	.string "Salut, {PLAYER}{KUN}!\n"
	.string "C’est {STR_VAR_1}!\p"
	.string "Je sais tout! Félicitations, tu as\n"
	.string "remporté le titre du bâtiment\l"
	.string "{STR_VAR_2} {STR_VAR_3} fois!\p"
	.string "C’est formidable!\n"
	.string "Bon, je ferais bien de t’imiter!$"

MatchCall_BattleDomeText10::
	.string "Bonjour {PLAYER}{KUN}.\n"
	.string "C’est {STR_VAR_1}.\p"
	.string "Tu as obtenu le titre du bâtiment\n"
	.string "{STR_VAR_2} {STR_VAR_3} fois,\l"
	.string "c’est bien vrai?\p"
	.string "Je vais essayer de suivre ton\n"
	.string "exemple. Je dois m’améliorer.$"

MatchCall_BattleDomeText11::
	.string "{PLAYER}{KUN}?\n"
	.string "Bonjour, c’est {STR_VAR_1}.\p"
	.string "On va devoir t’appeler sa Majesté\n"
	.string "{STR_VAR_2} bientôt, non?\p"
	.string "Tu en as remporté le titre {STR_VAR_3} fois,\n"
	.string "non?\p"
	.string "Je me demande si je remporterai\n"
	.string "un titre un jour…\p"
	.string "Mais ça m’étonnerait…\n"
	.string "Bon, au revoir!$"

MatchCall_BattleDomeText12::
	.string "Bonjour, {PLAYER}{KUN}.\n"
	.string "C’est {STR_VAR_1}.\l"
	.string "Ça va?\p"
	.string "Tu as gagné {STR_VAR_3} fois le\n"
	.string "titre d’un endroit appelé\l"
	.string "{STR_VAR_2}?\p"
	.string "C’est assez impressionnant.\n"
	.string "Au revoir!$"

MatchCall_BattleDomeText13::
	.string "Bonjour, {PLAYER}{KUN}!\n"
	.string "C’est {STR_VAR_1} qui appelle!\l"
	.string "J’espère que tout va bien.\p"
	.string "Il paraît que tu as obtenu {STR_VAR_3} fois\n"
	.string "le titre du bâtiment\l"
	.string "{STR_VAR_2}?\p"
	.string "Quelle énergie! Je t’admire.\n"
	.string "A bientôt.$"

MatchCall_BattleDomeText14::
	.string "{PLAYER}{KUN}?\n"
	.string "Bonjour, c’est {STR_VAR_1}.\l"
	.string "J’ai entendu parler de toi!\p"
	.string "Tu as remporté {STR_VAR_3} fois le titre du\n"
	.string "bâtiment {STR_VAR_2}!\p"
	.string "Tu es un modèle pour moi!\n"
	.string "Au revoir!$"

MatchCall_BattlePikeText1::
	.string "Bonjour, {PLAYER}!\n"
	.string "C’est {STR_VAR_1}!\l"
	.string "Je suis au courant!\p"
	.string "Tu as traversé {STR_VAR_3} salles\n"
	.string "du {STR_VAR_2}!\p"
	.string "C’est superbe!\n"
	.string "Au revoir!$"

MatchCall_BattlePikeText2::
	.string "Bonjour, c’est {STR_VAR_1}!\n"
	.string "J’ai entendu parler de toi!\p"
	.string "Il paraît que tu as traversé {STR_VAR_3}\n"
	.string "salles du {STR_VAR_2}.\p"
	.string "Moi, il faut que je redouble\n"
	.string "d’efforts! Au revoir!$"

MatchCall_BattlePikeText3::
	.string "Salut, {PLAYER}!\n"
	.string "C’est moi, {STR_VAR_1}.\l"
	.string "Comment ça va?\p"
	.string "Il paraît que tu as traversé\n"
	.string "{STR_VAR_3} salles du {STR_VAR_2}!\p"
	.string "Essaie de faire encore mieux\n"
	.string "la prochaine fois! Au revoir!$"

MatchCall_BattlePikeText4::
	.string "Allô, {PLAYER}{KUN}?\n"
	.string "Ici {STR_VAR_1}. Bonjour!\p"
	.string "Alors comme ça, tu as traversé\n"
	.string "{STR_VAR_3} salles du {STR_VAR_2}?\p"
	.string "Je ferais bien de m’occuper un peu\n"
	.string "mieux de mes POKéMON!$"

MatchCall_BattlePikeText5::
	.string "Salut, {PLAYER}{KUN}!\n"
	.string "{STR_VAR_1} à l’appareil.\p"
	.string "Il paraît que tu as traversé\n"
	.string "{STR_VAR_3} salles du {STR_VAR_2}!\p"
	.string "Moi aussi, je devrais m’y mettre!\n"
	.string "A bientôt!$"

MatchCall_BattlePikeText6::
	.string "Hé, {PLAYER}{KUN}?\n"
	.string "Ici {STR_VAR_1}. Comment vas-tu?\p"
	.string "J’ai entendu dire que tu avais\n"
	.string "traversé {STR_VAR_3} salles du\l"
	.string "{STR_VAR_2}.\p"
	.string "Je ferais bien de me concentrer\n"
	.string "sur mes POKéMON.$"

MatchCall_BattlePikeText7::
	.string "{PLAYER}{KUN}?\n"
	.string "Ici {STR_VAR_1}.\p"
	.string "Tu as osé entrer dans le\n"
	.string "{STR_VAR_2}? Et tu as\l"
	.string "traversé {STR_VAR_3} salles?\p"
	.string "Pas mal du tout.\p"
	.string "Je viens de voir un POKéMON rare!\n"
	.string "Je te laisse!$"

MatchCall_BattlePikeText8::
	.string "Ça va, {PLAYER}{KUN}?\n"
	.string "C’est {STR_VAR_1}.\l"
	.string "Ça a l’air d’aller pour toi.\p"
	.string "Il paraît que tu as traversé\n"
	.string "{STR_VAR_3} salles du {STR_VAR_2}!\p"
	.string "C’est très impressionnant!\n"
	.string "Je vais élever mes POKéMON de la\l"
	.string "même façon que toi. Au revoir!$"

MatchCall_BattlePikeText9::
	.string "Salut, {PLAYER}{KUN}!\n"
	.string "C’est {STR_VAR_1}!\p"
	.string "Je suis au courant! Tu as traversé\n"
	.string "{STR_VAR_3} salles du {STR_VAR_2}!\p"
	.string "C’est formidable!\n"
	.string "Bon, je ferais bien de t’imiter!$"

MatchCall_BattlePikeText10::
	.string "Bonjour, {PLAYER}{KUN}.\n"
	.string "C’est {STR_VAR_1}.\p"
	.string "Tu as réussi à traverser\n"
	.string "{STR_VAR_3} salles du {STR_VAR_2}?\p"
	.string "Je vais essayer de suivre ton\n"
	.string "exemple. Je dois m’améliorer.$"

MatchCall_BattlePikeText11::
	.string "{PLAYER}{KUN}?\n"
	.string "Bonjour, c’est {STR_VAR_1}.\p"
	.string "On va devoir t’appeler sa Majesté\n"
	.string "{STR_VAR_2} bientôt, non?\p"
	.string "Tu as traversé quoi? {STR_VAR_3} salles?\n"
	.string "Ce n’est pas rien!\p"
	.string "Je me demande si je remporterai\n"
	.string "un titre un jour…\p"
	.string "Mais ça m’étonnerait…\n"
	.string "Bon, au revoir!$"

MatchCall_BattlePikeText12::
	.string "Bonjour, {PLAYER}{KUN}.\n"
	.string "C’est {STR_VAR_1}.\l"
	.string "Ça va?\p"
	.string "Tu as traversé {STR_VAR_3} salles d’un\n"
	.string "certain {STR_VAR_2}?\p"
	.string "C’est assez impressionnant.\n"
	.string "Au revoir!$"

MatchCall_BattlePikeText13::
	.string "Bonjour, {PLAYER}{KUN}!\n"
	.string "C’est {STR_VAR_1} qui appelle!\l"
	.string "J’espère que tout va bien.\p"
	.string "C’est vrai ce qu’on dit? Tu as\n"
	.string "traversé {STR_VAR_3} salles du\l"
	.string "{STR_VAR_2}?\p"
	.string "Quelle énergie! Je t’admire.\n"
	.string "A bientôt.$"

MatchCall_BattlePikeText14::
	.string "Bonjour, {PLAYER}{KUN}.\n"
	.string "C’est {STR_VAR_1}.\l"
	.string "J’ai entendu parler de toi!\p"
	.string "Tu as traversé {STR_VAR_3} salles du\n"
	.string "{STR_VAR_2}, non?\p"
	.string "Tu es un modèle pour moi!\n"
	.string "Au revoir!$"

MatchCall_BattlePyramidText1::
	.string "{PLAYER}?\n"
	.string "Bonjour, c’est {STR_VAR_1}!\l"
	.string "Je suis au courant!\p"
	.string "Tu as accédé à {STR_VAR_3} niveaux\n"
	.string "de la {STR_VAR_2}?\p"
	.string "C’est super, ça!\n"
	.string "Je devrais essayer d’y aller.$"

MatchCall_BattlePyramidText2::
	.string "Bonjour, c’est {STR_VAR_1}!\n"
	.string "J’ai entendu parler de toi!\p"
	.string "Il paraît que tu as accédé à\n"
	.string "{STR_VAR_3} niveaux de la\l"
	.string "{STR_VAR_2}.\p"
	.string "Fantastique! Je devrais m’occuper\n"
	.string "mieux de mes POKéMON!$"

MatchCall_BattlePyramidText3::
	.string "Salut, {PLAYER}!\n"
	.string "C’est moi, {STR_VAR_1}.\l"
	.string "Comment vas-tu?\p"
	.string "J’ai entendu dire que tu avais\n"
	.string "monté {STR_VAR_3} niveaux de la\l"
	.string "{STR_VAR_2}!\p"
	.string "Essaie de faire encore mieux\n"
	.string "la prochaine fois! Au revoir!$"

MatchCall_BattlePyramidText4::
	.string "Allô, {PLAYER}{KUN}?\n"
	.string "Ici {STR_VAR_1}. Bonjour!\p"
	.string "Il paraît que tu as exploré {STR_VAR_3}\n"
	.string "niveaux de la {STR_VAR_2}.\p"
	.string "Je devrais en prendre de\n"
	.string "la graine!$"

MatchCall_BattlePyramidText5::
	.string "Salut, {PLAYER}{KUN}!\n"
	.string "{STR_VAR_1} à l’appareil.\p"
	.string "On m’a dit que tu avais exploré {STR_VAR_3}\n"
	.string "niveaux de la {STR_VAR_2}.\p"
	.string "Moi aussi, je devrais m’y mettre!\n"
	.string "A bientôt!$"

MatchCall_BattlePyramidText6::
	.string "{PLAYER}{KUN}?\n"
	.string "Ici {STR_VAR_1}. Comment ça va?\p"
	.string "Au fait, il paraît que tu as accédé\n"
	.string "à {STR_VAR_3} niveaux de la\l"
	.string "{STR_VAR_2}!\p"
	.string "Je ferais bien de me concentrer sur\n"
	.string "mes POKéMON.$"

MatchCall_BattlePyramidText7::
	.string "{PLAYER}{KUN}?\n"
	.string "Ici {STR_VAR_1}.\p"
	.string "Tu as exploré la\n"
	.string "{STR_VAR_2} et accédé\l"
	.string "à {STR_VAR_3} des niveaux?\p"
	.string "Impec. Est-ce que tu y as vu des\n"
	.string "POKéMON rares?\p"
	.string "Non?\n"
	.string "Allez, au revoir!$"

MatchCall_BattlePyramidText8::
	.string "Ça va, {PLAYER}{KUN}?\n"
	.string "C’est {STR_VAR_1}.\l"
	.string "Ça a l’air d’aller pour toi.\p"
	.string "J’ai entendu dire que tu avais\n"
	.string "exploré {STR_VAR_3} niveaux de la\l"
	.string "{STR_VAR_2}.\p"
	.string "C’est très impressionnant!\n"
	.string "Je vais élever mes POKéMON de la\l"
	.string "même façon que toi. Au revoir!$"

MatchCall_BattlePyramidText9::
	.string "Salut, {PLAYER}{KUN}!\n"
	.string "C’est {STR_VAR_1}!\p"
	.string "Tu as conquis {STR_VAR_3} niveaux\n"
	.string "de la {STR_VAR_2}! Bravo!\p"
	.string "C’est formidable!\n"
	.string "Bon, je ferais bien de t’imiter!$"

MatchCall_BattlePyramidText10::
	.string "Bonjour, {PLAYER}{KUN}.\n"
	.string "C’est {STR_VAR_1}.\p"
	.string "C’est vrai ce qu’on dit?\n"
	.string "Tu as exploré {STR_VAR_3} niveaux\l"
	.string "de la {STR_VAR_2}?\p"
	.string "Je vais essayer de suivre ton\n"
	.string "exemple. Je dois m’améliorer.$"

MatchCall_BattlePyramidText11::
	.string "{PLAYER}{KUN}?\n"
	.string "Bonjour, c’est {STR_VAR_1}.\p"
	.string "On va devoir t’appeler sa Majesté\n"
	.string "{STR_VAR_2} bientôt, non?\p"
	.string "Tu as vraiment exploré {STR_VAR_3}\n"
	.string "niveaux?\l"
	.string "Ce n’est pas rien!\p"
	.string "Je me demande si je remporterai\n"
	.string "un titre un jour…\p"
	.string "Mais ça m’étonnerait…\n"
	.string "Bon, au revoir!$"

MatchCall_BattlePyramidText12::
	.string "Bonjour, {PLAYER}{KUN}.\n"
	.string "C’est {STR_VAR_1}.\l"
	.string "Ça va?\p"
	.string "Dis-moi, as-tu réellement exploré\n"
	.string "{STR_VAR_3} niveaux de la\l"
	.string "{STR_VAR_2}?\p"
	.string "C’est assez impressionnant.\n"
	.string "Au revoir!$"

MatchCall_BattlePyramidText13::
	.string "Bonjour, {PLAYER}{KUN}!\n"
	.string "C’est {STR_VAR_1} qui appelle!\l"
	.string "J’espère que tout va bien.\p"
	.string "On dit que tu as exploré {STR_VAR_3}\n"
	.string "niveaux de la {STR_VAR_2}?\p"
	.string "Quelle énergie! Je t’admire.\n"
	.string "A bientôt.$"

MatchCall_BattlePyramidText14::
	.string "Bonjour, {PLAYER}{KUN}.\n"
	.string "C’est {STR_VAR_1}.\l"
	.string "J’ai entendu parler de toi!\p"
	.string "C’est bien toi qui as exploré\n"
	.string "{STR_VAR_3} niveaux de la\l"
	.string "{STR_VAR_2}?\p"
	.string "Tu es un modèle pour moi!\n"
	.string "Au revoir!$"

MatchCall_Text_Mom1::
	.string "MAMAN: D’abord ton père,\n"
	.string "maintenant toi…\p"
	.string "Mais qu’est-ce qui vous attire\n"
	.string "tant chez les POKéMON?\p"
	.string "Moi? J’aime les POKéMON qui peuvent\n"
	.string "m’aider à la maison, c’est tout.$"

MatchCall_Text_Mom2::
	.string "MAMAN: Bonjour, {PLAYER}!\n"
	.string "Ton père passe tout son temps\l"
	.string "dans l’ARENE de CLEMENTI-VILLE.\p"
	.string "Il passe de temps en temps,\n"
	.string "avale tout ce qu’il peut et repart\l"
	.string "immédiatement à l’ARENE.\p"
	.string "Je me fais du souci pour lui. Perdre\n"
	.string "contre toi a été un gros choc!$"

MatchCall_Text_Mom3::
	.string "MAMAN: {PLAYER}…\n"
	.string "Tout va bien à la maison, mon chou.\p"
	.string "Use bien les semelles de tes\n"
	.string "CHAUSSURES DE SPORT!$"

MatchCall_Text_Roxanne1::
	.string "ROXANNE: Bonjour, {PLAYER}!\p"
	.string "Je suis en train de me remettre\n"
	.string "à niveau.\p"
	.string "Je ne vais pas rouvrir l’ARENE\n"
	.string "tout de suite.\p"
	.string "Mais dès que l’ARENE sera prête,\n"
	.string "passe faire un combat!$"

MatchCall_Text_Roxanne2::
	.string "ROXANNE: C’est toi, {PLAYER}?\n"
	.string "Félicitations!\l"
	.string "J’ai entendu parler de toi!\p"
	.string "Eh bien, je ne vais pas rouvrir\n"
	.string "l’ARENE tout de suite.\p"
	.string "Mais dès que l’ARENE sera prête,\n"
	.string "passe faire un combat!$"

MatchCall_Text_Roxanne3::
	.string "ROXANNE: {PLAYER}!\n"
	.string "L’ARENE est prête!\p"
	.string "J’espère que tu vas bientôt venir\n"
	.string "à MEROUVILLE!$"

MatchCall_Text_Roxanne4::
	.string "ROXANNE: M’être battue contre toi\n"
	.string "dans l’ARENE de MEROUVILLE me\l"
	.string "remplit de fierté, {PLAYER}.$"

MatchCall_Text_Brawly1::
	.string "BASTIEN: Salut, {PLAYER}{KUN}!\p"
	.string "Notre combat m’a beaucoup appris.\p"
	.string "Je vais suivre un entraînement\n"
	.string "intensif avant de rouvrir l’ARENE.\p"
	.string "Mais ça risque de durer quelque\n"
	.string "temps.\p"
	.string "Quand tout sera prêt, j’espère que\n"
	.string "tu passeras refaire un combat.$"

MatchCall_Text_Brawly2::
	.string "BASTIEN: Salut, {PLAYER}{KUN}!\n"
	.string "Bravo!\p"
	.string "La nouvelle s’est répandue comme\n"
	.string "une traînée de poudre!\p"
	.string "Je vais devoir me remettre\n"
	.string "sérieusement à l’entraînement.\p"
	.string "Ça va prendre un peu de temps\n"
	.string "avant que je rouvre l’ARENE.\p"
	.string "Quand tout sera prêt, j’espère que\n"
	.string "tu passeras refaire un combat.$"

MatchCall_Text_Brawly3::
	.string "BASTIEN: Salut, {PLAYER}{KUN}!\n"
	.string "Je suis prêt à rouvrir l’ARENE!\p"
	.string "Reviens à MYOKARA quand tu veux!$"

MatchCall_Text_Brawly4::
	.string "BASTIEN: {PLAYER}{KUN}, je ne me lasserai\n"
	.string "jamais de me battre contre toi!$"

MatchCall_Text_Wattson1::
	.string "VOLTERE: Oh, c’est toi!\p"
	.string "Après notre combat, j’ai repris\n"
	.string "l’entraînement depuis le début.\p"
	.string "J’ai besoin d’encore un petit peu\n"
	.string "de temps avant de rouvrir l’ARENE.\p"
	.string "Tu vas devoir attendre avant de\n"
	.string "m’affronter à nouveau. Wahahaha!$"

MatchCall_Text_Wattson2::
	.string "VOLTERE: Wahahaha!\p"
	.string "Tu as réussi, n’est-ce pas? La\n"
	.string "nouvelle est arrivée jusqu’à moi!\p"
	.string "J’ai encore besoin de continuer\n"
	.string "un peu l’entraînement.\p"
	.string "Je ne vais pas rouvrir l’ARENE\n"
	.string "tout de suite.\p"
	.string "Tu vas devoir attendre avant de\n"
	.string "m’affronter à nouveau. Wahahaha!$"

MatchCall_Text_Wattson3::
	.string "VOLTERE: Oh, c’est toi!\n"
	.string "L’ARENE est prête!\p"
	.string "Viens à LAVANDIA quand tu veux!\n"
	.string "Waaaaaouh!$"

MatchCall_Text_Wattson4::
	.string "VOLTERE: Wahahahaha!\p"
	.string "Ton énergie me fait toujours\n"
	.string "du bien!$"

MatchCall_Text_Flannery1::
	.string "ADRIANE: {PLAYER}…\p"
	.string "Après notre combat, j’ai réalisé\n"
	.string "que je manquais d’expérience.\p"
	.string "Mais je ne baisse pas les bras\n"
	.string "pour autant!\p"
	.string "Je vais m’entraîner dur avant de\n"
	.string "rouvrir l’ARENE.\p"
	.string "Quand le moment sera venu,\n"
	.string "nous nous battrons, {PLAYER}.$"

MatchCall_Text_Flannery2::
	.string "ADRIANE: Salut, {PLAYER}?\n"
	.string "Félicitations!\p"
	.string "La nouvelle de ta réussite m’a\n"
	.string "fait chaud au cœur!\p"
	.string "L’entraînement se passe à\n"
	.string "merveille.\p"
	.string "Dès que l’ARENE sera prête, une\n"
	.string "marque apparaîtra près de mon\l"
	.string "nom dans la liste du MATCH PHONE.$"

MatchCall_Text_Flannery3::
	.string "ADRIANE: Oh, {PLAYER}?\n"
	.string "L’ARENE est prête!\p"
	.string "Viens à VERMILAVA! On a des\n"
	.string "sources chaudes et j’aimerais\l"
	.string "me battre de nouveau contre toi!$"

MatchCall_Text_Flannery4::
	.string "ADRIANE: {PLAYER}…\n"
	.string "Je vois que tu ne cesses de\l"
	.string "progresser.$"

MatchCall_Text_Winona1::
	.string "ALIZEE: Bonjour, {PLAYER}!\p"
	.string "Notre combat m’a permis de\n"
	.string "comprendre mes points faibles!\p"
	.string "Quand je rouvrirai l’ARENE,\n"
	.string "j’aurai beaucoup progressé!$"

MatchCall_Text_Winona2::
	.string "ALIZEE: Bravo, {PLAYER}!\p"
	.string "Tout le monde à CIMETRONELLE\n"
	.string "sait qui est le nouveau MAITRE!\p"
	.string "Mais… l’issue de notre prochain\n"
	.string "combat sera différente, crois-moi.$"

MatchCall_Text_Winona3::
	.string "ALIZEE: C’est toi, {PLAYER}?\n"
	.string "J’ai rouvert l’ARENE!\p"
	.string "On t’attend tous à\n"
	.string "CIMETRONELLE!$"

MatchCall_Text_Winona4::
	.string "ALIZEE: {PLAYER}…\n"
	.string "J’ai perdu, mais cette défaite ne\l"
	.string "va pas m’ébranler.\p"
	.string "Tu peux comprendre, car toi aussi\n"
	.string "tu vis pour tes rêves.$"

MatchCall_Text_TateLiza1::
	.string "LEVY: Oh! C’est…\n"
	.string "TATIA: {PLAYER}!\p"
	.string "LEVY: On a repris l’entraînement…\n"
	.string "TATIA: pour rouvrir l’ARENE!\p"
	.string "LEVY: Quand l’ARENE sera prête…\n"
	.string "TATIA: il y aura un symbole…\p"
	.string "LEVY: près de nos noms dans…\n"
	.string "TATIA: la liste du MATCH PHONE.$"

MatchCall_Text_TateLiza2::
	.string "LEVY: Félicitations, {PLAYER}!\n"
	.string "TATIA: Félicitations, {PLAYER}!\p"
	.string "LEVY: Nous, on s’entraîne…\n"
	.string "TATIA: encore!\p"
	.string "LEVY: Quand l’ARENE sera prête…\n"
	.string "TATIA: il y aura un symbole…\p"
	.string "LEVY: près de nos noms dans…\n"
	.string "TATIA: la liste du MATCH PHONE.$"

MatchCall_Text_TateLiza3::
	.string "LEVY: {PLAYER}!\n"
	.string "TATIA: {PLAYER}!\p"
	.string "LEVY: L’ARENE est prête!\n"
	.string "TATIA: L’ARENE est prête!\p"
	.string "LEVY: Passe nous voir…\n"
	.string "TATIA: à ALGATIA!$"

MatchCall_Text_TateLiza4::
	.string "LEVY: {PLAYER}, notre combat…\n"
	.string "TATIA: a été une expérience unique.\p"
	.string "LEVY: Ce serait bien si on faisait…\n"
	.string "TATIA: un autre combat bientôt!$"

MatchCall_Text_Juan1::
	.string "JUAN: Hum…\n"
	.string "{PLAYER}{KUN}… C’est ça?\p"
	.string "Notre combat m’a rappelé la\n"
	.string "première fois que j’ai vu MARC.\p"
	.string "Peut-être arriverez-vous à\n"
	.string "surpasser MARC? Qui sait!?!$"

MatchCall_Text_Juan2::
	.string "JUAN: Dites donc… {PLAYER}{KUN}…\n"
	.string "Vous avez atteint votre objectif!\p"
	.string "Vous voyez, j’ai l’œil pour\n"
	.string "découvrir les nouveaux talents…\p"
	.string "Vous avez réussi à atteindre le\n"
	.string "sommet de la gloire. J’espère vous\l"
	.string "revoir bientôt!$"

MatchCall_Text_Juan3::
	.string "JUAN: Ho, ho… {PLAYER}{KUN}…\p"
	.string "L’ARENE d’ATALANOPOLIS a enfin\n"
	.string "rouvert.\p"
	.string "Si vous voulez me voir, vous pouvez\n"
	.string "passer quand vous voulez.$"

MatchCall_Text_Juan4::
	.string "JUAN: {PLAYER}{KUN}…\p"
	.string "Quand je me bats contre vous, c’est\n"
	.string "comme si une musique\l"
	.string "majestueuse jouait dans mon cœur…\p"
	.string "En fermant les yeux, je vous vois\n"
	.string "danser gracieusement…$"

MatchCall_Text_Sidney::
	.string "DAMIEN: Salut, {PLAYER}!\p"
	.string "Repasse quand tu veux à la LIGUE\n"
	.string "POKéMON si tu veux te battre\l"
	.string "encore contre moi.\p"
	.string "J’y serai!\n"
	.string "Je t’attends!$"

MatchCall_Text_Phoebe::
	.string "SPECTRA: Salut, {PLAYER}!\p"
	.string "Tu devrais passer nous voir, un de\n"
	.string "ces jours!\p"
	.string "J’aimerais voir à quel point ton\n"
	.string "attachement à tes POKéMON a\l"
	.string "grandi.$"

MatchCall_Text_Glacia::
	.string "GLACIA: Salut, {PLAYER}.\p"
	.string "Jure-moi que tu n’as pas pris la\n"
	.string "grosse tête!\p"
	.string "Si tu as besoin d’une petite douche\n"
	.string "froide, passe à la LIGUE POKéMON…$"

MatchCall_Text_Drake::
	.string "ARAGON: Cette voix…\n"
	.string "C’est toi, {PLAYER}?\p"
	.string "Je sais que maintenant il y a la\n"
	.string "ZONE DE COMBAT où les DRESSEURS\l"
	.string "peuvent tester leurs aptitudes.\p"
	.string "Mais si tu veux faire de vrais\n"
	.string "combats, on n’a encore rien inventé\l"
	.string "de mieux que la LIGUE POKéMON!\p"
	.string "Tu ne crois pas, {PLAYER}?$"

MatchCall_Text_Wallace::
	.string "MARC: Salut, {PLAYER}{KUN}.\n"
	.string "As-tu rencontré PIERRE?\p"
	.string "Il est… Comment dire…\n"
	.string "Il est vraiment doué!\p"
	.string "Mais il se bat très rarement,\n"
	.string "c’est un solitaire.\p"
	.string "Il préfère chercher des pierres\n"
	.string "rares.\p"
	.string "Au moment où on parle, il est\n"
	.string "sûrement en train de creuser\l"
	.string "dans une caverne ou une montagne.\p"
	.string "C’est quoi une pierre rare, en fait?\n"
	.string "Je ne vois que les METEORITES…$"

MatchCall_Text_MayRayquazaCall:
	.string "… … … … … …\n"
	.string "… … … … … Bip!\p"
	.string "FLORA: Bonjour, {PLAYER}{KUN}!\p"
	.string "Je suis allée à PACIFIVILLE\n"
	.string "il y a quelques jours.\p"
	.string "J’y ai vu un POKéMON géant\n"
	.string "de couleur verte voler dans le ciel!\p"
	.string "Je n’avais jamais vu une chose\n"
	.string "pareille…\p"
	.string "Je me demande bien ce que c’était.\n"
	.string "C’est peut-être une découverte!\p"
	.string "… … … … … …\n"
	.string "… … … … … Clic!$"

MatchCall_Text_BrendanRayquazaCall:
	.string "… … … … … …\n"
	.string "… … … … … Bip!\p"
	.string "BRICE: Salut, {PLAYER}!\n"
	.string "Je reviens de PACIFIVILLE.\p"
	.string "J’y ai vu un POKéMON géant de\n"
	.string "couleur verte voler dans le ciel!\p"
	.string "Je n’avais jamais vu un truc pareil!\p"
	.string "J’aurais aimé que tu voies ça,\n"
	.string "{PLAYER}.\p"
	.string "… … … … … …\n"
	.string "… … … … … Clic!$"

MatchCall_Text_May1::
	.string "FLORA: Bonjour, {PLAYER}{KUN}!\p"
	.string "M. MARCO a pris sa retraite de\n"
	.string "MARIN, mais de temps en temps,\l"
	.string "je le vois en mer avec son PIKO.\p"
	.string "La mer, c’était plus qu’un travail\n"
	.string "pour lui. C’est une vraie passion.$"

MatchCall_Text_May2::
	.string "FLORA: Bonjour, {PLAYER}{KUN}!\p"
	.string "Tu sais qu’il y a une ARENE à\n"
	.string "CLEMENTI-VILLE et MYOKARA?\l"
	.string "Ce sont pourtant de petites villes.\p"
	.string "Par contre, il n’y en a pas dans la\n"
	.string "grande ville portuaire de\l"
	.string "POIVRESSEL.\p"
	.string "Le jour où ils en construiront une,\n"
	.string "je postulerai pour le poste de\l"
	.string "CHAMPION D’ARENE.$"

MatchCall_Text_May3::
	.string "FLORA: Bonjour, {PLAYER}{KUN}!\p"
	.string "Tu te souviens de l’homme de la\n"
	.string "MAISON COUPCOUP à MEROUVILLE?\p"
	.string "Je viens d’apprendre qu’il a un\n"
	.string "petit frère qui habite à LAVANDIA.\p"
	.string "Tu veux savoir comment il\n"
	.string "s’appelle?\p"
	.string "… … … … … …\n"
	.string "… … … … … …\p"
	.string "TYPE ECLATE-ROC!$"

MatchCall_Text_May4::
	.string "FLORA: {PLAYER}{KUN}?\p"
	.string "TUNNEL MERAZON…\n"
	.string "Ils l’ont appelé comme ça parce \l"
	.string "qu’il relie MEROUVILLE à VERGAZON.$"

MatchCall_Text_May5::
	.string "FLORA: Comment ça va, {PLAYER}{KUN}?\p"
	.string "Je suis sur la ROUTE 111.\p"
	.string "Je vais faire une halte chez une\n"
	.string "dame âgée pour me reposer.\p"
	.string "Elle habite au nord du désert.$"

MatchCall_Text_May6::
	.string "FLORA: Bonjour, {PLAYER}{KUN}!\p"
	.string "Tu connais la TOUR MIRAGE\n"
	.string "qui se trouve dans le désert?\p"
	.string "Elle disparaît parfois\n"
	.string "mystérieusement, puis réapparaît\l"
	.string "tel un mirage.\p"
	.string "J’aimerais bien la voir.$"

MatchCall_Text_May7::
	.string "FLORA: Salut, {PLAYER}{KUN}!\n"
	.string "Je suis sur la ROUTE 119.\p"
	.string "Il y a une rivière immense.\n"
	.string "Et il n’arrête pas de pleuvoir.\p"
	.string "Je suis trempée jusqu’aux os!$"

MatchCall_Text_May8::
	.string "FLORA: Bonjour, {PLAYER}{KUN}.\p"
	.string "Le MONT MEMORIA est un mémorial\n"
	.string "dédié aux POKéMON qui nous ont\l"
	.string "malheureusement quittés.\p"
	.string "Forcément, le lieu est rempli de\n"
	.string "POKéMON de type SPECTRE!$"

MatchCall_Text_May9::
	.string "FLORA: Bonjour, {PLAYER}{KUN}!\p"
	.string "Je pensais aller aux sources\n"
	.string "chaudes de VERMILAVA.\p"
	.string "Mais près du SENTIER SINUROC, j’ai\n"
	.string "rencontré des gens bizarres. Ils\l"
	.string "n’avaient pas l’air de bonne humeur.$"

MatchCall_Text_May10::
	.string "FLORA: Bonjour, {PLAYER}{KUN}!\n"
	.string "Tu es au courant?\p"
	.string "Il paraît que le CAPT. POUPE a\n"
	.string "découvert la CAVERNE FONDMER lors\l"
	.string "de son expédition sous-marine.$"

MatchCall_Text_May11::
	.string "FLORA: Bonjour, {PLAYER}{KUN}!\n"
	.string "Tu sais quoi?\p"
	.string "Si tu n’as pas de bateau, il y a une\n"
	.string "capacité de POKéMON qui peut te\l"
	.string "faire flotter sur l’eau.\p"
	.string "Et ce n’est pas tout!\p"
	.string "Il y a même une autre capacité qui\n"
	.string "permet d’aller au fond de la mer.$"

MatchCall_Text_May12::
	.string "FLORA: Bonjour, {PLAYER}{KUN}!\n"
	.string "Tout va bien?\p"
	.string "Tu as dû voir que parfois on ne\n"
	.string "peut pas traverser la mer.\l"
	.string "C’est tout simplement bloqué.\p"
	.string "Il faut plonger sous l’eau et\n"
	.string "suivre les sillons.\p"
	.string "Une fois de l’autre côté, il suffit\n"
	.string "de remonter à la surface. Facile!$"

MatchCall_Text_May13::
	.string "FLORA: Bonjour, {PLAYER}{KUN}!\p"
	.string "Comment ça va?\n"
	.string "Tu remplis bien ton POKéDEX?\p"
	.string "J’ai entendu dire qu’il y a des\n"
	.string "POKéMON très anciens par ici.\l"
	.string "Il y en aurait trois!\p"
	.string "J’aimerais bien en voir au\n"
	.string "moins un…$"

MatchCall_Text_May14::
	.string "FLORA: {PLAYER}{KUN}!\n"
	.string "Les gens parlent de toi!\p"
	.string "Tu as battu le CHAMPION D’ARENE\n"
	.string "d’ATALANOPOLIS, c’est super!\p"
	.string "Il ne te reste plus beaucoup de\n"
	.string "chemin à parcourir.$"

MatchCall_Text_May15::
	.string "FLORA: Il n’y a pas un seul\n"
	.string "DRESSEUR à HOENN qui n’ait jamais\l"
	.string "entendu parler de toi, {PLAYER}{KUN}!\p"
	.string "Quand je dis aux gens que je\n"
	.string "te connais, {PLAYER}{KUN}, ils sont\l"
	.string "impressionnés!$"

MatchCall_Text_Brendan1::
	.string "BRICE: Salut, {PLAYER}!\p"
	.string "M. MARCO a pris sa retraite de\n"
	.string "MARIN, mais il part toujours en\l"
	.string "mer avec son PIKO.\p"
	.string "Ce n’est pas parce qu’il est à la\n"
	.string "retraite qu’il va oublier la mer!$"

MatchCall_Text_Brendan2::
	.string "BRICE: Salut, {PLAYER}!\p"
	.string "Pourquoi CLEMENTI-VILLE\n"
	.string "et MYOKARA ont une ARENE?\p"
	.string "Après tout, POIVRESSEL n’en a pas\n"
	.string "et c’est beaucoup plus grand!\p"
	.string "S’il y en avait une, je voudrais en\n"
	.string "être le CHAMPION.$"

MatchCall_Text_Brendan3::
	.string "BRICE: Bonjour, {PLAYER}!\p"
	.string "Tu te souviens de la MAISON\n"
	.string "COUPCOUP à MEROUVILLE?\p"
	.string "L’homme qui y vit a un petit frère\n"
	.string "à LAVANDIA.\p"
	.string "Devine comment il s’appelle!\p"
	.string "… … … … … …\n"
	.string "… … … … … …\p"
	.string "TYPE ECLATE-ROC!$"

MatchCall_Text_Brendan4::
	.string "BRICE: {PLAYER}?\p"
	.string "Tu sais que le TUNNEL MERAZON\n"
	.string "s’appelle comme ça parce qu’il\l"
	.string "relie MEROUVILLE à VERGAZON?\p"
	.string "Tu le savais?$"

MatchCall_Text_Brendan5::
	.string "BRICE: {PLAYER}, quoi de neuf?\p"
	.string "Je suis sur la ROUTE 111, là.\p"
	.string "Je vais me reposer un peu chez une\n"
	.string "vielle dame au nord du désert.\p"
	.string "Si tu es dans le coin, tu pourrais\n"
	.string "aussi lui rendre visite.$"

MatchCall_Text_Brendan6::
	.string "BRICE: Hé, {PLAYER}!\p"
	.string "Tu as entendu parler de la TOUR\n"
	.string "MIRAGE dans le désert?\p"
	.string "Il paraît qu’on ne peut pas la voir\n"
	.string "tout le temps, comme un mirage!\p"
	.string "Ça, c’est un truc à voir!$"

MatchCall_Text_Brendan7::
	.string "BRICE: Qui c’est? {PLAYER}!\n"
	.string "Je suis sur la ROUTE 119.\p"
	.string "Il y a une grosse rivière et il pleut\n"
	.string "des cordes.\p"
	.string "Je suis complètement trempé!$"

MatchCall_Text_Brendan8::
	.string "BRICE: {PLAYER}!\p"
	.string "Le MONT MEMORIA est dédié aux\n"
	.string "POKéMON qui nous ont quittés.\p"
	.string "Du coup, tous les POKéMON de type\n"
	.string "SPECTRE y vont!$"

MatchCall_Text_Brendan9::
	.string "BRICE: Salut, {PLAYER}.\p"
	.string "Je suis allé aux sources chaudes\n"
	.string "de VERMILAVA aujourd’hui.\p"
	.string "J’ai croisé des gens à l’air louche\n"
	.string "près du SENTIER SINUROC.\p"
	.string "Des sales types…\n"
	.string "Ça devait être la TEAM MAGMA.$"

MatchCall_Text_Brendan10::
	.string "BRICE: Bonjour, {PLAYER}!\n"
	.string "Tu es au courant?\p"
	.string "Le CAPT. POUPE a découvert la\n"
	.string "CAVERNE FONDMER pendant une\l"
	.string "expédition sous-marine.$"

MatchCall_Text_Brendan11::
	.string "BRICE: Hé! Salut, {PLAYER}!\n"
	.string "Je vais t’apprendre un truc!\p"
	.string "Il y a une capacité de POKéMON\n"
	.string "qui permet d’aller en mer même\l"
	.string "si on n’a pas de bateau!\p"
	.string "Et il y en a aussi une qui permet\n"
	.string "d’aller au fond de la mer.\p"
	.string "Je trouve ça dingue!$"

MatchCall_Text_Brendan12::
	.string "BRICE: Salut, {PLAYER}!\n"
	.string "Ça va comme tu veux?\p"
	.string "Tu sais que parfois il est\n"
	.string "impossible de franchir la mer?\p"
	.string "Dans ces cas-là, il faut plonger et\n"
	.string "suivre les sillons au fond de la mer.\p"
	.string "Une fois de l’autre côté, il suffit\n"
	.string "de revenir à la surface! Enfantin!$"

MatchCall_Text_Brendan13::
	.string "BRICE: Salut, {PLAYER}!\p"
	.string "Tu vas bien? Ça avance ton\n"
	.string "POKéDEX?\p"
	.string "Il paraît qu’il y a des POKéMON très\n"
	.string "anciens dans le coin. Trois!\p"
	.string "J’aimerais en attraper au moins un…$"

MatchCall_Text_Brendan14::
	.string "BRICE: {PLAYER}!\n"
	.string "Hé, je suis au courant!\p"
	.string "Tu as battu le CHAMPION D’ARENE\n"
	.string "d’ATALANOPOLIS! Trop cool!\p"
	.string "Tu es près du but!$"

MatchCall_Text_Brendan15::
	.string "BRICE: Tous les DRESSEURS te\n"
	.string "connaissent à HOENN, {PLAYER}!\p"
	.string "Les gens ne me croient même pas\n"
	.string "quand je leur dis que je suis l’ami\l"
	.string "de {PLAYER}! Ils sont tous jaloux.$"

MatchCall_Text_Wally1::
	.string "TIMMY: Oh, {PLAYER}!\p"
	.string "Je suis en bien meilleure\n"
	.string "forme, maintenant.\p"
	.string "J’espère être bientôt un aussi bon\n"
	.string "DRESSEUR que toi, {PLAYER}!$"

MatchCall_Text_Wally2::
	.string "TIMMY: Salut, {PLAYER}!\p"
	.string "Depuis que le TUNNEL MERAZON\n"
	.string "est creusé, SYLVIE est aux anges!$"

MatchCall_Text_Wally3::
	.string "TIMMY: Oh, {PLAYER}!\p"
	.string "Je suis parti de chez mon oncle\n"
	.string "à VERGAZON sans prévenir personne.\p"
	.string "Il doit être furieux contre moi…\p"
	.string "Mais {PLAYER}… Toi, tu me comprends,\n"
	.string "non?$"

MatchCall_Text_Wally4::
	.string "TIMMY: {PLAYER}?\n"
	.string "C’est moi, TIMMY!\p"
	.string "L’univers des DRESSEURS,\n"
	.string "c’est quelque chose!\p"
	.string "Dès que tu as des POKéMON, tout\n"
	.string "le monde te parle!\p"
	.string "C’est comme si les POKéMON\n"
	.string "rapprochaient les gens!$"

MatchCall_Text_Wally5::
	.string "TIMMY: {PLAYER}? Tu sais quoi?\n"
	.string "Le TARSAL qu’on a capturé\l"
	.string "ensemble a évolué!\p"
	.string "Peut-être que je suis doué,\n"
	.string "après tout…\p"
	.string "En tout cas, il ne faut pas que\n"
	.string "je prenne la grosse tête!\p"
	.string "C’est le POKéMON qui fait le\n"
	.string "plus gros du travail!$"

MatchCall_Text_Wally6::
	.string "… … … … … …\n"
	.string "… … … … … …\p"
	.string "TIMMY est dans un endroit non\n"
	.string "couvert par le réseau POKéNAV…$"

MatchCall_Text_Wally7::
	.string "TIMMY: Oh, {PLAYER}!\p"
	.string "Avant de te connaître, je passais\n"
	.string "tout mon temps à la maison…\p"
	.string "Et maintenant, je sillonne les\n"
	.string "routes avec mes POKéMON!\p"
	.string "{PLAYER}…\n"
	.string "Je te dois tant…$"

MatchCall_Text_Scott1::
	.string "SCOTT: Bien le bonjour, {PLAYER}{KUN}!\p"
	.string "Tu sais qu’on trouve des POKéMON\n"
	.string "absolument partout?\p"
	.string "En montagne, dans la mer,\n"
	.string "dans les hautes herbes!?!\p"
	.string "De même, tu peux rencontrer des\n"
	.string "DRESSEURS partout.\p"
	.string "C’est pour ça que je cours toujours\n"
	.string "à droite à gauche!$"

MatchCall_Text_Scott2::
	.string "SCOTT: Je suis sur la ROUTE 119.\n"
	.string "Ça grouille de DRESSEURS ici!\p"
	.string "Le sol est recouvert de hautes\n"
	.string "herbes.\p"
	.string "Je suis en short, l’herbe me\n"
	.string "chatouille les gambettes!$"

MatchCall_Text_Scott3::
	.string "SCOTT: Bonjour, bonjour, {PLAYER}{KUN}!\p"
	.string "As-tu déjà eu l’occasion de gravir\n"
	.string "le MONT MEMORIA?\p"
	.string "C’est un mémorial dédié aux\n"
	.string "POKéMON qui nous ont quittés.\p"
	.string "Les DRESSEURS devraient tous\n"
	.string "y monter au moins une fois.$"

MatchCall_Text_Scott4::
	.string "SCOTT: Bonjour, {PLAYER}{KUN}!\p"
	.string "J’ai entendu parler de ces deux\n"
	.string "bandes qui font du grabuge.\p"
	.string "TEAM MAGMA et TEAM AQUA,\n"
	.string "je crois.\p"
	.string "Il doit y avoir quelques bons\n"
	.string "DRESSEURS parmi eux.\p"
	.string "Mais ce sont des brutes…$"

MatchCall_Text_Scott5::
	.string "SCOTT: Tiens! Bonjour, {PLAYER}{KUN}.\p"
	.string "Y a-t-il de bons DRESSEURS\n"
	.string "au fond de la mer?\p"
	.string "Je ne peux pas vérifier moi-même.\n"
	.string "Je ne sais pas nager.\l"
	.string "Et je n’élève pas de POKéMON…$"

MatchCall_Text_Scott6::
	.string "SCOTT: Bonjour, bonjour, {PLAYER}{KUN}!\p"
	.string "Tu sais que si tu as tous les\n"
	.string "BADGES D’ARENES, tu as le droit\l"
	.string "de défier la LIGUE POKéMON?\p"
	.string "Avec ton talent, tu as toutes les\n"
	.string "chances de devenir MAITRE.\p"
	.string "Mais tu sais…\n"
	.string "Il y a un endroit encore mieux.\p"
	.string "Je ne veux pas t’en dire plus pour\n"
	.string "l’instant.\p"
	.string "Mais penses-y.\p"
	.string "Quand la LIGUE POKéMON et le\n"
	.string "PANTHEON DES DRESSEURS\l"
	.string "seront derrière toi!$"

MatchCall_Text_Scott7::
	.string "… … … … … …\n"
	.string "… … … … … …\p"
	.string "SCOTT est dans un endroit non\n"
	.string "couvert par le réseau POKéNAV…$"

MatchCall_Text_Norman1::
	.string "PAPA: A MEROUVILLE, il y a un\n"
	.string "endroit qui s’appelle la MAISON\l"
	.string "COUPCOUP. Quel drôle de nom!\p"
	.string "Vas-y, si tu es dans le coin.$"

MatchCall_Text_Norman2::
	.string "PAPA: Hum… Tu fais des\n"
	.string "progrès, {PLAYER}.\p"
	.string "Plus le temps passe et plus tu\n"
	.string "t’éloignes de ta mère et moi…\p"
	.string "C’est un drôle de sentiment.$"

MatchCall_Text_Norman3::
	.string "PAPA: Je vois…\n"
	.string "Tu as quatre BADGES…\p"
	.string "Je vais devoir tenir ma promesse.\n"
	.string "Nous allons nous battre.\p"
	.string "Viens quand tu veux.\n"
	.string "Je t’attendrai.$"

MatchCall_Text_Norman4::
	.string "PAPA: {PLAYER}! Tu devrais rendre\n"
	.string "visite à ta mère de temps en temps.\p"
	.string "Moi, je reste ici. Je m’entraîne\n"
	.string "dur.\p"
	.string "La voie qui mène à la perfection\n"
	.string "est un chemin sans fin!$"

MatchCall_Text_Norman5::
	.string "PAPA: Bonjour, {PLAYER}!\p"
	.string "Quoi? Un SCEAU MAGMA?\n"
	.string "Je n’en ai jamais entendu parler.\p"
	.string "Mais vu le nom, ça doit avoir un\n"
	.string "rapport avec un volcan!$"

MatchCall_Text_Norman6::
	.string "PAPA: Allez! C’est ça!\p"
	.string "Oh? {PLAYER}!\p"
	.string "Je suis en pleine séance\n"
	.string "d’entraînement avec mes POKéMON!$"

MatchCall_Text_Norman7::
	.string "PAPA: {PLAYER}!\p"
	.string "Si j’avais su que tu deviendrais le\n"
	.string "MAITRE de la LIGUE POKéMON…\p"
	.string "Bien! Je dois réagir!\n"
	.string "Je ne vais pas me laisser faire!$"

MatchCall_Text_Norman8::
	.string "PAPA: Hum? {PLAYER}?\n"
	.string "Tu appelles au bon moment!\p"
	.string "Je t’invite à venir faire un combat\n"
	.string "contre moi.\p"
	.string "Je suis dans l’ARENE de\n"
	.string "CLEMENTI-VILLE.$"

MatchCall_Text_Norman9::
	.string "PAPA: Tu m’épates, {PLAYER}.\n"
	.string "Mais jusqu’où iras-tu?$"

MatchCall_Text_Steven1::
	.string "PIERRE: Bonjour, {PLAYER}{KUN}!\p"
	.string "As-tu déjà visité LAVANDIA?\p"
	.string "Tu devrais aller te procurer un\n"
	.string "VELO COURSE aux CYCLES\l"
	.string "RODOLPHE.\p"
	.string "Ensuite, je te conseille d’aller\n"
	.string "explorer la GROTTE GRANITE.\p"
	.string "Tu pourrais bien y faire une\n"
	.string "découverte.$"

MatchCall_Text_Steven2::
	.string "PIERRE: Bonjour, {PLAYER}{KUN}!\p"
	.string "J’ai rencontré beaucoup de\n"
	.string "DRESSEURS dans ma vie.\p"
	.string "Mais toi, tu n’es pas comme les\n"
	.string "autres. Ça saute aux yeux.$"

MatchCall_Text_Steven3::
	.string "PIERRE: Bonjour, {PLAYER}{KUN}!\p"
	.string "Quand tu es sur la route avec tes\n"
	.string "POKéMON, à quoi penses-tu?\p"
	.string "Tu les considères comme des\n"
	.string "partenaires solides?\p"
	.string "Ou plutôt comme d’agréables\n"
	.string "petits camarades?\p"
	.string "Les enjeux de ton périple\n"
	.string "sont liés à ton état d’esprit.$"

MatchCall_Text_Steven4::
	.string "PIERRE: Allô?\n"
	.string "{PLAYER}{KUN}?\p"
	.string "Je suis au CENTRE SPATIAL.\n"
	.string "J’ai des ennuis, là.\p"
	.string "Je suis désolé, je ne peux pas\n"
	.string "parler. Au revoir!$"

MatchCall_Text_Steven5::
	.string "PIERRE: Oh!\n"
	.string "{PLAYER}{KUN}!\p"
	.string "Ce n’est plus le moment de\n"
	.string "discuter. Il n’y a plus rien à dire.\p"
	.string "Tu dois croire en toi et faire ce\n"
	.string "que tu penses être juste.$"

MatchCall_Text_Steven6::
	.string "… … … … … …\p"
	.string "PIERRE ne prend pas l’appel…$"

MatchCall_Text_Steven7::
	.string "PIERRE: {PLAYER}{KUN}… Bravo pour ton\n"
	.string "entrée au PANTHEON DES DRESSEURS.\p"
	.string "… … … … … …\n"
	.string "… … … … … …\p"
	.string "J’espère que nos chemins se\n"
	.string "croiseront de nouveau!$"

MatchCall_Text_BirchRegisterCall:
	.string "PROF. SEKO: Oh, {PLAYER}{KUN}!\n"
	.string "J’ai entendu parler de toi, tu sais!\p"
	.string "On dirait que ton POKéNAV a été\n"
	.string "équipé du MATCH PHONE.\p"
	.string "Il faudrait que j’y sois enregistré!\p"
	.string "Comme ça, je pourrai garder un œil\n"
	.string "sur ton POKéDEX même quand tu\l"
	.string "es en vadrouille.\p"
	.string "… … … … … …$"

MatchCall_Text_RegisteredBirch:
	.string "Vous avez enregistré PROF. SEKO\n"
	.string "dans le POKéNAV.$"

MatchCall_Text_UnusedProfBirch:
	.string "PROF. BIRCH: When one has both\n"
	.string "the POKéDEX and POKéNAV, studying\l"
	.string "POKéMON becomes more fun, eh?$"

MatchCall_Text_MrStone1::
	.string "M. ROCHARD: Oh? {PLAYER}{KUN}!\p"
	.string "Je suis content de voir que\n"
	.string "le POKéNAV fonctionne!\p"
	.string "D’autres personnes y seront\n"
	.string "enregistrées, alors tu auras\l"
	.string "plein de gens à appeler!\p"
	.string "Ça a l’air de te faire plaisir!\p"
	.string "Hum…\n"
	.string "Comment je sais ça?\p"
	.string "Mais je te vois de la fenêtre\n"
	.string "de mon bureau, pardi!\p"
	.string "Ha, ha, ha!\n"
	.string "A bientôt!$"

MatchCall_Text_MrStone2::
	.string "M. ROCHARD: Oh? {PLAYER}{KUN}!\p"
	.string "Dis, tu as oublié la course que\n"
	.string "je t’ai demandée de faire?\p"
	.string "J’ai besoin que tu donnes ma\n"
	.string "lettre à PIERRE à MYOKARA…\p"
	.string "et que tu apportes le paquet au \n"
	.string "CAPT. POUPE à POIVRESSEL.\p"
	.string "Tu n’as pas oublié, dis?\p"
	.string "Je te laisse, je suis un DIRECTEUR\n"
	.string "très occupé! Au revoir!$"

MatchCall_Text_MrStone3::
	.string "M. ROCHARD: Oh! {PLAYER}{KUN}!\p"
	.string "Tu as vu PIERRE?\n"
	.string "Une récompense t’attend, alors!\p"
	.string "Quand tu seras de passage à\n"
	.string "MEROUVILLE, viens à mon bureau.\p"
	.string "A bientôt!$"

MatchCall_Text_MrStone4::
	.string "M. ROCHARD: Oh! {PLAYER}{KUN}!\p"
	.string "Tu savais que DEVON creusait\n"
	.string "le TUNNEL MERAZON?\p"
	.string "Mais on a dû arrêter pour préserver\n"
	.string "les POKéMON de cette zone.\p"
	.string "Franchement, si ça ne tenait qu’à\n"
	.string "moi…\p"
	.string "Si on s’arrête à ce genre de\n"
	.string "détails, on ne fait plus rien!$"

MatchCall_Text_MrStone5::
	.string "M. ROCHARD: Bonjour, {PLAYER}{KUN}!\p"
	.string "Quelqu’un de CLEMENTI-VILLE m’a\n"
	.string "dit que NORMAN est ton père!\p"
	.string "Tu as de qui tenir!$"

MatchCall_Text_MrStone6::
	.string "M. ROCHARD: Comment?\p"
	.string "Tu as battu ton propre père?\p"
	.string "Mais c’est ahurissant!\p"
	.string "Tu n’es pas n’importe qui, toi!\n"
	.string "Ha, ha, ha!$"

MatchCall_Text_MrStone7::
	.string "Allô?\n"
	.string "DEVON SARL, j’écou…\l"
	.string "{PLAYER}! Bonjour!\p"
	.string "Malheureusement, le DIRECTEUR\n"
	.string "vient de s’absenter.\p"
	.string "Le DIRECTEUR est très occupé.\n"
	.string "Comme toi, {PLAYER}.$"

MatchCall_Text_MrStone8::
	.string "Hein? Comment?\p"
	.string "GROU… Quoi? DON?\p"
	.string "La ligne est mauvaise…\n"
	.string "Je ne t’entends plus…\p"
	.string "BZZZZ…$"

MatchCall_Text_MrStone9::
	.string "Hein? Comment?\p"
	.string "La CAV… Quoi? FONDMER?\p"
	.string "La ligne est mauvaise…\n"
	.string "Je ne t’entends plus…\p"
	.string "BZZZZ…$"

MatchCall_Text_MrStone10::
	.string "M. ROCHARD: {PLAYER}{KUN}! C’est moi!\p"
	.string "Je sais que tu as réalisé toutes\n"
	.string "sortes de choses, mais je n’ai\l"
	.string "pas le temps de me tenir informé!\p"
	.string "Quoi qu’il en soit, continue comme\n"
	.string "ça, je me fie à ton jugement.\p"
	.string "Et si tu as besoin de moi,\n"
	.string "n’hésite pas à appeler.$"

MatchCall_Text_MrStone11::
	.string "M. ROCHARD: … … … … … …\n"
	.string "C’est toi, {PLAYER}{KUN}?\p"
	.string "Ta voix a pris tant d’assurance que\n"
	.string "je ne n’ai pas pu te reconnaître!\p"
	.string "Passe me voir à DEVON,\n"
	.string "à l’occasion!$"
