ProfileMan_Text_CollectTrainerProfiles:
	.string "Salut, DRESSEUR!\n"
	.string "Quel magnifique sourire tu as là!\p"
	.string "J’ai une passion. Je rassemble les\n"
	.string "profils de DRESSEURS de POKéMON.$"

ProfileMan_Text_MayISeeYourProfile:
	.string "Alors, qu’en dis-tu?\n"
	.string "Je peux voir ton profil?$"

ProfileMan_Text_EasyChatExplanation:
	.string "Pour créer son propre profil,\n"
	.string "il faut associer quatre mots ou\l"
	.string "groupes de mots.\p"
	.string "Je vais donner un exemple de profil\n"
	.string "constitué de quatre segments de texte.\p"
	.string "Chacun remplace, à sa guise, ces quatre\n"
	.string "segments de texte par d’autres, de\l"
	.string "façon à dépeindre son propre profil.\p"
	.string "Les mots que l’on peut utiliser sont\n"
	.string "nombreux.\p"
	.string "Ils sont classés par catégories, telles\n"
	.string "que POKéMON, vie quotidienne, hobbies,\l"
	.string "permettant de les trouver facilement.\p"
	.string "Il faut d’abord choisir une catégorie\n"
	.string "pour afficher une liste de choix.\p"
	.string "Ensuite, il faut sélectionner son choix.\p"
	.string "Il suffit de refaire pareil pour les\n"
	.string "autres choix et le profil est déterminé.$"

ProfileMan_Text_LetsSeeItThen:
	.string "Oui! Merci!\n"
	.string "Alors, voyons ton profil!$"

ProfileMan_Text_ImagineYouWouldHaveWonderfulProfile:
	.string "Oh non, vraiment?\p"
	.string "J’imagine que quelqu’un comme toi\n"
	.string "doit avoir un merveilleux profil…$"

ProfileMan_Text_NotIntoItRightNow:
	.string "Oh? Tu ne veux pas le faire maintenant?\p"
	.string "Comme tu veux!$"

ProfileMan_Text_YouHaveWonderfulSmile:
	.string "Salut, DRESSEUR!\n"
	.string "Quel magnifique sourire tu as!$"

ProfileMan_Text_MayISeeYourNewProfile:
	.string "Puis-je voir ton nouveau profil?$"

ProfileMan_Text_EvenBetterThanLastProfile:
	.string "Oui! Merci!\p"
	.string "J’espère que ce sera encore mieux que\n"
	.string "le profil que tu m’as déjà montré.$"

ProfileMan_Text_LikeProfileWayItIs:
	.string "Oh, tu aimes ton profil tel qu’il est.\p"
	.string "Je ne t’en blâme pas. C’est devenu un\n"
	.string "très bon profil.$"

ProfileMan_Text_FantasticProfile:
	.string "F… Fantastique!\p"
	.string "Ton profil est génial!\n"
	.string "Il révèle vraiment qui tu es.\p"
	.string "Tu sais, en voyant ce profil, on est\n"
	.string "forcément captivé par toi!\p"
	.string "Merci!$"

@ Unused
ProfileMan_Text_YouKnowSecretSaying:
	.string "Oh?\n"
	.string "You know the secret saying!\p"
	.string "That means you’re now a fellow member\n"
	.string "of the MYSTERY EVENT CLUB!$"
