BattleFrontier_RankingHall: @ 848559C
	.4byte BattleFrontier_RankingHall_Layout
	.4byte BattleFrontier_RankingHall_MapEvents
	.4byte BattleFrontier_RankingHall_MapScripts
	.4byte 0x0
	.2byte MUS_BIJYUTU
	.2byte 396
	.byte MAPSEC_BATTLE_FRONTIER
	.byte 0
	.byte WEATHER_NONE
	.byte MAP_TYPE_INDOOR
	.2byte 0
	map_header_flags allow_bike=0, allow_escape_rope=0, allow_run=0, show_map_name=0
	.byte MAP_BATTLE_SCENE_NORMAL

