
BattleFrontier_RankingHall_Text_ExplainRankingHall:
	.string "Voici le HALL DE CLASSEMENT.\p"
	.string "Ici, nous immortalisons les DRESSEURS\n"
	.string "qui ont obtenu les meilleurs résultats\l"
	.string "dans la ZONE DE COMBAT.$"

BattleFrontier_RankingHall_Text_DomePikeFactoryRecords:
	.string "Records du DOME DE COMBAT, du REPTILE\n"
	.string "DE COMBAT et de l’USINE DE COMBAT.$"

BattleFrontier_RankingHall_Text_PalaceArenaPyramidRecords:
	.string "Records du PALACE DE COMBAT, du DOJO\n"
	.string "DE COMBAT et de la PYRAMIDE DE COMBAT.$"

BattleFrontier_RankingHall_Text_IsYourNameOnThisList:
	.string "Salut, ton nom est sur la liste?$"

BattleFrontier_RankingHall_Text_WowThatsSuper:
	.string "La chance!!!\n"
	.string "Moi, il faut que je m’entraîne plus!$"

BattleFrontier_RankingHall_Text_WorkHarderIfYouSawFriendsName:
	.string "Ah oui?\p"
	.string "Si tu voyais le nom de tes amis ici, tu\n"
	.string "ferais sûrement plus d’efforts!$"

BattleFrontier_RankingHall_Text_MyNamesNotUpThere:
	.string "Hum…\n"
	.string "Y a pas mon nom…\p"
	.string "Faut dire que j’ai participé à aucun\n"
	.string "défi, donc c’est plutôt normal…$"