
MossdeepCity_SpaceCenter_2F_Text_MossdeepIdealForRockets:
	.string "A ALGATIA, le temps est souvent\n"
	.string "ensoleillé et les vents sont stables.\p"
	.string "C’est l’endroit idéal pour lancer des\n"
	.string "fusées.$"

MossdeepCity_SpaceCenter_2F_Text_WhyWouldMagmaStealRocketFuel:
	.string "Mais pourquoi la TEAM MAGMA veut\n"
	.string "nous voler notre carburant?$"

MossdeepCity_SpaceCenter_2F_Text_WouldveLikedToBeAstronaut:
	.string "Si j’avais été un peu plus jeune,\n"
	.string "j’aurais bien aimé être astronaute…\p"
	.string "Non… Il n’est pas trop tard!\n"
	.string "Je vais essayer!$"

MossdeepCity_SpaceCenter_2F_Text_MagmaCantGetAwayWithThis:
	.string "Si la TEAM MAGMA vole notre carburant,\n"
	.string "je ne pourrai jamais aller dans l’espace!\p"
	.string "On ne peut pas les laisser partir\n"
	.string "comme ça!$"

MossdeepCity_SpaceCenter_2F_Text_WishOrdinaryPeopleCouldGoIntoSpace:
	.string "J’espère qu’un jour, tout le monde\n"
	.string "pourra aller dans l’espace…$"

MossdeepCity_SpaceCenter_2F_Text_DoesMagmaWantToGoToSpace:
	.string "Est-ce que la TEAM MAGMA souhaite\n"
	.string "également aller dans l’espace?$"

MossdeepCity_SpaceCenter_2F_Text_YoureOutnumberedTakeUsOn:
	.string "C’est quoi ton problème?\p"
	.string "Tu es à un contre trois mais tu veux\n"
	.string "quand même te battre?$"

MossdeepCity_SpaceCenter_2F_Text_GoodAnswer:
	.string "Bonne réponse! Tu n’es pas aussi\n"
	.string "stupide que je pensais.$"

MossdeepCity_SpaceCenter_2F_Text_Grunt5Intro:
	.string "Plutôt téméraire à ce que je vois…\n"
	.string "OK, à moi l’honneur alors!$"

MossdeepCity_SpaceCenter_2F_Text_Grunt5Defeat:
	.string "J’ai perdu!\n"
	.string "Mais…$"

MossdeepCity_SpaceCenter_2F_Text_Grunt6Intro:
	.string "Il est trop tôt pour te réjouir!\n"
	.string "Je suis le suivant.$"

MossdeepCity_SpaceCenter_2F_Text_Grunt6Defeat:
	.string "J’ai perdu aussi!\n"
	.string "Mais…$"

MossdeepCity_SpaceCenter_2F_Text_Grunt7Intro:
	.string "J’imagine que tu souhaites faire\n"
	.string "une pause. Mais ne compte pas dessus.$"

MossdeepCity_SpaceCenter_2F_Text_Grunt7Defeat:
	.string "On aurait dû faire une pause…\n"
	.string "On aurait vraiment dû…$"

MossdeepCity_SpaceCenter_2F_Text_Grunt6PostBattle:
	.string "On était trois, et regarde le résultat…$"

MossdeepCity_SpaceCenter_2F_Text_Grunt7PostBattle:
	.string "Perdre à trois contre un…\n"
	.string "On est trois fois plus ridicules.$"

MossdeepCity_SpaceCenter_2F_Text_Grunt5PostBattle:
	.string "Je me demande si on est vraiment\n"
	.string "utiles à notre chef…$"

MossdeepCity_SpaceCenter_2F_Text_WellTakeCareOfYou:
	.string "Héhéhé!\p"
	.string "On est venus jusqu’ici pour prendre le\n"
	.string "carburant, et tu es encore dans nos\l"
	.string "pattes!\p"
	.string "Si tu veux vraiment nous gêner, on va\n"
	.string "s’occuper définitivement de toi!$"

MossdeepCity_SpaceCenter_2F_Text_MaxieDontInterfere:
	.string "MAX: Hors de mon chemin!\n"
	.string "N’essaie même pas d’intervenir!$"

MossdeepCity_SpaceCenter_2F_Text_StevenWhyStealRocketFuel:
	.string "PIERRE: TEAM MAGMA…\p"
	.string "Pourquoi voulez-vous nous voler le\n"
	.string "carburant de notre fusée?$"

MossdeepCity_SpaceCenter_2F_Text_MaxieUseFuelToEruptVolcano:
	.string "MAX: Ha ha ha… Puisque tu es si\n"
	.string "curieux, tu mérites une explication.\p"
	.string "Nous voulons tout déverser dans le\n"
	.string "MONT CHIMNEE!\p"
	.string "GROUDON parti, nous n’avons plus\n"
	.string "besoin de cette montagne!\p"
	.string "Alors nous allons utiliser le carburant\n"
	.string "pour créer une énorme éruption!\p"
	.string "Ça va être terrible!$"

MossdeepCity_SpaceCenter_2F_Text_StevenAreYouReadyToBattle:
	.string "PIERRE: {PLAYER}{KUN}!\n"
	.string "Tu vas m’aider?\p"
	.string "Affrontons-les ensemble!\n"
	.string "On y va maintenant?$"

MossdeepCity_SpaceCenter_2F_Text_StevenHurryGetReadyQuickly:
	.string "PIERRE: Allez, dépêche-toi!\n"
	.string "Prépare-toi vite!$"

MossdeepCity_SpaceCenter_2F_Text_JustWantToExpandLand:
	.string "Tout ce que je souhaite…\n"
	.string "C’est étendre la surface de la terre…$"

MossdeepCity_SpaceCenter_Text_TabithaDefeat:
	.string "Je suis avec notre leader…$"

MossdeepCity_SpaceCenter_2F_Text_MaxieWeFailedIsAquaAlsoMisguided:
	.string "MAX: Nous n’arriverons pas à faire\n"
	.string "entrer le volcan en éruption…\p"
	.string "Nous n’avons pas réussi à contrôler\n"
	.string "GROUDON après l’avoir réveillé…\p"
	.string "Aurions-nous tort de vouloir\n"
	.string "étendre la terre?\p"
	.string "… … … … … …\n"
	.string "… … … … … …\p"
	.string "Si…\n"
	.string "Si nous, la TEAM MAGMA, avons tort…\l"
	.string "… … … … … …\p"
	.string "Alors que penser de la TEAM AQUA?$"

MossdeepCity_SpaceCenter_2F_Text_MaxieWeWillGiveUp:
	.string "MAX: Très bien…\n"
	.string "Nous allons vous laisser le carburant.\p"
	.string "Il y a des choses plus importantes\n"
	.string "auxquelles je dois penser…$"

MossdeepCity_SpaceCenter_2F_Text_StevenThankYouComeSeeMeAtHome:
	.string "PIERRE: Pfiuu, on a eu chaud!\n"
	.string "Merci, {PLAYER}{KUN}!\p"
	.string "Je voudrais te donner quelque chose\n"
	.string "pour te remercier de ton aide.\p"
	.string "Passe me voir chez moi plus tard.\p"
	.string "Ah oui, je n’habite pas à MEROUVILLE,\n"
	.string "mais bien ici, sur cette île.$"
