
BattleFrontier_Lounge6_Text_WouldYouLikeToTrade:
	.string "Mon POKéMON est un {STR_VAR_2}.\n"
	.string "Tu connais?\l"
	.string "C’est assez mignon et plutôt joli.\p"
	.string "Celui-là, je serais fière de l’échanger!\p"
	.string "Tu veux échanger un {STR_VAR_1} contre\n"
	.string "mon {STR_VAR_2}?$"

BattleFrontier_Lounge6_Text_PromiseIllBeGoodToIt:
	.string "Oh, c’est adorable!\n"
	.string "Merci!\l"
	.string "Je vais bien m’en occuper!\p"
	.string "Dis, j’espère que tu prendras bien soin\n"
	.string "de mon {STR_VAR_2}!$"

BattleFrontier_Lounge6_Text_DontTradeForAnythingButMon:
	.string "Oh, je suis désolée!\n"
	.string "Je ferai l’échange uniquement contre un\l"
	.string "{STR_VAR_1}.$"

BattleFrontier_Lounge6_Text_WellThatsFineToo:
	.string "Oh, tu ne veux pas?\n"
	.string "Bon, pas de problème.\l"
	.string "Reviens quand tu veux.$"

BattleFrontier_Lounge6_Text_SkittySoMuchCuterThanImagined:
	.string "Hi, hi!\n"
	.string "Un SKITTY, c’est encore plus mignon\l"
	.string "que je ne le pensais!$"
