name: 💾 Other errors 🖥️
description: Everything else that doesn't fit in the above categories.
labels: ["bug", "status: unconfirmed"]
body:
  - type: markdown
    attributes:
      value: |
        Please fill in all required fields with as many details as possible.
  - type: textarea
    id: description
    attributes:
      label: Description
      description: |
        Describe the issue you are experiencing.
        Attach images/videos if possible.
      placeholder: |
        Please enter a description of the issue. Here you can also attach log screenshots, gifs or a video
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of pokeemerald-expansion are you using as a base?
      options:
        - 1.6.1 (Default)
        - upcoming (Edge)
        - 1.6.0
        - 1.5.3
        - 1.5.2
        - 1.5.1
        - 1.5.0
        - pre-1.5.0
    validations:
      required: true
  - type: input
    id: upcomingversion
    attributes:
      label: Upcoming Version
      description: If you're using the upcoming branch, please specify what was the commit hash you pulled from.
    validations:
      required: false
  - type: input
    id: contact
    attributes:
      label: Discord contact info
      description: Provide your Discord tag here so we can contact you in case we need more details. Be sure to join our server ([here](https://discord.gg/6CzjAG6GZk)).
      placeholder: ex. Lunos#4026
    validations:
      required: false
