
EverGrandeCity_ChampionsRoom_Text_IntroSpeech:
	.string "MARC: Bienvenue, {PLAYER}{KUN}.\p"
	.string "A propos de l’incident d’ATALANOPOLIS…\n"
	.string "Réussir à mettre un terme à cette\l"
	.string "crise par tes propres moyens…\p"
	.string "Oups!\p"
	.string "Ça ne serait pas juste de dire que\n"
	.string "tout le mérite te revient.\p"
	.string "Tu as surmonté la situation grâce aux\n"
	.string "liens que tu as avec tes POKéMON.\p"
	.string "Nous, DRESSEURS, prenons soin de nos\n"
	.string "POKéMON en leur donnant des objets\l"
	.string "et en leur apprenant des capacités.\p"
	.string "Mais nous apprenons également\n"
	.string "énormément de nos POKéMON.\p"
	.string "Et c’est ici que tu peux tester le\n"
	.string "résultat de tous tes efforts, face à\l"
	.string "d’autres DRESSEURS et leurs POKéMON.\p"
	.string "Maintenant!\p"
	.string "Qui de nous deux va pouvoir se vanter\n"
	.string "d’avoir les meilleurs POKéMON d’HOENN?\p"
	.string "Nous allons le savoir tout de suite!$"

EverGrandeCity_ChampionsRoom_Text_Defeat:
	.string "Tu as réussi à me battre, moi, le\n"
	.string "MAITRE POKéMON…\p"
	.string "Beau travail.\n"
	.string "Tu as combattu de façon exaspérante,\l"
	.string "mais cependant glorieuse et élégante!\p"
	.string "Gloire à toi, {PLAYER}{KUN}!\p"
	.string "Tu es un DRESSEUR POKéMON\n"
	.string "de grande classe!$"

EverGrandeCity_ChampionsRoom_Text_PostBattleSpeech:
	.string "MARC: Les POKéMON que tu as\n"
	.string "envoyés au combat…\p"
	.string "Par moments, ils dansaient comme\n"
	.string "une brise de printemps, à d’autres,\l"
	.string "ils frappaient comme l’éclair.\p"
	.string "Bien que de manière assurée, tu\n"
	.string "as su combattre élégamment!\p"
	.string "Même moi, je fus ébloui par tant\n"
	.string "de maestria!\p"
	.string "Tu te trouves désormais au\n"
	.string "sommet de la LIGUE POKéMON.\p"
	.string "Je te proclame maintenant le\n"
	.string "nouveau…$"

EverGrandeCity_ChampionsRoom_Text_MayAdvice:
	.string "FLORA: {PLAYER}{KUN}!\p"
	.string "Voici un petit conseil avant que tu\n"
	.string "n’affrontes le MAITRE…$"

EverGrandeCity_ChampionsRoom_Text_MayItsAlreadyOver:
	.string "FLORA: Hum? Quoi, quoi, quoi?\p"
	.string "{PLAYER}{KUN}…\n"
	.string "Il se pourrait que…\p"
	.string "C’est déjà fait?$"

EverGrandeCity_ChampionsRoom_Text_BrendanAdvice:
	.string "BRICE: {PLAYER}!\p"
	.string "Tu veux un conseil avant d’affronter\n"
	.string "le MAITRE…?$"

EverGrandeCity_ChampionsRoom_Text_BrendanYouveWon:
	.string "BRICE: {PLAYER}…\p"
	.string "Serais-tu en train de me dire…\n"
	.string "que tu as battu le MAITRE?$"

EverGrandeCity_ChampionsRoom_Text_BirchArriveRatePokedex:
	.string "PROF. SEKO: Tu as vu?\n"
	.string "Qu’est-ce que je t’avais dit, {RIVAL}?\p"
	.string "Ne t’avais-je pas dit de ne pas te faire\n"
	.string "de soucis pour {PLAYER}{KUN}?\p"
	.string "… … … … … … … …\n"
	.string "{PLAYER}{KUN}, tu as enfin réussi!\p"
	.string "Quand j’ai su que tu avais battu ton\n"
	.string "propre père à l’ARENE de CLEMENTI,\l"
	.string "je me suis dit que tu avais une chance…\p"
	.string "Mais réaliser que tu es maintenant\n"
	.string "le MAITRE!\p"
	.string "Ah, oui!\p"
	.string "Qu’est-il advenu de ton POKéDEX?\n"
	.string "Laisse-moi voir.$"

EverGrandeCity_ChampionsRoom_Text_BirchCongratulations:
	.string "PROF. SEKO: Quoi qu’il en soit,\n"
	.string "félicitations!\p"
	.string "Entre fièrement dans l’ultime pièce!$"

EverGrandeCity_ChampionsRoom_Text_WallaceComeWithMe:
	.string "MARC: {PLAYER}{KUN}…\p"
	.string "Je vais donc terminer ma phrase.\p"
	.string "Le nouveau MAITRE!\p"
	.string "Suis-moi.$"

EverGrandeCity_ChampionsRoom_Text_WallaceWaitOutside:
	.string "MARC: Je suis désolé, mais…\p"
	.string "A partir d’ici, seuls les DRESSEURS\n"
	.string "devenus MAITRES peuvent entrer.\p"
	.string "Tu vas devoir attendre à l’extérieur\n"
	.string "avec le PROFESSEUR.$"

EverGrandeCity_ChampionsRoom_Text_MayCongratulations:
	.string "FLORA: Mais… Mais…\p"
	.string "… … … … … … … …\n"
	.string "… … … … … … … …\p"
	.string "Je plaisante! Pas de problème!\n"
	.string "C’est le règlement!\p"
	.string "{PLAYER}{KUN}!\n"
	.string "Sincères félicitations!$"

EverGrandeCity_ChampionsRoom_Text_BrendanCongratulations:
	.string "BRICE: … … … … … …\n"
	.string "… … … … … … … …\p"
	.string "Si c’est le règlement…\p"
	.string "{PLAYER}, c’est bien!\n"
	.string "Félicitations!$"

