
EverGrandeCity_ChampionsRoom_Text_IntroSpeech:
	.string "ADRIANO: Ti do il benvenuto,\n"
	.string "{PLAYER}{KUN}.\p"
	.string "Riguardo a CENERIDE…\n"
	.string "Hai fatto un lavoro superbo. Hai messo\l"
	.string "fine alla crisi senza l’aiuto di nessuno.\p"
	.string "Oops!\p"
	.string "Non è del tutto corretto dire\n"
	.string "senza l’aiuto di nessuno.\p"
	.string "Hai superato la crisi insieme alla\n"
	.string "tua squadra di POKéMON.\p"
	.string "Noi ALLENATORI alleviamo i\n"
	.string "POKéMON, gli diamo strumenti e gli\l"
	.string "insegniamo nuove tecniche di lotta.\p"
	.string "Tuttavia, anche noi impariamo\n"
	.string "moltissime cose dai POKéMON.\p"
	.string "Questo è il luogo dove puoi\n"
	.string "confrontarti con altri come te e\l"
	.string "mettere alla prova la tua abilità.\p"
	.string "Adesso!\p"
	.string "Chi sa danzare più elegantemente\n"
	.string "con i propri POKéMON nella\l"
	.string "regione di HOENN?\p"
	.string "È giunto il momento di scoprirlo!$"

EverGrandeCity_ChampionsRoom_Text_Defeat:
	.string "Io, il CAMPIONE, sono stato sconfitto…\p"
	.string "Un lavoro eccellente.\n"
	.string "Un’eleganza… quasi esasperante.\l"
	.string "Al tempo stesso semplicemente sublime!\p"
	.string "Gloria a te, {PLAYER}{KUN}!\p"
	.string "Sei un ALLENATORE di POKéMON\n"
	.string "di grande nobiltà d’animo!$"

EverGrandeCity_ChampionsRoom_Text_PostBattleSpeech:
	.string "ADRIANO: I POKéMON che hai fatto\n"
	.string "lottare…\p"
	.string "a volte danzavano leggiadri come la\n"
	.string "brezza del mattino e a volte colpivano\l"
	.string "con l’intensità del fulmine.\p"
	.string "Li hai guidati con un’eleganza\n"
	.string "sopraffina e con incredibile fermezza.\p"
	.string "Sono stato quasi abbagliato dalla\n"
	.string "tua maestria.\p"
	.string "Ora hai raggiunto la gloriosa vetta\n"
	.string "della LEGA POKéMON.\p"
	.string "Ti conferisco il titolo di…$"

EverGrandeCity_ChampionsRoom_Text_MayAdvice:
	.string "VERA: {PLAYER}{KUN}!\p"
	.string "Eccoti qualche utile consiglio prima\n"
	.string "di sfidare il CAMPIONE…$"

EverGrandeCity_ChampionsRoom_Text_MayItsAlreadyOver:
	.string "VERA: Uh? Che cosa?\p"
	.string "{PLAYER}{KUN}…\n"
	.string "Non può essere vero…\l"
	.string "È già tutto finito?$"

EverGrandeCity_ChampionsRoom_Text_BrendanAdvice:
	.string "BRENDON: {PLAYER}!\p"
	.string "Vuoi qualche dritta prima della\n"
	.string "supersfida con il CAMPIONE…?$"

EverGrandeCity_ChampionsRoom_Text_BrendanYouveWon:
	.string "BRENDON: {PLAYER}…\p"
	.string "Non mi dirai…\n"
	.string "che hai già sfidato il CAMPIONE?$"

EverGrandeCity_ChampionsRoom_Text_BirchArriveRatePokedex:
	.string "PROF. BIRCH: Ecco!\n"
	.string "Proprio come pensavo, {RIVAL}!\p"
	.string "Non ti avevo detto che {PLAYER}{KUN}\n"
	.string "se la sarebbe cavata benissimo?\p"
	.string "… … … … … … … …\n"
	.string "{PLAYER}{KUN}, ce l’hai fatta.\p"
	.string "Quando ho sentito che avevi sconfitto\n"
	.string "addirittura tuo padre nella PALESTRA di\l"
	.string "PETALIPOLI, ho capito che forse\l"
	.string "c’era una possibilità…\p"
	.string "Oggi questo presentimento è diventato\n"
	.string "realtà. Sei il CAMPIONE!\p"
	.string "Ah, dimenticavo!\p"
	.string "A che punto è il tuo POKéDEX?\n"
	.string "Fammi vedere.$"

EverGrandeCity_ChampionsRoom_Text_BirchCongratulations:
	.string "PROF. BIRCH: Congratulazioni vivissime!\p"
	.string "Ora entra a testa alta nella sala\n"
	.string "finale!$"

EverGrandeCity_ChampionsRoom_Text_WallaceComeWithMe:
	.string "ADRIANO: {PLAYER}{KUN}…\p"
	.string "O meglio…\p"
	.string "Nuovo CAMPIONE!\p"
	.string "Seguimi.$"

EverGrandeCity_ChampionsRoom_Text_WallaceWaitOutside:
	.string "ADRIANO: Spiacente, ma…\p"
	.string "solo gli ALLENATORI CAMPIONI\n"
	.string "possono procedere oltre.\p"
	.string "Devi aspettare fuori con\n"
	.string "il PROF. BIRCH.$"

EverGrandeCity_ChampionsRoom_Text_MayCongratulations:
	.string "VERA: Uffi…\p"
	.string "… … … … … … … …\n"
	.string "… … … … … … … …\p"
	.string "Scherzo, ok!\n"
	.string "Le regole sono regole!\p"
	.string "{PLAYER}{KUN}!\n"
	.string "Congratulazioni vivissime!$"

EverGrandeCity_ChampionsRoom_Text_BrendanCongratulations:
	.string "BRENDON: Cooosa?! … … … … …\n"
	.string "… … … … … … … …\p"
	.string "Capisco, non sono ammessi\n"
	.string "strappi alla regola!\p"
	.string "{PLAYER}, sei grande!\n"
	.string "Congratulazioni!$"

