
BattleFrontier_BattleFactoryLobby_Text_WelcomeForSingleBattle:
	.string "¡Aquí ponemos a prueba el saber\n"
	.string "de los ENTRENADORES!\p"
	.string "¡Te doy la más calurosa bienvenida\n"
	.string "a la FÁBRICA BATALLA!\p"
	.string "Yo soy el guía del TORNEO de COMBATES\n"
	.string "con TRUEQUE INDIVIDUALES.$"

BattleFrontier_BattleFactoryLobby_Text_TakeSinglesChallenge:
	.string "¿Participas en el TORNEO de COMBATES\n"
	.string "con TRUEQUE INDIVIDUALES?$"

BattleFrontier_BattleFactoryLobby_Text_ExplainSinglesChallenge:
	.string "En el TORNEO de COMBATES con TRUEQUE\n"
	.string "INDIVIDUALES se disputan COMBATES\l"
	.string "con POKéMON prestados.\p"
	.string "Primero, debes elegir los tres POKéMON\n"
	.string "con los que vas a comenzar el torneo.\p"
	.string "Con esos POKéMON prestados, debes\n"
	.string "luchar en el primer COMBATE INDIVIDUAL.\p"
	.string "Si ganas a tu rival, tendrás derecho a\n"
	.string "un trueque: podrás elegir uno de sus\l"
	.string "POKéMON y cambiárselo por uno tuyo.\p"
	.string "Repite este ciclo de combate y trueque\n"
	.string "y, si logras ganar siete veces seguidas,\l"
	.string "conseguirás PUNTOS de BATALLA.\p"
	.string "Si quieres interrumpir el desafío,\n"
	.string "no olvides guardar antes la partida.\p"
	.string "Si no la guardas, se te descalificará.$"

BattleFrontier_BattleFactoryLobby_Text_LookForwardToNextVisit:
	.string "Esperamos que vuelvas\n"
	.string "pronto por aquí.$"

BattleFrontier_BattleFactoryLobby_Text_WhichLevelMode:
	.string "¿En qué nivel deseas participar?\n"
	.string "¿Nivel 50 o nivel libre?$"

BattleFrontier_BattleFactoryLobby_Text_OkayToSaveBeforeChallenge:
	.string "Antes de comenzar,\n"
	.string "tengo que guardar la partida, ¿vale?$"

@ Unused
BattleFrontier_BattleFactoryLobby_Text_WillHoldMonsForSafekeeping:
	.string "Okay, I will hold your POKéMON for\n"
	.string "safekeeping while you compete.$"

BattleFrontier_BattleFactoryLobby_Text_StepThisWay:
	.string "Pasa por aquí.$"

BattleFrontier_BattleFactoryLobby_Text_ReturnMonsSaveResults:
	.string "¡Gracias por participar!\p"
	.string "Voy a devolverte tus POKéMON\n"
	.string "a cambio de los que te prestamos.\p"
	.string "Y voy a guardar también tus resultados.\n"
	.string "Un momento, por favor.$"

@ Unused
BattleFrontier_BattleFactoryLobby_Text_ReturnMons:
	.string "I will return your POKéMON in exchange\n"
	.string "for our rental POKéMON.$"

BattleFrontier_BattleFactoryLobby_Text_CongratsSevenWins:
	.string "¡Bravo! ¡Has ganado siete encuentros\n"
	.string "seguidos de COMBATE con TRUEQUE!$"

@ Unused
BattleFrontier_BattleFactoryLobby_Text_AwardBattlePointsForStreak:
	.string "In recognition of your 7-win streak,\n"
	.string "we award you these Battle Point(s).$"

@ Unused
BattleFrontier_BattleFactoryLobby_Text_MaxBattlePoints:
	.string "Oh, oh, oh!\p"
	.string "Your Battle Points are maxed.\p"
	.string "Please come back after using\n"
	.string "some Battle Points.$"

BattleFrontier_BattleFactoryLobby_Text_WaitingForYouToResume:
	.string "¡Te estábamos esperando!\p"
	.string "Antes de continuar el desafío,\n"
	.string "debo guardar la partida.$"

BattleFrontier_BattleFactoryLobby_Text_DidntSaveBeforeQuitting:
	.string "Siento decírtelo, pero no guardaste\n"
	.string "la partida la última vez que jugaste.\p"
	.string "Así que se te ha descalificado.\n"
	.string "Lo siento.$"

@ Unused
BattleFrontier_BattleFactoryLobby_Text_WellReturnMons:
	.string "We’ll return your personal POKéMON.$"

@ Unused
BattleFrontier_BattleFactoryLobby_Text_ReceivedPrizeItem:
	.string "{PLAYER} received the prize\n"
	.string "{STR_VAR_1}.$"

BattleFrontier_BattleFactoryLobby_Text_WelcomeForDoubleBattle:
	.string "¡Aquí ponemos a prueba el saber\n"
	.string "de los ENTRENADORES!\p"
	.string "¡Te doy la más calurosa bienvenida\n"
	.string "a la FÁBRICA BATALLA!\p"
	.string "Yo soy el guía del TORNEO de COMBATES\n"
	.string "con TRUEQUE DOBLES.$"

BattleFrontier_BattleFactoryLobby_Text_TakeDoublesChallenge:
	.string "¿Participas en el TORNEO de COMBATES\n"
	.string "con TRUEQUE DOBLES?$"

BattleFrontier_BattleFactoryLobby_Text_ExplainDoublesChallenge:
	.string "En el TORNEO de COMBATES con TRUEQUE\n"
	.string "DOBLES se disputan COMBATES\l"
	.string "con POKéMON prestados.\p"
	.string "Primero, debes elegir los tres POKéMON\n"
	.string "con los que vas a comenzar el torneo.\p"
	.string "Con esos POKéMON prestados, debes\n"
	.string "luchar en el primer COMBATE DOBLE.\p"
	.string "Si ganas a tu rival, tendrás derecho a\n"
	.string "un trueque: podrás elegir uno de sus\l"
	.string "POKéMON y cambiárselo por uno tuyo.\p"
	.string "Repite este ciclo de combate y trueque\n"
	.string "y, si logras ganar siete veces seguidas,\l"
	.string "conseguirás PUNTOS de BATALLA.\p"
	.string "Si quieres interrumpir el desafío,\n"
	.string "no olvides guardar antes la partida.\p"
	.string "Si no la guardas, se te descalificará.$"

BattleFrontier_BattleFactoryLobby_Text_CongratsForDefeatingHead:
	.string "¡Enhorabuena por tu victoria sobre\n"
	.string "el JEFE de la FÁBRICA\l"
	.string "y por tus siete triunfos consecutivos!$"

BattleFrontier_BattleFactoryLobby_Text_AwardBattlePoints:
	.string "Tu enorme saber y la agudeza\n"
	.string "de tu mente merecen ser reconocidos\l"
	.string "con PUNTOS de BATALLA.$"

BattleFrontier_BattleFactoryLobby_Text_ExchangeMonsAndSave:
	.string "Voy a cambiar tus POKéMON por\n"
	.string "los POKéMON que te prestamos.\p"
	.string "Y de paso guardaré los resultados.\n"
	.string "Un momento, por favor.$"

BattleFrontier_BattleFactoryLobby_Text_RecordLastMatch:
	.string "¿Quieres que tu último combate\n"
	.string "en la FÁBRICA BATALLA sea grabado\l"
	.string "en tu PASE del FRENTE?$"

BattleFrontier_BattleFactoryLobby_Text_NeedKnowledgeOfMonsMoves:
	.string "¡Hola! \n"
	.string "¿Qué tal?\p"
	.string "Seguro que crees que aquí los combates\n"
	.string "están chupados porque no se necesita\l"
	.string "un equipo experto de POKéMON, ¿verdad?\p"
	.string "Pues yo no estaría tan segura.\p"
	.string "Si no tienes suficientes conocimientos\n"
	.string "sobre los POKéMON y sus movimientos,\l"
	.string "te va a ser difícil ganar.$"

BattleFrontier_BattleFactoryLobby_Text_SwappedForWeakMon:
	.string "Cambié un POKéMON malo por otro peor.\n"
	.string "¡Creí que era justo el que necesitaba!\p"
	.string "Me han dado una buena tunda…$"

BattleFrontier_BattleFactoryLobby_Text_NeedToCheckOpponentsMons:
	.string "Las cosas no me han ido muy bien,\n"
	.string "que digamos.\p"
	.string "Es importante ver cómo se portan\n"
	.string "los POKéMON de tu rival en combate\l"
	.string "para saber si merecen la pena o no.$"

BattleFrontier_BattleFactoryLobby_Text_CantFigureOutStaffHints:
	.string "¿Sabías que los guías que trabajan\n"
	.string "aquí te dan pistas sobre los rivales?\p"
	.string "Pues yo no sé si es cosa mía,\n"
	.string "pero no pillo ni una, oye…$"

@ Unused
BattleFrontier_BattleFactoryLobby_Text_RentalMonsAreVaried:
	.string "Like, I’m really tough, but I get bored\n"
	.string "really easily, so I just kept swapping\l"
	.string "and battling over and over.\p"
	.string "So anyway, when I kept entering\n"
	.string "Battle Swap events, I noticed they\l"
	.string "varied the rental POKéMON.$"

BattleFrontier_BattleFactoryLobby_Text_RulesAreListed:
	.string "Son las reglas del COMBATE con TRUEQUE.$"

BattleFrontier_BattleFactoryLobby_Text_ReadWhichHeading:
	.string "¿Qué capítulo quieres leer?$"

BattleFrontier_BattleFactoryLobby_Text_ExplainBasicRules:
	.string "En los enfrentamientos de COMBATE\n"
	.string "con TRUEQUE, sólo se usan tres POKéMON.\p"
	.string "Al tomar prestados o trocar POKéMON,\n"
	.string "hay que tener en cuenta que el equipo\l"
	.string "no debe tener dos POKéMON iguales.$"

BattleFrontier_BattleFactoryLobby_Text_ExplainSwapPartnerRules:
	.string "Sólo puedes cambiarle un POKéMON\n"
	.string "al ENTRENADOR al que acabas de vencer.\p"
	.string "Y sólo puedes elegir entre los POKéMON\n"
	.string "que haya usado ese ENTRENADOR.$"

BattleFrontier_BattleFactoryLobby_Text_ExplainSwapNumberRules:
	.string "Después de cada victoria, podrás\n"
	.string "cambiar uno de tus POKéMON por\l"
	.string "uno de los del ENTRENADOR derrotado.\p"
	.string "Con el séptimo ENTRENADOR\n"
	.string "no podrás hacer trueque de POKéMON.$"

BattleFrontier_BattleFactoryLobby_Text_ExplainSwapNotesRules:
	.string "A la hora de trocar POKéMON, debes\n"
	.string "tener en cuenta dos cosas.\p"
	.string "Primera: en el momento del trueque,\n"
	.string "no podrás ver las características\l"
	.string "del POKéMON que vas a recibir.\p"
	.string "Segunda: los POKéMON de tu equipo\n"
	.string "se mostrarán siguiendo el orden\l"
	.string "en el que los elegiste.\p"
	.string "Ese orden no se altera aunque\n"
	.string "luego realices trueques.$"

BattleFrontier_BattleFactoryLobby_Text_ExplainOpenLvRules:
	.string "En el nivel libre, tanto los POKéMON\n"
	.string "que recibes prestados como los POKéMON\l"
	.string "del rival son todos del nivel 100.$"
