Route14_Frlg_MapScripts::
	.byte 0

Route14_EventScript_RouteSign::
	msgbox Route14_Text_RouteSign, MSGBOX_SIGN
	end

Route14_Text_CarterIntro::
	.string "You need to use TMs to teach good\n"
	.string "moves to POKéMON.$"

Route14_Text_CarterDefeat::
	.string "Not good enough quite yet.$"

Route14_Text_CarterPostBattle::
	.string "You have some HMs, right? POKéMON\n"
	.string "can't forget those moves easily.$"

Route14_Text_MitchIntro::
	.string "My bird POKéMON should be ready\n"
	.string "for battle.$"

Route14_Text_MitchDefeat::
	.string "Not ready yet!$"

Route14_Text_MitchPostBattle::
	.string "My bird POKéMON need to learn\n"
	.string "better moves.$"

Route14_Text_BeckIntro::
	.string "They have TMs on sale at the\n"
	.string "CELADON DEPT. STORE.\p"
	.string "TMs aren't really rare, but not\n"
	.string "many people have HMs.$"

Route14_Text_BeckDefeat::
	.string "Aww, bummer!$"

Route14_Text_BeckPostBattle::
	.string "Try teaching POKéMON a move that's\n"
	.string "the same type as it.\p"
	.string "That apparently boosts the power\n"
	.string "of the move.$"

Route14_Text_MarlonIntro::
	.string "Have you taught your bird POKéMON\n"
	.string "how to FLY?\p"
	.string "You'll be able to soar with it into\n"
	.string "the sky!$"

Route14_Text_MarlonDefeat::
	.string "Shot down in flames!$"

Route14_Text_MarlonPostBattle::
	.string "Bird POKéMON are my one true love.\n"
	.string "I don't want to raise anything else.$"

Route14_Text_DonaldIntro::
	.string "Have you heard the legend of the\n"
	.string "winged mirages?$"

Route14_Text_DonaldDefeat::
	.string "Why?\n"
	.string "Why'd I lose?$"

Route14_Text_DonaldPostBattle::
	.string "Well, the winged mirages are the\n"
	.string "legendary bird POKéMON.\p"
	.string "There are three of them: ARTICUNO,\n"
	.string "ZAPDOS, and MOLTRES.$"

Route14_Text_BennyIntro::
	.string "I'm not into it, but okay.\n"
	.string "Let's go!$"

Route14_Text_BennyDefeat::
	.string "I knew it!$"

Route14_Text_BennyPostBattle::
	.string "Winning, losing… It's insignificant\n"
	.string "under this huge sky.$"

Route14_Text_LukasIntro::
	.string "C'mon, c'mon.\n"
	.string "Let's go, let's go, let's go!$"

Route14_Text_LukasDefeat::
	.string "Arrg!\n"
	.string "Lost! Get lost!$"

Route14_Text_LukasPostBattle::
	.string "What, what, what?\n"
	.string "What do you want still?$"

Route14_Text_IsaacIntro::
	.string "I need to burn some time.\n"
	.string "Shut up and battle.$"

Route14_Text_IsaacDefeat::
	.string "What?\n"
	.string "You!?$"

Route14_Text_IsaacPostBattle::
	.string "Raising POKéMON is a drag, man.$"

Route14_Text_GeraldIntro::
	.string "We ride out here because of the\n"
	.string "wide-open spaces.$"

Route14_Text_GeraldDefeat::
	.string "Wipeout!$"

Route14_Text_GeraldPostBattle::
	.string "It's cool you made your POKéMON so\n"
	.string "strong.\p"
	.string "Might is right!\n"
	.string "And you know it!$"

Route14_Text_MalikIntro::
	.string "POKéMON battle?\n"
	.string "Cool! Rumble!$"

Route14_Text_MalikDefeat::
	.string "Blown away!$"

Route14_Text_MalikPostBattle::
	.string "You know who'd win, you and me\n"
	.string "one-on-one!$"

Route14_Text_RouteSign::
	.string "ROUTE 14\n"
	.string "West to FUCHSIA CITY$"

Route14_Text_KiriIntro::
	.string "KIRI: JAN, let's try really,\n"
	.string "really hard together.$"

Route14_Text_KiriDefeat::
	.string "KIRI: Whimper…\n"
	.string "We lost, didn't we?$"

Route14_Text_KiriPostBattle::
	.string "KIRI: Did we lose because of me?$"

Route14_Text_KiriNotEnoughMons::
	.string "KIRI: We can battle if you have\n"
	.string "two POKéMON.$"

Route14_Text_JanIntro::
	.string "JAN: KIRI, here we go!\n"
	.string "We have to try hard!$"

Route14_Text_JanDefeat::
	.string "JAN: Eeeeh!\n"
	.string "No fair!$"

Route14_Text_JanPostBattle::
	.string "JAN: KIRI, don't cry!\n"
	.string "We'll just try harder next time.$"

Route14_Text_JanNotEnoughMons::
	.string "JAN: You want to battle?\n"
	.string "You don't have enough POKéMON.$"
