
SkyPillar_Outside_Text_DoorIsClosed:
	.string "La puerta está cerrada.$"

SkyPillar_Outside_Text_OpenedDoorToSkyPillar:
	.string "PLUBIO: ¡Vaya, cuánto lo siento!\p"
	.string "¡Salí tan precipitadamente que no me di\n"
	.string "cuenta de que te habías quedado atrás!\p"
	.string "He logrado abrir la puerta\n"
	.string "del PILAR CELESTE.\p"
	.string "¡Vamos allá, {PLAYER}{KUN}!$"

SkyPillar_Outside_Text_EarthquakeNotMomentToWaste:
	.string "PLUBIO: ¡Un terremoto!\p"
	.string "¡No hay un momento que perder!\n"
	.string "¡Debemos apresurarnos!$"

SkyPillar_Outside_Text_SituationGettingWorse:
	.string "PLUBIO: Mmm…\n"
	.string "La situación está empeorando…$"

SkyPillar_Outside_Text_GotToGoBackForSootopolis:
	.string "PLUBIO: Esto no es bueno…\p"
	.string "Las condiciones climáticas se han\n"
	.string "alterado incluso aquí…\p"
	.string "{PLAYER}{KUN}…\p"
	.string "RAYQUAZA debería estar algo\n"
	.string "más arriba.\p"
	.string "Me preocupa ARRECÍPOLIS.\n"
	.string "Voy para allá de nuevo.\p"
	.string "Ahora todo depende de ti.\n"
	.string "¡No nos falles!$"
