
LilycoveCity_ContestLobby_Text_LadyGaveMePokeblockCase:
	.string "Urrà!\p"
	.string "La signora al banco di accettazione\n"
	.string "mi ha dato un contenitore per le {POKEMELLE}!$"

LilycoveCity_ContestLobby_Text_MakePokeblocksDifferentBerries:
	.string "Fai {POKEMELLE} e mettile lì dentro.\p"
	.string "Quando si fa una {POKEMELLA}, tutti devono\n"
	.string "mettere una BACCA differente.$"

LilycoveCity_ContestLobby_Text_YourPokemonSpurredMeToPaint:
	.string "Congratulazioni!\p"
	.string "Ho fatto un dipinto del tuo POKéMON\n"
	.string "per commemorare la sua vittoria…\p"
	.string "L’esibizione del tuo POKéMON è\n"
	.string "stata così fantastica da stimolare\l"
	.string "la mia vena artistica.\l"
	.string "Dai un’occhiata, che ne dici?$"

LilycoveCity_ContestLobby_Text_ShouldITakePaintingToMuseum:
	.string "Che ne pensi? Per me è un lavoro\n"
	.string "proprio ben fatto!\p"
	.string "Un’opera di questo calibro non\n"
	.string "sfigurerebbe in un museo d’arte.\p"
	.string "Uh? Davvero? Un museo d’arte sta\n"
	.string "cercando nuove opere?\p"
	.string "Credi che dovrei portarla lì?$"

LilycoveCity_ContestLobby_Text_IllTakePaintingToMuseum:
	.string "Che cosa? Sul serio? Beh, allora\n"
	.string "la porterò immediatamente!\p"
	.string "Devo trovare un titolo adatto…\p"
	.string "Spero che piaccia e che decidano di\n"
	.string "esporla.\p"
	.string "Per favore controlla che l’abbiano\n"
	.string "accettata. Grazie!$"

LilycoveCity_ContestLobby_Text_TakeMementoOfPainting:
	.string "Oh, dimenticavo!\p"
	.string "Prendi questo, come ricordo dell’opera\n"
	.string "che ho dipinto per il tuo POKéMON.$"

LilycoveCity_ContestLobby_Text_ReceivedARibbon:
	.string "{PLAYER} riceve un FIOCCO.$"

LilycoveCity_ContestLobby_Text_PutTheRibbonOnMon:
	.string "{PLAYER} mette il FIOCCO a {STR_VAR_1}.$"

LilycoveCity_ContestLobby_Text_OkaySeeYou:
	.string "Ok, ci si vede!$"

LilycoveCity_ContestLobby_Text_TakeHomeButIdLikeToTakeToMuseum:
	.string "Oh… beh, allora me la porterò\n"
	.string "a casa…\p"
	.string "Ma ricordati che io vorrei portarla\n"
	.string "al museo d’arte… ok?$"

LilycoveCity_ContestLobby_Text_FineThatsTheWayItIs:
	.string "Oh, beh, se le cose stanno così,\n"
	.string "la appenderò nel soggiorno di casa.\p"
	.string "Cercherò di impegnarmi di più la\n"
	.string "prossima volta. Beh, spero di rivederti.$"

LilycoveCity_ContestLobby_Text_MasterRankHereICome:
	.string "Yuppie! GARE di livello MASTER,\n"
	.string "sto arrivando!\p"
	.string "Il mondo saprà che il mio POKéMON\n"
	.string "prediletto è il più grazioso di tutti!\l"
	.string "È giunto il momento!\l"
	.string "Eheheh!$"

LilycoveCity_ContestLobby_Text_WholeVarietyOfPokemonHere:
	.string "Qui si vedono tanti POKéMON diversi.\p"
	.string "Per questo ogni giorno ci faccio \n"
	.string "una capatina.$"

LilycoveCity_ContestLobby_Text_ContestFeastForEyes:
	.string "Venire alle GARE è molto interessante!\p"
	.string "Ci sono POKéMON che farebbero\n"
	.string "qualsiasi cosa pur di essere ritratti.$"

LilycoveCity_ContestLobby_Text_ToughContestIsExtreme:
	.string "La GARA di GRINTA è il massimo!\p"
	.string "Queste esibizioni di muscoli…\n"
	.string "il sudore dei concorrenti… svengo!$"

LilycoveCity_ContestLobby_Text_LavishedCareOnMon:
	.string "Tutti i giorni ho dato il massimo\n"
	.string "per allenare il mio POKéMON.\p"
	.string "La sua virtù è in rapida ascesa.\n"
	.string "Oggi ho la vittoria in pugno!$"

LilycoveCity_ContestLobby_Text_MadePokeblocksWithFamily:
	.string "Ho fatto {POKEMELLE} con mamma, papà e\n"
	.string "mia sorella. Sono riuscite benissimo!\p"
	.string "Quando si è in tanti le {POKEMELLE} riescono\n"
	.string "più morbide.$"
