
MossdeepCity_Text_WantKingsRockStevenGaveMe:
	.string "MÁXIMO me ha dado esto,\n"
	.string "pero no sé para qué sirve.\p"
	.string "Creo que se llama ROCA del REY.\n"
	.string "¿La quieres?$"

MossdeepCity_Text_YouCanKeepIt:
	.string "¿Y para qué la quieres?\n"
	.string "Mira que la gente es rara…\p"
	.string "Bueno, quédatela, pero no\n"
	.string "se lo digas a MÁXIMO.$"

MossdeepCity_Text_StevensHouseOverThere:
	.string "¡La casa de MÁXIMO está justo ahí!$"

MossdeepCity_Text_WhatToDoWithWeirdRock:
	.string "¡Justamente eso digo yo! ¿Qué se\n"
	.string "puede hacer con una roca rara?$"

MossdeepCity_Text_WailmerWatching:
	.string "Cerca de ALGARIA, puedes ver\n"
	.string "WAILMER salvajes.\p"
	.string "El sitio en cuestión se llama…\n"
	.string "¿Cómo se llama…?\p"
	.string "Puesto…, puesto de algo…\p"
	.string "¡Puesto de observación de WAILMER!$"

MossdeepCity_Text_SpaceCenterReceivedLetter:
	.string "El CENTRO ESPACIAL de esta isla\n"
	.string "ha estado lanzando cohetes enormes.\p"
	.string "Es que andan bastante alborotados\n"
	.string "a causa de una carta que han recibido.$"

MossdeepCity_Text_SpaceCenterLaunchingRockets:
	.string "El CENTRO ESPACIAL de esta isla\n"
	.string "ha estado lanzando cohetes enormes.$"

MossdeepCity_Text_MossdeepTargetedByMagma:
	.string "Un MARINERO me ha dicho que el EQUIPO\n"
	.string "AQUA la ha montado gorda en CALAGUA.\p"
	.string "¡También he oído que alguien\n"
	.string "les ha dado una buena paliza!\p"
	.string "Pero ahora CIUDAD ALGARIA ha pasado\n"
	.string "a ser un objetivo del EQUIPO MAGMA.\p"
	.string "Si quieres saber qué están tramando,\n"
	.string "ve a visitar el CENTRO ESPACIAL.$"

MossdeepCity_Text_FeelReliefOnLand:
	.string "Soy un MARINERO, así que el mar\n"
	.string "es muy importante para mí.\p"
	.string "Pero cuando vuelvo a tierra después\n"
	.string "de un viaje, respiro tranquilo, ¿sabes?$"

MossdeepCity_Text_NiceIfWorldCoveredByFlowers:
	.string "Qué bonito sería…\p"
	.string "si el mundo entero estuviera cubierto\n"
	.string "de flores y plantas como las de aquí.$"

MossdeepCity_Text_LifeNeedsSeaToLive:
	.string "Todo ser vivo necesita el mar,\n"
	.string "aunque viva en la tierra.\p"
	.string "Todo ser vivo, con el tiempo, se\n"
	.string "convierte en polvo y vuelve a la tierra.\p"
	.string "El mar y la tierra están conectados…,\p"
	.string "basta mirar la costa para darse cuenta.$"

MossdeepCity_Text_SurfExhilarating:
	.string "Un viaje en barco es divertido.\p"
	.string "Pero cruzar el mar con un POKéMON\n"
	.string "que hace SURF…\p"
	.string "¡Eso sí que es un puntazo!\n"
	.string "¿A que sí?$"

MossdeepCity_Text_SpecialSpaceCenterRock:
	.string "Esta roca tiene un significado especial\n"
	.string "para la gente del CENTRO ESPACIAL.\p"
	.string "Es como un talismán para que los\n"
	.string "cohetes despeguen sin problemas.\p"
	.string "Y tú, cuando formulas un deseo,\n"
	.string "¿usas algún amuleto?\p"
	.string "Yo tengo una frase mágica…\n"
	.string "¡y siempre funciona!$"

MossdeepCity_Text_ItsAWhiteRock:
	.string "Es una roca blanca.$"

MossdeepCity_Text_GymSign:
	.string "GIMNASIO POKéMON de CIUDAD ALGARIA\n"
	.string "LÍDERES: LETI Y VITO\p"
	.string "“¡Una combinación mística!”$"

MossdeepCity_Text_CitySign:
	.string "CIUDAD ALGARIA\p"
	.string "“Nuestra divisa: ¡quiere\n"
	.string "a los POKéMON!”$"

MossdeepCity_Text_SpaceCenterSign:
	.string "CENTRO ESPACIAL de ALGARIA\p"
	.string "“¡A un paso del espacio exterior!”$"

MossdeepCity_Text_ScottSomethingWrongWithTown:
	.string "TRETO: {PLAYER}{KUN}, ¿cómo estás?\n"
	.string "¡Yo estoy estupendamente!\p"
	.string "He oído que los LÍDERES de GIMNASIO\n"
	.string "de CIUDAD ALGARIA son bastante\l"
	.string "fuertes, así que quiero comprobarlo.\p"
	.string "Pero hay algo en esta ciudad\n"
	.string "que no me da buena espina.\p"
	.string "Todos hablan de una misteriosa carta\n"
	.string "de advertencia y del CENTRO ESPACIAL…\p"
	.string "Aunque yo creo que todo eso\n"
	.string "a mí no me atañe.$"

MossdeepCity_Text_SootopolisNewGymLeader:
	.string "Aaah… Qué bien se está con\n"
	.string "el mar acariciándote los pies…\p"
	.string "Hablando de olas, ¿conoces la\n"
	.string "ciudad-isla de ARRECÍPOLIS?\p"
	.string "Creo que el GIMNASIO de allí\n"
	.string "tiene un nuevo LÍDER.\p"
	.string "Al parecer, el nuevo LÍDER fue\n"
	.string "el mentor de PLUBIO en su día.$"
