
MossdeepCity_House2_Text_SisterMailsBoyfriendInFortree:
	.string "Mi hermana pequeña se escribe CARTAS\n"
	.string "con su novio, que vive en ARBORADA.\p"
	.string "Yo preferiría poder quedar\n"
	.string "con él en vivo y en directo.$"

MossdeepCity_House2_Text_PokemonCarriesMailBackAndForth:
	.string "No puedo ver a mi novio, porque vive en\n"
	.string "ARBORADA, pero mi POKéMON le lleva\l"
	.string "mis CARTAS allí y me trae las suyas.\p"
	.string "Así podemos seguir en contacto\n"
	.string "a pesar de la distancia.$"

MossdeepCity_House2_Text_Wingull:
	.string "WINGULL: ¡Winguuu!$"
