SootopolisCity_MysteryEventsHouse_B1F: @ 8483BB0
	.4byte SootopolisCity_MysteryEventsHouse_B1F_Layout
	.4byte SootopolisCity_MysteryEventsHouse_B1F_MapEvents
	.4byte SootopolisCity_MysteryEventsHouse_B1F_MapScripts
	.4byte 0x0
	.2byte MUS_RUNECITY
	.2byte 440
	.byte MAPSEC_SOOTOPOLIS_CITY
	.byte 0
	.byte WEATHER_NONE
	.byte MAP_TYPE_INDOOR
	.2byte 0
	map_header_flags allow_bike=0, allow_escape_rope=0, allow_run=0, show_map_name=0
	.byte MAP_BATTLE_SCENE_NORMAL

