
SeafloorCavern_Room4_Text_Grunt3Intro:
	.string "Qui es-tu?\n"
	.string "Comment as-tu atterri ici?$"

SeafloorCavern_Room4_Text_Grunt3Defeat:
	.string "J’ai perdu…$"

SeafloorCavern_Room4_Text_Grunt3PostBattle:
	.string "J’arrive pas à trouver d’issue!\p"
	.string "J’ai pas peur. Comprends-moi bien!$"

SeafloorCavern_Room4_Text_Grunt4Intro:
	.string "Qui es-tu?\n"
	.string "Pour qui est-ce que tu te prends?$"

SeafloorCavern_Room4_Text_Grunt4Defeat:
	.string "Tu m’as eue!$"

SeafloorCavern_Room4_Text_Grunt4PostBattle:
	.string "Mon partenaire a oublié la carte dans\n"
	.string "le sous-marin!\p"
	.string "C’est le roi des incapables!$"
