
RustboroCity_Flat2_2F_Text_DevonWasTinyInOldDays:
	.string "Hace mucho, mucho tiempo, DEVON no\n"
	.string "era más que una mini-empresa de nada.$"

RustboroCity_Flat2_2F_Text_MyDaddyMadeThisYouCanHaveIt:
	.string "Mi papá trabaja en DEVON S.A.\p"
	.string "¡Mi papá ha hecho esto!\n"
	.string "Pero, como yo no puedo usarlo, te lo doy.$"

RustboroCity_Flat2_2F_Text_GoingToWorkAtDevonToo:
	.string "Mi papá trabaja en DEVON S.A.\p"
	.string "Cuando sea mayor, yo también\n"
	.string "voy a trabajar en DEVON.$"
