
RustboroCity_Flat2_2F_Text_DevonWasTinyInOldDays:
	.string "A l’époque, DEVON n’était qu’une toute\n"
	.string "petite, une minuscule entreprise.$"

RustboroCity_Flat2_2F_Text_MyDaddyMadeThisYouCanHaveIt:
	.string "Mon papa travaille chez DEVON.\p"
	.string "C’est mon papa qu’a fait ça!\n"
	.string "Mais ça m’sert pas. Tu peux l’prendre.$"

RustboroCity_Flat2_2F_Text_GoingToWorkAtDevonToo:
	.string "Mon papa travaille chez DEVON.\p"
	.string "Quand j’serai grand, moi aussi\n"
	.string "j’travaillerai pour DEVON.$"
