BattleFrontier_BattleDomePreBattleRoom_EventObjects:
	object_event 1, EVENT_OBJ_GFX_TEALA, 0, 5, 2, 3, MOVEMENT_TYPE_FACE_DOWN, 1, 1, 0, 0, 0x0, 0

BattleFrontier_BattleDomePreBattleRoom_MapWarps:
	warp_def 6, 8, 3, 1, MAP_BATTLE_FRONTIER_OUTSIDE_WEST
	warp_def 7, 8, 3, 1, MAP_BATTLE_FRONTIER_OUTSIDE_WEST

BattleFrontier_BattleDomePreBattleRoom_MapEvents::
	map_events BattleFrontier_BattleDomePreBattleRoom_EventObjects, BattleFrontier_BattleDomePreBattleRoom_MapWarps, 0x0, 0x0

