
BattleFrontier_BattleTowerBattleRoom_Text_RestoreMonsToFullHealth:
	.string "Je vais soigner vos POKéMON.$"

@ Unused
BattleFrontier_BattleTowerBattleRoom_Text_ReadyForOpponent:
	.string "You will be facing opponent no. {STR_VAR_1}.\n"
	.string "Are you ready?$"

BattleFrontier_BattleTowerBattleRoom_Text_ReadyFor2ndOpponent:
	.string "Vous allez affronter l’adversaire nº 2.\n"
	.string "Pouvons-nous continuer?$"

BattleFrontier_BattleTowerBattleRoom_Text_ReadyFor3rdOpponent:
	.string "Vous allez affronter l’adversaire nº 3.\n"
	.string "Pouvons-nous continuer?$"

BattleFrontier_BattleTowerBattleRoom_Text_ReadyFor4thOpponent:
	.string "Vous allez affronter l’adversaire nº 4.\n"
	.string "Pouvons-nous continuer?$"

BattleFrontier_BattleTowerBattleRoom_Text_ReadyFor5thOpponent:
	.string "Vous allez affronter l’adversaire nº 5.\n"
	.string "Pouvons-nous continuer?$$"

BattleFrontier_BattleTowerBattleRoom_Text_ReadyFor6thOpponent:
	.string "Vous allez affronter l’adversaire nº 6.\n"
	.string "Pouvons-nous continuer?$"

BattleFrontier_BattleTowerBattleRoom_Text_ReadyFor7thOpponent:
	.string "Vous allez affronter l’adversaire nº 7.\n"
	.string "Pouvons-nous continuer?$"

BattleFrontier_BattleTowerBattleRoom_Text_RecordYourBattle:
	.string "Enregistrer le combat sur le\n"
	.string "PASSE ZONE?$"

BattleFrontier_BattleTowerLobby_Text_BattleRecordedOnPass:
	.string "Le combat de {PLAYER} a été enregistré\n"
	.string "sur le PASSE ZONE.$"

BattleFrontier_BattleTowerBattleRoom_Text_SaveAndQuitGame:
	.string "Voulez-vous sauvegarder la partie et\n"
	.string "arrêter de jouer?$"

BattleFrontier_BattleTowerBattleRoom_Text_SavingPleaseWait:
	.string "Sauvegarde des données en cours…\n"
	.string "Veuillez patienter.$"

BattleFrontier_BattleTowerBattleRoom_Text_CancelYourChallenge:
	.string "Voulez-vous annuler le défi de la\n"
	.string "SALLE DE COMBAT?$"

BattleFrontier_BattleTowerBattleRoom_Text_RecordCouldntBeSaved::
	.string "Une erreur est survenue.\n"
	.string "La sauvegarde a échoué.$"

BattleFrontier_BattleTowerBattleRoom_Text_SalonMaidenOnHerWay:
	.string "Vous savez…\p"
	.string "Notre chef, l’AS DU SALON, arrive.\n"
	.string "Elle espère pouvoir vous affronter.\p"
	.string "Elle sera ici d’une minute à l’autre.$"

BattleFrontier_BattleTowerBattleRoom_Text_ReadyForSalonMaiden:
	.string "Vous allez affronter l’AS DU SALON.\n"
	.string "Pouvons-nous commencer?$"

BattleFrontier_BattleTowerBattleRoom_Text_GreetingsImAnabel:
	.string "Bonjour…\n"
	.string "Je m’appelle CATHY.\p"
	.string "Je suis l’AS DU SALON et je suis la\n"
	.string "responsable de la TOUR DE COMBAT…\p"
	.string "Je dois dire que j’ai beaucoup entendu\n"
	.string "parler de toi…\p"
	.string "Ce que j’ai entendu n’était pas\n"
	.string "toujours très flatteur, d’ailleurs…\p"
	.string "Tu dois te demander ce que je fais\n"
	.string "ici, alors… Eh bien, moi aussi!$"

BattleFrontier_BattleTowerBattleRoom_Text_LetMeSeeYourTalent:
	.string "Allez, essaie de m’éblouir par ton\n"
	.string "talent…$"

BattleFrontier_BattleTowerBattleRoom_Text_AnabelTalentShallBeRecognized:
	.string "CATHY: Oh, oh…\p"
	.string "Ton PASSE ZONE, s’il te plaît…\n"
	.string "Ton talent doit être reconnu.$"

BattleFrontier_BattleTowerBattleRoom_Text_ReceivedAbilitySymbol:
	.string "Le SYMBOLE CAPACITE a été ajouté\n"
	.string "sur le PASSE ZONE!$"

BattleFrontier_BattleTowerBattleRoom_Text_UntilNextTime:
	.string "… … … … … …\p"
	.string "Tu as une réelle confiance en tes\n"
	.string "POKéMON, n’est-ce pas?\p"
	.string "J’ai hâte de t’affronter à nouveau\n"
	.string "et de gagner!\p"
	.string "Je t’attendrai le temps qu’il faudra.\n"
	.string "Nous nous reverrons, j’en suis sûre…$"

BattleFrontier_BattleTowerBattleRoom_Text_AnabelYouCameBack:
	.string "CATHY: Toi? Je n’étais pas sûre\n"
	.string "que tu reviennes me voir…\p"
	.string "… … … … … …\p"
	.string "Tu as gagné beaucoup de combats…\n"
	.string "Je ne te faciliterai pas la tâche…\p"
	.string "Cela fait si longtemps…\p"
	.string "Cela fait si longtemps que j’attends ce\n"
	.string "moment…$"

BattleFrontier_BattleTowerBattleRoom_Text_LetsBeginShallWe:
	.string "On peut commencer?$"

BattleFrontier_BattleTowerBattleRoom_Text_AnabelCongratsYourPassPlease:
	.string "CATHY: Eh bien, félicitations…\n"
	.string "Ton PASSE ZONE, s’il te plaît…$"

BattleFrontier_BattleTowerBattleRoom_Text_AbilitySymbolTookGoldenShine:
	.string "Le SYMBOLE CAPACITE a pris une couleur\n"
	.string "dorée!$"

BattleFrontier_BattleTowerBattleRoom_Text_WishICouldBattleYouAgain:
	.string "Quel beau combat…\p"
	.string "Je crois que je n’avais jamais autant\n"
	.string "apprécié un combat de POKéMON…\p"
	.string "J’espère avoir l’occasion de me battre\n"
	.string "à nouveau contre toi…$"