
BattleFrontier_BattleTowerBattleRoom_Text_RestoreMonsToFullHealth:
	.string "Rimettiamo in sesto i POKéMON\n"
	.string "stanchi.$"

@ Unused
BattleFrontier_BattleTowerBattleRoom_Text_ReadyForOpponent:
	.string "You will be facing opponent no. {STR_VAR_1}.\n"
	.string "Are you ready?$"

BattleFrontier_BattleTowerBattleRoom_Text_ReadyFor2ndOpponent:
	.string "Ti attende il rivale numero 2.\n"
	.string "Tutto pronto?$"

BattleFrontier_BattleTowerBattleRoom_Text_ReadyFor3rdOpponent:
	.string "Ti attende il rivale numero 3.\n"
	.string "Tutto pronto?$"

BattleFrontier_BattleTowerBattleRoom_Text_ReadyFor4thOpponent:
	.string "Ti attende il rivale numero 4.\n"
	.string "Tutto pronto?$"

BattleFrontier_BattleTowerBattleRoom_Text_ReadyFor5thOpponent:
	.string "Ti attende il rivale numero 5.\n"
	.string "Tutto pronto?$"

BattleFrontier_BattleTowerBattleRoom_Text_ReadyFor6thOpponent:
	.string "Ti attende il rivale numero 6.\n"
	.string "Tutto pronto?$"

BattleFrontier_BattleTowerBattleRoom_Text_ReadyFor7thOpponent:
	.string "Ti attende il rivale numero 7.\n"
	.string "Tutto pronto?$"

BattleFrontier_BattleTowerBattleRoom_Text_RecordYourBattle:
	.string "Vuoi che il filmato dell’ultima lotta\n"
	.string "venga registrato nel PASS PARCO?$"

BattleFrontier_BattleTowerLobby_Text_BattleRecordedOnPass:
	.string "Il filmato dell’ultima lotta di {PLAYER}\n"
	.string "è stato registrato nel PASS PARCO.$"

BattleFrontier_BattleTowerBattleRoom_Text_SaveAndQuitGame:
	.string "Vuoi salvare e uscire dal gioco?$"

BattleFrontier_BattleTowerBattleRoom_Text_SavingPleaseWait:
	.string "Salvataggio in corso dei dati relativi\n"
	.string "alla lotta. Attendi.$"

BattleFrontier_BattleTowerBattleRoom_Text_CancelYourChallenge:
	.string "Vuoi annullare la sfida alla\n"
	.string "TORRE LOTTA?$"

BattleFrontier_BattleTowerBattleRoom_Text_RecordCouldntBeSaved::
	.string "Si è verificato un errore. I dati\n"
	.string "non possono essere salvati.$"

BattleFrontier_BattleTowerBattleRoom_Text_SalonMaidenOnHerWay:
	.string "Scusa, ma…\p"
	.string "Il nostro leader, la DAMA TORRE, ci sta\n"
	.string "raggiungendo con la speranza di lottare\l"
	.string "contro di te.\p"
	.string "Dovrebbe arrivare a momenti.$"

BattleFrontier_BattleTowerBattleRoom_Text_ReadyForSalonMaiden:
	.string "Affronterai la DAMA TORRE.\n"
	.string "Te la senti?$"

BattleFrontier_BattleTowerBattleRoom_Text_GreetingsImAnabel:
	.string "Salutissimi… mi chiamo ALBERTA.\p"
	.string "Sono la DAMA TORRE e gestisco\n"
	.string "la TORRE LOTTA…\p"
	.string "Ho sentito parlare molto di te…\p"
	.string "In tutta onestà, non mi sono fatta una\n"
	.string "buona opinione su di te…\p"
	.string "C’è solo un motivo per cui sono\n"
	.string "venuta a conoscerti…$"

BattleFrontier_BattleTowerBattleRoom_Text_LetMeSeeYourTalent:
	.string "Voglio vedere il tuo talento!$"

BattleFrontier_BattleTowerBattleRoom_Text_AnabelTalentShallBeRecognized:
	.string "ALBERTA: Fufufu, niente male…\p"
	.string "Dammi il tuo PASS PARCO… il tuo\n"
	.string "talento deve essere premiato.$"

BattleFrontier_BattleTowerBattleRoom_Text_ReceivedAbilitySymbol:
	.string "Il SIMBOLO ABILITÀ è stato aggiunto\n"
	.string "al PASS PARCO!$"

BattleFrontier_BattleTowerBattleRoom_Text_UntilNextTime:
	.string "… … … … … …\p"
	.string "Sai di avere talento nelle lotte coi\n"
	.string "POKéMON, non è vero?\p"
	.string "Ti consiglio di continuare a lottare e\n"
	.string "a vincere.\p"
	.string "Io ti aspetto.\n"
	.string "Al nostro prossimo incontro…$"

BattleFrontier_BattleTowerBattleRoom_Text_AnabelYouCameBack:
	.string "ALBERTA: Eccoti di nuovo qui!\p"
	.string "… … … … … …\p"
	.string "Hai vinto tante lotte per essere qui!\n"
	.string "Lottare contro di te è un piacere…\p"
	.string "È passato troppo tempo…\p"
	.string "È da tanto che non lotto contro\n"
	.string "qualcuno senza farmi troppi pensieri…$"

BattleFrontier_BattleTowerBattleRoom_Text_LetsBeginShallWe:
	.string "Ti va di iniziare?$"

BattleFrontier_BattleTowerBattleRoom_Text_AnabelCongratsYourPassPlease:
	.string "ALBERTA: Fufufu, congratulazioni!\n"
	.string "Dammi il tuo PASS PARCO…$"

BattleFrontier_BattleTowerBattleRoom_Text_AbilitySymbolTookGoldenShine:
	.string "Il SIMBOLO ABILITÀ si è colorato\n"
	.string "d’oro!$"

BattleFrontier_BattleTowerBattleRoom_Text_WishICouldBattleYouAgain:
	.string "È stato uno spasso…\p"
	.string "Non mi sono mai divertita così\n"
	.string "tanto coi POKéMON…\p"
	.string "Vorrei tanto lottare con te\n"
	.string "un’altra volta…$"
