
BattleFrontier_BattleTowerMultiBattleRoom_Text_ReadyFor2ndOpponentSet:
	.string "La deuxième équipe adverse est prête.\n"
	.string "Pouvons-nous commencer?$"

BattleFrontier_BattleTowerMultiBattleRoom_Text_ReadyFor3rdOpponentSet:
	.string "La troisième équipe adverse est prête.\n"
	.string "Pouvons-nous commencer?$"

BattleFrontier_BattleTowerMultiBattleRoom_Text_ReadyFor4thOpponentSet:
	.string "La quatrième équipe adverse est prête.\n"
	.string "Pouvons-nous commencer?$"

BattleFrontier_BattleTowerMultiBattleRoom_Text_ReadyFor5thOpponentSet:
	.string "La cinquième équipe adverse est prête.\n"
	.string "Pouvons-nous commencer?$"

BattleFrontier_BattleTowerMultiBattleRoom_Text_ReadyFor6thOpponentSet:
	.string "La sixième équipe adverse est prête.\n"
	.string "Pouvons-nous commencer?$"

BattleFrontier_BattleTowerMultiBattleRoom_Text_ReadyFor7thOpponentSet:
	.string "La septième équipe adverse est prête.\n"
	.string "Pouvons-nous commencer?$"

@ Unused
BattleFrontier_BattleTowerMultiBattleRoom_Text_2ndOpponentSetNext:
	.string "The 2nd set of opponents is next.\n"
	.string "Do your best!$"

@ Unused
BattleFrontier_BattleTowerMultiBattleRoom_Text_3rdOpponentSetNext:
	.string "The 3rd set of opponents is next.\n"
	.string "Do your best!$"

@ Unused
BattleFrontier_BattleTowerMultiBattleRoom_Text_4thOpponentSetNext:
	.string "The 4th set of opponents is next.\n"
	.string "Do your best!$"

@ Unused
BattleFrontier_BattleTowerMultiBattleRoom_Text_5thOpponentSetNext:
	.string "The 5th set of opponents is next.\n"
	.string "Do your best!$"

@ Unused
BattleFrontier_BattleTowerMultiBattleRoom_Text_6thOpponentSetNext:
	.string "The 6th set of opponents is next.\n"
	.string "Do your best!$"

@ Unused
BattleFrontier_BattleTowerMultiBattleRoom_Text_7thOpponentSetNext:
	.string "The 7th set of opponents is next.\n"
	.string "Do your best!$"

gText_LinkStandby3::
	.string "Connexion…$"

gText_YourPartnerHasRetired::
	.string "Votre partenaire a arrêté.\p"
	.string "Votre défi dans la SALLE DE\n"
	.string "COMBAT va être annulé.$"