LilycoveCity_ContestLobby_Text_292DEE: @ 8292DEE
	.string "Oh? Did you want to make some {POKEBLOCK}S\n"
	.string "with this old-timer?$"

LilycoveCity_ContestLobby_Text_292E28: @ 8292E28
	.string "Excellent!$"

LilycoveCity_ContestLobby_Text_292E33: @ 8292E33
	.string "Oh…\n"
	.string "You’ve made this old-timer sad…$"

LilycoveCity_ContestLobby_Text_292E57: @ 8292E57
	.string "Do you know how to make a {POKEBLOCK}?$"

LilycoveCity_ContestLobby_Text_292E78: @ 8292E78
	.string "Let’s get started, then!\p"
	.string "Let’s BERRY BLENDER!$"

LilycoveCity_ContestLobby_Text_292EA6: @ 8292EA6
	.string "Okay, a little explanation, then.\p"
	.string "Oh, don’t worry, it’s quite simple.\p"
	.string "When the BLENDER’s arrow comes to\n"
	.string "your marker, just press the A Button.\p"
	.string "That’s all you have to do.\n"
	.string "You’ll see how easy it is when you try.$"

LilycoveCity_ContestLobby_Text_292F77: @ 8292F77
	.string "Oh?\n"
	.string "You don’t have any BERRIES?\p"
	.string "If you don’t have any BERRIES,\n"
	.string "you can’t make any {POKEBLOCK}S.$"

LilycoveCity_ContestLobby_Text_292FD1: @ 8292FD1
	.string "Well, that won’t do at all now, will it?\p"
	.string "If you don’t mind leftovers, you can\n"
	.string "have one of my BERRIES.\p"
	.string "That way, we could make some {POKEBLOCK}S\n"
	.string "together using the BERRY BLENDER.$"

LilycoveCity_ContestLobby_Text_29307D: @ 829307D
	.string "If I had some BERRIES left over,\n"
	.string "I’d gladly give you one…\p"
	.string "But, I don’t have any to spare today.\n"
	.string "We’ll have to do this another time.$"

LilycoveCity_ContestLobby_Text_293101: @ 8293101
	.string "But your {POKEBLOCK} CASE is full.\p"
	.string "You should use some {POKEBLOCK}S before\n"
	.string "you come see me again.$"

LilycoveCity_ContestLobby_Text_293157: @ 8293157
	.string "But you don’t have a {POKEBLOCK} CASE.\p"
	.string "You should get a {POKEBLOCK} CASE and then\n"
	.string "come see me.$"

LilycoveCity_ContestLobby_Text_2931AA: @ 82931AA
	.string "Let’s get blending already!$"

LilycoveCity_ContestLobby_Text_2931C6: @ 82931C6
	.string "I wonder what kind of {POKEBLOCK} I’ll get?\n"
	.string "This is so exciting!$"

LilycoveCity_ContestLobby_Text_293201: @ 8293201
	.string "Hi, there! Did you want to blend some\n"
	.string "{POKEBLOCK}S with us?$"

LilycoveCity_ContestLobby_Text_293237: @ 8293237
	.string "Okay!$"

LilycoveCity_ContestLobby_Text_29323D: @ 829323D
	.string "That’s too bad…\p"
	.string "But we’ll always be around whenever\n"
	.string "you get the urge to blend!$"

LilycoveCity_ContestLobby_Text_29328C: @ 829328C
	.string "Of course, you do know how to\n"
	.string "blend {POKEBLOCK}S, don’t you?$"

LilycoveCity_ContestLobby_Text_2932C3: @ 82932C3
	.string "Let’s get started, then!\p"
	.string "Let’s BERRY BLENDER!$"

LilycoveCity_ContestLobby_Text_2932F1: @ 82932F1
	.string "Okay!\n"
	.string "Let me explain it to you!\p"
	.string "When the spinning BLENDER’s arrow\n"
	.string "reaches your marker, just press\l"
	.string "the A Button.\p"
	.string "That’s all it takes.\n"
	.string "Pretty easy, don’t you think?$"

LilycoveCity_ContestLobby_Text_293394: @ 8293394
	.string "Oh, but wait a second here…\n"
	.string "You don’t have any BERRIES.\p"
	.string "You can’t make any {POKEBLOCK}S without\n"
	.string "BERRIES…\p"
	.string "We’ll always be around whenever you\n"
	.string "get hold of some BERRIES to blend.$"

LilycoveCity_ContestLobby_Text_29343E: @ 829343E
	.string "Oh, but wait a second here…\n"
	.string "Your {POKEBLOCK} CASE is full.\p"
	.string "You should use some {POKEBLOCK}S and\n"
	.string "then come back.$"

LilycoveCity_ContestLobby_Text_2934A2: @ 82934A2
	.string "Oh, but wait a second here…\n"
	.string "You don’t have a {POKEBLOCK} CASE.\p"
	.string "You should get a {POKEBLOCK} CASE and\n"
	.string "then come back.$"

LilycoveCity_ContestLobby_Text_29350B: @ 829350B
	.string "Oh, hello! Did you want to make some\n"
	.string "{POKEBLOCK}S with our little group?$"

LilycoveCity_ContestLobby_Text_29354E: @ 829354E
	.string "Oh, dear!$"

LilycoveCity_ContestLobby_Text_293558: @ 8293558
	.string "Oh, dear me…\p"
	.string "You’ve left us in shock!$"

LilycoveCity_ContestLobby_Text_29357E: @ 829357E
	.string "Naturally, you know how to make\n"
	.string "{POKEBLOCK}S, don’t you?$"

LilycoveCity_ContestLobby_Text_2935B1: @ 82935B1
	.string "Okay, dear!\n"
	.string "Let’s get started!\p"
	.string "Let’s BERRY BLENDER!$"

LilycoveCity_ContestLobby_Text_2935E5: @ 82935E5
	.string "Oh, dear!\p"
	.string "Then, I’ll explain it to you nicely.\p"
	.string "When the BLENDER’s arrow spins to\n"
	.string "your marker, press the A Button.\p"
	.string "That’s all it takes.\n"
	.string "Isn’t it simple?$"

LilycoveCity_ContestLobby_Text_29367D: @ 829367D
	.string "You don’t have any BERRIES,\n"
	.string "do you?\p"
	.string "If you don’t have any BERRIES,\n"
	.string "you can’t make any {POKEBLOCK}S.\p"
	.string "We’ll always be making {POKEBLOCK}S here,\n"
	.string "so let’s make some together when\l"
	.string "you get a BERRY or two.$"

LilycoveCity_ContestLobby_Text_293738: @ 8293738
	.string "Your {POKEBLOCK} CASE is full,\n"
	.string "it looks like.\p"
	.string "You should use some {POKEBLOCK}S up\n"
	.string "and then come back.$"

LilycoveCity_ContestLobby_Text_293792: @ 8293792
	.string "You haven’t gotten a {POKEBLOCK} CASE\n"
	.string "yet, it looks like.\p"
	.string "You need to get a {POKEBLOCK} CASE before\n"
	.string "you come back.$"

LilycoveCity_ContestLobby_Text_2937F9: @ 82937F9
	.string "Okay! Today’s going to be the day that\n"
	.string "I set a new BLENDER speed record!$"

LilycoveCity_ContestLobby_Text_293842: @ 8293842
	.string "Oh, dear!\n"
	.string "You look as if you’re good at blending.\l"
	.string "Would you like to join us?$"

LilycoveCity_ContestLobby_Text_29388F: @ 829388F
	.string "I’m going to make delicious {POKEBLOCK}S\n"
	.string "and make my POKéMON cuter.$"

LilycoveCity_ContestLobby_Text_2938CD: @ 82938CD
	.string "{POKEBLOCK}S will be made with your friends \n"
	.string "from BERRIES in the BERRY BLENDER.\p"
	.string "Is it okay to save the game before\n"
	.string "linking with your friends?$"

LilycoveCity_ContestLobby_Text_293955: @ 8293955
	.string "Searching for your friends…\n"
	.string "… … B Button: Cancel$"

LilycoveCity_ContestLobby_Text_293986: @ 8293986
	.string "{STR_VAR_1} arrived.$"

LilycoveCity_ContestLobby_Text_293992: @ 8293992
	.string "{STR_VAR_1} and {STR_VAR_2} arrived.$"

LilycoveCity_ContestLobby_Text_2939A5: @ 82939A5
	.string "{STR_VAR_1}, {STR_VAR_2}, and\n"
	.string "{STR_VAR_3} arrived.$"

LilycoveCity_ContestLobby_Text_2939BD: @ 82939BD
	.string "You have no BERRIES.\n"
	.string "The BERRY BLENDER can’t be used.$"

LilycoveCity_ContestLobby_Text_2939F3: @ 82939F3
	.string "Your {POKEBLOCK} CASE is full.\n"
	.string "The BERRY BLENDER can’t be used.$"

LilycoveCity_ContestLobby_Text_293A2D: @ 8293A2D
	.string "You don’t have a {POKEBLOCK} CASE.\n"
	.string "The BERRY BLENDER can’t be used.$"

LilycoveCity_ContestLobby_Text_293A6B: @ 8293A6B
	.string "I love making {POKEBLOCK}S.\p"
	.string "I always have some BERRIES with me.$"

LilycoveCity_ContestLobby_Text_293AA5: @ 8293AA5
	.string "If you’d like, we could make some\n"
	.string "{POKEBLOCK}S together using the\l"
	.string "BERRY BLENDER.$"

LilycoveCity_ContestLobby_Text_293AF0: @ 8293AF0
	.string "Oh?\n"
	.string "You don’t have any BERRIES?\p"
	.string "Well, that won’t do at all now, will it?\p"
	.string "If you don’t mind leftovers, you can\n"
	.string "have one of my BERRIES.$"

LilycoveCity_ContestLobby_Text_293B76: @ 8293B76
	.string "We’ll use it to make {POKEBLOCK}S together\n"
	.string "using the BERRY BLENDER.$"

LilycoveCity_ContestLobby_Text_293BB4: @ 8293BB4
	.string "Oh?\n"
	.string "You don’t have any BERRIES?\p"
	.string "If I had some left over, I’d gladly\n"
	.string "give you one…\p"
	.string "But, I don’t have any to spare today.\n"
	.string "Sorry about that.$"

LilycoveCity_ContestLobby_EventScript_293C3E:: @ 8293C3E
	lockall
	checkflag FLAG_0x340
	goto_if 0, LilycoveCity_ContestLobby_EventScript_293EFB
	setvar VAR_0x8009, 1
	applymovement 16, LilycoveCity_ContestLobby_Movement_294053
	waitmovement 0
	msgbox LilycoveCity_ContestLobby_Text_292DEE, 5
	compare VAR_RESULT, 1
	goto_eq LilycoveCity_ContestLobby_EventScript_293CEE
	goto LilycoveCity_ContestLobby_EventScript_293C70
	end

LilycoveCity_ContestLobby_EventScript_293C70:: @ 8293C70
	msgbox LilycoveCity_ContestLobby_Text_292E33, 4
	releaseall
	end

LilycoveCity_ContestLobby_EventScript_293C7A:: @ 8293C7A
	msgbox LilycoveCity_ContestLobby_Text_292F77, 4
	dodailyevents
	checkflag FLAG_0x921
	goto_eq LilycoveCity_ContestLobby_EventScript_293C92
	goto LilycoveCity_ContestLobby_EventScript_293C9C
	end

LilycoveCity_ContestLobby_EventScript_293C92:: @ 8293C92
	msgbox LilycoveCity_ContestLobby_Text_29307D, 4
	releaseall
	end

LilycoveCity_ContestLobby_EventScript_293C9C:: @ 8293C9C
	msgbox LilycoveCity_ContestLobby_Text_292FD1, 4
	giveitem_std ITEM_PECHA_BERRY
	setflag FLAG_0x921
	goto LilycoveCity_ContestLobby_EventScript_293CB9
	end

LilycoveCity_ContestLobby_EventScript_293CB9:: @ 8293CB9
	msgbox LilycoveCity_ContestLobby_Text_292E57, 5
	compare VAR_RESULT, 1
	goto_eq LilycoveCity_ContestLobby_EventScript_293CD2
	goto LilycoveCity_ContestLobby_EventScript_293CE0
	end

LilycoveCity_ContestLobby_EventScript_293CD2:: @ 8293CD2
	msgbox LilycoveCity_ContestLobby_Text_292E78, 4
	goto LilycoveCity_ContestLobby_EventScript_293D2C
	end

LilycoveCity_ContestLobby_EventScript_293CE0:: @ 8293CE0
	msgbox LilycoveCity_ContestLobby_Text_292EA6, 4
	goto LilycoveCity_ContestLobby_EventScript_293CD2
	end

LilycoveCity_ContestLobby_EventScript_293CEE:: @ 8293CEE
	checkitem ITEM_POKEBLOCK_CASE, 1
	compare VAR_RESULT, 0
	goto_eq LilycoveCity_ContestLobby_EventScript_293D43
	specialvar VAR_RESULT, GetFirstFreePokeblockSlot
	compare VAR_RESULT, 65535
	goto_eq LilycoveCity_ContestLobby_EventScript_293D39
	specialvar VAR_RESULT, PlayerHasBerries
	compare VAR_RESULT, 0
	goto_eq LilycoveCity_ContestLobby_EventScript_293C7A
	msgbox LilycoveCity_ContestLobby_Text_292E28, 4
	goto LilycoveCity_ContestLobby_EventScript_293CB9
	end

LilycoveCity_ContestLobby_EventScript_293D2C:: @ 8293D2C
	copyvar VAR_0x8004, VAR_0x8009
	fadescreen 1
	special DoBerryBlending
	waitstate
	releaseall
	end

LilycoveCity_ContestLobby_EventScript_293D39:: @ 8293D39
	msgbox LilycoveCity_ContestLobby_Text_293101, 4
	releaseall
	end

LilycoveCity_ContestLobby_EventScript_293D43:: @ 8293D43
	msgbox LilycoveCity_ContestLobby_Text_293157, 4
	releaseall
	end

LilycoveCity_ContestLobby_EventScript_293D4D:: @ 8293D4D
	lockall
	setvar VAR_0x8009, 2
	applymovement 10, LilycoveCity_ContestLobby_Movement_2725A2
	applymovement 3, LilycoveCity_ContestLobby_Movement_294053
	waitmovement 0
	msgbox LilycoveCity_ContestLobby_Text_293201, 5
	compare VAR_RESULT, 1
	goto_eq LilycoveCity_ContestLobby_EventScript_293DC6
	goto LilycoveCity_ContestLobby_EventScript_293D7D
	end

LilycoveCity_ContestLobby_EventScript_293D7D:: @ 8293D7D
	msgbox LilycoveCity_ContestLobby_Text_29323D, 4
	releaseall
	end

LilycoveCity_ContestLobby_EventScript_293D87:: @ 8293D87
	msgbox LilycoveCity_ContestLobby_Text_293394, 4
	release
	end

LilycoveCity_ContestLobby_EventScript_293D91:: @ 8293D91
	msgbox LilycoveCity_ContestLobby_Text_29328C, 5
	compare VAR_RESULT, 1
	goto_eq LilycoveCity_ContestLobby_EventScript_293DAA
	goto LilycoveCity_ContestLobby_EventScript_293DB8
	end

LilycoveCity_ContestLobby_EventScript_293DAA:: @ 8293DAA
	msgbox LilycoveCity_ContestLobby_Text_2932C3, 4
	goto LilycoveCity_ContestLobby_EventScript_293D2C
	end

LilycoveCity_ContestLobby_EventScript_293DB8:: @ 8293DB8
	msgbox LilycoveCity_ContestLobby_Text_2932F1, 4
	goto LilycoveCity_ContestLobby_EventScript_293DAA
	end

LilycoveCity_ContestLobby_EventScript_293DC6:: @ 8293DC6
	specialvar VAR_RESULT, PlayerHasBerries
	compare VAR_RESULT, 0
	goto_eq LilycoveCity_ContestLobby_EventScript_293D87
	checkitem ITEM_POKEBLOCK_CASE, 1
	compare VAR_RESULT, 0
	goto_eq LilycoveCity_ContestLobby_EventScript_293E14
	msgbox LilycoveCity_ContestLobby_Text_293237, 4
	specialvar VAR_RESULT, GetFirstFreePokeblockSlot
	compare VAR_RESULT, 65535
	goto_if 5, LilycoveCity_ContestLobby_EventScript_293D91
	compare VAR_RESULT, 65535
	goto_eq LilycoveCity_ContestLobby_EventScript_293E0A
	end

LilycoveCity_ContestLobby_EventScript_293E0A:: @ 8293E0A
	msgbox LilycoveCity_ContestLobby_Text_29343E, 4
	releaseall
	end

LilycoveCity_ContestLobby_EventScript_293E14:: @ 8293E14
	msgbox LilycoveCity_ContestLobby_Text_2934A2, 4
	releaseall
	end

LilycoveCity_ContestLobby_EventScript_293E1E:: @ 8293E1E
	lockall
	setvar VAR_0x8008, 15
	setvar VAR_0x8009, 3
	applymovement 9, LilycoveCity_ContestLobby_Movement_2725A2
	applymovement 17, LilycoveCity_ContestLobby_Movement_2725A2
	applymovement VAR_0x8008, LilycoveCity_ContestLobby_Movement_294053
	waitmovement 0
	msgbox LilycoveCity_ContestLobby_Text_293842, 5
	compare VAR_RESULT, 1
	goto_eq LilycoveCity_ContestLobby_EventScript_293EA3
	goto LilycoveCity_ContestLobby_EventScript_293E5A
	end

LilycoveCity_ContestLobby_EventScript_293E5A:: @ 8293E5A
	msgbox LilycoveCity_ContestLobby_Text_293558, 4
	releaseall
	end

LilycoveCity_ContestLobby_EventScript_293E64:: @ 8293E64
	msgbox LilycoveCity_ContestLobby_Text_29367D, 4
	release
	end

LilycoveCity_ContestLobby_EventScript_293E6E:: @ 8293E6E
	msgbox LilycoveCity_ContestLobby_Text_29357E, 5
	compare VAR_RESULT, 1
	goto_eq LilycoveCity_ContestLobby_EventScript_293E87
	goto LilycoveCity_ContestLobby_EventScript_293E95
	end

LilycoveCity_ContestLobby_EventScript_293E87:: @ 8293E87
	msgbox LilycoveCity_ContestLobby_Text_2935B1, 4
	goto LilycoveCity_ContestLobby_EventScript_293D2C
	end

LilycoveCity_ContestLobby_EventScript_293E95:: @ 8293E95
	msgbox LilycoveCity_ContestLobby_Text_2935E5, 4
	goto LilycoveCity_ContestLobby_EventScript_293E87
	end

LilycoveCity_ContestLobby_EventScript_293EA3:: @ 8293EA3
	specialvar VAR_RESULT, PlayerHasBerries
	compare VAR_RESULT, 0
	goto_eq LilycoveCity_ContestLobby_EventScript_293E64
	checkitem ITEM_POKEBLOCK_CASE, 1
	compare VAR_RESULT, 0
	goto_eq LilycoveCity_ContestLobby_EventScript_293EF1
	msgbox LilycoveCity_ContestLobby_Text_29354E, 4
	specialvar VAR_RESULT, GetFirstFreePokeblockSlot
	compare VAR_RESULT, 65535
	goto_if 5, LilycoveCity_ContestLobby_EventScript_293E6E
	compare VAR_RESULT, 65535
	goto_eq LilycoveCity_ContestLobby_EventScript_293EE7
	end

LilycoveCity_ContestLobby_EventScript_293EE7:: @ 8293EE7
	msgbox LilycoveCity_ContestLobby_Text_293738, 4
	releaseall
	end

LilycoveCity_ContestLobby_EventScript_293EF1:: @ 8293EF1
	msgbox LilycoveCity_ContestLobby_Text_293792, 4
	releaseall
	end

LilycoveCity_ContestLobby_EventScript_293EFB:: @ 8293EFB
	lockall
	setvar VAR_0x8009, 1
	msgbox LilycoveCity_ContestLobby_Text_2C42F4, 5
	compare VAR_RESULT, 1
	goto_eq LilycoveCity_ContestLobby_EventScript_293F28
	msgbox LilycoveCity_ContestLobby_Text_2C4332, 4
	releaseall
	end

LilycoveCity_ContestLobby_EventScript_293F1E:: @ 8293F1E
	msgbox LilycoveCity_ContestLobby_Text_2C439D, 4
	releaseall
	end

LilycoveCity_ContestLobby_EventScript_293F28:: @ 8293F28
	checkitem ITEM_POKEBLOCK_CASE, 1
	compare VAR_RESULT, 0
	goto_eq LilycoveCity_ContestLobby_EventScript_293F8E
	specialvar VAR_RESULT, PlayerHasBerries
	compare VAR_RESULT, 0
	goto_eq LilycoveCity_ContestLobby_EventScript_293F1E
	specialvar VAR_RESULT, GetFirstFreePokeblockSlot
	compare VAR_RESULT, 65535
	goto_if 5, LilycoveCity_ContestLobby_EventScript_293F64
	compare VAR_RESULT, 65535
	goto_eq LilycoveCity_ContestLobby_EventScript_293F98
	end

LilycoveCity_ContestLobby_EventScript_293F64:: @ 8293F64
	msgbox LilycoveCity_ContestLobby_Text_2C43FA, 5
	compare VAR_RESULT, 0
	call_if 1, LilycoveCity_ContestLobby_EventScript_293F85
	msgbox LilycoveCity_ContestLobby_Text_2C451B, 4
	goto LilycoveCity_ContestLobby_EventScript_293D2C
	end

LilycoveCity_ContestLobby_EventScript_293F85:: @ 8293F85
	msgbox LilycoveCity_ContestLobby_Text_2C444C, 4
	return

LilycoveCity_ContestLobby_EventScript_293F8E:: @ 8293F8E
	msgbox LilycoveCity_ContestLobby_Text_2C4573, 4
	releaseall
	end

LilycoveCity_ContestLobby_EventScript_293F98:: @ 8293F98
	msgbox LilycoveCity_ContestLobby_Text_2C45E8, 4
	releaseall
	end

LilycoveCity_ContestLobby_EventScript_293FA2:: @ 8293FA2
	msgbox LilycoveCity_ContestLobby_Text_2937F9, 2
	end

LilycoveCity_ContestLobby_EventScript_293FAB:: @ 8293FAB
	msgbox LilycoveCity_ContestLobby_Text_293842, 2
	end

LilycoveCity_ContestLobby_EventScript_293FB4:: @ 8293FB4
	msgbox LilycoveCity_ContestLobby_Text_29388F, 2
	end

LilycoveCity_ContestLobby_EventScript_293FBD:: @ 8293FBD
	setvar VAR_0x8008, 15
	goto LilycoveCity_ContestLobby_EventScript_293FC8
	end

LilycoveCity_ContestLobby_EventScript_293FC8:: @ 8293FC8
	lock
	faceplayer
	msgbox LilycoveCity_ContestLobby_Text_293A6B, 4
	specialvar VAR_RESULT, PlayerHasBerries
	compare VAR_RESULT, 1
	goto_eq LilycoveCity_ContestLobby_EventScript_293FEE
	compare VAR_RESULT, 0
	goto_eq LilycoveCity_ContestLobby_EventScript_293FF8
	end

LilycoveCity_ContestLobby_EventScript_293FEE:: @ 8293FEE
	msgbox LilycoveCity_ContestLobby_Text_293AA5, 4
	release
	end

LilycoveCity_ContestLobby_EventScript_293FF8:: @ 8293FF8
	checkitem ITEM_POKEBLOCK_CASE, 1
	compare VAR_RESULT, 0
	goto_eq LilycoveCity_ContestLobby_EventScript_294028
	specialvar VAR_RESULT, GetFirstFreePokeblockSlot
	compare VAR_RESULT, 65535
	goto_eq LilycoveCity_ContestLobby_EventScript_294028
	dodailyevents
	checkflag FLAG_0x921
	goto_eq LilycoveCity_ContestLobby_EventScript_294028
	goto LilycoveCity_ContestLobby_EventScript_294032
	end

LilycoveCity_ContestLobby_EventScript_294028:: @ 8294028
	msgbox LilycoveCity_ContestLobby_Text_293BB4, 4
	release
	end

LilycoveCity_ContestLobby_EventScript_294032:: @ 8294032
	msgbox LilycoveCity_ContestLobby_Text_293AF0, 4
	giveitem_std ITEM_PECHA_BERRY
	setflag FLAG_0x921
	msgbox LilycoveCity_ContestLobby_Text_293B76, 4
	release
	end

LilycoveCity_ContestLobby_Movement_294053: @ 8294053
	walk_in_place_fastest_right
	step_end

LilycoveCity_ContestLobby_EventScript_294055:: @ 8294055
	lockall
	specialvar VAR_RESULT, PlayerHasBerries
	compare VAR_RESULT, 0
	goto_eq LilycoveCity_ContestLobby_EventScript_2940B1
	checkitem ITEM_POKEBLOCK_CASE, 1
	compare VAR_RESULT, 0
	goto_eq LilycoveCity_ContestLobby_EventScript_29416C
	specialvar VAR_RESULT, GetFirstFreePokeblockSlot
	compare VAR_RESULT, 65535
	goto_if 5, LilycoveCity_ContestLobby_EventScript_294092
	compare VAR_RESULT, 65535
	goto_eq LilycoveCity_ContestLobby_EventScript_294162
	end

LilycoveCity_ContestLobby_EventScript_294092:: @ 8294092
	msgbox LilycoveCity_ContestLobby_Text_2938CD, 5
	compare VAR_RESULT, 1
	goto_eq LilycoveCity_ContestLobby_EventScript_2940BB
	compare VAR_RESULT, 0
	goto_eq LilycoveCity_ContestLobby_EventScript_294160
	end

LilycoveCity_ContestLobby_EventScript_2940B1:: @ 82940B1
	msgbox LilycoveCity_ContestLobby_Text_2939BD, 4
	releaseall
	end

LilycoveCity_ContestLobby_EventScript_2940BB:: @ 82940BB
	call LilycoveCity_ContestLobby_EventScript_27134F
	compare VAR_RESULT, 0
	goto_eq LilycoveCity_ContestLobby_EventScript_294160
	specialvar VAR_RESULT, IsWirelessAdapterConnected
	compare VAR_RESULT, 1
	goto_eq LilycoveCity_ContestLobby_EventScript_2941ED
	message LilycoveCity_ContestLobby_Text_293955
	waitmessage
	special sub_80B2FD8
	waitstate
	compare VAR_RESULT, 1
	goto_eq LilycoveCity_ContestLobby_EventScript_2941AA
	compare VAR_RESULT, 2
	goto_eq LilycoveCity_ContestLobby_EventScript_294176
	compare VAR_RESULT, 3
	goto_eq LilycoveCity_ContestLobby_EventScript_294183
	compare VAR_RESULT, 5
	goto_eq LilycoveCity_ContestLobby_EventScript_294190
	compare VAR_RESULT, 6
	goto_eq LilycoveCity_ContestLobby_EventScript_29419D
	end

LilycoveCity_ContestLobby_EventScript_29411D:: @ 829411D
	msgbox LilycoveCity_ContestLobby_Text_293986, 4
	goto LilycoveCity_ContestLobby_EventScript_294147
	end

LilycoveCity_ContestLobby_EventScript_29412B:: @ 829412B
	msgbox LilycoveCity_ContestLobby_Text_293992, 4
	goto LilycoveCity_ContestLobby_EventScript_294147
	end

LilycoveCity_ContestLobby_EventScript_294139:: @ 8294139
	msgbox LilycoveCity_ContestLobby_Text_2939A5, 4
	goto LilycoveCity_ContestLobby_EventScript_294147
	end

LilycoveCity_ContestLobby_EventScript_294147:: @ 8294147
	setvar VAR_0x8004, 0
	fadescreen 1
	removeobject 240
	removeobject 239
	removeobject 238
	removeobject 237
	special DoBerryBlending
	waitstate
	releaseall
	end

LilycoveCity_ContestLobby_EventScript_294160:: @ 8294160
	releaseall
	end

LilycoveCity_ContestLobby_EventScript_294162:: @ 8294162
	msgbox LilycoveCity_ContestLobby_Text_2939F3, 4
	releaseall
	end

LilycoveCity_ContestLobby_EventScript_29416C:: @ 829416C
	msgbox LilycoveCity_ContestLobby_Text_293A2D, 4
	releaseall
	end

LilycoveCity_ContestLobby_EventScript_294176:: @ 8294176
	special CloseLink
	msgbox LilycoveCity_ContestLobby_Text_2781C7, 4
	releaseall
	end

LilycoveCity_ContestLobby_EventScript_294183:: @ 8294183
	special CloseLink
	msgbox LilycoveCity_ContestLobby_Text_278255, 4
	releaseall
	end

LilycoveCity_ContestLobby_EventScript_294190:: @ 8294190
	special CloseLink
	msgbox gUnknown_08272D9C, 4
	releaseall
	end

LilycoveCity_ContestLobby_EventScript_29419D:: @ 829419D
	special CloseLink
	msgbox LilycoveCity_ContestLobby_Text_27821C, 4
	releaseall
	end

LilycoveCity_ContestLobby_EventScript_2941AA:: @ 82941AA
	fadescreen 1
	specialvar VAR_RESULT, GetLinkPartnerNames
	copyvar VAR_0x8008, VAR_RESULT
	copyvar VAR_0x8004, VAR_0x8008
	special SpawnLinkPartnerEventObject
	goto LilycoveCity_ContestLobby_EventScript_2941C4
	end

LilycoveCity_ContestLobby_EventScript_2941C4:: @ 82941C4
	fadescreen 0
	switch VAR_0x8008
	case 2, LilycoveCity_ContestLobby_EventScript_29411D
	case 3, LilycoveCity_ContestLobby_EventScript_29412B
	case 4, LilycoveCity_ContestLobby_EventScript_294139
	end

LilycoveCity_ContestLobby_EventScript_2941ED:: @ 82941ED
	setvar VAR_0x8004, 13
	goto LilycoveCity_ContestLobby_EventScript_2941F8
	end

LilycoveCity_ContestLobby_EventScript_2941F8:: @ 82941F8
	message LilycoveCity_ContestLobby_Text_27C1EA
	waitmessage
	multichoice 16, 6, 81, 0
	switch VAR_RESULT
	case 0, LilycoveCity_ContestLobby_EventScript_29425D
	case 1, LilycoveCity_ContestLobby_EventScript_294235
	case 2, LilycoveCity_ContestLobby_EventScript_294190
	case 127, LilycoveCity_ContestLobby_EventScript_294190
	end

LilycoveCity_ContestLobby_EventScript_294235:: @ 8294235
	call LilycoveCity_ContestLobby_EventScript_294285
	compare VAR_RESULT, 1
	goto_eq LilycoveCity_ContestLobby_EventScript_29428F
	compare VAR_RESULT, 5
	goto_eq LilycoveCity_ContestLobby_EventScript_2941F8
	compare VAR_RESULT, 8
	goto_eq LilycoveCity_ContestLobby_EventScript_294235
	release
	end

LilycoveCity_ContestLobby_EventScript_29425D:: @ 829425D
	call LilycoveCity_ContestLobby_EventScript_29428A
	compare VAR_RESULT, 1
	goto_eq LilycoveCity_ContestLobby_EventScript_29428F
	compare VAR_RESULT, 5
	goto_eq LilycoveCity_ContestLobby_EventScript_2941F8
	compare VAR_RESULT, 8
	goto_eq LilycoveCity_ContestLobby_EventScript_29425D
	release
	end

LilycoveCity_ContestLobby_EventScript_294285:: @ 8294285
	special BerryBlenderLinkBecomeLeader
	waitstate
	return

LilycoveCity_ContestLobby_EventScript_29428A:: @ 829428A
	special BerryBlenderLinkJoinGroup
	waitstate
	return

LilycoveCity_ContestLobby_EventScript_29428F:: @ 829428F
	goto LilycoveCity_ContestLobby_EventScript_2941AA
	end
