Shuffler_NPC_Text_Error:
	.string "Cannot determine npc type.\n"
	.string "Let walkingeye know this happened.$"

Shuffler_NPC_Trader_Text_AfterTrade:
	.string "Thanks for the trade, nerd.$"

Shuffler_NPC_Trader_Text_Offer:
	.string "I'll trade you my {STR_VAR_2} for\n"
	.string "a {STR_VAR_1} type if you want.$"

Shuffler_NPC_Trader_Text_DeclineTrade:
	.string "Ok no trade then, nerd.$"

Shuffler_NPC_Trader_Text_WrongType:
	.string "That's not a {STR_VAR_1} type, nerd.$"

Shuffler_NPC_Trader_Text_PostTrade:
	.string "Eheheh… nice.$"

Shuffler_NPC_Healer_Text_AskHeal:
    .string "Would you like me to heal\nyour pokemon?$"

Shuffler_NPC_Healer_Text_DoHeal:
    .string "BAM! They're healed.$"

Shuffler_NPC_Healer_Text_Done:
    .string "Now go away.$"

Shuffler_NPC_Witch_Text_Ask:
	.string "If you let me {STR_VAR_1},\nI'll reward you with\p{STR_VAR_2}.\nWhat do you say?$"

Shuffler_NPC_Witch_Text_DoMagic:
	.string "Hocus Pocus! The pact is sealed!$"

Shuffler_NPC_Witch_Text_Done:
	.string "Ehehehehehehe!$"
