UnusualWeather_EventScript_PlaceTilesRoute114North:: @ 8273913
	setmetatile 7, 3, METATILE_Fallarbor_RedCaveEntrance_Top, 1
	setmetatile 7, 4, METATILE_Fallarbor_RedCaveEntrance_Bottom, 0
	return

UnusualWeather_EventScript_PlaceTilesRoute114South:: @ 8273926
	setmetatile 6, 45, METATILE_Fallarbor_BrownCaveEntrance_Top, 1
	setmetatile 6, 46, METATILE_Fallarbor_BrownCaveEntrance_Bottom, 0
	return

UnusualWeather_EventScript_PlaceTilesRoute115West:: @ 8273939
	setmetatile 21, 5, METATILE_Fallarbor_BrownCaveEntrance_Top, 1
	setmetatile 21, 6, METATILE_Fallarbor_BrownCaveEntrance_Bottom, 0
	return

UnusualWeather_EventScript_PlaceTilesRoute115East:: @ 827394C
	setmetatile 36, 9, METATILE_Fallarbor_BrownCaveEntrance_Top, 1
	setmetatile 36, 10, METATILE_Fallarbor_BrownCaveEntrance_Bottom, 0
	return

UnusualWeather_EventScript_PlaceTilesRoute116North:: @ 827395F
	setmetatile 59, 12, METATILE_General_CaveEntrance_Top, 1
	setmetatile 59, 13, METATILE_General_CaveEntrance_Bottom, 0
	return

UnusualWeather_EventScript_PlaceTilesRoute116South:: @ 8273972
	setmetatile 79, 5, METATILE_General_CaveEntrance_Top, 1
	setmetatile 79, 6, METATILE_General_CaveEntrance_Bottom, 0
	return

UnusualWeather_EventScript_PlaceTilesRoute118East:: @ 8273985
	setmetatile 42, 5, METATILE_General_CaveEntrance_Top, 1
	setmetatile 42, 6, METATILE_General_CaveEntrance_Bottom, 0
	return

UnusualWeather_EventScript_PlaceTilesRoute118West:: @ 8273998
	setmetatile 9, 5, METATILE_General_CaveEntrance_Top, 1
	setmetatile 9, 6, METATILE_General_CaveEntrance_Bottom, 0
	return

UnusualWeather_EventScript_PlaceTilesRoute105North:: @ 82739AB
	setmetatile 10, 28, METATILE_General_RoughWater, 0
	setmetatile 11, 28, METATILE_General_RoughWater, 0
	setmetatile 9, 29, METATILE_General_RoughWater, 0
	setmetatile 10, 29, METATILE_General_RoughDeepWater, 0
	setmetatile 11, 29, METATILE_General_RoughDeepWater, 0
	setmetatile 12, 29, METATILE_General_RoughWater, 0
	setmetatile 9, 30, METATILE_General_RoughWater, 0
	setmetatile 10, 30, METATILE_General_RoughDeepWater, 0
	setmetatile 11, 30, METATILE_General_RoughDeepWater, 0
	setmetatile 12, 30, METATILE_General_RoughWater, 0
	setmetatile 10, 31, METATILE_General_RoughWater, 0
	setmetatile 11, 31, METATILE_General_RoughWater, 0
	return

UnusualWeather_EventScript_PlaceTilesRoute105South:: @ 8273A18
	setmetatile 20, 53, METATILE_General_RoughWater, 0
	setmetatile 21, 53, METATILE_General_RoughWater, 0
	setmetatile 19, 54, METATILE_General_RoughWater, 0
	setmetatile 20, 54, METATILE_General_RoughDeepWater, 0
	setmetatile 21, 54, METATILE_General_RoughDeepWater, 0
	setmetatile 22, 54, METATILE_General_RoughWater, 0
	setmetatile 19, 55, METATILE_General_RoughWater, 0
	setmetatile 20, 55, METATILE_General_RoughDeepWater, 0
	setmetatile 21, 55, METATILE_General_RoughDeepWater, 0
	setmetatile 22, 55, METATILE_General_RoughWater, 0
	setmetatile 20, 56, METATILE_General_RoughWater, 0
	setmetatile 21, 56, METATILE_General_RoughWater, 0
	return

UnusualWeather_EventScript_PlaceTilesRoute125West:: @ 8273A85
	setmetatile 8, 16, METATILE_General_RoughWater, 0
	setmetatile 9, 16, METATILE_General_RoughWater, 0
	setmetatile 7, 17, METATILE_General_RoughWater, 0
	setmetatile 8, 17, METATILE_General_RoughDeepWater, 0
	setmetatile 9, 17, METATILE_General_RoughDeepWater, 0
	setmetatile 10, 17, METATILE_General_RoughWater, 0
	setmetatile 7, 18, METATILE_General_RoughWater, 0
	setmetatile 8, 18, METATILE_General_RoughDeepWater, 0
	setmetatile 9, 18, METATILE_General_RoughDeepWater, 0
	setmetatile 10, 18, METATILE_General_RoughWater, 0
	setmetatile 8, 19, METATILE_General_RoughWater, 0
	setmetatile 9, 19, METATILE_General_RoughWater, 0
	return

UnusualWeather_EventScript_PlaceTilesRoute125East:: @ 8273AF2
	setmetatile 53, 18, METATILE_General_RoughWater, 0
	setmetatile 54, 18, METATILE_General_RoughWater, 0
	setmetatile 52, 19, METATILE_General_RoughWater, 0
	setmetatile 53, 19, METATILE_General_RoughDeepWater, 0
	setmetatile 54, 19, METATILE_General_RoughDeepWater, 0
	setmetatile 55, 19, METATILE_General_RoughWater, 0
	setmetatile 52, 20, METATILE_General_RoughWater, 0
	setmetatile 53, 20, METATILE_General_RoughDeepWater, 0
	setmetatile 54, 20, METATILE_General_RoughDeepWater, 0
	setmetatile 55, 20, METATILE_General_RoughWater, 0
	setmetatile 53, 21, METATILE_General_RoughWater, 0
	setmetatile 54, 21, METATILE_General_RoughWater, 0
	return

UnusualWeather_EventScript_PlaceTilesRoute127North:: @ 8273B5F
	setmetatile 57, 9, METATILE_General_RoughWater, 0
	setmetatile 58, 9, METATILE_General_RoughWater, 0
	setmetatile 56, 10, METATILE_General_RoughWater, 0
	setmetatile 57, 10, METATILE_General_RoughDeepWater, 0
	setmetatile 58, 10, METATILE_General_RoughDeepWater, 0
	setmetatile 59, 10, METATILE_General_RoughWater, 0
	setmetatile 56, 11, METATILE_General_RoughWater, 0
	setmetatile 57, 11, METATILE_General_RoughDeepWater, 0
	setmetatile 58, 11, METATILE_General_RoughDeepWater, 0
	setmetatile 59, 11, METATILE_General_RoughWater, 0
	setmetatile 57, 12, METATILE_General_RoughWater, 0
	setmetatile 58, 12, METATILE_General_RoughWater, 0
	return

UnusualWeather_EventScript_PlaceTilesRoute127South:: @ 8273BCC
	setmetatile 61, 30, METATILE_General_RoughWater, 0
	setmetatile 62, 30, METATILE_General_RoughWater, 0
	setmetatile 60, 31, METATILE_General_RoughWater, 0
	setmetatile 61, 31, METATILE_General_RoughDeepWater, 0
	setmetatile 62, 31, METATILE_General_RoughDeepWater, 0
	setmetatile 63, 31, METATILE_General_RoughWater, 0
	setmetatile 60, 32, METATILE_General_RoughWater, 0
	setmetatile 61, 32, METATILE_General_RoughDeepWater, 0
	setmetatile 62, 32, METATILE_General_RoughDeepWater, 0
	setmetatile 63, 32, METATILE_General_RoughWater, 0
	setmetatile 61, 33, METATILE_General_RoughWater, 0
	setmetatile 62, 33, METATILE_General_RoughWater, 0
	return

UnusualWeather_EventScript_PlaceTilesRoute129West:: @ 8273C39
	setmetatile 16, 14, METATILE_General_RoughWater, 0
	setmetatile 17, 14, METATILE_General_RoughWater, 0
	setmetatile 15, 15, METATILE_General_RoughWater, 0
	setmetatile 16, 15, METATILE_General_RoughDeepWater, 0
	setmetatile 17, 15, METATILE_General_RoughDeepWater, 0
	setmetatile 18, 15, METATILE_General_RoughWater, 0
	setmetatile 15, 16, METATILE_General_RoughWater, 0
	setmetatile 16, 16, METATILE_General_RoughDeepWater, 0
	setmetatile 17, 16, METATILE_General_RoughDeepWater, 0
	setmetatile 18, 16, METATILE_General_RoughWater, 0
	setmetatile 16, 17, METATILE_General_RoughWater, 0
	setmetatile 17, 17, METATILE_General_RoughWater, 0
	return

UnusualWeather_EventScript_PlaceTilesRoute129East:: @ 8273CA6
	setmetatile 42, 19, METATILE_General_RoughWater, 0
	setmetatile 43, 19, METATILE_General_RoughWater, 0
	setmetatile 41, 20, METATILE_General_RoughWater, 0
	setmetatile 42, 20, METATILE_General_RoughDeepWater, 0
	setmetatile 43, 20, METATILE_General_RoughDeepWater, 0
	setmetatile 44, 20, METATILE_General_RoughWater, 0
	setmetatile 41, 21, METATILE_General_RoughWater, 0
	setmetatile 42, 21, METATILE_General_RoughDeepWater, 0
	setmetatile 43, 21, METATILE_General_RoughDeepWater, 0
	setmetatile 44, 21, METATILE_General_RoughWater, 0
	setmetatile 42, 22, METATILE_General_RoughWater, 0
	setmetatile 43, 22, METATILE_General_RoughWater, 0
	return

UnusualWeather_EventScript_HideMapNamePopup:: @ 8273D13
	setflag FLAG_HIDE_MAP_NAME_POPUP
	return

UnusualWeather_StartKyogreWeather:: @ 8273D17
	setweather WEATHER_RAIN_HEAVY
	return

UnusualWeather_StartGroudonWeather:: @ 8273D1B
	setweather WEATHER_DROUGHT
	return

UnusualWeather_EventScript_EndEventAndCleanup_1:: @ 8273D1F
	lockall
	compare VAR_UNUSUAL_WEATHER_LOCATION, UNUSUAL_WEATHER_KYOGRE_LOCATIONS_START
	goto_if_ge UnusualWeather_EventScript_ShowRainEndedMessage
	goto UnusualWeather_EventScript_ShowSunEndedMessage
	end

UnusualWeather_EventScript_EndEventAndCleanup_2:: @ 8273D31
	closemessage
	fadescreenswapbuffers 1
	setweather WEATHER_SUNNY
	doweather
	call UnusualWeather_EventScript_CleanupMapTiles
	special DrawWholeMapView
	setvar VAR_UNUSUAL_WEATHER_LOCATION, UNUSUAL_WEATHER_NONE
	setvar VAR_SHOULD_END_UNUSUAL_WEATHER, 0
	clearflag FLAG_HIDE_MAP_NAME_POPUP
	fadescreenswapbuffers 0
	releaseall
	end

UnusualWeather_EventScript_ShowRainEndedMessage:: @ 8273D51
	msgbox gText_UnusualWeatherEnded_Rain, MSGBOX_DEFAULT
	goto UnusualWeather_EventScript_EndEventAndCleanup_2
	end

UnusualWeather_EventScript_ShowSunEndedMessage:: @ 8273D5F
	msgbox gText_UnusualWeatherEnded_Sun, MSGBOX_DEFAULT
	goto UnusualWeather_EventScript_EndEventAndCleanup_2
	end

UnusualWeather_EventScript_CleanupMapTiles:: @ 8273D6D
	switch VAR_UNUSUAL_WEATHER_LOCATION
	case UNUSUAL_WEATHER_ROUTE_114_NORTH, UnusualWeather_EventScript_CleanupRoute114North
	case UNUSUAL_WEATHER_ROUTE_114_SOUTH, UnusualWeather_EventScript_CleanupRoute114South
	case UNUSUAL_WEATHER_ROUTE_115_WEST, UnusualWeather_EventScript_CleanupRoute115West
	case UNUSUAL_WEATHER_ROUTE_115_EAST, UnusualWeather_EventScript_CleanupRoute115East
	case UNUSUAL_WEATHER_ROUTE_116_NORTH, UnusualWeather_EventScript_CleanupRoute116North
	case UNUSUAL_WEATHER_ROUTE_116_SOUTH, UnusualWeather_EventScript_CleanupRoute116South
	case UNUSUAL_WEATHER_ROUTE_118_EAST, UnusualWeather_EventScript_CleanupRoute118East
	case UNUSUAL_WEATHER_ROUTE_118_WEST, UnusualWeather_EventScript_CleanupRoute118West
	case UNUSUAL_WEATHER_ROUTE_105_NORTH, UnusualWeather_EventScript_CleanupRoute105North
	case UNUSUAL_WEATHER_ROUTE_105_SOUTH, UnusualWeather_EventScript_CleanupRoute105South
	case UNUSUAL_WEATHER_ROUTE_125_WEST, UnusualWeather_EventScript_CleanupRoute125West
	case UNUSUAL_WEATHER_ROUTE_125_EAST, UnusualWeather_EventScript_CleanupRoute125East
	case UNUSUAL_WEATHER_ROUTE_127_NORTH, UnusualWeather_EventScript_CleanupRoute127North
	case UNUSUAL_WEATHER_ROUTE_127_SOUTH, UnusualWeather_EventScript_CleanupRoute127South
	case UNUSUAL_WEATHER_ROUTE_129_WEST, UnusualWeather_EventScript_CleanupRoute129West
	case UNUSUAL_WEATHER_ROUTE_129_EAST, UnusualWeather_EventScript_CleanupRoute129East
	return

UnusualWeather_EventScript_CleanupRoute114North:: @ 8273E23
	setmetatile 7, 3, METATILE_Fallarbor_RedRockWall, 1
	setmetatile 7, 4, METATILE_Fallarbor_RedRockWall, 1
	return

UnusualWeather_EventScript_CleanupRoute114South:: @ 8273E36
	setmetatile 6, 45, METATILE_Fallarbor_BrownRockWall, 1
	setmetatile 6, 46, METATILE_Fallarbor_BrownRockWall, 1
	return

UnusualWeather_EventScript_CleanupRoute115West:: @ 8273E49
	setmetatile 21, 5, METATILE_Fallarbor_BrownRockWall, 1
	setmetatile 21, 6, METATILE_Fallarbor_BrownRockWall, 1
	return

UnusualWeather_EventScript_CleanupRoute115East:: @ 8273E5C
	setmetatile 36, 9, METATILE_Fallarbor_BrownRockWall, 1
	setmetatile 36, 10, METATILE_Fallarbor_BrownRockWall, 1
	return

UnusualWeather_EventScript_CleanupRoute116North:: @ 8273E6F
	setmetatile 59, 12, METATILE_General_RockWall_RockBase, 1
	setmetatile 59, 13, METATILE_General_RockWall_RockBase, 1
	return

UnusualWeather_EventScript_CleanupRoute116South:: @ 8273E82
	setmetatile 79, 5, METATILE_General_RockWall_RockBase, 1
	setmetatile 79, 6, METATILE_General_RockWall_RockBase, 1
	return

UnusualWeather_EventScript_CleanupRoute118East:: @ 8273E95
	setmetatile 42, 5, METATILE_General_RockWall_RockBase, 1
	setmetatile 42, 6, METATILE_General_RockWall_GrassBase, 1
	return

UnusualWeather_EventScript_CleanupRoute118West:: @ 8273EA8
	setmetatile 9, 5, METATILE_General_RockWall_RockBase, 1
	setmetatile 9, 6, METATILE_General_RockWall_GrassBase, 1
	return

UnusualWeather_EventScript_CleanupRoute105North:: @ 8273EBB
	setmetatile 10, 28, METATILE_General_CalmWater, 0
	setmetatile 11, 28, METATILE_General_CalmWater, 0
	setmetatile 9, 29, METATILE_General_CalmWater, 0
	setmetatile 10, 29, METATILE_General_CalmWater, 0
	setmetatile 11, 29, METATILE_General_CalmWater, 0
	setmetatile 12, 29, METATILE_General_CalmWater, 0
	setmetatile 9, 30, METATILE_General_CalmWater, 0
	setmetatile 10, 30, METATILE_General_CalmWater, 0
	setmetatile 11, 30, METATILE_General_CalmWater, 0
	setmetatile 12, 30, METATILE_General_CalmWater, 0
	setmetatile 10, 31, METATILE_General_CalmWater, 0
	setmetatile 11, 31, METATILE_General_CalmWater, 0
	return

UnusualWeather_EventScript_CleanupRoute105South:: @ 8273F28
	setmetatile 20, 53, METATILE_General_CalmWater, 0
	setmetatile 21, 53, METATILE_General_CalmWater, 0
	setmetatile 19, 54, METATILE_General_CalmWater, 0
	setmetatile 20, 54, METATILE_General_CalmWater, 0
	setmetatile 21, 54, METATILE_General_CalmWater, 0
	setmetatile 22, 54, METATILE_General_CalmWater, 0
	setmetatile 19, 55, METATILE_General_CalmWater, 0
	setmetatile 20, 55, METATILE_General_CalmWater, 0
	setmetatile 21, 55, METATILE_General_CalmWater, 0
	setmetatile 22, 55, METATILE_General_CalmWater, 0
	setmetatile 20, 56, METATILE_General_CalmWater, 0
	setmetatile 21, 56, METATILE_General_CalmWater, 0
	return

UnusualWeather_EventScript_CleanupRoute125West:: @ 8273F95
	setmetatile 8, 16, METATILE_General_CalmWater, 0
	setmetatile 9, 16, METATILE_General_CalmWater, 0
	setmetatile 7, 17, METATILE_General_CalmWater, 0
	setmetatile 8, 17, METATILE_General_CalmWater, 0
	setmetatile 9, 17, METATILE_General_CalmWater, 0
	setmetatile 10, 17, METATILE_General_CalmWater, 0
	setmetatile 7, 18, METATILE_General_CalmWater, 0
	setmetatile 8, 18, METATILE_General_CalmWater, 0
	setmetatile 9, 18, METATILE_General_CalmWater, 0
	setmetatile 10, 18, METATILE_General_CalmWater, 0
	setmetatile 8, 19, METATILE_General_CalmWater, 0
	setmetatile 9, 19, METATILE_General_CalmWater, 0
	return

UnusualWeather_EventScript_CleanupRoute125East:: @ 8274002
	setmetatile 53, 18, METATILE_General_CalmWater, 0
	setmetatile 54, 18, METATILE_General_CalmWater, 0
	setmetatile 52, 19, METATILE_General_CalmWater, 0
	setmetatile 53, 19, METATILE_General_CalmWater, 0
	setmetatile 54, 19, METATILE_General_CalmWater, 0
	setmetatile 55, 19, METATILE_General_CalmWater, 0
	setmetatile 52, 20, METATILE_General_CalmWater, 0
	setmetatile 53, 20, METATILE_General_CalmWater, 0
	setmetatile 54, 20, METATILE_General_CalmWater, 0
	setmetatile 55, 20, METATILE_General_CalmWater, 0
	setmetatile 53, 21, METATILE_General_CalmWater, 0
	setmetatile 54, 21, METATILE_General_CalmWater, 0
	return

UnusualWeather_EventScript_CleanupRoute127North:: @ 827406F
	setmetatile 57, 9, METATILE_General_CalmWater, 0
	setmetatile 58, 9, METATILE_General_CalmWater, 0
	setmetatile 56, 10, METATILE_General_CalmWater, 0
	setmetatile 57, 10, METATILE_General_CalmWater, 0
	setmetatile 58, 10, METATILE_General_CalmWater, 0
	setmetatile 59, 10, METATILE_General_CalmWater, 0
	setmetatile 56, 11, METATILE_General_CalmWater, 0
	setmetatile 57, 11, METATILE_General_CalmWater, 0
	setmetatile 58, 11, METATILE_General_CalmWater, 0
	setmetatile 59, 11, METATILE_General_CalmWater, 0
	setmetatile 57, 12, METATILE_General_CalmWater, 0
	setmetatile 58, 12, METATILE_General_CalmWater, 0
	return

UnusualWeather_EventScript_CleanupRoute127South:: @ 82740DC
	setmetatile 61, 30, METATILE_General_CalmWater, 0
	setmetatile 62, 30, METATILE_General_CalmWater, 0
	setmetatile 60, 31, METATILE_General_CalmWater, 0
	setmetatile 61, 31, METATILE_General_CalmWater, 0
	setmetatile 62, 31, METATILE_General_CalmWater, 0
	setmetatile 63, 31, METATILE_General_CalmWater, 0
	setmetatile 60, 32, METATILE_General_CalmWater, 0
	setmetatile 61, 32, METATILE_General_CalmWater, 0
	setmetatile 62, 32, METATILE_General_CalmWater, 0
	setmetatile 63, 32, METATILE_General_CalmWater, 0
	setmetatile 61, 33, METATILE_General_CalmWater, 0
	setmetatile 62, 33, METATILE_General_CalmWater, 0
	return

UnusualWeather_EventScript_CleanupRoute129West:: @ 8274149
	setmetatile 16, 14, METATILE_General_CalmWater, 0
	setmetatile 17, 14, METATILE_General_CalmWater, 0
	setmetatile 15, 15, METATILE_General_CalmWater, 0
	setmetatile 16, 15, METATILE_General_CalmWater, 0
	setmetatile 17, 15, METATILE_General_CalmWater, 0
	setmetatile 18, 15, METATILE_General_CalmWater, 0
	setmetatile 15, 16, METATILE_General_CalmWater, 0
	setmetatile 16, 16, METATILE_General_CalmWater, 0
	setmetatile 17, 16, METATILE_General_CalmWater, 0
	setmetatile 18, 16, METATILE_General_CalmWater, 0
	setmetatile 16, 17, METATILE_General_CalmWater, 0
	setmetatile 17, 17, METATILE_General_CalmWater, 0
	return

UnusualWeather_EventScript_CleanupRoute129East:: @ 82741B6
	setmetatile 42, 19, METATILE_General_CalmWater, 0
	setmetatile 43, 19, METATILE_General_CalmWater, 0
	setmetatile 41, 20, METATILE_General_CalmWater, 0
	setmetatile 42, 20, METATILE_General_CalmWater, 0
	setmetatile 43, 20, METATILE_General_CalmWater, 0
	setmetatile 44, 20, METATILE_General_CalmWater, 0
	setmetatile 41, 21, METATILE_General_CalmWater, 0
	setmetatile 42, 21, METATILE_General_CalmWater, 0
	setmetatile 43, 21, METATILE_General_CalmWater, 0
	setmetatile 44, 21, METATILE_General_CalmWater, 0
	setmetatile 42, 22, METATILE_General_CalmWater, 0
	setmetatile 43, 22, METATILE_General_CalmWater, 0
	return

UnusualWeather_Underwater_SetupEscapeWarp:: @ 8274223
	switch VAR_UNUSUAL_WEATHER_LOCATION
	case UNUSUAL_WEATHER_ROUTE_105_NORTH, UnusualWeather_Underwater_SetupEscapeWarpRoute105North
	case UNUSUAL_WEATHER_ROUTE_105_SOUTH, UnusualWeather_Underwater_SetupEscapeWarpRoute105South
	case UNUSUAL_WEATHER_ROUTE_125_WEST, UnusualWeather_Underwater_SetupEscapeWarpRoute125West
	case UNUSUAL_WEATHER_ROUTE_125_EAST, UnusualWeather_Underwater_SetupEscapeWarpRoute125East
	case UNUSUAL_WEATHER_ROUTE_127_NORTH, UnusualWeather_Underwater_SetupEscapeWarpRoute127North
	case UNUSUAL_WEATHER_ROUTE_127_SOUTH, UnusualWeather_Underwater_SetupEscapeWarpRoute127South
	case UNUSUAL_WEATHER_ROUTE_129_WEST, UnusualWeather_Underwater_SetupEscapeWarpRoute129West
	case UNUSUAL_WEATHER_ROUTE_129_EAST, UnusualWeather_Underwater_SetupEscapeWarpRoute129East
	return

UnusualWeather_Underwater_SetupEscapeWarpRoute105North:: @ 8274281
	setescapewarp MAP_ROUTE105, 255, 11, 29
	return

UnusualWeather_Underwater_SetupEscapeWarpRoute105South:: @ 827428A
	setescapewarp MAP_ROUTE105, 255, 21, 54
	return

UnusualWeather_Underwater_SetupEscapeWarpRoute125West:: @ 8274293
	setescapewarp MAP_ROUTE125, 255, 9, 17
	return

UnusualWeather_Underwater_SetupEscapeWarpRoute125East:: @ 827429C
	setescapewarp MAP_ROUTE125, 255, 54, 19
	return

UnusualWeather_Underwater_SetupEscapeWarpRoute127North:: @ 82742A5
	setescapewarp MAP_ROUTE127, 255, 58, 10
	return

UnusualWeather_Underwater_SetupEscapeWarpRoute127South:: @ 82742AE
	setescapewarp MAP_ROUTE127, 255, 62, 31
	return

UnusualWeather_Underwater_SetupEscapeWarpRoute129West:: @ 82742B7
	setescapewarp MAP_ROUTE129, 255, 17, 15
	return

UnusualWeather_Underwater_SetupEscapeWarpRoute129East:: @ 82742C0
	setescapewarp MAP_ROUTE129, 255, 43, 20
	return
