
BattleFrontier_BattleDomeBattleRoom_Text_PlayerHasEnteredDome:
	.string "¡Aquí viene {PLAYER}! ¡Encantados de\n"
	.string "tenerte en la CÚPULA BATALLA!$"

BattleFrontier_BattleDomeBattleRoom_Text_PlayerVersusTrainer:
	.string "¡{STR_VAR_1}!\p"
	.string "¡{PLAYER} contra {STR_VAR_2}!\p"
	.string "¡Que comience el duelo!$"

BattleFrontier_BattleDomeBattleRoom_Text_PlayerIsWinner:
	.string "¡¡Ha vencido {PLAYER}!!\n"
	.string "¡¡Enhorabuena!!$"

BattleFrontier_BattleDomeBattleRoom_Text_TrainerIsWinner:
	.string "¡¡Ha vencido {STR_VAR_2}!!\n"
	.string "¡¡Enhorabuena!!$"

BattleFrontier_BattleDomeBattleRoom_Text_PlayerIsLv50Champ:
	.string "¡¡{PLAYER} ha ganado el TORNEO\n"
	.string "de COMBATES de nivel 50!!\p"
	.string "¡¡Enhorabuena!!$"

BattleFrontier_BattleDomeBattleRoom_Text_PlayerIsLvOpenChamp:
	.string "¡¡{PLAYER} ha ganado el TORNEO\n"
	.string "de COMBATES de nivel libre!!\p"
	.string "¡¡Enhorabuena!!$"

BattleFrontier_BattleDomeBattleRoom_Text_RefereeDecisionPleaseWait:
	.string "¡¡¡Qué final más emocionante!!!\n"
	.string "¡Tenemos un K.O. doble!\p"
	.string "En estos casos, las reglas del TORNEO\n"
	.string "de COMBATES establecen que son los\l"
	.string "JUECES los que tienen la última palabra.\p"
	.string "Un segundo, mientras los JUECES\n"
	.string "deliberan…$"

BattleFrontier_BattleDomeBattleRoom_Text_RefereesDecidedWinnerTrainer:
	.string "¡Los JUECES han tomado una decisión!\p"
	.string "El ganador es…\n"
	.string "¡Oh, increíble!\l"
	.string "¡¡El triunfo es para {STR_VAR_1}!!\l"
	.string "¡¡Enhorabuena!!$"

BattleFrontier_BattleDomeBattleRoom_Text_RefereesDecidedWinnerPlayer:
	.string "¡Los JUECES han tomado una decisión!\p"
	.string "El ganador es…\n"
	.string "¡Oh, increíble!\l"
	.string "¡¡El triunfo es para {PLAYER}!!\l"
	.string "¡¡Enhorabuena!!$"

BattleFrontier_BattleDomeBattleRoom_Text_BrightNewHope:
	.string "¡La nueva promesa!\p"
	.string "$"

BattleFrontier_BattleDomeBattleRoom_Text_RisingStar:
	.string "¡La estrella floreciente!\p"
	.string "$"

BattleFrontier_BattleDomeBattleRoom_Text_WillTheyRaceToChampionship:
	.string "¿Será capaz de llegar a la final?\p"
	.string "$"

BattleFrontier_BattleDomeBattleRoom_Text_CanAchieveChampionFirstTry:
	.string "¿Ganará el torneo teniendo en cuenta\n"
	.string "que es la primera vez que participa?\p"
	.string "$"

BattleFrontier_BattleDomeBattleRoom_Text_CanLossBeAvenged:
	.string "¿Podrá vengar su última derrota?\p"
	.string "$"

BattleFrontier_BattleDomeBattleRoom_Text_OnFireForChampionship:
	.string "¡Esta vez parece que se\n"
	.string "ha propuesto ganar el título!\p"
	.string "$"

BattleFrontier_BattleDomeBattleRoom_Text_WinHereAdvancesToFinal:
	.string "¡Una victoria significaría\n"
	.string "entrar en la final!\p"
	.string "$"

BattleFrontier_BattleDomeBattleRoom_Text_WillLongHeldDreamComeTrue:
	.string "¿Podría cumplirse hoy el ansiado\n"
	.string "sueño de ganar una final?\p"
	.string "$"

BattleFrontier_BattleDomeBattleRoom_Text_TheInvincibleChampion:
	.string "¡Rival invencible!\p"
	.string "$"

BattleFrontier_BattleDomeBattleRoom_Text_CanAnyoneHopeToBeatTrainer:
	.string "¿Será posible derrotar a este\n"
	.string "prodigio de la táctica?\p"
	.string "$"

BattleFrontier_BattleDomeBattleRoom_Text_DoBattlesExistSolelyForTrainer:
	.string "¿Habrá alguien capaz\n"
	.string "de hacerle sombra?\p"
	.string "$"

BattleFrontier_BattleDomeBattleRoom_Text_CurrentChampAimingToRetainTitle:
	.string "¡Defendiendo el título y\n"
	.string "con el público en el bolsillo!\p"
	.string "$"

BattleFrontier_BattleDomeBattleRoom_Text_FormerChampHasReturned:
	.string "¡Buscando renovar el título!\p"
	.string "$"

BattleFrontier_BattleDomeBattleRoom_Text_FormerToughnessReturned:
	.string "¡Parece estar de nuevo en forma!\p"
	.string "$"

BattleFrontier_BattleDomeBattleRoom_Text_WillDoExpectedAdvanceToFinals:
	.string "¿Hará lo que se espera\n"
	.string "y llegará a la final?\p"
	.string "$"

BattleFrontier_BattleDomeBattleRoom_Text_WillFormerChampRegainGlory:
	.string "¿Podrá recuperar la gloria perdida\n"
	.string "y renovar un título que fue suyo?\p"
	.string "$"

BattleFrontier_BattleDomeBattleRoom_Text_FeelGlowOfTrueMaster:
	.string "¡Es la definición de maestría!$"

BattleFrontier_BattleDomeBattleRoom_Text_MakeWayForDomeAceTucker:
	.string "Y ahora… El ENTRENADOR que se\n"
	.string "interpone entre {PLAYER} y la gloria…\p"
	.string "¡Sí! ¡El único e irrepetible!\n"
	.string "¡As indiscutible de la CÚPULA BATALLA!\l"
	.string "¡Nuestro auténtico ASTRO de la CÚPULA!\l"
	.string "¡¡Dejad paso a… TACTIO!!$"

BattleFrontier_BattleDomeBattleRoom_Text_SpectatorTuckerChant:
	.string "Público: ¡A la bim, a la bam, a la bim, bom,\n"
	.string "bam! ¡TACTIO, TACTIO y na-die-más!$"

BattleFrontier_BattleDomeBattleRoom_Text_TuckerSilverIntro:
	.string "TACTIO: ¡Ja, ja, ja, ja!\p"
	.string "¿Los oyes? ¡Me adoran!\n"
	.string "¡Están deseando ver nuestro combate!\p"
	.string "¡Ja, ja, ja, ja!\p"
	.string "¡Seguro que te tiemblan las piernas\n"
	.string "sólo de pensar en enfrentarte a mí!\p"
	.string "Bueno, no tienes que preocuparte.\p"
	.string "¡Yo soy el n.º 1 de la CÚPULA BATALLA!\n"
	.string "¡Yo, TACTIO, el ASTRO de la CÚPULA,\l"
	.string "te mostraré mi resplandor!$"

BattleFrontier_BattleDomeBattleRoom_Text_LetsSeeYourStrategy:
	.string "¡Veamos esa táctica tuya!\n"
	.string "¡Enséñamela!$"

BattleFrontier_BattleDomeBattleRoom_Text_IncredibleVictorIsPlayer:
	.string "¡Esto es increíble, señoras y señores!\n"
	.string "¡¡¡Ha ganado {PLAYER}!!!$"

BattleFrontier_BattleDomeBattleRoom_Text_WinnerIsTucker:
	.string "¡El ganador es TACTIO!\n"
	.string "¡Larga vida al ASTRO de la CÚPULA!\p"
	.string "¡Enhorabuena, TACTIO!$"

BattleFrontier_BattleDomeBattleRoom_Text_SeeYourFrontierPass:
	.string "TACTIO: ¡Las reglas son las reglas!\n"
	.string "Enséñame tu PASE del FRENTE.$"

BattleFrontier_BattleDomeBattleRoom_Text_ReceivedTacticsSymbol:
	.string "¡El SÍMBOLO de la TÁCTICA ha sido\n"
	.string "grabado en tu PASE del FRENTE!$"

BattleFrontier_BattleDomeBattleRoom_Text_WontUnderestimateYouNextTime:
	.string "Mmm…\p"
	.string "En verdad que te subestimé. Pero no\n"
	.string "cometeré el mismo error dos veces…$"

BattleFrontier_BattleDomeBattleRoom_Text_CanWinStreakBeStretched:
	.string "¿Podrá prolongar su racha de victorias?\n"
	.string "¡No será por falta de confianza!$"

BattleFrontier_BattleDomeBattleRoom_Text_LegendHasReturnedDomeAceTucker:
	.string "¡Señoras y señores!\n"
	.string "¡Niños, niñas y POKéMON!\p"
	.string "¡Por fin!\n"
	.string "¡Por fin ha vuelto la leyenda!\p"
	.string "¡Sí, todos conocemos su nombre!\n"
	.string "¡Nuestro auténtico ASTRO de la CÚPULA!\l"
	.string "¡Ni más ni menos que el gran TACTIO!$"

BattleFrontier_BattleDomeBattleRoom_Text_TuckerGoldIntro:
	.string "TACTIO: Ah…\n"
	.string "El rugido del público…\l"
	.string "La sangre hirviéndole en las venas…\l"
	.string "Qué lugar tan extraordinario…\p"
	.string "Para ellos, soy el ASTRO de la CÚPULA…\n"
	.string "Yo soy su esperanza y su sueño…\l"
	.string "No puedo permitirme defraudarlos…\p"
	.string "¡Tengo que dar el máximo de mí!\n"
	.string "¡Brillar más, resplandecer más!\l"
	.string "¡Debo deslumbrar a mi público!$"

BattleFrontier_BattleDomeBattleRoom_Text_UnleashAllPowerIPossess:
	.string "¡Voy a descargar todo mi poder!\n"
	.string "¡Aquí y ahora!$"

BattleFrontier_BattleDomeBattleRoom_Text_NeverLostWhenPowerUnleashed:
	.string "TACTIO: ¡Eres realmente increíble!\p"
	.string "¡Nunca! ¡Jamás había perdido en todas\n"
	.string "las veces que descargué mi poder!\p"
	.string "¡Sí, verdaderamente increíble!\n"
	.string "¿Tu PASE del FRENTE, por favor?$"

BattleFrontier_BattleDomeBattleRoom_Text_TacticsSymbolTookGoldenShine:
	.string "¡El SÍMBOLO de la TÁCTICA\n"
	.string "ha adquirido un brillo dorado!$"

BattleFrontier_BattleDomeBattleRoom_Text_LookForwardToNextEncounter:
	.string "Eres fuerte, pero sobre todo,\n"
	.string "posees un algo único.\p"
	.string "Veo en ti el potencial que se necesita\n"
	.string "para ser una superestrella como yo.\p"
	.string "¡Espero impaciente nuestro\n"
	.string "próximo encuentro!$"

@ Unused
BattleFrontier_BattleDomeBattleRoom_Text_PlayerIsLv50Champ2:
	.string "{PLAYER} is the Level 50\n"
	.string "Battle Tournament Champion!\p"
	.string "Congratulations!$"

@ Unused
BattleFrontier_BattleDomeBattleRoom_Text_PlayerIsLvOpenChamp2:
	.string "{PLAYER} is the Open Level\n"
	.string "Battle Tournament Champion!\p"
	.string "Congratulations!$"

BattleFrontier_BattleDomeBattleRoom_Text_PlayerVersusTucker:
	.string "¡El encuentro definitivo!\p"
	.string "¡{PLAYER} contra TACTIO!\p"
	.string "¡Que comience el combate!$"

BattleFrontier_BattleDomeBattleRoom_Text_RefereesDecidedWinnerTucker:
	.string "¡Los JUECES ya han tomado una decisión!\p"
	.string "El ganador es…\n"
	.string "¡Oh, qué extraordinario!\l"
	.string "¡Ha ganado nuestro ASTRO de la CÚPULA!\l"
	.string "¡Ha ganado TACTIO!\p"
	.string "¡Enhorabuena! ¡Y gracias!\n"
	.string "¡Celebremos la gran victoria de TACTIO!$"
