gMapGroup0: @ 8485D60
	.4byte PetalburgCity
	.4byte SlateportCity
	.4byte MauvilleCity
	.4byte RustboroCity
	.4byte FortreeCity
	.4byte LilycoveCity
	.4byte MossdeepCity
	.4byte SootopolisCity
	.4byte EverGrandeCity
	.4byte LittlerootTown
	.4byte OldaleTown
	.4byte DewfordTown
	.4byte LavaridgeTown
	.4byte FallarborTown
	.4byte VerdanturfTown
	.4byte PacifidlogTown
	.4byte Route101
	.4byte Route102
	.4byte Route103
	.4byte Route104
	.4byte Route105
	.4byte Route106
	.4byte Route107
	.4byte Route108
	.4byte Route109
	.4byte Route110
	.4byte Route111
	.4byte Route112
	.4byte Route113
	.4byte Route114
	.4byte Route115
	.4byte Route116
	.4byte Route117
	.4byte Route118
	.4byte Route119
	.4byte Route120
	.4byte Route121
	.4byte Route122
	.4byte Route123
	.4byte Route124
	.4byte Route125
	.4byte Route126
	.4byte Route127
	.4byte Route128
	.4byte Route129
	.4byte Route130
	.4byte Route131
	.4byte Route132
	.4byte Route133
	.4byte Route134
	.4byte Underwater1
	.4byte Underwater2
	.4byte Underwater3
	.4byte Underwater4
	.4byte Underwater5
	.4byte Underwater6
	.4byte Underwater7

gMapGroup1: @ 8485E44
	.4byte LittlerootTown_BrendansHouse_1F
	.4byte LittlerootTown_BrendansHouse_2F
	.4byte LittlerootTown_MaysHouse_1F
	.4byte LittlerootTown_MaysHouse_2F
	.4byte LittlerootTown_ProfessorBirchsLab

gMapGroup2: @ 8485E58
	.4byte OldaleTown_House1
	.4byte OldaleTown_House2
	.4byte OldaleTown_PokemonCenter_1F
	.4byte OldaleTown_PokemonCenter_2F
	.4byte OldaleTown_Mart

gMapGroup3: @ 8485E6C
	.4byte DewfordTown_House1
	.4byte DewfordTown_PokemonCenter_1F
	.4byte DewfordTown_PokemonCenter_2F
	.4byte DewfordTown_Gym
	.4byte DewfordTown_Hall
	.4byte DewfordTown_House2

gMapGroup4: @ 8485E84
	.4byte LavaridgeTown_HerbShop
	.4byte LavaridgeTown_Gym_1F
	.4byte LavaridgeTown_Gym_B1F
	.4byte LavaridgeTown_House
	.4byte LavaridgeTown_Mart
	.4byte LavaridgeTown_PokemonCenter_1F
	.4byte LavaridgeTown_PokemonCenter_2F

gMapGroup5: @ 8485EA0
	.4byte FallarborTown_Mart
	.4byte FallarborTown_BattleTentLobby
	.4byte FallarborTown_BattleTentCorridor
	.4byte FallarborTown_BattleTentBattleRoom
	.4byte FallarborTown_PokemonCenter_1F
	.4byte FallarborTown_PokemonCenter_2F
	.4byte FallarborTown_House1
	.4byte FallarborTown_House2

gMapGroup6: @ 8485EC0
	.4byte VerdanturfTown_BattleTentLobby
	.4byte VerdanturfTown_BattleTentCorridor
	.4byte VerdanturfTown_BattleTentBattleRoom
	.4byte VerdanturfTown_Mart
	.4byte VerdanturfTown_PokemonCenter_1F
	.4byte VerdanturfTown_PokemonCenter_2F
	.4byte VerdanturfTown_WandasHouse
	.4byte VerdanturfTown_FriendshipRatersHouse
	.4byte VerdanturfTown_House

gMapGroup7: @ 8485EE4
	.4byte PacifidlogTown_PokemonCenter_1F
	.4byte PacifidlogTown_PokemonCenter_2F
	.4byte PacifidlogTown_House1
	.4byte PacifidlogTown_House2
	.4byte PacifidlogTown_House3
	.4byte PacifidlogTown_House4
	.4byte PacifidlogTown_House5

gMapGroup8: @ 8485F00
	.4byte PetalburgCity_WallysHouse
	.4byte PetalburgCity_Gym
	.4byte PetalburgCity_House1
	.4byte PetalburgCity_House2
	.4byte PetalburgCity_PokemonCenter_1F
	.4byte PetalburgCity_PokemonCenter_2F
	.4byte PetalburgCity_Mart

gMapGroup9: @ 8485F1C
	.4byte SlateportCity_SternsShipyard_1F
	.4byte SlateportCity_SternsShipyard_2F
	.4byte SlateportCity_BattleTentLobby
	.4byte SlateportCity_BattleTentCorridor
	.4byte SlateportCity_BattleTentBattleRoom
	.4byte SlateportCity_House1
	.4byte SlateportCity_PokemonFanClub
	.4byte SlateportCity_OceanicMuseum_1F
	.4byte SlateportCity_OceanicMuseum_2F
	.4byte SlateportCity_Harbor
	.4byte SlateportCity_House2
	.4byte SlateportCity_PokemonCenter_1F
	.4byte SlateportCity_PokemonCenter_2F
	.4byte SlateportCity_Mart

gMapGroup10: @ 8485F54
	.4byte MauvilleCity_Gym
	.4byte MauvilleCity_BikeShop
	.4byte MauvilleCity_House1
	.4byte MauvilleCity_GameCorner
	.4byte MauvilleCity_House2
	.4byte MauvilleCity_PokemonCenter_1F
	.4byte MauvilleCity_PokemonCenter_2F
	.4byte MauvilleCity_Mart

gMapGroup11: @ 8485F74
	.4byte RustboroCity_DevonCorp_1F
	.4byte RustboroCity_DevonCorp_2F
	.4byte RustboroCity_DevonCorp_3F
	.4byte RustboroCity_Gym
	.4byte RustboroCity_PokemonSchool
	.4byte RustboroCity_PokemonCenter_1F
	.4byte RustboroCity_PokemonCenter_2F
	.4byte RustboroCity_Mart
	.4byte RustboroCity_Flat1_1F
	.4byte RustboroCity_Flat1_2F
	.4byte RustboroCity_House1
	.4byte RustboroCity_CuttersHouse
	.4byte RustboroCity_House2
	.4byte RustboroCity_Flat2_1F
	.4byte RustboroCity_Flat2_2F
	.4byte RustboroCity_Flat2_3F
	.4byte RustboroCity_House3

gMapGroup12: @ 8485FB8
	.4byte FortreeCity_House1
	.4byte FortreeCity_Gym
	.4byte FortreeCity_PokemonCenter_1F
	.4byte FortreeCity_PokemonCenter_2F
	.4byte FortreeCity_Mart
	.4byte FortreeCity_House2
	.4byte FortreeCity_House3
	.4byte FortreeCity_House4
	.4byte FortreeCity_House5
	.4byte FortreeCity_DecorationShop

gMapGroup13: @ 8485FE0
	.4byte LilycoveCity_CoveLilyMotel_1F
	.4byte LilycoveCity_CoveLilyMotel_2F
	.4byte LilycoveCity_LilycoveMuseum_1F
	.4byte LilycoveCity_LilycoveMuseum_2F
	.4byte LilycoveCity_ContestLobby
	.4byte LilycoveCity_ContestHall
	.4byte LilycoveCity_PokemonCenter_1F
	.4byte LilycoveCity_PokemonCenter_2F
	.4byte LilycoveCity_UnusedMart
	.4byte LilycoveCity_PokemonTrainerFanClub
	.4byte LilycoveCity_Harbor
	.4byte LilycoveCity_MoveDeletersHouse
	.4byte LilycoveCity_House1
	.4byte LilycoveCity_House2
	.4byte LilycoveCity_House3
	.4byte LilycoveCity_House4
	.4byte LilycoveCity_DepartmentStore_1F
	.4byte LilycoveCity_DepartmentStore_2F
	.4byte LilycoveCity_DepartmentStore_3F
	.4byte LilycoveCity_DepartmentStore_4F
	.4byte LilycoveCity_DepartmentStore_5F
	.4byte LilycoveCity_DepartmentStoreRooftop
	.4byte LilycoveCity_DepartmentStoreElevator

gMapGroup14: @ 848603C
	.4byte MossdeepCity_Gym
	.4byte MossdeepCity_House1
	.4byte MossdeepCity_House2
	.4byte MossdeepCity_PokemonCenter_1F
	.4byte MossdeepCity_PokemonCenter_2F
	.4byte MossdeepCity_Mart
	.4byte MossdeepCity_House3
	.4byte MossdeepCity_StevensHouse
	.4byte MossdeepCity_House4
	.4byte MossdeepCity_SpaceCenter_1F
	.4byte MossdeepCity_SpaceCenter_2F
	.4byte MossdeepCity_GameCorner_1F
	.4byte MossdeepCity_GameCorner_B1F

gMapGroup15: @ 8486070
	.4byte SootopolisCity_Gym_1F
	.4byte SootopolisCity_Gym_B1F
	.4byte SootopolisCity_PokemonCenter_1F
	.4byte SootopolisCity_PokemonCenter_2F
	.4byte SootopolisCity_Mart
	.4byte SootopolisCity_House1
	.4byte SootopolisCity_House2
	.4byte SootopolisCity_House3
	.4byte SootopolisCity_House4
	.4byte SootopolisCity_House5
	.4byte SootopolisCity_House6
	.4byte SootopolisCity_House7
	.4byte SootopolisCity_LotadAndSeedotHouse
	.4byte SootopolisCity_MysteryEventsHouse_1F
	.4byte SootopolisCity_MysteryEventsHouse_B1F

gMapGroup16: @ 84860AC
	.4byte EverGrandeCity_SidneysRoom
	.4byte EverGrandeCity_PhoebesRoom
	.4byte EverGrandeCity_GlaciasRoom
	.4byte EverGrandeCity_DrakesRoom
	.4byte EverGrandeCity_ChampionsRoom
	.4byte EverGrandeCity_Hall1
	.4byte EverGrandeCity_Hall2
	.4byte EverGrandeCity_Hall3
	.4byte EverGrandeCity_Hall4
	.4byte EverGrandeCity_Hall5
	.4byte EverGrandeCity_PokemonLeague_1F
	.4byte EverGrandeCity_HallOfFame
	.4byte EverGrandeCity_PokemonCenter_1F
	.4byte EverGrandeCity_PokemonCenter_2F
	.4byte EverGrandeCity_PokemonLeague_2F

gMapGroup17: @ 84860E8
	.4byte Route104_MrBrineysHouse
	.4byte Route104_PrettyPetalFlowerShop

gMapGroup18: @ 84860F0
	.4byte Route111_WinstrateFamilysHouse
	.4byte Route111_OldLadysRestStop

gMapGroup19: @ 84860F8
	.4byte Route112_CableCarStation
	.4byte MtChimney_CableCarStation

gMapGroup20: @ 8486100
	.4byte Route114_FossilManiacsHouse
	.4byte Route114_FossilManiacsTunnel
	.4byte Route114_LanettesHouse

gMapGroup21: @ 848610C
	.4byte Route116_TunnelersRestHouse

gMapGroup22: @ 8486110
	.4byte Route117_PokemonDayCare

gMapGroup23: @ 8486114
	.4byte Route121_SafariZoneEntrance

gMapGroup24: @ 8486118
	.4byte MeteorFalls_1F_1R
	.4byte MeteorFalls_1F_2R
	.4byte MeteorFalls_B1F_1R
	.4byte MeteorFalls_B1F_2R
	.4byte RusturfTunnel
	.4byte Underwater_SootopolisCity
	.4byte DesertRuins
	.4byte GraniteCave_1F
	.4byte GraniteCave_B1F
	.4byte GraniteCave_B2F
	.4byte GraniteCave_StevensRoom
	.4byte PetalburgWoods
	.4byte MtChimney
	.4byte JaggedPass
	.4byte FieryPath
	.4byte MtPyre_1F
	.4byte MtPyre_2F
	.4byte MtPyre_3F
	.4byte MtPyre_4F
	.4byte MtPyre_5F
	.4byte MtPyre_6F
	.4byte MtPyre_Exterior
	.4byte MtPyre_Summit
	.4byte AquaHideout_1F
	.4byte AquaHideout_B1F
	.4byte AquaHideout_B2F
	.4byte Underwater_SeafloorCavern
	.4byte SeafloorCavern_Entrance
	.4byte SeafloorCavern_Room1
	.4byte SeafloorCavern_Room2
	.4byte SeafloorCavern_Room3
	.4byte SeafloorCavern_Room4
	.4byte SeafloorCavern_Room5
	.4byte SeafloorCavern_Room6
	.4byte SeafloorCavern_Room7
	.4byte SeafloorCavern_Room8
	.4byte SeafloorCavern_Room9
	.4byte CaveOfOrigin_Entrance
	.4byte CaveOfOrigin_1F
	.4byte CaveOfOrigin_UnusedRubySapphireMap1
	.4byte CaveOfOrigin_UnusedRubySapphireMap2
	.4byte CaveOfOrigin_UnusedRubySapphireMap3
	.4byte CaveOfOrigin_B1F
	.4byte VictoryRoad_1F
	.4byte VictoryRoad_B1F
	.4byte VictoryRoad_B2F
	.4byte ShoalCave_LowTideEntranceRoom
	.4byte ShoalCave_LowTideInnerRoom
	.4byte ShoalCave_LowTideStairsRoom
	.4byte ShoalCave_LowTideLowerRoom
	.4byte ShoalCave_HighTideEntranceRoom
	.4byte ShoalCave_HighTideInnerRoom
	.4byte NewMauville_Entrance
	.4byte NewMauville_Inside
	.4byte AbandonedShip_Deck
	.4byte AbandonedShip_Corridors_1F
	.4byte AbandonedShip_Rooms_1F
	.4byte AbandonedShip_Corridors_B1F
	.4byte AbandonedShip_Rooms_B1F
	.4byte AbandonedShip_Rooms2_B1F
	.4byte AbandonedShip_Underwater1
	.4byte AbandonedShip_Room_B1F
	.4byte AbandonedShip_Rooms2_1F
	.4byte AbandonedShip_CaptainsOffice
	.4byte AbandonedShip_Underwater2
	.4byte AbandonedShip_HiddenFloorCorridors
	.4byte AbandonedShip_HiddenFloorRooms
	.4byte IslandCave
	.4byte AncientTomb
	.4byte Underwater_Route134
	.4byte Underwater_SealedChamber
	.4byte SealedChamber_OuterRoom
	.4byte SealedChamber_InnerRoom
	.4byte ScorchedSlab
	.4byte AquaHideout_UnusedRubyMap1
	.4byte AquaHideout_UnusedRubyMap2
	.4byte AquaHideout_UnusedRubyMap3
	.4byte SkyPillar_Entrance
	.4byte SkyPillar_Outside
	.4byte SkyPillar_1F
	.4byte SkyPillar_2F
	.4byte SkyPillar_3F
	.4byte SkyPillar_4F
	.4byte ShoalCave_LowTideIceRoom
	.4byte SkyPillar_5F
	.4byte SkyPillar_Top
	.4byte MagmaHideout_1F
	.4byte MagmaHideout_2F_1R
	.4byte MagmaHideout_2F_2R
	.4byte MagmaHideout_3F_1R
	.4byte MagmaHideout_3F_2R
	.4byte MagmaHideout_4F
	.4byte MagmaHideout_3F_3R
	.4byte MagmaHideout_2F_3R
	.4byte MirageTower_1F
	.4byte MirageTower_2F
	.4byte MirageTower_3F
	.4byte MirageTower_4F
	.4byte DesertUnderpass
	.4byte ArtisanCave_B1F
	.4byte ArtisanCave_1F
	.4byte Underwater_MarineCave
	.4byte MarineCave_Entrance
	.4byte MarineCave_End
	.4byte TerraCave_Entrance
	.4byte TerraCave_End
	.4byte AlteringCave
	.4byte MeteorFalls_StevensCave

gMapGroup25: @ 84862C8
	.4byte SecretBase_RedCave1
	.4byte SecretBase_BrownCave1
	.4byte SecretBase_BlueCave1
	.4byte SecretBase_YellowCave1
	.4byte SecretBase_Tree1
	.4byte SecretBase_Shrub1
	.4byte SecretBase_RedCave2
	.4byte SecretBase_BrownCave2
	.4byte SecretBase_BlueCave2
	.4byte SecretBase_YellowCave2
	.4byte SecretBase_Tree2
	.4byte SecretBase_Shrub2
	.4byte SecretBase_RedCave3
	.4byte SecretBase_BrownCave3
	.4byte SecretBase_BlueCave3
	.4byte SecretBase_YellowCave3
	.4byte SecretBase_Tree3
	.4byte SecretBase_Shrub3
	.4byte SecretBase_RedCave4
	.4byte SecretBase_BrownCave4
	.4byte SecretBase_BlueCave4
	.4byte SecretBase_YellowCave4
	.4byte SecretBase_Tree4
	.4byte SecretBase_Shrub4
	.4byte SingleBattleColosseum
	.4byte TradeCenter
	.4byte RecordCorner
	.4byte DoubleBattleColosseum
	.4byte LinkContestRoom1
	.4byte UnknownMap_25_29
	.4byte UnknownMap_25_30
	.4byte UnknownMap_25_31
	.4byte UnknownMap_25_32
	.4byte UnknownMap_25_33
	.4byte UnknownMap_25_34
	.4byte LinkContestRoom2
	.4byte LinkContestRoom3
	.4byte LinkContestRoom4
	.4byte LinkContestRoom5
	.4byte LinkContestRoom6
	.4byte InsideOfTruck
	.4byte SSTidalCorridor
	.4byte SSTidalLowerDeck
	.4byte SSTidalRooms
	.4byte BattlePyramidSquare01
	.4byte BattlePyramidSquare02
	.4byte BattlePyramidSquare03
	.4byte BattlePyramidSquare04
	.4byte BattlePyramidSquare05
	.4byte BattlePyramidSquare06
	.4byte BattlePyramidSquare07
	.4byte BattlePyramidSquare08
	.4byte BattlePyramidSquare09
	.4byte BattlePyramidSquare10
	.4byte BattlePyramidSquare11
	.4byte BattlePyramidSquare12
	.4byte BattlePyramidSquare13
	.4byte BattlePyramidSquare14
	.4byte BattlePyramidSquare15
	.4byte BattlePyramidSquare16
	.4byte UnionRoom

gMapGroup26: @ 84863BC
	.4byte SafariZone_Northwest
	.4byte SafariZone_North
	.4byte SafariZone_Southwest
	.4byte SafariZone_South
	.4byte BattleFrontier_OutsideWest
	.4byte BattleFrontier_BattleTowerLobby
	.4byte BattleFrontier_BattleTowerElevator
	.4byte BattleFrontier_BattleTowerCorridor
	.4byte BattleFrontier_BattleTowerBattleRoom
	.4byte SouthernIsland_Exterior
	.4byte SouthernIsland_Interior
	.4byte SafariZone_RestHouse
	.4byte SafariZone_Northeast
	.4byte SafariZone_Southeast
	.4byte BattleFrontier_OutsideEast
	.4byte BattleFrontier_BattleTowerMultiBattleRoom
	.4byte BattleFrontier_BattleTowerCorridor2
	.4byte BattleFrontier_BattleTowerBattleRoom2
	.4byte BattleFrontier_BattleDomeLobby
	.4byte BattleFrontier_BattleDomeCorridor
	.4byte BattleFrontier_BattleDomePreBattleRoom
	.4byte BattleFrontier_BattleDomeBattleRoom
	.4byte BattleFrontier_BattlePalaceLobby
	.4byte BattleFrontier_BattlePalaceCorridor
	.4byte BattleFrontier_BattlePalaceBattleRoom
	.4byte BattleFrontier_BattlePyramidLobby
	.4byte BattleFrontier_BattlePyramidEmptySquare
	.4byte BattleFrontier_BattlePyramidTop
	.4byte BattleFrontier_BattleArenaLobby
	.4byte BattleFrontier_BattleArenaCorridor
	.4byte BattleFrontier_BattleArenaBattleRoom
	.4byte BattleFrontier_BattleFactoryLobby
	.4byte BattleFrontier_BattleFactoryPreBattleRoom
	.4byte BattleFrontier_BattleFactoryBattleRoom
	.4byte BattleFrontier_BattlePikeLobby
	.4byte BattleFrontier_BattlePikeCorridor
	.4byte BattleFrontier_BattlePikeThreePathRoom
	.4byte BattleFrontier_BattlePikeRandomRoom1
	.4byte BattleFrontier_BattlePikeRandomRoom2
	.4byte BattleFrontier_BattlePikeRandomRoom3
	.4byte BattleFrontier_RankingHall
	.4byte BattleFrontier_Lounge1
	.4byte BattleFrontier_BattlePointExchangeServiceCorner
	.4byte BattleFrontier_Lounge2
	.4byte BattleFrontier_Lounge3
	.4byte BattleFrontier_Lounge4
	.4byte BattleFrontier_ScottsHouse
	.4byte BattleFrontier_Lounge5
	.4byte BattleFrontier_Lounge6
	.4byte BattleFrontier_Lounge7
	.4byte BattleFrontier_ReceptionGate
	.4byte BattleFrontier_Lounge8
	.4byte BattleFrontier_Lounge9
	.4byte BattleFrontier_PokemonCenter_1F
	.4byte BattleFrontier_PokemonCenter_2F
	.4byte BattleFrontier_Mart
	.4byte FarawayIsland_Entrance
	.4byte FarawayIsland_Interior
	.4byte BirthIsland_Exterior
	.4byte BirthIsland_Harbor
	.4byte TrainerHill_Entrance
	.4byte TrainerHill_1F
	.4byte TrainerHill_2F
	.4byte TrainerHill_3F
	.4byte TrainerHill_4F
	.4byte TrainerHill_Roof
	.4byte NavelRock_Exterior
	.4byte NavelRock_Harbor
	.4byte NavelRock_Entrance
	.4byte NavelRock_B1F
	.4byte NavelRock_Fork
	.4byte NavelRock_Up1
	.4byte NavelRock_Up2
	.4byte NavelRock_Up3
	.4byte NavelRock_Up4
	.4byte NavelRock_Top
	.4byte NavelRock_Down01
	.4byte NavelRock_Down02
	.4byte NavelRock_Down03
	.4byte NavelRock_Down04
	.4byte NavelRock_Down05
	.4byte NavelRock_Down06
	.4byte NavelRock_Down07
	.4byte NavelRock_Down08
	.4byte NavelRock_Down09
	.4byte NavelRock_Down10
	.4byte NavelRock_Down11
	.4byte NavelRock_Bottom
	.4byte TrainerHill_Elevator

gMapGroup27: @ 8486520
	.4byte Route104_Prototype
	.4byte Route104_PrototypePrettyPetalFlowerShop

gMapGroup28: @ 8486528
	.4byte Route109_SeashoreHouse

gMapGroup29: @ 848652C
	.4byte Route110_TrickHouseEntrance
	.4byte Route110_TrickHouseEnd
	.4byte Route110_TrickHouseCorridor
	.4byte Route110_TrickHousePuzzle1
	.4byte Route110_TrickHousePuzzle2
	.4byte Route110_TrickHousePuzzle3
	.4byte Route110_TrickHousePuzzle4
	.4byte Route110_TrickHousePuzzle5
	.4byte Route110_TrickHousePuzzle6
	.4byte Route110_TrickHousePuzzle7
	.4byte Route110_TrickHousePuzzle8
	.4byte Route110_SeasideCyclingRoadEntrance1
	.4byte Route110_SeasideCyclingRoadEntrance2

gMapGroup30: @ 8486560
	.4byte Route113_GlassWorkshop

gMapGroup31: @ 8486564
	.4byte Route123_BerryMastersHouse

gMapGroup32: @ 8486568
	.4byte Route119_WeatherInstitute_1F
	.4byte Route119_WeatherInstitute_2F
	.4byte Route119_House

gMapGroup33: @ 8486574
	.4byte Route124_DivingTreasureHuntersHouse

	.align 2
gMapGroups:: @ 8486578
	.4byte gMapGroup0
	.4byte gMapGroup1
	.4byte gMapGroup2
	.4byte gMapGroup3
	.4byte gMapGroup4
	.4byte gMapGroup5
	.4byte gMapGroup6
	.4byte gMapGroup7
	.4byte gMapGroup8
	.4byte gMapGroup9
	.4byte gMapGroup10
	.4byte gMapGroup11
	.4byte gMapGroup12
	.4byte gMapGroup13
	.4byte gMapGroup14
	.4byte gMapGroup15
	.4byte gMapGroup16
	.4byte gMapGroup17
	.4byte gMapGroup18
	.4byte gMapGroup19
	.4byte gMapGroup20
	.4byte gMapGroup21
	.4byte gMapGroup22
	.4byte gMapGroup23
	.4byte gMapGroup24
	.4byte gMapGroup25
	.4byte gMapGroup26
	.4byte gMapGroup27
	.4byte gMapGroup28
	.4byte gMapGroup29
	.4byte gMapGroup30
	.4byte gMapGroup31
	.4byte gMapGroup32
	.4byte gMapGroup33

