
MauvilleCity_PokemonCenter_1F_Text_ManOverThereSaysWeirdThings:
	.string "¡Ese hombre de ahí dice unas cosas\n"
	.string "muy raras!\p"
	.string "En cierto modo tiene gracia.\n"
	.string "Creo que no le olvidaré fácilmente.$"

MauvilleCity_PokemonCenter_1F_Text_MyDataUpdatedFromRecordCorner:
	.string "Cuando accedí al CENTRO de RÉCORDS,\n"
	.string "se actualizaron los datos de lo que\l"
	.string "más mola en AZULIZA.\p"
	.string "¡Ahora esos datos son los mismos\n"
	.string "que los de mis amigos!$"

MauvilleCity_PokemonCenter_1F_Text_RecordCornerSoundsFun:
	.string "Han abierto un CENTRO de RÉCORDS\n"
	.string "en la planta de arriba del CENTRO\l"
	.string "POKéMON.\p"
	.string "No sé de qué va, pero suena díver.\n"
	.string "¡Voy a echar un ojo!$"
