BattlePyramidSquare07_EventObjects: @ 853A8C8
	object_event 1, EVENT_OBJ_GFX_LITTLE_BOY_2, 0, 0, 6, 4, MOVEMENT_TYPE_FACE_RIGHT, 1, 1, 1, 6, BattleFrontier_BattlePyramidEmptySquare_EventScript_252C4F, 0
	object_event 2, EVENT_OBJ_GFX_LITTLE_BOY_2, 0, 4, 0, 4, MOVEMENT_TYPE_FACE_DOWN_AND_LEFT, 1, 1, 1, 4, BattleFrontier_BattlePyramidEmptySquare_EventScript_252C4F, 0
	object_event 3, EVENT_OBJ_GFX_LITTLE_BOY_2, 0, 6, 0, 4, MOVEMENT_TYPE_FACE_DOWN, 1, 1, 1, 3, BattleFrontier_BattlePyramidEmptySquare_EventScript_252C4F, 0
	object_event 4, EVENT_OBJ_GFX_LITTLE_BOY_2, 0, 4, 4, 4, MOVEMENT_TYPE_FACE_UP_AND_LEFT, 1, 1, 1, 4, BattleFrontier_BattlePyramidEmptySquare_EventScript_252C4F, 0
	object_event 5, EVENT_OBJ_GFX_ITEM_BALL, 0, 7, 4, 4, MOVEMENT_TYPE_LOOK_AROUND, 1, 1, 0, 0, BattleFrontier_BattlePyramidEmptySquare_EventScript_252C6A, 0
	object_event 6, EVENT_OBJ_GFX_ITEM_BALL, 0, 1, 1, 4, MOVEMENT_TYPE_LOOK_AROUND, 1, 1, 0, 0, BattleFrontier_BattlePyramidEmptySquare_EventScript_252C6A, 0
	object_event 7, EVENT_OBJ_GFX_ITEM_BALL, 0, 3, 7, 4, MOVEMENT_TYPE_LOOK_AROUND, 1, 1, 0, 0, BattleFrontier_BattlePyramidEmptySquare_EventScript_252C6A, 0

BattlePyramidSquare07_MapEvents:: @ 853A970
	map_events BattlePyramidSquare07_EventObjects, 0x0, 0x0, 0x0

