
TrainerHill_Entrance_Text_StillGettingReady:
	.string "Ésta es la COLINA DESAFÍO.\n"
	.string "Aquí podrás enfrentarte a otros\l"
	.string "ENTRENADORES en una carrera\l"
	.string "por llegar arriba lo antes posible.\p"
	.string "Por desgracia, aún no está preparado\n"
	.string "todo. Pásate por aquí en otro momento.$"

TrainerHill_Entrance_Text_WelcomeToTrainerHill:
	.string "¡Te damos la bienvenida!\p"
	.string "Ésta es la COLINA DESAFÍO.\n"
	.string "Aquí podrás enfrentarte a otros\l"
	.string "ENTRENADORES en una carrera\l"
	.string "por llegar arriba lo antes posible.$"

TrainerHill_Entrance_Text_SaveGameBeforeEnter:
	.string "¿Es la primera vez que vienes?\p"
	.string "Antes de entrar, debes\n"
	.string "guardar la partida.$"

TrainerHill_Entrance_Text_TrainersUpToFloorX:
	.string "Veamos…\n"
	.string "Los ENTRENADORES están ahora…\p"
	.string "Hasta el nivel {STR_VAR_1}.$"

TrainerHill_Entrance_Text_TrainersInEveryRoom:
	.string "Veamos…\n"
	.string "Los ENTRENADORES están ahora…\p"
	.string "¡Vaya, parece que hay ENTRENADORES\n"
	.string "en todos los niveles!$"

TrainerHill_Entrance_Text_LikeToChallengeTrainers:
	.string "¿Quieres enfrentarte a ellos?$"

TrainerHill_Entrance_Text_TimeProgessGetSetGo:
	.string "Cronometraré tu tiempo.\n"
	.string "¡Suerte!\p"
	.string "A la una…\p"
	.string "A las dos…\p"
	.string "¡Y a las tres!$"

TrainerHill_Entrance_Text_PleaseVisitUsAgain:
	.string "¡Vuelve cuando quieras!$"

TrainerHill_Entrance_Text_TooBadTremendousEffort:
	.string "Qué pena…\p"
	.string "La verdad es que te has esforzado\n"
	.string "mucho.\p"
	.string "¡Bueno, otra vez será!$"

TrainerHill_Entrance_Text_HopeYouGiveItYourBest:
	.string "¡Demuestra lo que sabes!$"

TrainerHill_Entrance_Text_MovedReceptionHereForSwitch:
	.string "Cuando los ENTRENADORES se\n"
	.string "cambian de sitio, organizan una…\l"
	.string "tremenda.\p"
	.string "Para evitar tanto follón pusimos\n"
	.string "la recepción aquí.\p"
	.string "Disculpa las molestias.$"

TrainerHill_Entrance_Text_ThankYouForPlaying:
	.string "¡Gracias por participar!$"

TrainerHill_Entrance_Text_ExplainTrainerHill:
	.string "En la COLINA DESAFÍO, los participantes\n"
	.string "compiten en la llamada “contrarreloj”.\p"
	.string "Es una carrera donde se cuenta\n"
	.string "el tiempo que tardas en llegar\l"
	.string "desde aquí hasta la azotea,\l"
	.string "donde te espera el dueño del local.\p"
	.string "Los récords de cada categoría están\n"
	.string "expuestos en el PANEL de TIEMPOS.\l"
	.string "¡Demuestra que no hay nadie\l"
	.string "más veloz que tú!\p"
	.string "En los combates que libres contra\n"
	.string "los ENTRENADORES que te encuentres\l"
	.string "en el ascenso, no ganarás ni dinero\l"
	.string "ni puntos de EXPERIENCIA.$"

@ Unused
TrainerHill_Entrance_Text_NeedAtLeastTwoPokemon:
	.string "Oh, I’m sorry, but you appear to have\n"
	.string "only one POKéMON with you.\p"
	.string "You will need at least two POKéMON\n"
	.string "to enter this event.$"

TrainerHill_Roof_Text_YouFinallyCameBravo:
	.string "¡Mmm!\p"
	.string "¡Por fin has llegado!\n"
	.string "¡Ya estás aquí!\p"
	.string "¡Espera! ¡No me lo digas!\n"
	.string "¡Ya sé por qué has subido\l"
	.string "corriendo hasta aquí!\p"
	.string "Querías verme a mí, al propietario\n"
	.string "de la COLINA DESAFÍO, porque…\p"
	.string "¡Quieres luchar a mi lado!\n"
	.string "¡¿A que sí?!\p"
	.string "¿Mmm?\n"
	.string "¿Cómo? ¿Que no ha sido por eso?\p"
	.string "Bueno, da igual, he visto cómo subías.\n"
	.string "¡Bien luchado! ¡Bravo! ¡Bravo!$"

TrainerHill_Roof_Text_HaveTheMostMarvelousGift:
	.string "Para alguien tan extraordinario,\n"
	.string "¡tengo un regalo extraordinario!$"

TrainerHill_Roof_Text_FullUpBeBackLaterForThis:
	.string "Oh, no, ¡no tienes sitio para nada!\n"
	.string "¡Vuelve cuando lo tengas!$"

TrainerHill_Roof_Text_GotHereMarvelouslyQuickly:
	.string "¡Oh, espera un momento! ¿De verdad\n"
	.string "has conseguido llegar aquí tan rápido?\p"
	.string "¡Espléndido! ¡Pero no tenías que\n"
	.string "correr tanto para venir a verme!\p"
	.string "Aunque es un detalle, claro.\n"
	.string "¡Le pediré a la chica de recepción\l"
	.string "que actualice el PANEL de TIEMPOS!$"

TrainerHill_Roof_Text_YouWerentVeryQuick:
	.string "Pero bueno…\n"
	.string "No parece que hayas corrido mucho…$"

TrainerHill_Roof_Text_ArriveZippierNextTime:
	.string "¿Sabes? Creo que me alegraría más\n"
	.string "si llegases más rápido la próxima vez.\p"
	.string "¡Seguro que hasta me animaba\n"
	.string "a formar un equipo contigo!\p"
	.string "¡Hasta entonces!$"

@ Unused
TrainerHill_Roof_Text_BuiltTrainerHillToFindPartner:
	.string "I had the TRAINER HILL built for but\n"
	.string "one reason and one only!\p"
	.string "To find the most suitable partner\n"
	.string "with whom I may form a tag team!$"

TrainerHill_Entrance_Text_ChallengeTime:
	.string "{STR_VAR_1} min {STR_VAR_2},{STR_VAR_3} s$"

TrainerHill_Entrance_Text_WhatSortOfTrainersAreAhead:
	.string "No sé qué clase de ENTRENADORES\n"
	.string "y de POKéMON esperan ahí arriba.\p"
	.string "¡Lo que sí sé es que no dejaré que\n"
	.string "nadie se interponga en mi camino!$"

TrainerHill_Entrance_Text_CantWaitToTestTheWaters:
	.string "He oído que a esta COLINA DESAFÍO\n"
	.string "vienen ENTRENADORES de todas partes.\p"
	.string "¡Estoy deseando probar!\p"
	.string "¡Voy a quitar de en medio a todos\n"
	.string "los que se me pongan por delante!$"

TrainerHill_Entrance_Text_FriendsTryingToReachTimeBoardTop:
	.string "¿Has visto el PANEL de TIEMPOS de ahí?\p"
	.string "Mis amigos y yo estamos a ver quién\n"
	.string "consigue llegar arriba en menos tiempo.$"

TrainerHill_Entrance_Text_DoYouKnowWhenTheyOpen:
	.string "¿Tienes idea de cuándo\n"
	.string "van a abrir este sitio?\p"
	.string "¡Quiero ser la primera de todos\n"
	.string "en competir aquí!$"

TrainerHill_Elevator_Text_ReturnToReception:
	.string "¿Quieres volver a la recepción?$"
