
BattleFrontier_BattlePalaceLobby_Text_WelcomeForSingleBattle:
	.string "¡Aquí ponemos a prueba el ánimo\n"
	.string "y el arrojo de los ENTRENADORES!\p"
	.string "¡Te doy la bienvenida\n"
	.string "al PALACIO BATALLA!\p"
	.string "Yo soy el guía del COMBATE\n"
	.string "sin TUTELA INDIVIDUAL.$"

BattleFrontier_BattlePalaceLobby_Text_TakeSingleBattleChallenge:
	.string "¿Aceptas el desafío del COMBATE\n"
	.string "sin TUTELA INDIVIDUAL?$"

BattleFrontier_BattlePalaceLobby_Text_ExplainSingleBattleChallenge:
	.string "En el PALACIO BATALLA, hay varias\n"
	.string "salas donde se celebran COMBATES\l"
	.string "sin TUTELA INDIVIDUALES.\p"
	.string "Los COMBATES sin TUTELA sólo se\n"
	.string "distinguen de los normales\l"
	.string "por una regla de obligado cumplimiento:\p"
	.string "Los ENTRENADORES sólo pueden\n"
	.string "cambiar de POKéMON.\p"
	.string "Es decir, los ENTRENADORES no pueden\n"
	.string "dar órdenes a sus POKéMON.\p"
	.string "De este modo, se deja que los POKéMON\n"
	.string "combatan solos, según su naturaleza.\p"
	.string "Debes confiar en tus POKéMON\n"
	.string "y vigilar para que nada les pase.\p"
	.string "Si logras derrotar consecutivamente\n"
	.string "a siete ENTRENADORES, obtendrás\l"
	.string "PUNTOS de BATALLA.\p"
	.string "Si quieres interrumpir el desafío,\n"
	.string "no olvides guardar antes la partida.\p"
	.string "Si no la guardas, se te descalificará.$"

BattleFrontier_BattlePalaceLobby_Text_ReturnWhenFortified:
	.string "Vuelve cuando tu ánimo y tus POKéMON\n"
	.string "sean más fuertes.$"

BattleFrontier_BattlePalaceLobby_Text_WhichChallenge:
	.string "Hay dos niveles de COMBATE sin TUTELA:\n"
	.string "el nivel 50 y el nivel libre. ¿Cuál eliges?$"

BattleFrontier_BattlePalaceLobby_Text_NotEnoughValidMonsLv50:
	.string "Lo lamento…\p"
	.string "No tienes tres POKéMON que puedan\n"
	.string "participar en este desafío.\p"
	.string "Necesitas tres POKéMON diferentes\n"
	.string "de nivel 50 o inferior.\p"
	.string "Además, deben sostener distintos\n"
	.string "tipos de objeto.\p"
	.string "Los HUEVOS{STR_VAR_1} participar.\p"
	.string "Vuelve cuando cumplas las condiciones\n"
	.string "para aceptar el desafío.$"

BattleFrontier_BattlePalaceLobby_Text_NotEnoughValidMonsLvOpen:
	.string "Lo lamento…\p"
	.string "No tienes tres POKéMON que puedan\n"
	.string "participar en este desafío.\p"
	.string "Necesitas tres POKéMON diferentes\n"
	.string "para poder participar.\p"
	.string "Además, deben sostener distintos\n"
	.string "tipos de objeto.\p"
	.string "Los HUEVOS{STR_VAR_1} participar.\p"
	.string "Vuelve cuando cumplas las condiciones\n"
	.string "para aceptar el desafío.$"

BattleFrontier_BattlePalaceLobby_Text_NowSelectThreeMons:
	.string "Selecciona los tres POKéMON\n"
	.string "con los que quieres combatir.$"

BattleFrontier_BattlePalaceLobby_Text_MustSaveBeforeChallenge2:
	.string "Antes de participar en el COMBATE sin\n"
	.string "TUTELA, debes guardar la partida…$"

BattleFrontier_BattlePalaceLobby_Text_FollowMe:
	.string "Bien.\n"
	.string "Vamos, pues.$"

BattleFrontier_BattlePalaceLobby_Text_ResultsWillBeRecorded:
	.string "Ha sido un honor ver combatir\n"
	.string "a tus POKéMON.\p"
	.string "Ahora debemos guardar los resultados.\n"
	.string "Un segundo, por favor.$"

BattleFrontier_BattlePalaceLobby_Text_FirmTrueBondsFor7WinStreak:
	.string "Has logrado una racha de 7 victorias…\p"
	.string "Sin duda, existe un fuerte vínculo\n"
	.string "entre tus POKéMON y tú.$"

BattleFrontier_BattlePalaceLobby_Text_FeatWillBeRecorded:
	.string "Vamos a guardar tu récord.\n"
	.string "Espera unos instantes.$"

@ Unused
BattleFrontier_BattlePalaceLobby_Text_BattlePointsFor7WinStreak:
	.string "For the feat of your 7-win streak,\n"
	.string "we present you with Battle Point(s).$"

BattleFrontier_BattlePalaceLobby_Text_NoSpaceForPrize:
	.string "Lástima, parece que no tienes sitio\n"
	.string "para guardar nuestro premio.\p"
	.string "No te olvides de volver cuando\n"
	.string "tengas sitio en la MOCHILA.$"

BattleFrontier_BattlePalaceLobby_Text_WeHaveBeenWaiting:
	.string "Te estábamos esperando…$"

BattleFrontier_BattlePalaceLobby_Text_MustSaveBeforeChallenge:
	.string "Antes de participar en el COMBATE sin\n"
	.string "TUTELA, debes guardar la partida…$"

BattleFrontier_BattlePalaceLobby_Text_FailedToSaveBeforeEndingChallenge:
	.string "Lo lamento…\p"
	.string "No debiste de guardar la partida antes\n"
	.string "de abandonar el desafío…\p"
	.string "Me temo que, por tanto, se te ha\n"
	.string "descalificado…$"

@ Unused
BattleFrontier_BattlePalaceLobby_Text_ReceivedPrize:
	.string "{PLAYER} received the prize\n"
	.string "{STR_VAR_1}.$"

BattleFrontier_BattlePalaceLobby_Text_LadyCanTellWhatMonsThink:
	.string "Para los tipos robustos como yo,\n"
	.string "los POKéMON robustos son los mejores.\p"
	.string "¡La mejor defensa es un buen ataque!\n"
	.string "¡Y un ataque incesante es aún mejor!\p"
	.string "Pero yo no quería hablarte de esto.\p"
	.string "De vez en cuando pasa por aquí\n"
	.string "una señorita realmente hermosa.\p"
	.string "Ella dice que puede adivinar lo\n"
	.string "que piensan los POKéMON.\p"
	.string "No sé si será verdad lo que dice,\n"
	.string "pero es que es guapa de verdad.\p"
	.string "¿Eh?\n"
	.string "¿Por qué me miras así?$"

BattleFrontier_BattlePalaceLobby_Text_NatureAndMovesKeyHere:
	.string "Mmm…\p"
	.string "Parece que la clave para ganar\n"
	.string "combates en este sitio está\l"
	.string "en la naturaleza de los POKéMON\l"
	.string "y en los movimientos que han aprendido.\p"
	.string "Concretamente, en lo bien que se\n"
	.string "corresponden los movimientos del\l"
	.string "POKéMON con su naturaleza.\p"
	.string "Si un POKéMON tiene problemas y no\n"
	.string "rinde como se espera de él, a lo mejor\l"
	.string "es que los movimientos que usa no\l"
	.string "tienen nada que ver con su naturaleza.$"

BattleFrontier_BattlePalaceLobby_Text_MonDocileButTransforms:
	.string "Mi POKéMON suele ser muy dócil.\p"
	.string "Pero, oye, cuando participa en un\n"
	.string "COMBATE sin TUTELA, es como si se\l"
	.string "transformara en una bestia salvaje.\p"
	.string "Se vuelve muy agresivo.\n"
	.string "Da miedo verlo.$"

BattleFrontier_BattlePalaceLobby_Text_WhatNatureFavorsChippingAway:
	.string "Me preguntaba qué clase de naturaleza\n"
	.string "tendrá un POKéMON que hace más y más\l"
	.string "débiles a sus rivales hasta agotarlos.\p"
	.string "Me sorprendería que fuese\n"
	.string "de naturaleza FLOJA.\p"
	.string "Pero, bah, no puede ser.$"

BattleFrontier_BattlePalaceLobby_Text_WelcomeForDoubleBattle:
	.string "¡Aquí ponemos a prueba el ánimo\n"
	.string "y el arrojo de los ENTRENADORES!\p"
	.string "¡Te doy la bienvenida\n"
	.string "al PALACIO BATALLA!\p"
	.string "Yo soy el guía del COMBATE\n"
	.string "sin TUTELA DOBLE.$"

BattleFrontier_BattlePalaceLobby_Text_TakeDoubleBattleChallenge:
	.string "¿Aceptas el desafío del COMBATE\n"
	.string "sin TUTELA DOBLE?$"

BattleFrontier_BattlePalaceLobby_Text_ExplainDoubleBattleChallenge:
	.string "En el PALACIO BATALLA, hay varias\n"
	.string "salas donde se celebran COMBATES\l"
	.string "sin TUTELA DOBLES.\p"
	.string "Los COMBATES sin TUTELA sólo se\n"
	.string "distinguen de los normales\l"
	.string "por una regla de obligado cumplimiento:\p"
	.string "Los ENTRENADORES sólo pueden\n"
	.string "cambiar de POKéMON.\p"
	.string "Es decir, los ENTRENADORES no pueden\n"
	.string "dar órdenes a sus POKéMON.\p"
	.string "De este modo, se deja que los POKéMON\n"
	.string "combatan solos, según su naturaleza.\p"
	.string "Debes confiar en tus POKéMON\n"
	.string "y vigilar para que nada les pase.\p"
	.string "Si logras derrotar consecutivamente\n"
	.string "a siete ENTRENADORES, obtendrás\l"
	.string "PUNTOS de BATALLA.\p"
	.string "Si quieres interrumpir el desafío,\n"
	.string "no olvides guardar antes la partida.\p"
	.string "Si no la guardas, se te descalificará.$"

BattleFrontier_BattlePalaceLobby_Text_ToDefeatMavenAnd7Trainers:
	.string "Derrotado el AMO del PALACIO y, con él,\n"
	.string "siete ENTRENADORES consecutivos…$"

BattleFrontier_BattlePalaceLobby_Text_PresentYouWithBattlePoints:
	.string "Debemos hacer honor al vínculo\n"
	.string "que has forjado entre tú y tus POKéMON,\l"
	.string "y premiarlo con PUNTOS de BATALLA.$"

BattleFrontier_BattlePalaceLobby_Text_LikeToRecordMatch:
	.string "¿Quieres grabar tu último\n"
	.string "enfrentamiento del PALACIO BATALLA\l"
	.string "en tu PASE del FRENTE?$"

BattleFrontier_BattlePalaceLobby_Text_RulesAreListed:
	.string "Son las reglas del COMBATE sin TUTELA.$"

BattleFrontier_BattlePalaceLobby_Text_ReadWhichHeading:
	.string "¿Qué capítulo quieres leer?$"

BattleFrontier_BattlePalaceLobby_Text_ExplainRulesBasics:
	.string "Aquí, los POKéMON deberán pensar\n"
	.string "y combatir por sí mismos.\p"
	.string "A diferencia de los POKéMON salvajes,\n"
	.string "los que viven con gente se comportan\l"
	.string "de manera distinta según su naturaleza.$"

BattleFrontier_BattlePalaceLobby_Text_ExplainRulesNature:
	.string "Según su naturaleza, un POKéMON puede\n"
	.string "atacar sin medir las consecuencias.\p"
	.string "Mientras que otro preferirá protegerse\n"
	.string "en lugar de atacar.\p"
	.string "Y otro puede que prefiera irritar\n"
	.string "o confundir a sus oponentes.\p"
	.string "Según su naturaleza, cada POKéMON\n"
	.string "tendrá unos movimientos preferidos,\l"
	.string "que sabrá usar muy bien.\p"
	.string "Igualmente, puede que deteste ciertos\n"
	.string "movimientos que le resultan difíciles.$"

BattleFrontier_BattlePalaceLobby_Text_ExplainRulesMoves:
	.string "Existen movimientos ofensivos que\n"
	.string "infligen un daño directo al enemigo.\p"
	.string "Hay movimientos defensivos que sirven\n"
	.string "para prepararse ante ataques enemigos,\l"
	.string "curar PS, etc.\p"
	.string "Existen también otros movimientos\n"
	.string "que pueden alterar el estado del rival\l"
	.string "con envenenamiento, parálisis, etc.\p"
	.string "Los POKéMON usarán movimientos\n"
	.string "de una de estas tres categorías.$"

BattleFrontier_BattlePalaceLobby_Text_ExplainRulesUnderpowered:
	.string "Cuando no está bajo el control de su\n"
	.string "ENTRENADOR, un POKéMON puede ser\l"
	.string "incapaz de usar ciertos movimientos.\p"
	.string "A los POKéMON no les gusta usar\n"
	.string "movimientos impropios de su naturaleza.\p"
	.string "Si un POKéMON sólo conoce movimientos\n"
	.string "ajenos a su naturaleza, es probable que\l"
	.string "nunca llegue a demostrar su valía.$"

BattleFrontier_BattlePalaceLobby_Text_ExplainRulesWhenInDanger:
	.string "Cuando un POKéMON está en peligro,\n"
	.string "es posible que decida usar movimientos\l"
	.string "que sean ajenos a su naturaleza.\p"
	.string "Si un POKéMON comienza a comportarse\n"
	.string "de modo extraño en un momento de apuro,\l"
	.string "no lo pierdas de vista.$"
