
SootopolisCity_Text_GymSign:
	.string "ARENE POKéMON d’ATALANOPOLIS\n"
	.string "CHAMPION: JUAN\p"
	.string "“Le DRESSEUR à la beauté pure.”$"

SootopolisCity_Text_CitySign:
	.string "ATALANOPOLIS\p"
	.string "“La ville mystique où sommeille\n"
	.string "l’histoire.”$"

SootopolisCity_Text_DoorIsClosed:
	.string "La porte est fermée.$"

SootopolisCity_Text_PhysicallyFitLivingHere:
	.string "Plonger dans la mer. Toujours monter et\n"
	.string "descendre les escaliers…\p"
	.string "Quand tu habites dans cette ville,\n"
	.string "tu finis par être musclé.$"

SootopolisCity_Text_GiantPokemonSuddenlyAppeared:
	.string "Ces POKéMON géants sont apparus d’un\n"
	.string "coup au milieu de la ville!\p"
	.string "J’les avais jamais vus!\p"
	.string "Mais pourquoi ils se battent comme ça?\p"
	.string "Ils pourraient essayer d’être copains!$"

SootopolisCity_Text_WhatIsThatGreenPokemon:
	.string "QUOI? Quoi?\n"
	.string "C’est quoi ce POKéMON vert?$"

SootopolisCity_Text_WhereDidLegendariesGo:
	.string "GROUDON et KYOGRE…\n"
	.string "Où sont-ils partis?\p"
	.string "Est-ce qu’ils sont allés provoquer\n"
	.string "des sécheresses ou des pluies\l"
	.string "torrentielles ailleurs?$"

SootopolisCity_Text_TwoPokemonArentAngry:
	.string "J’ai l’impression que ces POKéMON\n"
	.string "ne sont pas vraiment fâchés.\p"
	.string "Je pense juste qu’ils ne peuvent pas\n"
	.string "contrôler leur puissance…$"

SootopolisCity_Text_FlyingMonStoppedRampage:
	.string "Ce POKéMON volant est descendu\n"
	.string "du ciel et a calmé les deux autres…$"

SootopolisCity_Text_WonderWhatWorldIsLike:
	.string "Je… Je ne suis jamais sorti de la ville.\p"
	.string "Je me demande à quoi ressemble le monde\n"
	.string "de l’autre côté de ce ciel rond.$"

SootopolisCity_Text_ThisIsWicked:
	.string "Waouh!\n"
	.string "C’est incroyable!$"

SootopolisCity_Text_ThatWasWicked:
	.string "Waouh!\n"
	.string "C’était incroyable!$"

SootopolisCity_Text_GoRedAndBlueMon:
	.string "Allez le POKéMON rouge!\n"
	.string "Ne te laisse pas faire POKéMON bleu!$"

SootopolisCity_Text_DoYouKnowMonNames:
	.string "… … … … … …\p"
	.string "Salut, tu connais le nom des POKéMON\n"
	.string "en train de se battre là-bas?$"

SootopolisCity_Text_GreenOneSettlesThings:
	.string "Je me demandais qui gagnerait ce\n"
	.string "combat, le bleu ou le rouge…\p"
	.string "Mais c’est le vert qui a tout arrangé!\p"
	.string "Tu parles d’un retournement de\n"
	.string "situation!$"

SootopolisCity_Text_SeeingLegendWithOwnEyes:
	.string "Une ancienne légende raconte que la\n"
	.string "terre et la mer auraient été formées\p"
	.string "par un combat colossal entre\n"
	.string "deux POKéMON.\p"
	.string "J’ai l’impression que c’est ce qui est\n"
	.string "en train de se passer sous mes yeux!\p"
	.string "Waouh, je n’aurais jamais pensé pouvoir\n"
	.string "assister à quelque chose comme ça!$"

SootopolisCity_Text_SawLegendWithOwnEyes:
	.string "Une ancienne légende raconte que la\n"
	.string "terre et la mer auraient été formées\p"
	.string "par un combat colossal entre\n"
	.string "deux POKéMON.\p"
	.string "Eh bien, j’ai pu assister à cette scène\n"
	.string "de mes propres yeux!\p"
	.string "Waouh, je n’aurais jamais pensé pouvoir\n"
	.string "assister à quelque chose comme ça!$"

SootopolisCity_Text_BigPokemonFighting:
	.string "Un gros POKéMON se bat contre\n"
	.string "un autre gros POKéMON!\p"
	.string "Il faut que quelqu’un fasse\n"
	.string "quelque chose!$"

SootopolisCity_Text_PrettyMonCameFromSky:
	.string "Un joli POKéMON est descendu du ciel.$"

SootopolisCity_Text_SootopolisWillBeWrecked:
	.string "Oh non!\n"
	.string "ATALANOPOLIS va être détruite!$"

SootopolisCity_Text_SootopolisDidntGetWrecked:
	.string "ATALANOPOLIS n’a pas été détruite!$"

SootopolisCity_Text_NoOrdinaryTourist:
	.string "Hum! Tu as fait tout le trajet jusqu’à\n"
	.string "ATALANOPOLIS?\p"
	.string "Tu n’es pas un touriste ordinaire.\p"
	.string "Mais je suppose que ça ne fait pas de\n"
	.string "toi un touriste d’exception non plus.$"

SootopolisCity_Text_CityRegainedCalm:
	.string "La ville a retrouvé son calme…$"

SootopolisCity_Text_CaveOfOriginPleaseLeave:
	.string "Qui peux-tu bien être?\p"
	.string "C’est la GROTTE ORIGINE.\p"
	.string "Les esprits de POKéMON, qui reposent\n"
	.string "au MONT MEMORIA, reprendraient vie ici.\p"
	.string "Il faudrait que tu partes.$"

SootopolisCity_Text_LeadSuperiorTrainerToCave:
	.string "Une personne d’une grande volonté et\n"
	.string "aux capacités supérieures…\p"
	.string "Un DRESSEUR d’expérience et\n"
	.string "connaissant de nombreuses espèces\l"
	.string "de POKéMON…\p"
	.string "Si une telle personne devait se\n"
	.string "présenter, MARC m’a demandé de\l"
	.string "la conduire dans cette GROTTE.$"

SootopolisCity_Text_AwakenedPokemonClash:
	.string "Incroyable…\p"
	.string "Le combat entre les deux POKéMON\n"
	.string "a été stoppé par l’arrivée d’un\l"
	.string "troisième POKéMON…$"

SootopolisCity_Text_CaveOfOriginSleepsToo:
	.string "C’est la GROTTE ORIGINE…\p"
	.string "Une fois la crise passée, la GROTTE\n"
	.string "aussi devrait retrouver son calme…$"

SootopolisCity_Text_SootopolisSkyBeautiful:
	.string "ATALANOPOLIS s’élève telle une ville\n"
	.string "dans le cratère d’un volcan.\p"
	.string "Quand tu lèves les yeux au ciel, tu\n"
	.string "distingues aussi le bord du cratère.\p"
	.string "Alors tout ce que tu vois, c’est le ciel\n"
	.string "dans un cercle.\p"
	.string "Mais c’est ce qui rend le ciel au-dessus\n"
	.string "d’ATALANOPOLIS plus beau qu’ailleurs.$"

SootopolisCity_Text_GiganticPokemonFight:
	.string "Quand deux POKéMON si gigantesques\n"
	.string "s’affrontent sauvagement, nous ne\l"
	.string "pouvons pas faire grand chose.$"

SootopolisCity_Text_FearedWorstWhenPokemonFlewDown:
	.string "J’ai craint le pire en voyant arriver ce\n"
	.string "troisième POKéMON.$"

SootopolisCity_Text_NightSkyFavoriteScenery:
	.string "Un cercle de ciel, la nuit, entre les\n"
	.string "bords du cratère d’un volcan…\p"
	.string "Dans ce cercle les étoiles scintillent\n"
	.string "et clignotent comme si elles étaient\l"
	.string "en vie.\p"
	.string "C’est mon panorama préféré.$"

SootopolisCity_Text_WeatherWentWild:
	.string "Le ciel était clair ce matin,\n"
	.string "mais…\p"
	.string "Soudainement, des nuages noirs sont\n"
	.string "apparus et des orages ont éclaté.\p"
	.string "Le temps est complètement détraqué!\p"
	.string "Serait-ce à cause de ces POKéMON?$"

SootopolisCity_Text_YouBroughtFlyingMon:
	.string "Oh?\p"
	.string "C’est toi qui as ramené ce POKéMON\n"
	.string "volant ici?\p"
	.string "J’en reste bouche bée.$"

SootopolisCity_Text_GroudonPleaseStop:
	.string "MAX: G… GROUDON…\n"
	.string "Arrête! Je t’en prie arrête!\p"
	.string "Je connais l’étendue de ton pouvoir\n"
	.string "maintenant!\p"
	.string "Si tu continues, non seulement\n"
	.string "ATALANOPOLIS, mais aussi HOENN\l"
	.string "sera complètement détruit!$"

SootopolisCity_Text_AfterAllOurScheming:
	.string "MAX: Alors GROUDON et KYOGRE\n"
	.string "ne sont pas les seuls POKéMON\l"
	.string "ancestraux…\p"
	.string "Après tous nos plans inutiles et nos\n"
	.string "efforts désespérés, il a suffi d’un\p"
	.string "seul geste de ce POKéMON pour que\n"
	.string "tout redevienne normal…\p"
	.string "Ha ha…\n"
	.string "Ouah ha ha…$"

SootopolisCity_Text_KyogreCalmDown:
	.string "ARTHUR: KYOGRE! Que se passe-t-il?\n"
	.string "Regarde par ici! C’est l’ORBE ROUGE!\l"
	.string "Calme-toi! KYOGRE!\p"
	.string "… … … … … …\n"
	.string "… … … … … …\p"
	.string "Ça ne va pas!\n"
	.string "Il ne m’écoute même pas!$"

SootopolisCity_Text_TryingMeaninglessToPokemon:
	.string "ARTHUR: KYOGRE et GROUDON…\n"
	.string "Ils se sont tous les deux envolés\l"
	.string "on ne sait où.\p"
	.string "Le climat d’HOENN est revenu à\n"
	.string "la normale…\p"
	.string "Ha ha…\n"
	.string "Hahahaha…\p"
	.string "Ce que nous avons essayé d’accomplir\n"
	.string "semble bien insignifiant comparé à\l"
	.string "la puissance de ces POKéMON.$"

SootopolisCity_Text_InvolvedWithCrisisComeWithMe:
	.string "PIERRE: Ces deux POKéMON…\n"
	.string "GROUDON… et KYOGRE…\p"
	.string "Ces deux POKéMON ancestraux ont été\n"
	.string "tirés de leur long sommeil…\p"
	.string "Et maintenant, ils sont en train de\n"
	.string "s’affronter en utilisant leurs\l"
	.string "pouvoirs incontrôlables…\p"
	.string "… {PLAYER}{KUN}.\p"
	.string "A te voir là, j’imagine que tu as prévu\n"
	.string "de tenter quelque chose, non?\p"
	.string "Bien, dans ce cas, il y a quelqu’un que\n"
	.string "j’aimerais te faire rencontrer.\p"
	.string "Viens avec moi, s’il te plaît.$"

SootopolisCity_Text_DoesThisMakeYourFearPokemon:
	.string "PIERRE: Ecoute, {PLAYER}{KUN}.\p"
	.string "Est-ce que voir GROUDON et KYOGRE\n"
	.string "se battre ainsi te fait penser que\l"
	.string "les POKéMON doivent être craints?\p"
	.string "Mais il ne faut pas! Les POKéMON\n"
	.string "sont bien plus que ça…\p"
	.string "Mais pourquoi est-ce que je te\n"
	.string "dis ça? Tu le sais déjà!$"

SootopolisCity_Text_HereWereAreHelpWallace:
	.string "PIERRE: Très bien, nous sommes\n"
	.string "arrivés!\p"
	.string "A l’intérieur, tu trouveras quelqu’un\n"
	.string "qui se prénomme MARC.\p"
	.string "Je crois que tu seras en mesure\n"
	.string "de l’aider…$"

SootopolisCity_Text_KnowWhatsNeededToHelpHim:
	.string "PIERRE: Je crois que tu seras en mesure\n"
	.string "de l’aider…$"

SootopolisCity_Text_NeverBeenToSkyPillar:
	.string "PIERRE: Le PILIER CELESTE…\p"
	.string "Je n’y suis jamais allé.\n"
	.string "Où cela peut-il bien être?$"

SootopolisCity_Text_SoThatsRayquaza:
	.string "PIERRE: Alors ce RAYQUAZA…\p"
	.string "C’est incroyable que ces immenses\n"
	.string "POKéMON aient eu peur de lui comme ça…$"

SootopolisCity_Text_MaxieArchieLeft:
	.string "PIERRE: On dirait que MAX et ARTHUR\n"
	.string "sont partis quelque part.\p"
	.string "Peut-être sont-ils allés au MONT\n"
	.string "MEMORIA pour y déposer les ORBES…$"

SootopolisCity_Text_HaventYouScaledSkyPillar:
	.string "MARC: Oh?\n"
	.string "{PLAYER}{KUN}?\p"
	.string "Tu n’as pas encore gravi le\n"
	.string "PILIER CELESTE?\p"
	.string "Je suis sûr que ça ne devrait pas\n"
	.string "être un gros problème pour toi…$"

SootopolisCity_Text_AquaMagmaDidntMeanHarm:
	.string "MARC: {PLAYER}{KUN}…\p"
	.string "Les leaders des TEAMS MAGMA et\n"
	.string "AQUA, je ne pense pas qu’ils veuillent\l"
	.string "vraiment faire le mal.\p"
	.string "Il faudrait les écouter pour savoir ce\n"
	.string "qu’ils ont vraiment en tête.$"

SootopolisCity_Text_ThankYouForHelpAcceptThis:
	.string "MARC: {PLAYER}{KUN}…\n"
	.string "Mon intuition était bonne.\p"
	.string "Grâce à toi, ATALANOPOLIS…\n"
	.string "Non, tout HOENN a été sauvé.\p"
	.string "Au nom de tous ses habitants,\n"
	.string "je te remercie.\p"
	.string "C’est un cadeau de ma part. Je t’en\n"
	.string "prie, accepte-le.$"

SootopolisCity_Text_ExplainWaterfallGoToGym:
	.string "Cette CS contient CASCADE.\p"
	.string "Si tu as le BADGE PLUIE, un POKéMON\n"
	.string "connaissant cette CS sera capable\l"
	.string "de remonter des cascades d’eau.\p"
	.string "Et où trouve-t-on le BADGE PLUIE?\n"
	.string "Tu le sais, n’est-ce pas?\p"
	.string "C’est bien ça! Tu dois battre le\n"
	.string "CHAMPION D’ARENE d’ATALANOPOLIS.\p"
	.string "Tu n’as plus qu’à franchir la porte\n"
	.string "se trouvant derrière moi pour cela.$"

SootopolisCity_Text_DazzledByMentor:
	.string "MARC: Mais je tiens à te prévenir que\n"
	.string "l’élégant style de combat de mon mentor\l"
	.string "risque de te laisser le souffle coupé.$"
