
LilycoveCity_Harbor_Text_FerryUnavailable:
	.string "Che cosa hai detto?\n"
	.string "Stai cercando una nave?\p"
	.string "Spiacente, il servizio traghetto non è\n"
	.string "disponibile al momento…$"

LilycoveCity_Harbor_Text_MayISeeYourTicket:
	.string "Ciao, sei qui per prendere il traghetto?\n"
	.string "Mi fai vedere il BIGLIETTO?$"

LilycoveCity_Harbor_Text_NoTicket:
	.string "{PLAYER} non ha il BIGLIETTO…\p"
	.string "Spiacente.\p"
	.string "Devi avere il BIGLIETTO per imbarcarti\n"
	.string "sul traghetto.$"

LilycoveCity_Harbor_Text_FlashTicketWhereTo:
	.string "{PLAYER} mostra il BIGLIETTO.\p"
	.string "Perfetto! Non hai bisogno d’altro!\p"
	.string "Dove desideri andare?$"

LilycoveCity_Harbor_Text_SailAnotherTime:
	.string "Spero di rivederti un’altra volta!$"

LilycoveCity_Harbor_Text_SlateportItIs:
	.string "Ok, si salpa per PORTO SELCEPOLI!$"

LilycoveCity_Harbor_Text_BattleFrontierItIs:
	.string "Ok, si salpa per il PARCO LOTTA!$"

LilycoveCity_Harbor_Text_PleaseBoard:
	.string "Sali pure sul traghetto e attendi\n"
	.string "la partenza.$"

LilycoveCity_Harbor_Text_WhereWouldYouLikeToGo:
	.string "Dove vorresti andare allora?$"

LilycoveCity_Harbor_Text_SailorFerryUnavailable:
	.string "Fino a quando il traghetto non è finito,\n"
	.string "noi marinai stiamo con le mani in mano…\p"
	.string "Spero che al CANTIERE di SELCEPOLI\n"
	.string "facciano in fretta.$"

LilycoveCity_Harbor_Text_SailorFerryAvailable:
	.string "Il traghetto M/N MAREA è finalmente\n"
	.string "operativo.\p"
	.string "Al CANTIERE di SELCEPOLI\n"
	.string "hanno lavorato di buona lena.\p"
	.string "Beh, ora tocca a me rimboccarmi\n"
	.string "le maniche!$"
