
BattleFrontier_Mart_Text_ChaperonGrandson:
	.string "Hemos venido a animar a nuestro nieto.\p"
	.string "Pero, ya que estamos aquí, he pensado\n"
	.string "comprarme algo de recuerdo.$"

BattleFrontier_Mart_Text_ProteinMakeNiceGift:
	.string "Oye, ¿qué te parece esto?\n"
	.string "¿A que es un buen regalo?\p"
	.string "¿Pone… PRO… TE… Í… NA?\n"
	.string "Suena a algo delicioso, ¿no crees?$"

BattleFrontier_Mart_Text_FacilitiesDontAllowItems:
	.string "En muchos de los edificios del FRENTE\n"
	.string "de BATALLA no permiten el uso\l"
	.string "de objetos durante los combates.\p"
	.string "¡Esa regla pone las cosas aún más\n"
	.string "difíciles de lo que ya son!$"
