BattleFrontier_BattlePalaceBattleRoom: @ 84853DC
	.4byte BattleFrontier_BattlePalaceBattleRoom_Layout
	.4byte BattleFrontier_BattlePalaceBattleRoom_MapEvents
	.4byte BattleFrontier_BattlePalaceBattleRoom_MapScripts
	.4byte 0x0
	.2byte MUS_B_PALACE
	.2byte 344
	.byte MAPSEC_BATTLE_FRONTIER
	.byte 0
	.byte WEATHER_NONE
	.byte MAP_TYPE_INDOOR
	.2byte 0
	map_header_flags allow_bike=0, allow_escape_rope=0, allow_run=0, show_map_name=0
	.byte MAP_BATTLE_SCENE_NORMAL

