
BattleFrontier_BattlePalaceBattleRoom_Text_LetMeRestoreYourMons:
	.string "Eccellente!\n"
	.string "Rimetterò in sesto i tuoi POKéMON.$"

BattleFrontier_BattlePalaceBattleRoom_Text_PreparedFor2ndOpponent:
	.string "Ti attende il 2º rivale.\n"
	.string "Vuoi andare avanti?$"

BattleFrontier_BattlePalaceBattleRoom_Text_PreparedFor3rdOpponent:
	.string "Ti attende il 3º rivale.\n"
	.string "Vuoi andare avanti?$"

BattleFrontier_BattlePalaceBattleRoom_Text_PreparedFor4thOpponent:
	.string "Ti attende il 4º rivale.\n"
	.string "Vuoi andare avanti?$"

BattleFrontier_BattlePalaceBattleRoom_Text_PreparedFor5thOpponent:
	.string "Ti attende il 5º rivale.\n"
	.string "Vuoi andare avanti?$"

BattleFrontier_BattlePalaceBattleRoom_Text_PreparedFor6thOpponent:
	.string "Ti attende il 6º rivale.\n"
	.string "Vuoi andare avanti?$"

BattleFrontier_BattlePalaceBattleRoom_Text_PreparedFor7thOpponent:
	.string "Ti attende il 7º rivale.\n"
	.string "Vuoi andare avanti?$"

BattleFrontier_BattlePalaceBattleRoom_Text_SaveAndQuitGame:
	.string "Vuoi salvare e uscire dal gioco?$"

BattleFrontier_BattlePalaceBattleRoom_Text_WishToQuitChallenge:
	.string "Vuoi ritirarti dalla sfida?$"

BattleFrontier_BattlePalaceBattleRoom_Text_SavingData:
	.string "Sto salvando i dati di gioco.\n"
	.string "Un po’ di pazienza…$"

BattleFrontier_BattlePalaceBattleRoom_Text_RecordLastMatch:
	.string "Vuoi che il filmato dell’ultima lotta\n"
	.string "venga registrato nel tuo PASS PARCO?$"

BattleFrontier_BattlePalaceBattleRoom_Text_ChallengingPalaceMaven:
	.string "Ho un annuncio da fare…\p"
	.string "Dopo tante vittorie, ti meriti di sfidare\n"
	.string "il nostro maestro, il SIRE PALAZZO…$"

BattleFrontier_BattlePalaceBattleRoom_Text_ReadyForPalaceMaven:
	.string "Vado a chiamare il SIRE PALAZZO.\n"
	.string "Accetti la sfida?$"

BattleFrontier_BattlePalaceBattleRoom_Text_AnnounceArrivalOfSpenser:
	.string "Che squillino le trombe, sta per arrivare\n"
	.string "il SIRE PALAZZO, SPARTACO!$"

BattleFrontier_BattlePalaceBattleRoom_Text_SpenserFirstIntro:
	.string "SPARTACO: I POKéMON sono la mia vita!\p"
	.string "Il mio cuore batte all’unisono\n"
	.string "con il loro!\p"
	.string "ALLENATORE in erba!\n"
	.string "Credi nei tuoi POKéMON?\p"
	.string "Hai una fiducia cieca in loro?\p"
	.string "Se il legame che ti unisce a loro è\n"
	.string "fragile, non riuscirai a battere\l"
	.string "i miei fratelli!$"

BattleFrontier_BattlePalaceBattleRoom_Text_ProveYourBondWithMons:
	.string "Dimostrami quale tipo di legame ti\n"
	.string "unisce ai POKéMON!$"

BattleFrontier_BattlePalaceBattleRoom_Text_SpenserPostSilverBattle:
	.string "SPARTACO: Ahahah!\p"
	.string "Hai saputo tenermi testa!\n"
	.string "Scusa se ho fatto certi numeri…\p"
	.string "Dai, su!\n"
	.string "Portami quella cosa che tu ben sai!$"

BattleFrontier_BattlePalaceBattleRoom_Text_LetsSeeFrontierPass:
	.string "Il vero ALLENATORE deve sempre\n"
	.string "mantenere un certo contegno…\p"
	.string "Dai, su!\n"
	.string "Mostrami il tuo PASS PARCO!$"

BattleFrontier_BattlePalaceBattleRoom_Text_ReceivedSpiritsSymbol:
	.string "Il SIMBOLO SPIRITO è stato aggiunto\n"
	.string "al PASS PARCO!$"

BattleFrontier_BattlePalaceBattleRoom_Text_SpenserAwaitNextTime:
	.string "SPARTACO: Lo sguardo dei tuoi POKéMON è\n"
	.string "puro e limpido.\p"
	.string "Aspetterò con ansia il tuo ritorno.$"

BattleFrontier_BattlePalaceBattleRoom_Text_SpenserThisTimeWontHoldBack:
	.string "SPARTACO: Ahahah!\n"
	.string "Ce l’hai fatta anche questa volta?\p"
	.string "Devi aver sviluppato un legame\n"
	.string "incredibile con i tuoi POKéMON.\p"
	.string "Andiamo al sodo!\p"
	.string "Cercherò di lottare in modo equilibrato.\n"
	.string "Questa volta non si scherza.\p"
	.string "Te la senti di iniziare?\n"
	.string "Preparati a una sonora sconfitta!$"

BattleFrontier_BattlePalaceBattleRoom_Text_Kaaah:
	.string "Aaah!$"

BattleFrontier_BattlePalaceBattleRoom_Text_SpenserYourTeamIsAdmirable:
	.string "SPARTACO: Una bella performance!\n"
	.string "I miei fratelli, anche se determinati,\l"
	.string "non sono riusciti a tenerti testa.\p"
	.string "Lo spirito della tua squadra è\n"
	.string "ammirevole!\p"
	.string "Dai, su!\n"
	.string "Portami quella cosa che tu ben sai!$"

BattleFrontier_BattlePalaceBattleRoom_Text_HurryWithFrontierPass:
	.string "Il vero ALLENATORE deve sempre\n"
	.string "mantenere un certo contegno…\p"
	.string "Dai, su, forza! Sbrigati a tirare fuori\n"
	.string "il tuo PASS PARCO!$"

BattleFrontier_BattlePalaceBattleRoom_Text_SpiritsSymbolTookGoldenShine:
	.string "Il SIMBOLO SPIRITO si è colorato\n"
	.string "d’oro!$"

BattleFrontier_BattlePalaceBattleRoom_Text_SpenserComeSeeMeAgain:
	.string "SPARTACO: Ahahah!\p"
	.string "Torna a trovarmi!\n"
	.string "Ti aspetterò insieme ai miei fratelli!$"