
BattleFrontier_Lounge5_Text_NatureGirlGreeting::
	.string "Eheheh!\n"
	.string "So leggere nel pensiero dei POKéMON!\p"
	.string "Ti prego! Mi mostri uno dei\n"
	.string "tuoi POKéMON?$"

BattleFrontier_Lounge5_Text_NatureGirlNoneShown::
	.string "Buu!\n"
	.string "Sei un coniglio!$"

BattleFrontier_Lounge5_Text_NatureGirlHardy::
	.string "Uhm…\p"
	.string "Questo POKéMON dice di amare la lotta!\n"
	.string "Lotterebbe anche se si è fatto\l"
	.string "tanta bua!$"

BattleFrontier_Lounge5_Text_NatureGirlLonely::
	.string "Uhm…\p"
	.string "A questo POKéMON piace fare il furbo!\n"
	.string "Ma se si fa la bua, passa al\l"
	.string "contrattacco!$"

BattleFrontier_Lounge5_Text_NatureGirlBrave::
	.string "Uhm…\p"
	.string "Questo POKéMON dice di amare la lotta!\n"
	.string "Ma se si fa la bua, si preoccupa per se\l"
	.string "stesso!$"

BattleFrontier_Lounge5_Text_NatureGirlAdamant::
	.string "Uhm…\p"
	.string "Questo POKéMON dice di amare la lotta!\n"
	.string "Lotterebbe anche se si è fatto\l"
	.string "tanta bua!$"

BattleFrontier_Lounge5_Text_NatureGirlNaughty::
	.string "Uhm…\p"
	.string "Questo POKéMON dice di tenere a\n"
	.string "se stesso! Ma se si fa la bua,\l"
	.string "passa al contrattacco!$"

BattleFrontier_Lounge5_Text_NatureGirlBold::
	.string "Uhm…\p"
	.string "A questo POKéMON piace fare il furbo!\n"
	.string "Ma se si fa la bua, si preoccupa per se\l"
	.string "stesso!$"

BattleFrontier_Lounge5_Text_NatureGirlDocileNaiveQuietQuirky::
	.string "Uhm…\p"
	.string "Questo POKéMON dice di amare la lotta!\n"
	.string "Lotterebbe anche se si è fatto\l"
	.string "tanta bua!$"

BattleFrontier_Lounge5_Text_NatureGirlRelaxed::
	.string "Uhm…\p"
	.string "A questo POKéMON piace fare il furbo!\n"
	.string "Ma se si fa la bua, passa al\l"
	.string "contrattacco!$"

BattleFrontier_Lounge5_Text_NatureGirlImpish::
	.string "Uhm…\p"
	.string "Questo POKéMON dice di amare la lotta!\n"
	.string "Ma se si fa la bua, si preoccupa per se\l"
	.string "stesso!$"

BattleFrontier_Lounge5_Text_NatureGirlLax::
	.string "Uhm…\p"
	.string "A questo POKéMON piace fare il furbo!\n"
	.string "Anche quando si fa tanta bua!$"

BattleFrontier_Lounge5_Text_NatureGirlTimid::
	.string "Uhm…\p"
	.string "Questo POKéMON dice di amare la lotta!\n"
	.string "Ma se si fa tanta bua, diventa\l"
	.string "un furbacchione!$"

BattleFrontier_Lounge5_Text_NatureGirlHasty::
	.string "Uhm…\p"
	.string "Questo POKéMON dice di amare la lotta!\n"
	.string "Lotterebbe anche se si è fatto\l"
	.string "tanta bua!$"

BattleFrontier_Lounge5_Text_NatureGirlSerious::
	.string "Uhm…\p"
	.string "A questo POKéMON piace fare il furbo!\n"
	.string "Anche quando si fa tanta bua!$"

BattleFrontier_Lounge5_Text_NatureGirlJolly::
	.string "Uhm…\p"
	.string "A questo POKéMON piace fare il furbo!\n"
	.string "Ma se si fa la bua, si preoccupa per se\l"
	.string "stesso!$"

BattleFrontier_Lounge5_Text_NatureGirlModest::
	.string "Uhm…\p"
	.string "Questo POKéMON dice di tenere a\n"
	.string "se stesso, non importa se si è fatto\l"
	.string "tanta bua o meno!$"

BattleFrontier_Lounge5_Text_NatureGirlMild::
	.string "Uhm…\p"
	.string "Questo POKéMON dice di tenere a\n"
	.string "se stesso! Se si fa la bua, diventa\l"
	.string "un furbacchione!$"

BattleFrontier_Lounge5_Text_NatureGirlBashful::
	.string "Uhm…\p"
	.string "Questo POKéMON dice di tenere a\n"
	.string "se stesso e si preoccupa se si\l"
	.string "fa la bua!$"

BattleFrontier_Lounge5_Text_NatureGirlRash::
	.string "Uhm…\p"
	.string "A questo POKéMON piace fare il furbo!\n"
	.string "Anche quando si fa tanta bua!$"

BattleFrontier_Lounge5_Text_NatureGirlCalm::
	.string "Uhm…\p"
	.string "Questo POKéMON dice di tenere a\n"
	.string "se stesso! Se si fa tanta bua, si\l"
	.string "preoccupa!$"

BattleFrontier_Lounge5_Text_NatureGirlGentle::
	.string "Uhm…\p"
	.string "Questo POKéMON dice di tenere a\n"
	.string "se stesso! Ma se si fa la bua, passa\l"
	.string "al contrattacco!$"

BattleFrontier_Lounge5_Text_NatureGirlSassy::
	.string "Uhm…\p"
	.string "Questo POKéMON dice di amare la lotta!\n"
	.string "Ma se si fa la bua, diventa\l"
	.string "un furbacchione!$"

BattleFrontier_Lounge5_Text_NatureGirlCareful::
	.string "Uhm…\p"
	.string "Questo POKéMON dice di tenere a\n"
	.string "se stesso! Se si fa la bua, diventa\l"
	.string "un furbacchione!$"

BattleFrontier_Lounge5_Text_NatureGirlEgg::
	.string "Così non vale! Un UOVO dorme!\n"
	.string "Non posso parlargli!$"

BattleFrontier_Lounge5_Text_LadyClaimsSheUnderstandsPokemon::
	.string "Che carina!\n"
	.string "Quella ragazzina dice di saper\l"
	.string "leggere il pensiero dei POKéMON!$"

BattleFrontier_Lounge5_Text_GirlSayingSomethingProfound::
	.string "Credo che quella ragazzina abbia\n"
	.string "cose profonde da dire.$"

BattleFrontier_Lounge5_Text_GirlPlaysAtRedHouseALot::
	.string "Una cosa la so anch’io!\p"
	.string "Quella ragazzina gioca un sacco\n"
	.string "nella casa rossa!$"
