
RustboroCity_DevonCorp_3F_Text_MrStoneIHaveFavor:
	.string "Sono PIERANGELO PETRI, PRESIDENTE\n"
	.string "della DEVON SpA.\p"
	.string "Ho sentito parlare di te!\p"
	.string "Ci hai salvato ben due volte!\p"
	.string "Ho un favore da chiedere ad una\n"
	.string "persona meravigliosa come te.\p"
	.string "So che hai un pacchetto da consegnare\n"
	.string "al CANTIERE di SELCEPOLI.\p"
	.string "Bene, sulla strada ti potresti fermare a\n"
	.string "BLURUVIA?\p"
	.string "Vorrei che tu consegnassi una LETTERA\n"
	.string "a ROCCO.$"

RustboroCity_DevonCorp_3F_Text_MrStoneWantYouToHaveThis:
	.string "SIG. PETRI: Dovresti sapere che sono\n"
	.string "un PRESIDENTE molto magnanimo.\p"
	.string "Non potrei mai chiederti un favore\n"
	.string "senza offrirti qualcosa in cambio.\p"
	.string "Per cui ti prego di accettare questo.$"

RustboroCity_DevonCorp_3F_Text_ReceivedPokenav:
	.string "{PLAYER} riceve un POKéNAV.$"

RustboroCity_DevonCorp_3F_Text_MrStoneExplainPokenavRestUp:
	.string "SIG. PETRI: Questo dispositivo…\p"
	.string "è un NAVIGATORE POKéMON, detto anche\n"
	.string "POKéNAV.\p"
	.string "È indispensabile per gli ALLENATORI\n"
	.string "che vogliono partire all’avventura.\p"
	.string "Ha una mappa della regione di HOENN.\p"
	.string "Troverai facilmente la strada per\n"
	.string "BLURUVIA e SELCEPOLI!\p"
	.string "A proposito, ho sentito dire che dei\n"
	.string "teppistelli, credo il TEAM MAGMA e\l"
	.string "il TEAM IDRO, stanno portando\l"
	.string "scompiglio in lungo e in largo.\p"
	.string "Penso che sia meglio che ti riposi un po’\n"
	.string "prima di metterti in viaggio.$"

RustboroCity_DevonCorp_3F_Text_MrStoneGoWithCautionAndCare:
	.string "SIG. PETRI: Va bene, {PLAYER}{KUN},\n"
	.string "sii prudente allora!$"

RustboroCity_DevonCorp_3F_Text_CountingOnYou:
	.string "SIG. PETRI: Conto su di te!$"

RustboroCity_DevonCorp_3F_Text_ThankYouForDeliveringLetter:
	.string "SIG. PETRI: Hai consegnato la mia\n"
	.string "LETTERA? Ti ringrazio profondamente!\p"
	.string "Vorrei che tu accettassi questo dono\n"
	.string "molto utile per un ALLENATORE.$"

RustboroCity_DevonCorp_3F_Text_ExplainExpShare:
	.string "SIG. PETRI: Un POKéMON che tiene\n"
	.string "CONDIV. ESP. riceverà alcuni punti\l"
	.string "ESP. dalla lotta.\p"
	.string "Riceverà punti ESP. anche se non ha\n"
	.string "partecipato alla lotta.\p"
	.string "Credo che CONDIV. ESP. sia molto utile\n"
	.string "per allevare POKéMON deboli.$"

RustboroCity_DevonCorp_3F_Text_NotFamiliarWithTrends:
	.string "SIG. PETRI: Ho iniziato a lavorare\n"
	.string "quando ero ancora molto giovane.\p"
	.string "Pertanto non sono molto al passo\n"
	.string "con i tempi.\p"
	.string "I giovani d’oggi vogliono tutti essere\n"
	.string "ALLENATORI nella LEGA POKéMON?$"

RustboroCity_DevonCorp_3F_Text_ThisIs3rdFloorWaitHere:
	.string "Ti trovi al secondo piano della\n"
	.string "DEVON SpA.\p"
	.string "L’UFFICIO del nostro PRESIDENTE\n"
	.string "è su questo piano.\p"
	.string "Non trovo le parole per esprimere\n"
	.string "la mia gratitudine…\p"
	.string "Uhm… quel pacchetto che ci hai\n"
	.string "riportato…\p"
	.string "Ti posso chiedere di consegnarlo\n"
	.string "al CANTIERE di SELCEPOLI?\p"
	.string "Sarebbe terribile se ci venisse rubato\n"
	.string "un’altra volta.\p"
	.string "Uhm… eheheh, quindi, uhm, posso\n"
	.string "contare su di te?\p"
	.string "Oh, giusto!\n"
	.string "Puoi aspettare un attimino?$"

RustboroCity_DevonCorp_3F_Text_WordWithPresidentComeWithMe:
	.string "Il nostro PRESIDENTE ti vorrebbe\n"
	.string "parlare.\p"
	.string "Ti prego di seguirmi.$"

RustboroCity_DevonCorp_3F_Text_PleaseGoAhead:
	.string "Prego, accomodati.$"

RustboroCity_DevonCorp_3F_Text_VisitCaptSternShipyard:
	.string "Se visiti il CANTIERE di SELCEPOLI,\n"
	.string "dovresti andare a trovare il CAP. REMO.$"

RustboroCity_DevonCorp_3F_Text_RepeatAndTimerHugelyPopular:
	.string "I nuovi prodotti della DEVON, la BIS\n"
	.string "BALL e la TIMER BALL, stanno avendo\l"
	.string "un grande successo tra gli ALLENATORI.$"

RustboroCity_DevonCorp_3F_Text_RareRocksDisplay:
	.string "Una collezione di rocce e pietre rare\n"
	.string "del PRESIDENTE.$"
