
Route128_Text_ArchieWhatHappened:
	.string "IVAN: Che è successo?\n"
	.string "Che scena spaventosa è mai questa…?\p"
	.string "Ho fatto un terribile errore?$"

Route128_Text_ArchieIOnlyWanted:
	.string "Io… volevo solo…$"

Route128_Text_MaxieDoYouUnderstandNow:
	.string "MAX: Capisci ora, IVAN?\p"
	.string "Vedi le conseguenze disastrose\n"
	.string "del tuo sogno?\p"
	.string "Dobbiamo sbrigarci! Dobbiamo fare\n"
	.string "qualcosa prima che la situazione ci\l"
	.string "sfugga di mano!$"

Route128_Text_MaxieResposibilityFallsToArchieAndMe:
	.string "MAX: {PLAYER}, non dire niente.\p"
	.string "So di non avere il diritto di criticare\n"
	.string "IVAN…\p"
	.string "Vista la situazione attuale, dubito che\n"
	.string "noi esseri umani saremo in grado di\l"
	.string "fare qualcosa.\p"
	.string "Ma non possiamo neppure stare lì\n"
	.string "con le mani in mano.\p"
	.string "Sta a me e a IVAN porre fine\n"
	.string "a questa situazione…$"

Route128_Text_MaxieThisDefiesBelief:
	.string "MAX: Incredibile…\p"
	.string "Un POKéMON antichissimo…\p"
	.string "Il suo potere è eccezionale.\n"
	.string "Ha sconvolto l’equilibrio naturale…$"

Route128_Text_StevenWhatIsHappening:
	.string "ROCCO: {PLAYER}{KUN}!\n"
	.string "Che succede?$"

Route128_Text_StevenWholeWorldWillDrown:
	.string "È terribile…\p"
	.string "Dopo l’ondata di caldo insopportabile,\n"
	.string "è cominciato questo diluvio.\p"
	.string "Se non cessa, tutta la regione di HOENN,\n"
	.string "anzi, il mondo intero verrà sommerso.\p"
	.string "Una gigantesca nuvola si sta\n"
	.string "estendendo da CENERIDE…\p"
	.string "Che cosa starà succedendo là?\p"
	.string "Non c’è nulla da discutere…\n"
	.string "A CENERIDE avremo la risposta.$"

Route128_Text_StevenImGoingToSootopolis:
	.string "{PLAYER}{KUN}!\n"
	.string "Non so cosa tu voglia fare,\l"
	.string "ma che non sia niente di imprudente!\p"
	.string "Ok.\n"
	.string "Andrò a CENERIDE.$"
