FallarborTown_House2_EventObjects:
	object_event 1, EVENT_OBJ_GFX_FAT_MAN, 0, 4, 4, 3, MOVEMENT_TYPE_FACE_DOWN, 0, 0, 0, 0, FallarborTown_House2_EventScript_201383, 0

FallarborTown_House2_MapWarps:
	warp_def 3, 7, 0, 4, MAP_FALLARBOR_TOWN
	warp_def 4, 7, 0, 4, MAP_FALLARBOR_TOWN

FallarborTown_House2_MapEvents::
	map_events FallarborTown_House2_EventObjects, FallarborTown_House2_MapWarps, 0x0, 0x0

