
FallarborTown_MoveRelearnersHouse_Text_ImTheMoveTutor:
	.string "Soy el TUTOR de MOVIMIENTOS.\p"
	.string "Me sé todos los movimientos que\n"
	.string "aprenden los POKéMON. Todos, toditos,\l"
	.string "todos. Y además los puedo enseñar.\p"
	.string "Si quieres, puedo enseñar a uno\n"
	.string "de tus POKéMON un movimiento.\p"
	.string "Lo haré por una insignificante ESCAMA\n"
	.string "CORAZÓN. Es que las colecciono.$"

FallarborTown_MoveRelearnersHouse_Text_ThatsAHeartScaleWantMeToTeachMove:
	.string "¡Sí! ¡Ésa es! ¡Una auténtica ESCAMA\n"
	.string "CORAZÓN! ¡Una de las de verdad!\p"
	.string "A ver que lo adivine, ¿quieres que\n"
	.string "enseñe un movimiento a tu POKéMON?$"

FallarborTown_MoveRelearnersHouse_Text_TutorWhichMon:
	.string "¿Qué POKéMON quieres que lo aprenda?$"

FallarborTown_MoveRelearnersHouse_Text_TeachWhichMove:
	.string "¿Qué movimiento quieres que aprenda?$"

FallarborTown_MoveRelearnersHouse_Text_DontHaveMoveToTeachPokemon:
	.string "Perdona…\p"
	.string "Parece que no puedo enseñar ningún\n"
	.string "movimiento a ese POKéMON…$"

FallarborTown_MoveRelearnersHouse_Text_HandedOverHeartScale:
	.string "{PLAYER} entregó una ESCAMA CORAZÓN\n"
	.string "a cambio de la lección.$"

FallarborTown_MoveRelearnersHouse_Text_ComeBackWithHeartScale:
	.string "Si tu POKéMON necesita aprender\n"
	.string "un movimiento, vuelve con una ESCAMA\l"
	.string "CORAZÓN.$"

FallarborTown_MoveRelearnersHouse_Text_CantTeachEgg:
	.string "¿Eh? No puedo enseñar absolutamente\n"
	.string "ningún movimiento a un HUEVO…$"
