
FallarborTown_MoveRelearnersHouse_Text_ImTheMoveTutor:
	.string "Sono la GUIDA MOSSE.\p"
	.string "Conosco tutte le mosse che può\n"
	.string "apprendere ogni singolo POKéMON,\l"
	.string "e sono in grado anche di insegnarle.\p"
	.string "Se vuoi posso insegnare una mossa\n"
	.string "a un tuo POKéMON!\p"
	.string "In cambio voglio una SQUAMA CUORE.\n"
	.string "Ne faccio la collezione!$"

FallarborTown_MoveRelearnersHouse_Text_ThatsAHeartScaleWantMeToTeachMove:
	.string "Oh! Stupendo! È un’autentica\n"
	.string "SQUAMA CUORE!\p"
	.string "Lasciami indovinare! Vuoi che\n"
	.string "insegni una mossa?$"

FallarborTown_MoveRelearnersHouse_Text_TutorWhichMon:
	.string "Che POKéMON vuoi istruire?$"

FallarborTown_MoveRelearnersHouse_Text_TeachWhichMove:
	.string "Che mossa devo insegnargli?$"

FallarborTown_MoveRelearnersHouse_Text_DontHaveMoveToTeachPokemon:
	.string "Sono spiacente…\p"
	.string "Non credo di avere alcuna mossa\n"
	.string "da insegnare a quel POKéMON.$"

FallarborTown_MoveRelearnersHouse_Text_HandedOverHeartScale:
	.string "In cambio {PLAYER} consegna\n"
	.string "la SQUAMA CUORE.$"

FallarborTown_MoveRelearnersHouse_Text_ComeBackWithHeartScale:
	.string "Se i tuoi POKéMON hanno bisogno di\n"
	.string "mosse, torna con la SQUAMA CUORE.$"

FallarborTown_MoveRelearnersHouse_Text_CantTeachEgg:
	.string "Eh? Non conosco alcuna mossa\n"
	.string "per quell’UOVO.$"
