
Route111_WinstrateFamilysHouse_Text_MySonIsStrongerThanYou:
	.string "Nunca antes había visto a nadie que\n"
	.string "usara los POKéMON con tanto arte.\p"
	.string "No te ofendas, pero mi hijo es\n"
	.string "más fuerte que tú.\p"
	.string "Ha participado incluso en el desafío\n"
	.string "de la LIGA POKéMON. Que lo sepas…$"

Route111_WinstrateFamilysHouse_Text_LikeYouToHaveMachoBrace:
	.string "Usamos VESTIDURA para que nuestros\n"
	.string "POKéMON mejoren aún más durante\l"
	.string "el entrenamiento.\p"
	.string "Ya que has vencido a toda la familia, no\n"
	.string "creo que la necesites, pero me gustaría\l"
	.string "darte nuestra VESTIDURA igualmente.$"

Route111_WinstrateFamilysHouse_Text_PassionateAboutBattles:
	.string "Cuando se trata de combates POKéMON,\n"
	.string "tendemos a tomárnoslo muy en serio…$"

Route111_WinstrateFamilysHouse_Text_StrongerFamilyMembers:
	.string "Mamá es más fuerte que papá.\p"
	.string "Yo soy más fuerte que mamá.\p"
	.string "¡Y la abuelita es más fuerte que yo!\p"
	.string "Pero mi hermano mayor es aún\n"
	.string "más fuerte que la abuelita.$"

Route111_WinstrateFamilysHouse_Text_GrandsonStrong:
	.string "No cabe duda de que eres fuerte.\p"
	.string "Pero, si tuvieras que luchar contra mi\n"
	.string "nieto, llorarías pidiendo clemencia.\p"
	.string "Es mucho más fuerte que cualquier\n"
	.string "otro ENTRENADOR que conozcamos.\p"
	.string "Ahora debe de estar enfrentándose al\n"
	.string "CAMPEÓN de la LIGA POKéMON…\p"
	.string "Conociendo a mi nieto…, ¡puede que\n"
	.string "ya sea el nuevo CAMPEÓN y todo!$"

Route111_WinstrateFamilysHouse_Text_GrandsonStrongShort:
	.string "Mi nieto debe de estar enfrentándose\n"
	.string "al CAMPEÓN de la LIGA POKéMON…\p"
	.string "Conociendo a mi nieto…, ¡puede que\n"
	.string "ya sea el nuevo CAMPEÓN y todo!$"
