LittlerootTown_BrendansHouse_1F: @ 8482AF4
	.4byte LittlerootTown_BrendansHouse_1F_Layout
	.4byte LittlerootTown_BrendansHouse_1F_MapEvents
	.4byte LittlerootTown_BrendansHouse_1F_MapScripts
	.4byte 0x0
	.2byte MUS_MISHIRO
	.2byte 54
	.byte MAPSEC_LITTLEROOT_TOWN
	.byte 0
	.byte WEATHER_NONE
	.byte MAP_TYPE_INDOOR
	.2byte 0
	map_header_flags allow_bike=0, allow_escape_rope=0, allow_run=0, show_map_name=0
	.byte MAP_BATTLE_SCENE_NORMAL

