
PlayersHouse_1F_Text_IsntItNiceInHere:
	.string "MAMAN: Alors, {PLAYER}?\n"
	.string "C’est joli ici, non?$"

PlayersHouse_1F_Text_MoversPokemonGoSetClock:
	.string "Les POKéMON déménageurs font tout\n"
	.string "le travail et nettoient après.\p"
	.string "C’est vraiment pratique!\p"
	.string "{PLAYER}, ta chambre est à l’étage.\n"
	.string "Va voir à quoi elle ressemble, mon chou!\p"
	.string "PAPA a acheté une nouvelle horloge\n"
	.string "pour fêter notre déménagement.\p"
	.string "N’oublie pas de la mettre à l’heure!$"

PlayersHouse_1F_Text_ArentYouInterestedInRoom:
	.string "MAMAN: Eh bien, {PLAYER}?\p"
	.string "Tu n’as pas envie de voir ta\n"
	.string "nouvelle chambre?$"

PlayersHouse_1F_Text_GoSetTheClock:
	.string "MAMAN: {PLAYER}.\p"
	.string "Va mettre l’horloge de ta chambre à\n"
	.string "l’heure, mon chou.$"

PlayersHouse_1F_Text_OhComeQuickly:
	.string "MAMAN: Oh! {PLAYER}, {PLAYER}!\n"
	.string "Vite! Viens voir!$"

PlayersHouse_1F_Text_MaybeDadWillBeOn:
	.string "MAMAN: Regarde! C’est l’ARENE de\n"
	.string "CLEMENTI-VILLE!\p"
	.string "On va peut-être voir PAPA!$"

PlayersHouse_1F_Text_ItsOverWeMissedHim:
	.string "MAMAN: Oh… C’est terminé.\p"
	.string "Ils ont sûrement interviewé PAPA,\n"
	.string "mais on l’a raté. Dommage.$"

PlayersHouse_1F_Text_GoIntroduceYourselfNextDoor:
	.string "Ah, tiens!\n"
	.string "L’un des amis de PAPA vit ici.\p"
	.string "Il s’appelle PROF. SEKO.\p"
	.string "C’est notre voisin. Tu pourrais aller\n"
	.string "lui dire bonjour et te présenter.$"

PlayersHouse_1F_Text_SeeYouHoney:
	.string "MAMAN: A plus tard, mon chou!$"

PlayersHouse_1F_Text_DidYouMeetProfBirch:
	.string "MAMAN: Tu as déjà rencontré le\n"
	.string "PROF. SEKO?$"

PlayersHouse_1F_Text_YouShouldRestABit:
	.string "MAMAN: Comment ça va, {PLAYER}?\n"
	.string "Tu as l’air raplapla.\p"
	.string "Tu devrais peut-être te reposer.$"

PlayersHouse_1F_Text_TakeCareHoney:
	.string "MAMAN: A bientôt, mon chou!$"

PlayersHouse_1F_Text_GotDadsBadgeHeresSomethingFromMom:
	.string "MAMAN: Oh? PAPA t’a donné\n"
	.string "un BADGE?\p"
	.string "Dans ce cas, je vais te donner ça!$"

PlayersHouse_1F_Text_DontPushYourselfTooHard:
	.string "Ne t’épuise pas trop, mon chou. Tu peux\n"
	.string "revenir à la maison quand tu veux.\p"
	.string "Bon courage, mon poussin!$"

PlayersHouse_1F_Text_IsThatAPokenav:
	.string "MAMAN: C’est un POKéNAV, mon chou? \n"
	.string "Quelqu’un de DEVON te l’a donné?\p"
	.string "Dis, mon chou? Et si tu enregistrais\n"
	.string "ta maman?\p"
	.string "… … …$"

PlayersHouse_1F_Text_RegisteredMom:
	.string "Vous avez enregistré MAMAN\n"
	.string "dans le POKéNAV.$"

PlayersHouse_1F_Text_Vigoroth1:
	.string "Vigooooh…$"

PlayersHouse_1F_Text_Vigoroth2:
	.string "Gorooooh…$"

PlayersHouse_1F_Text_ReportFromPetalburgGym:
	.string "JOURNALISTE: … Ce reportage vous a été\n"
	.string "présenté devant l’ARENE de CLEMENTI.$"

PlayersHouse_1F_Text_TheresAMovieOnTV:
	.string "Il y a un film à la télé.\p"
	.string "Deux hommes dansent sur un\n"
	.string "grand piano.\p"
	.string "Bon, il faut y aller!$"

PlayersHouse_1F_Text_RunningShoesManual:
	.string "C’est le manuel d’instructions des\n"
	.string "CHAUSSURES DE SPORT.\p"
	.string "“Lorsque vous portez vos CHAUSSURES\n"
	.string "DE SPORT, appuyez sur le bouton B\l"
	.string "pour courir.”\p"
	.string "“Enfilez vos CHAUSSURES DE SPORT\n"
	.string "et foncez droit devant!”$"

PlayersHouse_1F_Text_TicketFromBrineyCameForYou:
	.string "PAPA: Hein?\p"
	.string "Hé, mais c’est {PLAYER}!\p"
	.string "Ça fait un moment qu’on ne s’est pas\n"
	.string "vus. Tu as l’air d’avoir plus d’aplomb.\p"
	.string "C’est l’impression que tu me donnes.\n"
	.string "Mais ton vieux père n’abandonne pas!\p"
	.string "Ah, oui, j’ai quelque chose pour toi.\n"
	.string "Un certain M. MARCO m’a donné ça\l"
	.string "pour toi.$"

PlayersHouse_1F_Text_PortsInSlateportLilycove:
	.string "PAPA: C’est un PASSE pour le ferry?\p"
	.string "Si ma mémoire est bonne, il y a des \n"
	.string "embarcadères à POIVRESSEL et à\l"
	.string "NENUCRIQUE pour le ferry.$"

PlayersHouse_1F_Text_BetterGetBackToGym:
	.string "Je dois retourner à l’ARENE de\n"
	.string "CLEMENTI-VILLE.\p"
	.string "Désolé chérie, je dois déjà repartir.$"

PlayersHouse_1F_Text_DadShouldStayLonger:
	.string "MAMAN: Ton PAPA est incroyable…\p"
	.string "Il n’est jamais à la maison et quand il\n"
	.string "rentre, il ne parle que de POKéMON.\p"
	.string "Il devrait se reposer et rentrer\n"
	.string "plus souvent.$"

PlayersHouse_1F_Text_IsThatABreakingStory:
	.string "MAMAN: Est-ce que c’est un scoop?$"

PlayersHouse_1F_Text_LatiEmergencyNewsFlash:
	.string "Et voici un bulletin spécial\n"
	.string "d’informations.\p"
	.string "Selon des témoignages, un POKéMON\n"
	.string "VOLANT de couleur BZZT… a été\l"
	.string "aperçu à plusieurs endroits dans HOENN.\p"
	.string "L’identité de ce POKéMON n’a pas encore\n"
	.string "été déterminée.\p"
	.string "Et maintenant, voici votre film du soir\n"
	.string "en exclusivité.$"

PlayersHouse_1F_Text_WhatColorDidTheySay:
	.string "MAMAN: {PLAYER}, tu as compris?\p"
	.string "Qu’est-ce qu’ils ont dit à propos de la\n"
	.string "couleur de ce POKéMON?$"

PlayersHouse_1F_Text_StillUnknownPokemon:
	.string "MAMAN: Dire qu’il reste encore des\n"
	.string "POKéMON inconnus à notre époque!$"
