
MtPyre_6F_Text_ValerieIntro:
	.string "Cuando estoy aquí…\n"
	.string "siento un extraño poder dentro de mí.$"

MtPyre_6F_Text_ValerieDefeat:
	.string "Pues esta vez no lo he sentido mucho…$"

MtPyre_6F_Text_ValeriePostBattle:
	.string "Quizás provenga del espíritu de los\n"
	.string "POKéMON que a veces acuden aquí…$"

MtPyre_6F_Text_ValerieRegister:
	.string "Ji, ji, ji… He perdido el combate, pero…\n"
	.string "todavía puedo sorprenderte…\p"
	.string "No hace falta ni que ponga mis manos\n"
	.string "sobre tu POKéNAV… ¡Toma ya!$"

MtPyre_6F_Text_ValerieRematchIntro:
	.string "¡Detrás de ti!\n"
	.string "¿Qué es eso?$"

MtPyre_6F_Text_ValerieRematchDefeat:
	.string "Pues juraría que había algo…$"

MtPyre_6F_Text_ValeriePostRematch:
	.string "Los POKéMON que descansan aquí\n"
	.string "pueden ser muy juguetones.$"

MtPyre_6F_Text_CedricIntro:
	.string "¿Has perdido el norte?\n"
	.string "¡No te preocupes, que aquí estoy yo!$"

MtPyre_6F_Text_CedricDefeat:
	.string "¿Pero tú no te habías perdido?$"

MtPyre_6F_Text_CedricPostBattle:
	.string "Pensaba que era más fácil derrotar\n"
	.string "a los ENTRENADORES que se pierden.\p"
	.string "No volveré a intentar un truco\n"
	.string "tan sucio nunca más…$"
