gUnknown_08DB7AA0:: @ 0x08DB7AA0
	.incbin "baserom.gba", 0xdb7aa0, 0x94

gUnknown_08DB7B34:: @ 0x08DB7B34
	.incbin "baserom.gba", 0xdb7b34, 0x28

gUnknown_08DB7B5C:: @ 0x08DB7B5C
	.incbin "baserom.gba", 0xdb7b5c, 0x90

gUnknown_08DB7BEC:: @ 0x08DB7BEC
	.incbin "baserom.gba", 0xdb7bec, 0x1c

gUnknown_08DB7C08:: @ 0x08DB7C08
	.incbin "baserom.gba", 0xdb7c08, 0xe0

gUnknown_08DB7CE8:: @ 0x08DB7CE8
	.incbin "baserom.gba", 0xdb7ce8, 0x20

gUnknown_08DB7D08:: @ 0x08DB7D08
	.incbin "baserom.gba", 0xdb7d08, 0xc4

gUnknown_08DB7DCC:: @ 0x08DB7DCC
	.incbin "baserom.gba", 0xdb7dcc, 0x28

gUnknown_08DB7DF4:: @ 0x08DB7DF4
	.incbin "baserom.gba", 0xdb7df4, 0xac

gUnknown_08DB7EA0:: @ 0x08DB7EA0
	.incbin "baserom.gba", 0xdb7ea0, 0x24

gUnknown_08DB7EC4:: @ 0x08DB7EC4
	.incbin "baserom.gba", 0xdb7ec4, 0x9c

gUnknown_08DB7F60:: @ 0x08DB7F60
	.incbin "baserom.gba", 0xdb7f60, 0x1c

gUnknown_08DB7F7C:: @ 0x08DB7F7C
	.incbin "baserom.gba", 0xdb7f7c, 0xf4

gUnknown_08DB8070:: @ 0x08DB8070
	.incbin "baserom.gba", 0xdb8070, 0x1c

gUnknown_08DB808C:: @ 0x08DB808C
	.incbin "baserom.gba", 0xdb808c, 0xac

gUnknown_08DB8138:: @ 0x08DB8138
	.incbin "baserom.gba", 0xdb8138, 0x28

gUnknown_08DB8160:: @ 0x08DB8160
	.incbin "baserom.gba", 0xdb8160, 0xb8

gUnknown_08DB8218:: @ 0x08DB8218
	.incbin "baserom.gba", 0xdb8218, 0x24

gUnknown_08DB823C:: @ 0x08DB823C
	.incbin "baserom.gba", 0xdb823c, 0xc4

gUnknown_08DB8300:: @ 0x08DB8300
	.incbin "baserom.gba", 0xdb8300, 0x28

gUnknown_08DB8328:: @ 0x08DB8328
	.incbin "baserom.gba", 0xdb8328, 0x108

gUnknown_08DB8430:: @ 0x08DB8430
	.incbin "baserom.gba", 0xdb8430, 0x28

gUnknown_08DB8458:: @ 0x08DB8458
	.incbin "baserom.gba", 0xdb8458, 0xd0

gUnknown_08DB8528:: @ 0x08DB8528
	.incbin "baserom.gba", 0xdb8528, 0x24

gUnknown_08DB854C:: @ 0x08DB854C
	.incbin "baserom.gba", 0xdb854c, 0xe0

gUnknown_08DB862C:: @ 0x08DB862C
	.incbin "baserom.gba", 0xdb862c, 0x28

gUnknown_08DB8654:: @ 0x08DB8654
	.incbin "baserom.gba", 0xdb8654, 0x70

gUnknown_08DB86C4:: @ 0x08DB86C4
	.incbin "baserom.gba", 0xdb86c4, 0x1c

gUnknown_08DB86E0:: @ 0x08DB86E0
	.incbin "baserom.gba", 0xdb86e0, 0x70

gUnknown_08DB8750:: @ 0x08DB8750
	.incbin "baserom.gba", 0xdb8750, 0x1c

gUnknown_08DB876C:: @ 0x08DB876C
	.incbin "baserom.gba", 0xdb876c, 0x70

gUnknown_08DB87DC:: @ 0x08DB87DC
	.incbin "baserom.gba", 0xdb87dc, 0x1c

gUnknown_08DB87F8:: @ 0x08DB87F8
	.incbin "baserom.gba", 0xdb87f8, 0xe0

gUnknown_08DB88D8:: @ 0x08DB88D8
	.incbin "baserom.gba", 0xdb88d8, 0x28

gUnknown_08DB8900:: @ 0x08DB8900
	.incbin "baserom.gba", 0xdb8900, 0xe0

gUnknown_08DB89E0:: @ 0x08DB89E0
	.incbin "baserom.gba", 0xdb89e0, 0x28

gUnknown_08DB8A08:: @ 0x08DB8A08
	.incbin "baserom.gba", 0xdb8a08, 0x60

gUnknown_08DB8A68:: @ 0x08DB8A68
	.incbin "baserom.gba", 0xdb8a68, 0x1c

gUnknown_08DB8A84:: @ 0x08DB8A84
	.incbin "baserom.gba", 0xdb8a84, 0xbc

gUnknown_08DB8B40:: @ 0x08DB8B40
	.incbin "baserom.gba", 0xdb8b40, 0x28

gUnknown_08DB8B68:: @ 0x08DB8B68
	.incbin "baserom.gba", 0xdb8b68, 0xd8

gUnknown_08DB8C40:: @ 0x08DB8C40
	.incbin "baserom.gba", 0xdb8c40, 0x1c

gUnknown_08DB8C5C:: @ 0x08DB8C5C
	.incbin "baserom.gba", 0xdb8c5c, 0x98

gUnknown_08DB8CF4:: @ 0x08DB8CF4
	.incbin "baserom.gba", 0xdb8cf4, 0x24

gUnknown_08DB8D18:: @ 0x08DB8D18
	.incbin "baserom.gba", 0xdb8d18, 0x98

gUnknown_08DB8DB0:: @ 0x08DB8DB0
	.incbin "baserom.gba", 0xdb8db0, 0x24

gUnknown_08DB8DD4:: @ 0x08DB8DD4
	.incbin "baserom.gba", 0xdb8dd4, 0xac

gUnknown_08DB8E80:: @ 0x08DB8E80
	.incbin "baserom.gba", 0xdb8e80, 0x20

gUnknown_08DB8EA0:: @ 0x08DB8EA0
	.incbin "baserom.gba", 0xdb8ea0, 0xb8

gUnknown_08DB8F58:: @ 0x08DB8F58
	.incbin "baserom.gba", 0xdb8f58, 0x24

gUnknown_08DB8F7C:: @ 0x08DB8F7C
	.incbin "baserom.gba", 0xdb8f7c, 0xbc

gUnknown_08DB9038:: @ 0x08DB9038
	.incbin "baserom.gba", 0xdb9038, 0x20

gUnknown_08DB9058:: @ 0x08DB9058
	.incbin "baserom.gba", 0xdb9058, 0xd8

gUnknown_08DB9130:: @ 0x08DB9130
	.incbin "baserom.gba", 0xdb9130, 0x24

gUnknown_08DB9154:: @ 0x08DB9154
	.incbin "baserom.gba", 0xdb9154, 0xc4

gUnknown_08DB9218:: @ 0x08DB9218
	.incbin "baserom.gba", 0xdb9218, 0x1c

gUnknown_08DB9234:: @ 0x08DB9234
	.incbin "baserom.gba", 0xdb9234, 0xc8

gUnknown_08DB92FC:: @ 0x08DB92FC
	.incbin "baserom.gba", 0xdb92fc, 0x20

gUnknown_08DB931C:: @ 0x08DB931C
	.incbin "baserom.gba", 0xdb931c, 0xcc

gUnknown_08DB93E8:: @ 0x08DB93E8
	.incbin "baserom.gba", 0xdb93e8, 0x24

gUnknown_08DB940C:: @ 0x08DB940C
	.incbin "baserom.gba", 0xdb940c, 0xc0

gUnknown_08DB94CC:: @ 0x08DB94CC
	.incbin "baserom.gba", 0xdb94cc, 0x1c

gUnknown_08DB94E8:: @ 0x08DB94E8
	.incbin "baserom.gba", 0xdb94e8, 0xc4

gUnknown_08DB95AC:: @ 0x08DB95AC
	.incbin "baserom.gba", 0xdb95ac, 0x24

gUnknown_08DB95D0:: @ 0x08DB95D0
	.incbin "baserom.gba", 0xdb95d0, 0xf4

gUnknown_08DB96C4:: @ 0x08DB96C4
	.incbin "baserom.gba", 0xdb96c4, 0x28

gUnknown_08DB96EC:: @ 0x08DB96EC
	.incbin "baserom.gba", 0xdb96ec, 0x108

gUnknown_08DB97F4:: @ 0x08DB97F4
	.incbin "baserom.gba", 0xdb97f4, 0x28

gUnknown_08DB981C:: @ 0x08DB981C
	.incbin "baserom.gba", 0xdb981c, 0xec

gUnknown_08DB9908:: @ 0x08DB9908
	.incbin "baserom.gba", 0xdb9908, 0x28

gUnknown_08DB9930:: @ 0x08DB9930
	.incbin "baserom.gba", 0xdb9930, 0x124

gUnknown_08DB9A54:: @ 0x08DB9A54
	.incbin "baserom.gba", 0xdb9a54, 0x28

gUnknown_08DB9A7C:: @ 0x08DB9A7C
	.incbin "baserom.gba", 0xdb9a7c, 0x100

gUnknown_08DB9B7C:: @ 0x08DB9B7C
	.incbin "baserom.gba", 0xdb9b7c, 0x28

gUnknown_08DB9BA4:: @ 0x08DB9BA4
	.incbin "baserom.gba", 0xdb9ba4, 0x10c

gUnknown_08DB9CB0:: @ 0x08DB9CB0
	.incbin "baserom.gba", 0xdb9cb0, 0x28

gUnknown_08DB9CD8:: @ 0x08DB9CD8
	.incbin "baserom.gba", 0xdb9cd8, 0xd4

gUnknown_08DB9DAC:: @ 0x08DB9DAC
	.incbin "baserom.gba", 0xdb9dac, 0x28

gUnknown_08DB9DD4:: @ 0x08DB9DD4
	.incbin "baserom.gba", 0xdb9dd4, 0x110

gUnknown_08DB9EE4:: @ 0x08DB9EE4
	.incbin "baserom.gba", 0xdb9ee4, 0x24

gUnknown_08DB9F08:: @ 0x08DB9F08
	.incbin "baserom.gba", 0xdb9f08, 0xf4

gUnknown_08DB9FFC:: @ 0x08DB9FFC
	.incbin "baserom.gba", 0xdb9ffc, 0x24

gUnknown_08DBA020:: @ 0x08DBA020
	.incbin "baserom.gba", 0xdba020, 0x10c

gUnknown_08DBA12C:: @ 0x08DBA12C
	.incbin "baserom.gba", 0xdba12c, 0x3ec

