FallarborTown_BattleTentBattleRoom_EventObjects: @ 852E444
	object_event 1, EVENT_OBJ_GFX_VAR_1, 0, 4, 8, 3, MOVEMENT_TYPE_FACE_UP, 1, 1, 0, 0, 0x0, 0
	object_event 2, EVENT_OBJ_GFX_BLACK_BELT, 0, 3, 2, 0, MOVEMENT_TYPE_FACE_DOWN, 1, 1, 0, 0, 0x0, 0
	object_event 3, EVENT_OBJ_GFX_VAR_0, 0, 5, 1, 3, MOVEMENT_TYPE_FACE_DOWN, 1, 1, 0, 0, 0x0, 0

FallarborTown_BattleTentBattleRoom_MapEvents:: @ 852E48C
	map_events FallarborTown_BattleTentBattleRoom_EventObjects, 0x0, 0x0, 0x0

