
	.byte 0x00
	.string "SMALL DESK$     ", 16
	.byte 0x00, 0x00, 0x00
	.2byte 0x0000
	.align 2, 0
	.4byte gUnknown_085A4748
	.4byte gUnknown_085A4514

	.byte 0x01
	.string "SMALL DESK$     ", 16
	.byte 0x00, 0x00, 0x00
	.2byte 0x0bb8
	.align 2, 0
	.4byte gUnknown_085A4748
	.4byte gUnknown_085A4514

	.byte 0x02
	.string "POKéMON DESK$   ", 16
	.byte 0x00, 0x00, 0x00
	.2byte 0x0bb8
	.align 2, 0
	.4byte gUnknown_085A4764
	.4byte gUnknown_085A4516

	.byte 0x03
	.string "HEAVY DESK$     ", 16
	.byte 0x00, 0x09, 0x00
	.2byte 0x1770
	.align 2, 0
	.4byte gUnknown_085A4794
	.4byte gUnknown_085A4518

	.byte 0x04
	.string "RAGGED DESK$    ", 16
	.byte 0x00, 0x09, 0x00
	.2byte 0x1770
	.align 2, 0
	.4byte gUnknown_085A47CC
	.4byte gUnknown_085A4524

	.byte 0x05
	.string "COMFORT DESK$   ", 16
	.byte 0x00, 0x09, 0x00
	.2byte 0x1770
	.align 2, 0
	.4byte gUnknown_085A4803
	.4byte gUnknown_085A4530

	.byte 0x06
	.string "PRETTY DESK$    ", 16
	.byte 0x00, 0x08, 0x00
	.2byte 0x2328
	.align 2, 0
	.4byte gUnknown_085A483C
	.4byte gUnknown_085A453C

	.byte 0x07
	.string "BRICK DESK$     ", 16
	.byte 0x00, 0x08, 0x00
	.2byte 0x2328
	.align 2, 0
	.4byte gUnknown_085A4872
	.4byte gUnknown_085A454E

	.byte 0x08
	.string "CAMP DESK$      ", 16
	.byte 0x00, 0x08, 0x00
	.2byte 0x2328
	.align 2, 0
	.4byte gUnknown_085A48A8
	.4byte gUnknown_085A4560

	.byte 0x09
	.string "HARD DESK$      ", 16
	.byte 0x00, 0x08, 0x00
	.2byte 0x2328
	.align 2, 0
	.4byte gUnknown_085A48E1
	.4byte gUnknown_085A4572

	.byte 0x0a
	.string "SMALL CHAIR$    ", 16
	.byte 0x01, 0x00, 0x01
	.2byte 0x07d0
	.align 2, 0
	.4byte gUnknown_085A4914
	.4byte gUnknown_085A4584

	.byte 0x0b
	.string "POKéMON CHAIR$  ", 16
	.byte 0x01, 0x00, 0x01
	.2byte 0x07d0
	.align 2, 0
	.4byte gUnknown_085A4930
	.4byte gUnknown_085A4586

	.byte 0x0c
	.string "HEAVY CHAIR$    ", 16
	.byte 0x01, 0x00, 0x01
	.2byte 0x07d0
	.align 2, 0
	.4byte gUnknown_085A4961
	.4byte gUnknown_085A4588

	.byte 0x0d
	.string "PRETTY CHAIR$   ", 16
	.byte 0x01, 0x00, 0x01
	.2byte 0x07d0
	.align 2, 0
	.4byte gUnknown_085A497E
	.4byte gUnknown_085A458A

	.byte 0x0e
	.string "COMFORT CHAIR$  ", 16
	.byte 0x01, 0x00, 0x01
	.2byte 0x07d0
	.align 2, 0
	.4byte gUnknown_085A499B
	.4byte gUnknown_085A458C

	.byte 0x0f
	.string "RAGGED CHAIR$   ", 16
	.byte 0x01, 0x00, 0x01
	.2byte 0x07d0
	.align 2, 0
	.4byte gUnknown_085A49B9
	.4byte gUnknown_085A458E

	.byte 0x10
	.string "BRICK CHAIR$    ", 16
	.byte 0x01, 0x00, 0x01
	.2byte 0x07d0
	.align 2, 0
	.4byte gUnknown_085A49D5
	.4byte gUnknown_085A4590

	.byte 0x11
	.string "CAMP CHAIR$     ", 16
	.byte 0x01, 0x00, 0x01
	.2byte 0x07d0
	.align 2, 0
	.4byte gUnknown_085A49F2
	.4byte gUnknown_085A4592

	.byte 0x12
	.string "HARD CHAIR$     ", 16
	.byte 0x01, 0x00, 0x01
	.2byte 0x07d0
	.align 2, 0
	.4byte gUnknown_085A4A0E
	.4byte gUnknown_085A4594

	.byte 0x13
	.string "RED PLANT$      ", 16
	.byte 0x02, 0x05, 0x02
	.2byte 0x0bb8
	.align 2, 0
	.4byte gUnknown_085A4A2A
	.4byte gUnknown_085A4596

	.byte 0x14
	.string "TROPICAL PLANT$ ", 16
	.byte 0x02, 0x05, 0x02
	.2byte 0x0bb8
	.align 2, 0
	.4byte gUnknown_085A4A44
	.4byte gUnknown_085A459A

	.byte 0x15
	.string "PRETTY FLOWERS$ ", 16
	.byte 0x02, 0x05, 0x02
	.2byte 0x0bb8
	.align 2, 0
	.4byte gUnknown_085A4A69
	.4byte gUnknown_085A459E

	.byte 0x16
	.string "COLORFUL PLANT$ ", 16
	.byte 0x02, 0x04, 0x02
	.2byte 0x1388
	.align 2, 0
	.4byte gUnknown_085A4A80
	.4byte gUnknown_085A45A2

	.byte 0x17
	.string "BIG PLANT$      ", 16
	.byte 0x02, 0x04, 0x02
	.2byte 0x1388
	.align 2, 0
	.4byte gUnknown_085A4AA8
	.4byte gUnknown_085A45AA

	.byte 0x18
	.string "GORGEOUS PLANT$ ", 16
	.byte 0x02, 0x04, 0x02
	.2byte 0x1388
	.align 2, 0
	.4byte gUnknown_085A4AD6
	.4byte gUnknown_085A45B2

	.byte 0x19
	.string "RED BRICK$      ", 16
	.byte 0x00, 0x05, 0x03
	.2byte 0x01f4
	.align 2, 0
	.4byte gUnknown_085A4AFE
	.4byte gUnknown_085A45BA

	.byte 0x1a
	.string "YELLOW BRICK$   ", 16
	.byte 0x00, 0x05, 0x03
	.2byte 0x01f4
	.align 2, 0
	.4byte gUnknown_085A4B35
	.4byte gUnknown_085A45BE

	.byte 0x1b
	.string "BLUE BRICK$     ", 16
	.byte 0x00, 0x05, 0x03
	.2byte 0x01f4
	.align 2, 0
	.4byte gUnknown_085A4B6A
	.4byte gUnknown_085A45C2

	.byte 0x1c
	.string "RED BALLOON$    ", 16
	.byte 0x01, 0x00, 0x03
	.2byte 0x01f4
	.align 2, 0
	.4byte gUnknown_085A4B9D
	.4byte gUnknown_085A45C6

	.byte 0x1d
	.string "BLUE BALLOON$   ", 16
	.byte 0x01, 0x00, 0x03
	.2byte 0x01f4
	.align 2, 0
	.4byte gUnknown_085A4BD4
	.4byte gUnknown_085A45C8

	.byte 0x1e
	.string "YELLOW BALLOON$ ", 16
	.byte 0x01, 0x00, 0x03
	.2byte 0x01f4
	.align 2, 0
	.4byte gUnknown_085A4C0C
	.4byte gUnknown_085A45CA

	.byte 0x1f
	.string "RED TENT$       ", 16
	.byte 0x01, 0x08, 0x03
	.2byte 0x2710
	.align 2, 0
	.4byte gUnknown_085A4C44
	.4byte gUnknown_085A45CC

	.byte 0x20
	.string "BLUE TENT$      ", 16
	.byte 0x01, 0x08, 0x03
	.2byte 0x2710
	.align 2, 0
	.4byte gUnknown_085A4C6E
	.4byte gUnknown_085A45DE

	.byte 0x21
	.string "SOLID BOARD$    ", 16
	.byte 0x01, 0x05, 0x03
	.2byte 0x0bb8
	.align 2, 0
	.4byte gUnknown_085A4C99
	.4byte gUnknown_085A45F0

	.byte 0x22
	.string "SLIDE$          ", 16
	.byte 0x01, 0x07, 0x03
	.2byte 0x1f40
	.align 2, 0
	.4byte gUnknown_085A4CC7
	.4byte gUnknown_085A45F4

	.byte 0x23
	.string "FENCE LENGTH$   ", 16
	.byte 0x00, 0x00, 0x03
	.2byte 0x01f4
	.align 2, 0
	.4byte gUnknown_085A4CEC
	.4byte gUnknown_085A4604

	.byte 0x24
	.string "FENCE WIDTH$    ", 16
	.byte 0x00, 0x00, 0x03
	.2byte 0x01f4
	.align 2, 0
	.4byte gUnknown_085A4D0F
	.4byte gUnknown_085A4606

	.byte 0x25
	.string "TIRE$           ", 16
	.byte 0x00, 0x04, 0x03
	.2byte 0x0320
	.align 2, 0
	.4byte gUnknown_085A4D32
	.4byte gUnknown_085A4608

	.byte 0x26
	.string "STAND$          ", 16
	.byte 0x01, 0x03, 0x03
	.2byte 0x1b58
	.align 2, 0
	.4byte gUnknown_085A4D67
	.4byte gUnknown_085A4610

	.byte 0x27
	.string "MUD BALL$       ", 16
	.byte 0x01, 0x00, 0x03
	.2byte 0x00c8
	.align 2, 0
	.4byte gUnknown_085A4D84
	.4byte gUnknown_085A4620

	.byte 0x28
	.string "BREAKABLE DOOR$ ", 16
	.byte 0x01, 0x05, 0x03
	.2byte 0x0bb8
	.align 2, 0
	.4byte gUnknown_085A4DB1
	.4byte gUnknown_085A4622

	.byte 0x29
	.string "SAND ORNAMENT$  ", 16
	.byte 0x02, 0x05, 0x03
	.2byte 0x0bb8
	.align 2, 0
	.4byte gUnknown_085A4DE2
	.4byte gUnknown_085A4626

	.byte 0x2a
	.string "SILVER SHIELD$  ", 16
	.byte 0x02, 0x05, 0x03
	.2byte 0x0000
	.align 2, 0
	.4byte gUnknown_085A4E11
	.4byte gUnknown_085A462A

	.byte 0x2b
	.string "GOLD SHIELD$    ", 16
	.byte 0x02, 0x05, 0x03
	.2byte 0x0000
	.align 2, 0
	.4byte gUnknown_085A4E43
	.4byte gUnknown_085A462E

	.byte 0x2c
	.string "GLASS ORNAMENT$ ", 16
	.byte 0x02, 0x05, 0x03
	.2byte 0x0000
	.align 2, 0
	.4byte gUnknown_085A4E76
	.4byte gUnknown_085A4632

	.byte 0x2d
	.string "TV$             ", 16
	.byte 0x00, 0x00, 0x03
	.2byte 0x0bb8
	.align 2, 0
	.4byte gUnknown_085A4EAF
	.4byte gUnknown_085A4636

	.byte 0x2e
	.string "ROUND TV$       ", 16
	.byte 0x00, 0x00, 0x03
	.2byte 0x0fa0
	.align 2, 0
	.4byte gUnknown_085A4ECE
	.4byte gUnknown_085A4638

	.byte 0x2f
	.string "CUTE TV$        ", 16
	.byte 0x00, 0x00, 0x03
	.2byte 0x0fa0
	.align 2, 0
	.4byte gUnknown_085A4EF9
	.4byte gUnknown_085A463A

	.byte 0x30
	.string "GLITTER MAT$    ", 16
	.byte 0x01, 0x00, 0x04
	.2byte 0x07d0
	.align 2, 0
	.4byte gUnknown_085A4F24
	.4byte gUnknown_085A463C

	.byte 0x31
	.string "JUMP MAT$       ", 16
	.byte 0x01, 0x00, 0x04
	.2byte 0x07d0
	.align 2, 0
	.4byte gUnknown_085A4F4C
	.4byte gUnknown_085A463E

	.byte 0x32
	.string "SPIN MAT$       ", 16
	.byte 0x01, 0x00, 0x04
	.2byte 0x07d0
	.align 2, 0
	.4byte gUnknown_085A4F7A
	.4byte gUnknown_085A4640

	.byte 0x33
	.string "C Low NOTE MAT$ ", 16
	.byte 0x01, 0x00, 0x04
	.2byte 0x01f4
	.align 2, 0
	.4byte gUnknown_085A4FA9
	.4byte gUnknown_085A4642

	.byte 0x34
	.string "D NOTE MAT$     ", 16
	.byte 0x01, 0x00, 0x04
	.2byte 0x01f4
	.align 2, 0
	.4byte gUnknown_085A4FD8
	.4byte gUnknown_085A4644

	.byte 0x35
	.string "E NOTE MAT$     ", 16
	.byte 0x01, 0x00, 0x04
	.2byte 0x01f4
	.align 2, 0
	.4byte gUnknown_085A5003
	.4byte gUnknown_085A4646

	.byte 0x36
	.string "F NOTE MAT$     ", 16
	.byte 0x01, 0x00, 0x04
	.2byte 0x01f4
	.align 2, 0
	.4byte gUnknown_085A502F
	.4byte gUnknown_085A4648

	.byte 0x37
	.string "G NOTE MAT$     ", 16
	.byte 0x01, 0x00, 0x04
	.2byte 0x01f4
	.align 2, 0
	.4byte gUnknown_085A505B
	.4byte gUnknown_085A464A

	.byte 0x38
	.string "A NOTE MAT$     ", 16
	.byte 0x01, 0x00, 0x04
	.2byte 0x01f4
	.align 2, 0
	.4byte gUnknown_085A5086
	.4byte gUnknown_085A464C

	.byte 0x39
	.string "B NOTE MAT$     ", 16
	.byte 0x01, 0x00, 0x04
	.2byte 0x01f4
	.align 2, 0
	.4byte gUnknown_085A50B2
	.4byte gUnknown_085A464E

	.byte 0x3a
	.string "C High NOTE MAT$", 16
	.byte 0x01, 0x00, 0x04
	.2byte 0x01f4
	.align 2, 0
	.4byte gUnknown_085A50DD
	.4byte gUnknown_085A4650

	.byte 0x3b
	.string "SURF MAT$       ", 16
	.byte 0x01, 0x08, 0x04
	.2byte 0x0fa0
	.align 2, 0
	.4byte gUnknown_085A510D
	.4byte gUnknown_085A4652

	.byte 0x3c
	.string "THUNDER MAT$    ", 16
	.byte 0x01, 0x08, 0x04
	.2byte 0x0fa0
	.align 2, 0
	.4byte gUnknown_085A5141
	.4byte gUnknown_085A4664

	.byte 0x3d
	.string "FIRE BLAST MAT$ ", 16
	.byte 0x01, 0x08, 0x04
	.2byte 0x0fa0
	.align 2, 0
	.4byte gUnknown_085A5178
	.4byte gUnknown_085A4676

	.byte 0x3e
	.string "POWDER SNOW MAT$", 16
	.byte 0x01, 0x08, 0x04
	.2byte 0x0fa0
	.align 2, 0
	.4byte gUnknown_085A51B2
	.4byte gUnknown_085A4688

	.byte 0x3f
	.string "ATTRACT MAT$    ", 16
	.byte 0x01, 0x08, 0x04
	.2byte 0x0fa0
	.align 2, 0
	.4byte gUnknown_085A51EB
	.4byte gUnknown_085A469A

	.byte 0x40
	.string "FISSURE MAT$    ", 16
	.byte 0x01, 0x08, 0x04
	.2byte 0x0fa0
	.align 2, 0
	.4byte gUnknown_085A5223
	.4byte gUnknown_085A46AC

	.byte 0x41
	.string "SPIKES MAT$     ", 16
	.byte 0x01, 0x08, 0x04
	.2byte 0x0fa0
	.align 2, 0
	.4byte gUnknown_085A525A
	.4byte gUnknown_085A46BE

	.byte 0x42
	.string "BALL POSTER$    ", 16
	.byte 0x03, 0x00, 0x05
	.2byte 0x03e8
	.align 2, 0
	.4byte gUnknown_085A5290
	.4byte gUnknown_085A46D0

	.byte 0x43
	.string "GREEN POSTER$   ", 16
	.byte 0x03, 0x00, 0x05
	.2byte 0x03e8
	.align 2, 0
	.4byte gUnknown_085A52B8
	.4byte gUnknown_085A46D2

	.byte 0x44
	.string "RED POSTER$     ", 16
	.byte 0x03, 0x00, 0x05
	.2byte 0x03e8
	.align 2, 0
	.4byte gUnknown_085A52DD
	.4byte gUnknown_085A46D4

	.byte 0x45
	.string "BLUE POSTER$    ", 16
	.byte 0x03, 0x00, 0x05
	.2byte 0x03e8
	.align 2, 0
	.4byte gUnknown_085A5302
	.4byte gUnknown_085A46D6

	.byte 0x46
	.string "CUTE POSTER$    ", 16
	.byte 0x03, 0x00, 0x05
	.2byte 0x03e8
	.align 2, 0
	.4byte gUnknown_085A5326
	.4byte gUnknown_085A46D8

	.byte 0x47
	.string "PIKA POSTER$    ", 16
	.byte 0x03, 0x01, 0x05
	.2byte 0x05dc
	.align 2, 0
	.4byte gUnknown_085A534C
	.4byte gUnknown_085A46DA

	.byte 0x48
	.string "LONG POSTER$    ", 16
	.byte 0x03, 0x01, 0x05
	.2byte 0x05dc
	.align 2, 0
	.4byte gUnknown_085A537B
	.4byte gUnknown_085A46DE

	.byte 0x49
	.string "SEA POSTER$     ", 16
	.byte 0x03, 0x01, 0x05
	.2byte 0x05dc
	.align 2, 0
	.4byte gUnknown_085A53A0
	.4byte gUnknown_085A46E2

	.byte 0x4a
	.string "SKY POSTER$     ", 16
	.byte 0x03, 0x01, 0x05
	.2byte 0x05dc
	.align 2, 0
	.4byte gUnknown_085A53C7
	.4byte gUnknown_085A46E6

	.byte 0x4b
	.string "KISS POSTER$    ", 16
	.byte 0x03, 0x01, 0x05
	.2byte 0x05dc
	.align 2, 0
	.4byte gUnknown_085A53EC
	.4byte gUnknown_085A46EA

	.byte 0x4c
	.string "PICHU DOLL$     ", 16
	.byte 0x04, 0x00, 0x06
	.2byte 0x0bb8
	.align 2, 0
	.4byte gUnknown_085A5412
	.4byte gUnknown_085A46EE

	.byte 0x4d
	.string "PIKACHU DOLL$   ", 16
	.byte 0x04, 0x00, 0x06
	.2byte 0x0bb8
	.align 2, 0
	.4byte gUnknown_085A543D
	.4byte gUnknown_085A46F0

	.byte 0x4e
	.string "MARILL DOLL$    ", 16
	.byte 0x04, 0x00, 0x06
	.2byte 0x0bb8
	.align 2, 0
	.4byte gUnknown_085A546A
	.4byte gUnknown_085A46F2

	.byte 0x4f
	.string "TOGEPI DOLL$    ", 16
	.byte 0x04, 0x00, 0x06
	.2byte 0x0bb8
	.align 2, 0
	.4byte gUnknown_085A5496
	.4byte gUnknown_085A46F4

	.byte 0x50
	.string "CYNDAQUIL DOLL$ ", 16
	.byte 0x04, 0x00, 0x06
	.2byte 0x0bb8
	.align 2, 0
	.4byte gUnknown_085A54C2
	.4byte gUnknown_085A46F6

	.byte 0x51
	.string "CHIKORITA DOLL$ ", 16
	.byte 0x04, 0x00, 0x06
	.2byte 0x0bb8
	.align 2, 0
	.4byte gUnknown_085A54F1
	.4byte gUnknown_085A46F8

	.byte 0x52
	.string "TOTODILE DOLL$  ", 16
	.byte 0x04, 0x00, 0x06
	.2byte 0x0bb8
	.align 2, 0
	.4byte gUnknown_085A5520
	.4byte gUnknown_085A46FA

	.byte 0x53
	.string "JIGGLYPUFF DOLL$", 16
	.byte 0x04, 0x00, 0x06
	.2byte 0x0bb8
	.align 2, 0
	.4byte gUnknown_085A554E
	.4byte gUnknown_085A46FC

	.byte 0x54
	.string "MEOWTH DOLL$    ", 16
	.byte 0x04, 0x00, 0x06
	.2byte 0x0bb8
	.align 2, 0
	.4byte gUnknown_085A557E
	.4byte gUnknown_085A46FE

	.byte 0x55
	.string "CLEFAIRY DOLL$  ", 16
	.byte 0x04, 0x00, 0x06
	.2byte 0x0bb8
	.align 2, 0
	.4byte gUnknown_085A55AA
	.4byte gUnknown_085A4700

	.byte 0x56
	.string "DITTO DOLL$     ", 16
	.byte 0x04, 0x00, 0x06
	.2byte 0x0bb8
	.align 2, 0
	.4byte gUnknown_085A55D8
	.4byte gUnknown_085A4702

	.byte 0x57
	.string "SMOOCHUM DOLL$  ", 16
	.byte 0x04, 0x00, 0x06
	.2byte 0x0bb8
	.align 2, 0
	.4byte gUnknown_085A5603
	.4byte gUnknown_085A4704

	.byte 0x58
	.string "TREECKO DOLL$   ", 16
	.byte 0x04, 0x00, 0x06
	.2byte 0x0bb8
	.align 2, 0
	.4byte gUnknown_085A5631
	.4byte gUnknown_085A4706

	.byte 0x59
	.string "TORCHIC DOLL$   ", 16
	.byte 0x04, 0x00, 0x06
	.2byte 0x0bb8
	.align 2, 0
	.4byte gUnknown_085A565E
	.4byte gUnknown_085A4708

	.byte 0x5a
	.string "MUDKIP DOLL$    ", 16
	.byte 0x04, 0x00, 0x06
	.2byte 0x0bb8
	.align 2, 0
	.4byte gUnknown_085A568B
	.4byte gUnknown_085A470A

	.byte 0x5b
	.string "DUSKULL DOLL$   ", 16
	.byte 0x04, 0x00, 0x06
	.2byte 0x0bb8
	.align 2, 0
	.4byte gUnknown_085A56B7
	.4byte gUnknown_085A470C

	.byte 0x5c
	.string "WYNAUT DOLL$    ", 16
	.byte 0x04, 0x00, 0x06
	.2byte 0x0bb8
	.align 2, 0
	.4byte gUnknown_085A56E4
	.4byte gUnknown_085A470E

	.byte 0x5d
	.string "BALTOY DOLL$    ", 16
	.byte 0x04, 0x00, 0x06
	.2byte 0x0bb8
	.align 2, 0
	.4byte gUnknown_085A5710
	.4byte gUnknown_085A4710

	.byte 0x5e
	.string "KECLEON DOLL$   ", 16
	.byte 0x04, 0x00, 0x06
	.2byte 0x0bb8
	.align 2, 0
	.4byte gUnknown_085A573C
	.4byte gUnknown_085A4712

	.byte 0x5f
	.string "AZURILL DOLL$   ", 16
	.byte 0x04, 0x00, 0x06
	.2byte 0x0bb8
	.align 2, 0
	.4byte gUnknown_085A5769
	.4byte gUnknown_085A4714

	.byte 0x60
	.string "SKITTY DOLL$    ", 16
	.byte 0x04, 0x00, 0x06
	.2byte 0x0bb8
	.align 2, 0
	.4byte gUnknown_085A5797
	.4byte gUnknown_085A4716

	.byte 0x61
	.string "SWABLU DOLL$    ", 16
	.byte 0x04, 0x00, 0x06
	.2byte 0x0bb8
	.align 2, 0
	.4byte gUnknown_085A57C3
	.4byte gUnknown_085A4718

	.byte 0x62
	.string "GULPIN DOLL$    ", 16
	.byte 0x04, 0x00, 0x06
	.2byte 0x0bb8
	.align 2, 0
	.4byte gUnknown_085A57EF
	.4byte gUnknown_085A471A

	.byte 0x63
	.string "LOTAD DOLL$     ", 16
	.byte 0x04, 0x00, 0x06
	.2byte 0x0bb8
	.align 2, 0
	.4byte gUnknown_085A581B
	.4byte gUnknown_085A471C

	.byte 0x64
	.string "SEEDOT DOLL$    ", 16
	.byte 0x04, 0x00, 0x06
	.2byte 0x0bb8
	.align 2, 0
	.4byte gUnknown_085A5846
	.4byte gUnknown_085A471E

	.byte 0x65
	.string "PIKA CUSHION$   ", 16
	.byte 0x04, 0x00, 0x07
	.2byte 0x07d0
	.align 2, 0
	.4byte gUnknown_085A5872
	.4byte gUnknown_085A4720

	.byte 0x66
	.string "ROUND CUSHION$  ", 16
	.byte 0x04, 0x00, 0x07
	.2byte 0x07d0
	.align 2, 0
	.4byte gUnknown_085A58A2
	.4byte gUnknown_085A4722

	.byte 0x67
	.string "KISS CUSHION$   ", 16
	.byte 0x04, 0x00, 0x07
	.2byte 0x07d0
	.align 2, 0
	.4byte gUnknown_085A58D1
	.4byte gUnknown_085A4724

	.byte 0x68
	.string "ZIGZAG CUSHION$ ", 16
	.byte 0x04, 0x00, 0x07
	.2byte 0x07d0
	.align 2, 0
	.4byte gUnknown_085A5902
	.4byte gUnknown_085A4726

	.byte 0x69
	.string "SPIN CUSHION$   ", 16
	.byte 0x04, 0x00, 0x07
	.2byte 0x07d0
	.align 2, 0
	.4byte gUnknown_085A5934
	.4byte gUnknown_085A4728

	.byte 0x6a
	.string "DIAMOND CUSHION$", 16
	.byte 0x04, 0x00, 0x07
	.2byte 0x07d0
	.align 2, 0
	.4byte gUnknown_085A5963
	.4byte gUnknown_085A472A

	.byte 0x6b
	.string "BALL CUSHION$   ", 16
	.byte 0x04, 0x00, 0x07
	.2byte 0x07d0
	.align 2, 0
	.4byte gUnknown_085A5993
	.4byte gUnknown_085A472C

	.byte 0x6c
	.string "GRASS CUSHION$  ", 16
	.byte 0x04, 0x00, 0x07
	.2byte 0x07d0
	.align 2, 0
	.4byte gUnknown_085A59C0
	.4byte gUnknown_085A472E

	.byte 0x6d
	.string "FIRE CUSHION$   ", 16
	.byte 0x04, 0x00, 0x07
	.2byte 0x07d0
	.align 2, 0
	.4byte gUnknown_085A59F3
	.4byte gUnknown_085A4730

	.byte 0x6e
	.string "WATER CUSHION$  ", 16
	.byte 0x04, 0x00, 0x07
	.2byte 0x07d0
	.align 2, 0
	.4byte gUnknown_085A5A25
	.4byte gUnknown_085A4732

	.byte 0x6f
	.string "SNORLAX DOLL$   ", 16
	.byte 0x04, 0x05, 0x06
	.2byte 0x2710
	.align 2, 0
	.4byte gUnknown_085A5A58
	.4byte gUnknown_085A4734

	.byte 0x70
	.string "RHYDON DOLL$    ", 16
	.byte 0x04, 0x05, 0x06
	.2byte 0x2710
	.align 2, 0
	.4byte gUnknown_085A5A83
	.4byte gUnknown_085A4736

	.byte 0x71
	.string "LAPRAS DOLL$    ", 16
	.byte 0x04, 0x05, 0x06
	.2byte 0x2710
	.align 2, 0
	.4byte gUnknown_085A5AAE
	.4byte gUnknown_085A4738

	.byte 0x72
	.string "VENUSAUR DOLL$  ", 16
	.byte 0x04, 0x05, 0x06
	.2byte 0x2710
	.align 2, 0
	.4byte gUnknown_085A5AD9
	.4byte gUnknown_085A473A

	.byte 0x73
	.string "CHARIZARD DOLL$ ", 16
	.byte 0x04, 0x05, 0x06
	.2byte 0x2710
	.align 2, 0
	.4byte gUnknown_085A5B04
	.4byte gUnknown_085A473C

	.byte 0x74
	.string "BLASTOISE DOLL$ ", 16
	.byte 0x04, 0x05, 0x06
	.2byte 0x2710
	.align 2, 0
	.4byte gUnknown_085A5B2F
	.4byte gUnknown_085A473E

	.byte 0x75
	.string "WAILMER DOLL$   ", 16
	.byte 0x04, 0x05, 0x06
	.2byte 0x2710
	.align 2, 0
	.4byte gUnknown_085A5B5A
	.4byte gUnknown_085A4740

	.byte 0x76
	.string "REGIROCK DOLL$  ", 16
	.byte 0x04, 0x05, 0x06
	.2byte 0x2710
	.align 2, 0
	.4byte gUnknown_085A5B85
	.4byte gUnknown_085A4742

	.byte 0x77
	.string "REGICE DOLL$    ", 16
	.byte 0x04, 0x05, 0x06
	.2byte 0x2710
	.align 2, 0
	.4byte gUnknown_085A5BB0
	.4byte gUnknown_085A4744

	.byte 0x78
	.string "REGISTEEL DOLL$ ", 16
	.byte 0x04, 0x05, 0x06
	.2byte 0x2710
	.align 2, 0
	.4byte gUnknown_085A5BDB
	.4byte gUnknown_085A4746
