AbandonedShip_Rooms2_B1F_MapScripts::
	.byte 0

AbandonedShip_Rooms2_B1F_EventScript_Camper::
	msgbox AbandonedShip_Rooms2_B1F_Text_PerfectPlaceToGoExploring, MSGBOX_NPC
	end

AbandonedShip_Rooms2_B1F_Text_PerfectPlaceToGoExploring:
	.string "C’est l’endroit idéal pour une petite\n"
	.string "exploration! C’est passionnant ici!\p"
	.string "Je parie qu’il y a de stupéfiants\n"
	.string "trésors à bord.$"

