SafariZone_Northwest_EventObjects: @ 853B11C
	object_event 1, EVENT_OBJ_GFX_MAN_1, 0, 8, 8, 5, MOVEMENT_TYPE_FACE_DOWN, 0, 0, 0, 0, SafariZone_Northwest_EventScript_23D24A, 0
	object_event 2, EVENT_OBJ_GFX_ITEM_BALL, 0, 33, 7, 3, MOVEMENT_TYPE_LOOK_AROUND, 1, 1, 0, 0, SafariZone_Northwest_EventScript_2912BC, FLAG_0x446

SafariZone_Northwest_MapEvents:: @ 853B14C
	map_events SafariZone_Northwest_EventObjects, 0x0, 0x0, 0x0

