
LittlerootTown_ProfessorBirchsLab_Text_BirchAwayOnFieldwork:
	.string "Eh? Il PROF. BIRCH?\p"
	.string "Il PROFESSORE è fuori per una ricerca\n"
	.string "sul campo. Mi dispiace, ma non c’è!\p"
	.string "Ah, sì, ti spiego cos’è una ricerca\n"
	.string "sul campo.\p"
	.string "È uno studio condotto nell’ambiente\n"
	.string "naturale, in campagna o in montagna,\l"
	.string "invece che in laboratorio.\p"
	.string "Il PROFESSORE non è tipo da star\n"
	.string "seduto alla scrivania. Preferisce\l"
	.string "il metodo empirico a quello tradizionale\l"
	.string "di imparare le nozioni dai libri.$"

LittlerootTown_ProfessorBirchsLab_Text_BirchIsntOneForDeskWork:
	.string "Il PROFESSORE non è tipo da star\n"
	.string "seduto alla scrivania. Preferisce\l"
	.string "il metodo empirico a quello tradizionale\l"
	.string "di imparare le nozioni dai libri.$"

LittlerootTown_ProfessorBirchsLab_Text_BirchEnjoysRivalsHelpToo:
	.string "Il PROF. BIRCH studia l’habitat e la\n"
	.string "diffusione dei POKéMON sul territorio.\p"
	.string "Al PROFESSORE piace anche farsi\n"
	.string "aiutare da {RIVAL}!$"

LittlerootTown_ProfessorBirchsLab_Text_LikeYouToHavePokemon:
	.string "PROF. BIRCH: Allora, {PLAYER}{KUN}.\p"
	.string "Ho sentito tanto parlare di te\n"
	.string "da tuo padre.\p"
	.string "Ma so anche che non hai ancora\n"
	.string "ricevuto il tuo POKéMON.\p"
	.string "Ma da come hai lottato prima…\n"
	.string "capisco che hai del talento!\p"
	.string "Suppongo tu abbia preso da\n"
	.string "tuo padre! Di certo è così!\p"
	.string "Ah, sì, grazie per avermi aiutato\n"
	.string "prima. Puoi tenerti il POKéMON\l"
	.string "che hai scelto.\p"
	.string "{PLAYER} riceve {STR_VAR_1}!$"

LittlerootTown_ProfessorBirchsLab_Text_WhyNotGiveNicknameToMon:
	.string "PROF. BIRCH: E già che ci sei, perché\n"
	.string "non dai un soprannome a {STR_VAR_1}?$"

LittlerootTown_ProfessorBirchsLab_Text_MightBeGoodIdeaToGoSeeRival:
	.string "PROF. BIRCH: Se ti dedichi ai POKéMON e\n"
	.string "accumuli esperienza, diventerai\l"
	.string "senz’altro un ALLENATORE in gamba.\p"
	.string "{RIVAL} studia i POKéMON e al\n"
	.string "contempo mi dà una mano.\p"
	.string "{PLAYER}{KUN}, perché non vai a cercare\n"
	.string "{RIVAL}? È una buona idea, non trovi?$"

LittlerootTown_ProfessorBirchsLab_Text_GetRivalToTeachYou:
	.string "PROF. BIRCH: Fantastico!\n"
	.string "{RIVAL} ne sarà felice!\p"
	.string "Fatti insegnare da {RIVAL} cosa\n"
	.string "significa essere un ALLENATORE.$"

LittlerootTown_ProfessorBirchsLab_Text_DontBeThatWay:
	.string "PROF. BIRCH: Oh, non fare così!\n"
	.string "Voglio che facciate amicizia!$"

LittlerootTown_ProfessorBirchsLab_Text_BirchRivalGoneHome:
	.string "PROF. BIRCH: {RIVAL}?\n"
	.string "Credo che sia a casa.\p"
	.string "O forse si sta dando da fare in\n"
	.string "qualche area erbosa…\p"
	.string "Se tu o i tuoi POKéMON vi stancate,\n"
	.string "tornate a casa a riposarvi.$"

LittlerootTown_ProfessorBirchsLab_Text_HeardYouBeatRivalTakePokedex:
	.string "PROF. BIRCH: Oh, ciao {PLAYER}{KUN}!\p"
	.string "Ho saputo che hai battuto {RIVAL}\n"
	.string "nella tua prima lotta. Eccellente!\p"
	.string "{RIVAL} mi aiuta sempre a condurre\n"
	.string "le mie ricerche.\p"
	.string "{RIVAL} ha già molta esperienza\n"
	.string "come ALLENATORE.\p"
	.string "Tieni, {PLAYER}{KUN}, l’ho ordinato per le mie\n"
	.string "ricerche, ma vorrei che questo POKéDEX\l"
	.string "lo usassi tu.$"

LittlerootTown_ProfessorBirchsLab_Text_ReceivedPokedex:
	.string "{PLAYER} riceve il POKéDEX!$"

LittlerootTown_ProfessorBirchsLab_Text_ExplainPokedex:
	.string "PROF. BIRCH: Il POKéDEX è un dispositivo\n"
	.string "ad alta tecnologia che registra \l"
	.string "automaticamente ogni POKéMON\l"
	.string "visto o catturato.\p"
	.string "{RIVAL} lo porta sempre con sé.\p"
	.string "Ogni volta che cattura un POKéMON raro,\n"
	.string "il POKéDEX ne registra i dati, poi\l"
	.string "{RIVAL} mi cerca, anche se sono fuori\l"
	.string "per i miei studi, e me lo fa vedere.$"

LittlerootTown_ProfessorBirchsLab_Text_CountlessPokemonAwait:
	.string "PROF. BIRCH: Forza! Ci sono moltissimi\n"
	.string "POKéMON che ti aspettano!\p"
	.string "Bene, devo tornare alla mia ricerca\n"
	.string "sul campo!$"

LittlerootTown_ProfessorBirchsLab_Text_MayGotPokedexTooTakeThese:
	.string "VERA: Ehi, {PLAYER}{KUN}!\n"
	.string "Ora hai un POKéDEX anche tu!\p"
	.string "Fantastico! È uguale al mio!\n"
	.string "Guarda, ho una cosa per te!$"

LittlerootTown_ProfessorBirchsLab_Text_CatchCutePokemonWithPokeBalls:
	.string "VERA: È divertente catturare\n"
	.string "un sacco di POKéMON!\p"
	.string "Andrò in giro dappertutto in cerca\n"
	.string "di diversi tipi di POKéMON.\p"
	.string "Se ne trovo di graziosi, li catturerò\n"
	.string "con le POKé BALL!$"

LittlerootTown_ProfessorBirchsLab_Text_OhYourBagsFull:
	.string "Cosa? Hai lo ZAINO pieno?$"

LittlerootTown_ProfessorBirchsLab_Text_MayWhereShouldIGoNext:
	.string "VERA: Mi chiedo dove posso andare a\n"
	.string "catturare dei POKéMON ora…$"

LittlerootTown_ProfessorBirchsLab_Text_BrendanGotPokedexTooTakeThese:
	.string "BRENDON: Eh…\n"
	.string "Hai un POKéDEX anche tu?\p"
	.string "Allora… prendi questo!$"

LittlerootTown_ProfessorBirchsLab_Text_CatchCoolPokemonWithPokeBalls:
	.string "BRENDON: Sai, è molto più divertente\n"
	.string "avere una bella squadra di POKéMON.\p"
	.string "Esplorerò tutta la zona per trovarne\n"
	.string "di ogni tipo.\p"
	.string "Se trovo POKéMON in gamba, li catturerò\n"
	.string "con le POKé BALL, stanne certa!$"

LittlerootTown_ProfessorBirchsLab_Text_HeyYourBagsFull:
	.string "Ehi, ma hai lo ZAINO pieno!$"

LittlerootTown_ProfessorBirchsLab_Text_BrendanWhereShouldIGoNext:
	.string "BRENDON: Dove potrei cercare\n"
	.string "altri POKéMON ora?$"

LittlerootTown_ProfessorBirchsLab_Text_SeriousLookingMachine:
	.string "Questa è una macchina seria!\n"
	.string "Servirà per la ricerca del PROFESSORE!$"

LittlerootTown_ProfessorBirchsLab_Text_PCUsedForResearch:
	.string "Un PC per la ricerca.\n"
	.string "Meglio non combinare pasticci.$"

LittlerootTown_ProfessorBirchsLab_Text_CrammedWithBooksOnPokemon:
	.string "È pieno zeppo di libri sui POKéMON.$"

LittlerootTown_ProfessorBirchsLab_Text_BookTooHardToRead:
	.string "Un libro: troppo difficile da leggere!$"

LittlerootTown_ProfessorBirchsLab_Text_OtherRegionsUpgradeToNational:
	.string "PROF. BIRCH: Ora…\p"
	.string "{PLAYER}{KUN} e {RIVAL}, voi due mi avete\n"
	.string "aiutato a studiare i POKéMON.\p"
	.string "Grazie al vostro aiuto, stanno\n"
	.string "emergendo nuovi fatti.\p"
	.string "Pare che nella regione di HOENN,\n"
	.string "siano apparsi POKéMON di altre\l"
	.string "regioni.\p"
	.string "Questo dimostra la ricchezza e\n"
	.string "la varietà degli ambienti naturali\l"
	.string "della regione di HOENN.\p"
	.string "Credo che sia giunta l’ora di\n"
	.string "aggiungere il DEX NAZIONALE\l"
	.string "al POKéDEX.\p"
	.string "Mostratemi i vostri POKéDEX.$"

LittlerootTown_ProfessorBirchsLab_Text_MayUpgradeSoCool:
	.string "VERA: Eheheh!\p"
	.string "Sono contenta che anche il mio POKéDEX\n"
	.string "venga aggiornato!\p"
	.string "Lo devo a te, perché hai catturato\n"
	.string "così tanti POKéMON, {PLAYER}{KUN}!$"

LittlerootTown_ProfessorBirchsLab_Text_BrendanYouCanThankMe:
	.string "BRENDON: Ho girato in lungo e in largo\n"
	.string "tutta la regione di HOENN e mi sono\l"
	.string "dato da fare coi POKéMON.\p"
	.string "Devi ringraziare solo me se\n"
	.string "al tuo POKéDEX viene aggiunto\l"
	.string "il DEX NAZIONALE.\p"
	.string "Bella fortuna, {PLAYER}!$"

LittlerootTown_ProfessorBirchsLab_Text_OkayAllDone:
	.string "PROF. BIRCH: Okay, ecco fatto!$"

LittlerootTown_ProfessorBirchsLab_Text_PokedexUpgradedToNational:
	.string "È stato aggiunto il DEX NAZIONALE\n"
	.string "al POKéDEX di {PLAYER}.$"

LittlerootTown_ProfessorBirchsLab_Text_GrassyPatchWaiting2:
	.string "PROF. BIRCH: Ascolta.\n"
	.string "Ora che sei CAMPIONE, la tua avventura\l"
	.string "con i POKéMON non finisce.\p"
	.string "Il tuo cammino insieme ai POKéMON\n"
	.string "non è destinato a terminare.\p"
	.string "Da qualche parte, ti attende un’area\n"
	.string "erbosa!$"

LittlerootTown_ProfessorBirchsLab_Text_MayTakeBreakFromFieldwork:
	.string "VERA: Ho intenzione di prendermi una\n"
	.string "breve pausa dalla ricerca sul campo.\p"
	.string "Credo che aiuterò il PROF. per un po’.$"

LittlerootTown_ProfessorBirchsLab_Text_BrendanTakeBreakFromFieldwork:
	.string "BRENDON: Mi prenderò una pausa\n"
	.string "dalla ricerca sul campo.\p"
	.string "Credo che aiuterò il PROF. per un po’.$"

LittlerootTown_ProfessorBirchsLab_Text_CompletedDexChoosePokemon:
	.string "PROF. BIRCH: Oh, {PLAYER}{KUN}!\n"
	.string "Fammi dare un’occhiata al tuo POKéDEX.\p"
	.string "… … … … … …\n"
	.string "… … … … … …\p"
	.string "Non ci sono dubbi.\p"
	.string "Hai completato il POKéDEX di tutta\n"
	.string "la regione di HOENN.\p"
	.string "È un risultato strabiliante.\p"
	.string "Ho un regalo per te.\p"
	.string "È un segno della mia riconoscenza per\n"
	.string "il fantastico lavoro che hai svolto.\p"
	.string "Il mio omaggio è un POKéMON raro\n"
	.string "che si trova solo in un’altra regione!\p"
	.string "Puoi scegliere uno di questi tre\n"
	.string "POKéMON!$"

LittlerootTown_ProfessorBirchsLab_Text_CanHaveAnyOneOfRarePokemon:
	.string "PROF. BIRCH: Questi sono POKéMON rari\n"
	.string "che si trovano solo in un’altra regione!\p"
	.string "Puoi scegliere uno di questi tre\n"
	.string "POKéMON!$"

LittlerootTown_ProfessorBirchsLab_Text_YoullTakeCyndaquil:
	.string "PROF. BIRCH: CYNDAQUIL, POKéMON di tipo\n"
	.string "FUOCO, ha suscitato il tuo interesse!\p"
	.string "Sei molto intelligente!\p"
	.string "Allora vuoi prendere CYNDAQUIL?$"

LittlerootTown_ProfessorBirchsLab_Text_YoullTakeTotodile:
	.string "PROF. BIRCH: Hai scelto TOTODILE, \n"
	.string "POKéMON di tipo ACQUA!\p"
	.string "Una scelta azzeccata.\p"
	.string "Allora vuoi prendere TOTODILE?$"

LittlerootTown_ProfessorBirchsLab_Text_YoullTakeChikorita:
	.string "PROF. BIRCH: Hai scelto CHIKORITA,\n"
	.string "POKéMON di tipo ERBA!\p"
	.string "Di sicuro hai le idee chiare.\p"
	.string "Allora vuoi prendere CHIKORITA?$"

LittlerootTown_ProfessorBirchsLab_Text_TakeYourTimeAllInvaluable:
	.string "PROF. BIRCH: Scegli pure con calma.\p"
	.string "Sono tutti POKéMON preziosi.$"

@ Unused
LittlerootTown_ProfessorBirchsLab_Text_PickedFinePokemon:
	.string "PROF. BIRCH: I see!\n"
	.string "You picked a fine POKéMON!$"

LittlerootTown_ProfessorBirchsLab_Text_ReceivedJohtoStarter:
	.string "{PLAYER} riceve {STR_VAR_1}\n"
	.string "dal PROF. BIRCH!$"

@ Unused
LittlerootTown_ProfessorBirchsLab_Text_NicknameJohtoStarter:
	.string "Want to give a nickname to\n"
	.string "the {STR_VAR_1} you received?$"

LittlerootTown_ProfessorBirchsLab_Text_GrassyPatchWaiting:
	.string "PROF. BIRCH: Ascolta, {PLAYER}{KUN}.\n"
	.string "Anche se hai completato il POKéDEX\l"
	.string "della regione di HOENN, la tua avventura\l"
	.string "con i POKéMON non finisce.\p"
	.string "Il tuo cammino insieme ai POKéMON\n"
	.string "non è destinato a terminare.\p"
	.string "Da qualche parte, ti attende un’area\n"
	.string "erbosa!$"

LittlerootTown_ProfessorBirchsLab_Text_BetterLeaveOthersAlone:
	.string "Hai ricevuto il POKéMON che ti era\n"
	.string "stato promesso. Lascia stare gli altri.$"

@ Unused
LittlerootTown_ProfessorBirchsLab_Text_DontHaveAnyRoomForPokemon:
	.string "Oh, you don’t have any room for\n"
	.string "this POKéMON.$"

LittlerootTown_ProfessorBirchsLab_Text_MayWhatNextImStayingHere:
	.string "VERA: {PLAYER}{KUN}, quali intenzioni hai\n"
	.string "adesso?\p"
	.string "Continuerai a lottare e ad affinare\n"
	.string "la tua tecnica?\p"
	.string "O cercherai di completare il tuo\n"
	.string "POKéDEX NAZIONALE?\p"
	.string "Io rimango qui ad aiutare il PROF.$"

LittlerootTown_ProfessorBirchsLab_Text_BrendanPreferCollectingSlowly:
	.string "BRENDON: Invece di collezionare altri\n"
	.string "POKéMON, preferisco allevare con cura \l"
	.string "quello che ho scelto.$"

LittlerootTown_ProfessorBirchsLab_Text_MayHaveYouGoneToBattleFrontier:
	.string "VERA: Ciao, {PLAYER}{KUN}!\n"
	.string "Hai visitato il PARCO LOTTA?$"

LittlerootTown_ProfessorBirchsLab_Text_BrendanHaveYouGoneToBattleFrontier:
	.string "BRENDON: Ciao, {PLAYER}!\n"
	.string "Hai visitato quel posto che\l"
	.string "chiamano PARCO LOTTA?$"

LittlerootTown_ProfessorBirchsLab_Text_ScottAboardSSTidalCall:
	.string "… … … … … …\n"
	.string "… … … … … Driiin!\p"
	.string "SCOTT: Ciao, {PLAYER}!\n"
	.string "Sono SCOTT.\p"
	.string "Mi trovo a bordo della M/N MAREA.\n"
	.string "Adoro attraversare il mare!\p"
	.string "A proposito…\p"
	.string "C’è un posto che ti invito a\n"
	.string "visitare.\p"
	.string "Se ti va, prendi il traghetto\n"
	.string "a SELCEPOLI o ALGHEPOLI.\p"
	.string "Ti darò ulteriori dettagli quando\n"
	.string "ci incontriamo. Ti aspetto!\p"
	.string "… … … … … …\n"
	.string "… … … … … Click!$"
