MtPyre_4F_MapScripts:: @ 8231BC8
	.byte 0

MtPyre_5F_EventScript_231BC9:: @ 8231BC9
	trainerbattle_single TRAINER_ATSUSHI, MtPyre_5F_Text_231BE0, MtPyre_5F_Text_231C08
	msgbox MtPyre_5F_Text_231C24, MSGBOX_AUTOCLOSE
	end

MtPyre_5F_Text_231BE0: @ 8231BE0
	.string "Teacher…\n"
	.string "Please watch over my progress!$"

MtPyre_5F_Text_231C08: @ 8231C08
	.string "Teacher…\n"
	.string "Please forgive me!$"

MtPyre_5F_Text_231C24: @ 8231C24
	.string "Until I improve, my teacher, who rests\n"
	.string "here, will never find true peace…$"

