
FortreeCity_House5_Text_TreeHousesAreGreat:
	.string "Le case sugli alberi di FORESTOPOLI\n"
	.string "sono fantastiche!\p"
	.string "Credo che sia la città più adatta\n"
	.string "per vivere insieme ai POKéMON.$"

FortreeCity_House5_Text_AdaptedToNature:
	.string "I POKéMON e la gente vivono in armonia\n"
	.string "con la natura.\p"
	.string "Non c’è bisogno di plasmare la natura\n"
	.string "al nostro stile di vita.$"

FortreeCity_House5_Text_Zigzagoon:
	.string "ZIGZAGOON: ZigzagZigzag…!$"
