
DewfordTown_House1_Text_LotToBeSaidForLivingOnIsland:
	.string "C’è molto da dire sulla vita su\n"
	.string "un’isoletta come questa, in perfetta\l"
	.string "armonia con i POKéMON e la famiglia.$"

DewfordTown_House1_Text_LifeGoesSlowlyOnIsland:
	.string "Prima abitavo nella grande città\n"
	.string "portuale di PORTO SELCEPOLI,\l"
	.string "poi mi sono sposata e sono venuta qui.\p"
	.string "La vita scorre lenta su quest’isoletta.\n"
	.string "Ma lo stupendo mare che la circonda\l"
	.string "infonde gioia e serenità.$"

DewfordTown_House1_Text_Zigzagoon:
	.string "ZIGZAGOON: ZigzagZigzag!$"

