
Route117_Text_DayCarePokemonHadNewMove:
	.string "Ho lasciato il mio POKéMON alla\n"
	.string "PENSIONE.\p"
	.string "Quando l’ho ripreso, aveva imparato\n"
	.string "una mossa che prima non sapeva.\l"
	.string "È stata una bella sorpresa.$"

Route117_Text_ArentTheseFlowersPretty:
	.string "Che ne dici?\n"
	.string "Non sono carini questi fiori?\p"
	.string "Li ho piantati tutti io!$"

Route117_Text_AirIsTastyHere:
	.string "Qui si respira un’aria proprio pulita!$"

Route117_Text_RouteSignVerdanturf:
	.string "PERCORSO 117\n"
	.string "{LEFT_ARROW} MENTANIA$"

Route117_Text_RouteSignMauville:
	.string "PERCORSO 117\n"
	.string "{RIGHT_ARROW} CICLAMIPOLI$"

Route117_Text_DayCareSign:
	.string "PENSIONE POKéMON\n"
	.string "“Ci prendiamo cura dei tuoi POKéMON”.$"
