
VerdanturfTown_WandasHouse_Text_StrongerSpeech:
	.string "LINO: Contro di te ho perso, {PLAYER},\n"
	.string "ma non sono più triste…\p"
	.string "Ho un nuovo scopo nella vita.\n"
	.string "Con il mio RALTS, andrò a sfidare ogni\l"
	.string "PALESTRA POKéMON per diventare\l"
	.string "un grande ALLENATORE.\p"
	.string "Tienimi d’occhio, {PLAYER}!\n"
	.string "Diventerò più forte di te!\p"
	.string "Quando sarò pronto, ti sfiderò di nuovo\n"
	.string "in lotta.$"

VerdanturfTown_WandasHouse_Text_StrongerSpeechShort:
	.string "LINO: Tienimi d’occhio, {PLAYER}!\n"
	.string "Diventerò più forte di te!\p"
	.string "Quando sarò pronto, ti sfiderò di nuovo\n"
	.string "in lotta.$"

VerdanturfTown_WandasHouse_Text_WallysNextDoor:
	.string "ZIO: Oh! {PLAYER}{KUN}!\n"
	.string "LINO è nella stanza accanto.\p"
	.string "Ma lascia che ti dica una cosa…\p"
	.string "Questa natura incontaminata sta\n"
	.string "facendo miracoli per la salute di LINO.\p"
	.string "Ma forse non è solo la natura. Magari\n"
	.string "sono anche i POKéMON a dargli speranza.$"

VerdanturfTown_WandasHouse_Text_WallySlippedOff:
	.string "LINO se n’è andato per conto suo…$"

VerdanturfTown_WandasHouse_Text_WallyGoneThatFar:
	.string "ZIO: Veramente? LINO se n’è\n"
	.string "andato lontano tutto solo…\p"
	.string "Beh, devo aiutarlo, è il figlio\n"
	.string "di mio fratello minore!$"

VerdanturfTown_WandasHouse_Text_MeetWanda:
	.string "LINDA: E tu chi sei?\n"
	.string "Ah, sì, è vero…\p"
	.string "Sei {PLAYER}! LINO mi ha parlato\n"
	.string "tanto di te.\p"
	.string "Io sono la cugina di LINO.\n"
	.string "Che piacere conoscerti!\p"
	.string "LINO è diventato molto più vivace\n"
	.string "da quando è venuto qua. Ora sta bene!$"

VerdanturfTown_WandasHouse_Text_DontWorryAboutWally:
	.string "LINDA: Non preoccuparti per LINO.\n"
	.string "Se la caverà!\p"
	.string "Conosco mio cugino… e poi ha anche\n"
	.string "i POKéMON con sé.$"

VerdanturfTown_WandasHouse_Text_CanSeeGirlfriendEveryDay:
	.string "Grazie a te, adesso posso vedere\n"
	.string "la mia ragazza tutti i giorni.\l"
	.string "Felice? Felicissimo, direi!$"

VerdanturfTown_WandasHouse_Text_DaughtersBoyfriendDriven:
	.string "Il ragazzo di mia figlia è molto\n"
	.string "innamorato… è pazzo di lei!\p"
	.string "Pensa che si è messo a scavare senza\n"
	.string "sosta un tunnel per poterla vedere.\p"
	.string "Mia figlia è un po’ preoccupata,\n"
	.string "così va a trovarlo spesso al tunnel.$"

VerdanturfTown_WandasHouse_Text_DaughtersBoyfriendWasDigging:
	.string "Incredibile! Il ragazzo di mia figlia\n"
	.string "ha scavato un tunnel a mano!\p"
	.string "Da non crederci!$"

VerdanturfTown_WandasHouse_Text_IfAnythingHappenedToWally:
	.string "Se dovesse succedere qualcosa a LINO,\n"
	.string "non riuscirei più a guardare in faccia\l"
	.string "i suoi genitori a PETALIPOLI…$"

VerdanturfTown_WandasHouse_Text_WallyWasInEverGrande:
	.string "LINO era a IRIDOPOLI?\p"
	.string "I suoi genitori a PETALIPOLI\n"
	.string "ne rimarrebbero esterrefatti!$"
