
MeteorFalls_1F_1R_Text_WithThisMeteorite:
	.string "Eheheh!\p"
	.string "Con questo METEORITE, sul\n"
	.string "MONTE CAMINO…$"

MeteorFalls_1F_1R_Text_DontExpectMercyFromMagma:
	.string "Eh?\p"
	.string "Non so chi tu sia, ma se metti i bastoni\n"
	.string "tra le ruote al TEAM MAGMA, non ti\l"
	.string "aspettare alcuna misericordia!$"

MeteorFalls_1F_1R_Text_HoldItRightThereMagma:
	.string "Un attimo, TEAM MAGMA!\p"
	.string "Vi sbagliate di grosso se pensate\n"
	.string "di farla franca!$"

MeteorFalls_1F_1R_Text_BeSeeingYouTeamAqua:
	.string "Eheheh!\n"
	.string "Ci è venuto a far visita il TEAM IDRO!\p"
	.string "Non mi voglio scomodare per liquidarvi\n"
	.string "tutti…\p"
	.string "Sorvoliamo per questa volta!\p"
	.string "Abbiamo il METEORITE, il MONTE CAMINO\n"
	.string "ci aspetta!\p"
	.string "Eheheh! Ci si ritrova, marmocchi del\n"
	.string "TEAM IDRO!$"

MeteorFalls_1F_1R_Text_ArchieSeenYouBefore:
	.string "IVAN: Non ci siamo già incontrati\n"
	.string "al MUSEO di SELCEPOLI?\p"
	.string "Ah, allora ti chiami {PLAYER}.\p"
	.string "L’ultima volta avevo pensato fossi\n"
	.string "del TEAM MAGMA.\p"
	.string "Sei un tipo strano…\p"
	.string "Il TEAM MAGMA è una temibile\n"
	.string "minaccia per tutti noi.\p"
	.string "Nel tentativo di allargare la\n"
	.string "terraferma, hanno compiuto molti\l"
	.string "atti distruttivi.\p"
	.string "Noi del TEAM IDRO amiamo il mare! Il\n"
	.string "TEAM MAGMA è il nostro nemico giurato!$"

MeteorFalls_1F_1R_Text_BossWeShouldChaseMagma:
	.string "CAPO, dobbiamo stare alle costole\n"
	.string "del TEAM MAGMA…$"

MeteorFalls_1F_1R_Text_ArchieYesNoTellingWhatMagmaWillDo:
	.string "IVAN: Sì, sì, dobbiamo sbrigarci!\n"
	.string "Non abbiamo un minuto da perdere.\p"
	.string "Chissà cosa combinerà il TEAM MAGMA\n"
	.string "sul MONTE CAMINO!$"

MeteorFalls_1F_1R_Text_ArchieFarewell:
	.string "IVAN: {PLAYER}, anche tu dovresti\n"
	.string "tenere sott’occhio il TEAM MAGMA.\p"
	.string "Addio!$"

MeteorFalls_1F_1R_Text_MeetProfCozmo:
	.string "Sono un PROFESSORE…\n"
	.string "Mi chiamo COSMI…\p"
	.string "Ho fatto da guida alle CASCATE METEORA\n"
	.string "ad alcuni individui del TEAM MAGMA.\p"
	.string "Mi hanno imbrogliato e mi hanno\n"
	.string "anche rubato il mio METEORITE…\p"
	.string "Poi si è presentato un altro gruppo\n"
	.string "di teppistelli, il TEAM IDRO.\p"
	.string "Non ci capisco più nulla…\p"
	.string "E poi mi chiedo, il TEAM MAGMA…\p"
	.string "che cosa ci farà con quel METEORITE\n"
	.string "sul MONTE CAMINO?$"

MeteorFalls_1F_1R_Text_WhatsTeamMagmaDoingAtMtChimney:
	.string "PROF. COSMI: Quel TEAM MAGMA…\p"
	.string "ma che cosa ci farà con quel\n"
	.string "METEORITE sul MONTE CAMINO?$"
