DewfordTown_PokemonCenter_2F: @ 8482C44
	.4byte PokemonCenter_2F_Layout
	.4byte DewfordTown_PokemonCenter_2F_MapEvents
	.4byte DewfordTown_PokemonCenter_2F_MapScripts
	.4byte 0x0
	.2byte MUS_POKECEN
	.2byte 62
	.byte MAPSEC_DEWFORD_TOWN
	.byte 0
	.byte WEATHER_NONE
	.byte MAP_TYPE_INDOOR
	.2byte 0
	map_header_flags allow_bike=0, allow_escape_rope=0, allow_run=0, show_map_name=0
	.byte MAP_BATTLE_SCENE_NORMAL

