
JaggedPass_Text_EricIntro:
	.string "PASSO SELVAGGIO del MONTE CAMINO…\p"
	.string "È tutto quello che ho sempre desiderato\n"
	.string "in montagna.\p"
	.string "Queste irregolarità selvagge…\n"
	.string "scuotono la mia anima!$"

JaggedPass_Text_EricDefeat:
	.string "Perdere mi lascia l’amaro in bocca!$"

JaggedPass_Text_EricPostBattle:
	.string "Sì, ho perso con i POKéMON…\p"
	.string "Ma in quanto ad amore per la montagna,\n"
	.string "non mi batte nessuno!$"

JaggedPass_Text_DianaIntro:
	.string "Questo posto non è adatto a scalatori\n"
	.string "improvvisati.$"

JaggedPass_Text_DianaDefeat:
	.string "Ohhh, no!\n"
	.string "Il terreno è troppo accidentato…$"

JaggedPass_Text_DianaPostBattle:
	.string "Lo sapevi?\p"
	.string "Alcune persone vanno in bicicletta\n"
	.string "per questo passo tanto sconnesso.$"

JaggedPass_Text_DianaRegister:
	.string "Tornerai ancora da queste parti?\n"
	.string "Mi piacerebbe sfidarti di nuovo.$"

JaggedPass_Text_DianaRematchIntro:
	.string "Adoro fare i picnic… e con i POKéMON la\n"
	.string "scampagnata è ancora più divertente!$"

JaggedPass_Text_DianaRematchDefeat:
	.string "Ho perso perché il terreno\n"
	.string "è troppo accidentato!$"

JaggedPass_Text_DianaPostRematch:
	.string "Dimentico la sconfitta e mi godo\n"
	.string "questa bella escursione.$"

JaggedPass_Text_EthanIntro:
	.string "Il PASSO SELVAGGIO non è adatto per\n"
	.string "camminare, ma è ottimo per allenarsi.$"

JaggedPass_Text_EthanDefeat:
	.string "È finito tutto prima che riuscissimo\n"
	.string "a rompere il ghiaccio…$"

JaggedPass_Text_EthanPostBattle:
	.string "Se avessi una BICI da CROSS, potrei\n"
	.string "discendere o risalire questi salti.$"

JaggedPass_Text_EthanRegister:
	.string "Se riesco ad abituarmi a questo terreno\n"
	.string "accidentato, vincerò di sicuro!\p"
	.string "Vuoi registrarmi nel tuo POKéNAV?$"

JaggedPass_Text_EthanRematchIntro:
	.string "Ormai il terreno sconnesso non mi fa più\n"
	.string "paura! Ora canto mentre mi arrampico.$"

JaggedPass_Text_EthanRematchDefeat:
	.string "Non è facile lottare su questo\n"
	.string "terreno così accidentato…$"

JaggedPass_Text_EthanPostRematch:
	.string "Dovrei andare a prendere una BICI da\n"
	.string "CROSS da CLELIO a CICLAMIPOLI…$"

JaggedPass_Text_GruntIntro:
	.string "Ah!\n"
	.string "Che cosa ci fai tu qui?\p"
	.string "Che ci faccio io in un posto così?\p"
	.string "Sono affari tuoi?$"

JaggedPass_Text_GruntDefeat:
	.string "Rrrr…\p"
	.string "Avrei dovuto scomparire nel nostro\n"
	.string "RIFUGIO immediatamente…$"

JaggedPass_Text_GoWhereverYouWant:
	.string "Sì, lo ammetto!\n"
	.string "Sei forte!\p"
	.string "Non pensare a me.\n"
	.string "Vai dove vuoi!$"

JaggedPass_Text_BoulderShakingInResponseToEmblem:
	.string "Oh! Il masso si muove grazie allo\n"
	.string "STEMMA MAGMA!$"

JaggedPass_Text_JulioIntro:
	.string "Wow! Che paura precipitarsi giù per la\n"
	.string "montagna tutto d’un fiato!$"

JaggedPass_Text_JulioDefeat:
	.string "Sento che sto andando a pezzi…$"

JaggedPass_Text_JulioPostBattle:
	.string "Ho fatto tanti di quei salti con la\n"
	.string "bicicletta che mi fa male il didietro…$"

JaggedPass_Text_AutumnIntro:
	.string "Scalo questa montagna ogni giorno.\n"
	.string "Confido nella mia forza.$"

JaggedPass_Text_AutumnDefeat:
	.string "Mmm… cos’è successo?$"

JaggedPass_Text_AutumnPostBattle:
	.string "Cos’è quello strano spuntone di roccia\n"
	.string "lì su?$"
