
PetalburgCity_Gym_Text_DadYoureHereWithYourPokemon:
	.string "PAPÀ: Uhm?\p"
	.string "Sei proprio tu, {PLAYER}!\n"
	.string "Ne hai fatta di strada!\p"
	.string "Sono sorpreso che ce l’abbia\n"
	.string "fatta con le tue forze.\p"
	.string "Oh, adesso vedo…\n"
	.string "Hai portato la tua squadra di POKéMON.\p"
	.string "Uhm… presumo che tu voglia diventare\n"
	.string "un ALLENATORE come me, {PLAYER}.\p"
	.string "Che bella notizia!\n"
	.string "Non vedo l’ora!$"

PetalburgCity_Gym_Text_WallyIdLikeAPokemon:
	.string "Uhm… vorrei… vorrei un POKéMON,\n"
	.string "per favore…$"

PetalburgCity_Gym_Text_DadOhYoureWallyRight:
	.string "PAPÀ: Uhm… tu devi essere…\n"
	.string "LINO, vero?$"

PetalburgCity_Gym_Text_WallyIveNeverCaughtAPokemon:
	.string "LINO: Andrò a trovare i miei parenti\n"
	.string "a MENTANIA.\p"
	.string "Temo di sentirmi solo, quindi\n"
	.string "vorrei portarmi un POKéMON.\p"
	.string "Però non ho mai catturato un POKéMON\n"
	.string "in vita mia. Non so come fare…$"

PetalburgCity_Gym_Text_DadHmISee:
	.string "PAPÀ: Uhm… capisco.$"

PetalburgCity_Gym_Text_DadPlayerGoWithWally:
	.string "PAPÀ: {PLAYER}, hai sentito?\p"
	.string "Accompagna LINO a catturare\n"
	.string "un POKéMON!$"

PetalburgCity_Gym_Text_IllLoanYouMyZigzagoon:
	.string "Ecco, LINO, ti presto il mio POKéMON.\p"
	.string "LINO riceve ZIGZAGOON!$"

PetalburgCity_Gym_Text_WallyThankYouAndDadGivesPokeBall:
	.string "LINO: Oh, wow!\n"
	.string "Un POKéMON!\p"
	.string "PAPÀ: Ti do anche una POKé BALL.\n"
	.string "Prendila!\p"
	.string "LINO riceve una POKé BALL!$"

PetalburgCity_Gym_Text_WallyOhWowThankYou:
	.string "LINO: Oh, wow!\n"
	.string "Grazie!$"

PetalburgCity_Gym_Text_WouldYouReallyComeWithMe:
	.string "Davvero?!\n"
	.string "Verresti con me, {PLAYER}?$"

PetalburgCity_Gym_Text_DadSoDidItWorkOut:
	.string "PAPÀ: Quindi ha funzionato?$"

PetalburgCity_Gym_Text_WallyThankYouBye:
	.string "LINO: Grazie… sì, ce l’abbiamo fatta!\n"
	.string "Le restituisco il suo POKéMON.\p"
	.string "{PLAYER}, ti ringrazio per avermi\n"
	.string "accompagnato.\p"
	.string "Con il vostro aiuto sono riuscito a\n"
	.string "catturare il mio POKéMON.\p"
	.string "Prometto di prendermene cura.\p"
	.string "Oh! La mamma mi aspetta!\n"
	.string "Devo andare!\p"
	.string "Ciao, {PLAYER}!$"

PetalburgCity_Gym_Text_DadGoCollectBadges:
	.string "PAPÀ: Bene…\p"
	.string "{PLAYER}, se vuoi diventare un bravo\n"
	.string "ALLENATORE, ecco il mio consiglio…\p"
	.string "Dirigiti verso FERRUGIPOLI,\n"
	.string "la prossima città.\p"
	.string "Lì devi sfidare il CAPOPALESTRA\n"
	.string "PETRA.\p"
	.string "Dopo di che, vai in altre PALESTRE\n"
	.string "POKéMON e sconfiggi i loro capi.\p"
	.string "Devi vincere le MEDAGLIE,\n"
	.string "hai capito bene?\p"
	.string "Anch’io sono un CAPOPALESTRA.\n"
	.string "Un giorno ci sfideremo, {PLAYER}.\p"
	.string "Ma solo quando diventerai più forte!$"

PetalburgCity_Gym_Text_NormanGoToRustboro:
	.string "PAPÀ: Uhm? Non vai alla PALESTRA\n"
	.string "POKéMON di FERRUGIPOLI?\p"
	.string "Sfidare un ALLENATORE alle\n"
	.string "prime armi non è avvincente.\p"
	.string "{PLAYER}, accetterò di sfidarti solo\n"
	.string "quando sarai molto più forte.\p"
	.string "Ti sfiderò solo quando avrai vinto\n"
	.string "quattro MEDAGLIE, è chiaro?$"

PetalburgCity_Gym_Text_NormanGoToDewford:
	.string "PAPÀ: Bene, vedo che hai vinto\n"
	.string "la sfida con il CAPOPALESTRA \l"
	.string "di FERRUGIPOLI.\p"
	.string "Ma ci sono tanti ALLENATORI più\n"
	.string "forti di te in circolazione, {PLAYER}.\p"
	.string "A BLURUVIA, al di là del mare,\n"
	.string "troverai un CAPOPALESTRA.\l"
	.string "Si chiama RUDI.\p"
	.string "Devi sfidarlo.$"

PetalburgCity_Gym_Text_YouHaveGottenStronger:
	.string "PAPÀ: Uhm… ne hai fatti di progressi,\n"
	.string "{PLAYER}.\p"
	.string "Lo si vede dal numero di MEDAGLIE\n"
	.string "che hai vinto.$"

PetalburgCity_Gym_Text_NormanIntro:
	.string "PAPÀ: Uhm… allora hai vinto quattro\n"
	.string "MEDAGLIE.\p"
	.string "Bene, come promesso ci sfideremo\n"
	.string "in una lotta di POKéMON.\p"
	.string "{PLAYER}…\p"
	.string "Per me è una gioia poterti sfidare \n"
	.string "in una vera lotta.\p"
	.string "Ma una lotta è pur sempre una lotta!\p"
	.string "In veste di CAPOPALESTRA, farò quanto\n"
	.string "in mio potere per vincere.\p"
	.string "{PLAYER}, cerca di fare anche tu\n"
	.string "del tuo meglio!$"

PetalburgCity_Gym_Text_NormanDefeat:
	.string "…\p"
	.string "Stento…\p"
	.string "stento a crederci, {PLAYER}…\p"
	.string "Mi hai sconfitto?\p"
	.string "Le regole sono regole!\n"
	.string "Prendi questo!$"

PetalburgCity_Gym_Text_ReceivedBalanceBadge:
	.string "{PLAYER} riceve la MEDAGLIA ARMONIA\n"
	.string "da PAPÀ!$"

PetalburgCity_Gym_Text_ExplainBalanceBadgeTakeThis:
	.string "PAPÀ: Questa MEDAGLIA migliora\n"
	.string "la DIFESA di tutti i tuoi POKéMON.\p"
	.string "I POKéMON che conoscono la mossa MN\n"
	.string "SURF possono nuotare.\p"
	.string "Eccoti un regalo. {PLAYER}, sono sicuro\n"
	.string "che lo saprai usare correttamente.$"

PetalburgCity_Gym_Text_ExplainFacade:
	.string "PAPÀ: La MT42 contiene FACCIATA.\p"
	.string "Raddoppia il potere delle mosse se\n"
	.string "un POKéMON è avvelenato, paralizzato\l"
	.string "o scottato.\p"
	.string "Può rovesciare la situazione\n"
	.string "in circostanze difficili.$"

PetalburgCity_Gym_Text_DadHappyAndSad:
	.string "PAPÀ: In veste di CAPOPALESTRA,\n"
	.string "provo disappunto…\p"
	.string "In qualità di padre, provo gioia e un po’\n"
	.string "di tristezza. È un sentimento strano…$"

PetalburgCity_Gym_Text_PleaseComeWithMe:
	.string "Ah, eccoti, {PLAYER}{KUN}!\p"
	.string "Vieni con me.\n"
	.string "Vorrei darti una cosa.$"

PetalburgCity_Gym_Text_LetMeBorrowPlayer:
	.string "Non ti dispiace vero, NORMAN?\p"
	.string "Posso rubarti {PLAYER}{KUN} per qualche\n"
	.string "minuto?$"

PetalburgCity_Gym_Text_DadGoingToKeepTraining:
	.string "PAPÀ: {PLAYER}, ogni tanto dovresti\n"
	.string "andare a trovare la mamma.\p"
	.string "Io rimango qui per migliorare\n"
	.string "il mio allenamento.\p"
	.string "Come ALLENATORE voglio prendermi\n"
	.string "la rivincita contro di te, {PLAYER}!$"

PetalburgCity_Gym_Text_DadNoAmountOfTrainingIsEnough:
	.string "PAPÀ: {PLAYER}, come ti vanno le cose?\p"
	.string "Il mondo dei POKéMON è immenso.\p"
	.string "Sono fermamente convinto che non\n"
	.string "si è mai allenati a sufficienza.$"

PetalburgCity_Gym_Text_GymGuideAdvice:
	.string "Ehi, {PLAYER}, la strada per diventare\n"
	.string "CAMPIONE è ancora lunga!\p"
	.string "Le porte di questa PALESTRA si aprono\n"
	.string "solo se batti gli ALLENATORI.\p"
	.string "Oops! Le porte di questa sala sono \n"
	.string "già aperte! Non attaccarmi!\p"
	.string "Gli ALLENATORI della PALESTRA\n"
	.string "di PETALIPOLI usano tanti tipi\l"
	.string "di strumenti.\p"
	.string "Dalla porta di sinistra si accede alla\n"
	.string "SALA VELOCITÀ.\p"
	.string "Dalla porta di destra si accede alla\n"
	.string "SALA PRECISIONE.\p"
	.string "Il nome della sala è scritto sulla porta.\n"
	.string "Fa’ una scelta oculata.\p"
	.string "Una volta scelta la porta…\n"
	.string "beh, lanciati nella sfida!$"

PetalburgCity_Gym_Text_GymGuidePostVictory:
	.string "{PLAYER}! Wow! Hai battuto persino\n"
	.string "tuo padre!\p"
	.string "Il destino a volte è davvero bizzarro!$"

PetalburgCity_Gym_Text_RandallIntro:
	.string "La capacità di colpire prima\n"
	.string "dell’avversario…\p"
	.string "Già questo mi dà un bel vantaggio,\n"
	.string "non credi?$"

PetalburgCity_Gym_Text_RandallDefeat:
	.string "È stata una lotta superba!$"

PetalburgCity_Gym_Text_RandallPostBattle:
	.string "Procedi verso la prossima sala\n"
	.string "dove ti aspetta una nuova sfida.\p"
	.string "Sulla sinistra si trova la SALA\n"
	.string "CONFUSIONE.\p"
	.string "Dalla porta di destra si accede alla\n"
	.string "SALA DIFESA.$"

PetalburgCity_Gym_Text_RandallPostBadge:
	.string "A prescindere dal numero di vittorie\n"
	.string "e sconfitte collezionate, non smettere\l"
	.string "mai di allenarti insieme ai tuoi POKéMON.\p"
	.string "Credo che questo sia il vero\n"
	.string "spirito del CAPOPALESTRA.$"

PetalburgCity_Gym_Text_ParkerIntro:
	.string "Questa è la SALA CONFUSIONE.\p"
	.string "Fammi vedere quant’è forte il legame\n"
	.string "con i tuoi POKéMON.$"

PetalburgCity_Gym_Text_ParkerDefeat:
	.string "Non sono riuscito a confondere\n"
	.string "abbastanza la tua squadra…\p"
	.string "Siete uniti da un legame molto forte.$"

PetalburgCity_Gym_Text_ParkerPostBattle:
	.string "Adesso ti aspetta la SALA FORZA.\n"
	.string "Riuscirai ad affrontare tanta potenza?$"

PetalburgCity_Gym_Text_ParkerPostBadge:
	.string "L’allenamento è diventato molto più\n"
	.string "duro da quando hai battuto il nostro\l"
	.string "CAPOPALESTRA.$"

PetalburgCity_Gym_Text_GeorgeIntro:
	.string "Proprio mentre pensi di averla\n"
	.string "spuntata, l’avversario recupera PS…\p"
	.string "Ti immagini come ci si possa sentire?\p"
	.string "Beh, ti faccio vedere io!$"

PetalburgCity_Gym_Text_GeorgeDefeat:
	.string "Non ho recuperato PS sufficienti…\n"
	.string "Che potenza di ATTACCO…!$"

PetalburgCity_Gym_Text_GeorgePostBattle:
	.string "Buon sangue non mente!\p"
	.string "No, aspetta! Solo lavorando sodo\n"
	.string "si diventa bravi ALLENATORI.\p"
	.string "Mi devo applicare di più.\p"
	.string "Forza! Ti aspetta la SALA KO IN 1\n"
	.string "ATTACCO.$"

PetalburgCity_Gym_Text_GeorgePostBadge:
	.string "Continuerò ad allenarmi nelle PALESTRE.\n"
	.string "Un giorno anch’io sarò un CAPOPALESTRA.$"

PetalburgCity_Gym_Text_BerkeIntro:
	.string "Il tuo legame di parentela con il nostro\n"
	.string "CAPOPALESTRA non mi intenerisce!\p"
	.string "Vedrai come ci si sente quando un\n"
	.string "POKéMON subisce un brutto colpo!$"

PetalburgCity_Gym_Text_BerkeDefeat:
	.string "La tua potenza… sei proprio un\n"
	.string "osso duro!$"

PetalburgCity_Gym_Text_BerkePostBattle:
	.string "Tuo padre è davvero forte e nutro\n"
	.string "un profondo rispetto per lui.\p"
	.string "Scorgo in te lo stesso talento.\p"
	.string "Spero che la sfida con tuo padre\n"
	.string "sia davvero avvincente!$"

PetalburgCity_Gym_Text_BerkePostBadge:
	.string "Da quando tuo padre è CAPOPALESTRA,\n"
	.string "gli ALLENATORI di PETALIPOLI\l"
	.string "sono diventati molto più forti.$"

PetalburgCity_Gym_Text_MaryIntro:
	.string "Scherzetto… questa è la\n"
	.string "SALA PRECISIONE.\p"
	.string "È dura quando tutti gli attacchi\n"
	.string "vanno a segno!$"

PetalburgCity_Gym_Text_MaryDefeat:
	.string "Sei una spanna sopra di me…$"

PetalburgCity_Gym_Text_MaryPostBattle:
	.string "Ti aspettano ALLENATORI sempre\n"
	.string "più forti.\p"
	.string "A sinistra si trova la SALA DIFESA.\p"
	.string "Invece a destra c’è la SALA RECUPERO.\p"
	.string "La potenza di ATTACCO dei tuoi POKéMON\n"
	.string "verrà comunque messa alla prova!$"

PetalburgCity_Gym_Text_MaryPostBadge:
	.string "Sai quale obiettivo perseguiamo noi\n"
	.string "ALLENATORI?\p"
	.string "Diventare amici per la pelle dei nostri\n"
	.string "POKéMON!$"

PetalburgCity_Gym_Text_AlexiaIntro:
	.string "Più forte è la DIFESA, più posso\n"
	.string "osare nell’attacco.$"

PetalburgCity_Gym_Text_AlexiaDefeat:
	.string "La DIFESA non è stata sufficiente…$"

PetalburgCity_Gym_Text_AlexiaPostBattle:
	.string "Il tuo insegnamento è stato prezioso.\p"
	.string "Ora fatti coraggio! La porta di sinistra\n"
	.string "conduce alla SALA FORZA.\p"
	.string "Dalla porta di destra si accede alla\n"
	.string "SALA KO IN 1 ATTACCO.\p"
	.string "Dietro ad entrambe si celano\n"
	.string "ALLENATORI molto combattivi.$"

PetalburgCity_Gym_Text_AlexiaPostBadge:
	.string "Ciao! Hai provato ad usare SURF?$"

PetalburgCity_Gym_Text_JodyIntro:
	.string "Il nostro CAPOPALESTRA ha chiesto\n"
	.string "di dare il massimo nella sfida con te.\p"
	.string "Anche se, dopotutto, si tratta\n"
	.string "di tuo padre!$"

PetalburgCity_Gym_Text_JodyDefeat:
	.string "Ma… ho dato il massimo!$"

PetalburgCity_Gym_Text_JodyPostBattle:
	.string "Usi i tuoi POKéMON con lo\n"
	.string "stesso stile di tuo padre.\p"
	.string "Fatti forza! Il CAPOPALESTRA,\n"
	.string "tuo padre, ti attende!$"

PetalburgCity_Gym_Text_JodyPostBadge:
	.string "Di sicuro è importante rafforzare\n"
	.string "i propri POKéMON.\p"
	.string "Ma come si ottiene la vittoria?\p"
	.string "Con l’affetto che gli ALLENATORI\n"
	.string "provano per i loro POKéMON.$"

PetalburgCity_Gym_Text_DoorAppearsLocked:
	.string "Per il momento la porta sembra\n"
	.string "essere chiusa…$"

PetalburgCity_Gym_Text_EnterSpeedRoom:
	.string "C’è scritto “SALA VELOCITÀ”.\p"
	.string "Vuoi oltrepassare la porta?$"

@ Unused
PetalburgCity_Gym_Text_DoorAppearsLocked2:
	.string "This door appears to be locked\n"
	.string "right now…$"

PetalburgCity_Gym_Text_EnterAccuracyRoom:
	.string "C’è scritto “SALA PRECISIONE”.\p"
	.string "Vuoi oltrepassare la porta?$"

PetalburgCity_Gym_Text_EnterConfusionRoom:
	.string "C’è scritto “SALA CONFUSIONE”.\p"
	.string "Vuoi oltrepassare la porta?$"

PetalburgCity_Gym_Text_EnterDefenseRoom:
	.string "C’è scritto “SALA DIFESA”.\p"
	.string "Vuoi oltrepassare la porta?$"

PetalburgCity_Gym_Text_EnterRecoveryRoom:
	.string "C’è scritto “SALA RECUPERO”.\p"
	.string "Vuoi oltrepassare la porta?$"

PetalburgCity_Gym_Text_EnterStrengthRoom:
	.string "C’è scritto “SALA FORZA”.\p"
	.string "Vuoi oltrepassare la porta?$"

PetalburgCity_Gym_Text_EnterOHKORoom:
	.string "C’è scritto “SALA KO IN 1 ATTACCO”.\p"
	.string "Vuoi oltrepassare la porta?$"

PetalburgCity_Gym_Text_EnterGymLeadersRoom:
	.string "“SALA CAPOPALESTRA”\p"
	.string "C’è scritto “Vai a vedere quali POKéMON\n"
	.string "ti aspettano!”.\p"
	.string "Vuoi oltrepassare la porta?$"

PetalburgCity_Gym_Text_GymStatue:
	.string "PALESTRA POKéMON di PETALIPOLI$"

PetalburgCity_Gym_Text_GymStatueCertified:
	.string "PALESTRA POKéMON di PETALIPOLI\p"
	.string "ALLENATORE CERTIFICATO da NORMAN:\n"
	.string "{PLAYER}$"

PetalburgCity_Gym_Text_NormanPreRematch:
	.string "PAPÀ: {PLAYER}… me lo sentivo\n"
	.string "che stavi per arrivare.\p"
	.string "Non mi sottrarrei mai a una sfida\n"
	.string "contro di te.\p"
	.string "Lo capisci, vero?\p"
	.string "All’interno di una PALESTRA, il legame di\n"
	.string "parentela non conta.\p"
	.string "Anzi, proprio perché c’è questo legame,\n"
	.string "dobbiamo impegnarci e dare il meglio di\l"
	.string "noi stessi. Non credi, {PLAYER}?$"

PetalburgCity_Gym_Text_NormanRematchDefeat:
	.string "Uhm… ahah… forse ci\n"
	.string "ho dato troppo dentro…$"

PetalburgCity_Gym_Text_NormanPostRematch:
	.string "PAPÀ: {PLAYER}, hai un sogno\n"
	.string "nel cassetto?\p"
	.string "Il mio sogno…\n"
	.string "ahahah…\l"
	.string "si è già realizzato.$"

PetalburgCity_Gym_Text_NormanRematchNeedTwoMons:
	.string "PAPÀ: {PLAYER}… me lo\n"
	.string "sentivo che stavi per arrivare.\p"
	.string "Non mi sottrarrei mai a una sfida\n"
	.string "contro di te.\p"
	.string "Lo capisci, vero?\p"
	.string "All’interno di una PALESTRA, il legame di\n"
	.string "parentela non conta.\p"
	.string "Eh? Aspetta un attimo, {PLAYER}.\p"
	.string "Hai soltanto un POKéMON in grado di\n"
	.string "lottare?\p"
	.string "Spiacente, ma devi tornare quando hai\n"
	.string "almeno due POKéMON.$"
