Route10_Frlg_MapScripts::
	.byte 0

Route10_EventScript_Unused::
	end

Route10_EventScript_NorthRockTunnelSign::
	msgbox Route10_Text_RockTunnelDetourToLavender, MSGBOX_SIGN
	end

Route10_EventScript_SouthRockTunnelSign::
	msgbox Route10_Text_RockTunnel, MSGBOX_SIGN
	end

Route10_EventScript_PowerPlantSign::
	msgbox Route10_Text_PowerPlant, MSGBOX_SIGN
	end

Route10_Text_MarkIntro::
	.string "Wow, you came all the way here?\n"
	.string "Maybe you're a POKéMANIAC, too?\l"
	.string "Want to see my collection?$"

Route10_Text_MarkDefeat::
	.string "Humph.\n"
	.string "I'm not angry!$"

Route10_Text_MarkPostBattle::
	.string "I have more rare POKéMON at home!$"

Route10_Text_ClarkIntro::
	.string "Ha-hahah-ah-ha!$"

Route10_Text_ClarkDefeat::
	.string "Ha-haha!\n"
	.string "Not laughing!\l"
	.string "Ha-hay fever! Haha-ha-choo!$"

Route10_Text_ClarkPostBattle::
	.string "Haha-ha-choo!\n"
	.string "Ha-choo!\l"
	.string "Snort! Snivel!$"

Route10_Text_HermanIntro::
	.string "Hi, kid!\n"
	.string "Want to see my POKéMON?$"

Route10_Text_HermanDefeat::
	.string "Oh, no!\n"
	.string "My POKéMON!$"

Route10_Text_HermanPostBattle::
	.string "I don't like you.\n"
	.string "I don't like anyone better than me!$"

Route10_Text_HeidiIntro::
	.string "I've been out at a POKéMON GYM\n"
	.string "a few times.\p"
	.string "…But I always lose.$"

Route10_Text_HeidiDefeat::
	.string "Ohh!\n"
	.string "After all my training!$"

Route10_Text_HeidiPostBattle::
	.string "I noticed some POKéMANIACS\n"
	.string "prowling around.\p"
	.string "Can you imagine? Them?\n"
	.string "Up here in the mountains?$"

Route10_Text_TrentIntro::
	.string "Ah!\n"
	.string "This mountain air is delicious!$"

Route10_Text_TrentDefeat::
	.string "That cleared my head!$"

Route10_Text_TrentPostBattle::
	.string "I feel bloated on mountain air!$"

Route10_Text_CarolIntro::
	.string "I'm feeling a bit faint.\n"
	.string "I haven't hiked in some time.$"

Route10_Text_CarolDefeat::
	.string "I'm too tired.\n"
	.string "I wasn't up for it.$"

Route10_Text_CarolPostBattle::
	.string "The POKéMON here in the mountains\n"
	.string "are so chunky…\p"
	.string "I wish there were pink POKéMON\n"
	.string "with a floral pattern!$"

Route10_Text_RockTunnelDetourToLavender::
	.string "ROCK TUNNEL\n"
	.string "Detour to LAVENDER TOWN$"

Route10_Text_RockTunnel::
	.string "ROCK TUNNEL$"

Route10_Text_PowerPlant::
	.string "POWER PLANT$"

