
SlateportCity_BattleTentLobby_Text_CouldntFindMonForMe:
	.string "Tu vois, comme j’pouvais pas trouver\n"
	.string "de POKéMON pour moi, tu vois…\p"
	.string "Alors j’suis allé me plaindre à ce\n"
	.string "type là, tu vois.\p"
	.string "Et il voulait même pas m’écouter, quoi!\n"
	.string "Un vrai pourri, quoi!\p"
	.string "J’pouvais pas en placer une!\n"
	.string "Attends, prends ça, quoi!$"

SlateportCity_BattleTentLobby_Text_ExplainTorment:
	.string "Ben quoi, c’est la CT41, tu vois?\n"
	.string "Hé, c’est TOURMENTE, tu piges?\p"
	.string "Avec ça, l’autre pourra pas utiliser\n"
	.string "deux fois de suite la même capacité, OK?\p"
	.string "Hé, maintenant, tu m’écoutes, alors!\n"
	.string "C’est quand même pas la mort!$"

SlateportCity_BattleTentLobby_Text_IllTryUsingBugMons:
	.string "J’aime pas vraiment les POKéMON\n"
	.string "INSECTE, mais je devrais peut-être\l"
	.string "en essayer, juste pour voir.\p"
	.string "Qui sait, j’pourrais peut-être même\n"
	.string "aimer ça!$"

SlateportCity_BattleTentLobby_Text_BattleEvenWithoutToughMons:
	.string "Tu peux te battre quand tu veux ici,\n"
	.string "même si tu ne possèdes pas de\l"
	.string "POKéMON.$"

SlateportCity_BattleTentLobby_Text_NiceIfMoreSelection:
	.string "Ne serait-ce pas super s’ils avaient\n"
	.string "plus de choix?$"
