
EverGrandeCity_PokemonCenter_1F_Text_LeagueAfterVictoryRoad:
	.string "La LIGUE POKéMON se trouve juste\n"
	.string "un peu après la ROUTE VICTOIRE.\p"
	.string "Si tu as fait la route jusqu’ici,\n"
	.string "autant continuer!$"

EverGrandeCity_PokemonCenter_1F_Text_BelieveInYourPokemon:
	.string "Longue et impitoyable ROUTE VICTOIRE…\p"
	.string "C’est comme refaire un trajet\n"
	.string "déjà parcouru…\p"
	.string "Crois en tes POKéMON et donne-leur\n"
	.string "tout ce que tu as!$"

EverGrandeCity_PokemonCenter_1F_Text_ScottHappyForYou:
	.string "SCOTT: {PLAYER}{KUN}, tu as franchi les\n"
	.string "étapes qui mènent à la LIGUE POKéMON!\p"
	.string "Je suis heureux pour toi! Ça a valu le\n"
	.string "coup que je te soutienne!\p"
	.string "{PLAYER}{KUN}, si tu arrives à devenir le\n"
	.string "MAITRE de la LIGUE POKéMON…\p"
	.string "Je prendrai contact avec toi.\p"
	.string "OK, le chemin de la gloire est\n"
	.string "devant toi!$"

