#ifndef GUARD_MULTIBOOT_POKEMON_COLOSSEUM_H
#define GUARD_MULTIBOOT_POKEMON_COLOSSEUM_H

extern const u16 gMultiBootProgram_PokemonColosseum_Start[0x14000];

#endif // GUARD_MULTIBOOT_POKEMON_COLOSSEUM_H
