#ifndef GUARD_ORAS_DOWSE_H
#define GUARD_ORAS_DOWSE_H

// States for ORAS Dowsing
enum
{
    ORASD_WIGGLE_NONE,
    ORASD_WIGGLE_SLOW,
    ORASD_WIGGLE_NORMAL,
    ORASD_WIGGLE_FAST,
    ORASD_WIGGLE_FASTER
};

#define ANIM_ORAS_DOWSE_WIGGLE_SOUTH_SLOW   (ANIM_STD_FACE_EAST + 1)
#define ANIM_ORAS_DOWSE_WIGGLE_NORTH_SLOW   (ANIM_STD_FACE_EAST + 2)
#define ANIM_ORAS_DOWSE_WIGGLE_WEST_SLOW    (ANIM_STD_FACE_EAST + 3)
#define ANIM_ORAS_DOWSE_WIGGLE_EAST_SLOW    (ANIM_STD_FACE_EAST + 4)
#define ANIM_ORAS_DOWSE_WIGGLE_SOUTH        (ANIM_STD_FACE_EAST + 5)
#define ANIM_ORAS_DOWSE_WIGGLE_NORTH        (ANIM_STD_FACE_EAST + 6)
#define ANIM_ORAS_DOWSE_WIGGLE_WEST         (ANIM_STD_FACE_EAST + 7)
#define ANIM_ORAS_DOWSE_WIGGLE_EAST         (ANIM_STD_FACE_EAST + 8)
#define ANIM_ORAS_DOWSE_WIGGLE_SOUTH_FAST   (ANIM_STD_FACE_EAST + 9)
#define ANIM_ORAS_DOWSE_WIGGLE_NORTH_FAST   (ANIM_STD_FACE_EAST + 10)
#define ANIM_ORAS_DOWSE_WIGGLE_WEST_FAST    (ANIM_STD_FACE_EAST + 11)
#define ANIM_ORAS_DOWSE_WIGGLE_EAST_FAST    (ANIM_STD_FACE_EAST + 12)
#define ANIM_ORAS_DOWSE_WIGGLE_SOUTH_FASTER (ANIM_STD_FACE_EAST + 13)
#define ANIM_ORAS_DOWSE_WIGGLE_NORTH_FASTER (ANIM_STD_FACE_EAST + 14)
#define ANIM_ORAS_DOWSE_WIGGLE_WEST_FASTER  (ANIM_STD_FACE_EAST + 15)
#define ANIM_ORAS_DOWSE_WIGGLE_EAST_FASTER  (ANIM_STD_FACE_EAST + 16)

extern const u16 gFieldEffectPal_ORASDowsing[];

void Task_UseORASDowsingMachine(u8 taskId);
void ResumeORASDowseFieldEffect(void);
void UpdateDowseState(struct Sprite *sprite);
void UpdateDowsingAnimDirection(struct Sprite *sprite, struct ObjectEvent *playerObj);
void EndORASDowsing(void);

#endif // GUARD_ORAS_DOWSE_H
