#ifndef GUARD_TRAINER_IDS_H
#define GUARD_TRAINER_IDS_H

#define NO_OF_TRAINERS      854

#define TRAINER_ID_SIDNEY   261
#define TRAINER_ID_PHOEBE   262
#define TRAINER_ID_GLACIA   263
#define TRAINER_ID_DRAKE    264
#define TRAINER_ID_STEVEN   804

#endif // GUARD_TRAINER_IDS_H
