AbandonedShip_Underwater1: @ 8484550
	.4byte AbandonedShip_Underwater1_Layout
	.4byte AbandonedShip_Underwater1_MapEvents
	.4byte AbandonedShip_Underwater1_MapScripts
	.4byte 0x0
	.2byte MUS_DEEPDEEP
	.2byte 192
	.byte MAPSEC_ABANDONED_SHIP
	.byte 0
	.byte WEATHER_BUBBLES
	.byte MAP_TYPE_UNDERWATER
	.2byte 0
	map_header_flags allow_bike=1, allow_escape_rope=0, allow_run=1, show_map_name=1
	.byte MAP_BATTLE_SCENE_NORMAL

