
VerdanturfTown_Text_ManTryingToDigTunnel:
	.string "Me lo ha dicho mi papá.\p"
	.string "Dice que este túnel está lleno\n"
	.string "de POKéMON asustadizos.\p"
	.string "Si escuchan algún ruido fuerte, se\n"
	.string "asustan y montan alborotos.\p"
	.string "Por eso detuvieron el proyecto de\n"
	.string "construcción del túnel.\p"
	.string "¡Pero hay un hombre empeñado en\n"
	.string "terminar el túnel él solito!$"

VerdanturfTown_Text_ManDugTunnelForLove:
	.string "Un hombre excavó un túnel para\n"
	.string "la mujer que amaba…\p"
	.string "Es decir, para poder ir a verla más\n"
	.string "fácilmente. ¡Eso es amor, señores!$"

VerdanturfTown_Text_AirCleanHere:
	.string "Por cómo sopla el viento, aquí nunca\n"
	.string "llega la ceniza volcánica.\p"
	.string "Al contrario, el aire de aquí es puro\n"
	.string "y agradable. Es muy bueno para las\l"
	.string "personas de salud delicada.$"

VerdanturfTown_Text_MakeBattleTentDebut:
	.string "Mis POKéMON y yo estamos de racha.\p"
	.string "Así que he decidido probar suerte en\n"
	.string "la TIENDA de BATALLA que hay aquí.$"

VerdanturfTown_Text_GuyTryingToBustThroughCave:
	.string "¿Has visto la cueva que hay cerca de\n"
	.string "la TIENDA POKéMON?\p"
	.string "Dentro hay un tipo que intenta romper\n"
	.string "rocas para poder llegar al otro lado.\p"
	.string "Sería estupendo tener el túnel…\n"
	.string "Visitar CIUDAD FÉRRICA sería\l"
	.string "más sencillo.$"

VerdanturfTown_Text_EasyToGetToRustboroNow:
	.string "La cueva que hay cerca de la TIENDA\n"
	.string "POKéMON es ahora un túnel que\l"
	.string "conecta dos ciudades.\p"
	.string "Es lo mejor. Ahora no cuesta nada ir\n"
	.string "a comprar productos DEVON a\l"
	.string "CIUDAD FÉRRICA.$"

VerdanturfTown_Text_TownSign:
	.string "PUEBLO VERDEGAL\p"
	.string "“Las ventosas tierras altas que\n"
	.string "siempre huelen a hierba fresca.”$"

VerdanturfTown_Text_WandasHouse:
	.string "CASA de CLARA$"

VerdanturfTown_Text_BattleTentSign:
	.string "TIENDA de BATALLA de PUEBLO VERDEGAL\n"
	.string "“¡Disfruta de los mejores combates!”$"

VerdanturfTown_Text_RusturfTunnelSign:
	.string "TÚNEL FERVERGAL\n"
	.string "“Conecta CIUDAD FÉRRICA y VERDEGAL.\p"
	.string "El proyecto de construcción del\n"
	.string "túnel ha sido cancelado.”$"

