Route110_TrickHousePuzzle4: @ 8485BF4
	.4byte Route110_TrickHousePuzzle4_Layout
	.4byte Route110_TrickHousePuzzle4_MapEvents
	.4byte Route110_TrickHousePuzzle4_MapScripts
	.4byte 0x0
	.2byte MUS_KARAKURI
	.2byte 250
	.byte MAPSEC_ROUTE_110
	.byte 0
	.byte WEATHER_NONE
	.byte MAP_TYPE_INDOOR
	.2byte 0
	map_header_flags allow_bike=0, allow_escape_rope=0, allow_run=0, show_map_name=0
	.byte MAP_BATTLE_SCENE_NORMAL

