
Route110_TrickHousePuzzle4_Text_WroteSecretCodeLockOpened:
	.string "{PLAYER} scrive il codice segreto\n"
	.string "sulla porta.\p"
	.string "“Il MAGO del QUIZ è grande”.\n"
	.string "… … … … … … … …\p"
	.string "La porta si apre!$"

Route110_TrickHousePuzzle4_Text_CoraIntro:
	.string "Troppa fatica risolvere questo\n"
	.string "rompicapo. Voglio solo lottare!$"

Route110_TrickHousePuzzle4_Text_CoraDefeat:
	.string "Anche se ho perso, mi piace lottare\n"
	.string "al meglio!$"

Route110_TrickHousePuzzle4_Text_CoraPostBattle:
	.string "Andrei ovunque pur di incontrare degli\n"
	.string "ALLENATORI, tu no?$"

Route110_TrickHousePuzzle4_Text_YujiIntro:
	.string "Ehi! Massi come questi riesco\n"
	.string "a spostarli con un dito io!$"

Route110_TrickHousePuzzle4_Text_YujiDefeat:
	.string "Certo, so spostare i massi ma non\n"
	.string "riesco a risolvere questo rompicapo…$"

Route110_TrickHousePuzzle4_Text_YujiPostBattle:
	.string "Non basta essere forti… bisogna\n"
	.string "essere anche furbi! Usa il cervello!$"

Route110_TrickHousePuzzle4_Text_PaulaIntro:
	.string "La QUIZZOTECA si fa sempre più\n"
	.string "interessante, no?$"

Route110_TrickHousePuzzle4_Text_PaulaDefeat:
	.string "Nooooo!$"

Route110_TrickHousePuzzle4_Text_PaulaPostBattle:
	.string "Ma c’è mai arrivato nessuno alla fine?$"
