
LavaridgeTown_HerbShop_Text_WelcomeToHerbShop:
	.string "Hola. Éste es el HERBOLARIO. Nuestras\n"
	.string "medicinas son baratas y eficaces.$"

LavaridgeTown_HerbShop_Text_YouveComeToLookAtHerbalMedicine:
	.string "¿Has venido a comprar hierbas\n"
	.string "medicinales a LAVACALDA?\p"
	.string "Haces bien. Son muy recomendables.\p"
	.string "¡Me has gustado! ¡Toma esto!$"

LavaridgeTown_HerbShop_Text_ExplainCharcoal:
	.string "El CARBÓN que te he dado sirve\n"
	.string "para preparar una medicina natural.\p"
	.string "También hace maravillas cuando\n"
	.string "se lo das a un POKéMON.\p"
	.string "Intensifica la potencia de los\n"
	.string "movimientos de tipo FUEGO.$"

LavaridgeTown_HerbShop_Text_HerbalMedicineWorksButMonWillDislike:
	.string "Las hierbas medicinales funcionan\n"
	.string "increíblemente bien, pero, si le das\l"
	.string "una a un POKéMON, te tendrá manía.\l"
	.string "¡El sabor es superamargo!$"
