Route104_PrettyPetalFlowerShop: @ 8483D8C
	.4byte Route104_PrettyPetalFlowerShop_Layout
	.4byte Route104_PrettyPetalFlowerShop_MapEvents
	.4byte Route104_PrettyPetalFlowerShop_MapScripts
	.4byte 0x0
	.2byte MUS_MACHI_S2
	.2byte 117
	.byte MAPSEC_ROUTE_104
	.byte 0
	.byte WEATHER_NONE
	.byte MAP_TYPE_INDOOR
	.2byte 0
	map_header_flags allow_bike=0, allow_escape_rope=0, allow_run=0, show_map_name=0
	.byte MAP_BATTLE_SCENE_NORMAL

