	.align 2
gFallarborBattleTentTrainers:: @ 85DF084
@ 0
	.4byte FACILITY_CLASS_AROMA_LADY
	.string "AMBER$", 8
@ pre-battle speech
	.2byte EC_WORD_I
	.2byte EC_WORD_HAVE
	.2byte EC_WORD_TO
	.2byte EC_WORD_DIET
	.2byte EC_WORD_EVERY
	.2byte EC_WORD_DAY
@ win speech
	.2byte EC_WORD_A
	.2byte EC_MOVE(NIGHTMARE)
	.2byte EC_WORD_OF
	.2byte EC_WORD_SWEETS
	.2byte EC_WORD_SHOCKED
	.2byte EC_WORD_ME
@ loss speech
	.2byte EC_WORD_IF
	.2byte EC_WORD_YOU
	.2byte EC_WORD_GIVE_UP
	.2byte EC_WORD_YOU
	.2byte EC_WORD_WILL
	.2byte EC_WORD_LOSE
	.4byte gFallarborBattleTentTrainerMons_Amber

@ 1
	.4byte FACILITY_CLASS_RUIN_MANIAC
	.string "JAVIER$", 8
@ pre-battle speech
	.2byte EC_WORD_I
	.2byte EC_WORD_NEVER
	.2byte EC_WORD_EVER
	.2byte EC_WORD_HAVE
	.2byte EC_WORD_ENOUGH
	.2byte EC_WORD_MONEY
@ win speech
	.2byte EC_WORD_I
	.2byte EC_WORD_WON
	.2byte EC_WORD_BUT
	.2byte EC_WORD_I
	.2byte EC_WORD_NEED
	.2byte EC_WORD_MONEY
@ loss speech
	.2byte EC_WORD_I
	.2byte EC_WORD_NEED
	.2byte EC_WORD_MONEY
	.2byte EC_WORD_FOR
	.2byte EC_WORD_A
	.2byte EC_WORD_BIKE
	.4byte gFallarborBattleTentTrainerMons_Javier

@ 2
	.4byte FACILITY_CLASS_TUBER_F
	.string "NATALIE$", 8
@ pre-battle speech
	.2byte EC_WORD_THE
	.2byte EC_WORD_WAY
	.2byte EC_WORD_I
	.2byte EC_WORD_BATTLE
	.2byte EC_WORD_IS
	.2byte EC_WORD_WEIRD
@ win speech
	.2byte EC_WORD_YOU_RE
	.2byte EC_WORD_MUCH
	.2byte EC_WORD_TOO_WEAK
	.2byte EC_WORD_FOR
	.2byte EC_WORD_THIS
	.2byte EC_WORD_PLACE
@ loss speech
	.2byte EC_WORD_GIVE_ME
	.2byte EC_WORD_AN
	.2byte EC_WORD_EASY
	.2byte EC_WORD_MATCH
	.2byte EC_WORD_NEXT
	.2byte EC_WORD_TIME
	.4byte gFallarborBattleTentTrainerMons_Natalie

@ 3
	.4byte FACILITY_CLASS_TUBER_M
	.string "TREVE$", 8
@ pre-battle speech
	.2byte EC_WORD_LOOK
	.2byte EC_WORD_AT
	.2byte EC_WORD_MY
	.2byte EC_MOVE2(METRONOME)
	.2byte EC_WORD_AND
	.2byte EC_WORD_SLEEP
@ win speech
	.2byte EC_WORD_YEAH
	.2byte EC_WORD_EXCL
	.2byte EC_MOVE(HYPNOSIS)
	.2byte EC_WORD_IS
	.2byte EC_WORD_TOTALLY
	.2byte EC_WORD_GREAT
@ loss speech
	.2byte EC_WORD_MY
	.2byte EC_MOVE(HYPNOSIS)
	.2byte EC_WORD_DIDN_T
	.2byte EC_WORD_WORK
	.2byte EC_WORD_ELLIPSIS
	.2byte -1
	.4byte gFallarborBattleTentTrainerMons_Treve

@ 4
	.4byte FACILITY_CLASS_LADY
	.string "ARIANNA$", 8
@ pre-battle speech
	.2byte EC_WORD_IF_I_WIN
	.2byte EC_WORD_GIVE_ME
	.2byte EC_WORD_POKEMON
	.2byte EC_WORD_FOR
	.2byte EC_WORD_MY
	.2byte EC_WORD_COLLECTION
@ win speech
	.2byte EC_WORD_YOUR
	.2byte EC_WORD_POKEMON
	.2byte EC_WORD_ARE
	.2byte EC_WORD_TOO_WEAK
	.2byte EC_WORD_TO
	.2byte EC_WORD_COLLECT
@ loss speech
	.2byte EC_WORD_YOUR
	.2byte EC_WORD_POKEMON
	.2byte EC_WORD_ARE
	.2byte EC_WORD_SOMETHING
	.2byte EC_WORD_ELSE
	.2byte EC_WORD_ELLIPSIS
	.4byte gFallarborBattleTentTrainerMons_Arianna

@ 5
	.4byte FACILITY_CLASS_BEAUTY
	.string "JADYN$", 8
@ pre-battle speech
	.2byte EC_WORD_MY
	.2byte EC_WORD_NAME
	.2byte EC_WORD_IS
	.2byte EC_WORD_REALLY
	.2byte EC_WORD_A
	.2byte EC_WORD_MYSTERY
@ win speech
	.2byte EC_WORD_MY
	.2byte EC_WORD_NAME
	.2byte EC_WORD_GOES
	.2byte EC_WORD_ON
	.2byte EC_WORD_A
	.2byte EC_WORD_MYSTERY
@ loss speech
	.2byte EC_WORD_MY
	.2byte EC_WORD_NAME
	.2byte EC_WORD_QUES
	.2byte EC_WORD_I_AM
	.2byte EC_WORD_YOUR
	.2byte EC_WORD_MOTHER
	.4byte gFallarborBattleTentTrainerMons_Jadyn

@ 6
	.4byte FACILITY_CLASS_RICH_BOY
	.string "GERARDO$", 8
@ pre-battle speech
	.2byte EC_WORD_I_AM
	.2byte EC_WORD_THE
	.2byte EC_WORD_BEST
	.2byte EC_WORD_HERO
	.2byte EC_WORD_EVER
	.2byte EC_WORD_EXCL
@ win speech
	.2byte EC_WORD_SEE
	.2byte EC_WORD_WHAT
	.2byte EC_WORD_I
	.2byte EC_WORD_MEAN
	.2byte EC_WORD_QUES
	.2byte -1
@ loss speech
	.2byte EC_WORD_HUH_QUES
	.2byte EC_WORD_YOU
	.2byte EC_WORD_WERE
	.2byte EC_WORD_RIGHT
	.2byte EC_WORD_QUES
	.2byte -1
	.4byte gFallarborBattleTentTrainerMons_Gerardo

@ 7
	.4byte FACILITY_CLASS_POKEMANIAC
	.string "JONN$", 8
@ pre-battle speech
	.2byte EC_WORD_THE
	.2byte EC_WORD_WORLD
	.2byte EC_MOVE2(SUPERPOWER)
	.2byte EC_MOVE2(STOMP)
	.2byte EC_WORD_CONTEST
	.2byte EC_WORD_EXCL_EXCL
@ win speech
	.2byte EC_WORD_I_AM
	.2byte EC_WORD_NO_1
	.2byte EC_WORD_EXCL_EXCL
	.2byte EC_WORD_HEAR
	.2byte EC_WORD_ME
	.2byte EC_MOVE2(ROAR)
@ loss speech
	.2byte EC_WORD_I
	.2byte EC_WORD_GIVE_UP
	.2byte EC_WORD_EXCL
	.2byte EC_WORD_YOU_RE
	.2byte EC_WORD_NO_1
	.2byte EC_WORD_EXCL
	.4byte gFallarborBattleTentTrainerMons_Jonn

@ 8
	.4byte FACILITY_CLASS_SWIMMER_M
	.string "ESTEBAN$", 8
@ pre-battle speech
	.2byte EC_WORD_YOU_RE
	.2byte EC_WORD_A
	.2byte EC_WORD_GOOD
	.2byte EC_WORD_TRAINER
	.2byte EC_WORD_QUES
	.2byte EC_WORD_UNBELIEVABLE
@ win speech
	.2byte EC_WORD_YOU_RE
	.2byte EC_WORD_SOME
	.2byte EC_WORD_PUSHOVER
	.2byte EC_WORD_OF
	.2byte EC_WORD_A
	.2byte EC_WORD_TRAINER
@ loss speech
	.2byte EC_WORD_YOU_RE
	.2byte EC_WORD_MUCH
	.2byte EC_WORD_TOO
	.2byte EC_WORD_MUCH
	.2byte EC_WORD_FOR
	.2byte EC_WORD_ME
	.4byte gFallarborBattleTentTrainerMons_Esteban

@ 9
	.4byte FACILITY_CLASS_CAMPER
	.string "JAMESON$", 8
@ pre-battle speech
	.2byte EC_WORD_MY
	.2byte EC_WORD_POKEMON
	.2byte EC_WORD_ARE
	.2byte EC_WORD_SILKY
	.2byte EC_WORD_SMOOTH
	.2byte EC_WORD_EXCL
@ win speech
	.2byte EC_WORD_MY
	.2byte EC_WORD_SILKY
	.2byte EC_WORD_SMOOTH
	.2byte EC_WORD_POKEMON
	.2byte EC_WORD_RULE
	.2byte EC_WORD_EXCL
@ loss speech
	.2byte EC_WORD_MY
	.2byte EC_WORD_POKEMON
	.2byte EC_MOVE2(STRUGGLE)
	.2byte EC_WORD_IN
	.2byte EC_WORD_YOUR
	.2byte EC_WORD_STICKY_HOLD
	.4byte gFallarborBattleTentTrainerMons_Jameson

@ 10
	.4byte FACILITY_CLASS_BUG_MANIAC
	.string "ALANZO$", 8
@ pre-battle speech
	.2byte EC_MOVE2(FORESIGHT)
	.2byte EC_WORD_IS
	.2byte EC_WORD_A
	.2byte EC_WORD_POWER
	.2byte EC_WORD_I
	.2byte EC_WORD_HAVE
@ win speech
	.2byte EC_WORD_YOU_RE
	.2byte EC_WORD_OBLIVIOUS
	.2byte EC_WORD_ABOUT
	.2byte EC_MOVE2(FORESIGHT)
	.2byte EC_WORD_EXCL
	.2byte -1
@ loss speech
	.2byte EC_WORD_MY
	.2byte EC_MOVE2(FORESIGHT)
	.2byte EC_WORD_IS
	.2byte EC_WORD_ALWAYS
	.2byte EC_WORD_RIGHT
	.2byte EC_WORD_EXCL
	.4byte gFallarborBattleTentTrainerMons_Alanzo

@ 11
	.4byte FACILITY_CLASS_GENTLEMAN
	.string "HOWARD$", 8
@ pre-battle speech
	.2byte EC_WORD_YOUR
	.2byte EC_WORD_POKEMON
	.2byte EC_WORD_CAN_T
	.2byte EC_WORD_BEAT
	.2byte EC_WORD_ME
	.2byte -1
@ win speech
	.2byte EC_WORD_YOU
	.2byte EC_WORD_COULDN_T
	.2byte EC_WORD_WIN
	.2byte EC_WORD_COULD
	.2byte EC_WORD_YOU
	.2byte EC_WORD_QUES
@ loss speech
	.2byte EC_WORD_YOU
	.2byte EC_WORD_WOULD
	.2byte EC_WORD_GO
	.2byte EC_WORD_ALL
	.2byte EC_WORD_OUT
	.2byte EC_WORD_ELLIPSIS
	.4byte gFallarborBattleTentTrainerMons_Howard

@ 12
	.4byte FACILITY_CLASS_GUITARIST
	.string "CONRAD$", 8
@ pre-battle speech
	.2byte EC_WORD_YOUR
	.2byte EC_WORD_POKEMON
	.2byte EC_WORD_ARE
	.2byte EC_WORD_PRETTY
	.2byte EC_WORD_WILD
	.2byte EC_WORD_EXCL
@ win speech
	.2byte EC_WORD_WHOAH
	.2byte EC_WORD_EXCL_EXCL
	.2byte -1
	.2byte EC_WORD_LET_S
	.2byte EC_WORD_DANCE
	.2byte EC_WORD_EXCL
@ loss speech
	.2byte EC_WORD_MY
	.2byte EC_WORD_MUSIC
	.2byte EC_WORD_WILL
	.2byte EC_WORD_PLAY
	.2byte EC_WORD_ON
	.2byte EC_WORD_ELLIPSIS
	.4byte gFallarborBattleTentTrainerMons_Conrad

@ 13
	.4byte FACILITY_CLASS_SCHOOL_KID_F
	.string "MAKENNA$", 8
@ pre-battle speech
	.2byte EC_WORD_SHOW
	.2byte EC_WORD_ME
	.2byte EC_WORD_THAT
	.2byte EC_WORD_YOU
	.2byte EC_WORD_MEAN
	.2byte EC_WORD_IT
@ win speech
	.2byte EC_WORD_THAT_S
	.2byte EC_WORD_WHY
	.2byte EC_WORD_I
	.2byte EC_WORD_STUDY
	.2byte EC_WORD_EVERY
	.2byte EC_WORD_DAY
@ loss speech
	.2byte EC_WORD_AWW
	.2byte EC_WORD_I
	.2byte EC_WORD_STUDY
	.2byte EC_WORD_EVERY
	.2byte EC_WORD_DAY
	.2byte EC_WORD_TOO
	.4byte gFallarborBattleTentTrainerMons_Makenna

@ 14
	.4byte FACILITY_CLASS_COOLTRAINER_M
	.string "BRAYAN$", 8
@ pre-battle speech
	.2byte EC_WORD_CAN
	.2byte EC_WORD_YOU
	.2byte EC_WORD_SEE
	.2byte EC_WORD_MY
	.2byte EC_WORD_POWER
	.2byte EC_WORD_QUES
@ win speech
	.2byte EC_WORD_HOW
	.2byte EC_WORD_BORING
	.2byte EC_WORD_ELLIPSIS
	.2byte EC_WORD_THIS
	.2byte EC_WORD_IS
	.2byte EC_WORD_GOOD_BYE
@ loss speech
	.2byte EC_WORD_AM
	.2byte EC_WORD_I
	.2byte EC_WORD_THE
	.2byte EC_WORD_WEAK
	.2byte EC_WORD_TRAINER
	.2byte EC_WORD_QUES
	.4byte gFallarborBattleTentTrainerMons_Brayan

@ 15
	.4byte FACILITY_CLASS_COOLTRAINER_F
	.string "MARIANA$", 8
@ pre-battle speech
	.2byte EC_WORD_A
	.2byte EC_WORD_LIE
	.2byte EC_WORD_CAN
	.2byte EC_WORD_BE
	.2byte EC_WORD_KIND
	.2byte EC_WORD_ELLIPSIS
@ win speech
	.2byte EC_WORD_THIS
	.2byte EC_WORD_IS
	.2byte EC_WORD_LIKE
	.2byte EC_WORD_THE
	.2byte EC_WORD_SUNDAY
	.2byte EC_WORD_COMICS
@ loss speech
	.2byte EC_WORD_THIS
	.2byte EC_WORD_IS
	.2byte EC_WORD_LIKE
	.2byte EC_WORD_FROM
	.2byte EC_WORD_A
	.2byte EC_WORD_MOVIE
	.4byte gFallarborBattleTentTrainerMons_Mariana

@ 16
	.4byte FACILITY_CLASS_POKEFAN_M
	.string "SHELDON$", 8
@ pre-battle speech
	.2byte EC_WORD_A
	.2byte EC_WORD_POKEMON
	.2byte EC_WORD_TEACHER
	.2byte EC_WORD_GETS
	.2byte EC_WORD_NO
	.2byte EC_MOVE2(REST)
@ win speech
	.2byte EC_WORD_MY
	.2byte EC_WORD_SMARTNESS
	.2byte EC_WORD_GETS
	.2byte EC_WORD_ME
	.2byte EC_WORD_EASY
	.2byte EC_WORD_WINS
@ loss speech
	.2byte EC_WORD_I
	.2byte EC_WORD_HAVE
	.2byte EC_WORD_TO
	.2byte EC_WORD_GO
	.2byte EC_WORD_WORK
	.2byte EC_WORD_BYE_BYE
	.4byte gFallarborBattleTentTrainerMons_Sheldon

@ 17
	.4byte FACILITY_CLASS_POKEFAN_F
	.string "GIANNA$", 8
@ pre-battle speech
	.2byte EC_WORD_AHAHA
	.2byte EC_WORD_YES
	.2byte EC_WORD_EXCL
	.2byte EC_WORD_LOVEY_DOVEY
	.2byte EC_WORD_POKEMON
	.2byte EC_WORD_WORLD
@ win speech
	.2byte EC_WORD_MY
	.2byte EC_WORD_SHINE
	.2byte EC_WORD_IS
	.2byte EC_WORD_MAKING
	.2byte EC_WORD_THINGS
	.2byte EC_WORD_BETTER
@ loss speech
	.2byte EC_WORD_DO
	.2byte EC_WORD_YOU
	.2byte EC_WORD_DISLIKE
	.2byte EC_WORD_POKEMON
	.2byte EC_WORD_QUES
	.2byte -1
	.4byte gFallarborBattleTentTrainerMons_Gianna

@ 18
	.4byte FACILITY_CLASS_EXPERT_M
	.string "YAHIR$", 8
@ pre-battle speech
	.2byte EC_WORD_YOU
	.2byte EC_WORD_ELLIPSIS_ELLIPSIS_ELLIPSIS
	.2byte EC_WORD_ELLIPSIS_ELLIPSIS_ELLIPSIS
	.2byte EC_WORD_ELLIPSIS_ELLIPSIS_ELLIPSIS
	.2byte EC_WORD_COME_ON
	.2byte EC_WORD_EXCL
@ win speech
	.2byte EC_WORD_YOU
	.2byte EC_WORD_NEED
	.2byte EC_WORD_TO
	.2byte EC_WORD_TRAIN
	.2byte EC_WORD_A_LOT
	.2byte EC_WORD_MORE
@ loss speech
	.2byte EC_WORD_NOT
	.2byte EC_WORD_ENOUGH
	.2byte EC_WORD_ELLIPSIS
	.2byte EC_WORD_JUST
	.2byte EC_WORD_NOT
	.2byte EC_WORD_ENOUGH
	.4byte gFallarborBattleTentTrainerMons_Yahir

@ 19
	.4byte FACILITY_CLASS_EXPERT_F
	.string "BRITNEY$", 8
@ pre-battle speech
	.2byte EC_WORD_IT
	.2byte EC_WORD_SEEMS
	.2byte EC_WORD_THAT
	.2byte EC_WORD_YOU_RE
	.2byte EC_WORD_QUITE
	.2byte EC_WORD_GOOD
@ win speech
	.2byte EC_WORD_YOU_RE
	.2byte EC_WORD_A
	.2byte EC_WORD_LUKEWARM
	.2byte EC_WORD_TALENT
	.2byte EC_WORD_AT
	.2byte EC_WORD_BEST
@ loss speech
	.2byte EC_WORD_YOU_RE
	.2byte EC_WORD_A
	.2byte EC_WORD_COOL
	.2byte EC_WORD_HERO
	.2byte EC_WORD_AT
	.2byte EC_WORD_THIS
	.4byte gFallarborBattleTentTrainerMons_Britney

@ 20
	.4byte FACILITY_CLASS_YOUNGSTER
	.string "HECTER$", 8
@ pre-battle speech
	.2byte EC_WORD_MY
	.2byte EC_MOVE2(HIDDEN_POWER)
	.2byte EC_WORD_IS
	.2byte EC_WORD_EXCITING
	.2byte EC_WORD_ME
	.2byte EC_WORD_EXCL
@ win speech
	.2byte EC_WORD_YEEHAW_EXCL
	.2byte EC_WORD_LET_S
	.2byte EC_WORD_HAVE
	.2byte EC_WORD_A
	.2byte EC_MOVE2(HIDDEN_POWER)
	.2byte EC_WORD_PARTY
@ loss speech
	.2byte EC_WORD_WAAAH
	.2byte EC_WORD_EXCL
	.2byte EC_WORD_DON_T
	.2byte EC_WORD_YOU
	.2byte EC_MOVE2(MIMIC)
	.2byte EC_WORD_ME
	.4byte gFallarborBattleTentTrainerMons_Hecter

@ 21
	.4byte FACILITY_CLASS_FISHERMAN
	.string "TANNOR$", 8
@ pre-battle speech
	.2byte EC_WORD_YOU
	.2byte EC_WORD_HAVE
	.2byte EC_WORD_GOT
	.2byte EC_WORD_TO
	.2byte EC_WORD_BE
	.2byte EC_WORD_JOKING
@ win speech
	.2byte EC_WORD_YOU_RE
	.2byte EC_WORD_THE
	.2byte EC_WORD_BEST
	.2byte EC_WORD_AT
	.2byte EC_WORD_BEING
	.2byte EC_WORD_FUNNY
@ loss speech
	.2byte EC_WORD_YOU
	.2byte EC_WORD_WEREN_T
	.2byte EC_WORD_BEING
	.2byte EC_WORD_FUNNY
	.2byte EC_WORD_AT
	.2byte EC_WORD_ALL
	.4byte gFallarborBattleTentTrainerMons_Tannor

@ 22
	.4byte FACILITY_CLASS_BIRD_KEEPER
	.string "BENJI$", 8
@ pre-battle speech
	.2byte EC_WORD_YOU
	.2byte EC_WORD_DON_T
	.2byte EC_WORD_THINK
	.2byte EC_WORD_VERY
	.2byte EC_WORD_FAST
	.2byte EC_WORD_HUH_QUES
@ win speech
	.2byte EC_WORD_SORRY
	.2byte EC_WORD_EXCL
	.2byte EC_WORD_I
	.2byte EC_WORD_DIDN_T
	.2byte EC_WORD_MEAN
	.2byte EC_WORD_YOU
@ loss speech
	.2byte EC_WORD_YOU
	.2byte EC_WORD_LEFT
	.2byte EC_WORD_ME
	.2byte EC_WORD_FEELING
	.2byte EC_WORD_SAD
	.2byte EC_WORD_ELLIPSIS
	.4byte gFallarborBattleTentTrainerMons_Benji

@ 23
	.4byte FACILITY_CLASS_NINJA_BOY
	.string "RORY$", 8
@ pre-battle speech
	.2byte EC_WORD_DON_T
	.2byte EC_WORD_CAUSE
	.2byte EC_WORD_AN
	.2byte EC_MOVE(UPROAR)
	.2byte EC_WORD_YOU
	.2byte EC_WORD_EXCL
@ win speech
	.2byte EC_WORD_I
	.2byte EC_WORD_DON_T
	.2byte EC_WORD_NEED
	.2byte EC_WORD_AN
	.2byte EC_MOVE(UPROAR)
	.2byte EC_WORD_EXCL
@ loss speech
	.2byte EC_WORD_I_AM
	.2byte EC_WORD_GOING
	.2byte EC_WORD_TO
	.2byte EC_WORD_CAUSE
	.2byte EC_WORD_AN
	.2byte EC_MOVE(UPROAR)
	.4byte gFallarborBattleTentTrainerMons_Rory

@ 24
	.4byte FACILITY_CLASS_PARASOL_LADY
	.string "ELEANOR$", 8
@ pre-battle speech
	.2byte EC_WORD_I
	.2byte EC_WORD_REALLY
	.2byte EC_WORD_WANT
	.2byte EC_WORD_TO
	.2byte EC_WORD_PARTY
	.2byte -1
@ win speech
	.2byte EC_WORD_A
	.2byte EC_WORD_TRENDY
	.2byte EC_WORD_PARTY
	.2byte EC_WORD_WOULD
	.2byte EC_WORD_BE
	.2byte EC_WORD_REFRESHING
@ loss speech
	.2byte EC_WORD_DON_T
	.2byte EC_WORD_YOU
	.2byte EC_WORD_LIKE
	.2byte EC_WORD_TO
	.2byte EC_WORD_PARTY
	.2byte EC_WORD_QUES
	.4byte gFallarborBattleTentTrainerMons_Eleanor

@ 25
	.4byte FACILITY_CLASS_SWIMMER_F
	.string "EVELYN$", 8
@ pre-battle speech
	.2byte EC_WORD_MY
	.2byte EC_WORD_PC
	.2byte EC_WORD_IS
	.2byte EC_WORD_MY
	.2byte EC_WORD_SECRET_BASE
	.2byte EC_WORD_EXCL
@ win speech
	.2byte EC_WORD_IT_S
	.2byte EC_WORD_ALL
	.2byte EC_WORD_SECRET
	.2byte EC_WORD_ON
	.2byte EC_WORD_MY
	.2byte EC_WORD_PC
@ loss speech
	.2byte EC_WORD_NO
	.2byte EC_WORD_EXCL
	.2byte -1
	.2byte EC_WORD_I
	.2byte EC_WORD_REJECT
	.2byte EC_WORD_THIS
	.4byte gFallarborBattleTentTrainerMons_Evelyn

@ 26
	.4byte FACILITY_CLASS_PICNICKER
	.string "ARIELLE$", 8
@ pre-battle speech
	.2byte EC_WORD_IT_S
	.2byte EC_WORD_NOT_VERY
	.2byte EC_WORD_PRETTY
	.2byte EC_WORD_BUT
	.2byte EC_WORD_I
	.2byte EC_WORD_TRY
@ win speech
	.2byte EC_WORD_WE_RE
	.2byte EC_WORD_NOT_VERY
	.2byte EC_WORD_PRETTY
	.2byte EC_WORD_BUT
	.2byte EC_WORD_WE_RE
	.2byte EC_WORD_GREAT
@ loss speech
	.2byte EC_WORD_THAT_WAS
	.2byte EC_WORD_PRETTY
	.2byte EC_WORD_MEAN
	.2byte EC_WORD_OF
	.2byte EC_WORD_YOU
	.2byte EC_WORD_EXCL
	.4byte gFallarborBattleTentTrainerMons_Arielle

@ 27
	.4byte FACILITY_CLASS_SAILOR
	.string "CONNAR$", 8
@ pre-battle speech
	.2byte EC_WORD_I_AM
	.2byte EC_WORD_NOT
	.2byte EC_WORD_STRONG
	.2byte EC_WORD_ENOUGH
	.2byte EC_WORD_FOR
	.2byte EC_WORD_THIS
@ win speech
	.2byte EC_WORD_DO
	.2byte EC_WORD_YOU
	.2byte EC_WORD_THINK
	.2byte EC_WORD_YOU_RE
	.2byte EC_WORD_OK_QUES
	.2byte -1
@ loss speech
	.2byte EC_WORD_GOOD_BYE
	.2byte EC_WORD_AND
	.2byte EC_WORD_THANK_YOU
	.2byte -1
	.2byte -1
	.2byte -1
	.4byte gFallarborBattleTentTrainerMons_Connar

@ 28
	.4byte FACILITY_CLASS_COLLECTOR
	.string "MAURICE$", 8
@ pre-battle speech
	.2byte EC_WORD_THERE
	.2byte EC_WORD_IS
	.2byte EC_WORD_NO
	.2byte EC_WORD_RADIO
	.2byte EC_WORD_OR
	.2byte EC_WORD_TELEVISION
@ win speech
	.2byte EC_WORD_BUT
	.2byte EC_WORD_THERE
	.2byte EC_WORD_IS
	.2byte EC_WORD_A_LOT
	.2byte EC_WORD_OF
	.2byte EC_WORD_POKEMON
@ loss speech
	.2byte EC_WORD_I
	.2byte EC_WORD_CAN_T
	.2byte EC_WORD_ENJOY
	.2byte EC_WORD_MYSELF
	.2byte EC_WORD_WITHOUT
	.2byte EC_WORD_MONEY
	.4byte gFallarborBattleTentTrainerMons_Maurice

@ 29
	.4byte FACILITY_CLASS_LASS
	.string "KIANNA$", 8
@ pre-battle speech
	.2byte EC_WORD_I
	.2byte EC_WORD_WANT
	.2byte EC_WORD_TO
	.2byte EC_WORD_GO
	.2byte EC_WORD_DEPT_STORE
	.2byte EC_WORD_SHOPPING
@ win speech
	.2byte EC_WORD_I
	.2byte EC_WORD_DISLIKE
	.2byte EC_WORD_SHOPPING
	.2byte EC_WORD_ALONE
	.2byte -1
	.2byte -1
@ loss speech
	.2byte EC_WORD_WANT
	.2byte EC_WORD_TO
	.2byte EC_WORD_GO
	.2byte EC_WORD_SHOPPING
	.2byte EC_WORD_TOGETHER
	.2byte EC_WORD_QUES
	.4byte gFallarborBattleTentTrainerMons_Kianna
