
MauvilleCity_House2_Text_BuyHarborMailAtSlateport:
	.string "Si tuviera una BICI, sería facilísimo\n"
	.string "ir de compras por CIUDAD PORTUAL.\p"
	.string "Podría comprar una CARTA PUERTO en\n"
	.string "la TIENDA POKéMON de CIUDAD PORTUAL.$"

MauvilleCity_House2_Text_TradeHarborMailForCoinCase:
	.string "Ah, ¿tienes una CARTA PUERTO?\n"
	.string "¿La cambiarías por un MONEDERO?$"

MauvilleCity_House2_Text_IllTradeYouCoinCase:
	.string "¡Qué buena suerte!\n"
	.string "Muy bien, te daré un MONEDERO.$"

MauvilleCity_House2_Text_UseCoinCaseAtGameCorner:
	.string "Ese MONEDERO se puede usar\n"
	.string "en el CASINO.$"

MauvilleCity_House2_Text_ThatsDisappointing:
	.string "Qué disgusto…\p"
	.string "Pues que sepas que necesitas un\n"
	.string "MONEDERO en el CASINO.$"
