
MauvilleCity_House2_Text_BuyHarborMailAtSlateport:
	.string "Avec un VELO, ce serait facile d’aller\n"
	.string "faire des courses à POIVRESSEL.\p"
	.string "Je pourrais acheter une LETTRE PORT à\n"
	.string "la BOUTIQUE POKéMON de POIVRESSEL…$"

MauvilleCity_House2_Text_TradeHarborMailForCoinCase:
	.string "Oh! Tu as une LETTRE PORT?\p"
	.string "Tu me l’échanges contre une\n"
	.string "BOITE JETONS?$"

MauvilleCity_House2_Text_IllTradeYouCoinCase:
	.string "Oh, ça me fait tellement plaisir!\n"
	.string "OK, je t’échange une BOITE JETONS!$"

MauvilleCity_House2_Text_UseCoinCaseAtGameCorner:
	.string "Cette BOITE JETONS peut être utilisée\n"
	.string "au CASINO.$"

MauvilleCity_House2_Text_ThatsDisappointing:
	.string "Oh, désolée…\p"
	.string "Mais il faut une BOITE JETONS\n"
	.string "pour jouer au CASINO.$"
