
VerdanturfTown_PokemonCenter_1F_Text_FaithInYourPokemon:
	.string "Chi non ha fiducia nei propri POKéMON,\n"
	.string "non può considerarsi un vero\l"
	.string "ALLENATORE.\p"
	.string "Solo coloro che credono nei POKéMON\n"
	.string "che mandano in campo possono \l"
	.string "sperare di uscirne vittoriosi.$"

VerdanturfTown_PokemonCenter_1F_Text_VisitForBattleTent:
	.string "Il motivo che spinge chiunque a\n"
	.string "venire a MENTANIA…\p"
	.string "è il TENDONE LOTTA. Non ci piove.\p"
	.string "O sei qui per far visita a qualcuno?$"
