
MossdeepCity_StevensHouse_Text_YouveEarnedHMDive:
	.string "PIERRE: {PLAYER}{KUN}…\p"
	.string "Comme tu vois, il n’y a pas grand\n"
	.string "chose ici, mais je m’y sens bien.\p"
	.string "Merci pour tout ce que tu as fait.\p"
	.string "Pour te prouver ma gratitude, je\n"
	.string "voudrais te donner cette CS!\p"
	.string "Elle contient PLONGEE. Tu la mérites\n"
	.string "vraiment, tu ne peux pas refuser.$"

MossdeepCity_StevensHouse_Text_ExplainDive:
	.string "PIERRE: Quand tu utiliseras SURF,\n"
	.string "tu verras des zones d’eau plus sombres.\p"
	.string "Utilise PLONGEE si tu es au-dessus des\n"
	.string "profondeurs. Tu iras au fond de la mer.\p"
	.string "Si tu veux remonter à la surface,\n"
	.string "utilise PLONGEE à nouveau.\p"
	.string "Cependant, à certains endroits, il ne\n"
	.string "sera pas possible de remonter.$"

MossdeepCity_StevensHouse_Text_UnderwateCavernBetweenMossdeepSootopolis:
	.string "PIERRE: Apparemment, il y a une caverne\n"
	.string "sous l’eau entre ALGATIA et\l"
	.string "ATALANOPOLIS.\p"
	.string "Tu sais, celle que le CAPT. POUPE\n"
	.string "a découverte avec son sous-marin.$"

MossdeepCity_StevensHouse_Text_TakeBallContainingBeldum:
	.string "{PLAYER} examine la POKé BALL.\p"
	.string "Elle contient le POKéMON\n"
	.string "TERHAL.\p"
	.string "Prendre la POKé BALL?$"

MossdeepCity_StevensHouse_Text_ObtainedBeldum:
	.string "{PLAYER} reçoit un TERHAL.$"

@ Unused
MossdeepCity_StevensHouse_Text_NoSpaceForAnotherMon:
	.string "There is no space for another POKéMON.$"

MossdeepCity_StevensHouse_Text_LeftPokeBallWhereItWas:
	.string "{PLAYER} laisse la POKé BALL à sa place.$"

MossdeepCity_StevensHouse_Text_LetterFromSteven:
	.string "C’est une lettre.\p"
	.string "… … … … … …\p"
	.string "Pour {PLAYER}{KUN}…\p"
	.string "J’ai décidé de faire un petit examen de\n"
	.string "conscience et de m’entraîner en route.\p"
	.string "Je ne prévois pas de rentrer chez moi\n"
	.string "tout de suite.\p"
	.string "J’ai un service à te demander.\p"
	.string "Je veux que tu prennes la POKé BALL\n"
	.string "qui est sur le bureau.\p"
	.string "A l’intérieur, il y a un TERHAL, mon\n"
	.string "POKéMON préféré.\p"
	.string "Je compte sur toi.\p"
	.string "Nos chemins se croiseront peut-être\n"
	.string "à nouveau.\p"
	.string "PIERRE ROCHARD$"

MossdeepCity_StevensHouse_Text_CollectionOfRareRocks:
	.string "C’est une collection de roches et de\n"
	.string "pierres rares réunies par PIERRE.$"
