BerryTree_Text_ItsSoftLoamySoil:
	.string "Un terreno soffice e fertile!$"

BerryTree_Text_WantToPlant:
	.string "Un terreno soffice e fertile!\n"
	.string "Vuoi piantare una BACCA?$"

BerryTree_Text_PlantedOneBerry:
	.string "{PLAYER} pianta una {STR_VAR_1}\n"
	.string "nel terreno soffice e fertile.$"

BerryTree_Text_BerryGrowthStage1:
	.string "Qui è stata piantata una {STR_VAR_1}.$"

BerryTree_Text_BerryGrowthStage2:
	.string "La pianta di BACCA{STR_VAR_1}\n"
	.string "ha germogliato.$"

BerryTree_Text_BerryGrowthStage3:
	.string "Questa pianta di BACCA{STR_VAR_1}\n"
	.string "è cresciuta.$"

BerryTree_Text_BerryGrowthStage4:
	.string "Questi fiori di BACCA{STR_VAR_1} si stanno\n"
	.string "aprendo {STR_VAR_2}.$"

BerryTree_Text_CareAdverbGreat:
	.string "stupendamente$"

BerryTree_Text_CareAdverbPoor:
	.string "bene$"

BerryTree_Text_CareAdverbGood:
	.string "perfettamente$"

BerryTree_Text_WantToPick:
	.string "Hai trovato {STR_VAR_2} {STR_VAR_1}!\p"
	.string "Vuoi raccogliere {STR_VAR_1}?$"

BerryTree_Text_PickedTheBerry:
	.string "{PLAYER} raccoglie {STR_VAR_2} {STR_VAR_1}.$"

BerryTree_Text_PutAwayBerry:
	.string "{PLAYER} mette tutto nella\n"
	.string "TASCA BACCHE dello ZAINO.\p"
	.string "Il terreno torna soffice e fertile.$"

BerryTree_Text_BerryPocketFull:
	.string "La TASCA BACCHE dello ZAINO è piena.\p"
	.string "Non è possibile raccogliere altre \n"
	.string "BACCHE.$"

BerryTree_Text_BerryLeftUnpicked:
	.string "{PLAYER} non raccoglie nessuna\n"
	.string "{STR_VAR_1}.$"

BerryTree_Text_WantToWater:
	.string "Vuoi annaffiare la pianta di\n"
	.string "BACCA{STR_VAR_1} con il VASO WAILMER?$"

BerryTree_Text_WateredTheBerry:
	.string "{PLAYER} annaffia la pianta.$"

BerryTree_Text_PlantIsDelighted:
	.string "La pianta assorbe tutta l’acqua.$"

BerryTree_Text_ExclamationPoint:
	.string "!$"
