
SlateportCity_OceanicMuseum_2F_Text_ThankYouForTheParts:
	.string "Sì? Se stai cercando il CAP. REMO,\n"
	.string "sono io in persona!\p"
	.string "Ah! Devono essere i pezzi che ho\n"
	.string "ordinato dal SIG. PETRI della DEVON.\p"
	.string "Perfetto! Grazie! Adesso possiamo\n"
	.string "prepararci per la spedizione.$"

SlateportCity_OceanicMuseum_2F_Text_WellTakeThoseParts:
	.string "Eheheh, aspetta!\n"
	.string "Il pacchetto è nostro!$"

SlateportCity_OceanicMuseum_2F_Text_SternWhoAreYou:
	.string "CAP. REMO: Che cosa?!\n"
	.string "Chi sono queste persone?$"

SlateportCity_OceanicMuseum_2F_Text_WereTeamAqua:
	.string "Siamo il TEAM IDRO!\p"
	.string "Il nostro CAPO vuole quei pezzi!\n"
	.string "Dammeli senza tante storie!$"

SlateportCity_OceanicMuseum_2F_Text_Grunt1Defeat:
	.string "Aaaaah!\n"
	.string "Sono stato battuto!$"

SlateportCity_OceanicMuseum_2F_Text_BossGoingToBeFurious:
	.string "Oh, che disastro… il CAPO andrà\n"
	.string "su tutte le furie…$"

SlateportCity_OceanicMuseum_2F_Text_LetMeTakeCareOfThis:
	.string "Largo, frignone!\n"
	.string "Ci penso io!$"

SlateportCity_OceanicMuseum_2F_Text_Grunt2Defeat:
	.string "Che cosa?!\n"
	.string "Ho perso anch’io!$"

SlateportCity_OceanicMuseum_2F_Text_MeddlingKid:
	.string "Se torniamo a mani vuote, ne sentiremo\n"
	.string "delle belle!\p"
	.string "Arrgh, non pensavo che i nostri piani\n"
	.string "sarebbero andati all’aria!$"

SlateportCity_OceanicMuseum_2F_Text_CameToSeeWhatsTakingSoLong:
	.string "Sono venuto a vedere perché è tanto\n"
	.string "complicato portare via alcuni pezzi,\l"
	.string "ma vedo davanti a me solo una ciurma di\l"
	.string "pappamolle!$"

SlateportCity_OceanicMuseum_2F_Text_ArchieWarning:
	.string "Noi siamo il TEAM IDRO e\n"
	.string "adoriamo il mare!\p"
	.string "E io sono IVAN, il CAPO del\n"
	.string "TEAM IDRO.\p"
	.string "Cosa ti spinge ad interferire con\n"
	.string "i nostri piani?\p"
	.string "No! Non può essere! Non sarai\n"
	.string "un membro del TEAM MAGMA?\p"
	.string "Non posso crederci. Non hai l’aspetto\n"
	.string "di uno di quelli.\p"
	.string "… … … … … …\n"
	.string "… … … … … …\p"
	.string "I POKéMON, le persone… tutta\n"
	.string "la vita dipende dal mare.\p"
	.string "Lo scopo del TEAM IDRO è\n"
	.string "l’espansione del mare.\p"
	.string "Non trovi che il nostro sia un obiettivo\n"
	.string "magnifico?\p"
	.string "Ma perché sto parlando con te?\n"
	.string "Sei ancora troppo giovane per\l"
	.string "comprendere la nostra nobile causa!\p"
	.string "Se oserai interferire con i nostri piani\n"
	.string "un’altra volta…\p"
	.string "la pagherai cara!\n"
	.string "Non dimenticarlo!$"

SlateportCity_OceanicMuseum_2F_Text_SternThankYouForSavingUs:
	.string "CAP. REMO: Come ti chiami?\n"
	.string "Ah, sì, me l’hai già detto, sei {PLAYER}{KUN}…\p"
	.string "Una situazione davvero tesa!\n"
	.string "Ti ringrazio per l’aiuto!\p"
	.string "Oh, sì, per poco dimenticavo che i pezzi\n"
	.string "dalla DEVON sono arrivati grazie a te!$"

SlateportCity_OceanicMuseum_2F_Text_SternIveGotToGo:
	.string "CAP. REMO: Oops!\n"
	.string "Non c’è tempo da perdere!\p"
	.string "Dobbiamo partire al più presto alla\n"
	.string "scoperta dei fondali marini.\p"
	.string "Mille grazie ancora, ma ora\n"
	.string "devo proprio andare!\p"
	.string "Tu puoi restare e dare un’occhiata alle\n"
	.string "nostre sale, se ti va.$"

SlateportCity_OceanicMuseum_2F_Text_RemindsMeOfAbandonedShip:
	.string "Qui ho visto un modello di nave.\p"
	.string "Assomigliava alla VECCHIA NAVE\n"
	.string "vicino a BLURUVIA…$"

SlateportCity_OceanicMuseum_2F_Text_DontRunInMuseum:
	.string "Dentro al MUSEO non si corre!$"

SlateportCity_OceanicMuseum_2F_Text_WantToRideSubmarine:
	.string "Wow, il sottomarino è splendido!\n"
	.string "Voglio farci un giro!$"

SlateportCity_OceanicMuseum_2F_Text_WaterQualitySample1:
	.string "Sull’etichetta c’è scritto:\n"
	.string "“CAMPIONE d’ACQUA 1”.\p"
	.string "Il mare è un’unica distesa, ma l’acqua\n"
	.string "differisce da regione a regione.$"

SlateportCity_OceanicMuseum_2F_Text_WaterQualitySample2:
	.string "Sull’etichetta c’è scritto:\n"
	.string "“CAMPIONE d’ACQUA 2”.\p"
	.string "Forse la salinità dell’acqua differisce\n"
	.string "da regione a regione…$"

SlateportCity_OceanicMuseum_2F_Text_PressureExperiment:
	.string "Una palla di gomma si restringe e \n"
	.string "si allarga.\p"
	.string "“Nel mare, il peso dell’acqua esercita\n"
	.string "una pressione.\p"
	.string "Nelle acque poco profonde,\n"
	.string "la pressione non è molto forte.\p"
	.string "In acque molto profonde, su di un’area\n"
	.string "piccola, si concentra una pressione di\l"
	.string "decine di migliaia di tonnellate”.$"

SlateportCity_OceanicMuseum_2F_Text_HoennModel:
	.string "“MODELLO della REGIONE di HOENN”\p"
	.string "Rappresentazione in miniatura della\n"
	.string "regione di HOENN.\p"
	.string "Dove si trova ALBANOVA?$"

SlateportCity_OceanicMuseum_2F_Text_DeepSeawaterDisplay:
	.string "Rappresentazione del flusso del mare.\p"
	.string "“In prossimità dei fondali, l’acqua\n"
	.string "scorre a causa delle differenze tra\l"
	.string "fattori come temperatura e salinità”.$"

SlateportCity_OceanicMuseum_2F_Text_SurfaceSeawaterDisplay:
	.string "Rappresentazione del flusso del mare.\p"
	.string "“In superficie, l’acqua scorre come\n"
	.string "la corrente sospinta dal vento”.$"

SlateportCity_OceanicMuseum_2F_Text_SSTidalReplica:
	.string "“TRAGHETTO M/N MAREA”\p"
	.string "“Riproduzione in scala della nave in\n"
	.string "costruzione al CANTIERE del CAP. REMO”.$"

SlateportCity_OceanicMuseum_2F_Text_SubmarineReplica:
	.string "“SOTTOMARINO EXPLORER 1”\p"
	.string "“Riproduzione del sottomarino per\n"
	.string "l’esplorazione dei fondali oceanici”.$"

SlateportCity_OceanicMuseum_2F_Text_SumbersibleReplica:
	.string "“CAPSULA SOMMERGIBILE”\p"
	.string "“Riproduzione di una capsula compatta\n"
	.string "ed automatizzata per l’esplorazione\l"
	.string "dei fondali marini”.$"

SlateportCity_OceanicMuseum_2F_Text_SSAnneReplica:
	.string "“M/N ANNA”\p"
	.string "“Riproduzione della nave da crociera\n"
	.string "che fa il giro del mondo”.$"
