
Route113_Text_AshCanBeFashionedIntoGlass:
	.string "Wow! La tecnologia moderna è qualcosa\n"
	.string "di straordinario!\p"
	.string "Guarda questa cenere vulcanica!\n"
	.string "La si può trasformare in vetro!$"

Route113_Text_FunWalkingThroughAsh:
	.string "Che bello camminare sulla cenere del\n"
	.string "vulcano posata a terra o sull’erba!\p"
	.string "Lasci le tracce ovunque passi. \n"
	.string "Fantastico!$"

Route113_Text_RouteSign111:
	.string "PERCORSO 113\n"
	.string "{RIGHT_ARROW} PERCORSO 111$"

Route113_Text_RouteSignFallarbor:
	.string "PERCORSO 113\n"
	.string "{LEFT_ARROW} BRUNIFOGLIA$"

Route113_Text_TrainerTipsRegisterKeyItems:
	.string "CONSIGLI UTILI\p"
	.string "Puoi assegnare a SELECT uno degli\n"
	.string "STRUMENTI BASE nello ZAINO.\p"
	.string "Basta premere SELECT per usare lo\n"
	.string "strumento al momento desiderato.$"

Route113_Text_GlassWorkshopSign:
	.string "VETRERIA\n"
	.string "“Cenere vulcanica? Da noi si trasforma\l"
	.string "in strumenti di vetro!”.$"
