
MossdeepCity_Mart_Text_ReviveIsFantastic:
	.string "Il REVITALIZZANTE è fantastico!\p"
	.string "Dallo ad un POKéMON esausto\n"
	.string "e ritornerà subito in sé.\p"
	.string "Ma attenzione: il REVITALIZZANTE non\n"
	.string "restituisce i PP esauriti delle mosse.$"

MossdeepCity_Mart_Text_MaxRepelLastsLongest:
	.string "Il REPELLENTE MAX tiene alla larga\n"
	.string "i POKéMON deboli.\p"
	.string "È lo spray REPELLENTE che dura\n"
	.string "più a lungo.$"

MossdeepCity_Mart_Text_NetAndDiveBallsRare:
	.string "RETE e SUB BALL sono POKé BALL\n"
	.string "rare che si fanno solo a VERDEAZZUPOLI.\p"
	.string "La RETE BALL è efficace contro\n"
	.string "i POKéMON di tipo COLEOTTERO e ACQUA.\p"
	.string "La SUB BALL funziona meglio sui POKéMON\n"
	.string "dei fondali marini.$"
