LilycoveCity_House4_MapScripts:: @ 821F5B4
	.byte 0

LilycoveCity_House4_EventScript_21F5B5:: @ 821F5B5
	msgbox LilycoveCity_House4_Text_21F5C7, MSGBOX_NPC
	end

LilycoveCity_House4_EventScript_21F5BE:: @ 821F5BE
	msgbox LilycoveCity_House4_Text_21F62B, MSGBOX_NPC
	end

LilycoveCity_House4_Text_21F5C7: @ 821F5C7
	.string "This planet's biggest mysteries are\n"
	.string "at the bottom of the sea.\p"
	.string "Somebody said that, but I don't know…$"

LilycoveCity_House4_Text_21F62B: @ 821F62B
	.string "There's a deep underwater trench\n"
	.string "between MOSSDEEP and SOOTOPOLIS.\p"
	.string "That's what someone told me, anyway.$"

