
DewfordTown_Gym_Text_GymGuideAdvice:
	.string "Hé, comment ça va, futur MAITRE\n"
	.string "{PLAYER}?\p"
	.string "BASTIEN, le CHAMPION D’ARENE\n"
	.string "de MYOKARA a des POKéMON de\l"
	.string "type COMBAT.\p"
	.string "Si tu comptes te battre contre lui avec\n"
	.string "des POKéMON de type NORMAL, tu\l"
	.string "risques la déception.\p"
	.string "Les POKéMON COMBAT infligent de\n"
	.string "sérieux dégâts aux POKéMON de type\l"
	.string "NORMAL. Sois prudent!\p"
	.string "En plus, l’ARENE est plongée dans\n"
	.string "l’obscurité la plus totale.\p"
	.string "Mais elle s’illuminera quand tu auras\n"
	.string "vaincu les DRESSEURS sur ton chemin.\p"
	.string "Bon, allez, c’est parti!$"

DewfordTown_Gym_Text_GymGuidePostVictory:
	.string "Ouah! Il y a trop de lumière, ici!\p"
	.string "Toi aussi, tu as l’air d’être une lumière!$"

DewfordTown_Gym_Text_TakaoIntro:
	.string "La puissance est ma raison d’être!\n"
	.string "Allez, bats-toi!$"

DewfordTown_Gym_Text_TakaoDefeat:
	.string "Pas assez de puissance…$"

DewfordTown_Gym_Text_TakaoPostBattle:
	.string "Ta compétence a surpassé ma force!\n"
	.string "Ta technique est impressionnante!$"

DewfordTown_Gym_Text_JocelynIntro:
	.string "Inutile de déranger BASTIEN!\n"
	.string "Je vais t’écraser moi-même!$"

DewfordTown_Gym_Text_JocelynDefeat:
	.string "Mais… Comment?\n"
	.string "Comment as-tu pu gagner si facilement?$"

DewfordTown_Gym_Text_JocelynPostBattle:
	.string "Je ne vais pas rester sur une défaite.\n"
	.string "Je vais me motiver pour l’entraînement!\p"
	.string "Un jour, je deviendrai CHAMPION\n"
	.string "D’ARENE…\p"
	.string "Non, je deviendrai MAITRE de la\n"
	.string "LIGUE POKéMON!$"

DewfordTown_Gym_Text_LauraIntro:
	.string "Comment oses-tu me provoquer?\n"
	.string "Bon, tu ne viendras pas pleurer!$"

DewfordTown_Gym_Text_LauraDefeat:
	.string "Ouiiiiiiiiiin!\n"
	.string "J’ai perdu!$"

DewfordTown_Gym_Text_LauraPostBattle:
	.string "J’ai l’habitude de me battre dans le noir\n"
	.string "pour endurcir mon cœur.\p"
	.string "Mais il fait toujours si noir que je n’ai\n"
	.string "jamais vu le visage de BASTIEN…$"

DewfordTown_Gym_Text_LilithIntro:
	.string "Ouh…\n"
	.string "Fais attention, tu vas tomber!$"

DewfordTown_Gym_Text_LilithDefeat:
	.string "Oh, toi…\n"
	.string "Je n’ai pas envie de te connaître!$"

DewfordTown_Gym_Text_LilithPostBattle:
	.string "Je te souhaite de te perdre et de\n"
	.string "te retrouver à l’entrée!$"

DewfordTown_Gym_Text_BrendenIntro:
	.string "Tu vas voir! On ne la fait pas à un vieux\n"
	.string "loup de mer comme moi!$"

DewfordTown_Gym_Text_BrendenDefeat:
	.string "Je t’assure, ce n’est pas mon genre\n"
	.string "de perdre comme ça!$"

DewfordTown_Gym_Text_BrendenPostBattle:
	.string "Je crois que tu as bien mérité de\n"
	.string "voir notre CHAMPION D’ARENE.$"

DewfordTown_Gym_Text_CristianIntro:
	.string "Si tu veux aller plus loin, tu devras\n"
	.string "d’abord me passer sur le corps!$"

DewfordTown_Gym_Text_CristianDefeat:
	.string "Grrrrr!\n"
	.string "Sans commentaire…$"

DewfordTown_Gym_Text_CristianPostBattle:
	.string "Tu as gagné!\n"
	.string "Va chercher ce BADGE!$"

DewfordTown_Gym_Text_BrawlyIntro:
	.string "Je suis BASTIEN!\n"
	.string "Le CHAMPION D’ARENE de MYOKARA!\p"
	.string "J’ai résisté aux vagues déchaînées\n"
	.string "de la région et je me suis endurci dans\l"
	.string "les cavernes obscures!\p"
	.string "Alors, comme ça, tu viens me défier?\n"
	.string "Voyons donc de quoi tu es capable!$"

DewfordTown_Gym_Text_BrawlyDefeat:
	.string "Pfffou, bon sang! Tu as fait plus de\n"
	.string "vagues que je ne l’aurais imaginé!\p"
	.string "Tu m’as submergé!\p"
	.string "Je l’admets, tu m’as vaincu.\n"
	.string "Prends ce BADGE!$"

DewfordTown_Gym_Text_ReceivedKnuckleBadge:
	.string "{PLAYER} reçoit le BADGE POING\n"
	.string "de la part de BASTIEN.$"

DewfordTown_Gym_Text_KnuckleBadgeInfoTakeThis:
	.string "Le BADGE POING oblige tous les POKéMON\n"
	.string "jusqu’au niveau 30, même ceux échangés,\l"
	.string "à obéir sans poser de question.\p"
	.string "Et tu pourras aussi utiliser la CS FLASH\n"
	.string "en dehors des combats.\p"
	.string "Si tu veux, tu peux aussi utiliser cette\n"
	.string "CAPSULE TECHNIQUE.$"

DewfordTown_Gym_Text_ExplainBulkUp:
	.string "Cette CT08 contient GONFLETTE.\p"
	.string "C’est une technique qui permet de\n"
	.string "booster l’ATTAQUE et la DEFENSE.\p"
	.string "… … … … … …$"

DewfordTown_Gym_Text_RegisteredBrawly:
	.string "Vous avez enregistré le CHAMPION\n"
	.string "D’ARENE BASTIEN dans le POKéNAV.$"

DewfordTown_Gym_Text_BrawlyPostBattle:
	.string "Je vois que tes talents ont causé un\n"
	.string "raz-de-marée d’admiration parmi les\l"
	.string "DRESSEURS, l’autre jour!$"

DewfordTown_Gym_Text_GymStatue:
	.string "ARENE POKéMON du VILLAGE MYOKARA$"

DewfordTown_Gym_Text_GymStatueCertified:
	.string "ARENE POKéMON du VILLAGE MYOKARA\p"
	.string "NOUVEAU DRESSEUR RECONNU PAR BASTIEN:\n"
	.string "{PLAYER}$"

DewfordTown_Gym_Text_BrawlyPreRematch:
	.string "BASTIEN: La vague se retire, mais elle\n"
	.string "revient toujours sur le rivage.\p"
	.string "Toi… Une telle vague de talent…\n"
	.string "Je savais que tu reviendrais!\p"
	.string "Montre-moi tes progrès!$"

DewfordTown_Gym_Text_BrawlyRematchDefeat:
	.string "Waouh!\n"
	.string "Je me suis de nouveau fait submerger!$"

DewfordTown_Gym_Text_BrawlyPostRematch:
	.string "BASTIEN: Les combats sont vastes et\n"
	.string "profonds. On n’en voit pas le fond!\l"
	.string "Exactement comme la mer de HOENN!$"

DewfordTown_Gym_Text_BrawlyRematchNeedTwoMons:
	.string "BASTIEN: La vague se replie, mais elle\n"
	.string "revient toujours sur le rivage.\p"
	.string "Une telle vague de talent comme toi…\n"
	.string "Je savais que tu reviendrais!\p"
	.string "Oh? Tu n’as qu’un POKéMON apte\n"
	.string "au combat?\p"
	.string "Je suis désolé, mais je préfère que tu\n"
	.string "reviennes avec au moins deux POKéMON.$"

